### ISSUE TITLE
Ubuntu 20.04 LTS installation fails

### ISSUE THREAD

**Issue by niekvanderven** [Chia-Network/chia-blockchain#10033]
Hi,
having issues with running the "sh install.sh" and can't figure out what is wrong, not i can find any existing issues.
Install is done with Git clone on a fresh Ubuntu install:
(venv) chia@chia-harvester02:~$ git clone https://github.com/Chia-Network/chia-blockchain.git -b latest --recurse-submodules
Cloning into 'chia-blockchain'...
remote: Enumerating objects: 73810, done.
remote: Counting objects: 100% (2267/2267), done.
remote: Compressing objects: 100% (888/888), done.
remote: Total 73810 (delta 1621), reused 1896 (delta 1379), pack-reused 71543
Receiving objects: 100% (73810/73810), 31.72 MiB | 6.72 MiB/s, done.
Resolving deltas: 100% (57622/57622), done.
Submodule 'chia-blockchain-gui' (https://github.com/Chia-Network/chia-blockchain-gui.git) registered for path 'chia-blockchain-gui'
Submodule 'mozilla-ca' (https://github.com/Chia-Network/mozilla-ca.git) registered for path 'mozilla-ca'
Cloning into '/home/chia/chia-blockchain/chia-blockchain-gui'...
remote: Enumerating objects: 41182, done.        
remote: Counting objects: 100% (3611/3611), done.        
remote: Compressing objects: 100% (1563/1563), done.        
remote: Total 41182 (delta 2321), reused 3121 (delta 1956), pack-reused 37571        
Receiving objects: 100% (41182/41182), 45.92 MiB | 16.80 MiB/s, done.
Resolving deltas: 100% (26515/26515), done.
Cloning into '/home/chia/chia-blockchain/mozilla-ca'...
remote: Enumerating objects: 80, done.        
remote: Counting objects: 100% (80/80), done.        
remote: Compressing objects: 100% (45/45), done.        
remote: Total 80 (delta 24), reused 56 (delta 12), pack-reused 0        
Submodule path 'chia-blockchain-gui': checked out '1863a31603db272746af4db2b4003280c51d302b'
Submodule path 'mozilla-ca': checked out 'b1b808ab930004fc6b4afc4b248dee0a136f3f00'
(venv) chia@chia-harvester02:~$ 
(venv) chia@chia-harvester02:~$ 
(venv) chia@chia-harvester02:~$ cd chia-
-bash: cd: chia-: No such file or directory
(venv) chia@chia-harvester02:~$ cd chia-blockchain/
(venv) chia@chia-harvester02:~/chia-blockchain$ sudo sh install.sh 
apt-get is /usr/bin/apt-get
Installing on Ubuntu 20.04 LTS.
Hit:1 http://nl.archive.ubuntu.com/ubuntu focal InRelease
Hit:2 http://nl.archive.ubuntu.com/ubuntu focal-updates InRelease
Hit:3 http://nl.archive.ubuntu.com/ubuntu focal-backports InRelease
Hit:4 http://nl.archive.ubuntu.com/ubuntu focal-security InRelease
Reading package lists... Done                            
Reading package lists... Done
Building dependency tree       
Reading state information... Done
python3-distutils is already the newest version (3.8.10-0ubuntu1~20.04).
python3.8-venv is already the newest version (3.8.10-0ubuntu1~20.04.2).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Python version is 3.9
Collecting pip
  Downloading pip-22.0-py3-none-any.whl (2.1 MB)
     |████████████████████████████████| 2.1 MB 12.7 MB/s 
Installing collected packages: pip
  Attempting uninstall: pip
    Found existing installation: pip 20.0.2
    Uninstalling pip-20.0.2:
      Successfully uninstalled pip-20.0.2
Successfully installed pip-22.0
Collecting wheel
  Downloading wheel-0.37.1-py2.py3-none-any.whl (35 kB)
Installing collected packages: wheel
Successfully installed wheel-0.37.1
Looking in indexes: https://pypi.org/simple, https://pypi.chia.net/simple/
ERROR: Exception:
Traceback (most recent call last):
  File "/home/chia/chia-blockchain/venv/lib/python3.9/site-packages/pip/_internal/cli/base_command.py", line 165, in exc_logging_wrapper
    status = run_func(*args)
  File "/home/chia/chia-blockchain/venv/lib/python3.9/site-packages/pip/_internal/cli/req_command.py", line 205, in wrapper
    return func(self, options, args)
  File "/home/chia/chia-blockchain/venv/lib/python3.9/site-packages/pip/_internal/commands/install.py", line 339, in run
    requirement_set = resolver.resolve(
  File "/home/chia/chia-blockchain/venv/lib/python3.9/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 94, in resolve
    result = self._result = resolver.resolve(
  File "/home/chia/chia-blockchain/venv/lib/python3.9/site-packages/pip/_vendor/resolvelib/resolvers.py", line 481, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
  File "/home/chia/chia-blockchain/venv/lib/python3.9/site-packages/pip/_vendor/resolvelib/resolvers.py", line 348, in resolve
    self._add_to_criteria(self.state.criteria, r, parent=None)
  File "/home/chia/chia-blockchain/venv/lib/python3.9/site-packages/pip/_vendor/resolvelib/resolvers.py", line 172, in _add_to_criteria
    if not criterion.candidates:
  File "/home/chia/chia-blockchain/venv/lib/python3.9/site-packages/pip/_vendor/resolvelib/structs.py", line 151, in __bool__
    return bool(self._sequence)
  File "/home/chia/chia-blockchain/venv/lib/python3.9/site-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 155, in __bool__
    return any(self)
  File "/home/chia/chia-blockchain/venv/lib/python3.9/site-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 143, in <genexpr>
    return (c for c in iterator if id(c) not in self._incompatible_ids)
  File "/home/chia/chia-blockchain/venv/lib/python3.9/site-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 44, in _iter_built
    for version, func in infos:
  File "/home/chia/chia-blockchain/venv/lib/python3.9/site-packages/pip/_internal/resolution/resolvelib/factory.py", line 294, in iter_index_candidate_infos
    result = self._finder.find_best_candidate(
  File "/home/chia/chia-blockchain/venv/lib/python3.9/site-packages/pip/_internal/index/package_finder.py", line 868, in find_best_candidate
    candidates = self.find_all_candidates(project_name)
  File "/home/chia/chia-blockchain/venv/lib/python3.9/site-packages/pip/_internal/index/package_finder.py", line 809, in find_all_candidates
    page_candidates = list(page_candidates_it)
  File "/home/chia/chia-blockchain/venv/lib/python3.9/site-packages/pip/_internal/index/sources.py", line 134, in page_candidates
    yield from self._candidates_from_page(self._link)
  File "/home/chia/chia-blockchain/venv/lib/python3.9/site-packages/pip/_internal/index/package_finder.py", line 773, in process_project_url
    page_links = list(parse_links(html_page, self._use_deprecated_html5lib))
  File "/home/chia/chia-blockchain/venv/lib/python3.9/site-packages/pip/_internal/index/collector.py", line 310, in wrapper_wrapper
    return list(fn(page, use_deprecated_html5lib))
  File "/home/chia/chia-blockchain/venv/lib/python3.9/site-packages/pip/_internal/index/collector.py", line 350, in parse_links
    parser.feed(page.content.decode(encoding))
  File "/usr/lib/python3.9/html/parser.py", line 110, in feed
    self.goahead(0)
  File "/usr/lib/python3.9/html/parser.py", line 170, in goahead
    k = self.parse_starttag(i)
  File "/usr/lib/python3.9/html/parser.py", line 344, in parse_starttag
    self.handle_starttag(tag, attrs)
  File "/home/chia/chia-blockchain/venv/lib/python3.9/site-packages/pip/_internal/index/collector.py", line 410, in handle_starttag
    self._raise_error()
  File "/home/chia/chia-blockchain/venv/lib/python3.9/site-packages/pip/_internal/index/collector.py", line 426, in _raise_error
    raise ValueError(
ValueError: HTML doctype missing or incorrect. Expected <!DOCTYPE html>.

If you believe this error to be incorrect, try passing the command line option --use-deprecated=html5lib and please leave a comment on the pip issue at https://github.com/pypa/pip/issues/10825.
(venv) chia@chia-harvester02:~/chia-blockchain$

**Comment by ShortRouter** [comment]
same, ubuntu 21.04 with python 3.9.5

**Comment by JakeHillion** [comment]
same, archlinux with python 3.9.9.

also happens if you try the pip install (manual venv, `pip install -i https://hosted.chia.net/simple/ miniupnpc==2.1 setproctitle==1.1.10`). `--use-deprecated=html` doesn't coredump for me, instead says:

```
ERROR: Could not find a version that satisfies the requirement miniupnpc==2.1 (from versions: none)
ERROR: No matching distribution found for miniupnpc==2.1
```

**Comment by Lukas1893** [comment]
same error with Ubuntu 21.10 and Python 3.9.7.

**Comment by alx741** [comment]
Related: https://github.com/pytorch/pytorch/issues/72045

**Comment by alx741** [comment]
Related: https://github.com/pypa/pip/issues/10825

**Comment by fegauthier** [comment]
Same issue here...
Workaround is replace theses lines in install.sh file

```
python -m pip install --extra-index-url https://pypi.chia.net/simple/ miniupnpc==2.2.2
python -m pip install -e . --extra-index-url https://pypi.chia.net/simple/
```

by

```
python -m pip install --use-deprecated=html5lib --extra-index-url https://pypi.chia.net/simple/ miniupnpc==2.2.2
python -m pip install --use-deprecated=html5lib -e . --extra-index-url https://pypi.chia.net/simple/
```

**Comment by A-Caccese** [comment]
Solved on _Ubuntu 20.04.1_ changing **lines 177-178** in `install.sh`:
```
python -m pip install --use-deprecated=html5lib --extra-index-url https://pypi.chia.net/simple/ miniupnpc==2.2.2
python -m pip install --use-deprecated=html5lib -e ."${EXTRAS}" --extra-index-url https://pypi.chia.net/simple/
```

**Comment by niekvanderven** [comment]
Solved for me, thanx to fegauthier!!
Workaround is replace these lines in install.sh file

python -m pip install --extra-index-url https://pypi.chia.net/simple/ miniupnpc==2.2.2
python -m pip install -e . --extra-index-url https://pypi.chia.net/simple/
by

python -m pip install --use-deprecated=html5lib --extra-index-url https://pypi.chia.net/simple/ miniupnpc==2.2.2
python -m pip install --use-deprecated=html5lib -e . --extra-index-url https://pypi.chia.net/simple/

**Comment by esaung** [comment]
Closing as issue looks resolved.
