### ISSUE TITLE
[Bug] sync from fork point failed err

### ISSUE THREAD

**Issue by kawww** [Chia-Network/chia-blockchain#10037]
### What happened?

My node broken twice this month. I deleted the db and resync. Today is Invalid again. I have logs this time.
 
(venv) root@localhost:~/chia-blockchain# chia netspace
Older Block
Block Height: 1490230
Weight:           3043696384
VDF Iterations:   5766332251359
Header Hash:      0xf733bd293e24324292202ac572159df23bc9bbeec1933e9a1b10c2c5804d8ba0

Newer Block
Block Height: 1494838
Weight:           3056054944
VDF Iterations:   5785924473560
Header Hash:      0xb1f2dd0f229237cdbd593987483b12059bff7dd652887a1b060ed301b4e51b03

(venv) root@localhost:~/chia-blockchain# chia start node -r
chia_full_node: stopped
chia_full_node: started
(venv) root@localhost:~/chia-blockchain# chia netspace
Older Block
Block Height: 0
Weight:           7
VDF Iterations:   11798946
Header Hash:      0xd780d22c7a87c9e01d98b49a0910f6701c3b95015741316b3fda042e5d7b81d2

Newer Block
Block Height: 0
Weight:           7
VDF Iterations:   11798946
Header Hash:      0xd780d22c7a87c9e01d98b49a0910f6701c3b95015741316b3fda042e5d7b81d2

Invalid

### Version

chia blockchain infrastructure (1.2.11)

### What platform are you using?

Linux

### What ui mode are you using?

CLI

### Relevant log output

```shell
2022-01-30T12:46:27.563 full_node chia.full_node.full_node: WARNING  Block validation time: 5.11 seconds, pre_validation time: 0.55 seconds, cost: 953352271, percent full: 8.667%
2022-01-30T12:47:28.253 full_node chia.full_node.full_node: WARNING  Block validation time: 2.49 seconds, pre_validation time: 0.39 seconds, cost: 915754942, percent full: 8.325%
2022-01-30T12:54:02.786 full_node chia.full_node.full_node: WARNING  Block validation time: 2.88 seconds, pre_validation time: 0.32 seconds, cost: 553418341, percent full: 5.031%
2022-01-30T12:55:50.477 full_node chia.full_node.coin_store: WARNING  It took 10.10s to apply 820 additions and 52 removals to the coin store. Make sure blockchain database is on a fast drive
2022-01-30T12:55:51.850 full_node chia.full_node.full_node: WARNING  Block validation time: 12.69 seconds, pre_validation time: 0.89 seconds, cost: 2436550754, percent full: 22.15%
2022-01-30T13:02:34.554 full_node chia.full_node.coin_store: WARNING  It took 10.99s to apply 916 additions and 51 removals to the coin store. Make sure blockchain database is on a fast drive
2022-01-30T13:02:35.621 full_node chia.full_node.full_node: WARNING  Block validation time: 12.69 seconds, pre_validation time: 0.39 seconds, cost: 2582694500, percent full: 23.479%
2022-01-30T13:04:50.645 full_node chia.full_node.full_node: WARNING  Block validation time: 6.36 seconds, pre_validation time: 0.35 seconds, cost: 2130905325, percent full: 19.372%
2022-01-30T13:35:58.420 full_node full_node_server        : ERROR    Peer has been rate limited and will be disconnected: 110.249.214.91, message: new_compact_vdf
2022-01-30T13:35:58.426 full_node full_node_server        : WARNING  Banning 110.249.214.91 for 300 seconds
2022-01-30T13:36:43.605 full_node chia.full_node.full_node: ERROR    got weight proof request for unknown peak 0cd22f39475bed1b19730afad610002467ac4271155700239a322ca04e2eadbd
2022-01-30T18:49:37.100 full_node full_node_server        : WARNING  Was not able to get peername from 75.105.233.247 - closing connection
2022-01-30T18:53:41.095 full_node full_node_server        : ERROR    Peer has been rate limited and will be disconnected: 222.187.220.130, message: new_compact_vdf
2022-01-30T18:53:41.096 full_node full_node_server        : WARNING  Banning 222.187.220.130 for 300 seconds
2022-01-30T19:06:23.207 full_node chia.full_node.full_node: ERROR    sync from fork point failed err: UNIQUE constraint failed: coin_record.coin_name
2022-01-30T19:07:00.275 full_node asyncio                 : ERROR    Task was destroyed but it is pending!
task: <Task pending name='Task-850' coro=<FullNode.sync_from_fork_point.<locals>.fetch_block_batches() running at /root/chia-blockchain/chia/full_node/full_node.py:893> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7f99a8b34fd0>()]> cb=[gather.<locals>._done_callback() at /usr/lib/python3.8/asyncio/tasks.py:769]>
2022-01-30T19:08:32.662 full_node chia.full_node.full_node: ERROR    sync from fork point failed err: UNIQUE constraint failed: coin_record.coin_name
2022-01-30T19:11:17.808 full_node chia.full_node.full_node: ERROR    sync from fork point failed err: UNIQUE constraint failed: coin_record.coin_name
2022-01-30T19:11:43.600 full_node chia.rpc.rpc_server     : WARNING  Error while handling message: Traceback (most recent call last):
  File "/root/chia-blockchain/chia/rpc/rpc_server.py", line 83, in inner
    res_object = await f(request_data)
  File "/root/chia-blockchain/chia/rpc/full_node_rpc_api.py", line 392, in get_network_space
    raise ValueError("New and old must not be the same")
ValueError: New and old must not be the same

2022-01-30T19:11:55.418 full_node chia.rpc.rpc_server     : WARNING  Error while handling message: Traceback (most recent call last):
  File "/root/chia-blockchain/chia/rpc/rpc_server.py", line 83, in inner
    res_object = await f(request_data)
  File "/root/chia-blockchain/chia/rpc/full_node_rpc_api.py", line 392, in get_network_space
    raise ValueError("New and old must not be the same")
ValueError: New and old must not be the same
```

**Comment by mariano54** [comment]
Sorry, this is the DB corruption that was recently fixed in main. You can use the "unstable" release of main or wait for the 1.3 release which fixes this issue. You will unfortunately have to delete the DB and resync.

**Comment by kawww** [comment]
Good, thanks. I found if I don't reboot ubuntu, the chia start node -r never start again.

(venv) root@localhost:~/chia-blockchain# chia start node -r
chia_full_node: started
(venv) root@localhost:~/chia-blockchain# chia netspace
Connection error. Check if full node rpc is running at 8555
