### ISSUE TITLE
initial_target_state when creating plot in GUI[Bug] 

### ISSUE THREAD

**Issue by danieljperry** [Chia-Network/chia-blockchain#10058]
### What happened?

I attempted to create a k25 plot in Chia's GUI, using folders inside my home folder for the temp and final directories. When I clicked OK, I got an "initial_target_state" error. Note that this could be a situation where an exception is warranted (though I don't know why), but even in that case, the error message is not clear. Also note that this is on a Linux VM. I never have tried plotting from a VM before.

Here's the top half of the dialog before clicking CREATE:

![plotter](https://user-images.githubusercontent.com/69756004/151914546-e5f0c9bc-2046-44b3-ab24-cafc30a52a39.png)

And the bottom half of the dialog and error message:

![error_message](https://user-images.githubusercontent.com/69756004/151914566-c0172f5e-9086-47af-918d-4781c5a4461d.png)

### Version

1.2.12 dev 207

### What platform are you using?

Linux

### What ui mode are you using?

GUI

### Relevant log output

```shell
2022-02-01T12:40:37.875 wallet wallet_server              : INFO     Connected with full_node {'host': '136.24.71.5', 'port': 8444}
2022-02-01T12:40:39.597 wallet chia.wallet.wallet_state_manager: INFO     Puzzle at index 155 wallet ID 1 puzzle hash 235d360cc5838403dd7e1e43b88a3c413cd7bd5ab010e5317037d9c1e0ee9a68
2022-02-01T12:40:39.609 wallet chia.wallet.wallet_state_manager: INFO     Puzzle at index 155 wallet ID 1 puzzle hash a36a8fd1e37a202e5ee007326846dbd7c0c065c20492631e12f98965c92c6d69
2022-02-01T12:40:39.705 wallet chia.wallet.wallet_state_manager: INFO     Puzzle at index 155 wallet ID 2 puzzle hash f2e82cfc1e91639270763eb685babb75d2d4c974511b467ce107faae1788fc5c
2022-02-01T12:40:39.780 wallet chia.wallet.wallet_state_manager: INFO     Puzzle at index 155 wallet ID 2 puzzle hash a4d72a285bf3ae707cd965823248da480a0417de42252efe15ff962053a06927
2022-02-01T12:40:39.886 wallet chia.wallet.wallet_state_manager: INFO     Puzzle at index 155 wallet ID 3 puzzle hash 54cbe74ac3e7c40c92489f1af8edd6c1fa15d49ff2d069ba5b8793e194386b75
2022-02-01T12:40:39.956 wallet chia.wallet.wallet_state_manager: INFO     Puzzle at index 155 wallet ID 3 puzzle hash c22166fe596d4146aa99caa57b93b137c7531298a196f8f5409adaa7850102e1
2022-02-01T12:40:40.050 wallet chia.rpc.rpc_server        : WARNING  Error while handling message: Traceback (most recent call last):
  File "chia/rpc/rpc_server.py", line 215, in safe_handle
  File "chia/rpc/rpc_server.py", line 206, in ws_api
  File "chia/rpc/wallet_rpc_api.py", line 541, in create_new_wallet
KeyError: 'initial_target_state'

2022-02-01T12:40:40.253 wallet chia.wallet.wallet_state_manager: INFO     parent: 8d2069df2d7d47930da20cd7bc2f09e23feebafcb4ad6dce6af38e7940e20120 inner_puzzle_hash for parent is 93e5f23702addecc3acfb4f9357b9f6ffefcaceaba83537e9fbc176c6dcb3501
2022-02-01T12:40:40.265 wallet chia.wallet.wallet_state_manager: INFO     Received state for the coin that doesn't belong to us {'coin': {'amount': 10000000,
          'parent_coin_info': '0x8d2069df2d7d47930da20cd7bc2f09e23feebafcb4ad6dce6af38e7940e20120',
          'puzzle_hash': '0x1be6d421691a1e5f5c23790053738c9b59c9aa45fa32cf6019b3852b576dfd17'},
 'created_height': 1462190,
 'spent_height': 1462691}
2022-02-01T12:40:40.279 wallet chia.wallet.wallet_state_manager: INFO     No wallet for coin state: {'coin': {'amount': 10000000,
          'parent_coin_info': '0x8d2069df2d7d47930da20cd7bc2f09e23feebafcb4ad6dce6af38e7940e20120',
          'puzzle_hash': '0x1be6d421691a1e5f5c23790053738c9b59c9aa45fa32cf6019b3852b576dfd17'},
 'created_height': 1462190,
 'spent_height': 1462691}
2022-02-01T12:40:40.397 wallet chia.wallet.wallet_state_manager: INFO     parent: e1ebe645be490803c9bb2e7fd0b1263ce537346257a5363d5b086b318adeffc1 inner_puzzle_hash for parent is a36a8fd1e37a202e5ee007326846dbd7c0c065c20492631e12f98965c92c6d69
2022-02-01T12:40:40.649 wallet chia.wallet.wallet_state_manager: INFO     No wallet for coin state: {'coin': {'amount': 10000000,
          'parent_coin_info': '0xe1ebe645be490803c9bb2e7fd0b1263ce537346257a5363d5b086b318adeffc1',
          'puzzle_hash': '0x1be6d421691a1e5f5c23790053738c9b59c9aa45fa32cf6019b3852b576dfd17'},
 'created_height': 1462691,
 'spent_height': None}
2022-02-01T12:40:40.670 wallet wallet_server              : INFO     Connection closed: 73.189.98.92, node id: 5c5944981eeb810adf5f62d8995bb31d4d78a9f390f963b2bd786fca3550ea3e
2022-02-01T12:40:40.671 wallet chia.wallet.wallet_node    : INFO     Connected peer <chia.server.ws_connection.WSChiaConnection object at 0x7fa7fda0f070> is False
2022-02-01T12:40:40.674 wallet wallet_server              : INFO     Connected with full_node {'host': '73.189.98.92', 'port': 8444}
```

**Comment by bolshoytoster** [comment]
@danieljperry it looks like this happens when the daemon sends a json object that doesn't have the `initial_target_state` key [added in june 2021](https://github.com/Chia-Network/chia-blockchain/commit/89f7a4b3d6329493cd2b4bc5f346a819c99d3e7b).

You may have mismatched versions for your server/daemon.
Try updating the daemon.

I'll still add handling for this.

**Comment by danieljperry** [comment]
Thanks for adding the handling. If there is something an end user needs to do, that's fine. But the error message should say something to that effect.

**Comment by bolshoytoster** [comment]
@danieljperry The error message tells the user to make sure their daemon is updated, that should be good enough for the average user to understand.

**Comment by seeden** [comment]
Already fixed via https://github.com/Chia-Network/chia-blockchain-gui/commit/9f3c1764e23a3f51aed9dcd76e99b9aa8de10b1b
