### ISSUE TITLE
[Bug] Install does not work on ubuntu server

### ISSUE THREAD

**Issue by esaung** [Chia-Network/chia-blockchain#10098]
### What happened?

installing the latest 1.2.12 beta build from chia.net/downloads, here's the issue that JM ran into on a fresh install on a VM:
the install does not work on ubuntu server btw
as it just broke apt and I had to clean up some packages

(venv) jm@h370:~/chia-blockchain$ chia start farmer
Daemon not started yet
Starting daemon
(Unlock Keyring) Passphrase:
Unlocking daemon keyring
chia_harvester: started
chia_farmer: started
chia_full_node: started
chia_wallet: started
(venv) jm@h370:~/chia-blockchain$ Traceback (most recent call last):
  File "/home/jm/chia-blockchain/venv/bin/chia_full_node", line 33, in <module>
    sys.exit(load_entry_point('chia-blockchain', 'console_scripts', 'chia_full_node')())
  File "/home/jm/chia-blockchain/chia/server/start_full_node.py", line 60, in main
    return run_service(**kwargs)
  File "/home/jm/chia-blockchain/chia/server/start_service.py", line 263, in run_service
    return asyncio.run(async_run_service(*args, **kwargs))
  File "/usr/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/home/jm/chia-blockchain/chia/server/start_service.py", line 257, in async_run_service
    return await service.run()
  File "/home/jm/chia-blockchain/chia/server/start_service.py", line 177, in run
    await self.start()
  File "/home/jm/chia-blockchain/chia/server/start_service.py", line 148, in start
    await self._server.start_server(self._on_connect_callback)
  File "/home/jm/chia-blockchain/chia/server/server.py", line 268, in start_server
    await self.site.start()
  File "/home/jm/chia-blockchain/venv/lib/python3.9/site-packages/aiohttp/web_runner.py", line 121, in start
    self._server = await loop.create_server(
  File "/usr/lib/python3.9/asyncio/base_events.py", line 1494, in create_server
    raise OSError(err.errno, 'error while attempting '
OSError: [Errno 98] error while attempting to bind on address ('::', 8444, 0, 0): address already in use

(venv) jm@h370:~/chia-blockchain$ chia stop all -d
Exception ignored in: <module 'threading' from '/usr/lib/python3.9/threading.py'>
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 1448, in _shutdown
    lock.acquire()
  File "/home/jm/chia-blockchain/chia/server/start_service.py", line 199, in _accept_signal
    self.stop()
  File "/home/jm/chia-blockchain/chia/server/start_service.py", line 215, in stop
    self._server.close_all()
  File "/home/jm/chia-blockchain/chia/server/server.py", line 730, in close_all
    self.connection_close_task = asyncio.create_task(self.close_all_connections())
  File "/usr/lib/python3.9/asyncio/tasks.py", line 360, in create_task
    loop = events.get_running_loop()
RuntimeError: no running event loop
sys:1: RuntimeWarning: coroutine 'ChiaServer.close_all_connections' was never awaited
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
daemon: {'ack': True, 'command': 'exit', 'data': {'success': True}, 'destination': 'client', 'origin': 'daemon', 'request_id': '43c6d86daec9ea76e49b5990475ae16dd68f5c9666b9765c6b0a27ea51a06e93'}

### Version

1.2.12 debian/ubuntu

### What platform are you using?

Linux

### What ui mode are you using?

GUI

**Comment by esaung** [comment]
Amine can you take a look at this issue? if you have any follow up questions, please follow up with @jmhands

**Comment by jmhands** [comment]
I tried this on a clean install of Ubuntu 21 server and did not see the issue. This system previously had been testing the Chia docker and a failed install of the .deb (only for Ubuntu Desktop). Seems like the latter even after an apt fix left the packages in a bad state, and the install.sh did not fix
