### ISSUE TITLE
wont sync

### ISSUE THREAD

**Issue by chrismikefowler1** [Chia-Network/chia-blockchain#10175]
I'm running the most up to date chia program on this computer.  I have a second computer on the network that it is syncing.  it sees everything just wont sync, here is the log. what do i do?

2022-02-10T09:47:25.379 harvester chia.rpc.rpc_server     : WARNING  Cannot connect to daemon at ws://localhost:55400
2022-02-10T09:47:26.019 full_node full_node_server        : WARNING  Banning 91.218.88.40 for 10 seconds
2022-02-10T09:47:26.019 full_node full_node_server        : ERROR    Exception b'\xd7\x80\xd2,z\x87\xc9\xe0\x1d\x98\xb4\x9a\t\x10\xf6p\x1c;\x95\x01WA1k?\xda\x04.]{\x81\xd2', exception Stack: Traceback (most recent call last):
  File "chia\server\server.py", line 437, in start_client
  File "chia\server\server.py", line 335, in connection_added
  File "chia\full_node\full_node.py", line 619, in on_connect
  File "chia\full_node\full_node.py", line 585, in synced
  File "chia\consensus\blockchain.py", line 157, in get_peak
  File "chia\consensus\blockchain.py", line 674, in height_to_block_record
  File "chia\consensus\blockchain.py", line 670, in block_record
KeyError: b'\xd7\x80\xd2,z\x87\xc9\xe0\x1d\x98\xb4\x9a\t\x10\xf6p\x1c;\x95\x01WA1k?\xda\x04.]{\x81\xd2'

2022-02-10T09:47:26.160 full_node full_node_server        : WARNING  Banning 108.230.244.252 for 10 seconds
2022-02-10T09:47:26.176 full_node full_node_server        : ERROR    Exception b'\xd7\x80\xd2,z\x87\xc9\xe0\x1d\x98\xb4\x9a\t\x10\xf6p\x1c;\x95\x01WA1k?\xda\x04.]{\x81\xd2', exception Stack: Traceback (most recent call last):
  File "chia\server\server.py", line 437, in start_client
  File "chia\server\server.py", line 335, in connection_added
  File "chia\full_node\full_node.py", line 619, in on_connect
  File "chia\full_node\full_node.py", line 585, in synced
  File "chia\consensus\blockchain.py", line 157, in get_peak
  File "chia\consensus\blockchain.py", line 674, in height_to_block_record
  File "chia\consensus\blockchain.py", line 670, in block_record
KeyError: b'\xd7\x80\xd2,z\x87\xc9\xe0\x1d\x98\xb4\x9a\t\x10\xf6p\x1c;\x95\x01WA1k?\xda\x04.]{\x81\xd2'

2022-02-10T09:47:26.441 wallet chia.rpc.rpc_server        : WARNING  Cannot connect to daemon at ws://localhost:55400
2022-02-10T09:47:26.894 farmer chia.rpc.rpc_server        : WARNING  Cannot connect to daemon at ws://localhost:55400
2022-02-10T09:47:27.769 full_node full_node_server        : WARNING  Banning 211.177.167.115 for 10 seconds
2022-02-10T09:47:27.769 full_node full_node_server        : ERROR    Exception b'\xd7\x80\xd2,z\x87\xc9\xe0\x1d\x98\xb4\x9a\t\x10\xf6p\x1c;\x95\x01WA1k?\xda\x04.]{\x81\xd2', exception Stack: Traceback (most recent call last):
  File "chia\server\server.py", line 437, in start_client
  File "chia\server\server.py", line 335, in connection_added
  File "chia\full_node\full_node.py", line 619, in on_connect
  File "chia\full_node\full_node.py", line 585, in synced
  File "chia\consensus\blockchain.py", line 157, in get_peak
  File "chia\consensus\blockchain.py", line 674, in height_to_block_record
  File "chia\consensus\blockchain.py", line 670, in block_record
KeyError: b'\xd7\x80\xd2,z\x87\xc9\xe0\x1d\x98\xb4\x9a\t\x10\xf6p\x1c;\x95\x01WA1k?\xda\x04.]{\x81\xd2'

2022-02-10T09:47:30.612 full_node chia.rpc.rpc_server     : WARNING  Cannot connect to daemon at ws://localhost:55400
2022-02-10T09:47:31.503 harvester chia.rpc.rpc_server     : WARNING  Cannot connect to daemon at ws://localhost:55400
2022-02-10T09:47:32.549 wallet chia.rpc.rpc_server        : WARNING  Cannot connect to daemon at ws://localhost:55400
2022-02-10T09:47:33.002 farmer chia.rpc.rpc_server        : WARNING  Cannot connect to daemon at ws://localhost:55400
2022-02-10T09:47:36.689 full_node chia.rpc.rpc_server     : WARNING  Cannot connect to daemon at ws://localhost:55400
2022-02-10T09:47:36.908 full_node full_node_server        : WARNING  Banning 141.239.120.238 for 10 seconds
2022-02-10T09:47:36.908 full_node full_node_server        : ERROR    Exception b'\xd7\x80\xd2,z\x87\xc9\xe0\x1d\x98\xb4\x9a\t\x10\xf6p\x1c;\x95\x01WA1k?\xda\x04.]{\x81\xd2', exception Stack: Traceback (most recent call last):
  File "chia\server\server.py", line 437, in start_client
  File "chia\server\server.py", line 335, in connection_added
  File "chia\full_node\full_node.py", line 619, in on_connect
  File "chia\full_node\full_node.py", line 585, in synced
  File "chia\consensus\blockchain.py", line 157, in get_peak
  File "chia\consensus\blockchain.py", line 674, in height_to_block_record
  File "chia\consensus\blockchain.py", line 670, in block_record
KeyError: b'\xd7\x80\xd2,z\x87\xc9\xe0\x1d\x98\xb4\x9a\t\x10\xf6p\x1c;\x95\x01WA1k?\xda\x04.]{\x81\xd2'

2022-02-10T09:47:37.595 harvester chia.rpc.rpc_server     : WARNING  Cannot connect to daemon at ws://localhost:55400
2022-02-10T09:47:38.095 full_node full_node_server        : WARNING  Banning 81.175.158.117 for 10 seconds
2022-02-10T09:47:38.095 full_node full_node_server        : ERROR    Exception b'\xd7\x80\xd2,z\x87\xc9\xe0\x1d\x98\xb4\x9a\t\x10\xf6p\x1c;\x95\x01WA1k?\xda\x04.]{\x81\xd2', exception Stack: Traceback (most recent call last):
  File "chia\server\server.py", line 437, in start_client
  File "chia\server\server.py", line 335, in connection_added
  File "chia\full_node\full_node.py", line 619, in on_connect
  File "chia\full_node\full_node.py", line 585, in synced
  File "chia\consensus\blockchain.py", line 157, in get_peak
  File "chia\consensus\blockchain.py", line 674, in height_to_block_record
  File "chia\consensus\blockchain.py", line 670, in block_record
KeyError: b'\xd7\x80\xd2,z\x87\xc9\xe0\x1d\x98\xb4\x9a\t\x10\xf6p\x1c;\x95\x01WA1k?\xda\x04.]{\x81\xd2'

2022-02-10T09:47:38.642 full_node full_node_server        : WARNING  Banning 116.48.13.207 for 10 seconds
2022-02-10T09:47:38.657 full_node full_node_server        : ERROR    Exception b'\xd7\x80\xd2,z\x87\xc9\xe0\x1d\x98\xb4\x9a\t\x10\xf6p\x1c;\x95\x01WA1k?\xda\x04.]{\x81\xd2', exception Stack: Traceback (most recent call last):
  File "chia\server\server.py", line 437, in start_client
  File "chia\server\server.py", line 335, in connection_added
  File "chia\full_node\full_node.py", line 619, in on_connect
  File "chia\full_node\full_node.py", line 585, in synced
  File "chia\consensus\blockchain.py", line 157, in get_peak
  File "chia\consensus\blockchain.py", line 674, in height_to_block_record
  File "chia\consensus\blockchain.py", line 670, in block_record
KeyError: b'\xd7\x80\xd2,z\x87\xc9\xe0\x1d\x98\xb4\x9a\t\x10\xf6p\x1c;\x95\x01WA1k?\xda\x04.]{\x81\xd2'

2022-02-10T09:47:38.673 wallet chia.rpc.rpc_server        : WARNING  Cannot connect to daemon at ws://localhost:55400
2022-02-10T09:47:38.923 full_node full_node_server        : WARNING  Banning 67.184.78.210 for 10 seconds
2022-02-10T09:47:38.938 full_node full_node_server        : ERROR    Exception b'\xd7\x80\xd2,z\x87\xc9\xe0\x1d\x98\xb4\x9a\t\x10\xf6p\x1c;\x95\x01WA1k?\xda\x04.]{\x81\xd2', exception Stack: Traceback (most recent call last):
  File "chia\server\server.py", line 437, in start_client
  File "chia\server\server.py", line 335, in connection_added
  File "chia\full_node\full_node.py", line 619, in on_connect
  File "chia\full_node\full_node.py", line 585, in synced
  File "chia\consensus\blockchain.py", line 157, in get_peak
  File "chia\consensus\blockchain.py", line 674, in height_to_block_record
  File "chia\consensus\blockchain.py", line 670, in block_record
KeyError: b'\xd7\x80\xd2,z\x87\xc9\xe0\x1d\x98\xb4\x9a\t\x10\xf6p\x1c;\x95\x01WA1k?\xda\x04.]{\x81\xd2'

2022-02-10T09:47:39.110 farmer chia.rpc.rpc_server        : WARNING  Cannot connect to daemon at ws://localhost:55400
2022-02-10T09:47:39.282 full_node full_node_server        : WARNING  Banning 121.168.215.241 for 10 seconds
2022-02-10T09:47:39.282 full_node full_node_server        : ERROR    Exception b'\xd7\x80\xd2,z\x87\xc9\xe0\x1d\x98\xb4\x9a\t\x10\xf6p\x1c;\x95\x01WA1k?\xda\x04.]{\x81\xd2', exception Stack: Traceback (most recent call last):
  File "chia\server\server.py", line 437, in start_client
  File "chia\server\server.py", line 335, in connection_added
  File "chia\full_node\full_node.py", line 619, in on_connect
  File "chia\full_node\full_node.py", line 585, in synced
  File "chia\consensus\blockchain.py", line 157, in get_peak
  File "chia\consensus\blockchain.py", line 674, in height_to_block_record
  File "chia\consensus\blockchain.py", line 670, in block_record
KeyError: b'\xd7\x80\xd2,z\x87\xc9\xe0\x1d\x98\xb4\x9a\t\x10\xf6p\x1c;\x95\x01WA1k?\xda\x04.]{\x81\xd2'

2022-02-10T09:47:40.282 full_node full_node_server        : WARNING  Banning 194.39.45.195 for 10 seconds
2022-02-10T09:47:40.297 full_node full_node_server        : ERROR    Exception b'\xd7\x80\xd2,z\x87\xc9\xe0\x1d\x98\xb4\x9a\t\x10\xf6p\x1c;\x95\x01WA1k?\xda\x04.]{\x81\xd2', exception Stack: Traceback (most recent call last):
  File "chia\server\server.py", line 437, in start_client
  File "chia\server\server.py", line 335, in connection_added
  File "chia\full_node\full_node.py", line 619, in on_connect
  File "chia\full_node\full_node.py", line 585, in synced
  File "chia\consensus\blockchain.py", line 157, in get_peak
  File "chia\consensus\blockchain.py", line 674, in height_to_block_record
  File "chia\consensus\blockchain.py", line 670, in block_record
KeyError: b'\xd7\x80\xd2,z\x87\xc9\xe0\x1d\x98\xb4\x9a\t\x10\xf6p\x1c;\x95\x01WA1k?\xda\x04.]{\x81\xd2'

2022-02-10T09:47:41.266 full_node full_node_server        : WARNING  Banning 31.186.205.94 for 10 seconds
2022-02-10T09:47:41.266 full_node full_node_server        : ERROR    Exception b'\xd7\x80\xd2,z\x87\xc9\xe0\x1d\x98\xb4\x9a\t\x10\xf6p\x1c;\x95\x01WA1k?\xda\x04.]{\x81\xd2', exception Stack: Traceback (most recent call last):
  File "chia\server\server.py", line 437, in start_client
  File "chia\server\server.py", line 335, in connection_added
  File "chia\full_node\full_node.py", line 619, in on_connect
  File "chia\full_node\full_node.py", line 585, in synced
  File "chia\consensus\blockchain.py", line 157, in get_peak
  File "chia\consensus\blockchain.py", line 674, in height_to_block_record
  File "chia\consensus\blockchain.py", line 670, in block_record
KeyError: b'\xd7\x80\xd2,z\x87\xc9\xe0\x1d\x98\xb4\x9a\t\x10\xf6p\x1c;\x95\x01WA1k?\xda\x04.]{\x81\xd2'

2022-02-10T09:47:42.766 full_node chia.rpc.rpc_server     : WARNING  Cannot connect to daemon at ws://localhost:55400
2022-02-10T09:47:43.016 full_node full_node_server        : WARNING  Banning 184.57.4.6 for 10 seconds
2022-02-10T09:47:43.016 full_node full_node_server        : ERROR    Exception b'\xd7\x80\xd2,z\x87\xc9\xe0\x1d\x98\xb4\x9a\t\x10\xf6p\x1c;\x95\x01WA1k?\xda\x04.]{\x81\xd2', exception Stack: Traceback (most recent call last):
  File "chia\server\server.py", line 437, in start_client
  File "chia\server\server.py", line 335, in connection_added
  File "chia\full_node\full_node.py", line 619, in on_connect
  File "chia\full_node\full_node.py", line 585, in synced
  File "chia\consensus\blockchain.py", line 157, in get_peak
  File "chia\consensus\blockchain.py", line 674, in height_to_block_record
  File "chia\consensus\blockchain.py", line 670, in block_record
KeyError: b'\xd7\x80\xd2,z\x87\xc9\xe0\x1d\x98\xb4\x9a\t\x10\xf6p\x1c;\x95\x01WA1k?\xda\x04.]{\x81\xd2'

2022-02-10T09:47:43.687 harvester chia.rpc.rpc_server     : WARNING  Cannot connect to daemon at ws://localhost:55400
2022-02-10T09:47:44.781 wallet chia.rpc.rpc_server        : WARNING  Cannot connect to daemon at ws://localhost:55400
2022-02-10T09:47:45.140 full_node full_node_server        : WARNING  Banning 45.11.63.140 for 10 seconds
2022-02-10T09:47:45.140 full_node full_node_server        : ERROR    Exception b'\xd7\x80\xd2,z\x87\xc9\xe0\x1d\x98\xb4\x9a\t\x10\xf6p\x1c;\x95\x01WA1k?\xda\x04.]{\x81\xd2', exception Stack: Traceback (most recent call last):
  File "chia\server\server.py", line 437, in start_client
  File "chia\server\server.py", line 335, in connection_added
  File "chia\full_node\full_node.py", line 619, in on_connect
  File "chia\full_node\full_node.py", line 585, in synced
  File "chia\consensus\blockchain.py", line 157, in get_peak
  File "chia\consensus\blockchain.py", line 674, in height_to_block_record
  File "chia\consensus\blockchain.py", line 670, in block_record
KeyError: b'\xd7\x80\xd2,z\x87\xc9\xe0\x1d\x98\xb4\x9a\t\x10\xf6p\x1c;\x95\x01WA1k?\xda\x04.]{\x81\xd2'

2022-02-10T09:47:45.234 farmer chia.rpc.rpc_server        : WARNING  Cannot connect to daemon at ws://localhost:55400
2022-02-10T09:47:48.124 full_node full_node_server        : WARNING  Banning 61.49.52.92 for 10 seconds
2022-02-10T09:47:48.124 full_node full_node_server        : ERROR    Exception b'\xd7\x80\xd2,z\x87\xc9\xe0\x1d\x98\xb4\x9a\t\x10\xf6p\x1c;\x95\x01WA1k?\xda\x04.]{\x81\xd2', exception Stack: Traceback (most recent call last):
  File "chia\server\server.py", line 437, in start_client
  File "chia\server\server.py", line 335, in connection_added
  File "chia\full_node\full_node.py", line 619, in on_connect
  File "chia\full_node\full_node.py", line 585, in synced
  File "chia\consensus\blockchain.py", line 157, in get_peak
  File "chia\consensus\blockchain.py", line 674, in height_to_block_record
  File "chia\consensus\blockchain.py", line 670, in block_record
KeyError: b'\xd7\x80\xd2,z\x87\xc9\xe0\x1d\x98\xb4\x9a\t\x10\xf6p\x1c;\x95\x01WA1k?\xda\x04.]{\x81\xd2'

2022-02-10T09:47:48.514 full_node full_node_server        : WARNING  Banning 14.44.12.193 for 10 seconds
2022-02-10T09:47:48.514 full_node full_node_server        : ERROR    Exception b'\xd7\x80\xd2,z\x87\xc9\xe0\x1d\x98\xb4\x9a\t\x10\xf6p\x1c;\x95\x01WA1k?\xda\x04.]{\x81\xd2', exception Stack: Traceback (most recent call last):
  File "chia\server\server.py", line 437, in start_client
  File "chia\server\server.py", line 335, in connection_added
  File "chia\full_node\full_node.py", line 619, in on_connect
  File "chia\full_node\full_node.py", line 585, in synced
  File "chia\consensus\blockchain.py", line 157, in get_peak
  File "chia\consensus\blockchain.py", line 674, in height_to_block_record
  File "chia\consensus\blockchain.py", line 670, in block_record
KeyError: b'\xd7\x80\xd2,z\x87\xc9\xe0\x1d\x98\xb4\x9a\t\x10\xf6p\x1c;\x95\x01WA1k?\xda\x04.]{\x81\xd2'

2022-02-10T09:47:48.858 full_node chia.rpc.rpc_server     : WARNING  Cannot connect to daemon at ws://localhost:55400
2022-02-10T09:47:49.686 full_node full_node_server        : WARNING  Banning 114.230.222.79 for 10 seconds
2022-02-10T09:47:49.686 full_node full_node_server        : ERROR    Exception b'\xd7\x80\xd2,z\x87\xc9\xe0\x1d\x98\xb4\x9a\t\x10\xf6p\x1c;\x95\x01WA1k?\xda\x04.]{\x81\xd2', exception Stack: Traceback (most recent call last):
  File "chia\server\server.py", line 437, in start_client
  File "chia\server\server.py", line 335, in connection_added
  File "chia\full_node\full_node.py", line 619, in on_connect
  File "chia\full_node\full_node.py", line 585, in synced
  File "chia\consensus\blockchain.py", line 157, in get_peak
  File "chia\consensus\blockchain.py", line 674, in height_to_block_record
  File "chia\consensus\blockchain.py", line 670, in block_record
KeyError: b'\xd7\x80\xd2,z\x87\xc9\xe0\x1d\x98\xb4\x9a\t\x10\xf6p\x1c;\x95\x01WA1k?\xda\x04.]{\x81\xd2'

2022-02-10T09:47:49.780 harvester chia.rpc.rpc_server     : WARNING  Cannot connect to daemon at ws://localhost:55400
2022-02-10T09:47:50.936 wallet chia.rpc.rpc_server        : WARNING  Cannot connect to daemon at ws://localhost:55400
2022-02-10T09:47:51.342 farmer chia.rpc.rpc_server        : WARNING  Cannot connect to daemon at ws://localhost:55400
2022-02-10T09:47:54.347 full_node full_node_server        : WARNING  Banning 109.193.231.30 for 10 seconds
2022-02-10T09:47:54.347 full_node full_node_server        : ERROR    Exception b'\xd7\x80\xd2,z\x87\xc9\xe0\x1d\x98\xb4\x9a\t\x10\xf6p\x1c;\x95\x01WA1k?\xda\x04.]{\x81\xd2', exception Stack: Traceback (most recent call last):
  File "chia\server\server.py", line 437, in start_client
  File "chia\server\server.py", line 335, in connection_added
  File "chia\full_node\full_node.py", line 619, in on_connect
  File "chia\full_node\full_node.py", line 585, in synced
  File "chia\consensus\blockchain.py", line 157, in get_peak
  File "chia\consensus\blockchain.py", line 674, in height_to_block_record
  File "chia\consensus\blockchain.py", line 670, in block_record
KeyError: b'\xd7\x80\xd2,z\x87\xc9\xe0\x1d\x98\xb4\x9a\t\x10\xf6p\x1c;\x95\x01WA1k?\xda\x04.]{\x81\xd2'

2022-02-10T09:47:54.941 full_node chia.rpc.rpc_server     : WARNING  Cannot connect to daemon at ws://localhost:55400
2022-02-10T09:47:55.863 harvester chia.rpc.rpc_server     : WARNING  Cannot connect to daemon at ws://localhost:55400
2022-02-10T09:47:57.050 wallet chia.rpc.rpc_server        : WARNING  Cannot connect to daemon at ws://localhost:55400
2022-02-10T09:47:57.424 farmer chia.rpc.rpc_server        : WARNING  Cannot connect to daemon at ws://localhost:55400
2022-02-10T09:47:57.831 full_node full_node_server        : WARNING  Banning 89.28.82.3 for 10 seconds
2022-02-10T09:47:57.846 full_node full_node_server        : ERROR    Exception b'\xd7\x80\xd2,z\x87\xc9\xe0\x1d\x98\xb4\x9a\t\x10\xf6p\x1c;\x95\x01WA1k?\xda\x04.]{\x81\xd2', exception Stack: Traceback (most recent call last):
  File "chia\server\server.py", line 437, in start_client
  File "chia\server\server.py", line 335, in connection_added
  File "chia\full_node\full_node.py", line 619, in on_connect
  File "chia\full_node\full_node.py", line 585, in synced
  File "chia\consensus\blockchain.py", line 157, in get_peak
  File "chia\consensus\blockchain.py", line 674, in height_to_block_record
  File "chia\consensus\blockchain.py", line 670, in block_record
KeyError: b'\xd7\x80\xd2,z\x87\xc9\xe0\x1d\x98\xb4\x9a\t\x10\xf6p\x1c;\x95\x01WA1k?\xda\x04.]{\x81\xd2'

2022-02-10T09:48:01.018 full_node chia.rpc.rpc_server     : WARNING  Cannot connect to daemon at ws://localhost:55400
2022-02-10T09:48:01.611 full_node full_node_server        : WARNING  Banning 98.142.68.195 for 10 seconds
2022-02-10T09:48:01.611 full_node full_node_server        : ERROR    Exception b'\xd7\x80\xd2,z\x87\xc9\xe0\x1d\x98\xb4\x9a\t\x10\xf6p\x1c;\x95\x01WA1k?\xda\x04.]{\x81\xd2', exception Stack: Traceback (most recent call last):
  File "chia\server\server.py", line 437, in start_client
  File "chia\server\server.py", line 335, in connection_added
  File "chia\full_node\full_node.py", line 619, in on_connect
  File "chia\full_node\full_node.py", line 585, in synced
  File "chia\consensus\blockchain.py", line 157, in get_peak
  File "chia\consensus\blockchain.py", line 674, in height_to_block_record
  File "chia\consensus\blockchain.py", line 670, in block_record
KeyError: b'\xd7\x80\xd2,z\x87\xc9\xe0\x1d\x98\xb4\x9a\t\x10\xf6p\x1c;\x95\x01WA1k?\xda\x04.]{\x81\xd2'

**Comment by chrismikefowler1** [comment]
![image](https://user-images.githubusercontent.com/84326972/153446037-2e43af3d-4f88-494f-a08a-f09bde837914.png)

this is what my screen looks like when i close then open chia again
