### ISSUE TITLE
ImportError: libstdc++.so.6: version `GLIBCXX_3.4.26' not found

### ISSUE THREAD

**Issue by mbarkhau** [Chia-Network/chia-blockchain#102]
```
[.venv] mbarkhau@mb-spectre:~/chia-blockchain-alpha-1.4 
$ python -m scripts.create_plots -k 30 -n 1
Traceback (most recent call last):
  File "/home/mbarkhau/miniconda3/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/mbarkhau/miniconda3/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/mbarkhau/chia-blockchain-alpha-1.4/scripts/create_plots.py", line 8, in <module>
    from chiapos import DiskPlotter
ImportError: /home/mbarkhau/miniconda3/bin/../lib/libstdc++.so.6: version `GLIBCXX_3.4.26' not found (required by /home/mbarkhau/chia-blockchain-alpha-1.4/lib/chiapos/chiapos.cpython-37m-x86_64-linux-gnu.so)
```

```
$ python --version
Python 3.7.1
$ uname -a
Linux mb-spectre 5.3.0-29-generic #31-Ubuntu SMP Fri Jan 17 17:27:26 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
$ sudo apt-get install libgmp3-dev --no-install-recommends
Reading package lists... Done
Building dependency tree       
Reading state information... Done
libgmp3-dev is already the newest version (2:6.1.2+dfsg-4).
0 upgraded, 0 newly installed, 0 to remove and 19 not upgraded.
```

**Comment by hoffmang9** [comment]
I believer your running into an anaconda problem which is very similar to this one: https://github.com/AllenDowney/ThinkStats2/issues/92

**Comment by mbarkhau** [comment]
Not quite sure what did the trick, but it seems to be working now. Most probable thing that fixed it was `conda install libgcc gmp` and maybe also because I've cloned the git repo instead of using the tarball.
