### ISSUE TITLE
[Bug] Error in DB Migration

### ISSUE THREAD

**Issue by prodchia** [Chia-Network/chia-blockchain#10205]
### What happened?

I tried to upgrade to the DB V2 available with Chia 1.3.

### Version

1.3

### What platform are you using?

Windows

### What ui mode are you using?

CLI

### Relevant log output

```shell
c:\Users\USER\AppData\Local\chia-blockchain\app-1.2.12269\resources\app.asar.unpacked\daemon>chia db upgrade
opening file for reading: C:\Users\USER\.chia\mainnet\db\blockchain_v1_mainnet.sqlite
opening file for writing: C:\Users\USER\.chia\mainnet\db\blockchain_v2_mainnet.sqlite
initializing v2 version
initializing v2 block store
peak: 2c36f2014baa8a2c2596ae00b2c208dd7f1d14aac245379c4ae767847d32ffdf height: 895585
[1/5] converting full_blocks
      377.27 seconds
[2/5] converting sub_epoch_segments_v3
      9.84 seconds
[3/5] converting hint_store
Traceback (most recent call last):
  File "Lib\site-packages\chia\cmds\chia.py", line 152, in <module>
  File "Lib\site-packages\chia\cmds\chia.py", line 148, in main
  File "click\core.py", line 829, in __call__
  File "click\core.py", line 782, in main
  File "click\core.py", line 1259, in invoke
  File "click\core.py", line 1259, in invoke
  File "click\core.py", line 1066, in invoke
  File "click\core.py", line 610, in invoke
  File "click\decorators.py", line 21, in new_func
  File "chia\cmds\db.py", line 26, in db_upgrade_cmd
  File "chia\cmds\db_upgrade_func.py", line 48, in db_upgrade_func
  File "asyncio\runners.py", line 44, in run
  File "asyncio\base_events.py", line 642, in run_until_complete
  File "chia\cmds\db_upgrade_func.py", line 240, in convert_v1_to_v2
  File "aiosqlite\context.py", line 41, in __aenter__
  File "aiosqlite\core.py", line 184, in execute
  File "aiosqlite\core.py", line 129, in _execute
  File "aiosqlite\core.py", line 102, in run
sqlite3.OperationalError: no such table: hints
[20648] Failed to execute script 'chia' due to unhandled exception!
```

**Comment by esaung** [comment]
@arvidn  - can you look into this?

**Comment by arvidn** [comment]
this happens when upgrading from a version before we added support for hints. in that case the blockchain database doesn't have a `hints` table. The conversion function must tolerate a missing `hints` table. stay tuned for a PR

**Comment by arvidn** [comment]
I think we can close this issue now
