### ISSUE TITLE
[Bug] chia db upgrade gives sqlite3.OperationalError: table full_blocks already exists

### ISSUE THREAD

**Issue by jfikar** [Chia-Network/chia-blockchain#10262]
### What happened?

I'm trying convert to the v2 DB with `chia db upgrade` and I see this error: 

```
chia db upgrade
opening file for reading: /home/test/.chia/mainnet/db/blockchain_v2_mainnet.sqlite
opening file for writing: /home/test/.chia/mainnet/db/blockchain_v2_mainnet.sqlite
initializing v2 version
initializing v2 block store
Traceback (most recent call last):
  File "/home/test/chia-blockchain/venv/bin/chia", line 33, in <module>
    sys.exit(load_entry_point('chia-blockchain', 'console_scripts', 'chia')())
  File "/home/test/chia-blockchain/chia/cmds/chia.py", line 148, in main
    cli()  # pylint: disable=no-value-for-parameter
  File "/home/test/chia-blockchain/venv/lib/python3.9/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/test/chia-blockchain/venv/lib/python3.9/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/test/chia-blockchain/venv/lib/python3.9/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/test/chia-blockchain/venv/lib/python3.9/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/test/chia-blockchain/venv/lib/python3.9/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/test/chia-blockchain/venv/lib/python3.9/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/test/chia-blockchain/venv/lib/python3.9/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/test/chia-blockchain/chia/cmds/db.py", line 26, in db_upgrade_cmd
    db_upgrade_func(
  File "/home/test/chia-blockchain/chia/cmds/db_upgrade_func.py", line 49, in db_upgrade_func
    asyncio.run(convert_v1_to_v2(in_db_path, out_db_path))
  File "/usr/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/home/test/chia-blockchain/chia/cmds/db_upgrade_func.py", line 101, in convert_v1_to_v2
    await out_db.execute(
  File "/home/test/chia-blockchain/venv/lib/python3.9/site-packages/aiosqlite/core.py", line 184, in execute
    cursor = await self._execute(self._conn.execute, sql, parameters)
  File "/home/test/chia-blockchain/venv/lib/python3.9/site-packages/aiosqlite/core.py", line 129, in _execute
    return await future
  File "/home/test/chia-blockchain/venv/lib/python3.9/site-packages/aiosqlite/core.py", line 102, in run
    result = function()
sqlite3.OperationalError: table full_blocks already exists
```

### Version

1.3.0 beta recent from GitHub 

### What platform are you using?

Linux

### What ui mode are you using?

CLI

**Comment by arvidn** [comment]
it looks like this happens if you attempt to upgrade the database when your database is already in v2 format. is that right?

**Comment by arvidn** [comment]
The message:

```
opening file for reading: /home/test/.chia/mainnet/db/blockchain_v2_mainnet.sqlite
```

Suggests that your database file is already called `_v2_`, which suggests that you started a fresh install with the 1.3 beta. Did you run `chia init`? `chia init` is supposed to initialize the database to be in the v2 format. The error happens because the conversion function assumes that replacing `_v1_` with `_v2_` produces a unique name. In your case it doesn't.

So, there definitely need to be a check against opening the same output database as input database. but I would also like to understand how one can get into the state of having a database called `v2` that has the v1 format.

**Comment by arvidn** [comment]
the only way I can reproduce that error is if I:

* do a fresh install with 1.3, so the database is already v2
* delete the blockchain database file
* run `chia db upgrade`

Is that how you got here?

I'm thinking the error message should be better, but I don't think there's a fundamental problem with any of the conversion logic.

**Comment by arvidn** [comment]
https://github.com/Chia-Network/chia-blockchain/pull/10272

**Comment by jfikar** [comment]
I do a fresh install of 1.3.0, then I copy there the two v1 DB files and then run `chia db upgrade`. The v2 files are not yet created.
 
How to make 1.3.0 believe that it should run on v1 first? Maybe I have to copy `config.xml` as well?

**Comment by arvidn** [comment]
right, the `config.yml` points to which database you're currently using. That's also the database that will be converted (by default). If you want to convert a database independently of configurations and the node, you can specify `--input` and `--output` files.

The v2 database is created during `chia init`. so as far as I can tell v2 file *should* have existed, when you copied the v1 blockchain there, the node would still have been configured to use the (empty) v2 file.

Somehow the v2 database file must have been removed before you ran `chia db upgrade`.

The current command expects a work flow where you perform a fresh install followed by a sync from scratch, or an upgrade from 1.2.x -> 1.3 followed by a `chia db upgrade`. i.e. where you have an existing config file and database.

Maybe it would be useful to have an `--import` option to the `db convert` command, but it would get a bit messy having to move the existing database file aside.

**Comment by jfikar** [comment]
I see. I've just checked that the command `chia init` creates a config with v2 DB files in it. Maybe `chia db upgrade` should check the config for `database_path: db/blockchain_v2_CHALLENGE.sqlite` and emit and error like **According to the config file the DB is already expected to be V2** or something like that.

**Comment by arvidn** [comment]
yeah, the patch I linked above improves the precondition checking and will diagnose your case (and a few other)
