### ISSUE TITLE
[Bug] Chia-wallet 1.3 Beta - Wallet not syncing and showing 0 balance

### ISSUE THREAD

**Issue by andriitalkstech** [Chia-Network/chia-blockchain#10286]
### What happened?

Chia wallet never syncs and showing 0 balance.
No errors in the logs, tho

![image](https://user-images.githubusercontent.com/84045191/154564056-be553fe9-fb80-4185-85a7-e7a3c2a0de90.png)
![image](https://user-images.githubusercontent.com/84045191/154564073-36dbbe4f-0fb4-4597-8460-bc99b02a4930.png)

### Version

1.3 Beta

### What platform are you using?

Windows

### What ui mode are you using?

GUI

### Relevant log output

```shell
2022-02-17T21:20:44.061 wallet chia.wallet.wallet_node    : INFO     Fetched blocks: 1291200 - 1291231 | duration: 2.2211990356445312
2022-02-17T21:20:44.204 wallet chia.wallet.wallet_node    : INFO     Fetched blocks: 578272 - 578303 | duration: 2.2101991176605225
2022-02-17T21:20:44.341 wallet chia.wallet.wallet_node    : INFO     Fetched blocks: 880480 - 880511 | duration: 2.210200309753418
2022-02-17T21:20:44.486 wallet chia.wallet.wallet_node    : INFO     Fetched blocks: 444448 - 444479 | duration: 2.211200475692749
2022-02-17T21:20:44.628 wallet chia.wallet.wallet_node    : INFO     Fetched blocks: 441568 - 441599 | duration: 2.209197759628296
2022-02-17T21:20:45.249 wallet chia.wallet.wallet_node    : INFO     Fetched blocks: 578304 - 578311 | duration: 1.0439128875732422
2022-02-17T21:20:45.617 wallet chia.wallet.wallet_node    : INFO     new coin state received (247 / 519)
2022-02-17T21:20:45.650 wallet chia.wallet.wallet_node    : INFO     Fetched blocks: 441600 - 441606 | duration: 1.0209131240844727
2022-02-17T21:20:46.040 wallet chia.wallet.wallet_node    : INFO     new coin state received (251 / 519)
2022-02-17T21:20:46.102 wallet chia.wallet.wallet_node    : INFO     Fetched blocks: 880512 - 880525 | duration: 1.760413646697998
2022-02-17T21:20:46.495 wallet chia.wallet.wallet_node    : INFO     new coin state received (249 / 519)
2022-02-17T21:20:46.645 wallet chia.wallet.wallet_node    : INFO     Fetched blocks: 1291232 - 1291263 | duration: 2.583911657333374
2022-02-17T21:20:46.793 wallet chia.wallet.wallet_node    : INFO     Fetched blocks: 444480 - 444511 | duration: 2.306913137435913
2022-02-17T21:20:46.952 wallet chia.wallet.wallet_node    : INFO     Fetched blocks: 589504 - 589535 | duration: 2.1097824573516846
2022-02-17T21:20:48.257 wallet chia.wallet.wallet_node    : INFO     Fetched blocks: 1291264 - 1291295 | duration: 1.6107027530670166
2022-02-17T21:20:48.259 wallet chia.wallet.wallet_node    : INFO     Using cache for blocks 577952 - 577983
2022-02-17T21:20:48.259 wallet chia.wallet.wallet_node    : INFO     Using cache for blocks 577984 - 578015
2022-02-17T21:20:48.260 wallet chia.wallet.wallet_node    : INFO     Using cache for blocks 578016 - 578047
2022-02-17T21:20:48.261 wallet chia.wallet.wallet_node    : INFO     Using cache for blocks 578048 - 578079
2022-02-17T21:20:48.261 wallet chia.wallet.wallet_node    : INFO     Using cache for blocks 578080 - 578111
2022-02-17T21:20:48.262 wallet chia.wallet.wallet_node    : INFO     Using cache for blocks 578112 - 578143
2022-02-17T21:20:48.263 wallet chia.wallet.wallet_node    : INFO     Using cache for blocks 578144 - 578175
2022-02-17T21:20:48.263 wallet chia.wallet.wallet_node    : INFO     Using cache for blocks 578176 - 578207
2022-02-17T21:20:48.264 wallet chia.wallet.wallet_node    : INFO     Using cache for blocks 578208 - 578239
2022-02-17T21:20:48.265 wallet chia.wallet.wallet_node    : INFO     Using cache for blocks 578240 - 578271
2022-02-17T21:20:48.265 wallet chia.wallet.wallet_node    : INFO     Using cache for blocks 578272 - 578303
2022-02-17T21:20:48.266 wallet chia.wallet.wallet_node    : INFO     Using cache for blocks 578304 - 578311
2022-02-17T21:20:48.781 wallet chia.wallet.wallet_node    : INFO     Fetched blocks: 444512 - 444543 | duration: 1.98720383644104
2022-02-17T21:20:48.930 wallet chia.wallet.wallet_node    : INFO     Fetched blocks: 589536 - 589567 | duration: 1.9772021770477295
2022-02-17T21:20:50.322 wallet chia.wallet.wallet_node    : INFO     Fetched blocks: 1291296 - 1291327 | duration: 2.064345359802246
2022-02-17T21:20:50.466 wallet chia.wallet.wallet_node    : INFO     Fetched blocks: 444544 - 444575 | duration: 1.6833436489105225
2022-02-17T21:20:50.616 wallet chia.wallet.wallet_node    : INFO     Fetched blocks: 589568 - 589599 | duration: 1.685347557067871
2022-02-17T21:20:50.772 wallet chia.wallet.wallet_node    : INFO     Fetched blocks: 587104 - 587135 | duration: 1.2222650051116943
2022-02-17T21:20:51.770 wallet chia.wallet.wallet_node    : INFO     Fetched blocks: 587136 - 587154 | duration: 0.9963762760162354
2022-02-17T21:20:52.213 wallet chia.wallet.wallet_node    : INFO     Fetched blocks: 1291328 - 1291359 | duration: 1.890406847000122
2022-02-17T21:20:52.358 wallet chia.wallet.wallet_node    : INFO     Fetched blocks: 444576 - 444607 | duration: 1.8913755416870117
2022-02-17T21:20:52.503 wallet chia.wallet.wallet_node    : INFO     Fetched blocks: 589600 - 589631 | duration: 1.8863773345947266
2022-02-17T21:20:53.248 wallet chia.wallet.wallet_node    : INFO     Using cache for blocks 880160 - 880191
2022-02-17T21:20:53.249 wallet chia.wallet.wallet_node    : INFO     Using cache for blocks 880192 - 880223
2022-02-17T21:20:53.250 wallet chia.wallet.wallet_node    : INFO     Using cache for blocks 880224 - 880255
2022-02-17T21:20:53.250 wallet chia.wallet.wallet_node    : INFO     Using cache for blocks 880256 - 880287
2022-02-17T21:20:53.251 wallet chia.wallet.wallet_node    : INFO     Using cache for blocks 880288 - 880319
2022-02-17T21:20:53.251 wallet chia.wallet.wallet_node    : INFO     Using cache for blocks 880320 - 880351
2022-02-17T21:20:53.252 wallet chia.wallet.wallet_node    : INFO     Using cache for blocks 880352 - 880383
2022-02-17T21:20:53.253 wallet chia.wallet.wallet_node    : INFO     Using cache for blocks 880384 - 880415
2022-02-17T21:20:53.253 wallet chia.wallet.wallet_node    : INFO     Using cache for blocks 880416 - 880447
2022-02-17T21:20:53.254 wallet chia.wallet.wallet_node    : INFO     Using cache for blocks 880448 - 880479
2022-02-17T21:20:53.255 wallet chia.wallet.wallet_node    : INFO     Using cache for blocks 880480 - 880511
2022-02-17T21:20:53.255 wallet chia.wallet.wallet_node    : INFO     Using cache for blocks 880512 - 880525
2022-02-17T21:20:57.174 wallet chia.wallet.wallet_node    : INFO     Fetched blocks: 1291360 - 1291391 | duration: 4.959371089935303
2022-02-17T21:20:57.324 wallet chia.wallet.wallet_node    : INFO     Fetched blocks: 444608 - 444639 | duration: 4.964367866516113
2022-02-17T21:20:57.473 wallet chia.wallet.wallet_node    : INFO     Fetched blocks: 589632 - 589663 | duration: 4.968871116638184
```

**Comment by esaung** [comment]
which dev build of 1.3 beta? we have some more updates coming soon that will provide more improvements to syncing reliability in wallet mode.

**Comment by andriitalkstech** [comment]
> which dev build of 1.3 beta? we have some more updates coming soon that will provide more improvements to syncing reliability in wallet mode.

It's a 1.2.12143

**Comment by andriitalkstech** [comment]
@esaung I'm trying to use stay updated with the latest from dev every day, but it seems it's not getting any better for the wallet service itself

**Comment by mariano54** [comment]
From the log it looks like you are properly syncing. Did you wait for it to finish?

**Comment by mariano54** [comment]
Also try clicking View > Reload on the GUI

**Comment by andriitalkstech** [comment]
@mariano54 yes, it got synced and now I'm getting an error
![image](https://user-images.githubusercontent.com/84045191/155399730-61a22f56-10b1-4d37-8eec-7a13becdae92.png)

`2022-02-23T21:08:43.040 wallet chia.rpc.rpc_server        : WARNING  Error while handling message: Traceback (most recent call last):
  File "chia\rpc\rpc_server.py", line 215, in safe_handle
  File "chia\rpc\rpc_server.py", line 206, in ws_api
  File "chia\rpc\wallet_rpc_api.py", line 637, in get_wallet_balance
  File "chia\wallet\wallet.py", line 114, in get_unconfirmed_balance
  File "chia\wallet\wallet_state_manager.py", line 531, in get_unconfirmed_balance
  File "chia\wallet\wallet_state_manager.py", line 552, in _get_unconfirmed_balance
  File "chia\util\ints.py", line 42, in __new__
ValueError: Value -<large_int> of does not fit into uint128`

**Comment by mariano54** [comment]
Can you send me your log on keybase? I am sorgente711. Also are you using the latest 1.3 beta and did you wipe your wallet DB?

**Comment by siamsukto7720** [comment]
Hello Mariano54. I am chia farmer who has the same issue. Do we have to wipe wallet DB ( remove everything from wallet DB) before running the 1.3 beta?   Thank you so much for your advise.

**Comment by mariano54** [comment]
> Hello Mariano54. I am chia farmer who has the same issue. Do we have to wipe wallet DB ( remove everything from wallet DB) before running the 1.3 beta? Thank you so much for your advise.

No you do not. if you experience issues: rename this folder: `~/.chia/standalone_wallet`.
