### ISSUE TITLE
[Bug] 1.3 Syncing stopped

### ISSUE THREAD

**Issue by SecurID** [Chia-Network/chia-blockchain#10432]
### What happened?

Syncing stopped again even with the beta of 1.3 and the v2 database. 

### Version

1.3

### What platform are you using?

Linux

### What ui mode are you using?

GUI

### Relevant log output

```shell
2022-02-25T15:01:41.545 full_node full_node_server        : ERROR    Exception: <bytes32: 4125efe38aed2e33a6b718f423a711de8b6670162dee8469a03f4741aab7eef2>, {'host': '45.51.47.123', 'port': 8444}. Traceback (most recent call last):
  File "chia/server/server.py", line 595, in wrapped_coroutine
  File "chia/full_node/full_node_api.py", line 472, in respond_unfinished_block
  File "chia/full_node/full_node.py", line 1691, in respond_unfinished_block
  File "chia/consensus/blockchain.py", line 598, in validate_unfinished_block
  File "chia/consensus/block_body_validation.py", line 434, in validate_block_body
KeyError: <bytes32: 4125efe38aed2e33a6b718f423a711de8b6670162dee8469a03f4741aab7eef2>

2022-02-25T15:01:41.545 full_node full_node_server        : ERROR    Exception: <bytes32: 4125efe38aed2e33a6b718f423a711de8b6670162dee8469a03f4741aab7eef2> <class 'KeyError'>, closing connection {'host': '45.51.47.123', 'port': 8444}. Traceback (most recent call last):
  File "chia/server/server.py", line 605, in api_call
  File "asyncio/tasks.py", line 494, in wait_for
  File "chia/server/server.py", line 602, in wrapped_coroutine
  File "chia/server/server.py", line 595, in wrapped_coroutine
  File "chia/full_node/full_node_api.py", line 472, in respond_unfinished_block
  File "chia/full_node/full_node.py", line 1691, in respond_unfinished_block
  File "chia/consensus/blockchain.py", line 598, in validate_unfinished_block
  File "chia/consensus/block_body_validation.py", line 434, in validate_block_body
KeyError: <bytes32: 4125efe38aed2e33a6b718f423a711de8b6670162dee8469a03f4741aab7eef2>

2022-02-25T15:01:41.753 full_node full_node_server        : WARNING  Banning 45.51.47.123 for 10 seconds
2022-02-25T15:02:07.175 full_node full_node_server        : ERROR    Exception: <bytes32: 4125efe38aed2e33a6b718f423a711de8b6670162dee8469a03f4741aab7eef2>, {'host': '173.79.48.189', 'port': 8444}. Traceback (most recent call last):
  File "chia/server/server.py", line 595, in wrapped_coroutine
  File "chia/full_node/full_node_api.py", line 124, in new_peak
  File "chia/full_node/full_node.py", line 533, in new_peak
  File "chia/full_node/full_node.py", line 467, in short_sync_backtrack
  File "chia/full_node/full_node.py", line 464, in short_sync_backtrack
  File "chia/full_node/full_node.py", line 1486, in respond_block
  File "chia/consensus/blockchain.py", line 227, in receive_block
  File "chia/consensus/block_body_validation.py", line 434, in validate_block_body
KeyError: <bytes32: 4125efe38aed2e33a6b718f423a711de8b6670162dee8469a03f4741aab7eef2>

2022-02-25T15:02:07.176 full_node full_node_server        : ERROR    Exception: <bytes32: 4125efe38aed2e33a6b718f423a711de8b6670162dee8469a03f4741aab7eef2> <class 'KeyError'>, closing connection {'host': '173.79.48.189', 'port': 8444}. Traceback (most recent call last):
  File "chia/server/server.py", line 605, in api_call
  File "asyncio/tasks.py", line 455, in wait_for
  File "chia/server/server.py", line 602, in wrapped_coroutine
  File "chia/server/server.py", line 595, in wrapped_coroutine
  File "chia/full_node/full_node_api.py", line 124, in new_peak
  File "chia/full_node/full_node.py", line 533, in new_peak
  File "chia/full_node/full_node.py", line 467, in short_sync_backtrack
  File "chia/full_node/full_node.py", line 464, in short_sync_backtrack
  File "chia/full_node/full_node.py", line 1486, in respond_block
  File "chia/consensus/blockchain.py", line 227, in receive_block
  File "chia/consensus/block_body_validation.py", line 434, in validate_block_body
KeyError: <bytes32: 4125efe38aed2e33a6b718f423a711de8b6670162dee8469a03f4741aab7eef2>

2022-02-25T15:02:07.282 full_node full_node_server        : WARNING  Banning 173.79.48.189 for 10 seconds
2022-02-25T15:02:07.284 full_node full_node_server        : ERROR    Exception: Failed to fetch block 1614892 from {'host': '173.79.48.189', 'port': 8444}, timed out, {'host': '173.79.48.189', 'port': 8444}. Traceback (most recent call last):
  File "chia/server/server.py", line 595, in wrapped_coroutine
  File "chia/full_node/full_node_api.py", line 124, in new_peak
  File "chia/full_node/full_node.py", line 533, in new_peak
  File "chia/full_node/full_node.py", line 467, in short_sync_backtrack
  File "chia/full_node/full_node.py", line 452, in short_sync_backtrack
ValueError: Failed to fetch block 1614892 from {'host': '173.79.48.189', 'port': 8444}, timed out

2022-02-25T15:02:07.284 full_node full_node_server        : ERROR    Exception: Failed to fetch block 1614892 from {'host': '173.79.48.189', 'port': 8444}, timed out <class 'ValueError'>, closing connection {'host': '173.79.48.189', 'port': 8444}. Traceback (most recent call last):
  File "chia/server/server.py", line 605, in api_call
  File "asyncio/tasks.py", line 455, in wait_for
  File "chia/server/server.py", line 602, in wrapped_coroutine
  File "chia/server/server.py", line 595, in wrapped_coroutine
  File "chia/full_node/full_node_api.py", line 124, in new_peak
  File "chia/full_node/full_node.py", line 533, in new_peak
  File "chia/full_node/full_node.py", line 467, in short_sync_backtrack
  File "chia/full_node/full_node.py", line 452, in short_sync_backtrack
ValueError: Failed to fetch block 1614892 from {'host': '173.79.48.189', 'port': 8444}, timed out
```

**Comment by SecurID** [comment]
Wallet is synced

**Comment by SecurID** [comment]
![image](https://user-images.githubusercontent.com/7266850/155758003-d24ac9bb-5503-4a01-8004-617101999f63.png)

There are many fully synced nodes connected

**Comment by SecurID** [comment]
Resync isn't functioning too. 

Database malformed is the error message

**Comment by mariano54** [comment]
Any idea what this could be @arvidn?

**Comment by arvidn** [comment]
I believe that's a sign of the disk corrupting data. I would try to store the blockchain database on a different drive.

I have experienced this myself. I have a very cheap NVMe SSD, and I was running my node with the database on this drive for a two weeks, and pretty reliably, every 2-3 days the database would fail with this message; "Database malformed". Every time I had to copy a new database file into my `db` folder and restart the node again.

Once I switched the database to run off of a different disk (a spinning HDD), it's been stable.

**Comment by arvidn** [comment]
sorry, I wasn't paying attention to the key error. I'll investigate.

**Comment by arvidn** [comment]
@SecurID which version of 1.3 beta are you using specifically?

**Comment by arvidn** [comment]
I interpret the error message as it being block at height `1614892` that's failing to validate. Looking at my block a that height, there is no spend of coin `4125efe38aed2e33a6b718f423a711de8b6670162dee8469a03f4741aab7eef2`

**Comment by SecurID** [comment]
My version is: 1.2.12.dev269

But i got it working. 
Deleting the whole .chia folder and redoing a ./chia init and than resync solved the problem for now. 
Maybe a misconfiguration caused it within the folder?

**Comment by berlef80** [comment]
I have this same issue.  Stops syncing and then never can get it to catch up again.  Internet is fast.  Computer has nothing else running.  Upgrades to 1.3 beta.  Same thing happens.  Have two machines running in different places and same thing happens.  Havemoved for a faster drive, still has problem  HELP.

**Comment by SecurID** [comment]
Have you tried deleting the whole .chia folder and resync again? That helped me restore the db and it's stable since 3 days.

**Comment by berlef80** [comment]
I really was trying to avoid that because I am worried at the rate I am syncing it will take years to get the database back.  I actually just moved it to another NVMe drive and it seems to be moving now

**Comment by SecurID** [comment]
`2022-03-06T23:09:39.665 full_node asyncio                 : ERROR    Task was destroyed but it is pending!
task: <Task pending name='Task-1167013' coro=<FullNode.sync_from_fork_point.<locals>.fetch_block_batches() running at chia/full_node/full_node.py:921> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7fbe0637dca0>()]> cb=[gather.<locals>._done_callback() at asyncio/tasks.py:769]>
2022-03-06T23:09:52.463 full_node chia.consensus.blockchain: ERROR    Error while adding block 87668c0dd1692eec61d3323d92934b7055aeb9f63423d3c535eccbdbda85e724 height 1654708, rolling back: Traceback (most recent call last):
  File "chia/consensus/blockchain.py", line 258, in receive_block
  File "chia/consensus/blockchain.py", line 402, in _reconsider_peak
  File "chia/full_node/coin_store.py", line 146, in new_block
  File "chia/full_node/coin_store.py", line 468, in _add_coin_records
  File "aiosqlite/core.py", line 210, in executemany
  File "aiosqlite/core.py", line 129, in _execute
  File "aiosqlite/core.py", line 102, in run
sqlite3.DatabaseError: database disk image is malformed
 database disk image is malformed
2022-03-06T23:09:52.463 full_node chia.full_node.full_node: ERROR    sync from fork point failed err: database disk image is malformed
2022-03-06T23:10:23.369 farmer chia.farmer.farmer         : ERROR    Failed to update farmer information on the pool https://eu1.pool.space
2022-03-06T23:10:25.954 wallet wallet_server              : WARNING  Banning 91.225.224.199 for 120 seconds
2022-03-06T23:11:43.236 full_node chia.consensus.blockchain: ERROR    Error while adding block 87668c0dd1692eec61d3323d92934b7055aeb9f63423d3c535eccbdbda85e724 height 1654708, rolling back: Traceback (most recent call last):
  File "chia/consensus/blockchain.py", line 258, in receive_block
  File "chia/consensus/blockchain.py", line 402, in _reconsider_peak
  File "chia/full_node/coin_store.py", line 146, in new_block
  File "chia/full_node/coin_store.py", line 468, in _add_coin_records
  File "aiosqlite/core.py", line 210, in executemany
  File "aiosqlite/core.py", line 129, in _execute
  File "aiosqlite/core.py", line 102, in run
sqlite3.DatabaseError: database disk image is malformed
 database disk image is malformed
2022-03-06T23:11:43.236 full_node chia.full_node.full_node: ERROR    sync from fork point failed err: database disk image is malformed`

So it worked for quite a week after a resycn but now it's stuck again. Maybe it is the ssd on which the system is running?

**Comment by SecurID** [comment]
So it worked for quite a week after a resycn but now it's stuck again. Maybe it is the ssd on which the system is running?

**Comment by SecurID** [comment]
Trying now to resync on a different ssd (the plotting one) if thats the issue.

**Comment by emlowe** [comment]
Right now I don't have any other explanation why your DB would get corrupted in such a fashion on every re-resync - other than some problem with the disk

**Comment by berlef80** [comment]
Look at the size of your SSD - Is it full? that is what happened with mine. The DB was just taking up too much room. Had to get a larger SSD Now works fine.

Sent with [ProtonMail](https://protonmail.com/) Secure Email.

------- Original Message -------

**Comment by SecurID** [comment]
Reinstalled complete system
Changed SSD completely

SSD is 1TB large so that shouldn't be the problem

Still the same error. Any more ideas?

**Comment by SecurID** [comment]
```
(venv) user@system:~/chia-blockchain$ chia db validate
opening file for reading: /home/kupferschmidt/.chia/mainnet/db/blockchain_v2_mainnet.sqlite
FAILED: Database is missing version table

```
Found something. Is that helpful? And how to add the version table

**Comment by arvidn** [comment]
@SecurID `chia db validate` doesn't work on v1 databases. I suspect your database is v1

**Comment by SecurID** [comment]
But the file name says it's a v2 database. 
How to check that properly? Or how to get to a v2 db?
I reinstalled v1.3 and started syncing on a total new system so I expect it's a v2 db

**Comment by arvidn** [comment]
> I reinstalled v1.3 and started syncing on a total new system so I expect it's a v2 db

Until recently, there was an issue where the database (in a fresh install) would only be made v2 if there wasn't already an existing `.chia/mainnet/config/config.yml` file. So, if your fresh install just meant deleting the database, it would still have created a v1 database.

**Comment by SecurID** [comment]
Ok I just deleted the whole .chia folder and repulled from the repository. 
Now the chia db validate command runs correct. I try now to resync. 
Thank you :)
