### ISSUE TITLE
[Bug] Pool Invalid State throws "AttributeError: 'WalletStateManager' object has no attribute 'get_peak'"

### ISSUE THREAD

**Issue by danarbraz** [Chia-Network/chia-blockchain#10448]
### What happened?

Pool wallet showing:
```
Wallet id 10: 
Current state: INVALID_STATE. Please leave/join again after block height 1603718
```

Attempt to leave produces this output:
`{'error': "'WalletStateManager' object has no attribute 'get_peak'", 'success': False}`

With this is in debug.log:
```
2022-02-26T13:48:58.350 wallet chia.rpc.rpc_server        : WARNING  Error while handling message: Traceback (most recent call last):
  File "/home/chia/chia-blockchain/chia/rpc/rpc_server.py", line 215, in safe_handle
    response = await self.ws_api(message)
  File "/home/chia/chia-blockchain/chia/rpc/rpc_server.py", line 206, in ws_api
    return await f(data)
  File "/home/chia/chia-blockchain/chia/rpc/wallet_rpc_api.py", line 1359, in pw_self_pool
    total_fee, tx, fee_tx = await wallet.self_pool(fee)
  File "/home/chia/chia-blockchain/chia/pools/pool_wallet.py", line 754, in self_pool
    if self.wallet_state_manager.get_peak().height <= last_height + current_state.current.relative_lock_height:
AttributeError: 'WalletStateManager' object has no attribute 'get_peak'
```

I am unable to join any pool with other plotnfts. When attempting to join any other self-pooling plotnft to a pool, this appears in debug.log:
```
2022-02-26T14:01:57.866 wallet chia.rpc.rpc_server        : WARNING  Error while handling message: Traceback (most recent call last):
  File "/home/chia/chia-blockchain/chia/rpc/rpc_server.py", line 215, in safe_handle
    response = await self.ws_api(message)
  File "/home/chia/chia-blockchain/chia/rpc/rpc_server.py", line 206, in ws_api
    return await f(data)
  File "/home/chia/chia-blockchain/chia/rpc/wallet_rpc_api.py", line 666, in get_transaction
    raise ValueError(f"Transaction 0x{transaction_id.hex()} not found")
ValueError: Transaction 0xc...<edited by me> not found

```

### Version

1.2.12.dev376

### What platform are you using?

Linux

### What ui mode are you using?

CLI

**Comment by danarbraz** [comment]
I was able to rejoin a pool although the immediate messages indicated it was unsuccessful. 

Still, the pool connection that was in an invalid state remains in that state. Attempting to leave it continues to produce this error:
```
2022-02-26T13:48:58.350 wallet chia.rpc.rpc_server        : WARNING  Error while handling message: Traceback (most recent call last):
  File "/home/chia/chia-blockchain/chia/rpc/rpc_server.py", line 215, in safe_handle
    response = await self.ws_api(message)
  File "/home/chia/chia-blockchain/chia/rpc/rpc_server.py", line 206, in ws_api
    return await f(data)
  File "/home/chia/chia-blockchain/chia/rpc/wallet_rpc_api.py", line 1359, in pw_self_pool
    total_fee, tx, fee_tx = await wallet.self_pool(fee)
  File "/home/chia/chia-blockchain/chia/pools/pool_wallet.py", line 754, in self_pool
    if self.wallet_state_manager.get_peak().height <= last_height + current_state.current.relative_lock_height:
AttributeError: 'WalletStateManager' object has no attribute 'get_peak'
```

**Comment by esaung** [comment]
@danarbraz - can you try the following:

1. reboot
2. run install.sh (if you are installing from git clone)

**Comment by danarbraz** [comment]
@esaung I'd tried that a few times previously but did again today with the latest code:
```
 $ chia version
1.2.12.dev401
```
...and it seems to have fixed the above issue I reported and that wallet id (10) is gone. Note that I previously tried with last night's commits and there was no change. 

I also opened the GUI out of curiosity. It seems pretty borked on the pool screen but what's supposed to work is working. Lots of artifacts it seems though. I'll open another bug report for that.

**Comment by danarbraz** [comment]
Somehow I'm also 3xch shy in my main wallet on this instance on this system now. If I cannot to the same wallet (wallet only) with another system, the balance is correct.

**Comment by danarbraz** [comment]
Got frustrated. Deleted wallet db (AGAIN). On resync, balance is correct but I have the invalid pool state back. I'm giving up for now.

**Comment by esaung** [comment]
can you provide screenshots of the borked screens?

I understand some of the pools have a time period you have to be in before you can switch to another pool.

I imagine you're outside of that, but wanted to confirm?

could your issue be similar to: https://github.com/Chia-Network/chia-blockchain/issues/10356 ?

**Comment by mariano54** [comment]
Should be fixed now by https://github.com/Chia-Network/chia-blockchain/pull/10545
