### ISSUE TITLE
I am unable to join any pool with other plotnfts. [Bug] 

### ISSUE THREAD

**Issue by cai1111** [Chia-Network/chia-blockchain#10459]
### What happened?

I am unable to join any pool with other plotnfts. When attempting to join any other self-pooling plotnft to a pool, this appears in debug.log:
2022-02-27T20:03:11.389 wallet chia.rpc.rpc_server        : WARNING  Error while handling message: Traceback (most recent call last):
  File "chia\rpc\rpc_server.py", line 215, in safe_handle
  File "chia\rpc\rpc_server.py", line 206, in ws_api
  File "chia\rpc\wallet_rpc_api.py", line 1333, in pw_join_pool
AssertionError

### Version

1.2.12355

### What platform are you using?

Windows

### What ui mode are you using?

CLI

### Relevant log output

```shell
2022-02-27T20:03:11.389 wallet chia.rpc.rpc_server        : WARNING  Error while handling message: Traceback (most recent call last):
  File "chia\rpc\rpc_server.py", line 215, in safe_handle
  File "chia\rpc\rpc_server.py", line 206, in ws_api
  File "chia\rpc\wallet_rpc_api.py", line 1333, in pw_join_pool
AssertionError
```

**Comment by mariano54** [comment]
I would try with latest changes in main, I think this is fixed by https://github.com/Chia-Network/chia-blockchain/pull/10545

**Comment by emlowe** [comment]
Yes, almost certainly fixed in 1.3 release version - please re-open if you have further problems
