### ISSUE TITLE
Barely any peers [Bug] 

### ISSUE THREAD

**Issue by Oscillator098** [Chia-Network/chia-blockchain#10482]
### What happened?

Dell XPS 17 x702l (core i7, 8gb RAM, SSD)
Completely clean install after format Windows 10 21H2.
Only software installed is Chia v 1.2.12355
Imported key from Powershell
I'm slowly syncing wallet only from one node 45.156.37.64 while all others are getting "Not-trusted peer, not synced, disconnecting, banning x.x.x.x for 120 sec".

This success happened after hours and hours of debugging with last windows/chia installation when none of peers got through at all.
I Have tried to connect on my local 192.168.x.x peer without success, tried different machines, differed ISP providers.

Very poor performance.
Few weeks ago there was some older beta version with much better performance.

I Also have issues with detecting and adding CATs.

### Version

1.2.12355

### What platform are you using?

Windows

### What ui mode are you using?

GUI

### Relevant log output

```shell
2022-03-01T07:25:36.978 daemon __main__                   : ERROR    Unexpected exception trying to send to websocket: code = 1005 (no status code [internal]), no reason Traceback (most recent call last):
  File "Lib\site-packages\chia\daemon\server.py", line 225, in safe_handle
  File "websockets\protocol.py", line 555, in send
  File "websockets\protocol.py", line 812, in ensure_open
websockets.exceptions.ConnectionClosedError: code = 1005 (no status code [internal]), no reason

2022-03-01T07:25:36.991 daemon __main__                   : ERROR    Unexpected exception trying to send to websocket: code = 1005 (no status code [internal]), no reason Traceback (most recent call last):
  File "Lib\site-packages\chia\daemon\server.py", line 225, in safe_handle
  File "websockets\protocol.py", line 555, in send
  File "websockets\protocol.py", line 803, in ensure_open
websockets.exceptions.ConnectionClosedError: code = 1005 (no status code [internal]), no reason

2022-03-01T07:25:37.002 daemon __main__                   : ERROR    Unexpected exception trying to send to websocket: code = 1005 (no status code [internal]), no reason Traceback (most recent call last):
  File "Lib\site-packages\chia\daemon\server.py", line 225, in safe_handle
  File "websockets\protocol.py", line 555, in send
  File "websockets\protocol.py", line 803, in ensure_open
websockets.exceptions.ConnectionClosedError: code = 1005 (no status code [internal]), no reason

2022-03-01T07:25:37.007 daemon __main__                   : ERROR    Unexpected exception trying to send to websocket: code = 1005 (no status code [internal]), no reason Traceback (most recent call last):
  File "Lib\site-packages\chia\daemon\server.py", line 225, in safe_handle
  File "websockets\protocol.py", line 555, in send
  File "websockets\protocol.py", line 803, in ensure_open
websockets.exceptions.ConnectionClosedError: code = 1005 (no status code [internal]), no reason

2022-03-01T07:25:37.017 daemon __main__                   : ERROR    Unexpected exception trying to send to websocket: code = 1005 (no status code [internal]), no reason Traceback (most recent call last):
  File "Lib\site-packages\chia\daemon\server.py", line 225, in safe_handle
  File "websockets\protocol.py", line 555, in send
  File "websockets\protocol.py", line 803, in ensure_open
websockets.exceptions.ConnectionClosedError: code = 1005 (no status code [internal]), no reason

2022-03-01T07:26:11.970 wallet chia.wallet.wallet_node    : WARNING  No keys present. Create keys with the UI, or with the 'chia keys' program.
2022-03-01T07:26:45.132 wallet chia.wallet.wallet_node    : WARNING  querying DNS introducer failed: The resolution lifetime expired after 32.01668882369995 seconds: Server 192.168.43.1 UDP port 53 answered The DNS operation timed out after 1.999002456665039 seconds; Server 192.168.43.1 UDP port 53 answered The DNS operation timed out after 2.0 seconds; Server 192.168.43.1 UDP port 53 answered The DNS operation timed out after 1.9990241527557373 seconds; Server 192.168.43.1 UDP port 53 answered The DNS operation timed out after 1.9979660511016846 seconds; Server 192.168.43.1 UDP port 53 answered The DNS operation timed out after 2.0 seconds; Server 192.168.43.1 UDP port 53 answered The DNS operation timed out after 2.0 seconds; Server 192.168.43.1 UDP port 53 answered The DNS operation timed out after 2.0 seconds; Server 192.168.43.1 UDP port 53 answered The DNS operation timed out after 2.0 seconds; Server 192.168.43.1 UDP port 53 answered The DNS operation timed out after 2.0 seconds; Server 192.168.43.1 UDP port 53 answered The DNS operation timed out after 0.7019579410552979 seconds
2022-03-01T07:27:45.213 daemon __main__                   : ERROR    Unexpected exception trying to send to websocket: code = 1005 (no status code [internal]), no reason Traceback (most recent call last):
  File "Lib\site-packages\chia\daemon\server.py", line 225, in safe_handle
  File "websockets\protocol.py", line 555, in send
  File "websockets\protocol.py", line 812, in ensure_open
websockets.exceptions.ConnectionClosedError: code = 1005 (no status code [internal]), no reason

2022-03-01T07:27:45.220 daemon __main__                   : ERROR    Unexpected exception trying to send to websocket: code = 1005 (no status code [internal]), no reason Traceback (most recent call last):
  File "Lib\site-packages\chia\daemon\server.py", line 225, in safe_handle
  File "websockets\protocol.py", line 555, in send
  File "websockets\protocol.py", line 803, in ensure_open
websockets.exceptions.ConnectionClosedError: code = 1005 (no status code [internal]), no reason

2022-03-01T07:27:45.220 daemon __main__                   : ERROR    Unexpected exception trying to send to websocket: code = 1005 (no status code [internal]), no reason Traceback (most recent call last):
  File "Lib\site-packages\chia\daemon\server.py", line 225, in safe_handle
  File "websockets\protocol.py", line 555, in send
  File "websockets\protocol.py", line 803, in ensure_open
websockets.exceptions.ConnectionClosedError: code = 1005 (no status code [internal]), no reason

2022-03-01T07:27:45.235 daemon __main__                   : ERROR    Unexpected exception trying to send to websocket: code = 1005 (no status code [internal]), no reason Traceback (most recent call last):
  File "Lib\site-packages\chia\daemon\server.py", line 225, in safe_handle
  File "websockets\protocol.py", line 555, in send
  File "websockets\protocol.py", line 803, in ensure_open
websockets.exceptions.ConnectionClosedError: code = 1005 (no status code [internal]), no reason

2022-03-01T07:31:25.948 wallet chia.wallet.wallet_node    : WARNING  Non-trusted peer {'host': '171.96.100.153', 'port': 8444} is not synced, disconnecting
2022-03-01T07:31:26.198 wallet wallet_server              : WARNING  Banning 171.96.100.153 for 120 seconds
2022-03-01T07:31:26.667 wallet chia.wallet.wallet_node    : WARNING  Non-trusted peer {'host': '5.14.178.135', 'port': 8444} is not synced, disconnecting
2022-03-01T07:31:26.776 wallet wallet_server              : WARNING  Banning 5.14.178.135 for 120 seconds
2022-03-01T07:31:32.630 wallet chia.wallet.wallet_node    : WARNING  Non-trusted peer {'host': '72.180.118.62', 'port': 8444} is not synced, disconnecting
2022-03-01T07:31:32.833 wallet wallet_server              : WARNING  Banning 72.180.118.62 for 120 seconds
2022-03-01T07:31:34.006 wallet chia.wallet.wallet_node    : WARNING  Non-trusted peer {'host': '174.102.42.116', 'port': 8444} is not synced, disconnecting
2022-03-01T07:31:34.312 wallet wallet_server              : WARNING  Banning 174.102.42.116 for 120 seconds
2022-03-01T07:31:34.312 wallet chia.wallet.wallet_node    : WARNING  Peer None did not respond in time.
2022-03-01T07:31:35.802 wallet chia.wallet.wallet_node    : WARNING  Non-trusted peer {'host': '70.55.32.65', 'port': 8444} is not synced, disconnecting
2022-03-01T07:31:35.985 wallet wallet_server              : WARNING  Banning 70.55.32.65 for 120 seconds
2022-03-01T07:31:36.344 wallet chia.wallet.wallet_node    : WARNING  Non-trusted peer {'host': '94.26.237.44', 'port': 8444} is not synced, disconnecting
2022-03-01T07:31:36.453 wallet wallet_server              : WARNING  Banning 94.26.237.44 for 120 seconds
2022-03-01T07:31:45.373 wallet chia.wallet.wallet_node    : WARNING  Non-trusted peer {'host': '68.44.204.106', 'port': 8444} is not synced, disconnecting
2022-03-01T07:31:45.578 wallet wallet_server              : WARNING  Banning 68.44.204.106 for 120 seconds
2022-03-01T07:31:52.411 wallet chia.wallet.wallet_node    : WARNING  Non-trusted peer {'host': '89.76.22.106', 'port': 8444} is not synced, disconnecting
2022-03-01T07:31:52.507 wallet wallet_server              : WARNING  Banning 89.76.22.106 for 120 seconds
2022-03-01T07:31:56.628 wallet chia.wallet.wallet_node    : WARNING  Non-trusted peer {'host': '122.116.240.33', 'port': 8444} is not synced, disconnecting
2022-03-01T07:31:56.987 wallet wallet_server              : WARNING  Banning 122.116.240.33 for 120 seconds
2022-03-01T07:31:57.644 wallet chia.wallet.wallet_node    : WARNING  Non-trusted peer {'host': '51.38.231.198', 'port': 8444} is not synced, disconnecting
2022-03-01T07:31:57.762 wallet wallet_server              : WARNING  Banning 51.38.231.198 for 120 seconds
2022-03-01T07:32:00.594 wallet chia.wallet.wallet_node    : WARNING  Non-trusted peer {'host': '203.17.183.232', 'port': 8444} is not synced, disconnecting
2022-03-01T07:32:00.907 wallet wallet_server              : WARNING  Banning 203.17.183.232 for 120 seconds
```

**Comment by esaung** [comment]
Hi @Oscillator098 - try the latest beta update on the downloads page. It will be version 1.2.12 dev376 and let us know if you are experiencing the same issues. Also please let us know if you are in wallet mode or farmer mode.

Please submit a separate github issue for your CAT token issue. Auto-discovery is no longer enabled. so if you used the light wallet beta where it was enabled, switching to a new machine and new install, the app won't automatically discover the CATs. you'll have to manually add the CATs in your wallet for the balances to show up.
