### ISSUE TITLE
ValueError does not fit into uint128 1.3 beta

### ISSUE THREAD

**Issue by andrew2hart** [Chia-Network/chia-blockchain#10489]
2022-03-01T08:44:05.254 wallet chia.rpc.rpc_server        : WARNING  Error while handling message: Traceback (most recent call last):
  File "chia/rpc/rpc_server.py", line 215, in safe_handle
  File "chia/rpc/rpc_server.py", line 206, in ws_api
  File "chia/rpc/wallet_rpc_api.py", line 637, in get_wallet_balance
  File "chia/wallet/wallet.py", line 114, in get_unconfirmed_balance
  File "chia/wallet/wallet_state_manager.py", line 531, in get_unconfirmed_balance
  File "chia/wallet/wallet_state_manager.py", line 552, in _get_unconfirmed_balance
  File "chia/util/ints.py", line 42, in __new__
ValueError: Value -483689500995 of does not fit into uint128

**Comment by mariano54** [comment]
what version of beta? Can you try using the latest dev instead? https://www.chia.net/download/

**Comment by andrew2hart** [comment]
latest dev gives
2022-03-02T18:06:51.295 daemon __main__                   : INFO     Websocket exception. Closing websocket with chia_wallet code = 1006 (connection closed abnormally [internal]), no reason Traceback (most recent call last):
  File "websockets/protocol.py", line 827, in transfer_data
  File "websockets/protocol.py", line 895, in read_message
  File "websockets/protocol.py", line 971, in read_data_frame
  File "websockets/protocol.py", line 1047, in read_frame
  File "websockets/framing.py", line 105, in read
  File "asyncio/streams.py", line 721, in readexactly
asyncio.exceptions.IncompleteReadError: 0 bytes read on a total of 2 expected bytes

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "chia/daemon/server.py", line 210, in safe_handle
  File "websockets/protocol.py", line 439, in __aiter__
  File "websockets/protocol.py", line 509, in recv
  File "websockets/protocol.py", line 803, in ensure_open
websockets.exceptions.ConnectionClosedError: code = 1006 (connection closed abnormally [internal]), no reason

Not sure it is the same error though
dpkg --install chia-blockchain_arm64_latest_beta.deb 
(Reading database ... 202003 files and directories currently installed.)
Preparing to unpack chia-blockchain_arm64_latest_beta.deb ...
Unpacking chia-blockchain (1.2.12.dev389) over (1.2.12.dev355)

**Comment by esaung** [comment]
@mariano54 - the update height was 378 and he's running 389

**Comment by esaung** [comment]
@andrew2hart - can you try the following:
1.) chia stop -d all
2.) delete the ~/.chia/mainnet/wallet directory
3.) start chia

**Comment by emlowe** [comment]
We believe all such issues are fixed in 1.3 release. Please upgrade to 1.3 release and re-sync your wallet.
Please re-open if you continue to have issues
