### ISSUE TITLE
[Bug] Wallet RPC get_offers_count return an error when there are no trades

### ISSUE THREAD

**Issue by dkackman** [Chia-Network/chia-blockchain#10569]
### What happened?

Calling the wallet rpc method `get_offers_count` in a wallet without trades (it is still syncing) returned this error `int() argument must be a string, a bytes-like object or a number, not 'NoneType'`

(Where I indicate CLI below, I mean from my own code)

The error comes from (in main as of right now) _trade_store.py_ line 223.

        return int(row[0]), int(row[1]), int(row[2])

this previous check does not appear effective:

```
        if row is None:
            return 0, 0, 0
```

Also, there is no call to this rpc endpoint anywhere in the codebase, including unit tests. 

### Version

1.2.12.dev413

### What platform are you using?

Linux

### What ui mode are you using?

CLI

### Relevant log output

```shell
2022-03-06T20:25:59.545 wallet chia.rpc.rpc_server        : WARNING  Error while handling message: Traceback (most recent call last):
  File "/home/don/src/github/Chia-Network/chia-blockchain/chia/rpc/rpc_server.py", line 215, in safe_handle
    response = await self.ws_api(message)
  File "/home/don/src/github/Chia-Network/chia-blockchain/chia/rpc/rpc_server.py", line 206, in ws_api
    return await f(data)
  File "/home/don/src/github/Chia-Network/chia-blockchain/chia/rpc/wallet_rpc_api.py", line 995, in get_offers_count
    (total, my_offers_count, taken_offers_count) = await trade_mgr.trade_store.get_trades_count()
  File "/home/don/src/github/Chia-Network/chia-blockchain/chia/wallet/trading/trade_store.py", line 223, in get_trades_count
    return int(row[0]), int(row[1]), int(row[2])
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
```

**Comment by dkackman** [comment]
I see what the fix is. will PR it when i get a chance to test it out.

```python
    async def get_trades_count(self) -> Tuple[int, int, int]:
        """
        Returns the number of trades in the database broken down by is_my_offer status
        """
        query = "SELECT COUNT(*) AS total, "
        query += "SUM(CASE WHEN is_my_offer=1 THEN 1 ELSE 0 END) AS my_offers, "
        query += "SUM(CASE WHEN is_my_offer=0 THEN 1 ELSE 0 END) AS taken_offers "
        query += "FROM trade_records"
        cursor = await self.db_connection.execute(query)
        row = await cursor.fetchone()
        await cursor.close()

        total = 0
        my_offers_count = 0
        taken_offers_count = 0

        if row is not None: 
            if row[0] is not None:
                total = int(row[0])
            if row[1] is not None:
                my_offers_count = int(row[1])
            if row[2] is not None:
                taken_offers_count = int(row[2])               

        return total, my_offers_count, taken_offers_count
```
