### ISSUE TITLE
[Bug] full-node not starting

### ISSUE THREAD

**Issue by Dunuin** [Chia-Network/chia-blockchain#10588]
### What happened?

I downloaded the "chia-blockchain_1.3.0_amd64.deb" and installed it, replacing my working 1.2.11. When starting the GUI it starts all the services except for the full_node. Then the GUI is stuck at "Starting Services Full Node" and in the log I see the error shown below, which indicates to me that the full node got a problem and the process stopped.

Someone knows what the problem could be or how to fix this?

Chia is running on the latest Debian Bullseye inside a VM run on a Proxmox Hypervisor.

### Version

1.3.0

### What platform are you using?

Linux

### What ui mode are you using?

GUI

### Relevant log output

```shell
2022-03-08T09:03:37.315 daemon __main__                   : INFO     Websocket exception. Closing websocket with Unknown code = 1006 (connection closed abnormally [internal]), no reason Traceback (most recent call last):
  File "websockets/protocol.py", line 827, in transfer_data
  File "websockets/protocol.py", line 895, in read_message
  File "websockets/protocol.py", line 971, in read_data_frame
  File "websockets/protocol.py", line 1047, in read_frame
  File "websockets/framing.py", line 105, in read
  File "asyncio/streams.py", line 721, in readexactly
asyncio.exceptions.IncompleteReadError: 0 bytes read on a total of 2 expected bytes

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "chia/daemon/server.py", line 210, in safe_handle
  File "websockets/protocol.py", line 439, in __aiter__
  File "websockets/protocol.py", line 509, in recv
  File "websockets/protocol.py", line 803, in ensure_open
websockets.exceptions.ConnectionClosedError: code = 1006 (connection closed abnormally [internal]), no reason

2022-03-08T09:03:37.696 daemon __main__                   : INFO     process chia_wallet returned 0
2022-03-08T09:03:38.761 daemon __main__                   : INFO     sending term signal to chia_full_node
2022-03-08T09:03:38.763 full_node full_node               : INFO     got signal 15
2022-03-08T09:03:38.763 full_node full_node               : INFO     Cancelling reconnect task
2022-03-08T09:03:38.764 full_node full_node               : INFO     Closing connections
2022-03-08T09:03:38.768 full_node asyncio                 : ERROR    Exception in callback Service._accept_signal(signal_number=<Signals.SIGTERM: 15>)()
handle: <Handle Service._accept_signal(signal_number=<Signals.SIGTERM: 15>)()>
Traceback (most recent call last):
  File "asyncio/events.py", line 81, in _run
  File "chia/server/start_service.py", line 214, in _accept_signal
  File "chia/server/start_service.py", line 231, in stop
  File "chia/full_node/full_node.py", line 756, in _close
AttributeError: 'FullNode' object has no attribute '_sync_task'
2022-03-08T09:03:53.793 daemon __main__                   : INFO     sending kill signal to chia_full_node
2022-03-08T09:03:53.807 daemon __main__                   : INFO     process chia_full_node returned -9
2022-03-08T09:03:53.808 daemon __main__                   : INFO     chia daemon exiting in 5 seconds
2022-03-08T09:03:53.847 daemon __main__                   : INFO     Websocket exception. Closing websocket with wallet_ui code = 1005 (no status code [internal]), no reason Traceback (most recent call last):
  File "chia/daemon/server.py", line 210, in safe_handle
  File "websockets/protocol.py", line 439, in __aiter__
  File "websockets/protocol.py", line 509, in recv
  File "websockets/protocol.py", line 812, in ensure_open
websockets.exceptions.ConnectionClosedError: code = 1005 (no status code [internal]), no reason

2022-03-08T09:03:53.851 daemon __main__                   : INFO     Daemon WebSocketServer closed
2022-03-08T09:04:43.914 daemon __main__                   : INFO     Starting Daemon Server
2022-03-08T09:04:43.917 daemon __main__                   : INFO     Waiting Daemon WebSocketServer closure
2022-03-08T09:04:44.764 daemon __main__                   : INFO     Register service {'service': 'wallet_ui'}
2022-03-08T09:04:44.765 daemon __main__                   : INFO     registered for service wallet_ui
2022-03-08T09:04:44.765 daemon __main__                   : INFO     {'success': True}
```

**Comment by babipanghang** [comment]
Looks like there is an error making some connection. Could be a firewall issue?

**Comment by Dunuin** [comment]
Firewalls shouldn't be the problem as I didn't changed anything and it was running fine some minutes before with 1.2.11.
I deleted my ".chia" folder and looks like Chia is now working but needs to download the full blockchain again. So looks like some configs of Chia 1.2.11 won't allow Chia 1.3.0 to operate.
