### ISSUE TITLE
Fullnode don't start - database is locked

### ISSUE THREAD

**Issue by amnesia106** [Chia-Network/chia-blockchain#106]
`sudo ./scripts/run_full_node.sh
Starting process and logging to chia.log. Run with & to run in the background.
Starting process and logging to chia.log. Run with & to run in the background.
Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/testuser/chia-blockchain/src/server/start_full_node.py", line 150, in <module>
    asyncio.run(main())
  File "/usr/lib/python3.7/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.7/asyncio/base_events.py", line 583, in run_until_complete
    return future.result()
  File "/home/testuser/chia-blockchain/src/server/start_full_node.py", line 64, in main
    await store.add_block(genesis)
  File "/home/testuser/chia-blockchain/src/store.py", line 116, in add_block
    (block.height, block.header_hash.hex(), bytes(block)),
  File "/home/testuser/chia-blockchain/.venv/lib/python3.7/site-packages/aiosqlite/core.py", line 209, in execute
    cursor = await self._execute(self._conn.execute, sql, parameters)
  File "/home/testuser/chia-blockchain/.venv/lib/python3.7/site-packages/aiosqlite/core.py", line 167, in _execute
    return await future
  File "/home/testuser/chia-blockchain/.venv/lib/python3.7/site-packages/aiosqlite/core.py", line 153, in run
    result = function()
sqlite3.OperationalError: database is locked`

**Comment by Yostra** [comment]
Possibly you have another instance of FullNode already running on that machine ?

**Comment by mariano54** [comment]
Yes, try removing processes that start with chia. Also maybe don't run as sudo.
