### ISSUE TITLE
[Bug] chia keys migrate crash

### ISSUE THREAD

**Issue by Ealrann** [Chia-Network/chia-blockchain#10628]
### What happened?

The command `chia keys migrate` always crash. It happens on two different computers. Just do a new install to reproduce...

I guess it's no big deal, keys doesn't need to be migrated, but I didn't expect user command crash this way.

Step to reproduce:
1. Clone the repo
2. sh install.sh
3. . ./activate
4. chia init
5. chia keys generate
6. chia keys migrate

### Version

1.3.0

### What platform are you using?

Linux

### What ui mode are you using?

CLI

### Relevant log output

```shell
(venv) [chia@Field ~]$ chia keys migrate
Traceback (most recent call last):
  File "/home/chia/git/chia-blockchain/venv/bin/chia", line 33, in <module>
    sys.exit(load_entry_point('chia-blockchain', 'console_scripts', 'chia')())
  File "/home/chia/git/chia-blockchain/chia/cmds/chia.py", line 148, in main
    cli()  # pylint: disable=no-value-for-parameter
  File "/home/chia/git/chia-blockchain/venv/lib/python3.9/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/chia/git/chia-blockchain/venv/lib/python3.9/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/chia/git/chia-blockchain/venv/lib/python3.9/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/chia/git/chia-blockchain/venv/lib/python3.9/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/chia/git/chia-blockchain/venv/lib/python3.9/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/chia/git/chia-blockchain/venv/lib/python3.9/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/chia/git/chia-blockchain/venv/lib/python3.9/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/chia/git/chia-blockchain/chia/cmds/keys.py", line 144, in migrate_cmd
    migrate_keys()
  File "/home/chia/git/chia-blockchain/chia/cmds/keys_funcs.py", line 191, in migrate_keys
    keys_to_migrate, legacy_keyring = Keychain.get_keys_needing_migration()
  File "/home/chia/git/chia-blockchain/chia/util/keychain.py", line 568, in get_keys_needing_migration
    all_legacy_sks = legacy_keyring.get_all_private_keys()
  File "/home/chia/git/chia-blockchain/chia/util/keychain.py", line 350, in get_all_private_keys
    pkent = self._get_pk_and_entropy(get_private_key_user(self.user, index))
  File "/home/chia/git/chia-blockchain/chia/util/keychain.py", line 126, in wrapper
    return func(*args, **kwargs)
  File "/home/chia/git/chia-blockchain/chia/util/keychain.py", line 257, in _get_pk_and_entropy
    read_str = self.keyring_wrapper.get_passphrase(self.service, user)
  File "/home/chia/git/chia-blockchain/chia/util/keyring_wrapper.py", line 556, in get_passphrase
    return self.get_keyring().get_password(service, user)
AttributeError: 'NoneType' object has no attribute 'get_password'
```

**Comment by emlowe** [comment]
When you generate keys in 1.3 they are already stored in the new .chia_keys/keyring.yaml file, so you don't need to migrate them - but this should throw an exception either

**Comment by Ealrann** [comment]
> but this should throw an exception either

I'm not convinced exposing exceptions like that is a good idea, it feels like the software is broken.

**Comment by paninaro** [comment]
I'm pretty sure that @emlowe meant "but this shouldn't throw an exception either". So we're in agreement, the exception should not be raised.

**Comment by Ealrann** [comment]
Oh ok, my bad, I misunderstood  :no_mouth:

**Comment by emlowe** [comment]
typo on my part - yes it should **NOT** throw an exception
