### ISSUE TITLE
[Bug]  'chia db upgrade' returning unhandled exception

### ISSUE THREAD

**Issue by preto677** [Chia-Network/chia-blockchain#10634]
### What happened?

Tried twice, first time I had client ON, second time - OFF

```
[1/5] converting full_blocks
      1232.16 seconds
[2/5] converting sub_epoch_segments_v3
      49.31 seconds
[3/5] converting hint_store
      20.09 seconds
[4/5] converting coin_store
      4769.69 seconds
[5/5] build indices
      block store
      coin store
Traceback (most recent call last):
  File "Lib\site-packages\chia\cmds\chia.py", line 152, in <module>
  File "Lib\site-packages\chia\cmds\chia.py", line 148, in main
  File "click\core.py", line 829, in __call__
  File "click\core.py", line 782, in main
  File "click\core.py", line 1259, in invoke
  File "click\core.py", line 1259, in invoke
  File "click\core.py", line 1066, in invoke
  File "click\core.py", line 610, in invoke
  File "click\decorators.py", line 21, in new_func
  File "chia\cmds\db.py", line 28, in db_upgrade_cmd
  File "chia\cmds\db_upgrade_func.py", line 43, in db_upgrade_func
  File "chia\cmds\db_upgrade_func.py", line 361, in convert_v1_to_v2
sqlite3.OperationalError: database or disk is full
[11912] Failed to execute script 'chia' due to unhandled exception!
```

I have 150GB free on that drive.. So I have no idea why it's ending with **sqlite3.OperationalError: database or disk is full**

any tips? I really dont want to sync entire blockchain again

### Version

1.3

### What platform are you using?

Windows

### What ui mode are you using?

CLI

**Comment by emlowe** [comment]
I suspect it's using a temporary directory on your system drive - we are working on some better text output for these cases.

**Comment by emlowe** [comment]
Closing issue - there is a PR to give better feedback
