### ISSUE TITLE
[BUG] uvloop doesn't work

### ISSUE THREAD

**Issue by soulmerge** [Chia-Network/chia-blockchain#1077]
**Describe the bug**
The daemon cannot establish any connections when uvloop is installed.

**To Reproduce**
1. Install chia as usual
2. activate virtual environment
3. install uvloop-0.15.1
4. start daemon

**Environment:**

- debian buster
- python 3.7

**Stack trace**
```
12:45:30.866 full_node full_node_server        : ERROR    Error handling request                                             
Traceback (most recent call last):                                                                                           
  File "/home/chia/chia-blockchain/venv/lib/python3.7/site-packages/aiohttp/web_protocol.py", line 422, in _handle_request    
    resp = await self._request_handler(request)                                                                              
  File "/home/hia/chia-blockchain/venv/lib/python3.7/site-packages/aiohttp/web_app.py", line 499, in _handle                 
    resp = await handler(request)                                                                                            
  File "/home/chia/chia-blockchain/src/server/server.py", line 196, in incoming_connection                                    
    cert_bytes = request.transport._ssl_protocol._extra["ssl_object"].getpeercert(True)                                      
AttributeError: 'uvloop.loop._SSLProtocolTransport' object has no attribute '_ssl_protocol'                                  
```

**Comment by soulmerge** [comment]
Maybe this is just a documentation issue: I had installed uvloop because it was mentioned in the docs somewhere.

**Comment by hoffmang9** [comment]
I removed uvloop from the documentation last night in fact. It's a leftover from the Alpha stage and untested for months.
