### ISSUE TITLE
[Bug] 1.3.0 not synced

### ISSUE THREAD

**Issue by komocode** [Chia-Network/chia-blockchain#10807]
### What happened?

I've had the not syncing issue in 1.2.11. I commented on a previous bug report about it. I was told 1.3.0 fixes this so I upgraded from 1.2.11 to 1.3.0, but it is still not syncing.

I haven't been able to farm since November.

### Version

1.3.0

### What platform are you using?

Windows

### What ui mode are you using?

GUI

### Relevant log output

2022-03-22T15:35:05.472 full_node asyncio                 : ERROR    Task exception was never retrieved
future: <Task finished name='Task-2689671' coro=<RpcServer._state_changed() done, defined at chia\rpc\rpc_server.py:49> exception=KeyError(<bytes32: d780d22c7a87c9e01d98b49a0910f6701c3b95015741316b3fda042e5d7b81d2>)>
Traceback (most recent call last):
  File "chia\rpc\rpc_server.py", line 52, in _state_changed
  File "chia\rpc\full_node_rpc_api.py", line 71, in _state_changed
  File "chia\rpc\full_node_rpc_api.py", line 130, in get_blockchain_state
  File "chia\consensus\blockchain.py", line 172, in get_peak
  File "chia\consensus\blockchain.py", line 680, in height_to_block_record
  File "chia\consensus\blockchain.py", line 673, in block_record
KeyError: <bytes32: d780d22c7a87c9e01d98b49a0910f6701c3b95015741316b3fda042e5d7b81d2>
2022-03-22T15:35:05.678 full_node full_node_server        : INFO     Cannot connect to host 220.180.137.118:8444 ssl:<ssl.SSLContext object at 0x000001C821DDD6C0> [The semaphore timeout period has expired]
2022-03-22T15:35:05.978 wallet wallet                     : INFO     Reconnecting to peer {'host': '127.0.0.1', 'port': 8444}
2022-03-22T15:35:05.984 wallet wallet_server              : INFO     Connected with full_node {'host': '127.0.0.1', 'port': 8444}
2022-03-22T15:35:05.984 full_node asyncio                 : ERROR    Task exception was never retrieved
future: <Task finished name='Task-2689680' coro=<RpcServer._state_changed() done, defined at chia\rpc\rpc_server.py:49> exception=KeyError(<bytes32: d780d22c7a87c9e01d98b49a0910f6701c3b95015741316b3fda042e5d7b81d2>)>
Traceback (most recent call last):
  File "chia\rpc\rpc_server.py", line 52, in _state_changed
  File "chia\rpc\full_node_rpc_api.py", line 71, in _state_changed
  File "chia\rpc\full_node_rpc_api.py", line 130, in get_blockchain_state
  File "chia\consensus\blockchain.py", line 172, in get_peak
  File "chia\consensus\blockchain.py", line 680, in height_to_block_record
  File "chia\consensus\blockchain.py", line 673, in block_record
KeyError: <bytes32: d780d22c7a87c9e01d98b49a0910f6701c3b95015741316b3fda042e5d7b81d2>
2022-03-22T15:35:05.986 wallet wallet_server              : INFO     Connection closed: 127.0.0.1, node id: cf09db555ce6dd85ed748d04214d6e763d498bc196695af8ef642180098bc739
2022-03-22T15:35:05.986 full_node full_node_server        : INFO     Connection closed: 127.0.0.1, node id: 62c469ce3ef8e17853e30dd83b891ae1a7729937c86f125941e3ac65e64f0062
2022-03-22T15:35:06.997 full_node chia.full_node.full_node: INFO     peer disconnected {'host': '127.0.0.1', 'port': 8449}
2022-03-22T15:35:06.998 full_node full_node_server        : ERROR    Exception <bytes32: d780d22c7a87c9e01d98b49a0910f6701c3b95015741316b3fda042e5d7b81d2>, exception Stack: Traceback (most recent call last):
  File "chia\server\server.py", line 323, in incoming_connection
  File "chia\server\server.py", line 366, in connection_added
  File "chia\full_node\full_node.py", line 679, in on_connect
  File "chia\consensus\blockchain.py", line 673, in block_record
KeyError: <bytes32: d780d22c7a87c9e01d98b49a0910f6701c3b95015741316b3fda042e5d7b81d2>

2022-03-22T15:35:06.999 full_node asyncio                 : ERROR    Task exception was never retrieved
future: <Task finished name='Task-2689683' coro=<RpcServer._state_changed() done, defined at chia\rpc\rpc_server.py:49> exception=KeyError(<bytes32: d780d22c7a87c9e01d98b49a0910f6701c3b95015741316b3fda042e5d7b81d2>)>
Traceback (most recent call last):
  File "chia\rpc\rpc_server.py", line 52, in _state_changed
  File "chia\rpc\full_node_rpc_api.py", line 71, in _state_changed
  File "chia\rpc\full_node_rpc_api.py", line 130, in get_blockchain_state
  File "chia\consensus\blockchain.py", line 172, in get_peak
  File "chia\consensus\blockchain.py", line 680, in height_to_block_record
  File "chia\consensus\blockchain.py", line 673, in block_record
KeyError: <bytes32: d780d22c7a87c9e01d98b49a0910f6701c3b95015741316b3fda042e5d7b81d2>
2022-03-22T15:35:07.044 full_node full_node_server        : INFO     Cannot connect to host 175.139.224.242:8444 ssl:<ssl.SSLContext object at 0x000001C823742EC0> [The semaphore timeout period has expired]
2022-03-22T15:35:08.119 full_node full_node_server        : INFO     Cannot connect to host 213.3.4.31:8444 ssl:<ssl.SSLContext object at 0x000001C822109140> [The remote computer refused the network connection]
2022-03-22T15:35:08.386 full_node full_node_server        : INFO     Cannot connect to host 73.69.107.157:8444 ssl:<ssl.SSLContext object at 0x000001C822166EC0> [The semaphore timeout period has expired]
2022-03-22T15:35:08.667 full_node full_node_server        : INFO     Cannot connect to host 2405:9800:bc20:289:1413:414e:4015:7ae3:8444 ssl:<ssl.SSLContext object at 0x000001C8224C54C0> [The network location cannot be reached. For information about network troubleshooting, see Windows Help]
2022-03-22T15:35:08.824 full_node full_node_server        : INFO     Cannot connect to host 111.85.70.63:8444 ssl:<ssl.SSLContext object at 0x000001C8222619C0> [The semaphore timeout period has expired]
2022-03-22T15:35:09.012 wallet wallet                     : INFO     Reconnecting to peer {'host': '127.0.0.1', 'port': 8444}
2022-03-22T15:35:09.018 wallet wallet_server              : INFO     Connected with full_node {'host': '127.0.0.1', 'port': 8444}
2022-03-22T15:35:09.020 full_node asyncio                 : ERROR    Task exception was never retrieved
future: <Task finished name='Task-2689700' coro=<RpcServer._state_changed() done, defined at chia\rpc\rpc_server.py:49> exception=KeyError(<bytes32: d780d22c7a87c9e01d98b49a0910f6701c3b95015741316b3fda042e5d7b81d2>)>
Traceback (most recent call last):
  File "chia\rpc\rpc_server.py", line 52, in _state_changed
  File "chia\rpc\full_node_rpc_api.py", line 71, in _state_changed
  File "chia\rpc\full_node_rpc_api.py", line 130, in get_blockchain_state
  File "chia\consensus\blockchain.py", line 172, in get_peak
  File "chia\consensus\blockchain.py", line 680, in height_to_block_record
  File "chia\consensus\blockchain.py", line 673, in block_record
KeyError: <bytes32: d780d22c7a87c9e01d98b49a0910f6701c3b95015741316b3fda042e5d7b81d2>
2022-03-22T15:35:09.021 full_node full_node_server        : INFO     Connection closed: 127.0.0.1, node id: 62c469ce3ef8e17853e30dd83b891ae1a7729937c86f125941e3ac65e64f0062
2022-03-22T15:35:09.022 full_node chia.full_node.full_node: INFO     peer disconnected {'host': '127.0.0.1', 'port': 8449}
2022-03-22T15:35:09.023 full_node full_node_server        : ERROR    Exception <bytes32: d780d22c7a87c9e01d98b49a0910f6701c3b95015741316b3fda042e5d7b81d2>, exception Stack: Traceback (most recent call last):
  File "chia\server\server.py", line 323, in incoming_connection
  File "chia\server\server.py", line 366, in connection_added
  File "chia\full_node\full_node.py", line 679, in on_connect
  File "chia\consensus\blockchain.py", line 673, in block_record
KeyError: <bytes32: d780d22c7a87c9e01d98b49a0910f6701c3b95015741316b3fda042e5d7b81d2>

2022-03-22T15:35:09.024 full_node asyncio                 : ERROR    Task exception was never retrieved
future: <Task finished name='Task-2689703' coro=<RpcServer._state_changed() done, defined at chia\rpc\rpc_server.py:49> exception=KeyError(<bytes32: d780d22c7a87c9e01d98b49a0910f6701c3b95015741316b3fda042e5d7b81d2>)>
Traceback (most recent call last):
  File "chia\rpc\rpc_server.py", line 52, in _state_changed
  File "chia\rpc\full_node_rpc_api.py", line 71, in _state_changed
  File "chia\rpc\full_node_rpc_api.py", line 130, in get_blockchain_state
  File "chia\consensus\blockchain.py", line 172, in get_peak
  File "chia\consensus\blockchain.py", line 680, in height_to_block_record
  File "chia\consensus\blockchain.py", line 673, in block_record
KeyError: <bytes32: d780d22c7a87c9e01d98b49a0910f6701c3b95015741316b3fda042e5d7b81d2>
2022-03-22T15:35:09.020 wallet wallet_server              : INFO     Connection closed: 127.0.0.1, node id: cf09db555ce6dd85ed748d04214d6e763d498bc196695af8ef642180098bc739
2022-03-22T15:35:10.069 full_node full_node_server        : INFO     Cannot connect to host 14.223.160.19:8444 ssl:<ssl.SSLContext object at 0x000001C822E0FEC0> [The semaphore timeout period has expired]
2022-03-22T15:35:10.504 full_node full_node_server        : INFO     Cannot connect to host 92.244.99.106:8444 ssl:<ssl.SSLContext object at 0x000001C822E0FCC0> [The semaphore timeout period has expired]
2022-03-22T15:35:10.897 full_node full_node_server        : INFO     Cannot connect to host 2.155.66.3:8444 ssl:<ssl.SSLContext object at 0x000001C823A07540> [The semaphore timeout period has expired]
2022-03-22T15:35:11.336 full_node full_node_server        : INFO     Cannot connect to host 93.183.162.124:8444 ssl:<ssl.SSLContext object at 0x000001C822282B40> [The semaphore timeout period has expired]
2022-03-22T15:35:12.032 wallet wallet                     : INFO     Reconnecting to peer {'host': '127.0.0.1', 'port': 8444}
2022-03-22T15:35:12.038 wallet wallet_server              : INFO     Connected with full_node {'host': '127.0.0.1', 'port': 8444}
2022-03-22T15:35:12.039 full_node asyncio                 : ERROR    Task exception was never retrieved
future: <Task finished name='Task-2689727' coro=<RpcServer._state_changed() done, defined at chia\rpc\rpc_server.py:49> exception=KeyError(<bytes32: d780d22c7a87c9e01d98b49a0910f6701c3b95015741316b3fda042e5d7b81d2>)>
Traceback (most recent call last):
  File "chia\rpc\rpc_server.py", line 52, in _state_changed
  File "chia\rpc\full_node_rpc_api.py", line 71, in _state_changed
  File "chia\rpc\full_node_rpc_api.py", line 130, in get_blockchain_state
  File "chia\consensus\blockchain.py", line 172, in get_peak
  File "chia\consensus\blockchain.py", line 680, in height_to_block_record
  File "chia\consensus\blockchain.py", line 673, in block_record
KeyError: <bytes32: d780d22c7a87c9e01d98b49a0910f6701c3b95015741316b3fda042e5d7b81d2>
2022-03-22T15:35:12.040 wallet wallet_server              : INFO     Connection closed: 127.0.0.1, node id: cf09db555ce6dd85ed748d04214d6e763d498bc196695af8ef642180098bc739
2022-03-22T15:35:12.040 full_node full_node_server        : INFO     Connection closed: 127.0.0.1, node id: 62c469ce3ef8e17853e30dd83b891ae1a7729937c86f125941e3ac65e64f0062
2022-03-22T15:35:12.041 full_node chia.full_node.full_node: INFO     peer disconnected {'host': '127.0.0.1', 'port': 8449}
2022-03-22T15:35:12.043 full_node full_node_server        : ERROR    Exception <bytes32: d780d22c7a87c9e01d98b49a0910f6701c3b95015741316b3fda042e5d7b81d2>, exception Stack: Traceback (most recent call last):
  File "chia\server\server.py", line 323, in incoming_connection
  File "chia\server\server.py", line 366, in connection_added
  File "chia\full_node\full_node.py", line 679, in on_connect
  File "chia\consensus\blockchain.py", line 673, in block_record
KeyError: <bytes32: d780d22c7a87c9e01d98b49a0910f6701c3b95015741316b3fda042e5d7b81d2>

2022-03-22T15:35:12.044 full_node asyncio                 : ERROR    Task exception was never retrieved
future: <Task finished name='Task-2689730' coro=<RpcServer._state_changed() done, defined at chia\rpc\rpc_server.py:49> exception=KeyError(<bytes32: d780d22c7a87c9e01d98b49a0910f6701c3b95015741316b3fda042e5d7b81d2>)>
Traceback (most recent call last):
  File "chia\rpc\rpc_server.py", line 52, in _state_changed
  File "chia\rpc\full_node_rpc_api.py", line 71, in _state_changed
  File "chia\rpc\full_node_rpc_api.py", line 130, in get_blockchain_state
  File "chia\consensus\blockchain.py", line 172, in get_peak
  File "chia\consensus\blockchain.py", line 680, in height_to_block_record
  File "chia\consensus\blockchain.py", line 673, in block_record
KeyError: <bytes32: d780d22c7a87c9e01d98b49a0910f6701c3b95015741316b3fda042e5d7b81d2>
2022-03-22T15:35:12.195 full_node asyncio                 : ERROR    Task exception was never retrieved
future: <Task finished name='Task-2689734' coro=<RpcServer._state_changed() done, defined at chia\rpc\rpc_server.py:49> exception=KeyError(<bytes32: d780d22c7a87c9e01d98b49a0910f6701c3b95015741316b3fda042e5d7b81d2>)>
Traceback (most recent call last):
  File "chia\rpc\rpc_server.py", line 52, in _state_changed
  File "chia\rpc\full_node_rpc_api.py", line 71, in _state_changed
  File "chia\rpc\full_node_rpc_api.py", line 130, in get_blockchain_state
  File "chia\consensus\blockchain.py", line 172, in get_peak
  File "chia\consensus\blockchain.py", line 680, in height_to_block_record
  File "chia\consensus\blockchain.py", line 673, in block_record
KeyError: <bytes32: d780d22c7a87c9e01d98b49a0910f6701c3b95015741316b3fda042e5d7b81d2>
2022-03-22T15:35:12.196 full_node full_node_server        : INFO     Connection closed: 77.59.149.134, node id: 84c47aa3a01b8d23c42b0cab7f9d1698212dde5055e6e5382bed4bc16ca4061e
2022-03-22T15:35:12.197 full_node full_node_server        : WARNING  Banning 77.59.149.134 for 10 seconds
2022-03-22T15:35:12.197 full_node chia.full_node.full_node: INFO     peer disconnected {'host': '77.59.149.134', 'port': 8444}
2022-03-22T15:35:12.199 full_node full_node_server        : ERROR    Exception <bytes32: d780d22c7a87c9e01d98b49a0910f6701c3b95015741316b3fda042e5d7b81d2>, exception Stack: Traceback (most recent call last):
  File "chia\server\server.py", line 466, in start_client
  File "chia\server\server.py", line 366, in connection_added
  File "chia\server\node_discovery.py", line 241, in on_connect_callback
  File "chia\full_node\full_node.py", line 667, in on_connect
  File "chia\full_node\full_node.py", line 633, in synced
  File "chia\consensus\blockchain.py", line 172, in get_peak
  File "chia\consensus\blockchain.py", line 680, in height_to_block_record
  File "chia\consensus\blockchain.py", line 673, in block_record
KeyError: <bytes32: d780d22c7a87c9e01d98b49a0910f6701c3b95015741316b3fda042e5d7b81d2>

2022-03-22T15:35:12.200 full_node asyncio                 : ERROR    Task exception was never retrieved
future: <Task finished name='Task-2689737' coro=<RpcServer._state_changed() done, defined at chia\rpc\rpc_server.py:49> exception=KeyError(<bytes32: d780d22c7a87c9e01d98b49a0910f6701c3b95015741316b3fda042e5d7b81d2>)>
Traceback (most recent call last):
  File "chia\rpc\rpc_server.py", line 52, in _state_changed
  File "chia\rpc\full_node_rpc_api.py", line 71, in _state_changed
  File "chia\rpc\full_node_rpc_api.py", line 130, in get_blockchain_state
  File "chia\consensus\blockchain.py", line 172, in get_peak
  File "chia\consensus\blockchain.py", line 680, in height_to_block_record
  File "chia\consensus\blockchain.py", line 673, in block_record
KeyError: <bytes32: d780d22c7a87c9e01d98b49a0910f6701c3b95015741316b3fda042e5d7b81d2>
2022-03-22T15:35:13.524 full_node full_node_server        : INFO     Cannot connect to host 220.233.206.183:8444 ssl:<ssl.SSLContext object at 0x000001C8224C50C0> [The semaphore timeout period has expired]
2022-03-22T15:35:13.934 full_node full_node_server        : INFO     Cannot connect to host 120.33.37.64:8444 ssl:<ssl.SSLContext object at 0x000001C8232DB140> [The semaphore timeout period has expired]

**Comment by emlowe** [comment]
Insufficient details provided to help - please provide at a minimum log output

**Comment by komocode** [comment]
I've updated to 1.3.1. Now it shows "error".  Added logs.

**Comment by loppefaaret** [comment]
`KeyError: <bytes32: d780d22c7a87c9e01d98b49a0910f6701c3b95015741316b3fda042e5d7b81d2>`
You very likely got the `is_peak` error from #9677 
short fix, you need to close down the client and remove the faulty blockchain database manually, it is located under your users home folder, in `C:\Users\<USERNAME>\.chia\mainnet\db\blockchain_v....` seeing as you are on 1.3.X now, it is possible that you now have a v2 database, and that leaves more files to remove. 
basically, you need to remove everything but `peers.dat` (should you remove _all_ the files in the above folder, it is not the worse - it will get new peers on first run)
then open up the client again, and resync the entire blockchain from 0 - will take little more than a day on higher end hardware, and up to a week on lower end hardware, please have the database on an SSD based device.

the longer fix is to follow the directions in the above mentioned issue, and manually editing the database, moving the `is_peak` flag from block 0, to the highest block in your blockchain database with a tool such as "DB browser for SQLite" or similar tool that allows you to edit SQL databases.
