### ISSUE TITLE
No sincroniza nunca Bloques [Bug] 

### ISSUE THREAD

**Issue by Jugatitan** [Chia-Network/chia-blockchain#10831]
### What happened?

Al abrir la aplicacion queda sincronizando y nunca avanza el estado, dejo de funcionar de un dia para el otro.

### Version

1.3.1

### What platform are you using?

Windows

### What ui mode are you using?

GUI

### Relevant log output

```shell
2022-03-21T23:35:50.325 farmer asyncio                    : ERROR    Task exception was never retrieved
future: <Task finished name='Task-7' coro=<DaemonProxy.start.<locals>.listener() done, defined at chia\daemon\client.py:30> exception=ConnectionClosedError('code = 1006 (connection closed abnormally [internal]), no reason')>
Traceback (most recent call last):
  File "asyncio\windows_events.py", line 457, in finish_recv
OSError: [WinError 64] El nombre de red especificado ya no está disponible

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "websockets\protocol.py", line 827, in transfer_data
  File "websockets\protocol.py", line 895, in read_message
  File "websockets\protocol.py", line 971, in read_data_frame
  File "websockets\protocol.py", line 1047, in read_frame
  File "websockets\framing.py", line 105, in read
  File "asyncio\streams.py", line 723, in readexactly
  File "asyncio\streams.py", line 517, in _wait_for_data
  File "asyncio\proactor_events.py", line 280, in _loop_reading
  File "asyncio\windows_events.py", line 812, in _poll
  File "asyncio\windows_events.py", line 461, in finish_recv
ConnectionResetError: [WinError 64] El nombre de red especificado ya no está disponible

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "chia\daemon\client.py", line 33, in listener
  File "websockets\protocol.py", line 509, in recv
  File "websockets\protocol.py", line 803, in ensure_open
websockets.exceptions.ConnectionClosedError: code = 1006 (connection closed abnormally [internal]), no reason
2022-03-21T23:35:52.334 full_node chia.full_node.full_node: ERROR    failed fetching 2400 to 2432 from peers
2022-03-21T23:36:56.322 harvester chia.plotting.manager   : WARNING  Have multiple copies of the plot plot-k32-2021-07-21-03-51-9e4a3eeafb76fa983ac4e7a356685104f4b1490afb5164aaca0e370ba375e02b.plot in ['I:\\', 'H:\\'].
2022-03-21T23:36:56.425 harvester chia.plotting.manager   : WARNING  Have multiple copies of the plot plot-k32-2021-07-21-01-27-71d3852976c00cb6e8f4309c0485bd033bf315c6938253b6be941cc18421b695.plot in ['I:\\', 'H:\\'].
2022-03-21T23:40:49.369 full_node chia.full_node.full_node: ERROR    failed fetching 1920 to 1952 from peers
2022-03-21T23:47:00.921 wallet chia.wallet.wallet_node    : WARNING  Non-trusted peer {'host': '13.212.154.17', 'port': 8444} is not synced, disconnecting
2022-03-21T23:47:01.462 wallet wallet_server              : WARNING  Banning 13.212.154.17 for 120 seconds
2022-03-21T23:47:01.478 wallet chia.wallet.wallet_node    : WARNING  Peer None did not respond in time.
2022-03-21T23:47:32.447 wallet chia.wallet.wallet_node    : WARNING  Peer None did not respond in time.
2022-03-21T23:47:32.447 wallet chia.wallet.wallet_node    : WARNING  Peer None did not respond in time.
2022-03-21T23:47:33.025 wallet chia.wallet.wallet_node    : WARNING  Non-trusted peer {'host': '82.25.239.178', 'port': 8444} is not synced, disconnecting
2022-03-21T23:47:33.275 wallet wallet_server              : WARNING  Banning 82.25.239.178 for 120 seconds
2022-03-21T23:47:33.291 wallet chia.wallet.wallet_node    : WARNING  Peer None did not respond in time.
2022-03-21T23:47:33.291 wallet chia.wallet.wallet_node    : WARNING  Peer None did not respond in time.
2022-03-21T23:47:33.291 wallet chia.wallet.wallet_node    : WARNING  Peer None did not respond in time.
2022-03-21T23:47:33.291 wallet chia.wallet.wallet_node    : WARNING  Peer {'host': '82.25.239.178', 'port': 8444} did not respond in time.
2022-03-21T23:47:33.291 wallet chia.wallet.wallet_node    : WARNING  Peer None did not respond in time.
2022-03-21T23:47:33.291 wallet chia.wallet.wallet_node    : WARNING  Peer None did not respond in time.
2022-03-21T23:47:33.291 wallet chia.wallet.wallet_node    : WARNING  Peer None did not respond in time.
2022-03-21T23:47:33.291 wallet chia.wallet.wallet_node    : WARNING  Peer None did not respond in time.
2022-03-21T23:47:33.291 wallet chia.wallet.wallet_node    : WARNING  Peer None did not respond in time.
2022-03-21T23:47:33.291 wallet chia.wallet.wallet_node    : WARNING  Peer {'host': '82.25.239.178', 'port': 8444} did not respond in time.
2022-03-21T23:47:33.291 wallet chia.wallet.wallet_node    : WARNING  Peer {'host': '82.25.239.178', 'port': 8444} did not respond in time.
2022-03-21T23:47:33.291 wallet chia.wallet.wallet_node    : WARNING  Peer None did not respond in time.
2022-03-21T23:47:33.291 wallet chia.wallet.wallet_node    : WARNING  Peer None did not respond in time.
2022-03-21T23:47:33.291 wallet chia.wallet.wallet_node    : WARNING  Peer None did not respond in time.
2022-03-21T23:47:33.291 wallet chia.wallet.wallet_node    : WARNING  Peer None did not respond in time.
2022-03-21T23:47:33.291 wallet chia.wallet.wallet_node    : WARNING  Peer None did not respond in time.
2022-03-21T23:47:33.291 wallet chia.wallet.wallet_node    : WARNING  Peer {'host': '82.25.239.178', 'port': 8444} did not respond in time.
2022-03-21T23:47:33.291 wallet chia.wallet.wallet_node    : WARNING  Peer None did not respond in time.
2022-03-21T23:47:33.291 wallet chia.wallet.wallet_node    : WARNING  Peer None did not respond in time.
2022-03-21T23:47:33.291 wallet chia.wallet.wallet_node    : WARNING  Peer None did not respond in time.
2022-03-21T23:47:33.291 wallet chia.wallet.wallet_node    : WARNING  Peer None did not respond in time.
2022-03-21T23:47:33.291 wallet chia.wallet.wallet_node    : WARNING  Peer {'host': '82.25.239.178', 'port': 8444} did not respond in time.
2022-03-21T23:47:33.291 wallet chia.wallet.wallet_node    : WARNING  Peer None did not respond in time.
2022-03-21T23:47:33.291 wallet chia.wallet.wallet_node    : WARNING  Peer None did not respond in time.
2022-03-21T23:47:33.307 wallet chia.wallet.wallet_node    : WARNING  Peer None did not respond in time.
2022-03-21T23:47:33.307 wallet chia.wallet.wallet_node    : WARNING  Peer {'host': '82.25.239.178', 'port': 8444} did not respond in time.
2022-03-21T23:47:33.307 wallet chia.wallet.wallet_node    : WARNING  Peer None did not respond in time.
2022-03-21T23:47:33.307 wallet chia.wallet.wallet_node    : WARNING  Peer None did not respond in time.
2022-03-21T23:47:33.307 wallet chia.wallet.wallet_node    : WARNING  Peer None did not respond in time.
2022-03-21T23:47:33.307 wallet chia.wallet.wallet_node    : WARNING  Peer {'host': '82.25.239.178', 'port': 8444} did not respond in time.
2022-03-21T23:47:33.307 wallet chia.wallet.wallet_node    : WARNING  Peer {'host': '82.25.239.178', 'port': 8444} did not respond in time.
2022-03-21T23:47:33.307 wallet chia.wallet.wallet_node    : WARNING  Peer None did not respond in time.
2022-03-21T23:47:33.307 wallet chia.wallet.wallet_node    : WARNING  Peer None did not respond in time.
2022-03-21T23:47:33.307 wallet chia.wallet.wallet_node    : WARNING  Peer None did not respond in time.
2022-03-21T23:47:33.307 wallet chia.wallet.wallet_node    : WARNING  Peer {'host': '82.25.239.178', 'port': 8444} did not respond in time.
2022-03-21T23:47:33.307 wallet chia.wallet.wallet_node    : WARNING  Peer None did not respond in time.
2022-03-21T23:47:33.307 wallet chia.wallet.wallet_node    : WARNING  Peer None did not respond in time.
2022-03-21T23:47:33.307 wallet chia.wallet.wallet_node    : WARNING  Peer None did not respond in time.
2022-03-21T23:47:33.307 wallet chia.wallet.wallet_node    : WARNING  Peer None did not respond in time.
2022-03-21T23:47:33.307 wallet chia.wallet.wallet_node    : WARNING  Peer {'host': '82.25.239.178', 'port': 8444} did not respond in time.
2022-03-21T23:47:33.307 wallet chia.wallet.wallet_node    : WARNING  Peer None did not respond in time.
2022-03-21T23:47:33.307 wallet chia.wallet.wallet_node    : WARNING  Peer None did not respond in time.
2022-03-21T23:47:33.307 wallet chia.wallet.wallet_node    : WARNING  Peer {'host': '82.25.239.178', 'port': 8444} did not respond in time.
2022-03-21T23:47:33.307 wallet chia.wallet.wallet_node    : WARNING  Peer {'host': '82.25.239.178', 'port': 8444} did not respond in time.
2022-03-21T23:47:33.307 wallet chia.wallet.wallet_node    : WARNING  Peer None did not respond in time.
2022-03-21T23:47:33.307 wallet chia.wallet.wallet_node    : WARNING  Peer None did not respond in time.
2022-03-21T23:48:53.456 full_node chia.full_node.full_node: ERROR    sync from fork point failed err: <bytes32: d780d22c7a87c9e01d98b49a0910f6701c3b95015741316b3fda042e5d7b81d2>
2022-03-21T23:48:53.456 full_node asyncio                 : ERROR    Task exception was never retrieved
future: <Task finished name='Task-910' coro=<FullNode._sync() done, defined at chia\full_node\full_node.py:770> exception=KeyError(<bytes32: d780d22c7a87c9e01d98b49a0910f6701c3b95015741316b3fda042e5d7b81d2>)>
Traceback (most recent call last):
  File "chia\full_node\full_node.py", line 902, in _sync
  File "chia\full_node\full_node.py", line 1146, in _finish_sync
  File "chia\consensus\blockchain.py", line 172, in get_peak
  File "chia\consensus\blockchain.py", line 680, in height_to_block_record
  File "chia\consensus\blockchain.py", line 673, in block_record
KeyError: <bytes32: d780d22c7a87c9e01d98b49a0910f6701c3b95015741316b3fda042e5d7b81d2>
2022-03-21T23:48:53.484 full_node asyncio                 : ERROR    Task exception was never retrieved
future: <Task finished name='Task-2903' coro=<RpcServer._state_changed() done, defined at chia\rpc\rpc_server.py:49> exception=KeyError(<bytes32: d780d22c7a87c9e01d98b49a0910f6701c3b95015741316b3fda042e5d7b81d2>)>
Traceback (most recent call last):
  File "chia\rpc\rpc_server.py", line 52, in _state_changed
  File "chia\rpc\full_node_rpc_api.py", line 71, in _state_changed
  File "chia\rpc\full_node_rpc_api.py", line 130, in get_blockchain_state
  File "chia\consensus\blockchain.py", line 172, in get_peak
  File "chia\consensus\blockchain.py", line 680, in height_to_block_record
  File "chia\consensus\blockchain.py", line 673, in block_record
KeyError: <bytes32: d780d22c7a87c9e01d98b49a0910f6701c3b95015741316b3fda042e5d7b81d2>
2022-03-21T23:48:55.677 full_node full_node_server        : ERROR    Exception: <bytes32: d780d22c7a87c9e01d98b49a0910f6701c3b95015741316b3fda042e5d7b81d2>, {'host': '45.79.106.116', 'port': 8444}. Traceback (most recent call last):
  File "chia\server\server.py", line 595, in wrapped_coroutine
  File "chia\full_node\full_node_api.py", line 124, in new_peak
  File "chia\full_node\full_node.py", line 530, in new_peak
  File "chia\consensus\blockchain.py", line 172, in get_peak
  File "chia\consensus\blockchain.py", line 680, in height_to_block_record
  File "chia\consensus\blockchain.py", line 673, in block_record
KeyError: <bytes32: d780d22c7a87c9e01d98b49a0910f6701c3b95015741316b3fda042e5d7b81d2>

2022-03-21T23:48:55.678 full_node full_node_server        : ERROR    Exception: <bytes32: d780d22c7a87c9e01d98b49a0910f6701c3b95015741316b3fda042e5d7b81d2> <class 'KeyError'>, closing connection {'host': '45.79.106.116', 'port': 8444}. Traceback (most recent call last):
  File "chia\server\server.py", line 605, in api_call
  File "asyncio\tasks.py", line 442, in wait_for
  File "chia\server\server.py", line 602, in wrapped_coroutine
  File "chia\server\server.py", line 595, in wrapped_coroutine
  File "chia\full_node\full_node_api.py", line 124, in new_peak
  File "chia\full_node\full_node.py", line 530, in new_peak
  File "chia\consensus\blockchain.py", line 172, in get_peak
  File "chia\consensus\blockchain.py", line 680, in height_to_block_record
  File "chia\consensus\blockchain.py", line 673, in block_record
KeyError: <bytes32: d780d22c7a87c9e01d98b49a0910f6701c3b95015741316b3fda042e5d7b81d2>

2022-03-21T23:48:56.162 full_node full_node_server        : ERROR    Exception: <bytes32: d780d22c7a87c9e01d98b49a0910f6701c3b95015741316b3fda042e5d7b81d2>, {'host': '84.123.228.29', 'port': 8444}. Traceback (most recent call last):
  File "chia\server\server.py", line 595, in wrapped_coroutine
  File "chia\full_node\full_node_api.py", line 124, in new_peak
  File "chia\full_node\full_node.py", line 530, in new_peak
  File "chia\consensus\blockchain.py", line 172, in get_peak
  File "chia\consensus\blockchain.py", line 680, in height_to_block_record
  File "chia\consensus\blockchain.py", line 673, in block_record
KeyError: <bytes32: d780d22c7a87c9e01d98b49a0910f6701c3b95015741316b3fda042e5d7b81d2>

2022-03-21T23:48:56.164 full_node full_node_server        : ERROR    Exception: <bytes32: d780d22c7a87c9e01d98b49a0910f6701c3b95015741316b3fda042e5d7b81d2> <class 'KeyError'>, closing connection {'host': '84.123.228.29', 'port': 8444}. Traceback (most recent call last):
  File "chia\server\server.py", line 605, in api_call
  File "asyncio\tasks.py", line 442, in wait_for
  File "chia\server\server.py", line 602, in wrapped_coroutine
  File "chia\server\server.py", line 595, in wrapped_coroutine
  File "chia\full_node\full_node_api.py", line 124, in new_peak
  File "chia\full_node\full_node.py", line 530, in new_peak
  File "chia\consensus\blockchain.py", line 172, in get_peak
  File "chia\consensus\blockchain.py", line 680, in height_to_block_record
  File "chia\consensus\blockchain.py", line 673, in block_record
KeyError: <bytes32: d780d22c7a87c9e01d98b49a0910f6701c3b95015741316b3fda042e5d7b81d2>

2022-03-21T23:48:56.282 full_node full_node_server        : WARNING  Banning 45.79.106.116 for 10 seconds
2022-03-21T23:48:56.283 full_node asyncio                 : ERROR    Task exception was never retrieved
future: <Task finished name='Task-2912' coro=<RpcServer._state_changed() done, defined at chia\rpc\rpc_server.py:49> exception=KeyError(<bytes32: d780d22c7a87c9e01d98b49a0910f6701c3b95015741316b3fda042e5d7b81d2>)>
Traceback (most recent call last):
  File "chia\rpc\rpc_server.py", line 52, in _state_changed
  File "chia\rpc\full_node_rpc_api.py", line 71, in _state_changed
  File "chia\rpc\full_node_rpc_api.py", line 130, in get_blockchain_state
  File "chia\consensus\blockchain.py", line 172, in get_peak
  File "chia\consensus\blockchain.py", line 680, in height_to_block_record
  File "chia\consensus\blockchain.py", line 673, in block_record
KeyError: <bytes32: d780d22c7a87c9e01d98b49a0910f6701c3b95015741316b3fda042e5d7b81d2>
2022-03-21T23:48:56.530 full_node full_node_server        : WARNING  Banning 84.123.228.29 for 10 seconds
2022-03-21T23:48:56.531 full_node asyncio                 : ERROR    Task exception was never retrieved
future: <Task finished name='Task-2914' coro=<RpcServer._state_changed() done, defined at chia\rpc\rpc_server.py:49> exception=KeyError(<bytes32: d780d22c7a87c9e01d98b49a0910f6701c3b95015741316b3fda042e5d7b81d2>)>
Traceback (most recent call last):
  File "chia\rpc\rpc_server.py", line 52, in _state_changed
  File "chia\rpc\full_node_rpc_api.py", line 71, in _state_changed
  File "chia\rpc\full_node_rpc_api.py", line 130, in get_blockchain_state
  File "chia\consensus\blockchain.py", line 172, in get_peak
  File "chia\consensus\blockchain.py", line 680, in height_to_block_record
  File "chia\consensus\blockchain.py", line 673, in block_record
KeyError: <bytes32: d780d22c7a87c9e01d98b49a0910f6701c3b95015741316b3fda042e5d7b81d2>
2022-03-21T23:48:56.947 full_node full_node_server        : ERROR    Exception: <bytes32: d780d22c7a87c9e01d98b49a0910f6701c3b95015741316b3fda042e5d7b81d2>, {'host': '54.212.28.156', 'port': 8444}. Traceback (most recent call last):
  File "chia\server\server.py", line 595, in wrapped_coroutine
  File "chia\full_node\full_node_api.py", line 124, in new_peak
  File "chia\full_node\full_node.py", line 530, in new_peak
  File "chia\consensus\blockchain.py", line 172, in get_peak
  File "chia\consensus\blockchain.py", line 680, in height_to_block_record
  File "chia\consensus\blockchain.py", line 673, in block_record
KeyError: <bytes32: d780d22c7a87c9e01d98b49a0910f6701c3b95015741316b3fda042e5d7b81d2>

2022-03-21T23:48:56.948 full_node full_node_server        : ERROR    Exception: <bytes32: d780d22c7a87c9e01d98b49a0910f6701c3b95015741316b3fda042e5d7b81d2> <class 'KeyError'>, closing connection {'host': '54.212.28.156', 'port': 8444}. Traceback (most recent call last):
  File "chia\server\server.py", line 605, in api_call
  File "asyncio\tasks.py", line 442, in wait_for
  File "chia\server\server.py", line 602, in wrapped_coroutine
  File "chia\server\server.py", line 595, in wrapped_coroutine
  File "chia\full_node\full_node_api.py", line 124, in new_peak
  File "chia\full_node\full_node.py", line 530, in new_peak
  File "chia\consensus\blockchain.py", line 172, in get_peak
  File "chia\consensus\blockchain.py", line 680, in height_to_block_record
  File "chia\consensus\blockchain.py", line 673, in block_record
KeyError: <bytes32: d780d22c7a87c9e01d98b49a0910f6701c3b95015741316b3fda042e5d7b81d2>

2022-03-21T23:48:57.225 full_node full_node_server        : WARNING  Banning node.chia.net for 10 seconds
2022-03-21T23:48:57.226 full_node asyncio                 : ERROR    Task exception was never retrieved
future: <Task finished name='Task-2920' coro=<RpcServer._state_changed() done, defined at chia\rpc\rpc_server.py:49> exception=KeyError(<bytes32: d780d22c7a87c9e01d98b49a0910f6701c3b95015741316b3fda042e5d7b81d2>)>
Traceback (most recent call last):
  File "chia\rpc\rpc_server.py", line 52, in _state_changed
  File "chia\rpc\full_node_rpc_api.py", line 71, in _state_changed
  File "chia\rpc\full_node_rpc_api.py", line 130, in get_blockchain_state
  File "chia\consensus\blockchain.py", line 172, in get_peak
  File "chia\consensus\blockchain.py", line 680, in height_to_block_record
  File "chia\consensus\blockchain.py", line 673, in block_record
KeyError: <bytes32: d780d22c7a87c9e01d98b49a0910f6701c3b95015741316b3fda042e5d7b81d2>
2022-03-21T23:48:57.488 full_node full_node_server        : ERROR    Exception: <bytes32: d780d22c7a87c9e01d98b49a0910f6701c3b95015741316b3fda042e5d7b81d2>, {'host': '103.233.193.26', 'port': 8444}. Traceback (most recent call last):
  File "chia\server\server.py", line 595, in wrapped_coroutine
  File "chia\full_node\full_node_api.py", line 138, in new_transaction
  File "chia\full_node\full_node.py", line 633, in synced
  File "chia\consensus\blockchain.py", line 172, in get_peak
  File "chia\consensus\blockchain.py", line 680, in height_to_block_record
  File "chia\consensus\blockchain.py", line 673, in block_record
KeyError: <bytes32: d780d22c7a87c9e01d98b49a0910f6701c3b95015741316b3fda042e5d7b81d2>

2022-03-21T23:48:57.489 full_node full_node_server        : ERROR    Exception: <bytes32: d780d22c7a87c9e01d98b49a0910f6701c3b95015741316b3fda042e5d7b81d2> <class 'KeyError'>, closing connection {'host': '103.233.193.26', 'port': 8444}. Traceback (most recent call last):
  File "chia\server\server.py", line 605, in api_call
  File "asyncio\tasks.py", line 479, in wait_for
  File "chia\server\server.py", line 602, in wrapped_coroutine
  File "chia\server\server.py", line 595, in wrapped_coroutine
  File "chia\full_node\full_node_api.py", line 138, in new_transaction
  File "chia\full_node\full_node.py", line 633, in synced
  File "chia\consensus\blockchain.py", line 172, in get_peak
  File "chia\consensus\blockchain.py", line 680, in height_to_block_record
  File "chia\consensus\blockchain.py", line 673, in block_record
KeyError: <bytes32: d780d22c7a87c9e01d98b49a0910f6701c3b95015741316b3fda042e5d7b81d2>

2022-03-21T23:48:58.384 full_node full_node_server        : WARNING  Banning 103.233.193.26 for 10 seconds
2022-03-21T23:48:58.385 full_node asyncio                 : ERROR    Task exception was never retrieved
future: <Task finished name='Task-2924' coro=<RpcServer._state_changed() done, defined at chia\rpc\rpc_server.py:49> exception=KeyError(<bytes32: d780d22c7a87c9e01d98b49a0910f6701c3b95015741316b3fda042e5d7b81d2>)>
Traceback (most recent call last):
  File "chia\rpc\rpc_server.py", line 52, in _state_changed
  File "chia\rpc\full_node_rpc_api.py", line 71, in _state_changed
  File "chia\rpc\full_node_rpc_api.py", line 130, in get_blockchain_state
  File "chia\consensus\blockchain.py", line 172, in get_peak
  File "chia\consensus\blockchain.py", line 680, in height_to_block_record
  File "chia\consensus\blockchain.py", line 673, in block_record
KeyError: <bytes32: d780d22c7a87c9e01d98b49a0910f6701c3b95015741316b3fda042e5d7b81d2>
2022-03-21T23:48:59.436 full_node full_node_server        : ERROR    Exception: <bytes32: d780d22c7a87c9e01d98b49a0910f6701c3b95015741316b3fda042e5d7b81d2>, {'host': '62.170.5.71', 'port': 8444}. Traceback (most recent call last):
  File "chia\server\server.py", line 595, in wrapped_coroutine
  File "chia\full_node\full_node_api.py", line 124, in new_peak
  File "chia\full_node\full_node.py", line 530, in new_peak
  File "chia\consensus\blockchain.py", line 172, in get_peak
  File "chia\consensus\blockchain.py", line 680, in height_to_block_record
  File "chia\consensus\blockchain.py", line 673, in block_record
KeyError: <bytes32: d780d22c7a87c9e01d98b49a0910f6701c3b95015741316b3fda042e5d7b81d2>

2022-03-21T23:48:59.438 full_node full_node_server        : ERROR    Exception: <bytes32: d780d22c7a87c9e01d98b49a0910f6701c3b95015741316b3fda042e5d7b81d2> <class 'KeyError'>, closing connection {'host': '62.170.5.71', 'port': 8444}. Traceback (most recent call last):
  File "chia\server\server.py", line 605, in api_call
  File "asyncio\tasks.py", line 442, in wait_for
  File "chia\server\server.py", line 602, in wrapped_coroutine
  File "chia\server\server.py", line 595, in wrapped_coroutine
  File "chia\full_node\full_node_api.py", line 124, in new_peak
  File "chia\full_node\full_node.py", line 530, in new_peak
  File "chia\consensus\blockchain.py", line 172, in get_peak
  File "chia\consensus\blockchain.py", line 680, in height_to_block_record
  File "chia\consensus\blockchain.py", line 673, in block_record
KeyError: <bytes32: d780d22c7a87c9e01d98b49a0910f6701c3b95015741316b3fda042e5d7b81d2>

2022-03-21T23:49:00.349 full_node full_node_server        : WARNING  Banning 62.170.5.71 for 10 seconds
2022-03-21T23:49:00.351 full_node asyncio                 : ERROR    Task exception was never retrieved
future: <Task finished name='Task-2929' coro=<RpcServer._state_changed() done, defined at chia\rpc\rpc_server.py:49> exception=KeyError(<bytes32: d780d22c7a87c9e01d98b49a0910f6701c3b95015741316b3fda042e5d7b81d2>)>
Traceback (most recent call last):
  File "chia\rpc\rpc_server.py", line 52, in _state_changed
  File "chia\rpc\full_node_rpc_api.py", line 71, in _state_changed
  File "chia\rpc\full_node_rpc_api.py", line 130, in get_blockchain_state
  File "chia\consensus\blockchain.py", line 172, in get_peak
  File "chia\consensus\blockchain.py", line 680, in height_to_block_record
  File "chia\consensus\blockchain.py", line 673, in block_record
KeyError: <bytes32: d780d22c7a87c9e01d98b49a0910f6701c3b95015741316b3fda042e5d7b81d2>
```

**Comment by emlowe** [comment]
You need to resync your node DB.
