### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by ChrisCalvin** [Chia-Network/chia-blockchain#10834]
### What happened?

Ubuntu 20.04 LTS updated and upgraded
chia 1.3.1

unable to sync full node or wallet.  This issue happened after I noticed that I was no longer submitting partials to my pool.  My full node was out of sync, but my wallet was not.  I updated chia to 1.3.1 and then lost my wallet sync as well.

~/chia-blockchain$ chia start farmer
Daemon not started yet
Starting daemon
Traceback (most recent call last):
  File "/home/chris/chia-blockchain/venv/bin/chia", line 33, in <module>
    sys.exit(load_entry_point('chia-blockchain', 'console_scripts', 'chia')())
  File "/home/chris/chia-blockchain/chia/cmds/chia.py", line 148, in main
    cli()  # pylint: disable=no-value-for-parameter
  File "/home/chris/chia-blockchain/venv/lib/python3.9/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/chris/chia-blockchain/venv/lib/python3.9/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/chris/chia-blockchain/venv/lib/python3.9/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/chris/chia-blockchain/venv/lib/python3.9/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/chris/chia-blockchain/venv/lib/python3.9/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/chris/chia-blockchain/venv/lib/python3.9/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/chris/chia-blockchain/chia/cmds/chia.py", line 125, in run_daemon_cmd
    asyncio.get_event_loop().run_until_complete(async_run_daemon(ctx.obj["root_path"], wait_for_unlock=wait_for_unlock))
  File "/home/chris/miniconda3/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/home/chris/chia-blockchain/chia/daemon/server.py", line 1483, in async_run_daemon
    await ws_server.start()
  File "/home/chris/chia-blockchain/chia/daemon/server.py", line 187, in start
    self.websocket_server = await serve(
  File "/home/chris/chia-blockchain/venv/lib/python3.9/site-packages/websockets/server.py", line 965, in __await_impl__
    server = await self._create_server()
  File "/home/chris/miniconda3/lib/python3.9/asyncio/base_events.py", line 1494, in create_server
    raise OSError(err.errno, 'error while attempting '
OSError: [Errno 98] error while attempting to bind on address ('127.0.0.1', 55400): address already in use
Daemon not started yet
Failed to create the chia daemon

Not sure what to do.  I have since deleted the .chia folder and reinstalled chia, but I get the same error.

### Version

1.3.1

### What platform are you using?

Linux

### What ui mode are you using?

CLI

### Relevant log output

```shell
~/chia-blockchain$ chia start farmer
Daemon not started yet
Starting daemon
Traceback (most recent call last):
  File "/home/chris/chia-blockchain/venv/bin/chia", line 33, in <module>
    sys.exit(load_entry_point('chia-blockchain', 'console_scripts', 'chia')())
  File "/home/chris/chia-blockchain/chia/cmds/chia.py", line 148, in main
    cli()  # pylint: disable=no-value-for-parameter
  File "/home/chris/chia-blockchain/venv/lib/python3.9/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/chris/chia-blockchain/venv/lib/python3.9/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/chris/chia-blockchain/venv/lib/python3.9/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/chris/chia-blockchain/venv/lib/python3.9/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/chris/chia-blockchain/venv/lib/python3.9/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/chris/chia-blockchain/venv/lib/python3.9/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/chris/chia-blockchain/chia/cmds/chia.py", line 125, in run_daemon_cmd
    asyncio.get_event_loop().run_until_complete(async_run_daemon(ctx.obj["root_path"], wait_for_unlock=wait_for_unlock))
  File "/home/chris/miniconda3/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/home/chris/chia-blockchain/chia/daemon/server.py", line 1483, in async_run_daemon
    await ws_server.start()
  File "/home/chris/chia-blockchain/chia/daemon/server.py", line 187, in start
    self.websocket_server = await serve(
  File "/home/chris/chia-blockchain/venv/lib/python3.9/site-packages/websockets/server.py", line 965, in __await_impl__
    server = await self._create_server()
  File "/home/chris/miniconda3/lib/python3.9/asyncio/base_events.py", line 1494, in create_server
    raise OSError(err.errno, 'error while attempting '
OSError: [Errno 98] error while attempting to bind on address ('127.0.0.1', 55400): address already in use
Daemon not started yet
Failed to create the chia daemon
```

**Comment by Fenex** [comment]
> OSError: [Errno 98] error while attempting to bind on address ('127.0.0.1', 55400): address already in use

This port (55400 already in use on your system. Try to restart system or make sure that all chia processes is NOT running `ps -aux` .

Also see similar issue #7606 and its comments.
