### ISSUE TITLE
[Bug] Unable to start full node after updating to 1.3.1

### ISSUE THREAD

**Issue by filipejsbrandao** [Chia-Network/chia-blockchain#10883]
### What happened?

Updated to 1.3.1 from 1.2.11 and now the GUI doesn't pass the loading of the full node service.
Reloading the gui after a minute or so it shows that the wallet is synced and the blockchain also.

After shutting down the service, I tried to resart the full node using powershell as suggested in another issue.
Bellow is the log of the console. 

### Version

1.3.1

### What platform are you using?

Windows

### What ui mode are you using?

GUI

### Relevant log output

```shell
Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

Try the new cross-platform PowerShell https://aka.ms/pscore6

PS C:\Users\Filipe> cd ~\AppData\Local\chia-blockchain\app-1.3.1\resources\app.asar.unpacked\daemon\
PS C:\Users\Filipe\AppData\Local\chia-blockchain\app-1.3.1\resources\app.asar.unpacked\daemon> .\chia.exe start node
Daemon not started yet
Starting daemon
chia_full_node: started
PS C:\Users\Filipe\AppData\Local\chia-blockchain\app-1.3.1\resources\app.asar.unpacked\daemon> Traceback (most recent call last):
  File "Lib\site-packages\chia\server\start_full_node.py", line 65, in <module>
  File "Lib\site-packages\chia\server\start_full_node.py", line 60, in main
  File "chia\server\start_service.py", line 278, in run_service
  File "asyncio\runners.py", line 44, in run
  File "asyncio\base_events.py", line 642, in run_until_complete
  File "chia\server\start_service.py", line 272, in async_run_service
  File "chia\server\start_service.py", line 182, in run
  File "chia\server\start_service.py", line 144, in start
  File "chia\full_node\full_node.py", line 197, in _start
  File "chia\consensus\blockchain.py", line 136, in create
  File "chia\consensus\blockchain.py", line 149, in _load_chain_from_store
  File "chia\full_node\block_height_map.py", line 123, in create
  File "chia\full_node\block_height_map.py", line 185, in _load_blocks_from
KeyError: <bytes32: 8777daf2d6bb4682565a98cba73a1098846402d64ef5dbe1ec289af69e001e06>
[26368] Failed to execute script 'start_full_node' due to unhandled exception!
```

**Comment by emlowe** [comment]
Can you post the output of `chia db validate`?  You may have to resync the node

**Comment by arvidn** [comment]
this can also be reproduced by running:
```
$ python tools/test_full_sync.py run --db-version 2 ~/.chia/mainnet/db/blockchain_v2_mainnet.sqlite
```

(at least it looks like the same issue).

```
Traceback (most recent call last):
  File "/home/arvid/dev/2/chia-blockchain/tools/test_full_sync.py", line 145, in <module>
    main()
  File "/home/arvid/dev/2/chia-blockchain/venv/lib/python3.9/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/arvid/dev/2/chia-blockchain/venv/lib/python3.9/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/arvid/dev/2/chia-blockchain/venv/lib/python3.9/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/arvid/dev/2/chia-blockchain/venv/lib/python3.9/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/arvid/dev/2/chia-blockchain/venv/lib/python3.9/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/arvid/dev/2/chia-blockchain/tools/test_full_sync.py", line 125, in run
    asyncio.run(run_sync_test(Path(file), db_version, profile))
  File "/usr/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/home/arvid/dev/2/chia-blockchain/tools/test_full_sync.py", line 98, in run_sync_test
    success, advanced_peak, fork_height, coin_changes = await full_node.receive_block_batch(
  File "/home/arvid/dev/2/chia-blockchain/chia/full_node/full_node.py", line 1090, in receive_block_batch
    pre_validation_results: List[PreValidationResult] = await self.blockchain.pre_validate_blocks_multiprocessing(
  File "/home/arvid/dev/2/chia-blockchain/chia/consensus/blockchain.py", line 634, in pre_validate_blocks_multiprocessing
    return await pre_validate_blocks_multiprocessing(
  File "/home/arvid/dev/2/chia-blockchain/chia/consensus/multiprocess_validation.py", line 241, in pre_validate_blocks_multiprocessing
    challenge = get_block_challenge(constants, block, BlockCache(recent_blocks), prev_b is None, overflow, False)
  File "/home/arvid/dev/2/chia-blockchain/chia/consensus/get_block_challenge.py", line 91, in get_block_challenge
    curr: BlockRecord = blocks.block_record(header_block.prev_header_hash)
  File "/home/arvid/dev/2/chia-blockchain/chia/util/block_cache.py", line 35, in block_record
    return self._block_records[header_hash]
KeyError: <bytes32: 7c27699b939dbd9b026e872e13650901e38d2e9590934aed67ba516a0f1108a0>
```

**Comment by filipejsbrandao** [comment]
@emlowe this is the output of chia db validate:

Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

Try the new cross-platform PowerShell https://aka.ms/pscore6

PS C:\Users\Filipe> cd ~\AppData\Local\chia-blockchain\app-1.3.1\resources\app.asar.unpacked\daemon\
PS C:\Users\Filipe\AppData\Local\chia-blockchain\app-1.3.1\resources\app.asar.unpacked\daemon> .\chia db validate
opening file for reading: F:\Chia_Blockchain\mainnet\db\blockchain_v1_mainnet.sqlite
FAILED: Database is missing version table
PS C:\Users\Filipe\AppData\Local\chia-blockchain\app-1.3.1\resources\app.asar.unpacked\daemon>

**Comment by arvidn** [comment]
`chia db validate` only works on v2 databases

**Comment by filipejsbrandao** [comment]
So, @emlowe @arvidn that means I have to resync the node?

**Comment by arvidn** [comment]
I don't know (yet) what's causing this issue. syncing your node from scratch, will probably get you back up and running sooner, than for us to fix this issue.

I'm currently trying to pin-point where this broke to understand what's going wrong.

**Comment by arvidn** [comment]
@filipejsbrandao I took a closer look at your stack trace. It looks like the block with header hash `8777daf2d6bb4682565a98cba73a1098846402d64ef5dbe1ec289af69e001e06` is missing from your database.

Could you try opening your database in `sqlite3` and run:

```
select height from full_blocks where header_hash=x'8777daf2d6bb4682565a98cba73a1098846402d64ef5dbe1ec289af69e001e06';
```

**Comment by arvidn** [comment]
I'm proposing this change to improve the error message: https://github.com/Chia-Network/chia-blockchain/pull/10958
