### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by ydhuang1989** [Chia-Network/chia-blockchain#10970]
### What happened?

![13](https://user-images.githubusercontent.com/84565255/161014911-ba96bf33-1bc0-435e-bf3d-bd5fde595cf7.png)

ALL ERR"ORRRRRRR

### Version

Version 1.3.1 | 64 bit

### What platform are you using?

Windows

### What ui mode are you using?

GUI

**Comment by ydhuang1989** [comment]
2022-04-03T01:04:26.698 full_node asyncio                 : ERROR    Task exception was never retrieved
future: <Task finished name='Task-72414' coro=<RpcServer._state_changed() done, defined at chia\rpc\rpc_server.py:49> exception=KeyError(<bytes32: d780d22c7a87c9e01d98b49a0910f6701c3b95015741316b3fda042e5d7b81d2>)>
Traceback (most recent call last):
  File "chia\rpc\rpc_server.py", line 52, in _state_changed
  File "chia\rpc\full_node_rpc_api.py", line 71, in _state_changed
  File "chia\rpc\full_node_rpc_api.py", line 130, in get_blockchain_state
  File "chia\consensus\blockchain.py", line 172, in get_peak
  File "chia\consensus\blockchain.py", line 680, in height_to_block_record
  File "chia\consensus\blockchain.py", line 673, in block_record
KeyError: <bytes32: d780d22c7a87c9e01d98b49a0910f6701c3b95015741316b3fda042e5d7b81d2>
2022-04-03T01:04:27.105 full_node asyncio                 : ERROR    Task exception was never retrieved
future: <Task finished name='Task-72421' coro=<RpcServer._state_changed() done, defined at chia\rpc\rpc_server.py:49> exception=KeyError(<bytes32: d780d22c7a87c9e01d98b49a0910f6701c3b95015741316b3fda042e5d7b81d2>)>
Traceback (most recent call last):
  File "chia\rpc\rpc_server.py", line 52, in _state_changed
  File "chia\rpc\full_node_rpc_api.py", line 71, in _state_changed
  File "chia\rpc\full_node_rpc_api.py", line 130, in get_blockchain_state
  File "chia\consensus\blockchain.py", line 172, in get_peak
  File "chia\consensus\blockchain.py", line 680, in height_to_block_record
  File "chia\consensus\blockchain.py", line 673, in block_record
KeyError: <bytes32: d780d22c7a87c9e01d98b49a0910f6701c3b95015741316b3fda042e5d7b81d2>
2022-04-03T01:04:27.108 full_node full_node_server        : WARNING  Banning 185.45.33.85 for 10 seconds
2022-04-03T01:04:27.110 full_node full_node_server        : ERROR    Exception <bytes32: d780d22c7a87c9e01d98b49a0910f6701c3b95015741316b3fda042e5d7b81d2>, exception Stack: Traceback (most recent call last):
  File "chia\server\server.py", line 466, in start_client
  File "chia\server\server.py", line 366, in connection_added
  File "chia\server\node_discovery.py", line 241, in on_connect_callback
  File "chia\full_node\full_node.py", line 667, in on_connect
  File "chia\full_node\full_node.py", line 633, in synced
  File "chia\consensus\blockchain.py", line 172, in get_peak
  File "chia\consensus\blockchain.py", line 680, in height_to_block_record
  File "chia\consensus\blockchain.py", line 673, in block_record
KeyError: <bytes32: d780d22c7a87c9e01d98b49a0910f6701c3b95015741316b3fda042e5d7b81d2>

2022-04-03T01:04:27.112 full_node asyncio                 : ERROR    Task exception was never retrieved
future: <Task finished name='Task-72424' coro=<RpcServer._state_changed() done, defined at chia\rpc\rpc_server.py:49> exception=KeyError(<bytes32: d780d22c7a87c9e01d98b49a0910f6701c3b95015741316b3fda042e5d7b81d2>)>
Traceback (most recent call last):
  File "chia\rpc\rpc_server.py", line 52, in _state_changed
  File "chia\rpc\full_node_rpc_api.py", line 71, in _state_changed
  File "chia\rpc\full_node_rpc_api.py", line 130, in get_blockchain_state
  File "chia\consensus\blockchain.py", line 172, in get_peak
  File "chia\consensus\blockchain.py", line 680, in height_to_block_record
  File "chia\consensus\blockchain.py", line 673, in block_record
KeyError: <bytes32: d780d22c7a87c9e01d98b49a0910f6701c3b95015741316b3fda042e5d7b81d2>

**Comment by ydhuang1989** [comment]
> Does this happen after you do a full reboot? Do you have any logs that you can provide as well?

for sure i did, her is de debug ,anyway thank u

**Comment by emlowe** [comment]
`KeyError: <bytes32: d780d22c7a87c9e01d98b49a0910f6701c3b95015741316b3fda042e5d7b81d2>` indicates that your node DB has incorrect data .

You will need to resync the node DB
