### ISSUE TITLE
[Bug] Harvester crash

### ISSUE THREAD

**Issue by bhorvitz** [Chia-Network/chia-blockchain#11008]
### What happened?

chia_harvester process dies on remote harvester with websocket exception.

This has been observed twice since 1.3.1

```
$ ps -efa | grep chia
chia  3827282       1  0 Apr01 ?        00:00:09 chia_daemon
chia  3827287 3827282  8 Apr01 ?        01:53:51 [chia_harvester] <defunct>
```

### Version

1.3.2

### What platform are you using?

Linux

### What ui mode are you using?

CLI

### Relevant log output

```shell
2022-04-02T16:19:53.643 harvester chia.harvester.harvester: INFO     19 plots were eligible for farming 19b1b02412... Found 0 proofs. Time: 0.26003 s. Total 10556 plots
2022-04-02T16:20:02.178 harvester chia.harvester.harvester: INFO     15 plots were eligible for farming 19b1b02412... Found 0 proofs. Time: 0.28324 s. Total 10556 plots
2022-04-02T16:20:10.868 daemon chia.daemon.server         : INFO     Websocket exception. Closing websocket with chia_harvester code = 1006 (connection closed abnormally [internal]), no reason Traceback (most recent call last):
  File "/home/chia/venv/lib/python3.9/site-packages/websockets/protocol.py", line 827, in transfer_data
    message = await self.read_message()
  File "/home/chia/venv/lib/python3.9/site-packages/websockets/protocol.py", line 895, in read_message
    frame = await self.read_data_frame(max_size=self.max_size)
  File "/home/chia/venv/lib/python3.9/site-packages/websockets/protocol.py", line 971, in read_data_frame
    frame = await self.read_frame(max_size)
  File "/home/chia/venv/lib/python3.9/site-packages/websockets/protocol.py", line 1047, in read_frame
    frame = await Frame.read(
  File "/home/chia/venv/lib/python3.9/site-packages/websockets/framing.py", line 105, in read
    data = await reader(2)
  File "/usr/lib/python3.9/asyncio/streams.py", line 721, in readexactly
    raise exceptions.IncompleteReadError(incomplete, n)
asyncio.exceptions.IncompleteReadError: 0 bytes read on a total of 2 expected bytes

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/chia/venv/lib/python3.9/site-packages/chia/daemon/server.py", line 216, in safe_handle
    async for message in websocket:
  File "/home/chia/venv/lib/python3.9/site-packages/websockets/protocol.py", line 439, in __aiter__
    yield await self.recv()
  File "/home/chia/venv/lib/python3.9/site-packages/websockets/protocol.py", line 509, in recv
    await self.ensure_open()
  File "/home/chia/venv/lib/python3.9/site-packages/websockets/protocol.py", line 803, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedError: code = 1006 (connection closed abnormally [internal]), no reason
```

**Comment by emlowe** [comment]
The harvester is likely crashing - it's recommended that you run `chia plots check` and see if there is a bad plot causing the crash. 
If you identify a bad plot please let us know before deleting it, so we can arrange a way to analyze it.
Also, worthwhile to see if you have any core dumps or any interesting logging in syslog about this.

**Comment by xdustinface** [comment]
@bhorvitz Can you check the log on the farmer side around the same time? This might be an issue related to plot reporting from the harvester to the farmer being not scalable at the moment and if it is, #9695 would fix it.

**Comment by bhorvitz** [comment]
@xdustinface unfortunately nothing interesting at all.. normal node stuff.

**Comment by bhorvitz** [comment]
Goodish news on this front.  It happened again just now but this time I was able to catch a core dump associated.  Looks hardware related, so I'd say probably close the bug unless there's something more you'd like.

Received the following:
```
Apr 07 10:37:47 ch-h1 kernel: Code: 89 de e8 4f 9e ff ff 48 85 c0 74 da 83 38 04 75 d5 48 8b 50 20 48 8b 70 08 b9 13 00 00 00 48 8b bd 48 ff ff ff e8 bc a0 ff ff <48> 83 78 10 00 49 89 c7 74 b2 31 f6 4c 8d b5 68 ff ff ff 4c 8d ad
Apr 07 10:37:47 ch-h1 kernel: systemd-coredum[454001]: segfault at 10 ip 000056166eea59d4 sp 00007ffc9ae334f0 error 4 cpu 4 in systemd-coredump[56166ee9f000+8000]
Apr 07 10:37:46 ch-h1 kernel: traps: chia_harvester[1654] general protection fault ip:56276c034504 sp:7ffd6d519830 error:0 in python3.9[56276bf62000+202000]
```

**Comment by wallentx** [comment]
The crash looks to be within python, rather than ChiaPOS. Can you make sure that you are running python 3.9.11 or 3.9.12?

**Comment by bhorvitz** [comment]
I'm actually on 3.9.6.

**Comment by bhorvitz** [comment]
This was probably hardware.  Not reproducible.
