### ISSUE TITLE
Exception in logs when trying to take an offer (GUI)

### ISSUE THREAD

**Issue by jorgetu** [Chia-Network/chia-blockchain#11033]
### What happened?

I'm using chia wallet.
My wallet is synced and I try to accept an offer and I can't do it because I receive this error
Request 7338e08e4e8ed9b4be50ce53f916547c035797652e4ce42859feaa172c34d64e failed: {"error":"","success":false}

the information in the debug.log file is:

2022-04-04T16:47:51.713 wallet chia.wallet.wallet_node    : WARNING  Peer None did not respond in time.
2022-04-04T16:47:51.717 wallet chia.wallet.wallet_node    : WARNING  Peer None did not respond in time.
2022-04-04T16:48:16.737 wallet chia.wallet.trade_manager  : ERROR    Error with creating trade offer: <class 'AssertionError'>Traceback (most recent call last):
  File "chia/wallet/trade_manager.py", line 336, in _create_offer_for_ids
  File "chia/wallet/wallet.py", line 451, in generate_signed_transaction
  File "chia/wallet/wallet.py", line 344, in _generate_unsigned_transaction
AssertionError

2022-04-04T16:48:16.738 wallet chia.rpc.rpc_server        : WARNING  Error while handling message: Traceback (most recent call last):
  File "chia/rpc/rpc_server.py", line 215, in safe_handle
  File "chia/rpc/rpc_server.py", line 206, in ws_api
  File "chia/rpc/wallet_rpc_api.py", line 944, in take_offer
ValueError

### Version

1.3.2

### What platform are you using?

macOS

### What ui mode are you using?

GUI

### Relevant log output

```shell
2022-04-04T16:47:51.713 wallet chia.wallet.wallet_node    : WARNING  Peer None did not respond in time.
2022-04-04T16:47:51.717 wallet chia.wallet.wallet_node    : WARNING  Peer None did not respond in time.
2022-04-04T16:48:16.737 wallet chia.wallet.trade_manager  : ERROR    Error with creating trade offer: <class 'AssertionError'>Traceback (most recent call last):
  File "chia/wallet/trade_manager.py", line 336, in _create_offer_for_ids
  File "chia/wallet/wallet.py", line 451, in generate_signed_transaction
  File "chia/wallet/wallet.py", line 344, in _generate_unsigned_transaction
AssertionError

2022-04-04T16:48:16.738 wallet chia.rpc.rpc_server        : WARNING  Error while handling message: Traceback (most recent call last):
  File "chia/rpc/rpc_server.py", line 215, in safe_handle
  File "chia/rpc/rpc_server.py", line 206, in ws_api
  File "chia/rpc/wallet_rpc_api.py", line 944, in take_offer
ValueError
```

**Comment by wallentx** [comment]
Do you get this same behavior in 1.3.3?
