### ISSUE TITLE
chia reports an error when claiming a reward[Bug] 

### ISSUE THREAD

**Issue by chiavivi** [Chia-Network/chia-blockchain#11071]
### What happened?

Chia reported an error in claiming the reward, and the version was upgraded to the latest, but the reward still cannot be claimed. Please provide a solution.

### Version

1.3

### What platform are you using?

Windows

### What ui mode are you using?

GUI

**Comment by chiavivi** [comment]
chia reports an error when claiming a reward[Bug]

**Comment by chiavivi** [comment]
图片

**Comment by emlowe** [comment]
It would be helpful if you included the actual error and the relavent log information. Without this information, it's difficult to understand what went wrong

Also, it's possible the claim goes through anyway regardless of the error

**Comment by chiavivi** [comment]
2022-04-06T18:49:59.959 wallet chia.rpc.rpc_server&nbsp; &nbsp; &nbsp; &nbsp; : WARNING&nbsp; Error while handling message: Traceback (most recent call last):
&nbsp; File "chia\rpc\rpc_server.py", line 215, in safe_handle
&nbsp; File "chia\rpc\rpc_server.py", line 206, in ws_api
&nbsp; File "chia\rpc\wallet_rpc_api.py", line 1386, in pw_absorb_rewards
&nbsp; File "chia\pools\pool_wallet.py", line 784, in claim_pool_rewards
ValueError: Cannot claim due to unconfirmed transaction. If this is stuck, delete the unconfirmed transaction.


2022-04-07T08:27:30.129 wallet chia.rpc.rpc_server&nbsp; &nbsp; &nbsp; &nbsp; : WARNING&nbsp; Error while handling message: Traceback (most recent call last):
&nbsp; File "chia\rpc\rpc_server.py", line 215, in safe_handle
&nbsp; File "chia\rpc\rpc_server.py", line 206, in ws_api
&nbsp; File "chia\rpc\wallet_rpc_api.py", line 1386, in pw_absorb_rewards
&nbsp; File "chia\pools\pool_wallet.py", line 784, in claim_pool_rewards
ValueError: Cannot claim due to unconfirmed transaction. If this is stuck, delete the unconfirmed transaction.







------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Chia-Network/chia-blockchain"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年4月7日(星期四) 上午6:45
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Chia-Network/chia-blockchain] chia reports an error when claiming a reward[Bug]  (Issue #11071)





 
It would be helpful if you included the actual error and the relavent log information. Without this information, it's difficult to understand what went wrong
 
Also, it's possible the claim goes through anyway regardless of the error

**Comment by chiavivi** [comment]
2022-04-07T08:27:30.129 wallet chia.rpc.rpc_server        : WARNING  Error while handling message: Traceback (most recent call last):
  File "chia\rpc\rpc_server.py", line 215, in safe_handle
  File "chia\rpc\rpc_server.py", line 206, in ws_api
  File "chia\rpc\wallet_rpc_api.py", line 1386, in pw_absorb_rewards
  File "chia\pools\pool_wallet.py", line 784, in claim_pool_rewards
ValueError: Cannot claim due to unconfirmed transaction. If this is stuck, delete the unconfirmed transaction.

2022-04-07T08:38:14.281 wallet chia.wallet.wallet_node    : WARNING  SpendBundle has been rejected by the FullNode. {'error': 'DOUBLE_SPEND', 'status': 3, 'txid': '0xc9f46d50ad50d80af502971302d7fd2aa62d33d1087bd2b067e138017fa51d1f'}
2022-04-07T08:38:14.530 wallet chia.wallet.wallet_node    : WARNING  SpendBundle has been rejected by the FullNode. {'error': 'DOUBLE_SPEND', 'status': 3, 'txid': '0xc9f46d50ad50d80af502971302d7fd2aa62d33d1087bd2b067e138017fa51d1f'}
2022-04-07T08:38:38.665 wallet chia.rpc.rpc_server        : WARNING  Error while handling message: Traceback (most recent call last):
  File "chia\rpc\rpc_server.py", line 215, in safe_handle
  File "chia\rpc\rpc_server.py", line 206, in ws_api
  File "chia\rpc\wallet_rpc_api.py", line 1386, in pw_absorb_rewards
  File "chia\pools\pool_wallet.py", line 784, in claim_pool_rewards
ValueError: Cannot claim due to unconfirmed transaction. If this is stuck, delete the unconfirmed transaction.

2022-04-07T08:43:05.890 wallet chia.wallet.wallet_node    : WARNING  SpendBundle has been rejected by the FullNode. {'error': 'DOUBLE_SPEND', 'status': 3, 'txid': '0x88d6b8be37d07219632b110ae234c28c1318a80969625e501c9a6fd44e3ebc7e'}
2022-04-07T08:43:06.135 wallet chia.wallet.wallet_node    : WARNING  SpendBundle has been rejected by the FullNode. {'error': 'DOUBLE_SPEND', 'status': 3, 'txid': '0x88d6b8be37d07219632b110ae234c28c1318a80969625e501c9a6fd44e3ebc7e'}

**Comment by emlowe** [comment]
Are you connected to a local node or to multiple remote nodes?

**Comment by wallentx** [comment]
This might relate to https://github.com/Chia-Network/chia-blockchain/issues/10640

**Comment by chiavivi** [comment]
The local connection used. How to deal with this?

**Comment by jhwhtgg** [comment]
我的也是这样 从1.3.1到目前为止还是没能提取成功

**Comment by chiavivi** [comment]
不知道官方什么时候可以修复，1.3.3的版本，问题太多了。加入矿池也没有反应，系统已经瘫痪了。爆块也有问题，矿池总算力下降了，反而没有以前爆得多了。

**Comment by emlowe** [comment]
In order to remove `Cannot claim due to unconfirmed transaction. If this is stuck, delete the unconfirmed transaction` - you need to use delete unconfirmed transactions- this is in the GUI under the "3 dots" menu in the wallet.

We are working on some of the double spend errors reports. Note sometimes you get this error, but the claim transaction still completes, but this would happen within some minutes. We hope the next release resolves a number of these issues 
see PR: https://github.com/Chia-Network/chia-blockchain/pull/11038

**Comment by chiavivi** [comment]
什么时候可以 出新版本，还是领不了奖励。反馈了这么久了。

**Comment by FVierra27** [comment]
> In order to remove `Cannot claim due to unconfirmed transaction. If this is stuck, delete the unconfirmed transaction` - you need to use delete unconfirmed transactions- this is in the GUI under the "3 dots" menu in the wallet.
> 
> We are working on some of the double spend errors reports. Note sometimes you get this error, but the claim transaction still completes, but this would happen within some minutes. We hope the next release resolves a number of these issues see PR: #11038

How do we delete the unconfirmed transaction using CLI?

**Comment by chiavivi** [comment]
删除了还是不能领取，日志如下：
9:58:46.023 wallet chia.wallet.wallet_node    : WARNING  SpendBundle has been rejected by the FullNode. {'error': 'DOUBLE_SPEND', 'status': 3, 'txid': '0x0266512f7900c571956827aa0b622486bbf06dd141c01ed373e2f6f52d4e9f26'}
2022-04-19T09:58:46.263 wallet chia.wallet.wallet_node    : WARNING  SpendBundle has been rejected by the FullNode. {'error': 'DOUBLE_SPEND', 'status': 3, 'txid': '0x0266512f7900c571956827aa0b622486bbf06dd141c01ed373e2f6f52d4e9f26'}

**Comment by emlowe** [comment]
Please try again with v 1.3.4 as we did fix several bugs in the self-claim flow.

To delete unconfirmed transactions with CLI one uses - `chia wallet delete_unconfirmed_transactions` , I recommend add in the wallet id and run the command both for the standard wallet and the pooling wallet

**Comment by chiavivi** [comment]
已经升级到v 1.3.4   还是不行，而且还出现了，收割机的田数据不准确  日志如下：Traceback (most recent call last):
  File "chia\daemon\client.py", line 32, in listener
  File "websockets\protocol.py", line 509, in recv
  File "websockets\protocol.py", line 803, in ensure_open
websockets.exceptions.ConnectionClosedError: code = 1006 (connection closed abnormally [internal]), no reason
2022-04-20T09:14:11.177 full_node chia.rpc.rpc_server     : WARNING  Cannot connect to daemon at ws://localhost:55400
2022-04-20T09:14:11.208 farmer chia.rpc.rpc_server        : WARNING  Cannot connect to daemon at ws://localhost:55400
2022-04-20T09:14:11.224 wallet chia.rpc.rpc_server        : WARNING  Cannot connect to daemon at ws://localhost:55400
2022-04-20T09:15:05.058 wallet chia.wallet.wallet_node    : WARNING  SpendBundle has been rejected by the FullNode. {'error': 'DOUBLE_SPEND', 'status': 3, 'txid': '0x054fc031d5319dc0f1b1eddc0e91a099e9845e2b0d6e671dc813a40fa26b6bf5'}
2022-04-20T09:15:05.062 wallet chia.wallet.wallet_node    : WARNING  SpendBundle has been rejected by the FullNode. {'error': 'DOUBLE_SPEND', 'status': 3, 'txid': '0x054fc031d5319dc0f1b1eddc0e91a099e9845e2b0d6e671dc813a40fa26b6bf5'}
2022-04-20T09:25:52.668 wallet chia.wallet.wallet_node    : WARNING  SpendBundle has been rejected by the FullNode. {'error': 'MEMPOOL_NOT_INITIALIZED',
 'status': 3,
 'txid': '0x054fc031d5319dc0f1b1eddc0e91a099e9845e2b0d6e671dc813a40fa26b6bf5'}
2022-04-20T09:27:35.566 wallet chia.rpc.rpc_server        : WARNING  Error while handling message: Traceback (most recent call last):
  File "chia\rpc\rpc_server.py", line 225, in safe_handle
  File "chia\rpc\rpc_server.py", line 216, in ws_api
  File "chia\rpc\wallet_rpc_api.py", line 1418, in pw_absorb_rewards
  File "chia\pools\pool_wallet.py", line 788, in claim_pool_rewards
ValueError: Cannot claim due to unconfirmed transaction. If this is stuck, delete the unconfirmed transaction.

2022-04-20T09:28:30.172 wallet chia.wallet.wallet_node    : WARNING  SpendBundle has been rejected by the FullNode. {'error': 'DOUBLE_SPEND', 'status': 3, 'txid': '0x71209b30526699c60662dd015718566c5b2ffc7e27edd54a08cf05963a1bfa4b'}
2022-04-20T09:28:30.175 wallet chia.wallet.wallet_node    : WARNING  SpendBundle has been rejected by the FullNode. {'error': 'DOUBLE_SPEND', 'status': 3, 'txid': '0x71209b30526699c60662dd015718566c5b2ffc7e27edd54a08cf05963a1bfa4b'}

**Comment by catxch** [comment]
> Please try again with v 1.3.4 as we did fix several bugs in the self-claim flow.
> 
> To delete unconfirmed transactions with CLI one uses - `chia wallet delete_unconfirmed_transactions` , I recommend add in the wallet id and run the command both for the standard wallet and the pooling wallet

I got this problem from version 1.3.0 till 1.3.4 and still not able to claim Claim Rewards till now please help me
