### ISSUE TITLE
[Bug] White screening of the GUI window for mac (intel) occurs after large tx

### ISSUE THREAD

**Issue by pmaslana** [Chia-Network/chia-blockchain#11108]
### What happened?

When testing a very large transaction with a large fee (1,000,000 TXCH with a fee of 100,000 TXCH), the chia-blockchian GUI screen turns white. I have replicated this three separate times. 

I have also tested the transaction by sending 1 TXCH with 100,000 TXCH for the fee and 1,000,000 TXCH with a fee < 1 TXCH. These tests did not result in any white screening of the application.

### Version

1.3.2.dev122

### What platform are you using?

macOS

### What ui mode are you using?

GUI

### Relevant log output

```shell
2022-04-08T16:35:16.411 daemon __main__                   : ERROR    Unexpected exception trying to send to websocket: Connection lost Traceback (most recent call last):
  File "chia/daemon/server.py", line 239, in incoming_connection
  File "aiohttp/web_ws.py", line 300, in send_str
  File "aiohttp/http_websocket.py", line 687, in send
  File "aiohttp/http_websocket.py", line 656, in _send_frame
  File "aiohttp/base_protocol.py", line 80, in _drain_helper
ConnectionResetError: Connection lost
```

**Comment by emlowe** [comment]
This is caused by javascript and bignum related issues (see https://github.com/Chia-Network/chia-blockchain-gui/pull/642)
