### ISSUE TITLE
[Bug] Error trying to create a Plot NFT

### ISSUE THREAD

**Issue by jorgetu** [Chia-Network/chia-blockchain#11125]
### What happened?

Some weeks ago I tried to create a new Plot NFT. It took a lot of time and I deleted unconfirmed transactions and since then I am receiving this error every 9 seconds when I am in the Pool tab of the Chia GUI.
debug.log:
2022-04-11T09:49:00.428 wallet chia.rpc.rpc_server        : WARNING  Error while handling message: Traceback (most recent call last):
  File "chia/rpc/rpc_server.py", line 215, in safe_handle
  File "chia/rpc/rpc_server.py", line 206, in ws_api
  File "chia/rpc/wallet_rpc_api.py", line 667, in get_transaction
ValueError: Transaction 0x462df0b43dfc615821822cdaca588c3d103cde5da50e015883d4e24f4e577d4f not found

- I reinstalled chia client
- I deleted wallet db

but the error persists.
After it I have created another Plot NFT without any problem.

### Version

1.3.3

### What platform are you using?

macOS

### What ui mode are you using?

GUI

### Relevant log output

```shell
2022-04-11T09:49:00.428 wallet chia.rpc.rpc_server        : WARNING  Error while handling message: Traceback (most recent call last):
  File "chia/rpc/rpc_server.py", line 215, in safe_handle
  File "chia/rpc/rpc_server.py", line 206, in ws_api
  File "chia/rpc/wallet_rpc_api.py", line 667, in get_transaction
ValueError: Transaction 0x462df0b43dfc615821822cdaca588c3d103cde5da50e015883d4e24f4e577d4f not found

2022-04-11T09:49:09.022 wallet chia.rpc.rpc_server        : WARNING  Error while handling message: Traceback (most recent call last):
  File "chia/rpc/rpc_server.py", line 215, in safe_handle
  File "chia/rpc/rpc_server.py", line 206, in ws_api
  File "chia/rpc/wallet_rpc_api.py", line 667, in get_transaction
ValueError: Transaction 0x462df0b43dfc615821822cdaca588c3d103cde5da50e015883d4e24f4e577d4f not found

2022-04-11T09:49:17.611 wallet chia.rpc.rpc_server        : WARNING  Error while handling message: Traceback (most recent call last):
  File "chia/rpc/rpc_server.py", line 215, in safe_handle
  File "chia/rpc/rpc_server.py", line 206, in ws_api
  File "chia/rpc/wallet_rpc_api.py", line 667, in get_transaction
ValueError: Transaction 0x462df0b43dfc615821822cdaca588c3d103cde5da50e015883d4e24f4e577d4f not found
```

**Comment by danarbraz** [comment]
I've seen this behavior for months. Reported via https://github.com/Chia-Network/chia-blockchain/issues/9970

With the 1.3.4 release, I see this behavior... Navigating to the "Plotting" screen results in:
1. UI unresponsive for 20-30
2. Repeated "connecting to daemon" messages in the UI
3. UI eventually responds enough to change screens
4. Connection status on "Full node" screen displays "Error"
5. Repeated "connecting to daemon" messages in the UI

**Comment by jorgetu** [comment]
I am still receiving same error after upgrading to 1.3.4 version
2022-04-22T14:00:57.003 wallet chia.rpc.rpc_server        : WARNING  Error while handling message: Traceback (most recent call last):
  File "chia/rpc/rpc_server.py", line 225, in safe_handle
  File "chia/rpc/rpc_server.py", line 216, in ws_api
  File "chia/rpc/wallet_rpc_api.py", line 673, in get_transaction
ValueError: Transaction 0x462df0b43dfc615821822cdaca588c3d103cde5da50e015883d4e24f4e577d4f not found

**Comment by jorgetu** [comment]
I am still receiving same error after upgrading to 1.3.5 version

**Comment by emlowe** [comment]
Closing old issue, very likely resolved at some point
