### ISSUE TITLE
[Bug] CHIA FULL NODE does not connect. After upgrade 1.3.3

### ISSUE THREAD

**Issue by DonMarmueta** [Chia-Network/chia-blockchain#11168]
### What happened?

CHIA FULL NODE does not connect.

I updated to version 1.3.3. after updating the wallet opens but the farmer does not. full node screen keeps loading and does not connect

### Version

1.3.3

### What platform are you using?

Windows

### What ui mode are you using?

GUI

**Comment by stefan-lange** [comment]
you could check your windows firewall: new version of chia = new exe = new permissions required

**Comment by DonMarmueta** [comment]
I've been waiting more than 20 hours.
I already allowed it in the firewall.
full node screen is loading.

Wallet is already loaded and sinc. . . But cultivation is not yet.
![image](https://user-images.githubusercontent.com/89231240/163392557-7bf05651-de5e-4653-ba98-e1f038caca71.png)

**Comment by DonMarmueta** [comment]
> how long have you waited?
I've been waiting more than 20 hours.
I already allowed it in the firewall.
full node screen is loading.

Wallet is already loaded and sinc. . . But cultivation is not yet.

**Comment by DonMarmueta** [comment]
> you could check your windows firewall: new version of chia = new exe = new permissions required

I already allowed it in the firewall.
full node screen is loading.

Wallet is already loaded and sinc. . . But cultivation is not yet.

**Comment by DonMarmueta** [comment]
![image](https://user-images.githubusercontent.com/89231240/163440281-7543d008-8caf-4152-bcfd-d2c2153bf602.png)

**Comment by DonMarmueta** [comment]
I found that python 3.10 has some bugs, so I went back to 3.9.14...
Now it's opening the farmer screen, but it still doesn't connect.
![image](https://user-images.githubusercontent.com/89231240/163454821-cc4e4267-5cf6-4e46-b082-6bf92fd69347.png)

**Comment by wallentx** [comment]
Did you install this from src, or install from the 1.3.3 .exe? If you used the .exe, it would have installed chia with an included python 3.9.11 which is used independent of any python installed on your system. Are you able to share the log output when your full node is connecting?

**Comment by DonMarmueta** [comment]
> Did you install this from src, or install from the 1.3.3 .exe? If you used the .exe, it would have installed chia with an included python 3.9.11 which is used independent of any python installed on your system. Are you able to share the log output when your full node is connecting?

I used .exe, Tanks for explanation for python... ...

022-04-14T19:51:39.061 wallet chia.wallet.wallet_state_manager: INFO     Coin Removed: {'coin': {'amount': 1,
          'parent_coin_info': '0xf29dd66d73b0c64169772617531fe4265987e6d699a2a91a9def163cde8a1919',
          'puzzle_hash': '0x7e231e75dc2bffdeba086d8db9fd3d098d5bcb0e0bca12ca797e2357cb7a3ddd'},
 'created_height': 612909,
 'spent_height': 1039880}
2022-04-14T19:51:39.211 harvester chia.plotting.util      : WARNING  Directory: Z:\Hubiopool does not exist.
2022-04-14T19:51:39.216 farmer farmer_server              : INFO     Cannot connect to host 127.0.0.1:8444 ssl:<ssl.SSLContext object at 0x000002A460355840> [O computador remoto recusou a conexão de rede]
2022-04-14T19:51:39.248 harvester chia.harvester.harvester: INFO     _plot_refresh_callback: event done, loaded 0, removed 0, processed 302, remaining 0, duration: 0.01 seconds, total plots: 302
2022-04-14T19:51:39.312 wallet wallet                     : INFO     Reconnecting to peer {'host': '127.0.0.1', 'port': 8444}
2022-04-14T19:51:39.371 wallet chia.pools.pool_wallet     : INFO     Already have state transition: 094f39d715381ddff54d87c418145c72389f56b2e9c47cb971f4308457c34b41
2022-04-14T19:51:41.359 wallet wallet_server              : INFO     Cannot connect to host 127.0.0.1:8444 ssl:<ssl.SSLContext object at 0x0000025F9C037740> [O computador remoto recusou a conexão de rede]
2022-04-14T19:51:42.207 farmer farmer                     : INFO     Reconnecting to peer {'host': '127.0.0.1', 'port': 8444}
2022-04-14T19:51:43.908 wallet chia.wallet.wallet_node    : INFO     Successfully subscribed and updated 218 coin ids
2022-04-14T19:51:43.910 wallet chia.wallet.wallet_node    : INFO     Sync (trusted: False) duration was: 98.50222706794739
2022-04-14T19:51:44.253 farmer farmer_server              : INFO     Cannot connect to host 127.0.0.1:8444 ssl:<ssl.SSLContext object at 0x000002A4603557C0> [O computador remoto recusou a conexão de rede]
2022-04-14T19:51:44.349 wallet wallet                     : INFO     Reconnecting to peer {'host': '127.0.0.1', 'port': 8444}
2022-04-14T19:51:46.393 wallet wallet_server              : INFO     Cannot connect to host 127.0.0.1:8444 ssl:<ssl.SSLContext object at 0x0000025F9E0D75C0> [O computador remoto recusou a conexão de rede]
2022-04-14T19:51:47.241 farmer farmer                     : INFO     Reconnecting to peer {'host': '127.0.0.1', 'port': 8444}
2022-04-14T19:51:49.283 farmer farmer_server              : INFO     Cannot connect to host 127.0.0.1:8444 ssl:<ssl.SSLContext object at 0x000002A460355940> [O computador remoto recusou a conexão de rede]
2022-04-14T19:51:49.395 wallet wallet                     : INFO     Reconnecting to peer {'host': '127.0.0.1', 'port': 8444}
2022-04-14T19:51:51.439 wallet wallet_server              : INFO     Cannot connect to host 127.0.0.1:8444 ssl:<ssl.SSLContext object at 0x0000025F91A5E140> [O computador remoto recusou a conexão de rede]
2022-04-14T19:51:52.287 farmer farmer                     : INFO     Reconnecting to peer {'host': '127.0.0.1', 'port': 8444}
2022-04-14T19:51:54.331 farmer farmer_server              : INFO     Cannot connect to host 127.0.0.1:8444 ssl:<ssl.SSLContext object at 0x000002A460355A40> [O computador remoto recusou a conexão de rede]
2022-04-14T19:51:54.441 wallet wallet                     : INFO     Reconnecting to peer {'host': '127.0.0.1', 'port': 8444}
2022-04-14T19:51:56.484 wallet wallet_server              : INFO     Cannot connect to host 127.0.0.1:8444 ssl:<ssl.SSLContext object at 0x0000025F91A5EF40> [O computador remoto recusou a conexão de rede]
2022-04-14T19:51:57.344 farmer farmer                     : INFO     Reconnecting to peer {'host': '127.0.0.1', 'port': 8444}

**Comment by DonMarmueta** [comment]
File "websockets\protocol.py", line 827, in transfer_data
  File "websockets\protocol.py", line 895, in read_message
  File "websockets\protocol.py", line 971, in read_data_frame
  File "websockets\protocol.py", line 1047, in read_frame
  File "websockets\framing.py", line 105, in read
  File "asyncio\streams.py", line 721, in readexactly
asyncio.exceptions.IncompleteReadError: 0 bytes read on a total of 2 expected bytes

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "Lib\site-packages\chia\daemon\server.py", line 216, in safe_handle
  File "websockets\protocol.py", line 439, in __aiter__
  File "websockets\protocol.py", line 509, in recv
  File "websockets\protocol.py", line 803, in ensure_open
websockets.exceptions.ConnectionClosedError: code = 1006 (connection closed abnormally [internal]), no reason

2022-04-14T19:54:15.760 wallet wallet_server              : INFO     Cannot connect to host 127.0.0.1:8444 ssl:<ssl.SSLContext object at 0x0000025FA1741140> [O computador remoto recusou a conexão de rede]
2022-04-14T19:54:16.324 daemon __main__                   : INFO     Register service {'service': 'wallet_ui'}
2022-04-14T19:54:16.325 daemon __main__                   : INFO     registered for service wallet_ui
2022-04-14T19:54:16.327 daemon __main__                   : INFO     {'success': True}
2022-04-14T19:54:17.406 farmer farmer                     : INFO     Reconnecting to peer {'host': '127.0.0.1', 'port': 8444}
2022-04-14T19:54:17.736 full_node chia.full_node.full_node: INFO     Default port field not found in config.
2022-04-14T19:54:17.739 full_node full_node               : ERROR    full_node: already running
2022-04-14T19:54:18.756 wallet wallet                     : INFO     Reconnecting to peer {'host': '127.0.0.1', 'port': 8444}
2022-04-14T19:54:19.455 farmer farmer_server              : INFO     Cannot connect to host 127.0.0.1:8444 ssl:<ssl.SSLContext object at 0x000002A46045D740> [O computador remoto recusou a conexão de rede]
2022-04-14T19:54:20.808 wallet wallet_server              : INFO     Cannot connect to host 127.0.0.1:8444 ssl:<ssl.SSLContext object at 0x0000025FA17411C0> [O computador remoto recusou a conexão de rede]
2022-04-14T19:54:22.446 farmer farmer                     : INFO     Reconnecting to peer {'host': '127.0.0.1', 'port': 8444}

**Comment by DonMarmueta** [comment]
Thank you guys,
After several tries, I noticed that the .db was still in V1. so i went into chi-database and downloaded new volume v2. I deleted the old one. and it's connected... it hasn't synced yet, but I'm almost done syncing! everything seem
![image](https://user-images.githubusercontent.com/89231240/163582898-5f5e2c7a-49e8-4342-86c9-2d9039f79990.png)
s ok
