### ISSUE TITLE
[Bug] chia wallet service can become stuck

### ISSUE THREAD

**Issue by wallentx** [Chia-Network/chia-blockchain#11175]
### What happened?

![2022-07-17_03-35](https://user-images.githubusercontent.com/8990544/179390605-e10df08a-4b7a-48e7-a4fc-f3a7ab7d0fd9.png)

If you
• Have multiple keys
• Are in the middle of syncing a big wallet
• Execute a chia show wallet without specifying the fingerprint of the wallet that is currently syncing
it throws a `No keys loaded. Run 'chia keys generate' or import a key`
with error log:

```
ERROR    Task exception was never retrieved
future: <Task finished name='Task-4524' coro=<ClientWebSocketResponse.send_str() done, defined at /path/to/chia-blockchain/venv/lib/python3.9/site-packages/aiohttp/client_ws.py:147> exception=ConnectionResetError('Cannot write to closing transport')>
Traceback (most recent call last):
  File "/path/to/chia-blockchain/venv/lib/python3.9/site-packages/aiohttp/client_ws.py", line 150, in send_str
    await self._writer.send(data, binary=False, compress=compress)
  File "/path/to/chia-blockchain/venv/lib/python3.9/site-packages/aiohttp/http_websocket.py", line 687, in send
    await self._send_frame(message, WSMsgType.TEXT, compress)
  File "/path/to/chia-blockchain/venv/lib/python3.9/site-packages/aiohttp/http_websocket.py", line 598, in _send_frame
    raise ConnectionResetError("Cannot write to closing transport")
ConnectionResetError: Cannot write to closing transport
```

and it just stays broken
i can only chia wallet show -f to the same wallet i'm already synced to
if i pick a different fingerprint, i get a different error
`chia wallet show -f 233666666`

`Login failed: {'error': "'NoneType' object is not subscriptable", 'success': False}`

and wallet debug spits out

```
2022-04-14T01:52:21.714 wallet chia.rpc.util              : WARNING  Error while handling message: Traceback (most recent call last):
  File "/path/to/chia-blockchain/chia/rpc/util.py", line 16, in inner
    res_object = await f(request_data)
  File "/path/to/chia-blockchain/chia/rpc/wallet_rpc_api.py", line 189, in log_in
    started = await self.service._start(fingerprint)
  File "/path/to/chia-blockchain/chia/wallet/wallet_node.py", line 189, in _start
    private_key = await self.get_key_for_fingerprint(fingerprint)
  File "/path/to/chia-blockchain/chia/wallet/wallet_node.py", line 168, in get_key_for_fingerprint
    key = await keychain_proxy.get_key_for_fingerprint(fingerprint)
  File "/path/to/chia-blockchain/chia/daemon/keychain_proxy.py", line 270, in get_key_for_fingerprint
    response, success = await self.get_response_for_request(
  File "/path/to/chia-blockchain/chia/daemon/keychain_proxy.py", line 93, in get_response_for_request
    success = response["data"].get("success] False)
TypeError: 'NoneType' object is not subscriptable
```

### Version

1.3.2.dev156

### What platform are you using?

Linux

### What ui mode are you using?

CLI

**Comment by xulifan** [comment]
still no updates?

**Comment by altendky** [comment]
I don't have a fix around this, but for the sake of cross linking this does relate to the type hinting issues pointed out in https://github.com/Chia-Network/chia-blockchain/pull/12461.

**Comment by mcybz** [comment]
I'm getting this issue too on 1.4.0. How do I resolve... upgrade?

**Comment by mcybz** [comment]
Can confirm working now in 1.5.
