### ISSUE TITLE
cannot claim Claim Rewards until now.[Bug] 

### ISSUE THREAD

**Issue by catxch** [Chia-Network/chia-blockchain#11230]
### What happened?

I'm still having trouble with Claim Rewards.
From version 1.3.0 until now, 1.3.4 cannot claim Claim Rewards until now.

### Version

1.3.4

### What platform are you using?

Windows

### What ui mode are you using?

GUI

### Relevant log output

```shell
2022-04-20T09:57:17.911 wallet chia.wallet.wallet_node    : WARNING  SpendBundle has been rejected by the FullNode. {'error': 'DOUBLE_SPEND', 'status': 3, 'txid': '0x97ffc8db7395efb4fb334f95ff7070ccf83a58f0243c16db327a12266a388387'}
2022-04-20T09:57:17.917 wallet chia.wallet.wallet_node    : WARNING  SpendBundle has been rejected by the FullNode. {'error': 'DOUBLE_SPEND', 'status': 3, 'txid': '0x97ffc8db7395efb4fb334f95ff7070ccf83a58f0243c16db327a12266a388387'}
2022-04-20T10:10:59.645 wallet chia.wallet.wallet_node    : WARNING  SpendBundle has been rejected by the FullNode. {'error': 'MEMPOOL_NOT_INITIALIZED',
 'status': 3,
 'txid': '0x97ffc8db7395efb4fb334f95ff7070ccf83a58f0243c16db327a12266a388387'}
2022-04-20T10:18:01.044 wallet chia.wallet.wallet_node    : WARNING  SpendBundle has been rejected by the FullNode. {'error': 'DOUBLE_SPEND', 'status': 3, 'txid': '0x3bff8035471e0cb84aa876c90b4bb0ba4100178ca863d4036bb6e16ca906b885'}
2022-04-20T10:18:01.050 wallet chia.wallet.wallet_node    : WARNING  SpendBundle has been rejected by the FullNode. {'error': 'DOUBLE_SPEND', 'status': 3, 'txid': '0x3bff8035471e0cb84aa876c90b4bb0ba4100178ca863d4036bb6e16ca906b885'}
```
2022-04-20T11:17:12.148 wallet chia.rpc.rpc_server        : WARNING  Error while handling message: Traceback (most recent call last):
  File "chia\rpc\rpc_server.py", line 225, in safe_handle
  File "chia\rpc\rpc_server.py", line 216, in ws_api
  File "chia\rpc\wallet_rpc_api.py", line 618, in get_wallet_balance
KeyError: 0

**Comment by catxch** [comment]
And it has a very strange way of displaying the values ​​in the wallet window. @wallentx 
[https://www.img.in.th/image/79PkA7](url)

**Comment by emlowe** [comment]
When the wallet is connected to multiple nodes, getting DOUBLE_SPEND can be normal as you send the same transaction to multiple nodes, so some of those nodes may see it already in the mempool as a double spend. So the claim transaction may go through just fine despite this error.

**Comment by catxch** [comment]
> When the wallet is connected to multiple nodes, getting DOUBLE_SPEND can be normal as you send the same transaction to multiple nodes, so some of those nodes may see it already in the mempool as a double spend. So the claim transaction may go through just fine despite this error.

But now I can't get the reward for a very long time. Is there any reason that can help me to fix it, how to do it? I think I have a problem with my wallet.

**Comment by catxch** [comment]
@emlowe  Do I have a way to contact you personally? I'm sure there's a problem with my wallet.

**Comment by emlowe** [comment]
I would recommend to delete or rename your wallet DB and resync your wallet. You can get more real-time support in keybase in the support channel.

**Comment by catxch** [comment]
As you suggested, let's remove db and resync until I succeed. I've already done it. Remove everything, reinstall chia 1.3.4, but this problem is the same. No matter how much mojo I wear,
![1650593325782](https://user-images.githubusercontent.com/103640664/164583334-e0dfe393-07a7-4388-bfd7-ee396d07aaf6.jpg)
![1650428340900](https://user-images.githubusercontent.com/103640664/164583421-40ac3c19-13a1-4b22-97da-9f7373b20bd3.jpg)
log
 'status': 3,
 'txid': '0x37e18ec3fb4f247c90272df5e0c454a87444c7c35c079efc62569b50897bb814'}
2022-04-19T11:11:43.674 wallet chia.wallet.wallet_node    : WARNING  SpendBundle has been rejected by the FullNode. {'error': 'ASSERT_ANNOUNCE_CONSUMED_FAILED',
 'status': 3,
 'txid': '0x37e18ec3fb4f247c90272df5e0c454a87444c7c35c079efc62569b50897bb814'}

2022-04-22T01:46:54.580 wallet chia.wallet.wallet_node    : WARNING  SpendBundle has been rejected by the FullNode. {'error': 'DOUBLE_SPEND', 'status': 3, 'txid': '0x918da07ac2720f993a2272686631fdf33c6dfb223570d183e8fecb9c44b9846b'}
2022-04-22T01:46:54.713 wallet chia.wallet.wallet_node    : WARNING  SpendBundle has been rejected by the FullNode. {'error': 'DOUBLE_SPEND', 'status': 3, 'txid': '0x918da07ac2720f993a2272686631fdf33c6dfb223570d183e8fecb9c44b9846b'}

2022-04-22T09:39:58.817 wallet chia.wallet.wallet_node    : WARNING  SpendBundle has been rejected by the FullNode. {'error': 'INVALID_FEE_TOO_CLOSE_TO_ZERO',
 'status': 3,
 'txid': '0xeaf25e88c97ac58e6a39c5d5a3594c20d3b6083a2ad305031caa7eb6ad38ce28'}
2022-04-22T09:39:58.822 wallet chia.wallet.wallet_node    : WARNING  SpendBundle has been rejected by the FullNode. {'error': 'INVALID_FEE_TOO_CLOSE_TO_ZERO',
 'status': 3,
 'txid': '0xeaf25e88c97ac58e6a39c5d5a3594c20d3b6083a2ad305031caa7eb6ad38ce28'}

This is a log error each time I press Confirm, there is a different error, but every time it is completely steady until I press delete the bank.
