### ISSUE TITLE
[Bug] upgrade to 1.3.4 sqlite3.OperationalError: unable to open database file

### ISSUE THREAD

**Issue by wehnhew** [Chia-Network/chia-blockchain#11252]
### What happened?

sqlite3.OperationalError: unable to open database file

### Version

1.3.4

### What platform are you using?

Windows

### What ui mode are you using?

GUI

### Relevant log output

```shell
2022-04-21T14:57:23.808 full_node chia.consensus.blockchain: ERROR    Error while adding block 14a3b9c1f83ac446841a4c7f7b692051222d892d8aeee4c769e98fe2047365a3 height 154, rolling back: Traceback (most recent call last):
  File "chia\consensus\blockchain.py", line 268, in receive_block
  File "chia\consensus\blockchain.py", line 406, in _reconsider_peak
  File "chia\full_node\coin_store.py", line 149, in new_block
  File "chia\full_node\coin_store.py", line 485, in _add_coin_records
  File "aiosqlite\core.py", line 210, in executemany
  File "aiosqlite\core.py", line 129, in _execute
  File "aiosqlite\core.py", line 102, in run
sqlite3.OperationalError: unable to open database file
 unable to open database file
2022-04-21T14:57:23.812 full_node chia.full_node.full_node: ERROR    sync from fork point failed err: unable to open database file
2022-04-21T14:57:23.813 full_node chia.full_node.full_node: INFO     long sync done
2022-04-21T14:57:23.814 full_node chia.full_node.full_node: INFO      Updated peak to height 153, weight 1078, hh ee018432a8da8c272e152650d055f25d5c22395f3f39b170c2cc189f7ce86eb0, forked at 152, rh: b40f64a2636f3d073693233d9e74108dff32a508562ad6a7231175adaf49b64d, total iters: 585484066, overflow: False, deficit: 2, difficulty: 7, sub slot iters: 134217728, Generator size: No tx, Generator ref list size: No tx
```

**Comment by allzima1** [comment]
Hey, that is just a normal issue with new version. Try to reinstall the previous version u had. 
If wouldn't work, you need to go into **appdata** and cut the database from there and paste it in another destination. Then if it works , take back the folder and replace. Good luck

**Comment by emlowe** [comment]
I would try a reboot first, sometimes after installing the new version there are old version processes still running and this van be one of the causes. So reboot, and launch the GUI again.

**Comment by wehnhew** [comment]
> Hey, that is just a normal issue with new version. Try to reinstall the previous version u had. If wouldn't work, you need to go into **appdata** and cut the database from there and paste it in another destination. Then if it works , take back the folder and replace. Good luck

Go back to version 1.3.3 is normal

**Comment by wehnhew** [comment]
> 我会先尝试重新启动，有时在安装新版本后，旧版本进程仍在运行，这就是原因之一。所以重新启动，然后再次启动 GUI。

restart the computer and the problem persists

**Comment by wehnhew** [comment]
> 



> > Hey, that is just a normal issue with new version. Try to reinstall the previous version u had. If wouldn't work, you need to go into **appdata** and cut the database from there and paste it in another destination. Then if it works , take back the folder and replace. Good luck
> 
> Go back to version 1.3.3 is normal,but version 1.3.4 is not normal

**Comment by allzima1** [comment]
> > Hey, that is just a normal issue with new version. Try to reinstall the previous version u had. If wouldn't work, you need to go into **appdata** and cut the database from there and paste it in another destination. Then if it works , take back the folder and replace. Good luck
> 
> Go back to version 1.3.3 is normal, but version 1.3.4 is not normal




If i were you, i wouldn't launch 1.3.3 becuase at some point i had a serious problem with that shitty version. it didn't recover my account by the 24 words. so run one older version.

**Comment by wehnhew** [comment]
> I would try a reboot first, sometimes after installing the new version there are old version processes still running and this van be one of the causes. So reboot, and launch the GUI again.

restart the computer and the problem persists

**Comment by wallentx** [comment]
Is your DB on your root volume?
If you are comfortable with doing this, can you attempt to shut down Chia, and open the db with a SQLite browser of your choosing?

**Comment by emlowe** [comment]
closing issue due to lack of response
