### ISSUE TITLE
[Bug]  farmer chia.farmer.farmer : WARNING  No pool specific difficulty has been set for 

### ISSUE THREAD

**Issue by LYW0723** [Chia-Network/chia-blockchain#11293]
### What happened?

Is there a problem with this log?

### Version

1.3.4

### What platform are you using?

Windows

### What ui mode are you using?

GUI

### Relevant log output

```shell
2022-04-24T15:54:37.387 farmer chia.farmer.farmer         : WARNING  No pool specific difficulty has been set for 60fe417732e54f1fdb87b9d41b8124e078311429f6dcb04ed6552f43dc87ef83, check communication with the pool, skipping this signage point, pool: https://chia.dpool.cc 
2022-04-24T15:54:45.940 farmer chia.farmer.farmer         : WARNING  No pool specific difficulty has been set for 60fe417732e54f1fdb87b9d41b8124e078311429f6dcb04ed6552f43dc87ef83, check communication with the pool, skipping this signage point, pool: https://chia.dpool.cc 
2022-04-24T15:54:54.648 farmer chia.farmer.farmer         : WARNING  No pool specific difficulty has been set for 60fe417732e54f1fdb87b9d41b8124e078311429f6dcb04ed6552f43dc87ef83, check communication with the pool, skipping this signage point, pool: https://chia.dpool.cc 
2022-04-24T15:55:06.002 farmer chia.farmer.farmer         : WARNING  No pool specific difficulty has been set for 60fe417732e54f1fdb87b9d41b8124e078311429f6dcb04ed6552f43dc87ef83, check communication with the pool, skipping this signage point, pool: https://chia.dpool.cc 
2022-04-24T15:55:06.467 farmer chia.farmer.farmer         : WARNING  No pool specific difficulty has been set for 60fe417732e54f1fdb87b9d41b8124e078311429f6dcb04ed6552f43dc87ef83, check communication with the pool, skipping this signage point, pool: https://chia.dpool.cc 
2022-04-24T15:55:13.294 farmer chia.farmer.farmer         : WARNING  No pool specific difficulty has been set for 60fe417732e54f1fdb87b9d41b8124e078311429f6dcb04ed6552f43dc87ef83, check communication with the pool, skipping this signage point, pool: https://chia.dpool.cc 
2022-04-24T15:55:23.345 farmer chia.farmer.farmer         : WARNING  No pool specific difficulty has been set for 60fe417732e54f1fdb87b9d41b8124e078311429f6dcb04ed6552f43dc87ef83, check communication with the pool, skipping this signage point, pool: https://chia.dpool.cc 
2022-04-24T15:55:31.738 farmer chia.farmer.farmer         : WARNING  No pool specific difficulty has been set for 60fe417732e54f1fdb87b9d41b8124e078311429f6dcb04ed6552f43dc87ef83, check communication with the pool, skipping this signage point, pool: https://chia.dpool.cc 
2022-04-24T15:55:42.121 farmer chia.farmer.farmer         : WARNING  No pool specific difficulty has been set for 60fe417732e54f1fdb87b9d41b8124e078311429f6dcb04ed6552f43dc87ef83, check communication with the pool, skipping this signage point, pool: https://chia.dpool.cc 
2022-04-24T15:55:42.715 full_node chia.full_node.full_node: WARNING  Block validation time: 2.27 seconds, pre_validation time: 0.47 seconds, cost: 3856122078, percent full: 35.056% header_hash: 2efa7638dd85308481082e7fae4d3938051fbc5157931f3d3ff56f7965430c81 height: 1881578
2022-04-24T15:55:49.798 farmer chia.farmer.farmer         : WARNING  No pool specific difficulty has been set for 60fe417732e54f1fdb87b9d41b8124e078311429f6dcb04ed6552f43dc87ef83, check communication with the pool, skipping this signage point, pool: https://chia.dpool.cc 
2022-04-24T15:55:50.222 farmer chia.farmer.farmer         : WARNING  No pool specific difficulty has been set for 60fe417732e54f1fdb87b9d41b8124e078311429f6dcb04ed6552f43dc87ef83, check communication with the pool, skipping this signage point, pool: https://chia.dpool.cc 
2022-04-24T15:55:58.920 farmer chia.farmer.farmer         : WARNING  No pool specific difficulty has been set for 60fe417732e54f1fdb87b9d41b8124e078311429f6dcb04ed6552f43dc87ef83, check communication with the pool, skipping this signage point, pool: https://chia.dpool.cc 
2022-04-24T15:56:07.825 farmer chia.farmer.farmer         : WARNING  No pool specific difficulty has been set for 60fe417732e54f1fdb87b9d41b8124e078311429f6dcb04ed6552f43dc87ef83, check communication with the pool, skipping this signage point, pool: https://chia.dpool.cc 
2022-04-24T15:56:16.548 farmer chia.farmer.farmer         : WARNING  No pool specific difficulty has been set for 60fe417732e54f1fdb87b9d41b8124e078311429f6dcb04ed6552f43dc87ef83, check communication with the pool, skipping this signage point, pool: https://chia.dpool.cc 
2022-04-24T15:56:25.017 farmer chia.farmer.farmer         : WARNING  No pool specific authentication_token_timeout has been set for 60fe417732e54f1fdb87b9d41b8124e078311429f6dcb04ed6552f43dc87ef83, check communication with the pool.
2022-04-24T15:56:25.267 farmer chia.farmer.farmer         : WARNING  No pool specific difficulty has been set for 60fe417732e54f1fdb87b9d41b8124e078311429f6dcb04ed6552f43dc87ef83, check communication with the pool, skipping this signage point, pool: https://chia.dpool.cc 
2022-04-24T15:56:34.375 farmer chia.farmer.farmer         : WARNING  No pool specific difficulty has been set for 60fe417732e54f1fdb87b9d41b8124e078311429f6dcb04ed6552f43dc87ef83, check communication with the pool, skipping this signage point, pool: https://chia.dpool.cc 
2022-04-24T15:56:44.799 farmer chia.farmer.farmer         : WARNING  No pool specific difficulty has been set for 60fe417732e54f1fdb87b9d41b8124e078311429f6dcb04ed6552f43dc87ef83, check communication with the pool, skipping this signage point, pool: https://chia.dpool.cc 
2022-04-24T15:56:54.345 farmer chia.farmer.farmer         : WARNING  No pool specific difficulty has been set for 60fe417732e54f1fdb87b9d41b8124e078311429f6dcb04ed6552f43dc87ef83, check communication with the pool, skipping this signage point, pool: https://chia.dpool.cc 
2022-04-24T15:57:03.828 farmer chia.farmer.farmer         : WARNING  No pool specific difficulty has been set for 60fe417732e54f1fdb87b9d41b8124e078311429f6dcb04ed6552f43dc87ef83, check communication with the pool, skipping this signage point, pool: https://chia.dpool.cc 
2022-04-24T15:57:12.494 farmer chia.farmer.farmer         : WARNING  No pool specific difficulty has been set for 60fe417732e54f1fdb87b9d41b8124e078311429f6dcb04ed6552f43dc87ef83, check communication with the pool, skipping this signage point, pool: https://chia.dpool.cc 
2022-04-24T15:57:21.134 farmer chia.farmer.farmer         : WARNING  No pool specific difficulty has been set for 60fe417732e54f1fdb87b9d41b8124e078311429f6dcb04ed6552f43dc87ef83, check communication with the pool, skipping this signage point, pool: https://chia.dpool.cc 
2022-04-24T15:57:31.045 farmer chia.farmer.farmer         : WARNING  No pool specific difficulty has been set for 60fe417732e54f1fdb87b9d41b8124e078311429f6dcb04ed6552f43dc87ef83, check communication with the pool, skipping this signage point, pool: https://chia.dpool.cc 
2022-04-24T15:57:41.737 farmer chia.farmer.farmer         : WARNING  No pool specific difficulty has been set for 60fe417732e54f1fdb87b9d41b8124e078311429f6dcb04ed6552f43dc87ef83, check communication with the pool, skipping this signage point, pool: https://chia.dpool.cc 
2022-04-24T15:57:42.381 full_node chia.full_node.full_node: WARNING  Block validation time: 2.34 seconds, pre_validation time: 0.43 seconds, cost: 4761841584, percent full: 43.289% header_hash: e03557c68af0107c7d06f71ad8302b7e1c8dfbbaa9605089f0eda42ea9b129f7 height: 1881582
2022-04-24T15:57:42.387 farmer chia.farmer.farmer         : WARNING  No pool specific difficulty has been set for 60fe417732e54f1fdb87b9d41b8124e078311429f6dcb04ed6552f43dc87ef83, check communication with the pool, skipping this signage point, pool: https://chia.dpool.cc 
2022-04-24T15:57:51.142 farmer chia.farmer.farmer         : WARNING  No pool specific difficulty has been set for 60fe417732e54f1fdb87b9d41b8124e078311429f6dcb04ed6552f43dc87ef83, check communication with the pool, skipping this signage point, pool: https://chia.dpool.cc 
2022-04-24T15:57:59.529 farmer chia.farmer.farmer         : WARNING  No pool specific difficulty has been set for 60fe417732e54f1fdb87b9d41b8124e078311429f6dcb04ed6552f43dc87ef83, check communication with the pool, skipping this signage point, pool: https://chia.dpool.cc 
2022-04-24T15:58:08.408 farmer chia.farmer.farmer         : WARNING  No pool specific difficulty has been set for 60fe417732e54f1fdb87b9d41b8124e078311429f6dcb04ed6552f43dc87ef83, check communication with the pool, skipping this signage point, pool: https://chia.dpool.cc 
2022-04-24T15:58:16.907 farmer chia.farmer.farmer         : WARNING  No pool specific difficulty has been set for 60fe417732e54f1fdb87b9d41b8124e078311429f6dcb04ed6552f43dc87ef83, check communication with the pool, skipping this signage point, pool: https://chia.dpool.cc 
2022-04-24T15:58:27.125 farmer chia.farmer.farmer         : WARNING  No pool specific difficulty has been set for 60fe417732e54f1fdb87b9d41b8124e078311429f6dcb04ed6552f43dc87ef83, check communication with the pool, skipping this signage point, pool: https://chia.dpool.cc 
2022-04-24T15:58:36.496 farmer chia.farmer.farmer         : WARNING  No pool specific difficulty has been set for 60fe417732e54f1fdb87b9d41b8124e078311429f6dcb04ed6552f43dc87ef83, check communication with the pool, skipping this signage point, pool: https://chia.dpool.cc 
2022-04-24T15:58:45.705 farmer chia.farmer.farmer         : WARNING  No pool specific difficulty has been set for 60fe417732e54f1fdb87b9d41b8124e078311429f6dcb04ed6552f43dc87ef83, check communication with the pool, skipping this signage point, pool: https://chia.dpool.cc 
2022-04-24T15:58:55.352 farmer chia.farmer.farmer         : WARNING  No pool specific difficulty has been set for 60fe417732e54f1fdb87b9d41b8124e078311429f6dcb04ed6552f43dc87ef83, check communication with the pool, skipping this signage point, pool: https://chia.dpool.cc 
2022-04-24T15:59:04.830 farmer chia.farmer.farmer         : WARNING  No pool specific difficulty has been set for 60fe417732e54f1fdb87b9d41b8124e078311429f6dcb04ed6552f43dc87ef83, check communication with the pool, skipping this signage point, pool: https://chia.dpool.cc 
2022-04-24T15:59:14.495 farmer chia.farmer.farmer         : WARNING  No pool specific difficulty has been set for 60fe417732e54f1fdb87b9d41b8124e078311429f6dcb04ed6552f43dc87ef83, check communication with the pool, skipping this signage point, pool: https://chia.dpool.cc 
2022-04-24T15:59:23.100 farmer chia.farmer.farmer         : WARNING  No pool specific difficulty has been set for 60fe417732e54f1fdb87b9d41b8124e078311429f6dcb04ed6552f43dc87ef83, check communication with the pool, skipping this signage point, pool: https://chia.dpool.cc 
2022-04-24T15:59:32.844 farmer chia.farmer.farmer         : WARNING  No pool specific difficulty has been set for 60fe417732e54f1fdb87b9d41b8124e078311429f6dcb04ed6552f43dc87ef83, check communication with the pool, skipping this signage point, pool: https://chia.dpool.cc 
2022-04-24T15:59:41.576 farmer chia.farmer.farmer         : WARNING  No pool specific difficulty has been set for 60fe417732e54f1fdb87b9d41b8124e078311429f6dcb04ed6552f43dc87ef83, check communication with the pool, skipping this signage point, pool: https://chia.dpool.cc 
2022-04-24T15:59:50.091 farmer chia.farmer.farmer         : WARNING  No pool specific difficulty has been set for 60fe417732e54f1fdb87b9d41b8124e078311429f6dcb04ed6552f43dc87ef83, check communication with the pool, skipping this signage point, pool: https://chia.dpool.cc 
2022-04-24T15:59:59.001 farmer chia.farmer.farmer         : WARNING  No pool specific difficulty has been set for 60fe417732e54f1fdb87b9d41b8124e078311429f6dcb04ed6552f43dc87ef83, check communication with the pool, skipping this signage point, pool: https://chia.dpool.cc 
2022-04-24T16:00:06.511 full_node chia.full_node.full_node: WARNING  Block validation time: 2.50 seconds, pre_validation time: 0.51 seconds, cost: 4559192511, percent full: 41.447% header_hash: 32a16df7f124ec7c877f5ac1d09ec98581e1711b7b2ffe77471c64e6148a0946 height: 1881591
2022-04-24T16:00:09.115 farmer chia.farmer.farmer         : WARNING  No pool specific difficulty has been set for 60fe417732e54f1fdb87b9d41b8124e078311429f6dcb04ed6552f43dc87ef83, check communication with the pool, skipping this signage point, pool: https://chia.dpool.cc 
2022-04-24T16:00:17.408 farmer chia.farmer.farmer         : WARNING  No pool specific difficulty has been set for 60fe417732e54f1fdb87b9d41b8124e078311429f6dcb04ed6552f43dc87ef83, check communication with the pool, skipping this signage point, pool: https://chia.dpool.cc 
2022-04-24T16:00:27.213 farmer chia.farmer.farmer         : WARNING  No pool specific difficulty has been set for 60fe417732e54f1fdb87b9d41b8124e078311429f6dcb04ed6552f43dc87ef83, check communication with the pool, skipping this signage point, pool: https://chia.dpool.cc 
2022-04-24T16:00:35.756 farmer chia.farmer.farmer         : WARNING  No pool specific difficulty has been set for 60fe417732e54f1fdb87b9d41b8124e078311429f6dcb04ed6552f43dc87ef83, check communication with the pool, skipping this signage point, pool: https://chia.dpool.cc 
2022-04-24T16:00:44.581 farmer chia.farmer.farmer         : WARNING  No pool specific difficulty has been set for 60fe417732e54f1fdb87b9d41b8124e078311429f6dcb04ed6552f43dc87ef83, check communication with the pool, skipping this signage point, pool: https://chia.dpool.cc 
2022-04-24T16:00:53.370 farmer chia.farmer.farmer         : WARNING  No pool specific difficulty has been set for 60fe417732e54f1fdb87b9d41b8124e078311429f6dcb04ed6552f43dc87ef83, check communication with the pool, skipping this signage point, pool: https://chia.dpool.cc 
2022-04-24T16:01:02.268 farmer chia.farmer.farmer         : WARNING  No pool specific difficulty has been set for 60fe417732e54f1fdb87b9d41b8124e078311429f6dcb04ed6552f43dc87ef83, check communication with the pool, skipping this signage point, pool: https://chia.dpool.cc 
2022-04-24T16:01:12.717 farmer chia.farmer.farmer         : WARNING  No pool specific difficulty has been set for 60fe417732e54f1fdb87b9d41b8124e078311429f6dcb04ed6552f43dc87ef83, check communication with the pool, skipping this signage point, pool: https://chia.dpool.cc 
2022-04-24T16:01:21.377 farmer chia.farmer.farmer         : WARNING  No pool specific difficulty has been set for 60fe417732e54f1fdb87b9d41b8124e078311429f6dcb04ed6552f43dc87ef83, check communication with the pool, skipping this signage point, pool: https://chia.dpool.cc 
2022-04-24T16:01:30.153 farmer chia.farmer.farmer         : WARNING  No pool specific difficulty has been set for 60fe417732e54f1fdb87b9d41b8124e078311429f6dcb04ed6552f43dc87ef83, check communication with the pool, skipping this signage point, pool: https://chia.dpool.cc 
2022-04-24T16:01:38.912 farmer chia.farmer.farmer         : WARNING  No pool specific difficulty has been set for 60fe417732e54f1fdb87b9d41b8124e078311429f6dcb04ed6552f43dc87ef83, check communication with the pool, skipping this signage point, pool: https://chia.dpool.cc 
2022-04-24T16:01:38.916 daemon __main__                   : ERROR    Unexpected exception trying to send to websocket: Cannot write to closing transport Traceback (most recent call last):
  File "Lib\site-packages\chia\daemon\server.py", line 239, in incoming_connection
  File "aiohttp\web_ws.py", line 300, in send_str
  File "aiohttp\http_websocket.py", line 687, in send
  File "aiohttp\http_websocket.py", line 650, in _send_frame
  File "aiohttp\http_websocket.py", line 660, in _write
ConnectionResetError: Cannot write to closing transport
```

**Comment by wallentx** [comment]
When visiting https://chia.dpool.cc/, it looks like the cert is incorrect. Are you sure that this is the correct pool address, and that this pool is active?

**Comment by hajes** [comment]
I have similar "issues"...it is caused by old inactive pools that you used in past. I tried to remove pools I do not use, but they pop right back. No idea why is not possible to remove unused pools.
