### ISSUE TITLE
[Bug] ERROR    problem starting chia_full_node

### ISSUE THREAD

**Issue by timzhangliang** [Chia-Network/chia-blockchain#11291]
### What happened?

2022-04-24T10:02:35.551 daemon __main__                   : ERROR    problem starting chia_full_node
Traceback (most recent call last):
  File "Lib\site-packages\chia\daemon\server.py", line 1084, in start_service
  File "Lib\site-packages\chia\daemon\server.py", line 1264, in launch_service
  File "subprocess.py", line 951, in __init__
  File "subprocess.py", line 1420, in _execute_child
FileNotFoundError: [WinError 2] 系统找不到指定的文件。

### Version

1.3.4

### What platform are you using?

Windows

### What ui mode are you using?

GUI

### Relevant log output

```shell
2022-04-24T10:02:35.504 daemon __main__                   : ERROR    problem starting chia_full_node
Traceback (most recent call last):
  File "Lib\site-packages\chia\daemon\server.py", line 1084, in start_service
  File "Lib\site-packages\chia\daemon\server.py", line 1264, in launch_service
  File "subprocess.py", line 951, in __init__
  File "subprocess.py", line 1420, in _execute_child
FileNotFoundError: [WinError 2] 系统找不到指定的文件。
2022-04-24T10:02:35.520 daemon __main__                   : ERROR    problem starting chia_full_node
Traceback (most recent call last):
  File "Lib\site-packages\chia\daemon\server.py", line 1084, in start_service
  File "Lib\site-packages\chia\daemon\server.py", line 1264, in launch_service
  File "subprocess.py", line 951, in __init__
  File "subprocess.py", line 1420, in _execute_child
FileNotFoundError: [WinError 2] 系统找不到指定的文件。
2022-04-24T10:02:35.551 daemon __main__                   : ERROR    problem starting chia_full_node
Traceback (most recent call last):
  File "Lib\site-packages\chia\daemon\server.py", line 1084, in start_service
  File "Lib\site-packages\chia\daemon\server.py", line 1264, in launch_service
  File "subprocess.py", line 951, in __init__
  File "subprocess.py", line 1420, in _execute_child
FileNotFoundError: [WinError 2] 系统找不到指定的文件。
```

**Comment by timzhangliang** [comment]
2022-04-24T10:26:27.243 daemon __main__                   : ERROR    problem starting chia_full_node
Traceback (most recent call last):
  File "Lib\site-packages\chia\daemon\server.py", line 1084, in start_service
  File "Lib\site-packages\chia\daemon\server.py", line 1264, in launch_service
  File "subprocess.py", line 951, in __init__
  File "subprocess.py", line 1420, in _execute_child
PermissionError: [WinError 5] 拒绝访问。

**Comment by timzhangliang** [comment]
@arvidn

**Comment by neo57500** [comment]
2022-04-23T21:34:00.688 full_node full_node_server        : ERROR    Exception Stack: Traceback (most recent call last):
  File "chia\server\ws_connection.py", line 249, in outbound_handler
  File "chia\server\ws_connection.py", line 402, in _send_message
  File "aiohttp\web_ws.py", line 307, in send_bytes
  File "aiohttp\http_websocket.py", line 685, in send
  File "aiohttp\http_websocket.py", line 656, in _send_frame
  File "aiohttp\base_protocol.py", line 87, in _drain_helper
  File "asyncio\sslproto.py", line 534, in data_received
  File "asyncio\sslproto.py", line 199, in feed_ssldata
  File "ssl.py", line 888, in read
ssl.SSLError: [SSL: DECRYPTION_FAILED_OR_BAD_RECORD_MAC] decryption failed or bad record mac (_ssl.c:2633)

**Comment by emlowe** [comment]
@timzhangliang How did you install ? With the standard windows installer?  I might consider uninstalling Chia, re-installing it again, rebooting and trying it again.

**Comment by emlowe** [comment]
Closing issue due to lack of response
