### ISSUE TITLE
[Bug] farmer out of sync with harvester randomly

### ISSUE THREAD

**Issue by FlyingSB** [Chia-Network/chia-blockchain#11354]
### What happened?

The farmer drops out of sync with all harvesters randomly. I have to restart the farmer and all harvesters.

### Version

1.3.4

### What platform are you using?

Linux

### What ui mode are you using?

CLI

### Relevant log output

```shell
2022-04-28T22:42:59.428 farmer chia.plot_sync.receiver    : WARNING  _process: InvalidIdentifierError Invalid identifier: Actual {'message_id': 6, 'sync_id': 1651156873, 'timestamp': 1651156975}, Expected {'message_id': 0, 'sync_id': 0, 'timestamp': 1651156975}
2022-04-28T22:42:59.428 farmer chia.plot_sync.receiver    : WARNING  _process: InvalidIdentifierError Invalid identifier: Actual {'message_id': 6, 'sync_id': 1651156873, 'timestamp': 1651156975}, Expected {'message_id': 0, 'sync_id': 0, 'timestamp': 1651156975}
2022-04-28T22:42:59.428 farmer chia.plot_sync.receiver    : WARNING  _process: InvalidIdentifierError Invalid identifier: Actual {'message_id': 6, 'sync_id': 1651156880, 'timestamp': 1651156975}, Expected {'message_id': 0, 'sync_id': 0, 'timestamp': 1651156975}
2022-04-28T22:42:59.429 farmer chia.plot_sync.receiver    : WARNING  _process: InvalidIdentifierError Invalid identifier: Actual {'message_id': 6, 'sync_id': 1651156804, 'timestamp': 1651156975}, Expected {'message_id': 0, 'sync_id': 0, 'timestamp': 1651156975}
2022-04-28T22:42:59.429 farmer chia.plot_sync.receiver    : WARNING  _process: InvalidIdentifierError Invalid identifier: Actual {'message_id': 3, 'sync_id': 1651156920, 'timestamp': 1651156975}, Expected {'message_id': 4, 'sync_id': 1651156920, 'timestamp': 1651156975}
2022-04-28T22:42:59.429 farmer chia.plot_sync.receiver    : WARNING  _process: InvalidIdentifierError Invalid identifier: Actual {'message_id': 2, 'sync_id': 1651156925, 'timestamp': 1651156975}, Expected {'message_id': 3, 'sync_id': 1651156925, 'timestamp': 1651156975}
2022-04-28T22:42:59.429 farmer chia.plot_sync.receiver    : WARNING  _process: InvalidIdentifierError Invalid identifier: Actual {'message_id': 3, 'sync_id': 1651156882, 'timestamp': 1651156976}, Expected {'message_id': 4, 'sync_id': 1651156882, 'timestamp': 1651156976}
2022-04-28T22:42:59.430 farmer chia.plot_sync.receiver    : WARNING  _process: InvalidIdentifierError Invalid identifier: Actual {'message_id': 15, 'sync_id': 1651156550, 'timestamp': 1651156976}, Expected {'message_id': 0, 'sync_id': 0, 'timestamp': 1651156976}
2022-04-28T22:42:59.437 farmer chia.rpc.rpc_server        : WARNING  Sending data failed. Exception Traceback (most recent call last):
  File "/root/chia-blockchain/chia/rpc/rpc_server.py", line 76, in _state_changed
    await self.websocket.send_str(dict_to_json_str(payload))
  File "/root/chia-blockchain/venv/lib/python3.8/site-packages/aiohttp/client_ws.py", line 150, in send_str
    await self._writer.send(data, binary=False, compress=compress)
  File "/root/chia-blockchain/venv/lib/python3.8/site-packages/aiohttp/http_websocket.py", line 687, in send
    await self._send_frame(message, WSMsgType.TEXT, compress)
  File "/root/chia-blockchain/venv/lib/python3.8/site-packages/aiohttp/http_websocket.py", line 656, in _send_frame
    await self.protocol._drain_helper()
  File "/root/chia-blockchain/venv/lib/python3.8/site-packages/aiohttp/base_protocol.py", line 84, in _drain_helper
    assert waiter is None or waiter.cancelled()
AssertionError
.
```

**Comment by chiamaster** [comment]
Need to revert plot_sync commit to fix the issue

**Comment by xdustinface** [comment]
@FlyingSB Can you also post the related log of the harvester?

**Comment by FlyingSB** [comment]
> 

2022-04-30T05:16:23.947 harvester chia.plot_sync.sender   : INFO     _send_next_message didn't receive response expected_message_type: plot_sync_start, expected_identifier: {'message_id': 0, 'sync_id': 1651266973, 'timestamp': 1651266973}, message None
2022-04-30T05:16:25.806 harvester chia.plot_sync.sender   : WARNING  set_response skip expired response: PlotSyncResponse: identifier {'message_id': 0, 'sync_id': 1651266973, 'timestamp': 1651266973}, message_type 78, error None

**Comment by bds89** [comment]
The same problem:

2022-05-09 15:59:53    WARNING    _process: InvalidIdentifierError Invalid identifier: Actual {'message_id': 1, 'sync_id': 1652101150, 'timestamp': 1652101188}, Expected {'message_id': 2, 'sync_id': 1652101150, 'timestamp': 1652101188}
