### ISSUE TITLE
[Bug] chia stop responding while syncing db

### ISSUE THREAD

**Issue by paquinmathieu** [Chia-Network/chia-blockchain#11446]
### What happened?

I  installed  pop os 22.01 on a freshly formatted drive. Then installad chia. Using the gui, I started the sync. It began the sync process, but it is also crashing and stop responding after a while, maybe a couple of hours max. Never a full day
I tried

- in the gui
  - refresh
  - force refresh
    -  the result is a gui with turning wheel over each area where a number should have been
  - close the gui, wait reopen
    - it is never able to past through the "full node" starting and get stuck there. Refresh, force refresh leads to the turning wheels over the number
  - kill all chia process and reopen chia gui
    -  it is never able to past through the "full node" starting and get stuck there. Refresh, force refresh leads to the turning wheels 
  - delete the entire db folder, reboot computer and reopen the gui. 
    - it will works for a few hours then, it will get stuck
- starting from cli
  - the same type of behavior, it becomes unresponsive after a while, it stop answering the command "chia show -s"
  - i then try chia stop all, it says that the full node is stopped. but if I try "chia start farmer" I get 

> "chia_full_node: Already running, use `-r` to restart"

  - at this point, the only solution is to reboot. Then it works for a few hours and stops again.
- I installer docker and the "chianetwork/chia-docker" official docker image.
  - started a to sync the blockchain from zero.
  - the same from the cli happens, and once it hangs, stopping and restarting the container wont work. The entire computer needs to be restarted. After a restart, the containers works for a few hours before it stops again. **EDIT** sometimes I can stop and start the container and its working but its not syncing. 

### Version

1.3.4

### What platform are you using?

Linux

### What ui mode are you using?

CLI

### Relevant log output

```shell
This is the log from the docker
this seems to be the moment it hangs. This time, the docker had been running for approximatly 3 hours.

2022-05-05T02:13:28.657 full_node chia.full_node.full_node: ERROR    Error: Err.UNKNOWN_UNSPENT, Invalid block from peer: {'host': '110.188.51.241', 'port': 8444} 

2022-05-05T02:13:28.658 full_node full_node_server        : WARNING  Banning 110.188.51.241 for 600 seconds

2022-05-05T02:13:28.659 full_node chia.full_node.full_node: ERROR    sync from fork point failed err: Failed to validate block batch 703342 to 703374

2022-05-05T02:13:58.112 Healthcheck(s) completed successfully

2022-05-05T02:14:01.994 full_node full_node_server        : WARNING  Cannot write to closing transport 2.185.110.232

2022-05-05T02:19:58.965 Node healthcheck failed

2022-05-05T02:21:08.975 Node healthcheck failed

2022-05-05T02:22:19.018 Node healthcheck failed

2022-05-05T02:23:29.040 Node healthcheck failed

2022-05-05T02:23:49.238 farmer chia.farmer.farmer         : WARNING  PUT /farmer response: {'error_code': 16, 'error_message': 'Cannot update farmer c20f7b71b84452a3fc700d57ebd10f6a3c26ab7bd280849a47175dd647e3bef9 yet.'}

2022-05-05T02:24:39.030 Node healthcheck failed
```

**Comment by paquinmathieu** [comment]
well... apparently, this time, I'm stuck. It doesn't want to sync any further than 703342
I'm going to delete the db for the 7th time. I just can't seem to be able to sync the blockchain

**Comment by wallentx** [comment]
Hi, are you able to share a bit of info about your system specs?

**Comment by paquinmathieu** [comment]
Hi, @wallentx , thanks for taking the time

My system is 

- 20 CPUs Intel(R) Core(TM) i9-10900F CPU @ 2.80GHz (A0655),ASM,AES-NI)
- linux pop!_OS 22.10
- 47GiB or ram
- The OS is running on a 256GB SSD.
- running headless (no graphic card)
The computer is used only for farmer at the moment, nothing else. It had been running solid since may 2021 until 2 weeks ago when a power outage required me to reinstall the firmware of the lsi card. Then, I took the time to update POP OS to the latest version and update the chia software. Went downhill from there. I have been struggling for the last 2 weeks trying to sync it.

**Comment by paquinmathieu** [comment]
I tried to download the blockchain from a site, unpack it using 7z or the Pop!_OS included utility, each time it would give me "sqlite3.DatabaseError: database disk image is malformed". The downloaded file must have had a problem. I tried with multiple source and I was never able to make them work.

### So I deleted the DB and started from zero once more

here is a log of my last retry yesterday. I deleted the DB and started from scratch
[_Chia_logs (2).txt](https://github.com/Chia-Network/chia-blockchain/files/8640082/_Chia_logs.2.txt)
this is the log from docker. Let me know if you need anything else that can help.

no matter what I write those command in the container console , I get no answer and it stays black
- chia show -s
- chia farm summary

**Comment by paquinmathieu** [comment]
formatted the drive again and I installed Debian without GUI
I installed docker and portainer again and the official docker image of chia
It still have a lot of problem trying to sync the blockchain. I have 100TB of plot not generating any revenu right now for the last 2 weeks.

datetime (utc) | description | last block synced
--- | --- | ---
may8th 2022 23h26 |  I restarted the docker container. It started to sync correctly |  [block 238 000]
may9th 2022 00h47 | I get off the computer and shut down the remote computer (not the full node containing the plots) | [block 324 156]
may 9th 2022 01h22 | The logs starts to show a lot of (over 64 of those lines) "connection closed" and "peer disconnected" |[block 363 356]

Here is the log truncated to this specific event
[20220508-20220509_Truncated1.txt](https://github.com/Chia-Network/chia-blockchain/files/8651461/20220508-20220509_Truncated1.txt)

---

datetime (utc) | description | last block synced
--- | --- | ---
may 9th 2022 10h50 |  send commande  "chia stop all". Then I  stopped the container. Then I started the container again | [block 363 356]
may 9th 2022 11h15 | the logs shows "wallet wallet_server              : INFO     Connection closed: 127.0.0.1, node id: ..."  <br>then "Reconnecting to peer {'host': '127.0.0.1', 'port': 8444}" and no more block are synced | [block 394 812]

Here is the log truncated to this specific event
[20220508-20220509_Truncated2.txt](https://github.com/Chia-Network/chia-blockchain/files/8651567/20220508-20220509_Truncated2.txt)

---

Here is the full log since i restarted the docker on may8th
[20220508-20220509_FULL.txt](https://github.com/Chia-Network/chia-blockchain/files/8651502/20220508-20220509_FULL.txt)

Is there anything obvious that I'm doing wrong?

**Comment by paquinmathieu** [comment]
there is always something that prevents the synchronisation of the blockchain. I'm running out of ideas
it got stuck at blockheight 809582 and wouldnt budge after that. No matter what, restart,reboot, etc... 
I deleted the db once more...
I wrote a script that call the command "chia show -s". After 10 failed attempt at getting the proper answer, it shut down chia and then the docker container. Then restart the container.
Hopefully I can get up to speed.

**Comment by paquinmathieu** [comment]
got stuck at block 699590
```
  File "/chia-blockchain/venv/lib/python3.9/site-packages/aiosqlite/core.py", line 102, in run
    result = function()
sqlite3.DatabaseError: database disk image is malformed
 database disk image is malformed
2022-05-11T12:07:03.117 full_node chia.full_node.full_node: ERROR    sync from fork point failed err: database disk image is malformed
2022-05-11T12:07:03.117 full_node chia.full_node.full_node: INFO     long sync done
```

This is the section of the container log where you can see it is adding block successfully until it doesn't
```
2022-05-11T03:52:00.515 full_node chia.full_node.full_node: INFO     Added blocks 699324 to 699356
2022-05-11T03:52:01.988 full_node chia.full_node.full_node: INFO     Added blocks 699356 to 699388
2022-05-11T03:52:03.689 full_node chia.full_node.full_node: INFO     Added blocks 699388 to 699420
2022-05-11T03:52:04.907 full_node chia.full_node.full_node: INFO     Added blocks 699420 to 699452
2022-05-11T03:52:06.971 full_node chia.full_node.full_node: INFO     Added blocks 699452 to 699484
2022-05-11T03:52:08.766 full_node chia.full_node.full_node: INFO     Added blocks 699484 to 699516
2022-05-11T03:52:09.689 wallet chia.wallet.wallet_blockchain: INFO     Peak set to: 1959264 timestamp: 1652241096
2022-05-11T03:52:09.689 wallet chia.wallet.wallet_node    : INFO     Finished processing new peak of 1959264
2022-05-11T03:52:10.556 full_node chia.full_node.full_node: INFO     Added blocks 699516 to 699548
2022-05-11T03:52:12.205 full_node chia.full_node.full_node: INFO     Added blocks 699548 to 699580
2022-05-11T03:52:13.380 full_node chia.consensus.blockchain: ERROR    Error while adding block a2c15ecc45b6f23c7faac40203e1e242d40dabdefb8054d24e0b92ea0dd1b6e3 height 699591, rolling back: Traceback (most recent call last):

  File "/chia-blockchain/chia/consensus/blockchain.py", line 268, in receive_block
    fork_height, peak_height, records, (coin_record_change, hint_changes) = await self._reconsider_peak(
  File "/chia-blockchain/chia/consensus/blockchain.py", line 406, in _reconsider_peak
    added_rec = await self.coin_store.new_block(
  File "/chia-blockchain/chia/full_node/coin_store.py", line 149, in new_block
    await self._add_coin_records(additions)
  File "/chia-blockchain/chia/full_node/coin_store.py", line 485, in _add_coin_records
    await conn.executemany(
  File "/chia-blockchain/venv/lib/python3.9/site-packages/aiosqlite/core.py", line 210, in executemany
    cursor = await self._execute(self._conn.executemany, sql, parameters)
  File "/chia-blockchain/venv/lib/python3.9/site-packages/aiosqlite/core.py", line 129, in _execute
    return await future
  File "/chia-blockchain/venv/lib/python3.9/site-packages/aiosqlite/core.py", line 102, in run
    result = function()
sqlite3.DatabaseError: database disk image is malformed
 database disk image is malformed

2022-05-11T03:52:13.386 full_node chia.full_node.full_node: ERROR    sync from fork point failed err: database disk image is malformed
2022-05-11T03:52:13.387 full_node chia.full_node.full_node: INFO     long sync done

```

this is killing me
here is the last 100k lines of log (you can see the container being restarted multiple times (that is because my script determined that Chia had hang and decided to stop chia `chia stop all` and restart the docker container

[_chia_logs_databaseImageMalformed_20220511.txt](https://github.com/Chia-Network/chia-blockchain/files/8669801/_chia_logs_databaseImageMalformed_20220511.txt)

after 2 weeks, I'm still unable to sync the blockchain.

**Comment by paquinmathieu** [comment]
now trying with version 1.2.11

**Comment by emlowe** [comment]
Anytime you see `database disk image is malformed` - this means your DB is corrupted and you need to delete it and start again. Normally this is very rare, so if you are continuing to see this then I might start to suspect something in your environment is causing this.

It's quite normal to see plenty of disconnects in your log file as peer nodes come and go - sometimes it does take some time to find a good set of peers.

**Comment by paquinmathieu** [comment]
Hi,

@emlowe , thank you for your time. I'm not concerned about the regular disconnects. When it starts to sync it syncing well until it stops. And thats what I'm trying to solve, but I can't find anything to help me. I'm about to just leave chia. There's not point in trying over and over again the same thing expecting different results. Would it help to change the log level to debug?

Now I get this error of database disk image malformed everysingle time. I have tried to change the hdd where the db is stored. I still get the same error. I'm able to get to 550k or 552 or around 600k or 500k never been able to go further than 827k

my last attempts I was able to sync up to this block height
may 12th : 827k
may13th : 600k
on another drive. A hdd instead of a SDD
may 14th : 500k
may 15th : 552k
may 15th : 554k (restarting from a backup done at 500k)

I tried 1.2.11, 1.3.4 / latest

This is the latest log with what I think is the most relevant part. You can see it's syncing from 554142 to 554238 in here (it was syncing from 500 000 approximatly, but I didn'T paste it.
```
2022-05-15T18:50:15.840 full_node chia.full_node.full_node: INFO     Added blocks 554142 to 554174
2022-05-15T18:50:22.084 full_node chia.full_node.full_node: INFO     Added blocks 554174 to 554206
2022-05-15T18:50:29.583 full_node chia.full_node.full_node: INFO     Added blocks 554206 to 554238
2022-05-15T18:50:31.779 full_node chia.consensus.blockchain: ERROR    Error while adding block acd9ff6435a33e4de526fae2b25ecf2be8de164e4ca301e7e6992084812a3c5b height 554252, rolling back: Traceback (most recent call last):
  File "/chia-blockchain/chia/consensus/blockchain.py", line 267, in receive_block
    await self.block_store.add_full_block(header_hash, block, block_record)
  File "/chia-blockchain/chia/full_node/block_store.py", line 207, in add_full_block
    await conn.execute(
  File "/chia-blockchain/venv/lib/python3.9/site-packages/aiosqlite/core.py", line 184, in execute
    cursor = await self._execute(self._conn.execute, sql, parameters)
  File "/chia-blockchain/venv/lib/python3.9/site-packages/aiosqlite/core.py", line 129, in _execute
    return await future
  File "/chia-blockchain/venv/lib/python3.9/site-packages/aiosqlite/core.py", line 102, in run
    result = function()
sqlite3.DatabaseError: database disk image is malformed
 database disk image is malformed
2022-05-15T18:50:31.781 full_node chia.full_node.full_node: ERROR    sync from fork point failed err: database disk image is malformed
2022-05-15T18:50:31.782 full_node chia.full_node.full_node: INFO     long sync done
2022-05-15T18:50:31.782 full_node chia.full_node.full_node: INFO     🌱 Updated peak to height 554251, weight 411631968, hh de1b9f0948c98215613d0a22998276fd834835adad76df185d32ae29012e9639, forked at 554250, rh: 4174462b80413961c3790127b76b3c351df799dc6b22fa247f6c8e83060bf445, total iters: 1867932543037, overflow: False, deficit: 4, difficulty: 2272, sub slot iters: 120061952, Generator size: No tx, Generator ref list size: No tx
2022-05-15T18:50:31.785 full_node chia.full_node.weight_proof: INFO     create weight proof peak de1b9f0948c98215613d0a22998276fd834835adad76df185d32ae29012e9639 554251
2022-05-15T18:50:31.856 full_node chia.full_node.weight_proof: INFO     recent chain, start: 553740 end:  554251 
2022-05-15T18:50:31.857 full_node chia.full_node.full_node: INFO     Starting to perform sync.
2022-05-15T18:50:31.857 full_node chia.full_node.full_node: INFO     Waiting to receive peaks from peers.
2022-05-15T18:50:32.719 full_node asyncio                 : ERROR    Task was destroyed but it is pending!
task: <Task pending name='Task-445' coro=<FullNode.sync_from_fork_point.<locals>.fetch_block_batches() running at /chia-blockchain/chia/full_node/full_node.py:974> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7f2eab55c190>()]> cb=[_gather.<locals>._done_callback() at /usr/local/lib/python3.9/asyncio/tasks.py:767]>
2022-05-15T18:50:49.326 full_node full_node_server        : INFO     Connected with full_node {'host': '92.101.166.97', 'port': 8444}
2022-05-15T18:50:49.393 full_node full_node_server        : INFO     Connection closed: 92.101.166.97, node id: ff82c6c5327e8f7f3d0e28bc753f7dd84e9b1d973d05a10ab77429ef49177e26
2022-05-15T18:50:49.394 full_node chia.full_node.full_node: INFO     peer disconnected {'host': '92.101.166.97', 'port': 8444}
2022-05-15T18:50:49.927 full_node chia.full_node.full_node: INFO     Collected a total of 7 peaks.
2022-05-15T18:50:49.929 full_node chia.full_node.full_node: INFO     Selected peak 1980505, 1958572b1ed53ea3e2bf73454155cd00385e155ec60b5be6b1078dca86b0c311
2022-05-15T18:50:50.204 full_node chia.full_node.full_node: INFO     Total of 1 peers with peak 1980505
2022-05-15T18:50:50.206 full_node chia.full_node.full_node: INFO     Requesting weight proof from peer 76.65.87.9 up to height 1980505
2022-05-15T18:50:51.280 full_node chia.server.address_manager_store: INFO     Serializing peer data
2022-05-15T18:50:55.482 full_node chia.full_node.weight_proof: INFO     validate weight proof peak height 1980505
2022-05-15T18:50:55.560 full_node chia.full_node.weight_proof: INFO     validating 5157 sub epochs
2022-05-15T18:50:57.664 full_node full_node_server        : INFO     Cannot connect to host 84.170.81.197:8444 ssl:<ssl.SSLContext object at 0x7f2e9caab5c0> [Connect call failed ('84.170.81.197', 8444)]
2022-05-15T18:51:08.567 full_node chia.full_node.full_node: INFO     Re-checked peers: total of 1 peers with peak 1980505
2022-05-15T18:51:08.812 full_node chia.full_node.full_node: INFO     Start syncing from fork point at 553345 up to 1980505
2022-05-15T18:51:10.452 full_node chia.consensus.blockchain: ERROR    Error while adding block acd9ff6435a33e4de526fae2b25ecf2be8de164e4ca301e7e6992084812a3c5b height 554252, rolling back: Traceback (most recent call last):
  File "/chia-blockchain/chia/consensus/blockchain.py", line 267, in receive_block
    await self.block_store.add_full_block(header_hash, block, block_record)
  File "/chia-blockchain/chia/full_node/block_store.py", line 207, in add_full_block
    await conn.execute(
  File "/chia-blockchain/venv/lib/python3.9/site-packages/aiosqlite/core.py", line 184, in execute
    cursor = await self._execute(self._conn.execute, sql, parameters)
  File "/chia-blockchain/venv/lib/python3.9/site-packages/aiosqlite/core.py", line 129, in _execute
    return await future
  File "/chia-blockchain/venv/lib/python3.9/site-packages/aiosqlite/core.py", line 102, in run
    result = function()
sqlite3.DatabaseError: database disk image is malformed
 database disk image is malformed
2022-05-15T18:51:10.474 full_node chia.full_node.full_node: ERROR    sync from fork point failed err: database disk image is malformed
```

**Comment by paquinmathieu** [comment]
well, the node finally started. It took forever. I now see the linux harvester (the pc that was never able to sync to the blockchain). If this works, at least I could make the best of those hard drive

**Comment by paquinmathieu** [comment]
The linux harvester has been connected to the windows full node for over a week and has been very stable. No crash, no bug. Actually I wanted to get rid of my windows full node and tx the hdd to the linux machine...
