### ISSUE TITLE
不能领取奖励，1.3.4版本[Bug] 

### ISSUE THREAD

**Issue by chiavivi** [Chia-Network/chia-blockchain#11444]
### What happened?

不能领取奖励，1.3.4版本，想知道是个别不能领取还是，所有不能领取？

### Version

1.3.4

### What platform are you using?

Windows

### What ui mode are you using?

GUI

**Comment by chiavivi** [comment]
2022-05-06T11:07:19.585 wallet chia.wallet.wallet_node    : WARNING  SpendBundle has been rejected by the FullNode. {'error': 'DOUBLE_SPEND', 'status': 3, 'txid': '0x09d548d468d24454212893459446a482a7351044a98ce8bde7b66dc219260c1d'}
2022-05-06T11:07:19.589 wallet chia.wallet.wallet_node    : WARNING  SpendBundle has been rejected by the FullNode. {'error': 'DOUBLE_SPEND', 'status': 3, 'txid': '0x09d548d468d24454212893459446a482a7351044a98ce8bde7b66dc219260c1d'}
2022-05-06T11:50:01.919 wallet chia.wallet.wallet_node    : WARNING  SpendBundle has been rejected by the FullNode. {'error': 'DOUBLE_SPEND', 'status': 3, 'txid': '0x97f1d045d0930ff5175632da2d010518848477eb30bbf448a76ab00f2f290f3f'}
2022-05-06T11:50:01.922 wallet chia.wallet.wallet_node    : WARNING  SpendBundle has been rejected by the FullNode. {'error': 'DOUBLE_SPEND', 'status': 3, 'txid': '0x97f1d045d0930ff5175632da2d010518848477eb30bbf448a76ab00f2f290f3f'}

**Comment by chiavivi** [comment]
2022-05-18T10:04:26.955 wallet chia.rpc.rpc_server        : WARNING  Error while handling message: Traceback (most recent call last):
  File "chia\rpc\rpc_server.py", line 228, in safe_handle
  File "chia\rpc\rpc_server.py", line 219, in ws_api
  File "chia\rpc\wallet_rpc_api.py", line 1418, in pw_absorb_rewards
  File "chia\pools\pool_wallet.py", line 788, in claim_pool_rewards
ValueError: Cannot claim due to unconfirmed transaction. If this is stuck, delete the unconfirmed transaction.
