### ISSUE TITLE
[Bug] cant switch from pool to solo

### ISSUE THREAD

**Issue by OVelihin** [Chia-Network/chia-blockchain#11459]
### What happened?

When i try switch from pool.space to solo pool i recieve this message "Attempted to self pool when already self pooling". 
Can some one help?
https://prnt.sc/X9YNXKGJYrvY

### Version

last

### What platform are you using?

Linux

### What ui mode are you using?

GUI

### Relevant log output

```shell
2022-05-06T17:43:58.693 wallet chia.rpc.rpc_server        : WARNING  Error while handling message: Traceback (most recent call last):
  File "chia/rpc/rpc_server.py", line 225, in safe_handle
  File "chia/rpc/rpc_server.py", line 216, in ws_api
  File "chia/rpc/wallet_rpc_api.py", line 1401, in pw_self_pool
  File "chia/pools/pool_wallet.py", line 753, in self_pool
ValueError: Attempted to self pool when already self pooling

2022-05-06T17:47:10.382 wallet chia.rpc.rpc_server        : WARNING  Error while handling message: Traceback (most recent call last):
  File "chia/rpc/rpc_server.py", line 225, in safe_handle
  File "chia/rpc/rpc_server.py", line 216, in ws_api
  File "chia/rpc/wallet_rpc_api.py", line 1401, in pw_self_pool
  File "chia/pools/pool_wallet.py", line 753, in self_pool
ValueError: Attempted to self pool when already self pooling

2022-05-06T17:47:40.053 wallet chia.rpc.rpc_server        : WARNING  Error while handling message: Traceback (most recent call last):
  File "chia/rpc/rpc_server.py", line 225, in safe_handle
  File "chia/rpc/rpc_server.py", line 216, in ws_api
  File "chia/rpc/wallet_rpc_api.py", line 1401, in pw_self_pool
  File "chia/pools/pool_wallet.py", line 753, in self_pool
ValueError: Attempted to self pool when already self pooling
```

**Comment by emlowe** [comment]
I suspect a syncing problem. Please download 1.3.5 and resync your wallet DB. I believe this will resolve the issue. Feel free to reopen if you have further problems
