### ISSUE TITLE
1.3.5版本还是不能领取奖励日志如下[Bug] 

### ISSUE THREAD

**Issue by chiavivi** [Chia-Network/chia-blockchain#11559]
### What happened?

一直不能领取奖励，从1.3.1版本到现在1.3.5版本还是不能领取，发了日志还是没有解决方案：2022-05-18T10:04:26.955 wallet chia.rpc.rpc_server : WARNING Error while handling message: Traceback (most recent call last):
File "chia\rpc\rpc_server.py", line 228, in safe_handle
File "chia\rpc\rpc_server.py", line 219, in ws_api
File "chia\rpc\wallet_rpc_api.py", line 1418, in pw_absorb_rewards
File "chia\pools\pool_wallet.py", line 788, in claim_pool_rewards

### Version

1.3.5

### What platform are you using?

Windows

### What ui mode are you using?

GUI

### Relevant log output

```shell
chia.rpc.rpc_server : WARNING Error while handling message: Traceback (most recent call last):
File "chia\rpc\rpc_server.py", line 228, in safe_handle
File "chia\rpc\rpc_server.py", line 219, in ws_api
File "chia\rpc\wallet_rpc_api.py", line 1418, in pw_absorb_rewards
File "chia\pools\pool_wallet.py", line 788, in claim_pool_rewards
```

**Comment by chiavivi** [comment]
2022-05-19T09:13:36.368 wallet chia.wallet.wallet_node    : WARNING  SpendBundle has been rejected by the FullNode. {'error': 'ALREADY_INCLUDING_TRANSACTION',
 'status': 3,
 'txid': '0x48bfbc4cf296cafab61c2fac21e46e5aec3fd880ea2fdd6b4190ecf4aa4c5ccd'}
2022-05-19T09:13:36.369 wallet chia.wallet.wallet_node    : WARNING  SpendBundle has been rejected by the FullNode. {'error': 'ALREADY_INCLUDING_TRANSACTION',
 'status': 3,
 'txid': '0x48bfbc4cf296cafab61c2fac21e46e5aec3fd880ea2fdd6b4190ecf4aa4c5ccd'}
2022-05-19T09:13:36.370 wallet chia.wallet.wallet_node    : WARNING  SpendBundle has been rejected by the FullNode. {'error': 'ALREADY_INCLUDING_TRANSACTION',
 'status': 3,
 'txid': '0x9c0870e875bc170e6de42da4cb67f24dc7ba7765c63716eab9454e34f979cf92'}
2022-05-19T09:13:36.370 wallet chia.wallet.wallet_node    : WARNING  SpendBundle has been rejected by the FullNode. {'error': 'ALREADY_INCLUDING_TRANSACTION',
 'status': 3,
 'txid': '0x9c0870e875bc170e6de42da4cb67f24dc7ba7765c63716eab9454e34f979cf92'}
2022-05-19T09:14:06.230 wallet chia.wallet.wallet_node    : WARNING  SpendBundle has been rejected by the FullNode. {'error': 'ALREADY_INCLUDING_TRANSACTION',
 'status': 3,
 'txid': '0x48bfbc4cf296cafab61c2fac21e46e5aec3fd880ea2fdd6b4190ecf4aa4c5ccd'}
2022-05-19T09:14:06.231 wallet chia.wallet.wallet_node    : WARNING  SpendBundle has been rejected by the FullNode. {'error': 'DOUBLE_SPEND', 'status': 3, 'txid': '0x4898b35f0c8d16b68c39ab18c0a8a4bcff180abf0c7947a49fdca4cf940c3dd8'}
2022-05-19T09:14:06.237 wallet chia.wallet.wallet_node    : WARNING  SpendBundle has been rejected by the FullNode. {'error': 'ALREADY_INCLUDING_TRANSACTION',
 'status': 3,
 'txid': '0x48bfbc4cf296cafab61c2fac21e46e5aec3fd880ea2fdd6b4190ecf4aa4c5ccd'}
2022-05-19T09:14:06.238 wallet chia.wallet.wallet_node    : WARNING  SpendBundle has been rejected by the FullNode. {'error': 'DOUBLE_SPEND', 'status': 3, 'txid': '0x4898b35f0c8d16b68c39ab18c0a8a4bcff180abf0c7947a49fdca4cf940c3dd8'}
2022-05-19T09:15:42.660 wallet chia.wallet.wallet_node    : WARNING  SpendBundle has been rejected by the FullNode. {'error': 'ALREADY_INCLUDING_TRANSACTION',
 'status': 3,
 'txid': '0x48bfbc4cf296cafab61c2fac21e46e5aec3fd880ea2fdd6b4190ecf4aa4c5ccd'}
2022-05-19T09:15:42.662 wallet chia.wallet.wallet_node    : WARNING  SpendBundle has been rejected by the FullNode. {'error': 'DOUBLE_SPEND', 'status': 3, 'txid': '0xcaee52c88fe6489e7e9213025d096f38ffa9de52d39bb716904774d2ae5d2be5'}
2022-05-19T09:15:42.716 wallet chia.wallet.wallet_node    : WARNING  SpendBundle has been rejected by the FullNode. {'error': 'DOUBLE_SPEND', 'status': 3, 'txid': '0xcaee52c88fe6489e7e9213025d096f38ffa9de52d39bb716904774d2ae5d2be5'}

**Comment by wallentx** [comment]
Are you running your own local node? Can you try to delete any unconfirmed transactions and try to claim after that? If that is still an issue, you may want to delete your wallet DB, and re-sync.

**Comment by chiavivi** [comment]
谢谢 我现在删除钱包数据库，重新同步试一试，看看能不能解决问题！

**Comment by chiavivi** [comment]
问题已经解决，感谢wallentx 提供的解决方法
