### ISSUE TITLE
[Bug]harvester chia.plotting.manager:ERROR

### ISSUE THREAD

**Issue by gmmingg** [Chia-Network/chia-blockchain#11600]
### What happened?

seek help！

thank you

### Version

1.35

### What platform are you using?

Windows

### What ui mode are you using?

GUI

### Relevant log output

```shell
05-22T20:52:41.436 harvester chia.plotting.manager   : ERROR    _refresh_callback raised: 'NoneType' object is not iterable with the traceback: Traceback (most recent call last):
  File "chia\plotting\manager.py", line 233, in _refresh_task
  File "chia\plotting\util.py", line 74, in get_plot_filenames
TypeError: 'NoneType' object is not iterable
```

**Comment by emlowe** [comment]
Please check your config.yaml and make sure you have a "harvester" section.

**Comment by gmmingg** [comment]
![harvester1](https://user-images.githubusercontent.com/106019452/169993466-26e32d71-5b5b-4688-8362-833a778a07af.png)
![harvester2](https://user-images.githubusercontent.com/106019452/169993473-d4172b00-57f5-4ca2-9716-6c5cdcced92a.png)
yes

**Comment by gmmingg** [comment]
> 请检查您的 config.yaml 并确保您有一个“harvester”部分。
![harvester1](https://user-images.githubusercontent.com/106019452/169993935-1b966baa-9147-42f4-ab4a-abfab098231b.png)
![harvester2](https://user-images.githubusercontent.com/106019452/169993938-70a88378-dc80-4056-ba17-3f584e7233d3.png)

**Comment by xdustinface** [comment]
Does the `harvester` section contain `plot_directories`? If so, what is its value?

**Comment by gmmingg** [comment]
> plot_directorie

  plot_directories: null
  plot_loading_frequency_seconds: 120
  port: 8448
  private_ssl_ca:
    crt: config/ssl/ca/private_ca.crt
    key: config/ssl/ca/private_ca.key

**Comment by xdustinface** [comment]
> plot_directories: null

Thats the issue. You need to provide the plot directories there. Not sure how you ended up with `null` but you can either add them manually like 

```
 plot_directories:
 - /path/to/first
 - /path/to/second
```
or just set it to 
 ```
 plot_directories: []
 ```

To fix the error and then add the directories with the CLI/GUI.
