### ISSUE TITLE
[Bug] Unexpected keyword error when cancelling a "Pending Accept" offer

### ISSUE THREAD

**Issue by pmaslana** [Chia-Network/chia-blockchain#11683]
### What happened?

I attempted to cancel a "Pending Accept" offer. The offer fails to cancel and I attempted with and without fees.

### Version

1.3.6386 - NFT Dogfooding Build

### What platform are you using?

Windows

### What ui mode are you using?

GUI

### Relevant log output

```shell
2022-05-27T15:43:27.632 wallet chia.rpc.rpc_server        : WARNING  Error while handling message: Traceback (most recent call last):
  File "chia\rpc\rpc_server.py", line 228, in safe_handle
  File "chia\rpc\rpc_server.py", line 219, in ws_api
  File "chia\rpc\wallet_rpc_api.py", line 1106, in cancel_offer
  File "chia\wallet\trade_manager.py", line 250, in cancel_pending_offer_safely
TypeError: generate_signed_transaction() got an unexpected keyword argument 'ignore_max_send_amount'
```

**Comment by trepca** [comment]
can you try again?
