### ISSUE TITLE
[Bug] Error When Attempting to Mint Multiple NFTs about 20 seconds apart

### ISSUE THREAD

**Issue by pmaslana** [Chia-Network/chia-blockchain#11717]
### What happened?

For this particular scenario, I minted a single NFT, which had no errors associated with it. I then attempted to mint another NFT to the same wallet using a different image and artist address, however, it failed to mint. The second NFT was attempted to be minted about 20 seconds later.

I received this as an error terminal window (not in the log file):
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x000001E8A2C5ECA0>
Traceback (most recent call last):
  File "asyncio\proactor_events.py", line 116, in __del__
  File "asyncio\proactor_events.py", line 108, in close
  File "asyncio\base_events.py", line 751, in call_soon
  File "asyncio\base_events.py", line 515, in _check_closed
RuntimeError: Event loop is closed

### Version

1.3.6386 - NFT1 Dogfooding

### What platform are you using?

Windows

### What ui mode are you using?

CLI

### Relevant log output

```shell
The first NFT mint:
2022-05-31T12:52:06.791 wallet chia.wallet.wallet         : INFO     About to sign a transaction: [CoinSpend(coin=Coin(parent_coin_info=<bytes32: d5a1150cda4531d059f7388e5323103f0ccfd74c69c3f327ef0348ca2d4efd22>,
SpendBundle has been received and accepted to mempool by the FullNode. {'error': None,
'status': 1, 'txid': '0xcd4ebfd96b1dc0356626642391eb84a535f7ecdeb335ae2868d94a14db87f1ed'}

The second (failed) NFT mint
2022-05-31T12:52:27.533 wallet chia.wallet.wallet         : INFO     About to sign a transaction: [CoinSpend(coin=Coin(parent_coin_info=<bytes32: d5a1150cda4531d059f7388e5323103f0ccfd74c69c3f327ef0348ca2d4efd22>,
SpendBundle has been received (and is pending) by the FullNode. {'error':
'MEMPOOL_CONFLICT', 'status': 2, 'txid': '0xe8a5ad814548e4f80526085bd079e137ca53cdec8b5aaf1bbc5dee070a52a05e'}

The parent coin appears to be the same for both transactions, but the 'txid' is different.
```

**Comment by trepca** [comment]
@pmaslana did you provide a fee? 
@ytx1991 any ideas re parent coins being the same?

**Comment by pmaslana** [comment]
Parent coin is still utilized until the transaction is fully processed.
