### ISSUE TITLE
[BUG] `chia wallet get_transactions` crashes

### ISSUE THREAD

**Issue by matteomonti** [Chia-Network/chia-blockchain#1176]
On a Raspberry Pi 4, RC5 installed, whenever I run `chia wallet get_transactions` I get the following:
```usage: chia [-h] [--database_path DATABASE_PATH] [--full_node_peer.host FULL_NODE_PEER.HOST] [--full_node_peer.port FULL_NODE_PEER.PORT] [--initial_num_public_keys INITIAL_NUM_PUBLIC_KEYS]
            [--initial_num_public_keys_new_wallet INITIAL_NUM_PUBLIC_KEYS_NEW_WALLET] [--introducer_peer.host INTRODUCER_PEER.HOST] [--introducer_peer.port INTRODUCER_PEER.PORT] [--logging.log_filename LOGGING.LOG_FILENAME]
            [--logging.log_level LOGGING.LOG_LEVEL] [--logging.log_stdout LOGGING.LOG_STDOUT] [--network_overrides.config.mainnet.address_prefix NETWORK_OVERRIDES.CONFIG.MAINNET.ADDRESS_PREFIX]
            [--network_overrides.config.testnet0.address_prefix NETWORK_OVERRIDES.CONFIG.TESTNET0.ADDRESS_PREFIX] [--network_overrides.config.testnet4.address_prefix NETWORK_OVERRIDES.CONFIG.TESTNET4.ADDRESS_PREFIX]
            [--network_overrides.config.testnet5.address_prefix NETWORK_OVERRIDES.CONFIG.TESTNET5.ADDRESS_PREFIX] [--network_overrides.constants.mainnet.GENESIS_CHALLENGE NETWORK_OVERRIDES.CONSTANTS.MAINNET.GENESIS_CHALLENGE]
            [--network_overrides.constants.mainnet.NETWORK_TYPE NETWORK_OVERRIDES.CONSTANTS.MAINNET.NETWORK_TYPE] [--network_overrides.constants.testnet0.GENESIS_CHALLENGE NETWORK_OVERRIDES.CONSTANTS.TESTNET0.GENESIS_CHALLENGE]
            [--network_overrides.constants.testnet0.MIN_PLOT_SIZE NETWORK_OVERRIDES.CONSTANTS.TESTNET0.MIN_PLOT_SIZE] [--network_overrides.constants.testnet0.NETWORK_TYPE NETWORK_OVERRIDES.CONSTANTS.TESTNET0.NETWORK_TYPE]
            [--network_overrides.constants.testnet5.GENESIS_CHALLENGE NETWORK_OVERRIDES.CONSTANTS.TESTNET5.GENESIS_CHALLENGE]
            [--network_overrides.constants.testnet5.GENESIS_PRE_FARM_FARMER_PUZZLE_HASH NETWORK_OVERRIDES.CONSTANTS.TESTNET5.GENESIS_PRE_FARM_FARMER_PUZZLE_HASH]
            [--network_overrides.constants.testnet5.GENESIS_PRE_FARM_POOL_PUZZLE_HASH NETWORK_OVERRIDES.CONSTANTS.TESTNET5.GENESIS_PRE_FARM_POOL_PUZZLE_HASH]
            [--network_overrides.constants.testnet5.NETWORK_TYPE NETWORK_OVERRIDES.CONSTANTS.TESTNET5.NETWORK_TYPE] [--num_sync_batches NUM_SYNC_BATCHES] [--peer_connect_interval PEER_CONNECT_INTERVAL] [--port PORT]
            [--recent_peer_threshold RECENT_PEER_THRESHOLD] [--rpc_port RPC_PORT] [--selected_network SELECTED_NETWORK] [--ssl.private_crt SSL.PRIVATE_CRT] [--ssl.private_key SSL.PRIVATE_KEY] [--ssl.public_crt SSL.PUBLIC_CRT]
            [--ssl.public_key SSL.PUBLIC_KEY] [--start_height_buffer START_HEIGHT_BUFFER] [--starting_height STARTING_HEIGHT] [--target_peer_count TARGET_PEER_COUNT] [--testing TESTING] [--wallet_peers_path WALLET_PEERS_PATH]
chia: error: unrecognized arguments: wallet get_transactions
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0xffff84db9190>
Unclosed connector
connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0xffff84d7d280>, 599122.308445141)]']
connector: <aiohttp.connector.TCPConnector object at 0xffff84db94c0>
Fatal error on SSL transport
protocol: <asyncio.sslproto.SSLProtocol object at 0xffff84db96a0>
transport: <_SelectorSocketTransport closing fd=6>
Traceback (most recent call last):
  File "/usr/lib/python3.8/asyncio/selector_events.py", line 908, in write
    n = self._sock.send(data)
OSError: [Errno 9] Bad file descriptor

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/asyncio/sslproto.py", line 685, in _process_write_backlog
    self._transport.write(chunk)
  File "/usr/lib/python3.8/asyncio/selector_events.py", line 914, in write
    self._fatal_error(exc, 'Fatal write error on socket transport')
  File "/usr/lib/python3.8/asyncio/selector_events.py", line 709, in _fatal_error
    self._force_close(exc)
  File "/usr/lib/python3.8/asyncio/selector_events.py", line 721, in _force_close
    self._loop.call_soon(self._call_connection_lost, exc)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 719, in call_soon
    self._check_closed()
  File "/usr/lib/python3.8/asyncio/base_events.py", line 508, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed```

**Comment by zachlankton** [comment]
+1 I'm also experiencing the same bug

**Comment by mariano54** [comment]
Fixed: https://github.com/Chia-Network/chia-blockchain/pull/1178
