### ISSUE TITLE
[Bug] issue with creating a plot

### ISSUE THREAD

**Issue by AlexeyGanovich** [Chia-Network/chia-blockchain#11846]
### What happened?

Hi. I have an issue with creating a plot. After starting creating i have the crit error. Can you help me? thx

Windows 10 pro
v. 1.3.5

### Version

1.3.5

### What platform are you using?

Windows

### What ui mode are you using?

GUI

### Relevant log output

```shell
Multi-threaded pipelined Chia k32 plotter - 2092041
Network Port: 8444
Final Directory: A:
Number of Plots: 1
Crafting plot 1 out of 1 (2022/06/01 14:05:54)
Process ID: 11896
Number of Threads: 4
Number of Buckets P1: 2^8 (256)
Number of Buckets P3+P4: 2^8 (256)
Pool Puzzle Hash: 25f259640233639a275e55dbcbfdc076654ca9ccb2bb335f77be39438d8b430d
Farmer Public Key: ef20c3718803
Working Directory: X:
Working Directory 2: X:
Plot Name: plot-k32-2022-06-01-14-05-9598f450302f242242fcb8987b8fd94524b48eb2c1aea949b44de26062a4ad0e
[P1] Table 1 took 30.2935 sec
Progress update: 0.01
[P1] Table 2 took 220.384 sec, found 4294990385 matches
Progress update: 0.06
[P1] Table 3 took 273.126 sec, found 4295037759 matches
Progress update: 0.12
[P1] Table 4 took 260.14 sec, found 4295002977 matches
Progress update: 0.2
[P1] Table 5 took 273.705 sec, found 4294918294 matches
Progress update: 0.28
[P1] Table 6 took 271.365 sec, found 4294913334 matches
Progress update: 0.36
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x0000020F5E20C5E0>
Fatal error on SSL transport
protocol: <asyncio.sslproto.SSLProtocol object at 0x0000020F5E20CAC0>
transport: <_ProactorSocketTransport fd=-1 read=<_OverlappedFuture cancelled>>
Traceback (most recent call last):
File "asyncio\sslproto.py", line 690, in _process_write_backlog
File "asyncio\proactor_events.py", line 359, in write
File "asyncio\proactor_events.py", line 395, in _loop_writing
AttributeError: 'NoneType' object has no attribute 'send'
Exception ignored in: <function _SSLProtocolTransport.del at 0x0000020F5CBA5EE0>
Traceback (most recent call last):
File "asyncio\sslproto.py", line 321, in del
File "asyncio\sslproto.py", line 316, in close
File "asyncio\sslproto.py", line 599, in _start_shutdown
File "asyncio\sslproto.py", line 604, in _write_appdata
File "asyncio\sslproto.py", line 712, in _process_write_backlog
File "asyncio\sslproto.py", line 726, in _fatal_error
File "asyncio\proactor_events.py", line 151, in _force_close
File "asyncio\base_events.py", line 751, in call_soon
File "asyncio\base_events.py", line 515, in _check_closed
RuntimeError: Event loop is closed
```

**Comment by AlexeyGanovich** [comment]
> It might be that your daemon crashed. Can you attempt to do a full system reboot, and attempt to create a plot again and see if you still get this issue?
I was doing a reboot. But the error still remains

**Comment by AlexeyGanovich** [comment]
issue is still affecting me

**Comment by AlexeyGanovich** [comment]
issue is still affecting me

**Comment by wallentx** [comment]
The error that you are showing seems to indicate that the GUI is having issues reporting back the status of the plotter. This could be due to the wallet service when your system is under heavy load. Are you able to provide some details about the specs of your system? Have you attempted to create the plots from the CLI?
