### ISSUE TITLE
[Bug] 1.3.6 crazy error

### ISSUE THREAD

**Issue by 0X1231** [Chia-Network/chia-blockchain#11987]
### What happened?

2022-06-20T22:03:14.667 wallet chia.wallet.wallet_node    : ERROR    Exception handling None, Task <Task pending name='Task-15' coro=<WalletNode._process_new_subscriptions() running at chia\wallet\wallet_node.py:346>> got Future <Future pending> attached to a different loop Traceback (most recent call last):
  File "chia\wallet\wallet_node.py", line 346, in _process_new_subscriptions
  File "chia\wallet\util\new_peak_queue.py", line 70, in get
  File "asyncio\queues.py", line 166, in get
RuntimeError: Task <Task pending name='Task-15' coro=<WalletNode._process_new_subscriptions() running at chia\wallet\wallet_node.py:346>> got Future <Future pending> attached to a different loop

2022-06-20T22:03:14.668 wallet chia.wallet.wallet_node    : ERROR    Exception handling None, Task <Task pending name='Task-15' coro=<WalletNode._process_new_subscriptions() running at chia\wallet\wallet_node.py:346>> got Future <Future pending> attached to a different loop Traceback (most recent call last):
  File "chia\wallet\wallet_node.py", line 346, in _process_new_subscriptions
  File "chia\wallet\util\new_peak_queue.py", line 70, in get
  File "asyncio\queues.py", line 166, in get
RuntimeError: Task <Task pending name='Task-15' coro=<WalletNode._process_new_subscriptions() running at chia\wallet\wallet_node.py:346>> got Future <Future pending> attached to a different loop

2022-06-20T22:03:14.669 wallet chia.wallet.wallet_node    : ERROR    Exception handling None, Task <Task pending name='Task-15' coro=<WalletNode._process_new_subscriptions() running at chia\wallet\wallet_node.py:346>> got Future <Future pending> attached to a different loop Traceback (most recent call last):
  File "chia\wallet\wallet_node.py", line 346, in _process_new_subscriptions
  File "chia\wallet\util\new_peak_queue.py", line 70, in get
  File "asyncio\queues.py", line 166, in get
RuntimeError: Task <Task pending name='Task-15' coro=<WalletNode._process_new_subscriptions() running at chia\wallet\wallet_node.py:346>> got Future <Future pending> attached to a different loop

2022-06-20T22:03:14.670 wallet chia.wallet.wallet_node    : ERROR    Exception handling None, Task <Task pending name='Task-15' coro=<WalletNode._process_new_subscriptions() running at chia\wallet\wallet_node.py:346>> got Future <Future pending> attached to a different loop Traceback (most recent call last):
  File "chia\wallet\wallet_node.py", line 346, in _process_new_subscriptions
  File "chia\wallet\util\new_peak_queue.py", line 70, in get
  File "asyncio\queues.py", line 166, in get
RuntimeError: Task <Task pending name='Task-15' coro=<WalletNode._process_new_subscriptions() running at chia\wallet\wallet_node.py:346>> got Future <Future pending> attached to a different loop

2022-06-20T22:03:14.671 wallet chia.wallet.wallet_node    : ERROR    Exception handling None, Task <Task pending name='Task-15' coro=<WalletNode._process_new_subscriptions() running at chia\wallet\wallet_node.py:346>> got Future <Future pending> attached to a different loop Traceback (most recent call last):
  File "chia\wallet\wallet_node.py", line 346, in _process_new_subscriptions
  File "chia\wallet\util\new_peak_queue.py", line 70, in get
  File "asyncio\queues.py", line 166, in get
RuntimeError: Task <Task pending name='Task-15' coro=<WalletNode._process_new_subscriptions() running at chia\wallet\wallet_node.py:346>> got Future <Future pending> attached to a different loop

2022-06-20T22:03:14.674 wallet chia.wallet.wallet_node    : ERROR    Exception handling None, Task <Task pending name='Task-15' coro=<WalletNode._process_new_subscriptions() running at chia\wallet\wallet_node.py:346>> got Future <Future pending> attached to a different loop Traceback (most recent call last):
  File "chia\wallet\wallet_node.py", line 346, in _process_new_subscriptions
  File "chia\wallet\util\new_peak_queue.py", line 70, in get
  File "asyncio\queues.py", line 166, in get
RuntimeError: Task <Task pending name='Task-15' coro=<WalletNode._process_new_subscriptions() running at chia\wallet\wallet_node.py:346>> got Future <Future pending> attached to a different loop

2022-06-20T22:03:14.677 wallet chia.wallet.wallet_node    : ERROR    Exception handling None, Task <Task pending name='Task-15' coro=<WalletNode._process_new_subscriptions() running at chia\wallet\wallet_node.py:346>> got Future <Future pending> attached to a different loop Traceback (most recent call last):
  File "chia\wallet\wallet_node.py", line 346, in _process_new_subscriptions
  File "chia\wallet\util\new_peak_queue.py", line 70, in get
  File "asyncio\queues.py", line 166, in get
RuntimeError: Task <Task pending name='Task-15' coro=<WalletNode._process_new_subscriptions() running at chia\wallet\wallet_node.py:346>> got Future <Future pending> attached to a different loop

### Version

1.3.6

### What platform are you using?

Windows

### What ui mode are you using?

GUI

### Relevant log output

```shell
2022-06-20T22:03:14.669 wallet chia.wallet.wallet_node    : ERROR    Exception handling None, Task <Task pending name='Task-15' coro=<WalletNode._process_new_subscriptions() running at chia\wallet\wallet_node.py:346>> got Future <Future pending> attached to a different loop Traceback (most recent call last):
  File "chia\wallet\wallet_node.py", line 346, in _process_new_subscriptions
  File "chia\wallet\util\new_peak_queue.py", line 70, in get
  File "asyncio\queues.py", line 166, in get
RuntimeError: Task <Task pending name='Task-15' coro=<WalletNode._process_new_subscriptions() running at chia\wallet\wallet_node.py:346>> got Future <Future pending> attached to a different loop

2022-06-20T22:03:14.670 wallet chia.wallet.wallet_node    : ERROR    Exception handling None, Task <Task pending name='Task-15' coro=<WalletNode._process_new_subscriptions() running at chia\wallet\wallet_node.py:346>> got Future <Future pending> attached to a different loop Traceback (most recent call last):
  File "chia\wallet\wallet_node.py", line 346, in _process_new_subscriptions
  File "chia\wallet\util\new_peak_queue.py", line 70, in get
  File "asyncio\queues.py", line 166, in get
RuntimeError: Task <Task pending name='Task-15' coro=<WalletNode._process_new_subscriptions() running at chia\wallet\wallet_node.py:346>> got Future <Future pending> attached to a different loop

2022-06-20T22:03:14.671 wallet chia.wallet.wallet_node    : ERROR    Exception handling None, Task <Task pending name='Task-15' coro=<WalletNode._process_new_subscriptions() running at chia\wallet\wallet_node.py:346>> got Future <Future pending> attached to a different loop Traceback (most recent call last):
  File "chia\wallet\wallet_node.py", line 346, in _process_new_subscriptions
  File "chia\wallet\util\new_peak_queue.py", line 70, in get
  File "asyncio\queues.py", line 166, in get
RuntimeError: Task <Task pending name='Task-15' coro=<WalletNode._process_new_subscriptions() running at chia\wallet\wallet_node.py:346>> got Future <Future pending> attached to a different loop

2022-06-20T22:03:14.674 wallet chia.wallet.wallet_node    : ERROR    Exception handling None, Task <Task pending name='Task-15' coro=<WalletNode._process_new_subscriptions() running at chia\wallet\wallet_node.py:346>> got Future <Future pending> attached to a different loop Traceback (most recent call last):
  File "chia\wallet\wallet_node.py", line 346, in _process_new_subscriptions
  File "chia\wallet\util\new_peak_queue.py", line 70, in get
  File "asyncio\queues.py", line 166, in get
RuntimeError: Task <Task pending name='Task-15' coro=<WalletNode._process_new_subscriptions() running at chia\wallet\wallet_node.py:346>> got Future <Future pending> attached to a different loop

2022-06-20T22:03:14.677 wallet chia.wallet.wallet_node    : ERROR    Exception handling None, Task <Task pending name='Task-15' coro=<WalletNode._process_new_subscriptions() running at chia\wallet\wallet_node.py:346>> got Future <Future pending> attached to a different loop Traceback (most recent call last):
  File "chia\wallet\wallet_node.py", line 346, in _process_new_subscriptions
  File "chia\wallet\util\new_peak_queue.py", line 70, in get
  File "asyncio\queues.py", line 166, in get
RuntimeError: Task <Task pending name='Task-15' coro=<WalletNode._process_new_subscriptions() running at chia\wallet\wallet_node.py:346>> got Future <Future pending> attached to a different loop

2022-06-20T22:03:14.679 wallet chia.wallet.wallet_node    : ERROR    Exception handling None, Task <Task pending name='Task-15' coro=<WalletNode._process_new_subscriptions() running at chia\wallet\wallet_node.py:346>> got Future <Future pending> attached to a different loop Traceback (most recent call last):
  File "chia\wallet\wallet_node.py", line 346, in _process_new_subscriptions
  File "chia\wallet\util\new_peak_queue.py", line 70, in get
  File "asyncio\queues.py", line 166, in get
RuntimeError: Task <Task pending name='Task-15' coro=<WalletNode._process_new_subscriptions() running at chia\wallet\wallet_node.py:346>> got Future <Future pending> attached to a different loop
```

**Comment by Drhicom** [comment]
Which beta version of 1.3.6XXX ?

**Comment by reubes** [comment]
Same thing when I upgraded just now to 1.3.6.dev871. Had only just installed the latest upgrade from main a couple days ago without any problem then. Also this time popped back up that it needed to fix ssl permissions this time.

**Comment by 0X1231** [comment]
> 哪个 beta 版本的 1.3.6XXX ？

1.3.6871

**Comment by 0X1231** [comment]
1.3.6935问题仍然存在

**Comment by 0X1231** [comment]
仍然存在

**Comment by wallentx** [comment]
Duplicate of https://github.com/Chia-Network/chia-blockchain/issues/11980
