### ISSUE TITLE
[Bug] Errors in Log file from latest Beta

### ISSUE THREAD

**Issue by Drhicom** [Chia-Network/chia-blockchain#11980]
### What happened?

Errors in log file with latest betas

### Version

1.3.6871

### What platform are you using?

Windows

### What ui mode are you using?

GUI

### Relevant log output

```shell
2022-06-19T15:24:43.048 wallet chia.wallet.wallet_node    : ERROR    Exception handling None, Task <Task pending name='Task-17' coro=<WalletNode._process_new_subscriptions() running at chia\wallet\wallet_node.py:346>> got Future <Future pending> attached to a different loop Traceback (most recent call last):
  File "chia\wallet\wallet_node.py", line 346, in _process_new_subscriptions
  File "chia\wallet\util\new_peak_queue.py", line 70, in get
  File "asyncio\queues.py", line 166, in get
RuntimeError: Task <Task pending name='Task-17' coro=<WalletNode._process_new_subscriptions() running at chia\wallet\wallet_node.py:346>> got Future <Future pending> attached to a different loop

2022-06-19T15:24:43.054 wallet chia.wallet.wallet_node    : ERROR    Exception handling None, Task <Task pending name='Task-17' coro=<WalletNode._process_new_subscriptions() running at chia\wallet\wallet_node.py:346>> got Future <Future pending> attached to a different loop Traceback (most recent call last):
  File "chia\wallet\wallet_node.py", line 346, in _process_new_subscriptions
  File "chia\wallet\util\new_peak_queue.py", line 70, in get
  File "asyncio\queues.py", line 166, in get
RuntimeError: Task <Task pending name='Task-17' coro=<WalletNode._process_new_subscriptions() running at chia\wallet\wallet_node.py:346>> got Future <Future pending> attached to a different loop

2022-06-19T15:24:43.058 wallet chia.wallet.wallet_node    : ERROR    Exception handling None, Task <Task pending name='Task-17' coro=<WalletNode._process_new_subscriptions() running at chia\wallet\wallet_node.py:346>> got Future <Future pending> attached to a different loop Traceback (most recent call last):
  File "chia\wallet\wallet_node.py", line 346, in _process_new_subscriptions
  File "chia\wallet\util\new_peak_queue.py", line 70, in get
  File "asyncio\queues.py", line 166, in get
RuntimeError: Task <Task pending name='Task-17' coro=<WalletNode._process_new_subscriptions() running at chia\wallet\wallet_node.py:346>> got Future <Future pending> attached to a different loop

2022-06-19T15:24:43.059 wallet chia.wallet.wallet_node    : ERROR    Exception handling None, Task <Task pending name='Task-17' coro=<WalletNode._process_new_subscriptions() running at chia\wallet\wallet_node.py:346>> got Future <Future pending> attached to a different loop Traceback (most recent call last):
  File "chia\wallet\wallet_node.py", line 346, in _process_new_subscriptions
  File "chia\wallet\util\new_peak_queue.py", line 70, in get
  File "asyncio\queues.py", line 166, in get
RuntimeError: Task <Task pending name='Task-17' coro=<WalletNode._process_new_subscriptions() running at chia\wallet\wallet_node.py:346>> got Future <Future pending> attached to a different loop

2022-06-19T15:24:43.060 wallet chia.wallet.wallet_node    : ERROR    Exception handling None, Task <Task pending name='Task-17' coro=<WalletNode._process_new_subscriptions() running at chia\wallet\wallet_node.py:346>> got Future <Future pending> attached to a different loop Traceback (most recent call last):
  File "chia\wallet\wallet_node.py", line 346, in _process_new_subscriptions
  File "chia\wallet\util\new_peak_queue.py", line 70, in get
  File "asyncio\queues.py", line 166, in get
RuntimeError: Task <Task pending name='Task-17' coro=<WalletNode._process_new_subscriptions() running at chia\wallet\wallet_node.py:346>> got Future <Future pending> attached to a different loop
```

**Comment by Chardmw** [comment]
I am have the same issue running GUI on Unbuntu. 1.3.6 dev859
I see the same log ERRORs. I see the error in Wallet only and Full node. I also tried deleting the Wallet db and resync.

**Comment by 0X1231** [comment]
> 
删除钱包数据库重新同步我也试过，但是问题依然存在。

**Comment by wallentx** [comment]
Are you experiencing some particular behavior that is problematic that correlates with these error logs?

**Comment by 0X1231** [comment]
> 
Haven't noticed any specific behavior

**Comment by Jacek-ghub** [comment]
> Are you experiencing some particular behavior that is problematic that correlates with these error logs?

You are kidding, aren't you?  You don't control your code, and every few milliseconds flush the logs with not handled garbage, and you still dare to ask whether it correlates with something?

Since the very first dust storms last year, those excessive logs were identified as part of the problem hosing nodes, as those are basically choking the drive that hosts bc / wallet db, and you still don't have rate control, duplicated messages control, or chunk control in your logs?

**Comment by 0X1231** [comment]
This is indeed an urgent problem to be solved
