### ISSUE TITLE
[Bug] Endless spinner on offer screen after accepting offer

### ISSUE THREAD

**Issue by paulhainsworth-chia** [Chia-Network/chia-blockchain#12005]
### What happened?

Open an offer file
Add 0.1 TXCH fee
Accept offer

Outcome:
- endless spinner on the action button
- clicking back onto another screen clear it

### Version

dev686

### What platform are you using?

macOS

### What ui mode are you using?

GUI

### Relevant log output

```shell
2022-06-21T18:09:19.457 wallet wallet_server              : WARNING  Invalid handshake with peer {'host': '27.159.122.188', 'port': 8444}. Maybe the peer is running old software.
2022-06-21T18:09:29.982 wallet wallet_server              : WARNING  Invalid handshake with peer {'host': '73.170.236.49', 'port': 8444}. Maybe the peer is running old software.
2022-06-21T18:09:36.005 wallet wallet_server              : WARNING  Invalid handshake with peer {'host': '88.212.140.82', 'port': 8444}. Maybe the peer is running old software.
2022-06-21T18:09:36.986 wallet chia.wallet.wallet_node    : WARNING  SpendBundle has been rejected by the FullNode. {'error': 'DOUBLE_SPEND', 'status': 3, 'txid': '0x9a60523e2c3aeb98a177614b5394e7f033e99dc10680ae790245f293732f5ed6'}
2022-06-21T18:10:36.451 wallet chia.wallet.wallet_node    : WARNING  Peer None did not respond in time.
2022-06-21T18:10:36.470 wallet chia.wallet.wallet_node    : WARNING  Peer None did not respond in time.
2022-06-21T18:15:29.050 daemon __main__                   : ERROR    Ping error
Traceback (most recent call last):
  File "chia/daemon/server.py", line 284, in ping_task
  File "aiohttp/web_ws.py", line 295, in ping
  File "aiohttp/http_websocket.py", line 676, in ping
  File "aiohttp/http_websocket.py", line 653, in _send_frame
  File "aiohttp/http_websocket.py", line 663, in _write
ConnectionResetError: Cannot write to closing transport
2022-06-21T18:15:29.053 daemon __main__                   : ERROR    Ping failed, connection closed.
```

**Comment by paninaro** [comment]
Should be fixed in the 983ed87c build. Sebastjan's puzzle hash derivation fix addresses the timeout.
