### ISSUE TITLE
Error after minting NFT - RuntimeError: Event loop is closed

### ISSUE THREAD

**Issue by wallentx** [Chia-Network/chia-blockchain#12009]
### What happened?

On winders, I minted an NFT and got an error output, but everything seemed to have worked just fine(?)
https://test.skynft.org/item.php?launcher_id=bb6fc35e177beaa24e93d1b5a95cf325ac90856184311a12ebb2f4c3356a2853

@wjblanke found the following:
https://github.com/aio-libs/aiohttp/issues/6635
> recommends sleep(.25)?

https://docs.aiohttp.org/en/stable/client_advanced.html#graceful-shutdown
> Note that the appropriate amount of time to wait will vary from application to application.

### Version

1.3.6671

### What platform are you using?

Windows

### What ui mode are you using?

CLI

### Relevant log output

```shell
.\chia rpc wallet nft_mint_nft '{
  \"wallet_id\": 7,
  \"uris\": [
    \"https://lh3.googleusercontent.com/59H4vAxqBvyD5BKXCxHVMrZzWSS0BG5izhAms0FFsq0Hy71YgaiuRBGES7KJJY0oT5TkrNPIj3lVLUMG2nyljWu3I1jRgvr45NYm=s0\"
  ],
  \"series_total\": 12,
  \"series_number\": 1,
  \"hash\": \"24e04e8a50fbba39dfdef8759362236fb4ca8b2d4a02391a19bf4b7375ea97bb\",
  \"artist_percentage\": 1500,
  \"artist_address\": \"txch1yxpslrx30k7lnngpfczr3ltrge0ap25f4739jet5lz069lhn5szsu49uyh\"

}'
{
    "spend_bundle": {
        "aggregated_signature": "0x834a3be681a38f7cc10b338644619c35a057c0f89bbebee7ae8abf46d38d08a6c9d21740b8b6b239376c7bc7a9843c85123d0044ae40e0fe9115ebda24a5eb9d69d47fefe154cdc966cdb4c6253d619c834b53266eb4a2ffc97d6f7124c8cdf5",
        "coin_solutions": [
            {
                "coin": {
                    "amount": 999999999999,
                    "parent_coin_info": "0xd9ad384705f0013c1e69433bbacc2ff2e1e0c7b0791622e78be9e05297fd179b",
                    "puzzle_hash": "0x26fbaa149a5a1dd9cd30463cc6f49502c63f0dded3cce47e3a1d018c8447a8b5"
                },
                "puzzle_reveal": "0xff02ffff01ff02ffff01ff02ffff03ff0bffff01ff02ffff03ffff09ff05ffff1dff0bffff1effff0bff0bffff02ff06ffff04ff02ffff04ff17ff8080808080808080ffff01ff02ff17ff2f80ffff01ff088080ff0180ffff01ff04ffff04ff04ffff04ff05ffff04ffff02ff06ffff04ff02ffff04ff17ff80808080ff80808080ffff02ff17ff2f808080ff0180ffff04ffff01ff32ff02ffff03ffff07ff0580ffff01ff0bffff0102ffff02ff06ffff04ff02ffff04ff09ff80808080ffff02ff06ffff04ff02ffff04ff0dff8080808080ffff01ff0bffff0101ff058080ff0180ff018080ffff04ffff01b0b22c60a260f94c4da89b26684aef0669a75acb552e3049455bbb1780038dfed1a67e49120ba888ac2c81007e3af57ad8ff018080",
                "solution": "0xff80ffff01ffff33ffa0eff07522495060c066f66f32acc2a77e3a3e737aca8baea4d1a64ea4cdc13da9ff0180ffff33ffa0a0c0999a1dac63f5c2e86737fdc11f6761a477567ec23c564dc3f8e55ef276cbff8600e8d4a50ffe80ffff3cffa0334691c6f3243ab181563cbe1d9a7dee62e70fed8f6c043dcc3823a90280346f80ffff3dffa05514a8689a598ad1b2f9ba5b2626efcd5a32edcfc1a18e9f64d96813be52feef8080ff8080"
            },
            {
                "coin": {
                    "amount": 1,
                    "parent_coin_info": "0xc0a9550c629004468d6300d61fbcbf0195852a104d4287170313af69c9f321d4",
                    "puzzle_hash": "0xeff07522495060c066f66f32acc2a77e3a3e737aca8baea4d1a64ea4cdc13da9"
                },
                "puzzle_reveal": "0xff02ffff01ff04ffff04ff04ffff04ff05ffff04ff0bff80808080ffff04ffff04ff0affff04ffff02ff0effff04ff02ffff04ffff04ff05ffff04ff0bffff04ff17ff80808080ff80808080ff808080ff808080ffff04ffff01ff33ff3cff02ffff03ffff07ff0580ffff01ff0bffff0102ffff02ff0effff04ff02ffff04ff09ff80808080ffff02ff0effff04ff02ffff04ff0dff8080808080ffff01ff0bffff0101ff058080ff0180ff018080",
                "solution": "0xffa0ead0a7158df372fbff7d3edd1081178f95180e5f1747d735b7f12ed35c59a352ff01ff8080"
            },
            {
                "coin": {
                    "amount": 1,
                    "parent_coin_info": "0xbb6fc35e177beaa24e93d1b5a95cf325ac90856184311a12ebb2f4c3356a2853",
                    "puzzle_hash": "0xead0a7158df372fbff7d3edd1081178f95180e5f1747d735b7f12ed35c59a352"
                },
                "puzzle_reveal": "0xff02ffff01ff02ffff01ff02ffff03ffff18ff2fff3c80ffff01ff04ffff04ff10ffff04ff2fff808080ffff04ffff02ff3effff04ff02ffff04ff05ffff04ffff0bff27ffff02ffff03ff77ffff01ff02ff36ffff04ff02ffff04ff09ffff04ff57ffff04ffff02ff2effff04ff02ffff04ff05ff80808080ff808080808080ffff011d80ff0180ffff02ffff03ff77ffff0181b7ffff015780ff018080ffff04ff77ff808080808080ffff02ff26ffff04ff02ffff04ff05ffff04ffff02ff0bff5f80ffff01ff8080808080808080ffff01ff088080ff0180ffff04ffff01ffffff49ff4702ff33ff0401ffff01ff02ff02ffff03ff05ffff01ff02ff3affff04ff02ffff04ff0dffff04ffff0bff2affff0bff3cff2c80ffff0bff2affff0bff2affff0bff3cff1280ff0980ffff0bff2aff0bffff0bff3cff8080808080ff8080808080ffff010b80ff0180ffffff02ffff03ff0bffff01ff02ffff03ffff02ffff03ffff09ff23ff1480ffff01ff02ffff03ffff18ff81b3ff3c80ffff01ff0101ff8080ff0180ff8080ff0180ffff01ff02ffff03ffff20ff1780ffff01ff02ffff03ffff09ff81b3ffff01818f80ffff01ff02ff26ffff04ff02ffff04ff05ffff04ff1bffff04ff3cff808080808080ffff01ff04ffff04ff23ffff04ffff02ff36ffff04ff02ffff04ff09ffff04ff53ffff04ffff02ff2effff04ff02ffff04ff05ff80808080ff808080808080ff738080ffff02ff26ffff04ff02ffff04ff05ffff04ff1bffff04ff3cff8080808080808080ff0180ffff01ff088080ff0180ffff01ff04ff13ffff02ff26ffff04ff02ffff04ff05ffff04ff1bffff04ff17ff8080808080808080ff0180ffff01ff02ffff03ff17ff80ffff01ff088080ff018080ff0180ff0bff2affff0bff3cff3880ffff0bff2affff0bff2affff0bff3cff1280ff0580ffff0bff2affff02ff3affff04ff02ffff04ff07ffff04ffff0bff3cff3c80ff8080808080ffff0bff3cff8080808080ffff02ffff03ffff07ff0580ffff01ff0bffff0102ffff02ff2effff04ff02ffff04ff09ff80808080ffff02ff2effff04ff02ffff04ff0dff8080808080ffff01ff0bff3cff058080ff0180ff02ffff03ffff21ff17ffff09ff0bff158080ffff01ff04ff28ffff04ff0bff808080ffff01ff088080ff0180ff018080ffff04ffff01ffa0f1e8350cec62f8204aaf867cc3c12cae369f619258206616108c6cfd7be760b3ffa0bb6fc35e177beaa24e93d1b5a95cf325ac90856184311a12ebb2f4c3356a2853a0eff07522495060c066f66f32acc2a77e3a3e737aca8baea4d1a64ea4cdc13da9ffff04ffff01ff02ffff01ff02ffff01ff02ff3effff04ff02ffff04ff05ffff04ffff02ff2fff5f80ffff04ff80ffff04ffff04ffff04ff0bffff04ff17ff808080ffff01ff808080ffff01ff8080808080808080ffff04ffff01ffffff0233ff04ff0101ffff02ff02ffff03ff05ffff01ff02ff1affff04ff02ffff04ff0dffff04ffff0bff12ffff0bff2cff1480ffff0bff12ffff0bff12ffff0bff2cff3c80ff0980ffff0bff12ff0bffff0bff2cff8080808080ff8080808080ffff010b80ff0180ffff0bff12ffff0bff2cff1080ffff0bff12ffff0bff12ffff0bff2cff3c80ff0580ffff0bff12ffff02ff1affff04ff02ffff04ff07ffff04ffff0bff2cff2c80ff8080808080ffff0bff2cff8080808080ffff02ffff03ffff07ff0580ffff01ff0bffff0102ffff02ff2effff04ff02ffff04ff09ff80808080ffff02ff2effff04ff02ffff04ff0dff8080808080ffff01ff0bffff0101ff058080ff0180ff02ffff03ff0bffff01ff02ffff03ffff09ff23ff1880ffff01ff02ffff03ffff18ff81b3ff2c80ffff01ff02ffff03ffff20ff1780ffff01ff02ff3effff04ff02ffff04ff05ffff04ff1bffff04ff33ffff04ff2fffff04ff5fff8080808080808080ffff01ff088080ff0180ffff01ff04ff13ffff02ff3effff04ff02ffff04ff05ffff04ff1bffff04ff17ffff04ff2fffff04ff5fff80808080808080808080ff0180ffff01ff02ffff03ffff09ff23ffff0181e880ffff01ff02ff3effff04ff02ffff04ff05ffff04ff1bffff04ff17ffff04ffff02ffff03ffff22ffff09ffff02ff2effff04ff02ffff04ff53ff80808080ff82014f80ffff20ff5f8080ffff01ff02ff53ffff04ff818fffff04ff82014fffff04ff81b3ff8080808080ffff01ff088080ff0180ffff01ff0180808080808080ffff01ff04ff13ffff02ff3effff04ff02ffff04ff05ffff04ff1bffff04ff17ffff04ff2fffff04ff5fff80808080808080808080ff018080ff0180ffff01ff04ffff04ff18ffff04ffff02ff16ffff04ff02ffff04ff05ffff04ff27ffff04ffff0bff2cff82014f80ffff04ffff02ff2effff04ff02ffff04ff818fff80808080ffff04ffff0bff2cff0580ff8080808080808080ff378080ff81af8080ff0180ff018080ffff04ffff01a031f5e810e2ad078817e8b047306c877ad82c77511aa235179c4a98af413f162affff04ffff01ffff75ffc08968747470733a2f2f6c68332e676f6f676c6575736572636f6e74656e742e636f6d2f35394834764178714276794435424b58437848564d725a7a57535330424735697a68416d733046467371304879373159676169755242474553374b4a4a59306f5435546b724e50496a336c564c554d47326e796c6a57753349316a5267767234354e596d3d733080ffff68a024e04e8a50fbba39dfdef8759362236fb4ca8b2d4a02391a19bf4b7375ea97bbffff826d7580ffff826c7580ffff82736e01ffff8273740c80ffff04ffff01a0fe8a4b4e27a2e29a4d3fc7ce9d527adbcaccbab6ada3903ccf3ba9a769d2d78bffff04ffff01ff02ffff01ff02ffff01ff02ffff03ff0bffff01ff02ffff03ffff09ff05ffff1dff0bffff1effff0bff0bffff02ff06ffff04ff02ffff04ff17ff8080808080808080ffff01ff02ff17ff2f80ffff01ff088080ff0180ffff01ff04ffff04ff04ffff04ff05ffff04ffff02ff06ffff04ff02ffff04ff17ff80808080ff80808080ffff02ff17ff2f808080ff0180ffff04ffff01ff32ff02ffff03ffff07ff0580ffff01ff0bffff0102ffff02ff06ffff04ff02ffff04ff09ff80808080ffff02ff06ffff04ff02ffff04ff0dff8080808080ffff01ff0bffff0101ff058080ff0180ff018080ffff04ffff01b094b81fa2efc6109903e7c98340d5d8b230b2b786be64733e8377fc4707435890333863bd4e1105bd56c9c76ed2e00f05ff018080ff018080808080ff01808080",
                "solution": "0xffffa0c0a9550c629004468d6300d61fbcbf0195852a104d4287170313af69c9f321d4ff0180ff01ffffff80ffff01ffff33ffa019e0292fd5f32a53f44d6dbf31c182c5129e6568488d7d9354b2f48a8c2d576eff01ffffa019e0292fd5f32a53f44d6dbf31c182c5129e6568488d7d9354b2f48a8c2d576e808080ff8080ff018080"
            }
        ]
    },
    "success": true,
    "wallet_id": 7
}
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x00000000056C8B80>
Traceback (most recent call last):
  File "asyncio\proactor_events.py", line 116, in __del__
  File "asyncio\proactor_events.py", line 108, in close
  File "asyncio\base_events.py", line 751, in call_soon
  File "asyncio\base_events.py", line 515, in _check_closed
RuntimeError: Event loop is closed
```

**Comment by trepca** [comment]
@wallentx which python version are you running?

**Comment by wallentx** [comment]
3.10.4
