### ISSUE TITLE
DID recovery_spend: list index out of range [Bug] 

### ISSUE THREAD

**Issue by danieljperry** [Chia-Network/chia-blockchain#12014]
### What happened?

Start with DIDs in wallets 2 and 5:
```
Test DID:
   -Total Balance:         1.0
   -Pending Total Balance: 1.0
   -Spendable:             1.0
   -Type:                  DECENTRALIZED_ID
   -DID ID:                did:chia:13p5fdxgm8e2pngdwp8m088t0etp7rgzx9ye2ju8v5ackcyg7t9nqx2um83
   -Wallet ID:             2

New_DID:
   -Total Balance:         1.0
   -Pending Total Balance: 1.0
   -Spendable:             1.0
   -Type:                  DECENTRALIZED_ID
   -DID ID:                did:chia:1yxezm4nl4lhr4f7yr7yw0w4t9v6p32n2zt0skk0gumn4krfy8uxq8hhg9w
   -Wallet ID:             5
```

Update the recovery info for wallet 5 to use the DID from wallet 2:
```
chia rpc wallet did_update_recovery_ids '{\"wallet_id\": 5, \"new_list\": [\"did:chia:13p5fdxgm8e2pngdwp8m088t0etp7rgzx9ye2ju8v5ackcyg7t9nqx2um83\"]}'
{
    "success": true
}
```

Now gather the info required to create an attest:
```
chia rpc wallet did_get_current_coin_info '{\"wallet_id\": 2}'
{
    "did_amount": 1,
    "did_innerpuz": "0xd81e3f47c07dd9d17933e07cd5f7ea595049ea40eac091e33ca013c2c6baa60c",
    "did_parent": "0x1a80bb6c67b7cf4f27c9b261934878ee440056601870fbc4916b72b29f4a29b1",
    "my_did": "did:chia:13p5fdxgm8e2pngdwp8m088t0etp7rgzx9ye2ju8v5ackcyg7t9nqx2um83",
    "success": true,
    "wallet_id": 2
}

chia rpc wallet did_get_did '{\"wallet_id\": 2}'
{
    "coin_id": "0xcc63634ed61d3d6e75b8f4c6e798c514a58b12eb30f8df88dd2343234ea60440",
    "my_did": "did:chia:13p5fdxgm8e2pngdwp8m088t0etp7rgzx9ye2ju8v5ackcyg7t9nqx2um83",
    "success": true,
    "wallet_id": 2
}

chia keys show
...
Fingerprint: 2527948602
Master public key (m): b699060b533cc6c9b6cdfac545d89985b5768a0d47bf0b0fbe25a1b28a83059e22b910893f1c91a442e87273fa6123b0
```

Using this info, create an attest for recovery:
```
chia rpc wallet did_create_attest '{\"wallet_id\": 2, \"coin_name\": \"0xcc63634ed61d3d6e75b8f4c6e798c514a58b12eb30f8df88dd2343234ea60440\", \"pubkey\": \"b699060b533cc6c9b6cdfac545d89985b5768a0d47bf0b0fbe25a1b28a83059e22b910893f1c91a442e87273fa6123b0\", \"puzhash\": \"0xd81e3f47c07dd9d17933e07cd5f7ea595049ea40eac091e33ca013c2c6baa60c\"}'
{
    "attest_data": "886896991b3e5419a1ae09f6f39d6fcac3e1a0462932a970eca7716c111e5966:00000001cc63634ed61d3d6e75b8f4c6e798c514a58b12eb30f8df88dd2343234ea60440d49b95ab554040476451ffebf51c270dfffed40c50b6ad3c9247b636823958740000000000000000ff01ffff3cffa0cc63634ed61d3d6e75b8f4c6e798c514a58b12eb30f8df88dd2343234ea6044080ffff31ffb0b699060b533cc6c9b6cdfac545d89985b5768a0d47bf0b0fbe25a1b28a83059e22b910893f1c91a442e87273fa6123b0ffa0d81e3f47c07dd9d17933e07cd5f7ea595049ea40eac091e33ca013c2c6baa60c808080c00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000:1a80bb6c67b7cf4f27c9b261934878ee440056601870fbc4916b72b29f4a29b1:d81e3f47c07dd9d17933e07cd5f7ea595049ea40eac091e33ca013c2c6baa60c:1",
    "info": [
        "1a80bb6c67b7cf4f27c9b261934878ee440056601870fbc4916b72b29f4a29b1",
        "d81e3f47c07dd9d17933e07cd5f7ea595049ea40eac091e33ca013c2c6baa60c",
        1
    ],
    "message_spend_bundle": "00000001cc63634ed61d3d6e75b8f4c6e798c514a58b12eb30f8df88dd2343234ea60440d49b95ab554040476451ffebf51c270dfffed40c50b6ad3c9247b636823958740000000000000000ff01ffff3cffa0cc63634ed61d3d6e75b8f4c6e798c514a58b12eb30f8df88dd2343234ea6044080ffff31ffb0b699060b533cc6c9b6cdfac545d89985b5768a0d47bf0b0fbe25a1b28a83059e22b910893f1c91a442e87273fa6123b0ffa0d81e3f47c07dd9d17933e07cd5f7ea595049ea40eac091e33ca013c2c6baa60c808080c00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000",
    "success": true
}
```

Using this attest data, attempt a recovery spend:
```
chia rpc wallet did_recovery_spend '{\"wallet_id\": 5, \"attest_data\": \"886896991b3e5419a1ae09f6f39d6fcac3e1a0462932a970eca7716c111e5966:00000001cc63634ed61d3d6e75b8f4c6e798c514a58b12eb30f8df88dd2343234ea60440d49b95ab554040476451ffebf51c270dfffed40c50b6ad3c9247b636823958740000000000000000ff01ffff3cffa0cc63634ed61d3d6e75b8f4c6e798c514a58b12eb30f8df88dd2343234ea6044080ffff31ffb0b699060b533cc6c9b6cdfac545d89985b5768a0d47bf0b0fbe25a1b28a83059e22b910893f1c91a442e87273fa6123b0ffa0d81e3f47c07dd9d17933e07cd5f7ea595049ea40eac091e33ca013c2c6baa60c808080c00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000:1a80bb6c67b7cf4f27c9b261934878ee440056601870fbc4916b72b29f4a29b1:d81e3f47c07dd9d17933e07cd5f7ea595049ea40eac091e33ca013c2c6baa60c:1\"}'
Request failed: {'error': 'list index out of range', 'success': False}
```

### Version

1.3.6.dev722

### What platform are you using?

Windows

### What ui mode are you using?

CLI

### Relevant log output

```shell
2022-06-22T09:25:36.076 wallet chia.rpc.util              : WARNING  Error while handling message: Traceback (most recent call last):
  File "c:\users\user\chia\release_1.4.0\2022_06_22\chia-blockchain\chia\rpc\util.py", line 16, in inner
    res_object = await f(request_data)
  File "c:\users\user\chia\release_1.4.0\2022_06_22\chia-blockchain\chia\rpc\wallet_rpc_api.py", line 1232, in did_recovery_spend
    ) = await wallet.load_attest_files_for_recovery_spend(request["attest_data"])
  File "c:\users\user\chia\release_1.4.0\2022_06_22\chia-blockchain\chia\wallet\did_wallet\did_wallet.py", line 898, in load_attest_files_for_recovery_spend
    bytes.fromhex(info[2]),
IndexError: list index out of range
```

**Comment by ytx1991** [comment]
Recovery process
1. chia rpc wallet did_create_backup_file '{"wallet_id":You_Old_DID}'
2. Save the backup_data somewhere
3. Switch to another wallet and run
 chia rpc wallet create_new_wallet '{"wallet_type":"did_wallet", "did_type":"recovery", "backup_data":”YOUR_BACKUP_DATA”}’
Example return:
{
    "backup_dids": [
        "0x0d7b3def317c3061eda2821a8d32d24960b66c317e38ef797b7bb570887d167c",
        "0xde4f3e6a7fa223c3d97eddcf6ddccf21176469e3174b5306404c00957334ea5a"
    ],
    "coin_list": [
        "0x8be6b99a6deca2aac8270ee6a386e7ba2ef312a228fb525c6d3e928f6a4d6b80",
        "0x93de9f70ba993ebb8e435c2ba7c09abd24a8b2f60e0d9c5801f71eff27eeaa81",
        1
    ],
    "coin_name": "1fefa7e2aa7e342df780c86f29429f58cecaaeef044c44dfafde95957a9b0198",
    "my_did": "46991fda97f048557ca720a5942050b3e2a20b7b6a2de2db25ccf0489b6ab3d2",
    "newpuzhash": "4113b2c5b536dcbd62d43925ee69b2d703be578ae8f56bee457b28afffa6a436",
    "num_verifications_required": 2,
    "pubkey": "994bf614b0b2aab3aa786705d507bbddaa8644db4e86a49eba4c9e2a3cfab388a26a3779093b8ec7d1d1b7877fdf2bf2",
    "success": true,
    "type": 8,
    "wallet_id": 8
}

4. Switch to the backup DIDs wallet, create attestment use the coin name, newpuzhash & pubkey returned in the last step : 
chia rpc wallet did_create_attest '{"wallet_id":4, "coin_name":"1fefa7e2aa7e342df780c86f29429f58cecaaeef044c44dfafde95957a9b0198", "pubkey":"994bf614b0b2aab3aa786705d507bbddaa8644db4e86a49eba4c9e2a3cfab388a26a3779093b8ec7d1d1b7877fdf2bf2", "puzhash":"4113b2c5b536dcbd62d43925ee69b2d703be578ae8f56bee457b28afffa6a436"}'
 5. Ensure you have enough attestments and they are confirmed. Save all attest_data somewhere, switch to the new wallet
6. Recover the DID: chia rpc wallet did_recovery_spend '{"wallet_id":8, "attest_data":["Attest_data1",”Atest_data2”]}'
Wait the tx confirm, you should see the balance of your new wallet changed.

**Comment by ytx1991** [comment]
There is bug for generate the newpuzhash in the new wallet, fix here https://github.com/Chia-Network/chia-blockchain/pull/12051/files
