### ISSUE TITLE
[Bug]  full_node asyncio                 : ERROR    Task exception was never retrieved

### ISSUE THREAD

**Issue by ruipdguerra** [Chia-Network/chia-blockchain#12011]
### What happened?

![Screenshot_1](https://user-images.githubusercontent.com/107995281/175013354-978b013b-5758-44aa-bc60-47d48b818afa.jpg)

It's been like this forever..

Status
Syncing 0/2,153,871

### Version

1.3.5

### What platform are you using?

Windows

### What ui mode are you using?

GUI

### Relevant log output

```shell
2022-06-22T11:12:57.966 full_node asyncio                 : ERROR    Task exception was never retrieved
future: <Task finished name='Task-1598299' coro=<RpcServer._state_changed() done, defined at chia\rpc\rpc_server.py:56> exception=KeyError(<bytes32: d780d22c7a87c9e01d98b49a0910f6701c3b95015741316b3fda042e5d7b81d2>)>
Traceback (most recent call last):
  File "chia\rpc\rpc_server.py", line 59, in _state_changed
  File "chia\rpc\full_node_rpc_api.py", line 72, in _state_changed
  File "chia\rpc\full_node_rpc_api.py", line 132, in get_blockchain_state
  File "chia\consensus\blockchain.py", line 176, in get_peak
  File "chia\consensus\blockchain.py", line 677, in height_to_block_record
  File "chia\consensus\blockchain.py", line 670, in block_record
KeyError: <bytes32: d780d22c7a87c9e01d98b49a0910f6701c3b95015741316b3fda042e5d7b81d2>
2022-06-22T11:13:01.173 full_node asyncio                 : ERROR    Task exception was never retrieved
future: <Task finished name='Task-1598320' coro=<RpcServer._state_changed() done, defined at chia\rpc\rpc_server.py:56> exception=KeyError(<bytes32: d780d22c7a87c9e01d98b49a0910f6701c3b95015741316b3fda042e5d7b81d2>)>
Traceback (most recent call last):
  File "chia\rpc\rpc_server.py", line 59, in _state_changed
  File "chia\rpc\full_node_rpc_api.py", line 72, in _state_changed
  File "chia\rpc\full_node_rpc_api.py", line 132, in get_blockchain_state
  File "chia\consensus\blockchain.py", line 176, in get_peak
  File "chia\consensus\blockchain.py", line 677, in height_to_block_record
  File "chia\consensus\blockchain.py", line 670, in block_record
KeyError: <bytes32: d780d22c7a87c9e01d98b49a0910f6701c3b95015741316b3fda042e5d7b81d2>
2022-06-22T11:13:01.174 full_node full_node_server        : WARNING  Banning 95.84.220.194 for 10 seconds
2022-06-22T11:13:01.176 full_node full_node_server        : ERROR    Exception <bytes32: d780d22c7a87c9e01d98b49a0910f6701c3b95015741316b3fda042e5d7b81d2>, exception Stack: Traceback (most recent call last):
  File "chia\server\server.py", line 468, in start_client
  File "chia\server\server.py", line 368, in connection_added
  File "chia\server\node_discovery.py", line 241, in on_connect_callback
  File "chia\full_node\full_node.py", line 693, in on_connect
  File "chia\full_node\full_node.py", line 659, in synced
  File "chia\consensus\blockchain.py", line 176, in get_peak
  File "chia\consensus\blockchain.py", line 677, in height_to_block_record
  File "chia\consensus\blockchain.py", line 670, in block_record
KeyError: <bytes32: d780d22c7a87c9e01d98b49a0910f6701c3b95015741316b3fda042e5d7b81d2>

2022-06-22T11:13:01.176 full_node asyncio                 : ERROR    Task exception was never retrieved
future: <Task finished name='Task-1598323' coro=<RpcServer._state_changed() done, defined at chia\rpc\rpc_server.py:56> exception=KeyError(<bytes32: d780d22c7a87c9e01d98b49a0910f6701c3b95015741316b3fda042e5d7b81d2>)>
Traceback (most recent call last):
  File "chia\rpc\rpc_server.py", line 59, in _state_changed
  File "chia\rpc\full_node_rpc_api.py", line 72, in _state_changed
  File "chia\rpc\full_node_rpc_api.py", line 132, in get_blockchain_state
  File "chia\consensus\blockchain.py", line 176, in get_peak
  File "chia\consensus\blockchain.py", line 677, in height_to_block_record
  File "chia\consensus\blockchain.py", line 670, in block_record
KeyError: <bytes32: d780d22c7a87c9e01d98b49a0910f6701c3b95015741316b3fda042e5d7b81d2>
2022-06-22T11:13:01.531 full_node asyncio                 : ERROR    Task exception was never retrieved
future: <Task finished name='Task-1598330' coro=<RpcServer._state_changed() done, defined at chia\rpc\rpc_server.py:56> exception=KeyError(<bytes32: d780d22c7a87c9e01d98b49a0910f6701c3b95015741316b3fda042e5d7b81d2>)>
Traceback (most recent call last):
  File "chia\rpc\rpc_server.py", line 59, in _state_changed
  File "chia\rpc\full_node_rpc_api.py", line 72, in _state_changed
  File "chia\rpc\full_node_rpc_api.py", line 132, in get_blockchain_state
  File "chia\consensus\blockchain.py", line 176, in get_peak
  File "chia\consensus\blockchain.py", line 677, in height_to_block_record
  File "chia\consensus\blockchain.py", line 670, in block_record
KeyError: <bytes32: d780d22c7a87c9e01d98b49a0910f6701c3b95015741316b3fda042e5d7b81d2>
2022-06-22T11:13:01.674 full_node full_node_server        : WARNING  Banning 51.81.109.11 for 10 seconds
2022-06-22T11:13:01.676 full_node full_node_server        : ERROR    Exception <bytes32: d780d22c7a87c9e01d98b49a0910f6701c3b95015741316b3fda042e5d7b81d2>, exception Stack: Traceback (most recent call last):
  File "chia\server\server.py", line 468, in start_client
  File "chia\server\server.py", line 368, in connection_added
  File "chia\server\node_discovery.py", line 241, in on_connect_callback
  File "chia\full_node\full_node.py", line 693, in on_connect
  File "chia\full_node\full_node.py", line 659, in synced
  File "chia\consensus\blockchain.py", line 176, in get_peak
  File "chia\consensus\blockchain.py", line 677, in height_to_block_record
  File "chia\consensus\blockchain.py", line 670, in block_record
KeyError: <bytes32: d780d22c7a87c9e01d98b49a0910f6701c3b95015741316b3fda042e5d7b81d2>

2022-06-22T11:13:01.677 full_node asyncio                 : ERROR    Task exception was never retrieved
future: <Task finished name='Task-1598333' coro=<RpcServer._state_changed() done, defined at chia\rpc\rpc_server.py:56> exception=KeyError(<bytes32: d780d22c7a87c9e01d98b49a0910f6701c3b95015741316b3fda042e5d7b81d2>)>
Traceback (most recent call last):
  File "chia\rpc\rpc_server.py", line 59, in _state_changed
  File "chia\rpc\full_node_rpc_api.py", line 72, in _state_changed
  File "chia\rpc\full_node_rpc_api.py", line 132, in get_blockchain_state
  File "chia\consensus\blockchain.py", line 176, in get_peak
  File "chia\consensus\blockchain.py", line 677, in height_to_block_record
  File "chia\consensus\blockchain.py", line 670, in block_record
KeyError: <bytes32: d780d22c7a87c9e01d98b49a0910f6701c3b95015741316b3fda042e5d7b81d2>
```

**Comment by wallentx** [comment]
The logs seem to indicate that your blockchain db is corrupt. You'll need to delete your blockchain db, and allow it to resync.

**Comment by ruipdguerra** [comment]
How can i save my current tokens?

**Comment by ruipdguerra** [comment]
How can i save my current tokens?

**Comment by wallentx** [comment]
All of that is on-chain, and will show back up as you resync the db.
