### ISSUE TITLE
[BUG] Wallet sync error

### ISSUE THREAD

**Issue by hoffmang9** [Chia-Network/chia-blockchain#1210]
Running dev branch at 0025c154e42d3c0216fbbe0edb66276c23e1b9aa (but has been happening earlier too) wallet attempts to sync and then the sync excepts and dies forcing a new attempt at syncing - and keeps looping.

```
12:44:37.351 wallet src.wallet.wallet_state_manager: INFO     Adding coin: {'amount': '1398999000000000000',
 'parent_coin_info': '0xea75505262ece98fdab1a6ccbf24733a9dab6fcd7dd820299edbb0375704d48b',
 'puzzle_hash': '0x8c22c92e51d64c7c8003cb8a5e3506879c1f315bca9cbd9fc87d7fd16fb62aa9'} at 15844
12:44:37.354 wallet wallet_server              : INFO     Connection closed: 127.0.0.1, node id: 212d75eb866e12b17a0ec48b17c9cf4724822fbe65108f69e3ee1edfbabb3116
12:44:37.355 full_node src.full_node.full_node : INFO     peer disconnected {'host': '127.0.0.1', 'port': 8449}
12:44:37.356 wallet src.wallet.wallet_node     : ERROR    Error while trying to fetch from peer: Traceback (most recent call last):
  File "/Users/hoffmang/beta/chia-blockchain/src/wallet/wallet_node.py", line 548, in _sync
    added, advanced_peak = await self.fetch_blocks_and_validate(
  File "/Users/hoffmang/beta/chia-blockchain/src/wallet/wallet_node.py", line 635, in fetch_blocks_and_validate
    (result, error, fork_h,) = await self.wallet_state_manager.blockchain.receive_block(
  File "/Users/hoffmang/beta/chia-blockchain/src/wallet/wallet_blockchain.py", line 233, in receive_block
    fork_height: Optional[uint32] = await self._reconsider_peak(block_record, genesis, fork_point_with_peak)
  File "/Users/hoffmang/beta/chia-blockchain/src/wallet/wallet_blockchain.py", line 302, in _reconsider_peak
    await self.coins_of_interest_received(
  File "/Users/hoffmang/beta/chia-blockchain/src/wallet/wallet_state_manager.py", line 479, in coins_of_interest_received
    trade_additions = await self.coins_of_interest_added(additions, height)
  File "/Users/hoffmang/beta/chia-blockchain/src/wallet/wallet_state_manager.py", line 535, in coins_of_interest_added
    await self.coin_added(coin, is_coinbase, is_fee_reward, uint32(wallet_id), wallet_type, height)
  File "/Users/hoffmang/beta/chia-blockchain/src/wallet/wallet_state_manager.py", line 616, in coin_added
    records = await self.tx_store.tx_with_addition_coin(coin.name(), wallet_id)
  File "/Users/hoffmang/beta/chia-blockchain/src/wallet/wallet_transaction_store.py", line 162, in tx_with_addition_coin
    all_records = await self.get_all_transactions(wallet_id, TransactionType.OUTGOING_TX.value)
  File "/Users/hoffmang/beta/chia-blockchain/src/wallet/wallet_transaction_store.py", line 368, in get_all_transactions
      assert tx is not None
AssertionError

12:44:37.368 wallet src.wallet.wallet_node     : ERROR    Loop exception in sync Was not able to add blocks 16131-16163. Traceback (most recent call last):
  File "/Users/hoffmang/beta/chia-blockchain/src/wallet/wallet_node.py", line 490, in sync_job
    await self._sync()
  File "/Users/hoffmang/beta/chia-blockchain/src/wallet/wallet_node.py", line 558, in _sync
    raise RuntimeError(f"Was not able to add blocks {start_height}-{end_height}")
RuntimeError: Was not able to add blocks 16131-16163

12:44:37.368 wallet src.wallet.wallet_node     : INFO     Loop end in sync job
12:44:37.369 wallet src.wallet.wallet_node     : INFO     Loop start in sync job
```

I'm attaching full debug log. The wallet db is... large - will toss in Keybase.

[debug.log.zip](https://github.com/Chia-Network/chia-blockchain/files/6111329/debug.log.zip)

**Comment by lvcivs** [comment]
My wallet got stuck with a similar error in the log file as above (`ERROR    Loop exception in sync Was not able to add blocks ...`). I can provide the log file if neccesary.

**Comment by hoffmang9** [comment]
Closing for RC7
