### ISSUE TITLE
FATAL ERROR

### ISSUE THREAD

**Issue by Alanbor88** [Chia-Network/chia-blockchain#12223]
### What happened?

when I want to form plots I get this:

Failed to write to finaldir directory: 'C:\'
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x000001DB31B26880>
Fatal error on SSL transport
protocol: <asyncio.sslproto.SSLProtocol object at 0x000001DB31AF6280>
transport: <_ProactorSocketTransport fd=-1 read=<_OverlappedFuture cancelled>>
Traceback (most recent call last):
  File "asyncio\sslproto.py", line 690, in _process_write_backlog
  File "asyncio\proactor_events.py", line 359, in write
  File "asyncio\proactor_events.py", line 395, in _loop_writing
AttributeError: 'NoneType' object has no attribute 'send'
Exception ignored in: <function _SSLProtocolTransport.__del__ at 0x000001DB30D029D0>
Traceback (most recent call last):
  File "asyncio\sslproto.py", line 321, in __del__
  File "asyncio\sslproto.py", line 316, in close
  File "asyncio\sslproto.py", line 599, in _start_shutdown
  File "asyncio\sslproto.py", line 604, in _write_appdata
  File "asyncio\sslproto.py", line 712, in _process_write_backlog
  File "asyncio\sslproto.py", line 726, in _fatal_error
  File "asyncio\proactor_events.py", line 151, in _force_close
  File "asyncio\base_events.py", line 751, in call_soon
  File "asyncio\base_events.py", line 515, in _check_closed
RuntimeError: Event loop is closed

### Version

HELP

### What platform are you using?

Windows

### What ui mode are you using?

GUI

**Comment by Alanbor88** [comment]
Thanks a lot. It was possible to solve the problem with your contribution
