### ISSUE TITLE
[Bug] Repeated timeout when trying to send XCH 

### ISSUE THREAD

**Issue by wv-krmkz** [Chia-Network/chia-blockchain#12226]
### What happened?

Attempting to send ~2 XCH from one wallet to another on Win10 Chia 1.4 and getting repeated timeouts on the Tx. 
EDIT: Amount accuracy 

Never had trouble with this on past versions. Any suggestions? Thanks.

### Version

1.4

### What platform are you using?

Windows

### What ui mode are you using?

GUI

### Relevant log output or stacktrace

```shell
2022-07-02T16:xxxxxx wallet chia.rpc.rpc_server        : WARNING  Error while handling message: Traceback (most recent call last):
  File "chia\rpc\rpc_server.py", line 229, in safe_handle
  File "chia\rpc\rpc_server.py", line 220, in ws_api
  File "chia\rpc\wallet_rpc_api.py", line 838, in send_transaction
  File "chia\wallet\wallet.py", line 432, in generate_signed_transaction
  File "chia\wallet\wallet.py", line 315, in _generate_unsigned_transaction
  File "chia\wallet\wallet.py", line 267, in select_coins
  File "chia\wallet\coin_selection.py", line 90, in select_coins
  File "chia\wallet\coin_selection.py", line 119, in select_smallest_coin_over_target
ValueError: Unable to select coins for this transaction. Try sending a smaller amount
```

**Comment by giorgiomassar8** [comment]
I confirm that I am also experiencing crashes of the wallet daemon when trying to send more than 1 XCH since upgrading to 1.4.0. When sending 1 XCH it has a success rate of about 50/50.

**Comment by emlowe** [comment]
If you have many (thousands probably) of small coins that can add up to the total you need,  the knapsack algorithm may select this list of small coins, however, if that list of small coins is too many coins (more than 500) you can get this error even though you may have a set of coins that would work better - we are working on some fixes. This can happen if all your coins are smaller than the amount you are sending and some are fairly big (say 0.25 rewards) and many many are really small .

**Comment by jack60612** [comment]
Being fixed by: https://github.com/Chia-Network/chia-blockchain/pull/12242

**Comment by jack60612** [comment]
https://trello.com/c/6LyH2mDm/1563-coin-selection-bug-fix
