### ISSUE TITLE
[Bug] Wallet mode remains in or reverts to syncing state with spinners on macOS

### ISSUE THREAD

**Issue by ghost** [Chia-Network/chia-blockchain#12232]
### What happened?

Wallet connects to peers, remains in syncing state for several minutes, appears to get intermittent sync before reverting back to syncing state (all transactions are shown, balance either shows as actual, 0 or error).

Randomly navigating to settings>profiles results in spinner with page unable to load, same for NFT page.

I have 1 DID profile with 1 NFT assigned, this is a fresh install with mnemonic restored (~250 transactions) - have tried deleting DB and config etc several times, results in same issues.

OS: MacOS Monterey v12.4 (Apple Silicon - M1)

### Version

1.4.0

### What platform are you using?

macOS

### What ui mode are you using?

GUI

### Relevant log output

```shell
2022-07-05T17:22:11.958 daemon __main__                   : ERROR    Ping error
Traceback (most recent call last):
  File "chia/daemon/server.py", line 284, in ping_task
  File "aiohttp/web_ws.py", line 295, in ping
  File "aiohttp/http_websocket.py", line 676, in ping
  File "aiohttp/http_websocket.py", line 653, in _send_frame
  File "aiohttp/http_websocket.py", line 663, in _write
ConnectionResetError: Cannot write to closing transport
2022-07-05T17:22:11.960 daemon __main__                   : ERROR    Ping failed, connection closed.
2022-07-05T17:29:59.713 wallet chia.wallet.wallet_node    : WARNING  Peer {'host': '174.52.204.100', 'port': 8444} did not respond in time.
2022-07-05T17:30:01.015 wallet chia.wallet.wallet_node    : WARNING  Non-trusted peer {'host': '158.174.91.212', 'port': 8444} is not synced, disconnecting
2022-07-05T17:30:01.356 wallet wallet_server              : WARNING  Banning 158.174.91.212 for 120 seconds
2022-07-05T17:30:08.516 wallet chia.wallet.wallet_node    : WARNING  Non-trusted peer {'host': '177.82.90.193', 'port': 8444} is not synced, disconnecting
2022-07-05T17:30:09.368 wallet wallet_server              : WARNING  Banning 177.82.90.193 for 120 seconds
2022-07-05T17:30:09.369 wallet chia.wallet.wallet_node    : WARNING  Peer {'host': '177.82.90.193', 'port': 8444} did not respond in time.
2022-07-05T17:30:09.369 wallet chia.wallet.wallet_node    : WARNING  Peer None did not respond in time.
2022-07-05T17:30:09.370 wallet chia.wallet.wallet_node    : WARNING  Peer None did not respond in time.
2022-07-05T17:30:09.370 wallet chia.wallet.wallet_node    : WARNING  Peer {'host': '177.82.90.193', 'port': 8444} did not respond in time.
2022-07-05T17:30:09.370 wallet chia.wallet.wallet_node    : WARNING  Peer None did not respond in time.
2022-07-05T17:30:09.371 wallet chia.wallet.wallet_node    : WARNING  Peer None did not respond in time.
2022-07-05T17:30:09.371 wallet chia.wallet.wallet_node    : WARNING  Peer {'host': '177.82.90.193', 'port': 8444} did not respond in time.
2022-07-05T17:30:09.371 wallet chia.wallet.wallet_node    : WARNING  Peer None did not respond in time.
2022-07-05T17:30:09.371 wallet chia.wallet.wallet_node    : WARNING  Peer None did not respond in time.
2022-07-05T17:30:09.372 wallet chia.wallet.wallet_node    : WARNING  Peer None did not respond in time.
2022-07-05T17:30:09.372 wallet chia.wallet.wallet_node    : WARNING  Peer None did not respond in time.
2022-07-05T17:30:09.372 wallet chia.wallet.wallet_node    : WARNING  Peer {'host': '177.82.90.193', 'port': 8444} did not respond in time.
2022-07-05T17:30:09.373 wallet chia.wallet.wallet_node    : WARNING  Peer {'host': '177.82.90.193', 'port': 8444} did not respond in time.
2022-07-05T17:30:09.373 wallet chia.wallet.wallet_node    : WARNING  Peer None did not respond in time.
2022-07-05T17:30:09.373 wallet chia.wallet.wallet_node    : WARNING  Peer None did not respond in time.
2022-07-05T17:30:09.374 wallet chia.wallet.wallet_node    : WARNING  Peer None did not respond in time.
2022-07-05T17:30:09.374 wallet chia.wallet.wallet_node    : WARNING  Peer {'host': '177.82.90.193', 'port': 8444} did not respond in time.
2022-07-05T17:30:09.374 wallet chia.wallet.wallet_node    : WARNING  Peer None did not respond in time.
2022-07-05T17:30:09.374 wallet chia.wallet.wallet_node    : WARNING  Peer {'host': '177.82.90.193', 'port': 8444} did not respond in time.
2022-07-05T17:30:09.375 wallet chia.wallet.wallet_node    : WARNING  Peer None did not respond in time.
2022-07-05T17:30:09.375 wallet chia.wallet.wallet_node    : WARNING  Peer None did not respond in time.
2022-07-05T17:30:09.375 wallet chia.wallet.wallet_node    : WARNING  Peer {'host': '177.82.90.193', 'port': 8444} did not respond in time.
2022-07-05T17:30:09.375 wallet chia.wallet.wallet_node    : WARNING  Peer None did not respond in time.
2022-07-05T17:30:09.376 wallet chia.wallet.wallet_node    : WARNING  Peer None did not respond in time.
2022-07-05T17:30:09.376 wallet chia.wallet.wallet_node    : WARNING  Peer None did not respond in time.
2022-07-05T17:30:09.376 wallet chia.wallet.wallet_node    : WARNING  Peer None did not respond in time.
2022-07-05T17:30:09.377 wallet chia.wallet.wallet_node    : WARNING  Peer {'host': '177.82.90.193', 'port': 8444} did not respond in time.
2022-07-05T17:30:09.377 wallet chia.wallet.wallet_node    : WARNING  Peer {'host': '177.82.90.193', 'port': 8444} did not respond in time.
2022-07-05T17:30:09.377 wallet chia.wallet.wallet_node    : WARNING  Peer None did not respond in time.
2022-07-05T17:30:09.377 wallet chia.wallet.wallet_node    : WARNING  Peer None did not respond in time.
2022-07-05T17:30:09.378 wallet chia.wallet.wallet_node    : WARNING  Peer {'host': '177.82.90.193', 'port': 8444} did not respond in time.
2022-07-05T17:30:09.378 wallet chia.wallet.wallet_node    : WARNING  Peer None did not respond in time.
2022-07-05T17:30:09.378 wallet chia.wallet.wallet_node    : WARNING  Peer None did not respond in time.
2022-07-05T17:30:09.378 wallet chia.wallet.wallet_node    : WARNING  Peer {'host': '177.82.90.193', 'port': 8444} did not respond in time.
2022-07-05T17:30:09.378 wallet chia.wallet.wallet_node    : WARNING  Peer None did not respond in time.
2022-07-05T17:30:09.379 wallet chia.wallet.wallet_node    : WARNING  Peer None did not respond in time.
2022-07-05T17:30:09.379 wallet chia.wallet.wallet_node    : WARNING  Peer None did not respond in time.
2022-07-05T17:30:09.379 wallet chia.wallet.wallet_node    : WARNING  Peer {'host': '177.82.90.193', 'port': 8444} did not respond in time.
2022-07-05T17:30:09.379 wallet chia.wallet.wallet_node    : WARNING  Peer None did not respond in time.
2022-07-05T17:30:09.380 wallet chia.wallet.wallet_node    : WARNING  Peer {'host': '177.82.90.193', 'port': 8444} did not respond in time.
2022-07-05T17:30:09.380 wallet chia.wallet.wallet_node    : WARNING  Peer None did not respond in time.
2022-07-05T17:30:09.380 wallet chia.wallet.wallet_node    : WARNING  Peer None did not respond in time.
2022-07-05T17:30:09.380 wallet chia.wallet.wallet_node    : WARNING  Peer {'host': '177.82.90.193', 'port': 8444} did not respond in time.
2022-07-05T17:30:09.381 wallet chia.wallet.wallet_node    : WARNING  Peer None did not respond in time.
2022-07-05T17:30:09.381 wallet chia.wallet.wallet_node    : WARNING  Peer None did not respond in time.
2022-07-05T17:30:09.381 wallet chia.wallet.wallet_node    : WARNING  Peer {'host': '177.82.90.193', 'port': 8444} did not respond in time.
2022-07-05T17:30:09.381 wallet chia.wallet.wallet_node    : WARNING  Peer None did not respond in time.
2022-07-05T17:30:09.382 wallet chia.wallet.wallet_node    : WARNING  Peer None did not respond in time.
2022-07-05T17:30:09.382 wallet chia.wallet.wallet_node    : WARNING  Peer {'host': '177.82.90.193', 'port': 8444} did not respond in time.
2022-07-05T17:30:09.382 wallet chia.wallet.wallet_node    : WARNING  Peer None did not respond in time.
2022-07-05T17:30:09.382 wallet chia.wallet.wallet_node    : WARNING  Peer None did not respond in time.
2022-07-05T17:30:09.383 wallet chia.wallet.wallet_node    : WARNING  Peer {'host': '177.82.90.193', 'port': 8444} did not respond in time.
2022-07-05T17:30:09.383 wallet chia.wallet.wallet_node    : WARNING  Peer None did not respond in time.
2022-07-05T17:30:09.383 wallet chia.wallet.wallet_node    : WARNING  Peer None did not respond in time.
2022-07-05T17:30:09.383 wallet chia.wallet.wallet_node    : WARNING  Peer {'host': '177.82.90.193', 'port': 8444} did not respond in time.
2022-07-05T17:30:09.384 wallet chia.wallet.wallet_node    : WARNING  Peer None did not respond in time.
2022-07-05T17:30:09.384 wallet chia.wallet.wallet_node    : WARNING  Peer None did not respond in time.
2022-07-05T17:30:09.384 wallet chia.wallet.wallet_node    : WARNING  Peer None did not respond in time.
2022-07-05T17:30:09.384 wallet chia.wallet.wallet_node    : WARNING  Peer None did not respond in time.
2022-07-05T17:30:09.385 wallet chia.wallet.wallet_node    : WARNING  Peer {'host': '177.82.90.193', 'port': 8444} did not respond in time.
2022-07-05T17:30:09.385 wallet chia.wallet.wallet_node    : WARNING  Peer None did not respond in time.
2022-07-05T17:30:09.385 wallet chia.wallet.wallet_node    : WARNING  Peer {'host': '177.82.90.193', 'port': 8444} did not respond in time.
2022-07-05T17:30:09.385 wallet chia.wallet.wallet_node    : WARNING  Peer None did not respond in time.
2022-07-05T17:30:09.385 wallet chia.wallet.wallet_node    : WARNING  Peer {'host': '177.82.90.193', 'port': 8444} did not respond in time.
2022-07-05T17:30:09.386 wallet chia.wallet.wallet_node    : WARNING  Peer None did not respond in time.
2022-07-05T17:30:09.386 wallet chia.wallet.wallet_node    : WARNING  Peer None did not respond in time.
2022-07-05T17:30:09.386 wallet chia.wallet.wallet_node    : WARNING  Peer {'host': '177.82.90.193', 'port': 8444} did not respond in time.
2022-07-05T17:30:09.386 wallet chia.wallet.wallet_node    : WARNING  Peer None did not respond in time.
2022-07-05T17:30:09.387 wallet chia.wallet.wallet_node    : WARNING  Peer None did not respond in time.
2022-07-05T17:30:09.387 wallet chia.wallet.wallet_node    : WARNING  Peer None did not respond in time.
2022-07-05T17:30:09.387 wallet chia.wallet.wallet_node    : WARNING  Peer {'host': '177.82.90.193', 'port': 8444} did not respond in time.
2022-07-05T17:30:09.387 wallet chia.wallet.wallet_node    : WARNING  Peer None did not respond in time.
2022-07-05T17:30:09.387 wallet chia.wallet.wallet_node    : WARNING  Peer None did not respond in time.
2022-07-05T17:30:09.388 wallet chia.wallet.wallet_node    : WARNING  Peer {'host': '177.82.90.193', 'port': 8444} did not respond in time.
2022-07-05T17:30:09.388 wallet chia.wallet.wallet_node    : WARNING  Peer None did not respond in time.
2022-07-05T17:30:09.388 wallet chia.wallet.wallet_node    : WARNING  Peer None did not respond in time.
2022-07-05T17:30:09.388 wallet chia.wallet.wallet_node    : WARNING  Peer None did not respond in time.
2022-07-05T17:30:09.388 wallet chia.wallet.wallet_node    : WARNING  Peer {'host': '177.82.90.193', 'port': 8444} did not respond in time.
2022-07-05T17:30:09.389 wallet chia.wallet.wallet_node    : WARNING  Peer {'host': '177.82.90.193', 'port': 8444} did not respond in time.
2022-07-05T17:30:09.389 wallet chia.wallet.wallet_node    : WARNING  Peer None did not respond in time.
2022-07-05T17:30:09.389 wallet chia.wallet.wallet_node    : WARNING  Peer None did not respond in time.
2022-07-05T17:30:09.389 wallet chia.wallet.wallet_node    : WARNING  Peer {'host': '177.82.90.193', 'port': 8444} did not respond in time.
2022-07-05T17:30:09.390 wallet chia.wallet.wallet_node    : WARNING  Peer {'host': '177.82.90.193', 'port': 8444} did not respond in time.
2022-07-05T17:30:09.390 wallet chia.wallet.wallet_node    : WARNING  Peer None did not respond in time.
2022-07-05T17:30:09.390 wallet chia.wallet.wallet_node    : WARNING  Peer None did not respond in time.
2022-07-05T17:30:09.390 wallet chia.wallet.wallet_node    : WARNING  Peer {'host': '177.82.90.193', 'port': 8444} did not respond in time.
2022-07-05T17:30:09.390 wallet chia.wallet.wallet_node    : WARNING  Peer None did not respond in time.
2022-07-05T17:30:09.391 wallet chia.wallet.wallet_node    : ERROR    Error fetching blocks 1302731 1302915
2022-07-05T17:30:09.391 wallet chia.wallet.wallet_node    : ERROR    Error fetching blocks 1526232 1526407
2022-07-05T17:30:09.396 wallet chia.wallet.wallet_node    : ERROR    Exception while adding state: Not connected to the full node Traceback (most recent call last):
  File "chia/wallet/wallet_node.py", line 683, in receive_and_validate
  File "chia/wallet/wallet_state_manager.py", line 859, in new_coin_state
  File "chia/wallet/wallet_state_manager.py", line 564, in determine_coin_type
  File "chia/wallet/wallet_node.py", line 1451, in get_coin_state
ValueError: Not connected to the full node

2022-07-05T17:39:18.465 daemon __main__                   : ERROR    Unexpected exception trying to send to websocket: Cannot write to closing transport Traceback (most recent call last):
  File "chia/daemon/server.py", line 241, in incoming_connection
  File "aiohttp/web_ws.py", line 308, in send_str
  File "aiohttp/http_websocket.py", line 690, in send
  File "aiohttp/http_websocket.py", line 653, in _send_frame
  File "aiohttp/http_websocket.py", line 663, in _write
ConnectionResetError: Cannot write to closing transport

2022-07-05T17:44:57.379 wallet chia.wallet.wallet_node    : WARNING  Non-trusted peer {'host': '67.21.158.82', 'port': 8444} is not synced, disconnecting
2022-07-05T17:44:57.629 wallet wallet_server              : WARNING  Banning 67.21.158.82 for 120 seconds
2022-07-05T17:44:58.689 wallet chia.wallet.wallet_node    : WARNING  Non-trusted peer {'host': '68.7.60.136', 'port': 8444} is not synced, disconnecting
2022-07-05T17:44:58.869 wallet wallet_server              : WARNING  Banning 68.7.60.136 for 120 seconds
2022-07-05T17:44:59.485 wallet chia.wallet.wallet_node    : WARNING  Non-trusted peer {'host': '213.148.199.23', 'port': 8444} is not synced, disconnecting
2022-07-05T17:44:59.769 wallet wallet_server              : WARNING  Banning 213.148.199.23 for 120 seconds
2022-07-05T17:44:59.810 wallet chia.wallet.wallet_node    : WARNING  Peer None did not respond in time.
2022-07-05T17:44:59.811 wallet chia.wallet.wallet_node    : WARNING  Peer None did not respond in time.
2022-07-05T17:44:59.811 wallet chia.wallet.wallet_node    : WARNING  Peer {'host': '213.148.199.23', 'port': 8444} did not respond in time.
2022-07-05T17:44:59.811 wallet chia.wallet.wallet_node    : WARNING  Peer None did not respond in time.
2022-07-05T17:44:59.812 wallet chia.wallet.wallet_node    : WARNING  Peer None did not respond in time.
2022-07-05T17:44:59.812 wallet chia.wallet.wallet_node    : WARNING  Peer {'host': '213.148.199.23', 'port': 8444} did not respond in time.
2022-07-05T17:44:59.812 wallet chia.wallet.wallet_node    : WARNING  Peer None did not respond in time.
2022-07-05T17:44:59.813 wallet chia.wallet.wallet_node    : WARNING  Peer None did not respond in time.
2022-07-05T17:44:59.813 wallet chia.wallet.wallet_node    : WARNING  Peer {'host': '213.148.199.23', 'port': 8444} did not respond in time.
2022-07-05T17:44:59.813 wallet chia.wallet.wallet_node    : WARNING  Peer None did not respond in time.
2022-07-05T17:44:59.814 wallet chia.wallet.wallet_node    : WARNING  Peer None did not respond in time.
2022-07-05T17:44:59.814 wallet chia.wallet.wallet_node    : WARNING  Peer {'host': '213.148.199.23', 'port': 8444} did not respond in time.
2022-07-05T17:44:59.814 wallet chia.wallet.wallet_node    : WARNING  Peer None did not respond in time.
2022-07-05T17:44:59.814 wallet chia.wallet.wallet_node    : WARNING  Peer None did not respond in time.
2022-07-05T17:44:59.815 wallet chia.wallet.wallet_node    : WARNING  Peer None did not respond in time.
2022-07-05T17:44:59.815 wallet chia.wallet.wallet_node    : WARNING  Peer {'host': '213.148.199.23', 'port': 8444} did not respond in time.
2022-07-05T17:44:59.815 wallet chia.wallet.wallet_node    : WARNING  Peer None did not respond in time.
2022-07-05T17:44:59.815 wallet chia.wallet.wallet_node    : WARNING  Peer None did not respond in time.
2022-07-05T17:44:59.815 wallet chia.wallet.wallet_node    : WARNING  Peer None did not respond in time.
2022-07-05T17:44:59.816 wallet chia.wallet.wallet_node    : WARNING  Peer {'host': '213.148.199.23', 'port': 8444} did not respond in time.
2022-07-05T17:44:59.816 wallet chia.wallet.wallet_node    : WARNING  Peer {'host': '213.148.199.23', 'port': 8444} did not respond in time.
2022-07-05T17:44:59.816 wallet chia.wallet.wallet_node    : WARNING  Peer None did not respond in time.
2022-07-05T17:44:59.816 wallet chia.wallet.wallet_node    : WARNING  Peer None did not respond in time.
2022-07-05T17:44:59.816 wallet chia.wallet.wallet_node    : WARNING  Peer None did not respond in time.
2022-07-05T17:44:59.817 wallet chia.wallet.wallet_node    : WARNING  Peer {'host': '213.148.199.23', 'port': 8444} did not respond in time.
2022-07-05T17:44:59.817 wallet chia.wallet.wallet_node    : WARNING  Peer None did not respond in time.
2022-07-05T17:44:59.817 wallet chia.wallet.wallet_node    : WARNING  Peer {'host': '213.148.199.23', 'port': 8444} did not respond in time.
2022-07-05T17:44:59.817 wallet chia.wallet.wallet_node    : WARNING  Peer None did not respond in time.
2022-07-05T17:44:59.818 wallet chia.wallet.wallet_node    : WARNING  Peer None did not respond in time.
2022-07-05T17:44:59.818 wallet chia.wallet.wallet_node    : WARNING  Peer {'host': '213.148.199.23', 'port': 8444} did not respond in time.
2022-07-05T17:44:59.818 wallet chia.wallet.wallet_node    : WARNING  Peer None did not respond in time.
2022-07-05T17:44:59.818 wallet chia.wallet.wallet_node    : WARNING  Peer None did not respond in time.
2022-07-05T17:44:59.818 wallet chia.wallet.wallet_node    : WARNING  Peer None did not respond in time.
2022-07-05T17:44:59.819 wallet chia.wallet.wallet_node    : WARNING  Peer {'host': '213.148.199.23', 'port': 8444} did not respond in time.
2022-07-05T17:44:59.819 wallet chia.wallet.wallet_node    : WARNING  Peer None did not respond in time.
2022-07-05T17:44:59.819 wallet chia.wallet.wallet_node    : WARNING  Peer None did not respond in time.
2022-07-05T17:44:59.819 wallet chia.wallet.wallet_node    : WARNING  Peer None did not respond in time.
2022-07-05T17:44:59.819 wallet chia.wallet.wallet_node    : WARNING  Peer {'host': '213.148.199.23', 'port': 8444} did not respond in time.
2022-07-05T17:44:59.820 wallet chia.wallet.wallet_node    : WARNING  Peer {'host': '213.148.199.23', 'port': 8444} did not respond in time.
2022-07-05T17:44:59.820 wallet chia.wallet.wallet_node    : WARNING  Peer None did not respond in time.
2022-07-05T17:44:59.820 wallet chia.wallet.wallet_node    : WARNING  Peer None did not respond in time.
2022-07-05T17:44:59.820 wallet chia.wallet.wallet_node    : WARNING  Peer None did not respond in time.
2022-07-05T17:44:59.820 wallet chia.wallet.wallet_node    : WARNING  Peer {'host': '213.148.199.23', 'port': 8444} did not respond in time.
2022-07-05T17:44:59.821 wallet chia.wallet.wallet_node    : WARNING  Peer None did not respond in time.
2022-07-05T17:44:59.821 wallet chia.wallet.wallet_node    : WARNING  Peer {'host': '213.148.199.23', 'port': 8444} did not respond in time.
2022-07-05T17:44:59.821 wallet chia.wallet.wallet_node    : WARNING  Peer None did not respond in time.
2022-07-05T17:44:59.821 wallet chia.wallet.wallet_node    : WARNING  Peer None did not respond in time.
2022-07-05T17:44:59.821 wallet chia.wallet.wallet_node    : WARNING  Peer {'host': '213.148.199.23', 'port': 8444} did not respond in time.
2022-07-05T17:44:59.821 wallet chia.wallet.wallet_node    : WARNING  Peer None did not respond in time.
2022-07-05T17:44:59.822 wallet chia.wallet.wallet_node    : WARNING  Peer None did not respond in time.
2022-07-05T17:44:59.822 wallet chia.wallet.wallet_node    : WARNING  Peer {'host': '213.148.199.23', 'port': 8444} did not respond in time.
2022-07-05T17:44:59.822 wallet chia.wallet.wallet_node    : WARNING  Peer None did not respond in time.
2022-07-05T17:44:59.822 wallet chia.wallet.wallet_node    : WARNING  Peer None did not respond in time.
2022-07-05T17:44:59.822 wallet chia.wallet.wallet_node    : WARNING  Peer {'host': '213.148.199.23', 'port': 8444} did not respond in time.
2022-07-05T17:44:59.822 wallet chia.wallet.wallet_node    : WARNING  Peer None did not respond in time.
2022-07-05T17:44:59.823 wallet chia.wallet.wallet_node    : WARNING  Peer None did not respond in time.
2022-07-05T17:44:59.823 wallet chia.wallet.wallet_node    : WARNING  Peer {'host': '213.148.199.23', 'port': 8444} did not respond in time.
2022-07-05T17:44:59.823 wallet chia.wallet.wallet_node    : WARNING  Peer None did not respond in time.
2022-07-05T17:44:59.823 wallet chia.wallet.wallet_node    : WARNING  Peer None did not respond in time.
2022-07-05T17:44:59.823 wallet chia.wallet.wallet_node    : WARNING  Peer None did not respond in time.
2022-07-05T17:44:59.824 wallet chia.wallet.wallet_node    : WARNING  Peer None did not respond in time.
2022-07-05T17:44:59.824 wallet chia.wallet.wallet_node    : WARNING  Peer {'host': '213.148.199.23', 'port': 8444} did not respond in time.
2022-07-05T17:44:59.824 wallet chia.wallet.wallet_node    : WARNING  Peer {'host': '213.148.199.23', 'port': 8444} did not respond in time.
2022-07-05T17:44:59.824 wallet chia.wallet.wallet_node    : WARNING  Peer None did not respond in time.
2022-07-05T17:44:59.824 wallet chia.wallet.wallet_node    : WARNING  Peer None did not respond in time.
2022-07-05T17:44:59.824 wallet chia.wallet.wallet_node    : WARNING  Peer {'host': '213.148.199.23', 'port': 8444} did not respond in time.
2022-07-05T17:44:59.825 wallet chia.wallet.wallet_node    : WARNING  Peer None did not respond in time.
2022-07-05T17:44:59.825 wallet chia.wallet.wallet_node    : WARNING  Peer None did not respond in time.
2022-07-05T17:44:59.825 wallet chia.wallet.wallet_node    : WARNING  Peer None did not respond in time.
2022-07-05T17:44:59.825 wallet chia.wallet.wallet_node    : WARNING  Peer {'host': '213.148.199.23', 'port': 8444} did not respond in time.
2022-07-05T17:44:59.825 wallet chia.wallet.wallet_node    : WARNING  Peer None did not respond in time.
2022-07-05T17:44:59.826 wallet chia.wallet.wallet_node    : WARNING  Peer {'host': '213.148.199.23', 'port': 8444} did not respond in time.
2022-07-05T17:44:59.826 wallet chia.wallet.wallet_node    : WARNING  Peer None did not respond in time.
2022-07-05T17:44:59.826 wallet chia.wallet.wallet_node    : WARNING  Peer None did not respond in time.
2022-07-05T17:44:59.826 wallet chia.wallet.wallet_node    : WARNING  Peer None did not respond in time.
2022-07-05T17:44:59.826 wallet chia.wallet.wallet_node    : WARNING  Peer {'host': '213.148.199.23', 'port': 8444} did not respond in time.
2022-07-05T17:44:59.826 wallet chia.wallet.wallet_node    : WARNING  Peer None did not respond in time.
2022-07-05T17:44:59.827 wallet chia.wallet.wallet_node    : WARNING  Peer {'host': '213.148.199.23', 'port': 8444} did not respond in time.
2022-07-05T17:44:59.827 wallet chia.wallet.wallet_node    : WARNING  Peer None did not respond in time.
2022-07-05T17:44:59.827 wallet chia.wallet.wallet_node    : WARNING  Peer None did not respond in time.
2022-07-05T17:44:59.827 wallet chia.wallet.wallet_node    : WARNING  Peer None did not respond in time.
2022-07-05T17:44:59.827 wallet chia.wallet.wallet_node    : WARNING  Peer None did not respond in time.
2022-07-05T17:44:59.828 wallet chia.wallet.wallet_node    : WARNING  Peer {'host': '213.148.199.23', 'port': 8444} did not respond in time.
2022-07-05T17:44:59.828 wallet chia.wallet.wallet_node    : WARNING  Peer None did not respond in time.
2022-07-05T17:44:59.828 wallet chia.wallet.wallet_node    : WARNING  Peer {'host': '213.148.199.23', 'port': 8444} did not respond in time.
2022-07-05T17:44:59.828 wallet chia.wallet.wallet_node    : WARNING  Peer None did not respond in time.
2022-07-05T17:44:59.828 wallet chia.wallet.wallet_node    : WARNING  Peer {'host': '213.148.199.23', 'port': 8444} did not respond in time.
2022-07-05T17:44:59.828 wallet chia.wallet.wallet_node    : WARNING  Peer None did not respond in time.
2022-07-05T17:44:59.829 wallet chia.wallet.wallet_node    : WARNING  Peer None did not respond in time.
2022-07-05T17:44:59.829 wallet chia.wallet.wallet_node    : WARNING  Peer None did not respond in time.
2022-07-05T17:44:59.829 wallet chia.wallet.wallet_node    : WARNING  Peer {'host': '213.148.199.23', 'port': 8444} did not respond in time.
2022-07-05T17:44:59.829 wallet chia.wallet.wallet_node    : WARNING  Peer None did not respond in time.
2022-07-05T17:44:59.829 wallet chia.wallet.wallet_node    : WARNING  Peer None did not respond in time.
2022-07-05T17:44:59.829 wallet chia.wallet.wallet_node    : WARNING  Peer {'host': '213.148.199.23', 'port': 8444} did not respond in time.
2022-07-05T17:44:59.829 wallet chia.wallet.wallet_node    : WARNING  Peer None did not respond in time.
2022-07-05T17:44:59.830 wallet chia.wallet.wallet_node    : WARNING  Peer None did not respond in time.
2022-07-05T17:44:59.830 wallet chia.wallet.wallet_node    : WARNING  Peer {'host': '213.148.199.23', 'port': 8444} did not respond in time.
2022-07-05T17:44:59.830 wallet chia.wallet.wallet_node    : WARNING  Peer None did not respond in time.
2022-07-05T17:44:59.830 wallet chia.wallet.wallet_node    : WARNING  Peer None did not respond in time.
2022-07-05T17:44:59.830 wallet chia.wallet.wallet_node    : WARNING  Peer {'host': '213.148.199.23', 'port': 8444} did not respond in time.
2022-07-05T17:44:59.830 wallet chia.wallet.wallet_node    : WARNING  Peer None did not respond in time.
2022-07-05T17:46:35.006 wallet chia.rpc.rpc_server        : WARNING  Error while handling message: Traceback (most recent call last):
  File "chia/rpc/rpc_server.py", line 237, in safe_handle
  File "aiohttp/client_ws.py", line 151, in send_str
  File "aiohttp/http_websocket.py", line 690, in send
  File "aiohttp/http_websocket.py", line 601, in _send_frame
ConnectionResetError: Cannot write to closing transport

2022-07-05T17:46:35.006 wallet chia.rpc.rpc_server        : WARNING  Exception: Traceback (most recent call last):
  File "chia/rpc/rpc_server.py", line 237, in safe_handle
  File "aiohttp/client_ws.py", line 151, in send_str
  File "aiohttp/http_websocket.py", line 690, in send
  File "aiohttp/http_websocket.py", line 601, in _send_frame
ConnectionResetError: Cannot write to closing transport

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "chia/rpc/rpc_server.py", line 288, in connect_to_daemon
  File "chia/rpc/rpc_server.py", line 257, in connection
  File "chia/rpc/rpc_server.py", line 245, in safe_handle
  File "aiohttp/client_ws.py", line 151, in send_str
  File "aiohttp/http_websocket.py", line 690, in send
  File "aiohttp/http_websocket.py", line 601, in _send_frame
ConnectionResetError: Cannot write to closing transport
 <class 'ConnectionResetError'>
2022-07-05T17:57:17.614 wallet chia.rpc.rpc_server        : WARNING  Error while handling message: Traceback (most recent call last):
  File "chia/rpc/rpc_server.py", line 237, in safe_handle
  File "aiohttp/client_ws.py", line 151, in send_str
  File "aiohttp/http_websocket.py", line 690, in send
  File "aiohttp/http_websocket.py", line 646, in _send_frame
  File "aiohttp/http_websocket.py", line 663, in _write
ConnectionResetError: Cannot write to closing transport

2022-07-05T17:57:17.615 wallet chia.rpc.rpc_server        : WARNING  Exception: Traceback (most recent call last):
  File "chia/rpc/rpc_server.py", line 237, in safe_handle
  File "aiohttp/client_ws.py", line 151, in send_str
  File "aiohttp/http_websocket.py", line 690, in send
  File "aiohttp/http_websocket.py", line 646, in _send_frame
  File "aiohttp/http_websocket.py", line 663, in _write
ConnectionResetError: Cannot write to closing transport

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "chia/rpc/rpc_server.py", line 288, in connect_to_daemon
  File "chia/rpc/rpc_server.py", line 257, in connection
  File "chia/rpc/rpc_server.py", line 245, in safe_handle
  File "aiohttp/client_ws.py", line 151, in send_str
  File "aiohttp/http_websocket.py", line 690, in send
  File "aiohttp/http_websocket.py", line 646, in _send_frame
  File "aiohttp/http_websocket.py", line 663, in _write
ConnectionResetError: Cannot write to closing transport
 <class 'ConnectionResetError'>
2022-07-05T17:57:18.909 wallet chia.wallet.wallet_node    : WARNING  Non-trusted peer {'host': '177.82.90.193', 'port': 8444} is not synced, disconnecting
2022-07-05T17:57:19.306 wallet wallet_server              : WARNING  Banning 177.82.90.193 for 120 seconds
2022-07-05T17:57:19.346 wallet chia.wallet.wallet_node    : WARNING  Peer None did not respond in time.
2022-07-05T17:57:19.347 wallet chia.wallet.wallet_node    : WARNING  Peer None did not respond in time.
2022-07-05T17:57:19.347 wallet chia.wallet.wallet_node    : WARNING  Peer None did not respond in time.
2022-07-05T17:57:19.347 wallet chia.wallet.wallet_node    : WARNING  Peer None did not respond in time.
2022-07-05T17:57:19.348 wallet chia.wallet.wallet_node    : WARNING  Peer None did not respond in time.
2022-07-05T17:57:19.348 wallet chia.wallet.wallet_node    : WARNING  Peer None did not respond in time.
2022-07-05T17:57:19.348 wallet chia.wallet.wallet_node    : WARNING  Peer None did not respond in time.
2022-07-05T17:57:19.348 wallet chia.wallet.wallet_node    : WARNING  Peer None did not respond in time.
2022-07-05T17:59:04.371 wallet chia.rpc.rpc_server        : WARNING  Error while handling message: Traceback (most recent call last):
  File "chia/rpc/rpc_server.py", line 237, in safe_handle
  File "aiohttp/client_ws.py", line 151, in send_str
  File "aiohttp/http_websocket.py", line 690, in send
  File "aiohttp/http_websocket.py", line 601, in _send_frame
ConnectionResetError: Cannot write to closing transport

2022-07-05T17:59:04.372 wallet chia.rpc.rpc_server        : WARNING  Exception: Traceback (most recent call last):
  File "chia/rpc/rpc_server.py", line 237, in safe_handle
  File "aiohttp/client_ws.py", line 151, in send_str
  File "aiohttp/http_websocket.py", line 690, in send
  File "aiohttp/http_websocket.py", line 601, in _send_frame
ConnectionResetError: Cannot write to closing transport

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "chia/rpc/rpc_server.py", line 288, in connect_to_daemon
  File "chia/rpc/rpc_server.py", line 257, in connection
  File "chia/rpc/rpc_server.py", line 245, in safe_handle
  File "aiohttp/client_ws.py", line 151, in send_str
  File "aiohttp/http_websocket.py", line 690, in send
  File "aiohttp/http_websocket.py", line 601, in _send_frame
ConnectionResetError: Cannot write to closing transport
 <class 'ConnectionResetError'>
```

**Comment by icodestuffx** [comment]
Update: I edited config.yaml specifying my own remote full node in the wallet section, synced from fresh within minutes and have remained synced without spinners since.

**Comment by emlowe** [comment]
I believe the original problems were all related to networking issues with your wallet client finding good peers to sync with (notice all the timeouts and did not respond in time entries). As you noted, using your own node is often a solution to this. Closing issue as it doesn't appear to be any problem other than networking
