### ISSUE TITLE
[Bug] AttributeError: 'FullNode' object has no attribute 'simulator_transaction_callback'

### ISSUE THREAD

**Issue by d1m1trus** [Chia-Network/chia-blockchain#12448]
### What happened?

After the update 1.4.1.dev337, this error appeared. Synchronization does not occur, peers do not connect.

### Version

1.4.1.dev337

### What platform are you using?

Linux

### What ui mode are you using?

GUI

### Relevant log output

```shell
2022-07-17T07:28:24.344 full_node chia.full_node.full_node: ERROR    Error in _handle_one_transaction, closing: Traceback (most recent call last):
  File "/opt/chia/1.4.1.dev337/chia/full_node/full_node.py", line 318, in _handle_one_transaction
    inc_status, err = await self.respond_transaction(entry.transaction, entry.spend_name, peer, entry.test)
  File "/opt/chia/1.4.1.dev337/chia/full_node/full_node.py", line 2117, in respond_transaction
    if self.simulator_transaction_callback is not None:  # callback
AttributeError: 'FullNode' object has no attribute 'simulator_transaction_callback'

2022-07-17T07:28:24.349 full_node chia.full_node.full_node: ERROR    Error in _handle_one_transaction, closing: Traceback (most recent call last):
  File "/opt/chia/1.4.1.dev337/chia/full_node/full_node.py", line 318, in _handle_one_transaction
    inc_status, err = await self.respond_transaction(entry.transaction, entry.spend_name, peer, entry.test)
  File "/opt/chia/1.4.1.dev337/chia/full_node/full_node.py", line 2117, in respond_transaction
    if self.simulator_transaction_callback is not None:  # callback
AttributeError: 'FullNode' object has no attribute 'simulator_transaction_callback'

2022-07-17T07:28:24.360 full_node chia.full_node.full_node: ERROR    Error in _handle_one_transaction, closing: Traceback (most recent call last):
  File "/opt/chia/1.4.1.dev337/chia/full_node/full_node.py", line 318, in _handle_one_transaction
    inc_status, err = await self.respond_transaction(entry.transaction, entry.spend_name, peer, entry.test)
  File "/opt/chia/1.4.1.dev337/chia/full_node/full_node.py", line 2117, in respond_transaction
    if self.simulator_transaction_callback is not None:  # callback
AttributeError: 'FullNode' object has no attribute 'simulator_transaction_callback'
```

**Comment by jack60612** [comment]
This was fixed, please pull from main again.
