### ISSUE TITLE
RuntimeError: Event loop is closed while plotting

### ISSUE THREAD

**Issue by adesgran9** [Chia-Network/chia-blockchain#12474]
Hello i keep getting an RuntimeError: Event loop is closed while trying to create new plots

> Multi-threaded pipelined Chia k32 plotter - 2092041
Network Port: 8444
Final Directory: I:\Chia Farm\Chia Plots\
Number of Plots: 1
Crafting plot 1 out of 1 (2022/07/19 03:09:19)
Process ID: 9552
Number of Threads: 4
Number of Buckets P1:    2^8 (256)
Number of Buckets P3+P4: 2^8 (256)
Pool Puzzle Hash:  a0ad194b848c7c323a854fd9cee76bf0339b4ccf5f4cf18657eed570917e1821
Farmer Public Key: 8f3d00a790a9dd360a6548e86b3328914a11c1e8f2182659ec4e5c08d91aeb96c3f7c8df51a744d86a3db9c888ef57ad
Working Directory:   C:\chia\Active Plotting\
Working Directory 2: C:\chia\Active Plotting\
Plot Name: plot-k32-2022-07-19-03-09-ee3d0aff94079db22c1265df2ed28964ec69d95bf0c1acd522dd4f6062c21db9
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x0000026730CB52E0>
Fatal error on SSL transport
protocol: <asyncio.sslproto.SSLProtocol object at 0x0000026730C9A190>
transport: <_ProactorSocketTransport fd=-1 read=<_OverlappedFuture cancelled>>
Traceback (most recent call last):
  File "asyncio\sslproto.py", line 690, in _process_write_backlog
  File "asyncio\proactor_events.py", line 359, in write
  File "asyncio\proactor_events.py", line 395, in _loop_writing
AttributeError: 'NoneType' object has no attribute 'send'
Exception ignored in: <function _SSLProtocolTransport.__del__ at 0x000002672F67D0D0>
Traceback (most recent call last):
  File "asyncio\sslproto.py", line 321, in __del__
  File "asyncio\sslproto.py", line 316, in close
  File "asyncio\sslproto.py", line 599, in _start_shutdown
  File "asyncio\sslproto.py", line 604, in _write_appdata
  File "asyncio\sslproto.py", line 712, in _process_write_backlog
  File "asyncio\sslproto.py", line 726, in _fatal_error
  File "asyncio\proactor_events.py", line 151, in _force_close
  File "asyncio\base_events.py", line 751, in call_soon
  File "asyncio\base_events.py", line 515, in _check_closed
RuntimeError: Event loop is closed

**Comment by wallentx** [comment]
Are you using the GUI to create these plots?
Also, did you verify if this actually stopped the plotting process?
