### ISSUE TITLE
[Bug] Unable to apply for rewards

### ISSUE THREAD

**Issue by tiger-hn** [Chia-Network/chia-blockchain#12502]
### What happened?

I received 0.25xch at the block height of 2275810, but I couldn't get the 1.75xch reward at the cooperative. There is no response after clicking to apply for the reward. Click the prompt again:
cannot claim due to unconfirmed transaction.if this is stuck,delete the unconfirmed transaction.

Please let me know if you need me to provide further information.

### Version

1.4.0

### What platform are you using?

Windows

### What ui mode are you using?

GUI

### Relevant log output

```shell
2022-07-20T08:34:45.140 wallet chia.wallet.wallet_node    : WARNING  SpendBundle has been rejected by the FullNode. {'error': 'DOUBLE_SPEND', 'status': 3, 'txid': '0x76923420c5b412da3b8373f8c5bdbeef5a88780611f4d3cd8b9f595288a2434a'}
2022-07-20T08:35:18.959 farmer chia.farmer.farmer         : ERROR    Error in pooling: (14, 'The singleton with launcherId B9DD00E5ECED2562D590E9E510F02726147CA786238546F8FF0CA14F575A5A2C is not assigned to this pool')
2022-07-20T08:36:48.800 farmer chia.farmer.farmer         : ERROR    Error in pooling: (14, 'The singleton with launcherId B9DD00E5ECED2562D590E9E510F02726147CA786238546F8FF0CA14F575A5A2C is not assigned to this pool')
2022-07-20T08:44:22.332 wallet chia.wallet.wallet_node    : WARNING  SpendBundle has been rejected by the FullNode. {'error': 'DOUBLE_SPEND', 'status': 3, 'txid': '0x76923420c5b412da3b8373f8c5bdbeef5a88780611f4d3cd8b9f595288a2434a'}
2022-07-20T08:44:24.302 wallet chia.rpc.rpc_server        : WARNING  Error while handling message: Traceback (most recent call last):
  File "chia\rpc\rpc_server.py", line 229, in safe_handle
  File "chia\rpc\rpc_server.py", line 220, in ws_api
  File "chia\rpc\wallet_rpc_api.py", line 1887, in pw_absorb_rewards
  File "chia\pools\pool_wallet.py", line 788, in claim_pool_rewards
ValueError: Cannot claim due to unconfirmed transaction. If this is stuck, delete the unconfirmed transaction.

2022-07-20T08:46:15.356 farmer chia.farmer.farmer         : ERROR    Error in pooling: (14, 'The singleton with launcherId B9DD00E5ECED2562D590E9E510F02726147CA786238546F8FF0CA14F575A5A2C is not assigned to this pool')
2022-07-20T08:50:44.270 wallet chia.wallet.wallet_node    : WARNING  SpendBundle has been rejected by the FullNode. {'error': 'DOUBLE_SPEND', 'status': 3, 'txid': '0x76923420c5b412da3b8373f8c5bdbeef5a88780611f4d3cd8b9f595288a2434a'}
2022-07-20T08:52:26.559 farmer chia.farmer.farmer         : ERROR    Error in pooling: (14, 'The singleton with launcherId B9DD00E5ECED2562D590E9E510F02726147CA786238546F8FF0CA14F575A5A2C is not assigned to this pool')
2022-07-20T08:52:51.574 farmer chia.farmer.farmer         : ERROR    Error in pooling: (14, 'The singleton with launcherId B9DD00E5ECED2562D590E9E510F02726147CA786238546F8FF0CA14F575A5A2C is not assigned to this pool')
2022-07-20T08:54:24.568 farmer chia.farmer.farmer         : ERROR    Error in pooling: (14, 'The singleton with launcherId B9DD00E5ECED2562D590E9E510F02726147CA786238546F8FF0CA14F575A5A2C is not assigned to this pool')
2022-07-20T08:55:02.219 farmer chia.farmer.farmer         : ERROR    Error in pooling: (14, 'The singleton with launcherId B9DD00E5ECED2562D590E9E510F02726147CA786238546F8FF0CA14F575A5A2C is not assigned to this pool')
2022-07-20T08:55:38.728 wallet chia.rpc.rpc_server        : WARNING  Error while handling message: Traceback (most recent call last):
  File "chia\rpc\rpc_server.py", line 229, in safe_handle
  File "chia\rpc\rpc_server.py", line 220, in ws_api
  File "chia\rpc\wallet_rpc_api.py", line 1887, in pw_absorb_rewards
  File "chia\pools\pool_wallet.py", line 788, in claim_pool_rewards
ValueError: Cannot claim due to unconfirmed transaction. If this is stuck, delete the unconfirmed transaction.

2022-07-20T08:59:03.744 farmer chia.farmer.farmer         : ERROR    Error in pooling: (14, 'The singleton with launcherId B9DD00E5ECED2562D590E9E510F02726147CA786238546F8FF0CA14F575A5A2C is not assigned to this pool')
```

**Comment by wallentx** [comment]
You are self-pooling, correct? It sometimes might take a while for these to go through. Did you see if the 1.75 transaction ever came through? Did you enter in a fee when claiming the transaction? Also, can you share a screenshot of the Pool page in the GUI? You may omit the `launcher_id`.

**Comment by tiger-hn** [comment]
I can apply for rewards normally after I change a machine to synchronize my wallet. It is also version 1.4.0. So is it a configuration problem?
I took a screenshot, but I don't know how to upload it to this page.

Is it all right now? Close this bug?

**Comment by tiger-hn** [comment]
I can see 1.75xch, I can't switch the pool, prompt: please apply for the reward first. The transaction cannot be completed if 1mojos or 500000 Ojos have been entered in the fee. If the fee is entered, the transaction that has been pending confirmation in the wallet has not been completed.

**Comment by tiger-hn** [comment]
Thank you, William. I closed this bug.

**Comment by tiger-hn** [comment]
There is a problem again, the same as last time.

debug.txt display

2022-07-27T08:47:21.659 farmer chia.farmer.farmer         : ERROR    Error in pooling: (14, 'The singleton with launcherId B9DD00E5ECED2562D590E9E510F02726147CA786238546F8FF0CA14F575A5A2C is not assigned to this pool')
2022-07-27T08:49:13.175 wallet chia.rpc.rpc_server        : WARNING  Error while handling message: Traceback (most recent call last):
  File "chia\rpc\rpc_server.py", line 229, in safe_handle
  File "chia\rpc\rpc_server.py", line 220, in ws_api
  File "chia\rpc\wallet_rpc_api.py", line 1887, in pw_absorb_rewards
  File "chia\pools\pool_wallet.py", line 788, in claim_pool_rewards
ValueError: Cannot claim due to unconfirmed transaction. If this is stuck, delete the unconfirmed transaction.

2022-07-27T08:49:47.522 full_node chia.full_node.full_node: WARNING  Block validation time: 2.12 seconds, pre_validation time: 0.36 seconds, cost: 3424217986, percent full: 31.129% header_hash: ba4dc92ad92f2e603abc0eba61da6d811fad9ad962dcda8705d3e9ccf17ecda3 height: 2313374
2022-07-27T08:49:51.744 farmer chia.farmer.farmer         : ERROR    Error in pooling: (14, 'The singleton with launcherId B9DD00E5ECED2562D590E9E510F02726147CA786238546F8FF0CA14F575A5A2C is not assigned to this pool')

**Comment by tiger-hn** [comment]
![图片](https://user-images.githubusercontent.com/66813799/181138161-eb90e71a-0cf9-4f38-bd63-fe290cac43e8.png)

**Comment by tiger-hn** [comment]
After I applied for the reward last time, I couldn't switch pool.
After entering the fee during pool switching, the "pending" will always be displayed in the exchange record.

Unconfirmed transactions can also be deleted.

**Comment by tiger-hn** [comment]
Switch pool debug.txt display:

2022-07-26T08:57:12.276 full_node chia.full_node.full_node: ERROR    Respond peers exception: 'NoneType' object has no attribute 'host'. Traceback: Traceback (most recent call last):
  File "chia\server\node_discovery.py", line 624, in respond_peers
  File "chia\server\node_discovery.py", line 589, in add_peers_neighbour
AttributeError: 'NoneType' object has no attribute 'host'

2022-07-26T08:57:23.863 wallet chia.wallet.wallet_node    : WARNING  SpendBundle has been rejected by the FullNode. {'error': 'ALREADY_INCLUDING_TRANSACTION',
 'status': 3,
 'txid': '0x19cd21583e0d7c228659c0f669257ea87fc85d1e5482fe57dc92f293b8a0dd0e'}
2022-07-26T08:57:23.865 wallet chia.wallet.wallet_node    : WARNING  SpendBundle has been rejected by the FullNode. {'error': 'ALREADY_INCLUDING_TRANSACTION',
 'status': 3,
 'txid': '0x19cd21583e0d7c228659c0f669257ea87fc85d1e5482fe57dc92f293b8a0dd0e'}
2022-07-26T09:00:59.468 wallet chia.rpc.rpc_server        : WARNING  Error while handling message: Traceback (most recent call last):
  File "chia\rpc\rpc_server.py", line 229, in safe_handle
  File "chia\rpc\rpc_server.py", line 220, in ws_api
  File "chia\rpc\wallet_rpc_api.py", line 1870, in pw_self_pool
  File "chia\pools\pool_wallet.py", line 753, in self_pool
ValueError: Attempted to self pool when already self poolingSwitch pool debug.txt display:

2022-07-26T08:57:12.276 full_node chia.full_node.full_node: ERROR    Respond peers exception: 'NoneType' object has no attribute 'host'. Traceback: Traceback (most recent call last):
  File "chia\server\node_discovery.py", line 624, in respond_peers
  File "chia\server\node_discovery.py", line 589, in add_peers_neighbour
AttributeError: 'NoneType' object has no attribute 'host'

2022-07-26T08:57:23.863 wallet chia.wallet.wallet_node    : WARNING  SpendBundle has been rejected by the FullNode. {'error': 'ALREADY_INCLUDING_TRANSACTION',
 'status': 3,
 'txid': '0x19cd21583e0d7c228659c0f669257ea87fc85d1e5482fe57dc92f293b8a0dd0e'}
2022-07-26T08:57:23.865 wallet chia.wallet.wallet_node    : WARNING  SpendBundle has been rejected by the FullNode. {'error': 'ALREADY_INCLUDING_TRANSACTION',
 'status': 3,
 'txid': '0x19cd21583e0d7c228659c0f669257ea87fc85d1e5482fe57dc92f293b8a0dd0e'}
2022-07-26T09:00:59.468 wallet chia.rpc.rpc_server        : WARNING  Error while handling message: Traceback (most recent call last):
  File "chia\rpc\rpc_server.py", line 229, in safe_handle
  File "chia\rpc\rpc_server.py", line 220, in ws_api
  File "chia\rpc\wallet_rpc_api.py", line 1870, in pw_self_pool
  File "chia\pools\pool_wallet.py", line 753, in self_pool
ValueError: Attempted to self pool when already self pooling
