### ISSUE TITLE
[Bug] `wallet_ui` service updates stop after reconnect

### ISSUE THREAD

**Issue by felixbrucker** [Chia-Network/chia-blockchain#12534]
### Steps to reproduce:
- Start a chia full node (tested with 1.3.5 and 1.4.0)
- Connect to its daemon via websocket
- Register the `wallet_ui` service
- Observe that new `get_blockchain_state` updates come in regularly
- Reconnect the websocket connection
- Observe the wallet throwing lots of these errors:
```
2022-07-22T08:18:23.223 daemon chia.daemon.server         : ERROR    Unexpected exception trying to send to websocket: Cannot write to closing transport Traceback (most recent call last):
  File "/app/chia/daemon/server.py", line 241, in incoming_connection
    await socket.send_str(response)
  File "/app/venv/lib/python3.10/site-packages/aiohttp/web_ws.py", line 308, in send_str
    await self._writer.send(data, binary=False, compress=compress)
  File "/app/venv/lib/python3.10/site-packages/aiohttp/http_websocket.py", line 690, in send
    await self._send_frame(message, WSMsgType.TEXT, compress)
  File "/app/venv/lib/python3.10/site-packages/aiohttp/http_websocket.py", line 601, in _send_frame
    raise ConnectionResetError("Cannot write to closing transport")
ConnectionResetError: Cannot write to closing transport
```
- Register the `wallet_ui` service again
- Observe no more `get_blockchain_state` updates coming in, despite the service being registered

### Expected behavior:
- no such errors are thrown (or only a few if there are indeed in-flight requests for the closing socket)
- after registering the service for the reconnected connection new updates come in

### Notes:
In previous versions (at least 1.2.11 and below) the wallet also threw tons of these errors but registering the `wallet_ui` service actually resulted in updates coming in again after a reconnect.

### Version

1.4.0

### What platform are you using?

Linux

### What ui mode are you using?

CLI

**Comment by felixbrucker** [comment]
Seems this was fixed in 1.5.0 with https://github.com/Chia-Network/chia-blockchain/pull/12241
