### ISSUE TITLE
[Bug] 1.5.0 no such column: is_block

### ISSUE THREAD

**Issue by Jsewill** [Chia-Network/chia-blockchain#12612]
### What happened?

`chia start farmer`

after a few seconds I receive this:

```shell
Traceback (most recent call last):
  File "<redacted_path>chia-blockchain/venv/bin/chia_full_node", line 33, in <module>
    sys.exit(load_entry_point('chia-blockchain', 'console_scripts', 'chia_full_node')())
  File "<redacted_path>chia-blockchain/chia/server/start_full_node.py", line 60, in main
    return run_service(**kwargs)
  File "<redacted_path>chia-blockchain/chia/server/start_service.py", line 255, in run_service
    return asyncio.run(async_run_service(*args, **kwargs))
  File "/usr/lib/python3.7/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.7/asyncio/base_events.py", line 587, in run_until_complete
    return future.result()
  File "<redacted_path>chia-blockchain/chia/server/start_service.py", line 249, in async_run_service
    return await service.run()
  File "<redacted_path>chia-blockchain/chia/server/start_service.py", line 171, in run
    await self.start()
  File "<redacted_path>chia-blockchain/chia/server/start_service.py", line 135, in start
    await self._node._start(**kwargs)
  File "<redacted_path>chia-blockchain/chia/full_node/full_node.py", line 124, in _start 
    self.block_store = await BlockStore.create(self.db_wrapper)
  File "<redacted_path>chia-blockchain/chia/full_node/block_store.py", line 55, in create 
    await self.db.execute("CREATE INDEX IF NOT EXISTS is_block on full_blocks(is_block)")
  File "<redacted_path>chia-blockchain/venv/lib/python3.7/site-packages/aiosqlite/core.py", line 184, in execute
    cursor = await self._execute(self._conn.execute, sql, parameters)
  File "<redacted_path>chia-blockchain/venv/lib/python3.7/site-packages/aiosqlite/core.py", line 129, in _execute
    return await future
  File "<redacted_path>chia-blockchain/venv/lib/python3.7/site-packages/aiosqlite/core.py", line 102, in run
    result = function()
sqlite3.OperationalError: no such column: is_block
```

There are no log entries about the traceback above, and the wallet, harvester, and farmer all refuse to connect to the full node:

```shell
2022-07-26T19:12:04.482 harvester harvester               : INFO     Reconnecting to peer {'host': '127.0.0.1', 'port': 8447}
2022-07-26T19:12:04.486 harvester harvester_server        : INFO     Cannot connect to host 127.0.0.1:8447 ssl:<ssl.SSLContext object at <redacted_memory_address>> [Connect call failed ('127.0.0.1', 8447)]
2022-07-26T19:15:16.530 farmer farmer                     : INFO     Reconnecting to peer {'host': '127.0.0.1', 'port': 8444}
2022-07-26T19:15:16.553 farmer farmer_server              : INFO     Cannot connect to host 127.0.0.1:8444 ssl:<ssl.SSLContext object at <redacted_memory_address>> [Connect call failed ('127.0.0.1', 8444)]
2022-07-26T19:15:16.271 wallet wallet                     : INFO     Reconnecting to peer {'host': '127.0.0.1', 'port': 8444}
2022-07-26T19:15:16.296 wallet wallet_server              : INFO     Cannot connect to host 127.0.0.1:8444 ssl:<ssl.SSLContext object at <redacted_memory_address>> [Connect call failed ('127.0.0.1', 8444)]
```

and at all times, `chia show -sc` returns this:
```shell
Connection error. Check if full node rpc is running at 8555
This is normal if full node is still starting up
```

Furthermore, on shutdown I receive this error:
```shell
Exception ignored in: <module 'threading' from '/usr/lib/python3.7/threading.py'>
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 1307, in _shutdown
    lock.acquire()
  File "<redacted_path>chia-blockchain/chia/server/start_service.py", line 193, in _accept_signal
    self.stop()
  File "<redacted_path>chia-blockchain/chia/server/start_service.py", line 209, in stop
    self._server.close_all()
  File "<redacted_path>chia-blockchain/chia/server/server.py", line 634, in close_all 
    self.connection_close_task = asyncio.create_task(self.close_all_connections())
  File "/usr/lib/python3.7/asyncio/tasks.py", line 350, in create_task
    loop = events.get_running_loop()
RuntimeError: no running event loop
sys:1: RuntimeWarning: coroutine 'ChiaServer.close_all_connections' was never awaited
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
daemon: {'ack': True, 'command': 'exit', 'data': {'success': True}, 'destination': 'client', 'origin': 'daemon', 'request_id': '153c906b2c92ec89f446b475a0c62db11d4dbb3da56f6d406920ef6c38c81f54'}
```

Chia 1.5.0 is currently unusable for me. I will try downgrading while you work to resolve these issues. I hope 1.5.0 didn't bork my DB. Thanks in advance for working to resolve this!

UPDATE: after upgrading chia to 1.5.0 on another machine which is only running the wallet, and synchronizing the wallet, my XCH balance shows 6x less than I actually have in my wallet. Downgrading and letting the wallet resync, fixed it.

### Version

1.5.0

### What platform are you using?

Linux

### What ui mode are you using?

CLI

### Relevant log output

```shell
2022-07-26T19:12:04.482 harvester harvester               : INFO     Reconnecting to peer {'host': '127.0.0.1', 'port': 8447}
2022-07-26T19:12:04.486 harvester harvester_server        : INFO     Cannot connect to host 127.0.0.1:8447 ssl:<ssl.SSLContext object at <redacted_memory_address>> [Connect call failed ('127.0.0.1', 8447)]
2022-07-26T19:15:16.530 farmer farmer                     : INFO     Reconnecting to peer {'host': '127.0.0.1', 'port': 8444}
2022-07-26T19:15:16.553 farmer farmer_server              : INFO     Cannot connect to host 127.0.0.1:8444 ssl:<ssl.SSLContext object at <redacted_memory_address>> [Connect call failed ('127.0.0.1', 8444)]
2022-07-26T19:15:16.271 wallet wallet                     : INFO     Reconnecting to peer {'host': '127.0.0.1', 'port': 8444}
2022-07-26T19:15:16.296 wallet wallet_server              : INFO     Cannot connect to host 127.0.0.1:8444 ssl:<ssl.SSLContext object at <redacted_memory_address>> [Connect call failed ('127.0.0.1', 8444)]
```

**Comment by Jsewill** [comment]
I have confirmed, downgrading to Chia 1.4.0 gets my farmer back online.

**Comment by stefan-lange** [comment]
Have you migrated your blockchain db to v2 with chia 1.3?

**Comment by rizlah** [comment]
I am having the same issue, tbh when I woke this morning my farm had stoped working, so I updated to 1.5.0, which itself was a challenge, but the issue still exists, it connected and worked for about 10 minutes, then went back to the same issue as you mention above.  looks to me like the server side has some issues after the 1.5.0 upgrade.

**Comment by stefan-lange** [comment]
I also upgraded from 1.4.0 to 1.5.0 without any issues (so far). My blockchain db is v2.

Error in the stack trace is `no such column: is_block`. This could have sth todo with your blockchain database.

You guys could check the config.yaml (users/USERNAME/.chia/mainnet/config/config.yaml).
There is a section `full_node`, followed by `database_path`. What is the value of this property? db/blockchain_v1 or db/blockchain_v2...?

**Comment by rizlah** [comment]
Mine is on database_path: db/blockchain_v2_CHALLENGE.sqlite

**Comment by rizlah** [comment]
seems if i install the GUI on my ubuntu machine, i can launch it that way, just not through the CLI, very strange

**Comment by Jsewill** [comment]
> Have you migrated your blockchain db to v2 with chia 1.3?

Yes.

**Comment by Jsewill** [comment]
> I also upgraded from 1.4.0 to 1.5.0 without any issues (so far). My blockchain db is v2.
> 
> Error in the stack trace is `no such column: is_block`. This could have sth todo with your blockchain database.
> 
> You guys could check the config.yaml (users/USERNAME/.chia/mainnet/config/config.yaml). There is a section `full_node`, followed by `database_path`. What is the value of this property? db/blockchain_v1 or db/blockchain_v2...?
> 
> The thread creator could also adjust the title of the Bug an add the 'no such column: is_block' as short error message. Maybe that will trigger Arvid ;)

For some reason I thought that I had put a descriptive title on this issue. I must be too busy.

**Comment by stefan-lange** [comment]
> seems if i install the GUI on my ubuntu machine, i can launch it that way, just not through the CLI, very strange

Hm, indeed, sounds a bit strange. I have everything in docker (debian 11, python 3.10), all-the-way CLI without GUI.

**Comment by Jsewill** [comment]
I know the Chia team is hard at work, but I do hope they can address this problem. I can't be the only one dealing with these issues. I have CATs to reissue too.

**Comment by arvidn** [comment]
the `is_block` field only exists in v1 databases. it's possible that the database file is in v2 format but for some reason is mistaken as a v1 format.

The full node determines the version by looking up `SELECT * from database_version`.

you could check using the `sqlite3` tool, like this:
```
sqlite3 ~/.chia/mainnet/db/blockchain_v2_mainnet.sqlite
SQLite version 3.37.0 2021-12-09 01:34:53
Enter ".help" for usage hints.
sqlite> SELECT * from database_version;
2
```

**Comment by Jsewill** [comment]
> the `is_block` field only exists in v1 databases. it's possible that the database file is in v2 format but for some reason is mistaken as a v1 format.
> 
> The full node determines the version by looking up `SELECT * from database_version`.
> 
> you could check using the `sqlite3` tool, like this:
> 
> ```
> sqlite3 ~/.chia/mainnet/db/blockchain_v2_mainnet.sqlite
> SQLite version 3.37.0 2021-12-09 01:34:53
> Enter ".help" for usage hints.
> sqlite> SELECT * from database_version;
> 2
> ```

It reports `2`. Are there any other queries that I could run which could help track down the problem? I don't know the DB structure very well.

**Comment by Jsewill** [comment]
So, what should I do from here?

**Comment by arvidn** [comment]
I'm looking into this. There weren't any obvious changes that would affect this between 1.4.0 and 1.5.0.

Are you sure you were looking at the right blockchain database file?
the path I posted is the default one, after upgrading to v2. It's possible your configuration file specifies a different path for the database.

I'm proposing this additional logging in main to make it easier to trouble-shoot issues like this: https://github.com/Chia-Network/chia-blockchain/pull/12737

**Comment by arvidn** [comment]
@Jsewill you could also ensure you have all the tables in the blockchain database:

```
sqlite> .tables
coin_record            database_version       hints                
current_peak           full_blocks            sub_epoch_segments_v3
```

And see what schema they use, for example:

```
sqlite> .schema full_blocks
CREATE TABLE full_blocks(header_hash blob PRIMARY KEY,prev_hash blob,height bigint,sub_epoch_summary blob,is_fully_compactified tinyint,in_main_chain tinyint,block blob,block_record blob);
CREATE INDEX height on full_blocks(height);
CREATE INDEX is_fully_compactified ON full_blocks(is_fully_compactified, in_main_chain) WHERE in_main_chain=1;
CREATE INDEX main_chain ON full_blocks(height, in_main_chain) WHERE in_main_chain=1;
```

and

```
sqlite> .schema coin_record
CREATE TABLE coin_record(coin_name blob PRIMARY KEY, confirmed_index bigint, spent_index bigint, coinbase int, puzzle_hash blob, coin_parent blob, amount blob, timestamp bigint);
CREATE INDEX coin_confirmed_index on coin_record(confirmed_index);
CREATE INDEX coin_spent_index on coin_record(spent_index);
CREATE INDEX coin_puzzle_hash on coin_record(puzzle_hash);
CREATE INDEX coin_parent_index on coin_record(coin_parent);
```

That's what a v2 database should look like.

**Comment by Jsewill** [comment]
I am certain that there are no other DB files, and that the configuration file is pointing to the "v2" DB.

As far as schema is concerned, they're identical, with one exception: it appears that the full_blocks table in my DB has an extra column:
```shell
CREATE INDEX full_block_height on full_blocks(height);```

**Comment by arvidn** [comment]
@Jsewill I noticed that your stack trace doesn't line up with my source code at version 1.5.0.

Are you running this out of a git repository? Where did you get the 1.5.0 version from?

**Comment by Jsewill** [comment]
The official chia-blockchain GitHub repository.  I checked out tags/1.5.0. I thoroughly and recursively cleaned and reset multiple times.

**Comment by arvidn** [comment]
this is the source code to `block_store.py` for the `1.5.0` tag: https://github.com/Chia-Network/chia-blockchain/blob/1.5.0/chia/full_node/block_store.py

One of the frames in your stack trace points to `block_store.py` line 55, saying it has the following line of code:

```
await self.db.execute("CREATE INDEX IF NOT EXISTS is_block on full_blocks(is_block)")
```

That line of code doesn't exist in `1.5.0`, certainly not on line 55.

This makes me believe that, for whatever reason, you may be running some mismatching code.

Is the commit hash you're running from `787e96b8edc6ed95ca7a6d6ade115a62e6bff672`?

**Comment by Jsewill** [comment]
@arvidn git status reports HEAD detached at 1.5.0, but `chia version` says `1.2.1`, even after several recursive git resets, cleans and other tricks, and several invocations of `sh install.sh` while deactivated. I haven't been on 1.2.1 for a very long time. I don't know what is going on with this local repository, but that seems to be the problem. I will freshly clone it and return to this issue if I still have trouble.

**Comment by Jsewill** [comment]
It appears this was the main problem. I'm closing this issue. I'll open a new one and reference this one, if it crops up again. I've had an accurate report from `chia version` on this machine, up through 1.4.0, so I'm not sure what could have happened.

It makes little sense to me, and why my database wouldn't have the correct schema, I don't know. So many times I've heard from others, and many times I have experienced this myself, that they had to delete the chia root folder and resync. I like chia, but should it really be so fragile?

It is pretty hard to be certain that we're keeping an accurate record of the blockchain, from our node's point of view, when deleting and resynchronizing seems so often to be the remedy to bugs.
