### ISSUE TITLE
[Bug] 1.5.0 RPC /get_wallets not usable

### ISSUE THREAD

**Issue by vayamos-exchange** [Chia-Network/chia-blockchain#12622]
### What happened?

Hello,
RPC /get_wallets cannot be used in the latest version of Chia
Each request ends with this error:

'list' object has no attribute 'get'

As one of the few centralized exchanges that already supports CAT tokens, we are not able to restore our clients deposits and withdrawals, due to this problem

### Version

1.5.0

### What platform are you using?

Linux

### What ui mode are you using?

CLI

### Relevant log output

```shell
'list' object has no attribute 'get'
```

**Comment by vayamos-exchange** [comment]
From debug.log

`2022-07-27T11:32:50.399 wallet chia.rpc.util              : WARNING  Error while handling message: Traceback (most recent call last):
  File "chia/rpc/util.py", line 16, in inner
  File "chia/rpc/wallet_rpc_api.py", line 445, in get_wallets
AttributeError: 'list' object has no attribute 'get'`
