### ISSUE TITLE
chia stop -d all on RC6: rpi4 8gb ram ARM [BUG]

### ISSUE THREAD

**Issue by wrosko** [Chia-Network/chia-blockchain#1264]
Raspberry pi was not syncing after upgrading and then release of the challenge. Waited for 40ish minutes for blockchain to update but still showed nothing. Went to stop all processes in order to reset and it threw an attribute error in shutdown `AttributeError: 'FullNode' object has no attribute 'blockchain'`:
```(venv) rpi4_user@rpi4_user-pi4:~/chia-blockchain$ chia show -s              
                                                                                
Searching for an initial chain                                                  
                                                                                
You may be able to expedite with 'chia show -a host:port' using a known node.   
                                                                                
Blockchain has no blocks yet                                                    
(venv) rpi4_user@rpi4_user-pi4:~/chia-blockchain$ chia stop -d all          
Traceback (most recent call last):                                              
  File "/home/rpi4_user/chia-blockchain/venv/bin/chia_full_node", line 33, in 
<module>                                                                        
    sys.exit(load_entry_point('chia-blockchain', 'console_scripts', 'chia_full_n
ode')())
  File "/home/rpi4_user/chia-blockchain/src/server/start_full_node.py", line 6
0, in main
    return run_service(**kwargs)
  File "/home/rpi4_user/chia-blockchain/src/server/start_service.py", line 211
, in run_service
    return asyncio.run(async_run_service(*args, **kwargs))
  File "/usr/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main) 
  File "/usr/lib/python3.8/asyncio/base_events.py", line 603, in run_until_compl
ete
    self.run_forever()
  File "/usr/lib/python3.8/asyncio/base_events.py", line 570, in run_forever
    self._run_once() 
  File "/usr/lib/python3.8/asyncio/base_events.py", line 1823, in _run_once
    event_list = self._selector.select(timeout)
  File "/usr/lib/python3.8/selectors.py", line 468, in select
    fd_event_list = self._selector.poll(timeout, max_ev)
  File "/home/rpi4_user/chia-blockchain/src/server/start_service.py", line 162
, in _accept_signal
    self.stop()
  File "/home/rpi4_user/chia-blockchain/src/server/start_service.py", line 172
, in stop
    self._node._close()
  File "/home/rpi4_user/chia-blockchain/src/full_node/full_node.py", line 504,
 in _close
    if self.blockchain is not None:
AttributeError: 'FullNode' object has no attribute 'blockchain'
daemon: {'ack': True, 'command': 'exit', 'data': {'success': True}, 'destination
': 'client', 'origin': 'daemon', 'request_id': 'b81ba44e50da3073a21975f259b9bc06
27521ec1668b21ad8d7af9a0c00b9dcf'}```

**Comment by mariano54** [comment]
Use this:
https://github.com/Chia-Network/chia-blockchain/issues/1273

**Comment by wrosko** [comment]
@mariano54 not sure how the GUI installer problem on Mac/Windows affects the headless Ubuntu issue.

Issue appeared to be related to a git sibmodule problem where I had deleted the `package-lock` to try and get around the GUI build. (Never got the GUI running again on rc5). Problem ocvyred after git fetch/checkout - was stopped from doing the full branch checkout due to that package-lock and so the build then installed `1.0rc7` instead of `1.0rc6`
