### ISSUE TITLE
[FREEBSD] Building and installing Chia on FreeBSD

### ISSUE THREAD

**Issue by vkz** [Chia-Network/chia-blockchain#1289]
Installing chia on FreeBSD remains problematic. To the best of my knowledge building from source is the only semi-reliable way of having chia on FreeBSD. Despite issues #1110 and #1275 marked closed problem remains if only because binary wheel for e.g. `clvm_rs` that's available on https://pypi.chia.net/simple/ is only suitable for FreeBSD 11.3. You can trick the install script by renaming it to match your installation e.g. FreeBSD 12.2 Release but that's an ugly hack.

Proper way of solving it IMO is to simply build for all FreeBSD releases and push to https://pypi.chia.net/simple/.
Speaking of, is there a way to have `pip wheel` build something not so specific, so e.g. it matches not just a single version of OS etc etc. Would Python hackers please step in.

I know absolutely nothing about Python and its ecosystem. I think storing package metadata in a filename a-la wheel is stupid and prone to all sort of mistakes. I very much wish that a real Python hacker would get on FreeBSD issue and fix it once and for all. Please.

Until then the only reliable way of getting chia, at least for me has been this ugly script. To be clear I despise shell scripting and want none of it in my life. Parts borrowed from chia's own install.sh.

How to use:
- save it e.g. into `chia.sh`
- `chmod u+x chia.sh`
-  execute `./chia.sh` to build build `1.0rc7` or supply another git tag e.g. `./chia.sh '1.0rc6'`
- once script finishes you'll find everything in `./chia` so `. chia/activate and now you should be able to issue `chia` cli commands.

```sh
#!/usr/bin/env bash

# echo commands
#set -x

# exit on error
set -e

# install necessary packages
ASSUME_ALWAYS_YES=yes sudo /usr/sbin/pkg bootstrap -f
sudo pkg install --yes indexinfo security/sudo bash tmux git gmake cmake node lang/gcc lang/python37 py37-sqlite3 py37-cryptography lang/rust

mkdir -p chia
cd chia
chiadir=`pwd`

git clone https://github.com/Chia-Network/clvm_rs.git
(cd ${chiadir}/clvm_rs && git checkout tags/0.1.4)

git clone https://github.com/Chia-Network/chiapos.git
(cd ${chiadir}/chiapos && git checkout tags/0.9)

VERSION=$1

git clone https://github.com/Chia-Network/chia-blockchain.git
cd ${chiadir}/chia-blockchain
git checkout tags/${VERSION:-1.0rc7}
git submodule update --init mozilla-ca
sed -i -e 's/clvm_rs==.*"/clvm_rs==0.1.4"/' setup.py
sed -i -e 's/cryptography==.*"/cryptography==2.9.2"/' setup.py

cd ${chiadir}

find_python() {
	set +e
	unset BEST_VERSION
	for V in 37 3.7 38 3.8 39 3.9 3; do
		if which python$V >/dev/null; then
			if [ x"$BEST_VERSION" = x ]; then
				BEST_VERSION=$V
			fi
		fi
	done
	echo $BEST_VERSION
	set -e
}

if [ x"$INSTALL_PYTHON_VERSION" = x ]; then
	INSTALL_PYTHON_VERSION=$(find_python)
fi

# this fancy syntax sets INSTALL_PYTHON_PATH to "python3.7" unless INSTALL_PYTHON_VERSION is defined
# if INSTALL_PYTHON_VERSION=3.8, then INSTALL_PYTHON_PATH becomes python3.8

INSTALL_PYTHON_PATH=python${INSTALL_PYTHON_VERSION:-3.7}

echo "Python version is $INSTALL_PYTHON_VERSION"
$INSTALL_PYTHON_PATH -m venv venv

if [ ! -f "activate" ]; then
	ln -s venv/bin/activate .
fi

. ./activate

export MAKE=${MAKE:-gmake}
export BUILD_VDF_CLIENT=${BUILD_VDF_CLIENT:-N}

pip install --upgrade pip
pip install wheel

# build wheels
mkdir -p ./wheels
pip wheel --wheel-dir=./wheels ./clvm_rs
pip wheel --wheel-dir=./wheels ./chiapos

# TODO is there a way like to tell these commands to put any wheels
# they build to --wheel-dir=./wheels? Except pip install doesn't have
# that option. Else it puts everything in some .cache somewhere
pip install --find-links ./wheels --extra-index-url https://pypi.chia.net/simple/ miniupnpc==2.1
pip install --find-links ./wheels --extra-index-url https://pypi.chia.net/simple/ -e ./chia-blockchain
```

**Comment by vkz** [comment]
Also if anyone could teach me how to "cross" build that'd be rad. Essentially I thought I'd be clever and `pip wheel path/to/chia/git/repo` and then move all dependencies over to another less powerful server and install the wheel but alas I get random unsatisfied constraints even though those deps are right there in `wheels` dir. And for every attempt you randomly get some wheel that's actually available in that `--find-links` dir. I don't get it.
```
venvm) [user@farmer ~/tmp/chia]$ pip install --no-index --find-links=wheels --pre chia-blockchain
Looking in links: wheels
Processing ./wheels/chia_blockchain-1.0rc8.dev0-py3-none-any.whl
Processing ./wheels/bitstring-3.1.7-py3-none-any.whl
ERROR: Could not find a version that satisfies the requirement aiohttp==3.7.4 (from chia-blockchain) (from versions: none)
ERROR: No matching distribution found for aiohttp==3.7.4 (from chia-blockchain)

# but they are right here damn it
(venvm) [user@farmer ~/tmp/chia]$ ls wheels

PyYAML-5.4.1-cp37-cp37m-freebsd_12_2_release_amd64.whl          colorlog-4.7.2-py2.py3-none-any.whl
aiohttp-3.7.4-cp37-cp37m-freebsd_12_2_release_amd64.whl         concurrent_log_handler-0.9.19-py2.py3-none-any.whl
aiosqlite-0.17.0-py3-none-any.whl                               cryptography-2.9.2-cp37-cp37m-freebsd_12_2_release_amd64.whl
aiter-0.13.20191203-py3-none-any.whl                            idna-3.1-py3-none-any.whl
argon2_cffi-20.1.0-cp37-abi3-freebsd_12_2_release_amd64.whl     importlib_metadata-3.7.3-py3-none-any.whl
async_timeout-3.0.1-py3-none-any.whl                            keyring-23.0.0-py3-none-any.whl
attrs-20.3.0-py2.py3-none-any.whl                               keyrings.cryptfile-1.3.4-py2.py3-none-any.whl
bitstring-3.1.7-py3-none-any.whl                                multidict-5.1.0-cp37-cp37m-freebsd_12_2_release_amd64.whl
blspy-1.0-cp37-cp37m-freebsd_12_2_release_amd64.whl             portalocker-2.2.1-py2.py3-none-any.whl
cffi-1.14.5-cp37-cp37m-freebsd_12_2_release_amd64.whl           pycparser-2.20-py2.py3-none-any.whl
chardet-3.0.4-py2.py3-none-any.whl                              pycryptodome-3.10.1-cp35-abi3-freebsd_12_2_release_amd64.whl
chia_blockchain-1.0rc8.dev0-py3-none-any.whl                    setproctitle-1.2.2-cp37-cp37m-freebsd_12_2_release_amd64.whl
chiabip158-1.0-cp37-cp37m-freebsd_12_2_release_amd64.whl        six-1.15.0-py2.py3-none-any.whl
chiapos-0.9-cp37-cp37m-freebsd_12_2_release_amd64.whl           sortedcontainers-2.3.0-py2.py3-none-any.whl
chiavdf-1.0.1-cp37-cp37m-freebsd_12_2_release_amd64.whl         typing_extensions-3.7.4.3-py3-none-any.whl
click-7.1.2-py2.py3-none-any.whl                                websockets-8.1-cp37-cp37m-freebsd_12_2_release_amd64.whl
clvm-0.9.4-py3-none-any.whl                                     wheel-0.36.2-py2.py3-none-any.whl
clvm_rs-0.1.4-cp37-cp37m-freebsd_12_2_RELEASE_amd64.whl         yarl-1.6.3-cp37-cp37m-freebsd_12_2_release_amd64.whl
clvm_tools-0.4.3-py3-none-any.whl                               zipp-3.4.1-py3-none-any.whl
```

**Comment by vkz** [comment]
Well. Turns out that script I posted worked because I had "maturin" built on this machine cached. If you don't and you are on FreeBSD 12.2 Release expect and exception when `clvm_rs` attempts to build `maturin`. That was discussed #1110. So, as far as I'm concerned `chia` blockchain is broken on FreeBSD and the only way to get it to mainnet now is for an operator like me to do some nasty compilation and build hackery ... this sucks. I can't reliably build `chia` on any of my machines.

**Comment by devinrsmith** [comment]
I'm trying to build in a FreeBSD 12.2 jail. I've been following along from https://github.com/Chia-Network/chia-blockchain/wiki/FreeBSD-Install, trying to see if it would work (had to change a few things - like installing `lang/python37` instead of `lang/py37`).

Posting for reference. This is as far as I've gotten so far:

```
(chia-venv) [root@plotter2 ~/clvm_rs]# pip install maturin
Collecting maturin
  Downloading maturin-0.9.4.tar.gz (88 kB)
     |████████████████████████████████| 88 kB 2.4 MB/s
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Collecting toml~=0.10.0
  Using cached toml-0.10.2-py2.py3-none-any.whl (16 kB)
Building wheels for collected packages: maturin
  Building wheel for maturin (PEP 517) ... error
  ERROR: Command errored out with exit status 1:
   command: /root/chia-venv/bin/python3 /root/chia-venv/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py build_wheel /tmp/tmp5s0fn4rn
       cwd: /tmp/pip-install-samb57x_/maturin_a603fdfddab746e690540f9ee61b03e1
  Complete output (400 lines):
  running bdist_wheel
  running build
  installing to build/bdist.freebsd-12.2-RELEASE-p3-amd64/wheel
  running install
      Updating crates.io index
   Downloading crates ...
    Downloaded fnv v1.0.7
    Downloaded miniz_oxide v0.4.3
    Downloaded addr2line v0.14.1
    Downloaded adler v0.2.3
    Downloaded atty v0.2.14
    Downloaded mailparse v0.13.2
    Downloaded platform-info v0.1.0
    Downloaded plain v0.2.3
    Downloaded bitflags v1.2.1
    Downloaded base64 v0.13.0
    Downloaded backtrace v0.3.56
    Downloaded llvm-bitcode v0.1.2
    Downloaded fat-macho v0.4.2
    Downloaded base64 v0.12.3
    Downloaded anyhow v1.0.38
    Downloaded num_enum_derive v0.5.1
    Downloaded reqwest v0.11.0
    Downloaded quoted_printable v0.4.2
    Downloaded humantime v1.3.0
    Downloaded goblin v0.3.4
    Downloaded rand v0.8.3
    Downloaded mime_guess v2.0.3
    Downloaded base64 v0.10.1
    Downloaded matches v0.1.8
    Downloaded ansi_term v0.11.0
    Downloaded block-buffer v0.9.0
    Downloaded autocfg v1.0.1
    Downloaded aho-corasick v0.7.15
    Downloaded thiserror-impl v1.0.23
    Downloaded tracing v0.1.23
    Downloaded xattr v0.2.2
    Downloaded flate2 v1.0.20
    Downloaded digest v0.9.0
    Downloaded h2 v0.3.0
    Downloaded want v0.3.0
    Downloaded futures-util v0.3.12
    Downloaded futures-core v0.3.12
    Downloaded fs-err v2.5.0
    Downloaded futures-channel v0.3.12
    Downloaded form_urlencoded v1.0.0
    Downloaded bytes v1.0.1
    Downloaded num_enum v0.5.1
    Downloaded glob v0.3.0
    Downloaded generic-array v0.14.4
    Downloaded ipnet v2.3.0
    Downloaded heck v0.3.2
    Downloaded http-body v0.4.0
    Downloaded http v0.2.3
    Downloaded httpdate v0.3.2
    Downloaded futures-task v0.3.12
    Downloaded itoa v0.4.7
    Downloaded futures-macro v0.3.12
    Downloaded zip v0.5.6
    Downloaded pin-utils v0.1.0
    Downloaded num_cpus v1.13.0
    Downloaded thiserror v1.0.23
    Downloaded termcolor v1.1.2
    Downloaded once_cell v1.5.2
    Downloaded hyper v0.14.4
    Downloaded opaque-debug v0.3.0
    Downloaded mio v0.7.7
    Downloaded unicode-width v0.1.8
    Downloaded unicode-normalization v0.1.17
    Downloaded indexmap v1.6.1
    Downloaded percent-encoding v2.1.0
    Downloaded structopt-derive v0.4.14
    Downloaded pin-project-lite v0.2.4
    Downloaded quick-error v1.2.3
    Downloaded rand_core v0.6.2
    Downloaded typenum v1.12.0
    Downloaded hyper-rustls v0.22.1
    Downloaded human-panic v1.0.3
    Downloaded shlex v1.0.0
    Downloaded ppv-lite86 v0.2.10
    Downloaded proc-macro-nested v0.1.7
    Downloaded remove_dir_all v0.5.3
    Downloaded proc-macro-error v1.0.4
    Downloaded platforms v1.1.0
    Downloaded quote v1.0.9
    Downloaded proc-macro2 v1.0.24
    Downloaded proc-macro-error-attr v1.0.4
    Downloaded env_logger v0.7.1
    Downloaded semver v0.11.0
    Downloaded regex v1.4.3
    Downloaded gimli v0.23.0
    Downloaded dirs v3.0.1
    Downloaded httparse v1.3.5
    Downloaded proc-macro-crate v0.1.5
    Downloaded rand_chacha v0.3.0
    Downloaded serde v1.0.123
    Downloaded serde_derive v1.0.123
    Downloaded tokio-util v0.6.3
    Downloaded serde_json v1.0.62
    Downloaded ryu v1.0.5
    Downloaded rpassword v5.0.1
    Downloaded rustc-demangle v0.1.18
    Downloaded untrusted v0.7.1
    Downloaded try-lock v0.2.3
    Downloaded os_type v2.2.0
    Downloaded tinyvec v1.1.1
    Downloaded unicode-bidi v0.3.4
    Downloaded derivative v2.2.0
    Downloaded configparser v2.0.0
    Downloaded serde_urlencoded v0.7.0
    Downloaded textwrap v0.11.0
    Downloaded socket2 v0.3.19
    Downloaded scroll_derive v0.10.5
    Downloaded bytesize v1.0.1
    Downloaded scroll v0.10.2
    Downloaded cargo-platform v0.1.1
    Downloaded slab v0.4.2
    Downloaded encoding_rs v0.8.28
    Downloaded cfg-if v1.0.0
    Downloaded thread_local v1.1.3
    Downloaded spin v0.5.2
    Downloaded semver-parser v0.10.2
    Downloaded syn v1.0.60
    Downloaded podio v0.1.7
    Downloaded structopt v0.3.21
    Downloaded walkdir v2.3.1
    Downloaded unicode-xid v0.2.1
    Downloaded tracing-futures v0.2.5
    Downloaded clap v2.33.3
    Downloaded pretty_env_logger v0.4.0
    Downloaded toml v0.5.8
    Downloaded regex-syntax v0.6.22
    Downloaded unicode-segmentation v1.7.1
    Downloaded version_check v0.9.2
    Downloaded uuid v0.8.2
    Downloaded ucd-trie v0.1.3
    Downloaded tracing-core v0.1.17
    Downloaded url v2.2.0
    Downloaded tower-service v0.3.1
    Downloaded time v0.1.43
    Downloaded crc32fast v1.2.1
    Downloaded cpuid-bool v0.1.2
    Downloaded idna v0.2.1
    Downloaded sha2 v0.9.3
    Downloaded strsim v0.8.0
    Downloaded bzip2 v0.3.3
    Downloaded tempfile v3.2.0
    Downloaded webpki v0.21.4
    Downloaded charset v0.1.2
    Downloaded tokio-rustls v0.22.0
    Downloaded tar v0.4.32
    Downloaded vec_map v0.8.2
    Downloaded ring v0.16.20
    Downloaded cargo_metadata v0.12.3
    Downloaded unicase v2.6.0
    Downloaded sct v0.6.0
    Downloaded bzip2-sys v0.1.10+1.0.8
    Downloaded tokio v1.2.0
    Downloaded libc v0.2.86
    Downloaded cc v1.0.66
    Downloaded rustls v0.19.0
    Downloaded tinyvec_macros v0.1.0
    Downloaded webpki-roots v0.21.0
    Downloaded winapi v0.3.9
    Downloaded same-file v1.0.6
    Downloaded pest v2.1.3
    Downloaded pin-project-internal v1.0.5
    Downloaded getrandom v0.2.2
    Downloaded cbindgen v0.17.0
    Downloaded byteorder v1.4.2
    Downloaded pkg-config v0.3.19
    Downloaded pin-project v1.0.5
    Downloaded mime v0.3.16
    Downloaded proc-macro-hack v0.5.19
    Downloaded log v0.4.14
    Downloaded lazy_static v1.4.0
    Downloaded futures-io v0.3.12
    Downloaded filetime v0.2.14
    Downloaded object v0.23.0
    Downloaded memchr v2.3.4
    Downloaded futures-sink v0.3.12
    Downloaded dirs-sys v0.3.5
    Downloaded hashbrown v0.9.1
     Compiling libc v0.2.86
     Compiling proc-macro2 v1.0.24
     Compiling unicode-xid v0.2.1
     Compiling cfg-if v1.0.0
     Compiling syn v1.0.60
     Compiling version_check v0.9.2
     Compiling autocfg v1.0.1
     Compiling once_cell v1.5.2
     Compiling serde_derive v1.0.123
     Compiling log v0.4.14
     Compiling serde v1.0.123
     Compiling memchr v2.3.4
     Compiling cc v1.0.66
     Compiling itoa v0.4.7
     Compiling pin-project-lite v0.2.4
     Compiling getrandom v0.2.2
     Compiling bytes v1.0.1
     Compiling proc-macro-hack v0.5.19
     Compiling lazy_static v1.4.0
     Compiling untrusted v0.7.1
     Compiling spin v0.5.2
     Compiling ryu v1.0.5
     Compiling proc-macro-nested v0.1.7
     Compiling futures-core v0.3.12
     Compiling typenum v1.12.0
     Compiling matches v0.1.8
     Compiling hashbrown v0.9.1
     Compiling fnv v1.0.7
     Compiling pkg-config v0.3.19
     Compiling regex-syntax v0.6.22
     Compiling futures-sink v0.3.12
     Compiling httparse v1.3.5
     Compiling pin-utils v0.1.0
     Compiling futures-io v0.3.12
     Compiling tinyvec_macros v0.1.0
     Compiling adler v0.2.3
     Compiling encoding_rs v0.8.28
     Compiling slab v0.4.2
     Compiling crc32fast v1.2.1
     Compiling ucd-trie v0.1.3
     Compiling base64 v0.13.0
     Compiling unicode-segmentation v1.7.1
     Compiling ppv-lite86 v0.2.10
     Compiling try-lock v0.2.3
     Compiling serde_json v1.0.62
     Compiling bitflags v1.2.1
     Compiling percent-encoding v2.1.0
     Compiling gimli v0.23.0
     Compiling tower-service v0.3.1
     Compiling unicode-width v0.1.8
     Compiling byteorder v1.4.2
     Compiling termcolor v1.1.2
     Compiling winapi v0.3.9
     Compiling quick-error v1.2.3
     Compiling httpdate v0.3.2
     Compiling strsim v0.8.0
     Compiling object v0.23.0
     Compiling rustc-demangle v0.1.18
     Compiling platforms v1.1.0
     Compiling vec_map v0.8.2
     Compiling plain v0.2.3
     Compiling anyhow v1.0.38
     Compiling mime v0.3.16
     Compiling remove_dir_all v0.5.3
     Compiling cbindgen v0.17.0
     Compiling ansi_term v0.11.0
     Compiling cpuid-bool v0.1.2
     Compiling quoted_printable v0.4.2
     Compiling podio v0.1.7
     Compiling same-file v1.0.6
     Compiling ipnet v2.3.0
     Compiling base64 v0.12.3
     Compiling opaque-debug v0.3.0
     Compiling bytesize v1.0.1
     Compiling glob v0.3.0
     Compiling fs-err v2.5.0
     Compiling configparser v2.0.0
     Compiling shlex v1.0.0
     Compiling thread_local v1.1.3
     Compiling futures-task v0.3.12
     Compiling unicase v2.6.0
     Compiling generic-array v0.14.4
     Compiling proc-macro-error-attr v1.0.4
     Compiling proc-macro-error v1.0.4
     Compiling tokio v1.2.0
     Compiling indexmap v1.6.1
     Compiling miniz_oxide v0.4.3
     Compiling tracing-core v0.1.17
     Compiling unicode-bidi v0.3.4
     Compiling futures-channel v0.3.12
     Compiling http v0.2.3
     Compiling tinyvec v1.1.1
     Compiling pest v2.1.3
     Compiling heck v0.3.2
     Compiling ring v0.16.20
     Compiling bzip2-sys v0.1.10+1.0.8
     Compiling form_urlencoded v1.0.0
     Compiling textwrap v0.11.0
     Compiling humantime v1.3.0
     Compiling base64 v0.10.1
     Compiling walkdir v2.3.1
     Compiling tracing v0.1.23
     Compiling addr2line v0.14.1
     Compiling unicode-normalization v0.1.17
     Compiling semver-parser v0.10.2
     Compiling want v0.3.0
     Compiling aho-corasick v0.7.15
     Compiling http-body v0.4.0
     Compiling num_cpus v1.13.0
     Compiling mio v0.7.7
     Compiling atty v0.2.14
     Compiling socket2 v0.3.19
     Compiling xattr v0.2.2
     Compiling time v0.1.43
     Compiling filetime v0.2.14
     Compiling dirs-sys v0.3.5
     Compiling rpassword v5.0.1
     Compiling quote v1.0.9
     Compiling platform-info v0.1.0
     Compiling mime_guess v2.0.3
     Compiling idna v0.2.1
     Compiling charset v0.1.2
     Compiling rand_core v0.6.2
     Compiling uuid v0.8.2
     Compiling backtrace v0.3.56
     Compiling flate2 v1.0.20
     Compiling clap v2.33.3
     Compiling regex v1.4.3
     Compiling tar v0.4.32
     Compiling dirs v3.0.1
     Compiling bzip2 v0.3.3
     Compiling mailparse v0.13.2
     Compiling rand_chacha v0.3.0
     Compiling digest v0.9.0
     Compiling block-buffer v0.9.0
     Compiling url v2.2.0
     Compiling zip v0.5.6
     Compiling webpki v0.21.4
     Compiling sct v0.6.0
     Compiling os_type v2.2.0
     Compiling env_logger v0.7.1
     Compiling rand v0.8.3
     Compiling sha2 v0.9.3
     Compiling rustls v0.19.0
     Compiling webpki-roots v0.21.0
     Compiling tokio-util v0.6.3
     Compiling pretty_env_logger v0.4.0
     Compiling tempfile v3.2.0
     Compiling tokio-rustls v0.22.0
     Compiling pin-project-internal v1.0.5
     Compiling futures-macro v0.3.12
     Compiling scroll_derive v0.10.5
     Compiling derivative v2.2.0
     Compiling structopt-derive v0.4.14
     Compiling thiserror-impl v1.0.23
     Compiling futures-util v0.3.12
     Compiling scroll v0.10.2
     Compiling goblin v0.3.4
     Compiling thiserror v1.0.23
     Compiling pin-project v1.0.5
     Compiling tracing-futures v0.2.5
     Compiling structopt v0.3.21
     Compiling h2 v0.3.0
     Compiling hyper v0.14.4
     Compiling toml v0.5.8
     Compiling cargo-platform v0.1.1
     Compiling serde_urlencoded v0.7.0
     Compiling semver v0.11.0
     Compiling cargo_metadata v0.12.3
     Compiling proc-macro-crate v0.1.5
     Compiling human-panic v1.0.3
     Compiling hyper-rustls v0.22.1
     Compiling reqwest v0.11.0
     Compiling num_enum_derive v0.5.1
     Compiling num_enum v0.5.1
     Compiling llvm-bitcode v0.1.2
     Compiling fat-macho v0.4.2
     Compiling maturin v0.9.4 (/tmp/pip-install-samb57x_/maturin_a603fdfddab746e690540f9ee61b03e1)
  error: could not compile `maturin`

  To learn more, run the command again with --verbose.
  Traceback (most recent call last):
    File "/root/chia-venv/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py", line 280, in <module>
      main()
    File "/root/chia-venv/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py", line 263, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/root/chia-venv/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py", line 205, in build_wheel
      metadata_directory)
    File "/tmp/pip-build-env-gh60nkih/overlay/lib/python3.7/site-packages/setuptools/build_meta.py", line 209, in build_wheel
      wheel_directory, config_settings)
    File "/tmp/pip-build-env-gh60nkih/overlay/lib/python3.7/site-packages/setuptools/build_meta.py", line 194, in _build_with_temp_dir
      self.run_setup()
    File "/tmp/pip-build-env-gh60nkih/overlay/lib/python3.7/site-packages/setuptools/build_meta.py", line 142, in run_setup
      exec(compile(code, __file__, 'exec'), locals())
    File "setup.py", line 116, in <module>
      zip_safe=False,
    File "/tmp/pip-build-env-gh60nkih/overlay/lib/python3.7/site-packages/setuptools/__init__.py", line 145, in setup
      return distutils.core.setup(**attrs)
    File "/usr/local/lib/python3.7/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/usr/local/lib/python3.7/distutils/dist.py", line 966, in run_commands
      self.run_command(cmd)
    File "/usr/local/lib/python3.7/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/tmp/pip-build-env-gh60nkih/overlay/lib/python3.7/site-packages/wheel/bdist_wheel.py", line 228, in run
      self.run_command('install')
    File "/usr/local/lib/python3.7/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/local/lib/python3.7/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "setup.py", line 72, in run
      metadata = json.loads(subprocess.check_output(cargo_args).splitlines()[-2])
    File "/usr/local/lib/python3.7/sub
```

**Comment by risner** [comment]
I've submitted a FreeBSD port for the clvm_rs library.
I'm working on a port for chia-blockchanin, and running into many issues:
https://github.com/risner/chia-freebsd

**Comment by risner** [comment]
The one I've been working on this morning is:
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (clvm-tools unknown (/usr/local/lib/python3.8/site-packages), Requirement.parse('clvm_tools==0.4.3'), {'chia-blockchain'})
pkg_resources.DistributionNotFound: The 'clvm_tools==0.4.3' distribution was not found and is required by chia-blockchain

There seems to be a confusion on whether tools is clvm_tools or clvm-tools.
