### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by brause** [Chia-Network/chia-blockchain#1290]
**Describe the bug**
debug log 
~/.chia/1.0rc4/log/debug.log
contains a ton of only 
19:09:26.070 wallet wallet_server              : ERROR    Exception: , None. Traceback (most recent call last):
  File "src\server\server.py", line 449, in wrapped_coroutine
  File "src\wallet\wallet_node_api.py", line 40, in new_peak_wallet
  File "src\wallet\wallet_node.py", line 438, in new_peak_wallet
  File "src\server\ws_connection.py", line 241, in invoke
  File "src\server\ws_connection.py", line 287, in create_request
  File "asyncio\locks.py", line 293, in wait
concurrent.futures._base.CancelledError

19:09:40.230 wallet wallet_server              : ERROR    Unexpected WebSocket message type: WSMessage(type=<WSMsgType.ERROR: 258>, data=WebSocketError(<WSCloseCode.MESSAGE_TOO_BIG: 1009>, 'Message size 84403691 exceeds limit 52428800'), extra=None)
19:09:40.239 wallet wallet_server              : ERROR    Exception: , closing connection None. Traceback (most recent call last):
  File "src\server\server.py", line 456, in api_call
  File "asyncio\tasks.py", line 435, in wait_for
concurrent.futures._base.CancelledError

19:09:40.252 wallet wallet_server              : ERROR    Exception: , None. Traceback (most recent call last):
  File "src\server\server.py", line 449, in wrapped_coroutine
  File "src\wallet\wallet_node_api.py", line 40, in new_peak_wallet
  File "src\wallet\wallet_node.py", line 438, in new_peak_wallet
  File "src\server\ws_connection.py", line 241, in invoke
  File "src\server\ws_connection.py", line 287, in create_request
  File "asyncio\locks.py", line 293, in wait
concurrent.futures._base.CancelledError

19:09:51.746 wallet wallet_server              : ERROR    Unexpected WebSocket message type: WSMessage(type=<WSMsgType.ERROR: 258>, data=WebSocketError(<WSCloseCode.MESSAGE_TOO_BIG: 1009>, 'Message size 84403691 exceeds limit 52428800'), extra=None)
19:09:51.763 wallet wallet_server              : ERROR    Exception: , closing connection None. Traceback (most recent call last):
  File "src\server\server.py", line 456, in api_call
  File "asyncio\tasks.py", line 435, in wait_for
concurrent.futures._base.CancelledError

19:09:51.776 wallet wallet_server              : ERROR    Exception: , None. Traceback (most recent call last):
  File "src\server\server.py", line 449, in wrapped_coroutine
  File "src\wallet\wallet_node_api.py", line 40, in new_peak_wallet
  File "src\wallet\wallet_node.py", line 438, in new_peak_wallet
  File "src\server\ws_connection.py", line 241, in invoke
  File "src\server\ws_connection.py", line 287, in create_request
  File "asyncio\locks.py", line 293, in wait
concurrent.futures._base.CancelledError

**To Reproduce**
installed chia windows gui
Version 0.2.4

**Expected behavior**
no error messages

**Screenshot**
![image](https://user-images.githubusercontent.com/6328682/111079111-c6620300-84f8-11eb-989d-758ebca3bc04.png)

**Desktop (please complete the following information):**

- OS: Windows 10
- OS Version/Flavor: Version	10.0.19041 Build 19041
- CPU: I5-6500

**Comment by wrosko** [comment]
You're running rc4, current version is rc7.

**Comment by brause** [comment]
Uuuuh, sorry about that.

**Comment by wrosko** [comment]
All good, just pointing it out for ya! I'm not a dev. Try rc7!

**Comment by brause** [comment]
Thanks for pointing out. I am on rc7 now. AND set up some release alerts. :-)
