### ISSUE TITLE
[Bug] GUI error upon clicking NFTs button

### ISSUE THREAD

**Issue by danieljperry** [Chia-Network/chia-blockchain#12920]
### What happened?

I'm running a DF build and have a 1.4 NFT/DID wallet which contains 1 NFT. Upon clicking the NFTs button in the GUI, I receive this error:

```
Something went wrong
Error: Cannot read properties of undefined (reading 'id')
at webpack://@chia/gui/src/components/nfts/NFTProfileDropdown.tsx:84:31 id
at webpack://@chia/gui/src/components/nfts/NFTProfileDropdown.tsx:82:45 filter
at webpack://@chia/gui/node_modules/react-dom/cjs/react-dom.production.min.js:168:376 $h
at webpack://@chia/gui/node_modules/react/cjs/react.production.min.js:23:112 useLayoutEffect
at webpack://@chia/gui/src/components/nfts/NFTProfileDropdown.tsx:77:30 useMemo
at webpack://@chia/gui/node_modules/react-dom/cjs/react-dom.production.min.js:157:136 Ch
at webpack://@chia/gui/node_modules/react-dom/cjs/react-dom.production.min.js:180:153 oi
at webpack://@chia/gui/node_modules/react-dom/cjs/react-dom.production.min.js:269:342 a=b.pendingProps;f=e._init;e=f(e._payload);b.type=e;f=b.tag=hk(e);a=lg(e,a);switch
at webpack://@chia/gui/node_modules/react-dom/cjs/react-dom.production.min.js:250:346 Pj
```

This error does not occur from viewing the NFT from the CLI:

```
chia wallet nft list -i 3
Wallet keys:
1) * 502984008 (Synced)
2)   1239193935
3)   378808701
Choose a wallet key [1-3] ('q' to quit, or Enter to use 502984008):

NFT identifier:            nft1xylp0rne2rteqfktc48lnsln44psrwcq0nqxrehd70pmdl7ychssx9960x
Launcher coin ID:          313e178e7950d79026cbc54ff9c3f3ad4301bb007cc061e6edf3c3b6ffc4c5e1
Launcher puzhash:          eff07522495060c066f66f32acc2a77e3a3e737aca8baea4d1a64ea4cdc13da9
Current NFT coin ID:       84ba56b406acccdc0c76bc66df29a1b05d16398fd5d7eac06a0d886fe199cb3d
On-chain data/info:        ((117 "https://images.pexels.com/photos/1529881/pexels-photo-1529881.jpeg") (104 . 0xfeef1ea09c0f93fcf5a8d7e0018f2511638d317d78e3d3a71462cdb061baad68) (28021 "https://pastebin.com/raw/WUSyFQ8N") (27765 "https://raw.githubusercontent.com/Chia-Network/chia-blockchain/main/LICENSE") (29550 . 1) (29556 . 2) (28008 . 0xe4a93975287651e9e9a31d96777e96f19d7b4aac29b9e0f21db54f09f15e50b3) (27752 . 0x30a358857da6b49f57cfe819c1ca43bfe007f528eb784df5da5cb64577e0ffc6))
Owner DID:                 did:chia:1yt4dnznmghl7zsvnncg5vu0rkc8h5a9ct0l0c4u8cf4frgqjccasp6tkct
Royalty percentage:        300
Royalty puzhash:           8f7648c9213dadb074fecc1c45ca3d3e52a54f6713a098e2c1587671b3ca02d0
NFT content hash:          feef1ea09c0f93fcf5a8d7e0018f2511638d317d78e3d3a71462cdb061baad68
Metadata hash:             e4a93975287651e9e9a31d96777e96f19d7b4aac29b9e0f21db54f09f15e50b3
License hash:              30a358857da6b49f57cfe819c1ca43bfe007f528eb784df5da5cb64577e0ffc6
NFT series total:          2
Current NFT number in the series: 1
Metadata updater puzhash:  fe8a4b4e27a2e29a4d3fc7ce9d527adbcaccbab6ada3903ccf3ba9a769d2d78b
NFT minting block height:  2183567
Inner puzzle supports DID: True
NFT is pending for a transaction: False

URIs:
   https://images.pexels.com/photos/1529881/pexels-photo-1529881.jpeg

Metadata URIs:
   https://pastebin.com/raw/WUSyFQ8N

License URIs:
   https://raw.githubusercontent.com/Chia-Network/chia-blockchain/main/LICENSE
```

### Version

1.5.1.dev438

### What platform are you using?

Windows

### What ui mode are you using?

GUI

### Relevant log output

```shell
No errors or warnings appear in the log file.
```

**Comment by danieljperry** [comment]
Fixed in 1.5.1.452.
