### ISSUE TITLE
[Bug] Failed to execute script 'start_full_node' due to unhandled exception! (on last two updates)

### ISSUE THREAD

**Issue by yaaaaa** [Chia-Network/chia-blockchain#13136]
### What happened?

Stack on full node startup

### Version

1.5.1 (last two updates)

### What platform are you using?

Linux

### What ui mode are you using?

GUI

### Relevant log output

```shell
Checking if userData migration is needed
/home/rooot/.config/Chia Blockchain/Local Storage/leveldb exists: true
/home/rooot/.chia/mainnet/gui/Chia Blockchain/Local Storage/leveldb exists: true
/home/rooot/.config/Chia Blockchain/Local Storage/leveldb/migrated exists: true
Migration needed: false
Setting user data directory to /home/rooot/.chia/mainnet/gui/Chia Blockchain
[20291:0824/125543.136239:ERROR:browser_main_loop.cc(271)] GLib-GObject: g_value_set_boxed: assertion 'G_VALUE_HOLDS_BOXED (value)' failed

(chia-blockchain:20291): Gtk-WARNING **: 12:55:43.148: Theme parsing error: gtk.css:3611:22: 'none' is not a valid color name
Running python executable: 
child process success
No cert
Have cert
stderr: Traceback (most recent call last):
  File "chia/server/start_full_node.py", line 92, in <module>
  File "chia/server/start_full_node.py", line 88, in main
  File "chia/server/start_service.py", line 283, in async_run
  File "asyncio/runners.py", line 44, in run
  File "asyncio/base_events.py", line 616, in run_until_complete
  File "chia/server/start_full_node.py", line 81, in async_main
  File "chia/server/start_service.py", line 185, in run
  File "chia/server/start_service.py", line 146, in start
  File "chia/full_node/full_node.py", line 237, in _start
  File "chia/consensus/blockchain.py", line 146, in create
  File "chia/consensus/blockchain.py", line 159, in _load_chain_from_store
  File "chia/full_node/block_height_map.py", line 124, in create
  File "chia/full_node/block_height_map.py", line 187, in _load_blocks_from
ValueError: block with header hash is missing from your blockchain database: 4418f1039bb8cc5cabdf044964ee58b1ddaaf99be86969dbc27f9ec6d1931279
[20400] Failed to execute script 'start_full_node' due to unhandled exception!
```

**Comment by emlowe** [comment]
can you try `chia db validate`

**Comment by yaaaaa** [comment]
> opening file for reading: /run/media/rooot/TRASH/.chia/mainnet/db/blockchain_v2_mainnet.sqlite
> peak hash: 9d304b34f458f5b7a84ee51bb0316fd2460bf414d4ca468a12dd02f0f2e3e771
> peak height: 2304118
> traversing the full chain
> 2304116 orphaned blocks: 0 FAILED: block c2dbd4c6a7d588ff48308ddcb3dff65183f0f70b7ec136341127c66a7620822d (height: 2304114) is orphaned, but in_main_chain is set

**Comment by yaaaaa** [comment]
Can I fix it myself?

**Comment by arvidn** [comment]
somehow your blockchain database was corrupted. We don't have a command to attempt to repair a database. The simplest solution is probably to sync from scratch. If you're storing the database on a drive that's unreliable, you may want to run `chia db backup` periodically.

**Comment by emlowe** [comment]
Closing issue, there is no automatic way to recover your DB - syncing again is the recommended resolution
