### ISSUE TITLE
Legacy key migration failure when starting wallet

### ISSUE THREAD

**Issue by paninaro** [Chia-Network/chia-blockchain#13391]
Paul Hainsworth ran into an issue with legacy keyring migration when testing a new dogfood build. Running `chia start wallet` initiated legacy keyring migration but timed out for some reason. Perhaps starting the wallet took too long. Terminal output captured below:

```
paulhainsworth@Pauls-MacBook-Air ~ % chia start wallet
Daemon not started yet
Starting daemon

Legacy keyring support is deprecated and will be removed in an upcoming version. You need to migrate your keyring to continue using Chia.

Found 4 key(s) that need migration:
Fingerprint: 4255594369
Fingerprint: 1256268877
Fingerprint: 652326543
Fingerprint: 2665935416

Migrate these keys? (y/n): y
Error, timeout.
Traceback (most recent call last):
  File "chia/cmds/chia.py", line 153, in <module>
  File "chia/cmds/chia.py", line 149, in main
  File "click/core.py", line 829, in __call__
  File "click/core.py", line 782, in main
  File "click/core.py", line 1259, in invoke
  File "click/core.py", line 1066, in invoke
  File "click/core.py", line 610, in invoke
  File "click/decorators.py", line 21, in new_func
  File "chia/cmds/start.py", line 17, in start_cmd
  File "asyncio/runners.py", line 44, in run
  File "asyncio/base_events.py", line 647, in run_until_complete
  File "chia/cmds/start_funcs.py", line 68, in async_start
  File "chia/cmds/keys_funcs.py", line 245, in migrate_keys
  File "chia/daemon/keychain_proxy.py", line 180, in add_private_key
  File "chia/daemon/keychain_proxy.py", line 146, in get_response_for_request
TypeError: 'NoneType' object is not subscriptable
[40962] Failed to execute script 'chia' due to unhandled exception!
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x1079d6190>
```

**Comment by emlowe** [comment]
Closing old issues, pretty much all keyring migrations in the wild have already happened and we don't even attempt a migration anymore as support for the old keyring has been entirely removed
