### ISSUE TITLE
Linux-Wallet[Bug] 

### ISSUE THREAD

**Issue by rones-dev** [Chia-Network/chia-blockchain#13449]
### What happened?

While I am sync my blockchain I get such bug unable to sync forward and run full node ???

### Version

1.5.1

### What platform are you using?

Linux

### What ui mode are you using?

CLI

### Relevant log output

```shell
chia_harvester: stopped
chia_harvester: started
chia_farmer: stopped
chia_farmer: started
chia_full_node: started
chia_wallet: Traceback (most recent call last):
  File "/home/user/BlockChains/chia-blockchain/chia/util/lock.py", line 42, in acquire
    self._lock.acquire(timeout=timeout, poll_interval=poll_interval)
  File "/home/user/BlockChains/chia-blockchain/venv/lib/python3.10/site-packages/filelock/_api.py", line 183, in acquire
    raise Timeout(self._lock_file)
filelock._error.Timeout: The file lock '/home/user/.chia/mainnet/run/full_node.lock' could not be acquired.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/user/BlockChains/chia-blockchain/chia/server/start_service.py", line 184, in run
    with Lockfile.create(service_launch_lock_path(self.root_path, self._service_name), timeout=1):
  File "/home/user/BlockChains/chia-blockchain/chia/util/lock.py", line 29, in __enter__
    self.acquire(timeout=self.timeout, poll_interval=self.poll_interval)
  File "/home/user/BlockChains/chia-blockchain/chia/util/lock.py", line 44, in acquire
    raise LockfileError(e) from e
chia.util.lock.LockfileError: The file lock '/home/user/.chia/mainnet/run/full_node.lock' could not be acquired.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/user/BlockChains/chia-blockchain/venv/bin/chia_full_node", line 8, in <module>
    sys.exit(main())
  File "/home/user/BlockChains/chia-blockchain/chia/server/start_full_node.py", line 88, in main
    return async_run(async_main())
  File "/home/user/BlockChains/chia-blockchain/chia/server/start_service.py", line 283, in async_run
    return asyncio.run(coro)
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/home/user/BlockChains/chia-blockchain/chia/server/start_full_node.py", line 81, in async_main
    await service.run()
  File "/home/user/BlockChains/chia-blockchain/chia/server/start_service.py", line 189, in run
    raise ValueError(f"{self._service_name}: already running") from e
ValueError: full_node: already running
stopped
chia_wallet: started
```

**Comment by wallentx** [comment]
It looks like you may have had some chia services that were in a "zombie" state from a Chia previously running. You would just need to kill those services individually, or just do a reboot to ensure that there are no remaining detached services.

**Comment by rones-dev** [comment]
Thnaks
