### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by rones-dev** [Chia-Network/chia-blockchain#13475]
### What happened?

When I am doing re-sync the same error.
When enn I am doing a new db deploy from my plotter to the same error.
Please help ???

### Version

1.5.1

### What platform are you using?

Linux

### What ui mode are you using?

CLI

### Relevant log output

```shell
(venv) user@user:~/BlockChains/chia-blockchain$ Traceback (most recent call last):
  File "/home/user/BlockChains/chia-blockchain/venv/bin/chia_full_node", line 8, in <module>
    sys.exit(main())
  File "/home/user/BlockChains/chia-blockchain/chia/server/start_full_node.py", line 88, in main
    return async_run(async_main())
  File "/home/user/BlockChains/chia-blockchain/chia/server/start_service.py", line 283, in async_run
    return asyncio.run(coro)
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/home/user/BlockChains/chia-blockchain/chia/server/start_full_node.py", line 81, in async_main
    await service.run()
  File "/home/user/BlockChains/chia-blockchain/chia/server/start_service.py", line 185, in run
    await self.start()
  File "/home/user/BlockChains/chia-blockchain/chia/server/start_service.py", line 146, in start
    await self._node._start(**kwargs)
  File "/home/xch_sandman/BlockChains/chia-blockchain/chia/full_node/full_node.py", line 237, in _start
    self.blockchain = await Blockchain.create(
  File "/home/user/BlockChains/chia-blockchain/chia/consensus/blockchain.py", line 146, in create
    await self._load_chain_from_store(blockchain_dir)
  File "/home/user/BlockChains/chia-blockchain/chia/consensus/blockchain.py", line 159, in _load_chain_from_store
    self.__height_map = await BlockHeightMap.create(blockchain_dir, self.block_store.db_wrapper)
  File "/home/user/BlockChains/chia-blockchain/chia/full_node/block_height_map.py", line 67, in create
    async with conn.execute(
  File "/home/user/BlockChains/chia-blockchain/venv/lib/python3.10/site-packages/aiosqlite/context.py", line 41, in __aenter__
    self._obj = await self._coro
  File "/home/user/BlockChains/chia-blockchain/venv/lib/python3.10/site-packages/aiosqlite/core.py", line 184, in execute
    cursor = await self._execute(self._conn.execute, sql, parameters)
  File "/home/user/BlockChains/chia-blockchain/venv/lib/python3.10/site-packages/aiosqlite/core.py", line 129, in _execute
    return await future
  File "/home/user/BlockChains/chia-blockchain/venv/lib/python3.10/site-packages/aiosqlite/core.py", line 102, in run
    result = function()
sqlite3.DatabaseError: database disk image is malformed
```

**Comment by gritesh** [comment]
Maybe you have issue with your database. Please check this link!
https://www.nucleustechnologies.com/blog/fix-sqlite-database-disk-image-is-malformed/#:~:text=If%20you%20find%20the%20'SQLite,and%20define%20the%20other%20options.

**Comment by rones-dev** [comment]
This not helping at all.
I tried re-sync from the blockchain but after approx 15 Gb it stopped syncing and the log shows:
sqlite3.DatabaseError: database disk image is malformed...
Any idea what next ???

**Comment by emlowe** [comment]
Getting this error in the middle of syncing the DB is very unusual and might suggest some issue with the disk. I might suggest trying to sync the DB to a different disk or even on another computer.

BTW, a remote harvester doesn't need to run the full node in any event and so doesn't need the DB anyway. I'm not sure if you meant to say your farmer machine (or if you run them all on the same machine).
