### ISSUE TITLE
[Bug]  Harvester raise asyncio.exceptions.TimeoutError exception

### ISSUE THREAD

**Issue by xulifan** [Chia-Network/chia-blockchain#13480]
### What happened?

Recently, one of my harvester started to raise asyncio.exceptions.TimeoutError after running for couple hours. I have to reboot the machine to start chia harvester again.

I have attached the log.

### Version

1.5.1

### What platform are you using?

Linux

### What ui mode are you using?

CLI

### Relevant log output

```shell
2022-09-20T03:12:25.000 harvester harvester_server        : DEBUG    <- new_signage_point_harvester from peer 2daa464f784aca4d84aa6adc2f6ab67f2539b43ea9cf8832bc6d146889e9593f 192.168.100.11
2022-09-20T03:12:30.308 harvester harvester_server        : ERROR    Exception:  <class 'asyncio.exceptions.TimeoutError'>, closing connection {'host': '192.168.100.11', 'port': 8447}. Traceback (most recent call last):
  File "/home/lxu/chia-blockchain/chia/server/server.py", line 607, in api_call
    response: Optional[Message] = await asyncio.wait_for(wrapped_coroutine(), timeout=timeout)
  File "/usr/lib/python3.8/asyncio/tasks.py", line 501, in wait_for
    raise exceptions.TimeoutError()
asyncio.exceptions.TimeoutError

2022-09-20T03:12:30.308 harvester harvester_server        : DEBUG    Inbound_handler task cancelled
2022-09-20T03:12:30.310 harvester harvester_server        : INFO     Connection closed: 192.168.100.11, node id: 2daa464f784aca4d84aa6adc2f6ab67f2539b43ea9cf8832bc6d146889e9593f
2022-09-20T03:12:30.310 harvester harvester_server        : WARNING  Banning 192.168.100.11 for 10 seconds
2022-09-20T03:12:30.311 harvester chia.harvester.harvester: INFO     peer disconnected {'host': '192.168.100.11', 'port': 8447}
2022-09-20T03:12:46.686 daemon chia.daemon.server         : DEBUG    About to ping: chia_harvester
2022-09-20T03:13:16.698 daemon chia.daemon.server         : DEBUG    About to ping: chia_harvester
2022-09-20T03:13:16.698 daemon chia.daemon.server         : ERROR    Ping error
Traceback (most recent call last):
  File "/home/lxu/chia-blockchain/chia/daemon/server.py", line 275, in ping_task
    await socket.ping()
  File "/home/lxu/chia-blockchain/venv/lib/python3.8/site-packages/aiohttp/web_ws.py", line 295, in ping
    await self._writer.ping(message)
  File "/home/lxu/chia-blockchain/venv/lib/python3.8/site-packages/aiohttp/http_websocket.py", line 676, in ping
    await self._send_frame(message, WSMsgType.PING)
  File "/home/lxu/chia-blockchain/venv/lib/python3.8/site-packages/aiohttp/http_websocket.py", line 653, in _send_frame
    self._write(header + message)
  File "/home/lxu/chia-blockchain/venv/lib/python3.8/site-packages/aiohttp/http_websocket.py", line 663, in _write
    raise ConnectionResetError("Cannot write to closing transport")
ConnectionResetError: Cannot write to closing transport
2022-09-20T03:13:16.701 daemon chia.daemon.server         : ERROR    Ping failed, connection closed.
```

**Comment by emlowe** [comment]
This is a ping error from the Daemon - it may be resolved by #13886 where the heartbeat timeout was increased
