### ISSUE TITLE
[Bug] Wallet get_address broken after installing 1.6.0 and create_data_store usage

### ISSUE THREAD

**Issue by BookSwapSteve** [Chia-Network/chia-blockchain#13500]
### What happened?

Wallet appears to be partially broken after installation of 1.6.0 and attempt to run create_data_store.

Full node and wallet show as fully synced, some functions of the wallet are working as expected.

**From CLI:**
`chia wallet get_address`

gives:
`Exception from 'wallet' {'error': '', 'success': False}`

**In the GUI:**
The receive addresses are missing for NFT and Tokens. Unable to accept an offer file.

Tokens are showing as expected in the GUI and `chia wallet show` appears to be functioning correctly.

**Steps taken:**

- Installed 1.6.0.
- Enabled Data Layer & Restarted GUI client
- Enabled File Propagation Server & Restarted GUI client
- Opened firewall ports for Data Layer

Tried:
`chia data create_data_store -m 0.00001`

received the error 
`Exception from 'data': {'error': "{'error': '', 'success': False}", 'success': False}`

checked the log files and noticed the problems with the wallet.

Tried restarting the GUI and PC, problem persists.

Logs attached, I don't see the wallet problems in the logs until the create_data_store is run.

### Version

1.6.0

### What platform are you using?

Windows

### What ui mode are you using?

GUI

### Relevant log output

```shell
2022-09-21T10:00:41.028 daemon __main__                   : INFO     chia-blockchain version: 1.6.0
2022-09-21T10:00:41.083 daemon __main__                   : INFO     Starting Daemon Server
2022-09-21T10:00:41.085 daemon __main__                   : INFO     Not implemented
2022-09-21T10:00:41.526 daemon __main__                   : INFO     Register service {'service': 'wallet_ui'}
2022-09-21T10:00:41.527 daemon __main__                   : INFO     registered for service wallet_ui
2022-09-21T10:00:41.528 daemon __main__                   : INFO     {'success': True}
2022-09-21T10:00:43.523 farmer farmer                     : INFO     chia-blockchain version: 1.6.0
2022-09-21T10:00:43.524 farmer farmer_server              : INFO     Service capabilities: [(1, '1'), (2, '1'), (3, '1')]
2022-09-21T10:00:43.612 harvester chia.harvester.harvester: INFO     Using plots_refresh_parameter: {'batch_size': 300, 'batch_sleep_milliseconds': 1, 'interval_seconds': 120, 'retry_invalid_seconds': 1200}
2022-09-21T10:00:43.614 harvester harvester               : INFO     chia-blockchain version: 1.6.0
2022-09-21T10:00:43.617 harvester harvester_server        : INFO     Service capabilities: [(1, '1'), (2, '1'), (3, '1')]
2022-09-21T10:00:43.636 harvester harvester               : INFO     Started harvester service on network_id: mainnet
2022-09-21T10:00:43.638 harvester harvester               : INFO     Reconnecting to peer {'host': '127.0.0.1', 'port': 8447}
2022-09-21T10:00:43.653 farmer farmer_server              : INFO     Started listening on port: 8447
2022-09-21T10:00:43.656 farmer farmer                     : INFO     Started farmer service on network_id: mainnet
2022-09-21T10:00:43.658 farmer farmer                     : INFO     Reconnecting to peer {'host': '127.0.0.1', 'port': 8444}
2022-09-21T10:00:43.663 daemon __main__                   : INFO     Register service {'service': 'chia_harvester'}
2022-09-21T10:00:43.664 daemon __main__                   : INFO     registered for service chia_harvester
2022-09-21T10:00:43.666 daemon __main__                   : INFO     {'success': True}
2022-09-21T10:00:43.683 harvester harvester_server        : INFO     Connected with farmer {'host': '127.0.0.1', 'port': 8447}
2022-09-21T10:00:43.684 daemon __main__                   : INFO     Register service {'service': 'chia_farmer'}
2022-09-21T10:00:43.685 daemon __main__                   : INFO     registered for service chia_farmer
2022-09-21T10:00:43.686 daemon __main__                   : INFO     {'success': True}
2022-09-21T10:00:43.772 full_node full_node               : INFO     chia-blockchain version: 1.6.0
2022-09-21T10:00:43.773 full_node full_node_server        : INFO     Service capabilities: [(1, '1'), (2, '1'), (3, '1')]
2022-09-21T10:00:43.786 full_node chia.full_node.full_node: INFO     using blockchain database C:\Users\Steve\.chia\mainnet\db\blockchain_v2_mainnet.sqlite, which is version 2
2022-09-21T10:00:43.798 full_node chia.full_node.full_node: INFO     opening blockchain DB: synchronous=FULL
2022-09-21T10:00:43.800 full_node chia.full_node.block_store: INFO     DB: Creating block store tables and indexes.
2022-09-21T10:00:43.802 full_node chia.full_node.block_store: INFO     DB: Creating index height



2022-09-21T19:04:04.621 wallet chia.rpc.util              : WARNING  Error while handling message: Traceback (most recent call last):
  File "chia\rpc\util.py", line 16, in inner
  File "chia\rpc\wallet_rpc_api.py", line 2078, in create_new_dl
  File "chia\data_layer\data_layer_wallet.py", line 309, in generate_new_reporter
  File "chia\wallet\wallet.py", line 185, in get_new_puzzle
  File "chia\wallet\wallet_state_manager.py", line 446, in get_unused_derivation_record
AssertionError

2022-09-21T19:04:04.625 data_layer chia.rpc.util          : WARNING  Error while handling message: Traceback (most recent call last):
  File "chia\rpc\util.py", line 16, in inner
  File "chia\rpc\data_layer_rpc_api.py", line 106, in create_data_store
  File "chia\data_layer\data_layer.py", line 119, in create_store
  File "chia\rpc\wallet_rpc_client.py", line 718, in create_new_dl
  File "chia\rpc\rpc_client.py", line 49, in fetch
ValueError: {'error': '', 'success': False}


2022-09-21T19:04:55.644 wallet chia.rpc.util              : WARNING  Error while handling message: Traceback (most recent call last):
  File "chia\rpc\util.py", line 16, in inner
  File "chia\rpc\wallet_rpc_api.py", line 2078, in create_new_dl
  File "chia\data_layer\data_layer_wallet.py", line 309, in generate_new_reporter
  File "chia\wallet\wallet.py", line 185, in get_new_puzzle
  File "chia\wallet\wallet_state_manager.py", line 446, in get_unused_derivation_record
AssertionError

2022-09-21T19:04:55.647 data_layer chia.rpc.util          : WARNING  Error while handling message: Traceback (most recent call last):
  File "chia\rpc\util.py", line 16, in inner
  File "chia\rpc\data_layer_rpc_api.py", line 106, in create_data_store
  File "chia\data_layer\data_layer.py", line 119, in create_store
  File "chia\rpc\wallet_rpc_client.py", line 718, in create_new_dl
  File "chia\rpc\rpc_client.py", line 49, in fetch
ValueError: {'error': '', 'success': False}



2022-09-21T19:07:44.202 wallet chia.rpc.rpc_server        : WARNING  Error while handling message: Traceback (most recent call last):
  File "chia\rpc\rpc_server.py", line 244, in safe_handle
  File "chia\rpc\rpc_server.py", line 235, in ws_api
  File "chia\rpc\wallet_rpc_api.py", line 829, in get_next_address
  File "chia\wallet\wallet.py", line 198, in get_puzzle_hash
  File "chia\wallet\wallet.py", line 202, in get_new_puzzlehash
  File "chia\wallet\wallet_state_manager.py", line 446, in get_unused_derivation_record
AssertionError
```

**Comment by wallentx** [comment]
Hi, are you able to enable DEBUG logs and provide those to us over direct message in Keybase?

**Comment by yyolk** [comment]
I also ran into this yesterday. 
However, after leaving it overnight and _I think_ after receiving farmer rewards I was able to send again.


When I ran into the error I saw this issue. I tried using the latest development version (checked out a5ea7fb) It didn't solve anything, it had the same problem. I also tried `chia wallet update_derivation_index` and updating it by `1` (`$(($(chia wallet get_derivation_index | cut -d' ' -f4) + 1))`)


I did enable debug and saved a portion of the logs that I can share over keybase, if it's useful.

This line that stuck out to me was right before the traceback
```
2022-10-02T00:48:24.594 wallet chia.wallet.wallet_state_manager: DEBUG    Fetching derivation record for: 5 1 False
2022-10-02T00:48:24.600 wallet chia.rpc.util              : WARNING  Error while handling message: Traceback (most recent call last):
  File "/home/ubuntu/code/github.com/Chia-Network/chia-blockchain/chia/rpc/util.py", line 16, in inner
    res_object = await f(request_data)
  File "/home/ubuntu/code/github.com/Chia-Network/chia-blockchain/chia/rpc/wallet_rpc_api.py", line 869, in send_transaction
    tx: TransactionRecord = await wallet.generate_signed_transaction(
  File "/home/ubuntu/code/github.com/Chia-Network/chia-blockchain/chia/wallet/wallet.py", line 451, in generate_signed_transaction
    transaction = await self._generate_unsigned_transaction(
  File "/home/ubuntu/code/github.com/Chia-Network/chia-blockchain/chia/wallet/wallet.py", line 375, in _generate_unsigned_transaction
    change_puzzle_hash: bytes32 = await self.get_new_puzzlehash()
  File "/home/ubuntu/code/github.com/Chia-Network/chia-blockchain/chia/wallet/wallet.py", line 202, in get_new_puzzlehash
    puzhash = (await self.wallet_state_manager.get_unused_derivation_record(self.id())).puzzle_hash
  File "/home/ubuntu/code/github.com/Chia-Network/chia-blockchain/chia/wallet/wallet_state_manager.py", line 446, in get_unused_derivation_record
    assert record is not None
AssertionError
```

To reiterate; today I didn't run into that error when trying to send the same XCH, the only thing that I believe changed after trying the different code paths was receiving pool rewards.

**Comment by yyolk** [comment]
I spoke too soon, after sending one payment I am encountering the same issue as OP and my previous comment

**Comment by emlowe** [comment]
Closing this issue; it hasn't been seen since this release, and since most people have upgrade long ago , any problems here seem either resolved somewhere else, or are no longer particularly important to address
