### ISSUE TITLE
[Bug] - PermissionError: [Errno 13] Permission denied:

### ISSUE THREAD

**Issue by cr0n-dist0rti0n** [Chia-Network/chia-blockchain#13595]
### What happened?

Using Ubuntu 20.04 LTS with no GUI only CLI.

Updated to Chia 1.6.0 and for some reason when I try to plot I keep running into a PermissionError. I have quadruple checked the folder permission which are set at: `drwxrwxrwx`. Moreover, this appears to be the case for any drive I use with the Chia program. Outside the Chia program I am able to transfer files to those folders with the `mv` command and I can create directories. I copied over 4 chia plot files from another drive; however, I am unable to create due to permission error.

### Version

1.6.0

### What platform are you using?

Linux

### What ui mode are you using?

CLI

### Relevant log output

```shell
chia plots create -k 32 -n 20  -b 15000 -r 4 -c ****** -t /mnt/plots-14 -2 /mnt/plots-14 -d /mnt/plots-6
2022-10-04T00:03:25.634  chia.plotting.create_plots       : INFO     Creating 20 plots of size 32, pool contract address:  ****** farmer public key: ******
Traceback (most recent call last):
  File "/home/******/chia-blockchain/venv/bin/chia", line 8, in <module>
    sys.exit(main())
  File "/home/******/chia-blockchain/chia/cmds/chia.py", line 149, in main
    cli()  # pylint: disable=no-value-for-parameter
  File "/home/******/chia-blockchain/venv/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/******/chia-blockchain/venv/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/******/chia-blockchain/venv/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/******/chia-blockchain/venv/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/******/chia-blockchain/venv/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/******/chia-blockchain/venv/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/******/chia-blockchain/venv/lib/python3.8/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/******/chia-blockchain/chia/cmds/plots.py", line 153, in create_cmd
    asyncio.run(create_plots(Params(), plot_keys))
  File "/usr/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/******/chia-blockchain/chia/plotting/create_plots.py", line 175, in create_plots
    args.final_dir.mkdir(parents=True, exist_ok=True)
  File "/usr/lib/python3.8/pathlib.py", line 1288, in mkdir
    self._accessor.mkdir(self, mode)
PermissionError: [Errno 13] Permission denied: '/mnt/plots-6'
```

**Comment by cr0n-dist0rti0n** [comment]
Worked it out. I'm truly just a dumb ass. Directory is `/mnt/plots-06`. Not `/mnt/plots-6`. Kinda want to shoot myself right now. Like WTF?! I was like staring at that for days 😳.
