### ISSUE TITLE
[BUG] 2 out of 8 parallel plot jobs fail silently, UI continues to report Plotting

### ISSUE THREAD

**Issue by centrd** [Chia-Network/chia-blockchain#1361]
**Describe the bug**
2 out of 8 parallel plot jobs fail silently, UI continues to report Plotting.
Traceback can be seen in log, as well as a parse error.

What I did:

1. Installed Chia 1.0rc9
2. Upgraded to Chia 1.0.0
3. Started 8 parallel plot jobs

Result: 2 jobs (the bottom two on the plotter list) failed silently, while the UI continue to claim "Plotting". Error report can be seen when clicking on view log.

**Expected behavior**
If a plotting job fails, the UI should reflect that. Optionally, a notification would be nice.

**Log**

23:41:41.628  src.plotting.create_plots        : [32mINFO    [0m Adding directory F:\ to harvester for farming[0m
[6800] Failed to execute script chia
Traceback (most recent call last):
  File "src\cmds\chia.py", line 63, in <module>
  File "src\cmds\chia.py", line 59, in main
  File "click\core.py", line 1026, in __call__
  File "click\core.py", line 956, in main
  File "click\core.py", line 1518, in invoke
  File "click\core.py", line 1518, in invoke
  File "click\core.py", line 1280, in invoke
  File "click\core.py", line 711, in invoke
  File "click\decorators.py", line 22, in new_func
  File "src\cmds\plots.py", line 134, in create_cmd
  File "src\plotting\create_plots.py", line 158, in create_plots
  File "src\plotting\plot_tools.py", line 107, in add_plot_directory
  File "src\util\config.py", line 55, in load_config
  File "yaml\__init__.py", line 162, in safe_load
  File "yaml\__init__.py", line 114, in load
  File "yaml\constructor.py", line 49, in get_single_data
  File "yaml\composer.py", line 36, in get_single_node
  File "yaml\composer.py", line 55, in compose_document
  File "yaml\composer.py", line 84, in compose_node
  File "yaml\composer.py", line 133, in compose_mapping_node
  File "yaml\composer.py", line 84, in compose_node
  File "yaml\composer.py", line 127, in compose_mapping_node
  File "yaml\parser.py", line 98, in check_event
  File "yaml\parser.py", line 428, in parse_block_mapping_key
  File "yaml\scanner.py", line 115, in check_token
  File "yaml\scanner.py", line 152, in need_more_tokens
  File "yaml\scanner.py", line 292, in stale_possible_simple_keys
yaml.scanner.ScannerError: while scanning a simple key
  in "C:\Users\Administrator\.chia\mainnet\config\config.yaml", line 244, column 1
could not find expected ':'
  in "C:\Users\Administrator\.chia\mainnet\config\config.yaml", line 245, column 1

**Desktop (please complete the following information):**

- OS: Windows Server 2019, fully updated as of March 18, 2021
- CPU: E5-2660 v1 / 64GB RAM

**Comment by centrd** [comment]
Update
Came back to the plotter this evening, and Chia wasn't running. Checked Event Viewer, and found an app crash:

Faulting application name: Chia.exe, version: 1.0.0.0, time stamp: 0x60301e4e
Faulting module name: KERNELBASE.dll, version: 10.0.17763.1790, time stamp: 0xc97af40a
Exception code: 0xe0000008
Fault offset: 0x0000000000039689
Faulting process id: 0xcac
Faulting application start time: 0x01d71ba8351c2600
Faulting application path: C:\Users\Administrator\AppData\Local\chia-blockchain\app-1.0.0\Chia.exe
Faulting module path: C:\Windows\System32\KERNELBASE.dll
Report Id: 951a7032-b67e-44d7-a6c3-ddeedb0ee237
Faulting package full name: 
Faulting package-relative application ID:

**Comment by wjblanke** [comment]
yaml.scanner.ScannerError: while scanning a simple key
in "C:\Users\Administrator.chia\mainnet\config\config.yaml", line 244, column 1
could not find expected ':'
in "C:\Users\Administrator.chia\mainnet\config\config.yaml", line 245, column 1

Can you show us whats in your config.yaml around lines 244/245?

**Comment by centrd** [comment]
Also noteworthy: .chia is a folder under Administrator. There is a \ missing in the path for some reason.

> 243  target_peer_count: 5
> 244  testing: false
> 245  wallet_peers_path: wallet/db/wallet_peers.sqlite
> 246
(line 246 is blank)

Screenshot:
![Fzf7foR](https://user-images.githubusercontent.com/77421674/111723523-0ba86c80-883a-11eb-8c7b-1530c22c4490.png)

**Comment by centrd** [comment]
Another crash of the UI 8:10:51AM local time. Started plotting jobs last night. Lots of disk activity still happening, but I'm not sure if it's plotting stuff that will completed and usable.

When I re-opened the UI, it started showing database locked errors after a couple of minutes running.

Faulting application name: Chia.exe, version: 1.0.0.0, time stamp: 0x60301e4e
Faulting module name: KERNELBASE.dll, version: 10.0.17763.1790, time stamp: 0xc97af40a
Exception code: 0xe0000008
Fault offset: 0x0000000000039689
Faulting process id: 0x1d38
Faulting application start time: 0x01d71c5168a45deb
Faulting application path: C:\Users\Administrator\AppData\Local\chia-blockchain\app-1.0.0\Chia.exe
Faulting module path: C:\Windows\System32\KERNELBASE.dll
Report Id: 0a25f2c5-2641-40bf-a381-32507e90935c
Faulting package full name: 
Faulting package-relative application ID:

**Comment by centrd** [comment]
Crashed again, this time around 2.23 AM. More plot jobs have been added since the last crash. Lots of disk IO still happening, so looks like it's continuing to plot, but the UI has crashed. Same exception code and fault offset.

**Comment by centrd** [comment]
Crashes are daily. Plotting continues in the background after UI crash.

**Comment by centrd** [comment]
I've given up and switched to using the terminal + scripts.
Leaving the issue open.

**Comment by gmjgh** [comment]
Same here. Got this error twice. It seems that nothing gets broken but it is quite uncomfortable

**Comment by emike09** [comment]
Can confirm. Brand new Windows 10 installation, and new Chia installation. Nothing else installed but drivers. i5-3470, 500GB 850 Pro, 6TB ST6000VN0021-1ZA17Z. The message came up after I started 29 plots.
