### ISSUE TITLE
[BUG] rc9 daemon on a farmer dies silently - ghost fullnode created

### ISSUE THREAD

**Issue by vkz** [Chia-Network/chia-blockchain#1363]
**Describe the bug**
This happened two days in a row and first was reported on keybase: keybase://chat/chia_network.public#testnet/104158 . Running cloud based farmer on Vlutr instance Ubuntu that talks to two remote harvesters. Everyone running rc9. After many hours harvesters stop receiving challenges and farmer logs show that wallet and fullnode cannot connect to local daemon.

Timeline (UTC): harvesters on two separate remote hosts stop receiving challenges after 04:07, later on the farmer:
```
04:17:40.385 farmer farmer_server              : INFO     Connection closed: 127.0.0.1, node id: 2b55593dcf85dddbdb7a84b0ca24c47046d5a1c37a491fc53fbc3bf9e65f156d
04:17:41.130 farmer src.farmer.farmer          : INFO     peer disconnected {'host': '127.0.0.1', 'port': 58444}
04:17:42.866 farmer farmer                     : INFO     Reconnecting to peer {'host': '127.0.0.1', 'port': 58444}
04:17:50.669 full_node src.full_node.full_node_store: WARNING  Don't have challenge hash 712d1dabb105760b3721922508fc66d419696f143bb736a2bf00c83fd09a72dc
04:17:53.014 full_node src.full_node.full_node : INFO     End of slot not added CC challenge 218b2f75f31c9c8d48f1c3a0532403f87c6df01d326ca6f6368d23030f69b91d
04:17:56.670 full_node src.full_node.full_node_store: WARNING  Don't have challenge hash 712d1dabb105760b3721922508fc66d419696f143bb736a2bf00c83fd09a72dc
04:17:57.305 full_node src.full_node.full_node : INFO     End of slot not added CC challenge 218b2f75f31c9c8d48f1c3a0532403f87c6df01d326ca6f6368d23030f69b91d
04:17:59.897 wallet wallet_server              : INFO     Connection closed: 127.0.0.1, node id: 2b55593dcf85dddbdb7a84b0ca24c47046d5a1c37a491fc53fbc3bf9e65f156d
04:18:01.178 farmer farmer                     : INFO     Reconnecting to peer {'host': '127.0.0.1', 'port': 58444}
04:18:01.226 wallet wallet                     : INFO     Reconnecting to peer {'host': '127.0.0.1', 'port': 58444}

... fullnode continues to receive signages but wallet and farmer can't reach daemon
... until finally

04:27:52.038 farmer farmer                     : INFO     Reconnecting to peer {'host': '127.0.0.1', 'port': 58444}
04:27:58.852 daemon src.daemon.server          : INFO     Websocket exception. Closing websocket with chia_full_node code = 1006 (connection closed abnormally [internal]), no reason Traceback (most recent ca
ll last):
  File "/home/fullmeta/chia/chia-blockchain/venv/lib/python3.8/site-packages/websockets/protocol.py", line 827, in transfer_data
    message = await self.read_message()
  File "/home/fullmeta/chia/chia-blockchain/venv/lib/python3.8/site-packages/websockets/protocol.py", line 895, in read_message
    frame = await self.read_data_frame(max_size=self.max_size)
  File "/home/fullmeta/chia/chia-blockchain/venv/lib/python3.8/site-packages/websockets/protocol.py", line 971, in read_data_frame
    frame = await self.read_frame(max_size)
  File "/home/fullmeta/chia/chia-blockchain/venv/lib/python3.8/site-packages/websockets/protocol.py", line 1047, in read_frame
    frame = await Frame.read(
  File "/home/fullmeta/chia/chia-blockchain/venv/lib/python3.8/site-packages/websockets/framing.py", line 105, in read
    data = await reader(2)
  File "/usr/lib/python3.8/asyncio/streams.py", line 723, in readexactly
    await self._wait_for_data('readexactly')
  File "/usr/lib/python3.8/asyncio/streams.py", line 517, in _wait_for_data
    await self._waiter
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/fullmeta/chia/chia-blockchain/src/daemon/server.py", line 218, in safe_handle
    async for message in websocket:
  File "/home/fullmeta/chia/chia-blockchain/venv/lib/python3.8/site-packages/websockets/protocol.py", line 439, in __aiter__
    yield await self.recv()
  File "/home/fullmeta/chia/chia-blockchain/venv/lib/python3.8/site-packages/websockets/protocol.py", line 509, in recv
    await self.ensure_open()
  File "/home/fullmeta/chia/chia-blockchain/venv/lib/python3.8/site-packages/websockets/protocol.py", line 812, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedError: code = 1006 (connection closed abnormally [internal]), no reason

04:27:59.051 wallet wallet                     : INFO     Reconnecting to peer {'host': '127.0.0.1', 'port': 58444}
04:28:06.038 farmer farmer                     : INFO     Reconnecting to peer {'host': '127.0.0.1', 'port': 58444}
04:28:13.043 wallet wallet                     : INFO     Reconnecting to peer {'host': '127.0.0.1', 'port': 58444}
```

When discovered in the morning I see this in `ps`:
```
$ ps -aux |grep chia
fullmeta    2341  0.0  0.6  10432  6644 ?        Ss   Mar16   1:53 tmux new -s chia
fullmeta   16700  0.0  4.9 218120 49080 pts/2    Sl   Mar17   0:28 chia_daemon
fullmeta   16859  0.0  3.8 155500 38484 pts/2    Sl   Mar17   0:51 chia_harvester
fullmeta   16860  0.1  4.6 207180 46492 pts/2    SLl  Mar17   1:58 chia_farmer
fullmeta   16861  8.6  0.0      0     0 pts/2    Z    Mar17 103:14 [chia_full_node] <defunct>
fullmeta   16862  2.0  8.2 391648 82936 pts/2    SLl  Mar17  24:31 chia_wallet
fullmeta   17187  1.8  7.8 347728 78400 pts/2    S    Mar17  21:35 chia_full_node
fullmeta   17246  0.0 13.4 551216 134188 pts/2   S    Mar17   0:21 chia_full_node
fullmeta   20097  0.0  0.3   7160  3440 pts/0    S+   07:08   0:00 tmux attach -t chia
```

Only way to restart is to manually kill processes. Here's what happens if try `chia stop all -d`
```
$ chia stop all -d
daemon: {'ack': True, 'command': 'exit', 'data': {'success': True}, 'destination': 'client', 'origin': 'daemon', 'request_id': '64ce19fb140e6c6615c0b46d538f85e5a6375c95b41c935561063bf633fae7a4'}

# nope, something is still running
(venv) fullmeta@farmer:~/chia$ ps -aux |grep chia
fullmeta    2341  0.0  0.6  10432  6436 ?        Ss   Mar16   1:54 tmux new -s chia
fullmeta   17187  1.6  7.8 347728 78400 pts/2    S    Mar17  21:35 chia_full_node
fullmeta   17246  0.0 13.4 551216 134188 pts/2   S    Mar17   0:21 chia_full_node
```

Report re first time this happened is available on keybayse here: keybase://chat/chia_network.public#testnet/104158 . Scroll down for more details and snippets from logs.

My best guess is that something stops responding, chia tries to restart e.g. daemon and we end up with conflicting processes running. Maybe a race or inability to clean up while spawning new daemon.

Like mentioned on keybase: nothing else runs, there are no cron jobs that do anything with chia etc etc. And obviously I don't run any chia commands at 4 in the morning.

```
$ chia version
1.0rc9.dev8
```

Full zipped `debug.log`: [debug.zip](https://github.com/Chia-Network/chia-blockchain/files/6162179/debug.zip)

**To Reproduce**
1. start farmer on host 1
2. start harvesters, see them connect to farmer
3. wait for a day or so

**Expected behavior**
Have farmer to work and daemon not die suddenly.

**Screenshots**

**Desktop (please complete the following information):**

```
$ uname -a
Linux 5.8.0-44-generic #50-Ubuntu SMP Tue Feb 9 06:29:41 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```

- OS: [e.g. Linux]
- OS Version/Flavor: [e.g. CentOS 7.2]
- CPU: [e.g. Intel Xeon 8175M]

**Additional context**

**Comment by vkz** [comment]
We may have a winner (snipped):

```
sudo dmesg | less

[130789.628540] oom-kill:constraint=CONSTRAINT_NONE,nodemask=(null),cpuset=/,mems_allowed=0,global_oom,task_memcg=/user.slice/user-1000.slice/session-1.scope,task=chia_full_node,pid=16861,uid=1000
[130789.628571] Out of memory: Killed process 16861 (chia_full_node) total-vm:937572kB, anon-rss:384768kB, file-rss:0kB, shmem-rss:16kB, UID:1000 pgtables:944kB oom_score_adj:0
[130789.677733] oom_reaper: reaped process 16861 (chia_full_node), now anon-rss:0kB, file-rss:0kB, shmem-rss:16kB
```

If that's the reason then there're two things to consider:
1. have `chia` spot when `full_node` or `daemon` go down and recover. By the looks of it it probably does already but instead blocks itself with old `farmer` and `wallet` etc trying to connect and failing. See those ghost `full_node` processes I mentioned earlier
2. Spread far and wide that turns out `chia` memory requirements are such you cannot run a framer on $5 instance e.g. on Vultr.

**Comment by mariano54** [comment]
Any update on whether this is working now? Was it the daemon or full node running out of memory? I think there was a memory leak in the daemon related to plotting. have you been GUI plotting?

**Comment by aqk** [comment]
Hi There,

Thank you for the detailed bug report. It would be great to know how much memory your instance had.

Was this instance running only the farmer and node? 

My experience is that a 1 GB instance is not enough, but a 2GB instance is enough for that.

Were you plotting as well?

**Comment by timdev** [comment]
I've seen this as well. In my case, I was running only a node (i.e.: `chia start node`). On a dinky 1GB VPS (with no swap), it would eventually go OOM.
