### ISSUE TITLE
[Bug] Python 3.10.8 causes full node to be unable to connect to peers

### ISSUE THREAD

**Issue by jzjsuper** [Chia-Network/chia-blockchain#13636]
### What happened?

After upgrading Arch Linux, which upgrades python to 3.10.8, I found that the full node was unable to connect to any peers and sync, and there were python errors in the log. I tried to downgrade chia to 1.5.1 and the problem remained. I downgraded python to 3.10.7 and the issue was resolved in both chia v1.5.1 and v1.6.0.

### Version

1.6.0

### What platform are you using?

Linux

### What ui mode are you using?

CLI

### Relevant log output

```shell
2022-10-15T01:17:43.272 full_node full_node_server        : ERROR    Exception: object of type 'NoneType' has no len(), {'host': 'xx.xx.xx.xx', 'port': 8444}. Traceb
ack (most recent call last):
  File "/home/server/chia-blockchain/chia/server/server.py", line 597, in wrapped_coroutine
    result = await coroutine
  File "/home/server/chia-blockchain/chia/full_node/full_node_api.py", line 114, in new_peak
    waiter_count = len(self.full_node.new_peak_sem._waiters)
TypeError: object of type 'NoneType' has no len()

2022-10-15T01:17:43.273 full_node full_node_server        : ERROR    Exception: object of type 'NoneType' has no len() <class 'TypeError'>, closing connection {'host':
'xx.xx.xx.xx', 'port': 8444}. Traceback (most recent call last):
  File "/home/server/chia-blockchain/chia/server/server.py", line 607, in api_call
    response: Optional[Message] = await asyncio.wait_for(wrapped_coroutine(), timeout=timeout)
  File "/usr/lib/python3.10/asyncio/tasks.py", line 408, in wait_for
    return await fut
  File "/home/server/chia-blockchain/chia/server/server.py", line 604, in wrapped_coroutine
    raise e
  File "/home/server/chia-blockchain/chia/server/server.py", line 597, in wrapped_coroutine
    result = await coroutine
  File "/home/server/chia-blockchain/chia/full_node/full_node_api.py", line 114, in new_peak
    waiter_count = len(self.full_node.new_peak_sem._waiters)
TypeError: object of type 'NoneType' has no len()
```

**Comment by AlexSSD7** [comment]
+1, seeing this on our nodes as well.
