### ISSUE TITLE
chia plotters error (1.6.1rc1)

### ISSUE THREAD

**Issue by reythia** [Chia-Network/chia-blockchain#13690]
...\AppData\Local\Programs\Chia\resources\app.asar.unpacked\daemon>**chia plotters**

Traceback (most recent call last):
  File "chia\cmds\chia.py", line 140, in <module>
  File "chia\cmds\chia.py", line 136, in main
  File "click\core.py", line 1130, in __call__
  File "click\core.py", line 1055, in main
  File "click\core.py", line 1657, in invoke
  File "click\core.py", line 1404, in invoke
  File "click\core.py", line 760, in invoke
  File "click\decorators.py", line 26, in new_func
  File "chia\cmds\plotters.py", line 14, in plotters_cmd
  File "chia\plotters\plotters.py", line 457, in call_plotters
AttributeError: 'NoneType' object has no attribute 'startswith'
[22752] Failed to execute script 'chia' due to unhandled exception!

**Comment by ChiaMineJP** [comment]
Thank you for reporting.
A PR has been created to fix this issue.
