### ISSUE TITLE
1.6.1-rc2 NFT sending issues [Bug] 

### ISSUE THREAD

**Issue by HVNC1** [Chia-Network/chia-blockchain#13696]
### What happened?

error when sending NFT
NFT Transfer Failed
The NFT transfer failed: Error: wallet_id

### Version

1.6.1-rc2

### What platform are you using?

Windows

### What ui mode are you using?

GUI

### Relevant log output

```shell
2022-10-24T23:07:10.221 wallet chia.rpc.rpc_server        : WARNING  Error while handling message: Traceback (most recent call last):
  File "chia\rpc\rpc_server.py", line 324, in safe_handle
  File "chia\rpc\rpc_server.py", line 315, in ws_api
  File "chia\rpc\wallet_rpc_api.py", line 1793, in nft_transfer_nft
KeyError: 'wallet_id'
```

**Comment by paninaro** [comment]
Previously fixed with PR https://github.com/Chia-Network/chia-blockchain-gui/pull/1081. Will verify in rc3.
