### ISSUE TITLE
[Bug] PermissionError: [WinError 21]

### ISSUE THREAD

**Issue by risksoft** [Chia-Network/chia-blockchain#13723]
### What happened?

After error PermissionError: [WinError 21] farmer does not see any plots. Updating the plots does not help, only restarting the program. 

### Version

1.6

### What platform are you using?

Windows

### What ui mode are you using?

GUI

### Relevant log output

```shell
2022-10-27T14:39:57.283 full_node chia.full_node.full_node: INFO      Updated peak to height 2740037, weight 5700708424, hh 5e38809896ef3a037e236b3b69028f8516c3d6997d195aab02200cc30cf868a9, forked at 2740036, rh: 2bb1ced85d05799daf0e3bd45b5ebc4688f55e3b5b16348bedb43e0750ba16af, total iters: 11107282522647, overflow: False, deficit: 0, difficulty: 1776, sub slot iters: 137363456, Generator size: No tx, Generator ref list size: No tx
2022-10-27T14:39:57.337 wallet chia.wallet.wallet_blockchain: INFO     Peak set to: 2740037 timestamp: 1666870752
2022-10-27T14:39:57.410 farmer chia.farmer.farmer         : INFO     GET /farmer response: {'authentication_public_key': '0x8ca07f4d625fa8fc11bcf8abda1d08463469329e4e997235316366900192e728db5da8f52810c91f5468ac7eb0601897', 'payout_instructions': '39493dc9d87535b7309f3f7b6ded5b4643fa9f602cffc4920c12f320dfb9399c', 'current_difficulty': 134, 'current_points': 20116}
2022-10-27T14:39:59.359 full_node full_node_server        : WARNING  Rate limiting ourselves. message type: respond_peers, peer: 59.16.41.55
2022-10-27T14:39:59.359 full_node full_node_server        : WARNING  Rate limiting ourselves. message type: respond_peers, peer: 84.112.15.54
2022-10-27T14:40:03.950 full_node chia.full_node.full_node: INFO       Finished signage point 55/64: CC: f33ec5dee434fd3bef84e08c0303a7a77af207c6034d6e00e382a6a941239490 RC: d12a9c154816aa95b4e7a15f928fdc0f06e762dad73eaf361d79d4ecacf1bfd4 
2022-10-27T14:40:05.380 harvester chia.harvester.harvester: INFO     16 plots were eligible for farming 84112f64c7... Found 0 proofs. Time: 1.39869 s. Total 6472 plots
2022-10-27T14:40:10.498 full_node chia.full_node.mempool_manager: INFO     Replacing conflicting tx in mempool. New tx fee: 500000005, old tx fees: 0
2022-10-27T14:40:11.211 full_node full_node_server        : INFO     Not accepting inbound connection: {'host': '78.134.246.106', 'port': 8444}.Inbound limit reached.
2022-10-27T14:40:11.327 full_node full_node_server        : INFO     Connection closed: 78.134.246.106, node id: 5d893a4f4f2d67e704da60bbb466b7042df463c6d7a01f2cc9eda86161b22844
2022-10-27T14:40:11.327 full_node chia.full_node.full_node: INFO     peer disconnected {'host': '78.134.246.106', 'port': 8444}
2022-10-27T14:40:12.350 full_node chia.full_node.full_node: INFO       Finished signage point 56/64: CC: 498b58b150adb106d1f35349733aec20d3d8600cedb9dbe9e3c6ef57d4ee79a7 RC: be5993b34d61bae7a5aff171e45a277f294f7753f1add02ac9f9802fbed9cc05 
2022-10-27T14:40:12.840 harvester chia.harvester.harvester: ERROR    Error using prover object Invalid file \\STATION-4\m\Chia\plot-k32-2022-05-18-10-24-de04711bfedaa634abcc1ed26dd7855a59f9419a26d0cf841fba0509df2b3faf.plot
2022-10-27T14:40:12.840 harvester chia.harvester.harvester: ERROR    File: \\STATION-4\m\Chia\plot-k32-2022-05-18-10-24-de04711bfedaa634abcc1ed26dd7855a59f9419a26d0cf841fba0509df2b3faf.plot Plot ID: de04711bfedaa634abcc1ed26dd7855a59f9419a26d0cf841fba0509df2b3faf, challenge: 04d32e4e46895e0c05547407d4d0ec26d5a2aead2618ac05dff18eb57d26bc5c, plot_info: PlotInfo(prover=<chiapos.DiskProver object at 0x000001CB7B34BDF0>, pool_public_key=None, pool_contract_puzzle_hash=<bytes32: 26683ab1f3d930755a62282105de3559da3808da209e85dd372040235153a480>, plot_public_key=<G1Element b3bed5a77a75c636a779e131e01514124272e2c17d651c002b294a147bbc83c2daa26ce9aef39c7720754c0385db118a>, file_size=108817530880, time_modified=1652860590.5045984)
2022-10-27T14:40:13.188 harvester chia.harvester.harvester: INFO     12 plots were eligible for farming 84112f64c7... Found 0 proofs. Time: 0.82262 s. Total 6472 plots
2022-10-27T14:40:18.584 harvester chia.plotting.manager   : ERROR    _refresh_callback raised: [WinError 21] Устройство не готово: '\\\\STATION-4\\m\\Chia' with the traceback: Traceback (most recent call last):
  File "chia\plotting\manager.py", line 137, in _refresh_task
  File "chia\plotting\util.py", line 79, in get_plot_filenames
  File "pathlib.py", line 1215, in resolve
  File "pathlib.py", line 215, in resolve
PermissionError: [WinError 21] The device is not ready: '\\\\STATION-4\\m\\Chia'

2022-10-27T14:40:21.079 full_node chia.full_node.full_node: INFO       Finished signage point 57/64: CC: 1a981cb10845f3c0c4a9b9e4ff8c95c3b983ccb9ea435c9d17302f0f9a268645 RC: 0018348999fd1b83ecb2cd2a3f670509e3a205d8ec8616030e003b1248384673 
2022-10-27T14:40:21.098 harvester chia.harvester.harvester: INFO     0 plots were eligible for farming 84112f64c7... Found 0 proofs. Time: 0.00000 s. Total 0 plots
2022-10-27T14:40:25.054 full_node chia.full_node.full_node: INFO     Added unfinished_block a8363d929fa8eec83987c26e664a4ba305ee3da2fe4af04d18825df8f34fde6f, not farmed by us, SP: 57 farmer response time: 3.7391, Pool pk xch1f0ryxk6qn096hefcwrdwpuph2hm24w69jnzezhkfswk0z2jar7aq5zzpfj, validation time: 0.0984 seconds, pre_validation time 0.1277, cost: 623419350, percent full: 5.667%
2022-10-27T14:40:29.827 full_node chia.full_node.full_node: INFO       Finished signage point 58/64: CC: 6399c7876c7fd2bffd1272113f563bb7d81341bacba20f45d424e5605e0da264 RC: 43a234d73efcfbbef7d43bfbd840421d6e6542fd447a32682e3e6b8e8bfd954f 
2022-10-27T14:40:29.843 harvester chia.harvester.harvester: INFO     0 plots were eligible for farming 84112f64c7... Found 0 proofs. Time: 0.00000 s. Total 0 plots
```

**Comment by emlowe** [comment]
We believe this is fixed in 1.6.2
