### ISSUE TITLE
[Bug] Wallet crashes while syncing, never finishing the process

### ISSUE THREAD

**Issue by FazendaPool** [Chia-Network/chia-blockchain#13749]
### What happened?

Wallet doesn't finish syncing, currently in unrecoverable state. Can probably be fixed by deleting DB.

### Version

1.6.0

### What platform are you using?

Linux

### What ui mode are you using?

GUI

### Relevant log output

```shell
2022-10-29T06:36:20.188 wallet chia.pools.pool_wallet     : INFO     Already have state transition: b'wa\xdb\xa9J\x90\xfbg\xa0\xd6\xb2\xdd\xbcpG\xc4\x02\xa6\xc6\x1cS\xcf\\\xb6(\x9dX~\xa4\x9d\xb3i'
2022-10-29T06:36:20.191 wallet wallet_server              : ERROR    Exception:  <class 'asyncio.exceptions.TimeoutError'>, closing connection {'host': '127.0.0.1', 'port': 58444}. Traceback (most recent call last):
  File "/home/chia/chia-blockchain/chia/server/server.py", line 608, in api_call
    response: Optional[Message] = await asyncio.wait_for(wrapped_coroutine(), timeout=timeout)
  File "/usr/lib/python3.8/asyncio/tasks.py", line 501, in wait_for
    raise exceptions.TimeoutError()
asyncio.exceptions.TimeoutError

2022-10-29T06:36:20.192 wallet wallet_server              : WARNING  Trying to ban localhost for 10, but will not ban
2022-10-29T06:36:20.192 full_node full_node_server        : INFO     Connection closed: 127.0.0.1, node id: 9d3514584ed19b8563be625b9d7e337d09418301e2f20d8707c2e54915bdfba0
2022-10-29T06:36:20.192 wallet wallet_server              : INFO     Connection closed: 127.0.0.1, node id: b314b346c881ff1fad056d18ff5b4764051a01327dfc44f022395909272db38c
2022-10-29T06:36:20.193 full_node chia.full_node.full_node: INFO     peer disconnected {'host': '127.0.0.1', 'port': 8449}
2022-10-29T06:36:20.193 wallet chia.server.address_manager_store: INFO     Loading peers from /home/chia/.chia/testnet10/wallet/db/wallet_peers.dat
2022-10-29T06:36:20.195 wallet chia.wallet.wallet_node    : ERROR    Error adding states.. Was not able to obtain children None Traceback (most recent call last):
  File "/home/chia/chia-blockchain/chia/wallet/wallet_node.py", line 800, in receive_state_from_peer
    await self.wallet_state_manager.new_coin_state(states, peer, fork_height)
  File "/home/chia/chia-blockchain/chia/wallet/wallet_state_manager.py", line 1179, in new_coin_state
    children = await self.wallet_node.fetch_children(coin_name, peer=peer, fork_height=fork_height)
  File "/home/chia/chia-blockchain/chia/wallet/wallet_node.py", line 1601, in fetch_children
    raise ValueError(f"Was not able to obtain children {response}")
ValueError: Was not able to obtain children None
2022-10-29T06:36:21.786 wallet chia.wallet.wallet_node    : WARNING  Peer None did not respond in time.
....................
2022-10-29T06:36:21.786 wallet chia.wallet.wallet_node    : WARNING  Peer None did not respond in time.
2022-10-29T06:36:21.786 wallet wallet                     : INFO     Reconnecting to peer {'host': '127.0.0.1', 'port': 58444}
2022-10-29T06:36:21.792 wallet wallet_server              : INFO     Connected with full_node {'host': '127.0.0.1', 'port': 58444}
2022-10-29T06:36:21.980 wallet chia.wallet.wallet_blockchain: INFO     Peak set to: 1730296 timestamp: 1667021743
2022-10-29T06:36:21.981 wallet chia.wallet.wallet_node    : INFO     Starting sync trusted: True to peer 127.0.0.1
2022-10-29T06:36:21.981 wallet chia.wallet.wallet_node    : INFO     perform_atomic_rollback to 1712901
```

**Comment by emlowe** [comment]
We believe that PR #13371 would fix this that in so far that this exception occurs, the wallet would not get continuously stuck at this point. That code is in 1.6.1+
