### ISSUE TITLE
[Bug] Failed to set DID on NFT

### ISSUE THREAD

**Issue by Jsewill** [Chia-Network/chia-blockchain#13765]
### What happened?

When attempting to move an NFT to a DID to which I've moved other NFTs in the past, I received the error, `The NFT move failed: Error: Failed to set DID on NFT:`. This has been a problem since at least 1.5.0.

### Version

1.6.0

### What platform are you using?

Linux

### What ui mode are you using?

GUI

### Relevant log output

```shell
wallet chia.rpc.wallet_rpc_api    : ERROR    Failed to set DID on NFT:~
Traceback (most recent call last):
  File "/redacted/path/chia-blockchain/chia/rpc/wallet_rpc_api.py", line 1581, in nft_set_nft_did
    spend_bundle = await nft_wallet.set_nft_did(nft_coin_info, did_id, fee=fee)
  File "/redacted/path/chia-blockchain/chia/wallet/nft_wallet/nft_wallet.py", line 912, in set_nft_did
    did_inner_hash, did_bundle = await self.get_did_approval_info(nft_id, bytes32(did_id))
  File "/redacted/path/chia-blockchain/chia/wallet/nft_wallet/nft_wallet.py", line 292, in get_did_approval_info
    did_bundle = await wallet.create_message_spend(puzzle_announcements=[nft_id])
  File "/redacted/path/chia-blockchain/chia/wallet/did_wallet/did_wallet.py", line 703, in create_message_spend
    assert coins is not None
AssertionError
```

**Comment by ytx1991** [comment]
Did you move any NFT before this? You need to want the movement confirmed on the chain before moving the next one.

**Comment by Jsewill** [comment]
@ytx1991 Yes, just as I said in the issue description. I've moved many NFTs to the DID in question, all confirmed on chain. I had to resync, and now the wallet won't let me move to or from said DID.

Others had said that a full resync would help, so I tried removing my chia directory and reinitializing it a couple times to no avail.

**Comment by Jsewill** [comment]
No, I will give that a try and report back.

**Comment by ytx1991** [comment]
So you are able to see the DID wallet after the resync?

**Comment by Jsewill** [comment]
I have been able to see the DID wallet the whole time, both in settings->profiles, and viewing the NFTs within them. I simply can't move NFTs to or from it.

**Comment by ytx1991** [comment]
For assigning NFT to a new DID, you need to ensure you have that DID in your current wallet. If you transfer the DID to another wallet, it will fail. Unfortunately, the current version will not remove the DID wallet after you transferred it. In your case, it seems like you don't have the DID coin in your NFT wallet. You may need to confirm if you transferred the DID previously.

**Comment by Jsewill** [comment]
I have not transferred any DID. I don't really see an option for that, either.

**Comment by ytx1991** [comment]
Can you provide your DID ID?

**Comment by Jsewill** [comment]
Certainly. did:chia:133xtshe8ckqmlcjg7p9fytrzzz0vkqt4jsv8w87nm3mka93cstvqpp5920

**Comment by Jsewill** [comment]
Awhile back, after hearing about someone else having similar trouble with their DIDs, I tried to use the RPC API documentation to get backup information on it. So, technically, I also have a lot of other information which I got from my wallet via the RPC.

**Comment by ytx1991** [comment]
According to the on-chain records, you used this DID quite frequently in July. The last usage is on 08/01 https://chia.tt/info/coin/0x52890589f66eabd8608587a85bf5f51375fe2a3a799cc023db82c69c2cd6bbe5
Do you remember what kind of operation you did for this DID?

**Comment by Jsewill** [comment]
Yes, that sounds about right. I figured if I couldn't get it to work with a resync, it might have been a bug that would be worked out eventually. That's why I waited so long to create this issue.

To create the DID? No. I know that I did not do it via the GUI. I may have created it via CLI or RPC. The only DID operations I knew how to do was transferring NFTs to it via the GUI, so I assume that last operation was me moving an NFT to it.

**Comment by ytx1991** [comment]
It shows you transferred that DID from 
xch158ugllndgrm3k023wc2wxezxfaqdq8zza8lqm7k8r5qqrdhh45eqmz5769 to 
xch1nznh7ca9g25n5lxvhm58xvq3txqd078lr3clfue4zgq6aptucraq7hrneg on 07/26.
I cannot verify if there are derived from the same master key. You may need to check your wallet DB to see it. If they belong to different keys, you need to transfer that DID to the right wallet.

**Comment by Jsewill** [comment]
Hm. How would I go about checking that the latter address is derived from my private keys, on my end? I certainly didn't purposely transfer it out, as I wouldn't know how.

**Comment by ytx1991** [comment]
I suggest you check all the wallets you own and see if the DID is in any of them. Since the DID was spent several times after the transfer, someone must spend it intentionally.

**Comment by Jsewill** [comment]
I did nothing to transfer it. How would it have been transferred at all?

**Comment by Jsewill** [comment]
> It shows you transferred that DID from xch158ugllndgrm3k023wc2wxezxfaqdq8zza8lqm7k8r5qqrdhh45eqmz5769 to xch1nznh7ca9g25n5lxvhm58xvq3txqd078lr3clfue4zgq6aptucraq7hrneg on 07/26. I cannot verify if there are derived from the same master key. You may need to check your wallet DB to see it. If they belong to different keys, you need to transfer that DID to the right wallet.

Neither of these addresses are found when I run `chia keys derive search` searching both observer and non-observer derivation.

**Comment by Jsewill** [comment]
To illustrate what I am saying, here are a couple screenshots showing the DID firmly in my wallet.

![image](https://user-images.githubusercontent.com/141502/200383412-f00d881d-871f-4934-9a05-9031ff7fccb5.png)

![image](https://user-images.githubusercontent.com/141502/200383537-dd5d2047-a4c6-457d-802e-09fc863e817c.png)

Additionally, when I run `chia wallet did get_did` on either DID, I receive the following error:
`Failed to get DID: 'coin_id'`

Whereas, `chia rpc wallet did_get_did` returns as follows:
```
{
    "my_did": "did:chia:133xtshe8ckqmlcjg7p9fytrzzz0vkqt4jsv8w87nm3mka93cstvqpp5920",
    "success": true,
    "wallet_id": 11
}
```
and `chia rpc wallet did_get_current_coin_info` returns `Request failed: {'error': '', 'success': False}`.

For the record, I never once ran `chia rpc wallet did_transfer_did`.

**Comment by Jsewill** [comment]
I switched my log level to `INFO`. Here's some additional log output from running `chia rpc wallet did_get_current_coin_info`:

```
2022-11-07T13:03:24.664 wallet chia.wallet.did_wallet.did_wallet: WARNING  Can't select 1, from spendable 0 for wallet id 11
2022-11-07T13:03:24.664 wallet chia.rpc.util              : WARNING  Error while handling message: Traceback (most recent call last):
  File "/redacted/path/chia-blockchain/chia/rpc/util.py", line 16, in inner
    res_object = await f(request_data)
  File "/redacted/path/chia-blockchain/chia/rpc/wallet_rpc_api.py", line 1464, in did_get_current_coin_info
    assert did_coin_threeple is not None
AssertionError

```

**Comment by ytx1991** [comment]
Did you use it to create any attestment? Since I saw there is a Recovery DID.

**Comment by ytx1991** [comment]
I made a change on did_empty. Can you git pull that branch and reinstall it again? It may fix the issue.

**Comment by Jsewill** [comment]
> Did you use it to create any attestment? Since I saw there is a Recovery DID.

I did, and I saved that information.

> I made a change on did_empty. Can you git pull that branch then reinstall and resync it again? It may fix the issue.

Certainly, I'll give it a try and report back. Thanks for all your time on this.

**Comment by Jsewill** [comment]
I tried the updated `did_empty` branch. Here's what I got:

```
(venv) $ chia rpc wallet did_get_current_coin_info '{"wallet_id":11}'
Request failed: {'error': "Can't select 1, from spendable 0 for wallet id 11", 'success': False}
```

Logs:
```
2022-11-08T23:45:11.967 wallet chia.rpc.util              : WARNING  Error while handling message: Traceback (most recent call last):
  File "/redacted/path/chia-blockchain/chia/rpc/util.py", line 16, in inner
    res_object = await f(request_data)
  File "/redacted/path/chia-blockchain/chia/rpc/wallet_rpc_api.py", line 1456, in did_get_current_coin_info
    did_coin_threeple = await did_wallet.get_info_for_recovery()
  File "/redacted/path/chia-blockchain/chia/wallet/did_wallet/did_wallet.py", line 941, in get_info_for_recovery
    coins = await self.select_coins(uint64(1))
  File "/redacted/path/chia-blockchain/chia/wallet/did_wallet/did_wallet.py", line 321, in select_coins
    raise ValueError(error_msg)
ValueError: Can't select 1, from spendable 0 for wallet id 11
```

```
(venv) $ chia wallet did get_did -i 11
Failed to get DID: 'coin_id'
```

Logs
`2022-11-08T23:49:24.032 wallet chia.wallet.did_wallet.did_wallet: WARNING  Can't select 1, from spendable 0 for wallet id 11`

Attemping to move an NFT to said DID "Profile" fails in the same way that it has before.

**Comment by ytx1991** [comment]
Do you mind sending your wallet DB file to me? It's hard to tell what happened through the log.
Email: t.yu@chia.net

**Comment by ytx1991** [comment]
How did you resync if you don't know where the wallet DB is? You need to delete that file when the Chia client is not running.
For Windows it's in:
C:\Users\YOUR_USERNAME\.chia\mainnet\wallet\db
For Linux/MacOS:
~/.chia/mainnet/wallet/db

**Comment by Jsewill** [comment]
I'm not sure that you read what I wrote. I know where it is, I simply don't know precisely what it contains--what private info that I may or may not be sending you, etc. I skimmed through my wallet DB via sqlite3, and I'm satisfied enough to send it over.

**Comment by ytx1991** [comment]
Sorry, my bad. It doesn't have your keys for sure. Just some transaction records. I need to check your coin_reocrd table to see why you don't have a coin for your DID.

**Comment by Jsewill** [comment]
Certainly. **I've emailed you the output from that query**. I hope you don't mind. I'd rather not post it here, not that that info can't be obtained from the chain.

**Comment by ytx1991** [comment]
Just a quick update. I can confirm it's because of the inner puzzle change on 2022/07/26. I'm trying to get the puzzle and solution to see why it changed.

**Comment by ytx1991** [comment]
The issue is triggered by the recovery list update. You still own that DID. I need to make a change to handle this rare case.

**Comment by Jsewill** [comment]
Thank you for all your time on this.

**Comment by ytx1991** [comment]
I just updated the did_empty branch. You can pull again and then resync the DB.

**Comment by Jsewill** [comment]
`chia rpc wallet did_get_current_coin_info` reports `Request failed: {'error': "Can't select 1, from spendable 0 for wallet id 27", 'success': False}`
and results in the following log output:
```
2022-11-13T10:43:42.856 wallet chia.wallet.did_wallet.did_wallet: WARNING  Can't select 1, from spendable 0 for wallet id 27
2022-11-13T10:43:42.857 wallet chia.rpc.util              : WARNING  Error while handling message: Traceback (most recent call last):
  File "/redacted/path/chia-blockchain/chia/rpc/util.py", line 18, in inner
    res_object = await f(request_data)
  File "/redacted/path/chia-blockchain/chia/rpc/wallet_rpc_api.py", line 1815, in did_get_current_coin_info
    did_coin_threeple = await did_wallet.get_info_for_recovery()
  File "/redacted/path/chia-blockchain/chia/wallet/did_wallet/did_wallet.py", line 942, in get_info_for_recovery
    coins = await self.select_coins(uint64(1))
  File "/redacted/path/chia-blockchain/chia/wallet/did_wallet/did_wallet.py", line 321, in select_coins
    raise ValueError(error_msg)
ValueError: Can't select 1, from spendable 0 for wallet id 27
```

In the GUI, `Move NFT to Profile` opens the modal and hangs for a several minutes, not loading the NFT, profiles, or min fee amount. While it hangs, the CLI wallet also does not respond past printing `Balances, fingerprint: #############`

I let it run for a while, and returned to this message:

![image](https://user-images.githubusercontent.com/141502/201534707-29a70e2f-4660-4e9f-b68b-dfc6b3e63ff4.png)

There are a lot of similar errors in the logs, each with different IDs. Here's an example:

```
2022-11-13T11:02:51.760 wallet chia.wallet.wallet_state_manager: ERROR    Error adding state... Was not able to get states for [b'\x96-\xe3#\xc0\x1d\xa0\x1a\x92\xd4\xaeL7\x9d\xf5\x8f\x1c\xe6\xcc\x9c>\xa4Z\xdb\x80\xaf\xdb\xab\xcaCp\x0c']
Traceback (most recent call last):
  File "/redacted/path/chia-blockchain/chia/wallet/wallet_state_manager.py", line 1041, in new_coin_state
    wallet_id, wallet_type = await self.determine_coin_type(peer, coin_state, fork_height)
  File "/redacted/path/chia-blockchain/chia/wallet/wallet_state_manager.py", line 614, in determine_coin_type
    response: List[CoinState] = await self.wallet_node.get_coin_state(
  File "/redacted/path/chia-blockchain/chia/wallet/wallet_node.py", line 1628, in get_coin_state
    raise PeerRequestException(f"Was not able to get states for {coin_names}")
chia.wallet.util.wallet_sync_utils.PeerRequestException: Was not able to get states for [b'\x96-\xe3#\xc0\x1d\xa0\x1a\x92\xd4\xaeL7\x9d\xf5\x8f\x1c\xe6\xcc\x9c>\xa4Z\xdb\x80\xaf\xdb\xab\xcaCp\x0c']
```

**Comment by ytx1991** [comment]
Can you change the derivation index to 3000 then try resync again? Currently, your DID address is around 2500ish.

**Comment by Jsewill** [comment]
The derivation index is already at `3082`.

**Comment by ytx1991** [comment]
Can you switch to the did_recreate branch and then resync again?

**Comment by Jsewill** [comment]
Running `chia rpc wallet did_get_current_coin_info` produces the same error as before, with a slightly different traceback:

```
2022-11-15T23:19:19.070 wallet chia.rpc.util              : WARNING  Error while handling message: Traceback (most recent call last):
  File "/redacted/path/chia-blockchain/chia/rpc/util.py", line 18, in inner
    res_object = await f(request_data)
  File "/redacted/path/chia-blockchain/chia/rpc/wallet_rpc_api.py", line 1921, in did_get_current_coin_info
    did_coin_threeple = await did_wallet.get_info_for_recovery()
  File "/redacted/path/chia-blockchain/chia/wallet/did_wallet/did_wallet.py", line 942, in get_info_for_recovery
    coins = await self.select_coins(uint64(1))
  File "/redacted/path/chia-blockchain/chia/wallet/did_wallet/did_wallet.py", line 321, in select_coins
    raise ValueError(error_msg)
ValueError: Can't select 1, from spendable 0 for wallet id 27
```

Trying to move an NFT to the DID via the GUI resulted in a similar error as before, with the following traceback:

```
2022-11-15T23:25:56.081 wallet chia.rpc.rpc_server        : WARNING  Error while handling message: Traceback (most recent call last):
  File "/redacted/path/chia-blockchain/chia/rpc/rpc_server.py", line 324, in safe_handle
    response = await self.ws_api(message)
  File "/redacted/path/chia-blockchain/chia/rpc/rpc_server.py", line 315, in ws_api 
    return await f_rpc_api(data)
  File "/redacted/path/chia-blockchain/chia/rpc/wallet_rpc_api.py", line 2066, in nft_set_nft_did
    spend_bundle = await nft_wallet.set_nft_did(nft_coin_info, did_id, fee=fee)
  File "/redacted/path/chia-blockchain/chia/wallet/nft_wallet/nft_wallet.py", line 1045, in set_nft_did
    did_inner_hash, did_bundle = await self.get_did_approval_info(nft_id, bytes32(did_id))
  File "/redacted/path/chia-blockchain/chia/wallet/nft_wallet/nft_wallet.py", line 302, in get_did_approval_info
    did_bundle = await wallet.create_message_spend(puzzle_announcements=[nft_id])
  File "/redacted/path/chia-blockchain/chia/wallet/did_wallet/did_wallet.py", line 754, in create_message_spend
    coins = await self.select_coins(uint64(1))
  File "/redacted/path/chia-blockchain/chia/wallet/did_wallet/did_wallet.py", line 321, in select_coins
    raise ValueError(error_msg)
ValueError: Can't select 1, from spendable 0 for wallet id 27
```

**Comment by ytx1991** [comment]
Thanks, for your details. I just updated the did_recreate to cover this case. Please pull and resync again.

**Comment by Jsewill** [comment]
Command:

```
chia-blockchain $ chia rpc wallet did_get_current_coin_info '{"wallet_id":27}'
Request failed: {'error': "Can't select 1, from spendable 0 for wallet id 27", 'success': False}
```

Logs:
```
2022-11-17T11:14:13.280 wallet DID did:chia:133xtshe8ckqmlcjg7p9fytrzzz0vkqt4jsv8w87nm3mka93cstvqpp5920: WARNING  Can't select 1, from spendable 0 for wallet id 27
2022-11-17T11:14:13.280 wallet chia.rpc.util              : WARNING  Error while handling message: Traceback (most recent call last):
  File "/redacted/path/chia-blockchain/chia/rpc/util.py", line 18, in inner
    res_object = await f(request_data)
  File "/redacted/path/chia-blockchain/chia/rpc/wallet_rpc_api.py", line 1921, in did_get_current_coin_info
    did_coin_threeple = await did_wallet.get_info_for_recovery()
  File "/redacted/path/chia-blockchain/chia/wallet/did_wallet/did_wallet.py", line 949, in get_info_for_recovery
    coins = await self.select_coins(uint64(1))
  File "/redacted/path/chia-blockchain/chia/wallet/did_wallet/did_wallet.py", line 327, in select_coins
    raise ValueError(error_msg)
ValueError: Can't select 1, from spendable 0 for wallet id 27
```

GUI move NFT to profile results in the same `...can't select from...` message and the following log output:

```
2022-11-17T11:16:29.328 wallet chia.rpc.rpc_server        : WARNING  Error while handling message: Traceback (most recent call last):
  File "/redacted/path/chia-blockchain/chia/rpc/rpc_server.py", line 324, in safe_handle
    response = await self.ws_api(message)
  File "/redacted/path/chia-blockchain/chia/rpc/rpc_server.py", line 315, in ws_api 
    return await f_rpc_api(data)
  File "/redacted/path/chia-blockchain/chia/rpc/wallet_rpc_api.py", line 2066, in nft_set_nft_did
    spend_bundle = await nft_wallet.set_nft_did(nft_coin_info, did_id, fee=fee)
  File "/redacted/path/chia-blockchain/chia/wallet/nft_wallet/nft_wallet.py", line 1045, in set_nft_did
    did_inner_hash, did_bundle = await self.get_did_approval_info(nft_id, bytes32(did_id))
  File "/redacted/path/chia-blockchain/chia/wallet/nft_wallet/nft_wallet.py", line 302, in get_did_approval_info
    did_bundle = await wallet.create_message_spend(puzzle_announcements=[nft_id])
  File "/redacted/path/chia-blockchain/chia/wallet/did_wallet/did_wallet.py", line 761, in create_message_spend
    coins = await self.select_coins(uint64(1))
  File "/redacted/path/chia-blockchain/chia/wallet/did_wallet/did_wallet.py", line 327, in select_coins
    raise ValueError(error_msg)
ValueError: Can't select 1, from spendable 0 for wallet id 27
```

**Comment by ytx1991** [comment]
I decided to solve this issue in another way. You can try this.
1. Pull did_recreate then run ./install.sh. No need for resync this time.
2. Run this command in Chia CLI tool:
```
For Linux/Mac
chia rpc wallet did_find_lost_did '{"coin_id":"52890589f66eabd8608587a85bf5f51375fe2a3a799cc023db82c69c2cd6bbe5"}'
For Windows
chia rpc wallet did_find_lost_did "{\"coin_id\":\"52890589f66eabd8608587a85bf5f51375fe2a3a799cc023db82c69c2cd6bbe5\"}"
```
It may take some time depends on you spent DID how many times. You should see a response with "success": true.
Your recovery info will be invalid, so you need to update your DID recovery list again. Check RPC API doc for more details.

**Comment by Jsewill** [comment]
Command:

```
chia rpc wallet did_find_lost_did '{"coin_id":"52890589f66eabd8608587a85bf5f51375fe2a3a799cc023db82c69c2cd6bbe5"}'
Request failed: {'error': 'bad bytes32 initializer <redacted_hex_string>', 'success': False}

```

Logs:

```
2022-11-18T12:15:18.474 wallet chia.rpc.util              : WARNING  Error while handling message: Traceback (most recent call last):
  File "/redacted/path/chia-blockchain/chia/rpc/util.py", line 18, in inner
    res_object = await f(request_data)
  File "/redacted/path/chia-blockchain/chia/rpc/wallet_rpc_api.py", line 1825, in did_find_lost_did
    bytes32(p2_puzzle)
  File "/redacted/path/chia-blockchain/chia/util/byte_types.py", line 35, in __init__
    raise ValueError("bad %s initializer %s" % (type(self).__name__, v))
ValueError: bad bytes32 initializer <redacted_hex_string>
```

I didn't include the "initializer" hex string, as I simply don't know for certain if I should make that public. However, I could if you need it.

**Comment by ytx1991** [comment]
Fixed. Please pull and reinstall then try it again.

**Comment by Jsewill** [comment]
Command:

```
chia rpc wallet did_find_lost_did '{"coin_id":"52890589f66eabd8608587a85bf5f51375fe2a3a799cc023db82c69c2cd6bbe5"}'
Request failed: {'error': "'NoneType' object has no attribute 'pubkey'", 'success': False}
```

Logs:

```
2022-11-18T17:30:14.628 wallet chia.rpc.util              : WARNING  Error while handling message: Traceback (most recent call last):
  File "/redacted/path/chia-blockchain/chia/rpc/util.py", line 18, in inner
    res_object = await f(request_data)
  File "/redacted/path/chia-blockchain/chia/rpc/wallet_rpc_api.py", line 1920, in did_find_lost_did
    await did_wallet.coin_added(coin_state.coin, uint32(coin_state.created_height), peer)
  File "/redacted/path/chia-blockchain/chia/wallet/did_wallet/did_wallet.py", line 383, in coin_added 
    inner_puzzle = await self.inner_puzzle_for_did_puzzle(coin.puzzle_hash)
  File "/redacted/path/chia-blockchain/chia/wallet/did_wallet/did_wallet.py", line 1147, in inner_puzzle_for_did_puzzle
    puzzle_for_pk(record.pubkey),
AttributeError: 'NoneType' object has no attribute 'pubkey'
```

**Comment by ytx1991** [comment]
I made a fix for that glitch. If you want to recover multiple DID, you need to run it multiple times with their own DID ID (change "coin_id").

**Comment by Jsewill** [comment]
@ytx1991 I just went to move another NFT to the DID in question, and it failed again.

Logs:

```
2022-11-18T21:01:36.824 wallet chia.wallet.did_wallet.did_wallet: WARNING  Can't select 1, from spendable 0 for wallet id 27
2022-11-18T21:01:36.825 wallet chia.rpc.rpc_server        : WARNING  Error while handling message: Traceback (most recent call last):
  File "/redacted/path/chia-blockchain/chia/rpc/rpc_server.py", line 324, in safe_handle
    response = await self.ws_api(message)
  File "/redacted/path/chia-blockchain/chia/rpc/rpc_server.py", line 315, in ws_api
    return await f_rpc_api(data)
  File "/redacted/path/chia-blockchain/chia/rpc/wallet_rpc_api.py", line 2227, in nft_set_nft_did
    spend_bundle = await nft_wallet.set_nft_did(nft_coin_info, did_id, fee=fee)
  File "/redacted/path/chia-blockchain/chia/wallet/nft_wallet/nft_wallet.py", line 1045, in set_nft_did
    did_inner_hash, did_bundle = await self.get_did_approval_info(nft_id, bytes32(did_id))
  File "/redacted/path/chia-blockchain/chia/wallet/nft_wallet/nft_wallet.py", line 302, in get_did_approval_info
    did_bundle = await wallet.create_message_spend(puzzle_announcements=[nft_id])
  File "/redacted/path/chia-blockchain/chia/wallet/did_wallet/did_wallet.py", line 761, in create_message_spend
    coins = await self.select_coins(uint64(1))
  File "/redacted/path/chia-blockchain/chia/wallet/did_wallet/did_wallet.py", line 327, in select_coins
    raise ValueError(error_msg)
ValueError: Can't select 1, from spendable 0 for wallet id 27
```

**Comment by ytx1991** [comment]
Did you successfully moved one NFT after the recovery?

**Comment by Jsewill** [comment]
Yes, though the wallet seems to lose the DID after each NFT profile assignment. I have to use the `did_find_lost_did` procedure before/after every one, if I want to transfer another.

**Comment by Jsewill** [comment]
Now I can't move NFTs to that DID, even after using that procedure.

GUI error:

```
NFT Move Failed
The NFT move failed: Error: Request <redacted> failed: {"error":"","success":false}
```

Logs:

```
2022-11-20T12:07:13.919 wallet chia.rpc.rpc_server        : WARNING  Error while handling message: Traceback (most recent call last):
  File "/redacted/path/chia-blockchain/chia/rpc/rpc_server.py", line 324, in safe_handle
    response = await self.ws_api(message)
  File "/redacted/path/chia-blockchain/chia/rpc/rpc_server.py", line 315, in ws_api
    return await f_rpc_api(data)
  File "/redacted/path/chia-blockchain/chia/rpc/wallet_rpc_api.py", line 2227, in nft_set_nft_did
    spend_bundle = await nft_wallet.set_nft_did(nft_coin_info, did_id, fee=fee)
  File "/redacted/path/chia-blockchain/chia/wallet/nft_wallet/nft_wallet.py", line 1045, in set_nft_did
    did_inner_hash, did_bundle = await self.get_did_approval_info(nft_id, bytes32(did_id))
  File "/redacted/path/chia-blockchain/chia/wallet/nft_wallet/nft_wallet.py", line 302, in get_did_approval_info
    did_bundle = await wallet.create_message_spend(puzzle_announcements=[nft_id])
  File "/redacted/path/chia-blockchain/chia/wallet/did_wallet/did_wallet.py", line 791, in create_message_spend
    assert parent_info is not None
AssertionError
```

**Comment by ytx1991** [comment]
Some errors may happen while you call the did_find_lost_did. Can you check your log?

**Comment by Jsewill** [comment]
I no longer receive any errors when running `chia rpc wallet did_find_lost_did`, by stdout or by log. I only receive the above error now, with no delay, when attempting to move an NFT to that DID.

**Comment by Jsewill** [comment]
Yes, that's why I was able to move NFTs for a little while.

**Comment by Jsewill** [comment]
I deleted my mainnet directory and completely resync'd. Now I get an error to stdout and to the logs when running `did_find_lost_did`:

stdout:

```
Request failed: {'error': "'NoneType' object has no attribute 'pubkey'", 'success': False}
```

Logs:

```
2022-11-23T14:29:17.061 wallet chia.rpc.util              : WARNING  Error while handling message: Traceback (most recent call last):
  File "/redacted/path/chia-blockchain/chia/rpc/util.py", line 18, in inner
    res_object = await f(request_data)
  File "/redacted/path/chia-blockchain/chia/rpc/wallet_rpc_api.py", line 1920, in did_find_lost_did
    await did_wallet.coin_added(coin_state.coin, uint32(coin_state.created_height), peer)
  File "/redacted/path/chia-blockchain/chia/wallet/did_wallet/did_wallet.py", line 383, in coin_added 
    inner_puzzle = await self.inner_puzzle_for_did_puzzle(coin.puzzle_hash)
  File "/redacted/path/chia-blockchain/chia/wallet/did_wallet/did_wallet.py", line 1147, in inner_puzzle_for_did_puzzle
    puzzle_for_pk(record.pubkey),
AttributeError: 'NoneType' object has no attribute 'pubkey'
```

Moving an NFT to this DID still doesn't quite work. The GUI wallet displayed an error just like the one I mentioned before, but the NFT seemed to move in the end anyway. I'll be trying to move another in a little while.

**Comment by Jsewill** [comment]
I am unable to continue moving NFTs. No new log output. It appears after a `git pull`, that there are some changes to that branch. Should I pull and run install.sh again?

**Comment by ytx1991** [comment]
yes

**Comment by Jsewill** [comment]
I'd rather the bug be fixed and keep my current DID. The bulk set did procedure sounds convenient.

**Comment by Jsewill** [comment]
Is there anything more you'd like me to do to help get this fixed? In case I wasn't clear, using `did_find_lost_did` does **not** work indefinitely for my case. Eventually it stops working.

**Comment by ytx1991** [comment]
Can you pull the main branch and install it? Also, resync your wallet and wait for it fully synced then run the did_find_lost_did API with 5d21dfef22e78670bbbdbfb2e1e78cb3d85c96a947a725aa20940a5d190f8cae as the coin ID. 
The log you sent is not the root cause. I need to know the related error log before that one.

**Comment by Jsewill** [comment]
Yes. I've checked out the main branch, reinstalled, and synced from scratch. After running `did_find_lost_did`, per your instruction, I had no trouble initiating the movement of a few NFTs to the DID without a fee. However, they are still pending. Furthermore, when attempting to do the same, but specifying a fee, the GUI says it failed due to a timeout, and the logs show that the wallet simply hangs:

```
...
2022-12-06T14:41:08.395 wallet wallet_server              : INFO     Cannot connect to host 127.0.0.1:8444 ssl:<ssl.SSLContext object at <redacted>> [Connect call failed ('127.0.0.1', 8444)]
2022-12-06T14:41:11.396 wallet wallet                     : INFO     Reconnecting to peer {'host': '127.0.0.1', 'port': 8444}
...
```

All that said, the first NFT that I tried to move while including a fee, seems to have moved successfully. I have only had to call `did_find_lost_did` once, so far. I will continue to try to move NFTs to the DID and see if I can break it, and report back.

**Comment by Jsewill** [comment]
While waiting for the second, fee-included NFT to DID transfer to finish submitting, chia spat this out to stdout (rather than the logs):

```
Exception from 'wallet' :
Traceback (most recent call last):
  File "/redacted/path/chia-blockchain/chia/cmds/cmds_util.py", line 100, in get_any_service_client
    yield node_client, config, fingerprint
  File "/redacted/path/chia-blockchain/chia/cmds/cmds_util.py", line 211, in execute_with_wallet
    await function(extra_params, wallet_client, new_fp)
  File "/redacted/path/chia-blockchain/chia/cmds/wallet_funcs.py", line 228, in send
    res = await wallet_client.send_transaction(
  File "/redacted/path/chia-blockchain/chia/rpc/wallet_rpc_client.py", line 185, in send_transaction
    res = await self.fetch("send_transaction", send_dict)
  File "/redacted/path/chia-blockchain/chia/rpc/rpc_client.py", line 46, in fetch
    async with self.session.post(self.url + path, json=request_json, ssl_context=self.ssl_context) as response:
  File "/redacted/path/chia-blockchain/venv/lib/python3.9/site-packages/aiohttp/client.py", line 1141, in __aenter__ 
    self._resp = await self._coro
  File "/redacted/path/chia-blockchain/venv/lib/python3.9/site-packages/aiohttp/client.py", line 560, in _request
    await resp.start(conn)
  File "/redacted/path/chia-blockchain/venv/lib/python3.9/site-packages/aiohttp/client_reqrep.py", line 914, in start  
    self._continue = None
  File "/redacted/path/chia-blockchain/venv/lib/python3.9/site-packages/aiohttp/helpers.py", line 720, in __exit__
    raise asyncio.TimeoutError from None
asyncio.exceptions.TimeoutError
```

The aforementioned operation soon after reported a timeout error, just as before. I'm still waiting to see if this NFT transfers too.

**Comment by ytx1991** [comment]
This seems like another issue. Set DID for NFT takes a longer time. Sometimes you may need to restart the GUI to see the change. If you don't have any other questions about set DID for NFT, feel free to close the issue.
