### ISSUE TITLE
[BUG] Plot fails with Not enough memory for sort in memory

### ISSUE THREAD

**Issue by crhuber** [Chia-Network/chia-blockchain#1378]
**Describe the bug**
Ive tried multiple times to create a plot on Amazon Linux each time i get the following message. It always seems to fail at bucket 127 no matter how big my instance is

```
 Bucket 125 QS. Ram: 0.465GiB, u_sort min: 0.563GiB, qs min: 0.281GiB. force_qs: 0
 Bucket 126 QS. Ram: 0.465GiB, u_sort min: 0.563GiB, qs min: 0.281GiB. force_qs: 0
 Bucket 127 QS. Ram: 0.465GiB, u_sort min: 1.125GiB, qs min: 0.281GiB. force_qs: 0
 Total matches: 4294941446
Forward propagation table time: 3585.387 seconds. CPU (115.580%) Fri Mar 19 10:20:21 2021
Computing table 3
Caught plotting error: Not enough memory for sort in memory. Need to sort 0.562430GiB
Traceback (most recent call last):
  File "/home/ec2-user/chia-blockchain/venv/bin/chia", line 33, in <module>
    sys.exit(load_entry_point('chia-blockchain', 'console_scripts', 'chia')())
  File "/home/ec2-user/chia-blockchain/src/cmds/chia.py", line 59, in main
    cli()  # pylint: disable=no-value-for-parameter
  File "/home/ec2-user/chia-blockchain/venv/lib64/python3.7/site-packages/click/core.py", line 1026, in __call__
    return self.main(*args, **kwargs)
  File "/home/ec2-user/chia-blockchain/venv/lib64/python3.7/site-packages/click/core.py", line 956, in main
    rv = self.invoke(ctx)
  File "/home/ec2-user/chia-blockchain/venv/lib64/python3.7/site-packages/click/core.py", line 1518, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/ec2-user/chia-blockchain/venv/lib64/python3.7/site-packages/click/core.py", line 1518, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/ec2-user/chia-blockchain/venv/lib64/python3.7/site-packages/click/core.py", line 1280, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/ec2-user/chia-blockchain/venv/lib64/python3.7/site-packages/click/core.py", line 711, in invoke
    return callback(*args, **kwargs)
  File "/home/ec2-user/chia-blockchain/venv/lib64/python3.7/site-packages/click/decorators.py", line 22, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/ec2-user/chia-blockchain/src/cmds/plots.py", line 134, in create_cmd
    create_plots(Params(), ctx.obj["root_path"])
  File "/home/ec2-user/chia-blockchain/src/plotting/create_plots.py", line 176, in create_plots
    args.nobitfield,
RuntimeError: std::exception
```
However I have plenty of memory  (see below)

**To Reproduce**
1. chia plots create -n 1 -b 512 -e -d /mnt/data/chia-final

**Expected behavior**
Be able to create a plot

**Desktop**

```
chia version
1.0.0

uname -a
Linux  4.14.219-164.354.amzn2.x86_64 #1 SMP Mon Feb 22 21:18:39 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

df -h
Filesystem      Size  Used Avail Use% Mounted on
devtmpfs        3.9G     0  3.9G   0% /dev
tmpfs           3.9G     0  3.9G   0% /dev/shm
tmpfs           3.9G  448K  3.9G   1% /run
tmpfs           3.9G     0  3.9G   0% /sys/fs/cgroup
/dev/nvme0n1p1  8.0G  1.6G  6.5G  20% /
tmpfs           788M     0  788M   0% /run/user/1000
/dev/nvme1n1    600G   15G  586G   3% /mnt/data
tmpfs           788M     0  788M   0% /run/user/0

free -h
              total        used        free      shared  buff/cache   available
Mem:           7.7G        121M        6.4G        448K        1.1G        7.3G
Swap:            0B          0B          0B

```

**Additional context**

**Comment by hoffmang9** [comment]
Your -b setting is way too low. Memory guidance in the middle https://chia.net/2021/02/22/plotting-basics.html
