### ISSUE TITLE
[Bug] Creating Plot NFT and Joining Pool stuck forever

### ISSUE THREAD

**Issue by efjcapital** [Chia-Network/chia-blockchain#13853]
### What happened?

Tried to create a plot nft several months ago, the transaction did NOT go through. Since then, whenever I opened "Your Pool Overview" tab in GUI, it stuck in the page "Waiting for the transaction to be confirmed". Output log attached

![error page ](https://user-images.githubusercontent.com/117652749/200318998-3fcbac9a-ab17-4006-a9f0-cfd5c27c8ec6.jpg)

### Version

1.6.0

### What platform are you using?

Windows

### What ui mode are you using?

GUI

### Relevant log output

```shell
2022-11-07T08:09:01.202 wallet chia.rpc.rpc_server        : WARNING  Error while handling message: Traceback (most recent call last):
  File "chia\rpc\rpc_server.py", line 244, in safe_handle
  File "chia\rpc\rpc_server.py", line 235, in ws_api
  File "chia\rpc\wallet_rpc_api.py", line 771, in get_transaction
ValueError: Transaction 0x2f677d601c78371d7e41d5374dd472874cc125cef9330586ab0407169766daf0 not found

2022-11-07T08:09:06.209 wallet chia.rpc.rpc_server        : WARNING  Error while handling message: Traceback (most recent call last):
  File "chia\rpc\rpc_server.py", line 244, in safe_handle
  File "chia\rpc\rpc_server.py", line 235, in ws_api
  File "chia\rpc\wallet_rpc_api.py", line 771, in get_transaction
ValueError: Transaction 0x2f677d601c78371d7e41d5374dd472874cc125cef9330586ab0407169766daf0 not found
```

**Comment by emlowe** [comment]
I think you can resolve this by manually removing the entries from config.yaml that reference this pool. However, you may have to resync your wallet. 

I'll note that there were some bugs in 1.6.0 related to pool transitions, including joining a pool. These were fixed in 1.6.2

**Comment by emlowe** [comment]
Further review suggests the GUI caches these in local storage while waiting for confirmation - looking into the easiest way for you to remove them

**Comment by emlowe** [comment]
If you use the View->Developer menu to bring up the Developer Tools, you can then select "Application" and the Local Storage and delete the `unconfirmedPlotNFTsV2` - 

![Screenshot 2023-01-09 at 3 06 12 PM](https://user-images.githubusercontent.com/30607889/211426101-f9279b2c-0819-435e-8ce7-a47fe7b0f13f.png)

**Comment by emlowe** [comment]
Leaving this open in order to track making changes in the GUI where a `Transaction not found` error or similar will remove this from the Local Storage cache since it would never complete in this case.

**Comment by danieljperry** [comment]
Closing -- a workaround was supplied, it is now easier than before to resync one's wallet in these situations, and the new plotNFT format is coming soon.
