### ISSUE TITLE
[Bug] on Win10 1.6.1 wont start "Loading Keyring status"

### ISSUE THREAD

**Issue by amnesia106** [Chia-Network/chia-blockchain#13860]
### What happened?

After upgrade to 1.6.1 chia wont start. 
i try: delete the keyfiles and the db and reinstall. but same. Stuck on "loading keyring status"
PS: 1.6.0 runs smooth

when i start 1.6.1 in powershell see log output

### Version

1.61

### What platform are you using?

Windows

### What ui mode are you using?

GUI

### Relevant log output
Powershell:

PS C:\Users\Miner\AppData\Local\Programs\Chia> .\chia start farmer
PS C:\Users\Miner\AppData\Local\Programs\Chia>
Checking if userData migration is needed
C:\Users\Miner\AppData\Roaming\Chia Blockchain\Local Storage\leveldb exists: false
C:\Users\Miner\.chia\mainnet\gui\Chia Blockchain\Local Storage\leveldb exists: true
C:\Users\Miner\AppData\Roaming\Chia Blockchain\Local Storage\leveldb\migrated exists: false
Migration needed: false
Setting user data directory to C:\Users\Miner\.chia\mainnet\gui\Chia Blockchain
Running python executable:
child process success
stderr: Traceback (most recent call last):
  File "chia\daemon\server.py", line 1470, in <module>
stderr:   File "chia\daemon\server.py", line 1466, in main
  File "chia\daemon\server.py", line 1457, in run_daemon
  File "asyncio\runners.py", line 44, in run
  File "asyncio\base_events.py", line 647, in run_until_complete
stderr:   File "chia\daemon\server.py", line 1401, in async_run_daemon
  File "chia\cmds\init_funcs.py", line 480, in chia_init
  File "chia\cmds\init_funcs.py", line 84, in check_keys
stderr:   File "chia\util\keychain.py", line 387, in get_all_private_keys
  File "chia\util\keychain.py", line 288, in _get_key_data
stderr:   File "<string>", line 7, in __init__
  File "chia\util\keychain.py", line 203, in __post_init__
No cert
Chia directory G:\.chia\mainnet
stderr: chia.util.errors.KeychainKeyDataMismatch: KeyData mismatch for: public_key
[13108] Failed to execute script 'server' due to unhandled exception!
closing code: 1

Log: 

2022-11-08T00:00:02.190 harvester chia.rpc.rpc_server     : WARNING  Cannot connect to daemon at ws://localhost:55400
2022-11-08T00:00:02.368 wallet chia.rpc.rpc_server        : WARNING  Cannot connect to daemon at ws://localhost:55400
2022-11-08T00:00:02.369 wallet chia.wallet.wallet_node    : WARNING  Can not connect to keychain at wss://localhost:55400.
2022-11-08T00:00:05.226 farmer chia.farmer.farmer         : WARNING  Can not connect to keychain at wss://localhost:55400.
2022-11-08T00:00:05.228 farmer chia.rpc.rpc_server        : WARNING  Cannot connect to daemon at ws://localhost:55400
2022-11-08T00:00:08.199 harvester chia.rpc.rpc_server     : WARNING  Cannot connect to daemon at ws://localhost:55400
2022-11-08T00:00:08.366 wallet chia.wallet.wallet_node    : WARNING  Can not connect to keychain at wss://localhost:55400.
2022-11-08T00:00:08.368 wallet chia.rpc.rpc_server        : WARNING  Cannot connect to daemon at ws://localhost:55400
2022-11-08T00:00:11.228 farmer chia.rpc.rpc_server        : WARNING  Cannot connect to daemon at ws://localhost:55400

**Comment by mimeie** [comment]
same problem here (also win10 and 1.6.1)
I even deleted everything and installed it new

**Comment by ShadXo** [comment]
My log also looked like that, upgraded from 1.5.1 to 1.6.1. Restarted the computer and seems to be working now.

**Comment by jekeam** [comment]
A similar problem, it turned out that the port is busy:

```
Running python executable:
child process success
No cert
Have certain
stderr: Traceback (most recent call last):
  File "chia\daemon\server.py", line 1470, in <module>
stderr:   File "chia\daemon\server.py", line 1466, in main
  File "chia\daemon\server.py", line 1457, in run_daemon
  File "asyncio\runners.py", line 44, in run
stderr:   File "asyncio\base_events.py", line 647, in run_until_complete
  File "chia\daemon\server.py", line 1442, in async_run_daemon
  File "chia\daemon\server.py", line 175, in start
  File "chia\util\network.py", line 46, in create
  File "aiohttp\web_runner.py", line 121, in start
stderr:   File "asyncio\base_events.py", line 1506, in create_server
PermissionError: [Errno 13] error while attempting to bind on address ('127.0.0.1', 55400):
```

**Comment by jekeam** [comment]
There was the same problem, a reboot solved the problem (there was a problem with access to port 55400)

**Comment by wallentx** [comment]
@amnesia106 Does this issue still happen after a system reboot? I wonder if it has to do with the legacy keystore stored in Windows Credential Manager.

**Comment by PavelSigeti** [comment]
I have such problem when Docker or server on my PC works. Just stop this processes and reboot

**Comment by ytx1991** [comment]
For Windows users, make sure you stopped and disabled Hyper-V services. Hyper-V will occupy the port.

**Comment by jekeam** [comment]
> Hyper-V

I have Hyper-V enabled - but reboot solved the problem

**Comment by jekeam** [comment]
The problem reappeared, reboot does not help:
```
PS C:\Users\admin> C:\Users\admin\AppData\Local\Programs\Chia\Chia.exe

PS C:\Users\admin> Checking if userData migration is needed
C:\Users\admin\AppData\Roaming\Chia Blockchain\Local Storage\leveldb exists: false
C:\Users\admin\.chia\mainnet\gui\Chia Blockchain\Local Storage\leveldb exists: true
C:\Users\admin\AppData\Roaming\Chia Blockchain\Local Storage\leveldb\migrated exists: false
Migration needed: false
Setting user data directory to C:\Users\admin\.chia\mainnet\gui\Chia Blockchain
Running python executable:
child process success
No cert
Have cert
stderr: Traceback (most recent call last):
  File "chia\daemon\server.py", line 1390, in <module>
  File "chia\daemon\server.py", line 1386, in main
stderr:   File "chia\daemon\server.py", line 1377, in run_daemon
  File "asyncio\runners.py", line 44, in run
  File "asyncio\base_events.py", line 647, in run_until_complete
  File "chia\daemon\server.py", line 1362, in async_run_daemon
stderr:   File "chia\daemon\server.py", line 173, in start
  File "chia\util\network.py", line 47, in create
stderr:   File "aiohttp\web_runner.py", line 121, in start
  File "asyncio\base_events.py", line 1506, in create_server
PermissionError: [Errno 13] error while attempting to bind on address ('127.0.0.1', 55400): я┐╜я┐╜я┐╜я┐╜я┐╜я┐╜я┐╜ я┐╜я┐╜я┐╜я┐╜я┐╜я┐╜я┐╜ я┐╜я┐╜я┐╜я┐╜я┐╜я┐╜я┐╜ я┐╜ я┐╜я┐╜я┐╜я┐╜я┐╜я┐╜ я┐╜я┐╜я┐╜я┐╜я┐╜я┐╜я┐╜, я┐╜я┐╜я┐╜я┐╜я┐╜я┐╜я┐╜я┐╜я┐╜я┐╜я┐╜ я┐╜я┐╜я┐╜я┐╜я┐╜я┐╜я┐╜ я┐╜я┐╜я┐╜я┐╜я┐╜я┐╜я┐╜
[2668] Failed to executstderr: e script 'server' due to unhandled exception!
closing code: 1
```
I updated the version of the program - the problem remained, I do not see that the port would be busy:
![image](https://user-images.githubusercontent.com/19660852/210753740-ac540200-2467-40f2-ab59-437d7cb483c4.png)

**Comment by emlowe** [comment]
The original report was not related to ports - so the follow-up comments are not germane to the original report. Note that hyper-v will "reserve" the port even though it doesn't use it. Please post further port issues in a support discussion

**Comment by emlowe** [comment]
Closing issue as there was no response from the original bug reporter

**Comment by jekeam** [comment]
You are great at solving problems, keep the brand.

**Comment by emlowe** [comment]
For the problem of windows reserving the port, I recommend the following:

`dism.exe /Online /Disable-Feature:Microsoft-Hyper-V`
`reboot`
`netsh int ipv4 add excludedportrange protocol=tcp startport=55400 numberofports=1`
`reboot`
`dism.exe /Online /Disable-Feature:Microsoft-Hyper-V`
`reboot`

**Comment by jekeam** [comment]
> For the problem of windows reserving the port, I recommend the following:
> 
> `dism.exe /Online /Disable-Feature:Microsoft-Hyper-V` `reboot` `netsh int ipv4 add excludedportrange protocol=tcp startport=55400 numberofports=1` `reboot` `dism.exe /Online /Disable-Feature:Microsoft-Hyper-V` `reboot`

I understand this may be surprising, but I need Hyper-V, how should I be in this case?

**Comment by emlowe** [comment]
Those commands only temporarily disable Hyper-V and then re-enable it - but it will stop reserving the default daemon port of 55400. At the end you have hyper-V working just fine.

Alternatively, you can edit config.yaml and pick a different port for the daemon

**Comment by amnesia106** [comment]
> Those commands only temporarily disable Hyper-V and then re-enable it - but it will stop reserving the default daemon port of 55400. At the end you have hyper-V working just fine.
> 
> Alternatively, you can edit config.yaml and pick a different port for the daemon

This slove my problem. with 1.7.0 - change daemon port on top of the cfg, and under ui: 

Thanks

**Comment by nothinglastsforever** [comment]
> For the problem of windows reserving the port, I recommend the following:
> 
> `dism.exe /Online /Disable-Feature:Microsoft-Hyper-V` `reboot` `netsh int ipv4 add excludedportrange protocol=tcp startport=55400 numberofports=1` `reboot` `dism.exe /Online /Disable-Feature:Microsoft-Hyper-V` `reboot`

This solved my problem. Thank you!
