### ISSUE TITLE
[Bug] full_node chia.full_node.mempool_manager: WARNING  Conflicting pool items: 1

### ISSUE THREAD

**Issue by HVNC1** [Chia-Network/chia-blockchain#13900]
### What happened?

after disconnecting from the pool, such an error appeared that constantly appears in the log
![image](https://user-images.githubusercontent.com/95166695/201494119-c7c96876-37d8-4ea8-ab52-b7906bb103b7.png)

### Version

1.7.0 b1

### What platform are you using?

Windows

### What ui mode are you using?

GUI

### Relevant log output

```shell
2022-11-12T22:26:23.126 full_node chia.full_node.mempool_manager: WARNING  Conflicting pool items: 1
2022-11-12T22:26:23.127 full_node chia.full_node.mempool_manager: INFO     Replacing conflicting tx in mempool. New tx fee: 500000074, old tx fees: 0
```

**Comment by Sinkevi4** [comment]
### Version
### 1.7.0 
### What platform are you using?
### Windows
### What ui mode are you using?
### GUI
### Relevant log output
```
2022-11-13T10:57:54.853 full_node chia.full_node.mempool_manager: WARNING  Conflicting pool items: 1
2022-11-13T10:57:54.853 full_node chia.full_node.mempool_manager: INFO     Replacing conflicting tx in mempool. New tx fee: 500000032, old tx fees: 0
2022-11-13T11:00:02.213 full_node chia.full_node.mempool_manager: WARNING  Conflicting pool items: 1
2022-11-13T11:00:02.213 full_node chia.full_node.mempool_manager: INFO     Replacing conflicting tx in mempool. New tx fee: 500000091, old tx fees: 0
2022-11-13T11:02:09.478 full_node chia.full_node.mempool_manager: WARNING  Conflicting pool items: 1
2022-11-13T11:02:09.478 full_node chia.full_node.mempool_manager: INFO     Replacing conflicting tx in mempool. New tx fee: 500000096, old tx fees: 0
```
First seen in v1.6 or earlier.

**Comment by neo57500** [comment]
2022-11-13T17:36:12.668 data_layer_http aiohttp.server    : ERROR    Error handling request
Traceback (most recent call last):
  File "aiohttp\web_protocol.py", line 332, in data_received
  File "aiohttp\_http_parser.pyx", line 551, in aiohttp._http_parser.HttpParser.feed_data
aiohttp.http_exceptions.BadHttpMessage: 400, message='Pause on PRI/Upgrade'
2022-11-13T17:36:30.183 full_node chia.full_node.full_node: WARNING  Time for header validate: 0.050020694732666016
2022-11-13T17:36:32.230 full_node chia.full_node.full_node: WARNING  Time for header validate: 0.03798794746398926
2022-11-13T17:36:57.121 full_node chia.full_node.full_node: WARNING  Time for header validate: 0.038987159729003906
2022-11-13T17:37:00.125 full_node chia.full_node.mempool_manager: WARNING  Conflicting pool items: 1
2022-11-13T17:37:16.870 full_node chia.full_node.full_node: WARNING  Time for header validate: 0.04598116874694824
2022-11-13T17:37:19.098 full_node chia.full_node.full_node: WARNING  Time for header validate: 0.03598451614379883

**Comment by arvidn** [comment]
@HVNC1 in your description you say "error", but in the log there are only "warning"s and "info" log entries.
replacing items in the mempool is a feature and expected to happen. Is this report about it should not be logged as a WARNING, but it should be logged as INFO?

If so, that seems reasonable. Please confirm.
