### ISSUE TITLE
full_node chia.full_node.full_node: WARNING  Time for header validate: 0.015517473220825195 [Bug] 

### ISSUE THREAD

**Issue by mech2you** [Chia-Network/chia-blockchain#13901]
### What happened?

Is this a error or not? What this mean? Can´t finde any information about this. The log file is full of this erros... 

Win 10x64 22H2 i3-10100 64GB Ram... 106 HDD´s with USB connected and 1.554PiB farm size.

### Version

1.6.1

### What platform are you using?

Windows

### What ui mode are you using?

GUI

### Relevant log output

```shell
2022-11-12T23:18:04.773 full_node chia.full_node.full_node: WARNING  Time for header validate: 0.015589475631713867
2022-11-12T23:19:07.811 full_node chia.full_node.full_node: WARNING  Time for header validate: 0.015544652938842773
2022-11-12T23:19:33.636 full_node chia.full_node.full_node: WARNING  Time for header validate: 0.015548944473266602
2022-11-12T23:19:38.081 full_node chia.full_node.full_node: WARNING  Time for header validate: 0.0155487060546875
2022-11-12T23:19:41.047 full_node chia.full_node.full_node: WARNING  Time for header validate: 0.015521526336669922
```

**Comment by neo57500** [comment]
2022-11-13T17:36:12.668 data_layer_http aiohttp.server    : ERROR    Error handling request
Traceback (most recent call last):
  File "aiohttp\web_protocol.py", line 332, in data_received
  File "aiohttp\_http_parser.pyx", line 551, in aiohttp._http_parser.HttpParser.feed_data
aiohttp.http_exceptions.BadHttpMessage: 400, message='Pause on PRI/Upgrade'
2022-11-13T17:36:30.183 full_node chia.full_node.full_node: WARNING  Time for header validate: 0.050020694732666016
2022-11-13T17:36:32.230 full_node chia.full_node.full_node: WARNING  Time for header validate: 0.03798794746398926
2022-11-13T17:36:57.121 full_node chia.full_node.full_node: WARNING  Time for header validate: 0.038987159729003906
2022-11-13T17:37:00.125 full_node chia.full_node.mempool_manager: WARNING  Conflicting pool items: 1
2022-11-13T17:37:16.870 full_node chia.full_node.full_node: WARNING  Time for header validate: 0.04598116874694824
2022-11-13T17:37:19.098 full_node chia.full_node.full_node: WARNING  Time for header validate: 0.03598451614379883

**Comment by heget** [comment]
They working on it to be hidden again in next update. Anyway this isn't any error, just warnings but a lot of I know...

**Comment by wallentx** [comment]
It appears that this is a message that impacts larger farms. Our apologies for this. It's a harmless message. It prints out regardless of how long it takes. We'll look into fixing this.
