### ISSUE TITLE
[Bug] having issues with stuck transactions and fees

### ISSUE THREAD

**Issue by KryptomineCH** [Chia-Network/chia-blockchain#13956]
### What happened?

I have frequent issues with stuck transactions when minting or transferring NFT's. Normal transactiosn seem fine as long as I put a sufficient fee.
It does not seem to be an issue related to too little fee either. I tried to transfer 8 nfts to another profile. with 2 attemps (clear transactions) The client managed to transfer 3 nfts. Fee was set to 10k Mojos:
![image](https://user-images.githubusercontent.com/117320700/202792971-82482ad8-a04a-4cab-83b0-86529c49a4cc.png)

now, after one hour, I reinitiated one transfer, but halved the fee to 5k mojos... and it got executed after a few minutes:
![image](https://user-images.githubusercontent.com/117320700/202793206-04591849-d33d-49fa-be6b-bfc04c423c24.png)

please help me how to debug this. It prevents me from minting properly.
I have found a couple of double spend bundles in the logs... perhaps thats what causes the issue?

Network connection should not be an issue either but I see plenty of nodes timeouting
![image](https://user-images.githubusercontent.com/117320700/202793778-a76b8924-82b5-4409-8864-602ce4a6a19d.png)

### Version

1.6.1

### What platform are you using?

Windows

### What ui mode are you using?

GUI

### Relevant log output

```shell
2022-11-18T09:02:31.495 wallet chia.wallet.wallet_node    : WARNING  SpendBundle has been rejected by the FullNode. {'error': 'DOUBLE_SPEND', 'status': 3, 'txid': '0x6a4d6f634657295902cb93c780374ff419172c5caa3a5a953b1ac7a67abd0bf3'}
2022-11-18T09:02:42.159 wallet chia.wallet.wallet_node    : WARNING  SpendBundle has been rejected by the FullNode. {'error': 'DOUBLE_SPEND', 'status': 3, 'txid': '0x6a4d6f634657295902cb93c780374ff419172c5caa3a5a953b1ac7a67abd0bf3'}
2022-11-18T09:03:46.803 wallet chia.wallet.wallet_node    : WARNING  SpendBundle has been rejected by the FullNode. {'error': 'DOUBLE_SPEND', 'status': 3, 'txid': '0x6a4d6f634657295902cb93c780374ff419172c5caa3a5a953b1ac7a67abd0bf3'}
2022-11-18T09:03:46.806 wallet chia.wallet.wallet_node    : WARNING  SpendBundle has been rejected by the FullNode. {'error': 'DOUBLE_SPEND', 'status': 3, 'txid': '0x6a4d6f634657295902cb93c780374ff419172c5caa3a5a953b1ac7a67abd0bf3'}
2022-11-18T09:03:46.809 wallet chia.wallet.wallet_node    : WARNING  SpendBundle has been rejected by the FullNode. {'error': 'DOUBLE_SPEND', 'status': 3, 'txid': '0x6a4d6f634657295902cb93c780374ff419172c5caa3a5a953b1ac7a67abd0bf3'}
2022-11-18T09:03:46.812 wallet chia.wallet.wallet_node    : WARNING  SpendBundle has been rejected by the FullNode. {'error': 'DOUBLE_SPEND', 'status': 3, 'txid': '0x6a4d6f634657295902cb93c780374ff419172c5caa3a5a953b1ac7a67abd0bf3'}
2022-11-18T09:03:46.815 wallet chia.wallet.wallet_node    : WARNING  SpendBundle has been rejected by the FullNode. {'error': 'DOUBLE_SPEND', 'status': 3, 'txid': '0x6a4d6f634657295902cb93c780374ff419172c5caa3a5a953b1ac7a67abd0bf3'}
2022-11-18T09:04:24.790 wallet asyncio                    : ERROR    Task exception was never retrieved
future: <Task finished name='Task-12667' coro=<WalletNode.long_sync() done, defined at chia\wallet\wallet_node.py:621> exception=ValueError('None response from peer 44.234.58.73 for register_interest_in_puzzle_hash')>
Traceback (most recent call last):
  File "chia\wallet\wallet_node.py", line 666, in long_sync
  File "chia\wallet\util\wallet_sync_utils.py", line 74, in subscribe_to_phs
ValueError: None response from peer 44.234.58.73 for register_interest_in_puzzle_hash
2022-11-18T09:04:25.749 wallet chia.wallet.wallet_node    : WARNING  Peer None did not respond in time.
2022-11-18T09:04:27.060 wallet chia.wallet.wallet_node    : WARNING  Peer None did not respond in time.
2022-11-18T09:04:37.454 wallet chia.wallet.wallet_node    : WARNING  Peer None did not respond in time.
2022-11-18T09:04:39.443 wallet chia.wallet.wallet_node    : WARNING  Peer None did not respond in time.
2022-11-18T09:06:36.306 wallet chia.rpc.rpc_server        : WARNING  Error while handling message: Traceback (most recent call last):
  File "chia\rpc\rpc_server.py", line 324, in safe_handle
  File "chia\rpc\rpc_server.py", line 315, in ws_api
  File "chia\rpc\wallet_rpc_api.py", line 492, in get_wallets
  File "chia\wallet\wallet_node.py", line 154, in wallet_state_manager
RuntimeError: wallet state manager not assigned

2022-11-18T09:11:05.937 wallet chia.rpc.rpc_server        : WARNING  Error while handling message: Traceback (most recent call last):
  File "chia\rpc\rpc_server.py", line 332, in safe_handle
  File "aiohttp\client_ws.py", line 151, in send_str
  File "aiohttp\http_websocket.py", line 690, in send
  File "aiohttp\http_websocket.py", line 659, in _send_frame
  File "aiohttp\base_protocol.py", line 80, in _drain_helper
ConnectionResetError: Connection lost

2022-11-18T09:24:51.272 wallet chia.wallet.wallet_node    : WARNING  Peer {'host': '67.20.231.8', 'port': 8444} did not respond in time.
2022-11-18T09:40:22.696 wallet chia.wallet.wallet_node    : WARNING  Peer None did not respond in time.
2022-11-18T09:43:44.772 wallet chia.wallet.wallet_node    : WARNING  Peer {'host': '51.81.107.67', 'port': 8444} did not respond in time.
2022-11-18T10:23:32.658 wallet chia.rpc.util              : WARNING  Error while handling message: Traceback (most recent call last):
  File "chia\rpc\util.py", line 18, in inner
  File "chia\rpc\wallet_rpc_api.py", line 1625, in nft_mint_nft
KeyError: 'wallet_id'

2022-11-18T13:49:51.013 wallet chia.wallet.wallet_node    : WARNING  Peer {'host': '47.180.95.22', 'port': 8444} did not respond in time.
2022-11-18T14:40:55.365 wallet chia.wallet.wallet_node    : WARNING  Peer None did not respond in time.
2022-11-18T14:46:59.268 wallet chia.wallet.wallet_node    : WARNING  Peer {'host': '49.175.166.39', 'port': 8444} did not respond in time.
2022-11-18T15:56:20.783 wallet chia.wallet.wallet_node    : WARNING  Peer {'host': '108.49.53.28', 'port': 8444} did not respond in time.
2022-11-18T18:26:48.927 wallet chia.wallet.wallet_node    : WARNING  SpendBundle has been rejected by the FullNode. {'error': 'ALREADY_INCLUDING_TRANSACTION',
 'status': 3,
 'txid': '0xfcb684483f796c05593efa4dd5bcda425a43ab74c70c35de54da1c365e51024c'}
2022-11-18T19:33:52.965 wallet chia.wallet.wallet_node    : WARNING  SpendBundle has been rejected by the FullNode. {'error': 'DOUBLE_SPEND', 'status': 3, 'txid': '0x190fd23d5830d97c1ef57932a9761f9b70aab57030cabfc8fbe852038603c3e9'}
2022-11-18T19:33:52.968 wallet chia.wallet.wallet_node    : WARNING  SpendBundle has been rejected by the FullNode. {'error': 'DOUBLE_SPEND', 'status': 3, 'txid': '0xe60dcea92c12a47d62d62d197bd7925ff535514a5c7082a9f6ca42a7e64d9386'}
2022-11-18T19:33:52.972 wallet chia.wallet.wallet_node    : WARNING  SpendBundle has been rejected by the FullNode. {'error': 'DOUBLE_SPEND', 'status': 3, 'txid': '0x1b10b1ae5020bc58e7313576ead6fdfd9d50844784bfd2392a84fc7a705e6771'}
2022-11-18T19:33:52.975 wallet chia.wallet.wallet_node    : WARNING  SpendBundle has been rejected by the FullNode. {'error': 'DOUBLE_SPEND', 'status': 3, 'txid': '0xb5cf9a7c467e768ad90522d5b88af48272417f9a9a1b821a7f18d7f294a22d21'}
2022-11-18T19:33:52.978 wallet chia.wallet.wallet_node    : WARNING  SpendBundle has been rejected by the FullNode. {'error': 'DOUBLE_SPEND', 'status': 3, 'txid': '0xd7834f9c2cba8d6f0f66aef69c34f0f91977b26a4e427ef34657f5b4721365c4'}
2022-11-18T19:33:52.981 wallet chia.wallet.wallet_node    : WARNING  SpendBundle has been rejected by the FullNode. {'error': 'DOUBLE_SPEND', 'status': 3, 'txid': '0x190fd23d5830d97c1ef57932a9761f9b70aab57030cabfc8fbe852038603c3e9'}
2022-11-18T19:33:52.984 wallet chia.wallet.wallet_node    : WARNING  SpendBundle has been rejected by the FullNode. {'error': 'DOUBLE_SPEND', 'status': 3, 'txid': '0x190fd23d5830d97c1ef57932a9761f9b70aab57030cabfc8fbe852038603c3e9'}
2022-11-18T19:33:52.987 wallet chia.wallet.wallet_node    : WARNING  SpendBundle has been rejected by the FullNode. {'error': 'DOUBLE_SPEND', 'status': 3, 'txid': '0x190fd23d5830d97c1ef57932a9761f9b70aab57030cabfc8fbe852038603c3e9'}
2022-11-18T19:33:53.290 wallet chia.wallet.wallet_node    : WARNING  SpendBundle has been rejected by the FullNode. {'error': 'DOUBLE_SPEND', 'status': 3, 'txid': '0x190fd23d5830d97c1ef57932a9761f9b70aab57030cabfc8fbe852038603c3e9'}
2022-11-18T19:42:43.983 wallet chia.wallet.wallet_node    : WARNING  SpendBundle has been rejected by the FullNode. {'error': 'DOUBLE_SPEND', 'status': 3, 'txid': '0x6f2102a62bf6fb664f0aeec5d18ab01ff6466436db2380ac9354f6a24ec08828'}
2022-11-18T19:42:59.655 wallet chia.wallet.wallet_node    : WARNING  SpendBundle has been rejected by the FullNode. {'error': 'DOUBLE_SPEND', 'status': 3, 'txid': '0x21897d5cb651f650c937cbd82ce9bf71a0163a2af5d703f00e522e1074391060'}
2022-11-18T19:42:59.679 wallet chia.wallet.wallet_node    : WARNING  SpendBundle has been rejected by the FullNode. {'error': 'DOUBLE_SPEND', 'status': 3, 'txid': '0xd468b2ef40bc941a60860892ca36cc5a838ae2d17e68cc1a90adfca3fb734bad'}
2022-11-18T19:42:59.683 wallet chia.wallet.wallet_node    : WARNING  SpendBundle has been rejected by the FullNode. {'error': 'DOUBLE_SPEND', 'status': 3, 'txid': '0x958ea819295a81e1dbdb5af680d41e16683b207a0fb27397db3286f8acb4d3f8'}
2022-11-18T19:42:59.687 wallet chia.wallet.wallet_node    : WARNING  SpendBundle has been rejected by the FullNode. {'error': 'DOUBLE_SPEND', 'status': 3, 'txid': '0x21897d5cb651f650c937cbd82ce9bf71a0163a2af5d703f00e522e1074391060'}
2022-11-18T19:42:59.696 wallet chia.wallet.wallet_node    : WARNING  SpendBundle has been rejected by the FullNode. {'error': 'DOUBLE_SPEND', 'status': 3, 'txid': '0xea057873f370a80041d45b08c3f6256239f6ea16928a0a3093fd9f2fa9637b0e'}
2022-11-18T19:42:59.699 wallet chia.wallet.wallet_node    : WARNING  SpendBundle has been rejected by the FullNode. {'error': 'DOUBLE_SPEND', 'status': 3, 'txid': '0x21897d5cb651f650c937cbd82ce9bf71a0163a2af5d703f00e522e1074391060'}
2022-11-18T19:42:59.702 wallet chia.wallet.wallet_node    : WARNING  SpendBundle has been rejected by the FullNode. {'error': 'DOUBLE_SPEND', 'status': 3, 'txid': '0x6f2102a62bf6fb664f0aeec5d18ab01ff6466436db2380ac9354f6a24ec08828'}
2022-11-18T19:42:59.706 wallet chia.wallet.wallet_node    : WARNING  SpendBundle has been rejected by the FullNode. {'error': 'DOUBLE_SPEND', 'status': 3, 'txid': '0x21897d5cb651f650c937cbd82ce9bf71a0163a2af5d703f00e522e1074391060'}
2022-11-18T19:42:59.722 wallet chia.wallet.wallet_node    : WARNING  SpendBundle has been rejected by the FullNode. {'error': 'DOUBLE_SPEND', 'status': 3, 'txid': '0x6f2102a62bf6fb664f0aeec5d18ab01ff6466436db2380ac9354f6a24ec08828'}
2022-11-18T19:42:59.725 wallet chia.wallet.wallet_node    : WARNING  SpendBundle has been rejected by the FullNode. {'error': 'DOUBLE_SPEND', 'status': 3, 'txid': '0x21897d5cb651f650c937cbd82ce9bf71a0163a2af5d703f00e522e1074391060'}
2022-11-18T20:39:01.121 wallet chia.wallet.wallet_node    : WARNING  Peer {'host': '77.57.1.225', 'port': 8444} did not respond in time.
```

**Comment by KryptomineCH** [comment]
update. After a painful 2 hours, I have been able to transfer my 8 NFTs. one at a time.
more than that and it's liekely gonna get stuck.
In the meantime I have also noticed some other things:
all transations are through:
![image](https://user-images.githubusercontent.com/117320700/202798700-63919085-a1a4-4716-be02-9f3ab389f25c.png)

but my nft wallet still doesnt update:
![image](https://user-images.githubusercontent.com/117320700/202798796-22b78d01-04cc-41cf-b4c9-5f423403926f.png)
whatever I do in the client does not help. Except if I cancle the transaction on the nft, then it gets updated in my nft wallet.

Additionally, now, I frequently loose all peers and they wont reconnect quickly
![image](https://user-images.githubusercontent.com/117320700/202802099-6103d26a-100a-4c63-a38f-dbeab6e39648.png)
no further errors in the log except for the duplicate spend bundles

**Comment by KryptomineCH** [comment]
still having the issue, primairly when trying to do multiple transactions after another. 
It all seems fine if I wait for each transaction to complete before initiating the next one. This is quite cumbersome.

**Comment by KryptomineCH** [comment]
Today a really weird issue:
![image](https://user-images.githubusercontent.com/117320700/206864004-10f033c7-691d-4db4-898d-7e58931ab20c.png)

I guess it might be related to my stuck transactions

**Comment by KryptomineCH** [comment]
upon reloading, the transaction is still stuck in my wallet but this time, the nft is minted already:
![image](https://user-images.githubusercontent.com/117320700/206864421-93b22b43-0297-4e77-bafd-5723a6c05c49.png)
![image](https://user-images.githubusercontent.com/117320700/206864437-99bbfaca-4df4-45f1-92ec-97ee2d0df2f9.png)

**Comment by emlowe** [comment]
Closing old issue - this can be re-opened if the problem persists, however, quite a few fixes have been implemented since this was originally reported.
