### ISSUE TITLE
[Bug] Farmer crashing every few hours

### ISSUE THREAD

**Issue by unintended-consequences** [Chia-Network/chia-blockchain#13989]
### What happened?

I run a farmer / full-node on a ROCK PI 4 Model B+ (ARM-based RK3399 SoC) running Ubuntu 20.04.5 LTS. There are no drives connected to this node. I have three other hosts running harvesters.

The farmer syncs up and can farm successfully. I see in my log lots of `ERROR Task exception was never retrieved` and `ERROR Exception Trying to connect to a peer`.

After approximately 5 hours, it will crash. The log does not seem to show any new errors.

Chia is v 1.6.1 installed via apt. I have deleted .chia folder and uninstalled and reinstalled chia. Log below is last 60 lines before crash.

### Version

1.6.1

### What platform are you using?

Pi4

### What ui mode are you using?

CLI

### Relevant log output

```shell
File "chia/server/server.py", line 446, in start_client
RuntimeError: Trying to connect to a peer ({'host': '67.83.205.166', 'port': 8444}) with the same peer_id: 2f087e99ff5d70cf3337ba3ed693de149123a7ecf591e6f79ae27facda6a4690

2022-11-22T23:46:53.204 full_node full_node_server        : ERROR    Exception Trying to connect to a peer ({'host': '188.246.163.3', 'port': 8444}) with the same peer_id: 2f087e99ff5d70cf3337ba3ed693de149123a7ecf591e6f79ae27facda6a4690, exception Stack: Traceback (most recent call last):
  File "chia/server/server.py", line 446, in start_client
RuntimeError: Trying to connect to a peer ({'host': '188.246.163.3', 'port': 8444}) with the same peer_id: 2f087e99ff5d70cf3337ba3ed693de149123a7ecf591e6f79ae27facda6a4690

2022-11-22T23:46:53.607 full_node full_node_server        : WARNING  Rate limiting ourselves. message type: respond_peers, peer: 89.22.143.254
2022-11-22T23:46:53.609 full_node full_node_server        : WARNING  Rate limiting ourselves. message type: respond_peers, peer: 101.86.9.179
2022-11-22T23:46:54.780 full_node asyncio                 : ERROR    Task exception was never retrieved
future: <Task finished name='Task-526608' coro=<WebSocketWriter.ping() done, defined at aiohttp/http_websocket.py:672> exception=ConnectionResetError('Cannot write to closing transport')>
Traceback (most recent call last):
  File "aiohttp/http_websocket.py", line 676, in ping
  File "aiohttp/http_websocket.py", line 646, in _send_frame
  File "aiohttp/http_websocket.py", line 663, in _write
ConnectionResetError: Cannot write to closing transport
2022-11-22T23:46:55.747 full_node full_node_server        : ERROR    Exception Trying to connect to a peer ({'host': '1.161.213.28', 'port': 8444}) with the same peer_id: 2f087e99ff5d70cf3337ba3ed693de149123a7ecf591e6f79ae27facda6a4690, exception Stack: Traceback (most recent call last):
  File "chia/server/server.py", line 446, in start_client
RuntimeError: Trying to connect to a peer ({'host': '1.161.213.28', 'port': 8444}) with the same peer_id: 2f087e99ff5d70cf3337ba3ed693de149123a7ecf591e6f79ae27facda6a4690

2022-11-22T23:46:56.228 full_node chia.full_node.full_node: INFO     🌱 Updated peak to height 2860846, weight 5919668328, hh c373cbb18a70bd6adb2b08a480ddc8dfa244f1919353e50f63bf9d961d86557c, forked at 2860845, rh: 23f0fa4c897e90a9bdfc3f82f795c2480eb1bb518571c84730e455c355cdedd2, total iters: 11626030292395, overflow: False, deficit: 2, difficulty: 1856, sub slot iters: 137363456, Generator size: No tx, Generator ref list size: No tx
2022-11-22T23:46:56.384 wallet chia.wallet.wallet_blockchain: INFO     Peak set to: 2860846 timestamp: 1669131962
2022-11-22T23:46:57.249 full_node full_node_server        : ERROR    Exception Trying to connect to a peer ({'host': '47.54.123.22', 'port': 8444}) with the same peer_id: 2f087e99ff5d70cf3337ba3ed693de149123a7ecf591e6f79ae27facda6a4690, exception Stack: Traceback (most recent call last):
  File "chia/server/server.py", line 446, in start_client
RuntimeError: Trying to connect to a peer ({'host': '47.54.123.22', 'port': 8444}) with the same peer_id: 2f087e99ff5d70cf3337ba3ed693de149123a7ecf591e6f79ae27facda6a4690

2022-11-22T23:46:58.351 full_node chia.full_node.full_node: INFO     ⏲️  Finished signage point 44/64: CC: 300e6210d0526479139c75432ed45e368160e4424cce474c13bfe6aaeb47d1a9 RC: 1c8c57d63b54e7b27beac22e463b75e5f762cee13da8dba0272ed1f6d36212ec 
2022-11-22T23:46:58.922 full_node full_node_server        : ERROR    Exception Trying to connect to a peer ({'host': '60.179.225.199', 'port': 8444}) with the same peer_id: 2f087e99ff5d70cf3337ba3ed693de149123a7ecf591e6f79ae27facda6a4690, exception Stack: Traceback (most recent call last):
  File "chia/server/server.py", line 446, in start_client
RuntimeError: Trying to connect to a peer ({'host': '60.179.225.199', 'port': 8444}) with the same peer_id: 2f087e99ff5d70cf3337ba3ed693de149123a7ecf591e6f79ae27facda6a4690

2022-11-22T23:47:00.781 full_node asyncio                 : ERROR    Task exception was never retrieved
future: <Task finished name='Task-526769' coro=<WebSocketWriter.ping() done, defined at aiohttp/http_websocket.py:672> exception=ConnectionResetError('Cannot write to closing transport')>
Traceback (most recent call last):
  File "aiohttp/http_websocket.py", line 676, in ping
  File "aiohttp/http_websocket.py", line 646, in _send_frame
  File "aiohttp/http_websocket.py", line 663, in _write
ConnectionResetError: Cannot write to closing transport
2022-11-22T23:47:00.923 full_node full_node_server        : INFO     Cannot connect to host 2a05:d01c:ea2:1702:552b:43cf:60a1:51c5:8444 ssl:<ssl.SSLContext object at 0xffffa99fb440> [Network is unreachable]
2022-11-22T23:47:01.637 full_node full_node_server        : WARNING  Rate limiting ourselves. message type: respond_peers, peer: 89.22.143.254
2022-11-22T23:47:01.639 full_node full_node_server        : WARNING  Rate limiting ourselves. message type: respond_peers, peer: 101.86.9.179
2022-11-22T23:47:01.781 full_node asyncio                 : ERROR    Task exception was never retrieved
future: <Task finished name='Task-526782' coro=<WebSocketWriter.ping() done, defined at aiohttp/http_websocket.py:672> exception=ConnectionResetError('Cannot write to closing transport')>
Traceback (most recent call last):
  File "aiohttp/http_websocket.py", line 676, in ping
  File "aiohttp/http_websocket.py", line 646, in _send_frame
  File "aiohttp/http_websocket.py", line 663, in _write
ConnectionResetError: Cannot write to closing transport
2022-11-22T23:47:02.506 full_node full_node_server        : ERROR    Exception Trying to connect to a peer ({'host': '99.123.146.251', 'port': 8444}) with the same peer_id: 2f087e99ff5d70cf3337ba3ed693de149123a7ecf591e6f79ae27facda6a4690, exception Stack: Traceback (most recent call last):
  File "chia/server/server.py", line 446, in start_client
RuntimeError: Trying to connect to a peer ({'host': '99.123.146.251', 'port': 8444}) with the same peer_id: 2f087e99ff5d70cf3337ba3ed693de149123a7ecf591e6f79ae27facda6a4690

2022-11-22T23:47:03.781 full_node asyncio                 : ERROR    Task exception was never retrieved
future: <Task finished name='Task-526789' coro=<WebSocketWriter.ping() done, defined at aiohttp/http_websocket.py:672> exception=ConnectionResetError('Cannot write to closing transport')>
Traceback (most recent call last):
  File "aiohttp/http_websocket.py", line 676, in ping
  File "aiohttp/http_websocket.py", line 646, in _send_frame
  File "aiohttp/http_websocket.py", line 663, in _write
ConnectionResetError: Cannot write to closing transport
```

**Comment by unintended-consequences** [comment]
Am running a cron job to just restart farmer if it detects it's no longer running as interim solution.

**Comment by unintended-consequences** [comment]
Have logged the crashes over the last 48 hours as timestamps:
Nov 25 18:13:10 
Nov 26 02:40:51 
Nov 26 10:48:13 
Nov 27 05:56:12 
Nov 27 10:45:37 

Wallet is not syncing.

**Comment by unintended-consequences** [comment]
Still getting the same errors, still crashing 2-3 times a day. Here is a grep of the last 600 lines in the log:

`2022-12-01T10:20:41.415 full_node full_node_server        : ERROR    Exception Trying to connect to a peer ({'host': '84.72.86.47', 'port': 8444}) with the same peer_id: 2f087e99ff5d70cf3337ba3ed693de149123a7ecf591e6f79ae27facda6a4690, exception Stack: Traceback (most recent call last):
2022-12-01T10:20:46.499 full_node asyncio                 : ERROR    Task exception was never retrieved
2022-12-01T10:20:47.897 full_node full_node_server        : ERROR    Exception Trying to connect to a peer ({'host': '222.244.76.110', 'port': 8444}) with the same peer_id: 2f087e99ff5d70cf3337ba3ed693de149123a7ecf591e6f79ae27facda6a4690, exception Stack: Traceback (most recent call last):
2022-12-01T10:20:50.433 full_node asyncio                 : ERROR    Task exception was never retrieved
2022-12-01T10:20:51.645 full_node full_node_server        : ERROR    Exception Trying to connect to a peer ({'host': '176.107.253.4', 'port': 8444}) with the same peer_id: 2f087e99ff5d70cf3337ba3ed693de149123a7ecf591e6f79ae27facda6a4690, exception Stack: Traceback (most recent call last):
2022-12-01T10:20:54.564 full_node asyncio                 : ERROR    Task exception was never retrieved
2022-12-01T10:20:58.434 full_node asyncio                 : ERROR    Task exception was never retrieved
2022-12-01T10:20:59.312 full_node full_node_server        : ERROR    Exception Trying to connect to a peer ({'host': '189.113.51.215', 'port': 8444}) with the same peer_id: 2f087e99ff5d70cf3337ba3ed693de149123a7ecf591e6f79ae27facda6a4690, exception Stack: Traceback (most recent call last):
2022-12-01T10:21:03.098 full_node full_node_server        : ERROR    Exception Trying to connect to a peer ({'host': '159.196.153.235', 'port': 8444}) with the same peer_id: 2f087e99ff5d70cf3337ba3ed693de149123a7ecf591e6f79ae27facda6a4690, exception Stack: Traceback (most recent call last):
2022-12-01T10:21:06.434 full_node asyncio                 : ERROR    Task exception was never retrieved
2022-12-01T10:21:08.166 full_node full_node_server        : ERROR    Exception Trying to connect to a peer ({'host': '222.67.139.29', 'port': 8444}) with the same peer_id: 2f087e99ff5d70cf3337ba3ed693de149123a7ecf591e6f79ae27facda6a4690, exception Stack: Traceback (most recent call last):`

**Comment by wallentx** [comment]
Have you checked your system logs to see if you had any OOM (Out Of Memory) events? How much ram does your device have?
Do you have zswap set up? That may help.

**Comment by unintended-consequences** [comment]
Some troubleshooting I have done:

```chia db validate```
145 orphaned blocks but `DATABASE IS VALID`.

I am running Ubuntu 20.04.5 LTS, zswap is enabled by default. Confirmed with `CONFIG_ZSWAP=y` in my /boot/config-5.10.103+ file.

My Rock 4B has 4GB of RAM soldered on. No other programs are running except chia natively. rsyslog was not installed, so I just installed it, and will wait for next reboot to check logs. Thanks for pointer @wallentx 

`free -h` consistently shows 2.0G or more as available.

**Comment by unintended-consequences** [comment]
Completed `sqlite3 /home/pi/.chia/mainnet/db/blockchain_v2_mainnet.sqlite "PRAGMA integrity_check"` - database is ok. Still monitoring RAM, have not seen any OOM notifications in the log yet.

**Comment by unintended-consequences** [comment]
Huh. I'm not seeing any OOM in the syslog but this ntpd error occurred just before the most recent crash:

```Dec  5 04:48:39 rock01 ntpd[829]: receive: Unexpected origin timestamp 0xe7377ed0.54ff363c does not match aorg 0000000000.00000000 from server@210.23.25.77 xmt 0xe7378627.508ace24
Dec  5 04:48:39 rock01 ntpd[829]: receive: Unexpected origin timestamp 0xe7377ed0.551235da does not match aorg 0000000000.00000000 from server@128.199.243.248 xmt 0xe7378627.50db7438
Dec  5 04:48:39 rock01 ntpd[829]: receive: Unexpected origin timestamp 0xe7377ed0.5515f8aa does not match aorg 0000000000.00000000 from server@91.206.8.36 xmt 0xe7378627.65cbe1bd
Dec  5 04:48:39 rock01 ntpd[829]: receive: Unexpected origin timestamp 0xe7377ed0.551d5b7d does not match aorg 0000000000.00000000 from server@142.147.88.111 xmt 0xe7378627.68cbda34```

**Comment by unintended-consequences** [comment]
Two conclusions:
1. It was the host that was crashing / rebooting, not chia. 
2. Wallet not syncing was fixed by this comment:

https://www.reddit.com/r/chia/comments/w9lxb0/comment/ihzc40v/

Basically changed `connect_to_unknown_peers` to false in config.yaml and wallet synced instantly after weeks of no sync.

**Comment by emlowe** [comment]
Unclear if there is anything to fix related to this bug.
On the pi, sometimes the local node can be slow to respond, so the wallet will then reach out to remote nodes. We do hope to make some improvements here, but the `connect_to_unknown_peers` is a valid workaround

Closing issue. Please comment/re-open if there is something further
