### ISSUE TITLE
[Bug] Stuck on "Loading keyring status"

### ISSUE THREAD

**Issue by Sudodoc** [Chia-Network/chia-blockchain#14009]
### What happened?

![2022-11-27_chia](https://user-images.githubusercontent.com/118838242/204125944-a86d1415-9e43-4845-b2cc-e4f03128e25c.png)

OS: LMDE 5 (elsie) x86_64
Kernel: 6.0.0-0.deb11.2-amd64

:~$ chia start wallet
Daemon not started yet
Starting daemon
Traceback (most recent call last):
  File "chia/cmds/chia.py", line 140, in <module>
  File "chia/cmds/chia.py", line 136, in main
  File "click/core.py", line 1130, in __call__
  File "click/core.py", line 1055, in main
  File "click/core.py", line 1657, in invoke
  File "click/core.py", line 1404, in invoke
  File "click/core.py", line 760, in invoke
  File "click/decorators.py", line 26, in new_func
  File "chia/cmds/chia.py", line 112, in run_daemon_cmd
  File "asyncio/runners.py", line 44, in run
  File "asyncio/base_events.py", line 616, in run_until_complete
  File "chia/daemon/server.py", line 1442, in async_run_daemon
  File "chia/daemon/server.py", line 175, in start
  File "chia/util/network.py", line 46, in create
  File "aiohttp/web_runner.py", line 121, in start
  File "asyncio/base_events.py", line 1463, in create_server
OSError: [Errno 99] error while attempting to bind on address ('::1', 55400, 0, 0): cannot assign requested address
[11447] Failed to execute script 'chia' due to unhandled exception!
Daemon not started yet
Failed to create the chia daemon

### Version

1.7.0-b2

### What platform are you using?

Linux

### What ui mode are you using?

GUI

**Comment by Lipat381** [comment]
Ошибка ...уже около месяца, что можно сделать ? 
![2022-11-28_11-30-15](https://user-images.githubusercontent.com/119286578/204219805-d1bf43cf-ef64-4d6b-8df8-97091b773196.png)

**Comment by emlowe** [comment]
Something is using port 55400 on your machine preventing Chia from using it. You can use `lsof -i -P -n` to check what process is using the port.
