### ISSUE TITLE
ERROR    Error while adding block

### ISSUE THREAD

**Issue by diowil** [Chia-Network/chia-blockchain#14044]
### What happened?

It works fine for couple of minutes and then suddenly:
ERROR    Error while adding block
I have to restor it from backup start it again and again ...

### Version

1.6.1

### What platform are you using?

Linux

### What ui mode are you using?

CLI

### Relevant log output

```shell
2022-12-02T00:01:56.413 full_node chia.full_node.full_node: INFO     Added blocks 1615207 to 1615239
2022-12-02T00:02:03.044 full_node chia.full_node.full_node: INFO     Added blocks 1615239 to 1615271
2022-12-02T00:02:07.586 full_node chia.full_node.full_node: INFO     Added blocks 1615271 to 1615303
2022-12-02T00:02:13.721 full_node chia.full_node.full_node: INFO     Added blocks 1615303 to 1615335
2022-12-02T00:02:19.357 full_node chia.full_node.full_node: INFO     Added blocks 1615335 to 1615367
2022-12-02T00:02:25.262 full_node chia.full_node.full_node: INFO     Added blocks 1615367 to 1615399
2022-12-02T00:02:29.343 full_node chia.full_node.full_node: INFO     Added blocks 1615399 to 1615431
2022-12-02T00:02:34.975 full_node chia.full_node.full_node: INFO     Added blocks 1615431 to 1615463
2022-12-02T00:02:39.110 full_node chia.full_node.full_node: INFO     Added blocks 1615463 to 1615495
2022-12-02T00:02:45.732 full_node chia.full_node.full_node: INFO     Added blocks 1615495 to 1615527
2022-12-02T00:02:47.331 full_node full_node_server        : WARNING  Rate limiting ourselves. message type: respond_peers, peer: 193.237.84.48
2022-12-02T00:02:50.442 full_node chia.consensus.blockchain: ERROR    Error while adding block df0cb04afda03dcd6117e4d8584f584578b0457fa0264d29350289623dc0b01b height 1615549, rolling back: Traceback (most recent call last):
  File "chia/consensus/blockchain.py", line 270, in receive_block
  File "chia/consensus/blockchain.py", line 406, in _reconsider_peak
  File "chia/full_node/coin_store.py", line 157, in new_block
  File "chia/full_node/coin_store.py", line 545, in _add_coin_records
  File "aiosqlite/core.py", line 210, in executemany
  File "aiosqlite/core.py", line 129, in _execute
  File "aiosqlite/core.py", line 102, in run
sqlite3.DatabaseError: database disk image is malformed
 database disk image is malformed
2022-12-02T00:02:50.448 full_node chia.full_node.full_node: ERROR    sync from fork point failed err: database disk image is malformed
2022-12-02T00:02:50.448 full_node chia.full_node.full_node: INFO     long sync done
2022-12-02T00:02:50.449 full_node chia.full_node.full_node: INFO     🌱 Updated peak to height 1615548, weight 3367948016, hh dc8c8957474c674b18781a9280aa25c4d2d176d5da596694051980aa2fe710cc, forked at 1615547, rh: 22fb5bcf69322ac8dc10301ccec6fd395e1f0fda12bcc2b24653e5232f8433e1, total iters: 6294424746084, overflow: False, deficit: 15, difficulty: 2496, sub slot iters: 134217728, Generator size: No tx, Generator ref list size: No tx
2022-12-02T00:02:50.453 full_node chia.full_node.weight_proof: INFO     create weight proof peak dc8c8957474c674b18781a9280aa25c4d2d176d5da596694051980aa2fe710cc 1615548
2022-12-02T00:02:50.523 full_node chia.full_node.weight_proof: INFO     recent chain, start: 1615117 end:  1615548 
2022-12-02T00:02:52.219 full_node asyncio                 : ERROR    Task was destroyed but it is pending!
task: <Task pending name='Task-726' coro=<FullNode.sync_from_fork_point.<locals>.fetch_block_batches() running at chia/full_node/full_node.py:1130> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7f9728d75c70>()]> cb=[gather.<locals>._done_callback() at asyncio/tasks.py:769]>
```

**Comment by diowil** [comment]
I messed up with my databse backup where I had blockchain V1 version.  When I tried to do chia db upgrade it ended up with database malform. So I decided to sync all over again.
