### ISSUE TITLE
[Bug] Unsure about errors in logs

### ISSUE THREAD

**Issue by neo57500** [Chia-Network/chia-blockchain#14053]
### What happened?

2022-12-05T07:42:39.645 full_node full_node_server        : WARNING  Banning 172.88.78.26 for 10 seconds
2022-12-05T07:42:39.646 full_node full_node_server        : ERROR    Exception: Failed to fetch block 2918845 from {'host': '172.88.78.26', 'port': 8444}, timed out, {'host': '172.88.78.26', 'port': 8444}. Traceback (most recent call last):
  File "chia/server/server.py", line 624, in wrapped_coroutine
  File "chia/full_node/full_node_api.py", line 128, in new_peak
  File "chia/full_node/full_node.py", line 729, in new_peak
  File "chia/full_node/full_node.py", line 649, in short_sync_backtrack
ValueError: Failed to fetch block 2918845 from {'host': '172.88.78.26', 'port': 8444}, timed out

2022-12-05T07:42:39.647 full_node full_node_server        : ERROR    Exception: Failed to fetch block 2918845 from {'host': '172.88.78.26', 'port': 8444}, timed out <class 'ValueError'>, closing connection {'host': '172.88.78.26', 'port': 8444}. Traceback (most recent call last):
  File "chia/server/server.py", line 634, in api_call
  File "asyncio/tasks.py", line 455, in wait_for
  File "chia/server/server.py", line 624, in wrapped_coroutine
  File "chia/full_node/full_node_api.py", line 128, in new_peak
  File "chia/full_node/full_node.py", line 729, in new_peak
  File "chia/full_node/full_node.py", line 649, in short_sync_backtrack
ValueError: Failed to fetch block 2918845 from {'host': '172.88.78.26', 'port': 8444}, timed out

### Version

1.7.0b3

### What platform are you using?

Linux

### What ui mode are you using?

GUI

### Relevant log output

```shell
2022-12-05T07:42:39.645 full_node full_node_server        : WARNING  Banning 172.88.78.26 for 10 seconds
2022-12-05T07:42:39.646 full_node full_node_server        : ERROR    Exception: Failed to fetch block 2918845 from {'host': '172.88.78.26', 'port': 8444}, timed out, {'host': '172.88.78.26', 'port': 8444}. Traceback (most recent call last):
  File "chia/server/server.py", line 624, in wrapped_coroutine
  File "chia/full_node/full_node_api.py", line 128, in new_peak
  File "chia/full_node/full_node.py", line 729, in new_peak
  File "chia/full_node/full_node.py", line 649, in short_sync_backtrack
ValueError: Failed to fetch block 2918845 from {'host': '172.88.78.26', 'port': 8444}, timed out

2022-12-05T07:42:39.647 full_node full_node_server        : ERROR    Exception: Failed to fetch block 2918845 from {'host': '172.88.78.26', 'port': 8444}, timed out <class 'ValueError'>, closing connection {'host': '172.88.78.26', 'port': 8444}. Traceback (most recent call last):
  File "chia/server/server.py", line 634, in api_call
  File "asyncio/tasks.py", line 455, in wait_for
  File "chia/server/server.py", line 624, in wrapped_coroutine
  File "chia/full_node/full_node_api.py", line 128, in new_peak
  File "chia/full_node/full_node.py", line 729, in new_peak
  File "chia/full_node/full_node.py", line 649, in short_sync_backtrack
ValueError: Failed to fetch block 2918845 from {'host': '172.88.78.26', 'port': 8444}, timed out
```

**Comment by GitHubUser1711** [comment]
What happened?

Caught plotting error: Matches do not match with number of write entries 4294612913 4294612057
Traceback (most recent call last):
  File "chia\cmds\chia.py", line 135, in <module>
  File "chia\cmds\chia.py", line 131, in main
  File "click\core.py", line 1130, in __call__
  File "click\core.py", line 1055, in main
  File "click\core.py", line 1657, in invoke
  File "click\core.py", line 1404, in invoke
  File "click\core.py", line 760, in invoke
  File "click\decorators.py", line 26, in new_func
  File "chia\cmds\plotters.py", line 17, in plotters_cmd
  File "chia\plotters\plotters.py", line 464, in call_plotters
  File "chia\plotters\chiapos.py", line 56, in plot_chia
  File "asyncio\runners.py", line 44, in run
  File "asyncio\base_events.py", line 647, in run_until_complete
  File "chia\plotting\create_plots.py", line 229, in create_plots
RuntimeError: Unknown exception
[23812] Failed to execute script 'chia' due to unhandled exception!

Version

1.61 and 1.7.0rc2-dev8

What Platform are you using?

Windows 10 x64

**Comment by wallentx** [comment]
Your node will automatically connect to peers, and if they don't respond in time, the result of your logs is what you will see. Our logs might print out a bit more information than is really needed for these events. Is there a specific issue that you were encountering?

**Comment by emlowe** [comment]
Closed due to lack of response
