### ISSUE TITLE
Plotting Issue What happened?

### ISSUE THREAD

**Issue by wallentx** [Chia-Network/chia-blockchain#14098]
What happened?

Caught plotting error: Matches do not match with number of write entries 4294612913 4294612057
Traceback (most recent call last):
  File "chia\cmds\chia.py", line 135, in <module>
  File "chia\cmds\chia.py", line 131, in main
  File "click\core.py", line 1130, in __call__
  File "click\core.py", line 1055, in main
  File "click\core.py", line 1657, in invoke
  File "click\core.py", line 1404, in invoke
  File "click\core.py", line 760, in invoke
  File "click\decorators.py", line 26, in new_func
  File "chia\cmds\plotters.py", line 17, in plotters_cmd
  File "chia\plotters\plotters.py", line 464, in call_plotters
  File "chia\plotters\chiapos.py", line 56, in plot_chia
  File "asyncio\runners.py", line 44, in run
  File "asyncio\base_events.py", line 647, in run_until_complete
  File "chia\plotting\create_plots.py", line 229, in create_plots
RuntimeError: Unknown exception
[23812] Failed to execute script 'chia' due to unhandled exception!

Version

1.61 and 1.7.0rc2-dev8

What Platform are you using?

Windows 10 x64

_Originally posted by @GitHubUser1711 in https://github.com/Chia-Network/chia-blockchain/issues/14053#issuecomment-1340288291_

**Comment by wallentx** [comment]
@GitHubUser1711 are you seeing this issue every time when you make a plot? Can you share the plot create arguments that you were using?

**Comment by GitHubUser1711** [comment]
Yes, started happening a few days ago, every plot since then on 2 different computers using both stable and dev releases.

Plotter: Chia Proof of Space 1.0.11
Plot Size: 101.4GiB
Plot Count: From 1 to 15
Plot in Parallel
Number of threads: 4
Temporary folder location: SSD
Final Directory: HDD

**Comment by GitHubUser1711** [comment]
Hi, I have used 2 HDDs instead, and it is working again on latest dev35 build.  Possibly something wrong with my 2 SSDs.

**Comment by GitHubUser1711** [comment]
Now working on SSDs again.  After more testing, I have now found what I believe was the problem.

From the beginning I have changed Number of Threads from default 2 to 4, which worked up until a week ago.  Leaving it as default 2, plotting is now working normally again for anyone else having the same issue.
