### ISSUE TITLE
sending TXCH and CATS with memos on CLI

### ISSUE THREAD

**Issue by wallentx** [Chia-Network/chia-blockchain#14119]
```
Submitting transaction...
Exception from 'wallet' {'error': 'non-hexadecimal number found in fromhex() arg at position 0', 'success': False}:
Traceback (most recent call last):
  File "/home/william/wsrc/pool-reference/venv/lib/python3.10/site-packages/chia/cmds/cmds_util.py", line 100, in get_any_service_client
    yield node_client, config, fingerprint
  File "/home/william/wsrc/pool-reference/venv/lib/python3.10/site-packages/chia/cmds/cmds_util.py", line 211, in execute_with_wallet
    await function(extra_params, wallet_client, new_fp)
  File "/home/william/wsrc/pool-reference/venv/lib/python3.10/site-packages/chia/cmds/wallet_funcs.py", line 240, in send
    res = await wallet_client.cat_spend(
  File "/home/william/wsrc/pool-reference/venv/lib/python3.10/site-packages/chia/rpc/wallet_rpc_client.py", line 655, in cat_spend
    res = await self.fetch("cat_spend", send_dict)
  File "/home/william/wsrc/pool-reference/venv/lib/python3.10/site-packages/chia/rpc/rpc_client.py", line 50, in fetch
    raise ValueError(res_json)
ValueError: {'error': 'non-hexadecimal number found in fromhex() arg at position 0', 'success': False}
```

Should be fixed with https://github.com/Chia-Network/chia-blockchain/pull/14100

**Comment by wallentx** [comment]
The error is indeed gone, but there are some strange issues with sending CATS in general via the CLI - https://github.com/Chia-Network/chia-blockchain/issues/14118
