### ISSUE TITLE
Unable to enter[Bug] 

### ISSUE THREAD

**Issue by petercat80** [Chia-Network/chia-blockchain#14201]
### What happened?

Double click the program icon and you will never be able to enter
![image](https://user-images.githubusercontent.com/121129271/208752273-6395794a-ba2c-4f64-ae68-a78c2ed81bf0.png)

### Version

1.6.1

### What platform are you using?

Windows

### What ui mode are you using?

GUI

### Relevant log output

```shell
2022-12-15T12:16:25.118 daemon asyncio                    : ERROR    Accept failed on a socket
socket: <asyncio.TransportSocket fd=252, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 55400)>
Traceback (most recent call last):
  File "asyncio\proactor_events.py", line 819, in loop
  File "asyncio\windows_events.py", line 817, in _poll
  File "asyncio\windows_events.py", line 566, in finish_accept
OSError: [WinError 10014] 系统检测到在一个调用中尝试使用指针参数时的无效指针地址。
2022-12-15T12:16:25.120 daemon asyncio                    : ERROR    Task exception was never retrieved
future: <Task finished name='Task-4' coro=<IocpProactor.accept.<locals>.accept_coro() done, defined at asyncio\windows_events.py:568> exception=OSError(14, '系统检测到在一个调用中尝试使用指针参数时的无效指针地址。', None, 10014, None)>
Traceback (most recent call last):
  File "asyncio\windows_events.py", line 571, in accept_coro
  File "asyncio\proactor_events.py", line 819, in loop
  File "asyncio\windows_events.py", line 817, in _poll
  File "asyncio\windows_events.py", line 566, in finish_accept
OSError: [WinError 10014] 系统检测到在一个调用中尝试使用指针参数时的无效指针地址。
2022-12-15T20:02:11.770 daemon asyncio                    : ERROR    Accept failed on a socket
socket: <asyncio.TransportSocket fd=1180, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 55400)>
Traceback (most recent call last):
  File "asyncio\proactor_events.py", line 819, in loop
  File "asyncio\windows_events.py", line 817, in _poll
  File "asyncio\windows_events.py", line 566, in finish_accept
OSError: [WinError 10014] 系统检测到在一个调用中尝试使用指针参数时的无效指针地址。
2022-12-15T20:02:11.772 daemon asyncio                    : ERROR    Task exception was never retrieved
future: <Task finished name='Task-4' coro=<IocpProactor.accept.<locals>.accept_coro() done, defined at asyncio\windows_events.py:568> exception=OSError(14, '系统检测到在一个调用中尝试使用指针参数时的无效指针地址。', None, 10014, None)>
Traceback (most recent call last):
  File "asyncio\windows_events.py", line 571, in accept_coro
  File "asyncio\proactor_events.py", line 819, in loop
  File "asyncio\windows_events.py", line 817, in _poll
  File "asyncio\windows_events.py", line 566, in finish_accept
OSError: [WinError 10014] 系统检测到在一个调用中尝试使用指针参数时的无效指针地址。
2022-12-16T06:32:22.500 daemon asyncio                    : ERROR    Accept failed on a socket
socket: <asyncio.TransportSocket fd=1032, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 55400)>
Traceback (most recent call last):
  File "asyncio\proactor_events.py", line 819, in loop
  File "asyncio\windows_events.py", line 817, in _poll
  File "asyncio\windows_events.py", line 566, in finish_accept
OSError: [WinError 10014] 系统检测到在一个调用中尝试使用指针参数时的无效指针地址。
2022-12-16T06:32:22.502 daemon asyncio                    : ERROR    Task exception was never retrieved
future: <Task finished name='Task-3' coro=<IocpProactor.accept.<locals>.accept_coro() done, defined at asyncio\windows_events.py:568> exception=OSError(14, '系统检测到在一个调用中尝试使用指针参数时的无效指针地址。', None, 10014, None)>
Traceback (most recent call last):
  File "asyncio\windows_events.py", line 571, in accept_coro
  File "asyncio\proactor_events.py", line 819, in loop
  File "asyncio\windows_events.py", line 817, in _poll
  File "asyncio\windows_events.py", line 566, in finish_accept
OSError: [WinError 10014] 系统检测到在一个调用中尝试使用指针参数时的无效指针地址。
2022-12-16T06:37:05.829 daemon asyncio                    : ERROR    Accept failed on a socket
socket: <asyncio.TransportSocket fd=848, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 55400)>
Traceback (most recent call last):
  File "asyncio\proactor_events.py", line 819, in loop
  File "asyncio\windows_events.py", line 817, in _poll
  File "asyncio\windows_events.py", line 566, in finish_accept
OSError: [WinError 10014] 系统检测到在一个调用中尝试使用指针参数时的无效指针地址。
2022-12-16T06:37:05.830 daemon asyncio                    : ERROR    Task exception was never retrieved
future: <Task finished name='Task-3' coro=<IocpProactor.accept.<locals>.accept_coro() done, defined at asyncio\windows_events.py:568> exception=OSError(14, '系统检测到在一个调用中尝试使用指针参数时的无效指针地址。', None, 10014, None)>
Traceback (most recent call last):
  File "asyncio\windows_events.py", line 571, in accept_coro
  File "asyncio\proactor_events.py", line 819, in loop
  File "asyncio\windows_events.py", line 817, in _poll
  File "asyncio\windows_events.py", line 566, in finish_accept
OSError: [WinError 10014] 系统检测到在一个调用中尝试使用指针参数时的无效指针地址。
2022-12-16T06:38:36.381 daemon asyncio                    : ERROR    Accept failed on a socket
socket: <asyncio.TransportSocket fd=1068, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 55400)>
Traceback (most recent call last):
  File "asyncio\proactor_events.py", line 819, in loop
  File "asyncio\windows_events.py", line 817, in _poll
  File "asyncio\windows_events.py", line 566, in finish_accept
OSError: [WinError 10014] 系统检测到在一个调用中尝试使用指针参数时的无效指针地址。
2022-12-16T06:38:36.383 daemon asyncio                    : ERROR    Task exception was never retrieved
future: <Task finished name='Task-4' coro=<IocpProactor.accept.<locals>.accept_coro() done, defined at asyncio\windows_events.py:568> exception=OSError(14, '系统检测到在一个调用中尝试使用指针参数时的无效指针地址。', None, 10014, None)>
Traceback (most recent call last):
  File "asyncio\windows_events.py", line 571, in accept_coro
  File "asyncio\proactor_events.py", line 819, in loop
  File "asyncio\windows_events.py", line 817, in _poll
  File "asyncio\windows_events.py", line 566, in finish_accept
OSError: [WinError 10014] 系统检测到在一个调用中尝试使用指针参数时的无效指针地址。
2022-12-17T15:52:19.260 daemon asyncio                    : ERROR    Accept failed on a socket
socket: <asyncio.TransportSocket fd=1004, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 55400)>
Traceback (most recent call last):
  File "asyncio\proactor_events.py", line 819, in loop
  File "asyncio\windows_events.py", line 817, in _poll
  File "asyncio\windows_events.py", line 566, in finish_accept
OSError: [WinError 10014] 系统检测到在一个调用中尝试使用指针参数时的无效指针地址。
2022-12-17T15:52:19.262 daemon asyncio                    : ERROR    Task exception was never retrieved
future: <Task finished name='Task-3' coro=<IocpProactor.accept.<locals>.accept_coro() done, defined at asyncio\windows_events.py:568> exception=OSError(14, '系统检测到在一个调用中尝试使用指针参数时的无效指针地址。', None, 10014, None)>
Traceback (most recent call last):
  File "asyncio\windows_events.py", line 571, in accept_coro
  File "asyncio\proactor_events.py", line 819, in loop
  File "asyncio\windows_events.py", line 817, in _poll
  File "asyncio\windows_events.py", line 566, in finish_accept
OSError: [WinError 10014] 系统检测到在一个调用中尝试使用指针参数时的无效指针地址。
2022-12-20T13:20:51.696 daemon asyncio                    : ERROR    Accept failed on a socket
socket: <asyncio.TransportSocket fd=1020, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 55400)>
Traceback (most recent call last):
  File "asyncio\proactor_events.py", line 819, in loop
  File "asyncio\windows_events.py", line 817, in _poll
  File "asyncio\windows_events.py", line 566, in finish_accept
OSError: [WinError 10014] 系统检测到在一个调用中尝试使用指针参数时的无效指针地址。
2022-12-20T13:20:51.698 daemon asyncio                    : ERROR    Task exception was never retrieved
future: <Task finished name='Task-4' coro=<IocpProactor.accept.<locals>.accept_coro() done, defined at asyncio\windows_events.py:568> exception=OSError(14, '系统检测到在一个调用中尝试使用指针参数时的无效指针地址。', None, 10014, None)>
Traceback (most recent call last):
  File "asyncio\windows_events.py", line 571, in accept_coro
  File "asyncio\proactor_events.py", line 819, in loop
  File "asyncio\windows_events.py", line 817, in _poll
  File "asyncio\windows_events.py", line 566, in finish_accept
OSError: [WinError 10014] 系统检测到在一个调用中尝试使用指针参数时的无效指针地址。
2022-12-21T03:30:24.571 daemon asyncio                    : ERROR    Accept failed on a socket
socket: <asyncio.TransportSocket fd=1028, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 55400)>
Traceback (most recent call last):
  File "asyncio\proactor_events.py", line 819, in loop
  File "asyncio\windows_events.py", line 817, in _poll
  File "asyncio\windows_events.py", line 566, in finish_accept
OSError: [WinError 10014] 系统检测到在一个调用中尝试使用指针参数时的无效指针地址。
2022-12-21T03:30:24.574 daemon asyncio                    : ERROR    Task exception was never retrieved
future: <Task finished name='Task-4' coro=<IocpProactor.accept.<locals>.accept_coro() done, defined at asyncio\windows_events.py:568> exception=OSError(14, '系统检测到在一个调用中尝试使用指针参数时的无效指针地址。', None, 10014, None)>
Traceback (most recent call last):
  File "asyncio\windows_events.py", line 571, in accept_coro
  File "asyncio\proactor_events.py", line 819, in loop
  File "asyncio\windows_events.py", line 817, in _poll
  File "asyncio\windows_events.py", line 566, in finish_accept
OSError: [WinError 10014] 系统检测到在一个调用中尝试使用指针参数时的无效指针地址。
```

**Comment by petercat80** [comment]
He is always in LOADING for almost 30 hours

![image](https://user-images.githubusercontent.com/121129271/208752418-994cb04d-614b-407b-9cdf-8aa3e408e8e8.png)

**Comment by emlowe** [comment]
This is almost certainly because Windows has reserved the daemon port of 55400.

You can either change the default port in config.yaml - or you can configure windows to not reserve this port

```
- disable hyper-v: dism.exe /Online /Disable-Feature:Microsoft-Hyper-V, reboot
- reserve the ports yourself: netsh int ipv4 add excludedportrange protocol=tcp startport=55300 numberofports=200 , reboot (can reserver fewer ports if you want)
- enable hyper-v: dism.exe /Online /Enable-Feature:Microsoft-Hyper-V /All, reboot
```
