### ISSUE TITLE
 ERROR    Exception: Failed to fetch block 2997788 from 

### ISSUE THREAD

**Issue by neo57500** [Chia-Network/chia-blockchain#14219]
### What happened?

2022-12-22T07:07:46.569 full_node full_node_server        : ERROR    Exception: Failed to fetch block 2997788 from PeerInfo(host='213.172.238.227', port=8444), timed out, PeerInfo(host='213.172.238.227', port=8444). Traceback (most recent call last):
  File "chia/server/ws_connection.py", line 376, in wrapped_coroutine
  File "chia/full_node/full_node_api.py", line 133, in new_peak
  File "chia/full_node/full_node.py", line 737, in new_peak
  File "chia/full_node/full_node.py", line 655, in short_sync_backtrack
ValueError: Failed to fetch block 2997788 from PeerInfo(host='213.172.238.227', port=8444), timed out

### Version

1.7.0b4

### What platform are you using?

Linux

### What ui mode are you using?

GUI

### Relevant log output

```shell
2022-12-22T07:07:46.569 full_node full_node_server        : ERROR    Exception: Failed to fetch block 2997788 from PeerInfo(host='213.172.238.227', port=8444), timed out, PeerInfo(host='213.172.238.227', port=8444). Traceback (most recent call last):
  File "chia/server/ws_connection.py", line 376, in wrapped_coroutine
  File "chia/full_node/full_node_api.py", line 133, in new_peak
  File "chia/full_node/full_node.py", line 737, in new_peak
  File "chia/full_node/full_node.py", line 655, in short_sync_backtrack
ValueError: Failed to fetch block 2997788 from PeerInfo(host='213.172.238.227', port=8444), timed out
```

**Comment by MumfMeisterT** [comment]
It is normal in peer to peer networks to have network issues.
