### ISSUE TITLE
[Bug] Ping errors in Daemon

### ISSUE THREAD

**Issue by neo57500** [Chia-Network/chia-blockchain#14226]
### What happened?

2022-12-22T20:10:21.497 daemon __main__                   : ERROR    Ping error
Traceback (most recent call last):
  File "chia/daemon/server.py", line 283, in ping_task
  File "aiohttp/web_ws.py", line 295, in ping
  File "aiohttp/http_websocket.py", line 676, in ping
  File "aiohttp/http_websocket.py", line 653, in _send_frame
  File "aiohttp/http_websocket.py", line 663, in _write
ConnectionResetError: Cannot write to closing transport
2022-12-22T20:11:38.996 harvester harvester_server        : WARNING  Cannot write to closing transport 127.0.0.1
2022-12-22T20:11:39.027 daemon __main__                   : ERROR    Ping failed, connection closed.
2022-12-22T20:11:39.317 daemon aiohttp.server             : ERROR    Error handling request
Traceback (most recent call last):
  File "aiohttp/web_protocol.py", line 433, in _handle_request
  File "aiohttp/web_app.py", line 504, in _handle
  File "chia/daemon/server.py", line 224, in incoming_connection
  File "aiohttp/web_ws.py", line 444, in receive
  File "aiohttp/web_ws.py", line 301, in pong
  File "aiohttp/http_websocket.py", line 670, in pong
  File "aiohttp/http_websocket.py", line 653, in _send_frame
  File "aiohttp/http_websocket.py", line 663, in _write
ConnectionResetError: Cannot write to closing transport

### Version

1.7.0b4

### What platform are you using?

Linux

### What ui mode are you using?

GUI

### Relevant log output

```shell
2022-12-22T20:10:21.497 daemon __main__                   : ERROR    Ping error
Traceback (most recent call last):
  File "chia/daemon/server.py", line 283, in ping_task
  File "aiohttp/web_ws.py", line 295, in ping
  File "aiohttp/http_websocket.py", line 676, in ping
  File "aiohttp/http_websocket.py", line 653, in _send_frame
  File "aiohttp/http_websocket.py", line 663, in _write
ConnectionResetError: Cannot write to closing transport
2022-12-22T20:11:38.996 harvester harvester_server        : WARNING  Cannot write to closing transport 127.0.0.1
2022-12-22T20:11:39.027 daemon __main__                   : ERROR    Ping failed, connection closed.
2022-12-22T20:11:39.317 daemon aiohttp.server             : ERROR    Error handling request
Traceback (most recent call last):
  File "aiohttp/web_protocol.py", line 433, in _handle_request
  File "aiohttp/web_app.py", line 504, in _handle
  File "chia/daemon/server.py", line 224, in incoming_connection
  File "aiohttp/web_ws.py", line 444, in receive
  File "aiohttp/web_ws.py", line 301, in pong
  File "aiohttp/http_websocket.py", line 670, in pong
  File "aiohttp/http_websocket.py", line 653, in _send_frame
  File "aiohttp/http_websocket.py", line 663, in _write
ConnectionResetError: Cannot write to closing transport
```

**Comment by MumfMeisterT** [comment]
Have you received this issue multiple times? Restarting will usually fix this issue. - We currently have a PR that should improve this issue moving forward.

**Comment by emlowe** [comment]
If you are seeing this commonly - you could try the build from the following PR: https://github.com/Chia-Network/chia-blockchain/pull/13886

This increases the timeout for pings to 300, as well as makes it configurable for edge cases.
