### ISSUE TITLE
[Bug] Many bugs in wallet CLI + GUI since 1.6.1 release

### ISSUE THREAD

**Issue by mor** [Chia-Network/chia-blockchain#14225]
### What happened?

In previous versions I've had the occasional annoying glitch once or twice a week, but since the release of 1.6.1 it's pretty much a couple hours of downtime every day from the MANY different issues I'm having.

1. The wallet frequently decides to go through a lengthy resync. The GUI status light ping pongs from green to red on many simple transactions.
2. Resync can sometimes take a minute or two, but sometimes takes hours. Changing wallet keys is typically a 5 or 10 minute procedure, but sometimes more like 20 or 30 minutes.
3. When multiple transactions enter pending state at same time, it's a decent bet catastrophic problems will appear, including wallet corruption (out of balance) that will NEVER fix itself until deleting .sqlite db file and resync from scratch.
4. The GUI crashes frequently (a couple times a day). I send the crashpad reports it prompts for, no telling if anyone is looking at them on the Chia end. I also see once or twice a day, a white-screen crash without any messaging or reporting dialogs, that someone else opened a bug report on.
5. The 'Manage Token List' actions in GUI or CLI are very slow, and often result in a lengthy resync process. This is an old problem that seemed greatly improved in 1.6.0 but is now back to ultra-annoying status.
6. The worst thing that sometimes happens: after successfully accepting an offer that went pending, then confirmed, with all the relevant balances correct, if I subsequently change the key/fingerprint of the wallet, than come back, it resyncs but does not see the previously successful transaction and reports an invalid balance (as if the transaction DID NOT EVER HAPPEN). In some cases (every couple days) this problem will just not ever repair itself, claiming to be in sync with green light status, but just WRONG balances. I've waited in some cases for days, but the only way to fix is to delete the wallet .sqlite file and resync from scratch. This of course requires special handling for recreating CAT names and outstanding OFFERS, and sometimes bugs related to those actions further exacerbate the wallet stability fails turning this into an hours long, stressful process.

I've tried switching my wallet machine from an older server also running as a full_node. But no help--the current machine I'm testing with as a standalone wallet node, plots and runs games great, it's less than a year old.  I've tried every version released from 1.6.1 up through all the 1.7.0 bX and rcX and dev releases, including the latest 1.6.2 rc1... There are different flavors of issues from one to the next, but all of them struggle to provide any semblance of stable wallet performance. Going back to 1.6.0 fixes pretty much everything described here, but I am actually in need of the features introduced in 1.6.1 for CAT/NFT handling, so it's a quandry...

### Version

Currently 1.6.2 rc1

### What platform are you using?

Linux

### What ui mode are you using?

GUI

### Relevant log output

```shell
Under 1.6.2 rc1, I clicked on the selector of a CAT from 'Manage Token List' menu of the GUI, in order to turn it on for display, and the Wallet status light went from green to red and all the screens became unusable with circular twiddles for ~20 minutes. Here is a sample of some of the messaging in my log from those twenty minutes (this kind of thing, and more, goes on and on for thousands of lines during the resync--it confirms the balance of each wallet dozens, if not hundreds, of times during the resync):

2022-12-23T11:59:44.011 wallet chia.wallet.wallet_state_manager: INFO     Start: Creating puzzle hashes from 0 to 2382 for wallet_id: 22
2022-12-23T11:59:46.334 wallet chia.wallet.wallet_node    : INFO     new coin state received (11-20/ 28)
2022-12-23T11:59:47.389 wallet chia.wallet.wallet_state_manager: INFO     Done: Creating puzzle hashes from 0 to 2382 for wallet_id: 22 Time: 3.3793883323669434 seconds
2022-12-23T11:59:49.074 wallet chia.wallet.wallet_node    : INFO     new coin state received (21-28/ 28)
2022-12-23T11:59:52.922 wallet chia.wallet.wallet_node    : INFO     new coin state received (1-10/ 28)
2022-12-23T11:59:56.712 wallet chia.wallet.wallet_node    : INFO     new coin state received (21-23/ 23)
2022-12-23T11:59:56.715 wallet chia.wallet.wallet_node    : INFO     new coin state received (11-20/ 23)
2022-12-23T11:59:57.698 wallet chia.wallet.wallet_state_manager: INFO     Updating last used derivation index: 1882
2022-12-23T11:59:57.817 wallet chia.rpc.rpc_server        : WARNING  Error while handling message: Traceback (most recent call last):
  File "chia/rpc/rpc_server.py", line 329, in safe_handle
  File "chia/rpc/rpc_server.py", line 320, in ws_api
  File "chia/rpc/wallet_rpc_api.py", line 567, in create_new_wallet
ValueError: Wallet needs to be fully synced.

2022-12-23T11:59:57.818 wallet chia.rpc.rpc_server        : WARNING  Error while handling message: Traceback (most recent call last):
  File "chia/rpc/rpc_server.py", line 329, in safe_handle
  File "chia/rpc/rpc_server.py", line 320, in ws_api
  File "chia/rpc/wallet_rpc_api.py", line 567, in create_new_wallet
ValueError: Wallet needs to be fully synced.

2022-12-23T11:59:57.839 wallet chia.wallet.cat_wallet.cat_wallet: INFO     Confirmed balance for cat wallet 12 is 900000
2022-12-23T11:59:57.845 wallet chia.wallet.cat_wallet.cat_wallet: INFO     Confirmed balance for cat wallet 18 is 105760000
2022-12-23T11:59:57.850 wallet chia.wallet.cat_wallet.cat_wallet: INFO     Confirmed balance for cat wallet 21 is 0
2022-12-23T11:59:58.277 wallet chia.rpc.rpc_server        : WARNING  Error while handling message: Traceback (most recent call last):
  File "chia/rpc/rpc_server.py", line 329, in safe_handle
  File "chia/rpc/rpc_server.py", line 320, in ws_api
  File "chia/rpc/wallet_rpc_api.py", line 1323, in cat_set_name
KeyError: 'wallet_id'

2022-12-23T11:59:58.279 wallet chia.rpc.rpc_server        : WARNING  Error while handling message: Traceback (most recent call last):
  File "chia/rpc/rpc_server.py", line 329, in safe_handle
  File "chia/rpc/rpc_server.py", line 320, in ws_api
  File "chia/rpc/wallet_rpc_api.py", line 1323, in cat_set_name
KeyError: 'wallet_id'

2022-12-23T12:00:03.500 wallet chia.wallet.wallet_node    : INFO     new coin state received (1-10/ 23)
2022-12-23T12:00:08.304 wallet chia.wallet.cat_wallet.cat_wallet: INFO     Confirmed balance for cat wallet 21 is 0
2022-12-23T12:00:08.923 wallet chia.wallet.cat_wallet.cat_wallet: INFO     Confirmed balance for cat wallet 12 is 900000
2022-12-23T12:00:08.929 wallet chia.wallet.cat_wallet.cat_wallet: INFO     Confirmed balance for cat wallet 18 is 105760000
2022-12-23T12:00:08.935 wallet chia.wallet.cat_wallet.cat_wallet: INFO     Confirmed balance for cat wallet 21 is 0
2022-12-23T12:00:11.737 wallet chia.wallet.wallet_node    : INFO     new coin state received (11-15/ 15)
2022-12-23T12:00:19.081 wallet chia.wallet.cat_wallet.cat_wallet: INFO     Confirmed balance for cat wallet 21 is 0
2022-12-23T12:00:21.251 wallet chia.wallet.wallet_node    : INFO     new coin state received (1-10/ 15)
2022-12-23T12:00:29.095 wallet chia.wallet.cat_wallet.cat_wallet: INFO     Confirmed balance for cat wallet 21 is 0
2022-12-23T12:00:30.962 wallet chia.wallet.cat_wallet.cat_wallet: INFO     Confirmed balance for cat wallet 21 is 0
2022-12-23T12:00:39.940 wallet chia.wallet.wallet_node    : INFO     new coin state received (41-50/ 55)
2022-12-23T12:00:41.085 wallet chia.wallet.cat_wallet.cat_wallet: INFO     Confirmed balance for cat wallet 21 is 0
2022-12-23T12:00:47.992 wallet chia.wallet.wallet_node    : INFO     new coin state received (11-20/ 55)
2022-12-23T12:00:51.107 wallet chia.wallet.cat_wallet.cat_wallet: INFO     Confirmed balance for cat wallet 21 is 0
2022-12-23T12:00:58.284 wallet chia.wallet.wallet_node    : INFO     new coin state received (51-55/ 55)
2022-12-23T12:01:01.129 wallet chia.wallet.cat_wallet.cat_wallet: INFO     Confirmed balance for cat wallet 21 is 0
2022-12-23T12:01:04.274 wallet chia.wallet.wallet_node    : INFO     new coin state received (31-40/ 55)
2022-12-23T12:01:11.152 wallet chia.wallet.cat_wallet.cat_wallet: INFO     Confirmed balance for cat wallet 21 is 0
2022-12-23T12:01:13.432 wallet chia.wallet.wallet_node    : INFO     new coin state received (1-10/ 55)
2022-12-23T12:01:18.970 wallet chia.wallet.wallet_node    : INFO     new coin state received (21-30/ 55)
2022-12-23T12:01:21.169 wallet chia.wallet.cat_wallet.cat_wallet: INFO     Confirmed balance for cat wallet 21 is 0
```

**Comment by emlowe** [comment]
A few questions.

How many CATs and NFTs and overall wallets are we talking about ?.
Can you confirm that moving back to 1.6.0 and that version works better - this is surprising
Can you confirm that running a local node doesn't improve the situation - normally running a local node is expected to work better with larger wallets since there is less work to validate stuff

Can you give some more details on this: "I send the crashpad reports it prompts for, no telling if anyone is looking at them on the Chia end" - chia doesn't have any crash reporting built in, so we don't know where these crash reports might be going? Perhaps you can provide a screenshot of the dialog.

**Comment by mor** [comment]
Yes, 1.6.0 worked fine EXCEPT it couldn't accept offers created on 1.6.1 (which is a showstopper for me...). But it did not wallet-resync crazily or ever get wallet db corruption in response to making/accepting offers.  I am farming and pooling fine, these are all strictly wallet issues.  I am now on 1.6.2 and it is having similar problems to 1.6.1. Sometimes my wallet goes 'red' and begins a resync that can take HOURS before going green again. It's almost always in the wake of making/accepting offers, but sometimes it just seems to happen. It just finished 'syncing' after over an HOUR in the 'red' state that began this morning for no apparent reason.

I'm not a power user. I have 2 different wallet keys. Each one has a different set of CATs it tracks. One has 10 CATs and 2 NFTs, the other has 19 CATs and a bit more than 20 NFTs... I typically spend maybe an hour or so (in the wallet with NFTs), making/accepting anywhere from 5 to 20 offers per day--but at least twice as much of my time each day is lost waiting for the wallet to sync and get back to normal function. Sometimes (maybe not 50% of the time, but definitely more than 10% of the time) I can see an offer I created get accepted, go into pending, and then completed status at Dexie, while my GUI decides to resync, and not reflect the completed transaction for half-an-hour, a full-hour, or longer...

Previously to running the GUI wallet standalone on a fast computer, I ran the GUI on the same fast computer but in UI mode connected to a wallet node on my full_node box. There didn't seem to be any difference running either way: excessive/lengthy resync, out of balance, corruption issues that were happening on the full_node/wallet, also happened on the standalone wallet when I switched.  After seeing the problems right after upgrading to 1.6.1, I tried not using the GUI/UI, but only CLI control of the wallet, but that didn't avoid the problems either... Previously, I had run the GUI -> UI -> full_node/wallet model for a month or two on 1.6.0 with none of these problems. As far as I can see, all flavors of wallet configuration, in all versions of chia > 1.6.0 have these huge wallet/sync problems.

I'll follow up with a screen print of the crash dialog next time it happens. I will say I don't recall seeing a crash report dialog before 1.6.1, even though the GUI crashed occasionally in previous chia versions. So it seems this might be something recently setup by the package builder of the ubuntu release?

**Comment by mor** [comment]
![image](https://user-images.githubusercontent.com/110472/212885242-a1a73694-06dd-4551-843b-382ae091acdb.png)

**Comment by mor** [comment]
So once or twice a day since ~ when 1.6.1 came out, I get this popup as the GUI crashes. I've been authenticating and sending the problem reports, cuz, I dunno...

**Comment by MumfMeisterT** [comment]
How large is your derivation index?

What version of Ubuntu are you running and what GPU specs are you using? We believe this may be an electron issue related to GPU hardware rendering acceleration.

**Comment by mor** [comment]
1. Derivation Index: 2306
2. Ubuntu 22.04.1 LTS
3. Builtin VGA port on recent Dell XPS minitower:
       description: VGA compatible controller
       product: RocketLake-S GT1 [UHD Graphics 750]
       vendor: Intel Corporation
       physical id: 2
       bus info: pci@0000:00:02.0
       logical name: /dev/fb0
       version: 04
       width: 64 bits
       clock: 33MHz
       capabilities: pciexpress msi pm vga_controller bus_master cap_list rom fb
       configuration: depth=32 driver=i915 latency=0 resolution=1280,720
       resources: irq:162 memory:c2000000-c2ffffff memory:a0000000-afffffff ioport:5000(size=64) memory:c0000-dffff

**Comment by MumfMeisterT** [comment]
How did you install? Did you use git in source or did you install by using the package?

**Comment by mor** [comment]
I have re-installed chia perhaps 30 times on two different machines since the upgrade to 1.6.1 started me down this path last November. I've done it every which way, looking for a magic pill. From binary images, from github source, beta, rc, dev releases, downgrades, etc.... One thing I did notice is that when there are two machines running on my network, they definitely have many more problems if they have anything to do with each other (as in wallet peers and UI setups). So, I now run my full_node/farmer/harvester without a wallet on a cli machine, and my wallet in a standalone GUI on another machine. But the wallet is still very slow and inaccurate, just not 'rebuild the wallet database every other day' bad like it has been much of the past few months...

chia@Farmer:~/.chia$ journalctl -p 3 -xb | grep chia
chia@Farmer:~/.chia$

**Comment by MumfMeisterT** [comment]
Could you try running the Chia Wallet Check tool from this PR #14401 
One way you can do this if you're git savvy is use `git pull ak.wallet-db-check`.
