### ISSUE TITLE
[Bug] Missing profile

### ISSUE THREAD

**Issue by matholamew** [Chia-Network/chia-blockchain#14279]
### What happened?

I am missing a profile in one of my wallets.

For some back story, I set up a did profile in the past and was moving NFTs into it. A little bit ago I did a full resync of my database and now that profile does not show in the list when I edit them and I cannot move NFTs into that profile. I can see the NFTs if I look at 'All NFTs' so it's not a huge deal. Is there any way to get this profile back?

In the screenshots below, the one labeled 'NFT Wallet 4' is the one that is not showing in the list. The second one labeled 'nedini2' is one that I setup where I temporarily move some NFTs into.
<img width="918" alt="Screenshot 2023-01-04 at 19 19 37" src="https://user-images.githubusercontent.com/614992/210674571-a410eaa8-7c3a-4cf9-86f6-eaffdf19ef02.png">
<img width="391" alt="Screenshot 2023-01-04 at 19 20 44" src="https://user-images.githubusercontent.com/614992/210674575-f0f33070-c2d9-4cbb-889e-fda389ebfe50.png">

### Version

1.6.2

### What platform are you using?

macOS

### What ui mode are you using?

GUI

**Comment by MumfMeisterT** [comment]
Can you provide us the output from running `chia wallet show`?

**Comment by matholamew** [comment]
Here is some of the output from that. The profile is the one that ends in '...6sfg'

<img width="677" alt="Screenshot 2023-01-12 at 15 38 30" src="https://user-images.githubusercontent.com/614992/212176183-846ef987-ebe7-4134-9792-eb872cf032cc.png">

**Comment by stultuszoombie** [comment]
> Can you provide us the output from running `chia wallet show`? Could you also click on one of the NFTs you have assigned to the nedini2, then in the owner property field can you show us if the DID is linking to the nedini2 wallet?

i have this error also, but i see that
if you create a did with gui, and after go in cli for wallet show you can see this:
![did_chia_gui](https://user-images.githubusercontent.com/61159243/212197761-168e8e5f-ee0c-4e34-a9c8-de463668eddf.png)
if you create a did with cli you can see this:
![did_chia_cli](https://user-images.githubusercontent.com/61159243/212197908-d0c545ce-db63-4029-8ae7-f468d01034a6.png)
the nft is "unnamed" with gui
i'm editing all with cli from yesterday :(((((

**Comment by MumfMeisterT** [comment]
@matholamew Are your nedini2 and Goblin profiles on the same key or in separate keys? If so, do you have the Goblins profile on both sets of keys?

**Comment by matholamew** [comment]
They are in the same key as the one that is 'missing'.

**Comment by stultuszoombie** [comment]
![image](https://user-images.githubusercontent.com/61159243/213832165-520c7e22-7fcb-4c23-901d-ccfc8543f9e3.png)
today I checked the wallets I have on win 10
I deleted the db and at the end of the sync it appeared like this.
I don't know what this NFT wallet 23 is i search in cli and i see this:
[chia123txt.txt](https://github.com/Chia-Network/chia-blockchain/files/10471386/chia123txt.txt)
I hope it can help you to solve the problem

**Comment by matholamew** [comment]
I have just verified that the same thing has happened to another profile in a different wallet address. This one is for a NFT collection that was released under this DID so now the DID is not verified.

I DO _NOT_ want to delete the entire db and resync everything since this is what I do believe caused the issue in the first place! Can anyone help?

**Comment by matholamew** [comment]
> > Can you provide us the output from running `chia wallet show`? Could you also click on one of the NFTs you have assigned to the nedini2, then in the owner property field can you show us if the DID is linking to the nedini2 wallet?
> 
> i have this error also, but i see that if you create a did with gui, and after go in cli for wallet show you can see this: ![did_chia_gui](https://user-images.githubusercontent.com/61159243/212197761-168e8e5f-ee0c-4e34-a9c8-de463668eddf.png) if you create a did with cli you can see this: ![did_chia_cli](https://user-images.githubusercontent.com/61159243/212197908-d0c545ce-db63-4029-8ae7-f468d01034a6.png) the nft is "unnamed" with gui i'm editing all with cli from yesterday :((((( p.s. for editing i intend set a new name in a new did, transfer all nft, and delete the wrong one!!! send me 300000000000000000 moyos :))))))))))))))

Yes, I know that's the way it works. I now have 2 different wallets with profiles that I created. They only show the NFT wallet and not the DID wallet. Is there a way I can get the DID wallet back or created using the same wallet id/address?

**Comment by MumfMeisterT** [comment]
Can you check your log for `error adding state`? 
We are working on issues with conflicting DIDs, but it has not been resolved yet. 
I know you may not want to, but if you  do a full resysnc, it should resolve this issue.

**Comment by stultuszoombie** [comment]
> 

i found this: https://github.com/Chia-Network/chia-blockchain/pull/13925, i think is related to this: https://github.com/Chia-Network/chia-blockchain/commit/09f0184f7a32e832bead6ed87002cbedce35d668, i hope that 1.7 is ready soon :))
important: look and check the DID ID, i found a NTFs wallet with the **same DID** of a minter that sent to me a NTFs; 5 wallet ntfs are vanished..... i sent a mail to support..... probably are busy

**Comment by stultuszoombie** [comment]
> Can you check your log for `error adding state`? We are working on issues with conflicting DIDs, but it has not been resolved yet. I know you may not want to, but if you do a full resysnc, it should resolve this issue.

I done ful clean installation on windows 10
on iMac
on laptop
i resync every time, 1 time full_resync with farmer mode
2 times with wallet mode
i sent mail to support
i wrote on keybase
no_one answered to me..... 
probably are all very busy

2023-02-10T03:44:42.393 wallet chia.wallet.wallet_state_manager: ERROR    Error adding state... Was not able to obtain solution None
Traceback (most recent call last):
  File "chia\wallet\wallet_state_manager.py", line 1034, in new_coin_state
  File "chia\wallet\wallet_state_manager.py", line 624, in determine_coin_type
  File "chia\wallet\wallet_node.py", line 1602, in fetch_puzzle_solution
chia.wallet.util.wallet_sync_utils.PeerRequestException: Was not able to obtain solution None
2023-02-10T03:44:42.398 wallet chia.wallet.wallet_state_manager: ERROR    Error adding state... Was not able to get states for [b'\x8e\xcb\xdd\xa8Fl\x9c\xea 5\xaen\xf2\xddp6\x95%\x88\xbbh\xd8\xab@\x0b\t\xf36\x8f\xc9U\xcf']
Traceback (most recent call last):
  File "chia\wallet\wallet_state_manager.py", line 1034, in new_coin_state
  File "chia\wallet\wallet_state_manager.py", line 615, in determine_coin_type
  File "chia\wallet\wallet_node.py", line 1618, in get_coin_state
chia.wallet.util.wallet_sync_utils.PeerRequestException: Was not able to get states for [b'\x8e\xcb\xdd\xa8Fl\x9c\xea 5\xaen\xf2\xddp6\x95%\x88\xbbh\xd8\xab@\x0b\t\xf36\x8f\xc9U\xcf']
2023-02-10T03:44:42.408 wallet chia.wallet.wallet_state_manager: ERROR    Error adding state... Was not able to get states for [b'pS\xcd\x85x99*]\xc4N\xc7\xf9\xc5+\x93fUo\xd5\x15\xb7vt\x9cB\x924\x01\x87\x8c\xed']
Traceback (most recent call last):
  File "chia\wallet\wallet_state_manager.py", line 1034, in new_coin_state
  File "chia\wallet\wallet_state_manager.py", line 615, in determine_coin_type
  File "chia\wallet\wallet_node.py", line 1618, in get_coin_state
chia.wallet.util.wallet_sync_utils.PeerRequestException: Was not able to get states for [b'pS\xcd\x85x99*]\xc4N\xc7\xf9\xc5+\x93fUo\xd5\x15\xb7vt\x9cB\x924\x01\x87\x8c\xed']
2023-02-10T03:44:42.414 wallet chia.wallet.wallet_state_manager: ERROR    Error adding state... Was not able to obtain children None
Traceback (most recent call last):
  File "chia\wallet\wallet_state_manager.py", line 1139, in new_coin_state
  File "chia\wallet\wallet_node.py", line 1640, in fetch_children
chia.wallet.util.wallet_sync_utils.PeerRequestException: Was not able to obtain children None
2023-02-10T03:44:42.524 wallet chia.wallet.wallet_state_manager: ERROR    Error adding state... Was not able to obtain children None
Traceback (most recent call last):
  File "chia\wallet\wallet_state_manager.py", line 1139, in new_coin_state
  File "chia\wallet\wallet_node.py", line 1640, in fetch_children
chia.wallet.util.wallet_sync_utils.PeerRequestException: Was not able to obtain children None
2023-02-10T03:44:42.544 wallet chia.wallet.wallet_node    : WARNING  Validate false 1
2023-02-10T03:44:42.545 wallet wallet_server              : WARNING  Banning 5.40.101.49 for 9999 seconds
2023-02-10T03:44:42.548 wallet chia.wallet.wallet_node    : WARNING  Validate false 1
2023-02-10T03:44:42.549 wallet wallet_server              : WARNING  Banning 5.40.101.49 for 9999 seconds
### above you can see after installing  on new pc and doing resync
i started only wallet.
### under, you can see othe errors
2023-02-10T03:44:49.537 wallet wallet_server              : WARNING  Peer 5.40.101.49 is still banned, not connecting to it
2023-02-10T03:49:32.751 wallet chia.pools.pool_puzzles    : ERROR    Unexpected return from PoolWallet Smart Contract code cannot unpack non-iterable int object
2023-02-10T03:51:15.248 wallet chia.pools.pool_puzzles    : ERROR    Unexpected return from PoolWallet Smart Contract code cannot unpack non-iterable int object
2023-02-10T03:51:38.385 wallet chia.pools.pool_puzzles    : ERROR    Unexpected return from PoolWallet Smart Contract code cannot unpack non-iterable int object
2023-02-10T03:52:26.941 wallet chia.pools.pool_puzzles    : ERROR    Unexpected return from PoolWallet Smart Contract code cannot unpack non-iterable int object
2023-02-10T03:54:31.988 wallet chia.rpc.rpc_server        : WARNING  Error while handling message: Traceback (most recent call last):
  File "chia\rpc\rpc_server.py", line 329, in safe_handle
  File "chia\rpc\rpc_server.py", line 320, in ws_api
  File "chia\rpc\wallet_rpc_api.py", line 2317, in nft_get_wallet_did
KeyError: 11
2023-02-10T20:11:14.538 wallet chia.wallet.wallet_node    : ERROR    Error syncing to None
2023-02-10T20:29:51.724 wallet asyncio                    : ERROR    Task exception was never retrieved
future: <Task finished name='Task-6972' coro=<WalletNode.long_sync() done, defined at chia\wallet\wallet_node.py:609> exception=ValueError('None response from peer 84.196.161.47 for register_interest_in_puzzle_hash')>
Traceback (most recent call last):
  File "chia\wallet\wallet_node.py", line 654, in long_sync
  File "chia\wallet\util\wallet_sync_utils.py", line 75, in subscribe_to_phs
ValueError: None response from peer 84.196.161.47 for register_interest_in_puzzle_hash
**2023-02-10T23:54:06.570 wallet chia.rpc.wallet_rpc_api    : WARNING  NFT wallet 16 has DID .....eecafebc1bb6ac but no DID wallet**
**this DID is empty now, but i lost more NTFs this did is the same of a minter, that send to me a nft**

**Comment by stultuszoombie** [comment]
@matholamew
@ytx1991 
@MumfMeisterT 
even with version 1.7 the problems are the same, as specified in the update of the other day.
to solve the "derivation index" issue I modified the config.yaml and increased the number of starting addresses, deleted the "wallet db" and resync. now from 50 I have 57 wallet ids, I still have the nft wallet of Chia_Ndroids, NFTs from 98 now are 104....
thanks for Your Patience

**Comment by stultuszoombie** [comment]
### update 24/02/2023

possible relation with issue: **#13691**
full resync done, i started with "farmer mode"
today hundreds of this:
2023-02-23T21:05:56.223 wallet chia.wallet.nft_wallet.nft_wallet: INFO     **Tried removing NFT coin that doesn't exist**: b"\xc5\x8e\xa0\x05\xd1H'\xf7\xf7\xc2D\x98\x9f\xbd\xb8\xb0hM~\x80=9\xc1`\xa5\xb7\x8a\x88S\x18\xc6D"
70 times in 4h some are duplicated,

however, even after the full_resync, and having done a clean install, on a formatted pc, I still have another person's NFTwallet did:

![image](https://user-images.githubusercontent.com/61159243/221061339-6c7b60e2-bd0a-46a0-aff6-a931157ca2e8.png)
i'm still can't found some ntfs
i have the 'ids' not in sequence? (id 1,4,6,7,8,14,18....)
@ytx1991 @MumfMeisterT 
thanks

**Comment by ytx1991** [comment]
You can checkout the did_find branch and install it. The call the did_find_lost_did API. Let me know if you need guidance in detail.

**Comment by stultuszoombie** [comment]
> 
yes please, i don' know what i can do, i have:
NFT Wallet:
   -Total Balance:         0.0
   -Pending Total Balance: 0.0
   -Spendable:             0.0
   -Type:                  NFT
   -DID ID:                did:chia:1urc5cyc3n9x4ra69lqyawtasywclxj3wqlm4ytj4am90a0qmk6kqnkajrs
   -Wallet ID:             7
   
  **Without Decentralyzed_ID**
  the Decentralized id is in another wallet, not mine,
  that wallet is of:Chia_Ndroids (but i'm not "chia ndroids"..)
  since the did:id type: NFT appeared inside my main wallet, many of my dids (decentralyzed and nft) have disappeared
  i found a did:id but i don't have the name of the coin for this command:
  chia rpc wallet did_find_lost_did '{"coin_id":"YOUR_DID_ID_OR_COIN_ID"}'
  
  thanks for Your patience, please explain me how can i do, i think if is possible to send did:id type nft to his real owner the issues on my wallet gone also

**Comment by stultuszoombie** [comment]
https://github.com/Chia-Network/chia-blockchain/issues/14395#issuecomment-1454805757
this after run command chia wallet check

**Comment by stultuszoombie** [comment]
for more info go to:
https://github.com/Chia-Network/chia-blockchain/issues/14748

**Comment by emlowe** [comment]
Many fixes have gone in since this issue first was reported. tentatively Closing, however, feel free to comment and we can re-open is issues remain
