### ISSUE TITLE
[Bug] Fail to move NFT to profile

### ISSUE THREAD

**Issue by blupino** [Chia-Network/chia-blockchain#14347]
### What happened?

I try to move Holiday NFT to profile without fee, but it fail with below message

![image](https://user-images.githubusercontent.com/93529296/212442327-ea70b5fa-50ec-4c07-ad8f-9d560e0c0cae.png)

It's rather strange, because other NFT going to a different profile no issue. 

### Version

1.7.0b5.dev29

### What platform are you using?

Linux

### What ui mode are you using?

GUI

### Relevant log output

2023-01-14T09:34:10.741 wallet chia.wallet.nft_wallet.nft_wallet: DEBUG    Checking wallet type 6
2023-01-14T09:34:10.741 wallet chia.wallet.nft_wallet.nft_wallet: DEBUG    Checking wallet type 10
2023-01-14T09:34:10.741 wallet chia.wallet.nft_wallet.nft_wallet: DEBUG    Checking wallet type 6
2023-01-14T09:34:10.741 wallet chia.wallet.nft_wallet.nft_wallet: DEBUG    Checking wallet type 10
2023-01-14T09:34:10.741 wallet chia.wallet.nft_wallet.nft_wallet: DEBUG    Checking wallet type 10
2023-01-14T09:34:10.741 wallet chia.wallet.nft_wallet.nft_wallet: DEBUG    Checking wallet type 10
2023-01-14T09:34:10.741 wallet chia.wallet.nft_wallet.nft_wallet: DEBUG    Checking wallet type 10
2023-01-14T09:34:10.741 wallet chia.wallet.nft_wallet.nft_wallet: DEBUG    Checking wallet type 6
2023-01-14T09:34:10.742 wallet chia.wallet.nft_wallet.nft_wallet: DEBUG    Checking wallet type 10
2023-01-14T09:34:10.742 wallet chia.wallet.nft_wallet.nft_wallet: DEBUG    Checking wallet type 8
2023-01-14T09:34:10.742 wallet chia.wallet.nft_wallet.nft_wallet: DEBUG    Found a DID wallet, checking did: '25' == <bytes32: 25>
2023-01-14T09:34:10.742 wallet chia.wallet.nft_wallet.nft_wallet: DEBUG    Creating announcement from DID for nft_ids: [b""]
2023-01-14T09:34:10.743 wallet chia.wallet.did_wallet.did_wallet: WARNING  Can't select 1, from spendable 0 for wallet id 11
2023-01-14T09:34:10.743 wallet chia.rpc.rpc_server        : WARNING  Error while handling message: Traceback (most recent call last):
  File "/home/wallet/playground/src/chia-blockchain/chia/rpc/rpc_server.py", line 329, in safe_handle
    response = await self.ws_api(message)
  File "/home/wallet/playground/src/chia-blockchain/chia/rpc/rpc_server.py", line 320, in ws_api
    return await f_rpc_api(data)
  File "/home/wallet/playground/src/chia-blockchain/chia/rpc/wallet_rpc_api.py", line 2189, in nft_set_nft_did
    spend_bundle = await nft_wallet.set_nft_did(nft_coin_info, did_id, fee=fee)
  File "/home/wallet/playground/src/chia-blockchain/chia/wallet/nft_wallet/nft_wallet.py", line 1112, in set_nft_did
    did_inner_hash, did_bundle = await self.get_did_approval_info([nft_id], bytes32(did_id))
  File "/home/wallet/playground/src/chia-blockchain/chia/wallet/nft_wallet/nft_wallet.py", line 316, in get_did_approval_info
    did_bundle = await wallet.create_message_spend(puzzle_announcements=nft_ids)
  File "/home/wallet/playground/src/chia-blockchain/chia/wallet/did_wallet/did_wallet.py", line 764, in create_message_spend
    coins = await self.select_coins(uint64(1))
  File "/home/wallet/playground/src/chia-blockchain/chia/wallet/did_wallet/did_wallet.py", line 330, in select_coins
    raise ValueError(error_msg)
ValueError: Can't select 1, from spendable 0 for wallet id 11

2023-01-14T09:34:10.744 daemon __main__                   : DEBUG    Received message: WSMessage(type=<WSMsgType.TEXT: 1>, data='{"ack": true, "command": "nft_set_nft_did", "data": {"error": "Can\'t select 1, from spendable 0 for wallet id 11", "success": false}, "destination": "wallet_ui", "origin": "chia_wallet", "request_id": "ac42c5fae9f057d3bba7e0d9c69a30dbe72342f2a86f53e7ca30e4ae350d7ed3"}', extra='')

**Comment by blupino** [comment]
This problem repeatable, this specific holiday NFT always cannot be moved to the specific profile. But other NFT have no issue going to other profile

**Comment by codephunk** [comment]
I have exactly the same problem with a new DID I created. Same error message.

When I try to use `did_find_lost_did` I get the following error message:
`Request failed: {'error': 'Coin record 0x63c6c31c13a702b2784ee069933fbd581e15d35fd1a1dd0965d6557b1776155c not found', 'success': False}`

I also still wasn't able to recover my other DID I used for minting my NFT collection: https://github.com/Chia-Network/chia-blockchain/issues/13691

**Comment by MumfMeisterT** [comment]
@blupino Can you try the ```did_find_lost_did``` like @codephunk tried above to see if that works or if you have the same issue?

**Comment by blupino** [comment]
@codephunk is different issue. I don't have missing DID. My issue is I can't move NFT to DID

**Comment by blupino** [comment]
Request failed: {'error': 'This DID xxx is not belong to the connected wallet', 'success': False}

**Comment by codephunk** [comment]
btw: if I run `did_find_lost_did` on the machine where I created that DID, I get the same error message.
`Request failed: {'error': 'This DID 567d6ee0f9520613a96a0fb54229dc07c40a3e925e3a9db5b2d00d180553a85e is not belong to the connected wallet', 'success': False}`

**Comment by blupino** [comment]
Yup it's in my wallet

`Searching keys derived from: xxx
m/12381/8444/2/3756
Found wallet address: xxx (HD path: m/12381/8444/2/3756)`

**Comment by ytx1991** [comment]
We enhanced the did_find_lost_did API in the did_find branch, you can checkout and install it then try again.

**Comment by blupino** [comment]
Sorry for late reply... `did_find_lost_did` is working now

{"coin_id": "xxx"}'
{
    "latest_coin_id": "yyy",
    "success": true
}

and also now the main issue solved. I can now transfer the NFT to the profile. Thanks @ytx1991

**Comment by blupino** [comment]
Issue solved

**Comment by esaung** [comment]
closing as the issue looks resolved
