### ISSUE TITLE
[Bug] Harvester Crashes Frequently with ERROR Exception: <class 'asyncio.exceptions.TimeoutError'>

### ISSUE THREAD

**Issue by Furious-George** [Chia-Network/chia-blockchain#14380]
### What happened?

Between 3 days and 3 hours after starting the harvester, it crashes with:

`harvester harvester_server : ERROR Exception: <class 'asyncio.exceptions.TimeoutError'>, closing connection {'host': '10.5.0.21', 'port': 8447}.`

In a previous [bug report](https://github.com/Chia-Network/chia-blockchain/issues/13700) it was suggested that I check for failing or overheating disks, and clean up my config.yaml to not include empty directories.  I was not able to find any disks that seemed to be obviously failing.  (a few had between 1 and 3 SMART errors, none recent).

I have also upgraded chia twice via apt since this started.

It is interesting to note that I have two harvesters, and this one has all the new disks, while the other has disks that are quite old, and never crashes.

One theory I have is that when going from source-based to apt-based insallation, I made some mistake, and can't recall what it is.  I just recall purging the packaged, removing .chia, reinstalling, and regenerating .chia via chia init.  Perhaps this is related? 

### Version

harvester harvester_server : ERROR Exception: <class 'asyncio.exceptions.TimeoutError'>, closing connection {'host': '10.5.0.21', 'port': 8447}.

### What platform are you using?

Linux

### What ui mode are you using?

CLI

### Relevant log output

```shell
2023-01-20T08:50:51.958 daemon chia.daemon.server : DEBUG About to ping: chia_harvester
2023-01-20T08:50:58.639 harvester harvester_server : DEBUG <- new_signage_point_harvester from peer 201d3f186882a7c571ba5784d07580358e79ac08aafb1ddb4bf045333e916d0a 10.5.0.21
2023-01-20T08:50:58.640 harvester chia.harvester.harvester: DEBUG new_signage_point_harvester lookup: challenge_hash: 572f391a71e344d049d959361a56fdcbd0540fba3670defe06c757706040799d, sp_hash: 71f186c6b0af7b70df4d72320726a94973abd88c316e75976f1a00b7fb765665, signage_point_index: 25
2023-01-20T08:50:58.640 harvester chia.harvester.harvester: DEBUG new_signage_point_harvester lock acquired
2023-01-20T08:50:58.835 harvester chia.harvester.harvester: DEBUG new_signage_point_harvester 10 plots passed the plot filter
2023-01-20T08:50:59.414 harvester chia.harvester.harvester: INFO 10 plots were eligible for farming 572f391a71... Found 0 proofs. Time: 0.77449 s. Total 5034 plots
2023-01-20T08:50:59.415 harvester harvester_server : DEBUG -> farming_info to peer 10.5.0.21 201d3f186882a7c571ba5784d07580358e79ac08aafb1ddb4bf045333e916d0a
2023-01-20T08:50:59.415 harvester harvester_server : DEBUG Time taken to process new_signage_point_harvester from 201d3f186882a7c571ba5784d07580358e79ac08aafb1ddb4bf045333e916d0a is 0.7763848304748535 seconds
2023-01-20T08:50:59.416 daemon chia.daemon.server : DEBUG Received message: WSMessage(type=<WSMsgType.TEXT: 1>, data='{"ack": false, "command": "farming_info", "data": {"challenge_hash": "572f391a71e344d049d959361a56fdcbd0540fba3670defe06c757706040799d", "eligible_plots": 10, "found_proofs": 0, "success": true, "time": 0.7744929790496826, "total_plots": 5034}, "destination": "metrics", "origin": "chia_harvester", "request_id": "23ea6bc1826eb2bcb19f665fd3d062040fd02775310b83c3160c2be1b7522393"}', extra='')
2023-01-20T08:51:06.850 harvester harvester_server : ERROR Exception: <class 'asyncio.exceptions.TimeoutError'>, closing connection {'host': '10.5.0.21', 'port': 8447}. Traceback (most recent call last):
File "chia/server/server.py", line 634, in api_call
File "asyncio/tasks.py", line 501, in wait_for
asyncio.exceptions.TimeoutError

2023-01-20T08:51:06.850 harvester harvester_server : DEBUG Inbound_handler task cancelled
2023-01-20T08:51:06.852 harvester harvester_server : WARNING Banning 10.5.0.21 for 10 seconds
2023-01-20T08:51:06.852 harvester harvester_server : INFO Connection closed: 10.5.0.21, node id: 201d3f186882a7c571ba5784d07580358e79ac08aafb1ddb4bf045333e916d0a
2023-01-20T08:51:06.852 harvester chia.harvester.harvester: INFO peer disconnected {'host': '10.5.0.21', 'port': 8447}
2023-01-20T08:51:21.982 daemon chia.daemon.server : DEBUG About to ping: chia_harvester
2023-01-20T08:51:51.989 daemon chia.daemon.server : DEBUG About to ping: chia_harvester
2023-01-20T08:51:51.990 daemon chia.daemon.server : ERROR Ping error
Traceback (most recent call last):
File "chia/daemon/server.py", line 283, in ping_task
File "aiohttp/web_ws.py", line 295, in ping
File "aiohttp/http_websocket.py", line 676, in ping
File "aiohttp/http_websocket.py", line 653, in _send_frame
File "aiohttp/http_websocket.py", line 663, in _write
ConnectionResetError: Cannot write to closing transport
2023-01-20T08:51:51.991 daemon chia.daemon.server : ERROR Ping failed, connection closed.
```

**Comment by MumfMeisterT** [comment]
#13700

**Comment by MumfMeisterT** [comment]
Could you please provide your current setup for your machines and what you have for your farmer and harvester? Are they on seperate machines, etc?

**Comment by Furious-George** [comment]
> Could you please provide your current setup for your machines and what you have for your farmer and harvester? Are they on seperate machines, etc?

I have two harvesters and a separate farmer with no plots of its own.

At one time, I was compiling from source, but have switched to aptitude-based installs.  The problem seems to have started around that time.

Only one of the harvesters have this problem.

The plots are stored on ZFS, with one volume per disk.

I'm using a recent version of Proxmox as the operating system, but there are no VMs or LXCs running on the harvesters in question.

The other harvesters (the one that doesn't crash) runs the farmer as a debian VM.

The harvesters that crashes contains exclusively newer 16 tb disks.  (The other one has a hodge-podge of older and newer disks, but does not crash.)

**Comment by Furious-George** [comment]
Most recent crash:

```
ng: chia_harvester
2023-01-31T00:10:33.243 harvester harvester_server        : DEBUG    <- new_signage_point_harvester from peer 201d3f186882a7c571ba5784d07580358e79ac08aafb1ddb4bf045333e916d0a 10.5.0.21
2023-01-31T00:10:33.243 harvester chia.harvester.harvester: DEBUG    new_signage_point_harvester lookup: challenge_hash: ec56f10c27afd67379c62df2c4784598ecd6f715302a03ddaef8fa8120a122a6, sp_hash: f9b379b114edd82c5f5b1369424d05cc3c2a4fe0141f86e990d517d79637abc5, signage_point_index: 57
2023-01-31T00:10:33.243 harvester chia.harvester.harvester: DEBUG    new_signage_point_harvester lock acquired
2023-01-31T00:10:33.436 harvester chia.harvester.harvester: DEBUG    new_signage_point_harvester 11 plots passed the plot filter
2023-01-31T00:10:34.374 harvester harvester_server        : ERROR    Exception:  <class 'asyncio.exceptions.TimeoutError'>, closing connection {'host': '10.5.0.21', 'port': 8447}. Traceback (most recent call last):
  File "chia/server/server.py", line 634, in api_call
  File "asyncio/tasks.py", line 501, in wait_for
asyncio.exceptions.TimeoutError

2023-01-31T00:10:34.374 harvester harvester_server        : DEBUG    Inbound_handler task cancelled
2023-01-31T00:10:34.375 harvester harvester_server        : WARNING  Banning 10.5.0.21 for 10 seconds
2023-01-31T00:10:34.375 harvester harvester_server        : INFO     Connection closed: 10.5.0.21, node id: 201d3f186882a7c571ba5784d07580358e79ac08aafb1ddb4bf045333e916d0a
2023-01-31T00:10:34.376 harvester chia.harvester.harvester: INFO     peer disconnected {'host': '10.5.0.21', 'port': 8447}
2023-01-31T00:11:01.596 daemon chia.daemon.server         : DEBUG    About to ping: chia_harvester
2023-01-31T00:11:31.613 daemon chia.daemon.server         : DEBUG    About to ping: chia_harvester
2023-01-31T00:11:31.613 daemon chia.daemon.server         : ERROR    Ping error
Traceback (most recent call last):
  File "chia/daemon/server.py", line 283, in ping_task
  File "aiohttp/web_ws.py", line 295, in ping
  File "aiohttp/http_websocket.py", line 676, in ping
  File "aiohttp/http_websocket.py", line 653, in _send_frame
  File "aiohttp/http_websocket.py", line 663, in _write
ConnectionResetError: Cannot write to closing transport
2023-01-31T00:11:31.615 daemon chia.daemon.server         : ERROR    Ping failed, connection close


Please advice

**Comment by Furious-George** [comment]
# systemctl restart chia_harvester.service

# ps ax |grep chia
  21449 ?        Sl     1:34 chia_daemon
  21816 ?        Zl   440:18 [chia_harvester] <defunct>
2855096 ?        Ss     0:00 /bin/sh -c chia stop harvester
2855097 ?        Sl     0:00 chia stop harvester
2855217 pts/0    S+     0:00 grep chia

**Comment by Furious-George** [comment]
Hi again.

The crashes all seem to look pretty much alike.

```
2023-03-17T02:07:06.440 harvester harvester_server        : ERROR    Exception:  <class 'asyncio.exceptions.TimeoutError'>, closing connection {'host': '10.5.0.21', 'port': 8447}. Traceback (most recent call last):
  File "chia/server/server.py", line 634, in api_call
  File "asyncio/tasks.py", line 501, in wait_for
asyncio.exceptions.TimeoutError

2023-03-17T02:07:06.440 harvester harvester_server        : DEBUG    Inbound_handler task cancelled
2023-03-17T02:07:06.442 harvester harvester_server        : WARNING  Banning 10.5.0.21 for 10 seconds
2023-03-17T02:07:06.442 harvester harvester_server        : INFO     Connection closed: 10.5.0.21, node id: 201d3f186882a7c571ba5784d07580358e79ac08aafb1ddb4bf045333e916d0a
2023-03-17T02:07:06.443 harvester chia.harvester.harvester: INFO     peer disconnected {'host': '10.5.0.21', 'port': 8447}
2023-03-17T02:07:11.269 daemon chia.daemon.server         : DEBUG    About to ping: chia_harvester
2023-03-17T02:07:41.280 daemon chia.daemon.server         : DEBUG    About to ping: chia_harvester
2023-03-17T02:08:11.305 daemon chia.daemon.server         : DEBUG    About to ping: chia_harvester
2023-03-17T02:08:11.305 daemon chia.daemon.server         : ERROR    Ping error
Traceback (most recent call last):
  File "chia/daemon/server.py", line 283, in ping_task
  File "aiohttp/web_ws.py", line 295, in ping
  File "aiohttp/http_websocket.py", line 676, in ping
  File "aiohttp/http_websocket.py", line 653, in _send_frame
  File "aiohttp/http_websocket.py", line 663, in _write
ConnectionResetError: Cannot write to closing transport
2023-03-17T02:08:11.306 daemon chia.daemon.server         : ERROR    Ping failed, connection closed.
```

Could this be caused by some sort of hardware problem on this node, such as a bad NIC?  I'm running a traceroute from the node to the farmer, to see if any packets get lost.  I had it running for a few days, and no packets were lost, but neither did the server crash, and eventually we had a power outage before the next crash.

Updating the harvester does not fix the issue.  Is there some setting I can try changing in the config.yaml?

Can anyone think of anything to try?

**Comment by emlowe** [comment]
Have you tried checking the plots with `chia plots check`? Or possibly reducing the number of disks this harvester is scanning to see if the problem is with a disk or a plot

**Comment by emlowe** [comment]
Closing old issue

**Comment by Furious-George** [comment]
Remains unfixed, but I think it's a hardware problem on my side.

What do you think?
________________________________
