### ISSUE TITLE
Pressing ctrl+c during CLI commands spits out traceback

### ISSUE THREAD

**Issue by wallentx** [Chia-Network/chia-blockchain#14389]
![Image](https://user-images.githubusercontent.com/8990544/214121319-5ebef3b2-7846-4046-b7f5-9a26ff7c20e0.png)

![Image](https://user-images.githubusercontent.com/8990544/214121318-a0b2e519-8d46-483e-b8ec-b058c7835a02.png)

**Comment by altendky** [comment]
I think there are likely two separate cases to be considered here.  The general import-time cancellation which would be handled generically and the specific case of the client session in the first shown traceback.

**Comment by altendky** [comment]
I think there are two cases to be handled here separately.  The first traceback shows an unclosed client session that should be dealt with specifically.  The second traceback is a general cancellation while importing and would involve a fairly general keyboard interrupt consumption mechanism.  Maybe something with `sys.excepthook` when run from an entry points script or such.

**Comment by wallentx** [comment]
```
Traceback (most recent call last):
  File "chia\cmds\chia.py", line 9, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 499, in exec_module
  File "chia\cmds\beta.py", line 10, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 499, in exec_module
  File "chia\cmds\beta_funcs.py", line 9, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 499, in exec_module
  File "chia\util\chia_logging.py", line 11, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 499, in exec_module
  File "chia\cmds\init_funcs.py", line 14, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 499, in exec_module
  File "chia\ssl\create_ssl.py", line 9, in <module>
    from cryptography import x509
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 499, in exec_module
  File "cryptography\x509\__init__.py", line 7, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 499, in exec_module
  File "cryptography\x509\base.py", line 28, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 499, in exec_module
  File "cryptography\x509\extensions.py", line 25, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 499, in exec_module
  File "cryptography\x509\general_name.py", line 11, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 499, in exec_module
  File "cryptography\x509\name.py", line 362, in <module>
  File "cryptography\x509\name.py", line 375, in _RFC4514NameParser
  File "re.py", line 252, in compile
  File "re.py", line 304, in _compile
  File "sre_compile.py", line 788, in compile
  File "sre_parse.py", line 955, in parse
  File "sre_parse.py", line 444, in _parse_sub
  File "sre_parse.py", line 841, in _parse
  File "sre_parse.py", line 444, in _parse_sub
  File "sre_parse.py", line 841, in _parse
  File "sre_parse.py", line 444, in _parse_sub
  File "sre_parse.py", line 841, in _parse
  File "sre_parse.py", line 444, in _parse_sub
  File "sre_parse.py", line 841, in _parse
  File "sre_parse.py", line 436, in _parse_sub
KeyboardInterrupt
[1668] Failed to execute script 'chia' due to unhandled exception!
```

**Comment by wallentx** [comment]
Seems related to https://github.com/Chia-Network/chia-blockchain/pull/14319

**Comment by altendky** [comment]
Which case?  You did some check right before and then with that commit?

**Comment by emlowe** [comment]
Closing issue - seems fixed in the mentioned cases - new issue should be created if related behaviour is seen again
