### ISSUE TITLE
Can't create an offer with an included maker fee

### ISSUE THREAD

**Issue by paninaro** [Chia-Network/chia-blockchain#14412]
On testnet, I'm creating a simple offer of 1 TXCH for an NFT. If I create the offer without a fee included, the offer is created without any issue. If I add a fee to include in the offer, the CLI fails with:

```
Exception from 'wallet' {'error': 'Error creating offer: ', 'success': False}:
Traceback (most recent call last):
  File "/Users/jeffc/src/macos/chia-blockchain/chia/cmds/cmds_util.py", line 100, in get_any_service_client
    yield node_client, config, fingerprint
  File "/Users/jeffc/src/macos/chia-blockchain/chia/cmds/cmds_util.py", line 211, in execute_with_wallet
    await function(extra_params, wallet_client, new_fp)
  File "/Users/jeffc/src/macos/chia-blockchain/chia/cmds/wallet_funcs.py", line 455, in make_offer
    offer, trade_record = await wallet_client.create_offer_for_ids(
  File "/Users/jeffc/src/macos/chia-blockchain/chia/rpc/wallet_rpc_client.py", line 682, in create_offer_for_ids
    res = await self.fetch("create_offer_for_ids", req)
  File "/Users/jeffc/src/macos/chia-blockchain/chia/rpc/rpc_client.py", line 50, in fetch
    raise ValueError(res_json)
ValueError: {'error': 'Error creating offer: ', 'success': False}```

**Comment by paninaro** [comment]
```
chia wallet make_offer -f 52772570 -o 1:1 -r nft1f8hlqzjjh7nwqar2krz9yk7r6rzdu6tx47aqwr98c6z56dp0kkhs5lsdz0:1 -m 0.00005 -p cli.offer
Creating Offer
--------------

OFFERING:
  - 1 XCH (1000000000000 mojos)
REQUESTING:
  - 1 nft1f8hlqzjjh7nwqar2krz9yk7r6rzdu6tx47aqwr98c6z56dp0kkhs5lsdz0 (1 mojos)
Confirm (y/n): y
Exception from 'wallet' {'error': 'Error creating offer: ', 'success': False}:
Traceback (most recent call last):
  File "/Users/jeffc/src/macos/chia-blockchain/chia/cmds/cmds_util.py", line 100, in get_any_service_client
    yield node_client, config, fingerprint
  File "/Users/jeffc/src/macos/chia-blockchain/chia/cmds/cmds_util.py", line 211, in execute_with_wallet
    await function(extra_params, wallet_client, new_fp)
  File "/Users/jeffc/src/macos/chia-blockchain/chia/cmds/wallet_funcs.py", line 455, in make_offer
    offer, trade_record = await wallet_client.create_offer_for_ids(
  File "/Users/jeffc/src/macos/chia-blockchain/chia/rpc/wallet_rpc_client.py", line 682, in create_offer_for_ids
    res = await self.fetch("create_offer_for_ids", req)
  File "/Users/jeffc/src/macos/chia-blockchain/chia/rpc/rpc_client.py", line 50, in fetch
    raise ValueError(res_json)
ValueError: {'error': 'Error creating offer: ', 'success': False}
```

**Comment by paninaro** [comment]
From debug.log:

```
2023-01-26T20:12:44.112 wallet chia.wallet.wallet         : INFO     Cost of a single tx for standard wallet: 8624562
2023-01-26T20:12:44.113 wallet chia.wallet.wallet         : DEBUG    Got back max send amount: 21044223805264
2023-01-26T20:12:44.113 wallet chia.wallet.wallet         : INFO     coins is not None {Coin { parent_coin_info: 8dc8c0b30f859d7c3617223c79422d178c4f636fa0133dfdcdb847b5c7a60133, puzzle_hash: e97518045202f650ac57a888741f5b86aad082fa9e47af109f4829a0bf094e7f, amount: 1000000000000 }}
2023-01-26T20:12:44.116 wallet chia.wallet.trade_manager  : ERROR    Error with creating trade offer: <class 'AssertionError'>Traceback (most recent call last):
  File "/Users/jeffc/src/macos/chia-blockchain/chia/wallet/trade_manager.py", line 540, in _create_offer_for_ids
    tx = await wallet.generate_signed_transaction(
  File "/Users/jeffc/src/macos/chia-blockchain/chia/wallet/wallet.py", line 483, in generate_signed_transaction
    transaction = await self._generate_unsigned_transaction(
  File "/Users/jeffc/src/macos/chia-blockchain/chia/wallet/wallet.py", line 364, in _generate_unsigned_transaction
    assert change >= 0
AssertionError

2023-01-26T20:12:44.120 wallet chia.rpc.util              : WARNING  Error while handling message: Traceback (most recent call last):
  File "/Users/jeffc/src/macos/chia-blockchain/chia/rpc/util.py", line 18, in inner
    res_object = await f(request_data)
  File "/Users/jeffc/src/macos/chia-blockchain/chia/rpc/wallet_rpc_api.py", line 1486, in create_offer_for_ids
    result = await self.service.wallet_state_manager.trade_manager.create_offer_for_ids(
  File "/Users/jeffc/src/macos/chia-blockchain/chia/wallet/trade_manager.py", line 407, in create_offer_for_ids
    raise Exception(f"Error creating offer: {result[2]}")
Exception: Error creating offer:
```

**Comment by paninaro** [comment]
Working for me now with RC5
