### ISSUE TITLE
[Bug] errors in debug log file when fetching incoming offer notifications

### ISSUE THREAD

**Issue by esaung** [Chia-Network/chia-blockchain#14455]
### What happened?

seeing these errors in debug.log (debug=warning)

GUI is able to load the incoming offers so I don't believe this is critical, but something that is showing up in the logs.

2023-01-31T18:08:10.852 wallet chia.rpc.rpc_server        : WARNING  Error while handling message: Traceback (most recent call last):
  File "chia/rpc/rpc_server.py", line 331, in safe_handle
  File "chia/rpc/rpc_server.py", line 322, in ws_api
  File "chia/rpc/wallet_rpc_api.py", line 1548, in get_offer_summary
  File "chia/wallet/trading/offer.py", line 596, in from_bech32
ValueError: Invalid Offer

2023-01-31T18:08:11.056 wallet chia.rpc.rpc_server        : WARNING  Error while handling message: Traceback (most recent call last):
  File "chia/rpc/rpc_server.py", line 331, in safe_handle
  File "chia/rpc/rpc_server.py", line 322, in ws_api
  File "chia/rpc/wallet_rpc_api.py", line 1548, in get_offer_summary
  File "chia/wallet/trading/offer.py", line 596, in from_bech32
ValueError: Invalid Offer

2023-01-31T18:08:11.057 wallet chia.rpc.rpc_server        : WARNING  Error while handling message: Traceback (most recent call last):
  File "chia/rpc/rpc_server.py", line 331, in safe_handle
  File "chia/rpc/rpc_server.py", line 322, in ws_api
  File "chia/rpc/wallet_rpc_api.py", line 1548, in get_offer_summary
  File "chia/wallet/trading/offer.py", line 596, in from_bech32
ValueError: Invalid Offer

2023-01-31T18:08:11.057 wallet chia.rpc.rpc_server        : WARNING  Error while handling message: Traceback (most recent call last):
  File "chia/rpc/rpc_server.py", line 331, in safe_handle
  File "chia/rpc/rpc_server.py", line 322, in ws_api
  File "chia/rpc/wallet_rpc_api.py", line 1548, in get_offer_summary
  File "chia/wallet/trading/offer.py", line 596, in from_bech32
ValueError: Invalid Offer

2023-01-31T18:08:11.058 wallet chia.rpc.rpc_server        : WARNING  Error while handling message: Traceback (most recent call last):
  File "chia/rpc/rpc_server.py", line 331, in safe_handle
  File "chia/rpc/rpc_server.py", line 322, in ws_api
  File "chia/rpc/wallet_rpc_api.py", line 1548, in get_offer_summary
  File "chia/wallet/trading/offer.py", line 596, in from_bech32
ValueError: Invalid Offer

### Version

1.7.0rc5

### What platform are you using?

macOS

### What ui mode are you using?

GUI

### Relevant log output

```shell
2023-01-31T18:08:10.852 wallet chia.rpc.rpc_server        : WARNING  Error while handling message: Traceback (most recent call last):
  File "chia/rpc/rpc_server.py", line 331, in safe_handle
  File "chia/rpc/rpc_server.py", line 322, in ws_api
  File "chia/rpc/wallet_rpc_api.py", line 1548, in get_offer_summary
  File "chia/wallet/trading/offer.py", line 596, in from_bech32
ValueError: Invalid Offer

2023-01-31T18:08:11.056 wallet chia.rpc.rpc_server        : WARNING  Error while handling message: Traceback (most recent call last):
  File "chia/rpc/rpc_server.py", line 331, in safe_handle
  File "chia/rpc/rpc_server.py", line 322, in ws_api
  File "chia/rpc/wallet_rpc_api.py", line 1548, in get_offer_summary
  File "chia/wallet/trading/offer.py", line 596, in from_bech32
ValueError: Invalid Offer

2023-01-31T18:08:11.057 wallet chia.rpc.rpc_server        : WARNING  Error while handling message: Traceback (most recent call last):
  File "chia/rpc/rpc_server.py", line 331, in safe_handle
  File "chia/rpc/rpc_server.py", line 322, in ws_api
  File "chia/rpc/wallet_rpc_api.py", line 1548, in get_offer_summary
  File "chia/wallet/trading/offer.py", line 596, in from_bech32
ValueError: Invalid Offer

2023-01-31T18:08:11.057 wallet chia.rpc.rpc_server        : WARNING  Error while handling message: Traceback (most recent call last):
  File "chia/rpc/rpc_server.py", line 331, in safe_handle
  File "chia/rpc/rpc_server.py", line 322, in ws_api
  File "chia/rpc/wallet_rpc_api.py", line 1548, in get_offer_summary
  File "chia/wallet/trading/offer.py", line 596, in from_bech32
ValueError: Invalid Offer

2023-01-31T18:08:11.058 wallet chia.rpc.rpc_server        : WARNING  Error while handling message: Traceback (most recent call last):
  File "chia/rpc/rpc_server.py", line 331, in safe_handle
  File "chia/rpc/rpc_server.py", line 322, in ws_api
  File "chia/rpc/wallet_rpc_api.py", line 1548, in get_offer_summary
  File "chia/wallet/trading/offer.py", line 596, in from_bech32
ValueError: Invalid Offer
```

**Comment by esaung** [comment]
these error also show up when trying to create a counter-offer offer. the offer looks like it's created and shows up in the GUI.
