### ISSUE TITLE
[Bug] Full node database corruption problem

### ISSUE THREAD

**Issue by mor** [Chia-Network/chia-blockchain#14495]
### What happened?

I got this error while trying to run 'chia db backup' so I stopped and restarted chia, but the error remains when trying to validate the db. This a full_node machine running only CLI on Ubuntu 22.04 LTS. The database is on it's own SSD, while the box barely breaks a sweat running chia around 0 to 0.5 utilization. I guess I just restore a couple weeks old copy of V2 db and resync from there? Or is there an actual sqlite3 command that might correct? Chia seems to actually be working/farming now, but for how long?

### Version

1.6.2

### What platform are you using?

Linux

### What ui mode are you using?

CLI

### Relevant log output

```shell
chia@Farmer:~/.chia$ chia db validate
opening file for reading: /home/chia/.chia_data/mainnet/db/blockchain_v2_mainnet.sqlite
peak hash: cc87d845ea054d2036cb1d1bac6d94acbf24fd53074156af254fff470e02bf6f
peak height: 3207855
traversing the full chain
369530 orphaned blocks: 1272 Traceback (most recent call last):
  File "chia/cmds/chia.py", line 135, in <module>
  File "chia/cmds/chia.py", line 131, in main
  File "click/core.py", line 1130, in __call__
  File "click/core.py", line 1055, in main
  File "click/core.py", line 1657, in invoke
  File "click/core.py", line 1657, in invoke
  File "click/core.py", line 1404, in invoke
  File "click/core.py", line 760, in invoke
  File "click/decorators.py", line 26, in new_func
  File "chia/cmds/db.py", line 62, in db_validate_cmd
  File "chia/cmds/db_validate_func.py", line 27, in db_validate_func
  File "chia/cmds/db_validate_func.py", line 95, in validate_v2
sqlite3.DatabaseError: database disk image is malformed
[657615] Failed to execute script 'chia' due to unhandled exception!
```

**Comment by emlowe** [comment]
This error is not repairable that I know of. It would be strange for this to appear during a `db backup` as this is a wrapper around a sqlite feature (`vacuum into`). In any event, restoring from a backup is your best course here
