### ISSUE TITLE
[Bug] Creating a large number of offers results in "too many SQL variables" error

### ISSUE THREAD

**Issue by emlowe** [Chia-Network/chia-blockchain#14501]
### What happened?

Creating a large number of offers (400+) will create a large number of locked coins and fetching those locked coins can result in making a very large query to SQL which depending on the version of sqlite can throw the `too many SQL variables` error

The offers in this case were generated by using a script that loops around creating the offers one at a time using the CLI

### Version

1.6.2

### What platform are you using?

Linux

### What ui mode are you using?

CLI

### Relevant log output

```shell
2023-02-06T08:34:46.783 wallet chia.rpc.util              : WARNING  Error while handling message: Traceback (most recent call last):
  File "/site-packages/chia/rpc/util.py", line 18, in inner
    res_object = await f(request_data)
  File "/site-packages/chia/rpc/wallet_rpc_api.py", line 798, in get_wallet_balance
    spendable_balance = await wallet.get_spendable_balance(unspent_records)
  File "/site-packages/chia/wallet/cat_wallet/cat_wallet.py", line 408, in get_spendable_balance
    coins = await self.get_cat_spendable_coins(records)
  File "/site-packages/chia/wallet/cat_wallet/cat_wallet.py", line 439, in get_cat_spendable_coins
    record_list: Set[WalletCoinRecord] = await self.wallet_state_manager.get_spendable_coins_for_wallet(
  File "/site-packages/chia/wallet/wallet_state_manager.py", line 1698, in get_spendable_coins_for_wallet
    offer_locked_coins: Dict[bytes32, WalletCoinRecord] = await self.trade_manager.get_locked_coins()
  File "/site-packages/chia/wallet/trade_manager.py", line 197, in get_locked_coins
    coin_records = await self.wallet_state_manager.coin_store.get_multiple_coin_records(coins_of_interest)
  File "/site-packages/chia/wallet/wallet_coin_store.py", line 74, in get_multiple_coin_records
    rows = await conn.execute_fetchall(
  File "/site-packages/aiosqlite/core.py", line 203, in execute_fetchall
    return await self.execute(self.execute_fetchall, sql, parameters)
  File "/site-packages/aiosqlite/core.py", line 129, in _execute
    return await future
  File "/site-packages/aiosqlite/core.py", line 102, in run
    result = function()
  File "/site-packages/aiosqlite/core.py", line 81, in executefetchall
    cursor = self._conn.execute(sql, parameters)
sqlite3.OperationalError: too many SQL variables
```

**Comment by bwccnft** [comment]
Tested with SQL updated to 3.40.1 and Python 3.11.1 / 3.10 
After updating the Python 3.11.1 / 3.10 version, error `too many SQL variables error` seems fixed.

Script throws new errors due to the CATs. 
1st time crashed after creating aprox.1404 offers, 2nd time crashed after creating ~631 offers, 3th time crashed after creating ~417 offers. Failed to add coin 0xab5ff63deed917839b4a9bcaf0e85dc4d3648ca132a9298b757b19850112552c 

Total CATs: 6432
https://www.spacescan.io/coin/9bb28ab4cd61417164818914c7a1bb4ffd2d8fcd89e7827e1975671dc801f404
coin: 0x9bb28ab4cd61417164818914c7a1bb4ffd2d8fcd89e7827e1975671dc801f404
`2023-02-12T**09:32:07.840** wallet chia.wallet.cat_wallet.cat_wallet: INFO     Confirmed balance for cat wallet 12 is **9953000**`

Total CATs: 6431
https://www.spacescan.io/coin/0xab5ff63deed917839b4a9bcaf0e85dc4d3648ca132a9298b757b19850112552c
Coin: 0xab5ff63deed917839b4a9bcaf0e85dc4d3648ca132a9298b757b19850112552c
`2023-02-12T**09:32:14.322** wallet chia.wallet.cat_wallet.cat_wallet: INFO     Confirmed balance for cat wallet 12 is **3522000**`
**Suddenly Total Balance dropped from 9953 to 3522 within 6.482 milliseconds**
2023-02-12T09:32:14.322 - 2023-02-12T09:32:07.840  = 6.482   **~aprox.7 milliseconds**

Following errors are observed from the log data:
Logs from 2nd attempt errors out after generating ~631 offers:
```
2023-02-12T09:32:23.601 wallet chia.rpc.util              : WARNING  Error while handling message: Traceback (most recent call last):
  File "chia/rpc/util.py", line 18, in inner
  File "chia/rpc/wallet_rpc_api.py", line 1396, in cat_spend
  File "chia/wallet/cat_wallet/cat_wallet.py", line 786, in generate_signed_transaction
ValueError: Can't send more than 0 mojos in a single transaction
```
```
2023-02-12T09:32:28.365 wallet chia.wallet.cat_wallet.cat_wallet: INFO     Confirmed balance for cat wallet 12 is 3522000
2023-02-12T09:32:28.870 wallet chia.wallet.cat_wallet.cat_wallet: WARNING  Can't select amount higher than our spendable balance.  Amount: 1000, spendable: 0
2023-02-12T09:32:28.871 wallet chia.wallet.trade_manager  : ERROR    Error with creating trade offer: <class 'ValueError'>Traceback (most recent call last):
  File "chia/wallet/trade_manager.py", line 493, in _create_offer_for_ids
  File "chia/wallet/cat_wallet/cat_wallet.py", line 886, in get_coins_to_offer
  File "chia/wallet/cat_wallet/cat_wallet.py", line 472, in select_coins
  File "chia/wallet/coin_selection.py", line 39, in select_coins
ValueError: Can't select amount higher than our spendable balance.  Amount: 1000, spendable: 0

2023-02-12T09:32:28.871 wallet chia.rpc.util              : WARNING  Error while handling message: Traceback (most recent call last):
  File "chia/rpc/util.py", line 18, in inner
  File "chia/rpc/wallet_rpc_api.py", line 1485, in create_offer_for_ids
  File "chia/wallet/trade_manager.py", line 407, in create_offer_for_ids
Exception: Error creating offer: Can't select amount higher than our spendable balance.  Amount: 1000, spendable: 0

2023-02-12T09:32:31.730 wallet chia.rpc.util              : WARNING  Error while handling message: Traceback (most recent call last):
  File "chia/rpc/util.py", line 18, in inner
  File "chia/rpc/wallet_rpc_api.py", line 1396, in cat_spend
  File "chia/wallet/cat_wallet/cat_wallet.py", line 786, in generate_signed_transaction
ValueError: Can't send more than 0 mojos in a single transaction
```
**Logs from 3th attempt ~417 offers:**

`2023-02-13T06:12:59.167 wallet chia.wallet.cat_wallet.cat_wallet: INFO     Confirmed balance for cat wallet 12 is 9953000`

dropped to after **~aprox.9 milliseconds**

```
2023-02-13T06:13:09.625 wallet chia.wallet.cat_wallet.cat_wallet: INFO     Confirmed balance for cat wallet 12 is 3709000
```
......

```
2023-02-13T06:13:13.777 wallet chia.wallet.cat_wallet.cat_wallet: WARNING  Can't select amount higher than our spendable balance.  Amount: 1000, spendable: 0
2023-02-13T06:13:13.778 wallet chia.wallet.trade_manager  : ERROR    Error with creating trade offer: <class 'ValueError'>Traceback (most recent call last):
  File "chia/wallet/trade_manager.py", line 493, in _create_offer_for_ids
    coins_to_offer[id] = await wallet.get_coins_to_offer(
  File "chia/wallet/cat_wallet/cat_wallet.py", line 886, in get_coins_to_offer
    return await self.select_coins(amount, min_coin_amount=min_coin_amount, max_coin_amount=max_coin_amount)
  File "chia/wallet/cat_wallet/cat_wallet.py", line 472, in select_coins
    coins = await select_coins(
  File "chia/wallet/coin_selection.py", line 39, in select_coins
    raise ValueError(error_msg)
ValueError: Can't select amount higher than our spendable balance.  Amount: 1000, spendable: 0
```

..............

```
2023-02-13T06:13:13.778 wallet chia.rpc.util              : WARNING  Error while handling message: Traceback (most recent call last):
  File "chia/rpc/util.py", line 18, in inner
    res_object = await f(request_data)
  File "chia/rpc/wallet_rpc_api.py", line 1485, in create_offer_for_ids
    result = await self.service.wallet_state_manager.trade_manager.create_offer_for_ids(
  File "chia/wallet/trade_manager.py", line 407, in create_offer_for_ids
    raise Exception(f"Error creating offer: {result[2]}")
Exception: Error creating offer: Can't select amount higher than our spendable balance.  Amount: 1000, spendable: 0

2023-02-13T06:13:15.549 full_node chia.full_node.full_node: INFO     🌱 Updated peak to height 3242174

```

Please review the latest log data and advise how to fix this odd issue.


Thank you in advance🌱 
BWCC🍀

**Comment by emlowe** [comment]
This is likely due to the coin set model - your spendable balance is zero because although your total balance would be sufficient, that is locked up in coins already in use and so those coins cannot be otherwise used until you get change back - which won't happen until the offer is complete. Generally when you see spendable balance is zero, it is because all your coins are locked into pending transactions or offers

**Comment by bwccnft** [comment]
This is not the case here, we are splitting the CAT to a single coin (with value 1) and than creating an offer with multiple assets (1 NFT+1 NFT+ 1 CAT). Script is verifying that `pending_coin_removal_count` is 0, next splits the CAT to single coin, waits for the coin and then creates the offer file. It runs fine until hits the state described on previous post. The offer locks the  `"spendable_balance" ` in our case the correct amount is `**6234000**` with  `"confirmed_wallet_balance":` **9953000**, then  `"confirmed_wallet_balance":` drops to **3522000** and `"spendable_balance" ` to **0** even that we have specify to use 1 CAT to create the offer. See the output from the log file:

`2023-02-12T**09:32:07.840** wallet chia.wallet.cat_wallet.cat_wallet: INFO     Confirmed balance for cat wallet 12 is **9953000**`
...

`2023-02-12T**09:32:14.322** wallet chia.wallet.cat_wallet.cat_wallet: INFO     Confirmed balance for cat wallet 12 is **3522000**`

Wallet balance **before** hits the defect:

```
    "wallet_balance": {
        "asset_id": "76f8a24339230dcf8f83d79a6d7823929671f9dcc564583ae17f5aafaeceb68c",
        "confirmed_wallet_balance": 9953000,
        "max_send_amount": 6234000,
        "pending_change": 0,
        "pending_coin_removal_count": 0,
        "spendable_balance": 6234000,
        "unconfirmed_wallet_balance": 9953000,
        "unspent_coin_count": 3745,
    }
}
```
Few times, **`Pending Total Balance:  1815209.0  (1815209000 mojo)`** when up to 1815209.0, this is defiantly wrong, because we have minted total of 9999 CATs
```
   - Total Balance:                 9953.0  (9953000 mojo)
   - Pending Total Balance:  1815209.0  (1815209000 mojo)
   - Spendable:                     6292.0  (6292000 mojo)
   - Type:                               CAT
   - Asset ID:                         76f8a24339230dcf8f83d79a6d7823929671f9dcc564583ae17f5aafaeceb68c
```

Wallet balance **after** hits the defect:
```
{
    "wallet_balance": {
        "asset_id": "76f8a24339230dcf8f83d79a6d7823929671f9dcc564583ae17f5aafaeceb68c",
        "confirmed_wallet_balance": 9953000,
        "max_send_amount": 0,
        "pending_change": 0,
        "pending_coin_removal_count": 0,
        "spendable_balance": 0,
        "unconfirmed_wallet_balance": 9953000,
        "unspent_coin_count": 3745,
    }
```
To recover from this condition, we are canceling the last 1-5 offers `chia wallet cancel_offer --id`, because we are not sure which one caused the issue, once the offers are in `CANCELED` state, we are re-syncing the wallet db to restore the correct ` "spendable_balance"` value and performing Walled DB backup to keep all offer files. In this case `cancel_offer` is not working as expected (when executed should return the correct amount e.g.  ` "spendable_balance"` **6234000**)

Let me know if you need additional information or clarifications on this matter.

Thank you in advances :seedling:

**Comment by emlowe** [comment]
Created a new bug based on follow-up comments and closing this one specifically about SQL variables
