### ISSUE TITLE
[Bug] - get_transaction_memo RPC response can't be converted to JSON

### ISSUE THREAD

**Issue by paninaro** [Chia-Network/chia-blockchain#14511]
The RPC response is lost when the web server code attempts to JSON encode the response body:

```
2023-02-07T11:20:25.230 wallet aiohttp.server             : ERROR    Error handling request
Traceback (most recent call last):
  File "/Users/jeffc/src/macos/chia-blockchain/venv/lib/python3.10/site-packages/aiohttp/web_protocol.py", line 433, in _handle_request
    resp = await request_handler(request)
  File "/Users/jeffc/src/macos/chia-blockchain/venv/lib/python3.10/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/Users/jeffc/src/macos/chia-blockchain/chia/rpc/util.py", line 31, in inner
    return obj_to_response(res_object)
  File "/Users/jeffc/src/macos/chia-blockchain/chia/util/json_util.py", line 41, in obj_to_response
    json_str = dict_to_json_str(o)
  File "/Users/jeffc/src/macos/chia-blockchain/chia/util/json_util.py", line 33, in dict_to_json_str
    json_str = json.dumps(o, cls=EnhancedJSONEncoder, sort_keys=True)
  File "/usr/local/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/lib/python3.10/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/usr/local/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/lib/python3.10/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/lib/python3.10/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
TypeError: keys must be str, int, float, bool or None, not bytes
```

The issue is that `compute_memos()` returns an object with keys that are `bytes` values.

Example:

```
(Pdb) compute_memos(tr.spend_bundle)
{b'.\xbf\xf2\xdbW\x8d;\x1cv\xa6\x12P\xc0\x18\x8d\xbe\x9e\xe4?\x10\xf4\x1c\xdeecc\xc0\xcajD\xa2p': [b'Keep the change, ya filthy animal']}
```

**Comment by paninaro** [comment]
Fixed in PR https://github.com/Chia-Network/chia-blockchain/pull/14513
