### ISSUE TITLE
[Bug] wallet does not show up recent transactions after updating from 1.5.0 to 1.7.0

### ISSUE THREAD

**Issue by hbroer** [Chia-Network/chia-blockchain#14595]
### What happened?

Old 1.5 installation was last started ~Februar 11. I updated to 1.7.0 today and let it sync. Wallet shows it is synced now. Full node shows that it is synced and on February 16, 2023 5:02 PM now. Wallets last transaction is still February 10, 2023 10:20 PM and balance is the old too. I have an incoming transaction each day, so it is missing the last five incomming transactions. They exist on xchscan. Log is messy but I don't think the entries are related. Restarting the Chia App did not work.

### Version

1.7.0

### What platform are you using?

Windows

### What ui mode are you using?

GUI

### Relevant log output

```shell
2023-02-16T16:52:09.829 wallet chia.wallet.wallet_node    : WARNING  Keyring is locked
2023-02-16T16:52:11.805 wallet chia.rpc.rpc_server        : WARNING  Error while handling message: Traceback (most recent call last):
  File "chia\rpc\rpc_server.py", line 331, in safe_handle
  File "chia\rpc\rpc_server.py", line 322, in ws_api
  File "chia\rpc\wallet_rpc_api.py", line 1194, in get_notifications
  File "chia\wallet\wallet_node.py", line 147, in wallet_state_manager
RuntimeError: wallet state manager not assigned

2023-02-16T16:52:11.909 wallet chia.rpc.rpc_server        : WARNING  Error while handling message: Traceback (most recent call last):
  File "chia\rpc\rpc_server.py", line 331, in safe_handle
  File "chia\rpc\rpc_server.py", line 322, in ws_api
  File "chia\rpc\wallet_rpc_api.py", line 501, in get_sync_status
  File "chia\wallet\wallet_node.py", line 147, in wallet_state_manager
RuntimeError: wallet state manager not assigned

2023-02-16T16:52:11.912 wallet chia.rpc.rpc_server        : WARNING  Error while handling message: Traceback (most recent call last):
  File "chia\rpc\rpc_server.py", line 331, in safe_handle
  File "chia\rpc\rpc_server.py", line 322, in ws_api
  File "chia\rpc\wallet_rpc_api.py", line 561, in get_wallets
  File "chia\wallet\wallet_node.py", line 147, in wallet_state_manager
RuntimeError: wallet state manager not assigned

2023-02-16T16:52:21.950 wallet chia.rpc.rpc_server        : WARNING  Error while handling message: Traceback (most recent call last):
  File "chia\rpc\rpc_server.py", line 331, in safe_handle
  File "chia\rpc\rpc_server.py", line 322, in ws_api
  File "chia\rpc\wallet_rpc_api.py", line 501, in get_sync_status
  File "chia\wallet\wallet_node.py", line 147, in wallet_state_manager
RuntimeError: wallet state manager not assigned

2023-02-16T16:52:31.975 wallet chia.rpc.rpc_server        : WARNING  Error while handling message: Traceback (most recent call last):
  File "chia\rpc\rpc_server.py", line 331, in safe_handle
  File "chia\rpc\rpc_server.py", line 322, in ws_api
  File "chia\rpc\wallet_rpc_api.py", line 501, in get_sync_status
  File "chia\wallet\wallet_node.py", line 147, in wallet_state_manager
RuntimeError: wallet state manager not assigned

2023-02-16T16:52:48.454 full_node chia.full_node.mempool_manager: WARNING  pre_validate_spendbundle took 2.3255 seconds for 5bdef4fff6eaec39d91dc43489464c5e403b5e740b59f75b5e4744e9f3359ec2
2023-02-16T16:52:48.456 full_node chia.full_node.mempool_manager: WARNING  pre_validate_spendbundle took 2.3195 seconds for 73bf10e8d830d4c092f6d910ea250db55e1df6a6de98f2622d479d6d87fa1a48
2023-02-16T16:52:48.458 full_node chia.full_node.mempool_manager: WARNING  pre_validate_spendbundle took 2.3205 seconds for 65b21d4ad6bf4161155efc63c88ad08d0ed365de5362b9c5822fe2c3a5c9b82d
2023-02-16T16:52:48.459 full_node chia.full_node.mempool_manager: WARNING  pre_validate_spendbundle took 2.3115 seconds for 4ec96edc2fbff4430779dfe691fab7be650c3331ecc92e1603f8e71ff7995ccf
2023-02-16T16:52:48.461 full_node chia.full_node.mempool_manager: WARNING  pre_validate_spendbundle took 2.3125 seconds for be9330782b2b5e72fa35b28d6e2e216c9edb017b18f43d61ddee0f78c54bdb30
2023-02-16T16:52:48.463 full_node chia.full_node.mempool_manager: WARNING  pre_validate_spendbundle took 2.3425 seconds for b6f0aad67a57a9bd14ce78a38bc7dc8edec075f765eee9d29c7f110d83b3a60f
2023-02-16T16:52:48.464 full_node chia.full_node.mempool_manager: WARNING  pre_validate_spendbundle took 2.3155 seconds for 69e47c2892c0b8d494681170a2d8d3bd514f6a58cf0c6c7fbb0ec4562841e571
2023-02-16T16:52:48.466 full_node chia.full_node.mempool_manager: WARNING  pre_validate_spendbundle took 2.3175 seconds for 5a21f6bc5bfb9666118aa3d798f125a9f3eca0f3aac6e083d4f47d39210db194
2023-02-16T16:52:48.467 full_node chia.full_node.mempool_manager: WARNING  pre_validate_spendbundle took 2.3185 seconds for 801ef656871bd1b56ae05deea67c83308652bf46b8c672e7ef4c61ebc0bb2d96
2023-02-16T16:52:48.469 full_node chia.full_node.mempool_manager: WARNING  pre_validate_spendbundle took 2.3205 seconds for a3f2a0697a21c7800466b843c45d1261e088df6a17333adc6404a3144a088c68
2023-02-16T16:52:48.471 full_node chia.full_node.mempool_manager: WARNING  pre_validate_spendbundle took 2.3215 seconds for 84d78b9811b2b4ce79b55b2208d5a9e8473ec8d264dfa7c3990b22cf2d4c523f
2023-02-16T16:52:48.508 full_node chia.full_node.mempool_manager: WARNING  pre_validate_spendbundle took 2.1565 seconds for 4dbbd8376eb3d3d348ca5d6cb8a1ba78e87ce7d6c1b4fb4c7fcd1ac7f1fa09d0
2023-02-16T16:52:48.617 full_node chia.full_node.mempool_manager: WARNING  pre_validate_spendbundle took 2.2635 seconds for 65d4d41d6106d86a1c872cb1402255a5c751aa0faba403fdca7ef92db5f750ca
2023-02-16T16:52:48.639 full_node chia.full_node.mempool_manager: WARNING  pre_validate_spendbundle took 2.2865 seconds for dce5bd2829f523a2d086f91b96eb8a47f93368b02a6ee880514bf77c217b5dbe
2023-02-16T16:52:48.689 full_node chia.full_node.mempool_manager: WARNING  pre_validate_spendbundle took 2.3365 seconds for fd1e1f0d3af899d0c6760acc161b30f6391fadfa30e54bdb0f9f695fafc17de9
2023-02-16T16:52:48.822 full_node chia.full_node.mempool_manager: WARNING  pre_validate_spendbundle took 2.5806 seconds for 3d6d8078b39c9a404688c6df706d7d41b90a9a14eb7ab58ad0140bcce492ddba
2023-02-16T16:52:50.237 full_node chia.full_node.full_node: WARNING  Block validation time: 3.22 seconds, pre_validation time: 3.20 seconds, cost: None header_hash: 608e5d96f7ec514151dd69dd73b3769ea7ce627bd5a4fee0a716490aba353f1f height: 3258198
2023-02-16T16:59:45.817 full_node chia.full_node.full_node: WARNING  Block validation time: 2.25 seconds, pre_validation time: 1.28 seconds, cost: 5474360907, percent full: 49.767% header_hash: d5731a4534fa4c62ccc0e123e26777627e867c05d854c6e205dd957f4beaed80 height: 3258217
```

**Comment by hbroer** [comment]
Theere are 5 entries in the log related to the wallet, but I still don't think it is the reason because before the restart there was also some of that messages but more. But the error itself is new after update. 

```
2023-02-11T20:02:34.057 full_node full_node_server        : WARNING  Cannot write to closing transport 91.85.198.27
2023-02-16T15:28:14.572 wallet chia.wallet.wallet_node    : WARNING  Keyring is locked
2023-02-16T15:28:16.408 wallet chia.rpc.rpc_server        : WARNING  Error while handling message: Traceback (most recent call last):
  File "chia\rpc\rpc_server.py", line 331, in safe_handle
  File "chia\rpc\rpc_server.py", line 322, in ws_api
  File "chia\rpc\wallet_rpc_api.py", line 1194, in get_notifications
  File "chia\wallet\wallet_node.py", line 147, in wallet_state_manager
RuntimeError: wallet state manager not assigned

2023-02-16T15:28:16.562 wallet chia.rpc.rpc_server        : WARNING  Error while handling message: Traceback (most recent call last):
  File "chia\rpc\rpc_server.py", line 331, in safe_handle
  File "chia\rpc\rpc_server.py", line 322, in ws_api
  File "chia\rpc\wallet_rpc_api.py", line 501, in get_sync_status
  File "chia\wallet\wallet_node.py", line 147, in wallet_state_manager
RuntimeError: wallet state manager not assigned

2023-02-16T15:28:16.565 wallet chia.rpc.rpc_server        : WARNING  Error while handling message: Traceback (most recent call last):
  File "chia\rpc\rpc_server.py", line 331, in safe_handle
  File "chia\rpc\rpc_server.py", line 322, in ws_api
  File "chia\rpc\wallet_rpc_api.py", line 561, in get_wallets
  File "chia\wallet\wallet_node.py", line 147, in wallet_state_manager
RuntimeError: wallet state manager not assigned

2023-02-16T15:28:26.584 wallet chia.rpc.rpc_server        : WARNING  Error while handling message: Traceback (most recent call last):
  File "chia\rpc\rpc_server.py", line 331, in safe_handle
  File "chia\rpc\rpc_server.py", line 322, in ws_api
  File "chia\rpc\wallet_rpc_api.py", line 501, in get_sync_status
  File "chia\wallet\wallet_node.py", line 147, in wallet_state_manager
RuntimeError: wallet state manager not assigned

2023-02-16T15:28:36.599 wallet chia.rpc.rpc_server        : WARNING  Error while handling message: Traceback (most recent call last):
  File "chia\rpc\rpc_server.py", line 331, in safe_handle
  File "chia\rpc\rpc_server.py", line 322, in ws_api
  File "chia\rpc\wallet_rpc_api.py", line 501, in get_sync_status
  File "chia\wallet\wallet_node.py", line 147, in wallet_state_manager
RuntimeError: wallet state manager not assigned

2023-02-16T15:28:46.614 wallet chia.rpc.rpc_server        : WARNING  Error while handling message: Traceback (most recent call last):
  File "chia\rpc\rpc_server.py", line 331, in safe_handle
  File "chia\rpc\rpc_server.py", line 322, in ws_api
  File "chia\rpc\wallet_rpc_api.py", line 501, in get_sync_status
  File "chia\wallet\wallet_node.py", line 147, in wallet_state_manager
RuntimeError: wallet state manager not assigned

2023-02-16T15:28:56.625 wallet chia.rpc.rpc_server        : WARNING  Error while handling message: Traceback (most recent call last):
  File "chia\rpc\rpc_server.py", line 331, in safe_handle
  File "chia\rpc\rpc_server.py", line 322, in ws_api
  File "chia\rpc\wallet_rpc_api.py", line 501, in get_sync_status
  File "chia\wallet\wallet_node.py", line 147, in wallet_state_manager
RuntimeError: wallet state manager not assigned

2023-02-16T15:36:08.563 full_node chia.full_node.full_node: WARNING  Block pre-validation time: 12.45 seconds (32 blocks, start height: 3237462)
2023-02-16T15:37:00.989 full_node chia.full_node.full_node: WARNING  Block pre-validation time: 10.02 seconds (32 blocks, start height: 3237718)
2023-02-16T15:50:27.549 full_node chia.full_node.full_node: WARNING  Block pre-validation time: 18.12 seconds (32 blocks, start height: 3242038)
2023-02-16T15:50:46.385 full_node chia.full_node.full_node: WARNING  Block pre-validation time: 16.33 seconds (32 blocks, start height: 3242070)
2023-02-16T16:11:04.582 full_node chia.full_node.full_node: WARNING  Block pre-validation time: 17.77 seconds (32 blocks, start height: 3248342)
2023-02-16T16:21:06.205 full_node chia.full_node.full_node: WARNING  Block pre-validation time: 12.11 seconds (32 blocks, start height: 3251446)
2023-02-16T16:21:18.527 full_node chia.full_node.full_node: WARNING  Block pre-validation time: 10.38 seconds (32 blocks, start height: 3251478)
2023-02-16T16:24:32.985 full_node chia.full_node.full_node: WARNING  Block pre-validation time: 10.36 seconds (32 blocks, start height: 3252470)
2023-02-16T16:26:07.497 full_node chia.full_node.full_node: WARNING  Block pre-validation time: 11.98 seconds (32 blocks, start height: 3252950)
2023-02-16T16:33:18.434 full_node chia.full_node.full_node: WARNING  Block pre-validation time: 12.00 seconds (32 blocks, start height: 3255222)
2023-02-16T16:42:06.356 full_node chia.full_node.full_node: WARNING  Block pre-validation time: 11.98 seconds (32 blocks, start height: 3257654)
```

**Comment by hbroer** [comment]
Solution: Shutdown, then deleting the `~/.chia/mainnet/wallet/db` folder, and start again. Transactions shown up in short time.

A bit annoying that the wallet database can be bad for what ever reason without any log information, and on the other side the log is flooded with new unneeded information (comments in web full of "yea just ignore that") like every new release. ^^ There is something wrong in QA ^^ The "wallet state manager not assigned" still appear.

**Comment by MumfMeisterT** [comment]
Did you have to re-enter your 24 words after the reboot?

**Comment by hbroer** [comment]
No.

**Comment by bzeitler69** [comment]
@MumfMeisterT I had to to re-add keys after upgrade to 1.7.0. Without that it didn't work.

**Comment by ZdravkoRistic** [comment]
how to best upgrade version ? re install or ?
Because i have same problem

**Comment by MumfMeisterT** [comment]
> @MumfMeisterT I had to to re-add keys after upgrade to 1.7.0. Without that it didn't work.

@emlowe ^

**Comment by danieljperry** [comment]
Closing -- this issue has a workaround supplied. Resyncing a wallet is also easier today than it was at the time this ticket was opened.
