### ISSUE TITLE
[Bug] cancel_offer in 1.7 of an offer in pending cancel state reports error

### ISSUE THREAD

**Issue by johnathon-b** [Chia-Network/chia-blockchain#14632]
### What happened?

I am unable to cancel an offer that is stuck in a Pending Cancel state with Chia 1.7.0 wallet.

```
chia wallet cancel_offer -id 55a6c69a9b335a30933abf2b2d04e08f3d94a1a37f82bb5f4b180dbd8459cc3d -m 0.001 -f 1096298047
```

I get the following error within the terminal:
```
Exception from 'wallet' 6:
Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.10/site-packages/chia/cmds/cmds_util.py", line 100, in get_any_service_client
    yield node_client, config, fingerprint
  File "/opt/homebrew/lib/python3.10/site-packages/chia/cmds/cmds_util.py", line 211, in execute_with_wallet
    await function(extra_params, wallet_client, new_fp)
  File "/opt/homebrew/lib/python3.10/site-packages/chia/cmds/wallet_funcs.py", line 691, in cancel_offer
    trade_record = await wallet_client.get_offer(id, file_contents=True)
  File "/opt/homebrew/lib/python3.10/site-packages/chia/rpc/wallet_rpc_client.py", line 706, in get_offer
    offer_str = bytes(Offer.from_bech32(res["offer"])).hex() if file_contents else ""
  File "/opt/homebrew/lib/python3.10/site-packages/chia/wallet/trading/offer.py", line 599, in from_bech32
    return cls.try_offer_decompression(decoded_bytes)
  File "/opt/homebrew/lib/python3.10/site-packages/chia/wallet/trading/offer.py", line 582, in try_offer_decompression
    return cls.from_compressed(offer_bytes)
  File "/opt/homebrew/lib/python3.10/site-packages/chia/wallet/trading/offer.py", line 577, in from_compressed
    return Offer.from_bytes(decompress_object_with_puzzles(compressed_bytes))
  File "/opt/homebrew/lib/python3.10/site-packages/chia/wallet/util/puzzle_compression.py", line 72, in decompress_object_with_puzzles
    raise CompressionVersionError(version)
chia.wallet.util.puzzle_compression.CompressionVersionError: 6
```
 This needs better error handling to tell me what's going on.

1.6.2 wallet cannot see the offer file correctly. Does not mention a CAT2.
```
chia wallet get_offers -f 1096298047 -id 55a6c69a9b335a30933abf2b2d04e08f3d94a1a37f82bb5f4b180dbd8459cc3d -s

Record with id: 55a6c69a9b335a30933abf2b2d04e08f3d94a1a37f82bb5f4b180dbd8459cc3d
---------------
Created at: 2023-02-20 14:53:05
Confirmed at: Not confirmed
Accepted at: N/A
Status: PENDING_CANCEL
Summary:
  OFFERED:
  REQUESTED:
    - XCH (Wallet ID: 1): 5.455785405774 (5455785405774 mojos)
Pending Outbound Balances:
    - Unknown: 240000 mojos
Included Fees: 0
---------------
```

1.7.0 see's the offer file in a pending state within the Offers table and in the CLI.

```
chia wallet get_offers -f 1096298047 -id 55a6c69a9b335a30933abf2b2d04e08f3d94a1a37f82bb5f4b180dbd8459cc3d -s
Exception from 'wallet' 6:
Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.10/site-packages/chia/cmds/cmds_util.py", line 100, in get_any_service_client
    yield node_client, config, fingerprint
  File "/opt/homebrew/lib/python3.10/site-packages/chia/cmds/cmds_util.py", line 211, in execute_with_wallet
    await function(extra_params, wallet_client, new_fp)
  File "/opt/homebrew/lib/python3.10/site-packages/chia/cmds/wallet_funcs.py", line 564, in get_offers
    records = [await wallet_client.get_offer(bytes32.from_hexstr(id), file_contents)]
  File "/opt/homebrew/lib/python3.10/site-packages/chia/rpc/wallet_rpc_client.py", line 706, in get_offer
    offer_str = bytes(Offer.from_bech32(res["offer"])).hex() if file_contents else ""
  File "/opt/homebrew/lib/python3.10/site-packages/chia/wallet/trading/offer.py", line 599, in from_bech32
    return cls.try_offer_decompression(decoded_bytes)
  File "/opt/homebrew/lib/python3.10/site-packages/chia/wallet/trading/offer.py", line 582, in try_offer_decompression
    return cls.from_compressed(offer_bytes)
  File "/opt/homebrew/lib/python3.10/site-packages/chia/wallet/trading/offer.py", line 577, in from_compressed
    return Offer.from_bytes(decompress_object_with_puzzles(compressed_bytes))
  File "/opt/homebrew/lib/python3.10/site-packages/chia/wallet/util/puzzle_compression.py", line 72, in decompress_object_with_puzzles
    raise CompressionVersionError(version)
chia.wallet.util.puzzle_compression.CompressionVersionError: 6
```

Log states that it's double spent. 

### Version

1.7.0

### What platform are you using?

macOS

### What ui mode are you using?

CLI

### Relevant log output

```shell
2023-02-21T09:12:33.735 wallet chia.wallet.wallet_node    : WARNING  SpendBundle has been rejected by the FullNode. {'error': 'DOUBLE_SPEND', 'status': 3, 'txid': '0xfb83a6a363a2f9229cb7383b4a6ade8c154dbefb4f7d5fea5435c27592e76413'}
2023-02-21T09:12:33.778 wallet chia.wallet.wallet_node    : WARNING  SpendBundle has been rejected by the FullNode. {'error': 'DOUBLE_SPEND', 'status': 3, 'txid': '0x9d15fa3a2e097f9e5774c609888a8f3350aa4b1cba91596c82f661ee010a9c04'}
```

**Comment by MumfMeisterT** [comment]
#14621

**Comment by trepca** [comment]
can you try running main branch version of the wallet?

**Comment by emlowe** [comment]
Various fixes merged since initial report, closing issue
