### ISSUE TITLE
[BUG]Can't create plot files

### ISSUE THREAD

**Issue by JohnnyFFM** [Chia-Network/chia-blockchain#1467]
Plotting Always interrupts with:

'''
Total matches: 4273096874
Caught plotting error: Matches do not match with number of write entries 4273096874 4273037902
Traceback (most recent call last):
  File "src\cmds\chia.py", line 63, in <module>
  File "src\cmds\chia.py", line 59, in main
  File "click\core.py", line 1026, in __call__
  File "click\core.py", line 956, in main
  File "click\core.py", line 1518, in invoke
  File "click\core.py", line 1518, in invoke
  File "click\core.py", line 1280, in invoke
  File "click\core.py", line 711, in invoke
  File "click\decorators.py", line 22, in new_func
  File "src\cmds\plots.py", line 134, in create_cmd
  File "src\plotting\create_plots.py", line 176, in create_plots
RuntimeError: Unknown exception
[6568] Failed to execute script chia
'''

Command used:
>chia.exe plots create -t c:\chia\C02\1 -2 c:\chia\C02\2 -d C:\chia\C01

each CXX is root of an ntfs mount on a win10 machine. 64GB ram, Intel i7.

Any idea?

**Comment by JohnnyFFM** [comment]
Machine is faulty, most likely RAM or CPU issue, works on similar machine. Issue closed.
