### ISSUE TITLE
[Bug] error after upgrading to 1.7.0

### ISSUE THREAD

**Issue by terryxsq** [Chia-Network/chia-blockchain#14742]
### What happened?

`chia farm summary` returns an error after upgrading to 1.7.0. it was working before the upgrade.
`Exception from 'wallet' {'error': 'wallet state manager not assigned', 'success': False}:
Traceback (most recent call last):
  File "/home/it/chia-blockchain/chia/cmds/cmds_util.py", line 100, in get_any_service_client
    yield node_client, config, fingerprint
  File "/home/it/chia-blockchain/chia/cmds/farm_funcs.py", line 65, in get_wallets_stats
    return await wallet_client.get_farmed_amount()
  File "/home/it/chia-blockchain/chia/rpc/wallet_rpc_client.py", line 229, in get_farmed_amount
    return await self.fetch("get_farmed_amount", {})
  File "/home/it/chia-blockchain/chia/rpc/rpc_client.py", line 61, in fetch
    raise ValueError(res_json)
ValueError: {'error': 'wallet state manager not assigned', 'success': False}`

This is run on my farmer which does not have any keys. The summary shows 0 plots for my harvesters. The harvesters are connected and the logs shows that they are getting jobs.

### Version

1.7.0

### What platform are you using?

Linux

### What ui mode are you using?

CLI

### Relevant log output

```shell
Exception from 'wallet' {'error': 'wallet state manager not assigned', 'success': False}:
Traceback (most recent call last):
  File "/home/it/chia-blockchain/chia/cmds/cmds_util.py", line 100, in get_any_service_client
    yield node_client, config, fingerprint
  File "/home/it/chia-blockchain/chia/cmds/farm_funcs.py", line 65, in get_wallets_stats
    return await wallet_client.get_farmed_amount()
  File "/home/it/chia-blockchain/chia/rpc/wallet_rpc_client.py", line 229, in get_farmed_amount
    return await self.fetch("get_farmed_amount", {})
  File "/home/it/chia-blockchain/chia/rpc/rpc_client.py", line 61, in fetch
    raise ValueError(res_json)
ValueError: {'error': 'wallet state manager not assigned', 'success': False}
```

**Comment by MumfMeisterT** [comment]
What version did you upgrade from? What does `chia keys show` display?

**Comment by terryxsq** [comment]
> What version did you upgrade from? What does `chia keys show` display?

i upgraded from 1.3.5. i got this solved by generating a new key. previously it was not necessary to generate a key when it is farmer only. my farmer does not have any plots. all my harvesters connect to it.
