### ISSUE TITLE
Chia Full Node won't start after 1.7.1 upgrade [Bug] 

### ISSUE THREAD

**Issue by gyrodec** [Chia-Network/chia-blockchain#14894]
### What happened?

Upgraded to 1.7.1 from 1.7.0. Starting Chia gets to the loading Full Node and never completes:
![image](https://user-images.githubusercontent.com/35155182/227403448-882067f0-5e35-4ac7-9b61-2b363708097c.png)

I found developer tools and found 2 errors in the Console. Output pasted to LOG OUTPUT below.

### Version

1.7.1

### What platform are you using?

Windows

### What ui mode are you using?

GUI

### Relevant log output

```shell
init-prefs.ts:45 SyntaxError: Unexpected token 'e', "en-US" is not valid JSON
    at JSON.parse (<anonymous>)
    at init-prefs.ts:43:56
    at Array.forEach (<anonymous>)
    at init-prefs.ts:36:11
    at u (init-prefs.ts:2:1)
    at Generator.<anonymous> (init-prefs.ts:2:1)
    at Generator.next (init-prefs.ts:2:1)
    at o8 (init-prefs.ts:2:1)
    at i (init-prefs.ts:2:1)
    at init-prefs.ts:2:1
(anonymous)	@	init-prefs.ts:45
init-prefs.ts:45 SyntaxError: Unexpected token 'r', "farming" is not valid JSON
    at JSON.parse (<anonymous>)
    at init-prefs.ts:43:56
    at Array.forEach (<anonymous>)
    at init-prefs.ts:36:11
    at u (init-prefs.ts:2:1)
    at Generator.<anonymous> (init-prefs.ts:2:1)
    at Generator.next (init-prefs.ts:2:1)
    at o8 (init-prefs.ts:2:1)
    at i (init-prefs.ts:2:1)
    at init-prefs.ts:2:1
(anonymous)	@	init-prefs.ts:45
```

**Comment by gyrodec** [comment]
Did some more forum searching. Renamed my config.yml fiel and restarted and it works now.
