### ISSUE TITLE
[Bug] - FAILURE! (Missing derivation '1025' for wallet id '1' )

### ISSUE THREAD

**Issue by xchshark** [Chia-Network/chia-blockchain#14938]
### What happened?

I can't send XCH to the exchange. When I try I get this Error
Missing derivation '1025' for wallet id '1' (hardened=False. I can't upload NFT to exchange. When I try I get this Error
Error creating offer: Missing derivation '1025' for wallet id '1' (hardened=False). I cannot buy NFTs.I can only sell the ones I have. When I try - application action - none. Wallet address does not want to be updated. When I click on the refresh button - application action - none. I have not had support for over 12 hours. It's not normal for me to look for support on GitHub. If you are going to change the World - first provide support to those who use you from the beginning and believe in you! 

*Wallet is connected all the time!

### Version

1.7,1

### What platform are you using?

Windows

### What ui mode are you using?

GUI

**Comment by MumfMeisterT** [comment]
We willl look into this, in the mean time you should try resyncing your wallet.

**Comment by trepca** [comment]
Can you please provide a full stack trace that you see in logs?

**Comment by ctrlaltdel** [comment]
Hi @emlowe, could you please re-open this ticket? Thanks!

Same issue here while trying to send a 1 XCH transaction from a wallet whose derivation index is set to 2352.

Chia version 2.1.3 using the GUI.

Here's the complete log, happy to share any other useful information.

```
2024-01-04T16:54:02.425 daemon __main__                   : DEBUG    Received message: WSMessage(type=<WSMsgType.TEXT: 1>, data='{"command":"send_transaction","data": {"wallet_id":1,"address":"XXXXXXXX","amount":1000000000000,"fee":10000000000},"origin":"wallet_ui","destination":"chia_wallet","ack":false,"request_id":"6461e9e34ecf99fe58244e246ce10cd84a47a451fab565e37de906308bbc48f0"}', extra='')
2024-01-04T16:54:02.426 wallet chia.rpc.rpc_server        : DEBUG    Rpc call <- send_transaction
2024-01-04T16:54:02.426 wallet chia.wallet.wallet         : DEBUG    Generating transaction for: b762929eef2ea4b769bf076c35a31f43288ab3b97d069cca51f7cae4ed07b82f 1000000000000 None
2024-01-04T16:54:02.433 wallet chia.wallet.wallet         : DEBUG    Got back max send amount: XXXXXXXX
2024-01-04T16:54:02.438 wallet chia.wallet.wallet         : DEBUG    About to select coins for amount 1010000000000
2024-01-04T16:54:02.449 wallet chia.wallet.wallet         : DEBUG    Selected coins from knapsack algorithm: {<builtins.Coin object at 0x163b85650>, <builtins.Coin object at 0x110b63a50>, <builtins.Coin object at 0x163b84990>, <builtins.Coin object at 0x163b84d50>, <builtins.Coin object at 0x110b618f0>, <builtins.Coin object at 0x163b85890>}
2024-01-04T16:54:02.450 wallet chia.wallet.wallet         : INFO     coins is not None {<builtins.Coin object at 0x163b85650>, <builtins.Coin object at 0x110b63a50>, <builtins.Coin object at 0x163b84990>,
 <builtins.Coin object at 0x163b84d50>, <builtins.Coin object at 0x110b618f0>, <builtins.Coin object at 0x163b85890>}
2024-01-04T16:54:02.450 wallet chia.wallet.wallet         : INFO     spend_value is 1015965162893 and total_amount is 1010000000000
2024-01-04T16:54:02.557 wallet chia.wallet.wallet_state_manager: DEBUG    Fetching derivation record for: 1928 1 False
2024-01-04T16:54:02.558 wallet chia.rpc.rpc_server        : WARNING  Error while handling message: Traceback (most recent call last):
  File "chia/rpc/rpc_server.py", line 325, in safe_handle
  File "chia/rpc/rpc_server.py", line 316, in ws_api
  File "chia/rpc/util.py", line 82, in rpc_endpoint
  File "chia/rpc/wallet_rpc_api.py", line 1112, in send_transaction
  File "chia/wallet/wallet.py", line 450, in generate_signed_transaction
  File "chia/wallet/wallet.py", line 362, in _generate_unsigned_transaction
  File "chia/wallet/wallet.py", line 196, in get_new_puzzlehash
  File "chia/wallet/wallet_state_manager.py", line 540, in get_unused_derivation_record
ValueError: Missing derivation '1928' for wallet id '1' (hardened=False)

2024-01-04T16:54:02.558 daemon __main__                   : DEBUG    Received message: WSMessage(type=<WSMsgType.TEXT: 1>, data='{"ack": true, "command": "send_transaction", "data": {"error": "Missing derivation \'1928\' for wallet id \'1\' (hardened=False)", "success": false}, "destination": "wallet_ui", "origin": "chia_wallet", "request_id": "6461e9e34ecf99fe58244e246ce10cd84a47a451fab565e37de906308bbc48f0"}', extra='')
```
