### ISSUE TITLE
[Bug] wallet state manager not assigned

### ISSUE THREAD

**Issue by gades** [Chia-Network/chia-blockchain#14957]
### What happened?

I can't run wallet on Mac OS  anymore
<img width="1791" alt="Screenshot 2023-03-31 at 6 48 11 PM" src="https://user-images.githubusercontent.com/4200730/229168728-65979072-9ba6-4419-8643-a9a2b16eb8f0.png">

### Version

1.7.1

### What platform are you using?

macOS

### What ui mode are you using?

GUI

### Relevant log output

```shell
tail -f ~/.chia/mainnet/log/debug.log

2023-03-31T18:47:02.705 wallet chia.rpc.rpc_server        : WARNING  Error while handling message: Traceback (most recent call last):
  File "chia/rpc/rpc_server.py", line 340, in safe_handle
  File "chia/rpc/rpc_server.py", line 331, in ws_api
  File "chia/rpc/wallet_rpc_api.py", line 519, in get_sync_status
  File "chia/wallet/wallet_node.py", line 153, in wallet_state_manager
RuntimeError: wallet state manager not assigned

2023-03-31T18:47:12.715 wallet chia.rpc.rpc_server        : WARNING  Error while handling message: Traceback (most recent call last):
  File "chia/rpc/rpc_server.py", line 340, in safe_handle
  File "chia/rpc/rpc_server.py", line 331, in ws_api
  File "chia/rpc/wallet_rpc_api.py", line 519, in get_sync_status
  File "chia/wallet/wallet_node.py", line 153, in wallet_state_manager
RuntimeError: wallet state manager not assigned

2023-03-31T18:47:22.728 wallet chia.rpc.rpc_server        : WARNING  Error while handling message: Traceback (most recent call last):
  File "chia/rpc/rpc_server.py", line 340, in safe_handle
  File "chia/rpc/rpc_server.py", line 331, in ws_api
  File "chia/rpc/wallet_rpc_api.py", line 519, in get_sync_status
  File "chia/wallet/wallet_node.py", line 153, in wallet_state_manager
RuntimeError: wallet state manager not assigned
```

**Comment by gades** [comment]
Looks like it's the same issue with https://github.com/Chia-Network/chia-blockchain/issues/14595

**Comment by MumfMeisterT** [comment]
Are there any more errors or warnings in your logs? Could you provide full logs for us? thx

**Comment by gades** [comment]
it's duplicate of https://github.com/Chia-Network/chia-blockchain/issues/14595
