### ISSUE TITLE
[Bug] ERROR    Exception: bad bytes32 initializer b'\xf1Iy\x9e\xce\x12_'  

### ISSUE THREAD

**Issue by netserver** [Chia-Network/chia-blockchain#15050]
### What happened?

2023-04-16T21:56:25.451 full_node chia.full_node.full_node: INFO       Finished signage point 3/64: CC: 076075613d68e81ccf67924fb36dd75c4fc7009dad07b9160f8efcd6d75068c3 RC: fbe4e60ab0367d16207d09e542f585a180493d93e4482e47bb18dd82fffdbb65 
2023-04-16T21:56:25.722 full_node full_node_server        : ERROR    Exception: bad bytes32 initializer b'\xf1Iy\x9e\xce\x12_' <class 'ValueError'>, closing connection PeerInfo(_ip=IPv4Address('218.173.23.143'), _port=8449). Traceback (most recent call last):
  File "chia\server\ws_connection.py", line 388, in _api_call
  File "chia\util\api_decorators.py", line 63, in wrapper
  File "chia\util\streamable.py", line 648, in from_bytes
  File "chia\util\streamable.py", line 635, in parse
  File "chia\util\streamable.py", line 443, in <lambda>
  File "chia\util\streamable.py", line 394, in parse_list
  File "chia\util\byte_types.py", line 40, in parse
  File "chia\util\byte_types.py", line 35, in __init__
ValueError: bad bytes32 initializer b'\xf1Iy\x9e\xce\x12_'

2023-04-16T21:56:25.723 full_node full_node_server        : WARNING  Banning 218.173.23.143 for 10 seconds
2023-04-16T21:56:25.724 full_node full_node_server        : INFO     Connection closed: 218.173.23.143, node id: f05ab9f13cceea481ff2efe31b80d50d37606d491fb256eaa15c406c57f8fbd3
2023-04-16T21:56:25.724 full_node chia.full_node.full_node: INFO     peer disconnected PeerInfo(_ip=IPv4Address('218.173.23.143'), _port=8449)

### Version

1.7.1

### What platform are you using?

Windows

### What ui mode are you using?

GUI

**Comment by MumfMeisterT** [comment]
A peer sent you bad data so it was disconnected as designed. This an expected log entry when a peer sends you something bad.
