### ISSUE TITLE
[BUG] `chia start all` failed and GUI not work after restart.

### ISSUE THREAD

**Issue by Colin6618** [Chia-Network/chia-blockchain#1505]
**Describe the bug**
`chia start all` failed after a power lost.

**To Reproduce**

1. My PC lost power while GUI was running, there were plotting threads running as well.
2. Reconnect the power
3. Open GUI, The program is stuck on a screen "Connecting to the Wallet"
4. Try CLI, "chia start all"
5. Error logs as below 

**Expected behavior**
It Works as before

**Screenshots**
```
(venv) m****@MacBook-Pro-*** (v1.0.1.local) % chia start all                                           ~/chia/chia-blockchain
chia_harvester: Already running, use `-r` to restart
chia_timelord_launcher: started
chia_timelord: started
chia_farmer: started
chia_full_node: started
chia_wallet: started
(venv) m****@MacBook-Pro-*** (v1.0.1.local) % Traceback (most recent call last):                       ~/chia/chia-blockchain
  File "/Users/m****/chia/chia-blockchain/venv/bin/chia_full_node", line 33, in <module>
    sys.exit(load_entry_point('chia-blockchain', 'console_scripts', 'chia_full_node')())
  File "/Users/m****/chia/chia-blockchain/src/server/start_full_node.py", line 60, in main
    return run_service(**kwargs)
  File "/Users/m****/chia/chia-blockchain/src/server/start_service.py", line 211, in run_service
    return asyncio.run(async_run_service(*args, **kwargs))
  File "/usr/local/Cellar/python/3.7.2_2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "/usr/local/Cellar/python/3.7.2_2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/base_events.py", line 584, in run_until_complete
    return future.result()
  File "/Users/m****/chia/chia-blockchain/src/server/start_service.py", line 205, in async_run_service
    return await service.run()
  File "/Users/m****/chia/chia-blockchain/src/server/start_service.py", line 150, in run
    await self.start()
  File "/Users/m****/chia/chia-blockchain/src/server/start_service.py", line 121, in start
    await self._node._start(**kwargs)
  File "/Users/m****/chia/chia-blockchain/src/full_node/full_node.py", line 107, in _start
    self.block_store = await BlockStore.create(self.connection)
  File "/Users/m****/chia/chia-blockchain/src/full_node/block_store.py", line 30, in create
    "CREATE TABLE IF NOT EXISTS full_blocks(header_hash text PRIMARY KEY, height bigint,"
  File "/Users/m****/chia/chia-blockchain/venv/lib/python3.7/site-packages/aiosqlite/core.py", line 184, in execute
    cursor = await self._execute(self._conn.execute, sql, parameters)
  File "/Users/m****/chia/chia-blockchain/venv/lib/python3.7/site-packages/aiosqlite/core.py", line 129, in _execute
    return await future
  File "/Users/m****/chia/chia-blockchain/venv/lib/python3.7/site-packages/aiosqlite/core.py", line 102, in run
    result = function()
sqlite3.DatabaseError: database disk image is malformed
Traceback (most recent call last):
  File "/Users/m****/chia/chia-blockchain/venv/bin/chia_wallet", line 33, in <module>
    sys.exit(load_entry_point('chia-blockchain', 'console_scripts', 'chia_wallet')())
  File "/Users/m****/chia/chia-blockchain/src/server/start_wallet.py", line 86, in main
    return run_service(**kwargs)
  File "/Users/m****/chia/chia-blockchain/src/server/start_service.py", line 211, in run_service
    return asyncio.run(async_run_service(*args, **kwargs))
  File "/usr/local/Cellar/python/3.7.2_2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "/usr/local/Cellar/python/3.7.2_2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/base_events.py", line 584, in run_until_complete
    return future.result()
  File "/Users/m****/chia/chia-blockchain/src/server/start_service.py", line 205, in async_run_service
    return await service.run()
  File "/Users/m****/chia/chia-blockchain/src/server/start_service.py", line 150, in run
    await self.start()
  File "/Users/m****/chia/chia-blockchain/src/server/start_service.py", line 121, in start
    await self._node._start(**kwargs)
  File "/Users/m****/chia/chia-blockchain/src/wallet/wallet_node.py", line 148, in _start
    self.wallet_state_manager = await WalletStateManager.create(private_key, self.config, path, self.constants)
  File "/Users/m****/chia/chia-blockchain/src/wallet/wallet_state_manager.py", line 118, in create
    self.coin_store = await WalletCoinStore.create(self.db_connection)
  File "/Users/m****/chia/chia-blockchain/src/wallet/wallet_coin_store.py", line 30, in create
    "CREATE TABLE IF NOT EXISTS coin_record("
  File "/Users/m****/chia/chia-blockchain/venv/lib/python3.7/site-packages/aiosqlite/core.py", line 184, in execute
    cursor = await self._execute(self._conn.execute, sql, parameters)
  File "/Users/m****/chia/chia-blockchain/venv/lib/python3.7/site-packages/aiosqlite/core.py", line 129, in _execute
    return await future
  File "/Users/m****/chia/chia-blockchain/venv/lib/python3.7/site-packages/aiosqlite/core.py", line 102, in run
    result = function()
sqlite3.DatabaseError: database disk image is malformed
Traceback (most recent call last):
  File "/Users/m****/chia/chia-blockchain/venv/bin/chia_timelord_launcher", line 33, in <module>
    sys.exit(load_entry_point('chia-blockchain', 'console_scripts', 'chia_timelord_launcher')())
  File "/Users/m****/chia/chia-blockchain/src/timelord/timelord_launcher.py", line 107, in main
    loop.run_until_complete(spawn_all_processes(config, net_config))
  File "/usr/local/Cellar/python/3.7.2_2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/base_events.py", line 584, in run_until_complete
    return future.result()
  File "/Users/m****/chia/chia-blockchain/src/timelord/timelord_launcher.py", line 85, in spawn_all_processes
    await asyncio.gather(*awaitables)
  File "/Users/m****/chia/chia-blockchain/src/timelord/timelord_launcher.py", line 45, in spawn_process
    path_to_vdf_client = find_vdf_client()
  File "/Users/m****/chia/chia-blockchain/src/timelord/timelord_launcher.py", line 39, in find_vdf_client
    raise FileNotFoundError("can't find vdf_client binary")
FileNotFoundError: can't find vdf_client binary
```

**Desktop (please complete the following information):**

- OS: [MacOS 10.15.6]
- CPU: [2.6G i7 ] 
- Machine: Macbook Pro 2019 

**Additional context**
Is it ok to delete he files under .chia/mainnet/db. It seems that the sqllite database is broken. Any clue how to fix that..

**Comment by hoffmang9** [comment]
Don't chia start all as you do not need to run timelord. You can delete the dbs - you will just have to resync them.

**Comment by hoffmang9** [comment]
chia start farmer is all you need

**Comment by Colin6618** [comment]
Thanks @hoffmang9 , I'll delete the dbs and try to open the GUI again.

**Comment by Colin6618** [comment]
Works after deleting all dbs
