### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by aaronscientiae** [Chia-Network/chia-blockchain#15109]
### What happened?

Sending 42 sbx to an address I get a popup "inner_address"

### Version

1.8.0rc1

### What platform are you using?

Linux

### What ui mode are you using?

GUI

### Relevant log output

```shell
2023-04-24T09:31:42.684 wallet chia.rpc.rpc_server        : WARNING  Error while handling message: Traceback (most recent call last):
  File "chia/rpc/rpc_server.py", line 340, in safe_handle
  File "chia/rpc/rpc_server.py", line 331, in ws_api
  File "chia/rpc/wallet_rpc_api.py", line 1490, in cat_get_asset_id
  File "chia/wallet/wallet_state_manager.py", line 262, in get_wallet
KeyError: 36

2023-04-24T09:31:42.685 wallet chia.rpc.rpc_server        : WARNING  Error while handling message: Traceback (most recent call last):
  File "chia/rpc/rpc_server.py", line 340, in safe_handle
  File "chia/rpc/rpc_server.py", line 331, in ws_api
  File "chia/rpc/wallet_rpc_api.py", line 1490, in cat_get_asset_id
  File "chia/wallet/wallet_state_manager.py", line 262, in get_wallet
KeyError: 37

2023-04-24T09:32:45.258 wallet chia.wallet.wallet_state_manager: ERROR    Failed to add coin_state: CoinState { coin: Coin { parent_coin_info: cfd6da02e09d56c4db8b7e7f36d71e9a18dd1001283b86f4d050c778fcd20b9a, puzzle_hash: 781197f59608b1174833d74f8901c198ff87f8b75145a87005f74f0cc1439f45, amount: 1 }, spent_height: Some(3000685), created_height: Some(2691728) }, error: 15
Traceback (most recent call last):
  File "chia/wallet/wallet_state_manager.py", line 1253, in _add_coin_states
  File "chia/wallet/wallet_state_manager.py", line 262, in get_wallet
KeyError: 15
2023-04-24T09:39:20.805 wallet chia.wallet.wallet_state_manager: ERROR    Failed to add coin_state: CoinState { coin: Coin { parent_coin_info: 09e52f5e3ec5b4326e006cd46e1926ae8114c326da60d2f3e3a05da881ae5a12, puzzle_hash: 9f53179f0e5d4f5345e45714d0218e547a197ce5bc5afef2dfa8d668c61df164, amount: 1 }, spent_height: Some(2876949), created_height: Some(2848325) }, error: 31
Traceback (most recent call last):
  File "chia/wallet/wallet_state_manager.py", line 1253, in _add_coin_states
  File "chia/wallet/wallet_state_manager.py", line 262, in get_wallet
KeyError: 31
2023-04-24T09:41:56.764 wallet chia.rpc.rpc_server        : WARNING  Error while handling message: Traceback (most recent call last):
  File "chia/rpc/rpc_server.py", line 340, in safe_handle
  File "chia/rpc/rpc_server.py", line 331, in ws_api
  File "chia/rpc/wallet_rpc_api.py", line 1408, in cat_spend
KeyError: 'inner_address'

2023-04-24T09:42:08.883 wallet chia.rpc.rpc_server        : WARNING  Error while handling message: Traceback (most recent call last):
  File "chia/rpc/rpc_server.py", line 340, in safe_handle
  File "chia/rpc/rpc_server.py", line 331, in ws_api
  File "chia/rpc/wallet_rpc_api.py", line 1408, in cat_spend
KeyError: 'inner_address'

2023-04-24T09:43:01.433 wallet chia.rpc.rpc_server        : WARNING  Error while handling message: Traceback (most recent call last):
  File "chia/rpc/rpc_server.py", line 340, in safe_handle
  File "chia/rpc/rpc_server.py", line 331, in ws_api
  File "chia/rpc/wallet_rpc_api.py", line 1408, in cat_spend
KeyError: 'inner_address'
```

**Comment by esaung** [comment]
fixed in the RC3 build, please try that build and let us if you ares till seeing the issue.

**Comment by aaronscientiae** [comment]
Solved!
