### ISSUE TITLE
[Bug] 1.8.0 introduces a DB downgrade issue

### ISSUE THREAD

**Issue by emlowe** [Chia-Network/chia-blockchain#15132]
### What happened?

1.8.0 (and main) introduce 2 new columns to the `coin_record` store here: https://github.com/Chia-Network/chia-blockchain/pull/15013

When downgrading to 1.7.1, I received many of the following in the log:

```
2023-04-25T10:48:14.156 wallet chia.wallet.wallet_state_manager: ERROR    Error adding state... table coin_record has 12 columns but 10 values were supplied
Traceback (most recent call last):
  File "chia/wallet/wallet_state_manager.py", line 1146, in new_coin_state
  File "chia/wallet/wallet_coin_store.py", line 86, in add_coin_record
  File "aiosqlite/core.py", line 194, in execute_insert
  File "aiosqlite/core.py", line 129, in _execute
  File "aiosqlite/core.py", line 102, in run
  File "aiosqlite/core.py", line 74, in _execute_insert
sqlite3.OperationalError: table coin_record has 12 columns but 10 values were supplied
```

### Version

1.8.0RC3

### What platform are you using?

Windows

### What ui mode are you using?

GUI

**Comment by HVNC1** [comment]
also

**Comment by baturman** [comment]
Can confirm this happened to me as well.

**Comment by emlowe** [comment]
fixed in 1.8.0 proper release as the added columns were reverted and no longer added.

for people who run the RC releases with the added columns, recommendation is to delete your wallet and let it resync. Optionally for the technically inclined you can manually remove the columns
