### ISSUE TITLE
Fails to start on fedora 33 (installed through experimental rpm installer)

### ISSUE THREAD

**Issue by JohnnyBDude** [Chia-Network/chia-blockchain#1515]
I am trying to run gui installed that was installed using fedora installer `chia-blockchain-1.0.1-1.x86_64.rpm` and get the following error:

```
ImportError: /usr/lib/chia-blockchain/resources/app.asar.unpacked/daemon/chiavdf.cpython-38-x86_64-linux-gnu.so: ELF load command address/offset not properly aligned
```

- fedora version: 33
- `uname -a` result: `Linux fedora 5.11.8-200.fc33.x86_64 #1 SMP Mon Mar 22 01:35:01 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`

Is there anything i can try to fix this?
I am not really proficient at bug reporting in foss projects, please tell me if you need any other info.

**Comment by Chewbakka-Wakka** [comment]
I have the same issue with Fedora Rawhide. To add additional details:

Thought to test the CentOS RPM from the release OOTB. I see these various errors and I have no "chia" command. I only have chia-blockchain and see no other CLI tools. The issue is the GUI launches, and loops on "connecting to wallet"

These issues may appear to stem within chiavdf?

Also fyi - "electron: The default of contextIsolation is deprecated and will be changing from false to true in a future release of Electron. See electron/electron#23506 for more information"

Steps:
$ sudo rpm -ivh chia-blockchain-1.0.1-1.x86_64.rpm

$ chia-blockchain
/usr/lib/chia-blockchain/resources/app.asar.unpacked/daemon
true
Traceback (most recent call last):
File "src/cmds/chia.py", line 8, in
File "PyInstaller/loader/pyimod03_importers.py", line 531, in exec_module
File "src/cmds/farm.py", line 11, in
File "PyInstaller/loader/pyimod03_importers.py", line 531, in exec_module
File "src/rpc/full_node_rpc_client.py", line 7, in
File "PyInstaller/loader/pyimod03_importers.py", line 531, in exec_module
File "src/types/full_block.py", line 11, in
File "PyInstaller/loader/pyimod03_importers.py", line 531, in exec_module
File "src/types/blockchain_format/reward_chain_block.py", line 8, in
File "PyInstaller/loader/pyimod03_importers.py", line 531, in exec_module
File "src/types/blockchain_format/vdf.py", line 7, in
ImportError: /usr/lib/chia-blockchain/resources/app.asar.unpacked/daemon/chiavdf.cpython-38-x86_64-linux-gnu.so: ELF load command address/offset not properly aligned
[11180] Failed to execute script chia
Error loading config - using defaults
/usr/lib/chia-blockchain/resources/app.asar.unpacked/daemon
true
/usr/lib/chia-blockchain/resources/app.asar.unpacked/daemon
true
Running python executable:
child process success
(node:11155) electron: The default of contextIsolation is deprecated and will be changing from false to true in a future release of Electron. See electron/electron#23506 for more information
No cert
Have cert
stderr: Traceback (most recent call last):
File "src/server/start_full_node.py", line 8, in
File "PyInstaller/loader/pyimod03_importers.py", line 531, in exec_module
File "src/full_node/full_node.py", line 14, in
File "PyInstaller/loader/pyimod03_importers.py", line 531, in exec_module
File "src/consensus/block_creation.py", line 11, in
File "PyInstaller/loader/pyimod03_importers.py", line 531, in exec_module
File "src/consensus/blockchain_interface.py", line 6, in
File "PyInstaller/loader/pyimod03_importers.py", line 531, in exec_module
File "src/types/blockchain_format/vdf.py", line 7, in
ImportError: /usr/lib/chia-blockchain/resources/app.asar.unpacked/daemon/chiavdf.cpython-38-x86_64-linux-gnu.so: ELF load command address/offset not properly aligned
[11321] Failed to execute script start_full_node
stderr: Traceback (most recent call last):
File "src/server/start_wallet.py", line 7, in
File "PyInstaller/loader/pyimod03_importers.py", line 531, in exec_module
File "src/rpc/wallet_rpc_api.py", line 22, in
File "PyInstaller/loader/pyimod03_importers.py", line 531, in exec_module
File "src/wallet/cc_wallet/cc_wallet.py", line 13, in
File "PyInstaller/loader/pyimod03_importers.py", line 531, in exec_module
File "src/protocols/wallet_protocol.py", line 7, in
File "PyInstaller/loader/pyimod03_importers.py", line 531, in exec_module
File "src/types/header_block.py", line 5, in
File "PyInstaller/loader/pyimod03_importers.py", line 531, in exec_module
File "src/types/blockchain_format/reward_chain_block.py", line 8, in
File "PyInstaller/loader/pyimod03_importers.py", line 531, in exec_module
File "src/types/blockchain_format/vdf.py", line 7, in
ImportError: /usr/lib/chia-blockchain/resources/app.asar.unpacked/daemon/chiavdf.cpython-38-x86_64-linux-gnu.so: ELF load command address/offset not properly aligned
[11319] Failed to execute script start_wallet
stderr: Traceback (most recent call last):
File "src/server/start_farmer.py", line 68, in
File "src/server/start_farmer.py", line 63, in main
File "src/server/start_farmer.py", line 38, in service_kwargs_for_farmer
File "src/farmer/farmer.py", line 73, in init
RuntimeError: No keys exist. Please run 'chia keys generate' or open the UI.
[11323] Failed to execute script start_farmer

$ chia keys generate
bash: chia: command not found...

**Comment by TechnicallyComputers** [comment]
It is definitely caused by the wallet not running.  
I was able to build with the command line instructions here:
https://github.com/Chia-Network/chia-blockchain/wiki/INSTALL#centos--redhat--fedora
And when I am in the virtual environment, and I run "chia_wallet &" it starts the wallet, and the GUI app from the RPM will work.

**Comment by TechnicallyComputers** [comment]
I can see from the logs actually it fails to start the scripts for the full node, and for the wallet:
stderr: Traceback (most recent call last):
  File "chia/server/start_full_node.py", line 8, in <module>
  File "PyInstaller/loader/pyimod03_importers.py", line 531, in exec_module
  File "chia/full_node/full_node.py", line 14, in <module>
  File "PyInstaller/loader/pyimod03_importers.py", line 531, in exec_module
  File "chia/consensus/block_creation.py", line 11, in <module>
  File "PyInstaller/loader/pyimod03_importers.py", line 531, in exec_module
  File "chia/consensus/blockchain_interface.py", line 6, in <module>
  File "PyInstaller/loader/pyimod03_importers.py", line 531, in exec_module
  File "chia/types/blockchain_format/vdf.py", line 7, in <module>
ImportError: /usr/lib/chia-blockchain/resources/app.asar.unpacked/daemon/chiavdf.cpython-38-x86_64-linux-gnu.so: ELF load command address/offset not properly aligned
[9956] Failed to execute script start_full_node
stderr: Traceback (most recent call last):
  File "chia/server/start_wallet.py", line 7, in <module>
  File "PyInstaller/loader/pyimod03_importers.py", line 531, in exec_module
  File "chia/rpc/wallet_rpc_api.py", line 22, in <module>
  File "PyInstaller/loader/pyimod03_importers.py", line 531, in exec_module
  File "chia/wallet/cc_wallet/cc_wallet.py", line 13, in <module>
  File "PyInstaller/loader/pyimod03_importers.py", line 531, in exec_module
  File "chia/protocols/wallet_protocol.py", line 7, in <module>
  File "PyInstaller/loader/pyimod03_importers.py", line 531, in exec_module
  File "chia/types/header_block.py", line 5, in <module>
  File "PyInstaller/loader/pyimod03_importers.py", line 531, in exec_module
  File "chia/types/blockchain_format/reward_chain_block.py", line 8, in <module>
  File "PyInstaller/loader/pyimod03_importers.py", line 531, in exec_module
  File "chia/types/blockchain_format/vdf.py", line 7, in <module>
