### ISSUE TITLE
sqlite3.OperationalError: no such column: hardened[Bug] 

### ISSUE THREAD

**Issue by maybeTomorrow** [Chia-Network/chia-blockchain#15223]
### What happened?

chia version 1.4 update to 1.8.run chia wallet show got no key.run chia wallet check show error

### Version

1.8

### What platform are you using?

Linux

### What ui mode are you using?

CLI

### Relevant log output

```shell
chia wallet check
Reading /root/.chia/mainnet/wallet/db/blockchain_wallet_v1_mainnet_2927419218.sqlite
Traceback (most recent call last):
  File "chia/cmds/chia.py", line 139, in <module>
  File "chia/cmds/chia.py", line 135, in main
  File "click/core.py", line 1130, in __call__
  File "click/core.py", line 1055, in main
  File "click/core.py", line 1657, in invoke
  File "click/core.py", line 1657, in invoke
  File "click/core.py", line 1404, in invoke
  File "click/core.py", line 760, in invoke
  File "click/decorators.py", line 26, in new_func
  File "chia/cmds/wallet.py", line 576, in check_wallet_cmd
  File "asyncio/runners.py", line 44, in run
  File "asyncio/base_events.py", line 616, in run_until_complete
  File "chia/cmds/check_wallet_db.py", line 407, in scan
  File "chia/cmds/check_wallet_db.py", line 369, in scan
  File "chia/cmds/check_wallet_db.py", line 224, in get_derivation_paths
  File "aiosqlite/core.py", line 184, in execute
  File "aiosqlite/core.py", line 129, in _execute
  File "aiosqlite/core.py", line 102, in run
sqlite3.OperationalError: no such column: hardened
[3401008] Failed to execute script 'chia' due to unhandled exception!
```

**Comment by MumfMeisterT** [comment]
This looks to be an issue in your walletdb, so you can delete it and restart Chia and it should resolve.

**Comment by emlowe** [comment]
Closing issue
