### ISSUE TITLE
[Bug] On-demand minting is stopping working since v1.7.1

### ISSUE THREAD

**Issue by wizicer** [Chia-Network/chia-blockchain#15250]
### What happened?

- Last working version: 1.7.0
- Confirmed Bug version: 1.7.1/1.8.0/1.8.0b4-dev30(local)

Seems Chia Client checks the NFT existence before accepting offer. `error with Coin record 0x..... not found`

But on-demand minting would not create the NFT before offer taken. 

## How the spend bundle look like

![image](https://github.com/Chia-Network/chia-blockchain/assets/2389606/64ff3b3b-5a6f-4af6-a60a-f62db9c44aaa)

`0xd74d8c080d9fc28eaa4bb10b04897d922568d775d5cfdfa730af70e12d2e6db1` is the coin I pointed in above image.

## How are you minting the nft?

We created partial spend bundle of NFT minting which required the offer to be successfully taken through puzzle announcement
The NFT only minted when the offer accepted.

You can try in https://xch.cool/ .
Try to register and make one offer, then you can inspect this offer in  https://mixch.dev/

## Why it matters

I believe on-demand minting should be a useful feature benefit lots of scenarios, like mint blind box on-demand.

## How to reproduce

- try to register an xch name at https://xch.cool/ and copy the resulting offer

### Version

1.7.1/1.8.0/1.8.0b4-dev30

### What platform are you using?

Windows

### What ui mode are you using?

GUI

### Relevant log output

```shell
2023-05-05T20:12:33.355 wallet chia.rpc.rpc_server        : WARNING  Error while handling message: Traceback (most recent call last):
  File "chia\rpc\rpc_server.py", line 340, in safe_handle
  File "chia\rpc\rpc_server.py", line 331, in ws_api
  File "chia\rpc\wallet_rpc_api.py", line 2662, in nft_get_info
  File "chia\rpc\wallet_rpc_api.py", line 277, in get_latest_singleton_coin_spend
ValueError: Coin record 0xd74d8c080d9fc28eaa4bb10b04897d922568d775d5cfdfa730af70e12d2e6db1 not found

2023-05-05T20:12:33.483 wallet chia.rpc.rpc_server        : WARNING  Error while handling message: Traceback (most recent call last):
  File "chia\rpc\rpc_server.py", line 340, in safe_handle
  File "chia\rpc\rpc_server.py", line 331, in ws_api
  File "chia\rpc\wallet_rpc_api.py", line 2662, in nft_get_info
  File "chia\rpc\wallet_rpc_api.py", line 277, in get_latest_singleton_coin_spend
ValueError: Coin record 0xd74d8c080d9fc28eaa4bb10b04897d922568d775d5cfdfa730af70e12d2e6db1 not found
```

**Comment by MumfMeisterT** [comment]
How do you believe royalties should work in this use case? Does the user enter the royalty? The issue is that the coin doesn't exist, so we can't look this up.

**Comment by wizicer** [comment]
It works:
1. It works in `v1.7.0` and before. Only failed since `v1.7.1`.
2. The NFT is ephemeral coin in the spend bundle, the royalty can be calculated from there.

**Comment by MumfMeisterT** [comment]
@wizicer We will have DevRel reach out to you to discuss further.

**Comment by wizicer** [comment]
> @wizicer We will have DevRel reach out to you to discuss further.

I haven't received any message from DevRel until now, could you check with DevRel again?

**Comment by punish-yh** [comment]
someone can fix this?
