### ISSUE TITLE
[Bug] NTF's missing in wallet -> while transferring NFT's inbetween wallets, spendbundles were rejected as doublespends

### ISSUE THREAD

**Issue by BookSwapSteve** [Chia-Network/chia-blockchain#15263]
### What happened?

> pyl on chia discord ( @loppefaaret on GH ) support chat skimmed through the logs, and seem to suggest that while transferring NFT's inbetween wallets, spendbundles were rejected as doublespends ( 2023-05-12T00:58:16.199 ), and wallet tracebacks starting from ( 2023-05-12T00:58:56.540 )

Trying to transfer NFTs to two profiles, two of the NFTs are now not showing in the Windows GUI (1.8.0)

I tried to move 4 NTFs into different profiles in the 1.8 Windows client, in the process of doing that, two of them have disappeared from the client. I can see them on SpaceScan/MintGarden, one has been moved to the new profile, one hasn't, but they are not visible in the client.

I've rebuild the wallet, restarted the client, restarted windows, had a cup of tea, tried on a second instance of the client, checked the filters to ensure it's not being hidden, but  still nothing.

This was raised on the support chat on chia discord (12 May - 12:03 UK time (UTC+1) - search for the text above), logs have been sent to pyl on discord, who asked for a ticket to be raised here with the comments that I have put at the start of the ticket.

One of the four NFTs looked like it got stuck ('pending update' shown on the NFT in the client), however looking at MintGarden it looked like it was assigned to the correct profile, and two of the NFTs have never shown up again in the client. I've since "cancelled" the one that got stuck with the 'pending update' message.

### Version

1.8.0

### What platform are you using?

Windows

### What ui mode are you using?

GUI

### Relevant log output

```shell
2023-05-12T00:58:16.199 wallet chia.wallet.wallet_node    : WARNING  SpendBundle has been rejected by the FullNode. {'error': 'DOUBLE_SPEND', 'status': 3, 'txid': '0x35c7c085df27c652dd8fe8fb0e7fd0af68256f9265e38fa607bf5fe7c97a5039'}

2023-05-12T00:58:56.540 wallet chia.wallet.wallet_state_manager: ERROR    set_sync_mode failed - range: 3648289-3648293, seconds: 0.8960378170013428
Traceback (most recent call last):
  File "chia\wallet\wallet_state_manager.py", line 524, in set_sync_mode
  File "chia\wallet\wallet_node.py", line 1120, in long_sync_from_untrusted
  File "chia\wallet\wallet_node.py", line 751, in long_sync
  File "chia\wallet\util\wallet_sync_utils.py", line 79, in subscribe_to_phs
ValueError: None response from peer 155.93.180.192 for register_interest_in_puzzle_hash
2023-05-12T00:58:56.545 wallet chia.wallet.wallet_node    : WARNING  SpendBundle has been rejected by the FullNode. {'error': 'DOUBLE_SPEND', 'status': 3, 'txid': '0x35c7c085df27c652dd8fe8fb0e7fd0af68256f9265e38fa607bf5fe7c97a5039'}
2023-05-12T00:58:56.553 wallet chia.wallet.wallet_state_manager: INFO     Checking if we need to cancel trade for tx: 35c7c085df27c652dd8fe8fb0e7fd0af68256f9265e38fa607bf5fe7c97a5039
2023-05-12T00:58:56.572 wallet chia.wallet.wallet_node    : WARNING  SpendBundle has been rejected by the FullNode. {'error': 'DOUBLE_SPEND', 'status': 3, 'txid': '0xc9cd27474c59be1e059a6f8986f3795512549d8ac3d1859c18e367b4f1dbf911'}
2023-05-12T00:58:56.580 wallet chia.wallet.wallet_state_manager: INFO     Checking if we need to cancel trade for tx: c9cd27474c59be1e059a6f8986f3795512549d8ac3d1859c18e367b4f1dbf911
```

**Comment by MumfMeisterT** [comment]
@mikeblock Can you try deleting your walletdb and restarting the service to see if that works?

**Comment by MumfMeisterT** [comment]
@BookSwapSteve How many wallets do you have, and what is your derivation index, and are you using a trusted node?

**Comment by mikeblock** [comment]
> @mikeblock Can you try deleting your walletdb and restarting the service to see if that works?

Yup, that did the trick, thanks!

**Comment by BookSwapSteve** [comment]
> @BookSwapSteve How many wallets do you have, and what is your derivation index, and are you using a trusted node?

On the machine this originally happened on:
1 wallet, derivation index is 822. I don't believe I'm using a trusted node.

On the second machine I re-synced the walled on after this had happened:
2 wallets, derivation index is 825. Not using a trusted node.

**Comment by BookSwapSteve** [comment]
As GitHub has decided to close this, I'll just add that I still have this issue, two of my NFTs are still not showing my the GUI, on both 1.8.1 and 2.0.0b3-dev116.
