### ISSUE TITLE
[Bug] Error -3 while decompressing data: incorrect header check

### ISSUE THREAD

**Issue by hostingnuggets** [Chia-Network/chia-blockchain#15329]
### What happened?

After upgrading the chia-blockchain-cli package from version 1.8.0 to 1.8.1 on my Debian 11 node I can not start the chia wallet anymore. If I downgrade back to 1.8.0 it works again. 

### Version

1.8.0

### What platform are you using?

Linux

### What ui mode are you using?

CLI

### Relevant log output

```shell
2023-05-18T11:52:00.125 daemon chia.daemon.keychain_server: ERROR    Error -3 while decompressing data: incorrect header check
Traceback (most recent call last):
  File "chia/daemon/keychain_server.py", line 142, in handle_command
  File "chia/daemon/keychain_server.py", line 286, in get_key_for_fingerprint
  File "chia/util/keychain.py", line 386, in get_all_private_keys
  File "chia/util/keychain.py", line 291, in _get_key_data
  File "chia/util/keychain.py", line 181, in from_entropy
  File "chia/util/keychain.py", line 70, in bytes_to_mnemonic
  File "chia/util/keychain.py", line 56, in bip39_word_list
  File "pkg_resources/__init__.py", line 1142, in resource_string
  File "pkg_resources/__init__.py", line 1388, in get_resource_string
  File "pkg_resources/__init__.py", line 1555, in _get
  File "PyInstaller/loader/pyimod02_importers.py", line 193, in get_data
  File "PyInstaller/loader/pyimod01_archive.py", line 302, in extract
zlib.error: Error -3 while decompressing data: incorrect header check
```

**Comment by MumfMeisterT** [comment]
How did you install the deb? Did you install it from the repo or did you download the .deb file directly? 

- Are you able to run `chia init`?

**Comment by hostingnuggets** [comment]
> How did you install the deb? Did you install it from the repo or did you download the .deb file directly?

I installed it from the official APT repo which is configured as such in my `/etc/apt/sources.list.d/chia.list` file:

```deb [arch=amd64 signed-by=/usr/share/keyrings/chia.gpg] https://repo.chia.net/debian/ stable main```

So in order to upgrade it from 1.7.0 to 1.8.1 I simply ran an `apt-get upgrade`.

> * Are you able to run `chia init`?

I should have been more precise in my bug post but this is an already existing chia farm/harvester/wallet node which is running since a few months without any issues so I can't run `chia init` as I already did that months ago when I initially installed it.
