### ISSUE TITLE
[BUG] Node failing to sync: ValueError: Weight proof validation threw an error cannot convert 'NoneType' object to bytes

### ISSUE THREAD

**Issue by Playwo** [Chia-Network/chia-blockchain#1536]
**Describe the bug**
I'm using the docker image install of chia with the fullnode, wallet, farmer and harvester enabled.
After hours of waiting I still don't see any progress with the blockchain synchronization.
In the logs I found [this error](https://hatebin.com/gvlpowrnyd)

I tried to use the prebuilt image and built one from source, both had the same issue after hours of waiting.

**To Reproduce**

1. Install Chia using docker
2. Check logs for sync errors

**Expected behavior**
Synchronization starting when the node is running

**Desktop (please complete the following information):**

- OS: Linux
- OS Debian 10
- CPU: Unknown Server CPU (VPS)

**Comment by Playwo** [comment]
I have found another error during startup that is probably related:
``` 
full_node asyncio                 : ERROR    Task exception was never retrieved
future: <Task finished name='Task-5' coro=<FullNode.initialize_weight_proof() done, defined at /chia-blockchain/src/full_node/full_node.py:145> exception=AttributeError("'NoneType' object has no attribute 'header_hash'")>
Traceback (most recent call last):
  File "/chia-blockchain/src/full_node/full_node.py", line 147, in initialize_weight_proof
    await self.weight_proof_handler.get_proof_of_weight(self.blockchain.get_peak().header_hash)
AttributeError: 'NoneType' object has no attribute 'header_hash'```

**Comment by mariano54** [comment]
Are you on version 1.0.1? Can you close chia and restart your computer and try again?

**Comment by hoffmang9** [comment]
This is harmless and will be fixed in the next release.

**Comment by trepca** [comment]
@hoffmang9  This is still happening on `1.0.5`.

**Comment by radvansky-tomas** [comment]
Got similar error @hoffmang9 

```
2021-05-04T18:45:15.762 full_node chia.full_node.full_node: ERROR    Error with syncing: <class 'ValueError'>Traceback (most recent call last):
  File "/Users/tomasradvansky/Documents/chia/chia-blockchain/chia/full_node/full_node.py", line 637, in _sync
    validated, fork_point, summaries = await self.weight_proof_handler.validate_weight_proof(response.wp)
  File "/Users/tomasradvansky/Documents/chia/chia-blockchain/chia/full_node/weight_proof.py", line 592, in validate_weight_proof
    segment_validation_task = asyncio.get_running_loop().run_in_executor(
  File "/Users/tomasradvansky/.pyenv/versions/3.9.4/lib/python3.9/asyncio/base_events.py", line 814, in run_in_executor
    executor.submit(func, *args), loop=self)
  File "/Users/tomasradvansky/.pyenv/versions/3.9.4/lib/python3.9/concurrent/futures/process.py", line 697, in submit
    self._adjust_process_count()
  File "/Users/tomasradvansky/.pyenv/versions/3.9.4/lib/python3.9/concurrent/futures/process.py", line 675, in _adjust_process_count
    p.start()
  File "/Users/tomasradvansky/.pyenv/versions/3.9.4/lib/python3.9/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "/Users/tomasradvansky/.pyenv/versions/3.9.4/lib/python3.9/multiprocessing/context.py", line 284, in _Popen
    return Popen(process_obj)
  File "/Users/tomasradvansky/.pyenv/versions/3.9.4/lib/python3.9/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/Users/tomasradvansky/.pyenv/versions/3.9.4/lib/python3.9/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/Users/tomasradvansky/.pyenv/versions/3.9.4/lib/python3.9/multiprocessing/popen_spawn_posix.py", line 42, in _launch
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "/Users/tomasradvansky/.pyenv/versions/3.9.4/lib/python3.9/multiprocessing/spawn.py", line 176, in get_preparation_data
    dir=os.getcwd(),
PermissionError: [Errno 1] Operation not permitted

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/tomasradvansky/Documents/chia/chia-blockchain/chia/full_node/full_node.py", line 640, in _sync
    raise ValueError(f"Weight proof validation threw an error {e}")
```
