### ISSUE TITLE
[Bug] Datalayer subscribing to new store sometimes fails with Launcher ID is not a valid coin

### ISSUE THREAD

**Issue by emlowe** [Chia-Network/chia-blockchain#15414]
### What happened?

Occasional failures when subscribing to a datalayer singleton with `Launcher ID <id> is not a valid coin` - for example:
```
2023-05-30T15:25:35.014 wallet chia.rpc.util              : WARNING  Error while handling message: Traceback (most recent call last):
  File "chia\rpc\util.py", line 18, in inner
  File "chia\rpc\wallet_rpc_api.py", line 3094, in dl_track_new
  File "chia\data_layer\data_layer_wallet.py", line 220, in track_new_launcher_id
  File "chia\data_layer\data_layer_wallet.py", line 196, in get_launcher_coin_state
ValueError: Launcher ID fa47700cb693529602c3eab47a5d681ffe0145dabeee6c69cabdd7869537b917 is not a valid coin
```

The code in `dl_track_new` only asks for the coin from a single node. If this node for whatever reason doesn't have this coin, this error is returned. The wallet will likely continue to ask the same peer again on a retry.

It might make sense to use (certainly when in light wallet mode) the full list of peers and ask all the peers about this coin, as one node might have it correctly. This would hopefully reduce errors where the one selected node happens for whatever reason to not have this coin in its DB

### Version

all

### What platform are you using?

Windows

### What ui mode are you using?

GUI

**Comment by emlowe** [comment]
Fixed in 1.8.2
