### ISSUE TITLE
Caught plotting error

### ISSUE THREAD

**Issue by E-mouse** [Chia-Network/chia-blockchain#1550]
I run chia blockchain on my windows 10. Temporary directory is on an internal SSD. Final Directory is on an external HHD. This is the second time I met this error:
Caught plotting error: Matches do not match with number of write entries 4294995641 4294995666
[536] Failed to execute script chia
Traceback (most recent call last):
  File "src\cmds\chia.py", line 80, in <module>
  File "src\cmds\chia.py", line 76, in main
  File "click\core.py", line 829, in __call__
  File "click\core.py", line 782, in main
  File "click\core.py", line 1259, in invoke
  File "click\core.py", line 1259, in invoke
  File "click\core.py", line 1066, in invoke
  File "click\core.py", line 610, in invoke
  File "click\decorators.py", line 21, in new_func
  File "src\cmds\plots.py", line 134, in create_cmd
  File "src\plotting\create_plots.py", line 176, in create_plots
RuntimeError: Unknown exception

**Comment by Dravenex** [comment]
I got the same problem. I'm also on Windows 10.

**Comment by hoffmang9** [comment]
These are hardware errors with either the disk you are plotting on or more like your RAM.

**Comment by JohnnyFFM** [comment]
Had the same error, was driving me nuts. Tracked it down to using an Adaptec ASR 72405 Host Adapter. Having two of these in completely different machines, same issue. Replaced both with LSI-9305 24i -> now working like a charm.

**Comment by tajchert** [comment]
How did you trace source of the issue @JohnnyFFM ? I have same error and both RAM and disk seems solid.

**Comment by JohnnyFFM** [comment]
had the issues with two machines. the only thing they had in common was the adaptec sas hba. replaced with lsi. working like a charm now. 

so a starting point is to swap hard drive and swap i/o interface.

**Comment by E-mouse** [comment]
Thanks. One problem with my RAM is confirmed.

Gene Hoffman ***@***.***> 于2021年3月29日周一 下午10:46写道：
