### ISSUE TITLE
[Bug] Error adding proofs / transferring VC

### ISSUE THREAD

**Issue by danieljperry** [Chia-Network/chia-blockchain#15530]
### What happened?

Start by creating a VC and showing it:
```
chia wallet vcs get -f 2108245669
```
```
Proofs:

Launcher ID: 89a4ff17372dd3a8814712c0988b87b508a04cd7fa61d0228ce54b74111e7160
Coin ID: 72e522fecc64b539f8979b89e4cf2ffbcf8ba985faf4b701bcc882c6aec9e040
Inner Address: txch1at35qwx6djmadnh9v77a72z8vcaxsle36ke3dj26gcpt2fnh654qsqecnj
```
Next, add proofs to the DB and obtain a hash:
```
chia wallet vcs add_proof_reveal -f 2108245669 --proof test_proof1 --proof test_proof2 --root-only
```
```
Proof Hash: f063e22557705b14425b8fca60018796b4364eb6354f45d0b99431a71d3043e5
```
Next, add the proof hash and send the VC to a new wallet:
```
chia wallet vcs update_proofs -f 2108245669 -l 89a4ff17372dd3a8814712c0988b87b508a04cd7fa61d0228ce54b74111e7160 -t 0x6fc9728dcd29358fae2194a1145d54c58acfa4de0380c60f8af377742e67788b -p f063e22557705b14425b8fca60018796b4364eb6354f45d0b99431a71d3043e5 -m 0.0001
```
```
Proofs successfully updated!
Relevant TX records:

Transaction 76f5ea8475d695e798518cd405070dc22542e31fc85220ff7d2ca7b44852a45b
Status: Pending
Amount sent: 0 XCH
To address: txch10xjm79zct87gc8ux5vzrhnnt03zjn4ntn5y95w37rsfmp4rxjycquqctuc
Created at: 2023-06-15 10:15:27

Transaction f9eebb0520d024aaf4ae176d554c0f806b8d724d21d5da03b5f541fafd69c99f
Status: Pending
Amount sent: 1E-12 XCH
To address: txch1dlyh9rwd9y6clt3pjjs3gh25ck9vlfx7qwqvvru27dmhgtn80z9s2rruam
Created at: 2023-06-15 10:15:28
```
Now show the VC from the holders wallet (**this is the error**):
```
chia wallet vcs get -f 2053849171
```
```
Proofs:
- f063e22557705b14425b8fca60018796b4364eb6354f45d0b99431a71d3043e5
Exception from 'wallet' 'NoneType' object is not iterable:
Traceback (most recent call last):
  File "chia\cmds\cmds_util.py", line 104, in get_any_service_client
  File "chia\cmds\cmds_util.py", line 224, in execute_with_wallet
  File "chia\cmds\wallet_funcs.py", line 1259, in get_vcs
TypeError: 'NoneType' object is not iterable
```

If I try to revoke the proofs, the command line succeeds:
```
chia wallet vcs revoke -f 2108245669 -p 72e522fecc64b539f8979b89e4cf2ffbcf8ba985faf4b701bcc882c6aec9e040 -m 0.01
```
```
VC successfully revoked!
Relevant TX records:

Transaction e7c3b6b0bfff5d379cceef9533ed2739c4af7da669c0ffc7c6926ab11bc9cbef
Status: Pending
Amount sent: 1E-12 XCH
To address: txch1dlyh9rwd9y6clt3pjjs3gh25ck9vlfx7qwqvvru27dmhgtn80z9s2rruam
Created at: 2023-06-15 13:57:18

Transaction a634163a68ee385a0bbd340dbe9ec68c4ef8d77ac337d9bd01a9e914f94d4025
Status: Pending
Amount sent: 0 XCH
To address: txch1v04reqaeprcatvpcjyrhdkg0aclqxuz8aez9gcgdrjqs0d93sfuqx904g7
Created at: 2023-06-15 13:57:18
```

But the log shows an error:
```
2023-06-15T14:04:05.129 wallet chia.wallet.wallet_state_manager: WARNING  Verified credential 89a4ff17372dd3a8814712c0988b87b508a04cd7fa61d0228ce54b74111e7160 is not belong to the current wallet.
2023-06-15T14:04:05.129 wallet chia.wallet.wallet_node    : WARNING  SpendBundle has been rejected by the FullNode. {'error': 'ASSERT_MY_PARENT_ID_FAILED',
 'status': 3,
 'txid': '0xfd55039eee68fb3ddba1091882692c6033f22d768e99f100be4738d6b66ba390'}
```

If I try revoking from the RPC, I get this error in my log:
```
2023-06-15T15:07:25.782 wallet chia.wallet.wallet_state_manager: WARNING  Verified credential 75ea50e79d6020c655306bc27208fc454d656c3d45246763146a626cca17871d is not belong to the current wallet.
2023-06-15T15:07:25.782 wallet chia.wallet.wallet_node    : WARNING  SpendBundle has been rejected by the FullNode. {'error': 'ASSERT_MY_PARENT_ID_FAILED',
 'status': 3,
 'txid': '0xd3ada36f429cfe9058770000810a6e1e7069d05bbbaf5d61fc85e5bb73f67eb0'}
```

### Version

1.8.2rc3

### What platform are you using?

Windows

### What ui mode are you using?

CLI

**Comment by danieljperry** [comment]
Fixed in 1.8.2rc6.
