### ISSUE TITLE
Beta 18.2rc1 Fresh Install - Error: Fingerprint is not defined [Bug] 

### ISSUE THREAD

**Issue by rkroelin** [Chia-Network/chia-blockchain#15558]
### What happened?

Installed a fresh copy of 1.8.2rc1 on a fresh install of windows 11 and received "Something went wrong" "Error: Fingerprint is not defined" when it launched for the first time.  Reload application button results in the same error.  I did check the add chia to the path option but that's about it.  No prior versions of chia installed on this machine.

You can briefly see the light wallet/full node GUI screen before the error pops up. Restarting app results in same error

![image](https://github.com/Chia-Network/chia-blockchain/assets/53322426/ffccfb82-79cb-46e4-827e-3ea9ced4f571)

### Version

1.8.2rc1

### What platform are you using?

Windows

### What ui mode are you using?

GUI

### Relevant log output

```shell
Something went wrong
Error: Fingerprint is not defined
at webpack://@chia-network/src/hooks/useFingerprintSettings.ts:16:14 useFingerprintSettings<Type extends Serializable>
at webpack://@chia-network/gui/src/components/notification/NotificationsProvider.tsx:121:4 setLastPushNotificationTimestamp
at webpack://@chia-network/gui/src/components/notification/NotificationsProvider.tsx:184:4 showPushNotifications
at webpack://@chia-network/gui/node_modules/react-dom/cjs/react-dom.production.min.js:262:358 fk
at webpack://@chia-network/gui/node_modules/scheduler/cjs/scheduler.production.min.js:18:342 unstable_next
at webpack://@chia-network/gui/node_modules/react-dom/cjs/react-dom.production.min.js:122:324 eg
at webpack://@chia-network/gui/node_modules/react-dom/cjs/react-dom.production.min.js:261:307 ek
at webpack://@chia-network/gui/node_modules/react-dom/cjs/react-dom.production.min.js:261:214 ek
at webpack://@chia-network/gui/node_modules/scheduler/cjs/scheduler.production.min.js:16:223 V
at webpack://@chia-network/gui/node_modules/scheduler/cjs/scheduler.production.min.js:12:345 k
```

**Comment by rkroelin** [comment]
For what it is worth this didn't occur upon installing release 1.8.1 or subsequently installing 1.8.2rc5
