### ISSUE TITLE
[Bug]  Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x000001B85BA47B80>

### ISSUE THREAD

**Issue by azrielitay** [Chia-Network/chia-blockchain#15637]
### What happened?

When closing chia GUI app the bellow errors show in log. 

### Version

1.8.1

### What platform are you using?

Windows

### What ui mode are you using?

GUI

### Relevant log output

```shell
(node:7468) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 state_changed listeners added to [J]. Use emitter.setMaxListeners() to increase limit
(Use `Chia --trace-warnings ...` to show where the warning was created)
stderr: Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x000001B85BA47B80>
Traceback (most recent call last):
  File "asyncio\proactor_events.py", line 116, in __del__
stderr:   File "asyncio\proactor_events.py", line 108, in close
  File "asyncio\base_events.py", line 751, in call_soon
  File "asyncio\base_events.py", line 515, in _check_closed
stderr: RuntimeError: Event loop is closed
```

**Comment by azrielitay** [comment]
Open

בתאריך יום ד׳, 12 ביולי 2023 ב-14:05 מאת github-actions[bot] <
***@***.***>:
