### ISSUE TITLE
clawback bad bytes32 initializer [Bug] 

### ISSUE THREAD

**Issue by danieljperry** [Chia-Network/chia-blockchain#15635]
### What happened?

To reproduce, run the following CLI command:
`chia wallet clawback`

Result:
```
Exception from 'wallet' bad bytes32 initializer b'':
Traceback (most recent call last):
  File "chia\cmds\cmds_util.py", line 104, in get_any_service_client
    yield node_client, config
  File "chia\cmds\cmds_util.py", line 224, in execute_with_wallet
    await function(extra_params, wallet_client, new_fp)
  File "chia\cmds\wallet_funcs.py", line 1277, in spend_clawback
    tx_ids.append(bytes32.from_hexstr(tid))
  File "chia\util\byte_types.py", line 53, in from_hexstr
    return cls.fromhex(input_str)
  File "chia\util\byte_types.py", line 35, in __init__
    raise ValueError("bad %s initializer %s" % (type(self).__name__, v))
ValueError: bad bytes32 initializer b''
```

Note that when given extra arguments, the command succeeds. For example,
`chia wallet clawback -h`
works as expected.

### Version

1.8.2rc5 installed from binary

### What platform are you using?

Windows

### What ui mode are you using?

CLI

**Comment by wjblanke** [comment]
dan is this still a problem
