### ISSUE TITLE
clawbavk error

### ISSUE THREAD

**Issue by nicolaardito** [Chia-Network/chia-blockchain#15665]
command: chia wallet clawback

choose wallet 

error:
Exception from 'wallet' bad bytes32 initializer b'':
Traceback (most recent call last):
  File "chia/cmds/cmds_util.py", line 104, in get_any_service_client
  File "chia/cmds/cmds_util.py", line 224, in execute_with_wallet
  File "chia/cmds/wallet_funcs.py", line 1277, in spend_clawback
  File "chia/util/byte_types.py", line 53, in from_hexstr
  File "chia/util/byte_types.py", line 35, in init
ValueError: bad bytes32 initializer b''

**Comment by hbroer** [comment]
Duplicate of #15635

looks like a bug which happens if there is no parameter following. Normaly this should (AFAIK) output the help. But instead it tries to use a empty string as the parameter which fails.
