### ISSUE TITLE
Plotting stop at 6% [Bug] 

### ISSUE THREAD

**Issue by Alan911Black** [Chia-Network/chia-blockchain#15677]
### What happened?

Hi,
when i create multiple plots, some just get stack at 6%

Error:
RuntimeError: bad allocation
[12724] Failed to execute script 'chia' due to unhandled exception!
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x000001E81EF57E50>
Traceback (most recent call last):
  File "asyncio\proactor_events.py", line 116, in __del__
  File "asyncio\proactor_events.py", line 108, in close
  File "asyncio\base_events.py", line 751, in call_soon
  File "asyncio\base_events.py", line 515, in _check_closed
RuntimeError: Event loop is closed

### Version

1.8.2

### What platform are you using?

Windows

### What ui mode are you using?

GUI

### Relevant log output

```shell
Starting plotting progress into temporary dirs: D:\ and D:\
ID: 7eedf720432efd1f8e014d6e9e7731d0ac032e5cfc1e83b6b0ceb1da64dc0356
Plot size is: 32
Buffer size is: 3390MiB
Using 128 buckets
Final Directory is: H:\
Using 2 threads of stripe size 65536
Process ID is: 12724

Starting phase 1/4: Forward Propagation into tmp files... Sat Jul  1 23:52:29 2023
Computing table 1
Progress update: 0.01
F1 complete, time: 200.814 seconds. CPU (64.17%) Sat Jul  1 23:55:50 2023
Computing table 2
Progress update: 0.06
Caught plotting error: bad allocation
Traceback (most recent call last):
  File "chia\cmds\chia.py", line 139, in <module>
  File "chia\cmds\chia.py", line 135, in main
  File "click\core.py", line 1130, in __call__
  File "click\core.py", line 1055, in main
  File "click\core.py", line 1657, in invoke
  File "click\core.py", line 1404, in invoke
  File "click\core.py", line 760, in invoke
  File "click\decorators.py", line 26, in new_func
  File "chia\cmds\plotters.py", line 17, in plotters_cmd
  File "chia\plotters\plotters.py", line 474, in call_plotters
  File "chia\plotters\chiapos.py", line 58, in plot_chia
  File "asyncio\runners.py", line 44, in run
  File "asyncio\base_events.py", line 647, in run_until_complete
  File "chia\plotting\create_plots.py", line 232, in create_plots
RuntimeError: bad allocation
[12724] Failed to execute script 'chia' due to unhandled exception!
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x000001E81EF57E50>
Traceback (most recent call last):
  File "asyncio\proactor_events.py", line 116, in __del__
  File "asyncio\proactor_events.py", line 108, in close
  File "asyncio\base_events.py", line 751, in call_soon
  File "asyncio\base_events.py", line 515, in _check_closed
RuntimeError: Event loop is closed
```

**Comment by hbroer** [comment]
could be RAM, or swap file issue: #1847
