### ISSUE TITLE
[Bug]  No module named 'chia.wallet.puzzles.clawback' error when run chia installed via `pip`

### ISSUE THREAD

**Issue by kimsk** [Chia-Network/chia-blockchain#15681]
### What happened?

I fresh install `chia-blockchain` 1.8.2 via `pip`. But when I run `chia` CLI, I got the error below:
```sh
❯ chia version
Traceback (most recent call last):
  File "/Users/karlkim/venv3.11/bin/chia", line 5, in <module>
    from chia.cmds.chia import main
  File "/Users/karlkim/venv3.11/lib/python3.11/site-packages/chia/cmds/chia.py", line 14, in <module>
    from chia.cmds.dev import dev_cmd
  File "/Users/karlkim/venv3.11/lib/python3.11/site-packages/chia/cmds/dev.py", line 5, in <module>
    from chia.cmds.sim import sim_cmd
  File "/Users/karlkim/venv3.11/lib/python3.11/site-packages/chia/cmds/sim.py", line 9, in <module>
    from chia.cmds.sim_funcs import async_config_wizard, farm_blocks, print_status, revert_block_height, set_auto_farm
  File "/Users/karlkim/venv3.11/lib/python3.11/site-packages/chia/cmds/sim_funcs.py", line 13, in <module>
    from chia.cmds.cmds_util import get_any_service_client
  File "/Users/karlkim/venv3.11/lib/python3.11/site-packages/chia/cmds/cmds_util.py", line 17, in <module>
    from chia.rpc.wallet_rpc_client import WalletRpcClient
  File "/Users/karlkim/venv3.11/lib/python3.11/site-packages/chia/rpc/wallet_rpc_client.py", line 5, in <module>
    from chia.data_layer.data_layer_wallet import Mirror, SingletonRecord
  File "/Users/karlkim/venv3.11/lib/python3.11/site-packages/chia/data_layer/data_layer_wallet.py", line 56, in <module>
    from chia.wallet.wallet import Wallet
  File "/Users/karlkim/venv3.11/lib/python3.11/site-packages/chia/wallet/wallet.py", line 22, in <module>
    from chia.wallet.coin_selection import select_coins
  File "/Users/karlkim/venv3.11/lib/python3.11/site-packages/chia/wallet/coin_selection.py", line 10, in <module>
    from chia.wallet.wallet_coin_record import WalletCoinRecord
  File "/Users/karlkim/venv3.11/lib/python3.11/site-packages/chia/wallet/wallet_coin_record.py", line 11, in <module>
    from chia.wallet.puzzles.clawback.metadata import ClawbackMetadata, ClawbackVersion
ModuleNotFoundError: No module named 'chia.wallet.puzzles.clawback'
```

The version 1.8.1 seems to be fine.
<img width="873" alt="image" src="https://github.com/Chia-Network/chia-blockchain/assets/116863/6a9a4c6e-f099-4170-8c0e-601263c7f744">

### Version

1.8.2

### What platform are you using?

macOS

### What ui mode are you using?

CLI

**Comment by stefan-lange** [comment]
That is a known problem. Workaround: use https://github.com/Chia-Network/chia-blockchain/releases/tag/1.8.3-rc1
