### ISSUE TITLE
[BUG] Unable to run sh install.sh command

### ISSUE THREAD

**Issue by jimenezfer** [Chia-Network/chia-blockchain#1570]
**Describe the bug**
When running sh install.sh script fails 

**To Reproduce**
run  "sh install.sh"

see error 

Installing collected packages: chiapos, setproctitle, chiavdf
  Running setup.py develop for chiapos
    ERROR: Command errored out with exit status 1:
     command: /home/frank-zero/chia-blockchain-alpha-1.5/.venv/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/home/frank-zero/chia-blockchain-alpha-1.5/lib/chiapos/setup.py'"'"'; __file__='"'"'/home/frank-zero/chia-blockchain-alpha-1.5/lib/chiapos/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps
         cwd: /home/frank-zero/chia-blockchain-alpha-1.5/lib/chiapos/
    Complete output (100 lines):
    running develop
    running egg_info
    writing chiapos.egg-info/PKG-INFO
    writing dependency_links to chiapos.egg-info/dependency_links.txt
    writing requirements to chiapos.egg-info/requires.txt
    writing top-level names to chiapos.egg-info/top_level.txt
    reading manifest file 'chiapos.egg-info/SOURCES.txt'
    writing manifest file 'chiapos.egg-info/SOURCES.txt'
    running build_ext
    -- pybind11 v2.4.dev4
    -- AESNI Disabled
    -- Configuring done
    -- Generating done
    -- Build files have been written to: /home/frank-zero/chia-blockchain-alpha-1.5/lib/chiapos/build/temp.linux-x86_64-3.8
    -- pybind11 v2.4.dev4
    -- AESNI Disabled
    -- Configuring done
    -- Generating done
    -- Build files have been written to: /home/frank-zero/chia-blockchain-alpha-1.5/lib/chiapos/build/temp.linux-x86_64-3.8
    make[2]: Warning: File 'CMakeFiles/fse.dir/flags.make' has modification time 4978 s in the future
    make[2]: warning:  Clock skew detected.  Your build may be incomplete.
    make[2]: Warning: File 'CMakeFiles/fse.dir/flags.make' has modification time 4978 s in the future
    make[2]: warning:  Clock skew detected.  Your build may be incomplete.
    [ 71%] Built target fse
    make[2]: Warning: File 'CMakeFiles/RunTests.dir/flags.make' has modification time 4978 s in the future
    make[2]: Warning: File 'CMakeFiles/ProofOfSpace.dir/flags.make' has modification time 4978 s in the future
    make[2]: Warning: File 'CMakeFiles/HellmanAttacks.dir/flags.make' has modification time 4978 s in the future
    make[2]: Warning: File 'CMakeFiles/chiapos.dir/flags.make' has modification time 4978 s in the future
    make[2]: warning:  Clock skew detected.  Your build may be incomplete.
    make[2]: warning:  Clock skew detected.  Your build may be incomplete.
    make[2]: warning:  Clock skew detected.  Your build may be incomplete.
    make[2]: warning:  Clock skew detected.  Your build may be incomplete.
    make[2]: Warning: File 'CMakeFiles/ProofOfSpace.dir/flags.make' has modification time 4978 s in the future
    make[2]: Warning: File 'CMakeFiles/RunTests.dir/flags.make' has modification time 4978 s in the future
    make[2]: Warning: File 'CMakeFiles/HellmanAttacks.dir/flags.make' has modification time 4978 s in the future
    make[2]: Warning: File 'CMakeFiles/chiapos.dir/flags.make' has modification time 4978 s in the future
    [ 71%] Building CXX object CMakeFiles/RunTests.dir/tests/test.cpp.o
    [ 71%] Building CXX object CMakeFiles/HellmanAttacks.dir/src/cli.cpp.o
    [ 71%] Building CXX object CMakeFiles/ProofOfSpace.dir/src/cli.cpp.o
    [ 71%] Building CXX object CMakeFiles/RunTests.dir/tests/test-main.cpp.o
    [ 71%] Building CXX object CMakeFiles/chiapos.dir/python-bindings/chiapos.cpp.o
    cc1plus: error: bad value (‘tigerlake’) for ‘-march=’ switch
    cc1plus: error: bad value (‘tigerlake’) for ‘-march=’ switch
    cc1plus: note: valid arguments to ‘-march=’ switch are: nocona core2 nehalem corei7 westmere sandybridge corei7-avx ivybridge core-avx-i haswell core-avx2 broadwell skylake skylake-avx512 cannonlake icelake-client icelake-server cascadelake bonnell atom silvermont slm goldmont goldmont-plus tremont knl knm x86-64 eden-x2 nano nano-1000 nano-2000 nano-3000 nano-x2 eden-x4 nano-x4 k8 k8-sse3 opteron opteron-sse3 athlon64 athlon64-sse3 athlon-fx amdfam10 barcelona bdver1 bdver2 bdver3 bdver4 znver1 znver2 btver1 btver2 native
    cc1plus: note: valid arguments to ‘-march=’ switch are: nocona core2 nehalem corei7 westmere sandybridge corei7-avx ivybridge core-avx-i haswell core-avx2 broadwell skylake skylake-avx512 cannonlake icelake-client icelake-server cascadelake bonnell atom silvermont slm goldmont goldmont-plus tremont knl knm x86-64 eden-x2 nano nano-1000 nano-2000 nano-3000 nano-x2 eden-x4 nano-x4 k8 k8-sse3 opteron opteron-sse3 athlon64 athlon64-sse3 athlon-fx amdfam10 barcelona bdver1 bdver2 bdver3 bdver4 znver1 znver2 btver1 btver2 native
    cc1plus: error: bad value (‘tigerlake’) for ‘-mtune=’ switch
    cc1plus: error: bad value (‘tigerlake’) for ‘-mtune=’ switch
    cc1plus: note: valid arguments to ‘-mtune=’ switch are: nocona core2 nehalem corei7 westmere sandybridge corei7-avx ivybridge core-avx-i haswell core-avx2 broadwell skylake skylake-avx512 cannonlake icelake-client icelake-server cascadelake bonnell atom silvermont slm goldmont goldmont-plus tremont knl knm intel x86-64 eden-x2 nano nano-1000 nano-2000 nano-3000 nano-x2 eden-x4 nano-x4 k8 k8-sse3 opteron opteron-sse3 athlon64 athlon64-sse3 athlon-fx amdfam10 barcelona bdver1 bdver2 bdver3 bdver4 znver1 znver2 btver1 btver2 generic native
    cc1plus: note: valid arguments to ‘-mtune=’ switch are: nocona core2 nehalem corei7 westmere sandybridge corei7-avx ivybridge core-avx-i haswell core-avx2 broadwell skylake skylake-avx512 cannonlake icelake-client icelake-server cascadelake bonnell atom silvermont slm goldmont goldmont-plus tremont knl knm intel x86-64 eden-x2 nano nano-1000 nano-2000 nano-3000 nano-x2 eden-x4 nano-x4 k8 k8-sse3 opteron opteron-sse3 athlon64 athlon64-sse3 athlon-fx amdfam10 barcelona bdver1 bdver2 bdver3 bdver4 znver1 znver2 btver1 btver2 generic native
    cc1plus: error: bad value (‘tigerlake’) for ‘-march=’ switch
    cc1plus: note: valid arguments to ‘-march=’ switch are: nocona core2 nehalem corei7 westmere sandybridge corei7-avx ivybridge core-avx-i haswell core-avx2 broadwell skylake skylake-avx512 cannonlake icelake-client icelake-server cascadelake bonnell atom silvermont slm goldmont goldmont-plus tremont knl knm x86-64 eden-x2 nano nano-1000 nano-2000 nano-3000 nano-x2 eden-x4 nano-x4 k8 k8-sse3 opteron opteron-sse3 athlon64 athlon64-sse3 athlon-fx amdfam10 barcelona bdver1 bdver2 bdver3 bdver4 znver1 znver2 btver1 btver2 native
    cc1plus: error: bad value (‘tigerlake’) for ‘-mtune=’ switch
    cc1plus: note: valid arguments to ‘-mtune=’ switch are: nocona core2 nehalem corei7 westmere sandybridge corei7-avx ivybridge core-avx-i haswell core-avx2 broadwell skylake skylake-avx512 cannonlake icelake-client icelake-server cascadelake bonnell atom silvermont slm goldmont goldmont-plus tremont knl knm intel x86-64 eden-x2 nano nano-1000 nano-2000 nano-3000 nano-x2 eden-x4 nano-x4 k8 k8-sse3 opteron opteron-sse3 athlon64 athlon64-sse3 athlon-fx amdfam10 barcelona bdver1 bdver2 bdver3 bdver4 znver1 znver2 btver1 btver2 generic native
    make[2]: *** [CMakeFiles/ProofOfSpace.dir/build.make:63: CMakeFiles/ProofOfSpace.dir/src/cli.cpp.o] Error 1
    make[2]: *** [CMakeFiles/HellmanAttacks.dir/build.make:63: CMakeFiles/HellmanAttacks.dir/src/cli.cpp.o] Error 1
    make[1]: *** [CMakeFiles/Makefile2:131: CMakeFiles/ProofOfSpace.dir/all] Error 2
    make[1]: *** Waiting for unfinished jobs....
    make[1]: *** [CMakeFiles/Makefile2:158: CMakeFiles/HellmanAttacks.dir/all] Error 2
    make[2]: *** [CMakeFiles/RunTests.dir/build.make:76: CMakeFiles/RunTests.dir/tests/test.cpp.o] Error 1
    make[2]: *** Waiting for unfinished jobs....
    cc1plus: error: bad value (‘tigerlake’) for ‘-march=’ switch
    cc1plus: note: valid arguments to ‘-march=’ switch are: nocona core2 nehalem corei7 westmere sandybridge corei7-avx ivybridge core-avx-i haswell core-avx2 broadwell skylake skylake-avx512 cannonlake icelake-client icelake-server cascadelake bonnell atom silvermont slm goldmont goldmont-plus tremont knl knm x86-64 eden-x2 nano nano-1000 nano-2000 nano-3000 nano-x2 eden-x4 nano-x4 k8 k8-sse3 opteron opteron-sse3 athlon64 athlon64-sse3 athlon-fx amdfam10 barcelona bdver1 bdver2 bdver3 bdver4 znver1 znver2 btver1 btver2 native
    cc1plus: error: bad value (‘tigerlake’) for ‘-mtune=’ switch
    cc1plus: note: valid arguments to ‘-mtune=’ switch are: nocona core2 nehalem corei7 westmere sandybridge corei7-avx ivybridge core-avx-i haswell core-avx2 broadwell skylake skylake-avx512 cannonlake icelake-client icelake-server cascadelake bonnell atom silvermont slm goldmont goldmont-plus tremont knl knm intel x86-64 eden-x2 nano nano-1000 nano-2000 nano-3000 nano-x2 eden-x4 nano-x4 k8 k8-sse3 opteron opteron-sse3 athlon64 athlon64-sse3 athlon-fx amdfam10 barcelona bdver1 bdver2 bdver3 bdver4 znver1 znver2 btver1 btver2 generic native
    make[2]: *** [CMakeFiles/RunTests.dir/build.make:63: CMakeFiles/RunTests.dir/tests/test-main.cpp.o] Error 1
    make[1]: *** [CMakeFiles/Makefile2:104: CMakeFiles/RunTests.dir/all] Error 2
    cc1plus: error: bad value (‘tigerlake’) for ‘-march=’ switch
    cc1plus: note: valid arguments to ‘-march=’ switch are: nocona core2 nehalem corei7 westmere sandybridge corei7-avx ivybridge core-avx-i haswell core-avx2 broadwell skylake skylake-avx512 cannonlake icelake-client icelake-server cascadelake bonnell atom silvermont slm goldmont goldmont-plus tremont knl knm x86-64 eden-x2 nano nano-1000 nano-2000 nano-3000 nano-x2 eden-x4 nano-x4 k8 k8-sse3 opteron opteron-sse3 athlon64 athlon64-sse3 athlon-fx amdfam10 barcelona bdver1 bdver2 bdver3 bdver4 znver1 znver2 btver1 btver2 native
    cc1plus: error: bad value (‘tigerlake’) for ‘-mtune=’ switch
    cc1plus: note: valid arguments to ‘-mtune=’ switch are: nocona core2 nehalem corei7 westmere sandybridge corei7-avx ivybridge core-avx-i haswell core-avx2 broadwell skylake skylake-avx512 cannonlake icelake-client icelake-server cascadelake bonnell atom silvermont slm goldmont goldmont-plus tremont knl knm intel x86-64 eden-x2 nano nano-1000 nano-2000 nano-3000 nano-x2 eden-x4 nano-x4 k8 k8-sse3 opteron opteron-sse3 athlon64 athlon64-sse3 athlon-fx amdfam10 barcelona bdver1 bdver2 bdver3 bdver4 znver1 znver2 btver1 btver2 generic native
    make[2]: *** [CMakeFiles/chiapos.dir/build.make:63: CMakeFiles/chiapos.dir/python-bindings/chiapos.cpp.o] Error 1
    make[1]: *** [CMakeFiles/Makefile2:185: CMakeFiles/chiapos.dir/all] Error 2
    make: *** [Makefile:84: all] Error 2
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/home/frank-zero/chia-blockchain-alpha-1.5/lib/chiapos/setup.py", line 67, in <module>
        setup(
      File "/home/frank-zero/chia-blockchain-alpha-1.5/.venv/lib/python3.8/site-packages/setuptools/__init__.py", line 153, in setup
        return distutils.core.setup(**attrs)
      File "/usr/lib/python3.8/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/lib/python3.8/distutils/dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/home/frank-zero/chia-blockchain-alpha-1.5/.venv/lib/python3.8/site-packages/setuptools/command/develop.py", line 34, in run
        self.install_for_development()
      File "/home/frank-zero/chia-blockchain-alpha-1.5/.venv/lib/python3.8/site-packages/setuptools/command/develop.py", line 136, in install_for_development
        self.run_command('build_ext')
      File "/usr/lib/python3.8/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/home/frank-zero/chia-blockchain-alpha-1.5/lib/chiapos/setup.py", line 35, in run
        self.build_extension(ext)
      File "/home/frank-zero/chia-blockchain-alpha-1.5/lib/chiapos/setup.py", line 63, in build_extension
        subprocess.check_call(['cmake', '--build', '.'] +
      File "/usr/lib/python3.8/subprocess.py", line 364, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['cmake', '--build', '.', '--config', 'Release', '--', '-j', '6']' returned non-zero exit status 2.
    ----------------------------------------
ERROR: Command errored out with exit status 1: /home/frank-zero/chia-blockchain-alpha-1.5/.venv/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/home/frank-zero/chia-blockchain-alpha-1.5/lib/chiapos/setup.py'"'"'; __file__='"'"'/home/frank-zero/chia-blockchain-alpha-1.5/lib/chiapos/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps Check the logs for full command output.

**Expected behavior**
finish install, in ubuntu 20.04

**Screenshots**

![image](https://user-images.githubusercontent.com/23113643/112914370-d1588e00-90c9-11eb-8417-33880d923866.png)

**Desktop (please complete the following information):**

- OS: ubuntu 20.04
- CPU: VGA compatible controller: Intel Corporation Device 9a49 (rev 01)

**Additional context**
not much just installed python and then ran the install.sh and it blow up.

**Comment by hoffmang9** [comment]
Is that a 64 bit version of Ubuntu?

**Comment by jimenezfer** [comment]
Yes it is.

**Comment by hoffmang9** [comment]
You're building in an old alpha clone and it's picking up unsupported packages. You need to confirm that you have python 3.7 or newer with `python3 --version` and you should delete and reclone following the install instructions here https://github.com/Chia-Network/chia-blockchain/wiki/INSTALL#ubuntudebian

**Comment by jimenezfer** [comment]
chiapos is a C++ thing that is wrapped by python ?

**Comment by jimenezfer** [comment]
I have  Python 3.8.5.

ill reclone , thanks!
