### ISSUE TITLE
[Bug] Out of memory: Killed process XXXX (chia_full_node)

### ISSUE THREAD

**Issue by jonathan-molyneux** [Chia-Network/chia-blockchain#15719]
### What happened?

chia_full_node keeps triggering oom, even when it's given enough memory (system has 4gb)

Out of memory: Killed process 22965 (chia_full_node) total-vm:1330764kB, anon-rss:469828kB, file-rss:0kB, shmem-rss:8kB, UID:1008 pgtables:1468kB oom_score_adj:0

The system is running debian 10, have tried debian 11 and debian 12 all have the issue.

### Version

1.8.2

### What platform are you using?

Linux

### What ui mode are you using?

CLI

### Relevant log output

```shell
2023-07-09T22:55:22.268 daemon chia.daemon.server         : ERROR    Ping error to chia_full_node
Traceback (most recent call last):
  File "chia/daemon/server.py", line 303, in ping_task
  File "aiohttp/web_ws.py", line 295, in ping
  File "aiohttp/http_websocket.py", line 676, in ping
  File "aiohttp/http_websocket.py", line 653, in _send_frame
  File "aiohttp/http_websocket.py", line 663, in _write
ConnectionResetError: Cannot write to closing transport
2023-07-09T22:55:22.285 daemon chia.daemon.server         : ERROR    Ping failed, connection closed to chia_full_node.
```

**Comment by wjblanke** [comment]
try adding 2gb swap space. what else are you running at the same time?
