### ISSUE TITLE
[Bug] Chia Plotter Task Crashed because of Asyncio

### ISSUE THREAD

**Issue by AFCzzi** [Chia-Network/chia-blockchain#15723]
### What happened?

When using the GUI versions 1.6.1 and newer, the plotter crashed after showing the following error message. Everything else appeared to be normal except for the plotter.

### Version

1.8.2

### What platform are you using?

Windows

### What ui mode are you using?

GUI

### Relevant log output

```shell
Traceback (most recent call last):
  File "asyncio\windows_events.py", line 439, in select
RuntimeError: <_overlapped.Overlapped object at 0x0000022CF03DD6F0> still has pending operation at deallocation, the process may crash
Traceback (most recent call last):
  File "asyncio\windows_events.py", line 439, in select
RuntimeError: <_overlapped.Overlapped object at 0x0000022CF04B5420> still has pending operation at deallocation, the process may crash
Traceback (most recent call last):
  File "asyncio\windows_events.py", line 439, in select
RuntimeError: <_overlapped.Overlapped object at 0x0000022CF04B5420> still has pending operation at deallocation, the process may crash

Starting plotting progress into temporary dirs: C:\temp and C:\temp
ID: 2c9b2ebd508597aec7ef1301db7da064d0d1f5b50ed45d9dd6c73521c4340e43
Plot size is: 32
Buffer size is: 500000MiB
Using 128 buckets
Final Directory is: A:\AA
Using 20 threads of stripe size 65536
Process ID is: 3348

Starting phase 1/4: Forward Propagation into tmp files... Mon Jul 10 11:32:34 2023
Computing table 1
Progress update: 0.01
F1 complete, time: 284.418 seconds. CPU (195.85%) Mon Jul 10 11:37:19 2023
Computing table 2
Progress update: 0.06
Caught plotting error: bad allocation
Traceback (most recent call last):
  File "asyncio\windows_events.py", line 439, in select
RuntimeError: <_overlapped.Overlapped object at 0x0000022CF03DDC00> still has pending operation at deallocation, the process may crash
Traceback (most recent call last):
  File "asyncio\windows_events.py", line 439, in select
RuntimeError: <_overlapped.Overlapped object at 0x0000022CF03DDC00> still has pending operation at deallocation, the process may crash
Traceback (most recent call last):
  File "chia\cmds\chia.py", line 153, in <module>
  File "chia\cmds\chia.py", line 149, in main
  File "click\core.py", line 829, in __call__
  File "click\core.py", line 782, in main
  File "click\core.py", line 1259, in invoke
  File "click\core.py", line 1066, in invoke
  File "click\core.py", line 610, in invoke
  File "click\decorators.py", line 21, in new_func
  File "chia\cmds\plotters.py", line 14, in plotters_cmd
  File "chia\plotters\plotters.py", line 346, in call_plotters
  File "chia\plotters\chiapos.py", line 56, in plot_chia
  File "asyncio\runners.py", line 44, in run
  File "asyncio\base_events.py", line 647, in run_until_complete
  File "chia\plotting\create_plots.py", line 227, in create_plots
RuntimeError: bad allocation
[3348] Failed to execute script 'chia' due to unhandled exception!
```

```shell
Traceback (most recent call last):
  File "asyncio\windows_events.py", line 439, in select
RuntimeError: <_overlapped.Overlapped object at 0x0000017FB53F8420> still has pending operation at deallocation, the process may crash
Traceback (most recent call last):
  File "asyncio\windows_events.py", line 439, in select
RuntimeError: <_overlapped.Overlapped object at 0x0000017FB547A030> still has pending operation at deallocation, the process may crash
Traceback (most recent call last):
  File "asyncio\windows_events.py", line 439, in select
RuntimeError: <_overlapped.Overlapped object at 0x0000017FB547A030> still has pending operation at deallocation, the process may crash
```

```[tasklist]
### Tasks
```

**Comment by wjblanke** [comment]
Buffer size is: 500,000MiB is a lot of memory! do u have that much?

how much memory does your system have? to clarify you are using the stock chiapos plotter? what options are u using for the plotter? u can just make a screenshot (without showing keys please).

**Comment by AFCzzi** [comment]
I am currently plotting on a self-built server. The server has 18 32Gb Samsung RAM sticks. The server uses Windows 10 as the operating system. I installed Chia GUI and tried all three plotting options available on the Chia GUI, but they all crashed showing the error message in my previous post.
I designed the server to have this much memory so that I could use Bladebit RAM plotter, however, everytime I use Bladebit RAM plotter, it crashed.
Here is a picture of the server:
![a614f763143b39c092a6cd4635e1ec2](https://github.com/Chia-Network/chia-blockchain/assets/63986062/f1083b9e-0d14-4220-9d68-de54f28976d9)
Error message that shows up when using Bladebit RAM plotter:
```Traceback (most recent call last):
  File "asyncio\windows_events.py", line 439, in select
RuntimeError: &lt;_overlapped.Overlapped object at 0x000001A271033780&gt; still has pending operation at deallocation, the process may crash
Traceback (most recent call last):
  File "asyncio\windows_events.py", line 439, in select
RuntimeError: &lt;_overlapped.Overlapped object at 0x000001A2710C2270&gt; still has pending operation at deallocation, the process may crash
Traceback (most recent call last):
  File "asyncio\windows_events.py", line 439, in select
RuntimeError: &lt;_overlapped.Overlapped object at 0x000001A2710C2270&gt; still has pending operation at deallocation, the process may crash
Creating 1 plots:
 Output path           : A:\AA
 Thread count          : 20
 Warm start enabled    : true
 Farmer public key     : 8cd79c163f2bbbb0d097fa6b4b60626005a870d3ba3c4cf42b06cbb6b3a80d24f35d73ab6f09c69ed98328c1c0f2c562
 Pool public key       : 8a6e724407567aecaee6a36222e93824da031e26e1b08b0ab7125206a99eed50ff56bef5b1aab19cf1b2e93683a3d989

System Memory: 562/575 GiB.
Memory required: 416 GiB.
Allocating buffers.
Traceback (most recent call last):
  File "asyncio\windows_events.py", line 439, in select
RuntimeError: &lt;_overlapped.Overlapped object at 0x000001A271033930&gt; still has pending operation at deallocation, the process may crash
Traceback (most recent call last):
  File "asyncio\windows_events.py", line 439, in select
RuntimeError: &lt;_overlapped.Overlapped object at 0x000001A271033930&gt; still has pending operation at deallocation, the process may crash```

**Comment by wjblanke** [comment]
Try the bladebit executable directly instead of through the GUI. These "asyncio\windows_events.py" errors are from python and if you run the executable directly we can rule them out.
