### ISSUE TITLE
[Bug] Chia Plotter Crashed Due to Asyncio

### ISSUE THREAD

**Issue by AFCzzi** [Chia-Network/chia-blockchain#15722]
### What happened?

When I started the plotting process on my Windows 11 PC, the plotter crashed and it does not appear that I did anything wrong because when I fallback the software to the 1.6.2 release, although there was still the notice output, but it can still plot and function normally.

### Version

1.8.2

### What platform are you using?

Windows

### What ui mode are you using?

GUI

### Relevant log output

```shell
Traceback (most recent call last):
  File "asyncio\windows_events.py", line 439, in select
RuntimeError: <_overlapped.Overlapped object at 0x000002832F9D01E0> still has pending operation at deallocation, the process may crash
Traceback (most recent call last):
  File "asyncio\windows_events.py", line 439, in select
RuntimeError: <_overlapped.Overlapped object at 0x000002832F9D01E0> still has pending operation at deallocation, the process may crash
```

**Comment by AFCzzi** [comment]
I made an error in stating the correct version of Chia GUI that worked for me, it was the 1.6.0 version that worked. Although there was still that error message, but the plotter was still able to plot. To my surprise though, everything else appeared to be running smoothly with the newer versions except for the plotter.
