### ISSUE TITLE
[Bug] Exception: A child process terminated abruptly, the process pool is not usable anymore

### ISSUE THREAD

**Issue by hbroer** [Chia-Network/chia-blockchain#15791]
### What happened?

After updating from 1.8.2 farming stoped after ~ 30 minutes with spaming this error:

```
Exception: A child process terminated abruptly, the process pool is not usable anymore
```

### Service status:

```
● chiafarmer.service - Chia Farmer
     Loaded: loaded (/etc/systemd/system/chiafarmer.service; enabled; vendor preset: enabled)
     Active: active (running) since Sun 2023-07-16 16:52:33 UTC; 1h 38min ago
    Process: 1480 ExecStart=/usr/bin/env chia start farmer-no-wallet -r (code=exited, status=0/SUCCESS)
   Main PID: 1564 (chia_daemon)
      Tasks: 35 (limit: 2142)
     Memory: 1.0G
        CPU: 22min 28.672s
     CGroup: /system.slice/chiafarmer.service
             ├─1564 chia_daemon "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" ">
             ├─1725 chia_harvester "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" ""
             ├─1726 chia_farmer "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" ""
             ├─1727 chia_full_node "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" ""
             ├─1764 /PATHHIDDEN/venv/bin/python -c "from multiprocessing.resource_tracker import main;main(18)"
             ├─1855 chia_full_node_worker "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" >
             └─1858 chia_full_node_worker "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" >

Jul 16 16:52:33 farm systemd[1]: Started Chia Farmer.
Jul 16 17:25:37 farm env[3286]: Traceback (most recent call last):
Jul 16 17:25:37 farm env[3286]:   File "<string>", line 1, in <module>
Jul 16 17:25:37 farm env[3286]:   File "/usr/lib/python3.10/multiprocessing/spawn.py", line 116, in spawn_main
Jul 16 17:25:37 farm env[3286]:     exitcode = _main(fd, parent_sentinel)
Jul 16 17:25:37 farm env[3286]:   File "/usr/lib/python3.10/multiprocessing/spawn.py", line 126, in _main
Jul 16 17:25:37 farm env[3286]:     self = reduction.pickle.load(from_parent)
Jul 16 17:25:37 farm env[3286]:   File "/usr/lib/python3.10/multiprocessing/synchronize.py", line 110, in __setstate__
Jul 16 17:25:37 farm env[3286]:     self._semlock = _multiprocessing.SemLock._rebuild(*state)
Jul 16 17:25:37 farm env[3286]: FileNotFoundError: [Errno 2] No such file or directory
```

### Maybe related config
```
full_node:
  multiprocessing_start_method: spawn
  reserved_cores: 2
```

Before the update (only did it because had some time), it run for ~ one month without a problem or any restart with that config. After restarting the service it is farming now again, but not sure how long it will last.

### Version

1.8.2

### What platform are you using?

Pi4

### What ui mode are you using?

CLI

### Relevant log output

```shell
2023-07-16T18:19:38.313 full_node full_node_server        : ERROR    Exception: A child process terminated abruptly, the process pool is not usable anymore <class 'concurrent.futures.process.BrokenProcessPool'>, closing connection PeerInfo(_ip=IPv4Address('IPHIDDEN'), _port=8444). Traceback (most recent call last):
  File "/PATHHIDDEN/chia/server/ws_connection.py", line 403, in _api_call
    response: Optional[Message] = await asyncio.wait_for(wrapped_coroutine(), timeout=timeout)
  File "/usr/lib/python3.10/asyncio/tasks.py", line 408, in wait_for
    return await fut
  File "/PATHHIDDEN/chia/server/ws_connection.py", line 393, in wrapped_coroutine
    result: Message = await coroutine
  File "/PATHHIDDEN/chia/full_node/full_node_api.py", line 133, in new_peak
    await self.full_node.new_peak(request, peer)
  File "/PATHHIDDEN/chia/full_node/full_node.py", line 737, in new_peak
    if await self.short_sync_batch(peer, uint32(max(curr_peak_height - 6, 0)), request.height):
  File "/PATHHIDDEN/chia/full_node/full_node.py", line 581, in short_sync_batch
    success, state_change_summary = await self.add_block_batch(response.blocks, peer, None)
  File "/PATHHIDDEN/chia/full_node/full_node.py", line 1233, in add_block_batch
    pre_validation_results: List[PreValidationResult] = await self.blockchain.pre_validate_blocks_multiprocessing(
  File "/PATHHIDDEN/chia/consensus/blockchain.py", line 637, in pre_validate_blocks_multiprocessing
    return await pre_validate_blocks_multiprocessing(
  File "/PATHHIDDEN/chia/consensus/multiprocess_validation.py", line 333, in pre_validate_blocks_multiprocessing
    asyncio.get_running_loop().run_in_executor(
  File "/usr/lib/python3.10/asyncio/base_events.py", line 818, in run_in_executor
    executor.submit(func, *args), loop=self)
  File "/usr/lib/python3.10/concurrent/futures/process.py", line 715, in submit
    raise BrokenProcessPool(self._broken)
concurrent.futures.process.BrokenProcessPool: A child process terminated abruptly, the process pool is not usable anymore
```

**Comment by hbroer** [comment]
After restart the current service status is

``` 
● chiafarmer.service - Chia Farmer
     Loaded: loaded (/etc/systemd/system/chiafarmer.service; enabled; vendor preset: enabled)
     Active: active (running) since Sun 2023-07-16 18:43:01 UTC; 18min ago
    Process: 4824 ExecStart=/usr/bin/env chia start farmer-no-wallet -r (code=exited, status=0/SUCCESS)
   Main PID: 4832 (chia_daemon)
      Tasks: 34 (limit: 2142)
     Memory: 1.1G
        CPU: 8min 47.185s
     CGroup: /system.slice/chiafarmer.service
             ├─4832 chia_daemon "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" ">
             ├─4843 chia_harvester "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" ""
             ├─4844 chia_farmer "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" ""
             ├─4845 chia_full_node "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" ""
             ├─4876 /PATHHIDDEN/venv/bin/python -c "from multiprocessing.resource_tracker import main;main(18)"
             ├─4906 chia_full_node_worker "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" >
             ├─4909 chia_full_node_worker "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" >
             ├─4999 chia_full_node_worker "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" >
             └─5013 chia_full_node_worker "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" >

Jul 16 18:42:51 farm systemd[1]: Starting Chia Farmer...
Jul 16 18:43:00 farm env[4824]: Daemon not started yet
Jul 16 18:43:00 farm env[4824]: Starting daemon
Jul 16 18:43:00 farm env[4824]: chia_harvester: started
Jul 16 18:43:00 farm env[4824]: chia_farmer: started
Jul 16 18:43:00 farm env[4824]: chia_full_node: started
Jul 16 18:43:01 farm systemd[1]: Started Chia Farmer.
```

Two more workers, 4 instead of two with the failed status in starting post.

Question: Why so many worker? The Pi4 has only 4 cores, reserved_cores is set to 2 and db_readers to 1. I would expect it to start two workers + one db reader. Or is it a reader, a writer and two worker?

**Comment by wjblanke** [comment]
so there are a lot of things here. i would set multiprocessing back to fork from spawn as it is more tested being pythons default. we've seen issues with spawn under linux. also for the workers, possibly u have zombie processes from previous runs (2) where u had a crash and now u have 4 (2+2)? probably u should reboot. definitely we will leave this issue open.

**Comment by hbroer** [comment]
Before each start there was a reboot. They both where clean runs started via the service after boot. I always restart after a update even if it is not neccessary. I once had a problem with chia after a system update without a restart. It was openssl or so which got updated if I remember it correctly.

I can set it back to fork but I noticed that the main process with fork increased memory usage over time (weeks). But I may check out the other settings again as well because of the new version. Now it runs since 3 days without a problem (since the last restart on 16th july). I will wait with any changes until I need to restart it or something goes wrong.

Btw can you tell me the differences of the settings? The documentation I found of the chia settings are not very helpful. Maybe I missed the real documentation.

**Comment by wjblanke** [comment]
You can read about start methods here

https://docs.python.org/3/library/multiprocessing.html#contexts-and-start-methods

Fork will tend to have more memory usage over time as different processes dirty their shared memory pages and they become local.

Closing issue. Reopen if you have further problems.
