### ISSUE TITLE
[Bug] 1.8.2  not synced issue

### ISSUE THREAD

**Issue by maogo** [Chia-Network/chia-blockchain#15874]
### What happened?

It happens every few days to me, you must restart your farmer to sync.

the same report :
https://www.reddit.com/r/chia/comments/1549l9c/chia_node_randomly_not_synced/

### Version

1.8.2

### What platform are you using?

Linux

### What ui mode are you using?

CLI

### Relevant log output

```shell
2023-07-27T12:36:21.650 full_node full_node_server        : ERROR    Exception: Failed to fetch block 4001115 from PeerInfo(_ip=IPv4Address('176.249.244.240'), _port=8444), timed out, PeerInfo(_ip=IPv4Address('176.249.244.240'), _port=8444). Traceback (most recent call last):
  File "chia/server/ws_connection.py", line 393, in wrapped_coroutine
  File "chia/full_node/full_node_api.py", line 133, in new_peak
  File "chia/full_node/full_node.py", line 724, in new_peak
  File "chia/full_node/full_node.py", line 642, in short_sync_backtrack
ValueError: Failed to fetch block 4001115 from PeerInfo(_ip=IPv4Address('176.249.244.240'), _port=8444), timed out

2023-07-27T12:36:21.650 full_node full_node_server        : WARNING  Banning 176.249.244.240 for 10 seconds
2023-07-27T12:36:21.651 full_node full_node_server        : ERROR    Exception: Failed to fetch block 4001119 from PeerInfo(_ip=IPv4Address('176.249.244.240'), _port=8444), timed out, PeerInfo(_ip=IPv4Address('176.249.244.240'), _port=8444). Traceback (most recent call last):
  File "chia/server/ws_connection.py", line 393, in wrapped_coroutine
  File "chia/full_node/full_node_api.py", line 133, in new_peak
  File "chia/full_node/full_node.py", line 724, in new_peak
  File "chia/full_node/full_node.py", line 642, in short_sync_backtrack
ValueError: Failed to fetch block 4001119 from PeerInfo(_ip=IPv4Address('176.249.244.240'), _port=8444), timed out

2023-07-27T12:36:21.652 full_node full_node_server        : WARNING  Banning 176.249.244.240 for 10 seconds
2023-07-27T12:36:21.653 full_node full_node_server        : ERROR    Exception: Failed to fetch block 4001123 from PeerInfo(_ip=IPv4Address('176.249.244.240'), _port=8444), timed out, PeerInfo(_ip=IPv4Address('176.249.244.240'), _port=8444). Traceback (most recent call last):
  File "chia/server/ws_connection.py", line 393, in wrapped_coroutine
  File "chia/full_node/full_node_api.py", line 133, in new_peak
  File "chia/full_node/full_node.py", line 724, in new_peak
  File "chia/full_node/full_node.py", line 642, in short_sync_backtrack
ValueError: Failed to fetch block 4001123 from PeerInfo(_ip=IPv4Address('176.249.244.240'), _port=8444), timed out

2023-07-27T12:36:21.653 full_node full_node_server        : WARNING  Banning 176.249.244.240 for 10 seconds
2023-07-27T12:36:21.655 full_node full_node_server        : ERROR    Exception: Failed to fetch block 4001124 from PeerInfo(_ip=IPv4Address('176.249.244.240'), _port=8444), timed out, PeerInfo(_ip=IPv4Address('176.249.244.240'), _port=8444). Traceback (most recent call last):
  File "chia/server/ws_connection.py", line 393, in wrapped_coroutine
  File "chia/full_node/full_node_api.py", line 133, in new_peak
  File "chia/full_node/full_node.py", line 724, in new_peak
  File "chia/full_node/full_node.py", line 642, in short_sync_backtrack
ValueError: Failed to fetch block 4001124 from PeerInfo(_ip=IPv4Address('176.249.244.240'), _port=8444), timed out

2023-07-27T12:36:21.655 full_node full_node_server        : WARNING  Banning 176.249.244.240 for 10 seconds
```

```[tasklist]
### Tasks
```

**Comment by emlowe** [comment]
This indicates some type of network error, as you timed out trying to retrieve blocks. This doesn't indicate any issue with Chia. Check how many connections you have and make sure your incoming node is accepting incoming connections. Having multiple peers is the best way to maintain sync with the network
