### ISSUE TITLE
[BUG] RuntimeError: bad allocation

### ISSUE THREAD

**Issue by Dravenex** [Chia-Network/chia-blockchain#1590]
Somehow I get this error for my fifth plot. I have 32 GB of RAM and an i7-5820K with 6 cores. I would like to run 5 plots parallel due to 2 x 1 TB 860 Evo Raid 0 capacitiy limits. In the past I had no problem, maybe since I updated from V1.0 to 1.0.1 the error occurs? 

Starting plotting progress into temporary dirs: D:\ and D:\
ID: 
Plot size is: 32
Buffer size is: 4608MiB
Using 128 buckets
Using 2 threads of stripe size 65536

Starting phase 1/4: Forward Propagation into tmp files... Tue Mar 30 01:13:24 2021
Computing table 1
F1 complete, time: 97.303 seconds. CPU (172.73%) Tue Mar 30 01:15:01 2021
Computing table 2
Caught plotting error: bad allocation
[13612] Failed to execute script chia
Traceback (most recent call last):
  File "src\cmds\chia.py", line 80, in <module>
  File "src\cmds\chia.py", line 76, in main
  File "click\core.py", line 829, in __call__
  File "click\core.py", line 782, in main
  File "click\core.py", line 1259, in invoke
  File "click\core.py", line 1259, in invoke
  File "click\core.py", line 1066, in invoke
  File "click\core.py", line 610, in invoke
  File "click\decorators.py", line 21, in new_func
  File "src\cmds\plots.py", line 134, in create_cmd
  File "src\plotting\create_plots.py", line 176, in create_plots
RuntimeError: bad allocation

**Comment by mariano54** [comment]
Have you checked your RAM for issues?

**Comment by Dravenex** [comment]
I tested my RAM and everything is OK. I'm still getting this error. I don't believe that it's a hardware fault, because I only have this problems since V1.0.3.

Starting phase 1/4: Forward Propagation into tmp files... Fri Apr  9 09:18:08 2021
Computing table 1
F1 complete, time: 191.968 seconds. CPU (164.23%) Fri Apr  9 09:21:20 2021
Computing table 2
Caught plotting error: bad allocation
[16200] Failed to execute script chia
Traceback (most recent call last):
  File "src\cmds\chia.py", line 80, in <module>
  File "src\cmds\chia.py", line 76, in main
  File "click\core.py", line 829, in __call__
  File "click\core.py", line 782, in main
  File "click\core.py", line 1259, in invoke
  File "click\core.py", line 1259, in invoke
  File "click\core.py", line 1066, in invoke
  File "click\core.py", line 610, in invoke
  File "click\decorators.py", line 21, in new_func
  File "src\cmds\plots.py", line 134, in create_cmd
  File "src\plotting\create_plots.py", line 176, in create_plots
RuntimeError: bad allocation

**Comment by Dravenex** [comment]
So, I could fix this issue all by myself. As expected, it wasn't a hardware issue.

The problem was that I reduced the size of the pagefile.sys file too much. In Windows there is an option called "virtual RAM" that decides how big the pagefile.sys is. Once I changed the option again to "Managed by system" parallel plotting started working again.
