### ISSUE TITLE
[Bug] App can't sync

### ISSUE THREAD

**Issue by slavcho12** [Chia-Network/chia-blockchain#15942]
### What happened?

App can't sync. Please help.
Version is 1.8.2

### Version

1.8.2

### What platform are you using?

Windows

### What ui mode are you using?

GUI

### Relevant log output

```shell
2023-08-05T16:34:32.958 full_node chia.full_node.full_node: ERROR    sync from fork point failed err: no such savepoint: s368
2023-08-05T16:34:53.235 full_node asyncio                 : ERROR    Task was destroyed but it is pending!
task: <Task pending name='Task-88499' coro=<FullNode.sync_from_fork_point.<locals>.fetch_block_batches() running at chia\full_node\full_node.py:1099> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x000001AF59FF03D0>()]> cb=[_gather.<locals>._done_callback() at asyncio\tasks.py:767]>
2023-08-05T16:35:23.850 full_node chia.consensus.blockchain: ERROR    Error while adding block f554faeaf180adb58c1a217d3c6d2d696bd022c53e931b7548d4c8a2df2797 height 4025360, rolling back: Traceback (most recent call last):
  File "chia\consensus\blockchain.py", line 270, in add_block
  File "chia\consensus\blockchain.py", line 408, in _reconsider_peak
  File "chia\full_node\coin_store.py", line 153, in new_block
  File "chia\full_node\coin_store.py", line 525, in _add_coin_records
  File "aiosqlite\core.py", line 216, in executemany
  File "aiosqlite\core.py", line 133, in _execute
  File "aiosqlite\core.py", line 106, in run
sqlite3.OperationalError: disk I/O error
 disk I/O error
2023-08-05T16:35:23.850 full_node chia.full_node.full_node: ERROR    sync from fork point failed err: no such savepoint: s372
2023-08-05T16:36:16.509 full_node chia.consensus.blockchain: ERROR    Error while adding block f554faeaf180adb58c1a217d3c6d2d696bd022c53e931b7548d4c8a2df2797 height 4025360, rolling back: Traceback (most recent call last):
  File "chia\consensus\blockchain.py", line 270, in add_block
  File "chia\consensus\blockchain.py", line 408, in _reconsider_peak
  File "chia\full_node\coin_store.py", line 153, in new_block
  File "chia\full_node\coin_store.py", line 525, in _add_coin_records
  File "aiosqlite\core.py", line 216, in executemany
  File "aiosqlite\core.py", line 133, in _execute
  File "aiosqlite\core.py", line 106, in run
sqlite3.OperationalError: disk I/O error
 disk I/O error
2023-08-05T16:36:16.509 full_node chia.full_node.full_node: ERROR    sync from fork point failed err: no such savepoint: s376
```

**Comment by shaneo257** [comment]
What type of disk is the database stored on?
Has it got enough free space?
Done a smart scan and has no errors?
Checked that the cables are secured to the drive correctly?
