### ISSUE TITLE
Wallet did not display the amount of Stably USDS [Bug] 

### ISSUE THREAD

**Issue by Magicwalker** [Chia-Network/chia-blockchain#15966]
### What happened?

1. Version 2.0.0 RC3, when sending coins 500 usds from Goby to wallet on receive address did not display on UI. 
2. Close the Chia UI , delete wallet db and check process no more any chia.exe also same. Newly send over 500 usds was not show in UI
3. Environment Windows 10, CPU 5950x, RAM 128GB

Restore version 1.8.2 able to see the amount.

After that upgrade the 2.0.0 RC3, did not resync use existing copy wallet db able to see the USDS amount.
Other Asset ID, XCH amount was ok. 

Study case : [https://play.goby.app/history?tx=51ad5f48707b54de1e6b3fd3f7ca961142c9a867c8947e907488f4b5b0d74b5d&network=mainnet](url)

### Version

2.0.0 RC3

### What platform are you using?

Windows

### What ui mode are you using?

GUI

**Comment by BrandtH22** [comment]
Hey @Magicwalker , thank you for the information. 
This is a known bug related to dependencies in the dev tools which are used to process CAT information.

Our eng team is actively working on a solution to ensure the 2.0.0 versions will be able to properly identify CATs :+1:

**Comment by bramv-chia** [comment]
Can you test if this is related to the Goby wallet as follows:
- send yourself 1 USDS via 2.0.0 RC3 
and report back if you see the same behavior?

This way we can eliminate Goby as the possible source of the issue.

**Comment by Magicwalker** [comment]
> Can you test if this is related to the Goby wallet as follows:
> 
> * send yourself 1 USDS via 2.0.0 RC3
>   and report back if you see the same behavior?
> 
> This way we can eliminate Goby as the possible source of the issue.

Hi Bramv, 
I can confirm is 2.0.0 R3 wallet issue, another Asset TICA went missing when I delete wallet db and resync using 2.0.0 RC3.
Adding  Asset Id: 895d30090a17116d282af37cedec585613d4ee0faec3eaa7e19eb3f2bcd236e1 resync , token balance was 0.

**Comment by Magicwalker** [comment]
> Might be related to issues described in #15633? but these are with 1.8.

nope Chia not issue receive fund. Its only happen on CAT2, 1.8.2 no issue receive any CAT

**Comment by bramv-chia** [comment]
Could you provide us the logs [DEBUG] from the  2.0.0 R3 build? We're mainly concerned about exceptions from the log file.

**Comment by joshpainter** [comment]
I'm seeing this issue as well. To recreate, send any CAT from Goby to 2.0.0rc5 wallet. The CAT will never show up in the UI. I see these errors in the log:

2023-08-17T10:11:38.859 wallet chia.wallet.wallet_state_manager: ERROR    Failed to add coin_state: CoinState { coin: Coin { parent_coin_info: 4529c6161c10da53a81da7d97cf7017b8dac8c5edf46146d97a6e9b48c208efb, puzzle_hash: b8c6bc6af8b526fb8c5cf0459a4fb1e90ea87fe9923428a373597bd31b66872a, amount: 1 }, spent_height: Some(4026493), created_height: Some(4025218) }, error: list index out of range
Traceback (most recent call last):
  File "chia\wallet\wallet_state_manager.py", line 1301, in _add_coin_states
  File "chia\wallet\trade_manager.py", line 161, in coins_of_interest_farmed
IndexError: list index out of range
2023-08-17T10:11:40.209 wallet chia.wallet.wallet_state_manager: ERROR    Failed to add coin_state: CoinState { coin: Coin { parent_coin_info: 55ffb02f2e0f392e3b96fbd00b8c9e9c17538b3654644f598179a44980d339c2, puzzle_hash: 8986e8a1c0331831ce2e078809381edb859f6b7b396c70bdc344367f3005b33e, amount: 1 }, spent_height: Some(4026436), created_height: Some(4025218) }, error: list index out of range
Traceback (most recent call last):
  File "chia\wallet\wallet_state_manager.py", line 1301, in _add_coin_states
  File "chia\wallet\trade_manager.py", line 161, in coins_of_interest_farmed
IndexError: list index out of range
2023-08-17T10:11:41.662 wallet chia.wallet.wallet_state_manager: ERROR    Failed to add coin_state: CoinState { coin: Coin { parent_coin_info: 878e17e4337e2b9358691c47676b16a632825de62842fd9d7137f5a5c0f71d86, puzzle_hash: 59031dd8fa3d6caf6158df8be6ed548aaa3da60bb015d85e18637bc00cd4a9ca, amount: 1 }, spent_height: Some(4026479), created_height: Some(4025218) }, error: list index out of range
Traceback (most recent call last):
  File "chia\wallet\wallet_state_manager.py", line 1301, in _add_coin_states
  File "chia\wallet\trade_manager.py", line 161, in coins_of_interest_farmed
IndexError: list index out of range
2023-08-17T10:11:45.566 wallet chia.wallet.wallet_state_manager: ERROR    Failed to add coin_state: CoinState { coin: Coin { parent_coin_info: 4769f3d4ce99c1e289c1c10c8299dea81dbd0a234c8f1b125c6ae97edddad6ca, puzzle_hash: 09e6d392af7f9b47ec94c2dfe67509bc31f907d5bbefb259248451a93d9e9abe, amount: 1 }, spent_height: Some(4026438), created_height: Some(4025201) }, error: list index out of range
Traceback (most recent call last):
  File "chia\wallet\wallet_state_manager.py", line 1301, in _add_coin_states
  File "chia\wallet\trade_manager.py", line 161, in coins_of_interest_farmed
IndexError: list index out of range

As a workaround, I can load up the same fingerprint in 1.8. The CAT coins show up in the UI and I can send them to my own address. Once confirmed, they will show up in the new 2.0 RC. Something weird about Goby's spends/reveals maybe?

**Comment by Magicwalker** [comment]
This is not solve by the version 2.0, my asset id : 895d30090a17116d282af37cedec585613d4ee0faec3eaa7e19eb3f2bcd236e1 is not showing balance in my wallet and this is not related to Goby at all. If developer want to test it. Developer can purchase the coin in dexie.

**Comment by joshpainter** [comment]
Just an update to confirm that this bug remains in 2.0.0 final. Any CAT sent from Goby to the 2.0.0 wallet doesn't show up unless you use an older client and my workaround above.

**Comment by dimitrysuen** [comment]
Hi,
We just released a new version. Now, Goby is compatible with CHIP-20.
CAT2 transfers from Goby to Chia wallets are working fine now.

**Comment by BrandtH22** [comment]
> Hi, We just released a new version. Now, Goby is compatible with CHIP-20. **New CAT2 transfers** from Goby to Chia wallets are working fine now.

What is the recommendation for users who sent CATs prior to this new version being published?

**Comment by BrandtH22** [comment]
Just confirmed with a user who this issue effected that installing chia version 1.8.0 will allow the users walelt to properly identify the CATs. Once identified the user was able to send the tokens to another one of their xch addresses in the chia client then upgrade back to the current version of Chia and all tokens are accessible:
https://github.com/Chia-Network/chia-blockchain/releases/tag/1.8.0

**Comment by BrandtH22** [comment]
closing as Goby has updated their implementation and a workaround has been identified for anyone who had sent tokens prior to that update occurring.
