### ISSUE TITLE
[Bug] VCs - vcs get doesn't show proof reveals available in the database

### ISSUE THREAD

**Issue by esaung** [Chia-Network/chia-blockchain#16052]
### What happened?

running vcs get doesn't show proofs.

trying to add an proof reveal that's already in the database returns a code error

looking up proof reveals by root hash shows the values are there.

I'm expecting to see the proofs and the root hash when running the vcs get command. I'm also expecting to see a more user friendly error in the CLI when trying to add proof_reveals that are already in the proofs database.

### Version

2.0.0 rc4

### What platform are you using?

macOS

### What ui mode are you using?

CLI

### Relevant log output

```shell
(venv) esaung@Chia-Macbook chia-blockchain-gui % chia wallet vcs get

Active Wallet Key (*):
   -Fingerprint:           87074341
   -Label:                 Issuer (Issuer)
   -Sync Status:           Synced

Wallet Keys:
1)    3830434144   main farm
2)    1645933707   esaung hot wallet
3)    2920272449   TN10 - Custody
4)    3049838316   Documentation demo wallet tn10
5)    1964611303   pawket tn10 wallet
6)    233773231    NFT wallet
7)    2618175902   Background wallet
8)    2780699030   test walleth tn10
9)    1783862898   mainnet exp
10)   2803029382   TN10 main wallet
11)   1498393629   TN10 CF bag wallet
12)   965505910    tn10 chia nft use case test wallet
13)   852356298    nucle wallet
14)   107923803    mainnet test wallet
15)   2691838111   Big Big of NFts
16)   2867337490   5k tn10 NFT test wallet
17)   2752540257   Frodo wallet testnet
18)   3208516197   Jeff's CB test wallet
19)   1622336804   jeff cb test wallet 2 untrusted opera
20)   3554663204   County Demo wallet (Issuer)
21) * 87074341     Issuer (Issuer)
Choose a wallet key [1-21] ('q' to quit, or Enter to use 87074341): 
Proofs:

Launcher ID: 165e3cc5789923c0de4731f4a6b76320c2e39ea175d64e19c8a6b17c183ec798
Coin ID: bc15d1c6d0ed191fa08c0618179fb66e4646fcdc4f844171c8a90c24b9104af2
Inner Address: txch1z7dfrxx2qfd2lmxrl2fq7vdvgmk9ac6mnffv6tu0whnpx7y3eynql320y2
(venv) esaung@Chia-Macbook chia-blockchain-gui % chia wallet vcs add_proof_reveal --proof AliceKingsleigh --proof issuer.com --proof UT --proof 84604

Active Wallet Key (*):
   -Fingerprint:           87074341
   -Label:                 issuer.com (Issuer)
   -Sync Status:           Synced

Wallet Keys:
1)    3830434144   main farm
2)    1645933707   esaung hot wallet
3)    2920272449   TN10 - Custody
4)    3049838316   Documentation demo wallet tn10
5)    1964611303   pawket tn10 wallet
6)    233773231    NFT wallet
7)    2618175902   Background wallet
8)    2780699030   test walleth tn10
9)    1783862898   mainnet exp
10)   2803029382   TN10 main wallet
11)   1498393629   TN10 CF bag wallet
12)   965505910    tn10 chia nft use case test wallet
13)   852356298    nucle wallet
14)   107923803    mainnet test wallet
15)   2691838111   Big Big of NFts
16)   2867337490   5k tn10 NFT test wallet
17)   2752540257   Frodo wallet testnet
18)   3208516197   Jeff's CB test wallet
19)   1622336804   jeff cb test wallet 2 untrusted opera
20)   3554663204   County Demo wallet (Issuer)
21) * 87074341     issuer.com (Issuer)
Choose a wallet key [1-21] ('q' to quit, or Enter to use 87074341): 
Exception from 'wallet' {'error': 'UNIQUE constraint failed: vc_proofs.root', 'success': False}:
Traceback (most recent call last):
  File "/Users/esaung/Github/VC/chia-blockchain/chia/cmds/cmds_util.py", line 110, in get_any_service_client
    yield node_client, config
  File "/Users/esaung/Github/VC/chia-blockchain/chia/cmds/cmds_util.py", line 226, in get_wallet_client
    yield wallet_client, new_fp, config
  File "/Users/esaung/Github/VC/chia-blockchain/chia/cmds/wallet_funcs.py", line 1478, in add_proof_reveal
    await wallet_client.vc_add_proofs(proof_dict)
  File "/Users/esaung/Github/VC/chia-blockchain/chia/rpc/wallet_rpc_client.py", line 1270, in vc_add_proofs
    await self.fetch("vc_add_proofs", {"proofs": proofs})
  File "/Users/esaung/Github/VC/chia-blockchain/chia/rpc/rpc_client.py", line 61, in fetch
    raise ValueError(res_json)
ValueError: {'error': 'UNIQUE constraint failed: vc_proofs.root', 'success': False}

(venv) esaung@Chia-Macbook chia-blockchain-gui % chia wallet vcs add_proof_reveal --proof Alice_Kingsleigh --proof issuer.com --proof UT --proof 84604

Active Wallet Key (*):
   -Fingerprint:           87074341
   -Label:                 issuer.com (Issuer)
   -Sync Status:           Synced

Wallet Keys:
1)    3830434144   main farm
2)    1645933707   esaung hot wallet
3)    2920272449   TN10 - Custody
4)    3049838316   Documentation demo wallet tn10
5)    1964611303   pawket tn10 wallet
6)    233773231    NFT wallet
7)    2618175902   Background wallet
8)    2780699030   test walleth tn10
9)    1783862898   mainnet exp
10)   2803029382   TN10 main wallet
11)   1498393629   TN10 CF bag wallet
12)   965505910    tn10 chia nft use case test wallet
13)   852356298    nucle wallet
14)   107923803    mainnet test wallet
15)   2691838111   Big Big of NFts
16)   2867337490   5k tn10 NFT test wallet
17)   2752540257   Frodo wallet testnet
18)   3208516197   Jeff's CB test wallet
19)   1622336804   jeff cb test wallet 2 untrusted opera
20)   3554663204   County Demo wallet (Issuer)
21) * 87074341     EasyFoodHandlers.com (Issuer)
Choose a wallet key [1-21] ('q' to quit, or Enter to use 87074341): 
Proofs added to DB successfully!
(venv) esaung@Chia-Macbook chia-blockchain-gui % chia wallet vcs -h
Usage: chia wallet vcs [OPTIONS] COMMAND [ARGS]...

Options:
  -h, --help  Show this message and exit.

Commands:
  add_proof_reveal     Add a series of proofs that will combine to a single
                       proof hash
  get                  Get a list of existing VCs
  get_proofs_for_root  Get the stored proof flags for a given proof hash
  mint                 Mint a VC
  revoke               Revoke any VC if you have the proper DID and the VCs
                       parent coin
  update_proofs        Update a VC's proofs if you have the provider DID
(venv) esaung@Chia-Macbook chia-blockchain-gui % chia wallet vcs get_proofs_for_root -h
Usage: chia wallet vcs get_proofs_for_root [OPTIONS]

Options:
  -wp, --wallet-rpc-port INTEGER  Set the port where the Wallet is hosting
                                  the RPC interface. See the rpc_port under
                                  wallet in config.yaml
  -f, --fingerprint INTEGER       Set the fingerprint to specify which key to
                                  use
  -r, --proof-hash TEXT           The root to search for  [required]
  -h, --help                      Show this message and exit.
(venv) esaung@Chia-Macbook chia-blockchain-gui % chia wallet vcs get_proofs_for_root -r 986f9b7f57f52af42c7649790fc054bb2d8866894d408b65600b159b1ea22af3

Active Wallet Key (*):
   -Fingerprint:           87074341
   -Label:                 issuer.com (Issuer)
   -Sync Status:           Synced

Wallet Keys:
1)    3830434144   main farm
2)    1645933707   esaung hot wallet
3)    2920272449   TN10 - Custody
4)    3049838316   Documentation demo wallet tn10
5)    1964611303   pawket tn10 wallet
6)    233773231    NFT wallet
7)    2618175902   Background wallet
8)    2780699030   test walleth tn10
9)    1783862898   mainnet exp
10)   2803029382   TN10 main wallet
11)   1498393629   TN10 CF bag wallet
12)   965505910    tn10 chia nft use case test wallet
13)   852356298    nucle wallet
14)   107923803    mainnet test wallet
15)   2691838111   Big Big of NFts
16)   2867337490   5k tn10 NFT test wallet
17)   2752540257   Frodo wallet testnet
18)   3208516197   Jeff's CB test wallet
19)   1622336804   jeff cb test wallet 2 untrusted opera
20)   3554663204   County Demo wallet (Issuer)
21) * 87074341     issuer.com (Issuer)
Choose a wallet key [1-21] ('q' to quit, or Enter to use 87074341): 
Proofs:
 - 84604
 - AliceKingsleigh
 - UT
 - issuer.com
(venv) esaung@Chia-Macbook chia-blockchain-gui % chia wallet vcs get_proofs_for_root -r ac04b2f39be8adbaee0eadb8859cb88e28173fa84cd6a9a658ca98ea6678be8c

Active Wallet Key (*):
   -Fingerprint:           87074341
   -Label:                 issuer.com (Issuer)
   -Sync Status:           Synced

Wallet Keys:
1)    3830434144   main farm
2)    1645933707   esaung hot wallet
3)    2920272449   TN10 - Custody
4)    3049838316   Documentation demo wallet tn10
5)    1964611303   pawket tn10 wallet
6)    233773231    NFT wallet
7)    2618175902   Background wallet
8)    2780699030   test walleth tn10
9)    1783862898   mainnet exp
10)   2803029382   TN10 main wallet
11)   1498393629   TN10 CF bag wallet
12)   965505910    tn10 chia nft use case test wallet
13)   852356298    nucle wallet
14)   107923803    mainnet test wallet
15)   2691838111   Big Big of NFts
16)   2867337490   5k tn10 NFT test wallet
17)   2752540257   Frodo wallet testnet
18)   3208516197   Jeff's CB test wallet
19)   1622336804   jeff cb test wallet 2 untrusted opera
20)   3554663204   County Demo wallet (Issuer)
21) * 87074341     issuer.com (Issuer)
Choose a wallet key [1-21] ('q' to quit, or Enter to use 87074341): 
Proofs:
 - 84604
 - Alice_Kingsleigh
 - UT
 - issuer.com
(venv) esaung@Chia-Macbook chia-blockchain-gui % chia wallet vcs get_proofs_for_root -r e9ebc8af21d67987c385795b7a1af14f59ae55494d22ed0086d12c5e4c929c7d

Active Wallet Key (*):
   -Fingerprint:           87074341
   -Label:                 issuer.com (Issuer)
   -Sync Status:           Synced

Wallet Keys:
1)    3830434144   main farm
2)    1645933707   esaung hot wallet
3)    2920272449   TN10 - Custody
4)    3049838316   Documentation demo wallet tn10
5)    1964611303   pawket tn10 wallet
6)    233773231    NFT wallet
7)    2618175902   Background wallet
8)    2780699030   test walleth tn10
9)    1783862898   mainnet exp
10)   2803029382   TN10 main wallet
11)   1498393629   TN10 CF bag wallet
12)   965505910    tn10 chia nft use case test wallet
13)   852356298    nucle wallet
14)   107923803    mainnet test wallet
15)   2691838111   Big Big of NFts
16)   2867337490   5k tn10 NFT test wallet
17)   2752540257   Frodo wallet testnet
18)   3208516197   Jeff's CB test wallet
19)   1622336804   jeff cb test wallet 2 untrusted opera
20)   3554663204  County Demo wallet (Issuer)
21) * 87074341     issuer.com (Issuer)
Choose a wallet key [1-21] ('q' to quit, or Enter to use 87074341): 
Proofs:
 - 84604
 - Alice
 - Issuer.com
 - UT
(venv) esaung@Chia-Macbook chia-blockchain-gui %
```

**Comment by Quexington** [comment]
For the `vcs get` command, it will only show you proofs for VCs that are returned in the output.  It looks like your one VC has no proofs so it is not showing any proofs.

**Comment by Quexington** [comment]
> Understood, I guess I expected that it would so all the proof reveals that are in the proof database. so if I add proof reveals to the DB, is there a way to see what's in the db if those proof reveals and root hash aren't associated to a VC? the issue I was running into was that when I go to add something that's already there, you get an error in this non-human friendly error.
> 
> Choose a wallet key [1-21] ('q' to quit, or Enter to use 87074341): Exception from 'wallet' {'error': 'UNIQUE constraint failed: vc_proofs.root', 'success': False}: Traceback (most recent call last): File "/Users/esaung/Github/VC/chia-blockchain/chia/cmds/cmds_util.py", line 110, in get_any_service_client yield node_client, config File "/Users/esaung/Github/VC/chia-blockchain/chia/cmds/cmds_util.py", line 226, in get_wallet_client yield wallet_client, new_fp, config File "/Users/esaung/Github/VC/chia-blockchain/chia/cmds/wallet_funcs.py", line 1478, in add_proof_reveal await wallet_client.vc_add_proofs(proof_dict) File "/Users/esaung/Github/VC/chia-blockchain/chia/rpc/wallet_rpc_client.py", line 1270, in vc_add_proofs await self.fetch("vc_add_proofs", {"proofs": proofs}) File "/Users/esaung/Github/VC/chia-blockchain/chia/rpc/rpc_client.py", line 61, in fetch raise ValueError(res_json) ValueError: {'error': 'UNIQUE constraint failed: vc_proofs.root', 'success': False}

Yeah I'm working on fixing that error, to make it better, but no currently there's no way to just dump all of the proofs you have in a DB.  The nature of proofs means it's only really helpful to know which ones are associated with a VC.

**Comment by esaung** [comment]
yes, if we can fix the error that gets logged and also be a little more user friendly in the error that's returned on the command line, we should be good with closing this issue.
