### ISSUE TITLE
[BUG] `chia keys show` regression in 1.0.2...

### ISSUE THREAD

**Issue by fiveangle** [Chia-Network/chia-blockchain#1610]
Upgrade from 1.0.1 to 1.0.2 via git process on Debian 10.8/9

`chia keys show` functioned before but now results in:

```
(venv) speedster@chachacha:~/dev/chia-blockchain$ chia keys show
Traceback (most recent call last):
  File "/home/speedster/dev/chia-blockchain/venv/bin/chia", line 33, in <module>
    sys.exit(load_entry_point('chia-blockchain', 'console_scripts', 'chia')())
  File "/home/speedster/dev/chia-blockchain/src/cmds/chia.py", line 76, in main
    cli()  # pylint: disable=no-value-for-parameter
  File "/home/speedster/dev/chia-blockchain/venv/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/speedster/dev/chia-blockchain/venv/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/speedster/dev/chia-blockchain/venv/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/speedster/dev/chia-blockchain/venv/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/speedster/dev/chia-blockchain/venv/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/speedster/dev/chia-blockchain/venv/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/speedster/dev/chia-blockchain/src/cmds/keys.py", line 27, in show_cmd
    from .keys_funcs import show_all_keys
ModuleNotFoundError: No module named 'src.cmds.keys_funcs'
```

Tried on two different debian systems with same result.

**Comment by hoffmang9** [comment]
Known bug. 1.0.3 soon

**Comment by fiveangle** [comment]
I'll just back out of the room slowly then, never having whispered the phrase "unit testing" :wink:

**Comment by hoffmang9** [comment]
PRs for other community members changes that came in without a unit test... very welcome!

Fixed in https://github.com/Chia-Network/chia-blockchain/releases/tag/1.0.3
