### ISSUE TITLE
[Bug] chia (2.0)  plots check -g coredumps when terminated with ctrl-c 

### ISSUE THREAD

**Issue by jayhohoho2019** [Chia-Network/chia-blockchain#16254]
### What happened?

I ran chia plots check -g on a directory of c3 plots made with bladebit 3.0.0 and after the first few looked good I issued ctrl-C to stop the check, and it coredumped.  

 5.15.0-82-generic #91-Ubuntu SMP Mon Aug 14 14:14:14 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

### Version

2.0.0

### What platform are you using?

Linux

### What ui mode are you using?

CLI

### Relevant log output

```shell
2023-09-05T12:43:42.644  chia.plotting.check_plots        : INFO        Looking up qualities took: 98 ms. Filepath: /mnt/ssd/...b.plot
^CException ignored in: <module 'threading' from '/usr/lib/python3.10/threading.py'>
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1537, in _shutdown
^C  File "/usr/lib/python3.10/concurrent/futures/thread.py", line 31, in _python_exit
^C  File "/usr/lib/python3.10/threading.py", line 1096, in join
    self._wait_for_tstate_lock()
  File "/usr/lib/python3.10/threading.py", line 1116, in _wait_for_tstate_lock
    if lock.acquire(block, timeout):
KeyboardInterrupt:
terminate called without an active exception
^CAborted (core dumped)

------
coredump file exists if you need it.
```

**Comment by emlowe** [comment]
Closing issue as focus on the new plot format takes precedence over prior plot issues
