### ISSUE TITLE
[Bug] Wallet in sync loop -> wallet_server : ERROR <asyncio.exceptions.TimeoutError>

### ISSUE THREAD

**Issue by bwccnft** [Chia-Network/chia-blockchain#16311]
### What happened?

Wallet in sync loop and keeps rolling back to 3127995 peak. Wallet contains about 19k NFTs and 9k offer files. Deleting the wallet DB is not an option, as this will delete all offer files. The problem occurred following an abnormal shutdown.

Similar asyncio issues:
#13749 
#3950 

### Version

2.0.1

### What platform are you using?

Linux

### What ui mode are you using?

CLI

### Relevant log output

```shell
2023-09-12T06:21:46.549 wallet wallet_server              : ERROR    Exception:  <class 'asyncio.exceptions.TimeoutError'>, closing connection PeerInfo(_ip=IPv4Address('127.0.0.1'), _port=8444). Traceback (most recent call last):
  File "chia/server/ws_connection.py", line 420, in _api_call
  File "asyncio/tasks.py", line 496, in wait_for
asyncio.exceptions.TimeoutError

......

2023-09-12T06:21:50.169 wallet chia.wallet.wallet_state_manager: INFO     set_sync_mode syncing - range: 3128251-4218496
2023-09-12T06:21:50.170 wallet chia.wallet.wallet_blockchain: INFO     Peak set to: 4218496 timestamp: 1694488845
2023-09-12T06:21:50.170 wallet chia.wallet.wallet_node    : INFO     Starting sync trusted: True to peer 127.0.0.1
2023-09-12T06:21:50.170 wallet chia.wallet.wallet_node    : INFO     perform_atomic_rollback to 3127995
```

**Comment by wjblanke** [comment]
Rollback happens at the start of every sync. Can you send us the DEBUG debug.log file. It could be some corruption because of the bad shutdown. It may be an overflow on the response since you have so many coins but we would need to see that in the log. Have you tried a trusted local full node? It has a higher limit on the number of puzzle hashes that can be observed.
