### ISSUE TITLE
clvm raise during DAO mint proposal creation and voting [Bug] 

### ISSUE THREAD

**Issue by danieljperry** [Chia-Network/chia-blockchain#16331]
### What happened?

I am seeing an intermittent error during the creation of a DAO mint proposal. First, an overview of my wallet:
```
Chia Wallet:
   -Total Balance:         0.999345147232 txch (999345147232 mojo)
   -Pending Total Balance: 0.999345147232 txch (999345147232 mojo)
   -Spendable:             0.999345147232 txch (999345147232 mojo)
   -Type:                  STANDARD_WALLET
   -Wallet ID:             1

Profile 1:
   -Total Balance:         1.0
   -Pending Total Balance: 1.0
   -Spendable:             1.0
   -Type:                  DAO
   -Treasury ID:           dfe486693cddf312eae141688e72a0b5f597df152f7f30dcb7c775d0ffaa1a56
   -Wallet ID:             3

CAT 07e809aa0324acaf...:
   -Total Balance:         0.0  (0 mojo)
   -Pending Total Balance: 0.0  (0 mojo)
   -Spendable:             0.0  (0 mojo)
   -Type:                  CAT
   -Asset ID:              07e809aa0324acaf274ce1bb1502d18b31236ac46739e90ebf0a042dbbd2c882
   -Wallet ID:             4

CAT 07e809aa0324acaf...:
   -Total Balance:         100000.0
   -Pending Total Balance: 0.0
   -Spendable:             0.0
   -Type:                  DAO_CAT
   -Asset ID:              0000000000000003000000000000000407e809aa0324acaf274ce1bb1502d18b
   -Wallet ID:             5
```
And the DAO's treasury balance:
```
chia dao get_balance -i 3
XCH: 1.000001
```

First I tried creating 100,000 CATS and using 100 votes:
`chia dao create_proposal mint -i 3 -a 100000 -t txch1u7l0esj4jet6lc4uwm3qj3u3sgdh5y8h4msgl9g833907rrt4k6sj43nfx -v 100 -m 0.00001`

And I got this error:
```
Exception from 'wallet' {'error': 'clvm raise', 'success': False}:
Traceback (most recent call last):
  File "C:\Users\User\Chia\dao-wallet\chia-blockchain\chia\cmds\cmds_util.py", line 119, in get_any_service_client
    yield node_client, config
  File "C:\Users\User\Chia\dao-wallet\chia-blockchain\chia\cmds\cmds_util.py", line 235, in get_wallet_client
    yield wallet_client, new_fp, config
  File "C:\Users\User\Chia\dao-wallet\chia-blockchain\chia\cmds\dao_funcs.py", line 510, in create_mint_proposal
    res = await wallet_client.dao_create_proposal(
  File "C:\Users\User\Chia\dao-wallet\chia-blockchain\chia\rpc\wallet_rpc_client.py", line 1357, in dao_create_proposal
    response = await self.fetch("dao_create_proposal", request)
  File "C:\Users\User\Chia\dao-wallet\chia-blockchain\chia\rpc\rpc_client.py", line 61, in fetch
    raise ValueError(res_json)
ValueError: {'error': 'clvm raise', 'success': False}
```

Next I ran the same command, but with only 1 vote and it worked.
```
chia dao create_proposal mint -i 3 -a 100000 -t txch1u7l0esj4jet6lc4uwm3qj3u3sgdh5y8h4msgl9g833907rrt4k6sj43nfx -v 1 -m 0.00001

Successfully created proposal.
Proposal ID: 0x6e11db5e6a94b9f4f867d968ae6f971e6fa4dca9b75ad0d54e0450ebdb1d3c3a
```

When attempting to vote on the above proposal, I sometimes get the above error:
1000 -- clvm raise
500 -- clvm raise
1 -- success
125 -- a different error:

```Exception from 'wallet' {'error': 'Value -75 does not fit into uint64', 'success': False}:
Traceback (most recent call last):
  File "C:\Users\User\Chia\dao-wallet\chia-blockchain\chia\cmds\cmds_util.py", line 119, in get_any_service_client
    yield node_client, config
  File "C:\Users\User\Chia\dao-wallet\chia-blockchain\chia\cmds\cmds_util.py", line 235, in get_wallet_client
    yield wallet_client, new_fp, config
  File "C:\Users\User\Chia\dao-wallet\chia-blockchain\chia\cmds\dao_funcs.py", line 270, in vote_on_proposal
    res = await wallet_client.dao_vote_on_proposal(
  File "C:\Users\User\Chia\dao-wallet\chia-blockchain\chia\rpc\wallet_rpc_client.py", line 1389, in dao_vote_on_proposal
    response = await self.fetch("dao_vote_on_proposal", request)
  File "C:\Users\User\Chia\dao-wallet\chia-blockchain\chia\rpc\rpc_client.py", line 61, in fetch
    raise ValueError(res_json)
ValueError: {'error': 'Value -75 does not fit into uint64', 'success': False}```

110: `ValueError: {'error': 'Value -90 does not fit into uint64', 'success': False}`

This error appears to be intermittent. When I try the same voting command multiple times, sometimes it works.

### Version

dao-wallet branch, testnet10, 2.0.1b3.dev256

### What platform are you using?

Windows

### What ui mode are you using?

CLI

### Relevant log output

_No response_

**Comment by geoffwalmsley** [comment]
fixed: https://github.com/Chia-Network/chia-blockchain/pull/15559/commits/f46d687805f58691a015d1f92f473c43a362907b
