### ISSUE TITLE
Exception from DAO vote command[Bug] 

### ISSUE THREAD

**Issue by danieljperry** [Chia-Network/chia-blockchain#16330]
### What happened?

I'm testing DAOs on testnet10, using the `dao-wallet` branch. Here is the status of my wallet:
```
Chia Wallet:
   -Total Balance:         0.999756147233 txch (999756147233 mojo)
   -Pending Total Balance: 0.999756147233 txch (999756147233 mojo)
   -Spendable:             0.999756147233 txch (999756147233 mojo)
   -Type:                  STANDARD_WALLET
   -Wallet ID:             1

Profile 1:
   -Total Balance:         1.0
   -Pending Total Balance: 1.0
   -Spendable:             1.0
   -Type:                  DAO
   -Treasury ID:           dfe486693cddf312eae141688e72a0b5f597df152f7f30dcb7c775d0ffaa1a56
   -Wallet ID:             3

CAT 07e809aa0324acaf...:
   -Total Balance:         0.0  (0 mojo)
   -Pending Total Balance: 0.0  (0 mojo)
   -Spendable:             0.0  (0 mojo)
   -Type:                  CAT
   -Asset ID:              07e809aa0324acaf274ce1bb1502d18b31236ac46739e90ebf0a042dbbd2c882
   -Wallet ID:             4

CAT 07e809aa0324acaf...:
   -Total Balance:         100000.0
   -Pending Total Balance: 0.0
   -Spendable:             0.0
   -Type:                  DAO_CAT
   -Asset ID:              0000000000000003000000000000000407e809aa0324acaf274ce1bb1502d18b
   -Wallet ID:             5
```

This DAO has one open proposal:

```
Details of Proposal: 0x372a3e3d7f502a542d3c926588b62d5ca580d4ff60a158740563470f2114ef2d
---------------------------

Type: SPEND
Status: OPEN
Passed: False
Yes votes needed: 250
Closable: False
Total votes needed: 750
Blocks remaining: 0

Proposal XCH Conditions
0x6ace2ea83d1db903c2fef0237e1cd71cae017fa79fb3eeec4af3c7fc6c25c16e 1000000000000
```

When I vote on the proposal with this command:
`chia dao vote -i 3 -p 0x372a3e3d7f502a542d3c926588b62d5ca580d4ff60a158740563470f2114ef2d -a 100 -m 0.0001`

I receive the following error:
```
Exception from 'wallet' 'spend_bundle_name':
Traceback (most recent call last):
  File "C:\Users\User\Chia\dao-wallet\chia-blockchain\chia\cmds\cmds_util.py", line 119, in get_any_service_client
    yield node_client, config
  File "C:\Users\User\Chia\dao-wallet\chia-blockchain\chia\cmds\cmds_util.py", line 235, in get_wallet_client
    yield wallet_client, new_fp, config
  File "C:\Users\User\Chia\dao-wallet\chia-blockchain\chia\cmds\dao_funcs.py", line 286, in vote_on_proposal
    spend_bundle = res["spend_bundle_name"]
KeyError: 'spend_bundle_name'
```

However, the vote does get counted. This is made clear when I list the proposal's status again:
```
Details of Proposal: 0x372a3e3d7f502a542d3c926588b62d5ca580d4ff60a158740563470f2114ef2d
---------------------------

Type: SPEND
Status: OPEN
Passed: False
Yes votes needed: 150
Closable: False
Total votes needed: 650
Blocks remaining: 0

Proposal XCH Conditions
0x6ace2ea83d1db903c2fef0237e1cd71cae017fa79fb3eeec4af3c7fc6c25c16e 1000000000000
```

### Version

dao-wallet branch, testnet10, 2.0.1b3.dev256

### What platform are you using?

Windows

### What ui mode are you using?

CLI

**Comment by geoffwalmsley** [comment]
fixed: https://github.com/Chia-Network/chia-blockchain/pull/15559/commits/f46d687805f58691a015d1f92f473c43a362907b
