### ISSUE TITLE
"chia farm summary" produces an exception in 2.1.0rc1 [Bug] 

### ISSUE THREAD

**Issue by bhorvitz** [Chia-Network/chia-blockchain#16355]
### What happened?

```
$ chia version
2.1.0rc1
$ chia farm summary
Exception from 'wallet' {'error': 'too many SQL variables', 'success': False, 'traceback': 'Traceback (most recent call last):\n  File "chia/rpc/util.py", line 21, in inner\n  File "chia/rpc/wallet_rpc_api.py", line 3199, in get_farmed_amount\n  File "chia/wallet/wallet_transaction_store.py", line 269, in get_farming_rewards\n  File "chia/wallet/wallet_transaction_store.py", line 432, in _get_new_tx_records_from_old\n  File "aiosqlite/core.py", line 190, in execute\n  File "aiosqlite/core.py", line 133, in _execute\n  File "aiosqlite/core.py", line 106, in run\nsqlite3.OperationalError: too many SQL variables\n'}:
Traceback (most recent call last):
  File "chia/cmds/cmds_util.py", line 119, in get_any_service_client
  File "chia/cmds/farm_funcs.py", line 58, in get_wallets_stats
  File "chia/rpc/wallet_rpc_client.py", line 289, in get_farmed_amount
  File "chia/rpc/rpc_client.py", line 61, in fetch
ValueError: {'error': 'too many SQL variables', 'success': False, 'traceback': 'Traceback (most recent call last):\n  File "chia/rpc/util.py", line 21, in inner\n  File "chia/rpc/wallet_rpc_api.py", line 3199, in get_farmed_amount\n  File "chia/wallet/wallet_transaction_store.py", line 269, in get_farming_rewards\n  File "chia/wallet/wallet_transaction_store.py", line 432, in _get_new_tx_records_from_old\n  File "aiosqlite/core.py", line 190, in execute\n  File "aiosqlite/core.py", line 133, in _execute\n  File "aiosqlite/core.py", line 106, in run\nsqlite3.OperationalError: too many SQL variables\n'}

Farming status: Farming
...
```
And the rest is as normal.

### Version

2.1.0rc1

### What platform are you using?

Linux

### What ui mode are you using?

CLI

**Comment by wjblanke** [comment]
What version of linux are you running? We think this may be due to an old version of SQLite. Also how did you install?

**Comment by bhorvitz** [comment]
This is on Centos 9.  This kernel to be exact:
`Linux ch-n2 5.14.0-333.el9.x86_64 #1 SMP PREEMPT_DYNAMIC Wed Jun 28 09:47:27 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux`

I installed from the RPM - chia-blockchain-cli-2.1.0rc1-1.x86_64.rpm

Output from the commands (not in the venv):
```
$ python -c "import sqlite3; print(sqlite3.version)"
2.6.0
$ python -c "import sqlite3; print(sqlite3.sqlite_version)"
3.34.1
```

**Comment by cmmarslender** [comment]
Updated the build image to ensure the correct version of sqlite is used in https://github.com/Chia-Network/build-images/pull/45

Should be fixed in the next RC
