### ISSUE TITLE
[Bug] Adding/receiving CR Cats for first time in wallet results in Error

### ISSUE THREAD

**Issue by esaung** [Chia-Network/chia-blockchain#16402]
### What happened?

I minted a CR CAT in the same wallet that owns the DID being used, but didn't have a VC in that same wallet. Same error is shown when user receives the CR CAT for the first time and adds the CR CAT wallet when it shows up.

Wallet resulted in "Error" when showing balances along with errors in debug.log. Also can't add other asset IDs now.
![Screenshot 2023-09-22 at 5 12 58 PM](https://github.com/Chia-Network/chia-blockchain/assets/93196638/3f088903-1a24-4132-b9fe-6f95f14670f4)

workaround: logout of the wallet, switch to another wallet, and then switch back.

### Version

2.1.0rc2

### What platform are you using?

macOS

### What ui mode are you using?

CLI

### Relevant log output

```shell
2023-09-22T17:10:35.753 wallet chia.wallet.wallet_node    : INFO     request coin: e8ba2c35133196c86b37aa04887ea50da984bfc2364ac984206bfdb97df58225CoinState { coin: Coin { parent_coin_info: 67deb15e17f6fc7e46b4d96545464b9c5a8c33bcd3881d1f35638fe27ebded5f, puzzle_hash: c494c4a0ddf2aa5ef97a913a96d2a60e6d39765388d4e63725df5fce03bd3c7d, amount: 2899869990000 }, spent_height: None, created_height: Some(3227129) }
2023-09-22T17:10:35.754 wallet chia.wallet.wallet_node    : INFO     request coin: c9789fad661b484d8f09d569ee199e4dd9f4d64a8d3178b78b638a67ead1a5c4CoinState { coin: Coin { parent_coin_info: 010739f21cc4a3735996705934faec4bf8c813354644b7fd3f064a5c9a1f402e, puzzle_hash: f5c59bb3bca38ff2f51dd519159875d23edabb41a1be2b43b0b33884d941d127, amount: 120000000 }, spent_height: None, created_height: Some(3227129) }
2023-09-22T17:10:35.754 wallet chia.wallet.wallet_node    : INFO     request coin: 67deb15e17f6fc7e46b4d96545464b9c5a8c33bcd3881d1f35638fe27ebded5fCoinState { coin: Coin { parent_coin_info: f3ee109a546f0b0cd0c4cece9f82f3620053c6689fecef8ce55837ad36b29c91, puzzle_hash: cacc3983d79e5239a3a78c71574c50df51632e5de86d0244df993517795f1b50, amount: 2899990000000 }, spent_height: Some(3227129), created_height: Some(3227025) }
2023-09-22T17:10:35.756 wallet chia.wallet.wallet_node    : INFO     clear_after_height 3227128 for peer WSChiaConnection(local_type=<NodeType.WALLET: 6>, local_port=8449, local_capabilities=[<Capability.BASE: 1>, <Capability.BLOCK_HEADERS: 2>, <Capability.RATE_LIMITS_V2: 3>], peer_info=PeerInfo(_ip=IPv4Address('128.140.86.208'), _port=58444), peer_node_id=<bytes32: 7338393f1a66a064c1e1953c3fc23913439203256ab6e0ed17ff06cd93147c18>, outbound_rate_limiter=<chia.server.rate_limits.RateLimiter object at 0x1126cc610>, inbound_rate_limiter=<chia.server.rate_limits.RateLimiter object at 0x1126cfee0>, is_outbound=True, creation_time=1695415745.392069, bytes_read=18148136, bytes_written=54169, last_message_time=1695420635.751735, peer_server_port=58444, closed=False, connection_type=<NodeType.FULL_NODE: 1>, request_nonce=568, peer_capabilities=[<Capability.BASE: 1>, <Capability.BLOCK_HEADERS: 2>, <Capability.RATE_LIMITS_V2: 3>], version='2.0.1', protocol_version=<Version('0.0.35')>)
2023-09-22T17:10:35.768 wallet chia.wallet.cat_wallet.cat_wallet: INFO     Confirmed balance for cat wallet 7 is 0
2023-09-22T17:10:35.920 full_node chia.full_node.full_node: INFO     Added blocks 2655053 to 2655085
2023-09-22T17:10:36.494 wallet chia.wallet.wallet_blockchain: INFO     Peak set to: 3227129 timestamp: 1695420603
2023-09-22T17:10:36.495 wallet chia.wallet.wallet_node    : INFO     Apply race cache - height: 3227129, coin_states: {CoinState { coin: Coin { parent_coin_info: 67deb15e17f6fc7e46b4d96545464b9c5a8c33bcd3881d1f35638fe27ebded5f, puzzle_hash: c494c4a0ddf2aa5ef97a913a96d2a60e6d39765388d4e63725df5fce03bd3c7d, amount: 2899869990000 }, spent_height: None, created_height: Some(3227129) }, CoinState { coin: Coin { parent_coin_info: 010739f21cc4a3735996705934faec4bf8c813354644b7fd3f064a5c9a1f402e, puzzle_hash: f5c59bb3bca38ff2f51dd519159875d23edabb41a1be2b43b0b33884d941d127, amount: 120000000 }, spent_height: None, created_height: Some(3227129) }, CoinState { coin: Coin { parent_coin_info: f3ee109a546f0b0cd0c4cece9f82f3620053c6689fecef8ce55837ad36b29c91, puzzle_hash: cacc3983d79e5239a3a78c71574c50df51632e5de86d0244df993517795f1b50, amount: 2899990000000 }, spent_height: Some(3227129), created_height: Some(3227025) }}
2023-09-22T17:10:37.195 full_node chia.full_node.full_node: INFO     Added blocks 2655085 to 2655117
2023-09-22T17:10:37.312 wallet chia.wallet.wallet_node    : INFO     new coin state received (1-3/ 3)
2023-09-22T17:10:38.158 wallet Church of Chia CR CAT SI   : INFO     CR-CAT wallet has been notified that c9789fad661b484d8f09d569ee199e4dd9f4d64a8d3178b78b638a67ead1a5c4 was added
2023-09-22T17:10:38.275 full_node chia.full_node.full_node: INFO     Added blocks 2655117 to 2655149
2023-09-22T17:10:38.526 wallet Church of Chia CR CAT SI   : INFO     Found CRCAT coin c9789fad661b484d8f09d569ee199e4dd9f4d64a8d3178b78b638a67ead1a5c4
2023-09-22T17:10:38.528 wallet Church of Chia CR CAT SI   : ERROR    Cannot add CRCAT coin: Traceback (most recent call last):
  File "chia/wallet/vc_wallet/cr_cat_wallet.py", line 265, in add_crcat_coin
  File "chia/wallet/vc_wallet/cr_cat_wallet.py", line 187, in id
AttributeError: 'NoneType' object has no attribute 'id'

2023-09-22T17:10:38.531 wallet chia.wallet.wallet_node    : INFO     Finished processing new peak of 3227129
2023-09-22T17:10:38.536 wallet chia.wallet.wallet_node    : INFO     request coin: e8ba2c35133196c86b37aa04887ea50da984bfc2364ac984206bfdb97df58225CoinState { coin: Coin { parent_coin_info: 67deb15e17f6fc7e46b4d96545464b9c5a8c33bcd3881d1f35638fe27ebded5f, puzzle_hash: c494c4a0ddf2aa5ef97a913a96d2a60e6d39765388d4e63725df5fce03bd3c7d, amount: 2899869990000 }, spent_height: None, created_height: Some(3227129) }
2023-09-22T17:10:38.536 wallet chia.wallet.wallet_node    : INFO     request coin: c9789fad661b484d8f09d569ee199e4dd9f4d64a8d3178b78b638a67ead1a5c4CoinState { coin: Coin { parent_coin_info: 010739f21cc4a3735996705934faec4bf8c813354644b7fd3f064a5c9a1f402e, puzzle_hash: f5c59bb3bca38ff2f51dd519159875d23edabb41a1be2b43b0b33884d941d127, amount: 120000000 }, spent_height: None, created_height: Some(3227129) }
2023-09-22T17:10:38.538 wallet chia.wallet.wallet_node    : INFO     request coin: 67deb15e17f6fc7e46b4d96545464b9c5a8c33bcd3881d1f35638fe27ebded5fCoinState { coin: Coin { parent_coin_info: f3ee109a546f0b0cd0c4cece9f82f3620053c6689fecef8ce55837ad36b29c91, puzzle_hash: cacc3983d79e5239a3a78c71574c50df51632e5de86d0244df993517795f1b50, amount: 2899990000000 }, spent_height: Some(3227129), created_height: Some(3227025) }
2023-09-22T17:10:38.538 wallet chia.wallet.wallet_node    : INFO     clear_after_height 3227128 for peer WSChiaConnection(local_type=<NodeType.WALLET: 6>, local_port=8449, local_capabilities=[<Capability.BASE: 1>, <Capability.BLOCK_HEADERS: 2>, <Capability.RATE_LIMITS_V2: 3>], peer_info=PeerInfo(_ip=IPv4Address('119.247.173.185'), _port=58444), peer_node_id=<bytes32: b3d9de85d29931c10050b56c7afb91c99141943fc81ff2d1a8425e52be0d08ab>, outbound_rate_limiter=<chia.server.rate_limits.RateLimiter object at 0x10796d3c0>, inbound_rate_limiter=<chia.server.rate_limits.RateLimiter object at 0x10796d2a0>, is_outbound=True, creation_time=1695418652.908557, bytes_read=17523695, bytes_written=44039, last_message_time=1695420637.832632, peer_server_port=58444, closed=False, connection_type=<NodeType.FULL_NODE: 1>, request_nonce=226, peer_capabilities=[<Capability.BASE: 1>, <Capability.BLOCK_HEADERS: 2>, <Capability.RATE_LIMITS_V2: 3>], version='2.1.0rc2', protocol_version=<Version('0.0.35')>)
2023-09-22T17:10:38.562 wallet chia.rpc.rpc_server        : WARNING  Error while handling message: Traceback (most recent call last):
  File "chia/rpc/rpc_server.py", line 340, in safe_handle
  File "chia/rpc/rpc_server.py", line 331, in ws_api
  File "chia/rpc/wallet_rpc_api.py", line 869, in get_wallet_balance
  File "chia/rpc/wallet_rpc_api.py", line 852, in _get_wallet_balance
  File "chia/wallet/wallet_node.py", line 1675, in get_balance
  File "chia/wallet/wallet_node.py", line 1651, in _update_balance_cache
  File "chia/wallet/vc_wallet/cr_cat_wallet.py", line 335, in get_confirmed_balance
  File "chia/wallet/vc_wallet/cr_cat_wallet.py", line 187, in id
AttributeError: 'NoneType' object has no attribute 'id'

2023-09-22T17:10:39.657 full_node chia.full_node.full_node: INFO     Added blocks 2655149 to 2655181
2023-09-22T17:10:39.831 wallet chia.wallet.wallet_blockchain: INFO     Peak set to: 3227130 timestamp: 1695420603
2023-09-22T17:10:39.832 wallet chia.wallet.wallet_node    : INFO     Finished processing new peak of 3227130
2023-09-22T17:10:40.706 wallet chia.wallet.wallet_blockchain: INFO     Peak set to: 3227131 timestamp: 1695420603
2023-09-22T17:10:40.707 wallet chia.wallet.wallet_node    : INFO     Finished processing new peak of 3227131
2023-09-22T17:10:41.640 full_node chia.full_node.full_node: INFO     Added blocks 2655181 to 2655213
2023-09-22T17:10:41.670 wallet chia.wallet.wallet_blockchain: INFO     Peak set to: 3227132 timestamp: 1695420603
2023-09-22T17:10:41.671 wallet chia.wallet.wallet_node    : INFO     Finished processing new peak of 3227132
2023-09-22T17:10:42.008 wallet chia.rpc.rpc_server        : WARNING  Error while handling message: Traceback (most recent call last):
  File "chia/rpc/rpc_server.py", line 340, in safe_handle
  File "chia/rpc/rpc_server.py", line 331, in ws_api
  File "chia/rpc/wallet_rpc_api.py", line 1530, in cat_get_name
  File "chia/wallet/cat_wallet/cat_wallet.py", line 335, in get_name
AttributeError: 'NoneType' object has no attribute 'name'

2023-09-22T17:10:43.184 full_node chia.full_node.full_node: INFO     Added blocks 2655213 to 2655245
2023-09-22T17:10:44.177 full_node chia.full_node.full_node: INFO     Added blocks 2655245 to 2655277
2023-09-22T17:10:48.797 wallet chia.rpc.rpc_server        : WARNING  Error while handling message: Traceback (most recent call last):
  File "chia/rpc/rpc_server.py", line 340, in safe_handle
  File "chia/rpc/rpc_server.py", line 331, in ws_api
  File "chia/rpc/wallet_rpc_api.py", line 869, in get_wallet_balance
  File "chia/rpc/wallet_rpc_api.py", line 852, in _get_wallet_balance
  File "chia/wallet/wallet_node.py", line 1675, in get_balance
  File "chia/wallet/wallet_node.py", line 1651, in _update_balance_cache
  File "chia/wallet/vc_wallet/cr_cat_wallet.py", line 335, in get_confirmed_balance
  File "chia/wallet/vc_wallet/cr_cat_wallet.py", line 187, in id
AttributeError: 'NoneType' object has no attribute 'id'

2023-09-22T17:10:52.073 wallet chia.rpc.rpc_server        : WARNING  Error while handling message: Traceback (most recent call last):
  File "chia/rpc/rpc_server.py", line 340, in safe_handle
  File "chia/rpc/rpc_server.py", line 331, in ws_api
  File "chia/rpc/wallet_rpc_api.py", line 1530, in cat_get_name
  File "chia/wallet/cat_wallet/cat_wallet.py", line 335, in get_name
AttributeError: 'NoneType' object has no attribute 'name'

2023-09-22T17:10:52.783 wallet chia.wallet.wallet_blockchain: INFO     Peak set to: 3227133 timestamp: 1695420603
2023-09-22T17:10:52.784 wallet chia.wallet.wallet_node    : INFO     Finished processing new peak of 3227133
2023-09-22T17:10:58.681 wallet chia.wallet.wallet_blockchain: INFO     Peak set to: 3227134 timestamp: 1695420603
2023-09-22T17:10:58.683 wallet chia.wallet.wallet_node    : INFO     Finished processing new peak of 3227134
2023-09-22T17:10:58.826 wallet chia.rpc.rpc_server        : WARNING  Error while handling message: Traceback (most recent call last):
  File "chia/rpc/rpc_server.py", line 340, in safe_handle
  File "chia/rpc/rpc_server.py", line 331, in ws_api
  File "chia/rpc/wallet_rpc_api.py", line 869, in get_wallet_balance
  File "chia/rpc/wallet_rpc_api.py", line 852, in _get_wallet_balance
  File "chia/wallet/wallet_node.py", line 1675, in get_balance
  File "chia/wallet/wallet_node.py", line 1651, in _update_balance_cache
  File "chia/wallet/vc_wallet/cr_cat_wallet.py", line 335, in get_confirmed_balance
  File "chia/wallet/vc_wallet/cr_cat_wallet.py", line 187, in id
AttributeError: 'NoneType' object has no attribute 'id'

2023-09-22T17:11:02.218 wallet chia.rpc.rpc_server        : WARNING  Error while handling message: Traceback (most recent call last):
  File "chia/rpc/rpc_server.py", line 340, in safe_handle
  File "chia/rpc/rpc_server.py", line 331, in ws_api
  File "chia/rpc/wallet_rpc_api.py", line 1530, in cat_get_name
  File "chia/wallet/cat_wallet/cat_wallet.py", line 335, in get_name
AttributeError: 'NoneType' object has no attribute 'name'

2023-09-22T17:11:03.130 full_node chia.full_node.full_node: INFO     Added blocks 2655277 to 2655309
2023-09-22T17:11:04.364 full_node chia.full_node.full_node: INFO     Added blocks 2655309 to 2655341
2023-09-22T17:11:07.074 full_node chia.full_node.full_node: INFO     Added blocks 2655341 to 2655373
2023-09-22T17:11:08.854 wallet chia.rpc.rpc_server        : WARNING  Error while handling message: Traceback (most recent call last):
  File "chia/rpc/rpc_server.py", line 340, in safe_handle
  File "chia/rpc/rpc_server.py", line 331, in ws_api
  File "chia/rpc/wallet_rpc_api.py", line 869, in get_wallet_balance
  File "chia/rpc/wallet_rpc_api.py", line 852, in _get_wallet_balance
  File "chia/wallet/wallet_node.py", line 1675, in get_balance
  File "chia/wallet/wallet_node.py", line 1651, in _update_balance_cache
  File "chia/wallet/vc_wallet/cr_cat_wallet.py", line 335, in get_confirmed_balance
  File "chia/wallet/vc_wallet/cr_cat_wallet.py", line 187, in id
AttributeError: 'NoneType' object has no attribute 'id'

2023-09-22T17:11:08.924 full_node chia.full_node.full_node: INFO     Added blocks 2655373 to 2655405
2023-09-22T17:11:10.444 full_node chia.full_node.full_node: INFO     Added blocks 2655405 to 2655437
2023-09-22T17:11:11.559 full_node chia.full_node.full_node: INFO     Added blocks 2655437 to 2655469
2023-09-22T17:11:12.321 wallet chia.rpc.rpc_server        : WARNING  Error while handling message: Traceback (most recent call last):
  File "chia/rpc/rpc_server.py", line 340, in safe_handle
  File "chia/rpc/rpc_server.py", line 331, in ws_api
  File "chia/rpc/wallet_rpc_api.py", line 1530, in cat_get_name
  File "chia/wallet/cat_wallet/cat_wallet.py", line 335, in get_name
AttributeError: 'NoneType' object has no attribute 'name'

2023-09-22T17:11:15.758 full_node chia.full_node.full_node: INFO     Added blocks 2655469 to 2655501
2023-09-22T17:11:17.905 full_node chia.full_node.full_node: INFO     Added blocks 2655501 to 2655533
2023-09-22T17:11:18.875 wallet chia.rpc.rpc_server        : WARNING  Error while handling message: Traceback (most recent call last):
  File "chia/rpc/rpc_server.py", line 340, in safe_handle
  File "chia/rpc/rpc_server.py", line 331, in ws_api
  File "chia/rpc/wallet_rpc_api.py", line 869, in get_wallet_balance
  File "chia/rpc/wallet_rpc_api.py", line 852, in _get_wallet_balance
  File "chia/wallet/wallet_node.py", line 1675, in get_balance
  File "chia/wallet/wallet_node.py", line 1651, in _update_balance_cache
  File "chia/wallet/vc_wallet/cr_cat_wallet.py", line 335, in get_confirmed_balance
  File "chia/wallet/vc_wallet/cr_cat_wallet.py", line 187, in id
AttributeError: 'NoneType' object has no attribute 'id'

2023-09-22T17:11:19.344 full_node chia.full_node.full_node: INFO     Added blocks 2655533 to 2655565
2023-09-22T17:11:21.491 full_node chia.full_node.full_node: INFO     Added blocks 2655565 to 2655597
2023-09-22T17:11:22.380 full_node chia.full_node.full_node: INFO     Added blocks 2655597 to 2655629
2023-09-22T17:11:22.391 wallet chia.rpc.rpc_server        : WARNING  Error while handling message: Traceback (most recent call last):
  File "chia/rpc/rpc_server.py", line 340, in safe_handle
  File "chia/rpc/rpc_server.py", line 331, in ws_api
  File "chia/rpc/wallet_rpc_api.py", line 1530, in cat_get_name
  File "chia/wallet/cat_wallet/cat_wallet.py", line 335, in get_name
AttributeError: 'NoneType' object has no attribute 'name'

2023-09-22T17:11:23.615 full_node chia.full_node.full_node: INFO     Added blocks 2655629 to 2655661
2023-09-22T17:11:24.450 wallet chia.wallet.wallet_blockchain: INFO     Peak set to: 3227135 timestamp: 1695420651
2023-09-22T17:11:24.452 wallet chia.wallet.wallet_node    : INFO     Finished processing new peak of 3227135
2023-09-22T17:11:24.792 full_node chia.full_node.full_node: INFO     Added blocks 2655661 to 2655693
2023-09-22T17:11:25.913 full_node chia.full_node.full_node: INFO     Added blocks 2655693 to 2655725
2023-09-22T17:11:27.719 full_node chia.full_node.full_node: INFO     Added blocks 2655725 to 2655757
2023-09-22T17:11:28.896 wallet chia.rpc.rpc_server        : WARNING  Error while handling message: Traceback (most recent call last):
  File "chia/rpc/rpc_server.py", line 340, in safe_handle
  File "chia/rpc/rpc_server.py", line 331, in ws_api
  File "chia/rpc/wallet_rpc_api.py", line 869, in get_wallet_balance
  File "chia/rpc/wallet_rpc_api.py", line 852, in _get_wallet_balance
  File "chia/wallet/wallet_node.py", line 1675, in get_balance
  File "chia/wallet/wallet_node.py", line 1651, in _update_balance_cache
  File "chia/wallet/vc_wallet/cr_cat_wallet.py", line 335, in get_confirmed_balance
  File "chia/wallet/vc_wallet/cr_cat_wallet.py", line 187, in id
AttributeError: 'NoneType' object has no attribute 'id'

2023-09-22T17:11:29.283 full_node chia.full_node.full_node: INFO     Added blocks 2655757 to 2655789
2023-09-22T17:11:29.624 wallet chia.wallet.wallet_blockchain: INFO     Peak set to: 3227136 timestamp: 1695420651
2023-09-22T17:11:29.627 wallet chia.wallet.wallet_node    : INFO     Finished processing new peak of 3227136
2023-09-22T17:11:30.836 full_node chia.full_node.full_node: INFO     Added blocks 2655789 to 2655821
2023-09-22T17:11:32.098 full_node chia.full_node.full_node: INFO     Added blocks 2655821 to 2655853
2023-09-22T17:11:32.502 wallet chia.rpc.rpc_server        : WARNING  Error while handling message: Traceback (most recent call last):
  File "chia/rpc/rpc_server.py", line 340, in safe_handle
  File "chia/rpc/rpc_server.py", line 331, in ws_api
  File "chia/rpc/wallet_rpc_api.py", line 1530, in cat_get_name
  File "chia/wallet/cat_wallet/cat_wallet.py", line 335, in get_name
AttributeError: 'NoneType' object has no attribute 'name'

2023-09-22T17:11:33.122 full_node chia.full_node.full_node: INFO     Added blocks 2655853 to 2655885
2023-09-22T17:11:34.818 full_node chia.full_node.full_node: INFO     Added blocks 2655885 to 2655917
2023-09-22T17:11:36.849 full_node chia.full_node.full_node: INFO     Added blocks 2655917 to 2655949
2023-09-22T17:11:38.991 wallet chia.rpc.rpc_server        : WARNING  Error while handling message: Traceback (most recent call last):
  File "chia/rpc/rpc_server.py", line 340, in safe_handle
  File "chia/rpc/rpc_server.py", line 331, in ws_api
  File "chia/rpc/wallet_rpc_api.py", line 869, in get_wallet_balance
  File "chia/rpc/wallet_rpc_api.py", line 852, in _get_wallet_balance
  File "chia/wallet/wallet_node.py", line 1675, in get_balance
  File "chia/wallet/wallet_node.py", line 1651, in _update_balance_cache
  File "chia/wallet/vc_wallet/cr_cat_wallet.py", line 335, in get_confirmed_balance
  File "chia/wallet/vc_wallet/cr_cat_wallet.py", line 187, in id
AttributeError: 'NoneType' object has no attribute 'id'

2023-09-22T17:11:42.555 wallet chia.rpc.rpc_server        : WARNING  Error while handling message: Traceback (most recent call last):
  File "chia/rpc/rpc_server.py", line 340, in safe_handle
  File "chia/rpc/rpc_server.py", line 331, in ws_api
  File "chia/rpc/wallet_rpc_api.py", line 1530, in cat_get_name
  File "chia/wallet/cat_wallet/cat_wallet.py", line 335, in get_name
AttributeError: 'NoneType' object has no attribute 'name'
```

**Comment by esaung** [comment]
it seems that when you sync another wallet and then come back to this wallet, everything seems to go back to a working state.

**Comment by esaung** [comment]
1.) mint CR CAT
2.) add CR CAT Tail ID to token list
3.) wallet gets stuck
4.) switch to another wallet and let that sync
5.) come back to CR CAT wallet and let that resync and everything is good again

**Comment by paninaro** [comment]
Fixed with PR https://github.com/Chia-Network/chia-blockchain/pull/16423
