### ISSUE TITLE
[Bug]  Chia GUI is not Rendering (Goes White) 

### ISSUE THREAD

**Issue by CookieIdaho** [Chia-Network/chia-blockchain#16538]
### What happened?

Actions I took today 10/5/2023
1. Went to the Github for the latest release (2.1.0)
2. Installed the application via sudo dpkg -i chia-blockchain_2.1.0_amd64.deb
3. Opened GUI and it loaded the normal dark theme I had 
4. After clicking the harvester tab It changed to a white screen
5. I can "reload and force reload" and it will go white again
6. I rebooted the machine and the issue persisted
--------------------------------------------------------------------------------------------------------------------
Hardware of Machine
Ryzen 9 5900x 
128GB Ram 
3080 GPU
X570 Wifi 
-------------------------------------------------------------------------------------------------------------------
Software of machine 
Linux Mint 21.2 Cinnamon
Cinnamon Version 5.8.4
Linux Kernel 5.15.0-76 Generic
-----------------------------------------------------------------------------------------------------------------
GUI About info 
Version 2.1.0
Electron 26.2.1
Chrome 116.0.5845.188
Node 18.16.1
V8 11.6.189.20-electon.0
------------------------------------------------------------------------------------------------------------------
Screenshots 

![Screenshot from 2023-10-05 15-44-14](https://github.com/Chia-Network/chia-blockchain/assets/147107795/75124d87-2e62-4021-8561-40af6a2fa4cf)
![Screenshot from 2023-10-05 15-44-28](https://github.com/Chia-Network/chia-blockchain/assets/147107795/0f1e6fae-491d-4384-bbda-8dff4303d3d3)

### Version

2.1.0

### What platform are you using?

Linux

### What ui mode are you using?

GUI

**Comment by CookieIdaho** [comment]
It appears to only be a linux thing. It works fine on my Windows machine

**Comment by hedandan1989** [comment]
same problem.
Force reload/reboot will white window again.

**Comment by anieto** [comment]
I’m having the same issue as OP. Running Pop OS 22.04, also on a AMD Ryzen system and a 3060TI

**Comment by parkroyk** [comment]
Same issue on Debian 12 (amd64) running xfce. The GUI blanks out in few seconds, and I keep having to Reload it, only to blank out few seconds later. When I revert to 2.0.1 the issue disappears. Reappears with 2.1.0.

**Comment by bgpntx** [comment]
It appears same problem for me:

Oct 06 08:19:06 nest systemd[933]: Started app-gnome-chia\x2dblockchain-4616.scope - Application launched by gnome-shell. 
Oct 06 08:19:07 nest chia-blockchain.desktop[4616]: Checking if userData migration is needed 
Oct 06 08:19:07 nest chia-blockchain.desktop[4616]: /home/bug/.config/Chia Blockchain/Local Storage/leveldb exists: false 
Oct 06 08:19:07 nest chia-blockchain.desktop[4616]: /home/bug/.chia/mainnet/gui/Chia Blockchain/Local Storage/leveldb exists: true 
Oct 06 08:19:07 nest chia-blockchain.desktop[4616]: /home/bug/.config/Chia Blockchain/Local Storage/leveldb/migrated exists: false 
Oct 06 08:19:07 nest chia-blockchain.desktop[4616]: Migration needed: false 
Oct 06 08:19:07 nest chia-blockchain.desktop[4616]: Setting user data directory to /home/bug/.chia/mainnet/gui/Chia Blockchain 
Oct 06 08:19:07 nest dbus-daemon[568]: [system] Activating via systemd: service name='org.bluez' unit='dbus-org.bluez.service' requested by ':1.95' (uid=1000 pid=4616 comm="/opt/chia/chia-blockchain") 
Oct 06 08:19:07 nest systemd[1]: bluetooth.service - Bluetooth service was skipped because of an unmet condition check (ConditionPathIsDirectory=/sys/class/bluetooth). 
Oct 06 08:19:07 nest chia-blockchain.desktop[4616]: Running python executable: 
Oct 06 08:19:07 nest chia-blockchain.desktop[4616]: child process success 
**Oct 06 08:19:07 nest chia-blockchain.desktop[4653]: libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)** 
Oct 06 08:19:08 nest chia-blockchain.desktop[4616]: No cert 
Oct 06 08:19:08 nest chia-blockchain.desktop[4616]: Chia directory /nvme1/.chia/mainnet 
Oct 06 08:19:08 nest chia-blockchain.desktop[4616]: /nvme1/.chia/mainnet already exists, no migration action taken 
Oct 06 08:19:08 nest chia-blockchain.desktop[4616]: No cert 
Oct 06 08:19:08 nest chia-blockchain.desktop[4616]: Have cert 
Oct 06 08:19:11 nest chia-blockchain.desktop[4616]: stderr: Traceback (most recent call last): 
Oct 06 08:19:11 nest chia-blockchain.desktop[4616]: stderr:   File "chia/server/start_full_node.py", line 125, in <module> 
Oct 06 08:19:11 nest chia-blockchain.desktop[4616]:   File "chia/server/start_full_node.py", line 121, in main 
Oct 06 08:19:11 nest chia-blockchain.desktop[4616]:   File "chia/server/start_service.py", line 318, in async_run 
Oct 06 08:19:11 nest chia-blockchain.desktop[4616]:   File "asyncio/runners.py", line 44, in run 
Oct 06 08:19:11 nest chia-blockchain.desktop[4616]:   File "asyncio/base_events.py", line 649, in run_until_complete 
Oct 06 08:19:11 nest chia-blockchain.desktop[4616]:   File "chia/server/start_full_node.py", line 104, in async_main 
Oct 06 08:19:11 nest chia-blockchain.desktop[4616]:   File "chia/server/start_service.py", line 223, in run 
Oct 06 08:19:11 nest chia-blockchain.desktop[4616]:   File "chia/server/start_service.py", line 182, in start 
Oct 06 08:19:11 nest chia-blockchain.desktop[4616]:   File "chia/full_node/full_node.py", line 351, in _start 
Oct 06 08:19:11 nest chia-blockchain.desktop[4616]:   File "chia/full_node/block_store.py", line 49, in create 
**Oct 06 08:19:11 nest chia-blockchain.desktop[4616]: RuntimeError: BlockStore does not support database schema v1** 
**Oct 06 08:19:11 nest chia-blockchain.desktop[4616]: [4724] Failed to execute script 'start_full_node' due to unhandled exception!** 


GeForce RTX 2070 SUPER, 6.2.0-33-generic, Release:	23.04, Chia 2.1.0

**Comment by jlobue10** [comment]
Same problem for me on Nobara 38 (basically Fedora 38). Here is some cli info when I close out the white screen GUI.

```
(venv) [chia01-remote@nobara-Chia01-pc chia-blockchain]$ Error sending from webFrameMain:  Error: Render frame was disposed before WebFrameMain could be accessed
    at WebFrameMain.send (node:electron/js2c/browser_init:2:94495)
    at WebContents.send (node:electron/js2c/browser_init:2:79721)
    at BrowserWindow.<anonymous> (/home/chia01-remote/chia-blockchain/chia-blockchain-gui/packages/gui/build/electron/main.js:2:3786681)
    at BrowserWindow.emit (node:events:525:35)
```

**Comment by h0rd3** [comment]
Same issue for me; just installed 2.1.0 on Linux Mint

**Comment by ChiaMineJP** [comment]
We're aware of this issue and working on a fix.
Thank you for reporting and patience.

**Comment by CookieIdaho** [comment]
> We're aware of this issue and working on a fix. Thank you for reporting and patience.

Thanks for your help man :) I appreciate you

**Comment by BrandtH22** [comment]
> It appears same problem for me:
> 
> Oct 06 08:19:06 nest systemd[933]: Started app-gnome-chia\x2dblockchain-4616.scope - Application launched by gnome-shell. Oct 06 08:19:07 nest chia-blockchain.desktop[4616]: Checking if userData migration is needed Oct 06 08:19:07 nest chia-blockchain.desktop[4616]: /home/bug/.config/Chia Blockchain/Local Storage/leveldb exists: false Oct 06 08:19:07 nest chia-blockchain.desktop[4616]: /home/bug/.chia/mainnet/gui/Chia Blockchain/Local Storage/leveldb exists: true Oct 06 08:19:07 nest chia-blockchain.desktop[4616]: /home/bug/.config/Chia Blockchain/Local Storage/leveldb/migrated exists: false Oct 06 08:19:07 nest chia-blockchain.desktop[4616]: Migration needed: false Oct 06 08:19:07 nest chia-blockchain.desktop[4616]: Setting user data directory to /home/bug/.chia/mainnet/gui/Chia Blockchain Oct 06 08:19:07 nest dbus-daemon[568]: [system] Activating via systemd: service name='org.bluez' unit='dbus-org.bluez.service' requested by ':1.95' (uid=1000 pid=4616 comm="/opt/chia/chia-blockchain") Oct 06 08:19:07 nest systemd[1]: bluetooth.service - Bluetooth service was skipped because of an unmet condition check (ConditionPathIsDirectory=/sys/class/bluetooth). Oct 06 08:19:07 nest chia-blockchain.desktop[4616]: Running python executable: Oct 06 08:19:07 nest chia-blockchain.desktop[4616]: child process success **Oct 06 08:19:07 nest chia-blockchain.desktop[4653]: libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)** Oct 06 08:19:08 nest chia-blockchain.desktop[4616]: No cert Oct 06 08:19:08 nest chia-blockchain.desktop[4616]: Chia directory /nvme1/.chia/mainnet Oct 06 08:19:08 nest chia-blockchain.desktop[4616]: /nvme1/.chia/mainnet already exists, no migration action taken Oct 06 08:19:08 nest chia-blockchain.desktop[4616]: No cert Oct 06 08:19:08 nest chia-blockchain.desktop[4616]: Have cert Oct 06 08:19:11 nest chia-blockchain.desktop[4616]: stderr: Traceback (most recent call last): Oct 06 08:19:11 nest chia-blockchain.desktop[4616]: stderr: File "chia/server/start_full_node.py", line 125, in Oct 06 08:19:11 nest chia-blockchain.desktop[4616]: File "chia/server/start_full_node.py", line 121, in main Oct 06 08:19:11 nest chia-blockchain.desktop[4616]: File "chia/server/start_service.py", line 318, in async_run Oct 06 08:19:11 nest chia-blockchain.desktop[4616]: File "asyncio/runners.py", line 44, in run Oct 06 08:19:11 nest chia-blockchain.desktop[4616]: File "asyncio/base_events.py", line 649, in run_until_complete Oct 06 08:19:11 nest chia-blockchain.desktop[4616]: File "chia/server/start_full_node.py", line 104, in async_main Oct 06 08:19:11 nest chia-blockchain.desktop[4616]: File "chia/server/start_service.py", line 223, in run Oct 06 08:19:11 nest chia-blockchain.desktop[4616]: File "chia/server/start_service.py", line 182, in start Oct 06 08:19:11 nest chia-blockchain.desktop[4616]: File "chia/full_node/full_node.py", line 351, in _start Oct 06 08:19:11 nest chia-blockchain.desktop[4616]: File "chia/full_node/block_store.py", line 49, in create **Oct 06 08:19:11 nest chia-blockchain.desktop[4616]: RuntimeError: BlockStore does not support database schema v1** **Oct 06 08:19:11 nest chia-blockchain.desktop[4616]: [4724] Failed to execute script 'start_full_node' due to unhandled exception!**
> 
> GeForce RTX 2070 SUPER, 6.2.0-33-generic, Release: 23.04, Chia 2.1.0

It looks like you also need to upgrade your blockchain db to v2, the v1 db is no longer supported with 2.1.0.

You can upgrade using the cli command or by downloading the latest snapshot and replacing the current blockchain db.
Upgrade command - https://docs.chia.net/cli/#upgrade
DB download (about halfway down the page) - https://www.chia.net/downloads/

**Comment by lutsifer** [comment]
Same issue on focal fosa

**Comment by Kallhoinz** [comment]
Same on Ubuntu, even after  upgrade to blockchain db to v2

**Comment by surgus** [comment]
Still no progress? WTF???

**Comment by lutsifer** [comment]
> Same on Ubuntu, even after upgrade to blockchain db to v2

It's strictly UI rendering problem. Everything (even harvesting) is working just fine if you are using CLI for example...

**Comment by CookieIdaho** [comment]
> Still no progress? WTF???

1. Absolutely disrespectful 
2. You have no idea how this stuff works do you. You can't just make a change and say done. They have a series of things amd people this goes through before they can release up updates

**Comment by surgus** [comment]
> > Still no progress? WTF???
> 
> 1. Absolutely disrespectful
> 2. You have no idea how this stuff works do you. You can't just make a change and say done. They have a series of things amd people this goes through before they can release up updates

It was disrespectful to publish such bad release.

**Comment by lutsifer** [comment]
> > > Still no progress? WTF???
> > 
> > 
> > 
> > 1. Absolutely disrespectful
> > 2. You have no idea how this stuff works do you. You can't just make a change and say done. They have a series of things amd people this goes through before they can release up updates
> 
> It was disrespectful to publish such bad release.

As a programmer I can confirm, it doesn't matter how careful you are, shit always happens...

**Comment by CookieIdaho** [comment]
> > > Still no progress? WTF???
> > 
> > 
> > 
> > 1. Absolutely disrespectful
> > 2. You have no idea how this stuff works do you. You can't just make a change and say done. They have a series of things amd people this goes through before they can release up updates
> 
> It was disrespectful to publish such bad release, so shut up pls.

Lol if you think I'm gonna shut up you're wrong.  I'm calling you out for toxic and disrespectful. Let's see you push a fix for it.

**Comment by Kallhoinz** [comment]
after entering the password with copy paste in 2 seconds it works in the background of the white screen. reload shows you the status for 2 or 3 seconds. now I can relax and wait for the fix 😉

**Comment by QuintLeo** [comment]
2.1.0-1 for AMD still has the same issue on XUbubtu (aka Ubuntu + XFCE official release) 22.04.

Not a good sign when 2.1.0 claims to be a "required release".

**Comment by bgpntx** [comment]
> > It appears same problem for me:
> > Oct 06 08:19:06 nest systemd[933]: Started app-gnome-chia\x2dblockchain-4616.scope - Application launched by gnome-shell. Oct 06 08:19:07 nest chia-blockchain.desktop[4616]: Checking if userData migration is needed Oct 06 08:19:07 nest chia-blockchain.desktop[4616]: /home/bug/.config/Chia Blockchain/Local Storage/leveldb exists: false Oct 06 08:19:07 nest chia-blockchain.desktop[4616]: /home/bug/.chia/mainnet/gui/Chia Blockchain/Local Storage/leveldb exists: true Oct 06 08:19:07 nest chia-blockchain.desktop[4616]: /home/bug/.config/Chia Blockchain/Local Storage/leveldb/migrated exists: false Oct 06 08:19:07 nest chia-blockchain.desktop[4616]: Migration needed: false Oct 06 08:19:07 nest chia-blockchain.desktop[4616]: Setting user data directory to /home/bug/.chia/mainnet/gui/Chia Blockchain Oct 06 08:19:07 nest dbus-daemon[568]: [system] Activating via systemd: service name='org.bluez' unit='dbus-org.bluez.service' requested by ':1.95' (uid=1000 pid=4616 comm="/opt/chia/chia-blockchain") Oct 06 08:19:07 nest systemd[1]: bluetooth.service - Bluetooth service was skipped because of an unmet condition check (ConditionPathIsDirectory=/sys/class/bluetooth). Oct 06 08:19:07 nest chia-blockchain.desktop[4616]: Running python executable: Oct 06 08:19:07 nest chia-blockchain.desktop[4616]: child process success **Oct 06 08:19:07 nest chia-blockchain.desktop[4653]: libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)** Oct 06 08:19:08 nest chia-blockchain.desktop[4616]: No cert Oct 06 08:19:08 nest chia-blockchain.desktop[4616]: Chia directory /nvme1/.chia/mainnet Oct 06 08:19:08 nest chia-blockchain.desktop[4616]: /nvme1/.chia/mainnet already exists, no migration action taken Oct 06 08:19:08 nest chia-blockchain.desktop[4616]: No cert Oct 06 08:19:08 nest chia-blockchain.desktop[4616]: Have cert Oct 06 08:19:11 nest chia-blockchain.desktop[4616]: stderr: Traceback (most recent call last): Oct 06 08:19:11 nest chia-blockchain.desktop[4616]: stderr: File "chia/server/start_full_node.py", line 125, in Oct 06 08:19:11 nest chia-blockchain.desktop[4616]: File "chia/server/start_full_node.py", line 121, in main Oct 06 08:19:11 nest chia-blockchain.desktop[4616]: File "chia/server/start_service.py", line 318, in async_run Oct 06 08:19:11 nest chia-blockchain.desktop[4616]: File "asyncio/runners.py", line 44, in run Oct 06 08:19:11 nest chia-blockchain.desktop[4616]: File "asyncio/base_events.py", line 649, in run_until_complete Oct 06 08:19:11 nest chia-blockchain.desktop[4616]: File "chia/server/start_full_node.py", line 104, in async_main Oct 06 08:19:11 nest chia-blockchain.desktop[4616]: File "chia/server/start_service.py", line 223, in run Oct 06 08:19:11 nest chia-blockchain.desktop[4616]: File "chia/server/start_service.py", line 182, in start Oct 06 08:19:11 nest chia-blockchain.desktop[4616]: File "chia/full_node/full_node.py", line 351, in _start Oct 06 08:19:11 nest chia-blockchain.desktop[4616]: File "chia/full_node/block_store.py", line 49, in create **Oct 06 08:19:11 nest chia-blockchain.desktop[4616]: RuntimeError: BlockStore does not support database schema v1** **Oct 06 08:19:11 nest chia-blockchain.desktop[4616]: [4724] Failed to execute script 'start_full_node' due to unhandled exception!**
> > GeForce RTX 2070 SUPER, 6.2.0-33-generic, Release: 23.04, Chia 2.1.0
> 
> It looks like you also need to upgrade your blockchain db to v2, the v1 db is no longer supported with 2.1.0.
> 
> You can upgrade using the cli command or by downloading the latest snapshot and replacing the current blockchain db. Upgrade command - https://docs.chia.net/cli/#upgrade DB download (about halfway down the page) - https://www.chia.net/downloads/

It appears that issue is fixed after db upgrade or somehow automagically :) Thanks!

**Comment by airtac** [comment]
White screen here too. Unbuntu 22.04.   I am on DB v2.

**Comment by Shusi88** [comment]
I'm stuck on "Starting Serives" after update. 
Farm runs. Seems to be "only" UI. 
AMD Ryzen 5900X - RX 7800XT Windows 11

**Comment by Ealrann** [comment]
Just tested 2.1.1-rc1 , it solved the issue on my side. 
Thanks guy!

**Comment by lutsifer** [comment]
Confirming `2.1.1-rc1` works on focal fossa amd! Thank you!

P.S
In case anyone wonders how to clone by tag:
`
git clone --depth 1 --branch 2.1.1-rc1 https://github.com/Chia-Network/chia-blockchain.git  --recurse-submodules
`

**Comment by CookieIdaho** [comment]
I have been running the new update 2.1.1 and am not having any issues anymore. 
Thanks for getting this issue resolved. I appreciate the time and effort put in
