### ISSUE TITLE
[BUG] OperationalError('disk I/O error') • starting at 40% completion

### ISSUE THREAD

**Issue by Teledyol** [Chia-Network/chia-blockchain#1654]
Was trying the Parallel Queue hack — setting up unique Queue names to run parallel plotting. 

I had 4 queues of four plots running. Everything seemed to be going OK but my space seemed to be getting a bit too low. Does that methodology use more space?

Just using the GUI on macOS 11.2.3 • Mac Pro 2013 • 3.5 GHz 6-Core Intel Xeon E5 •128 GB 1066 MHz DDR3 • AMD FirePro D300 2 GB • Aura 2T SSD • 32T Final

The Activity Monitor is showing that the plotting took a CPU dip, but now all four queues are running above 90%. Is it safe to assume that the normative behavior will return or should I scrap this attempt?

… … … …

12:47:01.928 full_node asyncio                 : ERROR    Task exception was never retrieved
future: <Task finished name='Task-1129108' coro=<RpcServer._state_changed() done, defined at src/rpc/rpc_server.py:46> exception=OperationalError('disk I/O error')>
Traceback (most recent call last):
  File "src/rpc/rpc_server.py", line 50, in _state_changed
  File "src/rpc/full_node_rpc_api.py", line 52, in _state_changed
  File "src/rpc/full_node_rpc_api.py", line 119, in get_blockchain_state
  File "src/rpc/full_node_rpc_api.py", line 292, in get_network_space
  File "src/full_node/block_store.py", line 204, in get_block_record
  File "aiosqlite/core.py", line 184, in execute
  File "aiosqlite/core.py", line 129, in _execute
  File "aiosqlite/core.py", line 102, in run
sqlite3.OperationalError: disk I/O error
12:47:01.929 full_node asyncio                 : ERROR    Task exception was never retrieved
future: <Task finished name='Task-1129112' coro=<RpcServer._state_changed() done, defined at src/rpc/rpc_server.py:46> exception=OperationalError('disk I/O error')>
Traceback (most recent call last):
  File "src/rpc/rpc_server.py", line 50, in _state_changed
  File "src/rpc/full_node_rpc_api.py", line 52, in _state_changed
  File "src/rpc/full_node_rpc_api.py", line 119, in get_blockchain_state
  File "src/rpc/full_node_rpc_api.py", line 292, in get_network_space
  File "src/full_node/block_store.py", line 204, in get_block_record
  File "aiosqlite/core.py", line 184, in execute
  File "aiosqlite/core.py", line 129, in _execute
  File "aiosqlite/core.py", line 102, in run
sqlite3.OperationalError: disk I/O error
12:47:05.761 full_node asyncio                 : ERROR    Task exception was never retrieved
future: <Task finished name='Task-1129119' coro=<RpcServer._state_changed() done, defined at src/rpc/rpc_server.py:46> exception=OperationalError('disk I/O error')>
Traceback (most recent call last):
  File "src/rpc/rpc_server.py", line 50, in _state_changed
  File "src/rpc/full_node_rpc_api.py", line 52, in _state_changed
  File "src/rpc/full_node_rpc_api.py", line 119, in get_blockchain_state
  File "src/rpc/full_node_rpc_api.py", line 292, in get_network_space
  File "src/full_node/block_store.py", line 204, in get_block_record
  File "aiosqlite/core.py", line 184, in execute
  File "aiosqlite/core.py", line 129, in _execute
  File "aiosqlite/core.py", line 102, in run
sqlite3.OperationalError: disk I/O error
12:47:08.650 full_node full_node_server        : ERROR    Exception: disk I/O error, {'host': '2a01:4f8:211:6a::2', 'port': 8444}. Traceback (most recent call last):
  File "src/server/server.py", line 505, in wrapped_coroutine
  File "src/full_node/full_node_api.py", line 94, in new_peak
  File "src/full_node/full_node.py", line 335, in new_peak
  File "src/full_node/full_node.py", line 285, in short_sync_backtrack
  File "src/full_node/full_node.py", line 282, in short_sync_backtrack
  File "src/full_node/full_node.py", line 961, in respond_block
  File "src/consensus/blockchain.py", line 237, in receive_block
  File "src/full_node/block_store.py", line 79, in add_full_block
  File "aiosqlite/core.py", line 184, in execute
  File "aiosqlite/core.py", line 129, in _execute
  File "aiosqlite/core.py", line 102, in run
sqlite3.OperationalError: disk I/O error

12:47:08.652 full_node full_node_server        : ERROR    Exception: disk I/O error <class 'sqlite3.OperationalError'>, closing connection {'host': '2a01:4f8:211:6a::2', 'port': 8444}. Traceback (most recent call last):
  File "src/server/server.py", line 514, in api_call
  File "asyncio/tasks.py", line 481, in wait_for
  File "src/server/server.py", line 512, in wrapped_coroutine
  File "src/server/server.py", line 505, in wrapped_coroutine
  File "src/full_node/full_node_api.py", line 94, in new_peak
  File "src/full_node/full_node.py", line 335, in new_peak
  File "src/full_node/full_node.py", line 285, in short_sync_backtrack
  File "src/full_node/full_node.py", line 282, in short_sync_backtrack
  File "src/full_node/full_node.py", line 961, in respond_block
  File "src/consensus/blockchain.py", line 237, in receive_block
  File "src/full_node/block_store.py", line 79, in add_full_block
  File "aiosqlite/core.py", line 184, in execute
  File "aiosqlite/core.py", line 129, in _execute
  File "aiosqlite/core.py", line 102, in run
sqlite3.OperationalError: disk I/O error

12:47:08.815 full_node full_node_server        : WARNING  Banning [2a01:4f8:211:6a::2] for 10 seconds
12:47:08.818 full_node asyncio                 : ERROR    Task exception was never retrieved
future: <Task finished name='Task-1129140' coro=<RpcServer._state_changed() done, defined at src/rpc/rpc_server.py:46> exception=OperationalError('disk I/O error')>
Traceback (most recent call last):
  File "src/rpc/rpc_server.py", line 50, in _state_changed
  File "src/rpc/full_node_rpc_api.py", line 52, in _state_changed
  File "src/rpc/full_node_rpc_api.py", line 119, in get_blockchain_state
  File "src/rpc/full_node_rpc_api.py", line 292, in get_network_space
  File "src/full_node/block_store.py", line 204, in get_block_record
  File "aiosqlite/core.py", line 184, in execute
  File "aiosqlite/core.py", line 129, in _execute
  File "aiosqlite/core.py", line 102, in run
sqlite3.OperationalError: disk I/O error

**Comment by Teledyol** [comment]
Stagnated, cut and run. Back to old parallel plotting
