### ISSUE TITLE
[Bug] CANNOT Create a Multiple Issuance CAT

### ISSUE THREAD

**Issue by nicolaardito** [Chia-Network/chia-blockchain#16542]
### What happened?

Launching the command:

_cats --tail ./reference_tails/delegated_tail.clsp.hex --curry Ox############################### --send-to ##################### -a 1000000000 -m 1000 --as-bytes --select-coin_ 

the shell returns an error of insufficient funds

### Version

2.1.0

### What platform are you using?

Linux

### What ui mode are you using?

CLI

### Relevant log output

```shell
Exception from 'wallet' {'error': 'Transaction for 1000001000 is greater than spendable balance of 0. There may be other transactions pending or our minimum coin amount is too high.', 'success': False, 'traceback': 'Traceback (most recent call last):\n  File "chia/rpc/util.py", line 21, in inner\n  File "chia/rpc/util.py", line 82, in rpc_endpoint\n  File "chia/rpc/wallet_rpc_api.py", line 3364, in create_signed_transaction\n  File "chia/rpc/wallet_rpc_api.py", line 3326, in _generate_signed_transaction\n  File "chia/wallet/wallet.py", line 450, in generate_signed_transaction\n  File "chia/wallet/wallet.py", line 308, in _generate_unsigned_transaction\n  File "chia/wallet/wallet.py", line 256, in select_coins\n  File "chia/wallet/coin_selection.py", line 57, in select_coins\nValueError: Transaction for 1000001000 is greater than spendable balance of 0. There may be other transactions pending or our minimum coin amount is too high.\n'}:
Traceback (most recent call last):
  File "/home/nicolaardito/Documenti/CATCreationDIR/CAT-admin-tool/venv/lib/python3.11/site-packages/chia/cmds/cmds_util.py", line 110, in get_any_service_client
    yield node_client, config
  File "/home/nicolaardito/Documenti/CATCreationDIR/CAT-admin-tool/venv/lib/python3.11/site-packages/chia/cmds/cmds_util.py", line 226, in get_wallet_client
    yield wallet_client, new_fp, config
  File "/home/nicolaardito/Documenti/CATCreationDIR/CAT-admin-tool/venv/lib/python3.11/site-packages/cats/cats.py", line 45, in get_context_manager
    yield args
  File "/home/nicolaardito/Documenti/CATCreationDIR/CAT-admin-tool/venv/lib/python3.11/site-packages/cats/cats.py", line 64, in get_signed_tx
    return await wallet_client.create_signed_transaction(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/nicolaardito/Documenti/CATCreationDIR/CAT-admin-tool/venv/lib/python3.11/site-packages/chia/rpc/wallet_rpc_client.py", line 349, in create_signed_transaction
    txs: List[TransactionRecord] = await self.create_signed_transactions(
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/nicolaardito/Documenti/CATCreationDIR/CAT-admin-tool/venv/lib/python3.11/site-packages/chia/rpc/wallet_rpc_client.py", line 334, in create_signed_transactions
    response: Dict = await self.fetch("create_signed_transaction", request)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/nicolaardito/Documenti/CATCreationDIR/CAT-admin-tool/venv/lib/python3.11/site-packages/chia/rpc/rpc_client.py", line 61, in fetch
    raise ValueError(res_json)
ValueError: {'error': 'Transaction for 1000001000 is greater than spendable balance of 0. There may be other transactions pending or our minimum coin amount is too high.', 'success': False, 'traceback': 'Traceback (most recent call last):\n  File "chia/rpc/util.py", line 21, in inner\n  File "chia/rpc/util.py", line 82, in rpc_endpoint\n  File "chia/rpc/wallet_rpc_api.py", line 3364, in create_signed_transaction\n  File "chia/rpc/wallet_rpc_api.py", line 3326, in _generate_signed_transaction\n  File "chia/wallet/wallet.py", line 450, in generate_signed_transaction\n  File "chia/wallet/wallet.py", line 308, in _generate_unsigned_transaction\n  File "chia/wallet/wallet.py", line 256, in select_coins\n  File "chia/wallet/coin_selection.py", line 57, in select_coins\nValueError: Transaction for 1000001000 is greater than spendable balance of 0. There may be other transactions pending or our minimum coin amount is too high.\n'}

Traceback (most recent call last):
  File "/home/nicolaardito/Documenti/CATCreationDIR/CAT-admin-tool/venv/bin/cats", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/nicolaardito/Documenti/CATCreationDIR/CAT-admin-tool/venv/lib/python3.11/site-packages/cats/cats.py", line 389, in main
    cli()
  File "/home/nicolaardito/Documenti/CATCreationDIR/CAT-admin-tool/venv/lib/python3.11/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/nicolaardito/Documenti/CATCreationDIR/CAT-admin-tool/venv/lib/python3.11/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/home/nicolaardito/Documenti/CATCreationDIR/CAT-admin-tool/venv/lib/python3.11/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/nicolaardito/Documenti/CATCreationDIR/CAT-admin-tool/venv/lib/python3.11/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/nicolaardito/Documenti/CATCreationDIR/CAT-admin-tool/venv/lib/python3.11/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/nicolaardito/Documenti/CATCreationDIR/CAT-admin-tool/venv/lib/python3.11/site-packages/cats/cats.py", line 242, in cli
    asyncio.run(
  File "/usr/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/nicolaardito/Documenti/CATCreationDIR/CAT-admin-tool/venv/lib/python3.11/site-packages/cats/cats.py", line 321, in cmd_func
    if signed_tx.spend_bundle is None:
       ^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'spend_bundle'
```

**Comment by BrandtH22** [comment]
Hey @nicolaardito , the errors indicate that the spendable balance is 0. Can you confirm a few things:
1. There are sufficient funds in the wallet you are attempting to use (can run `chia wallet show` to verify balance)
2. The wallet is fully synced (the previous command will show sync status)
3. The wallet that has the balance is being chosen by the cat admin tool (you can generally add a -f flag and use the fingerprint to direct which wallet to use)

**Comment by nicolaardito** [comment]
Hi

I verify:

1) wallet fully synced
2) mojo amount is bigger than required
3) no locked coins for incomplete transactions
4) single wallet. I have tryed with -f option

Nothing... same error.

**Comment by wjblanke** [comment]
can u give us the output of 

chia wallet show

we are wondering what spendable amount is returned
