### ISSUE TITLE
[Bug] After upgrade to v2.1.1, services cannot be started

### ISSUE THREAD

**Issue by mislimcane** [Chia-Network/chia-blockchain#16608]
### What happened?

After I upgrade to v2.1.1 x64 services cannot be started.

I did not update to database chekpoint.

_mainnet
October 1, 2023 checkpoint:[Torrent ](https://torrents.chia.net/databases/mainnet/mainnet.2023-10-01.tar.gz.torrent)

SHA 256 Checksum:_

d28e772a48a656393e25c926674443d5a2a139997bb8cb46e4073655f90c3fa4
![image](https://github.com/Chia-Network/chia-blockchain/assets/10894982/5a2deaa9-5477-4852-8a97-7d756d61d0e7)
![image](https://github.com/Chia-Network/chia-blockchain/assets/10894982/f0663b87-ca41-462d-bac1-4fbc5653df9d)

### Version

2.1.1

### What platform are you using?

Windows

### What ui mode are you using?

GUI

### Relevant log output

```shell
2023-10-10T07:14:56.017 wallet chia.wallet.wallet_node    : WARNING  Peer None did not respond in time.
2023-10-10T07:14:56.033 wallet wallet_server              : WARNING  Banning 123.176.98.238 for 120 seconds
2023-10-10T07:15:51.252 full_node chia.full_node.full_node: WARNING  Block pre-validation time: 10.78 seconds (32 blocks, start height: 4346160)
2023-10-10T07:16:37.861 full_node chia.full_node.full_node: WARNING  Block pre-validation time: 11.08 seconds (32 blocks, start height: 4346192)
2023-10-10T07:17:31.736 full_node chia.full_node.full_node: WARNING  Block pre-validation time: 13.05 seconds (32 blocks, start height: 4346256)
2023-10-10T07:17:49.173 full_node chia.full_node.full_node: WARNING  Block pre-validation time: 11.17 seconds (32 blocks, start height: 4346288)
2023-10-10T07:18:07.011 full_node chia.full_node.full_node: WARNING  Block pre-validation time: 10.14 seconds (32 blocks, start height: 4346320)
2023-10-10T07:18:19.198 full_node chia.full_node.full_node: WARNING  Block pre-validation time: 10.06 seconds (32 blocks, start height: 4346352)
2023-10-10T07:18:51.924 full_node chia.full_node.full_node: WARNING  Block pre-validation time: 11.31 seconds (32 blocks, start height: 4346416)
2023-10-10T07:19:05.141 full_node chia.full_node.full_node: WARNING  Block pre-validation time: 10.41 seconds (32 blocks, start height: 4346448)
2023-10-10T07:19:20.923 full_node chia.full_node.full_node: WARNING  Block pre-validation time: 11.30 seconds (32 blocks, start height: 4346480)
2023-10-10T07:19:34.627 full_node chia.full_node.full_node: WARNING  Block pre-validation time: 10.80 seconds (32 blocks, start height: 4346512)
2023-10-10T07:19:48.846 full_node chia.full_node.full_node: WARNING  Block pre-validation time: 10.73 seconds (32 blocks, start height: 4346544)
2023-10-10T07:21:06.049 full_node chia.full_node.full_node: WARNING  Block pre-validation time: 10.44 seconds (32 blocks, start height: 4346736)
2023-10-10T07:21:20.690 full_node chia.full_node.full_node: WARNING  Block pre-validation time: 10.70 seconds (32 blocks, start height: 4346768)
2023-10-10T07:21:48.924 full_node chia.full_node.full_node: WARNING  Block pre-validation time: 10.39 seconds (32 blocks, start height: 4346832)
2023-10-10T07:22:12.877 full_node chia.full_node.full_node: WARNING  Block pre-validation time: 17.44 seconds (32 blocks, start height: 4346864)
2023-10-10T07:22:30.767 full_node chia.full_node.full_node: WARNING  Block pre-validation time: 11.56 seconds (32 blocks, start height: 4346896)
2023-10-10T07:22:45.610 full_node chia.full_node.full_node: WARNING  Block pre-validation time: 12.00 seconds (32 blocks, start height: 4346928)
2023-10-10T07:23:00.609 full_node chia.full_node.full_node: WARNING  Block pre-validation time: 11.72 seconds (32 blocks, start height: 4346960)
2023-10-10T07:23:14.944 full_node chia.full_node.full_node: WARNING  Block pre-validation time: 11.08 seconds (32 blocks, start height: 4346992)
2023-10-10T07:23:28.471 full_node chia.full_node.full_node: WARNING  Block pre-validation time: 10.50 seconds (32 blocks, start height: 4347024)
2023-10-10T07:23:40.485 full_node chia.full_node.full_node: WARNING  Block pre-validation time: 11.00 seconds (32 blocks, start height: 4347056)
2023-10-10T07:24:01.018 full_node chia.full_node.full_node: WARNING  Block pre-validation time: 13.25 seconds (32 blocks, start height: 4347088)
2023-10-10T07:27:07.926 wallet chia.wallet.wallet_node    : WARNING  Keyring is locked
2023-10-10T07:27:08.038 wallet chia.wallet.wallet_node    : WARNING  Keyring is locked
2023-10-10T07:27:09.004 wallet chia.rpc.rpc_server        : WARNING  Error while handling message: Traceback (most recent call last):
  File "chia\rpc\rpc_server.py", line 340, in safe_handle
  File "chia\rpc\rpc_server.py", line 331, in ws_api
  File "chia\rpc\wallet_rpc_api.py", line 1301, in get_notifications
  File "chia\wallet\wallet_node.py", line 171, in wallet_state_manager
RuntimeError: wallet state manager not assigned

2023-10-10T07:27:09.010 wallet chia.rpc.rpc_server        : WARNING  Error while handling message: Traceback (most recent call last):
  File "chia\rpc\rpc_server.py", line 340, in safe_handle
  File "chia\rpc\rpc_server.py", line 331, in ws_api
  File "chia\rpc\wallet_rpc_api.py", line 522, in get_sync_status
  File "chia\wallet\wallet_node.py", line 171, in wallet_state_manager
RuntimeError: wallet state manager not assigned

2023-10-10T07:27:09.013 wallet chia.rpc.rpc_server        : WARNING  Error while handling message: Traceback (most recent call last):
  File "chia\rpc\rpc_server.py", line 340, in safe_handle
  File "chia\rpc\rpc_server.py", line 331, in ws_api
  File "chia\rpc\wallet_rpc_api.py", line 598, in get_wallets
  File "chia\wallet\wallet_node.py", line 171, in wallet_state_manager
RuntimeError: wallet state manager not assigned

2023-10-10T07:27:09.841 wallet wallet_server              : ERROR    Caught exception: RuntimeError: wallet state manager not assigned
Traceback (most recent call last):
  File "chia\util\log_exceptions.py", line 20, in log_exceptions
  File "chia\server\ws_connection.py", line 307, in close
  File "chia\server\server.py", line 554, in connection_closed
  File "chia\wallet\wallet_node.py", line 687, in on_disconnect
  File "chia\wallet\wallet_node.py", line 171, in wallet_state_manager
RuntimeError: wallet state manager not assigned

2023-10-10T07:27:11.137 wallet wallet_server              : WARNING  API not ready, ignore request: {'data': '0x33d55e4cd78db3826b59dd0c2c34b26fdc84781c20d3d07476f68fbfdee16d80004259b700000000000000000000000221ddb4e0004259b7',
 'id': None,
 'type': 50}
2023-10-10T07:27:12.953 wallet wallet_server              : WARNING  API not ready, ignore request: {'data': '0x33d55e4cd78db3826b59dd0c2c34b26fdc84781c20d3d07476f68fbfdee16d80004259b700000000000000000000000221ddb4e0004259b7',
 'id': None,
 'type': 50}
2023-10-10T07:27:13.340 wallet wallet_server              : WARNING  API not ready, ignore request: {'data': '0x6b68e8e5343bb328505c87e5f57c9292f23d03202c9e1fb850e92fc4e88b8f6400412f770000000000000000000000021590174000412f77',
 'id': None,
 'type': 50}
2023-10-10T07:27:13.918 wallet wallet_server              : WARNING  API not ready, ignore request: {'data': '0x33d55e4cd78db3826b59dd0c2c34b26fdc84781c20d3d07476f68fbfdee16d80004259b700000000000000000000000221ddb4e0004259b7',
 'id': None,
 'type': 50}
2023-10-10T07:27:15.762 wallet wallet_server              : ERROR    Caught exception: RuntimeError: wallet state manager not assigned
Traceback (most recent call last):
  File "chia\util\log_exceptions.py", line 20, in log_exceptions
  File "chia\server\ws_connection.py", line 307, in close
  File "chia\server\server.py", line 554, in connection_closed
  File "chia\wallet\wallet_node.py", line 687, in on_disconnect
  File "chia\wallet\wallet_node.py", line 171, in wallet_state_manager
RuntimeError: wallet state manager not assigned

2023-10-10T07:27:19.460 wallet chia.rpc.rpc_server        : WARNING  Error while handling message: Traceback (most recent call last):
  File "chia\rpc\rpc_server.py", line 340, in safe_handle
  File "chia\rpc\rpc_server.py", line 331, in ws_api
  File "chia\rpc\wallet_rpc_api.py", line 522, in get_sync_status
  File "chia\wallet\wallet_node.py", line 171, in wallet_state_manager
RuntimeError: wallet state manager not assigned

2023-10-10T07:27:24.406 wallet wallet_server              : ERROR    Caught exception: RuntimeError: wallet state manager not assigned
Traceback (most recent call last):
  File "chia\util\log_exceptions.py", line 20, in log_exceptions
  File "chia\server\ws_connection.py", line 307, in close
  File "chia\server\server.py", line 554, in connection_closed
  File "chia\wallet\wallet_node.py", line 687, in on_disconnect
  File "chia\wallet\wallet_node.py", line 171, in wallet_state_manager
RuntimeError: wallet state manager not assigned

2023-10-10T07:27:24.483 wallet wallet_server              : ERROR    Caught exception: RuntimeError: wallet state manager not assigned
Traceback (most recent call last):
  File "chia\util\log_exceptions.py", line 20, in log_exceptions
  File "chia\server\ws_connection.py", line 307, in close
  File "chia\server\server.py", line 554, in connection_closed
  File "chia\wallet\wallet_node.py", line 687, in on_disconnect
  File "chia\wallet\wallet_node.py", line 171, in wallet_state_manager
RuntimeError: wallet state manager not assigned

2023-10-10T07:27:24.922 wallet wallet_server              : ERROR    Caught exception: RuntimeError: wallet state manager not assigned
Traceback (most recent call last):
  File "chia\util\log_exceptions.py", line 20, in log_exceptions
  File "chia\server\ws_connection.py", line 307, in close
  File "chia\server\server.py", line 554, in connection_closed
  File "chia\wallet\wallet_node.py", line 687, in on_disconnect
  File "chia\wallet\wallet_node.py", line 171, in wallet_state_manager
RuntimeError: wallet state manager not assigned

2023-10-10T07:27:25.210 wallet wallet_server              : ERROR    Caught exception: RuntimeError: wallet state manager not assigned
Traceback (most recent call last):
  File "chia\util\log_exceptions.py", line 20, in log_exceptions
  File "chia\server\ws_connection.py", line 307, in close
  File "chia\server\server.py", line 554, in connection_closed
  File "chia\wallet\wallet_node.py", line 687, in on_disconnect
  File "chia\wallet\wallet_node.py", line 171, in wallet_state_manager
RuntimeError: wallet state manager not assigned

2023-10-10T07:30:19.481 full_node chia.full_node.full_node: WARNING  Block pre-validation time: 12.70 seconds (32 blocks, start height: 4347120)
2023-10-10T07:30:34.449 full_node chia.full_node.full_node: WARNING  Block pre-validation time: 11.59 seconds (32 blocks, start height: 4347152)
2023-10-10T07:31:04.012 full_node chia.full_node.full_node: WARNING  Block pre-validation time: 11.23 seconds (32 blocks, start height: 4347216)
2023-10-10T07:32:03.981 full_node chia.full_node.full_node: WARNING  Block pre-validation time: 10.42 seconds (32 blocks, start height: 4347344)
2023-10-10T07:32:47.324 full_node chia.full_node.full_node: WARNING  Block pre-validation time: 10.34 seconds (32 blocks, start height: 4347440)
2023-10-10T07:33:29.042 full_node chia.full_node.full_node: WARNING  Block pre-validation time: 19.06 seconds (32 blocks, start height: 4347536)
2023-10-10T07:33:47.498 full_node chia.full_node.full_node: WARNING  Block pre-validation time: 15.36 seconds (32 blocks, start height: 4347568)
2023-10-10T07:34:04.231 full_node chia.full_node.full_node: WARNING  Block pre-validation time: 12.33 seconds (32 blocks, start height: 4347600)
2023-10-10T07:34:19.152 full_node chia.full_node.full_node: WARNING  Block pre-validation time: 12.55 seconds (32 blocks, start height: 4347632)
2023-10-10T07:34:38.527 full_node chia.full_node.full_node: WARNING  Block pre-validation time: 13.56 seconds (32 blocks, start height: 4347664)
2023-10-10T07:34:57.793 full_node chia.full_node.full_node: WARNING  Block pre-validation time: 13.22 seconds (32 blocks, start height: 4347696)
2023-10-10T07:35:21.293 full_node chia.full_node.full_node: WARNING  Block pre-validation time: 14.38 seconds (32 blocks, start height: 4347728)
2023-10-10T07:35:52.628 full_node chia.full_node.full_node: WARNING  Block pre-validation time: 24.44 seconds (32 blocks, start height: 4347760)
2023-10-10T07:36:06.949 full_node chia.full_node.full_node: ERROR    sync from fork point failed err: 
2023-10-10T08:12:40.640 wallet wallet_server              : WARNING  Cannot write to closing transport 62.74.249.238
2023-10-10T08:12:41.561 wallet wallet_server              : WARNING  Cannot write to closing transport 193.95.228.55
2023-10-10T08:27:14.053 wallet chia.wallet.wallet_node    : WARNING  Peer PeerInfo(_ip=IPv4Address('98.38.46.138'), _port=8444) did not respond in time.
2023-10-10T08:27:14.055 wallet wallet_server              : WARNING  Banning 98.38.46.138 for 120 seconds
2023-10-10T10:08:57.610 wallet chia.wallet.wallet_node    : WARNING  bad header block response from Peer PeerInfo(_ip=IPv4Address('180.150.31.32'), _port=8444).
2023-10-10T10:08:57.795 wallet chia.wallet.wallet_node    : WARNING  bad header block response from Peer PeerInfo(_ip=IPv4Address('70.55.114.187'), _port=8444).
2023-10-10T10:08:59.546 wallet chia.wallet.wallet_node    : WARNING  bad header block response from Peer PeerInfo(_ip=IPv4Address('136.34.184.222'), _port=8444).
2023-10-10T10:08:59.625 wallet chia.wallet.wallet_node    : WARNING  bad header block response from Peer PeerInfo(_ip=IPv4Address('79.98.106.170'), _port=8444).
2023-10-10T10:47:07.559 wallet chia.wallet.wallet_node    : WARNING  Peer PeerInfo(_ip=IPv4Address('1.162.182.239'), _port=8444) did not respond in time.
2023-10-10T10:47:07.561 wallet wallet_server              : WARNING  Banning 1.162.182.239 for 120 seconds
2023-10-11T20:57:54.883 wallet chia.wallet.wallet_node    : ERROR    Error syncing to PeerInfo(_ip=IPv4Address('217.198.130.81'), _port=8444)
Traceback (most recent call last):
  File "chia\wallet\wallet_node.py", line 1136, in new_peak_from_untrusted
  File "chia\wallet\wallet_node.py", line 1145, in long_sync_from_untrusted
  File "chia\wallet\wallet_node.py", line 1269, in fetch_and_update_weight_proof
Exception: weight proof response was none
2023-10-11T21:04:06.774 wallet wallet_server              : WARNING  Cannot write to closing transport 195.181.151.17
2023-10-11T21:14:07.333 wallet chia.wallet.wallet_node    : WARNING  bad header block response from Peer PeerInfo(_ip=IPv4Address('93.116.1.208'), _port=8444).
2023-10-11T21:40:03.320 wallet wallet_server              : WARNING  Cannot write to closing transport 135.26.83.180
2023-10-11T22:18:20.788 wallet chia.wallet.wallet_node    : WARNING  Peer None did not respond in time.
2023-10-11T22:18:20.804 wallet wallet_server              : WARNING  Banning 107.181.87.19 for 120 seconds
2023-10-11T23:18:08.461 wallet chia.wallet.wallet_node    : WARNING  Peer PeerInfo(_ip=IPv4Address('223.72.102.55'), _port=8444) did not respond in time.
2023-10-11T23:18:08.477 wallet wallet_server              : WARNING  Banning 223.72.102.55 for 120 seconds
2023-10-11T23:45:12.867 wallet chia.wallet.wallet_node    : WARNING  Peer None did not respond in time.
2023-10-11T23:45:12.883 wallet wallet_server              : WARNING  Banning 86.128.177.137 for 120 seconds
2023-10-12T06:37:27.756 wallet chia.wallet.wallet_state_manager: ERROR    set_sync_mode failed - range: 4356183-4357471, seconds: 21.672470808029175
Traceback (most recent call last):
  File "chia\wallet\wallet_state_manager.py", line 592, in set_sync_mode
  File "chia\wallet\wallet_node.py", line 1154, in long_sync_from_untrusted
  File "chia\wallet\wallet_node.py", line 775, in long_sync
  File "chia\wallet\util\wallet_sync_utils.py", line 62, in subscribe_to_phs
ValueError: None response from peer 71.227.39.0 for register_interest_in_puzzle_hash
2023-10-12T18:55:28.910 wallet chia.wallet.wallet_node    : ERROR    Error syncing to PeerInfo(_ip=IPv4Address('172.116.118.253'), _port=8444)
Traceback (most recent call last):
  File "chia\wallet\wallet_node.py", line 1136, in new_peak_from_untrusted
  File "chia\wallet\wallet_node.py", line 1145, in long_sync_from_untrusted
  File "chia\wallet\wallet_node.py", line 1269, in fetch_and_update_weight_proof
Exception: weight proof response was none
2023-10-12T18:55:28.914 wallet chia.wallet.wallet_node    : WARNING  Peer PeerInfo(_ip=IPv4Address('172.116.118.253'), _port=8444) did not respond in time.
2023-10-12T18:55:28.915 wallet wallet_server              : WARNING  Banning 172.116.118.253 for 120 seconds
```

**Comment by BrandtH22** [comment]
Hey @mislimcane  , It is likely that your database needs to be upgraded to v2 either by using the cli commands here (https://docs.chia.net/cli#upgrade) or by replacing the v1 with the official DB snapshot from here (https://www.chia.net/downloads/#database-checkpoint).

Steps for the CLI command:
```
1. Stop the chia client (this can be done while chia is running but stopping the client saves from any potential issues)
2. Run the command `chia db upgrade` (you do not need the input or output paths if these are still default)
- This process will take some time and requires additional space as the v1 db is compacted into the v2 db which leaves the v1 db intact
3. Verify the config file (~\.chia\mainnet\config\config.yaml) has the correct value under the full_node section for `database_path: db/blockchain_v2_CHALLENGE.sqlite` (should only need to change the v1 to v2)
4. After the above completes start the chia client
5. If all loads up properly (might take ~5-10 minutes to load) then you can safely delete the v1 db found here (~\.chia\mainnet\db\blockchain_v1_mainnet.sqlite)

```

Steps for using the torrent: 
```
1. Download the torrent file from https://www.chia.net/downloads/#database-checkpoint
2. Use a torrent client to download the full db
3. Unpack/reassemble the torrent file that was downloaded (on windows I used 7zip, Mac and linux have built in tools that work for this)
4. Move the db to the correct folder (~\.chia\mainnet\db\) and update the name to "blockchain_v2_mainnet.sqlite" (removing the date information in the name)
5. Verify the config file (~\.chia\mainnet\config\config.yaml) has the correct value under the full_node section for `database_path: db/blockchain_v2_CHALLENGE.sqlite` (should only need to change the v1 to v2)
6. Launch chia and wait for a bit (the height to hash and peers files need to be built so this can take 5-10 minutes)

```

**Comment by mislimcane** [comment]
Ok I tried the second option and it works, but syncing is started from beginning. I think that I need to wait few days on complete sync... so I will try the first one options.

I will close bug.

**Comment by csh-de** [comment]
> Steps for using the torrent:
> 
> ```
> 1. Download the torrent file from https://www.chia.net/downloads/#database-checkpoint
> 2. Use a torrent client to download the full db
> 3. Unpack/reassemble the torrent file that was downloaded (on windows I used 7zip, Mac and linux have built in tools that work for this)
> 4. Move the db to the correct folder (~\.chia\mainnet\db\) and update the name to "blockchain_v2_mainnet.sqlite" (removing the date information in the name)
> 5. Verify the config file (~\.chia\mainnet\config\config.yaml) has the correct value under the full_node section for `database_path: db/blockchain_v2_CHALLENGE.sqlite` (should only need to change the v1 to v2)
> 6. Launch chia and wait for a bit (the height to hash and peers files need to be built so this can take 5-10 minutes)
> ```

This worked perfectly for me, thank you!
