### ISSUE TITLE
[Bug] После обновления  на V2.1.1  возникли проблемы с видимостью каталогов дисков, подключенных как пустые папки.

### ISSUE THREAD

**Issue by LudmilaAlex** [Chia-Network/chia-blockchain#16616]
### What happened?

После обновления  на V2.1.1  возникли проблемы с видимостью каталогов дисков, подключенных как пустые папки.

Для дисков HDD(GPT)  после нового переназначения каталогов проблема исчезла.
Но для дисков HDD(MBR) проблема таким образом не решилась.
Не находит каталоги HDD(MBR) дисков , подключенных как пустые папки (без назначения букв дискам)
Path doesn't exist: Volume{3f0348f9-0000-0000-0010-080000000000}\Crc9
Однако APP DiskGenius находит такой путь: GUID Path:	\\?\Volume{3f0348f9-0000-0000-0010-080000000000
![2023-10-13_13-22-30](https://github.com/Chia-Network/chia-blockchain/assets/97796236/c0905d62-43a9-4902-a377-4bef24ce5205)

Приходиться назначать буквы таким дискам, чтобы добавить их каталоги. Это неудобно, и не безопасно (не исключены случайные ошибочные действия на этих разделах дисков с участками)
![2023-10-13_13-05-56 (2)](https://github.com/Chia-Network/chia-blockchain/assets/97796236/76e8afdc-a6d8-41dd-b138-52bf6013fc81)

### Version

Версия 2.1.1 | 64 бит

### What platform are you using?

Windows

### What ui mode are you using?

GUI

### Relevant log output

```shell
+++++++++++debug.log 
2023-10-13T09:58:41.579 harvester harvester_server        : INFO     Connected with farmer PeerInfo(_ip=IPv4Address('127.0.0.1'), _port=8447)
2023-10-13T09:58:41.585 harvester chia.plotting.cache     : INFO     Loaded 1151361 bytes of cached data
2023-10-13T09:58:41.639 harvester chia.plotting.cache     : INFO     Parsed 1151 cache entries in 0.05s
2023-10-13T09:58:41.668 harvester chia.plotting.util      : WARNING  Directory: C:\Users\1\AppData\Local\Programs\Chia\Volume{811bf8a4-66de-4e3f-9208-0a717f55c704}\Crc55 does not exist.
2023-10-13T09:58:41.669 harvester chia.plotting.util      : WARNING  Directory: C:\Users\1\AppData\Local\Programs\Chia\Volume{f93eb7bd-4ad1-4891-b284-6be56d0feef6}\Crc73 does not exist.
2023-10-13T09:58:41.669 harvester chia.plotting.util      : WARNING  Directory: C:\Users\1\AppData\Local\Programs\Chia\Volume{abd6e64b-65c2-4579-a434-edb068012b97}\Crc73 does not exist.
2023-10-13T09:58:41.669 harvester chia.plotting.util      : WARNING  Directory: C:\Users\1\AppData\Local\Programs\Chia\Volume{e4f2d32e-59ff-441e-9ca8-834ad8293482}\Crc73 does not exist.
2023-10-13T09:58:41.671 harvester chia.plotting.util      : WARNING  Directory: C:\Users\1\AppData\Local\Programs\Chia\Volume{3473f3ff-685b-4036-97ec-745265291ee5}\Crc73 does not exist.
2023-10-13T09:58:41.671 harvester chia.plotting.util      : WARNING  Directory: C:\Users\1\AppData\Local\Programs\Chia\Volume{14506a1c-b438-4c08-b984-4fd95c5010f1}\Crc73 does not exist.
2023-10-13T09:58:41.671 harvester chia.plotting.util      : WARNING  Directory: C:\Users\1\AppData\Local\Programs\Chia\Volume{7e74b0ce-8627-44ce-a790-6843f2e7a528}\Crc73 does not exist.
2023-10-13T09:58:41.672 harvester chia.plotting.util      : WARNING  Directory: C:\Users\1\AppData\Local\Programs\Chia\Volume{773fe227-cbde-42c2-b9ab-6e72d689a3f2}\Crc73 does not exist.
2023-10-13T09:58:41.672 harvester chia.plotting.util      : WARNING  Directory: C:\Users\1\AppData\Local\Programs\Chia\Volume{2fa887a9-8d1c-4f29-a4e4-7f6e1e9f3115}\Crc73 does not exist.
2023-10-13T09:58:41.672 harvester chia.plotting.util      : WARNING  Directory: C:\Users\1\AppData\Local\Programs\Chia\Volume{00aed128-33b3-458e-b8d5-3f9f76865d08}\Crc73 does not exist.
2023-10-13T09:58:41.673 harvester chia.plotting.util      : WARNING  Directory: C:\Users\1\AppData\Local\Programs\Chia\Volume{fb3b248d-37c0-4a48-8ed2-d493c879ac52}\Crc128 does not exist.
2023-10-13T09:58:41.673 harvester chia.plotting.util      : WARNING  Directory: C:\Users\1\AppData\Local\Programs\Chia\Volume{6bbba17b-1af5-463e-b872-984f59c8c0b4}\Crc128 does not exist.
2023-10-13T09:58:41.674 harvester chia.plotting.util      : WARNING  Directory: C:\Users\1\AppData\Local\Programs\Chia\Volume{9d664ec5-b25a-450f-a22a-e5b44dfa747f}\Crc73 does not exist.
2023-10-13T09:58:41.674 harvester chia.plotting.util      : WARNING  Directory: C:\Users\1\AppData\Local\Programs\Chia\Volume{3f0348f9-0000-0000-0010-080000000000}\Crc9 does not exist.
2023-10-13T09:58:41.674 harvester chia.plotting.util      : WARNING  Directory: C:\Users\1\AppData\Local\Programs\Chia\Volume{f853a759-0000-0000-0000-e02c03000000}\Crl18 does not exist.
2023-10-13T09:58:41.675 harvester chia.harvester.harvester: INFO     _plot_refresh_callback: event started, loaded 0, removed 0, processed 0, remaining 1, duration: 0.00 seconds, total plots: 0
2023-10-13T09:58:41.676 harvester chia.harvester.harvester: INFO     _plot_refresh_callback: event done, loaded 1, removed 0, processed 1, remaining 0, duration: 0.00 seconds, total plots: 1
2023-10-13T09:58:41.680 full_node chia.full_node.full_node: INFO     Blockchain initialized to peak 0aace7657d47c33cf30a2f0dbd8c6dfac3b6aa4a577528291ff5cc0356e3f641 height 4362528, time taken: 0s
2023-10-13T09:58:41.682 full_node chia.full_node.full_node: INFO      Updated peak to height 4362528, weight 9196569632, hh 0aace7657d47c33cf30a2f0dbd8c6dfac3b6aa4a577528291ff5cc0356e3f641, forked at 4362527, rh: 565d8797ed1485e8444562d09969c7834d28356fd6173b698a6c1304827c2665, total iters: 18525457354704, overflow: False, deficit: 4, difficulty: 2720, sub slot iters: 147849216, Generator size: No tx, Generator ref list size: No tx
2023-10-13T09:58:41.579 harvester harvester_server        : INFO     Connected with farmer PeerInfo(_ip=IPv4Address('127.0.0.1'), _port=8447)
2023-10-13T09:58:41.585 harvester chia.plotting.cache     : INFO     Loaded 1151361 bytes of cached data
2023-10-13T09:58:41.639 harvester chia.plotting.cache     : INFO     Parsed 1151 cache entries in 0.05s
2023-10-13T09:58:41.668 harvester chia.plotting.util      : WARNING  Directory: C:\Users\1\AppData\Local\Programs\Chia\Volume{811bf8a4-66de-4e3f-9208-0a717f55c704}\Crc55 does not exist.
2023-10-13T09:58:41.669 harvester chia.plotting.util      : WARNING  Directory: C:\Users\1\AppData\Local\Programs\Chia\Volume{f93eb7bd-4ad1-4891-b284-6be56d0feef6}\Crc73 does not exist.
2023-10-13T09:58:41.669 harvester chia.plotting.util      : WARNING  Directory: C:\Users\1\AppData\Local\Programs\Chia\Volume{abd6e64b-65c2-4579-a434-edb068012b97}\Crc73 does not exist.
2023-10-13T09:58:41.669 harvester chia.plotting.util      : WARNING  Directory: C:\Users\1\AppData\Local\Programs\Chia\Volume{e4f2d32e-59ff-441e-9ca8-834ad8293482}\Crc73 does not exist.
2023-10-13T09:58:41.671 harvester chia.plotting.util      : WARNING  Directory: C:\Users\1\AppData\Local\Programs\Chia\Volume{3473f3ff-685b-4036-97ec-745265291ee5}\Crc73 does not exist.
2023-10-13T09:58:41.671 harvester chia.plotting.util      : WARNING  Directory: C:\Users\1\AppData\Local\Programs\Chia\Volume{14506a1c-b438-4c08-b984-4fd95c5010f1}\Crc73 does not exist.
2023-10-13T09:58:41.671 harvester chia.plotting.util      : WARNING  Directory: C:\Users\1\AppData\Local\Programs\Chia\Volume{7e74b0ce-8627-44ce-a790-6843f2e7a528}\Crc73 does not exist.
2023-10-13T09:58:41.672 harvester chia.plotting.util      : WARNING  Directory: C:\Users\1\AppData\Local\Programs\Chia\Volume{773fe227-cbde-42c2-b9ab-6e72d689a3f2}\Crc73 does not exist.
2023-10-13T09:58:41.672 harvester chia.plotting.util      : WARNING  Directory: C:\Users\1\AppData\Local\Programs\Chia\Volume{2fa887a9-8d1c-4f29-a4e4-7f6e1e9f3115}\Crc73 does not exist.
2023-10-13T09:58:41.672 harvester chia.plotting.util      : WARNING  Directory: C:\Users\1\AppData\Local\Programs\Chia\Volume{00aed128-33b3-458e-b8d5-3f9f76865d08}\Crc73 does not exist.
2023-10-13T09:58:41.673 harvester chia.plotting.util      : WARNING  Directory: C:\Users\1\AppData\Local\Programs\Chia\Volume{fb3b248d-37c0-4a48-8ed2-d493c879ac52}\Crc128 does not exist.
2023-10-13T09:58:41.673 harvester chia.plotting.util      : WARNING  Directory: C:\Users\1\AppData\Local\Programs\Chia\Volume{6bbba17b-1af5-463e-b872-984f59c8c0b4}\Crc128 does not exist.
2023-10-13T09:58:41.674 harvester chia.plotting.util      : WARNING  Directory: C:\Users\1\AppData\Local\Programs\Chia\Volume{9d664ec5-b25a-450f-a22a-e5b44dfa747f}\Crc73 does not exist.
2023-10-13T09:58:41.674 harvester chia.plotting.util      : WARNING  Directory: C:\Users\1\AppData\Local\Programs\Chia\Volume{3f0348f9-0000-0000-0010-080000000000}\Crc9 does not exist.
2023-10-13T09:58:41.674 harvester chia.plotting.util      : WARNING  Directory: C:\Users\1\AppData\Local\Programs\Chia\Volume{f853a759-0000-0000-0000-e02c03000000}\Crl18 does not exist.
2023-10-13T09:58:41.675 harvester chia.harvester.harvester: INFO     _plot_refresh_callback: event started, loaded 0, removed 0, processed 0, remaining 1, duration: 0.00 seconds, total plots: 0
2023-10-13T09:58:41.676 harvester chia.harvester.harvester: INFO     _plot_refresh_callback: event done, loaded 1, removed 0, processed 1, remaining 0, duration: 0.00 seconds, total plots: 1
2023-10-13T09:58:41.680 full_node chia.full_node.full_node: INFO     Blockchain initialized to peak 0aace7657d47c33cf30a2f0dbd8c6dfac3b6aa4a577528291ff5cc0356e3f641 height 4362528, time taken: 0s
2023-10-13T09:58:41.682 full_node chia.full_node.full_node: INFO      Updated peak to height 4362528, weight 9196569632, hh 0aace7657d47c33cf30a2f0dbd8c6dfac3b6aa4a577528291ff5cc0356e3f641, forked at 4362527, rh: 565d8797ed1485e8444562d09969c7834d28356fd6173b698a6c1304827c2665, total iters: 18525457354704, overflow: False, deficit: 4, difficulty: 2720, sub slot iters: 147849216, Generator size: No tx, Generator ref list size: No tx
2023-10-13T09:58:41.579 harvester harvester_server        : INFO     Connected with farmer PeerInfo(_ip=IPv4Address('127.0.0.1'), _port=8447)
2023-10-13T09:58:41.585 harvester chia.plotting.cache     : INFO     Loaded 1151361 bytes of cached data
2023-10-13T09:58:41.639 harvester chia.plotting.cache     : INFO     Parsed 1151 cache entries in 0.05s
2023-10-13T09:58:41.668 harvester chia.plotting.util      : WARNING  Directory: C:\Users\1\AppData\Local\Programs\Chia\Volume{811bf8a4-66de-4e3f-9208-0a717f55c704}\Crc55 does not exist.
2023-10-13T09:58:41.669 harvester chia.plotting.util      : WARNING  Directory: C:\Users\1\AppData\Local\Programs\Chia\Volume{f93eb7bd-4ad1-4891-b284-6be56d0feef6}\Crc73 does not exist.
2023-10-13T09:58:41.669 harvester chia.plotting.util      : WARNING  Directory: C:\Users\1\AppData\Local\Programs\Chia\Volume{abd6e64b-65c2-4579-a434-edb068012b97}\Crc73 does not exist.
2023-10-13T09:58:41.669 harvester chia.plotting.util      : WARNING  Directory: C:\Users\1\AppData\Local\Programs\Chia\Volume{e4f2d32e-59ff-441e-9ca8-834ad8293482}\Crc73 does not exist.
2023-10-13T09:58:41.671 harvester chia.plotting.util      : WARNING  Directory: C:\Users\1\AppData\Local\Programs\Chia\Volume{3473f3ff-685b-4036-97ec-745265291ee5}\Crc73 does not exist.
2023-10-13T09:58:41.671 harvester chia.plotting.util      : WARNING  Directory: C:\Users\1\AppData\Local\Programs\Chia\Volume{14506a1c-b438-4c08-b984-4fd95c5010f1}\Crc73 does not exist.
2023-10-13T09:58:41.671 harvester chia.plotting.util      : WARNING  Directory: C:\Users\1\AppData\Local\Programs\Chia\Volume{7e74b0ce-8627-44ce-a790-6843f2e7a528}\Crc73 does not exist.
2023-10-13T09:58:41.672 harvester chia.plotting.util      : WARNING  Directory: C:\Users\1\AppData\Local\Programs\Chia\Volume{773fe227-cbde-42c2-b9ab-6e72d689a3f2}\Crc73 does not exist.
2023-10-13T09:58:41.672 harvester chia.plotting.util      : WARNING  Directory: C:\Users\1\AppData\Local\Programs\Chia\Volume{2fa887a9-8d1c-4f29-a4e4-7f6e1e9f3115}\Crc73 does not exist.
2023-10-13T09:58:41.672 harvester chia.plotting.util      : WARNING  Directory: C:\Users\1\AppData\Local\Programs\Chia\Volume{00aed128-33b3-458e-b8d5-3f9f76865d08}\Crc73 does not exist.
2023-10-13T09:58:41.673 harvester chia.plotting.util      : WARNING  Directory: C:\Users\1\AppData\Local\Programs\Chia\Volume{fb3b248d-37c0-4a48-8ed2-d493c879ac52}\Crc128 does not exist.
2023-10-13T09:58:41.673 harvester chia.plotting.util      : WARNING  Directory: C:\Users\1\AppData\Local\Programs\Chia\Volume{6bbba17b-1af5-463e-b872-984f59c8c0b4}\Crc128 does not exist.
2023-10-13T09:58:41.674 harvester chia.plotting.util      : WARNING  Directory: C:\Users\1\AppData\Local\Programs\Chia\Volume{9d664ec5-b25a-450f-a22a-e5b44dfa747f}\Crc73 does not exist.
2023-10-13T09:58:41.674 harvester chia.plotting.util      : WARNING  Directory: C:\Users\1\AppData\Local\Programs\Chia\Volume{3f0348f9-0000-0000-0010-080000000000}\Crc9 does not exist.
2023-10-13T09:58:41.674 harvester chia.plotting.util      : WARNING  Directory: C:\Users\1\AppData\Local\Programs\Chia\Volume{f853a759-0000-0000-0000-e02c03000000}\Crl18 does not exist.
2023-10-13T09:58:41.675 harvester chia.harvester.harvester: INFO     _plot_refresh_callback: event started, loaded 0, removed 0, processed 0, remaining 1, duration: 0.00 seconds, total plots: 0
2023-10-13T09:58:41.676 harvester chia.harvester.harvester: INFO     _plot_refresh_callback: event done, loaded 1, removed 0, processed 1, remaining 0, duration: 0.00 seconds, total plots: 1
2023-10-13T09:58:41.680 full_node chia.full_node.full_node: INFO     Blockchain initialized to peak 0aace7657d47c33cf30a2f0dbd8c6dfac3b6aa4a577528291ff5cc0356e3f641 height 4362528, time taken: 0s
2023-10-13T09:58:41.682 full_node chia.full_node.full_node: INFO      Updated peak to height 4362528, weight 9196569632, hh 0aace7657d47c33cf30a2f0dbd8c6dfac3b6aa4a577528291ff5cc0356e3f641, forked at 4362527, rh: 565d8797ed1485e8444562d09969c7834d28356fd6173b698a6c1304827c2665, total iters: 18525457354704, overflow: False, deficit: 4, difficulty: 2720, sub slot iters: 147849216, Generator size: No tx, Generator ref list size: No tx

++++2023-10-13T09:58:41.579 harvester harvester_server        : INFO     Connected with farmer PeerInfo(_ip=IPv4Address('127.0.0.1'), _port=8447)
2023-10-13T09:58:41.585 harvester chia.plotting.cache     : INFO     Loaded 1151361 bytes of cached data
2023-10-13T09:58:41.639 harvester chia.plotting.cache     : INFO     Parsed 1151 cache entries in 0.05s
2023-10-13T09:58:41.668 harvester chia.plotting.util      : WARNING  Directory: C:\Users\1\AppData\Local\Programs\Chia\Volume{811bf8a4-66de-4e3f-9208-0a717f55c704}\Crc55 does not exist.
2023-10-13T09:58:41.669 harvester chia.plotting.util      : WARNING  Directory: C:\Users\1\AppData\Local\Programs\Chia\Volume{f93eb7bd-4ad1-4891-b284-6be56d0feef6}\Crc73 does not exist.
2023-10-13T09:58:41.669 harvester chia.plotting.util      : WARNING  Directory: C:\Users\1\AppData\Local\Programs\Chia\Volume{abd6e64b-65c2-4579-a434-edb068012b97}\Crc73 does not exist.
2023-10-13T09:58:41.669 harvester chia.plotting.util      : WARNING  Directory: C:\Users\1\AppData\Local\Programs\Chia\Volume{e4f2d32e-59ff-441e-9ca8-834ad8293482}\Crc73 does not exist.
2023-10-13T09:58:41.671 harvester chia.plotting.util      : WARNING  Directory: C:\Users\1\AppData\Local\Programs\Chia\Volume{3473f3ff-685b-4036-97ec-745265291ee5}\Crc73 does not exist.
2023-10-13T09:58:41.671 harvester chia.plotting.util      : WARNING  Directory: C:\Users\1\AppData\Local\Programs\Chia\Volume{14506a1c-b438-4c08-b984-4fd95c5010f1}\Crc73 does not exist.
2023-10-13T09:58:41.671 harvester chia.plotting.util      : WARNING  Directory: C:\Users\1\AppData\Local\Programs\Chia\Volume{7e74b0ce-8627-44ce-a790-6843f2e7a528}\Crc73 does not exist.
2023-10-13T09:58:41.672 harvester chia.plotting.util      : WARNING  Directory: C:\Users\1\AppData\Local\Programs\Chia\Volume{773fe227-cbde-42c2-b9ab-6e72d689a3f2}\Crc73 does not exist.
2023-10-13T09:58:41.672 harvester chia.plotting.util      : WARNING  Directory: C:\Users\1\AppData\Local\Programs\Chia\Volume{2fa887a9-8d1c-4f29-a4e4-7f6e1e9f3115}\Crc73 does not exist.
2023-10-13T09:58:41.672 harvester chia.plotting.util      : WARNING  Directory: C:\Users\1\AppData\Local\Programs\Chia\Volume{00aed128-33b3-458e-b8d5-3f9f76865d08}\Crc73 does not exist.
2023-10-13T09:58:41.673 harvester chia.plotting.util      : WARNING  Directory: C:\Users\1\AppData\Local\Programs\Chia\Volume{fb3b248d-37c0-4a48-8ed2-d493c879ac52}\Crc128 does not exist.
2023-10-13T09:58:41.673 harvester chia.plotting.util      : WARNING  Directory: C:\Users\1\AppData\Local\Programs\Chia\Volume{6bbba17b-1af5-463e-b872-984f59c8c0b4}\Crc128 does not exist.
2023-10-13T09:58:41.674 harvester chia.plotting.util      : WARNING  Directory: C:\Users\1\AppData\Local\Programs\Chia\Volume{9d664ec5-b25a-450f-a22a-e5b44dfa747f}\Crc73 does not exist.
2023-10-13T09:58:41.674 harvester chia.plotting.util      : WARNING  Directory: C:\Users\1\AppData\Local\Programs\Chia\Volume{3f0348f9-0000-0000-0010-080000000000}\Crc9 does not exist.
2023-10-13T09:58:41.674 harvester chia.plotting.util      : WARNING  Directory: C:\Users\1\AppData\Local\Programs\Chia\Volume{f853a759-0000-0000-0000-e02c03000000}\Crl18 does not exist.
2023-10-13T09:58:41.675 harvester chia.harvester.harvester: INFO     _plot_refresh_callback: event started, loaded 0, removed 0, processed 0, remaining 1, duration: 0.00 seconds, total plots: 0
2023-10-13T09:58:41.676 harvester chia.harvester.harvester: INFO     _plot_refresh_callback: event done, loaded 1, removed 0, processed 1, remaining 0, duration: 0.00 seconds, total plots: 1
2023-10-13T09:58:41.680 full_node chia.full_node.full_node: INFO     Blockchain initialized to peak 0aace7657d47c33cf30a2f0dbd8c6dfac3b6aa4a577528291ff5cc0356e3f641 height 4362528, time taken: 0s
2023-10-13T09:58:41.682 full_node chia.full_node.full_node: INFO      Updated peak to height 4362528, weight 9196569632, hh 0aace7657d47c33cf30a2f0dbd8c6dfac3b6aa4a577528291ff5cc0356e3f641, forked at 4362527, rh: 565d8797ed1485e8444562d09969c7834d28356fd6173b698a6c1304827c2665, total iters: 18525457354704, overflow: False, deficit: 4, difficulty: 2720, sub slot iters: 147849216, Generator size: No tx, Generator ref list size: No tx
++++++++++ debug.log 
2023-10-13T11:46:57.698 harvester chia.rpc.rpc_server     : WARNING  Error while handling message: Traceback (most recent call last):
  File "chia\rpc\rpc_server.py", line 340, in safe_handle
  File "chia\rpc\rpc_server.py", line 331, in ws_api
  File "chia\rpc\harvester_rpc_api.py", line 71, in add_plot_directory
  File "chia\harvester\harvester.py", line 213, in add_plot_directory
  File "chia\plotting\util.py", line 126, in add_plot_directory
ValueError: Path doesn't exist: Volume{3f0348f9-0000-0000-0010-080000000000}\Crc9
+++++++++++++++++++++++++++++++config.yaml++++++++++++++
 plot_directories:
  - X:\BF\PL_W3
  - X:\CH\PL\D6T1\Crc55
  - X:\CH\PL\D6T2\Crc55
  - X:\CH\PL\D8T1E\Crc73
  - X:\CH\PL\D8T2\Crc73
  - X:\CH\PL\D8T3\Crc73
  - X:\CH\PL\D8T4\Crc73
  - X:\CH\PL\D8T5\Crc73
  - X:\CH\PL\D8T6\Crc73
  - X:\CH\PL\D8T7\Crc73
  - X:\CH\PL\D8T8E\Crc73
  - X:\CH\PL\D8T9E\Crc73
  - X:\CH\PL\D8T10\Crc73
  - X:\CH\PL\D14T1\Crc128
  - X:\CH\PL\D14T2\Crc128
  - E:\Crl18
  - D:\Crc9
```

**Comment by wjblanke** [comment]
If you run an older version do these issues stop happening? I'm trying to see if there is a regression in 2.1.0. What was the older version u ran?

**Comment by LudmilaAlex** [comment]
В моем случае проблему решил следующим образом. В моей сети Windows помимо дисков с плотами CHIA имеется 3 диска SSD (SamsungSSD980PRO1TB, SamsungSSD970PRO1TB, KINGSTONSA400S37240G), на разделах которых имеется несколько OS Windows 64: Win11,Win10, Win7, WinXP и  WinPE(ROM-RAMDISK) и даже экспериментальный WinPE(RAM!) с функциями обычного WinPE(ROM-RAMDISK), но работает как обычная Windows (т.е. работает на физическом диске,  и сохраняет в реестре параметры сеанса) .

1-м SSD основной. Он  имеет два активных раздела:
 ESP (part0) – основной рабочий
Win10PEEG1 21_03 (part2) -Recovery (экспериментальный WinPE(RAM!)
![image](https://github.com/Chia-Network/chia-blockchain/assets/97796236/a70ff7bf-9aa3-4cd7-a96b-fdaa72c3c16a)

2-й и 3-й SSD  используется для различных OS как физические диски  в на виртуальных машинах.
2-й диск также имеет два аналогичных активных раздела:
ESP (part0) – основной рабочий
Win10PEEG1 21_03_D1T2SSD - (part2) -Recovery (экспериментальный WinPE(RAM!)
![image](https://github.com/Chia-Network/chia-blockchain/assets/97796236/3ae08434-7b33-46ee-8455-965cc65ab09a)

3-й SSD диск c MBR стилем разделов - KINGSTONSA400S37240G.
part0 или part1 может быть настроен как активный для загрузки как старых так и новых OS 
6Win10PEEXG1_D025T1SSD (part 6) - Recovery (экспериментальный WinPE(RAM!)
![image](https://github.com/Chia-Network/chia-blockchain/assets/97796236/4a71d1a2-d41e-4223-9339-03d08106e3ed)

### Проблема с видимостью плотов оказалась связана с тем, как в системе настроен Boot entry для второго диск SSD!

![image](https://github.com/Chia-Network/chia-blockchain/assets/97796236/4f99c72b-bafe-4574-95ae-0127b1780e59)
