### ISSUE TITLE
[Bug] Failed to validate block batch

### ISSUE THREAD

**Issue by bwccnft** [Chia-Network/chia-blockchain#16630]
### What happened?

Failed to validate block batch 4371738 to 4371770. Full_node crashed this morning.

### Version

2.0.1

### What platform are you using?

Linux

### What ui mode are you using?

CLI

### Relevant log output

```shell
2023-10-15T22:42:15.486 full_node chia.full_node.full_node: ERROR    sync from fork point failed: ValueError: Failed to validate block batch 4371738 to 4371770
Traceback (most recent call last):
  File "chia/util/log_exceptions.py", line 20, in log_exceptions
    yield
  File "chia/full_node/full_node.py", line 1129, in sync_from_fork_point
    await asyncio.gather(fetch_task, validate_task)
  File "chia/full_node/full_node.py", line 1107, in validate_block_batches
    raise ValueError(f"Failed to validate block batch {start_height} to {end_height}")
ValueError: Failed to validate block batch 4371738 to 4371770
```

**Comment by wjblanke** [comment]
Can u send us the full log, especially concerning the crash
