### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Julio174** [Chia-Network/chia-blockchain#1666]
**Describe the bug**
I have 26.5 TiB, I have been growing on windows 10 and for 5 days no win. Is it normal? I attach a screenshot and a log.
Log:
14:16:45.091 wallet src.wallet.wallet_state_manager: WARNING  Starting in db path: C:\Users\user\.chia\mainnet\wallet\db\blockchain_wallet_v1_mainnet_finger_print.sqlite
14:17:03.606 wallet wallet_server              : ERROR    Exception , exception Stack: Traceback (most recent call last):
  File "src\server\server.py", line 353, in start_client
  File "aiohttp\client.py", line 763, in _ws_connect
  File "aiohttp\client.py", line 521, in _request
  File "aiohttp\connector.py", line 535, in connect
  File "aiohttp\connector.py", line 892, in _create_connection
  File "aiohttp\connector.py", line 1032, in _create_direct_connection
  File "aiohttp\connector.py", line 969, in _wrap_create_connection
  File "asyncio\base_events.py", line 989, in create_connection
  File "asyncio\base_events.py", line 1017, in _create_connection_transport
concurrent.futures._base.CancelledError

14:17:03.637 wallet src.wallet.wallet_state_manager: WARNING  Starting in db path: C:\Users\user\.chia\mainnet\wallet\db\blockchain_wallet_v1_mainnet_finger_print.sqlite

Thank you in advance for your help

**Expected behavior**

**Screenshots**
![Przechwytywanie](https://user-images.githubusercontent.com/81868938/113483589-857c5f00-94a4-11eb-992b-0ea1d0677bea.JPG)
![Przechwytywanie2](https://user-images.githubusercontent.com/81868938/113483805-91b4ec00-94a5-11eb-8843-56a4390f747b.JPG)

**Desktop (please complete the following information):**

**Comment by hoffmang9** [comment]
If you have attempts in Last Attempted Proof and they are current and about every 10 seconds you are farming. Luck plays a major part.
