### ISSUE TITLE
2.1.0-cli can not start farm on ubuntu 20.04

### ISSUE THREAD

**Issue by HomeLH** [Chia-Network/chia-blockchain#16666]
OS: ubuntu 20.04
version:   chia-blockchain-cli_2.1.0-1_amd64.deb
error:
```
$ chia start farmer
chia_harvester: chia_harvester failed to start. Error: start failed
chia_farmer: chia_farmer failed to start. Error: start failed
chia_full_node: chia_full_node failed to start. Error: start failed
chia_wallet: chia_wallet failed to start. Error: start failed
```
debug_log:
```

2023-10-20T22:56:02.972 daemon chia.daemon.server         : ERROR    problem starting chia_harvester
Traceback (most recent call last):
  File "chia/daemon/server.py", line 1157, in start_service
  File "chia/daemon/server.py", line 1332, in launch_service
  File "subprocess.py", line 858, in __init__
  File "subprocess.py", line 1704, in _execute_child
FileNotFoundError: [Errno 2] No such file or directory: '/opt/chia/resources/app.asar.unpacked/daemon/start_harvester'
2023-10-20T22:56:02.996 daemon chia.daemon.server         : ERROR    problem starting chia_farmer
Traceback (most recent call last):
  File "chia/daemon/server.py", line 1157, in start_service
  File "chia/daemon/server.py", line 1332, in launch_service
  File "subprocess.py", line 858, in __init__
  File "subprocess.py", line 1704, in _execute_child
FileNotFoundError: [Errno 2] No such file or directory: '/opt/chia/resources/app.asar.unpacked/daemon/start_farmer'
2023-10-20T22:56:03.019 daemon chia.daemon.server         : ERROR    problem starting chia_full_node
Traceback (most recent call last):
  File "chia/daemon/server.py", line 1157, in start_service
  File "chia/daemon/server.py", line 1332, in launch_service
  File "subprocess.py", line 858, in __init__
  File "subprocess.py", line 1704, in _execute_child
FileNotFoundError: [Errno 2] No such file or directory: '/opt/chia/resources/app.asar.unpacked/daemon/start_full_node'
2023-10-20T22:56:03.045 daemon chia.daemon.server         : ERROR    problem starting chia_wallet
Traceback (most recent call last):
  File "chia/daemon/server.py", line 1157, in start_service
  File "chia/daemon/server.py", line 1332, in launch_service
  File "subprocess.py", line 858, in __init__
  File "subprocess.py", line 1704, in _execute_child
FileNotFoundError: [Errno 2] No such file or directory: '/opt/chia/resources/app.asar.unpacked/daemon/start_wallet'
2023-10-20T22:56:03.055 daemon chia.daemon.server         : INFO     ConnectionClosed. Closing websocket with Unknown
```

**Comment by HomeLH** [comment]
I use `apt purge chia..` to remove it, then reinstall it with `dpkg -I chia...deb`. The error shows again.

**Comment by wjblanke** [comment]
can u provide the logging output? it may be best to uninstall all versions of chia and make sure nothing is in /opt/chia or any chia code on your system like in usr/bin, usr/local/bin. then install the latest version. possibly there are some version mismatches going on. another more drastic test would be to run this on a fresh system.

**Comment by wjblanke** [comment]
closing please reopen if u continue to have issues. we think it is a system related issue.
