### ISSUE TITLE
[Bug] full node not synced on version 2.1.1

### ISSUE THREAD

**Issue by xingzi178** [Chia-Network/chia-blockchain#16730]
### What happened?

I have upgraded to version 2.1.1 and since this morning full node keeps showing not synced, but actually it is keeping syncing as I can see new blocks keep coming in the list and the last transaction block time is also update to date.
can someone please guide me what can I do now?

![Screenshot from 2023-10-29 10-37-40](https://github.com/Chia-Network/chia-blockchain/assets/3358070/ec717883-f3ea-4a5a-9819-ae074cfee5ff)

### Version

2.1.1

### What platform are you using?

Linux

### What ui mode are you using?

GUI

**Comment by xingzi178** [comment]
db is already v2 version. tried with command chia db upgrade and it shows error that the output file is same as input

**Comment by xingzi178** [comment]
see following errors in the log, are they relevant?

2023-09-29T19:31:07.543 full_node full_node_server        : ERROR    Exception: Error code: TIMESTAMP_TOO_FAR_IN_FUTURE [], PeerInfo(_ip=IPv4Address('218.0.105.42'), _port=8444). Traceback (most recent call last):
  File "chia/server/ws_connection.py", line 393, in wrapped_coroutine
  File "chia/full_node/full_node_api.py", line 469, in respond_unfinished_block
  File "chia/full_node/full_node.py", line 1858, in add_unfinished_block
chia.util.errors.ConsensusError: Error code: TIMESTAMP_TOO_FAR_IN_FUTURE []

2023-09-29T19:31:07.547 full_node full_node_server        : ERROR    Exception: Error code: TIMESTAMP_TOO_FAR_IN_FUTURE [] <class 'chia.util.errors.ConsensusError'>, closing connection PeerInfo(_ip=IPv4Address('218.0.105.42'), _port=8444). Traceback (most recent call last):
  File "chia/server/ws_connection.py", line 403, in _api_call
  File "asyncio/tasks.py", line 494, in wait_for
  File "chia/server/ws_connection.py", line 393, in wrapped_coroutine
  File "chia/full_node/full_node_api.py", line 469, in respond_unfinished_block
  File "chia/full_node/full_node.py", line 1858, in add_unfinished_block
chia.util.errors.ConsensusError: Error code: TIMESTAMP_TOO_FAR_IN_FUTURE []

**Comment by xingzi178** [comment]
sorry, the root cause is found, the timezone of my server which CHIA runs somehow did not get an automatic update since this morning Germany switches the summer time to winter time. after manually update the server time the issue is now solved.
