### ISSUE TITLE
[Bug] Assertion failed while syncing from scratch and stuck at height 1802252/4446102

### ISSUE THREAD

**Issue by mehditlili** [Chia-Network/chia-blockchain#16734]
### What happened?

On Ubuntu 22.04, installed chia via apt install and started the node in order to sync from scratch.

`chia start node`

Syncing has reached height of `1802252/4446102` then got stuck there. I am syncing on an i5 13400 so CPU here is definitely not the problem.

When I checked the logs with 
`tail -F ~/.chia/mainnet/log/debug.log`

I get

```
2023-10-30T10:57:39.063 full_node chia.full_node.full_node: ERROR    sync from fork point failed: AssertionError: 
Traceback (most recent call last):
  File "chia/util/log_exceptions.py", line 20, in log_exceptions
  File "chia/full_node/full_node.py", line 1129, in sync_from_fork_point
  File "chia/full_node/full_node.py", line 1098, in validate_block_batches
  File "chia/full_node/full_node.py", line 1209, in add_block_batch
  File "chia/consensus/blockchain.py", line 651, in pre_validate_blocks_multiprocessing
  File "chia/consensus/multiprocess_validation.py", line 316, in pre_validate_blocks_multiprocessing
  File "chia/consensus/blockchain.py", line 927, in get_block_generator
AssertionError
```

Validating the db

```
root@chia:~# chia db validate
opening file for reading: /root/.chia/mainnet/db/blockchain_v2_mainnet.sqlite
peak hash: d7eb4418aea9417b1e53a00d87592f6bee9a12a065e6e67beca199abf4cec230
peak height: 1802252
traversing the full chain
0 orphaned blocks: 0       


DATABASE IS VALID: /root/.chia/mainnet/db/blockchain_v2_mainnet.sqlite
```

Not sure what the problem is here

### Version

2.1.1

### What platform are you using?

Linux

### What ui mode are you using?

CLI

**Comment by mehditlili** [comment]
Seems I have Disk IO errors on my system. So it is probably that.
