### ISSUE TITLE
[Bug] config.yaml is broken on pc restart

### ISSUE THREAD

**Issue by dEMonaRE** [Chia-Network/chia-blockchain#16770]
### What happened?

Config file content was deleted when the pc was turned on again after a power outage
I also tried to reinstall but the file was gone.
Is there a backup config file? 
![image](https://github.com/Chia-Network/chia-blockchain/assets/4335569/e6a45c83-ce13-43ca-a678-9abd348a9559)

### Version

2.1.1

### What platform are you using?

Windows

### What ui mode are you using?

GUI

### Relevant log output

```shell
C:\Windows\system32> chia configure -log-level DEBUG
Error loading file: Traceback (most recent call last):
  File "chia\util\config.py", line 135, in _load_config_maybe_locked
  File "yaml\__init__.py", line 125, in safe_load
  File "yaml\__init__.py", line 79, in load
  File "yaml\loader.py", line 34, in __init__
  File "yaml\reader.py", line 85, in __init__
  File "yaml\reader.py", line 135, in determine_encoding
  File "yaml\reader.py", line 169, in update
  File "yaml\reader.py", line 143, in check_printable
yaml.reader.ReaderError: unacceptable character #x0000: special characters are not allowed
  in "C:\Users\rog\.chia\mainnet\config\config.yaml", position 0
 unacceptable character #x0000: special characters are not allowed
  in "C:\Users\rog\.chia\mainnet\config\config.yaml", position 0 Retrying 0
Error loading file: Traceback (most recent call last):
  File "chia\util\config.py", line 135, in _load_config_maybe_locked
  File "yaml\__init__.py", line 125, in safe_load
  File "yaml\__init__.py", line 79, in load
  File "yaml\loader.py", line 34, in __init__
  File "yaml\reader.py", line 85, in __init__
  File "yaml\reader.py", line 135, in determine_encoding
  File "yaml\reader.py", line 169, in update
  File "yaml\reader.py", line 143, in check_printable
yaml.reader.ReaderError: unacceptable character #x0000: special characters are not allowed
  in "C:\Users\rog\.chia\mainnet\config\config.yaml", position 0
 unacceptable character #x0000: special characters are not allowed
  in "C:\Users\rog\.chia\mainnet\config\config.yaml", position 0 Retrying 1
Error loading file: Traceback (most recent call last):
  File "chia\util\config.py", line 135, in _load_config_maybe_locked
  File "yaml\__init__.py", line 125, in safe_load
  File "yaml\__init__.py", line 79, in load
  File "yaml\loader.py", line 34, in __init__
  File "yaml\reader.py", line 85, in __init__
  File "yaml\reader.py", line 135, in determine_encoding
  File "yaml\reader.py", line 169, in update
  File "yaml\reader.py", line 143, in check_printable
yaml.reader.ReaderError: unacceptable character #x0000: special characters are not allowed
  in "C:\Users\rog\.chia\mainnet\config\config.yaml", position 0
 unacceptable character #x0000: special characters are not allowed
  in "C:\Users\rog\.chia\mainnet\config\config.yaml", position 0 Retrying 2
Error loading file: Traceback (most recent call last):
  File "chia\util\config.py", line 135, in _load_config_maybe_locked
  File "yaml\__init__.py", line 125, in safe_load
  File "yaml\__init__.py", line 79, in load
  File "yaml\loader.py", line 34, in __init__
  File "yaml\reader.py", line 85, in __init__
  File "yaml\reader.py", line 135, in determine_encoding
  File "yaml\reader.py", line 169, in update
  File "yaml\reader.py", line 143, in check_printable
yaml.reader.ReaderError: unacceptable character #x0000: special characters are not allowed
  in "C:\Users\rog\.chia\mainnet\config\config.yaml", position 0
 unacceptable character #x0000: special characters are not allowed
  in "C:\Users\rog\.chia\mainnet\config\config.yaml", position 0 Retrying 3
Error loading file: Traceback (most recent call last):
  File "chia\util\config.py", line 135, in _load_config_maybe_locked
  File "yaml\__init__.py", line 125, in safe_load
  File "yaml\__init__.py", line 79, in load
  File "yaml\loader.py", line 34, in __init__
  File "yaml\reader.py", line 85, in __init__
  File "yaml\reader.py", line 135, in determine_encoding
  File "yaml\reader.py", line 169, in update
  File "yaml\reader.py", line 143, in check_printable
yaml.reader.ReaderError: unacceptable character #x0000: special characters are not allowed
  in "C:\Users\rog\.chia\mainnet\config\config.yaml", position 0
 unacceptable character #x0000: special characters are not allowed
  in "C:\Users\rog\.chia\mainnet\config\config.yaml", position 0 Retrying 4
Error loading file: Traceback (most recent call last):
  File "chia\util\config.py", line 135, in _load_config_maybe_locked
  File "yaml\__init__.py", line 125, in safe_load
  File "yaml\__init__.py", line 79, in load
  File "yaml\loader.py", line 34, in __init__
  File "yaml\reader.py", line 85, in __init__
  File "yaml\reader.py", line 135, in determine_encoding
  File "yaml\reader.py", line 169, in update
  File "yaml\reader.py", line 143, in check_printable
yaml.reader.ReaderError: unacceptable character #x0000: special characters are not allowed
  in "C:\Users\rog\.chia\mainnet\config\config.yaml", position 0
 unacceptable character #x0000: special characters are not allowed
  in "C:\Users\rog\.chia\mainnet\config\config.yaml", position 0 Retrying 5
Error loading file: Traceback (most recent call last):
  File "chia\util\config.py", line 135, in _load_config_maybe_locked
  File "yaml\__init__.py", line 125, in safe_load
  File "yaml\__init__.py", line 79, in load
  File "yaml\loader.py", line 34, in __init__
  File "yaml\reader.py", line 85, in __init__
  File "yaml\reader.py", line 135, in determine_encoding
  File "yaml\reader.py", line 169, in update
  File "yaml\reader.py", line 143, in check_printable
yaml.reader.ReaderError: unacceptable character #x0000: special characters are not allowed
  in "C:\Users\rog\.chia\mainnet\config\config.yaml", position 0
 unacceptable character #x0000: special characters are not allowed
  in "C:\Users\rog\.chia\mainnet\config\config.yaml", position 0 Retrying 6
Error loading file: Traceback (most recent call last):
  File "chia\util\config.py", line 135, in _load_config_maybe_locked
  File "yaml\__init__.py", line 125, in safe_load
  File "yaml\__init__.py", line 79, in load
  File "yaml\loader.py", line 34, in __init__
  File "yaml\reader.py", line 85, in __init__
  File "yaml\reader.py", line 135, in determine_encoding
  File "yaml\reader.py", line 169, in update
  File "yaml\reader.py", line 143, in check_printable
yaml.reader.ReaderError: unacceptable character #x0000: special characters are not allowed
  in "C:\Users\rog\.chia\mainnet\config\config.yaml", position 0
 unacceptable character #x0000: special characters are not allowed
  in "C:\Users\rog\.chia\mainnet\config\config.yaml", position 0 Retrying 7
Error loading file: Traceback (most recent call last):
  File "chia\util\config.py", line 135, in _load_config_maybe_locked
  File "yaml\__init__.py", line 125, in safe_load
  File "yaml\__init__.py", line 79, in load
  File "yaml\loader.py", line 34, in __init__
  File "yaml\reader.py", line 85, in __init__
  File "yaml\reader.py", line 135, in determine_encoding
  File "yaml\reader.py", line 169, in update
  File "yaml\reader.py", line 143, in check_printable
yaml.reader.ReaderError: unacceptable character #x0000: special characters are not allowed
  in "C:\Users\rog\.chia\mainnet\config\config.yaml", position 0
 unacceptable character #x0000: special characters are not allowed
  in "C:\Users\rog\.chia\mainnet\config\config.yaml", position 0 Retrying 8
Error loading file: Traceback (most recent call last):
  File "chia\util\config.py", line 135, in _load_config_maybe_locked
  File "yaml\__init__.py", line 125, in safe_load
  File "yaml\__init__.py", line 79, in load
  File "yaml\loader.py", line 34, in __init__
  File "yaml\reader.py", line 85, in __init__
  File "yaml\reader.py", line 135, in determine_encoding
  File "yaml\reader.py", line 169, in update
  File "yaml\reader.py", line 143, in check_printable
yaml.reader.ReaderError: unacceptable character #x0000: special characters are not allowed
  in "C:\Users\rog\.chia\mainnet\config\config.yaml", position 0
 unacceptable character #x0000: special characters are not allowed
  in "C:\Users\rog\.chia\mainnet\config\config.yaml", position 0 Retrying 9
Traceback (most recent call last):
  File "chia\cmds\chia.py", line 139, in <module>
  File "chia\cmds\chia.py", line 135, in main
  File "click\core.py", line 1130, in __call__
  File "click\core.py", line 1055, in main
  File "click\core.py", line 1657, in invoke
  File "click\core.py", line 1404, in invoke
  File "click\core.py", line 760, in invoke
  File "click\decorators.py", line 26, in new_func
  File "chia\cmds\configure.py", line 288, in configure_cmd
  File "chia\cmds\configure.py", line 29, in configure
  File "contextlib.py", line 135, in __enter__
  File "chia\util\config.py", line 70, in lock_and_load_config
  File "chia\util\config.py", line 149, in _load_config_maybe_locked
RuntimeError: Was not able to read config file successfully
[11540] Failed to execute script 'chia' due to unhandled exception!
C:\Windows\system32>
```

**Comment by dEMonaRE** [comment]
delete config.yaml and restart gui
