### ISSUE TITLE
Cannot start farmer on Ubuntu 18.04

### ISSUE THREAD

**Issue by davidbarratt** [Chia-Network/chia-blockchain#168]
I'm trying to start the farmer, but I get the following error:
```
(venv) david@monster:~/chia-blockchain$ chia-start-farmer
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/david/chia-blockchain/src/server/start_full_node.py", line 6, in <module>
    import aiosqlite
ModuleNotFoundError: No module named 'aiosqlite'
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/david/chia-blockchain/src/server/start_harvester.py", line 10, in <module>
    from src.harvester import Harvester
  File "/home/david/chia-blockchain/src/harvester.py", line 6, in <module>
    from blspy import PrependSignature, PrivateKey, PublicKey, Util
ModuleNotFoundError: No module named 'blspy'
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/david/chia-blockchain/src/server/start_farmer.py", line 10, in <module>
    from src.farmer import Farmer
  File "/home/david/chia-blockchain/src/farmer.py", line 5, in <module>
    from blspy import PrivateKey, Util
ModuleNotFoundError: No module named 'blspy'
```

Tried to install it manually, but no dice:
```
(venv) david@monster:~/chia-blockchain$ pip install aiosqlite
Requirement already satisfied: aiosqlite in ./venv/lib/python3.7/site-packages (0.11.0)
```

**Comment by mariano54** [comment]
You need to be running python 3.7, not 3.6.

**Comment by davidbarratt** [comment]
I tried uninstall python3.6, but the install script reinstalled it. :(

**Comment by mariano54** [comment]
Has this been fixed? Make sure to check the instructions which show how to install python3.7 on the various platforms.

**Comment by davidbarratt** [comment]
Has anything been changed that would have fixed it?

Again, as I mentioned previously, the script re-installs python3.6

**Comment by hoffmang9** [comment]
Brand new install of Ubuntu 18.04LTS on ec2.

When I start it python3 gives me Python 3.6.9.

Following the install instructions, I do:
```
sudo apt-get update
sudo apt-get install python3.7-venv python3.7-distutils git -y
```
Running `python3` still gives me 3.6.9.

However  install.sh looks for python37 and then python3.7. python37 fails, but python3.7 works perfectly to give me Python 3.7.5.

The install.sh script only installs npm and it only does that after it finds python3.7. Did you run the initial steps in the install instructions? What do you get when you type `python3.7`?
