### ISSUE TITLE
[Bug] After upgrading to 2.1.1, the log reported an error

### ISSUE THREAD

**Issue by coinbase-op** [Chia-Network/chia-blockchain#16854]
### What happened?

After upgrading to 2.1.1, the log reported an error

Dockerfile
------------------------
```
FROM ubuntu:20.04

ARG VERSION=1.1.2

# install dependencies
RUN apt-get update \    && apt-get upgrade -y \
    && apt-get install python3 sudo net-tools git curl -y \
    && DEBIAN_FRONTEND=noninteractive apt-get install -y lsb-core

# install chia
RUN cd $HOME \
    && git clone https://github.com/Chia-Network/chia-blockchain.git -b latest \
    && cd chia-blockchain \
    && git checkout ${VERSION} \
    && sh install.sh

ADD Entrypoint.sh /Entrypoint
RUN chmod +x /Entrypoint
HEALTHCHECK CMD netstat -tlnp |grep 8555 || exit 1

EXPOSE 8555 9256

ENTRYPOINT ["/Entrypoint"]
```

--------------------------
Entrypoint.sh

```
#!/bin/bash

cd ~/chia-blockchain
. ./activate
if [ ! -d ~/.chia/mainnet/config ];then
    chia init
    sed -i 's/localhost/0.0.0.0/g' ~/.chia/mainnet/config/config.yaml
    sed -i 's/127.0.0.1/0.0.0.0/g' ~/.chia/mainnet/config/config.yaml
    #sed -i 's/host: introducer.chia.net/host: introducer-apse.chia.net/g' ~/.chia/mainnet/config/config.yaml
    #chia keys generate
fi
chia start farmer
```

--------------------
```
#!/bin/bash

VERSION=2.1.1

docker build --build-arg VERSION=$VERSION -t xch:$VERSION .
docker stop xch
docker rm xch
docker run --init -d --restart=always --name xch -m 96G -p 8555:8555 -p 9256:9256 -v /data2/xch:/root/.chia xch:$VERSION


```

### Version

2.1.1

### What platform are you using?

Linux

### What ui mode are you using?

CLI

### Relevant log output

```shell
2023-11-17T10:36:22.347 wallet chia.wallet.wallet_node : WARNING Peer PeerInfo(_ip=IPv4Address('89.150.128.56'), _port=8444) did not respond in time.
2023-11-17T10:36:22.348 wallet wallet_server : WARNING Banning 89.150.128.56 for 120 seconds
2023-11-17T10:36:22.730 wallet chia.wallet.wallet_node: WARNING Peer None did not respond in time.
2023-11-17T10:36:22.730 wallet wallet_server : WARNING Banning 90.195.47.242 for 120 seconds
2023-11-17T10:36:28.515 wallet chia.wallet.wallet_state_manager: ERROR Failed to add coin_state: CoinState { coin: Coin { parent_coin_info: ee1c305efe3f604c9ebabd04f8c8994e53fea0d4e4b5591030ccf8cc13124 e7a, puzzle_hash: 53a7623c0a82ba7286478e2aab0cc09e76b2b58fe36eaebdb21cebb886d797f4, amount: 59000000000 }, spent_height: Some(3501255), created_height: Some(2994365) }, error: Error fetching timestamp from all peers
Traceback (most recent call last):
   File "/root/chia-blockchain/chia/wallet/wallet_state_manager.py", line 1543, in _add_coin_states
     created_timestamp = await self.wallet_node.get_timestamp_for_height(
   File "/root/chia-blockchain/chia/wallet/wallet_node.py", line 1041, in get_timestamp_for_height
     raise PeerRequestException("Error fetching timestamp from all peers")
chia.wallet.util.wallet_sync_utils.PeerRequestException: Error fetching timestamp from all peers
2023-11-17T10:36:28.522 wallet chia.wallet.wallet_node: WARNING Peer None did not respond in time.
2023-11-17T10:36:28.523 wallet wallet_server : WARNING Trying to ban localhost for 120, but will not ban
2023-11-17T10:36:28.524 wallet chia.wallet.wallet_node: WARNING Peer None did not respond in time.
2023-11-17T10:36:28.524 wallet wallet_server : WARNING Banning 79.117.9.110 for 120 seconds
2023-11-17T10:36:34.362 wallet chia.wallet.wallet_state_manager: ERROR Failed to add coin_state: CoinState { coin: Coin { parent_coin_info: 0bb8a4e134540e7a0d610cbf5e1f2568d98fba478ca0abad77e3af6c7b7ed7 bc, puzzle_hash: 111ab99fc06ad626bc7b4260ec41d6342a5814c579bbfa30bdb4711e8b02fdc7, amount: 1500000000000 }, spent_height: Some(3033742), created_height: Some(3032764) }, error: Error fetching timestamp from all peers
Traceback (most recent call last):
   File "/root/chia-blockchain/chia/wallet/wallet_state_manager.py", line 1543, in _add_coin_states
     created_timestamp = await self.wallet_node.get_timestamp_for_height(
   File "/root/chia-blockchain/chia/wallet/wallet_node.py", line 1041, in get_timestamp_for_height
     raise PeerRequestException("Error fetching timestamp from all peers")
chia.wallet.util.wallet_sync_utils.PeerRequestException: Error fetching timestamp from all peers
2023-11-17T10:36:37.393 wallet chia.wallet.wallet_state_manager: ERROR Failed to add coin_state: CoinState { coin: Coin { parent_coin_info: 0bb8a4e134540e7a0d610cbf5e1f2568d98fba478ca0abad77e3af6c7b7ed7 bc, puzzle_hash: 111ab99fc06ad626bc7b4260ec41d6342a5814c579bbfa30bdb4711e8b02fdc7, amount: 1500000000000 }, spent_height: Some(3033742), created_height: Some(3032764) }, error: Error fetching timestamp from all peers
Traceback (most recent call last):
   File "/root/chia-blockchain/chia/wallet/wallet_state_manager.py", line 1543, in _add_coin_states
     created_timestamp = await self.wallet_node.get_timestamp_for_height(
   File "/root/chia-blockchain/chia/wallet/wallet_node.py", line 1041, in get_timestamp_for_height
     raise PeerRequestException("Error fetching timestamp from all peers")
chia.wallet.util.wallet_sync_utils.PeerRequestException: Error fetching timestamp from all peers
2023-11-17T10:36:37.424 wallet chia.wallet.wallet_node: WARNING Peer None did not respond in time.
2023-11-17T10:36:37.425 wallet wallet_server : WARNING Banning 59.57.160.60 for 120 seconds
2023-11-17T10:36:37.425 wallet chia.wallet.wallet_node: WARNING Peer None did not respond in time.
2023-11-17T10:36:37.425 wallet wallet_server : WARNING Trying to ban localhost for 120, but will not ban
2023-11-17T10:36:40.385 wallet chia.wallet.wallet_state_manager: ERROR Failed to add coin_state: CoinState { coin: Coin { parent_coin_info: cf1600c15af567b8436222de984a306ecc816f3355a19712aad2baee9fadf3 e2, puzzle_hash: 53a7623c0a82ba7286478e2aab0cc09e76b2b58fe36eaebdb21cebb886d797f4, amount: 72000000000 }, spent_height: Some(3504847), created_height: Some(2988481) }, error: Error fetching timestamp from all peers
Traceback (most recent call last):
   File "/root/chia-blockchain/chia/wallet/wallet_state_manager.py", line 1606, in _add_coin_states
     spent_timestamp = await self.wallet_node.get_timestamp_for_height(
   File "/root/chia-blockchain/chia/wallet/wallet_node.py", line 1041, in get_timestamp_for_height
     raise PeerRequestException("Error fetching timestamp from all peers")
chia.wallet.util.wallet_sync_utils.PeerRequestException: Error fetching timestamp from all peers
2023-11-17T10:36:43.395 wallet chia.wallet.wallet_state_man
```

**Comment by wjblanke** [comment]
It may be due to a bad peer. do u always get this in your logs even after rebooting and rerunning?
