### ISSUE TITLE
[Bug] An offer with no requested assets is accepted but stays in PENDING_CONFIRM

### ISSUE THREAD

**Issue by ctrlaltdel** [Chia-Network/chia-blockchain#16871]
### What happened?

An offer which is offering 0.1 TXCH and doesn't request any assets is accepted, the transaction goes through but its status is stuck in PENDING_CONFIRM.

The following error is raised.

```
2023-11-18T17:27:01.422 wallet chia.wallet.wallet_state_manager: ERROR    Failed to add coin_state: CoinState { coin: Coin { parent_coin_info: 428f363d5689d76e4ecc82af0411399a9421b0120f8c031c541326cb2246c4c8, puzzle_hash: 32a7dfa0dd9148edbc82b2e6c412a4effac2ea24f94d47996f6028a15017e2c4, amount: 1000000000000 }, spent_height: Some(3488632), created_height: Some(3482714) }, error: list index out of range
Traceback (most recent call last):
  File "/home/ubuntu/venv/lib/python3.11/site-packages/chia/wallet/wallet_state_manager.py", line 1453, in _add_coin_states
    await self.trade_manager.coins_of_interest_farmed(coin_state, fork_height, peer)
  File "/home/ubuntu/venv/lib/python3.11/site-packages/chia/wallet/trade_manager.py", line 167, in coins_of_interest_farmed
    height = coin_states[0].created_height
             ~~~~~~~~~~~^^^
IndexError: list index out of range
```

### Version

2.1.1

### What platform are you using?

Linux

### What ui mode are you using?

CLI

### Relevant log output

```shell
The following offer was created offering 0.1 TXCH and not requesting any assets.


offer1qqr83wcuu2rykcmqvps8f63hkvx7h0y7uam6v6fa3wswttpf3gdcf7rmnpj59px4fc4mj8fevx60el5zhvfnmhhwd8d0fmyg6zf000cwh4f0n60t8cen7strvxq03gergqe4uhze9tqqqma8pmmnjm4scyd6d0q33ptt3dlrtjkrdcajs4aa2deatx0ld677mvykuw7t3segchee7fk9h6fykez0alv2mtjq04wwvlxw0qa4sgxlc8l6hujntzfprryrrl4lur70u7m0vd7pdhdnuhl24v8nknmlvy3t60ve083dajur3elel5lc49ullah3taeg00qsq5wuj66vl7n8k8ll5rcmklzt0h6w0jjkwtlyyzh4dxn4erc0al3lfmveel7mrqh0d6rfsp2dhlzlcqna7vzagwe08hr0uahe0uexahur2hdsun3ca03h4vhzsvt3yemzh65qsdk7v8ffyvmm00rlmlzr0z3s3dtcf84lyw36n4mvm8ll9yuywrnfyw4flul70h0wjve94cmau4ypmc6068khcy02w0mxke8mnek0h6nvjef0fs7tdhffdpe8gwmnahm0zgnalwdxdlusmzmhtsrka6mvn6utluyca3x3xq96pd9uuhpavmw
```

It was accepted with `chia wallet take_offer` but stays in PENDING_CONFIRM.

```
$ chia wallet get_offers --id aae608b543d063008a7066c61677cffbdefe26164c7565e042e0f5368dd10638 -f 2010328751

Record with id: aae608b543d063008a7066c61677cffbdefe26164c7565e042e0f5368dd10638
---------------
Created at: 2023-11-18 16:54:51
Confirmed at: Not confirmed
Accepted at: 2023-11-18 16:54:51
Status: PENDING_CONFIRM
```

However, it looks like the transaction correctly went through.

```
$ chia wallet get_transactions
Transaction 8f277af883ee84d91788a0aae5168acd005ee44eebbbd8e5100397cb7c384457
Status: Confirmed
Amount received in trade: 0.1 TXCH
To address: txch17egrzfmmup5skztx57wm2zk6mz3tkke7kl0c8jvvjcy23y55g8tqz0eh44
Created at: 2023-11-18 16:54:51
```
```

**Comment by wjblanke** [comment]
Quex can u check on this index out of range

**Comment by Quexington** [comment]
Hey, I've identified the issue here, and have added it to my list to fix.  The fix is more complicated than the severity of the issue so it's lower priority than some other tasks but we will get to it :+1:

**Comment by wjblanke** [comment]
FWIW this is still in the queue, it just hasn't been completed.

**Comment by wjblanke** [comment]
This should be fixed in main. Thanks for the report!

https://github.com/Chia-Network/chia-blockchain/pull/18494

**Comment by ctrlaltdel** [comment]
Tested successfully on 2.5.0, thanks @Quexington and @wjblanke for the fix!

This is a pretty nice feature to be able to create offers without requested assets for giveaways :)
