### ISSUE TITLE
[Bug] Win 11 crashes during operation without log entry. RuntimeError: wallet state manager not assigned

### ISSUE THREAD

**Issue by kbi-user** [Chia-Network/chia-blockchain#16892]
### What happened?

1. Chia Client is not running, when I log in, even though it should. Apparently 4 hours after I locked screen, Chia just stopped operations (8:53).
2. Error in log, when starting up Chia - again (20:09).

Remarks:
- Win 11 fully patched
- Chia uninstalled completely
- Chia 2.1.1 installed
- Download and install of Chia blockchain snapshot.

Nothing else is running on this machine except Chia Client.

### Version

2.1.1

### What platform are you using?

Windows

### What ui mode are you using?

GUI

### Relevant log output

```shell
2023-11-20T08:19:34.823 wallet wallet_server              : WARNING  Banning 2400:2653:23a0:8b00:50c7:39c0:1eeb:84c for 120 seconds
2023-11-20T08:30:18.155 wallet chia.wallet.wallet_node    : WARNING  Peer PeerInfo(_ip=IPv4Address('108.162.144.89'), _port=8444) did not respond in time.
2023-11-20T08:30:18.171 wallet wallet_server              : WARNING  Banning 108.162.144.89 for 120 seconds
2023-11-20T08:37:34.016 wallet chia.wallet.wallet_node    : WARNING  Peer PeerInfo(_ip=IPv6Address('2a02:1210:7a94:7e00:1006:e4c0:2291:c771'), _port=8444) did not respond in time.
2023-11-20T08:37:34.031 wallet wallet_server              : WARNING  Banning 2a02:1210:7a94:7e00:1006:e4c0:2291:c771 for 120 seconds
2023-11-20T08:50:22.820 wallet chia.wallet.wallet_node    : WARNING  Peer PeerInfo(_ip=IPv6Address('2806:2f0:a500:fb60:d544:5b9d:1bc1:f014'), _port=8444) did not respond in time.
2023-11-20T08:50:22.820 wallet wallet_server              : WARNING  Banning 2806:2f0:a500:fb60:d544:5b9d:1bc1:f014 for 120 seconds
2023-11-20T08:53:36.158 wallet chia.wallet.wallet_node    : WARNING  Peer PeerInfo(_ip=IPv4Address('171.97.168.236'), _port=8444) did not respond in time.
2023-11-20T08:53:36.174 wallet wallet_server              : WARNING  Banning 171.97.168.236 for 120 seconds
2023-11-20T20:09:03.490 wallet wallet_server              : ERROR    Caught exception: RuntimeError: wallet state manager not assigned
Traceback (most recent call last):
  File "chia\util\log_exceptions.py", line 20, in log_exceptions
  File "chia\server\ws_connection.py", line 307, in close
  File "chia\server\server.py", line 555, in connection_closed
  File "chia\wallet\wallet_node.py", line 675, in on_disconnect
  File "chia\wallet\wallet_node.py", line 161, in wallet_state_manager
RuntimeError: wallet state manager not assigned
```

**Comment by wjblanke** [comment]
can u set the logging to INFO. also a screenshot would be helpful. rebooting might resolve things for u.

**Comment by wjblanke** [comment]
Are you running an AMD Phenom?

**Comment by kbi-user** [comment]
Sorry didnt see your last answer.

1. Amd Epyc 7443P
2. Rebooting doesnt help at all
3. Farming crashes app. every 24 hours

Setting logging to info now. Posting when I got another crash (soon since those happen regularly).

**Comment by kbi-user** [comment]
Attached the full log.

I just logged on (new Chia Client) and the Client obviously crashed and had a reboot.
[debug.zip](https://github.com/Chia-Network/chia-blockchain/files/13694382/debug.zip)

**Comment by kbi-user** [comment]
@wjblanke any updates? I hoped the Client update would help, but its getting worse...

**Comment by kbi-user** [comment]
Issue persists.
