### ISSUE TITLE
[BUG]chia_harvester fault

### ISSUE THREAD

**Issue by asd2317419** [Chia-Network/chia-blockchain#1691]
![mmexport1617617030155](https://user-images.githubusercontent.com/81959665/113563067-aa560b00-9639-11eb-9b96-f0edef8740d2.jpg)
![QQ截图20210405180623](https://user-images.githubusercontent.com/81959665/113563080-afb35580-9639-11eb-9005-f2065cd61603.png)

**Comment by wjblanke** [comment]
Are you running 1.0.3?

**Comment by asd2317419** [comment]
> 您是否正在运行1.0.3？

yes

**Comment by mariano54** [comment]
Can you check ~/.chia/mainnet/log/debug.log for any errors?And paste here any lines in that file which contain "ERROR"

**Comment by asd2317419** [comment]
> 您可以检查〜/ .chia / mainnet / log / debug.log是否存在任何错误？并将此处包含“ ERROR”的任何行粘贴到此处


06:45:09.863 daemon src.daemon.server          : INFO     Websocket exception. Closing websocket with chia_harvester code = 1006 (connection closed abnormally [internal]), no reason Traceback (most recent call last):
  File "websockets\protocol.py", line 827, in transfer_data
  File "websockets\protocol.py", line 895, in read_message
  File "websockets\protocol.py", line 971, in read_data_frame
  File "websockets\protocol.py", line 1051, in read_frame
  File "websockets\framing.py", line 105, in read
  File "asyncio\streams.py", line 679, in readexactly
  File "asyncio\streams.py", line 473, in _wait_for_data
  File "asyncio\selector_events.py", line 814, in _read_ready__data_received
ConnectionResetError: [WinError 10054] 远程主机强迫关闭了一个现有的连接。

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "src\daemon\server.py", line 218, in safe_handle
  File "websockets\protocol.py", line 439, in __aiter__
  File "websockets\protocol.py", line 509, in recv
  File "websockets\protocol.py", line 803, in ensure_open
websockets.exceptions.ConnectionClosedError: code = 1006 (connection closed abnormally [internal]), no reason

06:45:13.015 harvester harvester               : INFO     Started harvester service on network_id: mainnet
06:45:13.015 harvester harvester               : INFO     Reconnecting to peer {'host': '192.168.50.187', 'port': 8447}
06:45:13.030 harvester harvester_server        : INFO     -> handshake to peer 192.168.50.187 9a2b72587700cfddbd3abd0dd6092169b251843ce1b52aee404b753fa623f653
06:45:13.030 harvester harvester_server        : INFO     Connected with farmer {'host': '192.168.50.187', 'port': 8447}
06:45:13.030 harvester harvester_server        : INFO     <- harvester_handshake from peer 9a2b72587700cfddbd3abd0dd6092169b251843ce1b52aee404b753fa623f653 192.168.50.187
06:45:13.077 harvester src.plotting.plot_tools : INFO     Searching directories ['A:\\ok', 'B:\\ok', 'D:\\ok', 'E:\\ok', 'F:\\ok', 'G:\\ok', 'H:\\ok', 'J:\\ok', 'L:\\ok', 'M:\\ok', 'N:\\ok', 'O:\\ok', 'P:\\ok', 'Q:\\ok', 'R:\\ok', 'S:\\ok', 'T:\\ok', 'U:\\ok', 'V:\\ok', 'W:\\ok', 'Z:\\ok', 'A:\\15\\ok', 'B:\\16\\ok', 'I:\\ok', 'X:\\ok', 'Y:\\ok', 'K:\\ok']

06:46:31.368 harvester src.rpc.rpc_server      : WARNING  Exception: Traceback (most recent call last):
  File "src\rpc\rpc_server.py", line 278, in connect_to_daemon
  File "aiohttp\client.py", line 1117, in __aenter__
  File "aiohttp\client.py", line 763, in _ws_connect
  File "aiohttp\client.py", line 544, in _request
  File "aiohttp\client_reqrep.py", line 890, in start
  File "aiohttp\streams.py", line 604, in read
aiohttp.client_exceptions.ClientOSError: [WinError 10053] 你的主机中的软件中止了一个已建立的连接。
 <class 'aiohttp.client_exceptions.ClientOSError'>

**Comment by asd2317419** [comment]
in the Ubuntu 
 logging: &id001
    log_filename: log/debug.log
    log_level: INFO
    log_stdout: WARNING

debug.log is blank，Next time I copy and save from the terminal

**Comment by asd2317419** [comment]
ERROR: apport (pid 11865) Tue Apr  6 05:15:57 2021: called for pid 11322, signal 11, core limit 0, dump mode 1
ERROR: apport (pid 11865) Tue Apr  6 05:15:57 2021: executable: /usr/bin/python3.8 (command line "chia_harvester")
ERROR: apport (pid 11865) Tue Apr  6 05:15:57 2021: is_closing_session(): no DBUS_SESSION_BUS_ADDRESS in environment
ERROR: apport (pid 11865) Tue Apr  6 05:15:59 2021: wrote report /var/crash/_usr_bin_python3.8.1000.crash
ERROR: apport (pid 13059) Tue Apr  6 10:10:16 2021: called for pid 11488, signal 11, core limit 0, dump mode 1
ERROR: apport (pid 13059) Tue Apr  6 10:10:16 2021: executable: /usr/bin/python3.8 (command line "chia_harvester")
ERROR: apport (pid 13059) Tue Apr  6 10:10:16 2021: is_closing_session(): no DBUS_SESSION_BUS_ADDRESS in environment
ERROR: apport (pid 13059) Tue Apr  6 10:10:19 2021: wrote report /var/crash/_usr_bin_python3.8.1000.crash

**Comment by asd2317419** [comment]
> 您可以检查〜/ .chia / mainnet / log / debug.log是否存在任何错误？并将此处包含“ ERROR”的任何行粘贴到此处

22:30:35.589 daemon src.daemon.server          : INFO     Websocket exception. Closing websocket with chia_harvester code = 1006 (connection closed abnormally [internal]), no reason Traceback (most recent call last):
  File "/home/a111/chia-blockchain/venv/lib/python3.8/site-packages/websockets/protocol.py", line 827, in transfer_data
    message = await self.read_message()
  File "/home/a111/chia-blockchain/venv/lib/python3.8/site-packages/websockets/protocol.py", line 895, in read_message
    frame = await self.read_data_frame(max_size=self.max_size)
  File "/home/a111/chia-blockchain/venv/lib/python3.8/site-packages/websockets/protocol.py", line 971, in read_data_frame
    frame = await self.read_frame(max_size)
  File "/home/a111/chia-blockchain/venv/lib/python3.8/site-packages/websockets/protocol.py", line 1047, in read_frame
    frame = await Frame.read(
  File "/home/a111/chia-blockchain/venv/lib/python3.8/site-packages/websockets/framing.py", line 105, in read
    data = await reader(2)
  File "/usr/lib/python3.8/asyncio/streams.py", line 721, in readexactly
    raise exceptions.IncompleteReadError(incomplete, n)
asyncio.exceptions.IncompleteReadError: 0 bytes read on a total of 2 expected bytes

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/a111/chia-blockchain/src/daemon/server.py", line 165, in safe_handle
    async for message in websocket:
  File "/home/a111/chia-blockchain/venv/lib/python3.8/site-packages/websockets/protocol.py", line 439, in __aiter__
    yield await self.recv()
  File "/home/a111/chia-blockchain/venv/lib/python3.8/site-packages/websockets/protocol.py", line 509, in recv
    await self.ensure_open()
  File "/home/a111/chia-blockchain/venv/lib/python3.8/site-packages/websockets/protocol.py", line 803, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedError: code = 1006 (connection closed abnormally [internal]), no reason

**Comment by mariano54** [comment]
Can you run `chia plots check` to see if you have a bad plot?

**Comment by asd2317419** [comment]
> Can you run `chia plots check` to see if you have a bad plot?

total 2660 plots  
Need to run 10  hour
When I'm done, I'll tell you the result

**Comment by asd2317419** [comment]
> Can you run `chia plots check` to see if you have a bad plot?
thank you
When I'm done, I'll tell you the result

**Comment by asd2317419** [comment]
![1617807684(1)](https://user-images.githubusercontent.com/81959665/113888863-4b3cf580-97f5-11eb-96e4-41aaeca402ab.png)
I have deleted this plot,   Will the problem be solved

**Comment by mariano54** [comment]
Yes, I hope so.

**Comment by asd2317419** [comment]
> 是的，我也希望如此。

![42408710600a08c822a789c00afb7e2](https://user-images.githubusercontent.com/81959665/113945527-0e92ed80-9839-11eb-949e-957e282a569d.jpg)
When this plot is checked，The process is down，I have deleted this plot
