### ISSUE TITLE
DAO close_proposal error [Bug] 

### ISSUE THREAD

**Issue by danieljperry** [Chia-Network/chia-blockchain#16923]
### What happened?

The proposal from this issue was created from
https://github.com/Chia-Network/chia-blockchain/issues/16922
Therefore, this issue might be limited proposals that were initially created multiple times, with more votes than required to pass.

Here are the DAO's rules:
```bash
 chia dao rules -i 2
attendance_required: 1000
oracle_spend_delay: 5
pass_percentage: 5000
proposal_minimum_amount: 1000001
proposal_timelock: 10
self_destruct_length: 10
soft_close_length: 2
```

And the proposal's details:
```bash
chia dao show_proposal -i 2 -p 0x6af20896b7848536a43abd3fa3cf40c947558db1d02f5168046e033fa7b03d4d

Details of Proposal: 0x6af20896b7848536a43abd3fa3cf40c947558db1d02f5168046e033fa7b03d4d
---------------------------

Type: SPEND
Status: OPEN
Passed: True
Closable: True

Proposal XCH Conditions
Address: txch1jufvasj9qwh2a3hml2mz36e3m505xzn8z5gfwxvtspvujx8t5ycs0z2a6t
Amount: 1000000999999
```

The proposal has already passed. Attempt to close it:
```bash
chia dao close_proposal -i 2 -p 0x6af20896b7848536a43abd3fa3cf40c947558db1d02f5168046e033fa7b03d4d -m 0.0001
```

This results in an error. I have tried closing this proposal from multiple wallets, including the wallet use to create the proposal, and have gotten the same error each time:

```bash
Exception from 'wallet' {'error': 'clvm raise', 'success': False, 'traceback': 'Traceback (most recent call last):\n  File "C:\\Users\\User\\Chia\\main\\chia-blockchain\\chia\\rpc\\util.py", line 21, in inner\n    res_object = await f(request_data)\n  File "C:\\Users\\User\\Chia\\main\\chia-blockchain\\chia\\rpc\\util.py", line 82, in rpc_endpoint\n    return await func(self, request, *args, tx_config=tx_config, extra_conditions=extra_conditions, **kwargs)\n  File "C:\\Users\\User\\Chia\\main\\chia-blockchain\\chia\\rpc\\wallet_rpc_api.py", line 2901, in dao_close_proposal\n    tx = await dao_wallet.create_proposal_close_spend(\n  File "C:\\Users\\User\\Chia\\main\\chia-blockchain\\chia\\wallet\\dao_wallet\\dao_wallet.py", line 1496, in create_proposal_close_spend\n    additions=full_spend.additions(),\n  File "C:\\Users\\User\\Chia\\main\\chia-blockchain\\chia\\types\\spend_bundle.py", line 46, in additions\n    coins, cost = compute_additions_with_cost(cs, max_cost=max_cost)\n  File "C:\\Users\\User\\Chia\\main\\chia-blockchain\\chia\\types\\coin_spend.py", line 48, in compute_additions_with_cost\n    cost, r = cs.puzzle_reveal.run_with_cost(max_cost, cs.solution)\n  File "C:\\Users\\User\\Chia\\main\\chia-blockchain\\chia\\types\\blockchain_format\\serialized_program.py", line 95, in run_with_cost\n    return self._run(max_cost, 0, arg)\n  File "C:\\Users\\User\\Chia\\main\\chia-blockchain\\chia\\types\\blockchain_format\\serialized_program.py", line 104, in _run\n    cost, ret = run_chia_program(\n  File "<string>", line 1, in <module>\nValueError: (\'clvm raise\', \'80\')\n'}:
Traceback (most recent call last):
  File "C:\Users\User\Chia\main\chia-blockchain\chia\cmds\cmds_util.py", line 119, in get_any_service_client
    yield node_client, config
  File "C:\Users\User\Chia\main\chia-blockchain\chia\cmds\cmds_util.py", line 235, in get_wallet_client
    yield wallet_client, new_fp, config
  File "C:\Users\User\Chia\main\chia-blockchain\chia\cmds\dao_funcs.py", line 332, in close_proposal
    res = await wallet_client.dao_close_proposal(
  File "C:\Users\User\Chia\main\chia-blockchain\chia\rpc\wallet_rpc_client.py", line 1479, in dao_close_proposal
    response = await self.fetch("dao_close_proposal", request)
  File "C:\Users\User\Chia\main\chia-blockchain\chia\rpc\rpc_client.py", line 87, in fetch
    raise ValueError(res_json)
ValueError: {'error': 'clvm raise', 'success': False, 'traceback': 'Traceback (most recent call last):\n  File "C:\\Users\\User\\Chia\\main\\chia-blockchain\\chia\\rpc\\util.py", line 21, in inner\n    res_object = await f(request_data)\n  File "C:\\Users\\User\\Chia\\main\\chia-blockchain\\chia\\rpc\\util.py", line 82, in rpc_endpoint\n    return await func(self, request, *args, tx_config=tx_config, extra_conditions=extra_conditions, **kwargs)\n  File "C:\\Users\\User\\Chia\\main\\chia-blockchain\\chia\\rpc\\wallet_rpc_api.py", line 2901, in dao_close_proposal\n    tx = await dao_wallet.create_proposal_close_spend(\n  File "C:\\Users\\User\\Chia\\main\\chia-blockchain\\chia\\wallet\\dao_wallet\\dao_wallet.py", line 1496, in create_proposal_close_spend\n    additions=full_spend.additions(),\n  File "C:\\Users\\User\\Chia\\main\\chia-blockchain\\chia\\types\\spend_bundle.py", line 46, in additions\n    coins, cost = compute_additions_with_cost(cs, max_cost=max_cost)\n  File "C:\\Users\\User\\Chia\\main\\chia-blockchain\\chia\\types\\coin_spend.py", line 48, in compute_additions_with_cost\n    cost, r = cs.puzzle_reveal.run_with_cost(max_cost, cs.solution)\n  File "C:\\Users\\User\\Chia\\main\\chia-blockchain\\chia\\types\\blockchain_format\\serialized_program.py", line 95, in run_with_cost\n    return self._run(max_cost, 0, arg)\n  File "C:\\Users\\User\\Chia\\main\\chia-blockchain\\chia\\types\\blockchain_format\\serialized_program.py", line 104, in _run\n    cost, ret = run_chia_program(\n  File "<string>", line 1, in <module>\nValueError: (\'clvm raise\', \'80\')\n'}
```

Here is my log file:

[debug_close_proposal.log](https://github.com/Chia-Network/chia-blockchain/files/13445833/debug_close_proposal.log)

### Version

2.1.2.dev292 (main branch)

### What platform are you using?

Windows

### What ui mode are you using?

CLI

**Comment by danieljperry** [comment]
Update: the same error is occurring for a proposal with 2000 yes votes, 1000 no votes, and 3000 total votes needed.

Proposal status:

```
Details of Proposal: 0x7b10351e130317fc3f7b6d5e50aeb3b8d63db7545ef5e80836913f5741cdbb22
---------------------------

Type: SPEND
Status: OPEN
Passed: True
Closable: True

Proposal XCH Conditions
Address: txch1796cqesu4cghd603743hdsp4ffz0tj0tacp63ag2p433fhudkyuq58sw69
Amount: 1000000000000
```

Close command:
```
chia dao close_proposal -i 2 -p 0x7b10351e130317fc3f7b6d5e50aeb3b8d63db7545ef5e80836913f5741cdbb22 -m 0.0001
```
Response:
```
Exception from 'wallet' {'error': 'clvm raise', 'success': False, 'traceback': 'Traceback (most recent call last):\n  File "C:\\Users\\User\\Chia\\main\\chia-blockchain\\chia\\rpc\\util.py", line 21, in inner\n    res_object = await f(request_data)\n  File "C:\\Users\\User\\Chia\\main\\chia-blockchain\\chia\\rpc\\util.py", line 82, in rpc_endpoint\n    return await func(self, request, *args, tx_config=tx_config, extra_conditions=extra_conditions, **kwargs)\n  File "C:\\Users\\User\\Chia\\main\\chia-blockchain\\chia\\rpc\\wallet_rpc_api.py", line 2901, in dao_close_proposal\n    tx = await dao_wallet.create_proposal_close_spend(\n  File "C:\\Users\\User\\Chia\\main\\chia-blockchain\\chia\\wallet\\dao_wallet\\dao_wallet.py", line 1496, in create_proposal_close_spend\n    additions=full_spend.additions(),\n  File "C:\\Users\\User\\Chia\\main\\chia-blockchain\\chia\\types\\spend_bundle.py", line 46, in additions\n    coins, cost = compute_additions_with_cost(cs, max_cost=max_cost)\n  File "C:\\Users\\User\\Chia\\main\\chia-blockchain\\chia\\types\\coin_spend.py", line 48, in compute_additions_with_cost\n    cost, r = cs.puzzle_reveal.run_with_cost(max_cost, cs.solution)\n  File "C:\\Users\\User\\Chia\\main\\chia-blockchain\\chia\\types\\blockchain_format\\serialized_program.py", line 95, in run_with_cost\n    return self._run(max_cost, 0, arg)\n  File "C:\\Users\\User\\Chia\\main\\chia-blockchain\\chia\\types\\blockchain_format\\serialized_program.py", line 104, in _run\n    cost, ret = run_chia_program(\n  File "<string>", line 1, in <module>\nValueError: (\'clvm raise\', \'80\')\n'}:
Traceback (most recent call last):
  File "C:\Users\User\Chia\main\chia-blockchain\chia\cmds\cmds_util.py", line 119, in get_any_service_client
    yield node_client, config
  File "C:\Users\User\Chia\main\chia-blockchain\chia\cmds\cmds_util.py", line 235, in get_wallet_client
    yield wallet_client, new_fp, config
  File "C:\Users\User\Chia\main\chia-blockchain\chia\cmds\dao_funcs.py", line 332, in close_proposal
    res = await wallet_client.dao_close_proposal(
  File "C:\Users\User\Chia\main\chia-blockchain\chia\rpc\wallet_rpc_client.py", line 1479, in dao_close_proposal
    response = await self.fetch("dao_close_proposal", request)
  File "C:\Users\User\Chia\main\chia-blockchain\chia\rpc\rpc_client.py", line 87, in fetch
    raise ValueError(res_json)
ValueError: {'error': 'clvm raise', 'success': False, 'traceback': 'Traceback (most recent call last):\n  File "C:\\Users\\User\\Chia\\main\\chia-blockchain\\chia\\rpc\\util.py", line 21, in inner\n    res_object = await f(request_data)\n  File "C:\\Users\\User\\Chia\\main\\chia-blockchain\\chia\\rpc\\util.py", line 82, in rpc_endpoint\n    return await func(self, request, *args, tx_config=tx_config, extra_conditions=extra_conditions, **kwargs)\n  File "C:\\Users\\User\\Chia\\main\\chia-blockchain\\chia\\rpc\\wallet_rpc_api.py", line 2901, in dao_close_proposal\n    tx = await dao_wallet.create_proposal_close_spend(\n  File "C:\\Users\\User\\Chia\\main\\chia-blockchain\\chia\\wallet\\dao_wallet\\dao_wallet.py", line 1496, in create_proposal_close_spend\n    additions=full_spend.additions(),\n  File "C:\\Users\\User\\Chia\\main\\chia-blockchain\\chia\\types\\spend_bundle.py", line 46, in additions\n    coins, cost = compute_additions_with_cost(cs, max_cost=max_cost)\n  File "C:\\Users\\User\\Chia\\main\\chia-blockchain\\chia\\types\\coin_spend.py", line 48, in compute_additions_with_cost\n    cost, r = cs.puzzle_reveal.run_with_cost(max_cost, cs.solution)\n  File "C:\\Users\\User\\Chia\\main\\chia-blockchain\\chia\\types\\blockchain_format\\serialized_program.py", line 95, in run_with_cost\n    return self._run(max_cost, 0, arg)\n  File "C:\\Users\\User\\Chia\\main\\chia-blockchain\\chia\\types\\blockchain_format\\serialized_program.py", line 104, in _run\n    cost, ret = run_chia_program(\n  File "<string>", line 1, in <module>\nValueError: (\'clvm raise\', \'80\')\n'}
```

Log:

```
2023-11-24T12:57:47.554 full_node chia.full_node.full_node: INFO       Finished signage point 42/64: CC: 17167efbded627411164018148db9b3fee2fbd971b2f441973a6bf8efacdb830 RC: 9ad7514d66696600fcdd0a9eb5c01e4b702b3e5c1aa1026144f7607c67372453 
2023-11-24T12:57:47.558 farmer farmer_server              : WARNING  API not ready, ignore request: {'data': '0x842a4dd290c2a8ed27733ba85fe7eaa596798972a39ea41ee49685be85c5c6fd17167efbded627411164018148db9b3fee2fbd971b2f441973a6bf8efacdb8309ad7514d66696600fcdd0a9eb5c01e4b702b3e5c1aa1026144f7607c67372453000000000000550000000000044000002a0007a460',
 'id': None,
 'type': 8}
2023-11-24T12:57:48.341 daemon __main__                   : INFO     Connection close requested. Closing websocket with ['Unknown'].
2023-11-24T12:57:48.787 wallet wallet_server              : INFO     Cannot connect to host 2600:1f13:c55:4404:79cd:bd19:da9f:cdc8:58444 ssl:<ssl.SSLContext object at 0x000001DB3E143540> [The network location cannot be reached. For information about network troubleshooting, see Windows Help]
2023-11-24T12:57:49.564 wallet wallet_server              : INFO     Cannot connect to host 2600:1f13:c55:4401:c74e:f61:4859:a758:58444 ssl:<ssl.SSLContext object at 0x000001DB3E143540> [The network location cannot be reached. For information about network troubleshooting, see Windows Help]
2023-11-24T12:57:50.012 full_node full_node_server        : INFO     Cannot connect to host 35.88.105.43:58444 ssl:<ssl.SSLContext object at 0x0000027C947D89C0> [The semaphore timeout period has expired]
2023-11-24T12:57:50.197 wallet wallet_server              : INFO     Cannot connect to host 54.244.166.235:58444 ssl:<ssl.SSLContext object at 0x000001DB3E143540> [The semaphore timeout period has expired]
2023-11-24T12:57:50.354 wallet chia.wallet.dao_wallet.dao_wallet: INFO     Trying to create a proposal close spend with ID: 7b10351e130317fc3f7b6d5e50aeb3b8d63db7545ef5e80836913f5741cdbb22
2023-11-24T12:57:50.363 wallet chia.wallet.dao_wallet.dao_wallet: INFO     Closing passed proposal: 7b10351e130317fc3f7b6d5e50aeb3b8d63db7545ef5e80836913f5741cdbb22
2023-11-24T12:57:50.521 wallet chia.wallet.wallet_state_manager: INFO     Start: Creating puzzle hashes from 451 to 451 for wallet_id: 1
2023-11-24T12:57:50.529 wallet chia.wallet.wallet_state_manager: INFO     Done: Creating puzzle hashes from 451 to 451 for wallet_id: 1 Time: 0.007872343063354492 seconds
2023-11-24T12:57:50.536 wallet chia.wallet.wallet_state_manager: INFO     Start: Creating puzzle hashes from 451 to 451 for wallet_id: 3
2023-11-24T12:57:50.543 wallet chia.wallet.wallet_state_manager: INFO     Done: Creating puzzle hashes from 451 to 451 for wallet_id: 3 Time: 0.022156953811645508 seconds
2023-11-24T12:57:50.550 wallet chia.wallet.wallet_state_manager: INFO     Start: Creating puzzle hashes from 451 to 451 for wallet_id: 4
2023-11-24T12:57:50.627 wallet chia.wallet.wallet_state_manager: INFO     Done: Creating puzzle hashes from 451 to 451 for wallet_id: 4 Time: 0.10561227798461914 seconds
2023-11-24T12:57:50.636 wallet chia.wallet.wallet_state_manager: INFO     Updating last used derivation index: 26
2023-11-24T12:57:50.653 wallet chia.wallet.wallet         : INFO     coins is not None {<builtins.Coin object at 0x000001DB4B08A2D0>}
2023-11-24T12:57:50.654 wallet chia.wallet.wallet         : INFO     spend_value is 999790000000 and total_amount is 100000000
2023-11-24T12:57:50.664 wallet chia.wallet.wallet_state_manager: INFO     Start: Creating puzzle hashes from 452 to 452 for wallet_id: 1
2023-11-24T12:57:50.672 wallet chia.wallet.wallet_state_manager: INFO     Done: Creating puzzle hashes from 452 to 452 for wallet_id: 1 Time: 0.0071375370025634766 seconds
2023-11-24T12:57:50.679 wallet chia.wallet.wallet_state_manager: INFO     Start: Creating puzzle hashes from 452 to 452 for wallet_id: 3
2023-11-24T12:57:50.688 wallet chia.wallet.wallet_state_manager: INFO     Done: Creating puzzle hashes from 452 to 452 for wallet_id: 3 Time: 0.02305293083190918 seconds
2023-11-24T12:57:50.695 wallet chia.wallet.wallet_state_manager: INFO     Start: Creating puzzle hashes from 452 to 452 for wallet_id: 4
2023-11-24T12:57:50.766 wallet chia.wallet.wallet_state_manager: INFO     Done: Creating puzzle hashes from 452 to 452 for wallet_id: 4 Time: 0.10131263732910156 seconds
2023-11-24T12:57:50.775 wallet chia.wallet.wallet_state_manager: INFO     Updating last used derivation index: 27
2023-11-24T12:57:50.782 wallet chia.wallet.wallet         : INFO     About to sign a transaction: [CoinSpend(coin=<builtins.Coin object at 0x000001DB4B08A2D0>, puzzle_reveal=SerializedProgram(ff02ffff01ff02ffff01ff02ffff03ff0bffff01ff02ffff03ffff09ff05ffff1dff0bffff1effff0bff0bffff02ff06ffff04ff02ffff04ff17ff8080808080808080ffff01ff02ff17ff2f80ffff01ff088080ff0180ffff01ff04ffff04ff04ffff04ff05ffff04ffff02ff06ffff04ff02ffff04ff17ff80808080ff80808080ffff02ff17ff2f808080ff0180ffff04ffff01ff32ff02ffff03ffff07ff0580ffff01ff0bffff0102ffff02ff06ffff04ff02ffff04ff09ff80808080ffff02ff06ffff04ff02ffff04ff0dff8080808080ffff01ff0bffff0101ff058080ff0180ff018080ffff04ffff01b093770818ec7ddd65b126f1c5130c63bd6b93706ab6ec07046482b4d6d53c2ff396fb2defec77780ea028dae5b17c2362ff018080), solution=SerializedProgram(ff80ffff01ffff33ffa049298130242b3cb556cc757c1252b0d5ef63db8302b70455d802fc88e9118b95ff8600e8c22ad68080ffff34ff8405f5e10080ffff3cffa0839379bc036a4d89cdb75694b255a9348d90b39d46d324afbfb78a19bca8534e8080ff8080))]
2023-11-24T12:57:50.805 wallet chia.rpc.util              : WARNING  Error while handling message: Traceback (most recent call last):
  File "C:\Users\User\Chia\main\chia-blockchain\chia\rpc\util.py", line 21, in inner
    res_object = await f(request_data)
  File "C:\Users\User\Chia\main\chia-blockchain\chia\rpc\util.py", line 82, in rpc_endpoint
    return await func(self, request, *args, tx_config=tx_config, extra_conditions=extra_conditions, **kwargs)
  File "C:\Users\User\Chia\main\chia-blockchain\chia\rpc\wallet_rpc_api.py", line 2901, in dao_close_proposal
    tx = await dao_wallet.create_proposal_close_spend(
  File "C:\Users\User\Chia\main\chia-blockchain\chia\wallet\dao_wallet\dao_wallet.py", line 1496, in create_proposal_close_spend
    additions=full_spend.additions(),
  File "C:\Users\User\Chia\main\chia-blockchain\chia\types\spend_bundle.py", line 46, in additions
    coins, cost = compute_additions_with_cost(cs, max_cost=max_cost)
  File "C:\Users\User\Chia\main\chia-blockchain\chia\types\coin_spend.py", line 48, in compute_additions_with_cost
    cost, r = cs.puzzle_reveal.run_with_cost(max_cost, cs.solution)
  File "C:\Users\User\Chia\main\chia-blockchain\chia\types\blockchain_format\serialized_program.py", line 95, in run_with_cost
    return self._run(max_cost, 0, arg)
  File "C:\Users\User\Chia\main\chia-blockchain\chia\types\blockchain_format\serialized_program.py", line 104, in _run
    cost, ret = run_chia_program(
  File "<string>", line 1, in <module>
ValueError: ('clvm raise', '80')
```
