### ISSUE TITLE
DAO close_proposal fails [Bug] 

### ISSUE THREAD

**Issue by danieljperry** [Chia-Network/chia-blockchain#16989]
### What happened?

I have a proposal to mint CATs. This proposal has passed and is ready to be closed:

```
Details of Proposal: 0x66fbce0ae62a7653d9769d19a9b0f56505df01e94fd431968be94d523b621c85
---------------------------

Type: MINT
Status: OPEN
Passed: True
Closable: True

Amount of CAT to mint: 1000
Address: txch12gftgd4ep7vlgmtgvk87htxp0k8rrl9jqrpfxm433k8meuv656pqljx82k
```

However, when I attempt to close the proposal, I receive an error:

```
chia dao close_proposal -i 2 -p 0x66fbce0ae62a7653d9769d19a9b0f56505df01e94fd431968be94d523b621c85 -m 0.0001
```
```
Exception from 'wallet' {'error': '', 'success': False}:
Traceback (most recent call last):
  File "C:\Users\User\Chia\gw.gte_vote_amounts\chia-blockchain\chia\cmds\cmds_util.py", line 119, in get_any_service_client
    yield node_client, config
  File "C:\Users\User\Chia\gw.gte_vote_amounts\chia-blockchain\chia\cmds\cmds_util.py", line 235, in get_wallet_client
    yield wallet_client, new_fp, config
  File "C:\Users\User\Chia\gw.gte_vote_amounts\chia-blockchain\chia\cmds\dao_funcs.py", line 332, in close_proposal
    res = await wallet_client.dao_close_proposal(
  File "C:\Users\User\Chia\gw.gte_vote_amounts\chia-blockchain\chia\rpc\wallet_rpc_client.py", line 1479, in dao_close_proposal
    response = await self.fetch("dao_close_proposal", request)
  File "C:\Users\User\Chia\gw.gte_vote_amounts\chia-blockchain\chia\rpc\rpc_client.py", line 87, in fetch
    raise ValueError(res_json)
ValueError: {'error': '', 'success': False}
```

See the `relevant log output` section for the error in the log file.

### Version

2.1.2rc3.dev3 (gw.gte_vote_amounts) branch

### What platform are you using?

Windows

### What ui mode are you using?

CLI

### Relevant log output

```shell
2023-12-04T14:03:29.379 wallet chia.wallet.dao_wallet.dao_wallet: INFO     Trying to create a proposal close spend with ID: 66fbce0ae62a7653d9769d19a9b0f56505df01e94fd431968be94d523b621c85
2023-12-04T14:03:29.394 wallet chia.wallet.dao_wallet.dao_wallet: INFO     Closing passed proposal: 66fbce0ae62a7653d9769d19a9b0f56505df01e94fd431968be94d523b621c85
2023-12-04T14:03:29.504 wallet chia.rpc.util              : WARNING  Error while handling message: Traceback (most recent call last):
  File "C:\Users\User\Chia\gw.gte_vote_amounts\chia-blockchain\chia\rpc\util.py", line 21, in inner
    res_object = await f(request_data)
  File "C:\Users\User\Chia\gw.gte_vote_amounts\chia-blockchain\chia\rpc\util.py", line 82, in rpc_endpoint
    return await func(self, request, *args, tx_config=tx_config, extra_conditions=extra_conditions, **kwargs)
  File "C:\Users\User\Chia\gw.gte_vote_amounts\chia-blockchain\chia\rpc\wallet_rpc_api.py", line 2901, in dao_close_proposal
    tx = await dao_wallet.create_proposal_close_spend(
  File "C:\Users\User\Chia\gw.gte_vote_amounts\chia-blockchain\chia\wallet\dao_wallet\dao_wallet.py", line 1287, in create_proposal_close_spend
    assert tail_reconstruction is not None
AssertionError
```

**Comment by danieljperry** [comment]
This issue is fixed with the latest commit in the gw.gte_vote_amounts branch.
