### ISSUE TITLE
What is this error

### ISSUE THREAD

**Issue by kryshal** [Chia-Network/chia-blockchain#1702]
20:30:58.323  src.plotting.create_plots        : [32mINFO    [0m Creating 1 plots of size 32, pool public key:  8737e627b52dfe2246b1cde1a4cc29540fce748238b49d8eeedd6c405f4164982efe8f6d6753f0b1c0abc3f0d7dcb12b farmer public key: 9000b5610beb6a677ba99903b14479203b5a7c27cf2aa81b9d2916124c70737dabd840359a6c5c8f0eacdc3a768ca09d[0m
20:30:58.339  src.plotting.create_plots        : [32mINFO    [0m Memo: 8737e627b52dfe2246b1cde1a4cc29540fce748238b49d8eeedd6c405f4164982efe8f6d6753f0b1c0abc3f0d7dcb12b9000b5610beb6a677ba99903b14479203b5a7c27cf2aa81b9d2916124c70737dabd840359a6c5c8f0eacdc3a768ca09d39313b5087be28fa3e3cae8e11451712da6c6eba89252f03f9e4949e02583c20[0m
20:30:58.386  src.plotting.create_plots        : [32mINFO    [0m Starting plot 1/1[0m
Caught plotting error: Bitfield plotting not supported by CPU
[11812] Failed to execute script chia
Traceback (most recent call last):
  File "src\cmds\chia.py", line 80, in <module>
  File "src\cmds\chia.py", line 76, in main
  File "click\core.py", line 829, in __call__
  File "click\core.py", line 782, in main
  File "click\core.py", line 1259, in invoke
  File "click\core.py", line 1259, in invoke
  File "click\core.py", line 1066, in invoke
  File "click\core.py", line 610, in invoke
  File "click\decorators.py", line 21, in new_func
  File "src\cmds\plots.py", line 134, in create_cmd
  File "src\plotting\create_plots.py", line 176, in create_plots
RuntimeError: Unknown exception

**Comment by hoffmang9** [comment]
Your CPU is too old to use Bitfield plotting. You can use non bitfield plotting either in the Advanced Options section of the Plot creation page in the GUI or adding the `-e` flag on the command line.
