### ISSUE TITLE
[Bug] Can't use the external drive to store the database after upgraded to 2.1.3

### ISSUE THREAD

**Issue by anguschang007** [Chia-Network/chia-blockchain#17180]
### What happened?

Just upgraded the app from 2.1.1 to 2.1.3 and then keeps having the following error about the database. However, the issue is gone if I move the database to original folder (~/.chia/mainnet/db)

> 2023-12-29T17:05:03.159 full_node chia.server.start_service: ERROR    fatal uncaught exception: DatabaseError: database disk image is malformed
Traceback (most recent call last):
  File "chia/util/log_exceptions.py", line 20, in log_exceptions
  File "chia/server/start_service.py", line 321, in async_run
  File "asyncio/runners.py", line 44, in run
  File "asyncio/base_events.py", line 649, in run_until_complete
  File "chia/server/start_full_node.py", line 83, in async_main
  File "chia/server/start_service.py", line 195, in run
  File "contextlib.py", line 199, in __aenter__
  File "chia/server/start_service.py", line 212, in manage
  File "contextlib.py", line 619, in enter_async_context
  File "contextlib.py", line 199, in __aenter__
  File "chia/full_node/full_node.py", line 268, in manage
  File "chia/consensus/blockchain.py", line 160, in create
  File "chia/consensus/blockchain.py", line 172, in _load_chain_from_store
  File "chia/full_node/block_height_map.py", line 124, in create
  File "chia/full_node/block_height_map.py", line 185, in _load_blocks_from
  File "aiosqlite/context.py", line 39, in __aenter__
  File "aiosqlite/core.py", line 190, in execute
  File "aiosqlite/core.py", line 133, in _execute
  File "aiosqlite/core.py", line 106, in run
sqlite3.DatabaseError: database disk image is malformed

### Version

2.1.3

### What platform are you using?

Linux

### What ui mode are you using?

GUI

**Comment by wjblanke** [comment]
Did u copy it while Chia was running? The copy on your external drive is bad.

sqlite3.DatabaseError: database disk image is malformed

is an error from SQLite itself saying that database has been corrupted. That isn't controlled by our code.

**Comment by anguschang007** [comment]
I use the same database, just copy the database from the external drive to the original folder and then all issues are gone! Why the same database without any issue if it is in the original folder?
