### ISSUE TITLE
[Bug] my chia app dojt want to start

### ISSUE THREAD

**Issue by Tora2405** [Chia-Network/chia-blockchain#17332]
### What happened?

My previous version was 2.1.1 I tried to update last version and then the app don’t want to start stuck on this 
![IMG_2672](https://github.com/Chia-Network/chia-blockchain/assets/156543704/2a49edda-40bb-4558-a6d8-590c88417c37)

### Version

2.1.1 / 2.1.4

### What platform are you using?

Windows

### What ui mode are you using?

GUI

**Comment by wjblanke** [comment]
Can u send u the DEBUG version of the debug.log. Then we can tell what is causing the full node to quit

**Comment by deltasigm4** [comment]
Same Problem here for the last several versions. Debug here:

2024-02-06T22:40:58.769 full_node chia.server.start_service: ERROR    fatal uncaught exception: RuntimeError: BlockStore does not support database schema v1
Traceback (most recent call last):
  File "chia\util\log_exceptions.py", line 20, in log_exceptions
  File "chia\server\start_service.py", line 321, in async_run
  File "asyncio\runners.py", line 44, in run
  File "asyncio\base_events.py", line 649, in run_until_complete
  File "chia\server\start_full_node.py", line 83, in async_main
  File "chia\server\start_service.py", line 195, in run
  File "contextlib.py", line 199, in __aenter__
  File "chia\server\start_service.py", line 212, in manage
  File "contextlib.py", line 619, in enter_async_context
  File "contextlib.py", line 199, in __aenter__
  File "chia\full_node\full_node.py", line 259, in manage
  File "chia\full_node\block_store.py", line 49, in create
RuntimeError: BlockStore does not support database schema v1

2024-02-06T22:41:11.063 wallet chia.wallet.wallet_node    : WARNING  Non-trusted peer PeerInfo(_ip=IPv4Address('38.142.54.50'), _port=8444) is not synced, disconnecting
2024-02-06T22:41:11.065 wallet wallet_server              : WARNING  Banning 38.142.54.50 for 120 seconds
2024-02-06T22:42:42.114 harvester chia.server.start_service: ERROR    fatal uncaught exception: AttributeError: 'int' object has no attribute 'name'
Traceback (most recent call last):
  File "chia\util\log_exceptions.py", line 20, in log_exceptions
  File "chia\server\start_service.py", line 321, in async_run
  File "asyncio\runners.py", line 44, in run
  File "asyncio\base_events.py", line 636, in run_until_complete
  File "asyncio\windows_events.py", line 321, in run_forever
  File "asyncio\base_events.py", line 603, in run_forever
  File "asyncio\base_events.py", line 1871, in _run_once
  File "asyncio\windows_events.py", line 444, in select
  File "asyncio\windows_events.py", line 797, in _poll
  File "chia\server\start_service.py", line 309, in _accept_signal
AttributeError: 'int' object has no attribute 'name'

2024-02-06T22:42:42.618 wallet chia.server.start_service  : ERROR    fatal uncaught exception: AttributeError: 'int' object has no attribute 'name'
Traceback (most recent call last):
  File "chia\util\log_exceptions.py", line 20, in log_exceptions
  File "chia\server\start_service.py", line 321, in async_run
  File "asyncio\runners.py", line 44, in run
  File "asyncio\base_events.py", line 636, in run_until_complete
  File "asyncio\windows_events.py", line 321, in run_forever
  File "asyncio\base_events.py", line 603, in run_forever
  File "asyncio\base_events.py", line 1871, in _run_once
  File "asyncio\windows_events.py", line 444, in select
  File "asyncio\windows_events.py", line 797, in _poll
  File "chia\server\start_service.py", line 309, in _accept_signal
AttributeError: 'int' object has no attribute 'name'

2024-02-06T22:42:44.631 farmer chia.server.start_service  : ERROR    fatal uncaught exception: AttributeError: 'int' object has no attribute 'name'
Traceback (most recent call last):
  File "chia\util\log_exceptions.py", line 20, in log_exceptions
  File "chia\server\start_service.py", line 321, in async_run
  File "asyncio\runners.py", line 44, in run
  File "asyncio\base_events.py", line 636, in run_until_complete
  File "asyncio\windows_events.py", line 321, in run_forever
  File "asyncio\base_events.py", line 603, in run_forever
  File "asyncio\base_events.py", line 1871, in _run_once
  File "asyncio\windows_events.py", line 444, in select
  File "asyncio\windows_events.py", line 797, in _poll
  File "chia\server\start_service.py", line 309, in _accept_signal
AttributeError: 'int' object has no attribute 'name'

2024-02-06T22:44:32.487 full_node chia.server.start_service: ERROR    fatal uncaught exception: RuntimeError: BlockStore does not support database schema v1
Traceback (most recent call last):
  File "chia\util\log_exceptions.py", line 20, in log_exceptions
  File "chia\server\start_service.py", line 321, in async_run
  File "asyncio\runners.py", line 44, in run
  File "asyncio\base_events.py", line 649, in run_until_complete
  File "chia\server\start_full_node.py", line 83, in async_main
  File "chia\server\start_service.py", line 195, in run
  File "contextlib.py", line 199, in __aenter__
  File "chia\server\start_service.py", line 212, in manage
  File "contextlib.py", line 619, in enter_async_context
  File "contextlib.py", line 199, in __aenter__
  File "chia\full_node\full_node.py", line 259, in manage
  File "chia\full_node\block_store.py", line 49, in create
RuntimeError: BlockStore does not support database schema v1

2024-02-06T22:45:13.788 wallet chia.server.start_service  : ERROR    fatal uncaught exception: AttributeError: 'int' object has no attribute 'name'
Traceback (most recent call last):
  File "chia\util\log_exceptions.py", line 20, in log_exceptions
  File "chia\server\start_service.py", line 321, in async_run
  File "asyncio\runners.py", line 44, in run
  File "asyncio\base_events.py", line 636, in run_until_complete
  File "asyncio\windows_events.py", line 321, in run_forever
  File "asyncio\base_events.py", line 603, in run_forever
  File "asyncio\base_events.py", line 1871, in _run_once
  File "asyncio\windows_events.py", line 444, in select
  File "asyncio\windows_events.py", line 797, in _poll
  File "chia\server\start_service.py", line 309, in _accept_signal
AttributeError: 'int' object has no attribute 'name'

2024-02-06T22:45:16.294 farmer chia.server.start_service  : ERROR    fatal uncaught exception: AttributeError: 'int' object has no attribute 'name'
Traceback (most recent call last):
  File "chia\util\log_exceptions.py", line 20, in log_exceptions
  File "chia\server\start_service.py", line 321, in async_run
  File "asyncio\runners.py", line 44, in run
  File "asyncio\base_events.py", line 636, in run_until_complete
  File "asyncio\windows_events.py", line 321, in run_forever
  File "asyncio\base_events.py", line 603, in run_forever
  File "asyncio\base_events.py", line 1871, in _run_once
  File "asyncio\windows_events.py", line 444, in select
  File "asyncio\windows_events.py", line 797, in _poll
  File "chia\server\start_service.py", line 309, in _accept_signal
AttributeError: 'int' object has no attribute 'name'

2024-02-06T22:45:16.803 harvester chia.server.start_service: ERROR    fatal uncaught exception: AttributeError: 'int' object has no attribute 'name'
Traceback (most recent call last):
  File "chia\util\log_exceptions.py", line 20, in log_exceptions
  File "chia\server\start_service.py", line 321, in async_run
  File "asyncio\runners.py", line 44, in run
  File "asyncio\base_events.py", line 636, in run_until_complete
  File "asyncio\windows_events.py", line 321, in run_forever
  File "asyncio\base_events.py", line 603, in run_forever
  File "asyncio\base_events.py", line 1871, in _run_once
  File "asyncio\windows_events.py", line 444, in select
  File "asyncio\windows_events.py", line 797, in _poll
  File "chia\server\start_service.py", line 309, in _accept_signal
AttributeError: 'int' object has no attribute 'name'

**Comment by emlowe** [comment]
@deltasigm4 You have the V1 DB and you need to upgrade to V2 `RuntimeError: BlockStore does not support database schema v1`

You can find some help on how to do this here: https://docs.chia.net/faq/#what-is-the-new-database
