### ISSUE TITLE
[Bug] ERROR    fatal uncaught exception: AttributeError: 'int' object has no attribute 'name'

### ISSUE THREAD

**Issue by Svetyr1** [Chia-Network/chia-blockchain#17578]
### What happened?

One of the seven wallets does not sync. The rest work fine.

### Version

2.1.4

### What platform are you using?

Windows

### What ui mode are you using?

GUI

### Relevant log output

```shell
2024-02-18T13:23:31.237 wallet chia.server.start_service  : ERROR    fatal uncaught exception: AttributeError: 'int' object has no attribute 'name'
Traceback (most recent call last):
  File "chia\util\log_exceptions.py", line 20, in log_exceptions
  File "chia\server\start_service.py", line 321, in async_run
  File "asyncio\runners.py", line 44, in run
  File "asyncio\base_events.py", line 636, in run_until_complete
  File "asyncio\windows_events.py", line 321, in run_forever
  File "asyncio\base_events.py", line 603, in run_forever
  File "asyncio\base_events.py", line 1871, in _run_once
  File "asyncio\windows_events.py", line 444, in select
  File "asyncio\windows_events.py", line 797, in _poll
  File "chia\server\start_service.py", line 309, in _accept_signal
AttributeError: 'int' object has no attribute 'name'
```

**Comment by wjblanke** [comment]
This should be fixed in main. Let us know if you still see the issue in main. Thanks for the report!

https://github.com/Chia-Network/chia-blockchain/pull/17123

**Comment by Svetyr1** [comment]
> Это должно быть исправлено в main. Дайте нам знать, если вы все еще видите проблему в файле main. Спасибо за отчет!
> 
> #17123

Thank you, it works!
