### ISSUE TITLE
[BUG] plotfiles not available for farming when a mapped drive is missing

### ISSUE THREAD

**Issue by LoudSyncro** [Chia-Network/chia-blockchain#1759]
**Describe the bug**

When a mapped network drive is listed in config.yaml, but it is not available during chia startup, then **no** plots (including local plot files) are available to chia for farming.

This affects GUI and CLI.

**To Reproduce**

1. Add fake network drive to config.yaml (e.g. \\192.168.178.95\\E\\chia)
2. Shutdown Chia

For GUI:
1. Start Chia GUI
2. A popup with "22" appears
3. check for plots in GUI: No plots are shown at all

For CLI:
1. start Chia: ./chia start farmer
2. wait for services being started 
3. Do: ./chia plots show
4. See error message: [2360] Failed to execute script chia
```
 Directories where plots are being searched for:
Note that subdirectories must be added manually
Add with 'chia plots add -d [dir]' and remove with 'chia plots remove -d [dir]' Scan and check plots with 'chia plots check'

Traceback (most recent call last):
  File "src\cmds\chia.py", line 80, in <module>
  File "src\cmds\chia.py", line 76, in main
  File "click\core.py", line 829, in __call__
  File "click\core.py", line 782, in main
  File "click\core.py", line 1259, in invoke
  File "click\core.py", line 1259, in invoke
  File "click\core.py", line 1066, in invoke
  File "click\core.py", line 610, in invoke
  File "click\decorators.py", line 21, in new_func
  File "src\cmds\plots.py", line 189, in show_cmd
  File "src\cmds\plots.py", line 25, in show_plots
  File "src\plotting\plot_tools.py", line 116, in get_plot_directories
  File "src\plotting\plot_tools.py", line 116, in <listcomp>
  File "pathlib.py", line 1166, in resolve
  File "pathlib.py", line 205, in resolve
OSError: [WinError 1326] Username or password wrong: '\\\\192.168.178.95\\E\\chia'
[2360] Failed to execute script chia
```

**Expected behavior**
1) Proper error handling of Error [2360] / [WinError 1326]  in GUI and CLI, so that a missing network drive cannot break the chia script.
2) Furthermore a meaningfull error / info message to the user would about a missing (network)drive out of the config.yaml makes sense.

**Screenshots**
![2021-04-08 07_20_49-Chia Blockchain](https://user-images.githubusercontent.com/82137080/113978604-6d119900-9844-11eb-82a5-d3d4e3868bc1.png)
![2021-04-08 07_52_20-Administrator_ Windows PowerShell](https://user-images.githubusercontent.com/82137080/113978622-713db680-9844-11eb-8e74-e3100b23a727.png)

**Desktop (please complete the following information):**

- OS: Win10 Pro
- Chia Version 1.0.3

**Additional context**

**Comment by aqk** [comment]
Thanks for your bug report. This has been entered in our bug tracker for triage.
