### ISSUE TITLE
Missing script: "electron"

### ISSUE THREAD

**Issue by zerbrecht** [Chia-Network/chia-blockchain#17612]
### What happened?

How can I fix this?  I tried to . ./activate and then run "npm run electron &" but still running into this same issue. Is there a script I can run to fix this?

m ERR! Missing script: "electron"
npm ERR! 
npm ERR! To see a list of scripts, run:
npm ERR!   npm run

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/zachary/.npm/_logs/2024-02-28T02_08_50_498Z-debug-0.log

### Version

2.1.5.dev0

### What platform are you using?

Linux

### What ui mode are you using?

GUI

### Relevant log output

```shell
0 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'electron' ]
1 info using npm@8.5.1
2 info using node@v12.22.9
3 timing npm:load:whichnode Completed in 1ms
4 timing config:load:defaults Completed in 3ms
5 timing config:load:file:/usr/share/nodejs/npm/npmrc Completed in 4ms
6 timing config:load:builtin Completed in 4ms
7 timing config:load:cli Completed in 3ms
8 timing config:load:env Completed in 1ms
9 timing config:load:file:/media/zachary/SSD2/zachary/chia-blockchain/chia-blockchain-gui/.npmrc Completed in 0ms
10 timing config:load:project Completed in 5ms
11 timing config:load:file:/home/zachary/.npmrc Completed in 0ms
12 timing config:load:user Completed in 1ms
13 timing config:load:file:/etc/npmrc Completed in 0ms
14 timing config:load:global Completed in 0ms
15 timing config:load:validate Completed in 1ms
16 timing config:load:credentials Completed in 1ms
17 timing config:load:setEnvs Completed in 1ms
18 timing config:load Completed in 21ms
19 timing npm:load:configload Completed in 21ms
20 timing npm:load:setTitle Completed in 0ms
21 timing config:load:flatten Completed in 4ms
22 timing npm:load:display Completed in 8ms
23 verbose logfile /home/zachary/.npm/_logs/2024-02-28T02_08_50_498Z-debug-0.log
24 timing npm:load:logFile Completed in 8ms
25 timing npm:load:timers Completed in 0ms
26 timing npm:load:configScope Completed in 0ms
27 timing npm:load Completed in 38ms
28 silly logfile start cleaning logs, removing 1 files
29 timing command:run Completed in 7ms
30 verbose stack Error: Missing script: "electron"
30 verbose stack
30 verbose stack To see a list of scripts, run:
30 verbose stack   npm run
30 verbose stack     at RunScript.run (/usr/share/nodejs/npm/lib/commands/run-script.js:95:13)
30 verbose stack     at async module.exports (/usr/share/nodejs/npm/lib/cli.js:66:5)
31 verbose cwd /media/zachary/SSD2/zachary/chia-blockchain/chia-blockchain-gui
32 verbose Linux 6.5.0-21-generic
33 verbose argv "/usr/bin/node" "/usr/bin/npm" "run" "electron"
34 verbose node v12.22.9
35 verbose npm  v8.5.1
36 error Missing script: "electron"
36 error
36 error To see a list of scripts, run:
36 error   npm run
37 verbose exit 1
38 timing npm Completed in 286ms
39 verbose code 1
40 error A complete log of this run can be found in:
40 error     /home/zachary/.npm/_logs/2024-02-28T02_08_50_498Z-debug-0.log
```

**Comment by wjblanke** [comment]
You need to run install-gui.sh script after activate.

**Comment by zerbrecht** [comment]
I did do this and keep running into this issue.

**Comment by zerbrecht** [comment]
It keeps stating that the electron script keeps failing.
