### ISSUE TITLE
GUI Opens, nothing happens

### ISSUE THREAD

**Issue by BobyMartinez** [Chia-Network/chia-blockchain#17633]
### What happened?

Hello,

I updated Chia to the last version and updated the DB with the V2. Since then running in a lot of trouble, unable to sync it... so uninstalled everything, erased all the chia files, all database.... literally everything (of course keeping a copy of the DB) and tried to reinstall Chia. The GUI opens, I put my 24 word passphrase, go on the main page but not sync (switch between not sync and sync 0/5.000.000), my chia collected shows 0 and unable to find any of my plots.
Tried to find a similar issue but last posted is from 2021 and not solving my problems

I put the log output for more details. First problems says "no key present" but I've put my key and accessed to the main page

Thanks for the help

### Version

2.1.4

### What platform are you using?

Windows

### What ui mode are you using?

GUI

### Relevant log output

```shell
2024-03-02T00:04:53.797 wallet chia.wallet.wallet_node    : WARNING  No keys present. Create keys with the UI, or with the 'chia keys' program.
2024-03-02T00:04:54.624 wallet chia.rpc.rpc_server        : WARNING  Error while handling message: Traceback (most recent call last):
  File "chia\rpc\rpc_server.py", line 325, in safe_handle
  File "chia\rpc\rpc_server.py", line 316, in ws_api
  File "chia\rpc\wallet_rpc_api.py", line 1416, in get_notifications
  File "chia\wallet\wallet_node.py", line 178, in wallet_state_manager
RuntimeError: wallet state manager not assigned

2024-03-02T00:04:54.624 wallet chia.rpc.rpc_server        : WARNING  Error while handling message: Traceback (most recent call last):
  File "chia\rpc\rpc_server.py", line 325, in safe_handle
  File "chia\rpc\rpc_server.py", line 316, in ws_api
  File "chia\rpc\wallet_rpc_api.py", line 560, in get_sync_status
  File "chia\wallet\wallet_node.py", line 178, in wallet_state_manager
RuntimeError: wallet state manager not assigned

2024-03-02T00:04:54.624 wallet chia.rpc.rpc_server        : WARNING  Error while handling message: Traceback (most recent call last):
  File "chia\rpc\rpc_server.py", line 325, in safe_handle
  File "chia\rpc\rpc_server.py", line 316, in ws_api
  File "chia\rpc\wallet_rpc_api.py", line 635, in get_wallets
  File "chia\wallet\wallet_node.py", line 178, in wallet_state_manager
RuntimeError: wallet state manager not assigned

2024-03-02T00:04:59.154 farmer chia.farmer.farmer         : WARNING  No keys exist. Please run 'chia keys generate' or open the UI.
2024-03-02T00:05:00.228 farmer chia.farmer.farmer         : WARNING  No keys exist. Please run 'chia keys generate' or open the UI.
2024-03-02T00:05:01.281 farmer chia.farmer.farmer         : WARNING  No keys exist. Please run 'chia keys generate' or open the UI.
2024-03-02T00:05:02.230 wallet wallet_server              : WARNING  API not ready, ignore request: {'data': '0xbfad0b8c8c24977b61d5a828ff3bcfbd9808a88a44397dfde4b86561db72cd42004c95c3000000000000000000000003b57948d0004c95c3',
 'id': None,
 'type': 50}
2024-03-02T00:05:02.342 farmer chia.farmer.farmer         : WARNING  No keys exist. Please run 'chia keys generate' or open the UI.
2024-03-02T00:05:02.475 wallet wallet_server              : WARNING  API not ready, ignore request: {'data': '0xbfad0b8c8c24977b61d5a828ff3bcfbd9808a88a44397dfde4b86561db72cd42004c95c3000000000000000000000003b57948d0004c95c3',
 'id': None,
 'type': 50}
2024-03-02T00:05:03.091 wallet wallet_server              : WARNING  API not ready, ignore request: {'data': '0x018888ef3ebf72914c6b992830645b9ed017105504e9b8d591fedd4e2ba5fa3a004a7925000000000000000000000003536b20d0004a7925',
 'id': None,
 'type': 50}
2024-03-02T00:05:03.414 farmer chia.farmer.farmer         : WARNING  No keys exist. Please run 'chia keys generate' or open the UI.
2024-03-02T00:05:04.492 farmer chia.farmer.farmer         : WARNING  No keys exist. Please run 'chia keys generate' or open the UI.
2024-03-02T00:05:04.649 wallet chia.rpc.rpc_server        : WARNING  Error while handling message: Traceback (most recent call last):
  File "chia\rpc\rpc_server.py", line 325, in safe_handle
  File "chia\rpc\rpc_server.py", line 316, in ws_api
  File "chia\rpc\wallet_rpc_api.py", line 560, in get_sync_status
  File "chia\wallet\wallet_node.py", line 178, in wallet_state_manager
RuntimeError: wallet state manager not assigned

2024-03-02T00:05:05.561 farmer chia.farmer.farmer         : WARNING  No keys exist. Please run 'chia keys generate' or open the UI.
2024-03-02T00:05:06.644 farmer chia.farmer.farmer         : WARNING  No keys exist. Please run 'chia keys generate' or open the UI.
2024-03-02T00:05:07.723 farmer chia.farmer.farmer         : WARNING  No keys exist. Please run 'chia keys generate' or open the UI.
2024-03-02T00:05:08.800 farmer chia.farmer.farmer         : WARNING  No keys exist. Please run 'chia keys generate' or open the UI.
2024-03-02T00:05:09.487 wallet wallet_server              : ERROR    Caught exception: RuntimeError: wallet state manager not assigned
Traceback (most recent call last):
  File "chia\util\log_exceptions.py", line 20, in log_exceptions
  File "chia\server\ws_connection.py", line 310, in close
  File "chia\server\server.py", line 558, in connection_closed
  File "chia\wallet\wallet_node.py", line 706, in on_disconnect
  File "chia\wallet\wallet_node.py", line 178, in wallet_state_manager
RuntimeError: wallet state manager not assigned

2024-03-02T00:05:09.488 wallet wallet_server              : ERROR    Caught exception: RuntimeError: wallet state manager not assigned
Traceback (most recent call last):
  File "chia\util\log_exceptions.py", line 20, in log_exceptions
  File "chia\server\ws_connection.py", line 310, in close
  File "chia\server\server.py", line 558, in connection_closed
  File "chia\wallet\wallet_node.py", line 706, in on_disconnect
  File "chia\wallet\wallet_node.py", line 178, in wallet_state_manager
RuntimeError: wallet state manager not assigned

2024-03-02T00:05:09.490 wallet wallet_server              : ERROR    Caught exception: RuntimeError: wallet state manager not assigned
Traceback (most recent call last):
  File "chia\util\log_exceptions.py", line 20, in log_exceptions
  File "chia\server\ws_connection.py", line 310, in close
  File "chia\server\server.py", line 558, in connection_closed
  File "chia\wallet\wallet_node.py", line 706, in on_disconnect
  File "chia\wallet\wallet_node.py", line 178, in wallet_state_manager
RuntimeError: wallet state manager not assigned

2024-03-02T00:05:09.490 wallet wallet_server              : ERROR    Caught exception: RuntimeError: wallet state manager not assigned
Traceback (most recent call last):
  File "chia\util\log_exceptions.py", line 20, in log_exceptions
  File "chia\server\ws_connection.py", line 310, in close
  File "chia\server\server.py", line 558, in connection_closed
  File "chia\wallet\wallet_node.py", line 706, in on_disconnect
  File "chia\wallet\wallet_node.py", line 178, in wallet_state_manager
RuntimeError: wallet state manager not assigned

2024-03-02T00:06:49.907 wallet chia.wallet.wallet_node    : ERROR    Error syncing to None
Traceback (most recent call last):
  File "chia\wallet\wallet_node.py", line 1167, in new_peak_from_untrusted
  File "chia\wallet\wallet_node.py", line 1176, in long_sync_from_untrusted
  File "chia\wallet\wallet_node.py", line 1300, in fetch_and_update_weight_proof
Exception: weight proof response was none
2024-03-02T00:06:54.066 full_node full_node_server        : WARNING  Banning 213.108.88.129 for 600 seconds
2024-03-02T00:06:54.066 full_node chia.full_node.full_node: ERROR    Error with syncing: <class 'RuntimeError'>Traceback (most recent call last):
  File "chia\full_node\full_node.py", line 974, in _sync
  File "chia\full_node\full_node.py", line 1015, in request_validate_wp
RuntimeError: Weight proof did not arrive in time from peer: 213.108.88.129

2024-03-02T00:08:31.701 wallet chia.wallet.wallet_node    : ERROR    Error syncing to None
Traceback (most recent call last):
  File "chia\wallet\wallet_node.py", line 1167, in new_peak_from_untrusted
  File "chia\wallet\wallet_node.py", line 1176, in long_sync_from_untrusted
  File "chia\wallet\wallet_node.py", line 1300, in fetch_and_update_weight_proof
Exception: weight proof response was none
2024-03-02T00:08:31.702 wallet chia.wallet.wallet_node    : WARNING  Peer None did not respond in time.
2024-03-02T00:08:31.703 wallet wallet_server              : WARNING  Banning 87.121.21.184 for 120 seconds
2024-03-02T00:08:41.998 full_node full_node_server        : WARNING  Banning 91.58.137.1 for 600 seconds
2024-03-02T00:08:41.998 full_node chia.full_node.full_node: ERROR    Error with syncing: <class 'RuntimeError'>Traceback (most recent call last):
  File "chia\full_node\full_node.py", line 974, in _sync
  File "chia\full_node\full_node.py", line 1015, in request_validate_wp
RuntimeError: Weight proof did not arrive in time from peer: 91.58.137.1

2024-03-02T00:10:04.618 wallet chia.wallet.wallet_node    : ERROR    Error syncing to None
Traceback (most recent call last):
  File "chia\wallet\wallet_node.py", line 1167, in new_peak_from_untrusted
  File "chia\wallet\wallet_node.py", line 1176, in long_sync_from_untrusted
  File "chia\wallet\wallet_node.py", line 1300, in fetch_and_update_weight_proof
Exception: weight proof response was none
2024-03-02T00:10:04.618 wallet chia.wallet.wallet_node    : WARNING  Peer None did not respond in time.
2024-03-02T00:10:04.618 wallet wallet_server              : WARNING  Banning 114.230.221.56 for 120 seconds
2024-03-02T00:10:04.633 wallet chia.wallet.wallet_node    : WARNING  Peer None did not respond in time.
2024-03-02T00:10:04.633 wallet wallet_server              : WARNING  Banning 114.230.221.56 for 120 seconds
2024-03-02T00:10:04.633 wallet chia.wallet.wallet_node    : WARNING  Peer None did not respond in time.
2024-03-02T00:10:04.633 wallet wallet_server              : WARNING  Banning 46.55.211.235 for 120 seconds
2024-03-02T00:10:04.633 wallet chia.wallet.wallet_node    : WARNING  Peer None did not respond in time.
2024-03-02T00:10:04.633 wallet wallet_server              : WARNING  Banning 114.230.221.56 for 120 seconds
2024-03-02T00:10:04.633 wallet chia.wallet.wallet_node    : WARNING  Peer None did not respond in time.
2024-03-02T00:10:04.633 wallet wallet_server              : WARNING  Banning 46.55.211.235 for 120 seconds
2024-03-02T00:10:04.633 wallet chia.wallet.wallet_node    : WARNING  Peer None did not respond in time.
2024-03-02T00:10:04.633 wallet wallet_server              : WARNING  Banning 114.230.221.56 for 120 seconds
2024-03-02T00:10:04.633 wallet chia.wallet.wallet_node    : WARNING  Peer None did not respond in time.
2024-03-02T00:10:04.633 wallet wallet_server              : WARNING  Banning 46.55.211.235 for 120 seconds
2024-03-02T00:10:04.633 wallet chia.wallet.wallet_node    : WARNING  Peer None did not respond in time.
2024-03-02T00:10:04.633 wallet wallet_server              : WARNING  Banning 46.55.211.235 for 120 seconds
2024-03-02T00:10:04.633 wallet chia.wallet.wallet_node    : WARNING  Peer None did not respond in time.
2024-03-02T00:10:04.633 wallet wallet_server              : WARNING  Banning 46.55.211.235 for 120 seconds
2024-03-02T00:10:04.633 wallet chia.wallet.wallet_node    : WARNING  Peer None did not respond in time.
2024-03-02T00:10:04.633 wallet wallet_server              : WARNING  Banning 46.55.211.235 for 120 seconds
2024-03-02T00:10:37.028 full_node full_node_server        : WARNING  Banning 24.15.67.0 for 600 seconds
2024-03-02T00:10:37.029 full_node chia.full_node.full_node: ERROR    Error with syncing: <class 'RuntimeError'>Traceback (most recent call last):
  File "chia\full_node\full_node.py", line 974, in _sync
  File "chia\full_node\full_node.py", line 1015, in request_validate_wp
RuntimeError: Weight proof did not arrive in time from peer: 24.15.67.0

2024-03-02T00:11:39.753 wallet chia.wallet.wallet_node    : ERROR    Error syncing to None
Traceback (most recent call last):
  File "chia\wallet\wallet_node.py", line 1167, in new_peak_from_untrusted
  File "chia\wallet\wallet_node.py", line 1176, in long_sync_from_untrusted
  File "chia\wallet\wallet_node.py", line 1300, in fetch_and_update_weight_proof
Exception: weight proof response was none
2024-03-02T00:11:39.753 wallet chia.wallet.wallet_node    : WARNING  Peer None did not respond in time.
2024-03-02T00:11:39.753 wallet wallet_server              : WARNING  Banning 46.55.211.235 for 120 seconds
2024-03-02T00:11:39.753 wallet chia.wallet.wallet_node    : WARNING  Peer None did not respond in time.
2024-03-02T00:11:39.753 wallet wallet_server              : WARNING  Banning 181.31.86.126 for 120 seconds
2024-03-02T00:11:39.753 wallet chia.wallet.wallet_node    : WARNING  Peer None did not respond in time.
2024-03-02T00:11:39.753 wallet wallet_server              : WARNING  Banning 181.31.86.126 for 120 seconds
2024-03-02T00:11:39.753 wallet chia.wallet.wallet_node    : WARNING  Peer None did not respond in time.
2024-03-02T00:11:39.753 wallet wallet_server              : WARNING  Banning 181.31.86.126 for 120 seconds
2024-03-02T00:12:18.546 full_node full_node_server        : WARNING  Banning 172.250.33.180 for 600 seconds
2024-03-02T00:12:18.546 full_node chia.full_node.full_node: ERROR    Error with syncing: <class 'RuntimeError'>Traceback (most recent call last):
  File "chia\full_node\full_node.py", line 974, in _sync
  File "chia\full_node\full_node.py", line 1015, in request_validate_wp
RuntimeError: Weight proof did not arrive in time from peer: 172.250.33.180

2024-03-02T00:13:12.528 wallet chia.wallet.wallet_node    : ERROR    Error syncing to None
Traceback (most recent call last):
  File "chia\wallet\wallet_node.py", line 1167, in new_peak_from_untrusted
  File "chia\wallet\wallet_node.py", line 1176, in long_sync_from_untrusted
  File "chia\wallet\wallet_node.py", line 1300, in fetch_and_update_weight_proof
Exception: weight proof response was none
2024-03-02T00:13:12.529 wallet chia.wallet.wallet_node    : WARNING  Peer None did not respond in time.
2024-03-02T00:13:12.529 wallet wallet_server              : WARNING  Banning 181.31.86.126 for 120 seconds
2024-03-02T00:13:12.530 wallet chia.wallet.wallet_node    : WARNING  Peer None did not respond in time.
2024-03-02T00:13:12.531 wallet wallet_server              : WARNING  Banning 174.49.44.152 for 120 seconds
2024-03-02T00:13:12.531 wallet chia.wallet.wallet_node    : WARNING  Peer None did not respond in time.
2024-03-02T00:13:12.532 wallet wallet_server              : WARNING  Banning 174.49.44.152 for 120 seconds
2024-03-02T00:13:12.533 wallet chia.wallet.wallet_node    : WARNING  Peer None did not respond in time.
2024-03-02T00:13:12.534 wallet wallet_server              : WARNING  Banning 174.49.44.152 for 120 seconds
2024-03-02T00:13:12.534 wallet chia.wallet.wallet_node    : WARNING  Peer None did not respond in time.
2024-03-02T00:13:12.535 wallet wallet_server              : WARNING  Banning 174.49.44.152 for 120 seconds
2024-03-02T00:13:12.535 wallet chia.wallet.wallet_node    : WARNING  Peer None did not respond in time.
2024-03-02T00:13:12.536 wallet wallet_server              : WARNING  Banning 174.49.44.152 for 120 seconds
2024-03-02T00:13:12.536 wallet chia.wallet.wallet_node    : WARNING  Peer None did not respond in time.
2024-03-02T00:13:12.537 wallet wallet_server              : WARNING  Banning 174.49.44.152 for 120 seconds
2024-03-02T00:13:12.538 wallet chia.wallet.wallet_node    : WARNING  Peer None did not respond in time.
2024-03-02T00:13:12.538 wallet wallet_server              : WARNING  Banning 174.49.44.152 for 120 seconds
2024-03-02T00:14:00.937 full_node full_node_server        : WARNING  Banning 114.218.23.246 for 600 seconds
2024-03-02T00:14:00.937 full_node chia.full_node.full_node: ERROR    Error with syncing: <class 'RuntimeError'>Traceback (most recent call last):
  File "chia\full_node\full_node.py", line 974, in _sync
  File "chia\full_node\full_node.py", line 1015, in request_validate_wp
RuntimeError: Weight proof did not arrive in time from peer: 114.218.23.246

2024-03-02T00:14:44.820 wallet chia.wallet.wallet_node    : ERROR    Error syncing to None
Traceback (most recent call last):
  File "chia\wallet\wallet_node.py", line 1167, in new_peak_from_untrusted
  File "chia\wallet\wallet_node.py", line 1176, in long_sync_from_untrusted
  File "chia\wallet\wallet_node.py", line 1300, in fetch_and_update_weight_proof
Exception: weight proof response was none
2024-03-02T00:14:44.835 wallet chia.wallet.wallet_node    : WARNING  Peer None did not respond in time.
2024-03-02T00:14:44.835 wallet wallet_server              : WARNING  Banning 83.219.130.77 for 120 seconds
2024-03-02T00:15:50.036 full_node full_node_server        : WARNING  Banning 223.108.78.126 for 600 seconds
2024-03-02T00:15:50.036 full_node chia.full_node.full_node: ERROR    Error with syncing: <class 'RuntimeError'>Traceback (most recent call last):
  File "chia\full_node\full_node.py", line 974, in _sync
  File "chia\full_node\full_node.py", line 1015, in request_validate_wp
RuntimeError: Weight proof did not arrive in time from peer: 223.108.78.126

2024-03-02T00:16:18.943 wallet chia.wallet.wallet_node    : ERROR    Error syncing to None
Traceback (most recent call last):
  File "chia\wallet\wallet_node.py", line 1167, in new_peak_from_untrusted
  File "chia\wallet\wallet_node.py", line 1176, in long_sync_from_untrusted
  File "chia\wallet\wallet_node.py", line 1300, in fetch_and_update_weight_proof
Exception: weight proof response was none
2024-03-02T00:16:21.161 wallet chia.wallet.wallet_node    : WARNING  Non-trusted peer PeerInfo(_ip=IPv4Address('32.216.58.156'), _port=8444) is not synced, disconnecting
2024-03-02T00:16:21.161 wallet wallet_server              : WARNING  Banning 32.216.58.156 for 120 seconds
2024-03-02T00:16:21.161 wallet chia.wallet.wallet_node    : WARNING  Peer PeerInfo(_ip=IPv4Address('32.216.58.156'), _port=8444) did not respond in time.
2024-03-02T00:16:21.161 wallet wallet_server              : WARNING  Banning 32.216.58.156 for 120 seconds
2024-03-02T00:16:21.161 wallet chia.wallet.wallet_node    : WARNING  Peer PeerInfo(_ip=IPv4Address('32.216.58.156'), _port=8444) did not respond in time.
2024-03-02T00:16:21.161 wallet wallet_server              : WARNING  Banning 32.216.58.156 for 120 seconds
2024-03-02T00:16:21.161 wallet chia.wallet.wallet_node    : WARNING  Peer None did not respond in time.
2024-03-02T00:16:21.161 wallet wallet_server              : WARNING  Banning 49.64.78.70 for 120 seconds
2024-03-02T00:16:21.161 wallet chia.wallet.wallet_node    : WARNING  Peer None did not respond in time.
2024-03-02T00:16:21.161 wallet wallet_server              : WARNING  Banning 49.64.78.70 for 120 seconds
2024-03-02T00:16:21.161 wallet chia.wallet.wallet_node    : WARNING  Peer None did not respond in time.
2024-03-02T00:16:21.161 wallet wallet_server              : WARNING  Banning 49.64.78.70 for 120 seconds
2024-03-02T00:17:26.723 full_node full_node_server        : WARNING  Banning 89.148.44.219 for 600 seconds
2024-03-02T00:17:26.723 full_node chia.full_node.full_node: ERROR    Error with syncing: <class 'RuntimeError'>Traceback (most recent call last):
  File "chia\full_node\full_node.py", line 974, in _sync
  File "chia\full_node\full_node.py", line 1015, in request_validate_wp
RuntimeError: Weight proof did not arrive in time from peer: 89.148.44.219

2024-03-02T00:18:02.049 wallet chia.wallet.wallet_node    : ERROR    Error syncing to None
Traceback (most recent call last):
  File "chia\wallet\wallet_node.py", line 1167, in new_peak_from_untrusted
  File "chia\wallet\wallet_node.py", line 1176, in long_sync_from_untrusted
  File "chia\wallet\wallet_node.py", line 1300, in fetch_and_update_weight_proof
Exception: weight proof response was none
2024-03-02T00:18:05.061 wallet chia.server.start_service  : ERROR    fatal uncaught exception: AttributeError: 'int' object has no attribute 'name'
Traceback (most recent call last):
  File "chia\util\log_exceptions.py", line 20, in log_exceptions
  File "chia\server\start_service.py", line 321, in async_run
  File "asyncio\runners.py", line 44, in run
  File "asyncio\base_events.py", line 636, in run_until_complete
  File "asyncio\windows_events.py", line 321, in run_forever
  File "asyncio\base_events.py", line 603, in run_forever
  File "asyncio\base_events.py", line 1871, in _run_once
  File "asyncio\windows_events.py", line 444, in select
  File "asyncio\windows_events.py", line 797, in _poll
  File "chia\server\start_service.py", line 309, in _accept_signal
AttributeError: 'int' object has no attribute 'name'

2024-03-02T00:18:05.559 harvester chia.server.start_service: ERROR    fatal uncaught exception: AttributeError: 'int' object has no attribute 'name'
Traceback (most recent call last):
  File "chia\util\log_exceptions.py", line 20, in log_exceptions
  File "chia\server\start_service.py", line 321, in async_run
  File "asyncio\runners.py", line 44, in run
  File "asyncio\base_events.py", line 636, in run_until_complete
  File "asyncio\windows_events.py", line 321, in run_forever
  File "asyncio\base_events.py", line 603, in run_forever
  File "asyncio\base_events.py", line 1871, in _run_once
  File "asyncio\windows_events.py", line 444, in select
  File "asyncio\windows_events.py", line 797, in _poll
  File "chia\server\start_service.py", line 309, in _accept_signal
AttributeError: 'int' object has no attribute 'name'

2024-03-02T00:18:06.073 farmer chia.server.start_service  : ERROR    fatal uncaught exception: AttributeError: 'int' object has no attribute 'name'
Traceback (most recent call last):
  File "chia\util\log_exceptions.py", line 20, in log_exceptions
  File "chia\server\start_service.py", line 321, in async_run
  File "asyncio\runners.py", line 44, in run
  File "asyncio\base_events.py", line 636, in run_until_complete
  File "asyncio\windows_events.py", line 321, in run_forever
  File "asyncio\base_events.py", line 603, in run_forever
  File "asyncio\base_events.py", line 1871, in _run_once
  File "asyncio\windows_events.py", line 444, in select
  File "asyncio\windows_events.py", line 797, in _poll
  File "chia\server\start_service.py", line 309, in _accept_signal
AttributeError: 'int' object has no attribute 'name'

2024-03-02T00:18:06.569 full_node chia.full_node.full_node: WARNING  Syncing failed, CancelledError
2024-03-02T00:18:06.641 full_node chia.server.start_service: ERROR    fatal uncaught exception: AttributeError: 'int' object has no attribute 'name'
Traceback (most recent call last):
  File "chia\util\log_exceptions.py", line 20, in log_exceptions
  File "chia\server\start_service.py", line 321, in async_run
  File "asyncio\runners.py", line 44, in run
  File "asyncio\base_events.py", line 636, in run_until_complete
  File "asyncio\windows_events.py", line 321, in run_forever
  File "asyncio\base_events.py", line 603, in run_forever
  File "asyncio\base_events.py", line 1871, in _run_once
  File "asyncio\windows_events.py", line 444, in select
  File "asyncio\windows_events.py", line 797, in _poll
  File "chia\server\start_service.py", line 309, in _accept_signal
AttributeError: 'int' object has no attribute 'name'
```

**Comment by wjblanke** [comment]
Did you try rebooting your system? Possibly some old services from a previous install are still running.
