### ISSUE TITLE
[Bug] ERROR Exception: Failed to validate block

### ISSUE THREAD

**Issue by d1m1trus** [Chia-Network/chia-blockchain#17685]
### What happened?

Because of this error, synchronization is lost. This happens very often. There is no regularity. It started after the 2.2.0 release.

### Version

2.2.2-dev195

### What platform are you using?

Linux

### What ui mode are you using?

CLI

### Relevant log output

```shell
2024-03-11T00:09:15.576 full_node full_node_server        : ERROR    Exception: Failed to validate block b'\xdb\xe4\xd7<\x88+\xe8B\xe1\x18\xa7\xdc\xd9wY\x80e\x1av\xc80a\xb5\x00\x0f\x1e\xaat\x84\x12;\x81' height 5060383: INVALID_TRANSACTIONS_FILTER_HASH, PeerInfo(_ip=IPv4Address('67.4.162.143'), _port=8444). Traceback (most recent call last):
  File "/opt/chia_devs/2.2.2-dev195/chia/server/ws_connection.py", line 404, in wrapped_coroutine
    result: Message = await coroutine
                      ^^^^^^^^^^^^^^^
  File "/opt/chia_devs/2.2.2-dev195/chia/full_node/full_node_api.py", line 136, in new_peak
    await self.full_node.new_peak(request, peer)
  File "/opt/chia_devs/2.2.2-dev195/chia/full_node/full_node.py", line 743, in new_peak
    if await self.short_sync_backtrack(
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/chia_devs/2.2.2-dev195/chia/full_node/full_node.py", line 670, in short_sync_backtrack
    await self.add_block(block, peer)
  File "/opt/chia_devs/2.2.2-dev195/chia/full_node/full_node.py", line 1744, in add_block
    raise ValueError(
ValueError: Failed to validate block b'\xdb\xe4\xd7<\x88+\xe8B\xe1\x18\xa7\xdc\xd9wY\x80e\x1av\xc80a\xb5\x00\x0f\x1e\xaat\x84\x12;\x81' height 5060383: INVALID_TRANSACTIONS_FILTER_HASH

2024-03-11T00:09:15.577 full_node full_node_server        : ERROR    Exception: Failed to validate block b'\xdb\xe4\xd7<\x88+\xe8B\xe1\x18\xa7\xdc\xd9wY\x80e\x1av\xc80a\xb5\x00\x0f\x1e\xaat\x84\x12;\x81' height 5060383: INVALID_TRANSACTIONS_FILTER_HASH <class 'ValueError'>, closing connection PeerInfo(_ip=IPv4Address('67.4.162.143'), _port=8444). Traceback (most recent call last):
  File "/opt/chia_devs/2.2.2-dev195/chia/server/ws_connection.py", line 425, in _api_call
    response: Optional[Message] = await asyncio.wait_for(wrapped_coroutine(), timeout=timeout)
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/tasks.py", line 452, in wait_for
    return await fut
           ^^^^^^^^^
  File "/opt/chia_devs/2.2.2-dev195/chia/server/ws_connection.py", line 404, in wrapped_coroutine
    result: Message = await coroutine
                      ^^^^^^^^^^^^^^^
  File "/opt/chia_devs/2.2.2-dev195/chia/full_node/full_node_api.py", line 136, in new_peak
    await self.full_node.new_peak(request, peer)
  File "/opt/chia_devs/2.2.2-dev195/chia/full_node/full_node.py", line 743, in new_peak
    if await self.short_sync_backtrack(
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/chia_devs/2.2.2-dev195/chia/full_node/full_node.py", line 670, in short_sync_backtrack
    await self.add_block(block, peer)
  File "/opt/chia_devs/2.2.2-dev195/chia/full_node/full_node.py", line 1744, in add_block
    raise ValueError(
ValueError: Failed to validate block b'\xdb\xe4\xd7<\x88+\xe8B\xe1\x18\xa7\xdc\xd9wY\x80e\x1av\xc80a\xb5\x00\x0f\x1e\xaat\x84\x12;\x81' height 5060383: INVALID_TRANSACTIONS_FILTER_HASH
```

**Comment by d1m1trus** [comment]
This bug exposed an additional issue in the mechanism for closed banned peers, which causes synchronization loss.  Disconnecting a banned peer should only be done after connecting a new peer for balance.

**Comment by wjblanke** [comment]
This is a known issue in main, we almost have it fixed. 2.2.1 as released should be ok. thanks for your report!

**Comment by d1m1trus** [comment]
> This is a known issue in main, we almost have it fixed. 2.2.1 as released should be ok. thanks for your report!
I'm currently using 2.2.2-dev197, problem not fixed, losing sync 10+ times per hour.

Last synchronization loss:
```
2024-03-13T18:10:49.510 full_node full_node_server        : ERROR    Exception: Failed to validate block b'U\xfd\x8chGR!\xe5\x11\xdf\xf1\xfc\xa81\x84\xdb\xe2,N_\xda\xc6.\x1b"3\x80\xf8\xd1\xb5\x1f\xf0' height 5073195: INVALID_TRANSACTIONS_FILTER_HASH <class 'ValueError'>, closing connection PeerInfo(_ip=IPv4Address('125.26.1.85'), _port=8444). Traceback (most recent call last):
2024-03-13T18:10:49.510 full_node full_node_server        : WARNING  Banning 125.26.1.85 for 10 seconds
```

**Comment by arvidn** [comment]
> I'm currently using 2.2.2-dev197, problem not fixed, losing sync 10+ times per hour.

that's built from `main`, right?

Btw, the fix has landed in `main` now as well, so it should be fixed as of today.

**Comment by d1m1trus** [comment]
> Btw, the fix has landed in `main` now as well, so it should be fixed as of today.

everything seems to be working fine 2.2.2-dev207
