### ISSUE TITLE
RuntimeError: Unknown exception

### ISSUE THREAD

**Issue by bolkinza** [Chia-Network/chia-blockchain#1771]
Starting plotting progress into temporary dirs: C:\chia Ñ„ÐµÑ€Ð¼Ð° and C:\chia Ñ„ÐµÑ€Ð¼Ð°
ID: 80304d34f72c9180814bc0242dac704ffa58fb241c837c5059240fd82c1f6b56
Plot size is: 32
Buffer size is: 6000MiB
Using 128 buckets
Using 8 threads of stripe size 65536
Caught plotting error: Temp directory C:\chia Ñ„ÐµÑ€Ð¼Ð° does not exist
[2648] Failed to execute script chia
Traceback (most recent call last):
  File "src\cmds\chia.py", line 80, in <module>
  File "src\cmds\chia.py", line 76, in main
  File "click\core.py", line 829, in __call__
  File "click\core.py", line 782, in main
  File "click\core.py", line 1259, in invoke
  File "click\core.py", line 1259, in invoke
  File "click\core.py", line 1066, in invoke
  File "click\core.py", line 610, in invoke
  File "click\decorators.py", line 21, in new_func
  File "src\cmds\plots.py", line 134, in create_cmd
  File "src\plotting\create_plots.py", line 176, in create_plots
RuntimeError: Unknown exception

what is this? how to fix it?

**Comment by hoffmang9** [comment]
`Caught plotting error: Temp directory C:\chia Ñ„ÐµÑ€Ð¼Ð° does not exist`

You may need to not use some higher order characters in your directory name or it may not actually exist.
