### ISSUE TITLE
[BUG] error while attempting to bind on address ('::1', 55400, 0, 0): cannot assign requested address closing code: 1

### ISSUE THREAD

**Issue by sigmaprojects** [Chia-Network/chia-blockchain#1775]
**Describe the bug**
Following the instructions "Ubuntu/Debian" at https://github.com/Chia-Network/chia-blockchain/wiki/INSTALL
Get to the "npm run electron &" command and it crashes.

**To Reproduce**
Follow the instructions above

**Expected behavior**
Not crashing

**Screenshots**
Logs below

- OS: Linux
- OS Version/Flavor: Debian 10 (Buster)
- CPU: AMD Ryzen 3600

**Additional context**
```
(venv) sig@rise:~/chia-blockchain/chia-blockchain-gui$ npm run electron &
[1] 31015
(venv) sig@rise:~/chia-blockchain/chia-blockchain-gui$ 
> chia-blockchain@ electron /home/sig/chia-blockchain/chia-blockchain-gui
> electron .

/home/sig/chia-blockchain/app.asar.unpacked/daemon
false
Error loading config - using defaults
/home/sig/chia-blockchain/app.asar.unpacked/daemon
false
/home/sig/chia-blockchain/app.asar.unpacked/daemon
false
Running python script
Script ../src/daemon/server.py
child process success
(node:31034) electron: The default of contextIsolation is deprecated and will be changing from false to true in a future release of Electron.  See https://github.com/electron/electron/issues/23506 for more information
No cert
Have cert
stderr: Traceback (most recent call last):
  File "../src/daemon/server.py", line 954, in <module>
    main()
  File "../src/daemon/server.py", line 950, in main
    return run_daemon(DEFAULT_ROOT_PATH)
  File "../src/daemon/server.py", line 944, in run_daemon
    return asyncio.get_event_loop().run_until_complete(async_run_daemon(root_path))
  File "/usr/lib/python3.7/asyncio/base_events.py", line 584, in run_until_complete
    return future.result()
  File "../src/daemon/server.py", line 936, in async_run_daemon
    await ws_server.start()
  File "../src/daemon/server.py", line 144, in start
    ssl=self.ssl_context,
  File "/home/sig/chia-blockchain/venv/lib/python3.7/site-packages/websockets/server.py", line 965, in __await_impl__
    server = await self._create_server()
  File "/usr/lib/python3.7/asyncio/base_events.py", line 1378, in create_server
    % (sa, err.strerror.lower())) from None
OSError: [Errno 99] error while attempting to bind on address ('::1', 55400, 0, 0): cannot assign requested address
closing code: 1
```

**Comment by sigmaprojects** [comment]
I should note that the port was not in use by any other process

**Comment by iwwwwwwi** [comment]
@sigmaprojects have you seen this comment: https://github.com/Chia-Network/chia-blockchain/issues/1535#issuecomment-808836547

**Comment by sigmaprojects** [comment]
@iwwwwwwi that was exactly the issue.  Thank you.

I'm using the .deb release, so once I edited ~/.chia/mainnet/config/config.yaml and replaced `self_hostname: localhost` with `self_hostname: 127.0.0.1` it started up like normal.  

I'll leave this open so the devs can see it
