### ISSUE TITLE
[BUG] Parallel plotting freezes at midnight, every time

### ISSUE THREAD

**Issue by stonehenge360** [Chia-Network/chia-blockchain#1779]
**Describe the bug**
When plotting [2] K-32s in parallel, both freeze just after midnight.

**Details**
When plotting [2] K-32s in parallel, both freeze just after midnight.  No error code is thrown, the log simply stops progressing.  

**It is always within a half hour of midnight, no matter when the plots were started.**

I have reproduced multiple times using different temp hard drives.  

I have checked power settings on computer -  but single plots never fail so it is not a disk shutoff issue as far as I can tell.

The freeze causes a catastrophic failure of Finder.  Finder must be force quit, and then will not open without a system reboot.

The GUI also freezes when asked to shut down, and hangs on the "closing node" shutdown window indefinitely.

After reboot, the GUI will not load, and hangs on the "connecting to wallet" window.  This requires the .chia hidden file to be deleted.   

Once all this is done, Finder and Chia GUI will boot up, but I have lost my node sync, and need to re-sync the entire node data.  

**Desktop:**

- Computer: iMac [5K, 27", Late 2015]
- OS: MacOS 11.2.3 [Big Sur]
- CPU: 3.3 GHz 4-core i5
- Memory: 32 GB 1600 MHz DDR3

- Temp disk: Samsung 938 NVME 980Gb
- Chia: MacOS Version 1.0.3 GUI

**Comment by hoffmang9** [comment]
How much RAM do you have and are you using the default settings for k32?

**Comment by stonehenge360** [comment]
32 Gb Ram.  Using the default settings.

**Comment by kindjacket** [comment]
Just had a similar issue. But with a single plot. Using the GUI and on MacOS 11.2.3. 32GB of RAM too.

**Comment by kindjacket** [comment]
here's the logs I'm getting from `cat ~/.chia/mainnet/log/debug.log`
`
 File "websockets/protocol.py", line 306, in _drain
  File "websockets/protocol.py", line 1077, in write_frame
  File "websockets/protocol.py", line 306, in _drain
  File "websockets/protocol.py", line 1077, in write_frame
  File "websockets/protocol.py", line 306, in _drain
  File "websockets/protocol.py", line 1077, in write_frame
  File "websockets/protocol.py", line 318, in _drain
  File "websockets/protocol.py", line 299, in _drain_helper
  File "websockets/protocol.py", line 827, in transfer_data
  File "websockets/protocol.py", line 895, in read_message
  File "websockets/protocol.py", line 971, in read_data_frame
  File "websockets/protocol.py", line 1047, in read_frame
  File "websockets/framing.py", line 105, in read
  File "asyncio/streams.py", line 723, in readexactly
  File "asyncio/streams.py", line 517, in _wait_for_data
  File "asyncio/selector_events.py", line 943, in _write_ready
BrokenPipeError: [Errno 32] Broken pipe

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "src/daemon/server.py", line 336, in _state_changed
  File "websockets/protocol.py", line 567, in send
  File "websockets/protocol.py", line 1083, in write_frame
  File "websockets/protocol.py", line 803, in ensure_open
websockets.exceptions.ConnectionClosedError: code = 1006 (connection closed abnormally [internal]), no reason

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "src/daemon/server.py", line 340, in _state_changed
ValueError: list.remove(x): x not in list
`

**Comment by kindjacket** [comment]
Somehow I managed to open it up. My plots weren't lost and it was still going even though I quit the GUI

**Comment by kindjacket** [comment]
Okay - I think the freezing at midnight just happened to me again. It looks like it happened at 3AM pacific for me which would be midnight eastern.

All plots are stuck. The start of the logs are as follows
```
22:22:40.908 daemon asyncio                    : ERROR    Task exception was never retrieved
future: <Task finished name='Task-333017' coro=<WebSocketServer._state_changed() done, defined at src/daemon/server.py:316> exception=ValueError('list.remove(x): x not in list')>
Traceback (most recent call last):
  File "websockets/protocol.py", line 1077, in write_frame
  File "websockets/protocol.py", line 306, in _drain
  File "websockets/protocol.py", line 1077, in write_frame
  File "websockets/protocol.py", line 306, in _drain
  File "websockets/protocol.py", line 1077, in write_frame
  File "websockets/protocol.py", line 306, in _drain
  File "websockets/protocol.py", line 1077, in write_frame
  File "websockets/protocol.py", line 306, in _drain
  File "websockets/protocol.py", line 1077, in write_frame
  File "websockets/protocol.py", line 306, in _drain
  File "websockets/protocol.py", line 1077, in write_frame
  File "websockets/protocol.py", line 306, in _drain
```

**Comment by kindjacket** [comment]
_The GUI also freezes when asked to shut down, and hangs on the "closing node" shutdown window indefinitely._

^ this also happened. Re-opening the GUI was fine after quitting though.

**Comment by gitscy** [comment]
Suddenly stopped, it happened several times a day.

23:15:02.785 wallet chia.wallet.wallet_node    : WARNING  No keys present. Create keys with the UI, or with the 'chia keys' program.
23:23:21.792 wallet chia.rpc.rpc_server        : WARNING  Cannot connect to daemon at ws://localhost:55400
23:23:21.793 full_node chia.rpc.rpc_server     : WARNING  Cannot connect to daemon at ws://localhost:55400
23:23:21.804 harvester chia.rpc.rpc_server     : WARNING  Cannot connect to daemon at ws://localhost:55400
23:23:27.798 full_node chia.rpc.rpc_server     : WARNING  Cannot connect to daemon at ws://localhost:55400
23:23:27.810 harvester chia.rpc.rpc_server     : WARNING  Cannot connect to daemon at ws://localhost:55400
23:23:27.798 wallet chia.rpc.rpc_server        : WARNING  Cannot connect to daemon at ws://localhost:55400
23:23:37.318 wallet chia.wallet.wallet_node    : WARNING  No keys present. Create keys with the UI, or with the 'chia keys' program.
23:25:39.263 full_node full_node_server        : ERROR    Exception:  <class 'concurrent.futures._base.CancelledError'>, closing connection {'host': '18.176.174.48', 'port': 8444}. Traceback (most recent call last):
  File "chia\server\server.py", line 519, in api_call
  File "asyncio\tasks.py", line 435, in wait_for
concurrent.futures._base.CancelledError

23:25:39.425 wallet chia.wallet.wallet_state_manager: WARNING  Starting in db path: C:\Users\S.cy_Big\.chia\mainnet\wallet\db\blockchain_wallet_v1_mainnet_3309194740.sqlite
23:25:42.340 harvester chia.harvester.harvester: WARNING  Not farming any plots on this harvester. Check your configuration.
23:44:19.880 full_node full_node_server        : WARNING  Banning 123.117.178.200 for 600 seconds
23:44:19.881 full_node chia.full_node.full_node: ERROR    Error with syncing: <class 'RuntimeError'>Traceback (most recent call last):
  File "chia\full_node\full_node.py", line 604, in _sync
RuntimeError: Weight proof did not arrive in time from peer: 123.117.178.200

23:47:16.973 full_node full_node_server        : ERROR    Exception , exception Stack: Traceback (most recent call last):
  File "chia\server\server.py", line 353, in start_client
  File "aiohttp\client.py", line 763, in _ws_connect
  File "aiohttp\client.py", line 521, in _request
  File "aiohttp\connector.py", line 535, in connect
  File "aiohttp\connector.py", line 892, in _create_connection
  File "aiohttp\connector.py", line 1032, in _create_direct_connection
  File "aiohttp\connector.py", line 969, in _wrap_create_connection
  File "asyncio\base_events.py", line 949, in create_connection
  File "asyncio\selector_events.py", line 473, in sock_connect
concurrent.futures._base.CancelledError

23:47:17.074 wallet chia.wallet.wallet_blockchain: ERROR    Error during db transaction: 
23:47:30.492 daemon asyncio                    : ERROR    Task exception was never retrieved
future: <Task finished coro=<kill_service() done, defined at chia\daemon\server.py:805> exception=AttributeError("'list' object has no attribute 'pid'")>
Traceback (most recent call last):
  File "chia\daemon\server.py", line 813, in kill_service
  File "chia\daemon\server.py", line 777, in kill_process
AttributeError: 'list' object has no attribute 'pid'
23:58:00.259 wallet chia.wallet.wallet_state_manager: WARNING  Starting in db path: C:\Users\S.cy_Big\.chia\mainnet\wallet\db\blockchain_wallet_v1_mainnet_3309194740.sqlite
23:58:00.728 harvester chia.harvester.harvester: WARNING  Not farming any plots on this harvester. Check your configuration.
23:58:07.881 wallet wallet_server              : ERROR    Exception , exception Stack: Traceback (most recent call last):
  File "chia\server\server.py", line 353, in start_client
  File "aiohttp\client.py", line 763, in _ws_connect
  File "aiohttp\client.py", line 521, in _request
  File "aiohttp\connector.py", line 535, in connect
  File "aiohttp\connector.py", line 892, in _create_connection
  File "aiohttp\connector.py", line 1032, in _create_direct_connection
  File "aiohttp\connector.py", line 969, in _wrap_create_connection
  File "asyncio\base_events.py", line 949, in create_connection
  File "asyncio\selector_events.py", line 473, in sock_connect
concurrent.futures._base.CancelledError

23:58:07.900 wallet chia.wallet.wallet_state_manager: WARNING  Starting in db path: C:\Users\S.cy_Big\.chia\mainnet\wallet\db\blockchain_wallet_v1_mainnet_3309194740.sqlite
00:02:03.533 full_node full_node_server        : ERROR    Exception:  <class 'concurrent.futures._base.CancelledError'>, closing connection {'host': '18.178.190.137', 'port': 8444}. Traceback (most recent call last):
  File "chia\server\server.py", line 519, in api_call
  File "asyncio\tasks.py", line 435, in wait_for
concurrent.futures._base.CancelledError

00:12:02.302 full_node full_node_server        : ERROR    Exception:  <class 'concurrent.futures._base.CancelledError'>, closing connection {'host': '18.176.174.48', 'port': 8444}. Traceback (most recent call last):
  File "chia\server\server.py", line 519, in api_call
  File "asyncio\tasks.py", line 435, in wait_for
concurrent.futures._base.CancelledError

00:14:26.101 full_node full_node_server        : ERROR    Exception:  <class 'concurrent.futures._base.CancelledError'>, closing connection {'host': '35.73.124.38', 'port': 8444}. Traceback (most recent call last):
  File "chia\server\server.py", line 519, in api_call
  File "asyncio\tasks.py", line 435, in wait_for
concurrent.futures._base.CancelledError

00:46:36.917 full_node full_node_server        : WARNING  Cannot write to closing transport 223.104.65.8
01:02:09.062 daemon asyncio                    : ERROR    Task exception was never retrieved
future: <Task finished coro=<WebSocketServer._start_plotting() done, defined at chia\daemon\server.py:441> exception=RuntimeError('coroutine raised StopIteration')>
Traceback (most recent call last):
  File "chia\daemon\server.py", line 445, in _start_plotting
  File "chia\daemon\server.py", line 428, in _get_plots_queue_item
StopIteration

The above exception was the direct cause of the following exception:

RuntimeError: coroutine raised StopIteration
01:14:34.113 full_node full_node_server        : ERROR    Exception:  <class 'concurrent.futures._base.CancelledError'>, closing connection {'host': '221.225.168.136', 'port': 8444}. Traceback (most recent call last):
  File "chia\server\server.py", line 519, in api_call
  File "asyncio\tasks.py", line 435, in wait_for
concurrent.futures._base.CancelledError

01:15:38.650 full_node full_node_server        : ERROR    Exception:  <class 'concurrent.futures._base.CancelledError'>, closing connection {'host': '112.98.97.76', 'port': 8444}. Traceback (most recent call last):
  File "chia\server\server.py", line 519, in api_call
  File "asyncio\tasks.py", line 435, in wait_for
concurrent.futures._base.CancelledError

01:30:36.402 daemon __main__                   : ERROR    Unexpected exception trying to send to websocket: code = 1006 (connection closed abnormally [internal]), no reason Traceback (most recent call last):
  File "websockets\protocol.py", line 838, in transfer_data
concurrent.futures._base.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "chia\daemon\server.py", line 180, in safe_handle
  File "websockets\protocol.py", line 555, in send
  File "websockets\protocol.py", line 812, in ensure_open
websockets.exceptions.ConnectionClosedError: code = 1006 (connection closed abnormally [internal]), no reason

01:35:59.900 full_node full_node_server        : ERROR    Exception:  <class 'concurrent.futures._base.CancelledError'>, closing connection {'host': '117.90.184.206', 'port': 8444}. Traceback (most recent call last):
  File "chia\server\server.py", line 519, in api_call
  File "asyncio\tasks.py", line 435, in wait_for
concurrent.futures._base.CancelledError

03:26:14.535 full_node chia.full_node.full_node: ERROR    got weight proof request for unknown peak e25d21eb2b831b9be4da94bd963bc66434cfccabe1b5ae83c27fbebc5d6258cb
03:54:54.277 full_node chia.full_node.full_node: ERROR    got weight proof request for unknown peak 8cd33a01ba9d3217c3f071fa17addeb8ad8053e484b93504dc3fe808be0197e4
06:38:31.959 full_node chia.full_node.full_node: ERROR    got weight proof request for unknown peak 3beaac7f7b2e34660d8bc598fc8105897fcc8b1b6a73afa300fa8eb4c798266b
06:51:12.163 full_node full_node_server        : ERROR    Exception:  <class 'concurrent.futures._base.CancelledError'>, closing connection None. Traceback (most recent call last):
  File "chia\server\server.py", line 519, in api_call
  File "asyncio\tasks.py", line 435, in wait_for
concurrent.futures._base.CancelledError

08:55:14.427 full_node full_node_server        : WARNING  Cannot write to closing transport 171.37.47.35
12:36:42.931 full_node full_node_server        : ERROR    Exception Was not able to get peername from <function WSChiaConnection.__getattr__.<locals>.invoke at 0x000002923A17C168> at 151.54.137.190, exception Stack: Traceback (most recent call last):
  File "chia\server\server.py", line 242, in incoming_connection
  File "chia\server\ws_connection.py", line 59, in __init__
ValueError: Was not able to get peername from <function WSChiaConnection.__getattr__.<locals>.invoke at 0x000002923A17C168> at 151.54.137.190

14:14:00.631 full_node full_node_server        : ERROR    Exception:  <class 'concurrent.futures._base.CancelledError'>, closing connection {'host': '117.139.253.59', 'port': 8444}. Traceback (most recent call last):
  File "chia\server\server.py", line 519, in api_call
  File "asyncio\tasks.py", line 435, in wait_for
concurrent.futures._base.CancelledError

14:14:02.014 full_node full_node_server        : ERROR    Exception:  <class 'concurrent.futures._base.CancelledError'>, closing connection {'host': '118.113.1.129', 'port': 8444}. Traceback (most recent call last):
  File "chia\server\server.py", line 519, in api_call
  File "asyncio\tasks.py", line 435, in wait_for
concurrent.futures._base.CancelledError

14:38:44.911 full_node full_node_server        : ERROR    Exception:  <class 'concurrent.futures._base.CancelledError'>, closing connection {'host': '27.44.182.57', 'port': 8444}. Traceback (most recent call last):
  File "chia\server\server.py", line 519, in api_call
  File "asyncio\tasks.py", line 435, in wait_for
concurrent.futures._base.CancelledError

14:38:44.930 full_node full_node_server        : ERROR    Exception:  <class 'concurrent.futures._base.CancelledError'>, closing connection {'host': '113.16.62.21', 'port': 8444}. Traceback (most recent call last):
  File "chia\server\server.py", line 519, in api_call
  File "asyncio\tasks.py", line 435, in wait_for
concurrent.futures._base.CancelledError

14:38:44.932 full_node full_node_server        : ERROR    Exception:  <class 'concurrent.futures._base.CancelledError'>, closing connection {'host': '117.23.198.222', 'port': 8444}. Traceback (most recent call last):
  File "chia\server\server.py", line 519, in api_call
  File "asyncio\tasks.py", line 435, in wait_for
concurrent.futures._base.CancelledError

14:38:44.933 full_node full_node_server        : ERROR    Exception:  <class 'concurrent.futures._base.CancelledError'>, closing connection {'host': '223.72.52.90', 'port': 8444}. Traceback (most recent call last):
  File "chia\server\server.py", line 519, in api_call
  File "asyncio\tasks.py", line 435, in wait_for
concurrent.futures._base.CancelledError

14:38:46.983 full_node full_node_server        : ERROR    Exception:  <class 'concurrent.futures._base.CancelledError'>, closing connection {'host': '114.225.114.190', 'port': 8444}. Traceback (most recent call last):
  File "chia\server\server.py", line 519, in api_call
  File "asyncio\tasks.py", line 435, in wait_for
concurrent.futures._base.CancelledError

15:35:19.249 full_node full_node_server        : WARNING  Cannot write to closing transport 112.0.162.187
16:04:05.652 full_node full_node_server        : ERROR    Exception:  <class 'concurrent.futures._base.CancelledError'>, closing connection {'host': '112.0.162.187', 'port': 8449}. Traceback (most recent call last):
  File "chia\server\server.py", line 519, in api_call
  File "asyncio\tasks.py", line 435, in wait_for
concurrent.futures._base.CancelledError

17:48:09.203 full_node full_node_server        : ERROR    Exception Was not able to get peername from <function WSChiaConnection.__getattr__.<locals>.invoke at 0x0000029237FFFA68> at 81.98.188.192, exception Stack: Traceback (most recent call last):
  File "chia\server\server.py", line 242, in incoming_connection
  File "chia\server\ws_connection.py", line 59, in __init__
ValueError: Was not able to get peername from <function WSChiaConnection.__getattr__.<locals>.invoke at 0x0000029237FFFA68> at 81.98.188.192

19:50:45.660 daemon asyncio                    : ERROR    Task exception was never retrieved
future: <Task finished coro=<kill_service() done, defined at chia\daemon\server.py:805> exception=AttributeError("'list' object has no attribute 'pid'")>
Traceback (most recent call last):
  File "chia\daemon\server.py", line 813, in kill_service
  File "chia\daemon\server.py", line 777, in kill_process
AttributeError: 'list' object has no attribute 'pid'
20:05:49.508 wallet chia.wallet.wallet_state_manager: WARNING  Starting in db path: C:\Users\S.cy_Big\.chia\mainnet\wallet\db\blockchain_wallet_v1_mainnet_3309194740.sqlite
20:06:55.113 wallet wallet_server              : ERROR    Exception , exception Stack: Traceback (most recent call last):
  File "chia\server\server.py", line 353, in start_client
  File "aiohttp\client.py", line 763, in _ws_connect
  File "aiohttp\client.py", line 521, in _request
  File "aiohttp\connector.py", line 535, in connect
  File "aiohttp\connector.py", line 892, in _create_connection
  File "aiohttp\connector.py", line 1032, in _create_direct_connection
  File "aiohttp\connector.py", line 969, in _wrap_create_connection
  File "asyncio\base_events.py", line 989, in create_connection
  File "asyncio\base_events.py", line 1017, in _create_connection_transport
concurrent.futures._base.CancelledError

20:10:42.648 wallet chia.wallet.wallet_state_manager: WARNING  Starting in db path: C:\Users\S.cy_Big\.chia\mainnet\wallet\db\blockchain_wallet_v1_mainnet_3309194740.sqlite
20:29:04.977 full_node chia.full_node.full_node: ERROR    Exception in create outbound connections: 
20:29:04.978 full_node chia.full_node.full_node: ERROR    Traceback: Traceback (most recent call last):
  File "chia\server\node_discovery.py", line 302, in _connect_to_peers
  File "asyncio\tasks.py", line 595, in sleep
concurrent.futures._base.CancelledError

20:41:18.047 wallet chia.wallet.wallet_state_manager: WARNING  Starting in db path: C:\Users\S.cy_Big\.chia\mainnet\wallet\db\blockchain_wallet_v1_mainnet_3309194740.sqlite
20:43:01.333 wallet chia.wallet.wallet_state_manager: WARNING  Starting in db path: C:\Users\S.cy_Big\.chia\mainnet\wallet\db\blockchain_wallet_v1_mainnet_3309194740.sqlite
20:47:46.203 harvester chia.plotting.plot_tools: ERROR    Failed to open file F:\chia_data\plot-k32-2021-04-19-09-09-ecf6499023f25c85bb72b6253dca8a05a3e502a0df8773c008ddbda838b7e52b.plot. Invalid file F:\chia_data\plot-k32-2021-04-19-09-09-ecf6499023f25c85bb72b6253dca8a05a3e502a0df8773c008ddbda838b7e52b.plot Traceback (most recent call last):
  File "chia\plotting\plot_tools.py", line 185, in load_plots
ValueError: Invalid file F:\chia_data\plot-k32-2021-04-19-09-09-ecf6499023f25c85bb72b6253dca8a05a3e502a0df8773c008ddbda838b7e52b.plot
