### ISSUE TITLE
[BUG] After installing "Conneting to wallet" stays forever

### ISSUE THREAD

**Issue by gregtyminski** [Chia-Network/chia-blockchain#1783]
**Describe the bug**
I've installed Windows 10 version 1.0.3.

**To Reproduce**

1. Double click on 'ChiaSetup-1.0.3.exe'
2. Keep watching and looking at "Conneting to wallet"
3. Restart app.
4. Restart system and start the "Chia" app again.

**Expected behavior**
Start farming? Showing some plots?
No idea. I have never seen anything else than "conneting to wallet".

**Screenshots**
See the screenshot.

**Desktop (please complete the following information):**

- OS: Windows 10
- OS Version/Flavor: Windows 10 Pro 19041.867
- CPU: Intel Cor i7-6820HQ 2.7 GHz

**Additional context**
I've tried with version 1.0.3 as well as with version 1.0.2.
I've restarted app as well as the OS itself.
No changes.
![chia](https://user-images.githubusercontent.com/55957815/114239219-13b18300-9986-11eb-8755-39a7023ce4dd.png)

**Comment by louie42** [comment]
My Chia used to work on version 1.0.0.
I have been having the same issue for weeks now and it all started after I uninstalled 1.0.0 and updated to 1.0.1.
Now, it doesn't matter the version I install (1.0.0, 1.0.3.), it will always be like that.

If I do View > Force Reload it goes to blank and the only way to view some text and be prompted for the key is to try View > Reload afterwards and I repeat between the two many times until it appears.

After being lucky, I get to see the wallet key prompt, and after clicking on the key I get to see all the normal things except it never connects to the nodes (I was already synchronized and farming when I was using 1.0.0)

If I check the Windows processes, all the Chia services have already been started, but nothing worked as I hoped.

I have also already tried on PowerShell from fresh boot, and from there I can "successfully start" everything.
I let it run for a few minutes and even after 3 or 4 hours, when querying its status with ./chia show -s it always shows this:

Connection error. Check if full node rpc is running at 8555
This is normal if full node is still starting up

Yes, I have already reviewed my Windows firewall settings and I have set everything Chia as accept IN/OUT.
I don't really know what other things to try :(

Thanks.

**Comment by wjblanke** [comment]
try this. close chia. delete ~/.chia/mainnet folder from your user directory. reboot. restart

**Comment by louie42** [comment]
Thanks wjblanke, using the UI it works on the first try after doing that!

**Comment by gregtyminski** [comment]
Meanwhile, I have removed version 1.0.2 and 1.0.3 and installed 1.0.0 to check if same think would work like @louie42 mentioned.
Unfortunately.

I have Windows 10.
There is no directory location like ~/.chia/

The place I have found at my disk with chia is:
```
PS C:\Users\GrzegorzTymiński\AppData\Local\chia-blockchain> dir

    Directory: C:\Users\GrzegorzTymiński\AppData\Local\chia-blockchain

Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d-----        10/04/2021     08:20                app-1.0.0
d-----        10/04/2021     08:20                packages
-a----        10/04/2021     08:20         286704 Chia.exe
-a----        10/04/2021     08:20        1930224 Update.exe
```
and then inside

```
PS C:\Users\GrzegorzTymiński\AppData\Local\chia-blockchain> cd .\app-1.0.0\
PS C:\Users\GrzegorzTymiński\AppData\Local\chia-blockchain\app-1.0.0> dir

    Directory: C:\Users\GrzegorzTymiński\AppData\Local\chia-blockchain\app-1.0.0

Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d-----        10/04/2021     08:20                locales
d-----        10/04/2021     08:20                resources
d-----        10/04/2021     08:20                swiftshader
-a----        10/04/2021     08:20      126186992 Chia.exe
-a----        10/04/2021     08:20         124377 chrome_100_percent.pak
-a----        10/04/2021     08:20         185871 chrome_200_percent.pak
-a----        10/04/2021     08:20        4524696 d3dcompiler_47.dll
-a----        10/04/2021     08:20        2827248 ffmpeg.dll
-a----        10/04/2021     08:20       10528096 icudtl.dat
-a----        10/04/2021     08:20         452592 libEGL.dll
-a----        10/04/2021     08:20        7623664 libGLESv2.dll
-a----        10/04/2021     08:20           1060 LICENSE
-a----        10/04/2021     08:20        5015745 resources.pak
-a----        10/04/2021     08:20          51447 snapshot_blob.bin
-a----        10/04/2021     08:20            277 Squirrel-UpdateSelf.log
-a----        10/04/2021     08:20        1930224 squirrel.exe
-a----        10/04/2021     08:20         172274 v8_context_snapshot.bin
-a----        10/04/2021     08:20        4491760 vk_swiftshader.dll
-a----        10/04/2021     08:20            106 vk_swiftshader_icd.json
-a----        10/04/2021     08:20         735728 vulkan-1.dll
```

I found one more place:
```
PS C:\Users\GrzegorzTymiński\AppData\Roaming\Chia Blockchain> dir

    Directory: C:\Users\GrzegorzTymiński\AppData\Roaming\Chia Blockchain

Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d-----        10/04/2021     08:22                blob_storage
d-----        09/04/2021     21:42                Code Cache
d-----        09/04/2021     21:42                Dictionaries
d-----        09/04/2021     21:42                GPUCache
d-----        09/04/2021     21:42                Local Storage
d-----        10/04/2021     08:22                Session Storage
-a----        09/04/2021     22:32            111 Network Persistent State
-a----        10/04/2021     08:22             57 Preferences
```

**Comment by louie42** [comment]
@gregtyminski, I think that directory exists on 1.0.3 and not 1.0.0.
Try uninstalling 1.0.0 and reinstalling 1.0.3.
If it doesn't work, try deleting the /mainnet folder.
You will find it at:
C:\Users\GrzegorzTymiński\.chia\mainnet

**Comment by gregtyminski** [comment]
@louie42 : I tried with ver. 1.0.3
There is no folder `mainnet` and stil doesn't work.
I don't have folder `C:\Users\GrzegorzTymiński\.chia\`.
I have fresh same folder like before, but with version 1.0.3.

**Comment by gregtyminski** [comment]
So I tried to do this a bit ... manually.
Look at the steps below.

```
PS C:\Users\GrzegorzTymiński\AppData\Local\chia-blockchain\app-1.0.3\resources\app.asar.unpacked\daemon> .\chia.exe stop all
can't find C:\Users\GrzegorzTymiński\.chia\mainnet\config\config.yaml
** please run `chia init` to migrate or create new config files **
```
```
PS C:\Users\GrzegorzTymiński\AppData\Local\chia-blockchain\app-1.0.3\resources\app.asar.unpacked\daemon> .\chia.exe --help
Usage: chia.exe [OPTIONS] COMMAND [ARGS]...

  Manage chia blockchain infrastructure (1.0.3.dev3)

Options:
  --root-path PATH  Config file root  [default:
                    C:\Users\GrzegorzTymiński\.chia\mainnet]

  -h, --help        Show this message and exit.

Commands:
  configure   Modify configuration
  farm        Manage your farm
  init        Create or migrate the configuration
  keys        Manage your keys
  netspace    Estimate total farmed space on the network
  plots       Manage your plots
  run_daemon  Runs chia daemon
  show        Show node information
  start       Start service groups
  stop        Stop services
  version     Show chia version
  wallet      Manage your wallet

  Try 'chia start node', 'chia netspace -d 192', or 'chia show -s'
```

```
PS C:\Users\GrzegorzTymiński\AppData\Local\chia-blockchain\app-1.0.3\resources\app.asar.unpacked\daemon> .\chia.exe configure
can't find C:\Users\GrzegorzTymiński\.chia\mainnet\config\config.yaml
** please run `chia init` to migrate or create new config files **
```

```
PS C:\Users\GrzegorzTymiński\AppData\Local\chia-blockchain\app-1.0.3\resources\app.asar.unpacked\daemon> .\chia.exe init
Chia directory C:\Users\GrzegorzTymiński\.chia\mainnet
Can't find private CA, creating a new one in C:\Users\GrzegorzTymiński\.chia\mainnet to generate TLS certificates
No keys are present in the keychain. Generate them with 'chia keys generate'

To see your keys, run 'chia keys show'
```

```
PS C:\Users\GrzegorzTymiński\AppData\Local\chia-blockchain\app-1.0.3\resources\app.asar.unpacked\daemon> .\chia.exe keys generate
Generating private key
Added private key with public key fingerprint 4004283592 and mnemonic
plastic project potato install capital main stadium response acquire evidence rifle also turkey giraffe news twin prison time journey private virtual deal morning olympic
Setting the xch destination address for coinbase fees reward to %wallet-id-lots-of-characters%
Setting the xch destination address for coinbase reward to %wallet-id-lots-of-characters%
```

```
PS C:\Users\GrzegorzTymiński\AppData\Local\chia-blockchain\app-1.0.3\resources\app.asar.unpacked\daemon> .\chia.exe keys show
Showing all private keys:

Fingerprint: 4004283592
Master public key (m): .....
Master private key (m): .....
Farmer public key (m/12381/8444/0/0):: .....
Pool public key (m/12381/8444/1/0): .....
First wallet key (m/12381/8444/2/0): .....
First wallet address: .....
```

```
PS C:\Users\GrzegorzTymiński\AppData\Local\chia-blockchain\app-1.0.3\resources\app.asar.unpacked\daemon> .\chia.exe init
Chia directory C:\Users\GrzegorzTymiński\.chia\mainnet
C:\Users\GrzegorzTymiński\.chia\mainnet already exists, no migration action taken
```

```
PS C:\Users\GrzegorzTymiński\AppData\Local\chia-blockchain\app-1.0.3\resources\app.asar.unpacked\daemon> .\chia.exe configure
```

```
PS C:\Users\GrzegorzTymiński\AppData\Local\chia-blockchain\app-1.0.3\resources\app.asar.unpacked\daemon> .\chia.exe start all
Daemon not started yet
Starting daemon
Traceback (most recent call last):
  File "src\cmds\chia.py", line 80, in <module>
  File "src\cmds\chia.py", line 76, in main
  File "click\core.py", line 829, in __call__
  File "click\core.py", line 782, in main
  File "click\core.py", line 1259, in invoke
  File "click\core.py", line 1066, in invoke
  File "click\core.py", line 610, in invoke
  File "click\decorators.py", line 21, in new_func
  File "src\cmds\chia.py", line 59, in run_daemon_cmd
  File "asyncio\base_events.py", line 587, in run_until_complete
  File "src\daemon\server.py", line 908, in async_run_daemon
  File "src\cmds\init.py", line 309, in chia_init
  File "C:\hostedtoolcache\windows\Python\3.7.9\x64\lib\encodings\cp1252.py", line 19, in encode
UnicodeEncodeError: 'charmap' codec can't encode character '\u0144' in position 55: character maps to <undefined>
[18512] Failed to execute script chia
Daemon not started yet
Failed to create the chia daemon
```

```
PS C:\Users\GrzegorzTymiński\AppData\Local\chia-blockchain\app-1.0.3\resources\app.asar.unpacked\daemon> .\chia.exe wallet show
Connection error. Check if wallet is running at 9256
```

So. Gives that anything to you?
After all above commands I started GUI again ... and same end effect ... "Connecting to wallet".

**What might be the issue?**

**Comment by gregtyminski** [comment]
At this Windows 10 OS I have as well Ubuntu (w/o GUI).
I've installed chia there and started plotting from command line.
It's not solution at all.
I have no idea, how to then start farming. :-)

**Comment by WangKehanK** [comment]
Same issue with Windows 10 here.

Also, the console in developer tools shows me "Already connected, not reconnecting."

![image](https://user-images.githubusercontent.com/45981322/114961597-1ead5d00-9e37-11eb-96f0-f3091fc51b0f.png)

**Comment by beasier** [comment]
Having the same issue on Mac Big Sur.  After my initial plotting which never completed my computer crashed and when I came back in again this happened. I started on 1.0.3. I was hoping this would be fixed by 1.0.4, and then 1.0.5. Still having the same issue. I'd really like to get started. I don't know why this issue isn't being addressed.

![image](https://user-images.githubusercontent.com/82682112/115087024-45fd3c00-9ec2-11eb-8314-23cc0447735b.png)

**Comment by kelatoz** [comment]
me toooo....
my  version 1.1.2

**Comment by kelatoz** [comment]
![Uploading QQ截图20210430103023.png…]()

**Comment by 001101** [comment]
same here on win 10 enterprise
no antivirus, tinywall disabled

deleted mainnet folder, manual chia init and still

**FIX THIS!!!!!!!!!!!!!**
