### ISSUE TITLE
[Bug] not synchronized in the future

### ISSUE THREAD

**Issue by Jayke2** [Chia-Network/chia-blockchain#17855]
### What happened?

18/10000
实时翻译
划译
Synchronized to 5202376, not synchronized in the future

### Version

2.2.1

### What platform are you using?

Linux

### What ui mode are you using?

CLI

### Relevant log output

```shell
ERROR    Error with syncing: <class 'ValueError'>Traceback (most recent call last):
  File "chia/full_node/full_node.py", line 970, in _sync
  File "chia/full_node/full_node.py", line 1035, in request_validate_wp
ValueError: Weight proof validation failed

2024-04-11T10:40:08.297 full_node chia.full_node.full_node: INFO     long sync done
2024-04-11T10:40:08.298 full_node chia.full_node.full_node: INFO     🌱 Updated peak to height 5202376, weight 18083879504, hh 9402bce30c48435288090fefbce213fadabe6b26b1567b4010f672234a7ba597, forked at 5202375, rh: f4eccaa5f9854d81e682691d59a0c75bc52c2c5bef6637887d6bccf423c7db13, total iters: 32676185642522, overflow: False, deficit: 15, difficulty: 11776, sub slot iters: 578813952, Generator size: No tx, Generator ref list size: No tx
```

**Comment by wjblanke** [comment]
Can u provide the full DEBUG version of debug.log. I assume this is always reproducible so we should be able to find the cause.
