### ISSUE TITLE
[Bug] Wrong type with memo argument

### ISSUE THREAD

**Issue by pmaslana** [Chia-Network/chia-blockchain#17859]
### What happened?

When trying to duplicate plots, errors were received when passing in the 128-byte hex string. Additionally, I was receiving an error when using the "chia plotters" command with a memo that the memo needed to be converted to a string.

### Version

2.3.0rc1

### What platform are you using?

macOS

### What ui mode are you using?

CLI

### Relevant log output

```shell
2024-04-09T12:44:44.606  chia.plotting.manager            : ERROR    Failed to open file /Users/pmaslana/chia-blockchain/plot/plot-k25-2024-04-09-12-37-2d6806268d3f4075a260c5dc4f8075de71a3b4c8185547fec1268a3a901dad95.plot. Invalid number of bytes 32 Traceback (most recent call last):
  File "/Users/pmaslana/chia-blockchain/chia/plotting/manager.py", line 346, in process_file
    cache_entry = CacheEntry.from_disk_prover(prover)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/pmaslana/chia-blockchain/chia/plotting/cache.py", line 59, in from_disk_prover
    ) = parse_plot_info(prover.get_memo())
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/pmaslana/chia-blockchain/chia/plotting/util.py", line 257, in parse_plot_info
    raise ValueError(f"Invalid number of bytes {len(memo)}")
ValueError: Invalid number of bytes 32
-------------------------------------------------------------------------------------------
  File "/Users/pmaslana/chia-blockchain/chia/util/byte_types.py", line 37, in __init__
    raise ValueError(f"bad {type(self).__name__} initializer {v}")
ValueError: bad bytes32 initializer b'\xa7\xffK\x18\xea\x93t\xb3\xee\x13\xac\xc6_^\x90\xa8\xb6\x97\xd5\xc6z\xce]\x0f\xaai\xc6\xef\x018\xb6s\xb4V5\xf4\xa6\x01z\xa50sB)W\x1c\xe0\xd4\xa68\xccN\xe9GH\x010\x954"W\xf0+\xda\xf2G/\xcb\xd2\xa9Lw\xe1\x11\xd8\x8cz\x15\xcfY\xef\xaeI\x86\x02\xd5\r\xf0Y\x88\x1fi\xce\xe9\xa8]\x18\xbc\xfcu\x18$\xac?\x0f\x8f\xe4"\x90s\x8e\xcf\xcf\xa9\xe4S^\xb3\xe7h\xd9Y\x91\xc2\xe2}\xdb\x9b'

-------------------------------------------------------------------------------------------


File "/Users/pmaslana/chia-blockchain/chia/plotting/create_plots.py", line 217, in create_plots
    plot_memo = bytes32.fromhex(args.memo)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: fromhex() argument must be str, not bytes
```

**Comment by pmaslana** [comment]
PR create: https://github.com/Chia-Network/chia-blockchain/pull/17856/files
