### ISSUE TITLE
[BUG] Error when creating plot "Caught plotting error: std::bad_alloc"

### ISSUE THREAD

**Issue by maltokyo** [Chia-Network/chia-blockchain#1788]
**Describe the bug**

**To Reproduce**

1. Run this command from within official docker image: `venv/bin/chia plots create -k 32 -b 6000 -t /plots/z_tmp -d /plots`
 (also have tried with `-b 4000` with same result)

**Expected behavior**
Plot should get created by instead I get error when creating plot "Caught plotting error: std::bad_alloc".  See full command and log below.

**Screenshots**
Add details in log below

**Desktop (please complete the following information):**

- OS: Linux (official docker of Chia)
- OS Version/Flavor: Debian 10
- CPU: AMD with 8GB Ram

**Additional context**

Log
```
root@68522f23e616:/chia-blockchain# venv/bin/chia plots create -k 32 -b 6000 -t /plots/z_tmp -d /plots
11:15:56.770  src.plotting.create_plots        : INFO     Creating 1 plots of size 32, pool public key:  b9f5785d4d2a808ebebb13885ae46a63c3eee9bde4ec241b1b43e8a00df92358efe1628002841471b49acf3e0a0e9bab farmer public key: 8ada4a5a4115f06c6c628983d5a80d6765a3e0154db920103475ed31e724f48c2e24aaef6ad21ae28a7f90cd143a5a8d
11:15:56.780  src.plotting.create_plots        : INFO     Memo: b9f5785d4d2a808ebebb13885ae46a63c3eee9bde4ec241b1b43e8a00df92358efe1628002841471b49acf3e0a0e9bab8ada4a5a4115f06c6c628983d5a80d6765a3e0154db920103475ed31e724f48c2e24aaef6ad21ae28a7f90cd143a5a8d2b36ccb79b941fca1d4543747b0f3d8b863db3b57a890b244b60ab58ec3e180d
11:15:56.780  src.plotting.create_plots        : INFO     Starting plot 1/1

Starting plotting progress into temporary dirs: /plots/z_tmp and /plots/z_tmp
ID: 1f0c5b7b1ae85d95db82d5a42caf986f300f04112ba14e217216312b5f8cdb61
Plot size is: 32
Buffer size is: 6000MiB
Using 128 buckets
Using 2 threads of stripe size 65536

Starting phase 1/4: Forward Propagation into tmp files... Sat Apr 10 11:15:57 2021
Computing table 1
F1 complete, time: 514.282 seconds. CPU (125.97%) Sat Apr 10 11:24:31 2021
Computing table 2
Caught plotting error: std::bad_alloc
Traceback (most recent call last):
  File "venv/bin/chia", line 33, in <module>
    sys.exit(load_entry_point('chia-blockchain', 'console_scripts', 'chia')())
  File "/chia-blockchain/src/cmds/chia.py", line 76, in main
    cli()  # pylint: disable=no-value-for-parameter
  File "/chia-blockchain/venv/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/chia-blockchain/venv/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/chia-blockchain/venv/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/chia-blockchain/venv/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/chia-blockchain/venv/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/chia-blockchain/venv/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/chia-blockchain/venv/lib/python3.8/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/chia-blockchain/src/cmds/plots.py", line 134, in create_cmd
    create_plots(Params(), ctx.obj["root_path"])
  File "/chia-blockchain/src/plotting/create_plots.py", line 164, in create_plots
    plotter.create_plot_disk(
RuntimeError: std::exception
```

**Comment by hoffmang9** [comment]
This is a problem with your machine. It is usually unstable RAM due to a bad stick, over clocking, or XMP. It could be your VM not allocating or handling swap correctly, etc.
