### ISSUE TITLE
[BUG] run electron return err "Error loading config" under ubuntu

### ISSUE THREAD

**Issue by thomas-pegot** [Chia-Network/chia-blockchain#1791]
**Describe the bug**
After first [install](https://github.com/Chia-Network/chia-blockchain/wiki/INSTALL#ubuntudebian) when I launch `npm run electron &`, npm return ERR!

**To Reproduce**
```
sudo apt-get update
sudo apt-get upgrade -y

# Checkout the source and install
git clone https://github.com/Chia-Network/chia-blockchain.git -b latest
cd chia-blockchain

sh install.sh

. ./activate

sh install-gui.sh

cd chia-blockchain-gui
npm run electron &
```

**Output**
```
(venv) thomas@thomas:~/chia-blockchain/chia-blockchain-gui$
> chia-blockchain@ electron /home/thomas/chia-blockchain/chia-blockchain-gui
> electron .

/home/thomas/chia-blockchain/app.asar.unpacked/daemon
false
Error loading config - using defaults
/home/thomas/chia-blockchain/chia-blockchain-gui/node_modules/electron/dist/electron exited with signal SIGSEGV
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! chia-blockchain@ electron: `electron .`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the chia-blockchain@ electron script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/thomas/.npm/_logs/2021-04-10T15_27_11_646Z-debug.log ```

with log:
```1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'electron' ]
2 info using npm@6.14.4
3 info using node@v10.19.0
4 verbose run-script [ 'preelectron', 'electron', 'postelectron' ]
5 info lifecycle chia-blockchain@~preelectron: chia-blockchain@
6 info lifecycle chia-blockchain@~electron: chia-blockchain@
7 verbose lifecycle chia-blockchain@~electron: unsafe-perm in lifecycle true
8 verbose lifecycle chia-blockchain@~electron: PATH: /usr/share/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/tho
mas/chia-blockchain/chia-blockchain-gui/node_modules/.bin:/home/thomas/chia-blockchain/venv/bin:/usr/local/sbin:/usr/
local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/snap/bin
9 verbose lifecycle chia-blockchain@~electron: CWD: /home/thomas/chia-blockchain/chia-blockchain-gui
10 silly lifecycle chia-blockchain@~electron: Args: [ '-c', 'electron .' ]
11 silly lifecycle chia-blockchain@~electron: Returned: code: 1  signal: null
12 info lifecycle chia-blockchain@~electron: Failed to exec electron script
13 verbose stack Error: chia-blockchain@ electron: `electron .`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/share/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:198:13)
13 verbose stack     at ChildProcess.<anonymous> (/usr/share/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:198:13)
13 verbose stack     at maybeClose (internal/child_process.js:982:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
14 verbose pkgid chia-blockchain@
15 verbose cwd /home/thomas/chia-blockchain/chia-blockchain-gui
16 verbose Linux 5.4.0-70-generic
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "run" "electron"
18 verbose node v10.19.0
19 verbose npm  v6.14.4
20 error code ELIFECYCLE
21 error errno 1
22 error chia-blockchain@ electron: `electron .`
22 error Exit status 1
23 error Failed at the chia-blockchain@ electron script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Desktop (please complete the following information):**

- OS: Ubuntu 20.04 LTS

**Comment by hoffmang9** [comment]
Do you have Ubuntu Desktop installed?

**Comment by thomas-pegot** [comment]
@hoffmang9 No it's Ubuntu server sorry I forgot to mention

**Comment by hoffmang9** [comment]
You can't run the GUI without Desktop.

**Comment by thomas-pegot** [comment]
Forgot about that xD . ty
Can it still work without GUI just command line.

**Comment by hoffmang9** [comment]
Yes.
