### ISSUE TITLE
[Bug] Node fails to start on Windows 10 with 64 cores (with workaround)

### ISSUE THREAD

**Issue by fizpawiz** [Chia-Network/chia-blockchain#17967]
### What happened?

I have a Threadripper 3970x with 64 cores.  On 2.2.1, I was farming fine.  On 2.3.0 the farmer will no longer start.

Per discussion on Keybase, I tried setting full_node/reserved_cores to 10 (from default of zero) in the config.yaml, and it resolved the issue.

### Version

2.3.0

### What platform are you using?

Windows

### What ui mode are you using?

GUI

### Relevant log output

```shell
2024-05-02T14:27:29.822 full_node chia.server.start_service: ERROR    fatal uncaught exception: ValueError: max_workers must be <= 61
Traceback (most recent call last):
  File "chia\util\log_exceptions.py", line 20, in log_exceptions
  File "chia\server\start_service.py", line 323, in async_run
  File "asyncio\runners.py", line 44, in run
  File "asyncio\base_events.py", line 649, in run_until_complete
  File "chia\server\start_full_node.py", line 85, in async_main
  File "chia\server\start_service.py", line 197, in run
  File "contextlib.py", line 199, in __aenter__
  File "chia\server\start_service.py", line 214, in manage
  File "contextlib.py", line 619, in enter_async_context
  File "contextlib.py", line 199, in __aenter__
  File "chia\full_node\full_node.py", line 266, in manage
  File "chia\consensus\blockchain.py", line 146, in create
  File "concurrent\futures\process.py", line 614, in __init__
ValueError: max_workers must be <= 61
```

**Comment by altendky** [comment]
Fix being added back in https://github.com/Chia-Network/chia-blockchain/pull/17958.  Was incorrectly removed in https://github.com/Chia-Network/chia-blockchain/pull/17409 first released in 2.3.0rc1.  This is specific to Windows and CPUs with more than 61 cores.

**Comment by SoftStoneDevelop** [comment]
I have the same problem, I'll have to roll back to 2.2.1

**Comment by altendky** [comment]
While this does need to be fixed, do note small configuration adjustment that can work around this.

> setting full_node/reserved_cores to 10
