### ISSUE TITLE
[Bug] 2.3.0 unable to run on FreeBSD

### ISSUE THREAD

**Issue by alghmma** [Chia-Network/chia-blockchain#17988]
### What happened?

Built 2.3.0 on Freebsd 14, won't run because of missing system_delays for this platform.  

Locally added 
```
    try:
        _system_delay = system_delays["local"][sys.platform]
    except KeyError:
        _system_delay = system_delays["local"]["linux"]
```
to chia/util/timing.py to fallback to linux settings if platform not found

### Version

2.3.0

### What platform are you using?

Linux

### What ui mode are you using?

CLI

### Relevant log output

```shell
# chia start farmer
Traceback (most recent call last):
  File "/usr/home/chia/chia_builds/2.3.0/venv/bin/chia", line 5, in <module>
    from chia.cmds.chia import main
  File "/usr/home/chia/chia_builds/2.3.0/chia/cmds/chia.py", line 15, in <module>
    from chia.cmds.dev import dev_cmd
  File "/usr/home/chia/chia_builds/2.3.0/chia/cmds/dev.py", line 5, in <module>
    from chia.cmds.installers import installers_group
  File "/usr/home/chia/chia_builds/2.3.0/chia/cmds/installers.py", line 12, in <module>
    from chia.util.timing import adjusted_timeout
  File "/usr/home/chia/chia_builds/2.3.0/chia/util/timing.py", line 28, in <module>
    _system_delay = system_delays["local"][sys.platform]
KeyError: 'freebsd14'
```

**Comment by ChristopherP1221** [comment]
I have the same bug on freebsd13. I tried updating locally and rerunning 'chia init' it still fails. Do I need to recompile anything or delete any cache files?

(venv) [chia@chia ~/chia-blockchain]$ chia init -c
Traceback (most recent call last):
  File "/home/chia/chia-blockchain/venv/bin/chia", line 5, in <module>
    from chia.cmds.chia import main
  File "/home/chia/chia-blockchain/venv/lib/python3.9/site-packages/chia/cmds/chia.py", line 15, in <module>
    from chia.cmds.dev import dev_cmd
  File "/home/chia/chia-blockchain/venv/lib/python3.9/site-packages/chia/cmds/dev.py", line 5, in <module>
    from chia.cmds.installers import installers_group
  File "/home/chia/chia-blockchain/venv/lib/python3.9/site-packages/chia/cmds/installers.py", line 12, in <module>
    from chia.util.timing import adjusted_timeout
  File "/home/chia/chia-blockchain/venv/lib/python3.9/site-packages/chia/util/timing.py", line 28, in <module>
    _system_delay = system_delays["local"][sys.platform]
KeyError: 'freebsd13'
