### ISSUE TITLE
wallet_server Exception at start on Win10 [BUG]

### ISSUE THREAD

**Issue by Richh1071** [Chia-Network/chia-blockchain#1799]
**Describe the bug**
Every time I start the GUI on my Win10 pc running 1.0.3 I get the following entry in the debug log:

10:40:05.153 wallet wallet_server              : ERROR    Exception , exception Stack: Traceback (most recent call last):
  File "src\server\server.py", line 353, in start_client
  File "aiohttp\client.py", line 763, in _ws_connect
  File "aiohttp\client.py", line 521, in _request
  File "aiohttp\connector.py", line 535, in connect
  File "aiohttp\connector.py", line 892, in _create_connection
  File "aiohttp\connector.py", line 1032, in _create_direct_connection
  File "aiohttp\connector.py", line 969, in _wrap_create_connection
  File "asyncio\base_events.py", line 949, in create_connection
  File "asyncio\selector_events.py", line 473, in sock_connect
concurrent.futures._base.CancelledError

10:40:05.230 wallet src.wallet.wallet_state_manager: WARNING  Starting in db path: C:\Users\Rich\.chia\mainnet\wallet\db\blockchain_wallet_v1_mainnet_3935463860.sqlite

**To Reproduce**
Start Chia GUI

**Expected behavior**
Clean debug log

**Screenshots**

- OS: Win10 Ent (2004)
<img width="276" alt="Screenshot 2021-04-11 at 14 53 08" src="https://user-images.githubusercontent.com/82323208/114307018-b593b580-9ad5-11eb-8dc7-2948f214a316.png">

Intel i5-5250U
RAM 8GB

The reason I was looking at the log was I have been farming since mainnet launch and not won any yet. Probably just being impatient, est has been 8-10days for the past 2 weeks or so. Everything else seems ok. So just checking and letting you know about this issue.

**Comment by hoffmang9** [comment]
Normal unimportant errors that will be gone in 1.0.4 and don't effect farming.
