### ISSUE TITLE
[Bug] After updating to version 2.3.0, the restart program is stuck in the process of continuously starting the service

### ISSUE THREAD

**Issue by Michael121318** [Chia-Network/chia-blockchain#18035]
### What happened?

After updating to version 2.3.0, the res
![Uploading 微信截图_20240516234532.png…]()
tart program is stuck in the process of continuously starting the service

### Version

2.3.0

### What platform are you using?

Windows

### What ui mode are you using?

GUI

**Comment by BrandtH22** [comment]
Hey @Michael121318 , please refer to the comment in the discussion:
 https://github.com/Chia-Network/chia-blockchain/discussions/18034

**Comment by SlightlyNoobish** [comment]
I am getting this error, same issue.
[No 18034](https://github.com/Chia-Network/chia-blockchain/discussions/18034) isn't a solution, i am already on v2 DB


2024-05-21T20:15:20.222 full_node chia.server.start_service: ERROR    fatal uncaught exception: ValueError: max_workers must be <= 61
Traceback (most recent call last):
  File "chia\util\log_exceptions.py", line 20, in log_exceptions
  File "chia\server\start_service.py", line 323, in async_run
  File "asyncio\runners.py", line 44, in run
  File "asyncio\base_events.py", line 649, in run_until_complete
  File "chia\server\start_full_node.py", line 85, in async_main
  File "chia\server\start_service.py", line 197, in run
  File "contextlib.py", line 199, in __aenter__
  File "chia\server\start_service.py", line 214, in manage
  File "contextlib.py", line 619, in enter_async_context
  File "contextlib.py", line 199, in __aenter__
  File "chia\full_node\full_node.py", line 266, in manage
  File "chia\consensus\blockchain.py", line 146, in create
  File "concurrent\futures\process.py", line 614, in __init__
ValueError: max_workers must be <= 61

**Comment by wjblanke** [comment]
How many CPU cores do you have? Python only can do multiprocessing with 61 cores. A workaround for this is to use the reserved_cores config.yaml setting to remove some of those cores from the multiprocessing pool. For example if you have 64 cores can you change 

reserved_cores: 0

to

reserved_cores: 10

And that should allow things to run. This is a regression as you noted.
