### ISSUE TITLE
Stuck on “Loading keyring status” after upgrade from 2.3.0 to 2.3.1

### ISSUE THREAD

**Issue by janit** [Chia-Network/chia-blockchain#18099]
### What happened?

After upgrading to 2.3.1 the GUI is stuck on the start screen with the "Loading keyring status" notice:

<img style=“width:100%;height:auto” alt="image" src="https://github.com/Chia-Network/chia-blockchain/assets/198965/e7107901-7b54-49e3-a85f-f1dd0f5aec11">

If I rename the ~/.chia_keys directory and start the app again, it makes no difference.

If delete the ~/.chia/ directory and retry, then a new one is created, with data only at  ".chia/mainnet/gui/Chia\ Blockchain”. Now the app is stuck at “Loading configuration”. There is nothing in the log directory (.chia/mainnet/logs) since there is no log directory.

If I revert to 2.3.0 then everything runs fine, just that the config and wallet db are wiped (as expected).

### Version

Chia 2.3.1 (ARM)

### What platform are you using?

macOS

### What ui mode are you using?

GUI

### Relevant log output

```shell
None found.
```

**Comment by BrandtH22** [comment]
Reproduced the above error on mac silicon. Previously running 2.3.0, upgraded to 2.3.1 and was stuck on loading keyring. 
When trying to run chia commands this error is presented:
```
Traceback (most recent call last):
  File "chia/cmds/chia.py", line 9, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 419, in exec_module
  File "chia/cmds/beta.py", line 10, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 419, in exec_module
  File "chia/cmds/beta_funcs.py", line 8, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 419, in exec_module
  File "chia/util/beta_metrics.py", line 13, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 419, in exec_module
  File "chia/util/config.py", line 21, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 419, in exec_module
  File "chia/types/peer_info.py", line 8, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 419, in exec_module
  File "chia/util/network.py", line 6, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 419, in exec_module
  File "ssl.py", line 99, in <module>
ImportError: dlopen(/Applications/Chia.app/Contents/Resources/app.asar.unpacked/daemon/_internal/lib-dynload/_ssl.cpython-310-darwin.so, 0x0002): Symbol not found: _X509_STORE_get1_objects
  Referenced from: <255D5D5D-5C68-3DA1-A40D-1D4A3D49EF46> /Applications/Chia.app/Contents/Resources/app.asar.unpacked/daemon/_internal/lib-dynload/_ssl.cpython-310-darwin.so
  Expected in:     <0A78C281-74DA-3842-9C01-78FF31BBBFF2> /opt/homebrew/Cellar/openssl@3/3.2.1/lib/libcrypto.3.dylib
[54172] Failed to execute script 'chia' due to unhandled exception!
```

**Comment by janit** [comment]
Can confirm I get the same when calling the daemon binary:

```
janit@ruutana:Downloads/Chia.app $ ./Contents/Resources/app.asar.unpacked/daemon/chia version
Traceback (most recent call last):
  File "chia/cmds/chia.py", line 9, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 419, in exec_module
  File "chia/cmds/beta.py", line 10, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 419, in exec_module
  File "chia/cmds/beta_funcs.py", line 8, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 419, in exec_module
  File "chia/util/beta_metrics.py", line 13, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 419, in exec_module
  File "chia/util/config.py", line 21, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 419, in exec_module
  File "chia/types/peer_info.py", line 8, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 419, in exec_module
  File "chia/util/network.py", line 6, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 419, in exec_module
  File "ssl.py", line 99, in <module>
ImportError: dlopen(/Users/janit/Downloads/Chia.app/Contents/Resources/app.asar.unpacked/daemon/_internal/lib-dynload/_ssl.cpython-310-darwin.so, 0x0002): Symbol not found: _X509_STORE_get1_objects
  Referenced from: <255D5D5D-5C68-3DA1-A40D-1D4A3D49EF46> /Users/janit/Downloads/Chia.app/Contents/Resources/app.asar.unpacked/daemon/_internal/lib-dynload/_ssl.cpython-310-darwin.so
  Expected in:     <3D2637A1-34E4-38A3-B599-4063C39534A2> /opt/homebrew/Cellar/openssl@3/3.2.1/lib/libcrypto.3.dylib
[24829] Failed to execute script 'chia' due to unhandled exception!
```

**Comment by BrandtH22** [comment]
@janit , there were some dependency updates in 2.3.1 and brew packages need to be updated accordingly. 

In terminal you will need to run:
- `brew update`
- `brew upgrade`

Then start 2.3.1 of chia and it will launch as expected. I have reproduced the above error and resolved it with this update.
Let us know if any other questions arise and happy farming!

**Comment by janit** [comment]
Yup did that and  got a bunch of updates, including:

```
==> Upgrading openssl@3
  3.2.1 -> 3.3.0
==> Pouring openssl@3--3.3.0.arm64_sonoma.bottle.1.tar.gz
🍺  /opt/homebrew/Cellar/openssl@3/3.3.0: 6,977 files, 32.4MB
```

Still bugs me a bit that this dependency silently kills the GUI app. I guess those who installs Brew can expect that, but where is it pulled from if you're not running Brew? Just the standard macOS one (that is compatible)?

**Comment by degiorgig** [comment]
> @janit , there were some dependency updates in 2.3.1 and brew packages need to be updated accordingly.
> 
> In terminal you will need to run:
> 
> * `brew update`
> * `brew upgrade`
> 
> Then start 2.3.1 of chia and it will launch as expected. I have reproduced the above error and resolved it with this update. Let us know if any other questions arise and happy farming!

fixed also for me..
