### ISSUE TITLE
[Bug] config.yaml full_node weight_proof_timeout is not respected (timeout after 90 sec)

### ISSUE THREAD

**Issue by madMAx43v3r** [Chia-Network/chia-blockchain#18211]
### What happened?

When trying to sync the node over a slow mobile network, it's unable to receive any weight proof in time.

It always fails with `RuntimeError: Weight proof did not arrive in time from peer` after around 90 seconds,
even though the timeout has been set to 360 seconds (default value), as shown from the debug output.

### Version

2.3.0

### What platform are you using?

Linux

### What ui mode are you using?

CLI

### Relevant log output

```shell
2024-06-20T14:56:31.427 full_node chia.full_node.full_node: INFO     Requesting weight proof from peer 37.235.174.43 up to height 5531555
2024-06-20T14:56:31.428 full_node chia.full_node.full_node: DEBUG    weight proof timeout is 360 sec
2024-06-20T14:58:06.497 full_node full_node_server        : DEBUG    Time for request request_proof_of_weight: PeerInfo(_ip=IPv4Address('37.235.174.43'), _port=8444) = 95.06866121292114, None? True
2024-06-20T14:58:06.498 full_node full_node_server        : WARNING  Banning 37.235.174.43 for 600 seconds
2024-06-20T14:58:06.499 full_node chia.full_node.full_node: ERROR    Error with syncing: <class 'RuntimeError'>Traceback (most recent call last):
  File "/opt/chia/chia/full_node/full_node.py", line 970, in _sync
  File "/opt/chia/chia/full_node/full_node.py", line 1011, in request_validate_wp
RuntimeError: Weight proof did not arrive in time from peer: 37.235.174.43
```

**Comment by wjblanke** [comment]
This happens with every peer? A log like this can happen if the peer disconnects. We used to recommend this early on when weight proofs took longer to validate and the timeout worked. Can u debug further to see if the 360 timeout isn't being honored in the code. It may take some time for an engineer here to get a "dialup" connection to test.

Maybe the issue is the lack of traffic on the websocket causing it to disconnect. Do you have a proxy running that would disconnect a silent connection.

**Comment by emlowe** [comment]
Max, in `server.py` there is a function `start_client` - maybe experiment with some different `heartbeat` settings here - it's not configurable in config.yaml, only in the code
```               
ws = await session.ws_connect(
            url,
            autoclose=True,
            autoping=True,
            heartbeat=60,
            ssl=self.ssl_client_context,
            max_msg_size=max_message_size,
)
```

**Comment by madMAx43v3r** [comment]
Yes it happened for many hours with every peer it tried. Always 90 sec timeout, response `None`.
I checked the code but I could not find any path where it could possibly return `None`...

I don't think the connection was idle, it was probably downloading the weight proof, just too slow.

You can try it with using your phone via USB tethering. The phone is acting as a router in this case. I had no issue downloading chia blockchain releases from github, which are 200 MB. So I don't think my phone was somehow killing connections.

The log also shows that the wallet banned the peer, it didn't disconnect.

**Comment by madMAx43v3r** [comment]
![image](https://github.com/Chia-Network/chia-blockchain/assets/951738/e5709de1-ba0e-4aae-84d7-672009ca258f)

If that's the issue, then it's probably on the server side, since the ping message from the server would not be received in time for the client to send back the pong.

While my wallet is busy receiving the weight proof, the server side ping would be stuck in the send queue.

**Comment by emlowe** [comment]
The server code doesn't set any of those parameters though - so tweaking them on the client should change the behaviour of the connection in general - the server code uses all aiohttp defaults for the most part.

I might try setting heartbeat=None and/or setting it very high

**Comment by emlowe** [comment]
You are right that I would expect some other log entries though if the connection was being closed abnormally - so I'm very unsure it will change anything for you

**Comment by madMAx43v3r** [comment]
Oh I see now, `send_request()` does return `None` in case `asyncio.wait_for()` returns without receiving the response first.
