### ISSUE TITLE
[Bug] Pressing the back arrow on the New Wallet page causes GUI to stall

### ISSUE THREAD

**Issue by chia-rschmidt** [Chia-Network/chia-blockchain#18416]
### What happened?

When on the New Wallet page, clicking the back arrow causes the GUI to get stuck on a page saying "Loading keyring status".

![TC-charlie1](https://github.com/user-attachments/assets/84b04906-2a1a-48d3-a15f-b269faf331e5)
![TC-Charlie2](https://github.com/user-attachments/assets/111f705c-4541-4699-a378-18cfd18a35d1)

### Version

2.4.3-rc1

### What platform are you using?

Linux

### What ui mode are you using?

GUI

### Relevant log output

```shell
2024-08-06T22:06:50.395 full_node full_node_server        : WARNING  Banning 65.109.30.123 for 10 seconds
2024-08-06T22:06:50.397 full_node full_node_server        : WARNING  Invalid handshake with peer PeerInfo(_ip=IPv4Address('65.109.30.123'), _port=58444). Maybe the peer is running old software.
2024-08-06T22:15:22.512 full_node full_node_server        : WARNING  Banning 222.128.30.73 for 10 seconds
2024-08-06T22:15:22.513 full_node full_node_server        : WARNING  Invalid handshake with peer PeerInfo(_ip=IPv4Address('222.128.30.73'), _port=8888). Maybe the peer is running old software.
2024-08-06T22:35:09.396 full_node full_node_server        : WARNING  Cannot write to closing transport 75.70.34.135
2024-08-06T22:43:49.218 full_node full_node_server        : WARNING  Banning 65.109.30.123 for 10 seconds
2024-08-06T22:43:49.219 full_node full_node_server        : WARNING  Invalid handshake with peer PeerInfo(_ip=IPv4Address('65.109.30.123'), _port=58444). Maybe the peer is running old software.
2024-08-06T22:48:18.192 full_node asyncio                 : ERROR    Future exception was never retrieved
future: <Future finished exception=ConnectionError('Connection lost')>
Traceback (most recent call last):
  File "asyncio/selector_events.py", line 949, in _write_ready
BrokenPipeError: [Errno 32] Broken pipe

The above exception was the direct cause of the following exception:

ConnectionError: Connection lost
2024-08-06T22:48:57.632 full_node chia.full_node.mempool_manager: WARNING  updating the mempool using the slow-path. peak: 55a02626eabfae0c651d805e6f2682088ef1797e56049f28cc8719eb96f4ef3b new-peak-prev: 52dc4aab9972fa6150d6f556c61a5acd910552b4623fa84171cb92bfc5041c94 coins: not set
2024-08-06T22:48:59.478 wallet wallet_server              : WARNING  Connection failed to wss://104.248.202.108:58444/ws. Error: 403, message='Invalid response status', url=URL('wss://104.248.202.108:58444/ws')
2024-08-06T22:49:25.167 full_node full_node_server        : WARNING  Banning 65.21.193.9 for 10 seconds
2024-08-06T22:49:25.167 full_node full_node_server        : WARNING  Invalid handshake with peer PeerInfo(_ip=IPv4Address('65.21.193.9'), _port=58444). Maybe the peer is running old software.
2024-08-06T22:50:21.203 wallet chia.wallet.wallet_node    : WARNING  querying DNS introducer failed: All nameservers failed to answer the query dns-introducer-testnet11.chia.net. IN A: Server Do53:127.0.0.53@53 answered SERVFAIL
2024-08-06T22:58:49.450 wallet chia.wallet.wallet_state_manager: ERROR    set_sync_mode failed - range: 1158838-1158838, seconds: 0.007984161376953125
Traceback (most recent call last):
  File "chia/wallet/wallet_state_manager.py", line 674, in set_sync_mode
  File "chia/wallet/wallet_node.py", line 1235, in long_sync_from_untrusted
  File "chia/wallet/wallet_node.py", line 847, in long_sync
  File "chia/wallet/util/wallet_sync_utils.py", line 61, in subscribe_to_phs
ValueError: None response from peer 47.197.8.197 for register_interest_in_puzzle_hash
```

**Comment by markdisano** [comment]
I have the same issue on 2.4.3.rc3-arm on Mac OS 14.6.1 using the GUI. 

Attaching video displaying a minute of the state. I left it for an additional 5 mins to see if it would recover but it did not.

https://github.com/user-attachments/assets/5a187814-b0e0-4e0b-9f65-be9dd9b728e7

**Comment by chia-rschmidt** [comment]
Heres the INFO log from Ubuntu when the bug occurred.

2024-08-15T11:00:05.269 wallet chia.wallet.wallet_node    : INFO     new coin state received (1-1/ 1)
2024-08-15T11:00:05.278 wallet chia.wallet.wallet_node    : INFO     new coin state received (1-1/ 1)
2024-08-15T11:00:05.374 wallet chia.wallet.wallet_node    : INFO     new coin state received (1-1/ 1)
2024-08-15T11:00:05.385 wallet chia.wallet.wallet_node    : INFO     new coin state received (1-1/ 1)
2024-08-15T11:00:05.481 wallet chia.wallet.wallet_node    : INFO     new coin state received (1-1/ 1)
2024-08-15T11:00:05.492 wallet chia.wallet.wallet_node    : INFO     new coin state received (1-3/ 3)
2024-08-15T11:00:05.593 wallet chia.wallet.wallet_node    : INFO     new coin state received (1-3/ 3)
2024-08-15T11:00:06.318 full_node chia.full_node.full_node: INFO     Starting to perform sync.
2024-08-15T11:00:06.318 full_node chia.full_node.full_node: INFO     Waiting to receive peaks from peers. (timeout: 30.0s)
2024-08-15T11:00:06.710 wallet chia.wallet.wallet_node    : INFO     disconnected from peer 07e70e666a55af06e8df1aa01b8bde257c154630bf03c5166bb8462985c1b49b, state will retry with 6e55f0eb44407ddd46106393271a8acdcb6bdfbceea30c1d6eb141be57d0fc70
2024-08-15T11:00:06.711 wallet chia.wallet.wallet_node    : INFO     retrying coin_state: CoinState { coin: Coin { parent_coin_info: 0d35df203fe554a8e59610ae057db932da97c1cc4d2eee3ff80e3ed7778974cd, puzzle_hash: 22cfdfb3034978dc3c7e67b891ecb31bb4e9a95fc3e2ebcc0dc050c61910a37b, amount: 1 }, spent_height: None, created_height: Some(1190818) }
2024-08-15T11:00:06.762 wallet chia.wallet.wallet_node    : INFO     disconnected from peer 07e70e666a55af06e8df1aa01b8bde257c154630bf03c5166bb8462985c1b49b, state will retry with 6e55f0eb44407ddd46106393271a8acdcb6bdfbceea30c1d6eb141be57d0fc70
2024-08-15T11:00:06.762 wallet chia.wallet.wallet_node    : INFO     retrying coin_state: CoinState { coin: Coin { parent_coin_info: 1fb67f2ef1e8a07d12971c2fc82631e1ab905e5511c85a06e484a30ce899abcd, puzzle_hash: 2f4959b5d68cf62dafe99ff05fcd526c6f1e6891f1e5b58853eaf7c5c0c2ec36, amount: 3000000000 }, spent_height: None, created_height: Some(1190818) }
2024-08-15T11:00:06.768 wallet chia.wallet.wallet_node    : INFO     disconnected from peer 07e70e666a55af06e8df1aa01b8bde257c154630bf03c5166bb8462985c1b49b, state will retry with 6e55f0eb44407ddd46106393271a8acdcb6bdfbceea30c1d6eb141be57d0fc70
2024-08-15T11:00:06.768 wallet chia.wallet.wallet_node    : INFO     retrying coin_state: CoinState { coin: Coin { parent_coin_info: 334f4c25aae438eb3af9d64040317ceba0a4889101c799e7d602af174ac99a6c, puzzle_hash: cfbfdeed5c4ca2de3d0bf520b9cb4bb7743a359bd2e6a188d19ce7dffc21d3e7, amount: 3000000000 }, spent_height: Some(1190818), created_height: Some(1190818) }
2024-08-15T11:00:06.831 full_node full_node_server        : INFO     Cannot connect to host 2600:1f13:c55:4403:854c:65aa:c1c4:cde1:58444 ssl:<ssl.SSLContext object at 0x7e72f2eaaec0> [Network is unreachable]
2024-08-15T11:00:07.538 full_node full_node_server        : WARNING  Banning 210.209.69.36 for 10 seconds
2024-08-15T11:00:07.539 full_node full_node_server        : INFO     Connection closed: 210.209.69.36, node id: 8f3b40cbb350c519a0eab69e8bb6efce417447c90fd8e4f4842f02c2079b31ef
2024-08-15T11:00:07.539 full_node chia.full_node.full_node: INFO     peer disconnected PeerInfo(_ip=IPv4Address('210.209.69.36'), _port=2213)
2024-08-15T11:00:07.540 full_node full_node_server        : WARNING  Incompatible network ID. Maybe the peer is on another network
2024-08-15T11:00:08.222 wallet wallet_server              : INFO     Cannot connect to host 2607:fb91:2d85:4c03:c49e:ae9a:2361:cc76:58444 ssl:<ssl.SSLContext object at 0x7e1040fb2c40> [Network is unreachable]
2024-08-15T11:00:09.724 wallet wallet_server              : INFO     Cannot connect to host 2601:280:5f80:45e0:a193:88e5:2489:f84f:58444 ssl:<ssl.SSLContext object at 0x7e1040fb2c40> [Network is unreachable]
2024-08-15T11:00:11.470 wallet chia.full_node.weight_proof: INFO     validating 3119 sub epochs
2024-08-15T11:00:11.477 wallet chia.full_node.weight_proof: INFO     validate weight proof peak height 1197977
2024-08-15T11:00:13.949 full_node full_node_server        : INFO     Cannot connect to host 38.98.191.157:58444 ssl:<ssl.SSLContext object at 0x7e72f2eaaec0> [Connect call failed ('38.98.191.157', 58444)]
2024-08-15T11:00:14.709 full_node full_node_server        : INFO     Cannot connect to host 38.98.191.114:58444 ssl:<ssl.SSLContext object at 0x7e72f2eaaec0> [Connect call failed ('38.98.191.114', 58444)]
2024-08-15T11:00:15.114 wallet chia.wallet.wallet_node    : INFO     Connected peer PeerInfo(_ip=IPv4Address('95.175.123.111'), _port=58444) is trusted: False
2024-08-15T11:00:15.118 wallet wallet_server              : INFO     Connected with full_node PeerInfo(_ip=IPv4Address('95.175.123.111'), _port=58444)
2024-08-15T11:00:15.729 wallet chia.wallet.wallet_node_api: INFO     Wallet received 535 peers.
2024-08-15T11:00:16.203 daemon chia.daemon.server         : INFO     Service chia_wallet already running
2024-08-15T11:00:16.203 daemon chia.daemon.server         : INFO     Service chia_full_node already running
2024-08-15T11:00:16.204 daemon chia.daemon.server         : INFO     Service chia_farmer already running
2024-08-15T11:00:16.204 daemon chia.daemon.server         : INFO     Service chia_harvester already running
2024-08-15T11:00:18.191 full_node full_node_server        : INFO     Connected with full_node PeerInfo(_ip=IPv4Address('162.254.33.176'), _port=58444)
2024-08-15T11:00:18.282 full_node chia.full_node.full_node: INFO     Collected a total of 3 peaks.
2024-08-15T11:00:18.282 full_node chia.full_node.full_node: INFO     Selected peak Peak(header_hash=<bytes32: 29f6966559bbd61da54fbe7a83f86522a1ffbd4c96239a149afa31c3ded5c010>, height=1197989, weight=726963980402)
2024-08-15T11:00:18.813 full_node chia.full_node.full_node: INFO     Total of 2 peers with peak 1197989
2024-08-15T11:00:18.813 full_node chia.full_node.full_node: INFO     Requesting weight proof from peer 85.215.63.125 up to height 1197989
2024-08-15T11:00:21.877 full_node full_node_server        : INFO     Cannot connect to host 114.37.194.28:58444 ssl:<ssl.SSLContext object at 0x7e72f2eaaec0> [Connect call failed ('114.37.194.28', 58444)]
2024-08-15T11:00:21.987 wallet chia.wallet.wallet_weight_proof_handler: INFO     It took 10.52043080329895 time to validate the weight proof aa7942a007db17505b69155912d787a55ca60ca2d41212f7a7bb1d5ada5ff56a
2024-08-15T11:00:22.030 wallet chia.wallet.wallet_blockchain: INFO     Peak set to: 1197977 timestamp: 1723733747
2024-08-15T11:00:22.128 wallet chia.wallet.wallet_state_manager: INFO     set_sync_mode syncing - range: 1190407-1197977
2024-08-15T11:00:22.128 wallet chia.wallet.wallet_node    : INFO     Starting sync trusted: False to peer 207.228.216.7
2024-08-15T11:00:22.128 wallet chia.wallet.wallet_node    : INFO     perform_atomic_rollback to 1190391
2024-08-15T11:00:25.891 wallet chia.wallet.wallet_node    : INFO     new coin state received (31-33/ 33)
2024-08-15T11:00:26.027 full_node full_node_server        : INFO     Cannot connect to host 109.250.226.167:8666 ssl:<ssl.SSLContext object at 0x7e72f2eaaec0> [Connect call failed ('109.250.226.167', 8666)]
2024-08-15T11:00:26.043 wallet chia.wallet.wallet_state_manager: INFO     Setting tx_id: 271988ce3b2098e2dca97895460972eb7123bf0e6248c65e57953137566629b8 to confirmed
2024-08-15T11:00:28.106 full_node full_node_server        : INFO     Cannot connect to host 240e:398:df:36e0:1e69:7aff:fe6c:311b:58444 ssl:<ssl.SSLContext object at 0x7e72f2eaaec0> [Network is unreachable]
2024-08-15T11:00:31.528 wallet chia.wallet.wallet_node    : INFO     new coin state received (11-20/ 33)

**Comment by BrandtH22** [comment]
Hey @chia-rschmidt thank you for confirming, I am able to reproduce the issue locally also. The team will review as time permits and determine the best course of action to resolve.

**Comment by ChiaMineJP** [comment]
I'll look into this.

**Comment by ChiaMineJP** [comment]
This issue will be fixed by https://github.com/Chia-Network/chia-blockchain-gui/pull/2471
