### ISSUE TITLE
[Bug] Clearing transactions during plot NFT setup causes it to be stuck indefinitely

### ISSUE THREAD

**Issue by chia-rschmidt** [Chia-Network/chia-blockchain#18489]
### What happened?

When creating a plot NFT, there was some issue that caused the transaction to not be accepted for over an hour. It was stuck on `Waiting for the transaction to be confirmed`. In an attempt to clear the faulty pool/transaction, I selected `Delete Unconfirmed Transactions`. This resulted in the Plot NFT being stuck indefinitely, even through GUI restarts.

Steps to recreate: 
1. Add A Plot NFT and select Create
2. Go to Tokens tab and select `Delete Unconfirmed Transactions`

![Screenshot from 2024-08-17 17-28-44](https://github.com/user-attachments/assets/d0120784-cef8-40b5-8db1-8239c5ed2109)

### Version

2.4.3-rc3

### What platform are you using?

Linux

### What ui mode are you using?

GUI

### Relevant log output

```shell
2024-08-18T17:59:33.704 wallet chia.wallet.wallet_node    : ERROR    Error syncing to PeerInfo(_ip=IPv4Address('35.90.101.18'), _port=58444)
Traceback (most recent call last):
  File "chia/wallet/wallet_node.py", line 1220, in new_peak_from_untrusted
  File "chia/wallet/wallet_node.py", line 1229, in long_sync_from_untrusted
  File "chia/wallet/wallet_node.py", line 1358, in fetch_and_update_weight_proof
Exception: weight proof response was none
2024-08-18T17:59:33.704 wallet chia.wallet.wallet_node    : WARNING  Peer PeerInfo(_ip=IPv4Address('73.164.88.229'), _port=58444) did not respond in time.
2024-08-18T17:59:33.705 wallet wallet_server              : WARNING  Banning 73.164.88.229 for 120 seconds
2024-08-18T17:59:55.047 full_node full_node_server        : WARNING  Connection failed to wss://104.248.202.108:58444/ws. Error: 403, message='Invalid response status', url=URL('wss://104.248.202.108:58444/ws')
2024-08-18T18:00:07.071 wallet chia.rpc.rpc_server        : WARNING  Error while handling message: Traceback (most recent call last):
  File "chia/rpc/rpc_server.py", line 340, in safe_handle
  File "chia/rpc/rpc_server.py", line 331, in ws_api
  File "chia/rpc/wallet_rpc_api.py", line 1010, in get_transaction
ValueError: Transaction 0xdb2605863a8ec6e93325cf1408957c1c89ac07d336f05f5f7973fe22a1ee2d80 not found

2024-08-18T18:00:12.084 wallet chia.rpc.rpc_server        : WARNING  Error while handling message: Traceback (most recent call last):
  File "chia/rpc/rpc_server.py", line 340, in safe_handle
  File "chia/rpc/rpc_server.py", line 331, in ws_api
  File "chia/rpc/wallet_rpc_api.py", line 1010, in get_transaction
ValueError: Transaction 0xdb2605863a8ec6e93325cf1408957c1c89ac07d336f05f5f7973fe22a1ee2d80 not found

2024-08-18T18:00:17.090 wallet chia.rpc.rpc_server        : WARNING  Error while handling message: Traceback (most recent call last):
  File "chia/rpc/rpc_server.py", line 340, in safe_handle
  File "chia/rpc/rpc_server.py", line 331, in ws_api
  File "chia/rpc/wallet_rpc_api.py", line 1010, in get_transaction
ValueError: Transaction 0xdb2605863a8ec6e93325cf1408957c1c89ac07d336f05f5f7973fe22a1ee2d80 not found

2024-08-18T18:00:22.097 wallet chia.rpc.rpc_server        : WARNING  Error while handling message: Traceback (most recent call last):
  File "chia/rpc/rpc_server.py", line 340, in safe_handle
  File "chia/rpc/rpc_server.py", line 331, in ws_api
  File "chia/rpc/wallet_rpc_api.py", line 1010, in get_transaction
ValueError: Transaction 0xdb2605863a8ec6e93325cf1408957c1c89ac07d336f05f5f7973fe22a1ee2d80 not found

2024-08-18T18:00:27.105 wallet chia.rpc.rpc_server        : WARNING  Error while handling message: Traceback (most recent call last):
  File "chia/rpc/rpc_server.py", line 340, in safe_handle
  File "chia/rpc/rpc_server.py", line 331, in ws_api
  File "chia/rpc/wallet_rpc_api.py", line 1010, in get_transaction
ValueError: Transaction 0xdb2605863a8ec6e93325cf1408957c1c89ac07d336f05f5f7973fe22a1ee2d80 not found
```

**Comment by BrandtH22** [comment]
Hey @chia-rschmidt , this is an expected issue as the clearing of the transactions removes it from the wallet and when closing then reopening the GUI it is unable to identify the transaction as it no longer exists. 

Can you:
- stop chia
- rename the config file at ~/.chia/mainnet/config/config.yaml (note if you changed your chia root to a testnet directory please rename the config there)
- delete the wallet db at ~/.chia/mainnet/wallet/db/ (note if you changed your chia root to a testnet directory please delete the wallet db there)
- run `chia init`
- run `chia configure --testnet true`
- start chia and let it sync fully
- once synced can you check if that failed plot NFT is still showing?

This will bring the wallet db and the config back to an original state and resync the plotNFTs that currently exist which should remove that failed plotNFT
