### ISSUE TITLE
Cannot start wallet on Ubuntu 18.04 on windows

### ISSUE THREAD

**Issue by ashjs1** [Chia-Network/chia-blockchain#185]
I've generated three hard drive plots. After generating the third, I now get this when I try to run: chia-start-wallet-server &

(venv) ashjs@DESKTOP-JI7HN2I:~$  chia-start-wallet-server &
[6] 923
[3]   Done                    chia-start-farmer
(venv) ashjs@DESKTOP-JI7HN2I:~$ Starting process and logging to /home/ashjs/.chia/beta-1.0b3/log/debug.log. Run with & to run in the background.
Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/ashjs/venv/lib/python3.7/site-packages/src/wallet/websocket_server.py", line 442, in <module>
    main()
  File "/home/ashjs/venv/lib/python3.7/site-packages/src/wallet/websocket_server.py", line 437, in main
    asyncio.run(start_websocket_server())
  File "/usr/lib/python3.7/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.7/asyncio/base_events.py", line 579, in run_until_complete
    return future.result()
  File "/home/ashjs/venv/lib/python3.7/site-packages/src/wallet/websocket_server.py", line 384, in start_websocket_server
    wallet_node = await WalletNode.create(config, key_config)
  File "/home/ashjs/venv/lib/python3.7/site-packages/src/wallet/wallet_node.py", line 89, in create
    key_config, config, path, self.constants
  File "/home/ashjs/venv/lib/python3.7/site-packages/src/wallet/wallet_state_manager.py", line 102, in create
    self.block_records = await self.wallet_store.get_lca_path()
  File "/home/ashjs/venv/lib/python3.7/site-packages/src/wallet/wallet_store.py", line 348, in get_lca_path
    assert max_height == len(rows) - 1
AssertionError

**Comment by mariano54** [comment]
This happens when you have multiple wallet servers running. Close all wallets, restart your computer, delete ~/.chia/beta-1.0b3/wallet/db/*, and try again

**Comment by ashjs1** [comment]
That's fixed it. Thank you!
