### ISSUE TITLE
[Bug] Balance is not displayed

### ISSUE THREAD

**Issue by krayneakkuraten** [Chia-Network/chia-blockchain#18545]
### What happened?

_Hey, everybody!_ 
It's been a while since I've logged into Chia Blockchain wallet. Yesterday I logged in and found that the account shows 0 XCH, although everything is OK in xch scanner. 

Please help me to solve the problem!

**Some explanations**
The status of the wallet is lit yellow;
When you click on a wallet, the following is displayed: 
```
Node ID
IP address
Port
MiB Outbound/Inbound
Connection type
0x650428f5c4ea9e0bf2215b160f74e1fb794ad35c35c4da788c95902c1da536a4
178.78.59.179
8444/8444
0.00/0.03
Full Node
0x9d20682be0508e05d2d9b2b3211401135b8f5f1e951a343f9123a67975b131a3
174.74.52.129
8444/8444
0.00/0.03
Full Node
```

The derivation index is constantly updated (I can't change it therefore)

**What I've been trying to do**
I went to settings -> advanced -> clicked RESYNC;
Deleted the contents of .chia/wallet/**db**;
Reinstalled Chia Blockhain v2.4.3 application.

Logs from debug.log below

### Version

2.4.3

### What platform are you using?

Windows

### What ui mode are you using?

GUI

### Relevant log output

```shell
2024-09-01T14:59:33.072 wallet chia.full_node.weight_proof: ERROR    failed validating weight proof recent blocks
2024-09-01T14:59:33.076 wallet chia.wallet.wallet_node    : ERROR    Error syncing to PeerInfo(_ip=IPv4Address('46.146.248.89'), _port=8444)
Traceback (most recent call last):
  File "chia\wallet\wallet_node.py", line 1220, in new_peak_from_untrusted
  File "chia\wallet\wallet_node.py", line 1229, in long_sync_from_untrusted
  File "chia\wallet\wallet_node.py", line 1370, in fetch_and_update_weight_proof
  File "chia\wallet\wallet_weight_proof_handler.py", line 66, in validate_weight_proof
ValueError: weight proof validation failed
2024-09-01T14:59:33.096 wallet chia.wallet.wallet_node    : WARNING  Peer None did not respond in time.
2024-09-01T14:59:33.096 wallet wallet_server              : WARNING  Banning 31.17.24.187 for 120 seconds
2024-09-01T14:59:33.100 wallet chia.wallet.wallet_node    : WARNING  Peer None did not respond in time.
2024-09-01T14:59:33.100 wallet wallet_server              : WARNING  Banning 31.17.24.187 for 120 seconds
2024-09-01T14:59:33.104 wallet chia.wallet.wallet_node    : WARNING  Peer PeerInfo(_ip=IPv4Address('46.146.248.89'), _port=8444) did not respond in time.
2024-09-01T14:59:33.104 wallet wallet_server              : WARNING  Banning 46.146.248.89 for 120 seconds
2024-09-01T14:59:33.108 wallet chia.wallet.wallet_node    : WARNING  Peer None did not respond in time.
2024-09-01T14:59:33.108 wallet wallet_server              : WARNING  Banning 91.109.21.175 for 120 seconds
2024-09-01T14:59:33.112 wallet chia.wallet.wallet_node    : WARNING  Peer None did not respond in time.
2024-09-01T14:59:33.116 wallet wallet_server              : WARNING  Banning 91.109.21.175 for 120 seconds
2024-09-01T14:59:33.120 wallet chia.wallet.wallet_node    : WARNING  Peer PeerInfo(_ip=IPv4Address('46.146.248.89'), _port=8444) did not respond in time.
2024-09-01T14:59:33.124 wallet wallet_server              : WARNING  Banning 46.146.248.89 for 120 seconds
2024-09-01T14:59:33.124 wallet chia.wallet.wallet_node    : WARNING  Peer None did not respond in time.
2024-09-01T14:59:33.128 wallet wallet_server              : WARNING  Banning 31.17.24.187 for 120 seconds
2024-09-01T14:59:33.132 wallet chia.wallet.wallet_node    : WARNING  Peer None did not respond in time.
2024-09-01T14:59:33.132 wallet wallet_server              : WARNING  Banning 31.17.24.187 for 120 seconds
2024-09-01T14:59:33.136 wallet chia.wallet.wallet_node    : WARNING  Peer PeerInfo(_ip=IPv4Address('46.146.248.89'), _port=8444) did not respond in time.
2024-09-01T14:59:33.136 wallet wallet_server              : WARNING  Banning 46.146.248.89 for 120 seconds
2024-09-01T14:59:33.140 wallet chia.wallet.wallet_node    : WARNING  Peer None did not respond in time.
2024-09-01T14:59:33.140 wallet wallet_server              : WARNING  Banning 91.109.21.175 for 120 seconds
2024-09-01T14:59:56.327 wallet chia.full_node.weight_proof: ERROR    failed validating weight proof recent blocks
2024-09-01T14:59:56.331 wallet chia.wallet.wallet_node    : ERROR    Error syncing to PeerInfo(_ip=IPv4Address('188.173.167.165'), _port=8444)
Traceback (most recent call last):
  File "chia\wallet\wallet_node.py", line 1220, in new_peak_from_untrusted
  File "chia\wallet\wallet_node.py", line 1229, in long_sync_from_untrusted
  File "chia\wallet\wallet_node.py", line 1370, in fetch_and_update_weight_proof
  File "chia\wallet\wallet_weight_proof_handler.py", line 66, in validate_weight_proof
ValueError: weight proof validation failed
2024-09-01T14:59:56.351 wallet chia.wallet.wallet_node    : WARNING  Peer None did not respond in time.
2024-09-01T14:59:56.351 wallet wallet_server              : WARNING  Banning 31.17.24.187 for 120 seconds
2024-09-01T14:59:56.355 wallet chia.wallet.wallet_node    : WARNING  Peer None did not respond in time.
2024-09-01T14:59:56.355 wallet wallet_server              : WARNING  Banning 46.146.248.89 for 120 seconds
2024-09-01T14:59:56.359 wallet chia.wallet.wallet_node    : WARNING  Peer PeerInfo(_ip=IPv4Address('188.173.167.165'), _port=8444) did not respond in time.
2024-09-01T14:59:56.359 wallet wallet_server              : WARNING  Banning 188.173.167.165 for 120 seconds
2024-09-01T14:59:56.363 wallet chia.wallet.wallet_node    : WARNING  Peer None did not respond in time.
2024-09-01T14:59:56.363 wallet wallet_server              : WARNING  Banning 46.146.248.89 for 120 seconds
2024-09-01T14:59:56.363 wallet chia.wallet.wallet_node    : WARNING  Peer None did not respond in time.
2024-09-01T14:59:56.363 wallet wallet_server              : WARNING  Banning 46.146.248.89 for 120 seconds
2024-09-01T15:00:03.861 wallet chia.rpc.util              : WARNING  Error while handling message: Traceback (most recent call last):
  File "chia\rpc\util.py", line 84, in inner
  File "chia\rpc\wallet_rpc_api.py", line 4265, in dl_owned_singletons
  File "chia\wallet\wallet_state_manager.py", line 2624, in get_dl_wallet
ValueError: DataLayerWallet not available
```

**Comment by krayneakkuraten** [comment]
The issue was solved by enabling VPN

**Comment by goncastrum** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by goncastrum** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx
