### ISSUE TITLE
[Bug] 'chia keys derive wallet-address' unhandled exception

### ISSUE THREAD

**Issue by DrakoPensulo** [Chia-Network/chia-blockchain#18626]
### What happened?

The command 'chia keys derive wallet-address' fails due to an unhandled exception. It seems that versions <=2.4 or 2.4.1 did not have that issue. 

### Version

2.4.3

### What platform are you using?

Windows

### What ui mode are you using?

CLI

### Relevant log output

```shell
chia keys derive wallet-address
Traceback (most recent call last):
  File "chia\cmds\chia.py", line 143, in <module>
  File "chia\cmds\chia.py", line 139, in main
  File "click\core.py", line 1157, in __call__
  File "click\core.py", line 1078, in main
  File "click\core.py", line 1688, in invoke
  File "click\core.py", line 1688, in invoke
  File "click\core.py", line 1688, in invoke
  File "click\core.py", line 1434, in invoke
  File "click\core.py", line 783, in invoke
  File "click\decorators.py", line 33, in new_func
  File "chia\cmds\keys.py", line 382, in wallet_address_cmd
  File "chia\cmds\keys_funcs.py", line 660, in derive_wallet_address
AssertionError
[29884] Failed to execute script 'chia' due to unhandled exception!
```

**Comment by BrandtH22** [comment]
Hey @DrakoPensulo , thank you for the report. I am able to reproduce the issue and the team is looking into a solution for it.

**Comment by thesemaphoreslim** [comment]
I was able to reproduce this; however, adding "-f <fingerprint_of_wallet>" resolved the issue.  Perhaps the fingerprint is simply required now?

**Comment by wjblanke** [comment]
@Quexington were you able to reproduce? maybe fingerprint is a workaround with the recent changes? IIRC the previous issue involved which default keyring to use.

**Comment by BrandtH22** [comment]
@wjblanke @Quexington , I have confirmed that this is fixed in main

**Comment by BrandtH22** [comment]
This issue has been fixed in main with #18516 and will be included in the next release

**Comment by BrandtH22** [comment]
Hey @DrakoPensulo , this fix should now be in the latest RC. Can you test it to see if the error is resolved on your side?
https://github.com/Chia-Network/chia-blockchain/releases/tag/2.4.4-rc1

**Comment by DrakoPensulo** [comment]
@BrandtH22 It seems it works in 2.4.4 rc3.

**Comment by BrandtH22** [comment]
Thank you for the confirmation @DrakoPensulo 🥳 Let us know if other issues or questions arise
