### ISSUE TITLE
[Bug] The wallet doesn't start

### ISSUE THREAD

**Issue by zMotoR** [Chia-Network/chia-blockchain#18677]
### What happened?

After the installation I run chia, the window appears, and spinner spins endlessly. I started to expect whats happening. Chia.exe starts "resources\app.asar.unpacked\daemon\chia start daemon --skip-keyring" and then "resources\app.asar.unpacked\daemon\chia run_daemon --wait-for-unlock". Then both exe files from daemon folder do finish. After that chia.exe is still waiting something. The log file is empty.

I tried to run "chia start daemon --skip-keyring" in the console, that's the result:

chia start daemon --skip-keyring
Daemon not started yet
Starting daemon
Starting daemon: chia run_daemon --wait-for-unlock
Traceback (most recent call last):
  File "chia\cmds\chia.py", line 143, in <module>
  File "chia\cmds\chia.py", line 139, in main
  File "click\core.py", line 1157, in __call__
  File "click\core.py", line 1078, in main
  File "click\core.py", line 1688, in invoke
  File "click\core.py", line 1434, in invoke
  File "click\core.py", line 783, in invoke
  File "click\decorators.py", line 33, in new_func
  File "chia\cmds\start.py", line 24, in start_cmd
  File "asyncio\runners.py", line 44, in run
  File "asyncio\base_events.py", line 649, in run_until_complete
  File "chia\cmds\start_funcs.py", line 81, in async_start
  File "chia\cmds\start_funcs.py", line 54, in create_start_daemon_connection
  File "codecs.py", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf8 in position 31: invalid start byte
[23908] Failed to execute script 'chia' due to unhandled exception!

I think this is because I use UTF-8 user name in the PC.

### Version

2.4.3

### What platform are you using?

Windows

### What ui mode are you using?

GUI

**Comment by zMotoR** [comment]
Also I tried to start Chia on another computer without utf-8 user name with similar result: spinner spins endlessly. Whe I tried to run "chia start daemon --skip-keyring" I have another result:

chia start daemon --skip-keyring
Daemon not started yet
Starting daemon
Starting daemon: chia run_daemon --wait-for-unlock
Daemon not started yet
Failed to create the chia daemon

The log:

2024-10-07T16:50:07.326 daemon filelock                   : DEBUG    Attempting to acquire lock 2687494145360 on C:\Users\alex\.chia\mainnet\run\daemon.lock
2024-10-07T16:50:07.329 daemon filelock                   : DEBUG    Lock 2687494145360 acquired on C:\Users\alex\.chia\mainnet\run\daemon.lock
2024-10-07T16:50:07.335 daemon chia.daemon.server         : INFO     chia-blockchain version: 2.4.3
2024-10-07T16:50:07.337 daemon filelock                   : DEBUG    Attempting to acquire lock 2687494150640 on C:\Users\alex\.chia\mainnet\config\config.yaml.lock
2024-10-07T16:50:07.338 daemon filelock                   : DEBUG    Lock 2687494150640 acquired on C:\Users\alex\.chia\mainnet\config\config.yaml.lock
2024-10-07T16:50:07.374 daemon filelock                   : DEBUG    Attempting to release lock 2687494150640 on C:\Users\alex\.chia\mainnet\config\config.yaml.lock
2024-10-07T16:50:07.376 daemon filelock                   : DEBUG    Lock 2687494150640 released on C:\Users\alex\.chia\mainnet\config\config.yaml.lock
2024-10-07T16:50:07.380 daemon chia.daemon.server         : INFO     Starting Daemon Server (localhost:55400)
2024-10-07T16:50:07.391 daemon filelock                   : DEBUG    Attempting to release lock 2687494145360 on C:\Users\alex\.chia\mainnet\run\daemon.lock
2024-10-07T16:50:07.392 daemon filelock                   : DEBUG    Lock 2687494145360 released on C:\Users\alex\.chia\mainnet\run\daemon.lock
2024-10-07T16:50:07.393 daemon chia.daemon.server         : DEBUG    State changed task received Cancel: CancelledError:

**Comment by BrandtH22** [comment]
Hey @zMotoR , as a heads up we can generally provide more timely and thorough support in our discord server (https://discord.gg/chia). 

As for the errors you are getting I have a few questions:
- is this a clean install of chia or are you upgrading from a previous version? (if from a previous version which one did you have previously?)
- which version of windows is on the two devices?
- which version of python is on the two devices?

**Comment by zMotoR** [comment]
It was an update. On the 1-st PC it was update 2.3.0 -> 2.4.3, on the 2-nd one I can't remember. I think the same. 

1-st PC: Windows 11, installed python 3.11 and python 3.4 at the same time in different paths
2-nd PC: Windows 10, can't find python at all

**Comment by BrandtH22** [comment]
@zMotoR , thank you for the information. One of our engineers has been assigned to review the issue and will provide more information as time permits 👍

**Comment by Riggie1000** [comment]
Same problem here. Everything worked. I closed Chia 2.4.1 Gigahorse and restartet the computer. After that, Chia is starting the wallet endlessly spinning.

**Comment by wjblanke** [comment]
This is now fixed in main
