### ISSUE TITLE
[BUG] Appears after starting full service “FileNotFoundError: can't find vdf_client binary”

### ISSUE THREAD

**Issue by zoharHao** [Chia-Network/chia-blockchain#1873]
**Describe the bug**
Traceback (most recent call last):
  File "/data/apps/chia-blockchain/venv/bin/chia_timelord_launcher", line 33, in <module>
    sys.exit(load_entry_point('chia-blockchain', 'console_scripts', 'chia_timelord_launcher')())
  File "/data/apps/chia-blockchain/chia/timelord/timelord_launcher.py", line 107, in main
    loop.run_until_complete(spawn_all_processes(config, net_config))
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/data/apps/chia-blockchain/chia/timelord/timelord_launcher.py", line 85, in spawn_all_processes
    await asyncio.gather(*awaitables)
  File "/data/apps/chia-blockchain/chia/timelord/timelord_launcher.py", line 45, in spawn_process
    path_to_vdf_client = find_vdf_client()
  File "/data/apps/chia-blockchain/chia/timelord/timelord_launcher.py", line 39, in find_vdf_client
    raise FileNotFoundError("can't find vdf_client binary")
FileNotFoundError: can't find vdf_client binary

**Comment by hoffmang9** [comment]
You generally do not want to run a timelord. If you do you need to `sh install-timelord.sh`. Usually you want `chia start farmer`.
