### ISSUE TITLE
[BUG]install-timelord.sh error 

### ISSUE THREAD

**Issue by chuwt** [Chia-Network/chia-blockchain#1874]
**Describe the bug**

when run sh install-timelord.sh , i got this error

```
Building wheels for collected packages: chiavdf
  Building wheel for chiavdf (PEP 517) ... error
  ERROR: Command errored out with exit status 1:
   command: /root/chia-blockchain/venv/bin/python /root/chia-blockchain/venv/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py build_wheel /tmp/tmp_kbr7lew
       cwd: /tmp/pip-install-tz4flrjw/chiavdf_238380aad6134dd7bc5d0b26ddf2639d
  Complete output (51 lines):
  running bdist_wheel
  running build
  running build_ext
  Traceback (most recent call last):
    File "/root/chia-blockchain/venv/bin/cmake", line 5, in <module>
      from cmake import cmake
  ModuleNotFoundError: No module named 'cmake'
  /tmp/pip-build-env-jqsm_2h2/overlay/lib/python3.7/site-packages/setuptools/dist.py:645: UserWarning: Usage of dash-separated 'index-url' will not be supported in future versions. Please use the underscore name 'index_url' instead
    % (opt, underscore_opt))
  Traceback (most recent call last):
    File "/root/chia-blockchain/venv/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py", line 280, in <module>
      main()
    File "/root/chia-blockchain/venv/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py", line 263, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/root/chia-blockchain/venv/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py", line 205, in build_wheel
      metadata_directory)
    File "/tmp/pip-build-env-jqsm_2h2/overlay/lib/python3.7/site-packages/setuptools/build_meta.py", line 222, in build_wheel
      wheel_directory, config_settings)
    File "/tmp/pip-build-env-jqsm_2h2/overlay/lib/python3.7/site-packages/setuptools/build_meta.py", line 207, in _build_with_temp_dir
      self.run_setup()
    File "/tmp/pip-build-env-jqsm_2h2/overlay/lib/python3.7/site-packages/setuptools/build_meta.py", line 150, in run_setup
      exec(compile(code, __file__, 'exec'), locals())
    File "setup.py", line 281, in <module>
      zip_safe=False,
    File "/tmp/pip-build-env-jqsm_2h2/overlay/lib/python3.7/site-packages/setuptools/__init__.py", line 153, in setup
      return distutils.core.setup(**attrs)
    File "/usr/lib/python3.7/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/usr/lib/python3.7/distutils/dist.py", line 966, in run_commands
      self.run_command(cmd)
    File "/usr/lib/python3.7/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/tmp/pip-build-env-jqsm_2h2/overlay/lib/python3.7/site-packages/wheel/bdist_wheel.py", line 299, in run
      self.run_command('build')
    File "/usr/lib/python3.7/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/lib/python3.7/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/usr/lib/python3.7/distutils/command/build.py", line 135, in run
      self.run_command(cmd_name)
    File "/usr/lib/python3.7/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/lib/python3.7/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "setup.py", line 96, in run
      out = subprocess.check_output(["cmake", "--version"])
    File "/usr/lib/python3.7/subprocess.py", line 411, in check_output
      **kwargs).stdout
    File "/usr/lib/python3.7/subprocess.py", line 512, in run
      output=stdout, stderr=stderr)
  subprocess.CalledProcessError: Command '['cmake', '--version']' returned non-zero exit status 1.
  ----------------------------------------
  ERROR: Failed building wheel for chiavdf
Failed to build chiavdf
ERROR: Could not build wheels for chiavdf which use PEP 517 and cannot be installed directly

```

and my cmake --version print is
```
cmake version 3.18.4

CMake suite maintained and supported by Kitware (kitware.com/cmake).
```
**Desktop (please complete the following information):**

- OS: Ubuntu

**Comment by hoffmang9** [comment]
It looks like you pip installed cmake and that's not going to work. You need cmake installed at the OS level if you want to build a timelord.

**Comment by chuwt** [comment]
It works after me uninstall cmake with pip and using OS cmake ! Thanks a lot!

**Comment by wearechiarex** [comment]
> 
> 
> It works after me uninstall cmake with pip and using OS cmake ! Thanks a lot!

[](https://github.com/Chia-Network/chia-blockchain/issues/6418)
I have same error. I did your suggestion. But I have same error. Could you explain details?
