### ISSUE TITLE
Starting GUI error "21" is showed without more information [BUG]

### ISSUE THREAD

**Issue by cmendozac** [Chia-Network/chia-blockchain#1881]
**Describe the bug**
This has been tested with CHIA v1.0.4 and near latests versions.

When starting GUI, a windows with the text "21" is showed with an "OK" button. This is happenig when the configured plot file paths for harvester are configured but doesn't exist nor aren't accesible.

**To Reproduce**
1) Configure a non existant path to a plot.
2) Start GUI.

**Expected behavior**
When starting gui, it will show the windows.
We can see that lines in debug log:
10:12:34.323 harvester harvester_server        : ERROR    Exception: [WinError 21] The device is not ready: 'D:\\plots' <class 'PermissionError'>, closing connection {'host': '127.0.0.1', 'port': 8447}. Traceback (most recent call last):
  File "chia\server\server.py", line 519, in api_call
  File "asyncio\tasks.py", line 442, in wait_for
  File "chia\server\server.py", line 517, in wrapped_coroutine
  File "chia\server\server.py", line 510, in wrapped_coroutine
  File "chia\harvester\harvester_api.py", line 42, in harvester_handshake
  File "chia\harvester\harvester.py", line 114, in refresh_plots
  File "chia\plotting\plot_tools.py", line 151, in load_plots
  File "chia\plotting\plot_tools.py", line 57, in get_plot_filenames
  File "pathlib.py", line 1166, in resolve
  File "pathlib.py", line 205, in resolve
PermissionError: [WinError 21] The device is not ready: 'D:\\plots'

**Desktop (please complete the following information):**

- OS: Windows server 2019 Standard with latest patch updates.
- CPU: VM using Hyper-V with intel i9-10900T on host server.

**Comment by hoffmang9** [comment]
PermissionError: [WinError 21] The device is not ready: 'D:\plots'

Either fix the permissions so that chia can read that directory or remove it from config.yaml in the plots directory.
