### ISSUE TITLE
Can't access Chia

### ISSUE THREAD

**Issue by apdredds** [Chia-Network/chia-blockchain#18861]
Hi

I have Chia 2.4.3 and the log in doesn't load. It stays on this screen attached. I did report the issue before but couldn't get any help on my side. I was asked from your team to provide a log file from ~/.chia/mainnet/log/debug.log. How do i do this?

Kind regards

Asiyah
![Chia screenshot](https://github.com/user-attachments/assets/02030921-0bb2-4d1c-b169-3ec2ae24eada)

**Comment by BrandtH22** [comment]
Hey @apdredds , as a heads up we can generally provide more timely and thorough support in our discord server (https://discord.gg/chia). 

The .chia directory is hidden and generally in your users folder.

MAC: open finder, click `COMMAND` + `SHIFT` + `.` (period) to show hidden files, look for the folder with your username and the .chia folder will be in there. Follow the rest of the file path to find the debug file.

WINDOWS / LINUX: open file explorer and with the view options enable hidden files. Then go to your user folder and look for the .chia folder. Follow the rest of the file path to find the debug file.

**Comment by apdredds** [comment]
Hi

Thank you for your help. The file is too large to attach. I've had to copy and paste part of it below, sorry.

2024-09-03T18:07:35.711 wallet chia.wallet.wallet_state_manager: WARNING  Could not find a parent coin with ID: e7e9bb060c302b79998512f89f772e1d9f494df18b878d27f6bda760d18dd0ea
2024-09-25T14:44:48.183 full_node chia.server.start_service: ERROR    fatal uncaught exception: RuntimeError: BlockStore does not support database schema v1
Traceback (most recent call last):
  File "chia\util\log_exceptions.py", line 20, in log_exceptions
  File "chia\server\start_service.py", line 328, in async_run
  File "asyncio\runners.py", line 44, in run
  File "asyncio\base_events.py", line 649, in run_until_complete
  File "chia\server\start_full_node.py", line 85, in async_main
  File "chia\server\start_service.py", line 202, in run
  File "contextlib.py", line 199, in __aenter__
  File "chia\server\start_service.py", line 219, in manage
  File "contextlib.py", line 619, in enter_async_context
  File "contextlib.py", line 199, in __aenter__
  File "chia\full_node\full_node.py", line 260, in manage
  File "chia\full_node\block_store.py", line 49, in create
RuntimeError: BlockStore does not support database schema v1

2024-09-25T14:44:48.734 harvester chia.plotting.util      : WARNING  Directory: F:\plots does not exist.
2024-09-25T14:44:48.735 harvester chia.plotting.util      : WARNING  Directory: E:\pooling-polit does not exist.
2024-09-25T14:44:48.738 harvester chia.plotting.util      : WARNING  Directory: F:\ does not exist.
2024-09-25T14:44:48.740 harvester chia.plotting.util      : WARNING  Directory: E:\ does not exist.
2024-09-25T14:44:48.741 harvester chia.plotting.util      : WARNING  Directory: G:\Plot does not exist.
2024-09-25T14:44:48.743 harvester chia.plotting.util      : WARNING  Directory: G:\ does not exist.
2024-09-25T14:44:48.745 harvester chia.plotting.util      : WARNING  Directory: I:\ does not exist.
2024-09-25T14:44:48.746 harvester chia.plotting.util      : WARNING  Directory: I:\plots does not exist.
2024-09-25T14:44:48.748 harvester chia.plotting.util      : WARNING  Directory: E:\Plot does not exist.
2024-09-25T14:44:48.749 harvester chia.plotting.util      : WARNING  Directory: F:\Plot does not exist.
2024-09-25T14:44:48.750 harvester chia.plotting.util      : WARNING  Directory: I:\Plot does not exist.
2024-09-25T14:44:49.437 farmer chia.pools.pool_config     : ERROR    Failed to update pool config entry for launcher_id 171733de08d9484041d80b7269cc77434b0c1c18c3d70dfc0ed1830d3aa5af8a
2024-09-25T14:46:48.922 harvester chia.plotting.util      : WARNING  Directory: F:\plots does not exist.
2024-09-25T14:46:48.924 harvester chia.plotting.util      : WARNING  Directory: E:\pooling-polit does not exist.
2024-09-25T14:46:48.927 harvester chia.plotting.util      : WARNING  Directory: F:\ does not exist.
2024-09-25T14:46:48.929 harvester chia.plotting.util      : WARNING  Directory: E:\ does not exist.
2024-09-25T14:46:48.931 harvester chia.plotting.util      : WARNING  Directory: G:\Plot does not exist.
2024-09-25T14:46:48.934 harvester chia.plotting.util      : WARNING  Directory: G:\ does not exist.
2024-09-25T14:46:48.937 harvester chia.plotting.util      : WARNING  Directory: I:\ does not exist.
2024-09-25T14:46:48.939 harvester chia.plotting.util      : WARNING  Directory: I:\plots does not exist.
2024-09-25T14:46:48.941 harvester chia.plotting.util      : WARNING  Directory: E:\Plot does not exist.
2024-09-25T14:46:48.943 harvester chia.plotting.util      : WARNING  Directory: F:\Plot does not exist.
2024-09-25T14:46:48.945 harvester chia.plotting.util      : WARNING  Directory: I:\Plot does not exist.
2024-09-25T14:48:49.278 harvester chia.plotting.util      : WARNING  Directory: F:\plots does not exist.
2024-09-25T14:48:49.279 harvester chia.plotting.util      : WARNING  Directory: E:\pooling-polit does not exist.
2024-09-25T14:48:49.280 harvester chia.plotting.util      : WARNING  Directory: F:\ does not exist.
2024-09-25T14:48:49.281 harvester chia.plotting.util      : WARNING  Directory: E:\ does not exist.
2024-09-25T14:48:49.281 harvester chia.plotting.util      : WARNING  Directory: G:\Plot does not exist.
2024-09-25T14:48:49.282 harvester chia.plotting.util      : WARNING  Directory: G:\ does not exist.
2024-09-25T14:48:49.283 harvester chia.plotting.util      : WARNING  Directory: I:\ does not exist.
2024-09-25T14:48:49.283 harvester chia.plotting.util      : WARNING  Directory: I:\plots does not exist.
2024-09-25T14:48:49.285 harvester chia.plotting.util      : WARNING  Directory: E:\Plot does not exist.
2024-09-25T14:48:49.287 harvester chia.plotting.util      : WARNING  Directory: F:\Plot does not exist.
2024-09-25T14:48:49.289 harvester chia.plotting.util      : WARNING  Directory: I:\Plot does not exist.
2024-09-30T14:04:05.532 full_node chia.server.start_service: ERROR    fatal uncaught exception: RuntimeError: BlockStore does not support database schema v1
Traceback (most recent call last):
  File "chia\util\log_exceptions.py", line 20, in log_exceptions
  File "chia\server\start_service.py", line 328, in async_run
  File "asyncio\runners.py", line 44, in run
  File "asyncio\base_events.py", line 649, in run_until_complete
  File "chia\server\start_full_node.py", line 85, in async_main
  File "chia\server\start_service.py", line 202, in run
  File "contextlib.py", line 199, in __aenter__
  File "chia\server\start_service.py", line 219, in manage
  File "contextlib.py", line 619, in enter_async_context
  File "contextlib.py", line 199, in __aenter__
  File "chia\full_node\full_node.py", line 260, in manage
  File "chia\full_node\block_store.py", line 49, in create
RuntimeError: BlockStore does not support database schema v1

2024-09-30T14:04:05.734 farmer chia.pools.pool_config     : ERROR    Failed to update pool config entry for launcher_id 171733de08d9484041d80b7269cc77434b0c1c18c3d70dfc0ed1830d3aa5af8a
2024-09-30T14:04:05.997 harvester chia.plotting.util      : WARNING  Directory: F:\plots does not exist.
2024-09-30T14:04:05.998 harvester chia.plotting.util      : WARNING  Directory: E:\pooling-polit does not exist.
2024-09-30T14:04:05.999 harvester chia.plotting.util      : WARNING  Directory: F:\ does not exist.
2024-09-30T14:04:06.000 harvester chia.plotting.util      : WARNING  Directory: E:\ does not exist.
2024-09-30T14:04:06.001 harvester chia.plotting.util      : WARNING  Directory: G:\Plot does not exist.
2024-09-30T14:04:06.001 harvester chia.plotting.util      : WARNING  Directory: G:\ does not exist.
2024-09-30T14:04:06.002 harvester chia.plotting.util      : WARNING  Directory: I:\ does not exist.
2024-09-30T14:04:06.002 harvester chia.plotting.util      : WARNING  Directory: I:\plots does not exist.
2024-09-30T14:04:06.003 harvester chia.plotting.util      : WARNING  Directory: E:\Plot does not exist.
2024-09-30T14:04:06.003 harvester chia.plotting.util      : WARNING  Directory: F:\Plot does not exist.
2024-09-30T14:04:06.004 harvester chia.plotting.util      : WARNING  Directory: I:\Plot does not exist.
2024-09-30T14:06:06.139 harvester chia.plotting.util      : WARNING  Directory: F:\plots does not exist.
2024-09-30T14:06:06.140 harvester chia.plotting.util      : WARNING  Directory: E:\pooling-polit does not exist.
2024-09-30T14:06:06.142 harvester chia.plotting.util      : WARNING  Directory: F:\ does not exist.
2024-09-30T14:06:06.142 harvester chia.plotting.util      : WARNING  Directory: E:\ does not exist.
2024-09-30T14:06:06.143 harvester chia.plotting.util      : WARNING  Directory: G:\Plot does not exist.
2024-09-30T14:06:06.144 harvester chia.plotting.util      : WARNING  Directory: G:\ does not exist.
2024-09-30T14:06:06.145 harvester chia.plotting.util      : WARNING  Directory: I:\ does not exist.
2024-09-30T14:06:06.146 harvester chia.plotting.util      : WARNING  Directory: I:\plots does not exist.
2024-09-30T14:06:06.146 harvester chia.plotting.util      : WARNING  Directory: E:\Plot does not exist.
2024-09-30T14:06:06.147 harvester chia.plotting.util      : WARNING  Directory: F:\Plot does not exist.
2024-09-30T14:06:06.148 harvester chia.plotting.util      : WARNING  Directory: I:\Plot does not exist.
2024-09-30T14:08:06.238 harvester chia.plotting.util      : WARNING  Directory: F:\plots does not exist.
2024-09-30T14:08:06.240 harvester chia.plotting.util      : WARNING  Directory: E:\pooling-polit does not exist.
2024-09-30T14:08:06.243 harvester chia.plotting.util      : WARNING  Directory: F:\ does not exist.
2024-09-30T14:08:06.245 harvester chia.plotting.util      : WARNING  Directory: E:\ does not exist.
2024-09-30T14:08:06.247 harvester chia.plotting.util      : WARNING  Directory: G:\Plot does not exist.
2024-09-30T14:08:06.249 harvester chia.plotting.util      : WARNING  Directory: G:\ does not exist.
2024-09-30T14:08:06.251 harvester chia.plotting.util      : WARNING  Directory: I:\ does not exist.
2024-09-30T14:08:06.253 harvester chia.plotting.util      : WARNING  Directory: I:\plots does not exist.
2024-09-30T14:08:06.255 harvester chia.plotting.util      : WARNING  Directory: E:\Plot does not exist.
2024-09-30T14:08:06.256 harvester chia.plotting.util      : WARNING  Directory: F:\Plot does not exist.
2024-09-30T14:08:06.258 harvester chia.plotting.util      : WARNING  Directory: I:\Plot does not exist.
2024-09-30T14:10:06.355 harvester chia.plotting.util      : WARNING  Directory: F:\plots does not exist.
2024-09-30T14:10:06.356 harvester chia.plotting.util      : WARNING  Directory: E:\pooling-polit does not exist.
2024-09-30T14:10:06.359 harvester chia.plotting.util      : WARNING  Directory: F:\ does not exist.
2024-09-30T14:10:06.361 harvester chia.plotting.util      : WARNING  Directory: E:\ does not exist.
2024-09-30T14:10:06.363 harvester chia.plotting.util      : WARNING  Directory: G:\Plot does not exist.
2024-09-30T14:10:06.364 harvester chia.plotting.util      : WARNING  Directory: G:\ does not exist.
2024-09-30T14:10:06.366 harvester chia.plotting.util      : WARNING  Directory: I:\ does not exist.
2024-09-30T14:10:06.368 harvester chia.plotting.util      : WARNING  Directory: I:\plots does not exist.
2024-09-30T14:10:06.370 harvester chia.plotting.util      : WARNING  Directory: E:\Plot does not exist.
2024-09-30T14:10:06.371 harvester chia.plotting.util      : WARNING  Directory: F:\Plot does not exist.
2024-09-30T14:10:06.373 harvester chia.plotting.util      : WARNING  Directory: I:\Plot does not exist.
2024-09-30T14:12:06.531 harvester chia.plotting.util      : WARNING  Directory: F:\plots does not exist.
2024-09-30T14:12:06.533 harvester chia.plotting.util      : WARNING  Directory: E:\pooling-polit does not exist.
2024-09-30T14:12:06.535 harvester chia.plotting.util      : WARNING  Directory: F:\ does not exist.
2024-09-30T14:12:06.538 harvester chia.plotting.util      : WARNING  Directory: E:\ does not exist.
2024-09-30T14:12:06.539 harvester chia.plotting.util      : WARNING  Directory: G:\Plot does not exist.
2024-09-30T14:12:06.541 harvester chia.plotting.util      : WARNING  Directory: G:\ does not exist.
2024-09-30T14:12:06.542 harvester chia.plotting.util      : WARNING  Directory: I:\ does not exist.
2024-09-30T14:12:06.543 harvester chia.plotting.util      : WARNING  Directory: I:\plots does not exist.
2024-09-30T14:12:06.543 harvester chia.plotting.util      : WARNING  Directory: E:\Plot does not exist.
2024-09-30T14:12:06.544 harvester chia.plotting.util      : WARNING  Directory: F:\Plot does not exist.
2024-09-30T14:12:06.544 harvester chia.plotting.util      : WARNING  Directory: I:\Plot does not exist.
2024-09-30T14:14:06.664 harvester chia.plotting.util      : WARNING  Directory: F:\plots does not exist.
2024-09-30T14:14:06.665 harvester chia.plotting.util      : WARNING  Directory: E:\pooling-polit does not exist.
2024-09-30T14:14:06.666 harvester chia.plotting.util      : WARNING  Directory: F:\ does not exist.
2024-09-30T14:14:06.667 harvester chia.plotting.util      : WARNING  Directory: E:\ does not exist.
2024-09-30T14:14:06.668 harvester chia.plotting.util      : WARNING  Directory: G:\Plot does not exist.
2024-09-30T14:14:06.668 harvester chia.plotting.util      : WARNING  Directory: G:\ does not exist.
2024-09-30T14:14:06.670 harvester chia.plotting.util      : WARNING  Directory: I:\ does not exist.
2024-09-30T14:14:06.671 harvester chia.plotting.util      : WARNING  Directory: I:\plots does not exist.
2024-09-30T14:14:06.672 harvester chia.plotting.util      : WARNING  Directory: E:\Plot does not exist.
2024-09-30T14:14:06.672 harvester chia.plotting.util      : WARNING  Directory: F:\Plot does not exist.
2024-09-30T14:14:06.673 harvester chia.plotting.util      : WARNING  Directory: I:\Plot does not exist.
2024-11-13T13:34:19.258 full_node chia.server.start_service: ERROR    fatal uncaught exception: RuntimeError: BlockStore does not support database schema v1
Traceback (most recent call last):
  File "chia\util\log_exceptions.py", line 20, in log_exceptions
  File "chia\server\start_service.py", line 328, in async_run
  File "asyncio\runners.py", line 44, in run
  File "asyncio\base_events.py", line 649, in run_until_complete
  File "chia\server\start_full_node.py", line 85, in async_main
  File "chia\server\start_service.py", line 202, in run
  File "contextlib.py", line 199, in __aenter__
  File "chia\server\start_service.py", line 219, in manage
  File "contextlib.py", line 619, in enter_async_context
  File "contextlib.py", line 199, in __aenter__
  File "chia\full_node\full_node.py", line 260, in manage
  File "chia\full_node\block_store.py", line 49, in create
RuntimeError: BlockStore does not support database schema v1

2024-11-13T13:34:20.370 farmer chia.pools.pool_config     : ERROR    Failed to update pool config entry for launcher_id 171733de08d9484041d80b7269cc77434b0c1c18c3d70dfc0ed1830d3aa5af8a
2024-11-13T13:34:20.563 harvester chia.plotting.util      : WARNING  Directory: F:\plots does not exist.
2024-11-13T13:34:20.564 harvester chia.plotting.util      : WARNING  Directory: E:\pooling-polit does not exist.
2024-11-13T13:34:20.565 harvester chia.plotting.util      : WARNING  Directory: F:\ does not exist.
2024-11-13T13:34:20.566 harvester chia.plotting.util      : WARNING  Directory: E:\ does not exist.
2024-11-13T13:34:20.566 harvester chia.plotting.util      : WARNING  Directory: G:\Plot does not exist.
2024-11-13T13:34:20.567 harvester chia.plotting.util      : WARNING  Directory: G:\ does not exist.
2024-11-13T13:34:20.568 harvester chia.plotting.util      : WARNING  Directory: I:\ does not exist.
2024-11-13T13:34:20.568 harvester chia.plotting.util      : WARNING  Directory: I:\plots does not exist.
2024-11-13T13:34:20.569 harvester chia.plotting.util      : WARNING  Directory: E:\Plot does not exist.
2024-11-13T13:34:20.569 harvester chia.plotting.util      : WARNING  Directory: F:\Plot does not exist.
2024-11-13T13:34:20.570 harvester chia.plotting.util      : WARNING  Directory: I:\Plot does not exist.
2024-11-13T13:36:21.538 harvester chia.plotting.util      : WARNING  Directory: F:\plots does not exist.
2024-11-13T13:36:21.539 harvester chia.plotting.util      : WARNING  Directory: E:\pooling-polit does not exist.
2024-11-13T13:36:21.540 harvester chia.plotting.util      : WARNING  Directory: F:\ does not exist.
2024-11-13T13:36:21.541 harvester chia.plotting.util      : WARNING  Directory: E:\ does not exist.
2024-11-13T13:36:21.541 harvester chia.plotting.util      : WARNING  Directory: G:\Plot does not exist.
2024-11-13T13:36:21.542 harvester chia.plotting.util      : WARNING  Directory: G:\ does not exist.
2024-11-13T13:36:21.543 harvester chia.plotting.util      : WARNING  Directory: I:\ does not exist.
2024-11-13T13:36:21.544 harvester chia.plotting.util      : WARNING  Directory: I:\plots does not exist.
2024-11-13T13:36:21.545 harvester chia.plotting.util      : WARNING  Directory: E:\Plot does not exist.
2024-11-13T13:36:21.546 harvester chia.plotting.util      : WARNING  Directory: F:\Plot does not exist.
2024-11-13T13:36:21.547 harvester chia.plotting.util      : WARNING  Directory: I:\Plot does not exist.
2024-11-13T13:38:22.492 harvester chia.plotting.util      : WARNING  Directory: F:\plots does not exist.
2024-11-13T13:38:22.494 harvester chia.plotting.util      : WARNING  Directory: E:\pooling-polit does not exist.
2024-11-13T13:38:22.496 harvester chia.plotting.util      : WARNING  Directory: F:\ does not exist.
2024-11-13T13:38:22.498 harvester chia.plotting.util      : WARNING  Directory: E:\ does not exist.
2024-11-13T13:38:22.500 harvester chia.plotting.util      : WARNING  Directory: G:\Plot does not exist.
2024-11-13T13:38:22.502 harvester chia.plotting.util      : WARNING  Directory: G:\ does not exist.
2024-11-13T13:38:22.504 harvester chia.plotting.util      : WARNING  Directory: I:\ does not exist.
2024-11-13T13:38:22.506 harvester chia.plotting.util      : WARNING  Directory: I:\plots does not exist.
2024-11-13T13:38:22.507 harvester chia.plotting.util      : WARNING  Directory: E:\Plot does not exist.
2024-11-13T13:38:22.509 harvester chia.plotting.util      : WARNING  Directory: F:\Plot does not exist.
2024-11-13T13:38:22.510 harvester chia.plotting.util      : WARNING  Directory: I:\Plot does not exist.
2024-11-13T13:40:23.324 harvester chia.plotting.util      : WARNING  Directory: F:\plots does not exist.
2024-11-13T13:40:23.325 harvester chia.plotting.util      : WARNING  Directory: E:\pooling-polit does not exist.
2024-11-13T13:40:23.326 harvester chia.plotting.util      : WARNING  Directory: F:\ does not exist.
2024-11-13T13:40:23.327 harvester chia.plotting.util      : WARNING  Directory: E:\ does not exist.
2024-11-13T13:40:23.328 harvester chia.plotting.util      : WARNING  Directory: G:\Plot does not exist.
2024-11-13T13:40:23.329 harvester chia.plotting.util      : WARNING  Directory: G:\ does not exist.
2024-11-13T13:40:23.330 harvester chia.plotting.util      : WARNING  Directory: I:\ does not exist.
2024-11-13T13:40:23.332 harvester chia.plotting.util      : WARNING  Directory: I:\plots does not exist.
2024-11-13T13:40:23.334 harvester chia.plotting.util      : WARNING  Directory: E:\Plot does not exist.
2024-11-13T13:40:23.336 harvester chia.plotting.util      : WARNING  Directory: F:\Plot does not exist.
2024-11-13T13:40:23.338 harvester chia.plotting.util      : WARNING  Directory: I:\Plot does not exist.
2024-11-13T13:42:24.171 harvester chia.plotting.util      : WARNING  Directory: F:\plots does not exist.
2024-11-13T13:42:24.172 harvester chia.plotting.util      : WARNING  Directory: E:\pooling-polit does not exist.
2024-11-13T13:42:24.174 harvester chia.plotting.util      : WARNING  Directory: F:\ does not exist.
2024-11-13T13:42:24.174 harvester chia.plotting.util      : WARNING  Directory: E:\ does not exist.
2024-11-13T13:42:24.175 harvester chia.plotting.util      : WARNING  Directory: G:\Plot does not exist.
2024-11-13T13:42:24.177 harvester chia.plotting.util      : WARNING  Directory: G:\ does not exist.
2024-11-13T13:42:24.177 harvester chia.plotting.util      : WARNING  Directory: I:\ does not exist.
2024-11-13T13:42:24.177 harvester chia.plotting.util      : WARNING  Directory: I:\plots does not exist.
2024-11-13T13:42:24.178 harvester chia.plotting.util      : WARNING  Directory: E:\Plot does not exist.
2024-11-13T13:42:24.179 harvester chia.plotting.util      : WARNING  Directory: F:\Plot does not exist.
2024-11-13T13:42:24.180 harvester chia.plotting.util      : WARNING  Directory: I:\Plot does not exist.
2024-11-13T13:44:25.132 harvester chia.plotting.util      : WARNING  Directory: F:\plots does not exist.
2024-11-13T13:44:25.133 harvester chia.plotting.util      : WARNING  Directory: E:\pooling-polit does not exist.
2024-11-13T13:44:25.135 harvester chia.plotting.util      : WARNING  Directory: F:\ does not exist.
2024-11-13T13:44:25.136 harvester chia.plotting.util      : WARNING  Directory: E:\ does not exist.
2024-11-13T13:44:25.136 harvester chia.plotting.util      : WARNING  Directory: G:\Plot does not exist.
2024-11-13T13:44:25.137 harvester chia.plotting.util      : WARNING  Directory: G:\ does not exist.
2024-11-13T13:44:25.138 harvester chia.plotting.util      : WARNING  Directory: I:\ does not exist.
2024-11-13T13:44:25.139 harvester chia.plotting.util      : WARNING  Directory: I:\plots does not exist.
2024-11-13T13:44:25.140 harvester chia.plotting.util      : WARNING  Directory: E:\Plot does not exist.
2024-11-13T13:44:25.140 harvester chia.plotting.util      : WARNING  Directory: F:\Plot does not exist.
2024-11-13T13:44:25.141 harvester chia.plotting.util      : WARNING  Directory: I:\Plot does not exist.
2024-11-13T13:46:26.063 harvester chia.plotting.util      : WARNING  Directory: F:\plots does not exist.
2024-11-13T13:46:26.064 harvester chia.plotting.util      : WARNING  Directory: E:\pooling-polit does not exist.
2024-11-13T13:46:26.066 harvester chia.plotting.util      : WARNING  Directory: F:\ does not exist.
2024-11-13T13:46:26.066 harvester chia.plotting.util      : WARNING  Directory: E:\ does not exist.
2024-11-13T13:46:26.067 harvester chia.plotting.util      : WARNING  Directory: G:\Plot does not exist.
2024-11-13T13:46:26.068 harvester chia.plotting.util      : WARNING  Directory: G:\ does not exist.
2024-11-13T13:46:26.069 harvester chia.plotting.util      : WARNING  Directory: I:\ does not exist.
2024-11-13T13:46:26.070 harvester chia.plotting.util      : WARNING  Directory: I:\plots does not exist.
2024-11-13T13:46:26.071 harvester chia.plotting.util      : WARNING  Directory: E:\Plot does not exist.
2024-11-13T13:46:26.072 harvester chia.plotting.util      : WARNING  Directory: F:\Plot does not exist.
2024-11-13T13:46:26.072 harvester chia.plotting.util      : WARNING  Directory: I:\Plot does not exist.
________________________________

**Comment by BrandtH22** [comment]
Thank you @apdredds , the logs show `RuntimeError: BlockStore does not support database schema v1` which is that second potential problem I mentioned. There are two methods to upgrade from the v1 to the v2 database based on how much space you have available on your drive. 

Let us know if you run into any issues or have questions while going through the below.

If you have ~500GB+ available I recommend using the CLI method but if you do not have that much space then I recommend the torrent option:

Steps for the CLI command:
1. Stop the chia client (this can be done while chia is running but stopping the client saves from any potential issues)
2. Run the command `chia db upgrade` (you do not need the input or output paths if these are still default)
- This process will take some time and requires additional space as the v1 db is compacted into the v2 db which leaves the v1 db intact
3. Verify the config file (`~\.chia\mainnet\config\config.yaml`) has the correct value under the full_node section for `database_path: db/blockchain_v2_CHALLENGE.sqlite` (should only need to change the v1 to v2)
4. After the above completes start the chia client
5. If all loads up properly (might take upwards of 30 minutes to load) then you can safely delete the v1 db found here (`~\.chia\mainnet\db\blockchain_v1_mainnet.sqlite`)


Steps for using the torrent: 
1. Download the torrent file from https://www.chia.net/downloads/#database-checkpoint
2. Use a torrent client to download the full db
3. Unpack/reassemble the torrent file that was downloaded (on windows I used 7zip, Mac and linux have built in tools that work for this)
4. Stop chia entirely then move the db to the correct folder (`~\.chia\mainnet\db\`) and update the name to "blockchain_v2_mainnet.sqlite" (removing the date information in the name)
5. Verify the config file (`~\.chia\mainnet\config\config.yaml`) has the correct value under the full_node section for `database_path: db/blockchain_v2_CHALLENGE.sqlite` (should only need to change the v1 to v2)
6. Launch chia and wait for a bit (the height to hash and peers files need to be built so this can take upwards of 30 minutes)

**Comment by apdredds** [comment]
I have downloaded the torrent files but when trying to unpack these, this pop up appears.

[cid:8a264d05-0e77-465e-a97c-0858d0602cf3]
________________________________

**Comment by BrandtH22** [comment]
Hey @apdredds , what torrent client did you use to download the files?

**Comment by apdredds** [comment]
I downloaded these two:

[cid:4d736b3d-e0f9-42d2-95a4-fd68ca7bb934]

Then right click on the below files and selected 7-zip GUI and then tried it with 7-zip file manager. Am I doing this incorrectly?

[cid:8fa2955d-9a03-4584-80ba-55e1c48e6c81]
________________________________

**Comment by BrandtH22** [comment]
@apdredds , you need to have a torrent client to download the files. Personally I have used qbittorrent in the past with success. The mainnet file that ends in .torrent needs to be opened with a torrent client (this is what downloads the actual files). It will take some time to download but then you will have a .tar.gz file that needs to be unpacked with 7-zip so just need to do the torrent download step then you can get to unpacking 👍

**Comment by apdredds** [comment]
Thank you. I am currently downloading them. Once complete I will let you know.

Kind regards

Asiyah
________________________________

**Comment by Taka-Tim** [comment]
I have a similar problem, after update to ver. 2.4.4:

![image](https://github.com/user-attachments/assets/19aaf500-10a2-4dcb-8b9c-f946d060510d)

2024-11-16T00:14:44.945 2.4.4 full_node chia.server.start_service: ERROR    fatal uncaught exception: DatabaseError: database disk image is malformed
Traceback (most recent call last):
  File "chia\util\log_exceptions.py", line 20, in log_exceptions
  File "chia\server\start_service.py", line 328, in async_run
  File "asyncio\runners.py", line 44, in run
  File "asyncio\base_events.py", line 649, in run_until_complete
  File "chia\server\start_full_node.py", line 85, in async_main
  File "chia\server\start_service.py", line 202, in run
  File "contextlib.py", line 199, in __aenter__
  File "chia\server\start_service.py", line 219, in manage
  File "contextlib.py", line 619, in enter_async_context
  File "contextlib.py", line 199, in __aenter__
  File "chia\full_node\full_node.py", line 270, in manage
  File "chia\consensus\blockchain.py", line 160, in create
  File "chia\consensus\blockchain.py", line 172, in _load_chain_from_store
  File "chia\full_node\block_height_map.py", line 133, in create
  File "chia\full_node\block_height_map.py", line 199, in _load_blocks_from
  File "aiosqlite\cursor.py", line 76, in fetchall
  File "aiosqlite\cursor.py", line 40, in _execute
  File "aiosqlite\core.py", line 132, in _execute
  File "aiosqlite\core.py", line 115, in run
sqlite3.DatabaseError: database disk image is malformed

**Comment by apdredds** [comment]
Hi

Hope all is well.

I think I have now completed the download (struggled with space on the PC but go there in the end). I opened the tar.gz file with WinZip. Not sure if I've un zipped it correctly. There is nothing in the zip folder.

[cid:b3432091-ec05-4cdb-9bbe-521e55e906b9]
Kind regards

Asiyah
________________________________

**Comment by apdredds** [comment]
Hi

Hope all is well.

I think I have now completed the download (struggled with space on the PC but go there in the end). I opened the tar.gz file with WinZip. Not sure if I've un zipped it correctly. There is nothing in the zip folder.

[cid:0245ccc1-f7c2-44c9-927a-762b888737fb]
Kind regards

Asiyah


________________________________

**Comment by BrandtH22** [comment]
Hey @apdredds , with winzip you need to unpack/unzip the file twice (once to unzip the .gz part and once to unpack the .tar part) and that should result in the folder that contains the files. 

If you are attempting to attach screenshots those are not coming through properly and need to be reattached.

**Comment by BrandtH22** [comment]
Hey @Taka-Tim , your logs indicate the database disk is malformed so you will need to download the snapshot db and sync from there:

Steps for using the torrent:

- Download the torrent file from https://www.chia.net/downloads/#database-checkpoint
- Use a torrent client to download the full db (I have used qbittorrent in the past)
- Unpack/reassemble the torrent file that was downloaded (on windows I used 7zip, Mac and linux have built in tools that work for this)
- Stop chia entirely then move the db to the correct folder (`~\.chia\mainnet\db\`) and update the name to "blockchain_v2_mainnet.sqlite" (removing the date information in the name)
- Verify the config file (`~\.chia\mainnet\config\config.yaml`) has the correct value under the full_node section for database_path: `db/blockchain_v2_CHALLENGE.sqlite` (should only need to change the v1 to v2)
- Launch chia and wait for a bit (the height to hash and peers files need to be built so this can take upwards of 30 minutes)

**Comment by Taka-Tim** [comment]
> Hey @BrandtH22 , Okay, thanks. If that's the case, I'll download the database again completely. But why did it "break" exactly at the moment of installing version 2.4.4 and worked on the previous release? "Technically" all the program folders and the DB itself are still on the hard drive and not deleted.

**Comment by BrandtH22** [comment]
Hey @Taka-Tim , it could be a number of reasons that lead to it breaking some including power outage, performing an upgrade without first shutting down chia, disk corruption, etc. Let us know if you run into any issues or have any questions while getting the snapshot DB setup

**Comment by Taka-Tim** [comment]
> Hey @BrandtH22 , I downloaded the specified file, but when I try to unpack it, I get an error that the specified file is not an archive
![image](https://github.com/user-attachments/assets/ed26d262-2e6f-4db0-b99c-0d652d051def)

**Comment by BrandtH22** [comment]
Hey @Taka-Tim , that does appear to be correct. When you use file explorer to navigate to that folder and double click on the tar.gz file does it show you the .tar file inside?

Also as a reminder we can generally provide more timely and thorough support in our discord server (https://discord.gg/chia)

**Comment by Taka-Tim** [comment]
After update to 2.4.5 all problems were eliminated. The program and DB are working.

**Comment by apdredds** [comment]
Hi Clyde

Hope all is well.

You helped me last year with this but I had a little trouble with storage. Can you help me again please? I have done the following so far, what is the next step? I can see below it says:

Stop chia entirely then move the db to the correct folder (~\.chia\mainnet\db\) and update the name to "blockchain_v2_mainnet.sqlite" (removing the date information in the name)

When you say db, do you mean the torrent file shown in screenshot attached?

Kind regards

Asiyah

________________________________
