### ISSUE TITLE
[BUG] v1.0.4 fedora32 can not run

### ISSUE THREAD

**Issue by dysuwen** [Chia-Network/chia-blockchain#1897]
fedora 32.0  64bit 
Linux localhost.localdomain 5.6.6-300.fc32.x86_64 #1 SMP Tue Apr 21 13:44:19 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

i try
rpm -ivh chia-blockchain-1.0.4-1.x86_64.rpm

./chia init
Traceback (most recent call last):
  File "chia/cmds/chia.py", line 8, in <module>
  File "PyInstaller/loader/pyimod03_importers.py", line 531, in exec_module
  File "chia/cmds/farm.py", line 11, in <module>
  File "PyInstaller/loader/pyimod03_importers.py", line 531, in exec_module
  File "chia/rpc/full_node_rpc_client.py", line 7, in <module>
  File "PyInstaller/loader/pyimod03_importers.py", line 531, in exec_module
  File "chia/types/full_block.py", line 11, in <module>
  File "PyInstaller/loader/pyimod03_importers.py", line 531, in exec_module
  File "chia/types/blockchain_format/reward_chain_block.py", line 8, in <module>
  File "PyInstaller/loader/pyimod03_importers.py", line 531, in exec_module
  File "chia/types/blockchain_format/vdf.py", line 7, in <module>
ImportError: /usr/lib/chia-blockchain/resources/app.asar.unpacked/daemon/chiavdf.cpython-38-x86_64-linux-gnu.so: ELF load command address/offset not properly aligned

**Comment by hoffmang9** [comment]
Thanks for this report. We'll dig into it.

**Comment by hoffmang9** [comment]
Can we confirm if the current rpm installer still has this issue?

**Comment by loppefaaret** [comment]
Installing fedora 32 workstation, updating, and installling `chia-blockchain-1.2.3-1.x86_64.rpm` works.
Closing issue - if you are still facing problems, please reopen the issue
