### ISSUE TITLE
centos error when running npm run electron

### ISSUE THREAD

**Issue by imwildstone** [Chia-Network/chia-blockchain#1907]
I get the error when running npm run electron:
![1](https://user-images.githubusercontent.com/20588344/114792226-87a2bf80-9dba-11eb-9c9f-8af6c5b11e16.png)

I have viewed the log,it is this:
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! chia-blockchain@ electron: `electron .`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the chia-blockchain@ electron script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-04-14T23_05_47_624Z-debug.log
(venv) [root@localhost chia-blockchain-gui]# ^C
(venv) [root@localhost chia-blockchain-gui]# cat /root/.npm/_logs/2021-04-14T23_05_47_624Z-debug.log
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'electron' ]
2 info using npm@6.14.12
3 info using node@v10.24.1
4 verbose run-script [ 'preelectron', 'electron', 'postelectron' ]
5 info lifecycle chia-blockchain@~preelectron: chia-blockchain@
6 info lifecycle chia-blockchain@~electron: chia-blockchain@
7 verbose lifecycle chia-blockchain@~electron: unsafe-perm in lifecycle true
8 verbose lifecycle chia-blockchain@~electron: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/root/chia-blockchain/chia-blockchain-gui/node_modules/.bin:/root/chia-blockchain/venv/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/bin:/sbin:/root/bin
9 verbose lifecycle chia-blockchain@~electron: CWD: /root/chia-blockchain/chia-blockchain-gui
10 silly lifecycle chia-blockchain@~electron: Args: [ '-c', 'electron .' ]
11 silly lifecycle chia-blockchain@~electron: Returned: code: 1  signal: null
12 info lifecycle chia-blockchain@~electron: Failed to exec electron script
13 verbose stack Error: chia-blockchain@ electron: `electron .`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:198:13)
13 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:198:13)
13 verbose stack     at maybeClose (internal/child_process.js:982:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
14 verbose pkgid chia-blockchain@
15 verbose cwd /root/chia-blockchain/chia-blockchain-gui
16 verbose Linux 3.10.0-1160.el7.x86_64
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "run" "electron"
18 verbose node v10.24.1
19 verbose npm  v6.14.12
20 error code ELIFECYCLE
21 error errno 1
22 error chia-blockchain@ electron: `electron .`
22 error Exit status 1
23 error Failed at the chia-blockchain@ electron script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by seeden** [comment]
You are using the old version of the node. Try to use version 12. I will change it in the package.json as well.
