### ISSUE TITLE
[BUG] Full Node not synced

### ISSUE THREAD

**Issue by daijmon** [Chia-Network/chia-blockchain#1923]
Since yesterday, Node is not able to sync, problem was present on 1.4 and is still present after upgrading to 1.5
Windows 10 Pro

07:28:49.502 full_node full_node_server        : ERROR    Exception , exception Stack: Traceback (most recent call last):
  File "chia\server\server.py", line 353, in start_client
  File "aiohttp\client.py", line 763, in _ws_connect
  File "aiohttp\client.py", line 521, in _request
  File "aiohttp\connector.py", line 535, in connect
  File "aiohttp\connector.py", line 892, in _create_connection
  File "aiohttp\connector.py", line 1032, in _create_direct_connection
  File "aiohttp\connector.py", line 969, in _wrap_create_connection
  File "asyncio\base_events.py", line 949, in create_connection
  File "asyncio\selector_events.py", line 473, in sock_connect
concurrent.futures._base.CancelledError

07:28:59.499 full_node chia.full_node.full_node: WARNING  Syncing failed, CancelledError
07:30:08.566 wallet chia.wallet.wallet_state_manager: WARNING  Starting in db path: C:\Users\xxx

07:30:13.466 wallet wallet_server              : ERROR    Exception:  <class 'concurrent.futures._base.CancelledError'>, closing connection {'host': 'x', 'port': 8444}. Traceback (most recent call last):
  File "chia\server\server.py", line 519, in api_call
  File "asyncio\tasks.py", line 435, in wait_for
concurrent.futures._base.CancelledError

07:38:56.798 wallet chia.wallet.wallet_state_manager: WARNING  Starting in db path: C:\Users\xxx
07:39:01.564 wallet wallet_server              : ERROR    Exception:  <class 'concurrent.futures._base.CancelledError'>, closing connection {'host': 'xxx', 'port': 8444}. Traceback (most recent call last):
  File "chia\server\server.py", line 519, in api_call
  File "asyncio\tasks.py", line 435, in wait_for
concurrent.futures._base.CancelledError

07:39:11.148 wallet chia.wallet.wallet_state_manager: WARNING  Starting in db path: C:\Users\xxx
07:48:10.322 full_node chia.full_node.full_node: ERROR    Error with syncing: <class 'RuntimeError'>Traceback (most recent call last):
  File "chia\full_node\full_node.py", line 604, in _sync
RuntimeError: Weight proof did not arrive in time from peer: xxx

**Comment by tangz777** [comment]
im also

**Comment by MoeGen** [comment]
same here

**Comment by kuloneko** [comment]
got the same

**Comment by Teledyol** [comment]
Same here The SSD gets totally used up even though the macOS window says that I have over 800 GB available.

The .tmp folder is showing way too many extra files

**Comment by Teledyol** [comment]
That was a waste of time. Looks like I have to stop plotting

**Comment by Teledyol** [comment]
![Screen Shot 2021-04-16 at 6 17 14 PM](https://user-images.githubusercontent.com/3718370/115097623-28d76600-9ee0-11eb-99c3-85218e69c025.png)

The SSD is filled with "other volumes" now, do I have to manually clean up these spurious containers? where are they. My SSD is showing that I should have 1.75 TB available, but this data is not properly erasing

**Comment by mariano54** [comment]
Please port forward 8444 in your router.
And follow the instructions here: https://github.com/Chia-Network/chia-blockchain/wiki/FAQ#why-does-my-node-have-no-connections

**Comment by Mainned** [comment]
8444 forwarded, chia connect to other full nodes but few minutes after that it lose the connections and synced nothing, tried a full reinstall, including dbs without any improvement:. 8444 is forwarded, as well as firewall policies applied, this is the only node in the network...

2021-05-16T02:48:18.615 full_node chia.full_node.full_node: ERROR    Error with syncing: <class 'RuntimeError'>Traceback (most recent call last):
  File "chia\full_node\full_node.py", line 628, in _sync
RuntimeError: Weight proof did not arrive in time from peer
