### ISSUE TITLE
[BUG] Can not create plot on AWS Linux 2

### ISSUE THREAD

**Issue by phanngt** [Chia-Network/chia-blockchain#1927]
**Describe the bug**
Unable to create plots

**To Reproduce**
1. Run command: `chia plots create -k 32 -n 1 -t /var/lib/dump/ -d /var/lib/dump/plot/`

**Screenshots**
```
12:12:59.944  chia.plotting.create_plots       : INFO     Creating 1 plots of size 32, pool public key:  a55dac3d48015e9fe839e595f3a306e693680cdbee79862a2591a4aa81e5c1d311926df38be7756989f3744719edb85e farmer public key: b85e7befcbf166ce0856100990ec045bc2d9bc28a0f62d9506e56b61057847bea707e9d01bfa28af9fc392e59b9d2e64
12:12:59.959  chia.plotting.create_plots       : INFO     Memo: a55dac3d48015e9fe839e595f3a306e693680cdbee79862a2591a4aa81e5c1d311926df38be7756989f3744719edb85eb85e7befcbf166ce0856100990ec045bc2d9bc28a0f62d9506e56b61057847bea707e9d01bfa28af9fc392e59b9d2e646cce6b141b372f90ca142f84a76d2ec0a7d2d76b18276b4a7020bd8b60a9965a
12:12:59.959  chia.plotting.create_plots       : INFO     Adding directory /var/lib/dump/plot to harvester for farming
12:13:00.027  chia.plotting.create_plots       : INFO     Starting plot 1/1

Starting plotting progress into temporary dirs: /var/lib/dump and /var/lib/dump
ID: afd21fcb3a334e1a82d74aef4730135e6c5f43a8942c5d5e4fc29aa3d88adb81
Plot size is: 32
Buffer size is: 4608MiB
Using 128 buckets
Using 2 threads of stripe size 65536

Starting phase 1/4: Forward Propagation into tmp files... Thu Apr 15 12:13:00 2021
Computing table 1
F1 complete, time: 296.045 seconds. CPU (169.73%) Thu Apr 15 12:17:56 2021
Computing table 2
Caught plotting error: std::bad_alloc
Traceback (most recent call last):
  File "/home/ec2-user/Python-3.8.3/chia-blockchain/venv/bin/chia", line 33, in <module>
    sys.exit(load_entry_point('chia-blockchain', 'console_scripts', 'chia')())
  File "/home/ec2-user/Python-3.8.3/chia-blockchain/chia/cmds/chia.py", line 76, in main
    cli()  # pylint: disable=no-value-for-parameter
  File "/home/ec2-user/Python-3.8.3/chia-blockchain/venv/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/ec2-user/Python-3.8.3/chia-blockchain/venv/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/ec2-user/Python-3.8.3/chia-blockchain/venv/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/ec2-user/Python-3.8.3/chia-blockchain/venv/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/ec2-user/Python-3.8.3/chia-blockchain/venv/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/ec2-user/Python-3.8.3/chia-blockchain/venv/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/ec2-user/Python-3.8.3/chia-blockchain/venv/lib/python3.8/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/ec2-user/Python-3.8.3/chia-blockchain/chia/cmds/plots.py", line 134, in create_cmd
    create_plots(Params(), ctx.obj["root_path"])
  File "/home/ec2-user/Python-3.8.3/chia-blockchain/chia/plotting/create_plots.py", line 164, in create_plots
    plotter.create_plot_disk(
RuntimeError: std::exception
```

**Desktop:**

- OS: [Amazon Linux]

**Comment by hoffmang9** [comment]
How much RAM does your EC2 instance have? You are probably running out of RAM.

**Comment by phanngt** [comment]
Here is my result: 
```
free -h
             total       used       free     shared    buffers     cached
Mem:          3.8G       1.7G       2.1G       160K       230M       224M
-/+ buffers/cache:       1.3G       2.5G
Swap:         4.0G         0B       4.0G
```

**Comment by phanngt** [comment]
377 free space

**Comment by hoffmang9** [comment]
You need more RAM in the instance. You can try no bitfield.
