### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Mati32167** [Chia-Network/chia-blockchain#1955]
My system is Windows10, I have this in logs since yesterday. 
I'm not shure that my plots are farming now...
My status is "synced" but i don't get any reward. 

09:41:40.955 full_node full_node_server        : ERROR    Exception:  <class 'concurrent.futures._base.CancelledError'>, closing connection {'host': 'xxx', 'port': 8449}. Traceback (most recent call last):
  File "chia\server\server.py", line 519, in api_call
  File "asyncio\tasks.py", line 435, in wait_for
concurrent.futures._base.CancelledError

09:41:42.561 wallet wallet_server              : ERROR    Exception:  <class 'concurrent.futures._base.CancelledError'>, closing connection {'host': 'xxx', 'port': 8444}. Traceback (most recent call last):
  File "chia\server\server.py", line 519, in api_call
  File "asyncio\tasks.py", line 435, in wait_for
concurrent.futures._base.CancelledError

**Comment by AmmarKothari** [comment]
I think i am seeing the same crash on ubuntu 20 with version 1.05.

```
10:09:26.305 wallet wallet_server              : ERROR    Exception , exception Stack: Traceback (most recent call last):
  File "/home/ammar/Documents/OtherRepos/chia-blockchain/chia/server/server.py", line 353, in start_client
    url, autoclose=True, autoping=True, heartbeat=60, ssl=ssl_context, max_msg_size=50 * 1024 * 1024
  File "/home/ammar/Documents/OtherRepos/chia-blockchain/venv/lib/python3.7/site-packages/aiohttp/client.py", line 763, in _ws_connect
    proxy_headers=proxy_headers,
  File "/home/ammar/Documents/OtherRepos/chia-blockchain/venv/lib/python3.7/site-packages/aiohttp/client.py", line 521, in _request
    req, traces=traces, timeout=real_timeout
  File "/home/ammar/Documents/OtherRepos/chia-blockchain/venv/lib/python3.7/site-packages/aiohttp/connector.py", line 535, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/home/ammar/Documents/OtherRepos/chia-blockchain/venv/lib/python3.7/site-packages/aiohttp/connector.py", line 892, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "/home/ammar/Documents/OtherRepos/chia-blockchain/venv/lib/python3.7/site-packages/aiohttp/connector.py", line 1032, in
_create_direct_connection
    client_error=client_error,
  File "/home/ammar/Documents/OtherRepos/chia-blockchain/venv/lib/python3.7/site-packages/aiohttp/connector.py", line 969, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore  # noqa
  File "/usr/lib/python3.7/asyncio/base_events.py", line 989, in create_connection
    ssl_handshake_timeout=ssl_handshake_timeout)
  File "/usr/lib/python3.7/asyncio/base_events.py", line 1017, in _create_connection_transport
    await waiter
concurrent.futures._base.CancelledError
```

Looks like this is being thrown for the connection to the wallet.

I tried this several times and looks to happen every time.
