### ISSUE TITLE
(БУГ) НЕТ,

### ISSUE THREAD

**Issue by Andreevi4** [Chia-Network/chia-blockchain#2058]
1%

23:06:19.409  chia.plotting.create_plots       : [32mINFO    [0m Creating 1 plots of size 32, pool public key:  ac443e640bd298dd7ff323f9574554dddfb02a9772bd8cf2c40658b67c523ec1cc6bd700f8446bda43b75dff2a8c2e10 farmer public key: 973c6ec919226ebffd51a89b6acc8a8d96fbbb34abf58af405f11394b6087aaaf9252056aa8b8a0ffb8f86693a0d0e87[0m
23:06:19.499  chia.plotting.create_plots       : [32mINFO    [0m Memo: ac443e640bd298dd7ff323f9574554dddfb02a9772bd8cf2c40658b67c523ec1cc6bd700f8446bda43b75dff2a8c2e10973c6ec919226ebffd51a89b6acc8a8d96fbbb34abf58af405f11394b6087aaaf9252056aa8b8a0ffb8f86693a0d0e872a954985ebe1c3b979634e6c1c54b36702c33cefce0062b68d0fe85950c060c4[0m
23:06:19.500  chia.plotting.create_plots       : [32mINFO    [0m Starting plot 1/1[0m

Starting plotting progress into temporary dirs: C:\ and C:\
ID: 232191a96d3b8636528257bacda8e44fd5a8d131765c7ae1066211bc1aec99b3
Plot size is: 32
Buffer size is: 3390MiB
Using 128 buckets
Using 2 threads of stripe size 65536
Caught plotting error: Could not open C:\plot-k32-2021-04-18-23-06-232191a96d3b8636528257bacda8e44fd5a8d131765c7ae1066211bc1aec99b3.plot.sort.tmp: Permission denied.
[2548] Failed to execute script chia
Traceback (most recent call last):
  File "chia\cmds\chia.py", line 80, in <module>
  File "chia\cmds\chia.py", line 76, in main
  File "click\core.py", line 829, in __call__
  File "click\core.py", line 782, in main
  File "click\core.py", line 1259, in invoke
  File "click\core.py", line 1259, in invoke
  File "click\core.py", line 1066, in invoke
  File "click\core.py", line 610, in invoke
  File "click\decorators.py", line 21, in new_func
  File "chia\cmds\plots.py", line 134, in create_cmd
  File "chia\plotting\create_plots.py", line 176, in create_plots
RuntimeError: Unknown exception

**Comment by Solitude12345** [comment]
You do not have write permission in the root directory of the c drive
