### ISSUE TITLE
[BUG] Raise manylinux to at least 2014 to support other architectures than x86?

### ISSUE THREAD

**Issue by viniciusferrao** [Chia-Network/chia-blockchain#2064]
**Describe the bug**
The software seems to be tiered to manylinux=2010, which only supports x86 architectures and it's variants.

**To Reproduce**

1. Run sh install.sh on any non x86 platform.
2. Wait for it...

    Caused by: Error ensuring manylinux2010 compliance
    Caused by: Your library is not manylinux compliant because it has unsupported architecture: ppc64le

**Expected behavior**
Software would be able to run on non x86 platforms

**Desktop (please complete the following information):**

- OS: Linux
- OS Version/Flavor: Red Hat Enterprise Linux 8.3
- CPU: IBM POWER9 2.2

**Additional context**
Full error:

```
Building wheels for collected packages: chiavdf, clvm-rs
  Building wheel for chiavdf (PEP 517) ... error
  ERROR: Command errored out with exit status 1:
   command: /root/chia-blockchain/venv/bin/python3.8 /root/chia-blockchain/venv/lib64/python3.8/site-packages/pip/_vendor/pep517/_in_process.py build_wheel /tmp/tmpp7m2tko7
       cwd: /tmp/pip-install-l3j46y5r/chiavdf_e0476c7903f24084bea03dac229deac8
  Complete output (87 lines):
  running bdist_wheel
  running build
  running build_ext
  -- The C compiler identification is GNU 8.3.1
  -- The CXX compiler identification is GNU 8.3.1
  -- Detecting C compiler ABI info
  -- Detecting C compiler ABI info - done
  -- Check for working C compiler: /usr/bin/cc - skipped
  -- Detecting C compile features
  -- Detecting C compile features - done
  -- Detecting CXX compiler ABI info
  -- Detecting CXX compiler ABI info - done
  -- Check for working CXX compiler: /usr/bin/c++ - skipped
  -- Detecting CXX compile features
  -- Detecting CXX compile features - done
  GMP_INCLUDES=/usr/include
  -- Found GMP: /usr/include (Required is at least version "5.1.0")
  GMP_INCLUDES=/usr/include
  -- Found GMPXX: /usr/lib64/libgmpxx.so
  -- pybind11 v2.6.2
  -- Found PythonInterp: /root/chia-blockchain/venv/bin/python3.8 (found version "3.8.3")
  -- Found PythonLibs: /usr/lib64/libpython3.8.so
  -- Performing Test HAS_FLTO
  -- Performing Test HAS_FLTO - Success
  -- Configuring done
  -- Generating done
  -- Build files have been written to: /tmp/pip-install-l3j46y5r/chiavdf_e0476c7903f24084bea03dac229deac8
  Scanning dependencies of target verifier_test
  [ 33%] Building CXX object CMakeFiles/verifier_test.dir/verifier_test.cpp.o
  [ 33%] Building C object CMakeFiles/verifier_test.dir/refcode/lzcnt.c.o
  Scanning dependencies of target chiavdf
  [ 50%] Building CXX object CMakeFiles/chiavdf.dir/python_bindings/fastvdf.cpp.o
  [ 66%] Building C object CMakeFiles/chiavdf.dir/refcode/lzcnt.c.o
  [ 83%] Linking CXX executable verifier_test
  CMakeFiles/verifier_test.dir/verifier_test.cpp.o: In function `Reducer::run()':
  verifier_test.cpp:(.text._ZN7Reducer3runEv[_ZN7Reducer3runEv]+0x14c): undefined reference to `lzcnt64_hard'
  verifier_test.cpp:(.text._ZN7Reducer3runEv[_ZN7Reducer3runEv]+0x228): undefined reference to `lzcnt64_hard'
  verifier_test.cpp:(.text._ZN7Reducer3runEv[_ZN7Reducer3runEv]+0x304): undefined reference to `lzcnt64_hard'
  collect2: error: ld returned 1 exit status
  gmake[2]: *** [CMakeFiles/verifier_test.dir/build.make:120: verifier_test] Error 1
  gmake[1]: *** [CMakeFiles/Makefile2:144: CMakeFiles/verifier_test.dir/all] Error 2
  gmake[1]: *** Waiting for unfinished jobs....
  [100%] Linking CXX shared module build/lib.linux-ppc64le-3.8/chiavdf.cpython-38-ppc64le-linux-gnu.so
  [100%] Built target chiavdf
  gmake: *** [Makefile:103: all] Error 2
  Traceback (most recent call last):
    File "/root/chia-blockchain/venv/lib64/python3.8/site-packages/pip/_vendor/pep517/_in_process.py", line 280, in <module>
      main()
    File "/root/chia-blockchain/venv/lib64/python3.8/site-packages/pip/_vendor/pep517/_in_process.py", line 263, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/root/chia-blockchain/venv/lib64/python3.8/site-packages/pip/_vendor/pep517/_in_process.py", line 204, in build_wheel
      return _build_backend().build_wheel(wheel_directory, config_settings,
    File "/tmp/pip-build-env-stycier8/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 221, in build_wheel
      return self._build_with_temp_dir(['bdist_wheel'], '.whl',
    File "/tmp/pip-build-env-stycier8/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 207, in _build_with_temp_dir
      self.run_setup()
    File "/tmp/pip-build-env-stycier8/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 150, in run_setup
      exec(compile(code, __file__, 'exec'), locals())
    File "setup.py", line 266, in <module>
      setup(
    File "/tmp/pip-build-env-stycier8/overlay/lib/python3.8/site-packages/setuptools/__init__.py", line 153, in setup
      return distutils.core.setup(**attrs)
    File "/usr/lib64/python3.8/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/usr/lib64/python3.8/distutils/dist.py", line 966, in run_commands
      self.run_command(cmd)
    File "/usr/lib64/python3.8/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/tmp/pip-build-env-stycier8/overlay/lib/python3.8/site-packages/wheel/bdist_wheel.py", line 299, in run
      self.run_command('build')
    File "/usr/lib64/python3.8/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/lib64/python3.8/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/usr/lib64/python3.8/distutils/command/build.py", line 135, in run
      self.run_command(cmd_name)
    File "/usr/lib64/python3.8/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/lib64/python3.8/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "setup.py", line 112, in run
      self.build_extension(ext)
    File "setup.py", line 140, in build_extension
      subprocess.check_call(["cmake", "--build", "."] + build_args)
    File "/usr/lib64/python3.8/subprocess.py", line 364, in check_call
      raise CalledProcessError(retcode, cmd)
  subprocess.CalledProcessError: Command '['cmake', '--build', '.', '--config', 'Release', '--', '-j', '6']' returned non-zero exit status 2.
  ----------------------------------------
  ERROR: Failed building wheel for chiavdf
  Building wheel for clvm-rs (PEP 517) ... error
  ERROR: Command errored out with exit status 1:
   command: /root/chia-blockchain/venv/bin/python3.8 /root/chia-blockchain/venv/lib64/python3.8/site-packages/pip/_vendor/pep517/_in_process.py build_wheel /tmp/tmpaf7or8gj
       cwd: /tmp/pip-install-l3j46y5r/clvm-rs_e5ea45236c7d4ec9b49f591e1f4a4515
  Complete output (61 lines):
  Running `maturin pep517 build-wheel -i /root/chia-blockchain/venv/bin/python3.8 --bindings=pyo3 --manylinux=2010`
     Compiling autocfg v1.0.1
     Compiling proc-macro2 v1.0.26
     Compiling unicode-xid v0.2.1
     Compiling syn v1.0.69
     Compiling proc-macro-hack v0.5.19
     Compiling radium v0.6.2
     Compiling libc v0.2.93
     Compiling cc v1.0.67
     Compiling cfg-if v1.0.0
     Compiling wyz v0.2.0
     Compiling tap v1.0.1
     Compiling funty v1.1.0
     Compiling pkg-config v0.3.19
     Compiling rand_core v0.6.2
     Compiling subtle v2.4.0
     Compiling scopeguard v1.1.0
     Compiling bitflags v1.2.1
     Compiling unindent v0.1.7
     Compiling byteorder v1.4.3
     Compiling inventory v0.1.10
     Compiling smallvec v1.6.1
     Compiling openssl v0.10.33
     Compiling pyo3 v0.13.2
     Compiling foreign-types-shared v0.1.1
     Compiling once_cell v1.7.2
     Compiling lazy_static v1.4.0
     Compiling hex v0.4.3
     Compiling instant v0.1.9
     Compiling lock_api v0.4.3
     Compiling foreign-types v0.3.2
     Compiling num-traits v0.2.14
     Compiling num-integer v0.1.44
     Compiling num-bigint v0.3.2
     Compiling openssl-src v111.15.0+1.1.1k
     Compiling quote v1.0.9
     Compiling bitvec v0.20.2
     Compiling openssl-sys v0.9.61
     Compiling parking_lot_core v0.8.3
     Compiling parking_lot v0.11.1
     Compiling paste-impl v0.1.18
     Compiling paste v0.1.18
     Compiling pyo3-macros-backend v0.13.2
     Compiling ff v0.9.0
     Compiling group v0.9.0
     Compiling pairing v0.19.0
     Compiling ctor v0.1.20
     Compiling ghost v0.1.2
     Compiling inventory-impl v0.1.10
     Compiling indoc-impl v0.3.6
     Compiling pyo3-macros v0.13.2
     Compiling indoc v0.3.6
     Compiling bls12_381 v0.4.0
     Compiling clvm_rs v0.1.6 (/tmp/pip-install-l3j46y5r/clvm-rs_e5ea45236c7d4ec9b49f591e1f4a4515)
      Finished release [optimized] target(s) in 2m 54s
  💥 maturin failed
    Caused by: Error ensuring manylinux2010 compliance
    Caused by: Your library is not manylinux compliant because it has unsupported architecture: ppc64le
  🔗 Found pyo3 bindings
  🐍 Found CPython 3.8 at /root/chia-blockchain/venv/bin/python3.8
  Error: command ['maturin', 'pep517', 'build-wheel', '-i', '/root/chia-blockchain/venv/bin/python3.8', '--bindings=pyo3', '--manylinux=2010'] returned non-zero exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for clvm-rs
Failed to build chiavdf clvm-rs
ERROR: Could not build wheels for chiavdf, clvm-rs which use PEP 517 and cannot be installed directly
```

**Comment by hoffmang9** [comment]
We are using manylinux2014 to support ARM64 - this will have to get on the todo list to support in that build chain.

**Comment by hoffmang9** [comment]
Supporting ppc64le is pretty low priority. Closing but would welcome community PRs on the various repositories.
