### ISSUE TITLE
ValueError: Relic library error during chia init on windows

### ISSUE THREAD

**Issue by dkackman** [Chia-Network/chia-blockchain#208]
this is what `chia init` returned after a windows install. The farmer is logging similar errors (see attachment)
[debug.log](https://github.com/Chia-Network/chia-blockchain/files/4566200/debug.log)

````
migrating to C:\Users\dkack\.chia\beta-1.0b4

C:\Users\dkack\.chia\beta-1.0b3 found
Copying files from C:\Users\dkack\.chia\beta-1.0b3 to C:\Users\dkack\.chia\beta-1.0b4

C:\Users\dkack\.chia\beta-1.0b4\config\config.yaml
C:\Users\dkack\.chia\beta-1.0b4\config\plots.yaml
C:\Users\dkack\.chia\beta-1.0b4\config\keys.yaml
C:\Users\dkack\.chia\beta-1.0b3\config\trusted.crt not found, skipping
C:\Users\dkack\.chia\beta-1.0b3\config\trusted.key not found, skipping

migrating plots.yaml
rewriting /mnt/d/plots/plot-0-31-1197c77f208ab4610b153269b22462bbda758e8f2a20e007c676d029eb7b7674.dat
 as plot-0-31-1197c77f208ab4610b153269b22462bbda758e8f2a20e007c676d029eb7b7674.dat
rewriting /mnt/d/plots/plot-1-31-2a8a10ec680d9595b6e0e3ef50c7ae8582b46a22b0a120c39dcd7447dad3832f.dat
 as plot-1-31-2a8a10ec680d9595b6e0e3ef50c7ae8582b46a22b0a120c39dcd7447dad3832f.dat
rewriting /mnt/d/plots/plot-2-31-125f6af87a686d1fab775cc9d8f9fc35b2aa475978538e34e47ee8f4380fb4b3.dat
 as plot-2-31-125f6af87a686d1fab775cc9d8f9fc35b2aa475978538e34e47ee8f4380fb4b3.dat
rewriting /mnt/d/plots/plot-3-31-c934982e2bf6dced3428883a62937ffa990480dcba3054bac998e061b483b6d4.dat
 as plot-3-31-c934982e2bf6dced3428883a62937ffa990480dcba3054bac998e061b483b6d4.dat
rewriting /mnt/d/plots/plot-4-31-0cc70e6944d3f94d8e6dc9eb10cc9ecc907a0fa74d5a3ca2c8814c44ecf7dbe5.dat
 as plot-4-31-0cc70e6944d3f94d8e6dc9eb10cc9ecc907a0fa74d5a3ca2c8814c44ecf7dbe5.dat
rewriting /mnt/d/plots/plot-5-31-d2815b24353c168cb6d87e02897001b9794d01e4e31cd69954747aa26dc49d66.dat
 as plot-5-31-d2815b24353c168cb6d87e02897001b9794d01e4e31cd69954747aa26dc49d66.dat
rewriting /mnt/d/plots/plot-6-31-1959fea7fc1587bd129cd56f9cf7648556fcae41b9d3a91480da6fbae2f8cb91.dat
 as plot-6-31-1959fea7fc1587bd129cd56f9cf7648556fcae41b9d3a91480da6fbae2f8cb91.dat
rewriting /mnt/d/plots/plot-7-31-52b0f5e1b34d0ae0f773f6205c0ee981a64dee02ddb622a6aafd2bdc537d7190.dat
 as plot-7-31-52b0f5e1b34d0ae0f773f6205c0ee981a64dee02ddb622a6aafd2bdc537d7190.dat
rewriting /mnt/d/plots/plot-8-31-7399f7fd9f64e422a9cb6fa500b6452a1762179bd5ddbfd10073a34bad138106.dat
 as plot-8-31-7399f7fd9f64e422a9cb6fa500b6452a1762179bd5ddbfd10073a34bad138106.dat


Your plots have not been moved so be careful deleting old preferences folders.

migrating keys.yaml
Traceback (most recent call last):
  File "C:\Users\dkack\AppData\Local\Programs\Python\Python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
    exec(code, run_globals)
  File "C:\Users\dkack\AppData\Local\Programs\Chia Network\Chia Blockchain\venv\Scripts\chia.exe\__main__.py", line 7, in <module>
  File "c:\users\dkack\appdata\local\programs\chia network\chia blockchain\venv\lib\site-packages\src\cmds\chia.py", line 48, in main
    return chia(args, parser)
  File "c:\users\dkack\appdata\local\programs\chia network\chia blockchain\venv\lib\site-packages\src\cmds\chia.py", line 42, in chia
    return args.function(args, parser)
  File "c:\users\dkack\appdata\local\programs\chia network\chia blockchain\venv\lib\site-packages\src\cmds\init.py", line 143, in init
    return chia_init(args)
  File "c:\users\dkack\appdata\local\programs\chia network\chia blockchain\venv\lib\site-packages\src\cmds\init.py", line 174, in chia_init
    r = migrate_from(old_path, root_path, manifest, DO_NOT_MIGRATE_KEYS)
  File "c:\users\dkack\appdata\local\programs\chia network\chia blockchain\venv\lib\site-packages\src\cmds\init.py", line 116, in migrate_from
    BLSPublicKey(bytes(wallet_sk.public_child(0).get_public_key()))
ValueError: Relic library error
````

**Comment by mariano54** [comment]
What OS version?

**Comment by hoffmang9** [comment]
Windows 10 native

**Comment by dkackman** [comment]
windows 10, with 1909 update.

**Comment by mariano54** [comment]
@wjblanke can we close this?

**Comment by wjblanke** [comment]
fixed in b6
