### ISSUE TITLE
[BUG] Can't start Electron GUI

### ISSUE THREAD

**Issue by driversti** [Chia-Network/chia-blockchain#2143]
**Describe the bug**
I can't start the GUI. The error log you can see on the bottom

**To Reproduce**

1. Go to https://github.com/Chia-Network/chia-blockchain/wiki/INSTALL#ubuntudebian
2. Run all described commands
3. Type the last one `npm run electron &`
4. See the error

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'run', 'electron' ]
2 info using npm@6.14.12
3 info using node@v14.16.1
4 verbose run-script [ 'preelectron', 'electron', 'postelectron' ]
5 info lifecycle chia-blockchain@~preelectron: chia-blockchain@
6 info lifecycle chia-blockchain@~electron: chia-blockchain@
7 verbose lifecycle chia-blockchain@~electron: unsafe-perm in lifecycle true
8 verbose lifecycle chia-blockchain@~electron: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/driversti/chia-blockchain/chia-blockchain-gui/node_modules/.$
9 verbose lifecycle chia-blockchain@~electron: CWD: /home/driversti/chia-blockchain/chia-blockchain-gui
10 silly lifecycle chia-blockchain@~electron: Args: [ '-c', 'electron .' ]
11 silly lifecycle chia-blockchain@~electron: Returned: code: 1  signal: null
12 info lifecycle chia-blockchain@~electron: Failed to exec electron script
13 verbose stack Error: chia-blockchain@ electron: `electron .`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:315:20)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:315:20)
13 verbose stack     at maybeClose (internal/child_process.js:1048:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
14 verbose pkgid chia-blockchain@
15 verbose cwd /home/driversti/chia-blockchain/chia-blockchain-gui
16 verbose Linux 4.15.0-142-generic
17 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "electron"
18 verbose node v14.16.1
19 verbose npm  v6.14.12
20 error code ELIFECYCLE
21 error errno 1
22 error chia-blockchain@ electron: `electron .`
22 error Exit status 1
23 error Failed at the chia-blockchain@ electron script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Expected behavior**
The GUI should start

**Screenshots**
not applicable

**Desktop (please complete the following information):**

- OS
```
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.5 LTS
Release:	18.04
Codename:	bionic
DE:             LXDE
```
- CPU (virtual CPX11 machine on Hetzner): 
```
Architecture:        x86_64
CPU op-mode(s):      32-bit, 64-bit
Byte Order:          Little Endian
CPU(s):              1
On-line CPU(s) list: 0
Thread(s) per core:  1
Core(s) per socket:  1
Socket(s):           1
NUMA node(s):        1
Vendor ID:           GenuineIntel
CPU family:          6
Model:               85
Model name:          Intel Xeon Processor (Skylake, IBRS)
Stepping:            4
CPU MHz:             2294.608
BogoMIPS:            4589.21
Hypervisor vendor:   KVM
Virtualization type: full
L1d cache:           32K
L1i cache:           32K
L2 cache:            4096K
L3 cache:            16384K
```
**Additional context**

**Comment by BIERAAP** [comment]
Make sure you have enough ram. I had the exact same issue. Increased to 4GB and problem solved.
