### ISSUE TITLE
[Fix] Solution sur le  Bug Infini du Porte-Feuille

### ISSUE THREAD

**Issue by dexter74** [Chia-Network/chia-blockchain#2148]
**Describe the bug**

**To Reproduce**

1. Go to 'Start Chia'
2. Click on 'Mode developer'

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/35907/115294407-db196280-a158-11eb-8538-dff24a32ff73.png)

**Desktop (please complete the following information):**

- OS: [e.g. Linux] Windows 10
- OS Version/Flavor: [e.g. CentOS 7.2]
- CPU: [e.g. Intel Xeon 8175M]

**Additional context**

**Comment by dexter74** [comment]
PS C:\Users\teste\AppData\Local\chia-blockchain\app-1.0.5\resources\app.asar.unpacked\daemon> .\daemon.exe
Chia directory C:\Users\teste\.chia\mainnet
Traceback (most recent call last):
  File "chia\daemon\server.py", line 954, in <module>
  File "chia\daemon\server.py", line 950, in main
  File "chia\daemon\server.py", line 944, in run_daemon
  File "asyncio\base_events.py", line 587, in run_until_complete
  File "chia\daemon\server.py", line 908, in async_run_daemon
  File "chia\cmds\init.py", line 318, in chia_init
  File "chia\cmds\init.py", line 58, in check_keys
  File "chia\util\config.py", line 55, in load_config
  File "yaml\__init__.py", line 162, in safe_load
  File "yaml\__init__.py", line 112, in load
  File "yaml\loader.py", line 34, in __init__
  File "yaml\reader.py", line 85, in __init__
  File "yaml\reader.py", line 135, in determine_encoding
  File "yaml\reader.py", line 169, in update
  File "yaml\reader.py", line 144, in check_printable
yaml.reader.ReaderError: unacceptable character #x0000: special characters are not allowed
  in "C:\Users\teste\.chia\mainnet\config\config.yaml", position 0
[4968] Failed to execute script server
PS C:\Users\teste\AppData\Local\chia-blockchain\app-1.0.5\resources\app.asar.unpacked\daemon> .\daemon.exe
Chia directory C:\Users\teste\.chia\mainnet
Can't find private CA, creating a new one in C:\Users\teste\.chia\mainnet to generate TLS certificates
Setting the xch destination address for coinbase fees reward to xch12dtun5zq2pu86qdmwcujke9afvqw3qys8kfw22s6x8qz6yhrrges9etal2
Setting the xch destination address for coinbase reward to xch12dtun5zq2pu86qdmwcujke9afvqw3qys8kfw22s6x8qz6yhrrges9etal2

To see your keys, run 'chia keys show'

{"ca_crt": "C:\\Users\\teste\\.chia\\mainnet\\config\\ssl\\ca\\private_ca.crt", "cert": "C:\\Users\\teste\\.chia\\mainnet\\config\\ssl\\daemon\\private_daemon.crt", "key": "C:\\Users\\teste\\.chia\\mainnet\\config\\ssl\\daemon\\private_daemon.key", "message": "cert_path", "success": true}

**Comment by dexter74** [comment]
Fix: 
Delete folder C:\Users\<user>\.chia and regenerate certificate is work

**Comment by dexter74** [comment]
0. Clos Launch.
1. Delete Folder
2. CMD

Je propose qu'une solution de contournement pas un correctif pour débloqué toute les situations.
