### ISSUE TITLE
Install gui (when electron-winstaller) failed on CentOS 7.7 

### ISSUE THREAD

**Issue by anderzheng** [Chia-Network/chia-blockchain#2162]
There's some thing error when I execut "sh install-gui.sh".

Here's the output on screen when error occur:
+----------------------------------------------------------------------------------
Submodule path 'chia-blockchain-gui': checked out '1dcfd1e8c057a3decee76a59dad60ecb673d5318'
Running git submodule update.

> yarn@1.22.10 preinstall /usr/lib/chia/chia-blockchain-gui/node_modules/yarn
> :; (node ./preinstall.js > /dev/null 2>&1 || true)

> electron-winstaller@5.0.0 install /usr/lib/chia/chia-blockchain-gui/node_modules/electron-winstaller
> node ./script/select-7z-arch.js

Selecting 7-Zip for arch x64
/usr/lib/chia/chia-blockchain-gui/node_modules/electron-winstaller/script/select-7z-arch.js:16
    throw err;
    ^

Error: EACCES: permission denied, copyfile 'vendor/7z-x64.exe' -> 'vendor/7z.exe'
    at Object.copyFileSync (fs.js:1941:3)
    at Object.<anonymous> (/usr/lib/chia/chia-blockchain-gui/node_modules/electron-winstaller/script/select-7z-arch.js:14:8)
    at Module._compile (internal/modules/cjs/loader.js:1251:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1272:10)
    at Module.load (internal/modules/cjs/loader.js:1100:32)
    at Function.Module._load (internal/modules/cjs/loader.js:962:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47 {
  errno: -13,
  syscall: 'copyfile',
  code: 'EACCES',
  path: 'vendor/7z-x64.exe',
  dest: 'vendor/7z.exe'
}
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules/webpack-dev-server/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.3.2 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! electron-winstaller@5.0.0 install: `node ./script/select-7z-arch.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the electron-winstaller@5.0.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-04-20T03_16_51_669Z-debug.log
--------------------------------------------------------------------------------------------------+

And this is the part content in 2021-04-20T03_16_51_669Z-debug.log :
+----------------------------------------------------------------------------------------------
42760 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid OS:    darwin
42760 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid Arch:  any
42760 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual OS:   linux
42760 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual Arch: x64
42761 verbose stack Error: electron-winstaller@5.0.0 install: `node ./script/select-7z-arch.js`
42761 verbose stack Exit status 1
42761 verbose stack     at EventEmitter.<anonymous> (/opt/node-v14.8.0-linux-x64/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
42761 verbose stack     at EventEmitter.emit (events.js:314:20)
42761 verbose stack     at ChildProcess.<anonymous> (/opt/node-v14.8.0-linux-x64/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
42761 verbose stack     at ChildProcess.emit (events.js:314:20)
42761 verbose stack     at maybeClose (internal/child_process.js:1051:16)
42761 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5)
42762 verbose pkgid electron-winstaller@5.0.0
42763 verbose cwd /usr/lib/chia/chia-blockchain-gui
42764 verbose Linux 3.10.0-1062.el7.x86_64
42765 verbose argv "/opt/node-v14.8.0-linux-x64/bin/node" "/opt/node-v14.8.0-linux-x64/bin/npm" "install"
42766 verbose node v14.8.0
42767 verbose npm  v6.14.7
42768 error code ELIFECYCLE
42769 error errno 1
42770 error electron-winstaller@5.0.0 install: `node ./script/select-7z-arch.js`
42770 error Exit status 1
42771 error Failed at the electron-winstaller@5.0.0 install script.
42771 error This is probably not a problem with npm. There is likely additional logging output above.
42772 verbose exit [ 1, true ]

**Comment by anderzheng** [comment]
I have tried to fix the shell, and it worked well on my machine.
I don't known the rule to commit it, anyone with the same problem could look this:
https://github.com/Chia-Network/chia-blockchain/pull/2163
