### ISSUE TITLE
[BUG] Cannot plot - Process is paused

### ISSUE THREAD

**Issue by mfoglio** [Chia-Network/chia-blockchain#2198]
I am using the GUI to create my first plot. I tried to do that in macOS as well as in a virtual machine running Ubuntu within macOS. Both times the process seemed to pause after a while (13% in one case, 30% in another). I tried to disabled all the os settings related to energy saving. K-Size is 32 but I have not tried with others yet. I am really new to Chia and farming in general.

**Comment by dorkmo** [comment]
you might post your plotting log, did it show any errors at the end?

**Comment by mfoglio** [comment]
I am sorry, I didn't notice I could access the log. I restarted the project. I will post the log if it stops again.

**Comment by gitscy** [comment]
What caused the error. I have sufficient cache disk space and RAM

Compressing tables 1 and 2
Caught plotting error: bad allocation
[3088] Failed to execute script chia
Traceback (most recent call last):
  File "chia\cmds\chia.py", line 80, in <module>
  File "chia\cmds\chia.py", line 76, in main
  File "click\core.py", line 829, in __call__
  File "click\core.py", line 782, in main
  File "click\core.py", line 1259, in invoke
  File "click\core.py", line 1259, in invoke
  File "click\core.py", line 1066, in invoke
  File "click\core.py", line 610, in invoke
  File "click\decorators.py", line 21, in new_func
  File "chia\cmds\plots.py", line 134, in create_cmd
  File "chia\plotting\create_plots.py", line 176, in create_plots
RuntimeError: bad allocation

**Comment by dorkmo** [comment]
i believe bad allocation is thought to mean a possible hardware failure

**Comment by hoffmang9** [comment]
This is almost always a hardware RAM problem though sometimes it is swap settings.
