### ISSUE TITLE
Caught plotting error: bad allocation - Creating Plott

### ISSUE THREAD

**Issue by LefiS** [Chia-Network/chia-blockchain#2206]
Starting plotting progress into temporary dirs: D:\CRYPTO\CHIA\TEMP and D:\CRYPTO\CHIA\TEMP
Plot size is: 32
Buffer size is: 3390MiB
Using 128 buckets
Using 2 threads of stripe size 65536

Starting phase 1/4: Forward Propagation into tmp files... Tue Apr 20 19:13:48 2021
Computing table 1
F1 complete, time: 394.423 seconds. CPU (43.61%) Tue Apr 20 19:20:22 2021
Computing table 2
Caught plotting error: bad allocation
[24216] Failed to execute script chia
Traceback (most recent call last):
  File "chia\cmds\chia.py", line 80, in <module>
  File "chia\cmds\chia.py", line 76, in main
  File "click\core.py", line 829, in __call__
  File "click\core.py", line 782, in main
  File "click\core.py", line 1259, in invoke
  File "click\core.py", line 1259, in invoke
  File "click\core.py", line 1066, in invoke
  File "click\core.py", line 610, in invoke
  File "click\decorators.py", line 21, in new_func
  File "chia\cmds\plots.py", line 134, in create_cmd
  File "chia\plotting\create_plots.py", line 176, in create_plots
RuntimeError: bad allocation

**Comment by hoffmang9** [comment]
This is either a hardware or software problem with your RAM. Sometimes the swap file is the problem but it's often overclocking.
