### ISSUE TITLE
Cannot find module "select-7z-arch.js" while installing GUI

### ISSUE THREAD

**Issue by EnGoPy** [Chia-Network/chia-blockchain#2231]
I've followed instructions how to install on ubuntu.
Perhaps logs are the best to describe.

Ubuntu 20.04.2 LTS

root@computer:~/chia-blockchain# sh install-gui.sh
apt-get is /usr/bin/apt-get
Reading package lists... Done
Building dependency tree       
Reading state information... Done
libxss1 is already the newest version (1:1.2.3-1).
nodejs is already the newest version (10.19.0~dfsg-3ubuntu1).
npm is already the newest version (6.14.4+ds-1ubuntu2).
The following packages were automatically installed and are no longer required:
  fonts-font-awesome libfprint-2-tod1 linux-headers-5.4.0-70 linux-headers-5.4.0-70-generic linux-image-5.4.0-70-generic linux-modules-5.4.0-70-generic linux-modules-extra-5.4.0-70-generic
Use 'sudo apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 44 not upgraded.

Installing on Ubuntu 20.04 LTS or newer: Using installed node.js version
Running git submodule update --init --recursive.

Running git submodule update.

> electron-winstaller@5.0.0 install /root/chia-blockchain/chia-blockchain-gui/node_modules/electron-winstaller
> node ./script/select-7z-arch.js

internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module '/root/chia-blockchain/chia-blockchain-gui/node_modules/electron-winstaller/script/select-7z-arch.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
npm WARN @pmmmwh/react-refresh-webpack-plugin@0.4.3 requires a peer of react-refresh@>=0.8.3 <0.10.0 but none is installed. You must install peer dependencies yourself.
npm WARN @use-it/event-listener@0.1.6 requires a peer of react@^16.8.0 but none is installed. You must install peer dependencies yourself.
npm WARN acorn-dynamic-import@4.0.0 requires a peer of acorn@^6.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN react-scroll-to-bottom@4.1.1-master.2780945 requires a peer of react@^16.8.6 but none is installed. You must install peer dependencies yourself.
npm WARN react-simple-code-editor@0.10.0 requires a peer of react@^16.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN react-simple-code-editor@0.10.0 requires a peer of react-dom@^16.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN use-dark-mode@2.3.1 requires a peer of react@^16.8.0 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.3.2 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules/webpack-dev-server/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! electron-winstaller@5.0.0 install: `node ./script/select-7z-arch.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the electron-winstaller@5.0.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-04-21T00_41_12_261Z-debug.log

**Comment by EnGoPy** [comment]
[#2163](https://github.com/Chia-Network/chia-blockchain/pull/2163) worked for me
