### ISSUE TITLE
[BUG] chia farm summary returns 'Not available'

### ISSUE THREAD

**Issue by JordyBaylac** [Chia-Network/chia-blockchain#2241]
I am getting ubuntu alerts about a crash with python, after I check the plotting process they look ok, however, when calling **chia farm summary** I get below response. 

```sh
$ chia farm summary
Connection error. Check if full node is running at 8555
Farming status: Not available
...
```

Above command was working and returning 'Farming' status minutes before.

```sh
$ chia show -s -c
Connection error. Check if full node rpc is running at 8555
This is normal if full node is still starting up
```

I then went to try **chia stop -d all** and  **chia start farmer**, but I get other errors:

```sh
$ chia stop -d all
daemon: {'ack': True, 'command': 'exit', 'data': {'success': True}, 'destination': 'client', 'origin': 'daemon', 'request_id': '5cb5cd3c89f8ae3bb0af8722027938fe4e5c7045cf461eed210ce3c006b7db30'}
```

```sh
$ chia start farmer
Daemon not started yet
Starting daemon
chia_harvester: started
chia_farmer: started
chia_full_node: started
chia_wallet: started
$ ... Traceback (most recent call last):
  File "/home/user/chia-blockchain/venv/bin/chia_full_node", line 33, in <module>
    sys.exit(load_entry_point('chia-blockchain', 'console_scripts', 'chia_full_node')())
  File "/home/user/chia-blockchain/chia/server/start_full_node.py", line 60, in main
    return run_service(**kwargs)
  File "/home/user/chia-blockchain/chia/server/start_service.py", line 211, in run_service
    return asyncio.run(async_run_service(*args, **kwargs))
  File "/usr/lib/python3.8/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/user/chia-blockchain/chia/server/start_service.py", line 205, in async_run_service
    return await service.run()
  File "/home/user/chia-blockchain/chia/server/start_service.py", line 150, in run
    await self.start()
  File "/home/user/chia-blockchain/chia/server/start_service.py", line 126, in start
    await self._server.start_server(self._on_connect_callback)
  File "/home/user/chia-blockchain/chia/server/server.py", line 212, in start_server
    await self.site.start()
  File "/home/user/chia-blockchain/venv/lib/python3.8/site-packages/aiohttp/web_runner.py", line 121, in start
    self._server = await loop.create_server(
  File "/usr/lib/python3.8/asyncio/base_events.py", line 1463, in create_server
    raise OSError(err.errno, 'error while attempting '
OSError: [Errno 98] error while attempting to bind on address ('::', 8444, 0, 0): address already in use
^C
```

**Desktop:**
- OS: Ubuntu 20.04

**Comment by caelumdev** [comment]
Same issue.

**Comment by shibowe** [comment]
The same error for me , how to solve it  ?

**Comment by JordyBaylac** [comment]
@shibowe at the moment I am **ps -aux | grep chia_** anc then killing each process (**kill pid1 pid2 ... pidN**)

**Comment by mariano54** [comment]
Yes kill all chia processes, restart computer

**Comment by shibowe** [comment]
but, why do that? Is it bug ? or others ?

**Comment by happy1989525** [comment]
Same issue here

**Comment by 0xPPPY** [comment]
> Same issue here

I fix this issue, it may cause by you are using different user to use chia.
For example, you use root user to "chia start all", but next time you are using ubuntu user to "chia show -s", the error will returned.
