### ISSUE TITLE
[BUG] ERROR    Exception:  <class 'concurrent.futures._base.CancelledError'>, closing connection {'host': '127.0.0.1', 'port': 8444}

### ISSUE THREAD

**Issue by GeorgePapageorgakis** [Chia-Network/chia-blockchain#2247]
Any idea what this is? Logs are getting full with these messages...
 Is this a bug or a problem on my side?

wallet wallet_server : ERROR Exception: <class 'concurrent.futures._base.CancelledError'>, closing connection {'host': '127.0.0.1', 'port': 8444}. Traceback (most recent call last):
File "chia\server\server.py", line 519, in api_call
File "asyncio\tasks.py", line 435, in wait_for
concurrent.futures._base.CancelledError

09:28:31.265 full_node full_node_server        : ERROR    Exception:  <class 'concurrent.futures._base.CancelledError'>, closing connection {'host': '127.0.0.1', 'port': 8449}. Traceback (most recent call last):
  File "chia\server\server.py", line 519, in api_call
  File "asyncio\tasks.py", line 435, in wait_for
concurrent.futures._base.CancelledError

09:28:32.770 wallet wallet_server              : ERROR    Exception:  <class 'concurrent.futures._base.CancelledError'>, closing connection {'host': '127.0.0.1', 'port': 8444}. Traceback (most recent call last):
  File "chia\server\server.py", line 519, in api_call
  File "asyncio\tasks.py", line 435, in wait_for
concurrent.futures._base.CancelledError

- OS: Windows 10 pro
- CPU: i7 6700K

**Comment by Sechui** [comment]
me too

**Comment by falsemail** [comment]
mine is ERROR    Exception:  <class 'concurrent.futures._base.CancelledError'>, closing connection {'host': '68.110.14.234', 'port': 8444}. Traceback (most recent call last):
  File "/root/chia-blockchain/chia/server/server.py", line 519, in api_call
    response: Optional[Message] = await asyncio.wait_for(wrapped_coroutine(), timeout=600)
  File "/usr/lib/python3.7/asyncio/tasks.py", line 435, in wait_for
    await waiter
concurrent.futures._base.CancelledError
any idea?
why 68.110.14.234?

**Comment by Sechui** [comment]
maybe VPN？能说中文吗？
我也不知道这是为什么报错。。。




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年4月21日(星期三) 晚上10:14
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Chia-Network/chia-blockchain] [BUG] ERROR    Exception:  <class &#39;concurrent.futures._base.CancelledError&#39;&gt;, closing connection {&#39;host&#39;: &#39;127.0.0.1&#39;, &#39;port&#39;: 8444} (#2247)





 
mine is ERROR    Exception:  <class 'concurrent.futures._base.CancelledError'&gt;, closing connection {'host': '68.110.14.234', 'port': 8444}. Traceback (most recent call last):
 File "/root/chia-blockchain/chia/server/server.py", line 519, in api_call
 response: Optional[Message] = await asyncio.wait_for(wrapped_coroutine(), timeout=600)
 File "/usr/lib/python3.7/asyncio/tasks.py", line 435, in wait_for
 await waiter
 concurrent.futures._base.CancelledError
 any idea?
 why 68.110.14.234?

**Comment by kernel1983** [comment]
Similiar suitation here, and try to configure log to DEBUG level
I found I can not connect to any peer, even if I increased timeout.

23:40:07.193 full_node full_node_server        : DEBUG    Connecting: wss://183.15.182.21:8444/ws, Peer info: {'host': '183.15.182.21', 'port': 8444}
23:40:28.236 full_node full_node_server        : INFO     Cannot connect to host 183.15.182.21:8444 ssl:<ssl.SSLContext object at 0x0000019692658A40>
23:40:30.246 full_node chia.server.address_manager: DEBUG    address_manager.select_peer took 0.00e+00 seconds in tried table.
23:40:30.250 full_node full_node_server        : DEBUG    Connecting: wss://157.90.1.43:8444/ws, Peer info: {'host': '157.90.1.43', 'port': 8444}
23:40:32.750 full_node full_node_server        : INFO     -> handshake to peer 157.90.1.43 14c9e15c785955303515f7e5d5c536dc8ff44d5c7dc4bcfe2d650569a576a2a2
23:40:33.058 full_node full_node_server        : INFO     Connected with full_node {'host': '157.90.1.43', 'port': 8444}
23:40:33.061 full_node full_node_server        : INFO     -> new_peak to peer 157.90.1.43 14c9e15c785955303515f7e5d5c536dc8ff44d5c7dc4bcfe2d650569a576a2a2
23:40:33.063 full_node full_node_server        : DEBUG    Peer closed connection full_node 157.90.1.43:8444/8444
23:40:33.066 full_node full_node_server        : DEBUG    Inbound_handler task cancelled
23:40:33.067 full_node full_node_server        : INFO     Connection closed: 157.90.1.43, node id: 14c9e15c785955303515f7e5d5c536dc8ff44d5c7dc4bcfe2d650569a576a2a2
23:40:33.069 full_node chia.full_node.full_node: INFO     peer disconnected {'host': '157.90.1.43', 'port': 8444}
23:40:35.084 full_node chia.server.address_manager: DEBUG    address_manager.select_peer took 0.00e+00 seconds in new table.
23:40:35.089 full_node full_node_server        : DEBUG    Connecting: wss://212.9.102.224:8444/ws, Peer info: {'host': '212.9.102.224', 'port': 8444}
23:40:46.777 full_node full_node_server        : INFO     Cannot connect to host 212.9.102.224:8444 ssl:<ssl.SSLContext object at 0x00000196934F5940>
23:40:48.783 full_node chia.server.address_manager: DEBUG    address_manager.select_peer took 0.00e+00 seconds in tried table.
23:40:48.786 full_node full_node_server        : DEBUG    Connecting: wss://71.238.21.196:8444/ws, Peer info: {'host': '71.238.21.196', 'port': 8444}
23:40:49.510 full_node full_node_server        : INFO     -> handshake to peer 71.238.21.196 6aa4b9f78e54cc6ddccd9a4be0bbd27312334dd7d8023d12ee6268d30c60ec09
23:40:49.711 full_node full_node_server        : INFO     Connected with full_node {'host': '71.238.21.196', 'port': 8444}
23:40:49.713 full_node full_node_server        : INFO     -> new_peak to peer 71.238.21.196 6aa4b9f78e54cc6ddccd9a4be0bbd27312334dd7d8023d12ee6268d30c60ec09
23:40:49.715 full_node full_node_server        : INFO     -> request_peers to peer 71.238.21.196 6aa4b9f78e54cc6ddccd9a4be0bbd27312334dd7d8023d12ee6268d30c60ec09
23:40:49.715 full_node full_node_server        : DEBUG    Peer closed connection full_node 71.238.21.196:8444/8444
23:40:49.715 full_node full_node_server        : DEBUG    Inbound_handler task cancelled
23:40:49.715 full_node full_node_server        : INFO     Connection closed: 71.238.21.196, node id: 6aa4b9f78e54cc6ddccd9a4be0bbd27312334dd7d8023d12ee6268d30c60ec09
23:40:49.715 full_node chia.full_node.full_node: INFO     peer disconnected {'host': '71.238.21.196', 'port': 8444}
23:40:51.721 full_node chia.server.address_manager: DEBUG    address_manager.select_peer took 0.00e+00 seconds in new table.

**Comment by trinsic** [comment]
Same problem.

```
2021-04-22T12:16:05.162 full_node full_node_server        : ERROR    Exception:  <class 'concurrent.futures._base.CancelledError'>, closing connection {'host': '114.242.242.12', 'port': 8444}. Traceback (most recent call last):
  File "/root/chia-blockchain/chia/server/server.py", line 521, in api_call
    response: Optional[Message] = await asyncio.wait_for(wrapped_coroutine(), timeout=600)
  File "/usr/lib/python3.7/asyncio/tasks.py", line 409, in wait_for
    await waiter
concurrent.futures._base.CancelledError
```
Chia 1.1.0
Raspberry Pi 3B

**Comment by xupeng9** [comment]
Same problem

**Comment by krychuq1** [comment]
I'm having same issue :( 

2021-04-23T09:28:56.660 full_node full_node_server        : ERROR    Exception:  <class 'concurrent.futures._base.CancelledError'>, closing connection {'host': '127.0.0.1', 'port': 8449}. Traceback (most recent call last):
  File "chia\server\server.py", line 521, in api_call
  File "asyncio\tasks.py", line 435, in wait_for
concurrent.futures._base.CancelledError

2021-04-23T09:28:58.349 wallet wallet_server              : ERROR    Exception:  <class 'concurrent.futures._base.CancelledError'>, closing connection {'host': '127.0.0.1', 'port': 8444}. Traceback (most recent call last):
  File "chia\server\server.py", line 521, in api_call
  File "asyncio\tasks.py", line 435, in wait_for
concurrent.futures._base.CancelledError

**Comment by lGSMl** [comment]
same problem after updating to 1.1.1, 1.0.5 worked fine

**Comment by krychuq1** [comment]
Ok I manged to fix it. I'm not sure which one worked but I opened port 8444 on router 
https://www.yougetsignal.com/tools/open-ports/
https://github.com/Chia-Network/chia-blockchain/wiki/Port-8444

Later on I've removed wallet database and restart chia. Everything seems to be working fine no errors in the logs :)

**Comment by zewort** [comment]
same problem 1.1.2

**Comment by piotrryczek** [comment]
@krychuq1 could you tell more about "wallet database"? Which files it is related, what can happen if I delete it, what is it responsible for?
Sorry for probably basic questions, also if I should dig into some url I will appreciate ;)

**Comment by krychuq1** [comment]
if you are on windows:  C:\Users\xxxx\.chia\mainnet\wallet, when i removed db and then gui started to sync wallet from 0

**Comment by piotrryczek** [comment]
Ok so generally it is just sync history of blocks (history of blocks in blockchain) so it is no dangerous to any data ;)

**Comment by gbrown2036** [comment]
Did you make sure that once you re-launched the GUI that you clicked the big black button to log back in?  I stupidly didn't do this and got this error too.  I then deleted the log file and relaunched and logged back in and it saw my two harvesters.

**Comment by adrdadr** [comment]
Same Issue
Version 1.1.2
OS Windows 10
Full desinstall of chia + delete .chia +reboot  + reinstall chia with mnemonic.. the issue persist. Port 8444  is opened 

full_node full_node_server        : ERROR    Exception:  <class 'concurrent.futures._base.CancelledError'>, closing connection None. Traceback (most recent call last):
  File "chia\server\server.py", line 521, in api_call
  File "asyncio\tasks.py", line 435, in wait_for
concurrent.futures._base.CancelledError

Any idea?
Thanks

**Comment by lordsid73** [comment]
> Same Issue
> Version 1.1.2
> OS Windows 10
> Full desinstall of chia + delete .chia +reboot + reinstall chia with mnemonic.. the issue persist. Port 8444 is opened
> 
> full_node full_node_server : ERROR Exception: <class 'concurrent.futures._base.CancelledError'>, closing connection None. Traceback (most recent call last):
> File "chia\server\server.py", line 521, in api_call
> File "asyncio\tasks.py", line 435, in wait_for
> concurrent.futures._base.CancelledError
> 
> Any idea?
> Thanks

exactly same issue and tryouts with problem not being solved

**Comment by shredding** [comment]
Does this mean it's not working at all?

**Comment by adrdadr** [comment]
Same issues with   Chia Version 1.1.3 
2021-05-04T08:22:22.989 full_node full_node_server        : ERROR    Exception:  <class 'concurrent.futures._base.CancelledError'>, closing connection {'host': '119.195.179.48', 'port': 8444}. Traceback (most recent call last):
  File "chia\server\server.py", line 531, in api_call
  File "asyncio\tasks.py", line 435, in wait_for
concurrent.futures._base.CancelledError

**Comment by vballe** [comment]
Same issue here;

full_node full_node_server        : ERROR    Exception:  <class 'concurrent.futures._base.CancelledError'>, closing connection None. Traceback (most recent call last):
  File "chia\server\server.py", line 531, in api_call
  File "asyncio\tasks.py", line 435, in wait_for
concurrent.futures._base.CancelledError

Really nervous. Acording to CanYouSeeMe.org my 8444 is open.

The GUI really needs to be better to tell you if something serious is of..

**Comment by ramet99** [comment]
2021-05-07T15:38:50.818 full_node full_node_server        : ERROR    Exception:  <class 'concurrent.futures._base.CancelledError'>, closing connection {'host': '127.0.0.1',
'port': 8449}. Traceback (most recent call last):
concurrent.futures._base.CancelledError

Same issue and I am on 1.1.4. I did restart and even reboot my computer, still no luck.  8444 is open on my router too.  
Anyone have any ideas or does this error not matter too much? over 120 plots and no coins yet.

**Comment by techbiadev** [comment]
Same problem 1.1.4

**Comment by rtmrodrigues** [comment]
...same here with same version.

**Comment by rtmrodrigues** [comment]
Solved for me!
Uninstall Chia GUI, delete folder "C:\Users\USERNAME\.chia\" (where your log and config files are).
Reboot, install Chia GUI again and wait for sync.

After some more reading, you may also stop Chia GUI, delete de DB files and start Chia GUI.

Hope this helps someone.

**Comment by rmreeves09** [comment]
> `ERROR Exception: <class 'concurrent.futures._base.CancelledError'>, closing connection {'host': '127.0.0.1', 'port': 8447}`
> 
> Can we have a response if this error is significant?
> My Node still does proofs according to the GUI and the occasional above 5s warning.
> Still the error references banning the localhost or 127.0.0.1 which kind of makes me uneasy.
> The error directly above is always:
> 
> `WARNING Trying to ban localhost for 10, but will not ban`
> 
> Maybe it bans anyways and that's the reason for the errors?
> A reinstall and wallet resync did not help.

Are you also seeing your wallet (127.0.0.1) on the full node page of the GUI constantly rotating through ports?

**Comment by CryHenry** [comment]
Chia is probably the worst piece of software released in the history of the internet. Nothing works.

**Comment by matteoflavi** [comment]
Same problem here,
wallet never synced and on host log I see the wallet connection to 127.0.0.1 change the port every 1 sec.

An answer from Chia developer would be appreciated...

**Comment by cihansardaslar** [comment]
SAme problem here. my 8444 is open but not 8449

2021-05-14T16:05:09.041 full_node full_node_server        : ERROR    Exception:  <class 'concurrent.futures._base.CancelledError'>, closing connection {'host': '127.0.0.1', 'port': 8449}. Traceback (most recent call last):
  File "chia\server\server.py", line 531, in api_call
  File "asyncio\tasks.py", line 435, in wait_for
concurrent.futures._base.CancelledError

2021-05-14T16:05:10.544 full_node full_node_server        : ERROR    Exception:  <class 'concurrent.futures._base.CancelledError'>, closing connection {'host': '127.0.0.1', 'port': 8449}. Traceback (most recent call last):
  File "chia\server\server.py", line 531, in api_call
  File "asyncio\tasks.py", line 435, in wait_for
concurrent.futures._base.CancelledError

2021-05-14T16:05:12.063 full_node full_node_server        : ERROR    Exception:  <class 'concurrent.futures._base.CancelledError'>, closing connection {'host': '127.0.0.1', 'port': 8449}. Traceback (most recent call last):
  File "chia\server\server.py", line 531, in api_call
  File "asyncio\tasks.py", line 435, in wait_for
concurrent.futures._base.CancelledError

**Comment by btalachian** [comment]
Any update on this issue?

ERROR    Exception:  <class 'concurrent.futures._base.CancelledError'>, closing connection {'host': '127.0.0.1', 'port': 8449}. Traceback (most recent call last):

**Comment by fabioyy** [comment]
i'm getting a lot of timeouts ( and when this happens, the sync appears to halt for several minutes )

2021-05-15T02:54:18.273 full_node full_node_server        : ERROR    Exception:  <class 'concurrent.futures._base.CancelledError'>, closing connection {'host': '127.0.0.1', 'port': 8449}. Traceback (most recent call last):
  File "/usr/home/chia/chia-blockchain/chia/server/server.py", line 531, in api_call
    response: Optional[Message] = await asyncio.wait_for(wrapped_coroutine(), timeout=timeout)
  File "/usr/local/lib/python3.7/asyncio/tasks.py", line 435, in wait_for
    await waiter
concurrent.futures._base.CancelledError


zfs/truenas - hdd raidz2 - ssd for cache - ssd for metadata - and ssd for zlog

( i did git update 2 days ago, and today )

**Comment by Jack74r** [comment]
Hi , my port is open but i have many error like this issue. Can you explain , it's critical error ?

`2021-05-15T19:02:26.609 full_node full_node_server        : ERROR    Exception:  <class 'concurrent.futures._base.CancelledError'>, closing connection {'host': '188.211.xxx.xxx', 'port': 8444}. Traceback (most recent call last):
  File "chia\server\server.py", line 521, in api_call
  File "asyncio\tasks.py", line 435, in wait_for
concurrent.futures._base.CancelledError`

Or 

`2021-05-15T19:16:28.237 full_node chia.full_node.full_node: WARNING  Wasn't able to add transaction with id 1e800e60005f8xxx6f17ca8463d6a645ba5bf08572e638fb80380c0db, status 3 error: Err.UNKNOWN_UNSPENT
2021-05-15T19:16:28.240 full_node chia.full_node.full_node: WARNING  Wasn't able to add transaction with id 787cb4fb7a7xxxx81a8b3ff73c0822ded5c03g7ca8cdfb627c33033d23df, status 3 error: Err.UNKNOWN_UNSPENT
2021-05-15T19:16:28.243 full_node chia.full_node.full_node: WARNING  Wasn't able to add transaction with id 1bd4d086xxxxxx13edf29e89b2b273bf06f60k863c0c897323a708f205c8dbe, status 3 error: Err.UNKNOWN_UNSPENT`

**Comment by leoliyuanduo** [comment]
Same. It's been terrible since my last update to 1.1.5  
Current Blockchain Status is ' Not Synced' most of the time, while Total iterations since the start of the blockchain increase. Only few Last Attempted Proof for a couple of days. Last Attempted Proof are most likely to be a couples hours ago.

**Comment by saulable** [comment]
Getting the same error. Yikes :/

**Comment by Hatly** [comment]
me too
any fix ?

also it says 
received unsolicited block from peer

**Comment by grafbcn** [comment]
Same problem chia 1.1.5, windows server 2016.

**Comment by vizrtit** [comment]
same on 1.1.5 windows server 2019

**Comment by saulable** [comment]
Working now. Had to restart my PC. Didn’t delete any files

**Comment by silence48** [comment]
What is the reason for closing this bug? it doesn't appear to be fixed?

**Comment by shaunlourdes84** [comment]
Hi Team,

I am on version 1.1.6, windows 10, started getting this error message frequently now

2021-05-22T15:20:20.715 full_node chia.full_node.full_node: ERROR    Respond peers exception: 'NoneType' object has no attribute 'host'. Traceback: Traceback (most recent call last):
  File "chia\server\node_discovery.py", line 564, in respond_peers
  File "chia\server\node_discovery.py", line 529, in add_peers_neighbour
AttributeError: 'NoneType' object has no attribute 'host'

2021-05-22T15:20:20.718 full_node full_node_server        : ERROR    Exception:  <class 'concurrent.futures._base.CancelledError'>, closing connection None. Traceback (most recent call last):
  File "chia\server\server.py", line 536, in api_call
  File "asyncio\tasks.py", line 435, in wait_for
concurrent.futures._base.CancelledError

**Comment by DESBY** [comment]
hi everyone,
mine running on windows 10 with chia ver 1.1.6, I'm running 2 full nodes but with **different network**, I don't know will be an issue or not, everything works fine until I get this error message

harvester harvester_server        : ERROR    Exception:  <class 'concurrent.futures._base.CancelledError'>, closing connection None. Traceback (most recent call last):
  File "chia\server\server.py", line 536, in api_call
  File "asyncio\tasks.py", line 435, in wait_for
concurrent.futures._base.CancelledError

can someone help

**Comment by GeorgePapageorgakis** [comment]
The network approach of this error is a bit dangerous. Why do you force people to use UPnP and port forwarding when IT IS KNOWN that it is a known security issue. An amateur hacker can hack people who farm chia with a simple SYN scan.

Please update the software so there is no need for UPnP or port forwarding. Its just outdated...

**Comment by InfiniteImp** [comment]
I've had the same error (<class 'concurrent.futures._base.CancelledError'>) for days (since installing 1.1.6 I believe).  I was seeing it in the logs each 8-11 seconds.  Thanks to the comments above I believe I have it resolved.

Here's what I did.  Not sure which of these steps actually fixed it.

1. Forwarded port 8444 in my router to my full node PC
2. Set logging level to DEBUG
3. Shut down Chia  (would not cleanly exit, had to close the window after waiting 20 seconds)
4. Terminated the remaining Chia running processes (harvester and wallet I believe)
3. Restarted the PC (Intel NUC)
4. I had a BIOS update to do, so I took this opportunity to do it.
5. The PC restarted, I started Chia, logged in, and the error hasn't been back since.

Hope this helps someone.

**Comment by GeorgePapageorgakis** [comment]
@InfiniteImp Do you understand what is the risk of opening a port?

**Comment by DESBY** [comment]
Try this
1. Close any chia in task manager - details
2. Set your pc to a static ip
3. Port forward that ip to 8444
4. Allow inbound connection in windows firewall for port 8444 - 8449 TCP.
5. Start chia
6. After synced, see if you still got errors

for me, i got errors during syncing but after synced, none was occur after applying those fixes.

**Comment by silence48** [comment]
> Try this
> 
> 1. Close any chia in task manager - details
> 2. Set your pc to a static ip
> 3. Port forward that ip to 8444
> 4. Disable upnp in config.yaml
> 5. Allow inbound connection in windows firewall for port 8444 - 8449 TCP.
> 6. Start chia
> 7. After synced, see if you still got errors
> 
> for me, i got errors during syncing but after synced, none was occur after applying those fixes.

So, I'm not running full nodes on the harvesters... Internal firewall rules are correct... My full node runs only on one server, the others connect to it. The full node is open to inbound connections (from my wan), though it does not need to be for this.  The issue is the harvesters are not connecting properly to the full node.  Ea, the full node is refusing or closing the connection, even though the correct ports are open on the server running the full node.  we are talking about a local network same subnet same vlan, no need for any port forwards, only local system firewalls need to be open.

**Comment by InfiniteImp** [comment]
> 
> 
> @InfiniteImp Do you understand what is the risk of opening a port?

Fortunately it's something I won't have to worry about.  I disabled forwarding of port 8444 on the router and the Chia error has not returned.  So, I'm glad to say that's not a required part of my solution.

**Comment by Mehonoshin** [comment]
Anyone knows what is the impact of this issue? Does if affect farming?

**Comment by scheibemanoel** [comment]
Hi, same issue.... CHIA 1.1.6

2021-06-03T21:16:22.169 full_node full_node_server        : ERROR    Exception:  <class 'concurrent.futures._base.CancelledError'>, closing connection None. Traceback (most recent call last):
  File "chia\server\server.py", line 536, in api_call
  File "asyncio\tasks.py", line 435, in wait_for
concurrent.futures._base.CancelledError

2021-06-03T21:35:07.761 full_node full_node_server        : WARNING  Invalid handshake with peer. Maybe the peer is running old software.
2021-06-03T21:42:04.508 full_node full_node_server        : WARNING  Invalid handshake with peer. Maybe the peer is running old software.
2021-06-03T22:07:25.630 full_node full_node_server        : WARNING  Invalid handshake with peer. Maybe the peer is running old software.
2021-06-03T22:08:44.099 full_node full_node_server        : WARNING  Banning 44.192.21.68 for 10 seconds
2021-06-03T22:08:44.101 full_node full_node_server        : WARNING  Invalid handshake with peer. Maybe the peer is running old software.
2021-06-03T22:22:57.328 full_node full_node_server        : WARNING  Invalid handshake with peer. Maybe the peer is running old software.

**Comment by critten27** [comment]
Im getting the same error. Today I noticed that my gui on my main node was not posting the plots attached to that computer. All harvesters were reporting no problem (the scrolling last attempted proof only had harvester connections not the full node itself). I notice when there is high activity on the network it died. I rebooted the computer and it works again. Don't know what is going on- but i just got to a decently high number of plots with a lot of drives so i think the network hangs and kills my main node's attempted proof...Not too sure how to fix this and a NAS is a necessity since I don't have a major system.

**Comment by LNChia** [comment]
I have the same issue using Chia 1.1.7 software
2021-06-11T20:40:05.572 full_node full_node_server        : ERROR    Exception:  <class 'concurrent.futures._base.CancelledError'>, closing connection {'host': '125.123.124.169', 'port': 8444}. Traceback (most recent call last):
  File "chia\server\server.py", line 536, in api_call
  File "asyncio\tasks.py", line 435, in wait_for
concurrent.futures._base.CancelledError

**Comment by LNChia** [comment]
> I've had the same error (<class 'concurrent.futures._base.CancelledError'>) for days (since installing 1.1.6 I believe). I was seeing it in the logs each 8-11 seconds. Thanks to the comments above I believe I have it resolved.
> 
> Here's what I did. Not sure which of these steps actually fixed it.
> 
> 1. ~Forwarded port 8444 in my router to my full node PC~  (update: not needed)
> 2. Set logging level to DEBUG
> 3. Shut down Chia  (would not cleanly exit, had to close the window after waiting 20 seconds)
> 4. Terminated the remaining Chia running processes (harvester and wallet I believe)
> 5. Restarted the PC (Intel NUC)
> 6. I had a BIOS update to do, so I took this opportunity to do it.
> 7. The PC restarted, I started Chia, logged in, and the error hasn't been back since.
> 
> Hope this helps someone.



> I've had the same error (<class 'concurrent.futures._base.CancelledError'>) for days (since installing 1.1.6 I believe). I was seeing it in the logs each 8-11 seconds. Thanks to the comments above I believe I have it resolved.
> 
> Here's what I did. Not sure which of these steps actually fixed it.
> 
> 1. ~Forwarded port 8444 in my router to my full node PC~  (update: not needed)
> 2. Set logging level to DEBUG
> 3. Shut down Chia  (would not cleanly exit, had to close the window after waiting 20 seconds)
> 4. Terminated the remaining Chia running processes (harvester and wallet I believe)
> 5. Restarted the PC (Intel NUC)
> 6. I had a BIOS update to do, so I took this opportunity to do it.
> 7. The PC restarted, I started Chia, logged in, and the error hasn't been back since.
> 
> Hope this helps someone.


@InfiniteImp, 
how do you set item 2? Set logging Level to debug? 

Thanks
LN CHIA

**Comment by InfiniteImp** [comment]
> @InfiniteImp,
> how do you set item 2? Set logging Level to debug?
> 
> Thanks
> LN CHIA

Open the config.yaml file found in C:\Users\<username>\.chia\mainnet\config.
Look for farmer -> logging -> log_level  (it's close to the top)
Change its value to DEBUG
Save the file and restart Chia

**Comment by mrxzius** [comment]
Same Here... 
2021-06-14T14:39:29.522 full_node full_node_server        : ERROR    Exception:  <class 'concurrent.futures._base.CancelledError'>, closing connection {'host': '127.0.0.1', 'port': 8449}. Traceback (most recent call last):
  File "chia\server\server.py", line 536, in api_call
  File "asyncio\tasks.py", line 435, in wait_for
concurrent.futures._base.CancelledError


will try to delete db files....

**Comment by sonpython** [comment]
any update on this

I got alot of this kind of error when setup 100 harvester to 1 farmer


```
2021-06-17T15:44:41.158 farmer farmer_server              : DEBUG    -> harvester_handshake to peer 34.116.198.168 50b870eacf93dfb8144fc4b4e7bbeaafad6b458523788d9c5f06da95376743a2
2021-06-17T15:44:41.184 farmer farmer_server              : DEBUG    -> handshake to peer 34.125.230.251 50b870eacf93dfb8144fc4b4e7bbeaafad6b458523788d9c5f06da95376743a2
2021-06-17T15:44:41.185 farmer farmer_server              : ERROR    Exception Stack: Traceback (most recent call last):
  File "/root/chia-blockchain/chia/server/ws_connection.py", line 223, in inbound_handler
    message: Message = await self._read_one_message()
  File "/root/chia-blockchain/chia/server/ws_connection.py", line 376, in _read_one_message
    message: WSMessage = await self.ws.receive(30)
  File "/root/chia-blockchain/venv/lib/python3.8/site-packages/aiohttp/web_ws.py", line 406, in receive
    msg = await self._reader.read()
  File "/root/chia-blockchain/venv/lib/python3.8/site-packages/aiohttp/streams.py", line 644, in read
    return await super().read()
  File "/root/chia-blockchain/venv/lib/python3.8/site-packages/aiohttp/streams.py", line 604, in read
    await self._waiter
asyncio.exceptions.CancelledError

2021-06-17T15:44:41.185 farmer farmer_server              : DEBUG    Inbound_handler task cancelled
2021-06-17T15:44:41.185 farmer farmer_server              : INFO     Connection closed: 34.116.198.168, node id: 50b870eacf93dfb8144fc4b4e7bbeaafad6b458523788d9c5f06da95376743a2
2021-06-17T15:44:41.186 farmer chia.farmer.farmer         : INFO     peer disconnected {'host': '34.116.198.168', 'port': 8448}```

**Comment by malikmarcel** [comment]
Try this and write if it helpf!

RimBlock user post:
```
" Possible solution - At least in my case.

Symtoms:
New install - Win10 Pro - Chia 1.1.7
Error:
2021-06-10T09:45:39.787 full_node full_node_server : ERROR Exception: <class 'concurrent.futures._base.CancelledError'>, closing connection {'host': '127.0.0.1', 'port': 8449}. Traceback (most recent call last):
File "chia\server\server.py", line 536, in api_call
File "asyncio\tasks.py", line 435, in wait_for
concurrent.futures._base.CancelledError

Chia will not Sync

Reason:
Seems Chia has not setup any outgoing firewall rules. This means, if your port forwarding / uPNP is working, you can receive messages fromt he Chia network but you cannot send any messages out.

Resolution (assuming you are using stock Windows Defender for your Firewall):
Type "Firewall" in the windows search box (bottom left of your desktop).

Choose Windows Defender Firewall --> select Advanced settings in the next window that opens.
Select "Outbound Rules" and look to see if Start_Farmer.exe (Chia Farmer) or Start_Full_Node.exe (Chia Node) are listed.
If they are listed then this is probably not the source of your issue.

If they are not listed then add rules for them.
Note: You will need to change the items in bold below depending on thw Chia version and your login acocunt.

Select "New Rule" from the menu on the right.
Leave it as Program --> Next --> Program Path --> browse --> ""C:\Users**[YOUR ACCOUNT NAME]**\AppData\Local\chia-blockchain\app-1.1.7\resources\app.asar.unpacked\daemon\start_farmer.exe""
Select "Allow the connection"
Check all three network types
Give the rule a name
Finish
Do the same again for start_full_node.exe

Hopefully this will then allow your Chia client to sync.... slowly.

If this does not resolve your issue then I am sorry but I do not know a solution for you as this worked for me.

@hoffmang9 : If someone can please do a quick sanity check of the Windows firewall setup of the latest 1.1.7 package it may help resolve a fair amount of noise.

This install was on a clean Windows 10 Pro Machine with only the Chia Software installed afterwards.

A previous install on Windows10 Pro machine which had Norton as its firewall had no issues.
"
```

**Comment by struxoje** [comment]
I can reproduce with Ubuntu 20.04 and Chia version 1.2.2

2021-07-15T00:11:11.572 full_node full_node_server        : ERROR    Exception:  <class 'concurrent.futures._base.CancelledError'>, closing connection {'host': '138.255.144.251', 'port': 8444}. Traceback (most recent call last):
  File "/srv/chia/chia-blockchain/chia/server/server.py", line 533, in api_call
    response: Optional[Message] = await asyncio.wait_for(wrapped_coroutine(), timeout=timeout)
  File "/usr/lib/python3.7/asyncio/tasks.py", line 435, in wait_for
    await waiter
concurrent.futures._base.CancelledError
