### ISSUE TITLE
[BUG] chia wallet show: Exception from 'wallet' - FileNotFoundError chia-blockchain/src/util/english.txt

### ISSUE THREAD

**Issue by actuallymentor** [Chia-Network/chia-blockchain#2252]
**Describe the bug**

When running `chia wallet show` I receive the error `{'error': '2', 'success': False}`. In `debug.log` I see:

```shell
07:58:32.723 wallet src.rpc.rpc_server         : WARNING  Error while handling message: Traceback (most recent call last):
  File "/home/me/chia-blockchain/src/rpc/rpc_server.py", line 81, in inner
  File "/home/me/chia-blockchain/src/rpc/wallet_rpc_api.py", line 173, in get_public_keys
  File "/home/me/chia-blockchain/src/util/keychain.py", line 248, in get_all_private_keys
  File "/home/me/chia-blockchain/src/util/keychain.py", line 47, in bytes_to_mnemonic
  File "/home/me/chia-blockchain/src/util/keychain.py", line 33, in bip39_word_list
  File "/home/me/chia-blockchain/venv/lib/python3.8/site-packages/pkg_resources/__init__.py", line 1156, in resource_string
    return get_provider(package_or_requirement).get_resource_string(
  File "/home/me/chia-blockchain/venv/lib/python3.8/site-packages/pkg_resources/__init__.py", line 1401, in get_resource_string
    return self._get(self._fn(self.module_path, resource_name))
  File "/home/me/chia-blockchain/venv/lib/python3.8/site-packages/pkg_resources/__init__.py", line 1616, in _get
    with open(path, 'rb') as stream:
FileNotFoundError: [Errno 2] No such file or directory: '/home/me/chia-blockchain/src/util/english.txt'
```

**To Reproduce**

1. Use CLI
1. Update to Chia `1.0.5`
2. Type `chia wallet show`

**Expected behavior**
Show wallet data

**Additional context**
Farmer seems to run fine.

**Comment by gitsang** [comment]
Check if you have file in `/home/me/chia-blockchain/src/util/english.txt`
If you move chia-blockchain file path, it may cause some problem.
Re-init chia maybe can help.

```
chia stop all
rm ~/.chia/mainnet -fr
chia init
chia start all
```
