### ISSUE TITLE
[BUG] Won't start without ipv6 stack with default config

### ISSUE THREAD

**Issue by n0izn0iz** [Chia-Network/chia-blockchain#2265]
**Describe the bug**

trying to run `chia-blockchain` without an ipv6 stack doesn't work
I did not find a way to override the bound address in the config
EDIT: [config workaround that works for me](https://github.com/Chia-Network/chia-blockchain/issues/2265#issuecomment-826015294)
```
/usr/share/chia-blockchain/app.asar.unpacked/daemon
true
Error loading config - using defaults
startUrl file:///usr/share/chia-blockchain/app.asar/build/renderer/index.html
/usr/share/chia-blockchain/app.asar.unpacked/daemon
true
/usr/share/chia-blockchain/app.asar.unpacked/daemon
true
Running python executable: 
child process success
(node:16229) electron: The default of contextIsolation is deprecated and will be changing from false to true in a future release of Electron.  See https://github.com/electron/electron/issues/23506 for more information
No cert
Have cert
stderr: Traceback (most recent call last):
  File "chia/daemon/server.py", line 954, in <module>
  File "chia/daemon/server.py", line 950, in main
  File "chia/daemon/server.py", line 944, in run_daemon
  File "asyncio/base_events.py", line 616, in run_until_complete
  File "chia/daemon/server.py", line 936, in async_run_daemon
  File "chia/daemon/server.py", line 137, in start
  File "websockets/server.py", line 965, in __await_impl__
  File "asyncio/base_events.py", line 1463, in create_server
OSError: [Errno 99] error while attempting to bind on address ('::1', 55400, 0, 0): cannot assign requested address
[16275] Failed to execute script server
closing code: 255
```

nothing is using the port as shown by:
```
❯ sudo ss -tulpn | grep :55400

```

**To Reproduce**

1. Disable ipv6 (https://wiki.archlinux.org/index.php/IPv6#Disable_IPv6)
2. Run `chia-blockchain`

**Expected behavior**
Work, or at least allow to specify an ipv4 address to bind to

**Screenshots**
![Screenshot from 2021-04-21 13-27-45](https://user-images.githubusercontent.com/7917064/115546934-efb74100-a2a5-11eb-8fff-8a6e06bc4e54.png)

**Desktop (please complete the following information):**

- OS: Linux
- OS Version/Flavor: 5.11.13-arch1-1/Arch

**Comment by iobond** [comment]
the same

**Comment by ferdiina** [comment]
the same
when i disable the ipv6 stack
`(venv) [root@centos8 chia-blockchain]# chia start all
Daemon not started yet
Starting daemon
Traceback (most recent call last):
  File "/opt/chia-blockchain/venv/bin/chia", line 33, in <module>
    sys.exit(load_entry_point('chia-blockchain', 'console_scripts', 'chia')())
  File "/opt/chia-blockchain/chia/cmds/chia.py", line 77, in main
    cli()  # pylint: disable=no-value-for-parameter
  File "/opt/chia-blockchain/venv/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/opt/chia-blockchain/venv/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/opt/chia-blockchain/venv/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/chia-blockchain/venv/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/chia-blockchain/venv/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/opt/chia-blockchain/venv/lib/python3.7/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/opt/chia-blockchain/chia/cmds/chia.py", line 60, in run_daemon_cmd
    asyncio.get_event_loop().run_until_complete(async_run_daemon(ctx.obj["root_path"]))
  File "/usr/local/lib/python3.7/asyncio/base_events.py", line 587, in run_until_complete
    return future.result()
  File "/opt/chia-blockchain/chia/daemon/server.py", line 944, in async_run_daemon
    await ws_server.start()
  File "/opt/chia-blockchain/chia/daemon/server.py", line 145, in start
    ssl=self.ssl_context,
  File "/opt/chia-blockchain/venv/lib/python3.7/site-packages/websockets/server.py", line 965, in __await_impl__
    server = await self._create_server()
  File "/usr/local/lib/python3.7/asyncio/base_events.py", line 1389, in create_server
    % (sa, err.strerror.lower())) from None
OSError: [Errno 99] error while attempting to bind on address ('::1', 55400, 0, 0): cannot assign requested address
Daemon not started yet
Failed to create the chia daemon`

**Comment by frederikheld** [comment]
This seems to be a known issue in some way. `chia-docker` shows the workaround: https://github.com/Chia-Network/chia-docker/blob/main/entrypoint.sh

Line 20:
```sh
sed -i 's/localhost/127.0.0.1/g' ~/.chia/mainnet/config/config.yaml
```
Replacing all references to `localhost` with it's IPv4 loopback address in `config.yml` prevents it being resolved to IPv6 `::1`.

It fixed the issue for me.

One question remains: is it a bug or is it a feature?
