### ISSUE TITLE
How to fixs RuntimeError: bad allocation

### ISSUE THREAD

**Issue by vander777** [Chia-Network/chia-blockchain#2272]
Plot size is: 32
Buffer size is: 22000MiB
Using 128 buckets
Using 12 threads of stripe size 65536

Starting phase 1/4: Forward Propagation into tmp files... Wed Apr 21 14:38:33 2021
Computing table 1
F1 complete, time: 155.283 seconds. CPU (166.19%) Wed Apr 21 14:41:08 2021
Computing table 2
Caught plotting error: bad allocation
[13156] Failed to execute script chia
Traceback (most recent call last):
  File "chia\cmds\chia.py", line 80, in <module>
  File "chia\cmds\chia.py", line 76, in main
  File "click\core.py", line 829, in __call__
  File "click\core.py", line 782, in main
  File "click\core.py", line 1259, in invoke
  File "click\core.py", line 1259, in invoke
  File "click\core.py", line 1066, in invoke
  File "click\core.py", line 610, in invoke
  File "click\decorators.py", line 21, in new_func
  File "chia\cmds\plots.py", line 134, in create_cmd
  File "chia\plotting\create_plots.py", line 176, in create_plots
RuntimeError: bad allocation

**Comment by botanegg** [comment]
Just try to use smaller buffer size (default size in GUI is 3390MiB)

**Comment by vander777** [comment]
This is 4 plots in  paraller end two of them stoping with error as mentioned on 1%.  Razen 7 4800h 32gb  ddr4 3200mhz 1.84 Tb nwme  it should do 4 i paraller easy.

**Comment by botanegg** [comment]
4*22GiB = 88GiB buffers on your 32GiB machine

**Comment by vander777** [comment]
THX i was thinking that if am doing ploting in Parallel i nedd to multiply Ram usage by plot itd..THX

**Comment by jkkj1630** [comment]
i got same question, my plot task stopped,but now,i have more free memory, can those tasks that stopped work continue?

**Comment by hoffmang9** [comment]
https://github.com/Chia-Network/chia-blockchain/wiki/FAQ#my-plotting-attempt-ended-with-runtimeerror-bad-allocation
