### ISSUE TITLE
Caught plotting error: bad allocation

### ISSUE THREAD

**Issue by colin4k** [Chia-Network/chia-blockchain#2285]
I got a problem below, why?

Starting plotting progress into temporary dirs: h:\ and h:\
ID: 58522ffcbceb26771ff3f0903673fadabd5290f95014680eed3825a98214c302
Plot size is: 32
Buffer size is: 8000MiB
Using 128 buckets
Using 2 threads of stripe size 65536

Starting phase 1/4: Forward Propagation into tmp files... Wed Apr 21 23:46:14 2021
Computing table 1
F1 complete, time: 100.035 seconds. CPU (175.53%) Wed Apr 21 23:47:54 2021
Computing table 2
Caught plotting error: bad allocation
Traceback (most recent call last):
  File "chia\cmds\chia.py", line 80, in <module>
  File "chia\cmds\chia.py", line 76, in main
  File "click\core.py", line 829, in __call__
  File "click\core.py", line 782, in main
  File "click\core.py", line 1259, in invoke
  File "click\core.py", line 1259, in invoke
  File "click\core.py", line 1066, in invoke
  File "click\core.py", line 610, in invoke
  File "click\decorators.py", line 21, in new_func
  File "chia\cmds\plots.py", line 134, in create_cmd
  File "chia\plotting\create_plots.py", line 176, in create_plots
RuntimeError: bad allocation
[20624] Failed to execute script chia

**Comment by botanegg** [comment]
Similar to #2272
Make sure you have enough RAM and just use smaller buffer size

**Comment by colin4k** [comment]
> 
> 
> Similar to #2272
> Make sure you have enough RAM and just use smaller buffer size

I have 64G ram.

**Comment by botanegg** [comment]
Do you use "Plot in parallel"?
How many parallel plotters did you run?

**Comment by colin4k** [comment]
> 
> 
> Do you use "Plot in parallel"?
> How many parallel plotters did you run?

When I got the problem I just runned 1, now I run 3 and it's ok.
