### ISSUE TITLE
[BUG]  RuntimeError: bad allocation

### ISSUE THREAD

**Issue by chchia** [Chia-Network/chia-blockchain#2336]
**Describe the bug**
My system with 20GB RAM, 6c12t CPU, 2TB SSD
whenever plot parallelly for more than 2 k32, i will receive below error.c

in previous version 1.0.5 when this happen i can just delete it.

but with 1.1.0 the delete had become gray.

![image](https://user-images.githubusercontent.com/1291771/115654416-ae856680-a363-11eb-9f43-e8c76d2dc66e.png)

i cannot delete error job anymore.

**Desktop (please complete the following information):**

- OS: Windows 10
- CPU: 10400f 6T12C 20GB ram.

**Additional context**

copy from log

Starting phase 1/4: Forward Propagation into tmp files... Thu Apr 22 09:52:47 2021
Computing table 1
F1 complete, time: 1963.06 seconds. CPU (32.19%) Thu Apr 22 10:25:31 2021
Computing table 2
Caught plotting error: bad allocation
[1292] Failed to execute script chia
Traceback (most recent call last):
  File "chia\cmds\chia.py", line 81, in <module>
  File "chia\cmds\chia.py", line 77, in main
  File "click\core.py", line 829, in __call__
  File "click\core.py", line 782, in main
  File "click\core.py", line 1259, in invoke
  File "click\core.py", line 1259, in invoke
  File "click\core.py", line 1066, in invoke
  File "click\core.py", line 610, in invoke
  File "click\decorators.py", line 21, in new_func
  File "chia\cmds\plots.py", line 135, in create_cmd
  File "chia\plotting\create_plots.py", line 176, in create_plots
RuntimeError: bad allocation

**Comment by hoffmang9** [comment]
Bad allocation is a RAM problem on your machine. The delete button was intentionally disabled for now in Windows.

**Comment by chchia** [comment]
so how can i delete broken plot?
