### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by CXW0504** [Chia-Network/chia-blockchain#2348]
**Describe the bug**
 Error -3 while decompressing data: incorrect header check 
 'NoneType' object has no attribute 'tx_store'

**To Reproduce**
   1.login

**Expected behavior**
login sucess

**Comment by eugene-manaev** [comment]
Here's a stack trace I found at ~/.chia/mainnet/log/debug.log

Displayed error is exactly the same - incorrect header check

```
2021-05-02T01:19:01.416 wallet chia.rpc.rpc_server        : WARNING  Error while handling message: Traceback (most recent call last):
  File "chia/rpc/rpc_server.py", line 212, in safe_handle
  File "chia/rpc/rpc_server.py", line 203, in ws_api
  File "chia/rpc/wallet_rpc_api.py", line 186, in get_public_keys
  File "chia/util/keychain.py", line 248, in get_all_private_keys
  File "chia/util/keychain.py", line 47, in bytes_to_mnemonic
  File "chia/util/keychain.py", line 33, in bip39_word_list
  File "pkg_resources/__init__.py", line 1155, in resource_string
  File "pkg_resources/__init__.py", line 1401, in get_resource_string
  File "pkg_resources/__init__.py", line 1570, in _get
  File "PyInstaller/loader/pyimod03_importers.py", line 351, in get_data
  File "PyInstaller/loader/pyimod02_archive.py", line 332, in extract
zlib.error: Error -3 while decompressing data: incorrect header check
```

**Comment by some27** [comment]
same here

**Comment by some27** [comment]
guys,  found restarting the mac can solve this bug

**Comment by clcmusic** [comment]
@some27 thank you! thank worked

**Comment by xiaoduola666** [comment]
我在1.2  Windows上也遇到了这个问题，尝试重启依然没有解决
