### ISSUE TITLE
[BUG] Caught plotting error: Matches do not match with number of write entries

### ISSUE THREAD

**Issue by w780215** [Chia-Network/chia-blockchain#2354]
**Describe the bug**
I'm runing the lastest chia program which version is 1.1.0.
When I start to plot it, that always shows the error message in below:

Caught plotting error: Matches do not match with number of write entries 4294987283 4294987341
[2752] Failed to execute script chia
Traceback (most recent call last):
  File "chia\cmds\chia.py", line 81, in <module>
  File "chia\cmds\chia.py", line 77, in main
  File "click\core.py", line 829, in __call__
  File "click\core.py", line 782, in main
  File "click\core.py", line 1259, in invoke
  File "click\core.py", line 1259, in invoke
  File "click\core.py", line 1066, in invoke
  File "click\core.py", line 610, in invoke
  File "click\decorators.py", line 21, in new_func
  File "chia\cmds\plots.py", line 135, in create_cmd
  File "chia\plotting\create_plots.py", line 176, in create_plots
RuntimeError: Unknown exception

**Screenshots**
![image](https://user-images.githubusercontent.com/83000707/115674825-9f60e180-a380-11eb-803b-720e87e5323b.png)

**Desktop:**

- OS: Window
- OS Version/Flavor: Window 10 1909
- CPU: AMD X5950
- RAM: 32 GB
- SSD: 2TB
- HDD:14TB

So, how can i fix it?

**Comment by hoffmang9** [comment]
This is usually a hardware problem with the storage or your RAM>

**Comment by w780215** [comment]
> This is usually a hardware problem with the storage or your RAM>

Thanks for your advice, I will try it.
