### ISSUE TITLE
[BUG] Harvester crashes with soccket error after couple of hours

### ISSUE THREAD

**Issue by SebastianMetzger** [Chia-Network/chia-blockchain#2356]
**Describe the bug**
Sometimes I find one my harvesters not talking to the farmer anymore.
This happened now several times on different machines in the last couple of days. Including Ubunut Server, Ubuntu Desktop and a raspberry pie with raspbian.
I updated to chia 1.0.5 on all devieces over the last couple of days.

**To Reproduce**
Run the harvester and wait couple of days/hours until it stops connecting to the farmer

**Expected behavior**
The harvester to continue harvesting :) 
When such an error occurs, it should at least restart itself. 
Will probably write a script in the short term that restarts the harvester regularly.

**Screenshots**
07:19:29.127 daemon chia.daemon.server         : INFO     Websocket exception. Closing websocket with chia_harvester code = 1006 (connection closed abnormally [internal]), no reason Traceback (most recent call last):
  File "/home/sebastian/chia-blockchain/venv/lib/python3.8/site-packages/websockets/protocol.py", line 827, in transfer_data
    message = await self.read_message()
  File "/home/sebastian/chia-blockchain/venv/lib/python3.8/site-packages/websockets/protocol.py", line 895, in read_message
    frame = await self.read_data_frame(max_size=self.max_size)
  File "/home/sebastian/chia-blockchain/venv/lib/python3.8/site-packages/websockets/protocol.py", line 971, in read_data_frame
    frame = await self.read_frame(max_size)
  File "/home/sebastian/chia-blockchain/venv/lib/python3.8/site-packages/websockets/protocol.py", line 1047, in read_frame
    frame = await Frame.read(
  File "/home/sebastian/chia-blockchain/venv/lib/python3.8/site-packages/websockets/framing.py", line 105, in read
    data = await reader(2)
  File "/usr/lib/python3.8/asyncio/streams.py", line 721, in readexactly
    raise exceptions.IncompleteReadError(incomplete, n)
asyncio.exceptions.IncompleteReadError: 0 bytes read on a total of 2 expected bytes

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/sebastian/chia-blockchain/chia/daemon/server.py", line 165, in safe_handle
    async for message in websocket:
  File "/home/sebastian/chia-blockchain/venv/lib/python3.8/site-packages/websockets/protocol.py", line 439, in __aiter__
    yield await self.recv()
  File "/home/sebastian/chia-blockchain/venv/lib/python3.8/site-packages/websockets/protocol.py", line 509, in recv
    await self.ensure_open()
  File "/home/sebastian/chia-blockchain/venv/lib/python3.8/site-packages/websockets/protocol.py", line 803, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedError: code = 1006 (connection closed abnormally [internal]), no reason

**Desktop (please complete the following information):**

- OS: Ubuntu Desktop, Ubuntu Server, Raspbian
- OS Version/Flavor: Ubuntu 20.04., Raspbian 64bit
- CPU: Different

**Additional context**
I can retrieve more info from the different machines, but as it seems to appear radomly everywhere, might be a genearal thing?
Happens with LAN connection at home, data center LAN and WiFi at home

**Comment by hoffmang9** [comment]
You appear to be using a very old version as aiter is no longer part of the package?

**Comment by SebastianMetzger** [comment]
Just checked the machine where the error occured and it should be on 1.0.4
Is this something that could be caused by old dependencies?
Will upgrade to the latest release over the weekend

**Comment by Hindalen** [comment]
I experience same issue.. im on windows running chia 1.0.5

**Comment by SebastianMetzger** [comment]
Actually happened again tonight on a harvester I upgraded to 1.1.1 this weekend.
This is Ubuntu Desktop Laptop, which is on wifi and internet sometimes not 100% stable.
Will probably set up wired LAN.
```
021-04-26T01:42:47.284 daemon chia.daemon.server         : INFO     Websocket exception. Closing websocket with chia_harvester code = 1006 (connection closed abnormally [internal]), no reason Traceback (most recent call last):
  File "/home/sebastian/chia-blockchain/venv/lib/python3.8/site-packages/websockets/protocol.py", line 827, in transfer_data
    message = await self.read_message()
  File "/home/sebastian/chia-blockchain/venv/lib/python3.8/site-packages/websockets/protocol.py", line 895, in read_message
    frame = await self.read_data_frame(max_size=self.max_size)
  File "/home/sebastian/chia-blockchain/venv/lib/python3.8/site-packages/websockets/protocol.py", line 971, in read_data_frame
    frame = await self.read_frame(max_size)
  File "/home/sebastian/chia-blockchain/venv/lib/python3.8/site-packages/websockets/protocol.py", line 1047, in read_frame
    frame = await Frame.read(
  File "/home/sebastian/chia-blockchain/venv/lib/python3.8/site-packages/websockets/framing.py", line 105, in read
    data = await reader(2)
  File "/usr/lib/python3.8/asyncio/streams.py", line 721, in readexactly
    raise exceptions.IncompleteReadError(incomplete, n)
asyncio.exceptions.IncompleteReadError: 0 bytes read on a total of 2 expected bytes

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/sebastian/chia-blockchain/chia/daemon/server.py", line 167, in safe_handle
    async for message in websocket:
  File "/home/sebastian/chia-blockchain/venv/lib/python3.8/s021-04-26T01:42:47.284 daemon chia.daemon.server         : INFO     Websocket exception. Closing websocket with chia_harvester code = 1006 (connection closed abnormally [internal]), no reason Traceback (most recent call last):
  File "/home/sebastian/chia-blockchain/venv/lib/python3.8/site-packages/websockets/protocol.py", line 827, in transfer_data
    message = await self.read_message()
  File "/home/sebastian/chia-blockchain/venv/lib/python3.8/site-packages/websockets/protocol.py", line 895, in read_message
    frame = await self.read_data_frame(max_size=self.max_size)
  File "/home/sebastian/chia-blockchain/venv/lib/python3.8/site-packages/websockets/protocol.py", line 971, in read_data_frame
    frame = await self.read_frame(max_size)
  File "/home/sebastian/chia-blockchain/venv/lib/python3.8/site-packages/websockets/protocol.py", line 1047, in read_frame
    frame = await Frame.read(
  File "/home/sebastian/chia-blockchain/venv/lib/python3.8/site-packages/websockets/framing.py", line 105, in read
    data = await reader(2)
  File "/usr/lib/python3.8/asyncio/streams.py", line 721, in readexactly
    raise exceptions.IncompleteReadError(incomplete, n)
asyncio.exceptions.IncompleteReadError: 0 bytes read on a total of 2 expected bytes

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/sebastian/chia-blockchain/chia/daemon/server.py", line 167, in safe_handle
    async for message in websocket:
  File "/home/sebastian/chia-blockchain/venv/lib/python3.8/site-packages/websockets/protocol.py", line 439, in __aiter__
    yield await self.recv()
  File "/home/sebastian/chia-blockchain/venv/lib/python3.8/site-packages/websockets/protocol.py", line 509, in recv
    await self.ensure_open()
  File "/home/sebastian/chia-blockchain/venv/lib/python3.8/site-packages/websockets/protocol.py", line 803, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedError: code = 1006 (connection closed abnormally [internal]), no reason
ite-packages/websockets/protocol.py", line 439, in __aiter__
    yield await self.recv()
  File "/home/sebastian/chia-blockchain/venv/lib/python3.8/site-packages/websockets/protocol.py", line 509, in recv
    await self.ensure_open()
  File "/home/sebastian/chia-blockchain/venv/lib/python3.8/site-packages/websockets/protocol.py", line 803, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedError: code = 1006 (connection closed abnormally [internal]), no reason

```

**Comment by Hindalen** [comment]
I get this error after upgrading to 1.1.2, why is this happening? Full reinstall did not help, (Delete of all chia files)..

**Comment by SebastianMetzger** [comment]
Happened again tonight on a freshly installed rasperry pie harvester with 1.1.2 release, which was also on wifi.

**Comment by jamierf** [comment]
I'm getting the same issue.   harvester version 1.1.15 running on ubuntu.   Happens roughly every 5-6 hours

(venv) root@chia:~/chia-blockchain# tail  ~/.chia/mainnet/log/debug.log 
  File "/root/chia-blockchain/chia/daemon/server.py", line 172, in safe_handle
    async for message in websocket:
  File "/root/chia-blockchain/venv/lib/python3.8/site-packages/websockets/protocol.py", line 439, in __aiter__
    yield await self.recv()
  File "/root/chia-blockchain/venv/lib/python3.8/site-packages/websockets/protocol.py", line 509, in recv
    await self.ensure_open()
  File "/root/chia-blockchain/venv/lib/python3.8/site-packages/websockets/protocol.py", line 803, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedError: code = 1006 (connection closed abnormally [internal]), no reason

**Comment by rm-killer** [comment]
Same here. Some time even restarting the harvester dosen't work. 1.1.15
Just resetting pc will work. No one found the solutions yet?

**Comment by jamierf** [comment]
my "fix" is a cronjob that calls a script with chia stop harvester and then chia start harvester every 30 minutes  so far that's been working.

**Comment by aarcro** [comment]
Anyone have better ideas? I'm running my full_node, farmer, wallet, harvester on a Pi4 (Chia 1.1.5):

Linux ubuntu 5.4.0-1034-raspi #37-Ubuntu SMP PREEMPT Mon Apr 12 23:14:49 UTC 2021 aarch64 aarch64 aarch64 GNU/Linux

And seeing a constant flood of these

```
2021-05-14T14:35:05.609 daemon chia.daemon.server         : ERROR    Unexpected exception trying to send to websocket: code = 1006 (connection closed abnormally [internal]), no reason Traceback (most recent call last):
  File "/home/chia/chia-blockchain/venv/lib/python3.8/site-packages/websockets/protocol.py", line 827, in transfer_data
    message = await self.read_message()
  File "/home/chia/chia-blockchain/venv/lib/python3.8/site-packages/websockets/protocol.py", line 895, in read_message
    frame = await self.read_data_frame(max_size=self.max_size)
  File "/home/chia/chia-blockchain/venv/lib/python3.8/site-packages/websockets/protocol.py", line 971, in read_data_frame
    frame = await self.read_frame(max_size)
  File "/home/chia/chia-blockchain/venv/lib/python3.8/site-packages/websockets/protocol.py", line 1047, in read_frame
    frame = await Frame.read(
  File "/home/chia/chia-blockchain/venv/lib/python3.8/site-packages/websockets/framing.py", line 105, in read
    data = await reader(2)
  File "/usr/lib/python3.8/asyncio/streams.py", line 721, in readexactly
    raise exceptions.IncompleteReadError(incomplete, n)
asyncio.exceptions.IncompleteReadError: 0 bytes read on a total of 2 expected bytes

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/chia/chia-blockchain/chia/daemon/server.py", line 187, in safe_handle
    await socket.send(response)
  File "/home/chia/chia-blockchain/venv/lib/python3.8/site-packages/websockets/protocol.py", line 555, in send
    await self.ensure_open()
  File "/home/chia/chia-blockchain/venv/lib/python3.8/site-packages/websockets/protocol.py", line 803, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedError: code = 1006 (connection closed abnormally [internal]), no reason
```

I'm not seeing anything impacted though? harvesters on 3 other nodes are still getting and responding to challenges. Even this node is still logging:

```
20911:2021-05-14T14:34:26.314 harvester chia.harvester.harvester: INFO     1 plots were eligible for farming 0a943edc95... Found 0 proofs. Time: 0.10383 s. Total 130 plots
```

How can we tell what websocket is disconnecting from `daemon chia.daemon.server` ?

I'm a python dev and can debug it with a bit of a hint.

**Comment by SebastianMetzger** [comment]
Actually just had the issue, while I also still had the terminal open.
Got this on stdout/stderr:
"malloc(): corrupted top size"

Maybe helps in debugging

**Comment by laszlojanosek** [comment]
Same, recurring issue after I migrated to a new server (I copied over DB files prior to synchronization). 
- Ubuntu 20.04, chia version 1.1.6
- i7 11700/64GB mem, SATA drives over SATA, SATA drives over SAS controllers, few USB3 external drives. ~200TB capacity
- chia watchdog is monitoring the debug.log

I read somewhere a similar issue happened when moving plots around. I am currently migrating plot directories from NTFS to ext4 based drives. I do my best to not stress the farmer, carefully redirecting the plot directory when the copy completed.

When a segfault occurs the only way to solve it was to restart the full node. I did not succeed by restarting the harvester only. No difference if I use GUI or CLI only, the issue comes back almost daily.

kernel ring buffer entry (kern.log)
-------------------------------------------

May 23 18:48:56 chiafarm01 kernel: [112454.372864] chia_harvester[125923]: segfault at 7f22a0137f7b ip 00007f22eafbe922 sp 00007f22dbff17f8 error 4 in chiapos.cpython-38-x86_64-linux-gnu.so[7f22eaf51000+b8000]
May 24 16:51:38 chiafarm01 kernel: [191817.415487] chia_harvester[183780]: segfault at 7ff32812e105 ip 00007ff35b4c5922 sp 00007ff3593fb7f8 error 4 in chiapos.cpython-38-x86_64-linux-gnu.so[7ff35b458000+b8000]
May 25 05:57:48 chiafarm01 kernel: [238987.616043] chia_harvester[335624]: segfault at 7f021c02ace5 ip 00007f0279386922 sp 00007f02762ba7f8 error 4 in chiapos.cpython-38-x86_64-linux-gnu.so[7f0279319000+b8000]
May 26 09:32:54 chiafarm01 kernel: [338293.667638] chia_harvester[354731]: segfault at 7f17a802e877 ip 00007f17cd90e922 sp 00007f1785fed7f8 error 4 in chiapos.cpython-38-x86_64-linux-gnu.so[7f17cd8a1000+b8000]
May 27 16:30:49 chiafarm01 kernel: [449769.093260] chia_harvester[443581]: segfault at 7f0044112ae5 ip 00007f00c75e1922 sp 00007f0059fed7f8 error 4 in chiapos.cpython-38-x86_64-linux-gnu.so[7f00c7574000+b8000]
[May28 04:57] chia_harvester[523473]: segfault at 7f613813b213 ip 00007f614985c922 sp 00007f61027ee7f8 error 4 in chiapos.cpython-38-x86_64-linux-gnu.so[7f61497ef000+b8000]
[  +0.000006] Code: d9 48 8b 7c 24 c8 49 89 d3 0f bd c0 83 f0 1f 8d 74 c8 29 e9 fb fc ff ff 48 85 c9 0f 84 5a ff ff ff 48 8d 5a 08 48 89 54 24 e0 <0f> b6 74 0a ff 48 89 5c 24 e8 48 83 f9 07 0f 86 5a 02 00 00 4c 8d

chia debug.log
--------------------

2021-05-28T04:57:16.844 daemon __main__                   : INFO     Websocket exception. Closing websocket with chia_harvester code = 1006 (connection closed abnormally [internal]), no reason Traceback (most recent call last):
  File "/home/lacmac/chia-blockchain/venv/lib/python3.8/site-packages/websockets/protocol.py", line 827, in transfer_data
    message = await self.read_message()
  File "/home/lacmac/chia-blockchain/venv/lib/python3.8/site-packages/websockets/protocol.py", line 895, in read_message
    frame = await self.read_data_frame(max_size=self.max_size)
  File "/home/lacmac/chia-blockchain/venv/lib/python3.8/site-packages/websockets/protocol.py", line 971, in read_data_frame
    frame = await self.read_frame(max_size)
  File "/home/lacmac/chia-blockchain/venv/lib/python3.8/site-packages/websockets/protocol.py", line 1047, in read_frame
    frame = await Frame.read(
  File "/home/lacmac/chia-blockchain/venv/lib/python3.8/site-packages/websockets/framing.py", line 105, in read
    data = await reader(2)
  File "/usr/lib/python3.8/asyncio/streams.py", line 721, in readexactly
    raise exceptions.IncompleteReadError(incomplete, n)
asyncio.exceptions.IncompleteReadError: 0 bytes read on a total of 2 expected bytes

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "../chia/daemon/server.py", line 172, in safe_handle
    async for message in websocket:
  File "/home/lacmac/chia-blockchain/venv/lib/python3.8/site-packages/websockets/protocol.py", line 439, in __aiter__
    yield await self.recv()
  File "/home/lacmac/chia-blockchain/venv/lib/python3.8/site-packages/websockets/protocol.py", line 509, in recv
    await self.ensure_open()
  File "/home/lacmac/chia-blockchain/venv/lib/python3.8/site-packages/websockets/protocol.py", line 803, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedError: code = 1006 (connection closed abnormally [internal]), no reason

**Comment by laszlojanosek** [comment]
just happened again, this time only few hours later:
[May28 09:35] chia_harvester[610333]: segfault at 7f485c03848b ip 00007f48c30d8922 sp 00007f4891fed7f8 error 4 in chiapos.cpython-38-x86_64-linux-gnu.so[7f48c306b000+b8000]

**Comment by laszlojanosek** [comment]
at the time of the crash strace shows:
14:05:13.260185 +++ killed by SIGSEGV (core dumped) +++

the crash file gdb output is:

[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `chia_harvester                                                                '.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007ff35b4c5922 in FSE_decompress_usingDTable () from /home/lacmac/chia-blockchain/venv/lib/python3.8/site-packages/chiapos.cpython-38-x86_64-linux-gnu.so
[Current thread is 1 (Thread 0x7ff359409700 (LWP 183780))]


and the backtrace:

#0  0x00007ff35b4c5922 in FSE_decompress_usingDTable () from /home/lacmac/chia-blockchain/venv/lib/python3.8/site-packages/chiapos.cpython-38-x86_64-linux-gnu.so
#1  0x00007ff35b4ad4e3 in ?? () from /home/lacmac/chia-blockchain/venv/lib/python3.8/site-packages/chiapos.cpython-38-x86_64-linux-gnu.so
#2  0x00007ff35b49ab42 in ?? () from /home/lacmac/chia-blockchain/venv/lib/python3.8/site-packages/chiapos.cpython-38-x86_64-linux-gnu.so
#3  0x00007ff35b49f8d4 in ?? () from /home/lacmac/chia-blockchain/venv/lib/python3.8/site-packages/chiapos.cpython-38-x86_64-linux-gnu.so
#4  0x00007ff35b49667e in ?? () from /home/lacmac/chia-blockchain/venv/lib/python3.8/site-packages/chiapos.cpython-38-x86_64-linux-gnu.so
#5  0x00007ff35b4b0297 in ?? () from /home/lacmac/chia-blockchain/venv/lib/python3.8/site-packages/chiapos.cpython-38-x86_64-linux-gnu.so
#6  0x00000000005f2fb9 in PyCFunction_Call ()
#7  0x00000000005f3446 in _PyObject_MakeTpCall ()
#8  0x000000000050aa8b in ?? ()
#9  0x000000000056ef97 in _PyEval_EvalFrameDefault ()
#10 0x000000000056822a in _PyEval_EvalCodeWithName ()
#11 0x00000000005f6033 in _PyFunction_Vectorcall ()
#12 0x00000000005f2b87 in PyObject_Call ()
#13 0x000000000056b7b0 in _PyEval_EvalFrameDefault ()
#14 0x00000000005f5e56 in _PyFunction_Vectorcall ()
#15 0x000000000056a136 in _PyEval_EvalFrameDefault ()
#16 0x00000000005f5e56 in _PyFunction_Vectorcall ()
#17 0x00000000005f2b87 in PyObject_Call ()
#18 0x000000000056b7b0 in _PyEval_EvalFrameDefault ()
#19 0x00000000005f5e56 in _PyFunction_Vectorcall ()
#20 0x000000000056a136 in _PyEval_EvalFrameDefault ()
#21 0x00000000005f5e56 in _PyFunction_Vectorcall ()
#22 0x000000000056a136 in _PyEval_EvalFrameDefault ()
#23 0x00000000005f5e56 in _PyFunction_Vectorcall ()
#24 0x000000000050a33c in ?? ()
#25 0x00000000005f2b87 in PyObject_Call ()
#26 0x0000000000654fbc in ?? ()
#27 0x0000000000674aa8 in ?? ()
#28 0x00007ff35e4a0609 in start_thread (arg=<optimized out>) at pthread_create.c:477
#29 0x00007ff35e5dc293 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
