### ISSUE TITLE
Wallet not connected - Windows

### ISSUE THREAD

**Issue by meurtn** [Chia-Network/chia-blockchain#237]
Hi, got 0.1.12 installed on Windows. Wallet connection wasn't an issue before, but after a recent reboot it didn't connect anymore. Any ideas? Error below:

--------
Wallet src.wallet.websocket_server: ERROR    17:30:13.302 Error while handling message: Traceback (most recent call last):
  File "c:\users\user\appdata\local\programs\chia network\chia blockchain\venv\lib\site-packages\src\wallet\websocket_server.py", line 480, in safe_handle
    await self.handle_message(websocket, path)
  File "c:\users\user\appdata\local\programs\chia network\chia blockchain\venv\lib\site-packages\src\wallet\websocket_server.py", line 549, in handle_message
    await self.get_wallet_summaries(websocket, data, command)
  File "c:\users\user\appdata\local\programs\chia network\chia blockchain\venv\lib\site-packages\src\wallet\websocket_server.py", line 428, in get_wallet_summaries
    colour = await wallet.get_colour()
  File "c:\users\user\appdata\local\programs\chia network\chia blockchain\venv\lib\site-packages\src\wallet\cc_wallet\cc_wallet.py", line 232, in get_colour
    colour = cc_wallet_puzzles.get_genesis_from_core(self.cc_info.my_core)
  File "c:\users\user\appdata\local\programs\chia network\chia blockchain\venv\lib\site-packages\src\wallet\cc_wallet\cc_wallet_puzzles.py", line 91, in get_genesis_from_core
    return core[-2678:].split(")")[0]
TypeError: 'NoneType' object is not subscriptable

**Comment by hoffmang9** [comment]
This UI/chia service pair will be deprecated in beta 1.6 so closing.
