### ISSUE TITLE
[BUG] Failed to start daemon

### ISSUE THREAD

**Issue by Dravenex** [Chia-Network/chia-blockchain#2372]
I updated to 1.1.1 on Raspberry Pi 4 64-bit and the blockchain wouldn't sync. So i deleted the /home/pi/.Chia/mainnet folder and re-installed chia. Now I get the following message when I try to start the chia services.

(venv) pi@raspberrypi:~/chia-blockchain $ chia start all
SSL handshake failed on verifying the certificate
protocol: <asyncio.sslproto.SSLProtocol object at 0x7f9d5ab278>
transport: <_SelectorSocketTransport fd=6 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/usr/lib/python3.7/asyncio/sslproto.py", line 625, in _on_handshake_complete
    raise handshake_exc
  File "/usr/lib/python3.7/asyncio/sslproto.py", line 189, in feed_ssldata
    self._sslobj.do_handshake()
  File "/usr/lib/python3.7/ssl.py", line 763, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate signature failure (_ssl.c:1056)
SSL error in data received
protocol: <asyncio.sslproto.SSLProtocol object at 0x7f9d5ab278>
transport: <_SelectorSocketTransport closing fd=6 read=idle write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/usr/lib/python3.7/asyncio/sslproto.py", line 526, in data_received
    ssldata, appdata = self._sslpipe.feed_ssldata(data)
  File "/usr/lib/python3.7/asyncio/sslproto.py", line 189, in feed_ssldata
    self._sslobj.do_handshake()
  File "/usr/lib/python3.7/ssl.py", line 763, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate signature failure (_ssl.c:1056)
Daemon not started yet
Starting daemon
Traceback (most recent call last):
  File "/home/pi/chia-blockchain/venv/bin/chia", line 33, in <module>
    sys.exit(load_entry_point('chia-blockchain', 'console_scripts', 'chia')())
  File "/home/pi/chia-blockchain/chia/cmds/chia.py", line 77, in main
    cli()  # pylint: disable=no-value-for-parameter
  File "/home/pi/chia-blockchain/venv/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/pi/chia-blockchain/venv/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/pi/chia-blockchain/venv/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/pi/chia-blockchain/venv/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/pi/chia-blockchain/venv/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/pi/chia-blockchain/venv/lib/python3.7/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/pi/chia-blockchain/chia/cmds/chia.py", line 60, in run_daemon_cmd
    asyncio.get_event_loop().run_until_complete(async_run_daemon(ctx.obj["root_path"]))
  File "/usr/lib/python3.7/asyncio/base_events.py", line 584, in run_until_complete
    return future.result()
  File "/home/pi/chia-blockchain/chia/daemon/server.py", line 944, in async_run_daemon
    await ws_server.start()
  File "/home/pi/chia-blockchain/chia/daemon/server.py", line 145, in start
    ssl=self.ssl_context,
  File "/home/pi/chia-blockchain/venv/lib/python3.7/site-packages/websockets/server.py", line 965, in __await_impl__
    server = await self._create_server()
  File "/usr/lib/python3.7/asyncio/base_events.py", line 1378, in create_server
    % (sa, err.strerror.lower())) from None
OSError: [Errno 98] error while attempting to bind on address ('127.0.0.1', 55400): address already in use
SSL handshake failed on verifying the certificate
protocol: <asyncio.sslproto.SSLProtocol object at 0x7f9d5c70b8>
transport: <_SelectorSocketTransport fd=7 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/usr/lib/python3.7/asyncio/sslproto.py", line 625, in _on_handshake_complete
    raise handshake_exc
  File "/usr/lib/python3.7/asyncio/sslproto.py", line 189, in feed_ssldata
    self._sslobj.do_handshake()
  File "/usr/lib/python3.7/ssl.py", line 763, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate signature failure (_ssl.c:1056)
SSL error in data received
protocol: <asyncio.sslproto.SSLProtocol object at 0x7f9d5c70b8>
transport: <_SelectorSocketTransport closing fd=7 read=idle write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/usr/lib/python3.7/asyncio/sslproto.py", line 526, in data_received
    ssldata, appdata = self._sslpipe.feed_ssldata(data)
  File "/usr/lib/python3.7/asyncio/sslproto.py", line 189, in feed_ssldata
    self._sslobj.do_handshake()
  File "/usr/lib/python3.7/ssl.py", line 763, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate signature failure (_ssl.c:1056)
Daemon not started yet
Failed to create the chia daemon

**Comment by hoffmang9** [comment]
Are you using git to install? Did you re run install.sh?

**Comment by Dravenex** [comment]
Yes, I followed the whole instruction https://github.com/Chia-Network/chia-blockchain/wiki/Raspberry-Pi 

I flashed my SD card with a new OS now and setting all up again, but for future updates I would like to know what's the correct way to update correctly, since the Pi is becoming my 24/7 farmer the next days. In general I would like to see more info about Raspberry Pi farming, since Chia is all about "green" energy and beeing a less energy consuming coin.

**Comment by gilMotta1** [comment]
same thing happened to me. I followed the instructions from the beginning to reinstall chia and I am getting the same issue. The only difference is that I am upgrading from version 1.1.3 to version 1.1.4.

![image](https://user-images.githubusercontent.com/13684523/117247193-d7016c00-ae0b-11eb-87ce-4dacbe1b6b11.png)

**Comment by gilMotta1** [comment]
After reading the last line of my dump, I thought maybe the daemon did not stop so I went ahead and rebooted the Pi and typed:
chia init
chia start farmer 
and it started without a problem!

**Comment by tksalarzai** [comment]
> Are you using git to install? Did you re run install.sh?

im getting this error in my harvester machine logs. i tried recopying CA folder through powershell but still this error pops up. ANY SOLUTIONS ?

True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate signature failure (_ssl.c:1091)')]
