### ISSUE TITLE
RuntimeError: Unknown exception

### ISSUE THREAD

**Issue by goncalocruz77** [Chia-Network/chia-blockchain#2382]
Hi. I have the error below when starting to load the Lots. Can you help me?

Traceback (most recent call last):
  File "chia\cmds\chia.py", line 81, in <module>
  File "chia\cmds\chia.py", line 77, in main
  File "click\core.py", line 829, in __call__
  File "click\core.py", line 782, in main
  File "click\core.py", line 1259, in invoke
  File "click\core.py", line 1259, in invoke
  File "click\core.py", line 1066, in invoke
  File "click\core.py", line 610, in invoke
  File "click\decorators.py", line 21, in new_func
  File "chia\cmds\plots.py", line 135, in create_cmd
  File "chia\plotting\create_plots.py", line 176, in create_plots
RuntimeError: Unknown exception

Thanks.

**Comment by dexter74** [comment]
Can you try install Microsoft Visual C++for fix a bug.

**Comment by hoffmang9** [comment]
This is an error with your file system or RAM. Make sure you have permissions and enough RAM left without causing your machine to swap.
