### ISSUE TITLE
MacOS Startup error (1.1.0, 1.1.1)

### ISSUE THREAD

**Issue by j4ys0n** [Chia-Network/chia-blockchain#2398]
`Chia` cli crashes on start.
Error:
```
Chia.app/Contents/MacOS
❯ ./Chia
/Applications/Chia.app/Contents/Resources/app.asar.unpacked/daemon
true
Error loading config - using defaults
startUrl file:///Applications/Chia.app/Contents/Resources/app.asar/build/renderer/index.html
/Applications/Chia.app/Contents/Resources/app.asar.unpacked/daemon
true
/Applications/Chia.app/Contents/Resources/app.asar.unpacked/daemon
true
Running python executable:
child process success
(node:26640) electron: The default of contextIsolation is deprecated and will be changing from false to true in a future release of Electron.  See https://github.com/electron/electron/issues/23506 for more information
GVA encoder info: AMD performance mode : 2
No cert
Have cert
stderr: Traceback (most recent call last):
  File "chia/daemon/server.py", line 962, in <module>
  File "chia/daemon/server.py", line 958, in main
  File "chia/daemon/server.py", line 952, in run_daemon
stderr:   File "asyncio/base_events.py", line 642, in run_until_complete
  File "chia/daemon/server.py", line 944, in async_run_daemon
  File "chia/daemon/server.py", line 138, in start
  File "websockets/server.py", line 965, in __await_impl__
  File "asyncio/base_events.py", line 1494, in create_server
OSError: [Errno 49] error while attempting to bind on address ('192.168.99.100', 55400): can't assign requested address
[26645] Failed to execute script server
closing code: 255
GVA encoder info: deleteSCDMetalContext : texture cache hits: 0, misses: 0
```

I'm not sure how it's getting that IP address (`192.168.99.100`). It's not the IP of my machine, it is however the IP of the VirtualBox/Docker Machine installation I have - that's not currently running.

- OS: MacOS 10.15
- CPU: AMD Ryzen 3600
- RAM: 32GB

I'm happy to debug further, just let me know how best to help.

**Comment by j4ys0n** [comment]
in `~/.chia/mainnet/config/config.yaml`, if I specify the machine IP, instead of `localhost` on line 5. The cli starts up without errors, but the UI does not connect.

`self_hostname: &self_hostname "192.168.2.150"`

```
Chia.app/Contents/MacOS
❯ ./Chia
/Applications/Chia.app/Contents/Resources/app.asar.unpacked/daemon
true
Error loading config - using defaults
startUrl file:///Applications/Chia.app/Contents/Resources/app.asar/build/renderer/index.html
/Applications/Chia.app/Contents/Resources/app.asar.unpacked/daemon
true
/Applications/Chia.app/Contents/Resources/app.asar.unpacked/daemon
true
Running python executable:
child process success
(node:27395) electron: The default of contextIsolation is deprecated and will be changing from false to true in a future release of Electron.  See https://github.com/electron/electron/issues/23506 for more information
GVA encoder info: AMD performance mode : 2
No cert
Have cert
GVA encoder info: deleteSCDMetalContext : texture cache hits: 0, misses: 0
```
![image](https://user-images.githubusercontent.com/979576/115750528-7ecf6200-a355-11eb-924b-2d3d891b1756.png)

**Comment by jayMcBee** [comment]
**OS: MacOS 10.15
CPU: AMD Ryzen 3600**

That's not a valid Mac configuration.

**Comment by j4ys0n** [comment]
It is - it's obviously not from Apple though. I'm running MacOS on PC hardware with an AMD Ryzen CPU.

**Comment by j4ys0n** [comment]
For the record, it starts up fine on my other Ryzen Mac - that's running MacOS 11.2.2 with an AMD 5600X.

**Comment by hoffmang9** [comment]
Try deleting the peer dbs in db/ and wallet/db
