### ISSUE TITLE
1.1.1 Ubuntu: Not Synced

### ISSUE THREAD

**Issue by salamanders** [Chia-Network/chia-blockchain#2408]
1. Woke up to the "this will stop working at height xxx" message.  Ok, no worries...
2. Noticed that I wasn't synced since last night.  Stopped around height 166101
3. Killed my plotting.
4. Updated to latest 1.1.1 via git.
5. installed latest using .sh
6. Rebooted machine
7. Saw it go from "Not Synced" to "Synchronizing..." then back to "Not Synced"
8. While UI was running, tried a few commands in the same `. /activate` terminal: 

- `chia show -a node.chia.net:8444` (failed to connect)
- `chia show -a 35.80.8.179:8444` (failed to connect)
- `chia show -a 18.168.101.107:8444` (failed to connect)

I am connected to 2 nodes (1 farmer, 1 wallet)

## Questions

1. Is this broken or just "dude, wait at least 6 hours before worrying."
2. Is trying to connect via command line when the GUI is running a "bad thing"?
3. If 1=Broken, Anything I should be doing to help debug?

```
Traceback (most recent call last):
  File "../chia/daemon/server.py", line 172, in safe_handle
    response, sockets_to_use = await self.handle_message(websocket, decoded)
  File "../chia/daemon/server.py", line 275, in handle_message
    response = await self.stop_plotting(cast(Dict[str, Any], data))
RuntimeError: coroutine raised StopIteration

2021-04-22T11:06:14.747 daemon __main__                   : ERROR    Error while handling message: Traceback (most recent call last):
  File "../chia/daemon/server.py", line 550, in stop_plotting
    config = self._get_plots_queue_item(id)
  File "../chia/daemon/server.py", line 432, in _get_plots_queue_item
    config = next(item for item in self.plots_queue if item["id"] == id)
StopIteration

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "../chia/daemon/server.py", line 172, in safe_handle
    response, sockets_to_use = await self.handle_message(websocket, decoded)
  File "../chia/daemon/server.py", line 275, in handle_message
    response = await self.stop_plotting(cast(Dict[str, Any], data))
RuntimeError: coroutine raised StopIteration

2021-04-22T11:06:22.349 daemon __main__                   : ERROR    Error while handling message: Traceback (most recent call last):
  File "../chia/daemon/server.py", line 550, in stop_plotting
    config = self._get_plots_queue_item(id)
  File "../chia/daemon/server.py", line 432, in _get_plots_queue_item
    config = next(item for item in self.plots_queue if item["id"] == id)
StopIteration

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "../chia/daemon/server.py", line 172, in safe_handle
    response, sockets_to_use = await self.handle_message(websocket, decoded)
  File "../chia/daemon/server.py", line 275, in handle_message
    response = await self.stop_plotting(cast(Dict[str, Any], data))
RuntimeError: coroutine raised StopIteration

2021-04-22T11:06:44.434 full_node asyncio                 : ERROR    Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7f2064ad61c0>
2021-04-22T11:06:47.860 daemon asyncio                    : ERROR    Task exception was never retrieved
future: <Task finished name='Task-11241' coro=<kill_service() done, defined at ../chia/daemon/server.py:813> exception=AttributeError("'list' object has no attribute 'terminate'")>
Traceback (most recent call last):
  File "../chia/daemon/server.py", line 821, in kill_service
    result = await kill_process(process, root_path, service_name, "", delay_before_kill)
  File "../chia/daemon/server.py", line 789, in kill_process
    process.terminate()
AttributeError: 'list' object has no attribute 'terminate'
2021-04-22T11:27:30.437 full_node chia.rpc.rpc_server     : WARNING  Error while handling message: Traceback (most recent call last):
  File "/home/ME/Documents/chia-blockchain/chia/rpc/rpc_server.py", line 81, in inner
    res_object = await f(request_data)
  File "/home/ME/Documents/chia-blockchain/chia/rpc/rpc_server.py", line 161, in open_connection
    raise ValueError("Start client failed, or server is not set")
ValueError: Start client failed, or server is not set

2021-04-22T11:28:16.426 full_node chia.rpc.rpc_server     : WARNING  Error while handling message: Traceback (most recent call last):
  File "/home/ME/Documents/chia-blockchain/chia/rpc/rpc_server.py", line 81, in inner
    res_object = await f(request_data)
  File "/home/ME/Documents/chia-blockchain/chia/rpc/rpc_server.py", line 161, in open_connection
    raise ValueError("Start client failed, or server is not set")
ValueError: Start client failed, or server is not set

2021-04-22T11:29:10.427 full_node chia.rpc.rpc_server     : WARNING  Error while handling message: Traceback (most recent call last):
  File "/home/ME/Documents/chia-blockchain/chia/rpc/rpc_server.py", line 81, in inner
    res_object = await f(request_data)
  File "/home/ME/Documents/chia-blockchain/chia/rpc/rpc_server.py", line 161, in open_connection
    raise ValueError("Start client failed, or server is not set")
ValueError: Start client failed, or server is not set
```

**Comment by dorkmo** [comment]
make sure your port 8444 is forwarded to your node on your network router

**Comment by salamanders** [comment]
> make sure your port 8444 is forwarded to your node on your network router

Just confirmed, is forwarded in wifi app config.

* Yet, https://www.yougetsignal.com/tools/open-ports/ is saying it is closed.  Interesting.
* https://www.grc.com/shieldsup says it is "stealth open" - so that is good!

**Comment by nowickj** [comment]
I had a similar problem. I have installed a new Ubuntu 20.04 LTS, configured everything. Now status is Not Synced. After few minutes it's changed for Syncing 1120/169461, and again it is changing to Not Synced.
I have another server on Ubuntu too, but it has older version and it is Synced.
Port 8444 is open on My router.
after making 
chia show -a node.chia.net:8444
chia show -a 35.80.8.179:8444

syncing moovs forward.

**Comment by megablue** [comment]
After updating to v1.1.1 none of my windows machines are able to sync as well...

**Comment by salamanders** [comment]
chia show -a node.chia.net:8444 - no error
chia show -a 35.80.8.179:8444 - error

"Status: Syncing 166101/169762"

**Comment by salamanders** [comment]
Oh freaky, `chia version` says `1.1.2.dev0`

**Comment by hoffmang9** [comment]
The 1.1.2.dev0 is a common git related issue you can ignore.

**Comment by salamanders** [comment]
> common git related issue you can ignore -- Cool, ignoring!  :)  

Any thoughts on how to debug?

**Comment by hoffmang9** [comment]
You need to get your router routing 8444 to your node.

**Comment by salamanders** [comment]
Hopefully red herring:

```
$ npm run electron &
[1] 9324
(venv) ME@YELLOW:~/Documents/chia-blockchain/chia-blockchain-gui$ 
> electron
> electron .

/home/ME/Documents/chia-blockchain/app.asar.unpacked/daemon
false
Error loading config - using defaults
```

**Comment by salamanders** [comment]
> You need to get your router routing 8444 to your node.

Is there anything that might have increased the chances of more rare issues (like this) in the last 2 days?  Over in /r/chia it seems like lots of ppl are suddenly having connection or sync issues.  Or did we reach some threshold where *not* having 8444 routed properly suddenly has more chances of causing a glitch?

**Comment by salamanders** [comment]
Upped the logs to INFO:

```
2021-04-22T15:17:56.204 full_node full_node_server        : INFO     -> handshake to peer 90.152.200.12 4ccc801aa64da04bd4a200ff3f49e5e398062ec1d56b876787320ff7029d9305
2021-04-22T15:17:56.450 full_node full_node_server        : INFO     Connected with full_node {'host': '90.152.200.12', 'port': 8444}
2021-04-22T15:17:56.451 full_node full_node_server        : INFO     -> new_peak to peer 90.152.200.12 4ccc801aa64da04bd4a200ff3f49e5e398062ec1d56b876787320ff7029d9305
2021-04-22T15:17:56.452 full_node full_node_server        : INFO     -> request_peers to peer 90.152.200.12 4ccc801aa64da04bd4a200ff3f49e5e398062ec1d56b876787320ff7029d9305
2021-04-22T15:17:56.453 full_node full_node_server        : INFO     Connection closed: 90.152.200.12, node id: 4ccc801aa64da04bd4a200ff3f49e5e398062ec1d56b876787320ff7029d9305
2021-04-22T15:17:56.454 full_node chia.full_node.full_node: INFO     peer disconnected {'host': '90.152.200.12', 'port': 8444}
```

**Comment by salamanders** [comment]
Ok so **I HAVE FIXED IT FOR JUST ME**.  (using @hoffmang9 's advice because of course they were right)

1. I had previously set up forwarding in my mesh Wifi.  This was working fine.
2. I had also checked that the firewall was behaving. This was ALSO working fine.
3. I had hoped that UPnP in my cable modem was working. this was NOT FINE.  
4. So I tried to do port forwarding from the modem to my mesh.  xfinity's port forwarding is (AFAIK) very broken.  I couldn't forward from the modem to my Mesh Wifi.  They are trying to figure out why it is so broken.
5. In the meantime, I moved my mesh network's router into the xFinity DMZ.  **This instantly fixed the issue.**

**Comment by dorkmo** [comment]
i believe they said it might have to do with the huge increase in new nodes coming online. if your ports were not set up correctly before, the nodes with ports open could support a good number of others, but it became too overwhelming.

**Comment by salamanders** [comment]
Huh.  If the port *needs* to be routed right, then the app should check for that and give you big blinky errors if it isn't... right?

**Comment by dorkmo** [comment]
that would be nice! but unfortunately it doesnt :( node communication seemed to be pretty stable a week or two ago, but there are thousands of nodes coming online everyday now. i think they were depending on upnp to keep most people connected to the network but it seems to not be reliable enough for the current reality.

**Comment by hoffmang9** [comment]
The largest blockchain in the world has 85,000 nodes. We passed that a few days ago and are adding about 10,000 nodes a day. That is... ahead of expectations.

**Comment by salamanders** [comment]
Daaaang.

**Comment by Dravenex** [comment]
To the moooooooon
