### ISSUE TITLE
[BUG] Peers problem (Win 1.1.1)

### ISSUE THREAD

**Issue by Siphrioth** [Chia-Network/chia-blockchain#2422]
Ive Problem with windows V 1.1.1 i get no peers
i can connect with node.chia.net. all firewall is open but i get no other peers.

Log:
2021-04-22T23:42:22.694 wallet wallet_server              : ERROR    Exception:  <class 'concurrent.futures._base.CancelledError'>, closing connection {'host': '127.0.0.1', 'port': 8444}. Traceback (most recent call last):
  File "chia\server\server.py", line 521, in api_call
  File "asyncio\tasks.py", line 435, in wait_for
concurrent.futures._base.CancelledError

2021-04-22T23:42:22.694 full_node full_node_server        : ERROR    Exception:  <class 'concurrent.futures._base.CancelledError'>, closing connection {'host': '127.0.0.1', 'port': 8449}. Traceback (most recent call last):
  File "chia\server\server.py", line 521, in api_call
  File "asyncio\tasks.py", line 435, in wait_for
concurrent.futures._base.CancelledError

2021-04-22T23:42:48.488 full_node full_node_server        : ERROR    Exception:  <class 'concurrent.futures._base.CancelledError'>, closing connection {'host': '2a05:d01c:e44:d701:ca21:417e:7305:31b0', 'port': 8444}. Traceback (most recent call last):
  File "chia\server\server.py", line 521, in api_call
  File "asyncio\tasks.py", line 435, in wait_for
concurrent.futures._base.CancelledError

**Comment by hoffmang9** [comment]
https://github.com/Chia-Network/chia-blockchain/wiki/FAQ#why-does-my-node-have-no-connections-how-can-i-get-more-connections

**Comment by Siphrioth** [comment]
ive all ports open. yesterday works all fine, today update 1.0.5 -> V1.1.1 and buggy now

**Comment by Siphrioth** [comment]
ok funktion now... i dont know why but win delet all my ports for Chia ... now ive 4 peers and more

**Comment by dorkmo** [comment]
make sure 8444 is forwarded to the correct local ip address
