### ISSUE TITLE
v1.1.0 (win10) Warnings and errors in the log file, Why?

### ISSUE THREAD

**Issue by longren610** [Chia-Network/chia-blockchain#2439]
The nodes are synchronized and the connection is normal, but there are warnings and errors in the log output.
What can I do to solve this problem?

![QQ截图20210423111050](https://user-images.githubusercontent.com/26690413/115812919-d688ce80-a424-11eb-8e6c-f210641723c3.png)

```
WARNING  Peer surpassed rate limit 127.0.0.1, message: farming_info, port 49901 but not disconnecting

2021-04-23T09:51:17.685 full_node full_node_server        : ERROR    Exception Was not able to get peername from <function WSChiaConnection.__getattr__.<locals>.invoke at 0x0000017EE8D24828> at 119.147.145.99, exception Stack: Traceback (most recent call last):
  File "chia\server\server.py", line 243, in incoming_connection
  File "chia\server\ws_connection.py", line 59, in __init__
ValueError: Was not able to get peername from <function WSChiaConnection.__getattr__.<locals>.invoke at 
0x0000017EE8D24828> at 119.147.145.99

2021-04-23T10:39:27.298 full_node full_node_server        : ERROR    Exception Was not able to get peername from <function WSChiaConnection.__getattr__.<locals>.invoke at 0x0000017EE931AF78> at 118.69.72.164, exception Stack: Traceback (most recent call last):
  File "chia\server\server.py", line 243, in incoming_connection
  File "chia\server\ws_connection.py", line 59, in __init__
ValueError: Was not able to get peername from <function WSChiaConnection.__getattr__.<locals>.invoke at 0x0000017EE931AF78> at 118.69.72.164

```

**Comment by gitscy** [comment]
win10, has the same debug log.
-------------------------------------
2021-04-25T20:53:58.025 full_node full_node_server        : WARNING  Banning 172.104.95.165 for 10 seconds
2021-04-25T20:53:58.026 full_node full_node_server        : WARNING  Invalid handshake with peer. Maybe the peer is running old software.
2021-04-25T20:54:08.604 full_node full_node_server        : WARNING  Banning 92.116.252.164 for 10 seconds
2021-04-25T20:54:08.607 full_node full_node_server        : WARNING  Invalid handshake with peer. Maybe the peer is running old software.
2021-04-25T21:01:14.772 full_node full_node_server        : ERROR    Exception Was not able to get peername from <function WSChiaConnection.__getattr__.<locals>.invoke at 0x000001095F6E9678> at 115.164.219.102, exception Stack: Traceback (most recent call last):
  File "chia\server\server.py", line 243, in incoming_connection
  File "chia\server\ws_connection.py", line 59, in __init__
ValueError: Was not able to get peername from <function WSChiaConnection.__getattr__.<locals>.invoke at 0x000001095F6E9678> at 115.164.219.102

**Comment by hoffmang9** [comment]
Peers disconnect and that creates these logs. Issues is not for tech questions. Discussions and Keybase are.

**Comment by tartley** [comment]
If it is normal, should it log an ERROR with traceback? Respectfully wonder whether lots of people, finding this in their logs, will report similar issues in future.
