### ISSUE TITLE
[BUG]G1 element is invalid

### ISSUE THREAD

**Issue by fullet-tortuga** [Chia-Network/chia-blockchain#2476]
"chia start all" yields the following error:

ValueError: G1 element is invalid
[12000] Failed to execute script chia
Daemon not started yet
Failed to create the chia daemon

**Comment by fullet-tortuga** [comment]
Still fails in current version:

Traceback (most recent call last):
  File "chia\cmds\chia.py", line 81, in <module>
  File "chia\cmds\chia.py", line 77, in main
  File "click\core.py", line 829, in __call__
  File "click\core.py", line 782, in main
  File "click\core.py", line 1259, in invoke
  File "click\core.py", line 1066, in invoke
  File "click\core.py", line 610, in invoke
  File "click\decorators.py", line 21, in new_func
  File "chia\cmds\init.py", line 29, in init_cmd
  File "chia\cmds\init_funcs.py", line 242, in init
  File "chia\cmds\init_funcs.py", line 316, in chia_init
  File "chia\cmds\init_funcs.py", line 69, in check_keys
  File "chia\consensus\coinbase.py", line 10, in create_puzzlehash_for_pk
  File "chia\wallet\puzzles\p2_delegated_puzzle_or_hidden_puzzle.py", line 78, in puzzle_for_pk
  File "chia\wallet\puzzles\p2_delegated_puzzle_or_hidden_puzzle.py", line 68, in puzzle_for_public_key_and_hidden_puzzle_hash
  File "chia\wallet\puzzles\p2_delegated_puzzle_or_hidden_puzzle.py", line 49, in calculate_synthetic_public_key
  File "chia\types\blockchain_format\program.py", line 78, in run
  File "chia\types\blockchain_format\program.py", line 74, in run_with_cost
  File "chia\types\blockchain_format\program.py", line 31, in run_program
  File "clvm\run_program.py", line 182, in run_program
  File "clvm\run_program.py", line 172, in apply_op
  File "clvm\operators.py", line 195, in __call__
  File "clvm\more_ops.py", line 211, in op_pubkey_for_exp
clvm.EvalError.EvalError: problem in op_pubkey_for_exp: G1 element is invalid

**Comment by fullet-tortuga** [comment]
Thank you. Please reopen it so programmers have another 14 days to fix the bug.

**Comment by stefanel96** [comment]
Hello, did you find the fix for this error, it's repatedly saying this for one of my plots?

**Comment by fullet-tortuga** [comment]
Nope. I'm still waiting for the programmers to fix this bug.
I wish they fixed the bugs instead of having 2,000 of them closed all at once with no fixture as in the past week.

**Comment by loppefaaret** [comment]
could you try to reproduce this error with chia 1.2.3, and also include what OS you are using ?
