### ISSUE TITLE
[BUG] Caught plotting error: Matches do not match with number of write entries

### ISSUE THREAD

**Issue by Kgonla** [Chia-Network/chia-blockchain#2493]
Caught plotting error: Matches do not match with number of write entries 4291074950 4291065194
[864] Failed to execute script chia
Traceback (most recent call last):
  File "chia\cmds\chia.py", line 80, in <module>
  File "chia\cmds\chia.py", line 76, in main
  File "click\core.py", line 829, in __call__
  File "click\core.py", line 782, in main
  File "click\core.py", line 1259, in invoke
  File "click\core.py", line 1259, in invoke
  File "click\core.py", line 1066, in invoke
  File "click\core.py", line 610, in invoke
  File "click\decorators.py", line 21, in new_func
  File "chia\cmds\plots.py", line 134, in create_cmd
  File "chia\plotting\create_plots.py", line 176, in create_plots
RuntimeError: Unknown exception

Unable to finish any plot.
Tested with SSD, HDD & USB HDD.
Tested increasing/decreasing cpus & ram usage.

**Comment by hoffmang9** [comment]
This is usually a hardware issue.
