### ISSUE TITLE
Cant delete stucked process in Chia Gui 1.1.1 , but why its get stuck?

### ISSUE THREAD

**Issue by aresstokrat** [Chia-Network/chia-blockchain#2497]
I tryed ask community in reddit and keybase, but there is only common problems. And than some specialist at keybase adviced me to report an issue in github, thats what im doind.

Process stuck at different percents. From 1-99% and it can stuck in this percents for days. Before that i just delete it and start again.
I have plenty of everything, ram (64gb), CPU (16threads), memory and ssd's space. Whats happening? 
 
https://www.reddit.com/r/chia/comments/mwwi7y/cant_delete_sucked_process_in_chia_gui_111_but/gvko76v/?context=3

And how to delete plotting tasks in 1.1.1 version, not killing all plotting procecces?

**Comment by dorkmo** [comment]
you might need to post your log here, they wouldnt have had to get stuck for a reason.

**Comment by aresstokrat** [comment]
First, i will post one that stick at 1%, then others:

`2021-04-23T13:13:12.401  chia.plotting.create_plots       : [32mINFO    [0m Creating 1 plots of size 32, pool public key:  a93b0499e3284f8bcfade97bba778883b431e4412b299236e10ab5003a2cf4f400fbb14a farmer public key: 90c71d5aad88690a16b18779901299bb9f15d6dcd68c9c5df4df50de539a07707be4e804a[0m
2021-04-23T13:13:12.406  chia.plotting.create_plots       : [32mINFO    [0m Memo: a93b0499e3284f8bcfade97bba36f2e972acc296687496e8ff8630b3b431e4412b299236e10ab5003a2cf4f400fbb14a90c71d5aad88690a17788631299bb9f15d6dcd68c9c5df4df50de539a07707be4e804a5a30bd2a5d37af9aa9789ebd683e031647f7476f4a4078a1e437d6af89b2dbba[0m
2021-04-23T13:13:12.407  chia.plotting.create_plots       : [32mINFO    [0m Adding directory I:\ to harvester for farming[0m
[29172] Failed to execute script chia
Traceback (most recent call last):
  File "chia\cmds\chia.py", line 81, in <module>
  File "chia\cmds\chia.py", line 77, in main
  File "click\core.py", line 829, in __call__
  File "click\core.py", line 782, in main
  File "click\core.py", line 1259, in invoke
  File "click\core.py", line 1259, in invoke
  File "click\core.py", line 1066, in invoke
  File "click\core.py", line 610, in invoke
  File "click\decorators.py", line 21, in new_func
  File "chia\cmds\plots.py", line 135, in create_cmd
  File "chia\plotting\create_plots.py", line 158, in create_plots
  File "chia\plotting\plot_tools.py", line 109, in add_plot_directory
  File "chia\util\config.py", line 55, in load_config
  File "yaml\__init__.py", line 162, in safe_load
  File "yaml\__init__.py", line 114, in load
  File "yaml\constructor.py", line 49, in get_single_data
  File "yaml\composer.py", line 36, in get_single_node
  File "yaml\composer.py", line 55, in compose_document
  File "yaml\composer.py", line 84, in compose_node
  File "yaml\composer.py", line 133, in compose_mapping_node
  File "yaml\composer.py", line 84, in compose_node
  File "yaml\composer.py", line 127, in compose_mapping_node
  File "yaml\parser.py", line 98, in check_event
  File "yaml\parser.py", line 428, in parse_block_mapping_key
  File "yaml\scanner.py", line 115, in check_token
  File "yaml\scanner.py", line 152, in need_more_tokens
  File "yaml\scanner.py", line 292, in stale_possible_simple_keys
yaml.scanner.ScannerError: while scanning a simple key
  in "C:\Users\ares_\.chia\mainnet\config\config.yaml", line 216, column 1
could not find expected ':'
  in "C:\Users\ares_\.chia\mainnet\config\config.yaml", line 217, column 1`

**Comment by aresstokrat** [comment]
Used different rig and its a common problem. Tottaly different config and same error::

`2021-04-24T07:52:12.973  chia.plotting.create_plots       : [32mINFO    [0m Creating 1 plots of size 32, pool public key:  a93b0499e3284f8bcfade97bba36f2e972acc296687496e8ff8630b3b431e4412b299236e10ab5003a2cf4f400fbb14a farmer public key: 90c71d5aad88690a16b18869a4b5b07dd8a35cbbe3c6260631299bb9f15d6dcd68c9c5df4df50de539a07707be4e804a[0m
2021-04-24T07:52:12.979  chia.plotting.create_plots       : [32mINFO    [0m Memo: a93b0499e3284f8bcfade97bba36f2e972acc296687496e8ff8630b3b431e4412b299236e10ab5003a2cf4f400fbb14a90c71d5aad88690a16b18869a4b5b07dd8a35cbbe3c6260631299bb9f15d6dcd68c9c5df4df50de539a07707be4e804a2579a300037fcc393af6e23c61cb80fc7fb4bd2da83aec8ef40d333570edcf28[0m
2021-04-24T07:52:12.979  chia.plotting.create_plots       : [32mINFO    [0m Adding directory G:\ to harvester for farming[0m
[2832] Failed to execute script chia
Traceback (most recent call last):
  File "chia\cmds\chia.py", line 81, in <module>
  File "chia\cmds\chia.py", line 77, in main
  File "click\core.py", line 829, in __call__
  File "click\core.py", line 782, in main
  File "click\core.py", line 1259, in invoke
  File "click\core.py", line 1259, in invoke
  File "click\core.py", line 1066, in invoke
  File "click\core.py", line 610, in invoke
  File "click\decorators.py", line 21, in new_func
  File "chia\cmds\plots.py", line 135, in create_cmd
  File "chia\plotting\create_plots.py", line 158, in create_plots
  File "chia\plotting\plot_tools.py", line 109, in add_plot_directory
  File "chia\util\config.py", line 55, in load_config
  File "yaml\__init__.py", line 162, in safe_load
  File "yaml\__init__.py", line 114, in load
  File "yaml\constructor.py", line 49, in get_single_data
  File "yaml\composer.py", line 36, in get_single_node
  File "yaml\composer.py", line 55, in compose_document
  File "yaml\composer.py", line 84, in compose_node
  File "yaml\composer.py", line 133, in compose_mapping_node
  File "yaml\composer.py", line 84, in compose_node
  File "yaml\composer.py", line 127, in compose_mapping_node
  File "yaml\parser.py", line 98, in check_event
  File "yaml\parser.py", line 428, in parse_block_mapping_key
  File "yaml\scanner.py", line 115, in check_token
  File "yaml\scanner.py", line 152, in need_more_tokens
  File "yaml\scanner.py", line 292, in stale_possible_simple_keys
yaml.scanner.ScannerError: while scanning a simple key
  in "C:\Users\WWW\.chia\mainnet\config\config.yaml", line 263, column 1
could not find expected ':'
  in "C:\Users\WWW\.chia\mainnet\config\config.yaml", line 264, column 1`

**Comment by maomingyang1314** [comment]
The deletion task of win10 is disabled, as mentioned in the update report of version 1.1.0

**Comment by aresstokrat** [comment]
> The deletion task of win10 is disabled, as mentioned in the update report of version 1.1.0

yeah, i also read changelog.
Still plotting process get stuck in the middle of nowhere and only chance to continue is to kill it.

How to kill exact plotting process without clossing GUI and stopping all proccesses?
