### ISSUE TITLE
[other]First start chia.harvester.harvester: WARNING

### ISSUE THREAD

**Issue by AckerPaul** [Chia-Network/chia-blockchain#2529]
The first startup log shows, is this normal?
harvester chia.harvester.harvester: WARNING Not farming any plots on this harvester. Check your configuration.

Does it affect my creation of P tasks ？

How to avoid this prompt ？
Thank you.
centos7

**Comment by AckerPaul** [comment]
chia_wallet: Exception in thread Thread-2:
Traceback (most recent call last):
  File "/root/chia-blockchain/venv/lib/python3.7/site-packages/aiosqlite/core.py", line 109, in run
    get_loop(future).call_soon_threadsafe(set_result, future, result)
  File "/usr/local/lib/python3.7/asyncio/base_events.py", line 736, in call_soon_threadsafe
    self._check_closed()
  File "/usr/local/lib/python3.7/asyncio/base_events.py", line 479, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed

During handling of the above exception, another exception occurred:

I try to stop the above error
