### ISSUE TITLE
[BUG] My chia is not plotting but disc is working stop at 1%

### ISSUE THREAD

**Issue by MegaKocur** [Chia-Network/chia-blockchain#2537]
**Describe the bug**
in hardware manager disc is working, but plotting after day is 1%

**To Reproduce**

Starting plotting progress into temporary dirs: F:\chiatemp and F:\chiatemp
ID: fbb79fdb4a1f1bcc62cc88e1fa2dfcffacfb6503da68bfc32c84d3553918ec70
Plot size is: 32
Buffer size is: 3390MiB
Using 128 buckets
Using 2 threads of stripe size 65536

Starting phase 1/4: Forward Propagation into tmp files... Fri Apr 23 22:33:51 2021
Computing table 1
F1 complete, time: 483.395 seconds. CPU (51.42%) Fri Apr 23 22:41:55 2021
Computing table 2
Caught plotting error: bad allocation
[11196] Failed to execute script chia
Traceback (most recent call last):
  File "chia\cmds\chia.py", line 81, in <module>
  File "chia\cmds\chia.py", line 77, in main
  File "click\core.py", line 829, in __call__
  File "click\core.py", line 782, in main
  File "click\core.py", line 1259, in invoke
  File "click\core.py", line 1259, in invoke
  File "click\core.py", line 1066, in invoke
  File "click\core.py", line 610, in invoke
  File "click\decorators.py", line 21, in new_func
  File "chia\cmds\plots.py", line 135, in create_cmd
  File "chia\plotting\create_plots.py", line 176, in create_plots
RuntimeError: bad allocation

**Expected behavior**

**Screenshots**

- OS: Win 10 x64
- OS Version/Flavor: Windows Feature Experience Pack 120.2212.551.0
- CPU: Intel(R) Core(TM) i7 CPU         860  @ 2.80GHz   2.80 GHz
**Additional context**

**Comment by hoffmang9** [comment]
This is a RAM problem. It could be your swap settings but is often actual hardware settings or broken ram sticks.
