### ISSUE TITLE
[BUG]can't find vdf_client binary

### ISSUE THREAD

**Issue by nassie256** [Chia-Network/chia-blockchain#2572]
**can't find vdf_client binary in Ubuntu 20.04**
execute chia start all, chia_timelord_launcher said:
~~~
(venv) myname@farm001:~/chia-blockchain$ Traceback (most recent call last):
  File "/home/myname/chia-blockchain/venv/bin/chia_timelord_launcher", line 33, in <module>
    sys.exit(load_entry_point('chia-blockchain', 'console_scripts', 'chia_timelord_launcher')())
  File "/home/myname/chia-blockchain/chia/timelord/timelord_launcher.py", line 107, in main
    loop.run_until_complete(spawn_all_processes(config, net_config))
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/myname/chia-blockchain/chia/timelord/timelord_launcher.py", line 85, in spawn_all_processes
    await asyncio.gather(*awaitables)
  File "/home/myname/chia-blockchain/chia/timelord/timelord_launcher.py", line 45, in spawn_process
    path_to_vdf_client = find_vdf_client()
  File "/home/myname/chia-blockchain/chia/timelord/timelord_launcher.py", line 39, in find_vdf_client
    raise FileNotFoundError("can't find vdf_client binary")
FileNotFoundError: can't find vdf_client binary
~~~

in debug.log:
~~~
timelord chia.timelord.timelord   : ERROR    Not active for 60 seconds, restarting all chains
~~~

**Desktop:**

- Chia 1.1.1
- OS: Linux
- OS Version/Flavor: ubuntu-20.04.2-live-server-amd64

**Comment by lvcivs** [comment]
Looks like you are trying to start a timelord. For most it does not make sense to run a timelord. Just run a full node.

**Comment by nassie256** [comment]
To use chia normally, "chia start all" Does that mean you shouldn't use?

**Comment by lvcivs** [comment]
I think `chia start farmer` is the normal way to start it from the CLI. Most people just start the GUI app, though, which will do this automatically.

The command `chia start all` includes the timelord. You don't want this.

**Comment by nassie256** [comment]
Thank you.
