### ISSUE TITLE
(BUG) Unknown exception v.1.1.1

### ISSUE THREAD

**Issue by IzmanT** [Chia-Network/chia-blockchain#2575]
Plot is not formed. Error after the first minute. Farm 101.4GiB Queue / parallel behaves the same way
What could have happened?

View Log:

1%

2021-04-24T11:34:41.126  chia.plotting.create_plots       : [32mINFO    [0m Creating 1 plots of size 32, pool public key:  b2aea06643964146566034d8fe981f3b020d7171b7860949fb8c9b6087caa5b146537f352b9eb7bd90d4d41c87221a6d farmer public key: 8ce540f57eb5654853e9023048140779ccaed9c384c760d0054e3f33a7e24fba73cbce6724737de9b72d9d7d75c6c8c4[0m
2021-04-24T11:34:41.142  chia.plotting.create_plots       : [32mINFO    [0m Memo: b2aea06643964146566034d8fe981f3b020d7171b7860949fb8c9b6087caa5b146537f352b9eb7bd90d4d41c87221a6d8ce540f57eb5654853e9023048140779ccaed9c384c760d0054e3f33a7e24fba73cbce6724737de9b72d9d7d75c6c8c42ee71643beb6fdf88b8bc4623249c5e5d8b208b911de773af3f280b67b23d009[0m
2021-04-24T11:34:41.142  chia.plotting.create_plots       : [32mINFO    [0m Starting plot 1/1[0m

Starting plotting progress into temporary dirs: C:\Р”РѕРєСѓРјРµРЅС‚С‹ and C:\Р”РѕРєСѓРјРµРЅС‚С‹
ID: ffbd116f63ec88386c126572d0c68f530b1e6fc01a91896ef55bb177fb2f02d7
Plot size is: 32
Buffer size is: 7000MiB
Using 128 buckets
Using 4 threads of stripe size 65536
Caught plotting error: Temp directory C:\Р”РѕРєСѓРјРµРЅС‚С‹ does not exist
[6236] Failed to execute script chia
Traceback (most recent call last):
  File "chia\cmds\chia.py", line 81, in <module>
  File "chia\cmds\chia.py", line 77, in main
  File "click\core.py", line 829, in __call__
  File "click\core.py", line 782, in main
  File "click\core.py", line 1259, in invoke
  File "click\core.py", line 1259, in invoke
  File "click\core.py", line 1066, in invoke
  File "click\core.py", line 610, in invoke
  File "click\decorators.py", line 21, in new_func
  File "chia\cmds\plots.py", line 135, in create_cmd
  File "chia\plotting\create_plots.py", line 176, in create_plots
RuntimeError: Unknown exception

**Comment by IzmanT** [comment]
Win 10 pro

i7 9700
2x16Gb DDR4
1tb NVME
2x4Tb HDD

**Comment by hoffmang9** [comment]
This is a hardware or swap problem on your computer.

**Comment by IzmanT** [comment]
What ias the problem? What could help me to resolve this situation? Thank you for the answer in advenced!
