### ISSUE TITLE
[BUG] Bitfield plotting not supported by CPU

### ISSUE THREAD

**Issue by Knight1** [Chia-Network/chia-blockchain#2602]
**Describe the bug**
Bitfield plotting is not supported by Proxmox. But i can not stop the Plotting without restarting Chia. After Restarting the Plotting is simply gone. 

**To Reproduce**
1. Use CPU or Hypervisor like Proxmox without Bitfield Support.
2. Add Plotting Job with Bitfield enabled

**Logs**
```
View Log
1%
 
2021-04-24T16:55:27.263  chia.plotting.create_plots       : [32mINFO    [0m Creating 1 plots of size 32, pool public key:  XXX farmer public key: XXX [0m
2021-04-24T16:55:27.276  chia.plotting.create_plots       : [32mINFO    [0m Memo: XXX[0m
2021-04-24T16:55:27.277  chia.plotting.create_plots       : [32mINFO    [0m Adding directory E:\ to harvester for farming [0m
2021-04-24T16:55:27.374  chia.plotting.create_plots       : [32mINFO    [0m Starting plot 1/1 [0m
Caught plotting error: Bitfield plotting not supported by CPU
[7936] Failed to execute script chia
Traceback (most recent call last):
  File "chia\cmds\chia.py", line 81, in <module>
  File "chia\cmds\chia.py", line 77, in main
  File "click\core.py", line 829, in __call__
  File "click\core.py", line 782, in main
  File "click\core.py", line 1259, in invoke
  File "click\core.py", line 1259, in invoke
  File "click\core.py", line 1066, in invoke
  File "click\core.py", line 610, in invoke
  File "click\decorators.py", line 21, in new_func
  File "chia\cmds\plots.py", line 135, in create_cmd
  File "chia\plotting\create_plots.py", line 176, in create_plots
RuntimeError: Unknown exception
```

**Expected behavior**
Delete Button enabled and ready to remove failed Plotting.
Info about the crashed plotter.

**Desktop (please complete the following information):**

- OS: Windows
- OS Version/Flavor: 10
- CPU: Hypvised Proxmox (Intel Core i5-8259U)

**Comment by hoffmang9** [comment]
This CPU is supported. This is usually an indicator of a hardware or file system problem. Sometimes it can be swap mis-configuration or RAM issues.

**Comment by Knight1** [comment]
If someone finds this, the Problem with Proxmox was that the CPU was "Common KVM Processor" not the Host CPU. You need to use this.

**Comment by Robin1631** [comment]
у меня такая же проблема, 2 день бьюсь. Можно конкретнее, куда нажимать?)

**Comment by Robin1631** [comment]
> Если кто-то обнаружит это, проблема с Proxmox заключалась в том, что ЦП был «общим процессором KVM», а не хост-процессором. Вам нужно это использовать. 

у меня такая же проблема, 2 день бьюсь. Можно конкретнее, куда нажимать?)
