### ISSUE TITLE
[BUG] [Errno 99] error while attempting to bind on address

### ISSUE THREAD

**Issue by s-a-p-i-e-n-s** [Chia-Network/chia-blockchain#2624]
I tried to write a dockerfile for Chia:

```
FROM ubuntu:20.04

# run updates
RUN apt-get update && apt-get upgrade -y && apt-get install git screen nano lsb-release sudo -y

# checkout and install chia
RUN git clone https://github.com/Chia-Network/chia-blockchain.git -b latest --recurse-submodules 
WORKDIR chia-blockchain
RUN chmod +x ./install.sh && sh install.sh 

# create mountpoints for ssd temporary storage and persistent hdd storage
WORKDIR /
RUN mkdir /ssd && mkdir /hdd

# copy over ".chia" folder if it exists in the build folder
COPY .chia /root/.chia

WORKDIR chia-blockchain

# manually activate virtual env (replaces the ". ./activate" command)
ENV VIRTUAL_ENV="/chia-blockchain/venv"
RUN python3 -m venv $VIRTUAL_ENV
ENV PATH="$VIRTUAL_ENV/bin:$PATH"

# run Chia init
RUN chia init
```
You can build it by running:

`sudo docker build -t chia-docker .`

You can login to the container by running:

`sudo docker run -it chia-docker`

Activate the Python environment in the container:

`. ./activate`

Trying to run the daemon or any command dependent on the daemon:

`chia run_daemon`

Unfortunately fails with:
`OSError: [Errno 99] error while attempting to bind on address ('::1', 55400, 0, 0): cannot assign requested address`

There is not much information why this error occurs, does anyone here have an idea?

**Comment by jdoerrer** [comment]
I found that is because the daemon is already running.

**Comment by s-a-p-i-e-n-s** [comment]
I don't think this is the issue, since trying to run `chia start node` fails with:
```
   raise OSError(err.errno, 'error while attempting '
OSError: [Errno 99] error while attempting to bind on address ('::1', 55400, 0, 0): cannot assign requested address
Daemon not started yet
Failed to create the chia daemon

```

**Comment by s-a-p-i-e-n-s** [comment]
The full output trying to run `chia start node`:
```
(venv) root@6a10ada33916:/chia-blockchain# chia start node
Daemon not started yet
Starting daemon
Traceback (most recent call last):
  File "/chia-blockchain/venv/bin/chia", line 33, in <module>
    sys.exit(load_entry_point('chia-blockchain', 'console_scripts', 'chia')())
  File "/chia-blockchain/chia/cmds/chia.py", line 77, in main
    cli()  # pylint: disable=no-value-for-parameter
  File "/chia-blockchain/venv/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/chia-blockchain/venv/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/chia-blockchain/venv/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/chia-blockchain/venv/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/chia-blockchain/venv/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/chia-blockchain/venv/lib/python3.8/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/chia-blockchain/chia/cmds/chia.py", line 60, in run_daemon_cmd
    asyncio.get_event_loop().run_until_complete(async_run_daemon(ctx.obj["root_path"]))
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/chia-blockchain/chia/daemon/server.py", line 944, in async_run_daemon
    await ws_server.start()
  File "/chia-blockchain/chia/daemon/server.py", line 138, in start
    self.websocket_server = await serve(
  File "/chia-blockchain/venv/lib/python3.8/site-packages/websockets/server.py", line 965, in __await_impl__
    server = await self._create_server()
  File "/usr/lib/python3.8/asyncio/base_events.py", line 1463, in create_server
    raise OSError(err.errno, 'error while attempting '
OSError: [Errno 99] error while attempting to bind on address ('::1', 55400, 0, 0): cannot assign requested address
Daemon not started yet
Failed to create the chia daemon

```

**Comment by s-a-p-i-e-n-s** [comment]
I went though the code and ended up in the `.chia/mainnet/config/config.yaml`.

Since this whole issue seems to be related to something around localhost not being resolves I changed the line containing:
`self_hostname: &self_hostname "localhost"`
to
`self_hostname: &self_hostname "127.0.0.1"`
and `chia start node` successfully starts.
