### ISSUE TITLE
[BUG] RuntimeError: bad allocation

### ISSUE THREAD

**Issue by Evil0ctal** [Chia-Network/chia-blockchain#2643]
**Describe the bug**
RuntimeError: bad allocation druing ploting

**Detail**
Starting phase 1/4: Forward Propagation into tmp files... Sat Apr 24 14:00:20 2021
Computing table 1
F1 complete, time: 215.981 seconds. CPU (161.83%) Sat Apr 24 14:03:56 2021
Computing table 2
Caught plotting error: bad allocation
[20960] Failed to execute script chia
Traceback (most recent call last):
  File "chia\cmds\chia.py", line 81, in <module>
  File "chia\cmds\chia.py", line 77, in main
  File "click\core.py", line 829, in __call__
  File "click\core.py", line 782, in main
  File "click\core.py", line 1259, in invoke
  File "click\core.py", line 1259, in invoke
  File "click\core.py", line 1066, in invoke
  File "click\core.py", line 610, in invoke
  File "click\decorators.py", line 21, in new_func
  File "chia\cmds\plots.py", line 135, in create_cmd
  File "chia\plotting\create_plots.py", line 176, in create_plots
RuntimeError: bad allocation

- OS: [Windows]
- OS Version/Flavor: [win10 pro]
- CPU: [I7 6800K]

**Comment by hoffmang9** [comment]
https://github.com/Chia-Network/chia-blockchain/wiki/FAQ#my-plotting-attempt-ended-with-runtimeerror-bad-allocation
