### ISSUE TITLE
[BUG] "Failed to execute script chia", the progress stop a 1%

### ISSUE THREAD

**Issue by sx5486510** [Chia-Network/chia-blockchain#2656]
**Describe the bug**
This is the log:
[2216] Failed to execute script chia
Traceback (most recent call last):
  File "chia\cmds\chia.py", line 81, in <module>
  File "chia\cmds\chia.py", line 77, in main
  File "click\core.py", line 829, in __call__
  File "click\core.py", line 782, in main
  File "click\core.py", line 1259, in invoke
  File "click\core.py", line 1259, in invoke
  File "click\core.py", line 1066, in invoke
  File "click\core.py", line 610, in invoke
  File "click\decorators.py", line 21, in new_func
  File "chia\cmds\plots.py", line 135, in create_cmd
  File "chia\plotting\create_plots.py", line 48, in create_plots
  File "chia\util\config.py", line 55, in load_config
  File "yaml\__init__.py", line 162, in safe_load
  File "yaml\__init__.py", line 114, in load
  File "yaml\constructor.py", line 49, in get_single_data
  File "yaml\composer.py", line 36, in get_single_node
  File "yaml\composer.py", line 55, in compose_document
  File "yaml\composer.py", line 84, in compose_node
  File "yaml\composer.py", line 133, in compose_mapping_node
  File "yaml\composer.py", line 84, in compose_node
  File "yaml\composer.py", line 127, in compose_mapping_node
  File "yaml\parser.py", line 98, in check_event
  File "yaml\parser.py", line 428, in parse_block_mapping_key
  File "yaml\scanner.py", line 115, in check_token
  File "yaml\scanner.py", line 152, in need_more_tokens
  File "yaml\scanner.py", line 292, in stale_possible_simple_keys
yaml.scanner.ScannerError: while scanning a simple key
  in "C:\Users\user\.chia\mainnet\config\config.yaml", line 267, column 1
could not find expected ':'
  in "C:\Users\user\.chia\mainnet\config\config.yaml", line 268, column 1

this is the yaml
![image](https://user-images.githubusercontent.com/13346232/115979284-91e16c80-a5b7-11eb-81f0-9c25f5d4b04c.png)

**Desktop (please complete the following information):**

- OS: Windows 10
- CPU: E5 2680V2

**Comment by juliootoni** [comment]
Realizei esse procedimento
https://www.youtube.com/watch?v=5aMhDfJyRsw&ab_channel=TrabalheeVen%C3%A7a

**Comment by JaydenWade** [comment]
Have the same problem.
