### ISSUE TITLE
[BUG] wallet can not add blocks

### ISSUE THREAD

**Issue by mqliang** [Chia-Network/chia-blockchain#2673]
**Describe the bug**
```
2021-04-24T23:34:20.877 wallet chia.wallet.wallet_blockchain: ERROR    Error during db transaction:
2021-04-24T23:34:20.883 wallet chia.wallet.wallet_node    : ERROR    Error while trying to fetch from peer:no active connection Traceback (most recent call last):
  File "/home/mqliang/chia-blockchain/chia/wallet/wallet_blockchain.py", line 217, in receive_block
    await self.block_store.add_block_record(header_block_record, block_record)
  File "/home/mqliang/chia-blockchain/chia/wallet/wallet_block_store.py", line 80, in add_block_record
    cursor = await self.db.execute(
  File "/home/mqliang/chia-blockchain/venv/lib/python3.8/site-packages/aiosqlite/core.py", line 184, in execute
    cursor = await self._execute(self._conn.execute, sql, parameters)
  File "/home/mqliang/chia-blockchain/venv/lib/python3.8/site-packages/aiosqlite/core.py", line 129, in _execute
    return await future
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mqliang/chia-blockchain/chia/wallet/wallet_node.py", line 595, in _sync
    added, advanced_peak = await self.fetch_blocks_and_validate(
  File "/home/mqliang/chia-blockchain/chia/wallet/wallet_node.py", line 682, in fetch_blocks_and_validate
    (result, error, fork_h,) = await self.wallet_state_manager.blockchain.receive_block(
  File "/home/mqliang/chia-blockchain/chia/wallet/wallet_blockchain.py", line 225, in receive_block
    await self.block_store.db_wrapper.rollback_transaction()
  File "/home/mqliang/chia-blockchain/chia/util/db_wrapper.py", line 24, in rollback_transaction
    if self.db.in_transaction:
  File "/home/mqliang/chia-blockchain/venv/lib/python3.8/site-packages/aiosqlite/core.py", line 258, in in_transaction
    return self._conn.in_transaction
  File "/home/mqliang/chia-blockchain/venv/lib/python3.8/site-packages/aiosqlite/core.py", line 67, in _conn
    raise ValueError("no active connection")
ValueError: no active connection

2021-04-24T23:34:20.883 wallet chia.wallet.wallet_node    : ERROR    Loop exception in sync Was not able to add blocks 153988-154020. Traceback (most recent call last):
  File "/home/mqliang/chia-blockchain/chia/wallet/wallet_node.py", line 508, in sync_job
    await self._sync()
  File "/home/mqliang/chia-blockchain/chia/wallet/wallet_node.py", line 605, in _sync
    raise RuntimeError(f"Was not able to add blocks {start_height}-{end_height}")
RuntimeError: Was not able to add blocks 153988-154020
```

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

- OS: [e.g. Linux]
- OS Version/Flavor: [e.g. CentOS 7.2]
- CPU: [e.g. Intel Xeon 8175M]

**Additional context**

**Comment by royimous** [comment]
Why do you think anyone is going to help you with your issue when you won't take the time to fill out the bug reporting template?
