### ISSUE TITLE
windows 10 RPC  ===>    500 Internal Server Error

### ISSUE THREAD

**Issue by cnwendaosi** [Chia-Network/chia-blockchain#2787]
curl --insecure --cert %HOMEPATH%\.chia\mainnet\config\ssl\full_node\private_full_node.crt --key %HOMEPATH%\.chia\mainnet\config\ssl\full_node\private_full_node.key -d '{"":""}' -H "Content-Type: application/json" -X POST https://localhost:8555/get_blockchain_state

500 Internal Server Error
Server got itself in trouble

**Comment by cnwendaosi** [comment]
Ubuntu下是没问题的，windows下不能访问RPC,提示错误，请问如何解决？

**Comment by justinphelps** [comment]
Also having this issue. 
Debug logs: 

2021-05-03T22:00:55.094 full_node aiohttp.server          : ERROR    Error handling request
Traceback (most recent call last):
  File "/home/chia/chia-blockchain/venv/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 422, in _handle_request
    resp = await self._request_handler(request)
  File "/home/chia/chia-blockchain/venv/lib/python3.9/site-packages/aiohttp/web_app.py", line 499, in _handle
    resp = await handler(request)
  File "/home/chia/chia-blockchain/chia/rpc/rpc_server.py", line 79, in inner
    request_data = await request.json()
  File "/home/chia/chia-blockchain/venv/lib/python3.9/site-packages/aiohttp/web_request.py", line 614, in json
    return loads(body)
  File "/usr/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2021-05-03T22:00:55.192 farmer farmer_server              : DEBUG    Rate l

**Comment by TaylorWenOne** [comment]
So did you fix problem,guys?

**Comment by TaylorWenOne** [comment]
> Also having this issue. Debug logs:
> 
> 2021-05-03T22:00:55.094 full_node aiohttp.server : ERROR Error handling request Traceback (most recent call last): File "/home/chia/chia-blockchain/venv/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 422, in _handle_request resp = await self._request_handler(request) File "/home/chia/chia-blockchain/venv/lib/python3.9/site-packages/aiohttp/web_app.py", line 499, in _handle resp = await handler(request) File "/home/chia/chia-blockchain/chia/rpc/rpc_server.py", line 79, in inner request_data = await request.json() File "/home/chia/chia-blockchain/venv/lib/python3.9/site-packages/aiohttp/web_request.py", line 614, in json return loads(body) File "/usr/lib/python3.9/json/**init**.py", line 346, in loads return _default_decoder.decode(s) File "/usr/lib/python3.9/json/decoder.py", line 337, in decode obj, end = self.raw_decode(s, idx=_w(s, 0).end()) File "/usr/lib/python3.9/json/decoder.py", line 355, in raw_decode raise JSONDecodeError("Expecting value", s, err.value) from None json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0) 2021-05-03T22:00:55.192 farmer farmer_server : DEBUG Rate l

hi,mate,did you fix the problem
