### ISSUE TITLE
[BUG] 1.1.2 Last Attempted Proof Stops

### ISSUE THREAD

**Issue by akeslo** [Chia-Network/chia-blockchain#2790]
**Describe the bug**
After hours of farming via the Chia 1.1.0 GUI on Mac, the "Last Attempted Proof" section stops updating which appears to indicate farming has stopped.  "Last Attempted Proof" section shows proofs from hours earlier and the only way to restart/resolve is to close and reopen the GUI.

**To Reproduce**
1. Open Chia GUI
2. Farm
3. Wait

**Expected behavior**
Uninterrupted Farming

**Screenshots**
![Not updated](https://user-images.githubusercontent.com/3003773/116083043-299f9300-a66a-11eb-880b-c4c884def45f.png)

**Desktop (please complete the following information):**

- OS: OSx
- OS Version/Flavor: 10.15.17
- CPU: i7 6700

**Additional context**
Seeing the following in the error log at about the time this happens:
```
2021-04-26T08:14:40.481 farmer farmer_server              : INFO     Connection closed: 127.0.0.1, node id: 9xxxxxxxx0b697935ace0xxxxx8e2
2021-04-26T08:14:40.482 farmer chia.farmer.farmer         : INFO     peer disconnected None
2021-04-26T08:14:40.485 daemon __main__                   : INFO     Websocket exception. Closing websocket with chia_harvester code = 1006 (connection closed abnormally [internal]), no reason Traceback (most recent call last):
  File "websockets/protocol.py", line 827, in transfer_data
  File "websockets/protocol.py", line 895, in read_message
  File "websockets/protocol.py", line 971, in read_data_frame
  File "websockets/protocol.py", line 1047, in read_frame
  File "websockets/framing.py", line 105, in read
  File "asyncio/streams.py", line 721, in readexactly
asyncio.exceptions.IncompleteReadError: 0 bytes read on a total of 2 expected bytes

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "chia/daemon/server.py", line 167, in safe_handle
  File "websockets/protocol.py", line 439, in __aiter__
  File "websockets/protocol.py", line 509, in recv
  File "websockets/protocol.py", line 803, in ensure_open
websockets.exceptions.ConnectionClosedError: code = 1006 (connection closed abnormally [internal]), no reason
```

**Edit: Updated title to 1.1.2 as I am experiencing the same issue after upgrade.**

**Comment by maomingyang1314** [comment]
Please update to version 1.1.2

**Comment by gs517** [comment]
> Please update to version 1.1.2

i have the same problem
version 1.1.2

`2021-04-26T15:50:14.884 daemon __main__                   : ERROR    Unexpected exception trying to send to websocket: code = 1006 (connection closed abnormally [internal]), no reason Traceback (most recent call last):
  File "chia\daemon\server.py", line 182, in safe_handle
  File "websockets\protocol.py", line 555, in send
  File "websockets\protocol.py", line 803, in ensure_open
websockets.exceptions.ConnectionClosedError: code = 1006 (connection closed abnormally [internal]), no reason


2021-04-26T15:52:18.079 full_node chia.rpc.rpc_server     : WARNING  Sending data failed. Exception Traceback (most recent call last):
  File "chia\rpc\rpc_server.py", line 67, in _state_changed
  File "aiohttp\client_ws.py", line 150, in send_str
  File "aiohttp\http_websocket.py", line 687, in send
  File "aiohttp\http_websocket.py", line 643, in _send_frame
  File "aiohttp\http_websocket.py", line 660, in _write
ConnectionResetError: Cannot write to closing transport`

![image](https://user-images.githubusercontent.com/83224749/116088266-254f9600-a6bb-11eb-96c8-05a64a3d8601.png)

**Comment by akeslo** [comment]
> Please update to version 1.1.2

I just upgraded and I'm seeing the exact same behavior

**Comment by gs517** [comment]
I run the dam ploting the CLI, this solved my problem
the main GUI client has been working for a day without errors

**Comment by akeslo** [comment]
> I run the dam ploting the CLI, this solved my problem
> the main GUI client has been working for a day without errors

I've done this as well - it helps and seems to allow farming to run for longer without being interrupted however the issue still occurs after enough time.

**Comment by Alqueraf** [comment]
I'm experiencing the same issue on 1.1.3 with an Ubuntu farming machine.
Need to manually restart the GUI.
Also switching to the "Keys" tab, selecting my key, and going back to the "Farm" tab works as well. 😟

**Comment by comquer77** [comment]
experiencing the same on ver. 1.1.5, 1.1.6 and 1.1.7!!!!!  what the xxxx!
