### ISSUE TITLE
 plotting error with Permission denied

### ISSUE THREAD

**Issue by FLIW1979** [Chia-Network/chia-blockchain#2806]
When I creating a new plot on my computer that it failed with Permission denied shown as below.
I tried to relax the permission on both C drive and D drive but still failed.
Could you help me to resolve the problem? thank you very much.

CPU: Intel(R) Xeon(R) CPU E5-2640 v3 @ 2.60GHz
RAM: 128GB 
OS: Windows 10 Pro x64

Starting plotting progress into temporary dirs: C:\ and C:\
ID: 45bf4f51beaec31b5f5b77fa65159b95f77e89e6a8a8ae1fa6c320a99d16e901
Plot size is: 32
Buffer size is: 16384MiB
Using 128 buckets
Using 2 threads of stripe size 65536
Caught plotting error: Could not open C:\plot-k32-2021-04-26-22-23-45bf4f51beaec31b5f5b77fa65159b95f77e89e6a8a8ae1fa6c320a99d16e901.plot.sort.tmp: Permission denied.
[10280] Failed to execute script chia
Traceback (most recent call last):
  File "chia\cmds\chia.py", line 81, in <module>
  File "chia\cmds\chia.py", line 77, in main
  File "click\core.py", line 829, in __call__
  File "click\core.py", line 782, in main
  File "click\core.py", line 1259, in invoke
  File "click\core.py", line 1259, in invoke
  File "click\core.py", line 1066, in invoke
  File "click\core.py", line 610, in invoke
  File "click\decorators.py", line 21, in new_func
  File "chia\cmds\plots.py", line 135, in create_cmd
  File "chia\plotting\create_plots.py", line 176, in create_plots
RuntimeError: Unknown exception

**Comment by hoffmang9** [comment]
Something is wrong with your file system.

**Comment by FLIW1979** [comment]
> Something is wrong with your file system.

Dear Hoffmang9,

could you give me more information about what went wrong on my file system?

**Comment by dorkmo** [comment]
dont plot into the top level of your drive, make a folder and plot into it.  D:/temp/
