### ISSUE TITLE
[BUG] Unexpected exception trying to send to websocket: code = 1006 (connection closed abnormally [internal])

### ISSUE THREAD

**Issue by ArrayZoneYour** [Chia-Network/chia-blockchain#2810]
**Describe the bug**
 Unexpected exception trying to send to websocket: code = 1006 (connection closed abnormally [internal])

**To Reproduce**

1. `npm run electron &`
2. Wait about 3~5 hours
3. chia daemon exit 

**Expected behavior**
Working fine

**Screenshots**
![Screenshot from 2021-04-26 22-57-52](https://user-images.githubusercontent.com/21001457/116104236-dc133c80-a6e2-11eb-9a3e-3761ce63391b.png)

**Desktop (please complete the following information):**

- OS: Linux
- OS Version/Flavor: Ubuntu 20.04
- CPU: 5950X

**Additional context**

`debug.log`

```
  File "/home/chia-miner/chia-blockchain/venv/lib/python3.8/site-packages/websockets/protocol.py", line 827, in transfer_data
    message = await self.read_message()
  File "/home/chia-miner/chia-blockchain/venv/lib/python3.8/site-packages/websockets/protocol.py", line 895, in read_message
    frame = await self.read_data_frame(max_size=self.max_size)
  File "/home/chia-miner/chia-blockchain/venv/lib/python3.8/site-packages/websockets/protocol.py", line 971, in read_data_frame
    frame = await self.read_frame(max_size)
  File "/home/chia-miner/chia-blockchain/venv/lib/python3.8/site-packages/websockets/protocol.py", line 1047, in read_frame
    frame = await Frame.read(
  File "/home/chia-miner/chia-blockchain/venv/lib/python3.8/site-packages/websockets/framing.py", line 105, in read
    data = await reader(2)
  File "/usr/lib/python3.8/asyncio/streams.py", line 721, in readexactly
    raise exceptions.IncompleteReadError(incomplete, n)
asyncio.exceptions.IncompleteReadError: 0 bytes read on a total of 2 expected bytes

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/chia-miner/chia-blockchain/chia/daemon/server.py", line 182, in safe_handle
    await socket.send(response)
  File "/home/chia-miner/chia-blockchain/venv/lib/python3.8/site-packages/websockets/protocol.py", line 555, in send
    await self.ensure_open()
  File "/home/chia-miner/chia-blockchain/venv/lib/python3.8/site-packages/websockets/protocol.py", line 803, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedError: code = 1006 (connection closed abnormally [internal]), no reason

2021-04-26T22:49:52.481 daemon chia.daemon.server         : INFO     Websocket exception. Closing websocket with chia_harvester code = 1006 (connection closed abnormally [internal]), no reason Traceback (most recent call last):
  File "/home/chia-miner/chia-blockchain/venv/lib/python3.8/site-packages/websockets/protocol.py", line 827, in transfer_data
    message = await self.read_message()
  File "/home/chia-miner/chia-blockchain/venv/lib/python3.8/site-packages/websockets/protocol.py", line 895, in read_message
    frame = await self.read_data_frame(max_size=self.max_size)
  File "/home/chia-miner/chia-blockchain/venv/lib/python3.8/site-packages/websockets/protocol.py", line 971, in read_data_frame
    frame = await self.read_frame(max_size)
  File "/home/chia-miner/chia-blockchain/venv/lib/python3.8/site-packages/websockets/protocol.py", line 1047, in read_frame
    frame = await Frame.read(
  File "/home/chia-miner/chia-blockchain/venv/lib/python3.8/site-packages/websockets/framing.py", line 105, in read
    data = await reader(2)
  File "/usr/lib/python3.8/asyncio/streams.py", line 723, in readexactly
    await self._wait_for_data('readexactly')
  File "/usr/lib/python3.8/asyncio/streams.py", line 517, in _wait_for_data
    await self._waiter
  File "/usr/lib/python3.8/asyncio/selector_events.py", line 846, in _read_ready__data_received
    data = self._sock.recv(self.max_size)
ConnectionResetError: [Errno 104] Connection reset by peer

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/chia-miner/chia-blockchain/chia/daemon/server.py", line 167, in safe_handle
    async for message in websocket:
  File "/home/chia-miner/chia-blockchain/venv/lib/python3.8/site-packages/websockets/protocol.py", line 439, in __aiter__
    yield await self.recv()
  File "/home/chia-miner/chia-blockchain/venv/lib/python3.8/site-packages/websockets/protocol.py", line 509, in recv
    await self.ensure_open()
  File "/home/chia-miner/chia-blockchain/venv/lib/python3.8/site-packages/websockets/protocol.py", line 803, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedError: code = 1006 (connection closed abnormally [internal]), no reason

2021-04-26T22:49:52.481 daemon chia.daemon.server         : INFO     Websocket exception. Closing websocket with Unknown code = 1006 (connection closed abnormally [internal]), no reason Traceback (most recent call last):
  File "/home/chia-miner/chia-blockchain/venv/lib/python3.8/site-packages/websockets/protocol.py", line 827, in transfer_data
    message = await self.read_message()
  File "/home/chia-miner/chia-blockchain/venv/lib/python3.8/site-packages/websockets/protocol.py", line 895, in read_message
    frame = await self.read_data_frame(max_size=self.max_size)
  File "/home/chia-miner/chia-blockchain/venv/lib/python3.8/site-packages/websockets/protocol.py", line 971, in read_data_frame
    frame = await self.read_frame(max_size)
  File "/home/chia-miner/chia-blockchain/venv/lib/python3.8/site-packages/websockets/protocol.py", line 1047, in read_frame
    frame = await Frame.read(
  File "/home/chia-miner/chia-blockchain/venv/lib/python3.8/site-packages/websockets/framing.py", line 105, in read
    data = await reader(2)
  File "/usr/lib/python3.8/asyncio/streams.py", line 721, in readexactly
    raise exceptions.IncompleteReadError(incomplete, n)
asyncio.exceptions.IncompleteReadError: 0 bytes read on a total of 2 expected bytes

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/chia-miner/chia-blockchain/chia/daemon/server.py", line 167, in safe_handle
    async for message in websocket:
  File "/home/chia-miner/chia-blockchain/venv/lib/python3.8/site-packages/websockets/protocol.py", line 439, in __aiter__
    yield await self.recv()
  File "/home/chia-miner/chia-blockchain/venv/lib/python3.8/site-packages/websockets/protocol.py", line 509, in recv
    await self.ensure_open()
  File "/home/chia-miner/chia-blockchain/venv/lib/python3.8/site-packages/websockets/protocol.py", line 803, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedError: code = 1006 (connection closed abnormally [internal]), no reason

2021-04-26T22:49:52.482 daemon chia.daemon.server         : INFO     Daemon WebSocketServer closed
```

**Comment by sargonas** [comment]
My logs are also flooded with these.... its to the point that it's rolling over logs due to the file size limit every few hours. In a 12 hour period it generated 7x 20MB logs of nothing but this error repeatedly over and over.

I've tried rebooting, as well as fully restarting my services several times. The only difference from above is my python version referenced is 3/9 (due to Ubuntu 21.04) but otherwise same as the above from what I can see. It's been driving me nuts!

**Comment by sargonas** [comment]
@ArrayZoneYour are you still having this issue? After a few reboots and fresh-restarts it went away for me today and has not come back since. I've not been able to reproduce it since, so I'm writing my own issue off on being an OS issue.

**Comment by ArrayZoneYour** [comment]
@sargonas My drive has been disconnect during farming. I think one broken drive will raise the exception above. I've not meet the issue after I remove the unstable portable hare drive.

**Comment by Underdoge** [comment]
I'm also having this issue. Will try restarting later. I'm on macOS Big Sur 11.3.1, npm 16.1.0

**Comment by sargonas** [comment]
reboots seem to consistently fix this for everyone I have spoken to, myself included. It appears to be a problem with the OS/python holding up sockets (or ghost processes doing so) and simply needing a refresh.

**Comment by Underdoge** [comment]
Unfortunately I just restarted and it started happening again. Any other ideas besides restarting?

**Comment by noisymime** [comment]
Same problem here as well (Ubuntu 18.04 / python 3.6.9). Rebooting helps for maybe 10 minutes, then the errors start flooding the logs again.

**Comment by gogito** [comment]
> 
> 
> reboots seem to consistently fix this for everyone I have spoken to, myself included. It appears to be a problem with the OS/python holding up sockets (or ghost processes doing so) and simply needing a refresh.

But will it affect farming in anyway?

**Comment by noisymime** [comment]
> But will it affect farming in anyway?

I've been playing with this and as best as I can tell, the answer is Yes. When this starts occurring in the logs I see my response times grow dramatically, going from around 1000ms at most to averages of 17000ms and maximums well above 50000ms. I can't confirm for certain that it's impacting farming, but that seems worrying. 

Just for reference, you don't need to restart your whole machine to resolve this, you can do (Note the `-d` as you must restart the daemon itself:
```
chia stop -d all
chia start harvester
```

The issue here is in `daemon/server.py` and seems to be as a result of the high value used for `ping_interval` on the websocket (500). From everything I've read 500 (Just over 8 minutes) is far too high and can result in these broken sockets, particularly with some NAT setups. I've adjusted the value to 20 and am not seeing the issue reoccurring yet.

20s seems to be a much more sensible value and will not impose any significant overhead on either the client or server. 

@ArrayZoneYour I think this issue needs to be looked at more seriously. Could you please reopen this issue? (Or if not I'll raise a new one with these findings as there still seems to be an issue).

**Comment by gogito** [comment]
> > But will it affect farming in anyway?
> 
> I've been playing with this and as best as I can tell, the answer is Yes. When this starts occurring in the logs I see my response times grow dramatically, going from around 1000ms at most to averages of 17000ms and maximums well above 50000ms. I can't confirm for certain that it's impacting farming, but that seems worrying.
> 
> Just for reference, you don't need to restart your whole machine to resolve this, you can do the following (Note the `-d` as you must restart the daemon itself):
> 
> ```
> chia stop -d all
> chia start harvester
> ```
> 
> The issue here is in `daemon/server.py` and seems to be as a result of the high value used for `ping_interval` on the websocket (500). From everything I've read 500 (Just over 8 minutes) is far too high and can result in these broken sockets, particularly with some NAT setups. I've adjusted the value to 20 and am not seeing the issue reoccurring yet.
> 
> 20s seems to be a much more sensible value and will not impose any significant overhead on either the client or server.
> 
> @ArrayZoneYour I think this issue needs to be looked at more seriously. Could you please reopen this issue? (Or if not I'll raise a new one with these findings as there still seems to be an issue).

Hmmmmm how do you check the response time? I want to check and see it myself and if I have any good information to contribute since I run into this a lot.

**Comment by Romijoxx** [comment]
Is it possible to run:
chia stop -d all
chia start harvester

during plotting?

**Comment by noisymime** [comment]
> during plotting?

Yes, it's fine.

**Comment by dorofino** [comment]
Can anyone explain exactly how to fix this?

Is this a bug, a configuration issue, or what?

**Comment by sargonas** [comment]
It appears to be a case of your operating system and python collectively not cleaning up after themselves, and leaving certain sockets in use after the programs terminate processes uncleanly. For the time being the only practical solution is to simply reboot your system.

**Comment by dorofino** [comment]
> It appears to be a case of your operating system and python collectively not cleaning up after themselves, and leaving certain sockets in use after the programs terminate processes uncleanly. For the time being the only practical solution is to simply first try to restart your chia daemon and if that fails to address it then reboot your system.

Great, that makes sense.
Does this affect farming?

**Comment by GeorgePapageorgakis** [comment]
This is not fixed yet. Reopen the issue plz.

**Comment by noisymime** [comment]
I submitted a PR that I believe resolves this (#6305), but if others can test to see whether it fixes this for them also that would be good.

**Comment by winkee01** [comment]
This bug still exists, my log file are full of this error message

**Comment by aarcro** [comment]
I don't know that the ping voodoo fix is related to what I'm seeing. I made this change:

```
diff --git a/chia/daemon/server.py b/chia/daemon/server.py
index 099f987d..808a117e 100644
--- a/chia/daemon/server.py
+++ b/chia/daemon/server.py
@@ -187,7 +187,7 @@ class WebSocketServer:
                             await socket.send(response)
                         except Exception as e:
                             tb = traceback.format_exc()
-                            self.log.error(f"Unexpected exception trying to send to websocket: {e} {tb}")
+                            self.log.error(f"Unexpected exception trying to send to websocket: {e} {tb}\n\nresponse: {response}")
                             self.remove_connection(socket)
                             await socket.close()
         except Exception as e:
```

And I can see that the failed destination is wallet_ui every time. Only problem is I'm not run the GUI, and I haven't ever been since the last reboot (I'm running without X now anyway).

For me it does seem harmless, but also pointlessly filling the logs. How can it be trying to send a response to wallet_ui, when the wallet_ui shouldn't even be running?

**Comment by lwloo** [comment]
A few reboot doesn't solve my issue, I did a sudo apt upgrade and seems like it fixed the issue.

**Comment by khituras** [comment]
I have this very issue since August 27th. Before that everything was perfectly fine. On the 20th I went to vacation from which I returned on the 30th. I did not even look at my Chia setup during my vacation time. In my pool logs I then saw that I don't send any shares any more since the 27th.
I updated Chia to the latest version the day before yesterday.
I did reboot the machine and started chia again, it worked for a few hours, then the same error appeared. Another reboot yesterday and now I see that error again. It wouldn't run straight for a single day currently.

**Comment by lidangqi** [comment]
1.2.5 version throws websocket 1006 every few minutes

```
2021-09-01T11:22:10.810 daemon chia.daemon.server         : INFO     Websocket exception. Closing websocket with chia_farmer code = 1006 (connection closed abnormally [internal]), no reason Traceback (most recent call last):
  File "/opt/chia-1.2.5/lib/python3.9/site-packages/websockets/protocol.py", line 827, in transfer_data
    message = await self.read_message()
  File "/opt/chia-1.2.5/lib/python3.9/site-packages/websockets/protocol.py", line 895, in read_message
    frame = await self.read_data_frame(max_size=self.max_size)
  File "/opt/chia-1.2.5/lib/python3.9/site-packages/websockets/protocol.py", line 971, in read_data_frame
    frame = await self.read_frame(max_size)
  File "/opt/chia-1.2.5/lib/python3.9/site-packages/websockets/protocol.py", line 1047, in read_frame
    frame = await Frame.read(
  File "/opt/chia-1.2.5/lib/python3.9/site-packages/websockets/framing.py", line 126, in read
    raise PayloadTooBig(
websockets.exceptions.PayloadTooBig: payload length exceeds size limit (53139578 > 50000000 bytes)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/chia-1.2.5/lib/python3.9/site-packages/chia/daemon/server.py", line 190, in safe_handle
    async for message in websocket:
  File "/opt/chia-1.2.5/lib/python3.9/site-packages/websockets/protocol.py", line 439, in __aiter__
    yield await self.recv()
  File "/opt/chia-1.2.5/lib/python3.9/site-packages/websockets/protocol.py", line 509, in recv
    await self.ensure_open()
  File "/opt/chia-1.2.5/lib/python3.9/site-packages/websockets/protocol.py", line 812, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedError: code = 1006 (connection closed abnormally [internal]), no reason

2021-09-01T11:22:10.813 farmer chia.rpc.rpc_server        : WARNING  Sending data failed. Exception Traceback (most recent call last):
  File "/opt/chia-1.2.5/lib/python3.9/site-packages/chia/rpc/rpc_server.py", line 69, in _state_changed
    await self.websocket.send_str(dict_to_json_str(payload))
  File "/opt/chia-1.2.5/lib/python3.9/site-packages/aiohttp/client_ws.py", line 150, in send_str
    await self._writer.send(data, binary=False, compress=compress)
  File "/opt/chia-1.2.5/lib/python3.9/site-packages/aiohttp/http_websocket.py", line 687, in send
    await self._send_frame(message, WSMsgType.TEXT, compress)
  File "/opt/chia-1.2.5/lib/python3.9/site-packages/aiohttp/http_websocket.py", line 656, in _send_frame
    await self.protocol._drain_helper()
  File "/opt/chia-1.2.5/lib/python3.9/site-packages/aiohttp/base_protocol.py", line 87, in _drain_helper
    await waiter
aiohttp.client_exceptions.ClientOSError: [Errno 104] Connection reset by peer
```

**Comment by w0lv3r1nix** [comment]
Yes, same here,

Tried different branches, latest and main:
````
2021-09-07T20:45:41.285 daemon chia.daemon.server         : INFO     Websocket exception. Closing websocket with chia_harvester code = 1006 (connection closed abnormally [internal]), no reason Traceback (most recent call last):
  File "/home/chia/chia-blockchain/venv/lib/python3.8/site-packages/websockets/protocol.py", line 827, in transfer_data
    message = await self.read_message()
  File "/home/chia/chia-blockchain/venv/lib/python3.8/site-packages/websockets/protocol.py", line 895, in read_message
    frame = await self.read_data_frame(max_size=self.max_size)
  File "/home/chia/chia-blockchain/venv/lib/python3.8/site-packages/websockets/protocol.py", line 971, in read_data_frame
    frame = await self.read_frame(max_size)
  File "/home/chia/chia-blockchain/venv/lib/python3.8/site-packages/websockets/protocol.py", line 1047, in read_frame
    frame = await Frame.read(
  File "/home/chia/chia-blockchain/venv/lib/python3.8/site-packages/websockets/framing.py", line 105, in read
    data = await reader(2)
  File "/usr/lib/python3.8/asyncio/streams.py", line 721, in readexactly
    raise exceptions.IncompleteReadError(incomplete, n)
asyncio.exceptions.IncompleteReadError: 0 bytes read on a total of 2 expected bytes

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/chia/chia-blockchain/chia/daemon/server.py", line 191, in safe_handle
    async for message in websocket:
  File "/home/chia/chia-blockchain/venv/lib/python3.8/site-packages/websockets/protocol.py", line 439, in __aiter__
    yield await self.recv()
  File "/home/chia/chia-blockchain/venv/lib/python3.8/site-packages/websockets/protocol.py", line 509, in recv
    await self.ensure_open()
  File "/home/chia/chia-blockchain/venv/lib/python3.8/site-packages/websockets/protocol.py", line 803, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedError: code = 1006 (connection closed abnormally [internal]), no reason
````

**Comment by waylonwang** [comment]
The official docker container (chia version is 1.2.11) has the same error. This error will cause port 8555 to fail. I cannot view the current full node status through the chia show -sc command. If you delete the database in the mainnet/db directory, restart After the system re-synchronized the full node, there would be no such problem, but after I tried to restart the full node service when I synchronized to a height of 80,000+, the problem occurred again.

**Comment by fritol** [comment]
> > But will it affect farming in anyway?
> 
> I've been playing with this and as best as I can tell, the answer is Yes. When this starts occurring in the logs I see my response times grow dramatically, going from around 1000ms at most to averages of 17000ms and maximums well above 50000ms. I can't confirm for certain that it's impacting farming, but that seems worrying.
> 
> Just for reference, you don't need to restart your whole machine to resolve this, you can do the following (Note the `-d` as you must restart the daemon itself):
> 
> ```
> chia stop -d all
> chia start harvester
> ```
> 
> The issue here is in `daemon/server.py` and seems to be as a result of the high value used for `ping_interval` on the websocket (500). From everything I've read 500 seconds (Just over 8 minutes) is far too high and can result in these broken sockets, particularly with some NAT setups. I've adjusted the value to 20 and am not seeing the issue reoccurring yet.
> 
> 20s seems to be a much more sensible value and will not impose any significant overhead on either the client or server.
> 
> @ArrayZoneYour I think this issue needs to be looked at more seriously. Could you please reopen this issue? (Or if not I'll raise a new one with these findings as there still seems to be an issue).

am testing this now! I will update in a few days as the farmer usually last about 2-3 days until it hits this error and stops harvesting.

**Comment by fritol** [comment]
> > > But will it affect farming in anyway?
> > 
> > 
> > I've been playing with this and as best as I can tell, the answer is Yes. When this starts occurring in the logs I see my response times grow dramatically, going from around 1000ms at most to averages of 17000ms and maximums well above 50000ms. I can't confirm for certain that it's impacting farming, but that seems worrying.
> > Just for reference, you don't need to restart your whole machine to resolve this, you can do the following (Note the `-d` as you must restart the daemon itself):
> > ```
> > chia stop -d all
> > chia start harvester
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > The issue here is in `daemon/server.py` and seems to be as a result of the high value used for `ping_interval` on the websocket (500). From everything I've read 500 seconds (Just over 8 minutes) is far too high and can result in these broken sockets, particularly with some NAT setups. I've adjusted the value to 20 and am not seeing the issue reoccurring yet.
> > 20s seems to be a much more sensible value and will not impose any significant overhead on either the client or server.
> > @ArrayZoneYour I think this issue needs to be looked at more seriously. Could you please reopen this issue? (Or if not I'll raise a new one with these findings as there still seems to be an issue).
> 
> am testing this now! I will update in a few days as the farmer usually last about 2-3 days until it hits this error and stops harvesting.

that did NOT solve anything still the same websocket error

**Comment by baerrs** [comment]
I'm having this issue too.  I see this is closed, is there a corrective action that I'm not seeing ?

**Comment by winkee01** [comment]
> I'm having this issue too. I see this is closed, is there a corrective action that I'm not seeing?

yes, just restart solve the problem.

**Comment by baerrs** [comment]
winkee01 thank you for responding.  I have restarted this, but means I would need to restart this about 10 times every day.  This doesn't seem to fix the issue but is a workaround.  And I will keep doing this.. just wanted to know if a fix is out there, or being worked on?
