### ISSUE TITLE
Caught plotting error: Bitfield plotting not supported by CPU [BUG]

### ISSUE THREAD

**Issue by Eustor** [Chia-Network/chia-blockchain#2851]
**Describe the bug**
Não consigo criar o Plot,, trava em 1%

LOG:
"2021-04-26T14:15:07.548  chia.plotting.create_plots       : [32mINFO    [0m Adding directory H:\FINAL01 to harvester for farming[0m
2021-04-26T14:15:07.708  chia.plotting.create_plots       : [32mINFO    [0m Starting plot 1/1[0m
**Caught plotting error: Bitfield plotting not supported by CPU**
[5848] Failed to execute script chia
Traceback (most recent call last):
  File "chia\cmds\chia.py", line 81, in <module>
  File "chia\cmds\chia.py", line 77, in main
  File "click\core.py", line 829, in __call__
  File "click\core.py", line 782, in main
  File "click\core.py", line 1259, in invoke
  File "click\core.py", line 1259, in invoke
  File "click\core.py", line 1066, in invoke
  File "click\core.py", line 610, in invoke
  File "click\decorators.py", line 21, in new_func
  File "chia\cmds\plots.py", line 135, in create_cmd
  File "chia\plotting\create_plots.py", line 176, in create_plots
RuntimeError: Unknown exception"

**Desktop:**

- OS: Windows 7 Ultimate
- OS Version/Flavor: 6.1.7601 Service Pack 1 
- CPU: Intel Core 2 Quad Q8200 2.33GHz
- RAM: 8GB DDR3

**Comment by royimous** [comment]
This isn't a bug. It's telling you your CPU can't handle bitfield plotting.

**Comment by fiveangle** [comment]
as @royimous states, this is w.a.d. To prevent the error, either disable the bitfield optimization in the gui, or add the "-e" switch to the plotter commandline to disable the optimizations.

you should close this issue

**Comment by Eustor** [comment]
OK
