### ISSUE TITLE
Sending data failed traceback

### ISSUE THREAD

**Issue by nealrahman** [Chia-Network/chia-blockchain#2868]
Receiving the following traceback error:

```
2021-04-26T23:05:28.540 full_node chia.rpc.rpc_server     : WARNING  Sending data failed. Exception Traceback (most recent call last):
  File "chia\rpc\rpc_server.py", line 67, in _state_changed
  File "aiohttp\client_ws.py", line 150, in send_str
  File "aiohttp\http_websocket.py", line 687, in send
  File "aiohttp\http_websocket.py", line 656, in _send_frame
  File "aiohttp\base_protocol.py", line 84, in _drain_helper
AssertionError'
```

Sometimes I see this related error instead:
```
2021-04-27T00:59:23.874 full_node chia.rpc.rpc_server     : WARNING  Sending data failed. Exception Traceback (most recent call last):
  File "chia\rpc\rpc_server.py", line 67, in _state_changed
  File "aiohttp\client_ws.py", line 150, in send_str
  File "aiohttp\http_websocket.py", line 687, in send
  File "aiohttp\http_websocket.py", line 643, in _send_frame
  File "aiohttp\http_websocket.py", line 660, in _write
ConnectionResetError: Cannot write to closing transport
```

Issue began on 4/24 upon updating to 1.12, occurs every 10 seconds. Attempting rollback to 1.11 after current plots are done to see if that fixes it.

**Comment by aqk** [comment]
Thank you for the log output. Please track this issue here:

https://trello.com/c/7Jeo0gLh/1112-rpcserverpy
