### ISSUE TITLE
Not Synced no node connection [8444 open], strange log on fedora 33 [BUG]

### ISSUE THREAD

**Issue by Tenma0** [Chia-Network/chia-blockchain#2886]
**Describe the bug**

Not synced and no node connection from 25/04 (first time install) with V. 1.1.2 on fedora 33. Port 8444 is open and work correctly (checked also with yougetsignal.com).
I've followed yet all the procedures desribed in the faq and tried also with ubuntu but doesnt'work
when i try to connect to another node by clcking on connect to others peers i get this log  in the consolle, different from other one seen in other issues,(see screnshot below)

I politely ask you if you have any suggestion to get better 
thank you

**To Reproduce**

1. Go to 'Full Node Tab'
2. Click on 'Connect to other peers'
3. Insert host name and port (8444)
4. the screen becomes grey and the circle start to spin but at the end nothing happen
5. I get the log that you can see below
**Expected behavior**
Get synced

**Screenshots**

![Screenshot from 2021-04-26 19-33-18](https://user-images.githubusercontent.com/83275340/116216183-a2751c80-a748-11eb-9dd3-1046d4d328bd.PNG)

![IMG-1334](https://user-images.githubusercontent.com/83275340/116217350-d735a380-a749-11eb-973e-6a8f996537ad.JPG)

**Desktop :**
- OS: [Linux]
- OS Version/Flavor: [ Fedora 33]
- CPU: [ryzen 3 1200]

**Additional context**
i'm tying everything to fix it but it isn't working. All the other things work very well, plotting is ok but we can't farm, I've read many issues where people solve the problem acting on the router or on the upnp but 've done it yet and doesn't work. I also tried to connect directly to other peers like someone suggests but doesn't work form me.

I ask you if you have any suggestion to get better 
thank you

**Comment by alexJew322** [comment]
I have same problem.U found solution?

**Comment by Tenma0** [comment]
Not yet, I'm trying everything i can but i'm not able to understand what is the problem. Just hope somebody will politely help us. i can't start farming

**Comment by dorkmo** [comment]
looks like youre having an issue with rpc. some other people are also having an issue. you might search the issues to see if you are having a similar issue.

**Comment by aqk** [comment]
Thank you. This is a very good bug report.

I have added it to our trello list for triage

https://trello.com/c/7Jeo0gLh/1112-rpcserverpy

**Comment by sinaflan** [comment]
`⬢$ chia-blockchain 
/usr/lib/chia-blockchain/resources/app.asar.unpacked/daemon
true
Error loading config - using defaults
startUrl file:///usr/lib/chia-blockchain/resources/app.asar/build/renderer/index.html
/usr/lib/chia-blockchain/resources/app.asar.unpacked/daemon
true
/usr/lib/chia-blockchain/resources/app.asar.unpacked/daemon
true
Running python executable: 
child process success
(node:17534) electron: The default of contextIsolation is deprecated and will be changing from false to true in a future release of Electron.  See https://github.com/electron/electron/issues/23506 for more information
No cert
Have cert
stderr: Traceback (most recent call last):
  File "chia/server/start_full_node.py", line 8, in <module>
  File "PyInstaller/loader/pyimod03_importers.py", line 531, in exec_module
  File "chia/full_node/full_node.py", line 14, in <module>
  File "PyInstaller/loader/pyimod03_importers.py", line 531, in exec_module
  File "chia/consensus/block_creation.py", line 12, in <module>
  File "PyInstaller/loader/pyimod03_importers.py", line 531, in exec_module
  File "chia/consensus/blockchain_interface.py", line 6, in <module>
  File "PyInstaller/loader/pyimod03_importers.py", line 531, in exec_module
  File "chia/types/blockchain_format/vdf.py", line 7, in <module>
ImportError: /usr/lib/chia-blockchain/resources/app.asar.unpacked/daemon/chiavdf.cpython-38-x86_64-linux-gnu.so: ELF load command address/offset not properly aligned
[17630] Failed to execute script start_full_node
stderr: Traceback (most recent call last):
  File "chia/server/start_wallet.py", line 7, in <module>
  File "PyInstaller/loader/pyimod03_importers.py", line 531, in exec_module
  File "chia/rpc/wallet_rpc_api.py", line 23, in <module>
  File "PyInstaller/loader/pyimod03_importers.py", line 531, in exec_module
  File "chia/wallet/cc_wallet/cc_wallet.py", line 14, in <module>
  File "PyInstaller/loader/pyimod03_importers.py", line 531, in exec_module
  File "chia/protocols/wallet_protocol.py", line 7, in <module>
  File "PyInstaller/loader/pyimod03_importers.py", line 531, in exec_module
  File "chia/types/header_block.py", line 5, in <module>
  File "PyInstaller/loader/pyimod03_importers.py", line 531, in exec_module
  File "chia/types/blockchain_format/reward_chain_block.py", line 8, in <module>
  File "PyInstaller/loader/pyimod03_importers.py", line 531, in exec_module
  File "chia/types/blockchain_format/vdf.py", line 7, in <module>
ImportError: /usr/lib/chia-blockchain/resources/app.asar.unpacked/daemon/chiavdf.cpython-38-x86_64-linux-gnu.so: ELF load command address/offset not properly aligned
[17628] Failed to execute script start_wallet
stderr: Traceback (most recent call last):
  File "chia/server/start_farmer.py", line 68, in <module>
  File "chia/server/start_farmer.py", line 63, in main
  File "chia/server/start_farmer.py", line 38, in service_kwargs_for_farmer
  File "chia/farmer/farmer.py", line 73, in __init__
RuntimeError: No keys exist. Please run 'chia keys generate' or open the UI.
[17632] Failed to execute script start_farmer
`
