### ISSUE TITLE
Error to start wallet in Ubuntu 20 [BUG]

### ISSUE THREAD

**Issue by cooliobr** [Chia-Network/chia-blockchain#2909]
```
chia start all
Daemon not started yet
Starting daemon
chia_harvester: started
chia_timelord_launcher: started
chia_timelord: started
chia_farmer: started
chia_full_node: started
chia_wallet: started
(venv) ubuntu@ns537008:/mnt/4/MiCaSa/mi1-teste$ Traceback (most recent call last):
  File "/mnt/4/MiCaSa/mi1-teste/venv/bin/chia_full_node", line 33, in <module>
    sys.exit(load_entry_point('chia-blockchain', 'console_scripts', 'chia_full_node')())
  File "/mnt/4/MiCaSa/mi1-teste/chia/server/start_full_node.py", line 60, in main
    return run_service(**kwargs)
  File "/mnt/4/MiCaSa/mi1-teste/chia/server/start_service.py", line 218, in run_service
    return asyncio.run(async_run_service(*args, **kwargs))
  File "/usr/lib/python3.8/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/mnt/4/MiCaSa/mi1-teste/chia/server/start_service.py", line 212, in async_run_service
    return await service.run()
  File "/mnt/4/MiCaSa/mi1-teste/chia/server/start_service.py", line 156, in run
    await self.start()
  File "/mnt/4/MiCaSa/mi1-teste/chia/server/start_service.py", line 127, in start
    await self._node._start(**kwargs)
  File "/mnt/4/MiCaSa/mi1-teste/chia/full_node/full_node.py", line 123, in _start
    self.blockchain = await Blockchain.create(self.coin_store, self.block_store, self.constants)
  File "/mnt/4/MiCaSa/mi1-teste/chia/consensus/blockchain.py", line 103, in create
    self.pool = ProcessPoolExecutor(max_workers=num_workers)
  File "/usr/lib/python3.8/concurrent/futures/process.py", line 555, in __init__
    self._call_queue = _SafeQueue(
  File "/usr/lib/python3.8/concurrent/futures/process.py", line 165, in __init__
    super().__init__(max_size, ctx=ctx)
  File "/usr/lib/python3.8/multiprocessing/queues.py", line 42, in __init__
    self._rlock = ctx.Lock()
  File "/usr/lib/python3.8/multiprocessing/context.py", line 68, in Lock
    return Lock(ctx=self.get_context())
  File "/usr/lib/python3.8/multiprocessing/synchronize.py", line 162, in __init__
    SemLock.__init__(self, SEMAPHORE, 1, 1, ctx=ctx)
  File "/usr/lib/python3.8/multiprocessing/synchronize.py", line 57, in __init__
    sl = self._semlock = _multiprocessing.SemLock(
OSError: [Errno 28] No space left on device
Traceback (most recent call last):
  File "/mnt/4/MiCaSa/mi1-teste/venv/bin/chia_wallet", line 33, in <module>
    sys.exit(load_entry_point('chia-blockchain', 'console_scripts', 'chia_wallet')())
  File "/mnt/4/MiCaSa/mi1-teste/chia/server/start_wallet.py", line 92, in main
    return run_service(**kwargs)
  File "/mnt/4/MiCaSa/mi1-teste/chia/server/start_service.py", line 218, in run_service
    return asyncio.run(async_run_service(*args, **kwargs))
  File "/usr/lib/python3.8/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/mnt/4/MiCaSa/mi1-teste/chia/server/start_service.py", line 212, in async_run_service
    return await service.run()
  File "/mnt/4/MiCaSa/mi1-teste/chia/server/start_service.py", line 156, in run
    await self.start()
  File "/mnt/4/MiCaSa/mi1-teste/chia/server/start_service.py", line 127, in start
    await self._node._start(**kwargs)
  File "/mnt/4/MiCaSa/mi1-teste/chia/wallet/wallet_node.py", line 151, in _start
    self.wallet_state_manager = await WalletStateManager.create(
  File "/mnt/4/MiCaSa/mi1-teste/chia/wallet/wallet_state_manager.py", line 139, in create
    self.blockchain = await WalletBlockchain.create(
  File "/mnt/4/MiCaSa/mi1-teste/chia/wallet/wallet_blockchain.py", line 94, in create
    self.pool = ProcessPoolExecutor(max_workers=num_workers)
  File "/usr/lib/python3.8/concurrent/futures/process.py", line 555, in __init__
    self._call_queue = _SafeQueue(
  File "/usr/lib/python3.8/concurrent/futures/process.py", line 165, in __init__
    super().__init__(max_size, ctx=ctx)
  File "/usr/lib/python3.8/multiprocessing/queues.py", line 42, in __init__
    self._rlock = ctx.Lock()
  File "/usr/lib/python3.8/multiprocessing/context.py", line 68, in Lock
    return Lock(ctx=self.get_context())
  File "/usr/lib/python3.8/multiprocessing/synchronize.py", line 162, in __init__
    SemLock.__init__(self, SEMAPHORE, 1, 1, ctx=ctx)
  File "/usr/lib/python3.8/multiprocessing/synchronize.py", line 57, in __init__
    sl = self._semlock = _multiprocessing.SemLock(
OSError: [Errno 28] No space left on device
Traceback (most recent call last):
  File "/mnt/4/MiCaSa/mi1-teste/venv/bin/chia_timelord_launcher", line 33, in <module>
    sys.exit(load_entry_point('chia-blockchain', 'console_scripts', 'chia_timelord_launcher')())
  File "/mnt/4/MiCaSa/mi1-teste/chia/timelord/timelord_launcher.py", line 107, in main
    loop.run_until_complete(spawn_all_processes(config, net_config))
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/mnt/4/MiCaSa/mi1-teste/chia/timelord/timelord_launcher.py", line 85, in spawn_all_processes
    await asyncio.gather(*awaitables)
  File "/mnt/4/MiCaSa/mi1-teste/chia/timelord/timelord_launcher.py", line 45, in spawn_process
    path_to_vdf_client = find_vdf_client()
  File "/mnt/4/MiCaSa/mi1-teste/chia/timelord/timelord_launcher.py", line 39, in find_vdf_client
    raise FileNotFoundError("can't find vdf_client binary")
FileNotFoundError: can't find vdf_client binary

```

my space is 14TB

**Comment by lvcivs** [comment]
`OSError: [Errno 28] No space left on device`

It is pretty clear, no?

**Comment by cooliobr** [comment]
No, is not clear, i have 4 HDD with 14TB each.. sistem is clear.

> Filesystem      Size  Used Avail Use% Mounted on
> udev             16G     0   16G   0% /dev
> tmpfs           3.2G  1.6M  3.2G   1% /run
> /dev/md2        219G  9.2G  199G   5% /
> tmpfs            16G     0   16G   0% /dev/shm
> tmpfs           5.0M     0  5.0M   0% /run/lock
> tmpfs            16G     0   16G   0% /sys/fs/cgroup
> /dev/loop0       56M   56M     0 100% /snap/core18/1988
> /dev/sda1       511M  7.9M  503M   2% /boot/efi
> /dev/sde         13T   68G   12T   1% /mnt/2
> /dev/sdf         13T   71G   12T   1% /mnt/4
> /dev/sdc         13T   82G   12T   1% /mnt/1
> /dev/loop1       70M   70M     0 100% /snap/lxd/19188
> /dev/loop2       71M   71M     0 100% /snap/lxd/19647
> /dev/sdd         13T   12G   12T   1% /mnt/3
> /dev/loop3       56M   56M     0 100% /snap/core18/1997
> /dev/loop4       33M   33M     0 100% /snap/snapd/11402
> /dev/loop5       33M   33M     0 100% /snap/snapd/11588
> tmpfs           3.2G     0  3.2G   0% /run/user/0
>
"Não existe patch para a estupidez humana"





Em ter., 27 de abr. de 2021 às 13:26, lvcivs ***@***.***>
escreveu:

**Comment by aqk** [comment]
Hi there, you are launching the timelord, which is an advanced use case.
Try starting up with `chia start wallet node farmer`

If you want to run the timelord,
please install https://keybase.io/download
And then come to keybase://chat/chia_network.public
and join `#timelords`
