### ISSUE TITLE
I can´t make a plot with this error

### ISSUE THREAD

**Issue by sareyes08** [Chia-Network/chia-blockchain#2915]
this is all the plot I can do with my ssd

2021-04-27T16:41:06.178  chia.plotting.create_plots       : [32mINFO    [0m Creating 1 plots of size 32, pool public key:  89722fcb34aeb55eb986474fe690005bc19c05d0bd2b84111a4b63d2d380167e20aed842fa6c5dac5ce98e4d96aedc2b farmer public key: aa64ad972034a86a577fa2a89f68b88abfcf3aa6812c6d0d88538aac3253ec6b0516ee9548f92681ad77433a8a7fb3e6[0m
2021-04-27T16:41:06.185  chia.plotting.create_plots       : [32mINFO    [0m Memo: 89722fcb34aeb55eb986474fe690005bc19c05d0bd2b84111a4b63d2d380167e20aed842fa6c5dac5ce98e4d96aedc2baa64ad972034a86a577fa2a89f68b88abfcf3aa6812c6d0d88538aac3253ec6b0516ee9548f92681ad77433a8a7fb3e633d1798eb101cfe4306d50b352f15c79265b7936efa1c3a16231b8b0365795cc[0m
2021-04-27T16:41:06.186  chia.plotting.create_plots       : [32mINFO    [0m Starting plot 1/1[0m

Starting plotting progress into temporary dirs: C:\ and C:\
ID: dae30d9fb04a376ace412704f5700a27a15a8f7f87e0d8cec63768a416b476d1
Plot size is: 32
Buffer size is: 3390MiB
Using 128 buckets
Using 2 threads of stripe size 65536
Caught plotting error: Could not open C:\plot-k32-2021-04-27-16-41-dae30d9fb04a376ace412704f5700a27a15a8f7f87e0d8cec63768a416b476d1.plot.sort.tmp: Permission denied.
[11820] Failed to execute script chia
Traceback (most recent call last):
  File "chia\cmds\chia.py", line 81, in <module>
  File "chia\cmds\chia.py", line 77, in main
  File "click\core.py", line 829, in __call__
  File "click\core.py", line 782, in main
  File "click\core.py", line 1259, in invoke
  File "click\core.py", line 1259, in invoke
  File "click\core.py", line 1066, in invoke
  File "click\core.py", line 610, in invoke
  File "click\decorators.py", line 21, in new_func
  File "chia\cmds\plots.py", line 135, in create_cmd
  File "chia\plotting\create_plots.py", line 176, in create_plots
RuntimeError: Unknown exception

**Comment by sareyes08** [comment]
I have a western digital blue of 500gb

**Comment by aqk** [comment]
Hello @sareyes08 

Windows protects the directory `c:\` by default.

Try to create the plot in your user folder.

Please install https://keybase.io/download
And then come to keybase://chat/chia_network.public#support for more support.

**Comment by sareyes08** [comment]
Thanks @aqk
