### ISSUE TITLE
[BUG] - Bitfield plotting not supported by CPU???

### ISSUE THREAD

**Issue by forkmiester** [Chia-Network/chia-blockchain#2924]
**Describe the bug**
When I create a plot, it won't start.  It gives me this error (I have a dozen or so other successful plots prior to 1.1.2)

**To Reproduce**
1. Click "Add Plot"
2. Plot Size 101.4GiB
3. set number of Plots 1 and threads to 4, disable bitfield plotting
4. Select proper directories (400GiB SSD for temp, empty 1Tb serial drive for Farm)
5. Start Plot
6. Plot will go to 1% 
7. View log - shows error (below)
8. You cannot delete plot. Plotting freezes.

**Expected behavior**
Plot is suppose to happen with the # of CPU threads available. Used to always work with 4. Now I can only use less than.

**Screenshots**

**Desktop (please complete the following information):**

- OS: Win10 20H2
- OS Version/Flavor: 19042.928
- CPU: Intel Quad Q9650 Q3.0Ghz

**Additional context**
2021-04-27T10:37:37.929  chia.plotting.create_plots       : [32mINFO    [0m Starting plot 1/1[0m
Caught plotting error: Bitfield plotting not supported by CPU
[1516] Failed to execute script chia
Traceback (most recent call last):
  File "chia\cmds\chia.py", line 81, in <module>
  File "chia\cmds\chia.py", line 77, in main
  File "click\core.py", line 829, in __call__
  File "click\core.py", line 782, in main
  File "click\core.py", line 1259, in invoke
  File "click\core.py", line 1259, in invoke
  File "click\core.py", line 1066, in invoke
  File "click\core.py", line 610, in invoke
  File "click\decorators.py", line 21, in new_func
  File "chia\cmds\plots.py", line 135, in create_cmd
  File "chia\plotting\create_plots.py", line 176, in create_plots
RuntimeError: Unknown exception

**Comment by garyhkirk** [comment]
The Q9650 was launched in 2008. Processors adopted instructions that support bitfield plotting in the early 2010's so Chia is reporting correctly.

**Comment by aqk** [comment]
@garyhkirk is correct. The bitfield instruction support detection code seems to be doing the right thing.

But, you said in your bug report that you "disable bitfield plotting". If that's right, we have a bug in setting the parameters.

Can you check this again for us, and upload your full debug.log?

Thank you.

**Comment by sargonas** [comment]
tagging @forkmiester just in case :) Are you still having this issue? if so can you follow up with aqk on if you are indeed disabling bitfield plotting, but still erroring over it being not supported? If the problem is no longer happening for you, or you don't followup in a few days I'll close this out to help keep the issue tracker semi-sane, but you can always reply back and reopen it later if that is not the case!
