### ISSUE TITLE
[BUG] Having connection issue Harvester

### ISSUE THREAD

**Issue by vkmis** [Chia-Network/chia-blockchain#2934]
2021-04-28T00:41:14.580 full_node full_node_server        : INFO     Connected with full_node {'host': '59.63.25.200', 'port': 8444}
2021-04-28T00:41:14.596 full_node full_node_server        : INFO     -> new_peak to peer 59.63.25.200 XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
2021-04-28T00:41:14.596 full_node full_node_server        : INFO     -> request_peers to peer 59.63.25.200 XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
2021-04-28T00:41:14.596 full_node full_node_server        : INFO     Connection closed: 59.63.25.200, node id: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
2021-04-28T00:41:14.596 full_node chia.full_node.full_node: INFO     peer disconnected {'host': '59.63.25.200', 'port': 8444}
2021-04-28T00:41:37.672 full_node full_node_server        : INFO     Cannot connect to host 1.172.117.46:8444 ssl:<ssl.SSLContext object at 0x000002279B293278> [Connect call failed ('1.172.117.46', 8444)]
2021-04-28T00:41:43.719 full_node full_node_server        : INFO     Cannot connect to host 59.48.142.102:8444 ssl:<ssl.SSLContext object at 0x000002279B2934A8> [Connect call failed ('59.48.142.102', 8444)]
2021-04-28T00:42:06.776 full_node full_node_server        : INFO     Cannot connect to host 112.47.158.198:8444 ssl:<ssl.SSLContext object at 0x000002279D602E48> [Connect call failed ('112.47.158.198', 8444)]
2021-04-28T00:42:29.839 full_node full_node_server        : INFO     Cannot connect to host 178.206.41.246:8444 ssl:<ssl.SSLContext object at 0x000002279B3EEF28> [Connect call failed ('178.206.41.246', 8444)]
2021-04-28T00:42:31.548 daemon __main__                   : INFO     Websocket exception. Closing websocket with wallet_ui code = 1006 (connection closed abnormally [internal]), no reason Traceback (most recent call last):
  File "websockets\protocol.py", line 827, in transfer_data
  File "websockets\protocol.py", line 895, in read_message
  File "websockets\protocol.py", line 971, in read_data_frame
  File "websockets\protocol.py", line 1051, in read_frame
  File "websockets\framing.py", line 105, in read
  File "asyncio\streams.py", line 677, in readexactly
asyncio.streams.IncompleteReadError: 0 bytes read on a total of 2 expected bytes

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "chia\daemon\server.py", line 167, in safe_handle
  File "websockets\protocol.py", line 439, in __aiter__
  File "websockets\protocol.py", line 509, in recv
  File "websockets\protocol.py", line 803, in ensure_open
websockets.exceptions.ConnectionClosedError: code = 1006 (connection closed abnormally [internal]), no reason

**Comment by Mlalosevic** [comment]
my log file looks different. Harvester stoped when the some of the disks went to sleep. Turned the option off, restarted all everything is working fine (so far) .
