### ISSUE TITLE
Plot problem, stuck at 32%

### ISSUE THREAD

**Issue by Joga1101** [Chia-Network/chia-blockchain#2998]
Plot has been at 32% for 8 hours and is blocking the others. 
How can I delete without closing Chia Blockchain?

**Comment by BACONATOR26** [comment]
Same issue I'm experiencing. I've only been able to do 1 plot (farming status). The second is now at 32% with bad allocation in the logs. 

Starting phase 3/4: Compression from tmp files into "F:\\Temp\\plot-k32-2021-04-26-21-16-d2a52f3f70b1641cf65e6565f2d864dc502d291c733802e0cd45d9371c20e802.plot.2.tmp" ... Tue Apr 27 16:39:20 2021
Compressing tables 1 and 2
Caught plotting error: bad allocation
[12540] Failed to execute script chia
Traceback (most recent call last):
  File "chia\cmds\chia.py", line 81, in <module>
  File "chia\cmds\chia.py", line 77, in main
  File "click\core.py", line 829, in __call__
  File "click\core.py", line 782, in main
  File "click\core.py", line 1259, in invoke
  File "click\core.py", line 1259, in invoke
  File "click\core.py", line 1066, in invoke
  File "click\core.py", line 610, in invoke
  File "click\decorators.py", line 21, in new_func
  File "chia\cmds\plots.py", line 135, in create_cmd
  File "chia\plotting\create_plots.py", line 176, in create_plots
RuntimeError: bad allocation

Chia Blockchain Version 1.1.2
Running processes:
Chia
Chia Blockbchain
daemon.exe
start_farmer.exe
start_full_node.exe

CPU running at 14-56%
2 Sockets 16 cores
8 GB physical memory
3.2 GB In use 4.1 GB Available
Committed 5.1/8.0 GB
Cached 4.8 GB
Paged pool 345 MB
Non-pages pool 142 MB

2 TB 6 Gbps SAS RAID
1.84 TB available for temp/final plot storage

Related with similar reports: #1847

Chia screenshot and logs attached below.

![chiaplot](https://user-images.githubusercontent.com/5950941/116417047-ed566900-a808-11eb-9c5c-5927b1096270.png)
[chialog.txt](https://github.com/Chia-Network/chia-blockchain/files/6392385/chialog.txt)

**Comment by thetongas** [comment]
hola se fijaron el espacio q les queda en el disco q estan creando la parcela?

me ayudan tengo un problema mi primer parcela creada solo me queda sincronizazndo y nunca se puso a cultivar saben x q sera este problema?
