### ISSUE TITLE
Installation has failed [Windows]

### ISSUE THREAD

**Issue by turkeyphant** [Chia-Network/chia-blockchain#2999]
`2019-03-07 21:49:41> Program: Starting Squirrel Updater: --install .
2019-03-07 21:49:41> Program: Starting install, writing to C:\Users\turkeyphant\AppData\Local\SquirrelTemp
2019-03-07 21:49:41> Program: About to install to: C:\Users\turkeyphant\AppData\Local\1Clipboard
2019-03-07 21:49:41> CheckForUpdateImpl: Failed to load local releases, starting from scratch: System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\turkeyphant\AppData\Local\1Clipboard\packages\RELEASES'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at Squirrel.Utility.LoadLocalReleases(String localReleaseFile)
   at Squirrel.UpdateManager.CheckForUpdateImpl.<CheckForUpdate>d__3f.MoveNext()
2019-03-07 21:49:41> CheckForUpdateImpl: Reading RELEASES file from C:\Users\turkeyphant\AppData\Local\SquirrelTemp
2019-03-07 21:49:41> CheckForUpdateImpl: First run or local directory is corrupt, starting from scratch
2019-03-07 21:49:41> ApplyReleasesImpl: Writing files to app directory: C:\Users\turkeyphant\AppData\Local\1Clipboard\app-0.1.8
2019-03-07 21:49:45> ApplyReleasesImpl: Moving file C:\Users\turkeyphant\AppData\Local\1Clipboard\app-0.1.8\lib\net45\1Clipboard.exe to C:\Users\turkeyphant\AppData\Local\1Clipboard\app-0.1.8\1Clipboard.exe
2019-03-07 21:49:45> ApplyReleasesImpl: Moving file C:\Users\turkeyphant\AppData\Local\1Clipboard\app-0.1.8\lib\net45\content_resources_200_percent.pak to C:\Users\turkeyphant\AppData\Local\1Clipboard\app-0.1.8\content_resources_200_percent.pak
2019-03-07 21:49:45> ApplyReleasesImpl: Moving file C:\Users\turkeyphant\AppData\Local\1Clipboard\app-0.1.8\lib\net45\content_shell.pak to C:\Users\turkeyphant\AppData\Local\1Clipboard\app-0.1.8\content_shell.pak
2019-03-07 21:49:45> ApplyReleasesImpl: Moving file C:\Users\turkeyphant\AppData\Local\1Clipboard\app-0.1.8\lib\net45\d3dcompiler_47.dll to C:\Users\turkeyphant\AppData\Local\1Clipboard\app-0.1.8\d3dcompiler_47.dll
2019-03-07 21:49:45> ApplyReleasesImpl: Moving file C:\Users\turkeyphant\AppData\Local\1Clipboard\app-0.1.8\lib\net45\icudtl.dat to C:\Users\turkeyphant\AppData\Local\1Clipboard\app-0.1.8\icudtl.dat
2019-03-07 21:49:45> ApplyReleasesImpl: Moving file C:\Users\turkeyphant\AppData\Local\1Clipboard\app-0.1.8\lib\net45\libEGL.dll to C:\Users\turkeyphant\AppData\Local\1Clipboard\app-0.1.8\libEGL.dll
2019-03-07 21:49:45> ApplyReleasesImpl: Moving file C:\Users\turkeyphant\AppData\Local\1Clipboard\app-0.1.8\lib\net45\libGLESv2.dll to C:\Users\turkeyphant\AppData\Local\1Clipboard\app-0.1.8\libGLESv2.dll
2019-03-07 21:49:45> ApplyReleasesImpl: Moving file C:\Users\turkeyphant\AppData\Local\1Clipboard\app-0.1.8\lib\net45\msvcp120.dll to C:\Users\turkeyphant\AppData\Local\1Clipboard\app-0.1.8\msvcp120.dll
2019-03-07 21:49:45> ApplyReleasesImpl: Moving file C:\Users\turkeyphant\AppData\Local\1Clipboard\app-0.1.8\lib\net45\msvcr120.dll to C:\Users\turkeyphant\AppData\Local\1Clipboard\app-0.1.8\msvcr120.dll
2019-03-07 21:49:45> ApplyReleasesImpl: Moving file C:\Users\turkeyphant\AppData\Local\1Clipboard\app-0.1.8\lib\net45\LICENSE to C:\Users\turkeyphant\AppData\Local\1Clipboard\app-0.1.8\LICENSE
2019-03-07 21:49:45> ApplyReleasesImpl: Moving file C:\Users\turkeyphant\AppData\Local\1Clipboard\app-0.1.8\lib\net45\natives_blob.bin to C:\Users\turkeyphant\AppData\Local\1Clipboard\app-0.1.8\natives_blob.bin
2019-03-07 21:49:45> ApplyReleasesImpl: Moving file C:\Users\turkeyphant\AppData\Local\1Clipboard\app-0.1.8\lib\net45\node.dll to C:\Users\turkeyphant\AppData\Local\1Clipboard\app-0.1.8\node.dll
2019-03-07 21:49:45> ApplyReleasesImpl: Moving file C:\Users\turkeyphant\AppData\Local\1Clipboard\app-0.1.8\lib\net45\snapshot_blob.bin to C:\Users\turkeyphant\AppData\Local\1Clipboard\app-0.1.8\snapshot_blob.bin
2019-03-07 21:49:45> ApplyReleasesImpl: Moving file C:\Users\turkeyphant\AppData\Local\1Clipboard\app-0.1.8\lib\net45\ui_resources_200_percent.pak to C:\Users\turkeyphant\AppData\Local\1Clipboard\app-0.1.8\ui_resources_200_percent.pak
2019-03-07 21:49:45> ApplyReleasesImpl: Moving file C:\Users\turkeyphant\AppData\Local\1Clipboard\app-0.1.8\lib\net45\vccorlib120.dll to C:\Users\turkeyphant\AppData\Local\1Clipboard\app-0.1.8\vccorlib120.dll
2019-03-07 21:49:45> ApplyReleasesImpl: Moving file C:\Users\turkeyphant\AppData\Local\1Clipboard\app-0.1.8\lib\net45\pdf.dll to C:\Users\turkeyphant\AppData\Local\1Clipboard\app-0.1.8\pdf.dll
2019-03-07 21:49:45> ApplyReleasesImpl: Moving file C:\Users\turkeyphant\AppData\Local\1Clipboard\app-0.1.8\lib\net45\squirrel.exe to C:\Users\turkeyphant\AppData\Local\1Clipboard\app-0.1.8\squirrel.exe
2019-03-07 21:49:45> ApplyReleasesImpl: Moving file C:\Users\turkeyphant\AppData\Local\1Clipboard\app-0.1.8\lib\net45\xinput1_3.dll to C:\Users\turkeyphant\AppData\Local\1Clipboard\app-0.1.8\xinput1_3.dll
2019-03-07 21:49:45> ApplyReleasesImpl: Moving file C:\Users\turkeyphant\AppData\Local\1Clipboard\app-0.1.8\lib\net45\xcp_win32.dll to C:\Users\turkeyphant\AppData\Local\1Clipboard\app-0.1.8\xcp_win32.dll
2019-03-07 21:49:47> ApplyReleasesImpl: Squirrel Enabled Apps: [C:\Users\turkeyphant\AppData\Local\1Clipboard\app-0.1.8\1Clipboard.exe]
2019-03-07 21:49:49> ApplyReleasesImpl: Starting fixPinnedExecutables
2019-03-07 21:49:49> ApplyReleasesImpl: Examining Pin: Google Chrome.lnk
2019-03-07 21:49:49> ApplyReleasesImpl: Fixing up tray icons
2019-03-07 21:49:49> ApplyReleasesImpl: Couldn't rewrite shim RegKey, most likely no apps are shimmed: System.NullReferenceException: Object reference not set to an instance of an object.
   at Squirrel.UpdateManager.ApplyReleasesImpl.<unshimOurselves>b__f5(RegistryView view)
2019-03-07 21:49:49> ApplyReleasesImpl: Couldn't rewrite shim RegKey, most likely no apps are shimmed: System.NullReferenceException: Object reference not set to an instance of an object.
   at Squirrel.UpdateManager.ApplyReleasesImpl.<unshimOurselves>b__f5(RegistryView view)
2019-03-07 21:49:49> ApplyReleasesImpl: cleanDeadVersions: for version 0.1.8
2019-03-07 21:49:49> ApplyReleasesImpl: cleanDeadVersions: exclude folder app-0.1.8
2019-03-20 00:58:29> Program: Starting Squirrel Updater: --install .
2019-03-20 00:58:29> Program: Starting install, writing to C:\Users\turkeyphant\AppData\Local\SquirrelTemp
2019-03-20 00:58:29> Program: About to install to: C:\Users\turkeyphant\AppData\Local\Wox
2019-03-20 00:58:29> CheckForUpdateImpl: Couldn't write out staging user ID, this user probably shouldn't get beta anything: System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\turkeyphant\AppData\Local\Wox\packages\.betaId'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamWriter.CreateFile(String path, Boolean append, Boolean checkHost)
   at System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding, Int32 bufferSize, Boolean checkHost)
   at System.IO.File.InternalWriteAllText(String path, String contents, Encoding encoding, Boolean checkHost)
   at System.IO.File.WriteAllText(String path, String contents, Encoding encoding)
   at Squirrel.UpdateManager.CheckForUpdateImpl.getOrCreateStagedUserId()
2019-03-20 00:58:29> CheckForUpdateImpl: Failed to load local releases, starting from scratch: System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\turkeyphant\AppData\Local\Wox\packages\RELEASES'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at Squirrel.Utility.LoadLocalReleases(String localReleaseFile)
   at Squirrel.UpdateManager.CheckForUpdateImpl.<CheckForUpdate>d__2.MoveNext()
2019-03-20 00:58:29> CheckForUpdateImpl: Reading RELEASES file from C:\Users\turkeyphant\AppData\Local\SquirrelTemp
2019-03-20 00:58:29> CheckForUpdateImpl: First run or local directory is corrupt, starting from scratch
2019-03-20 00:58:29> ApplyReleasesImpl: Writing files to app directory: C:\Users\turkeyphant\AppData\Local\Wox\app-1.3.578
2019-03-20 00:58:29> LogHost: Rigging execution stub for lib/net45/Wox_ExecutionStub.exe to C:\Users\turkeyphant\AppData\Local\Wox\Wox.exe
2019-03-20 00:58:30> ApplyReleasesImpl: Squirrel Enabled Apps: []
2019-03-20 00:58:30> ApplyReleasesImpl: No apps are marked as Squirrel-aware! Going to run them all
2019-03-20 00:58:30> ApplyReleasesImpl: About to create shortcuts for Wox.exe, rootAppDir C:\Users\turkeyphant\AppData\Local\Wox
2019-03-20 00:58:30> ApplyReleasesImpl: Creating shortcut for Wox.exe => C:\Users\turkeyphant\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Wox\Wox.lnk
2019-03-20 00:58:30> ApplyReleasesImpl: About to save shortcut: C:\Users\turkeyphant\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Wox\Wox.lnk (target C:\Users\turkeyphant\AppData\Local\Wox\Wox.exe, workingDir C:\Users\turkeyphant\AppData\Local\Wox\app-1.3.578, args , toastActivatorCSLID 9da9f3e0-d1f9-5b8f-a96b-7228c4d219b2)
2019-03-20 00:58:30> ApplyReleasesImpl: Creating shortcut for Wox.exe => C:\Users\turkeyphant\Desktop\Wox.lnk
2019-03-20 00:58:30> ApplyReleasesImpl: About to save shortcut: C:\Users\turkeyphant\Desktop\Wox.lnk (target C:\Users\turkeyphant\AppData\Local\Wox\Wox.exe, workingDir C:\Users\turkeyphant\AppData\Local\Wox\app-1.3.578, args , toastActivatorCSLID 9da9f3e0-d1f9-5b8f-a96b-7228c4d219b2)
2019-03-20 00:58:31> ApplyReleasesImpl: Starting fixPinnedExecutables
2019-03-20 00:58:31> ApplyReleasesImpl: Fixing up tray icons
2019-03-20 00:58:31> ApplyReleasesImpl: Couldn't rewrite shim RegKey, most likely no apps are shimmed: System.NullReferenceException: Object reference not set to an instance of an object.
   at Squirrel.UpdateManager.ApplyReleasesImpl.<unshimOurselves>b__13_0(RegistryView view)
2019-03-20 00:58:31> ApplyReleasesImpl: Couldn't rewrite shim RegKey, most likely no apps are shimmed: System.NullReferenceException: Object reference not set to an instance of an object.
   at Squirrel.UpdateManager.ApplyReleasesImpl.<unshimOurselves>b__13_0(RegistryView view)
2019-03-20 00:58:31> ApplyReleasesImpl: cleanDeadVersions: for version 1.3.578
2019-03-20 00:58:31> ApplyReleasesImpl: cleanDeadVersions: exclude folder app-1.3.578
2019-03-20 19:32:22> Program: Starting Squirrel Updater: --install .
2019-03-20 19:32:22> Program: Starting install, writing to C:\Users\turkeyphant\AppData\Local\SquirrelTemp
2019-03-20 19:32:22> Program: About to install to: C:\Users\turkeyphant\AppData\Local\hyper
2019-03-20 19:32:22> CheckForUpdateImpl: Couldn't write out staging user ID, this user probably shouldn't get beta anything: System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\turkeyphant\AppData\Local\hyper\packages\.betaId'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamWriter.CreateFile(String path, Boolean append, Boolean checkHost)
   at System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding, Int32 bufferSize, Boolean checkHost)
   at System.IO.File.InternalWriteAllText(String path, String contents, Encoding encoding, Boolean checkHost)
   at System.IO.File.WriteAllText(String path, String contents, Encoding encoding)
   at Squirrel.UpdateManager.CheckForUpdateImpl.getOrCreateStagedUserId()
2019-03-20 19:32:22> CheckForUpdateImpl: Failed to load local releases, starting from scratch: System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\turkeyphant\AppData\Local\hyper\packages\RELEASES'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at Squirrel.Utility.LoadLocalReleases(String localReleaseFile)
   at Squirrel.UpdateManager.CheckForUpdateImpl.<CheckForUpdate>d__2.MoveNext()
2019-03-20 19:32:22> CheckForUpdateImpl: Reading RELEASES file from C:\Users\turkeyphant\AppData\Local\SquirrelTemp
2019-03-20 19:32:22> CheckForUpdateImpl: First run or local directory is corrupt, starting from scratch
2019-03-20 19:32:23> ApplyReleasesImpl: Writing files to app directory: C:\Users\turkeyphant\AppData\Local\hyper\app-2.1.2
2019-03-20 19:32:25> LogHost: Rigging execution stub for Hyper_ExecutionStub.exe to C:\Users\turkeyphant\AppData\Local\hyper\Hyper.exe
2019-03-20 19:32:27> ApplyReleasesImpl: Squirrel Enabled Apps: [C:\Users\turkeyphant\AppData\Local\hyper\app-2.1.2\Hyper.exe]
2019-03-20 19:32:40> ApplyReleasesImpl: Starting fixPinnedExecutables
2019-03-20 19:32:40> ApplyReleasesImpl: Fixing up tray icons
2019-03-20 19:32:40> ApplyReleasesImpl: cleanDeadVersions: for version 2.1.2
2019-03-20 19:32:40> ApplyReleasesImpl: cleanDeadVersions: exclude folder app-2.1.2
2019-04-16 15:55:14> Program: Starting Squirrel Updater: --install .
2019-04-16 15:55:14> Program: Starting install, writing to C:\Users\turkeyphant\AppData\Local\SquirrelTemp
2019-04-16 15:55:14> Program: About to install to: C:\Users\turkeyphant\AppData\Local\hyper
2019-04-16 15:55:14> Program: Install path C:\Users\turkeyphant\AppData\Local\hyper already exists, burning it to the ground
2019-04-16 15:55:15> CheckForUpdateImpl: Couldn't write out staging user ID, this user probably shouldn't get beta anything: System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\turkeyphant\AppData\Local\hyper\packages\.betaId'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamWriter.CreateFile(String path, Boolean append, Boolean checkHost)
   at System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding, Int32 bufferSize, Boolean checkHost)
   at System.IO.File.InternalWriteAllText(String path, String contents, Encoding encoding, Boolean checkHost)
   at System.IO.File.WriteAllText(String path, String contents, Encoding encoding)
   at Squirrel.UpdateManager.CheckForUpdateImpl.getOrCreateStagedUserId()
2019-04-16 15:55:15> CheckForUpdateImpl: Failed to load local releases, starting from scratch: System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\turkeyphant\AppData\Local\hyper\packages\RELEASES'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at Squirrel.Utility.LoadLocalReleases(String localReleaseFile)
   at Squirrel.UpdateManager.CheckForUpdateImpl.<CheckForUpdate>d__2.MoveNext()
2019-04-16 15:55:15> CheckForUpdateImpl: Reading RELEASES file from C:\Users\turkeyphant\AppData\Local\SquirrelTemp
2019-04-16 15:55:15> CheckForUpdateImpl: First run or local directory is corrupt, starting from scratch
2019-04-16 15:55:15> ApplyReleasesImpl: Writing files to app directory: C:\Users\turkeyphant\AppData\Local\hyper\app-2.1.2
2019-04-16 15:55:17> LogHost: Rigging execution stub for Hyper_ExecutionStub.exe to C:\Users\turkeyphant\AppData\Local\hyper\Hyper.exe
2019-04-16 15:55:19> ApplyReleasesImpl: Squirrel Enabled Apps: [C:\Users\turkeyphant\AppData\Local\hyper\app-2.1.2\Hyper.exe]
2019-04-16 15:55:21> ApplyReleasesImpl: Starting fixPinnedExecutables
2019-04-16 15:55:21> ApplyReleasesImpl: Fixing up tray icons
2019-04-16 15:55:21> ApplyReleasesImpl: cleanDeadVersions: for version 2.1.2
2019-04-16 15:55:21> ApplyReleasesImpl: cleanDeadVersions: exclude folder app-2.1.2
2019-04-16 16:28:29> Program: Starting Squirrel Updater: --install .
2019-04-16 16:28:29> Program: Starting install, writing to C:\Users\turkeyphant\AppData\Local\SquirrelTemp
2019-04-16 16:28:29> Program: About to install to: C:\Users\turkeyphant\AppData\Local\hyper
2019-04-16 16:28:29> Program: Install path C:\Users\turkeyphant\AppData\Local\hyper already exists, burning it to the ground
2019-04-16 16:28:29> CheckForUpdateImpl: Couldn't write out staging user ID, this user probably shouldn't get beta anything: System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\turkeyphant\AppData\Local\hyper\packages\.betaId'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamWriter.CreateFile(String path, Boolean append, Boolean checkHost)
   at System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding, Int32 bufferSize, Boolean checkHost)
   at System.IO.File.InternalWriteAllText(String path, String contents, Encoding encoding, Boolean checkHost)
   at System.IO.File.WriteAllText(String path, String contents, Encoding encoding)
   at Squirrel.UpdateManager.CheckForUpdateImpl.getOrCreateStagedUserId()
2019-04-16 16:28:29> CheckForUpdateImpl: Failed to load local releases, starting from scratch: System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\turkeyphant\AppData\Local\hyper\packages\RELEASES'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at Squirrel.Utility.LoadLocalReleases(String localReleaseFile)
   at Squirrel.UpdateManager.CheckForUpdateImpl.<CheckForUpdate>d__2.MoveNext()
2019-04-16 16:28:29> CheckForUpdateImpl: Reading RELEASES file from C:\Users\turkeyphant\AppData\Local\SquirrelTemp
2019-04-16 16:28:29> CheckForUpdateImpl: First run or local directory is corrupt, starting from scratch
2019-04-16 16:28:29> ApplyReleasesImpl: Writing files to app directory: C:\Users\turkeyphant\AppData\Local\hyper\app-2.1.2
2019-04-16 16:28:32> LogHost: Rigging execution stub for Hyper_ExecutionStub.exe to C:\Users\turkeyphant\AppData\Local\hyper\Hyper.exe
2019-04-16 16:28:34> ApplyReleasesImpl: Squirrel Enabled Apps: [C:\Users\turkeyphant\AppData\Local\hyper\app-2.1.2\Hyper.exe]
2019-04-16 16:28:36> ApplyReleasesImpl: Starting fixPinnedExecutables
2019-04-16 16:28:36> ApplyReleasesImpl: Fixing up tray icons
2019-04-16 16:28:36> ApplyReleasesImpl: cleanDeadVersions: for version 2.1.2
2019-04-16 16:28:36> ApplyReleasesImpl: cleanDeadVersions: exclude folder app-2.1.2
`

**Comment by LoudSyncro** [comment]
Try running the installer with admin rights.

**Comment by turkeyphant** [comment]
> Try running the installer with admin rights.

That is running with admin rights. Same issue with and without.

**Comment by Dan1138** [comment]
The log file you posted is probably the wrong Squirrel installer log as it shows an install of 1Clipboard, an install of Wox, and two installs of hyper but no installs of Chia.  I had the same problem of the Chia installer opening the wrong Squirrel log file.  For me, the wrong log file it opened was %LOCALAPPDATA%\SquirrelTemp\SquirrelSetup.log while the real Chia error log it should have opened was at %LOCALAPPDATA%\SquirrelTemp\Squirrel-Install.log.  If you look at the correct log file, you may get a better idea of what exactly is failing.

For me, what was failing was that NVIDIA Share.exe was locking the DLL's libcrypto-1_1.dll and libssl-1_1.dll (found at %LOCALAPPDATA%\chia-blockchain\app-1.1.4\resources\app.asar.unpacked\daemon). I could not delete these files myself even after closing as much NVIDIA crap as I could.

My fix was to reboot into safe mode and delete those two files. After rebooting back into normal Windows (no longer safe mode) the installer then ran fine.

You could also do what @roybotbot suggests and just run the whole installer in safe mode, exit the app once it is done, and run the app (not the installer) again after rebooting back into windows (after existing safe mode).  I was concerned this might cause other issues so I chose to just delete the stuck files in safe mode instead and that worked too though that does require finding the right log and then deleting the right files, so a bit more work.
