### ISSUE TITLE
error when computing table3

### ISSUE THREAD

**Issue by myth2loki** [Chia-Network/chia-blockchain#3044]
Desktop (please complete the following information):

OS: Windows 10
amd 500x
48GB RAM
1tb M.2 for temp
10TB WD drive for final plot files.

Forward propagation table time: 1398.464 seconds. CPU (160.500%) Thu Apr 29 02:39:39 2021
Computing table 3	
        .......
        Bucket 122 uniform sort. Ram: 4.335GiB, u_sort min: 1.125GiB, qs min: 0.562GiB.
	Bucket 123 uniform sort. Ram: 4.335GiB, u_sort min: 2.250GiB, qs min: 0.563GiB.
	Bucket 124 uniform sort. Ram: 4.335GiB, u_sort min: 1.125GiB, qs min: 0.562GiB.
	Bucket 125 uniform sort. Ram: 4.335GiB, u_sort min: 1.125GiB, qs min: 0.562GiB.
	Bucket 126 uniform sort. Ram: 4.335GiB, u_sort min: 2.250GiB, qs min: 0.563GiB.
	Bucket 127 uniform sort. Ram: 4.335GiB, u_sort min: 1.125GiB, qs min: 0.562GiB.
	Total matches: 4295030832
Caught plotting error: Matches do not match with number of write entries 4295030832 4295030668
[13672] Failed to execute script chia
Traceback (most recent call last):
  File "chia\cmds\chia.py", line 81, in <module>
  File "chia\cmds\chia.py", line 77, in main
  File "click\core.py", line 829, in __call__
  File "click\core.py", line 782, in main
  File "click\core.py", line 1259, in invoke
  File "click\core.py", line 1259, in invoke
  File "click\core.py", line 1066, in invoke
  File "click\core.py", line 610, in invoke
  File "click\decorators.py", line 21, in new_func
  File "chia\cmds\plots.py", line 135, in create_cmd
  File "chia\plotting\create_plots.py", line 176, in create_plots
RuntimeError: Unknown exception

**Comment by lipalong** [comment]
Try checking your ram: disable overclocking and xmp, check cooling, run ram test, swap out your ram sticks until you find the one causing the problem.
