### ISSUE TITLE
Failed to execute script chia

### ISSUE THREAD

**Issue by maogo** [Chia-Network/chia-blockchain#3101]
Caught plotting error: std::bad_alloc
Traceback (most recent call last):
  File "chia/cmds/chia.py", line 81, in <module>
  File "chia/cmds/chia.py", line 77, in main
  File "click/core.py", line 829, in __call__
  File "click/core.py", line 782, in main
  File "click/core.py", line 1259, in invoke
  File "click/core.py", line 1259, in invoke
  File "click/core.py", line 1066, in invoke
  File "click/core.py", line 610, in invoke
  File "click/decorators.py", line 21, in new_func
  File "chia/cmds/plots.py", line 135, in create_cmd
  File "chia/plotting/create_plots.py", line 164, in create_plots
RuntimeError: std::exception
[10823] Failed to execute script chia

OS: Debian 10

Why did this happen?

**Comment by lvcivs** [comment]
Needs more info. What command did you run? How did you install? Which version did you install?
