### ISSUE TITLE
[BUG]Caught plotting error: Matches do not match with number of write entries 4294556721 4294556665

### ISSUE THREAD

**Issue by myth2loki** [Chia-Network/chia-blockchain#3102]
Caught plotting error: Matches do not match with number of write entries 4294556721 4294556665
[1328] Failed to execute script chia
Traceback (most recent call last):
  File "chia\cmds\chia.py", line 81, in <module>
  File "chia\cmds\chia.py", line 77, in main
  File "click\core.py", line 829, in __call__
  File "click\core.py", line 782, in main
  File "click\core.py", line 1259, in invoke
  File "click\core.py", line 1259, in invoke
  File "click\core.py", line 1066, in invoke
  File "click\core.py", line 610, in invoke
  File "click\decorators.py", line 21, in new_func
  File "chia\cmds\plots.py", line 135, in create_cmd
  File "chia\plotting\create_plots.py", line 176, in create_plots
RuntimeError: Unknown exception

**Comment by kenelf** [comment]
I got this error too, what is the reason causing this error?
