### ISSUE TITLE
[BUG] 'SSL error in data received' several times per minute on Linux farmer

### ISSUE THREAD

**Issue by malventano** [Chia-Network/chia-blockchain#3109]
Running from command line under Ubuntu (chia start farmer). After update to 1.1.2, logs began showing SSL errors several times per minute (approx. every 10 seconds, but not exactly in-step with challenges) as follows:

```
2021-04-29T11:29:01.253 full_node asyncio                 : ERROR    SSL error in data received
protocol: <asyncio.sslproto.SSLProtocol object at 0x7f113a08fc18>
transport: <_SelectorSocketTransport fd=149 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/usr/lib/python3.7/asyncio/sslproto.py", line 526, in data_received
    ssldata, appdata = self._sslpipe.feed_ssldata(data)
  File "/usr/lib/python3.7/asyncio/sslproto.py", line 207, in feed_ssldata
    self._sslobj.unwrap()
  File "/usr/lib/python3.7/ssl.py", line 767, in unwrap
    return self._sslobj.shutdown()
ssl.SSLError: [SSL: KRB5_S_INIT] application data after close notify (_ssl.c:2609)
```

While everything else appears to be working normally, I'm not sure if these errors would prevent successful wins. The same mainnet/db and wallet/db copied over to a Windows machine running 1.1.2 appears to run correctly and without throwing these errors.

**Comment by nocolife** [comment]
Are you using Debian? I get it constantly also.

```
2021-05-04T07:20:24.177 full_node asyncio                 : ERROR    SSL error in data received
protocol: <asyncio.sslproto.SSLProtocol object at 0x7f54825c5a90>
transport: <_SelectorSocketTransport fd=40 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/usr/lib/python3.7/asyncio/sslproto.py", line 526, in data_received
    ssldata, appdata = self._sslpipe.feed_ssldata(data)
  File "/usr/lib/python3.7/asyncio/sslproto.py", line 207, in feed_ssldata
    self._sslobj.unwrap()
  File "/usr/lib/python3.7/ssl.py", line 767, in unwrap
    return self._sslobj.shutdown()
ssl.SSLError: [SSL: KRB5_S_INIT] application data after close notify (_ssl.c:2609)

```

**Comment by papryczeq** [comment]
Same on rpi4. Chia version 1.1.3

`2021-05-04T20:08:44.264 full_node asyncio                 : ERROR    SSL error in data received
protocol: <asyncio.sslproto.SSLProtocol object at 0x7f6862ca90>
transport: <_SelectorSocketTransport fd=87 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/usr/lib/python3.7/asyncio/sslproto.py", line 526, in data_received
    ssldata, appdata = self._sslpipe.feed_ssldata(data)
  File "/usr/lib/python3.7/asyncio/sslproto.py", line 207, in feed_ssldata
    self._sslobj.unwrap()
  File "/usr/lib/python3.7/ssl.py", line 767, in unwrap
    return self._sslobj.shutdown()
ssl.SSLError: [SSL: KRB5_S_INIT] application data after close notify (_ssl.c:2609)`

**Comment by nocolife** [comment]
can't get answers on this anywhere. frustrating. Installed 1.1.4 today and made absolutely sure the full node and harvesters are all properly configured, still throwing out these errors constantly.

**Comment by malventano** [comment]
From the Keybase support chat, it appears to be a bug related to how Python 3.7-3.7.3 breaks down connections:
keybase://chat/chia_network.public#support/52843
https://github.com/aio-libs/aiohttp/issues/3535#issuecomment-483268542
