### ISSUE TITLE
[BUG] Errors with database transactions

### ISSUE THREAD

**Issue by wwwroth** [Chia-Network/chia-blockchain#3115]
I'm seeing errors in my log that are showing database transaction errors.

I've set up Chia GUI, added three plots and it shows them as farming.

- OS: Windows 10
- CPU: i7-9700K

```
2021-04-29T11:15:44.412 wallet chia.wallet.wallet_blockchain: ERROR    Error during db transaction: 
2021-04-29T11:15:47.489 wallet wallet_server              : ERROR    Exception:  <class 'concurrent.futures._base.CancelledError'>, closing connection None. Traceback (most recent call last):
  File "chia\server\server.py", line 521, in api_call
  File "asyncio\tasks.py", line 435, in wait_for
concurrent.futures._base.CancelledError
2021-04-29T11:15:47.490 wallet chia.wallet.wallet_blockchain: ERROR    Error during db transaction:
```

**Comment by b0wtieGIT** [comment]
Seeing the same error in debug.log. 41 plots farming

OS: Windows 10
CPU: i7-6700k

**Comment by chris8783** [comment]
Following, I'm having the same problem 

Windows 10
R9 3900X

**Comment by wwwroth** [comment]
Hopefully we can get some official dev help. I’m going to try and spend some time this weekend looking at what database the software is using and see if I can figure out a patch.

**Comment by wwwroth** [comment]
This seems to be resolved for me. I'm not exactly sure what did it, but I rebooted my plotter and farmer rig in an attempt to resolve #3268 and this was also resolved.
