### ISSUE TITLE
[help] RuntimeError: Unknown exception

### ISSUE THREAD

**Issue by byEpay** [Chia-Network/chia-blockchain#3210]
*I get this error when creating a plot, what can it be?*

2021-04-30T13:36:00.376  chia.plotting.create_plots       : [32mINFO    [0m Creating 1 plots of size 32, pool public key:  a5f352e7a3547e92c479c216d82ca2ef90a6136a29af1c407b873d92de400f989f1fa72ccbbc675eda13400f594c2d1e farmer public key: a96240704fb516110af78fbae12e300d5a12f2f84f712df69174a041314573fadb44fcb0b4b71e1d7ce240a7e5aa4b76[0m
2021-04-30T13:36:00.396  chia.plotting.create_plots       : [32mINFO    [0m Memo: a5f352e7a3547e92c479c216d82ca2ef90a6136a29af1c407b873d92de400f989f1fa72ccbbc675eda13400f594c2d1ea96240704fb516110af78fbae12e300d5a12f2f84f712df69174a041314573fadb44fcb0b4b71e1d7ce240a7e5aa4b766c9d836395183696088afb6d971a0bcb9f2341c2d798e3d7665e38d528642e3c[0m
2021-04-30T13:36:00.397  chia.plotting.create_plots       : [32mINFO    [0m Adding directory P:\ to harvester for farming[0m
2021-04-30T13:36:00.602  chia.plotting.create_plots       : [32mINFO    [0m Starting plot 1/1[0m
Caught plotting error: Bitfield plotting not supported by CPU
[2528] Failed to execute script chia
Traceback (most recent call last):
  File "chia\cmds\chia.py", line 81, in <module>
  File "chia\cmds\chia.py", line 77, in main
  File "click\core.py", line 829, in __call__
  File "click\core.py", line 782, in main
  File "click\core.py", line 1259, in invoke
  File "click\core.py", line 1259, in invoke
  File "click\core.py", line 1066, in invoke
  File "click\core.py", line 610, in invoke
  File "click\decorators.py", line 21, in new_func
  File "chia\cmds\plots.py", line 135, in create_cmd
  File "chia\plotting\create_plots.py", line 176, in create_plots
RuntimeError: Unknown exception

*My pc is old*
Intel Core 2 Quad
4gb Ram ddr2
2tb hdd Seagate
2tb hdd Seagate

**Comment by sargonas** [comment]
I see the line “Caught plotting error: Bitfield plotting not supported by CPU” in there. What CPU are you trying to use? Any CPU from a technology generation older than around 10 years ago is going to trigger this, and is not bitfield compatible. If you check the box of “do not use bitfield” in the GUI, or use the CLI flag “-e” then  you should be able to plot.
