### ISSUE TITLE
[HELP] WebSocket port error when running `chia start farmer`

### ISSUE THREAD

**Issue by wwwroth** [Chia-Network/chia-blockchain#3268]
**Describe the bug**
Powershell error message when running `chia start farmer`.

**To Reproduce**
Run `chia start farmer`!

**Expected behavior**
I think the error is not relevant and the farmer is running, but the WebSocket error has me concerned.

- Windows 10
- i7-9700k

```
PS C:\Users\wwwroth> chia start farmer
Daemon not started yet
Starting daemon
chia_harvester: started
chia_farmer: started
chia_full_node: started
chia_wallet: started
PS C:\Users\wwwroth> Traceback (most recent call last):
  File "chia\server\start_farmer.py", line 68, in <module>
  File "chia\server\start_farmer.py", line 64, in main
  File "chia\server\start_service.py", line 218, in run_service
  File "asyncio\runners.py", line 43, in run
  File "asyncio\base_events.py", line 587, in run_until_complete
  File "chia\server\start_service.py", line 212, in async_run_service
  File "chia\server\start_service.py", line 156, in run
  File "chia\server\start_service.py", line 132, in start
  File "chia\server\server.py", line 213, in start_server
  File "aiohttp\web_runner.py", line 128, in start
  File "asyncio\base_events.py", line 1389, in create_server
OSError: [Errno 10048] error while attempting to bind on address ('0.0.0.0', 8447): only one usage of each socket address (protocol/network address/port) is normally permitted
[18020] Failed to execute script start_farmer
```

**Comment by sargonas** [comment]
It looks like you possibly may already have a duplicate process running, making use of the socket.. can you confirm for sure there are no rogue processes before trying `chia start farmer` ? Worse case, you can try rebooting and then doing it and see what happens.

**Comment by drch90** [comment]
I ran into the same problem
```
chia start node
Daemon not started yet
Starting daemon
chia_full_node: started
PS C:\Users\drch> Traceback (most recent call last):
  File "chia\server\start_full_node.py", line 65, in <module>
  File "chia\server\start_full_node.py", line 60, in main
Exception in thread Thread-2:
Traceback (most recent call last):
  File "aiosqlite\core.py", line 109, in run
  File "asyncio\base_events.py", line 736, in call_soon_threadsafe
  File "asyncio\base_events.py", line 479, in _check_closed
RuntimeError: Event loop is closed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "threading.py", line 926, in _bootstrap_inner
  File "aiosqlite\core.py", line 117, in run
  File "asyncio\base_events.py", line 736, in call_soon_threadsafe
  File "asyncio\base_events.py", line 479, in _check_closed
RuntimeError: Event loop is closed

  File "chia\server\start_service.py", line 218, in run_service
  File "asyncio\runners.py", line 43, in run
  File "asyncio\base_events.py", line 587, in run_until_complete
  File "chia\server\start_service.py", line 212, in async_run_service
  File "chia\server\start_service.py", line 156, in run
  File "chia\server\start_service.py", line 132, in start
  File "chia\server\server.py", line 213, in start_server
  File "aiohttp\web_runner.py", line 128, in start
  File "asyncio\base_events.py", line 1389, in create_server
OSError: [Errno 10048] error while attempting to bind on address ('0.0.0.0', 8555): 通常每个套接字地址(协议/网络地址/端 口)只允许使用一次。
[16552] Failed to execute script start_full_node
```
And the port is not in use

**Comment by wwwroth** [comment]
This resolved for me with a reboot. I believe I was running the daemon via the GUI but also attempting to run the daemon again from the CMD utility.
