### ISSUE TITLE
[help] KeyError: 'min_mainnet_k_size' after creating the plot on harvester

### ISSUE THREAD

**Issue by markputrella74** [Chia-Network/chia-blockchain#3320]
Hi,
I run via windows powershell on my harvester but I return an error :

chia plots create -k 32 -b 4000 -t D:\CHIA -d D:\CHIA

Traceback (most recent call last):
File "chia\cmds\chia.py", line 81, in
File "chia\cmds\chia.py", line 77, in main
File "click\core.py", line 829, in call
File "click\core.py", line 782, in main
File "click\core.py", line 1259, in invoke
File "click\core.py", line 1259, in invoke
File "click\core.py", line 1066, in invoke
File "click\core.py", line 610, in invoke
File "click\decorators.py", line 21, in new_func
File "chia\cmds\plots.py", line 135, in create_cmd
File "chia\plotting\create_plots.py", line 76, in create_plots

KeyError: 'min_mainnet_k_size'
[3948] Failed to execute script chia

Seems a wrong number of the k parameters ?
With the GUI i have always used K 32...
Thank you for your help,
Matteo

**Comment by davemcphee** [comment]
`KeyError: 'min_mainnet_k_size'` indicates that either the config file wasn't loaded, or it was, but it doesn't contain they var `min_mainnet_k_size`.

Check your config file (unsure of it's default location on windows, maybe `..\Users\<yourusername>\.chia\mainnet\config\config.yaml` ?) and make sure it contains that variable.

**Comment by markputrella74** [comment]
you are 100% correct !! 
Many thanks, for an unknown reason the line was missing...
I have wrote manually the var and it works !
Many thanks !!!
