### ISSUE TITLE
[BUG] ELF load command address/offset not properly aligned

### ISSUE THREAD

**Issue by keybreak** [Chia-Network/chia-blockchain#3349]
Linux, Manjaro KDE, AUR  **chia-bin 1.1.2-1** (created from original .deb)

Seems to result in infinite 'Connecting to wallet' loop
~~~bash
Have cert
stderr: Traceback (most recent call last):
  File "chia/server/start_full_node.py", line 8, in <module>
  File "PyInstaller/loader/pyimod03_importers.py", line 531, in exec_module
  File "chia/full_node/full_node.py", line 14, in <module>
  File "PyInstaller/loader/pyimod03_importers.py", line 531, in exec_module
  File "chia/consensus/block_creation.py", line 12, in <module>
  File "PyInstaller/loader/pyimod03_importers.py", line 531, in exec_module
  File "chia/consensus/blockchain_interface.py", line 6, in <module>
  File "PyInstaller/loader/pyimod03_importers.py", line 531, in exec_module
  File "chia/types/blockchain_format/vdf.py", line 7, in <module>
ImportError: /usr/lib/chia-blockchain/resources/app.asar.unpacked/daemon/chiavdf.cpython-38-x86_64-linux-gnu.so: ELF load command address/offset not properly aligned
[53290] Failed to execute script start_full_node
stderr: Traceback (most recent call last):
  File "chia/server/start_wallet.py", line 7, in <module>
  File "PyInstaller/loader/pyimod03_importers.py", line 531, in exec_module
  File "chia/rpc/wallet_rpc_api.py", line 23, in <module>
  File "PyInstaller/loader/pyimod03_importers.py", line 531, in exec_module
  File "chia/wallet/cc_wallet/cc_wallet.py", line 14, in <module>
  File "PyInstaller/loader/pyimod03_importers.py", line 531, in exec_module
  File "chia/protocols/wallet_protocol.py", line 7, in <module>
  File "PyInstaller/loader/pyimod03_importers.py", line 531, in exec_module
  File "chia/types/header_block.py", line 5, in <module>
  File "PyInstaller/loader/pyimod03_importers.py", line 531, in exec_module
  File "chia/types/blockchain_format/reward_chain_block.py", line 8, in <module>
  File "PyInstaller/loader/pyimod03_importers.py", line 531, in exec_module
  File "chia/types/blockchain_format/vdf.py", line 7, in <module>
ImportError: /usr/lib/chia-blockchain/resources/app.asar.unpacked/daemon/chiavdf.cpython-38-x86_64-linux-gnu.so: ELF load command address/offset not properly aligned
[53288] Failed to execute script start_wallet
stderr: Traceback (most recent call last):
  File "chia/server/start_farmer.py", line 68, in <module>
  File "chia/server/start_farmer.py", line 63, in main
  File "chia/server/start_farmer.py", line 38, in service_kwargs_for_farmer
  File "chia/farmer/farmer.py", line 73, in __init__
RuntimeError: No keys exist. Please run 'chia keys generate' or open the UI.
~~~

and here's coredump in journalctl

~~~bash
systemd-coredump[53791]: Process 53185 (chia-blockchain) of user 1000 dumped core.
                                                 
Stack trace of thread 53196:
#0  0x000055e8e4cc4df9 n/a (chia-blockchain + 0x3f51df9)
#1  0x000055e8e428fef7 n/a (chia-blockchain + 0x351cef7)
#2  0x000055e8e428ddd1 n/a (chia-blockchain + 0x351add1)
#3  0x000055e8e428c483 n/a (chia-blockchain + 0x3519483)
#4  0x000055e8e4296673 n/a (chia-blockchain + 0x3523673)
#5  0x000055e8e412e8d3 n/a (chia-blockchain + 0x33bb8d3)
#6  0x000055e8e418e716 n/a (chia-blockchain + 0x341b716)
#7  0x000055e8e418e99d n/a (chia-blockchain + 0x341b99d)
#8  0x000055e8e4cfcc6e n/a (chia-blockchain + 0x3f89c6e)
#9  0x000055e8e4d0d061 n/a (chia-blockchain + 0x3f9a061)
#10 0x000055e8e4d0cd3e n/a (chia-blockchain + 0x3f99d3e)
#11 0x000055e8e4d59f8f n/a (chia-blockchain + 0x3fe6f8f)
#12 0x000055e8e4d0d659 n/a (chia-blockchain + 0x3f9a659)
#13 0x000055e8e4ce4a32 n/a (chia-blockchain + 0x3f71a32)
#14 0x000055e8e414aead n/a (chia-blockchain + 0x33d7ead)
#15 0x000055e8e4d25a9d n/a (chia-blockchain + 0x3fb2a9d)
#16 0x000055e8e4d4a3c1 n/a (chia-blockchain + 0x3fd73c1)
#17 0x00007f591196a299 start_thread (libpthread.so.0 + 0x9299)
#18 0x00007f59102dc053 __clone (libc.so.6 + 0xff053)

Stack trace of thread 53226:
#0  0x000055e8e28c2368 n/a (chia-blockchain + 0x1b4f368)
#1  0x000055e8e28c0146 n/a (chia-blockchain + 0x1b4d146)
#2  0x000055e8e28bff40 n/a (chia-blockchain + 0x1b4cf40)
#3  0x000055e8e28c06d6 n/a (chia-blockchain + 0x1b4d6d6)
#4  0x000055e8e28bd590 n/a (chia-blockchain + 0x1b4a590)
#5  0x000055e8e28bd497 n/a (chia-blockchain + 0x1b4a497)
#6  0x000055e8e28bd204 n/a (chia-blockchain + 0x1b4a204)
#7  0x000055e8e28c39fd n/a (chia-blockchain + 0x1b509fd)
#8  0x000055e8e4d515be _ZnwmRKSt9nothrow_t (chia-blockchain + 0x3fde5be)
#9  0x000055e8e502ae23 n/a (chia-blockchain + 0x42b7e23)
#10 0x000055e8e502a3b0 n/a (chia-blockchain + 0x42b73b0)
#11 0x000055e8e32eda5c n/a (chia-blockchain + 0x257aa5c)
#12 0x000055e8e32ed020 n/a (chia-blockchain + 0x257a020)
#13 0x000055e8e32e92aa n/a (chia-blockchain + 0x25762aa)
#14 0x000055e8e32ce8eb n/a (chia-blockchain + 0x255b8eb)
#15 0x000055e8e418e597 n/a (chia-blockchain + 0x341b597)
#16 0x000055e8e418e381 n/a (chia-blockchain + 0x341b381)
#17 0x000055e8e4cfcc6e n/a (chia-blockchain + 0x3f89c6e)
#18 0x000055e8e4d138f7 n/a (chia-blockchain + 0x3fa08f7)
#19 0x000055e8e4d1340e n/a (chia-blockchain + 0x3fa040e)
#20 0x000055e8e4d49c38 n/a (chia-blockchain + 0x3fd6c38)
#21 0x000055e8e4d12f3e n/a (chia-blockchain + 0x3f9ff3e)
#22 0x000055e8e4d1fae4 n/a (chia-blockchain + 0x3facae4)
#23 0x000055e8e4d1f84d n/a (chia-blockchain + 0x3fac84d)
#24 0x000055e8e4d4a3c1 n/a (chia-blockchain + 0x3fd73c1)
#25 0x00007f591196a299 start_thread (libpthread.so.0 + 0x9299)
#26 0x00007f59102dc053 __clone (libc.so.6 + 0xff053)

Stack trace of thread 53781:
#0  0x00007f59119769ba __futex_abstimed_wait_common64 (libpthread.so.0 + 0x159ba)
#1  0x00007f5911970574 pthread_cond_timedwait@@GLIBC_2.3.2 (libpthread.so.0 + 0xf574)
#2  0x000055e8e4d46511 n/a (chia-blockchain + 0x3fd3511)
#3  0x000055e8e4d46b77 n/a (chia-blockchain + 0x3fd3b77)
#4  0x000055e8e4d1f288 n/a (chia-blockchain + 0x3fac288)
#5  0x000055e8e4d1fbc9 n/a (chia-blockchain + 0x3facbc9)
#6  0x000055e8e4d1f7ed n/a (chia-blockchain + 0x3fac7ed)
#7  0x000055e8e4d4a3c1 n/a (chia-blockchain + 0x3fd73c1)
#8  0x00007f591196a299 start_thread (libpthread.so.0 + 0x9299)
#9  0x00007f59102dc053 __clone (libc.so.6 + 0xff053)

Stack trace of thread 53185:
#0  0x00007f59102d137f __poll (libc.so.6 + 0xf437f)
#1  0x00007f591186eae8 n/a (libglib-2.0.so.0 + 0xa7ae8)
#2  0x00007f5911818781 g_main_context_iteration (libglib-2.0.so.0 + 0x51781)
#3  0x000055e8e4cc8cb6 n/a (chia-blockchain + 0x3f55cb6)
#4  0x000055e8e4d0d659 n/a (chia-blockchain + 0x3f9a659)
#5  0x000055e8e4ce4a32 n/a (chia-blockchain + 0x3f71a32)
#6  0x000055e8e41473eb n/a (chia-blockchain + 0x33d43eb)
#7  0x000055e8e4149312 n/a (chia-blockchain + 0x33d6312)
#8  0x000055e8e414461c n/a (chia-blockchain + 0x33d161c)
#9  0x000055e8e403dffa n/a (chia-blockchain + 0x32caffa)
#10 0x000055e8e403dc1b n/a (chia-blockchain + 0x32cac1b)
#11 0x000055e8e32f5c64 n/a (chia-blockchain + 0x2582c64)
#12 0x000055e8e32f6372 n/a (chia-blockchain + 0x2583372)
#13 0x000055e8e2678bb6 n/a (chia-blockchain + 0x1905bb6)
#14 0x00007f5910204b25 __libc_start_main (libc.so.6 + 0x27b25)
#15 0x000055e8e2662a6a _start (chia-blockchain + 0x18efa6a)

Stack trace of thread 53193:
#0  0x00007f59102dc39e epoll_wait (libc.so.6 + 0xff39e)
#1  0x000055e8e4e85ded n/a (chia-blockchain + 0x4112ded)
#2  0x000055e8e4e8388b n/a (chia-blockchain + 0x411088b)
#3  0x000055e8e4d5a0d9 n/a (chia-blockchain + 0x3fe70d9)
#4  0x000055e8e4d0d659 n/a (chia-blockchain + 0x3f9a659)
#5  0x000055e8e4ce4a32 n/a (chia-blockchain + 0x3f71a32)
#6  0x000055e8e4d179ad n/a (chia-blockchain + 0x3fa49ad)
#7  0x000055e8e4d25a9d n/a (chia-blockchain + 0x3fb2a9d)
#8  0x000055e8e4d4a3c1 n/a (chia-blockchain + 0x3fd73c1)
#9  0x00007f591196a299 start_thread (libpthread.so.0 + 0x9299)
#10 0x00007f59102dc053 __clone (libc.so.6 + 0xff053)

Stack trace of thread 53186:
#0  0x00007f59102d137f __poll (libc.so.6 + 0xf437f)
#1  0x000055e8e44b69ef n/a (chia-blockchain + 0x37439ef)
#2  0x000055e8e4d4a3c1 n/a (chia-blockchain + 0x3fd73c1)
#3  0x00007f591196a299 start_thread (libpthread.so.0 + 0x9299)
#4  0x00007f59102dc053 __clone (libc.so.6 + 0xff053)

Stack trace of thread 53200:
#0  0x00007f59119769ba __futex_abstimed_wait_common64 (libpthread.so.0 + 0x159ba)
#1  0x00007f5911970260 pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0 + 0xf260)
#2  0x000055e8e26736a9 uv_cond_wait (chia-blockchain + 0x19006a9)
#3  0x000055e8e8557c22 n/a (chia-blockchain + 0x77e4c22)
#4  0x000055e8e8555c48 n/a (chia-blockchain + 0x77e2c48)
#5  0x00007f591196a299 start_thread (libpthread.so.0 + 0x9299)
#6  0x00007f59102dc053 __clone (libc.so.6 + 0xff053)

Stack trace of thread 53223:
#0  0x00007f59119769ba __futex_abstimed_wait_common64 (libpthread.so.0 + 0x159ba)
#1  0x00007f5911970260 pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0 + 0xf260)
#2  0x000055e8e4d4637d n/a (chia-blockchain + 0x3fd337d)
#3  0x000055e8e5b51c65 n/a (chia-blockchain + 0x4ddec65)
#4  0x000055e8e4d4a3c1 n/a (chia-blockchain + 0x3fd73c1)
#5  0x00007f591196a299 start_thread (libpthread.so.0 + 0x9299)
#6  0x00007f59102dc053 __clone (libc.so.6 + 0xff053)

Stack trace of thread 53202:
#0  0x00007f59119769ba __futex_abstimed_wait_common64 (libpthread.so.0 + 0x159ba)
#1  0x00007f5911972b98 __new_sem_wait_slow64.constprop.0 (libpthread.so.0 + 0x11b98)
#2  0x000055e8e267350b uv_sem_wait (chia-blockchain + 0x190050b)
#3  0x000055e8e85c0713 n/a (chia-blockchain + 0x784d713)
#4  0x00007f591196a299 start_thread (libpthread.so.0 + 0x9299)
#5  0x00007f59102dc053 __clone (libc.so.6 + 0xff053)

Stack trace of thread 53197:
#0  0x00007f59119769ba __futex_abstimed_wait_common64 (libpthread.so.0 + 0x159ba)
#1  0x00007f5911970260 pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0 + 0xf260)
#2  0x000055e8e4d4637d n/a (chia-blockchain + 0x3fd337d)
#3  0x000055e8e4d46dd6 n/a (chia-blockchain + 0x3fd3dd6)
#4  0x000055e8e4d4692e n/a (chia-blockchain + 0x3fd392e)
#5  0x000055e8e4cc87dc n/a (chia-blockchain + 0x3f557dc)
#6  0x000055e8e4d0d659 n/a (chia-blockchain + 0x3f9a659)
#7  0x000055e8e4ce4a32 n/a (chia-blockchain + 0x3f71a32)
#8  0x000055e8e4d25a9d n/a (chia-blockchain + 0x3fb2a9d)
#9  0x000055e8e4d4a3c1 n/a (chia-blockchain + 0x3fd73c1)
#10 0x00007f591196a299 start_thread (libpthread.so.0 + 0x9299)
#11 0x00007f59102dc053 __clone (libc.so.6 + 0xff053)

Stack trace of thread 53227:
#0  0x00007f59119769ba __futex_abstimed_wait_common64 (libpthread.so.0 + 0x159ba)
#1  0x00007f5911970260 pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0 + 0xf260)
#2  0x000055e8e4d4637d n/a (chia-blockchain + 0x3fd337d)
#3  0x000055e8e4d46dd6 n/a (chia-blockchain + 0x3fd3dd6)
#4  0x000055e8e4d4692e n/a (chia-blockchain + 0x3fd392e)
#5  0x000055e8e4cc87dc n/a (chia-blockchain + 0x3f557dc)
#6  0x000055e8e4d0d659 n/a (chia-blockchain + 0x3f9a659)
#7  0x000055e8e4ce4a32 n/a (chia-blockchain + 0x3f71a32)
#8  0x000055e8e4d25a9d n/a (chia-blockchain + 0x3fb2a9d)
#9  0x000055e8e4d4a3c1 n/a (chia-blockchain + 0x3fd73c1)
#10 0x00007f591196a299 start_thread (libpthread.so.0 + 0x9299)
#11 0x00007f59102dc053 __clone (libc.so.6 + 0xff053)

Stack trace of thread 53199:
#0  0x00007f59119769ba __futex_abstimed_wait_common64 (libpthread.so.0 + 0x159ba)
#1  0x00007f5911970260 pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0 + 0xf260)
#2  0x000055e8e26736a9 uv_cond_wait (chia-blockchain + 0x19006a9)
#3  0x000055e8e8557c22 n/a (chia-blockchain + 0x77e4c22)
#4  0x000055e8e8555c48 n/a (chia-blockchain + 0x77e2c48)
#5  0x00007f591196a299 start_thread (libpthread.so.0 + 0x9299)
#6  0x00007f59102dc053 __clone (libc.so.6 + 0xff053)

Stack trace of thread 53201:
#0  0x00007f59119769ba __futex_abstimed_wait_common64 (libpthread.so.0 + 0x159ba)
#1  0x00007f5911970260 pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0 + 0xf260)
#2  0x000055e8e26736a9 uv_cond_wait (chia-blockchain + 0x19006a9)
#3  0x000055e8e8557c22 n/a (chia-blockchain + 0x77e4c22)
#4  0x000055e8e8555c48 n/a (chia-blockchain + 0x77e2c48)
#5  0x00007f591196a299 start_thread (libpthread.so.0 + 0x9299)
#6  0x00007f59102dc053 __clone (libc.so.6 + 0xff053)

Stack trace of thread 53214:
#0  0x00007f59102d137f __poll (libc.so.6 + 0xf437f)
#1  0x00007f591186eae8 n/a (libglib-2.0.so.0 + 0xa7ae8)
#2  0x00007f5911818781 g_main_context_iteration (libglib-2.0.so.0 + 0x51781)
#3  0x00007f59118187d2 n/a (libglib-2.0.so.0 + 0x517d2)
#4  0x00007f59118490c1 n/a (libglib-2.0.so.0 + 0x820c1)
#5  0x00007f591196a299 start_thread (libpthread.so.0 + 0x9299)
#6  0x00007f59102dc053 __clone (libc.so.6 + 0xff053)

Stack trace of thread 53217:
#0  0x00007f59102dc39e epoll_wait (libc.so.6 + 0xff39e)
#1  0x000055e8e4e85ded n/a (chia-blockchain + 0x4112ded)
#2  0x000055e8e4e8388b n/a (chia-blockchain + 0x411088b)
#3  0x000055e8e4d5a02b n/a (chia-blockchain + 0x3fe702b)
#4  0x000055e8e4d0d659 n/a (chia-blockchain + 0x3f9a659)
#5  0x000055e8e4ce4a32 n/a (chia-blockchain + 0x3f71a32)
#6  0x000055e8e4d25a9d n/a (chia-blockchain + 0x3fb2a9d)
#7  0x000055e8e4d4a3c1 n/a (chia-blockchain + 0x3fd73c1)
#8  0x00007f591196a299 start_thread (libpthread.so.0 + 0x9299)
#9  0x00007f59102dc053 __clone (libc.so.6 + 0xff053)

Stack trace of thread 53218:
#0  0x00007f59102a4125 clock_nanosleep@@GLIBC_2.17 (libc.so.6 + 0xc7125)
#1  0x00007f59102a9357 __nanosleep (libc.so.6 + 0xcc357)
#2  0x00007f59102a928e sleep (libc.so.6 + 0xcc28e)
#3  0x000055e8e27ba929 n/a (chia-blockchain + 0x1a47929)
#4  0x000055e8e4d4a3c1 n/a (chia-blockchain + 0x3fd73c1)
#5  0x00007f591196a299 start_thread (libpthread.so.0 + 0x9299)
#6  0x00007f59102dc053 __clone (libc.so.6 + 0xff053)

Stack trace of thread 53224:
#0  0x00007f59119769ba __futex_abstimed_wait_common64 (libpthread.so.0 + 0x159ba)
#1  0x00007f5911970260 pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0 + 0xf260)
#2  0x000055e8e4d4637d n/a (chia-blockchain + 0x3fd337d)
#3  0x000055e8e4d46dd6 n/a (chia-blockchain + 0x3fd3dd6)
#4  0x000055e8e4d4692e n/a (chia-blockchain + 0x3fd392e)
#5  0x000055e8e4cc87dc n/a (chia-blockchain + 0x3f557dc)
#6  0x000055e8e4d0d659 n/a (chia-blockchain + 0x3f9a659)
#7  0x000055e8e4ce4a32 n/a (chia-blockchain + 0x3f71a32)
#8  0x000055e8e4d25a9d n/a (chia-blockchain + 0x3fb2a9d)
#9  0x000055e8e4d4a3c1 n/a (chia-blockchain + 0x3fd73c1)
#10 0x00007f591196a299 start_thread (libpthread.so.0 + 0x9299)
#11 0x00007f59102dc053 __clone (libc.so.6 + 0xff053)

Stack trace of thread 53230:
#0  0x00007f59119769ba __futex_abstimed_wait_common64 (libpthread.so.0 + 0x159ba)
#1  0x00007f5911970260 pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0 + 0xf260)
#2  0x000055e8e4d4637d n/a (chia-blockchain + 0x3fd337d)
#3  0x000055e8e4d46dd6 n/a (chia-blockchain + 0x3fd3dd6)
#4  0x000055e8e4d4692e n/a (chia-blockchain + 0x3fd392e)
#5  0x000055e8e4d1f27a n/a (chia-blockchain + 0x3fac27a)
#6  0x000055e8e4d1fbc9 n/a (chia-blockchain + 0x3facbc9)
#7  0x000055e8e4d1f81d n/a (chia-blockchain + 0x3fac81d)
#8  0x000055e8e4d4a3c1 n/a (chia-blockchain + 0x3fd73c1)
#9  0x00007f591196a299 start_thread (libpthread.so.0 + 0x9299)
#10 0x00007f59102dc053 __clone (libc.so.6 + 0xff053)

Stack trace of thread 53236:
#0  0x00007f59119769ba __futex_abstimed_wait_common64 (libpthread.so.0 + 0x159ba)
#1  0x00007f5911970260 pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0 + 0xf260)
#2  0x000055e8e4d4637d n/a (chia-blockchain + 0x3fd337d)
#3  0x000055e8e4d46dd6 n/a (chia-blockchain + 0x3fd3dd6)
#4  0x000055e8e4d4692e n/a (chia-blockchain + 0x3fd392e)
#5  0x000055e8e4cc87dc n/a (chia-blockchain + 0x3f557dc)
#6  0x000055e8e4d0d659 n/a (chia-blockchain + 0x3f9a659)
#7  0x000055e8e4ce4a32 n/a (chia-blockchain + 0x3f71a32)
#8  0x000055e8e4d25a9d n/a (chia-blockchain + 0x3fb2a9d)
#9  0x000055e8e4d4a3c1 n/a (chia-blockchain + 0x3fd73c1)
#10 0x00007f591196a299 start_thread (libpthread.so.0 + 0x9299)
#11 0x00007f59102dc053 __clone (libc.so.6 + 0xff053)

Stack trace of thread 53225:
#0  0x00007f59102dc39e epoll_wait (libc.so.6 + 0xff39e)
#1  0x000055e8e27c213c n/a (chia-blockchain + 0x1a4f13c)
#2  0x000055e8e2798108 n/a (chia-blockchain + 0x1a25108)
#3  0x00007f591196a299 start_thread (libpthread.so.0 + 0x9299)
#4  0x00007f59102dc053 __clone (libc.so.6 + 0xff053)

Stack trace of thread 53198:
#0  0x00007f59102dc39e epoll_wait (libc.so.6 + 0xff39e)
#1  0x000055e8e26764a4 n/a (chia-blockchain + 0x19034a4)
#2  0x000055e8e26682d9 uv_run (chia-blockchain + 0x18f52d9)
#3  0x000055e8e8557a71 n/a (chia-blockchain + 0x77e4a71)
#4  0x00007f591196a299 start_thread (libpthread.so.0 + 0x9299)
#5  0x00007f59102dc053 __clone (libc.so.6 + 0xff053)

Stack trace of thread 53194:
#0  0x00007f59119769ba __futex_abstimed_wait_common64 (libpthread.so.0 + 0x159ba)
#1  0x00007f5911970574 pthread_cond_timedwait@@GLIBC_2.3.2 (libpthread.so.0 + 0xf574)
#2  0x000055e8e4d46511 n/a (chia-blockchain + 0x3fd3511)
#3  0x000055e8e4d46b77 n/a (chia-blockchain + 0x3fd3b77)
#4  0x000055e8e4d1f288 n/a (chia-blockchain + 0x3fac288)
#5  0x000055e8e4d1fbc9 n/a (chia-blockchain + 0x3facbc9)
#6  0x000055e8e4d1f7ed n/a (chia-blockchain + 0x3fac7ed)
#7  0x000055e8e4d4a3c1 n/a (chia-blockchain + 0x3fd73c1)
#8  0x00007f591196a299 start_thread (libpthread.so.0 + 0x9299)
#9  0x00007f59102dc053 __clone (libc.so.6 + 0xff053)

Stack trace of thread 53235:
#0  0x00007f59102dc39e epoll_wait (libc.so.6 + 0xff39e)
#1  0x000055e8e4e85ded n/a (chia-blockchain + 0x4112ded)
#2  0x000055e8e4e8388b n/a (chia-blockchain + 0x411088b)
#3  0x000055e8e4d5a0d9 n/a (chia-blockchain + 0x3fe70d9)
#4  0x000055e8e4d0d659 n/a (chia-blockchain + 0x3f9a659)
#5  0x000055e8e4ce4a32 n/a (chia-blockchain + 0x3f71a32)
#6  0x000055e8e4d25a9d n/a (chia-blockchain + 0x3fb2a9d)
#7  0x000055e8e4d4a3c1 n/a (chia-blockchain + 0x3fd73c1)
#8  0x00007f591196a299 start_thread (libpthread.so.0 + 0x9299)
#9  0x00007f59102dc053 __clone (libc.so.6 + 0xff053)

Stack trace of thread 53788:
#0  0x00007f59102d137f __poll (libc.so.6 + 0xf437f)
#1  0x00007f590533b654 n/a (libpulse.so.0 + 0x33654)
#2  0x00007f59053249a9 pa_mainloop_poll (libpulse.so.0 + 0x1c9a9)
#3  0x00007f590532f281 pa_mainloop_iterate (libpulse.so.0 + 0x27281)
#4  0x00007f590532f331 pa_mainloop_run (libpulse.so.0 + 0x27331)
#5  0x00007f590533f7fe n/a (libpulse.so.0 + 0x377fe)
#6  0x00007f59052d95cc n/a (libpulsecommon-14.2.so + 0x565cc)
#7  0x00007f591196a299 start_thread (libpthread.so.0 + 0x9299)
#8  0x00007f59102dc053 __clone (libc.so.6 + 0xff053)

Stack trace of thread 53783:
#0  0x00007f59102d6a9d syscall (libc.so.6 + 0xf9a9d)
#1  0x00007f591186906b g_cond_wait_until (libglib-2.0.so.0 + 0xa206b)
#2  0x00007f59117ea8b3 n/a (libglib-2.0.so.0 + 0x238b3)
#3  0x00007f59117eaa44 g_async_queue_timeout_pop (libglib-2.0.so.0 + 0x23a44)
#4  0x00007f591184bd2a n/a (libglib-2.0.so.0 + 0x84d2a)
#5  0x00007f59118490c1 n/a (libglib-2.0.so.0 + 0x820c1)
#6  0x00007f591196a299 start_thread (libpthread.so.0 + 0x9299)
#7  0x00007f59102dc053 __clone (libc.so.6 + 0xff053)

Stack trace of thread 53231:
#0  0x00007f59119769ba __futex_abstimed_wait_common64 (libpthread.so.0 + 0x159ba)
#1  0x00007f5911970260 pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0 + 0xf260)
#2  0x000055e8e4d4637d n/a (chia-blockchain + 0x3fd337d)
#3  0x000055e8e4d46dd6 n/a (chia-blockchain + 0x3fd3dd6)
#4  0x000055e8e4d4692e n/a (chia-blockchain + 0x3fd392e)
#5  0x000055e8e4cc87dc n/a (chia-blockchain + 0x3f557dc)
#6  0x000055e8e4d0d659 n/a (chia-blockchain + 0x3f9a659)
#7  0x000055e8e4ce4a32 n/a (chia-blockchain + 0x3f71a32)
#8  0x000055e8e4d25a9d n/a (chia-blockchain + 0x3fb2a9d)
#9  0x000055e8e4d4a3c1 n/a (chia-blockchain + 0x3fd73c1)
#10 0x00007f591196a299 start_thread (libpthread.so.0 + 0x9299)
#11 0x00007f59102dc053 __clone (libc.so.6 + 0xff053)

Stack trace of thread 53220:
#0  0x00007f59102d3ad1 __select (libc.so.6 + 0xf6ad1)
#1  0x000055e8e4d4d16c n/a (chia-blockchain + 0x3fda16c)
#2  0x000055e8e4d4a3c1 n/a (chia-blockchain + 0x3fd73c1)
#3  0x00007f591196a299 start_thread (libpthread.so.0 + 0x9299)
#4  0x00007f59102dc053 __clone (libc.so.6 + 0xff053)

Stack trace of thread 53782:
#0  0x00007f59119769ba __futex_abstimed_wait_common64 (libpthread.so.0 + 0x159ba)
#1  0x00007f5911970574 pthread_cond_timedwait@@GLIBC_2.3.2 (libpthread.so.0 + 0xf574)
#2  0x000055e8e4d46511 n/a (chia-blockchain + 0x3fd3511)
#3  0x000055e8e4d46b77 n/a (chia-blockchain + 0x3fd3b77)
#4  0x000055e8e4d1f288 n/a (chia-blockchain + 0x3fac288)
#5  0x000055e8e4d1f953 n/a (chia-blockchain + 0x3fac953)
#6  0x000055e8e4d1f7ed n/a (chia-blockchain + 0x3fac7ed)
#7  0x000055e8e4d4a3c1 n/a (chia-blockchain + 0x3fd73c1)
#8  0x00007f591196a299 start_thread (libpthread.so.0 + 0x9299)
#9  0x00007f59102dc053 __clone (libc.so.6 + 0xff053)

Stack trace of thread 53215:
#0  0x00007f59102d137f __poll (libc.so.6 + 0xf437f)
#1  0x00007f591186eae8 n/a (libglib-2.0.so.0 + 0xa7ae8)
#2  0x00007f591181a593 g_main_loop_run (libglib-2.0.so.0 + 0x53593)
#3  0x00007f591170a558 n/a (libgio-2.0.so.0 + 0x102558)
#4  0x00007f59118490c1 n/a (libglib-2.0.so.0 + 0x820c1)
#5  0x00007f591196a299 start_thread (libpthread.so.0 + 0x9299)
#6  0x00007f59102dc053 __clone (libc.so.6 + 0xff053)

~~~

**Comment by keybreak** [comment]
**chia-bin 1.1.3-1** - same errors, please help :scream: :scream_cat:

**Comment by lukeomatik** [comment]
Same on Manjaro KDE for https://aur.archlinux.org/packages/chia-bin
upgraded from https://aur.archlinux.org/packages/chia-gui/
(removed 1.1.2 then build 1.1.3 one)

Reverted to the old 1.1.2 until further updates :(

**Comment by keybreak** [comment]
Fixed by AUR chia-bin 1.1.4-1

**Comment by lastb0isct** [comment]
How is this fixed? I am running the latest version of chia 1.1.4...do I have to upgrade to 1.1.4-1?  Where is that available?!

**Comment by keybreak** [comment]
@lastb0isct 
I don't know about rpm. i was speaking strictly about Arch Linux which is available in AUR as `chia-bin`
