### ISSUE TITLE
[BUG] harvester crashes: code = 1006 (connection closed abnormally [internal])

### ISSUE THREAD

**Issue by Dravenex** [Chia-Network/chia-blockchain#3367]
I'm farming with my Pi4 with about 110 TB attached to it via SATA-USB Adapters and some network shares. Sometimes farming stops and the following error occurs in the debug.log

> malloc(): corrupted top size
> 2021-05-01T23:28:15.656 farmer farmer_server              : INFO     Connection closed: 127.0.0.1, node id: ########
> 2021-05-01T23:28:15.657 farmer chia.farmer.farmer         : INFO     peer disconnected None
> 2021-05-01T23:28:15.667 daemon chia.daemon.server         : INFO     Websocket exception. Closing websocket with chia_harvester code = 1006 (connection closed abnormally [internal]), no reason Traceback (most recent call last):
>   File "/home/pi/chia-blockchain/venv/lib/python3.7/site-packages/websockets/protocol.py", line 827, in transfer_data
>     message = await self.read_message()
>   File "/home/pi/chia-blockchain/venv/lib/python3.7/site-packages/websockets/protocol.py", line 895, in read_message
>     frame = await self.read_data_frame(max_size=self.max_size)
>   File "/home/pi/chia-blockchain/venv/lib/python3.7/site-packages/websockets/protocol.py", line 971, in read_data_frame
>     frame = await self.read_frame(max_size)
>   File "/home/pi/chia-blockchain/venv/lib/python3.7/site-packages/websockets/protocol.py", line 1051, in read_frame
>     extensions=self.extensions,
>   File "/home/pi/chia-blockchain/venv/lib/python3.7/site-packages/websockets/framing.py", line 105, in read
>     data = await reader(2)
>   File "/usr/lib/python3.7/asyncio/streams.py", line 677, in readexactly
>     raise IncompleteReadError(incomplete, n)
> asyncio.streams.IncompleteReadError: 0 bytes read on a total of 2 expected bytes
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last):
>   File "/home/pi/chia-blockchain/chia/daemon/server.py", line 167, in safe_handle
>     async for message in websocket:
>   File "/home/pi/chia-blockchain/venv/lib/python3.7/site-packages/websockets/protocol.py", line 439, in __aiter__
>     yield await self.recv()
>   File "/home/pi/chia-blockchain/venv/lib/python3.7/site-packages/websockets/protocol.py", line 509, in recv
>     await self.ensure_open()
>   File "/home/pi/chia-blockchain/venv/lib/python3.7/site-packages/websockets/protocol.py", line 803, in ensure_open
>     raise self.connection_closed_exc()
> websockets.exceptions.ConnectionClosedError: code = 1006 (connection closed abnormally [internal]), no reason

After those errors I recognize that the harvester service crashed. Sometimes farming works again after "chia start farmer -r" but not everytime. Then only rebooting the Pi helps. 

Do you have any idea how I can troubleshoot this further? It's pretty annoying when the farmer crashed over night... :(

**Comment by Dravenex** [comment]
Happened again

`protocol: <asyncio.sslproto.SSLProtocol object at 0x7fa0a15780>
transport: <_SelectorSocketTransport fd=19 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/usr/lib/python3.7/asyncio/sslproto.py", line 526, in data_received
    ssldata, appdata = self._sslpipe.feed_ssldata(data)
  File "/usr/lib/python3.7/asyncio/sslproto.py", line 207, in feed_ssldata
    self._sslobj.unwrap()
  File "/usr/lib/python3.7/ssl.py", line 767, in unwrap
    return self._sslobj.shutdown()`

**Comment by erdincsk** [comment]
is there a solution to that?

**Comment by 24601** [comment]
I am also experiencing this on Mac OS X Big Sur 11.2.3, MacBook Pro (16-inch, 2019), built from source from main/master about 3 days ago. 


```
2021-05-14T20:22:22.978 farmer farmer_server              : INFO     -> new_signage_point_harvester to peer 127.0.0.1 d54bac130667f89631026fdbaae1c25ffa15137a9eeb049141b2ee58c7c895d0
2021-05-14T20:22:22.979 harvester harvester_server        : INFO     <- new_signage_point_harvester from peer d1e69d4f62fd2bb58a662adce75b98746e60b05e8b3a641df18c836788e196af 127.0.0.1
2021-05-14T20:22:23.029 full_node full_node_server        : INFO     <- new_signage_point_or_end_of_sub_slot from peer 8b968f1906a5dc28efff10879b10e972801dbbbd22d689c7244a84807763deef 5.95.187.3
2021-05-14T20:22:23.118 full_node full_node_server        : INFO     <- new_signage_point_or_end_of_sub_slot from peer 2d1528171f8e522579223fcd2b88929e75a80930002d8420b6fcfb33b1f62b9e 47.110.40.36
2021-05-14T20:22:23.120 full_node full_node_server        : INFO     <- new_signage_point_or_end_of_sub_slot from peer 01dcc92463623d283cb2915b830a3af6a2eec72eedb516e598ec082961beb219 yx.tplinkdns.com
2021-05-14T20:22:23.177 full_node full_node_server        : INFO     <- new_signage_point_or_end_of_sub_slot from peer 7f593845159075ee9428c3eeb819edd74ff8e6957d73697a38352a01fc2bb30d 14.203.210.131
2021-05-14T20:22:23.341 full_node full_node_server        : INFO     <- new_signage_point_or_end_of_sub_slot from peer e994356172deaa7da68e0011722ec7b4df6629142bbc1396d0abcb94def9efd1 188.32.196.250
2021-05-14T20:22:25.064 farmer farmer_server              : INFO     Connection closed: 127.0.0.1, node id: d54bac130667f89631026fdbaae1c25ffa15137a9eeb049141b2ee58c7c895d0
2021-05-14T20:22:25.067 farmer chia.farmer.farmer         : INFO     peer disconnected None
2021-05-14T20:22:25.084 daemon chia.daemon.server         : INFO     Websocket exception. Closing websocket with chia_harvester code = 1006 (connection closed abnormally [internal]), no reason Traceback (most recent call last):
  File "/Users/basitmustafa/chia-blockchain/venv/lib/python3.8/site-packages/websockets/protocol.py", line 827, in transfer_data
    message = await self.read_message()
  File "/Users/basitmustafa/chia-blockchain/venv/lib/python3.8/site-packages/websockets/protocol.py", line 895, in read_message
    frame = await self.read_data_frame(max_size=self.max_size)
  File "/Users/basitmustafa/chia-blockchain/venv/lib/python3.8/site-packages/websockets/protocol.py", line 971, in read_data_frame
    frame = await self.read_frame(max_size)
  File "/Users/basitmustafa/chia-blockchain/venv/lib/python3.8/site-packages/websockets/protocol.py", line 1047, in read_frame
    frame = await Frame.read(
  File "/Users/basitmustafa/chia-blockchain/venv/lib/python3.8/site-packages/websockets/framing.py", line 105, in read
    data = await reader(2)
  File "/Users/basitmustafa/opt/anaconda3/lib/python3.8/asyncio/streams.py", line 721, in readexactly
    raise exceptions.IncompleteReadError(incomplete, n)
asyncio.exceptions.IncompleteReadError: 0 bytes read on a total of 2 expected bytes

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/basitmustafa/chia-blockchain/chia/daemon/server.py", line 172, in safe_handle
    async for message in websocket:
  File "/Users/basitmustafa/chia-blockchain/venv/lib/python3.8/site-packages/websockets/protocol.py", line 439, in __aiter__
    yield await self.recv()
  File "/Users/basitmustafa/chia-blockchain/venv/lib/python3.8/site-packages/websockets/protocol.py", line 509, in recv
    await self.ensure_open()
  File "/Users/basitmustafa/chia-blockchain/venv/lib/python3.8/site-packages/websockets/protocol.py", line 803, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedError: code = 1006 (connection closed abnormally [internal]), no reason

2021-05-14T20:22:25.489 full_node full_node_server        : INFO     Cannot connect to host 59.7.5.226:8444 ssl:<ssl.SSLContext object at 0x7fd28279e240> [Connect call failed ('59.7.5.226', 8444)]
2021-05-14T20:22:25.491 full_node full_node_server        : INFO     <- new_compact_vdf from peer 7f593845159075ee9428c3eeb819edd74ff8e6957d73697a38352a01fc2bb30d 14.203.210.131
2021-05-14T20:22:27.367 full_node full_node_server        : INFO     <- new_unfinished_block from peer 8fdf745007cd38b1d250730bf2fc625c2606019cabcbe8ee964679f88c69dc9d 95.216.246.247
```

**Comment by alfs** [comment]
Also getting these crashes. Running the 1.1.5 offically distributed version on Windows.
Just before, I see a log message 
chia.harvester.harvester: ERROR   Error using prover object Destination buffer is too small
and the next line is referencing a plot.

Same for you?

chia start -r farmer 
restarts and it works a few more hours.

**Comment by blackflash** [comment]
same here version 1.1.5 -> all good and suddenly 

```
2021-05-20T17:13:44.143 daemon __main__                   : INFO     Websocket exception. Closing websocket with wallet_ui code = 1006 (connection closed abnormally [internal]), no reason Traceback (most recent call last):
  File "websockets\protocol.py", line 827, in transfer_data
  File "websockets\protocol.py", line 895, in read_message
  File "websockets\protocol.py", line 971, in read_data_frame
  File "websockets\protocol.py", line 1051, in read_frame
  File "websockets\framing.py", line 105, in read
  File "asyncio\streams.py", line 677, in readexactly
asyncio.streams.IncompleteReadError: 0 bytes read on a total of 2 expected bytes

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "chia\daemon\server.py", line 172, in safe_handle
  File "websockets\protocol.py", line 439, in __aiter__
  File "websockets\protocol.py", line 509, in recv
  File "websockets\protocol.py", line 803, in ensure_open
websockets.exceptions.ConnectionClosedError: code = 1006 (connection closed abnormally [internal]), no reason
```

I cant connect to wallet anymore

**Comment by jooooooooooe** [comment]
Is there a Solution in sight? 
I am farming on a MacMini late 2014 on Mojave and my log is quite filled with these Errors. Actually I am not aware of the consquences... Can I ignore these Errors?

**Comment by St3ffn** [comment]
I am experiencing the same problem on my Ubuntu 20.04.2 LTS Server. The server is only running a harvester. The farmer itself is a remote server.

The Problem happens after round about 12 hours. After it happens once, it happens again after 3-4 hours.

```
2021-06-14T19:06:07.248 daemon chia.daemon.server         : INFO     Websocket exception. Closing websocket with chia_harvester code = 1006 (connection closed abnormally [internal]), no reason Traceback (most recent call last):
  File "/home/marcus/chia-blockchain/venv/lib/python3.8/site-packages/websockets/protocol.py", line 827, in transfer_data
    message = await self.read_message()
  File "/home/marcus/chia-blockchain/venv/lib/python3.8/site-packages/websockets/protocol.py", line 895, in read_message
    frame = await self.read_data_frame(max_size=self.max_size)
  File "/home/marcus/chia-blockchain/venv/lib/python3.8/site-packages/websockets/protocol.py", line 971, in read_data_frame
    frame = await self.read_frame(max_size)
  File "/home/marcus/chia-blockchain/venv/lib/python3.8/site-packages/websockets/protocol.py", line 1047, in read_frame
    frame = await Frame.read(
  File "/home/marcus/chia-blockchain/venv/lib/python3.8/site-packages/websockets/framing.py", line 105, in read
    data = await reader(2)
  File "/usr/lib/python3.8/asyncio/streams.py", line 721, in readexactly
    raise exceptions.IncompleteReadError(incomplete, n)
asyncio.exceptions.IncompleteReadError: 0 bytes read on a total of 2 expected bytes

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/marcus/chia-blockchain/chia/daemon/server.py", line 172, in safe_handle
    async for message in websocket:
  File "/home/marcus/chia-blockchain/venv/lib/python3.8/site-packages/websockets/protocol.py", line 439, in __aiter__
    yield await self.recv()
  File "/home/marcus/chia-blockchain/venv/lib/python3.8/site-packages/websockets/protocol.py", line 509, in recv
    await self.ensure_open()
  File "/home/marcus/chia-blockchain/venv/lib/python3.8/site-packages/websockets/protocol.py", line 803, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedError: code = 1006 (connection closed abnormally [internal]), no reason
```

I can also provide additional information.

**Comment by St3ffn** [comment]
`/var/log/syslog` points out the following

```
... kernel: [14405.349722] chia_harvester[8295]: segfault at 0 ip 0000000000000000 sp 00007ffe6b8b2ba0 error 14 in python3.8[400000+23000]
... kernel: [14405.349729] Code: Bad RIP value.
```

**Comment by struxoje** [comment]
I'm getting the same with version 1.2.2

2021-07-15T00:09:04.240 daemon chia.daemon.server         : INFO     Websocket exception. Closing websocket with wallet_ui code = 1006 (connection closed abnormally [internal]), no reason Traceback (most recent call last):
  File "/srv/chia/chia-blockchain/venv/lib/python3.7/site-packages/websockets/protocol.py", line 827, in transfer_data
    message = await self.read_message()
  File "/srv/chia/chia-blockchain/venv/lib/python3.7/site-packages/websockets/protocol.py", line 895, in read_message
    frame = await self.read_data_frame(max_size=self.max_size)
  File "/srv/chia/chia-blockchain/venv/lib/python3.7/site-packages/websockets/protocol.py", line 971, in read_data_frame
    frame = await self.read_frame(max_size)
  File "/srv/chia/chia-blockchain/venv/lib/python3.7/site-packages/websockets/protocol.py", line 1051, in read_frame
    extensions=self.extensions,
  File "/srv/chia/chia-blockchain/venv/lib/python3.7/site-packages/websockets/framing.py", line 105, in read
    data = await reader(2)
  File "/usr/lib/python3.7/asyncio/streams.py", line 677, in readexactly
    raise IncompleteReadError(incomplete, n)
asyncio.streams.IncompleteReadError: 0 bytes read on a total of 2 expected bytes

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/srv/chia/chia-blockchain/chia/daemon/server.py", line 172, in safe_handle
    async for message in websocket:
  File "/srv/chia/chia-blockchain/venv/lib/python3.7/site-packages/websockets/protocol.py", line 439, in __aiter__
    yield await self.recv()
  File "/srv/chia/chia-blockchain/venv/lib/python3.7/site-packages/websockets/protocol.py", line 509, in recv
    await self.ensure_open()
  File "/srv/chia/chia-blockchain/venv/lib/python3.7/site-packages/websockets/protocol.py", line 803, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedError: code = 1006 (connection closed abnormally [internal]), no reason

**Comment by buglantiss** [comment]
same issue on 1.2.2, chia_harvester keeps crashing, no bad plots in the farm, ubuntu 20.04

**Comment by bnb70** [comment]
same issue on 1.2.2 ,ubuntu 18.04

2021-07-24T12:49:48.826 harvester chia.harvester.harvester: WARNING  Not farming any plots on this harvester. Check your configuration.
2021-07-24T12:49:50.220 daemon __main__                   : ERROR    Unexpected exception trying to send to websocket: code = 1006 (connection closed abnormally [internal]), no reason Traceback (most recent call last):
  File "websockets/protocol.py", line 827, in transfer_data
  File "websockets/protocol.py", line 895, in read_message
  File "websockets/protocol.py", line 971, in read_data_frame
  File "websockets/protocol.py", line 1047, in read_frame
  File "websockets/framing.py", line 105, in read
  File "asyncio/streams.py", line 721, in readexactly
asyncio.exceptions.IncompleteReadError: 0 bytes read on a total of 2 expected bytes

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "chia/daemon/server.py", line 187, in safe_handle
  File "websockets/protocol.py", line 555, in send
  File "websockets/protocol.py", line 803, in ensure_open
websockets.exceptions.ConnectionClosedError: code = 1006 (connection closed abnormally [internal]), no reason

**Comment by dev-quantum** [comment]
Same issue Windows 10, node/farmer/harvester all local:
2021-07-25T19:33:36.753 daemon __main__                   : INFO     Websocket exception. Closing websocket with chia_farmer code = 1006 (connection closed abnormally [internal]), no reason Traceback (most recent call last):
  File "asyncio\windows_events.py", line 457, in finish_recv
OSError: [WinError 64] The specified network name is no longer available

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "websockets\protocol.py", line 827, in transfer_data
  File "websockets\protocol.py", line 895, in read_message
  File "websockets\protocol.py", line 971, in read_data_frame
  File "websockets\protocol.py", line 1047, in read_frame
  File "websockets\framing.py", line 105, in read
  File "asyncio\streams.py", line 723, in readexactly
  File "asyncio\streams.py", line 517, in _wait_for_data
  File "asyncio\proactor_events.py", line 280, in _loop_reading
  File "asyncio\windows_events.py", line 812, in _poll
  File "asyncio\windows_events.py", line 461, in finish_recv
ConnectionResetError: [WinError 64] The specified network name is no longer available

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\a\chia-blockchain\chia-blockchain\venv\Lib\site-packages\chia\daemon\server.py", line 172, in safe_handle
  File "websockets\protocol.py", line 439, in __aiter__
  File "websockets\protocol.py", line 509, in recv
  File "websockets\protocol.py", line 803, in ensure_open
websockets.exceptions.ConnectionClosedError: code = 1006 (connection closed abnormally [internal]), no reason

**Comment by alex8900vbs** [comment]
Yes , harvester during plotting stop sometimes randomly , error 1006

**Comment by HououinKyouma01** [comment]
Same

```
2021-07-28T12:12:35.689 farmer farmer_server              : INFO     Connection closed: 127.0.0.1, node id: ***
2021-07-28T12:12:35.689 daemon __main__                   : INFO     Websocket exception. Closing websocket with chia_harvester code = 1006 (connection closed abnormally [internal]), no reason Traceback (most recent call last):
  File "websockets/protocol.py", line 827, in transfer_data
  File "websockets/protocol.py", line 895, in read_message
  File "websockets/protocol.py", line 971, in read_data_frame
  File "websockets/protocol.py", line 1047, in read_frame
  File "websockets/framing.py", line 105, in read
  File "asyncio/streams.py", line 721, in readexactly
asyncio.exceptions.IncompleteReadError: 0 bytes read on a total of 2 expected bytes
```

After this I'm unable to farm anything till I restart the client (I'm not getting any new challanges). 
It happens on both - windows and ubuntu. 
It's extremely annoying because I lost so much rewards because of this. It's impossible to check 24/7 if it's not crashed.

Please do something with this already. Add harvester restart after this error or something.

**Comment by iitzhaki** [comment]
It is application error:
this is the error from the event viewer :
Faulting application name: start_harvester.exe, version: 0.0.0.0, time stamp: 0x5ffec122
Faulting module name: chiapos.cp39-win_amd64.pyd, version: 0.0.0.0, time stamp: 0x60f84c16
Exception code: 0xc0000005
Fault offset: 0x0000000000001a1e
Faulting process id: 0x1780
Faulting application start time: 0x01d7852ac50a4f13
Faulting application path: C:\Users\User\AppData\Local\chia-blockchain\app-1.2.3\resources\app.asar.unpacked\daemon\start_harvester.exe
Faulting module path: C:\Users\User\AppData\Local\chia-blockchain\app-1.2.3\resources\app.asar.unpacked\daemon\chiapos.cp39-win_amd64.pyd
Report Id: c7cfda95-b861-44f6-a8a0-de921048c7a3
Faulting package full name: 
Faulting package-relative application ID: 


It happened to many people and to me too.
I tried almost everything including formatting the system and reinstall windows ,

No one in chia helps and did not fine any solution for that! 
i have 12400 plots!! respond tine is 2.5-4.5 sec

**Comment by djjaeger82** [comment]
Having this same problem on windows as well.  Maybe started when I began farming more and more forks, but seems simple enough to restart the harvester to fix it.  Its just not super obvious when it occurs, without 3rd party monitoring utilities (chiadog, farmr) I could easily see how people would miss out for days and days thinking they were farming away ok.  

PLEASE FIX THIS!

**Comment by djjaeger82** [comment]
Looks like there is a fix, just need the devs to review/approve:
https://github.com/Chia-Network/chia-blockchain/pull/6305

**Comment by rwarren** [comment]
For anyone landing here wondering why your plot counts drop to zero and this `code = 1006` error is in your logs... **this can happen when you have corrupted plots**. The harvester dies when it accesses them (when the plot passes the 1/512 filter).

To fix the problem, find all bad plots with `chia plots check` (this can take many hours, depending on farm size), then delete the bad plots that are identified. Replace as you like.

To revive harvesting while waiting to fix the real problem, just revive the harvester with `chia start harvester -r`, although the problem will inevitably happen again until you delete the bad plots. This is a lottery, depending on when the bad plot(s) passes the filter for the harvester to look at.
