### ISSUE TITLE
Fresh CentOS 8 install, GUI installer hangs on connecting to wallet

### ISSUE THREAD

**Issue by robkthx** [Chia-Network/chia-blockchain#3378]
Did a fresh install of CentOS 8, ran the GUI installer, and it hangs on connecting to wallet. This is what it logs, any idea how to fix?

```
2021-05-01T21:44:55.161 daemon __main__                   : ERROR    Unexpected exception trying to send to websocket: code = 1006 (connection closed abnormally [internal]), no reason Traceback (most recent call last):
  File "websockets/protocol.py", line 827, in transfer_data
  File "websockets/protocol.py", line 895, in read_message
  File "websockets/protocol.py", line 971, in read_data_frame
  File "websockets/protocol.py", line 1047, in read_frame
  File "websockets/framing.py", line 105, in read
  File "asyncio/streams.py", line 721, in readexactly
asyncio.exceptions.IncompleteReadError: 0 bytes read on a total of 2 expected bytes

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "chia/daemon/server.py", line 187, in safe_handle
  File "websockets/protocol.py", line 555, in send
  File "websockets/protocol.py", line 803, in ensure_open
websockets.exceptions.ConnectionClosedError: code = 1006 (connection closed abnormally [internal]), no reason
```

**Comment by stevenballs** [comment]
i have same problem. you can solve it? help me plase.

**Comment by robkthx** [comment]
Was able to install and get working by using the non-gui installation steps.
