### ISSUE TITLE
[BUG]full_node asyncio: ERROR Task exception was never retrieved

### ISSUE THREAD

**Issue by liya558** [Chia-Network/chia-blockchain#3403]
2021-05-02T14:13:50.661 full_node asyncio                 : ERROR    Task exception was never retrieved
future: <Task finished coro=<ChiaServer.incoming_api_task.<locals>.api_call() done, defined at /home/chia/chia-blockchain/chia/server/server.py:478> exception=CancelledError()>
concurrent.futures._base.CancelledError
2021-05-02T14:13:53.181 full_node chia.full_node.full_node: ERROR    Exception in create outbound connections:
2021-05-02T14:13:53.183 full_node chia.full_node.full_node: ERROR    Traceback: Traceback (most recent call last):
  File "/home/chia/chia-blockchain/chia/server/node_discovery.py", line 325, in _connect_to_peers
    await asyncio.sleep(sleep_interval)
  File "/usr/local/lib/python3.7/asyncio/tasks.py", line 595, in sleep
    return await future
concurrent.futures._base.CancelledError

2021-05-02T14:15:10.835 wallet wallet_server              : ERROR    Exception , exception Stack: Traceback (most recent call last):
  File "/home/chia/chia-blockchain/chia/server/server.py", line 354, in start_client
    url, autoclose=True, autoping=True, heartbeat=60, ssl=ssl_context, max_msg_size=50 * 1024 * 1024
  File "/home/chia/chia-blockchain/venv/lib/python3.7/site-packages/aiohttp/client.py", line 763, in _ws_connect
    proxy_headers=proxy_headers,

**Comment by liya558** [comment]
Unknown reason
