### ISSUE TITLE
[BUG] Imported plots dir after detache cause errors.

### ISSUE THREAD

**Issue by mariuszpoplawski** [Chia-Network/chia-blockchain#3410]
**Describe the bug**
If user add plot dir in GUI or by type chia.exe plots add -d locationHere, and pointed HDD will be detached or crash, in the next round of check for existing new plots wallet will crash and stop farm / import the rest of plots from the dir list. User is not able to remove crashed dir, wallet have to be terminated and config.yaml have to be modyfied manually.

**To Reproduce**
1. Add existing plot
2. Remove existing plot
3. Refresh plot list in gui or by type chia.exe plots show

**Expected behavior**
Wallet should import other existing plots and skip plot dir if it cant be reached, user should be only informed about that situation, crash cause stop of farming and do not import the rest plots, user have to turn off wallet and remove path from config.yaml

**Screenshots**
`C:\Users\u\Desktop>chia.exe.lnk plots remove -d \\Chia01-01\F\final_plots
Traceback (most recent call last):
  File "chia\cmds\chia.py", line 81, in <module>
  File "chia\cmds\chia.py", line 77, in main
  File "click\core.py", line 829, in __call__
  File "click\core.py", line 782, in main
  File "click\core.py", line 1259, in invoke
  File "click\core.py", line 1259, in invoke
  File "click\core.py", line 1066, in invoke
  File "click\core.py", line 610, in invoke
  File "click\decorators.py", line 21, in new_func
  File "chia\cmds\plots.py", line 189, in remove_cmd
  File "chia\plotting\plot_tools.py", line 130, in remove_plot_directory
  File "chia\plotting\plot_tools.py", line 130, in <listcomp>
  File "pathlib.py", line 1166, in resolve
  File "pathlib.py", line 205, in resolve
PermissionError: [WinError 21] Urządzenie nie jest gotowe: '\\\\Chia01-01\\F\\final_plots'
[2844] Failed to execute script chia
 
C:\Users\u\Desktop>chia.exe.lnk plots show
Directories where plots are being searched for:
Note that subdirectories must be added manually
Add with 'chia plots add -d [dir]' and remove with 'chia plots remove -d [dir]' Scan and check plots with 'chia plots check'
 
Traceback (most recent call last):
  File "chia\cmds\chia.py", line 81, in <module>
  File "chia\cmds\chia.py", line 77, in main
  File "click\core.py", line 829, in __call__
  File "click\core.py", line 782, in main
  File "click\core.py", line 1259, in invoke
  File "click\core.py", line 1259, in invoke
  File "click\core.py", line 1066, in invoke
  File "click\core.py", line 610, in invoke
  File "click\decorators.py", line 21, in new_func
  File "chia\cmds\plots.py", line 196, in show_cmd
  File "chia\cmds\plots.py", line 22, in show_plots
  File "chia\plotting\plot_tools.py", line 119, in get_plot_directories
  File "chia\plotting\plot_tools.py", line 119, in <listcomp>
  File "pathlib.py", line 1166, in resolve
  File "pathlib.py", line 205, in resolve
PermissionError: [WinError 21] Urządzenie nie jest gotowe: '\\\\Chia01-01\\F\\final_plots'
[4448] Failed to execute script chia
 `
**Desktop (please complete the following information):**

- OS: Windows
- OS Version/Flavor: 10

**Comment by Desrtom** [comment]
Im having this issue. Could you please explain how to terminate the wallet and what needs changed on the config.yami file?

**Comment by mariuszpoplawski** [comment]
> Im having this issue. Could you please explain how to terminate the wallet and what needs changed on the config.yami file?
> 
> iv removed the file via CLI, shut everything down, added path back and my plots are still not showing up.
