### ISSUE TITLE
[help] Cannot connect to host 67.188.143.14:8444 

### ISSUE THREAD

**Issue by markputrella74** [Chia-Network/chia-blockchain#3453]
Hi, my node is not synching (was working fine for the last several days) and I have got on the log file  only these lines now :

I have upgraded to that version : 1.1.3

2021-05-02T20:17:59.547 full_node full_node_server        : INFO     Cannot connect to host 67.188.143.14:8444 ssl:<ssl.SSLContext object at 0x000001E428729EB8> [Connect call failed ('67.188.143.14', 8444)]
2021-05-02T20:18:22.609 full_node full_node_server        : INFO     Cannot connect to host 67.188.143.14:8444 ssl:<ssl.SSLContext object at 0x000001E42A4FAC88> [Connect call failed ('67.188.143.14', 8444)]
2021-05-02T20:18:45.650 full_node full_node_server        : INFO     Cannot connect to host 67.188.143.14:8444 ssl:<ssl.SSLContext object at 0x000001E43262FE48> [Connect call failed ('67.188.143.14', 8444)]
2021-05-02T20:19:08.699 full_node full_node_server        : INFO     Cannot connect to host 67.188.143.14:8444 ssl:<ssl.SSLContext object at 0x000001E42BD572E8> [Connect call failed ('67.188.143.14', 8444)]
2021-05-02T20:19:31.756 full_node full_node_server        : INFO     Cannot connect to host 67.188.143.14:8444 ssl:<ssl.SSLContext object at 0x000001E428729C18> [Connect call failed ('67.188.143.14', 8444)]
2021-05-02T20:19:54.826 full_node full_node_server        : INFO     Cannot connect to host 67.188.143.14:8444 ssl:<ssl.SSLContext object at 0x000001E4287307B8> [Connect call failed ('67.188.143.14', 8444)]
2021-05-02T20:20:17.907 full_node full_node_server        : INFO     Cannot connect to host 67.188.143.14:8444 ssl:<ssl.SSLContext object at 0x000001E436932BA8> [Connect call failed ('67.188.143.14', 8444)]
2021-05-02T20:20:40.965 full_node full_node_server        : INFO     Cannot connect to host 67.188.143.14:8444 ssl:<ssl.SSLContext object at 0x000001E4378CD438> [Connect call failed ('67.188.143.14', 8444)]
2021-05-02T20:21:04.001 full_node full_node_server        : INFO     Cannot connect to host 67.188.143.14:8444 ssl:<ssl.SSLContext object at 0x000001E437840198> [Connect call failed ('67.188.143.14', 8444)]
2021-05-02T20:21:27.061 full_node full_node_server        : INFO     Cannot connect to host 67.188.143.14:8444 ssl:<ssl.SSLContext object at 0x000001E437261F28> [Connect call failed ('67.188.143.14', 8444)]
2021-05-02T20:21:50.116 full_node full_node_server        : INFO     Cannot connect to host 67.188.143.14:8444 ssl:<ssl.SSLContext object at 0x000001E43262F3C8> [Connect call failed ('67.188.143.14', 8444)]
2021-05-02T20:22:13.179 full_node full_node_server        : INFO     Cannot connect to host 67.188.143.14:8444 ssl:<ssl.SSLContext object at 0x000001E4331C8208> [Connect call failed ('67.188.143.14', 8444)]
2021-05-02T20:22:36.208 full_node full_node_server        : INFO     Cannot connect to host 67.188.143.14:8444 ssl:<ssl.SSLContext object at 0x000001E437840198> [Connect call failed ('67.188.143.14', 8444)]
2021-05-02T20:22:59.369 full_node full_node_server        : INFO     Cannot connect to host 67.188.143.14:8444 ssl:<ssl.SSLContext object at 0x000001E4378CD438> [Connect call failed ('67.188.143.14', 8444)]

**Comment by erwinpgo** [comment]
I have the same issue #3003  , this bug will stop your farming until you don't have connections anymore. I already experienced this on other Chia version as well. Unfortunately the only solution for now is to force stop your Chia then start again. I hope this will be seen by Chia team since this will impact the whole network if everyone will experience this on a daily/weekly basis.

This bug is not good for long term farming because you have to check everyday if your connection is not stucked at "Cannot connect to host"

2021-05-03T17:03:48.723 full_node full_node_server : INFO Cannot connect to host 202.65.95.233:8444 ssl:<ssl.SSLContext object at 0x000002A73D2A6828> [Connect call failed ('202.65.95.233', 8444)

**Comment by Thanasis82** [comment]
Same problem. As soon as I finish plotting I will try to restart chia. 
Thanks

**Comment by Thanasis82** [comment]
Well, it worked!

**Comment by LaHood0815** [comment]
same here. Have problems too with harvesters in my network. They cant get a connection the main machine.

**Comment by evereq** [comment]
tried also on a few Windows PCs with the latest soft installed (version 1.1.3) and same errors all over the log:

```
2021-05-04T21:39:47.919 full_node full_node_server        : INFO     Cannot connect to host 2.15.67.147:8444 ssl:<ssl.SSLContext object at 0x000001336ABD72E8> [Connect call failed ('2.15.67.147', 8444)]
2021-05-04T21:40:10.979 full_node full_node_server        : INFO     Cannot connect to host 49.51.41.33:8444 ssl:<ssl.SSLContext object at 0x000001336C003278> [Connect call failed ('49.51.41.33', 8444)]
2021-05-04T21:40:34.060 full_node full_node_server        : INFO     Cannot connect to host 120.8.85.179:8444 ssl:<ssl.SSLContext object at 0x000001336D425748> [Connect call failed ('120.8.85.179', 8444)]
```

Something really weird going on. 

I wonder, maybe it happens when it tries to connect back to the host which is not responding on port 8444 (e.g. all such nodes don't have port forwarded or just closed in the router, etc). In such a case, probably best to write something else into the log (e.g. that connection to some host established in one direction only).  However, in many cases after such errors I see also "disconnect" messages...

**Comment by LaHood0815** [comment]
i found a solution under win10. It has to do with network settings on the plot machine. after editing that it works fine.

**Comment by SKYBILLS** [comment]
https://www.yougetsignal.com/tools/open-ports
and port 8448 closed as well , why ? and should i open it for harvested and how to open it and solve it ? 
and the kib up/down always 0.0
Please advice as soon as possible thanks

![Screenshot (4)](https://user-images.githubusercontent.com/33307099/117161457-803c6800-adf4-11eb-87b9-7e0528646d31.png)
![Screenshot (5)](https://user-images.githubusercontent.com/33307099/117161628-a6620800-adf4-11eb-8fe7-713d58e7b7b0.png)

**Comment by mfrancekovic** [comment]
Having the same problem.

**Comment by vazmuten** [comment]
Absolutley the same arror every few hours. Had to script an automated process to auto-restart the farmer. I expect this error to be fixed ASAP. Anyone under Linux have it ot it's specific to MS Windows?

**Comment by varunawass** [comment]
I had this issue and instead of closing and opening the GUI which will stop all my ongoing plots, I ran the following commands which restarted the farmer only without disturbing the ongoing plotting. 

chia stop farmer-only
chia start all

**Comment by 42x42x42** [comment]
> I had this issue and instead of closing and opening the GUI which will stop all my ongoing plots, I ran the following commands which restarted the farmer only without disturbing the ongoing plotting.
> 
> chia stop farmer-only
> chia start all

seems it help, after this command I was able to manually connect to other peers. BUT I noticed that the first time ever I've seen Timelord in my connections. Does anybody knows is it ok that I hadn't seen it before?

**Comment by varunawass** [comment]
I'm also seeing a timelord after doing this. I guess chia start all command started a timelord as well in my PC

**Comment by oxygen** [comment]
I'm experiencing that SSL error as well.

Starting the wallet shows this IPv6 bind error:

```
 .\chia start -r wallet
chia_wallet: Traceback (most recent call last):
  File "chia\server\start_full_node.py", line 65, in <module>
  File "chia\server\start_full_node.py", line 60, in main
  File "chia\server\start_service.py", line 218, in run_service
  File "asyncio\runners.py", line 43, in run
  File "asyncio\base_events.py", line 587, in run_until_complete
  File "chia\server\start_service.py", line 212, in async_run_service
  File "chia\server\start_service.py", line 156, in run
  File "chia\server\start_service.py", line 132, in start
  File "chia\server\server.py", line 215, in start_server
  File "aiohttp\web_runner.py", line 128, in start
  File "asyncio\base_events.py", line 1389, in create_server
OSError: [Errno 10048] error while attempting to bind on address ('::', 8444, 0, 0): only one usage of each socket address (protocol/network address/port) is normally permitted
[15484] Failed to execute script start_full_node
Exception in thread Thread-1:
Traceback (most recent call last):
  File "aiosqlite\core.py", line 109, in run
  File "asyncio\base_events.py", line 736, in call_soon_threadsafe
  File "asyncio\base_events.py", line 479, in _check_closed
RuntimeError: Event loop is closed

During handling of the above exception, another exception occurred:

```
