### ISSUE TITLE
[BUG] - Plotting throws exception based on free memory, not available memory?

### ISSUE THREAD

**Issue by jwest75674** [Chia-Network/chia-blockchain#3487]
**Describe the bug**
Receiving "Caught plotting error: Not enough memory for sort in memory. Need to sort 2.249984GiB" I beleive incorrectly, as most system memory was available but holding write cached fluff from other plotting processes:
```
me@mycomputer:~$ free -h
              total        used        free      shared  buff/cache   available
Mem:          498Gi        19Gi       146Gi       1.1Gi       332Gi       474Gi
Swap:            0B          0B          0B                                    
```

**To Reproduce**

`chia plots create -t /mnt/flashdata -d /mnt/npdisk1/0 -u 16 -n 10000 -b 1000 -r 16`
(Also, why is 16 the minimum bucket size? Feature request: Single bucket for those of us with >400GB memory)

```
Computing table 2
--
Caught plotting error: Not enough memory for sort in memory. Need to sort 2.249984GiB
Traceback (most recent call last):
File "/usr/local/bin/chia", line 33, in <module>
sys.exit(load_entry_point('chia-blockchain', 'console_scripts', 'chia')())
File "/home/josh/chia-blockchain/chia/cmds/chia.py", line 77, in main
cli()  # pylint: disable=no-value-for-parameter
File "/usr/lib/python3/dist-packages/click/core.py", line 829, in __call__
return self.main(*args, **kwargs)
File "/usr/lib/python3/dist-packages/click/core.py", line 782, in main
rv = self.invoke(ctx)
File "/usr/lib/python3/dist-packages/click/core.py", line 1259, in invoke
return _process_result(sub_ctx.command.invoke(sub_ctx))
File "/usr/lib/python3/dist-packages/click/core.py", line 1259, in invoke
return _process_result(sub_ctx.command.invoke(sub_ctx))
File "/usr/lib/python3/dist-packages/click/core.py", line 1066, in invoke
return ctx.invoke(self.callback, **ctx.params)
File "/usr/lib/python3/dist-packages/click/core.py", line 610, in invoke
return callback(*args, **kwargs)
File "/usr/lib/python3/dist-packages/click/decorators.py", line 21, in new_func
return f(get_current_context(), *args, **kwargs)
File "/home/josh/chia-blockchain/chia/cmds/plots.py", line 135, in create_cmd
create_plots(Params(), ctx.obj["root_path"])
File "/home/josh/chia-blockchain/chia/plotting/create_plots.py", line 164, in create_plots
plotter.create_plot_disk(
RuntimeError: std::exception
```

**Comment by jwest75674** [comment]
I am an idiot, sorry!

**Comment by kelargo** [comment]
what did you do to recover?

**Comment by kelargo** [comment]
never mind.  I forgot to add new device into fstab.
