### ISSUE TITLE
Screen is always "Connecting to wallet"

### ISSUE THREAD

**Issue by lee20210503** [Chia-Network/chia-blockchain#3521]
**Describe the issue**
When I start the software, the screen always shows "Connecting to wallet". I have waited for more than 1 hour and the screen is is the same.

**To Reproduce**
I have tried re-install, reboot the PC, but the situation is still the same

**Expected behavior**
I expect to  see the control panel, but there is nothing shown

**Screenshots**
![image](https://user-images.githubusercontent.com/83591109/116880818-0752da00-ac55-11eb-8b40-0315488db7bf.png)
![螢幕擷取畫面 2021-05-03 211742](https://user-images.githubusercontent.com/83591109/116880835-0e79e800-ac55-11eb-8491-a2e89b6bcc5f.jpg)

**Additional context**

**Comment by Weihrich** [comment]
I have the same problem since last night.

**Comment by PaulDobsonUK** [comment]
I'm getting this now as well... Issue with the server?

**Comment by Gomes1990** [comment]
i have the same problem

**Comment by Ant-Miner** [comment]
Same Problem here....

**Comment by alexs20** [comment]
Same problem here since 1.1.3 released
Trying to run from CLI gives 
`Daemon not started yet
Starting daemon
Traceback (most recent call last):
  File "chia\cmds\chia.py", line 81, in <module>
  File "chia\cmds\chia.py", line 77, in main
  File "click\core.py", line 829, in __call__
  File "click\core.py", line 782, in main
  File "click\core.py", line 1259, in invoke
  File "click\core.py", line 1066, in invoke
  File "click\core.py", line 610, in invoke
  File "click\decorators.py", line 21, in new_func
  File "chia\cmds\chia.py", line 60, in run_daemon_cmd
  File "asyncio\base_events.py", line 587, in run_until_complete
  File "chia\daemon\server.py", line 964, in async_run_daemon
  File "chia\daemon\server.py", line 150, in start
  File "websockets\server.py", line 965, in __await_impl__
  File "asyncio\base_events.py", line 1389, in create_server
OSError: [Errno 10013] error while attempting to bind on address ('127.0.0.1', 55400): an attempt was made to access a socket in a way forbidden by its access permissions
[4172] Failed to execute script chia
Daemon not started yet
Failed to create the chia daemon`

The Linux version works so far but Ubuntu installation in 1.1.3 was also broken, had manually edit the installation script to finishe the upgrade process...

The 1.1.3 version is very buggy

**Comment by Ant-Miner** [comment]
I have the Problem since 1.1.3 and still got it on 1.1.4 ... Can anyone help?
