### ISSUE TITLE
[BUG] Start Chia - SystemRestart - PLOTTIG SystemRESTART

### ISSUE THREAD

**Issue by BannanaDJoe** [Chia-Network/chia-blockchain#3536]
**looks like there is some worg with the drivers. at the moment i start the the chia node my system reboots after i Plotttet 4 Plots. any idea ? , newst release installed after that only waiting war Wallet Sync and not more. really bad how that taste.... **

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

- OS: [e.g. Linux]
- OS Version/Flavor: [e.g. CentOS 7.2]
- CPU: [e.g. Intel Xeon 8175M]

**Additional context**

**Comment by BILLFANLL** [comment]
upgrade to latest version, it's bug already fixed. xch1ctlr23cxqsky2k452kjm438z6msn9zvx5fu5zanthhpsytcqx03q3unq60

**Comment by BannanaDJoe** [comment]
on the latest version the wallt will just sync any suggestion ?

**Comment by BannanaDJoe** [comment]
2021-05-03T11:20:38.802 full_node full_node_server        : ERROR    Exception:  <class 'concurrent.futures._base.CancelledError'>, closing connection None. Traceback (most recent call last):
  File "chia\server\server.py", line 521, in api_call
  File "asyncio\tasks.py", line 435, in wait_for
concurrent.futures._base.CancelledError

2021-05-03T11:25:38.489 full_node full_node_server        : ERROR    Exception , exception Stack: Traceback (most recent call last):
  File "chia\server\server.py", line 354, in start_client
  File "aiohttp\client.py", line 763, in _ws_connect
  File "aiohttp\client.py", line 521, in _request
  File "aiohttp\connector.py", line 535, in connect
  File "aiohttp\connector.py", line 892, in _create_connection
  File "aiohttp\connector.py", line 1032, in _create_direct_connection
  File "aiohttp\connector.py", line 969, in _wrap_create_connection
  File "asyncio\base_events.py", line 949, in create_connection
  File "asyncio\selector_events.py", line 473, in sock_connect
concurrent.futures._base.CancelledError

These are the last logs since them i cant use the wallt anymore on my pc and i dont want to delete the local chain so i wait again some days

**Comment by BILLFANLL** [comment]
> on the latest version the wallt will just sync any suggestion ?
> 
> 

I am using node-or.chia.net port 8444. It's working good
