### ISSUE TITLE
[BUG]why?help

### ISSUE THREAD

**Issue by uwerui** [Chia-Network/chia-blockchain#3541]
Starting phase 1/4: Forward Propagation into tmp files... Tue May  4 00:36:14 2021
Computing table 1
F1 complete, time: 343.91 seconds. CPU (174.76%) Tue May  4 00:41:58 2021
Computing table 2
Caught plotting error: bad allocation
[15048] Failed to execute script chia
Traceback (most recent call last):
  File "chia\cmds\chia.py", line 81, in <module>
  File "chia\cmds\chia.py", line 77, in main
  File "click\core.py", line 829, in __call__
  File "click\core.py", line 782, in main
  File "click\core.py", line 1259, in invoke
  File "click\core.py", line 1259, in invoke
  File "click\core.py", line 1066, in invoke
  File "click\core.py", line 610, in invoke
  File "click\decorators.py", line 21, in new_func
  File "chia\cmds\plots.py", line 135, in create_cmd
  File "chia\plotting\create_plots.py", line 176, in create_plots
RuntimeError: bad allocation

**Comment by vladborovtsov** [comment]
not enough RAM maybe? I've got the same errors when tried buckets=32.
