### ISSUE TITLE
[BUG]Can't Ploting

### ISSUE THREAD

**Issue by JRay9487** [Chia-Network/chia-blockchain#3542]
**Describe the bug**
Can't ploting after restart pc
*
*To Reproduce**

**Expected behavior**
Turn off PC,restart Chia still cant ploting.

**Screenshots**
2021-05-04T00:41:21.604  chia.plotting.create_plots       : [32mINFO    [0m Creating 1 plots of size 32, pool public key:  8e19c3eadaace1db3d9e388fa4f8dd7cfd24094bf633c49336de801811ca3cbcf93cd3b5e77764719461d3048f02c55d farmer public key: 982118f250f991482e83d10960c65a83c597b9f4b454481d6bc187de739342d2778be9b3936ab1c05e4ca129b0725fd3[0m
2021-05-04T00:41:21.612  chia.plotting.create_plots       : [32mINFO    [0m Memo: 8e19c3eadaace1db3d9e388fa4f8dd7cfd24094bf633c49336de801811ca3cbcf93cd3b5e77764719461d3048f02c55d982118f250f991482e83d10960c65a83c597b9f4b454481d6bc187de739342d2778be9b3936ab1c05e4ca129b0725fd30a1b3c35d7f74d62d7170ce416415bfc73add824ea757b3553aa2e7742671394[0m
2021-05-04T00:41:21.612  chia.plotting.create_plots       : [32mINFO    [0m Starting plot 1/1[0m

Starting plotting progress into temporary dirs: /home/jray/chia ssd and /home/jray/chia ssd
ID: 04ffa1a240e9d85e9e34a1e185df79a5535259e011db6819f83c2268de635322
Plot size is: 32
Buffer size is: 3390MiB
Using 128 buckets
Using 2 threads of stripe size 65536
Caught plotting error: filesystem error: cannot remove: Read-only file system [/media/jray/HDD/chia hdd/plot-k32-2021-05-04-00-41-04ffa1a240e9d85e9e34a1e185df79a5535259e011db6819f83c2268de635322.plot]
Traceback (most recent call last):
  File "/home/jray/chia-blockchain/venv/bin/chia", line 33, in <module>
    sys.exit(load_entry_point('chia-blockchain', 'console_scripts', 'chia')())
  File "/home/jray/chia-blockchain/chia/cmds/chia.py", line 77, in main
    cli()  # pylint: disable=no-value-for-parameter
  File "/home/jray/chia-blockchain/venv/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/jray/chia-blockchain/venv/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/jray/chia-blockchain/venv/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/jray/chia-blockchain/venv/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/jray/chia-blockchain/venv/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/jray/chia-blockchain/venv/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/jray/chia-blockchain/venv/lib/python3.8/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/jray/chia-blockchain/chia/cmds/plots.py", line 135, in create_cmd
    create_plots(Params(), ctx.obj["root_path"])
  File "/home/jray/chia-blockchain/chia/plotting/create_plots.py", line 164, in create_plots
    plotter.create_plot_disk(
RuntimeError: std::exception

**Desktop (please complete the following information):**

- OS: linux
- OS Version/Flavor: Ubuntu 20.04.2 LTS
- CPU: Intel® Core™ i5-3350P CPU @ 3.10GHz × 4

**Comment by lrnvrryth** [comment]
It says read-only file system, maybe make it writable? 

Also, maybe its missing a final dir arg when being called? 

"To plot successfully requires drives formatted to support large files; e.g. NTFS, APFS, exFAT, ext4, etc. Do not use drives with FAT formatting (FAT12, FAT16, or FAT32)" 

"...if you do get a failed plot, delete all *.tmp files before starting a new plot."

https://github.com/Chia-Network/chia-blockchain/wiki/INSTALL
