### ISSUE TITLE
Failed to create the chia daemon

### ISSUE THREAD

**Issue by JcobMajkowsky** [Chia-Network/chia-blockchain#3555]
I'm having a problem with starting chia daemon. Gui doesn't work, but when I start it with command line after typing **chia start farmer** I get these errors
Daemon not started yet
Starting daemon
Traceback (most recent call last):
  File "/home/fejker/crypto/chia-blockchain/venv/bin/chia", line 33, in <module>
    sys.exit(load_entry_point('chia-blockchain', 'console_scripts', 'chia')())
  File "/home/fejker/crypto/chia-blockchain/chia/cmds/chia.py", line 77, in main
    cli()  # pylint: disable=no-value-for-parameter
  File "/home/fejker/crypto/chia-blockchain/venv/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/fejker/crypto/chia-blockchain/venv/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/fejker/crypto/chia-blockchain/venv/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/fejker/crypto/chia-blockchain/venv/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/fejker/crypto/chia-blockchain/venv/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/fejker/crypto/chia-blockchain/venv/lib/python3.8/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/fejker/crypto/chia-blockchain/chia/cmds/chia.py", line 60, in run_daemon_cmd
    asyncio.get_event_loop().run_until_complete(async_run_daemon(ctx.obj["root_path"]))
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/fejker/crypto/chia-blockchain/chia/daemon/server.py", line 964, in async_run_daemon
    await ws_server.start()
  File "/home/fejker/crypto/chia-blockchain/chia/daemon/server.py", line 143, in start
    self.websocket_server = await serve(
  File "/home/fejker/crypto/chia-blockchain/venv/lib/python3.8/site-packages/websockets/server.py", line 965, in __await_impl__
    server = await self._create_server()
  File "/usr/lib/python3.8/asyncio/base_events.py", line 1463, in create_server
    raise OSError(err.errno, 'error while attempting '
OSError: [Errno 99] error while attempting to bind on address ('::1', 55400, 0, 0): cannot assign requested address
Daemon not started yet
Failed to create the chia daemon

Anyone got a solution? I checked if port 55400 is taken, but it's not

**Comment by jiacme** [comment]
I have the same problem, how can I solve it

**Comment by chrzimmer** [comment]
looks like i have the same problem ... i appreciate any help ... is this something with derectory structure ? or am I missinfg something in a parh variable ? 

`mars:/opt/chia-blockchain/venv/bin# ./chia start farmer
Daemon not started yet
Starting daemon
chia_harvester: chia_harvester failed to start. Error: start failed
chia_farmer: chia_farmer failed to start. Error: start failed
chia_full_node: chia_full_node failed to start. Error: start failed
chia_wallet: chia_wallet failed to start. Error: start failed`

the log says
`2021-05-06T18:07:54.683 daemon chia.daemon.server         : ERROR    problem starting chia_harvester
Traceback (most recent call last):
  File "/opt/chia-blockchain/chia/daemon/server.py", line 627, in start_service
    process, pid_path = launch_service(self.root_path, exe_command)
  File "/opt/chia-blockchain/chia/daemon/server.py", line 784, in launch_service
    process = subprocess.Popen(
  File "/usr/lib/python3.8/subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.8/subprocess.py", line 1702, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'chia_harvester'
2021-05-06T18:07:54.690 daemon chia.daemon.server         : ERROR    problem starting chia_farmer
Traceback (most recent call last):
  File "/opt/chia-blockchain/chia/daemon/server.py", line 627, in start_service
    process, pid_path = launch_service(self.root_path, exe_command)
  File "/opt/chia-blockchain/chia/daemon/server.py", line 784, in launch_service
    process = subprocess.Popen(
  File "/usr/lib/python3.8/subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.8/subprocess.py", line 1702, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'chia_farmer'
2021-05-06T18:07:54.695 daemon chia.daemon.server         : ERROR    problem starting chia_full_node
Traceback (most recent call last):
  File "/opt/chia-blockchain/chia/daemon/server.py", line 627, in start_service
    process, pid_path = launch_service(self.root_path, exe_command)
  File "/opt/chia-blockchain/chia/daemon/server.py", line 784, in launch_service
    process = subprocess.Popen(
  File "/usr/lib/python3.8/subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.8/subprocess.py", line 1702, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'chia_full_node'
2021-05-06T18:07:54.700 daemon chia.daemon.server         : ERROR    problem starting chia_wallet
Traceback (most recent call last):
  File "/opt/chia-blockchain/chia/daemon/server.py", line 627, in start_service
    process, pid_path = launch_service(self.root_path, exe_command)
  File "/opt/chia-blockchain/chia/daemon/server.py", line 784, in launch_service
    process = subprocess.Popen(
  File "/usr/lib/python3.8/subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.8/subprocess.py", line 1702, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'chia_wallet'`

**Comment by jmakov** [comment]
> looks like i have the same problem ... i appreciate any help ... is this something with derectory structure ? or am I missinfg something in a parh variable ?
> 
> mars:/opt/chia-blockchain/venv/bin# ./chia start farmer
> Daemon not started yet
> Starting daemon
> chia_harvester: chia_harvester failed to start. Error: start failed
> chia_farmer: chia_farmer failed to start. Error: start failed
> chia_full_node: chia_full_node failed to start. Error: start failed
> chia_wallet: chia_wallet failed to start. Error: start failed
> 
> the log says
> 2021-05-06T18:07:54.683 daemon chia.daemon.server : ERROR problem starting chia_harvester
> Traceback (most recent call last):
> File "/opt/chia-blockchain/chia/daemon/server.py", line 627, in start_service
> process, pid_path = launch_service(self.root_path, exe_command)
> File "/opt/chia-blockchain/chia/daemon/server.py", line 784, in launch_service
> process = subprocess.Popen(
> File "/usr/lib/python3.8/subprocess.py", line 854, in **init**
> self._execute_child(args, executable, preexec_fn, close_fds,
> File "/usr/lib/python3.8/subprocess.py", line 1702, in _execute_child
> raise child_exception_type(errno_num, err_msg, err_filename)
> FileNotFoundError: [Errno 2] No such file or directory: 'chia_harvester'
> 2021-05-06T18:07:54.690 daemon chia.daemon.server : ERROR problem starting chia_farmer
> Traceback (most recent call last):
> File "/opt/chia-blockchain/chia/daemon/server.py", line 627, in start_service
> process, pid_path = launch_service(self.root_path, exe_command)
> File "/opt/chia-blockchain/chia/daemon/server.py", line 784, in launch_service
> process = subprocess.Popen(
> File "/usr/lib/python3.8/subprocess.py", line 854, in **init**
> self._execute_child(args, executable, preexec_fn, close_fds,
> File "/usr/lib/python3.8/subprocess.py", line 1702, in _execute_child
> raise child_exception_type(errno_num, err_msg, err_filename)
> FileNotFoundError: [Errno 2] No such file or directory: 'chia_farmer'
> 2021-05-06T18:07:54.695 daemon chia.daemon.server : ERROR problem starting chia_full_node
> Traceback (most recent call last):
> File "/opt/chia-blockchain/chia/daemon/server.py", line 627, in start_service
> process, pid_path = launch_service(self.root_path, exe_command)
> File "/opt/chia-blockchain/chia/daemon/server.py", line 784, in launch_service
> process = subprocess.Popen(
> File "/usr/lib/python3.8/subprocess.py", line 854, in **init**
> self._execute_child(args, executable, preexec_fn, close_fds,
> File "/usr/lib/python3.8/subprocess.py", line 1702, in _execute_child
> raise child_exception_type(errno_num, err_msg, err_filename)
> FileNotFoundError: [Errno 2] No such file or directory: 'chia_full_node'
> 2021-05-06T18:07:54.700 daemon chia.daemon.server : ERROR problem starting chia_wallet
> Traceback (most recent call last):
> File "/opt/chia-blockchain/chia/daemon/server.py", line 627, in start_service
> process, pid_path = launch_service(self.root_path, exe_command)
> File "/opt/chia-blockchain/chia/daemon/server.py", line 784, in launch_service
> process = subprocess.Popen(
> File "/usr/lib/python3.8/subprocess.py", line 854, in **init**
> self._execute_child(args, executable, preexec_fn, close_fds,
> File "/usr/lib/python3.8/subprocess.py", line 1702, in _execute_child
> raise child_exception_type(errno_num, err_msg, err_filename)
> FileNotFoundError: [Errno 2] No such file or directory: 'chia_wallet'

Same problem here after computer restart.
