### ISSUE TITLE
[BUG] Wasn't able to add transaction with id .....

### ISSUE THREAD

**Issue by MrColoo** [Chia-Network/chia-blockchain#3561]
I'm farming but if I check the log there are many errors. What does the _"Wasn't able to add transaction with id"_ error mean? Are they a problem?

2021-05-03T20:23:29.804 wallet chia.wallet.wallet_blockchain: ERROR    Error during db transaction: 
2021-05-03T20:25:37.995 full_node full_node_server        : ERROR    Exception:  <class 'concurrent.futures._base.CancelledError'>, closing connection None. Traceback (most recent call last):
  File "chia\server\server.py", line 531, in api_call
  File "asyncio\tasks.py", line 435, in wait_for
concurrent.futures._base.CancelledError

2021-05-03T20:38:41.691 full_node chia.full_node.full_node: WARNING  Wasn't able to add transaction with id _**censored**_, status 3 error: Err.UNKNOWN_UNSPENT
2021-05-03T20:38:41.707 full_node chia.full_node.full_node: WARNING  Wasn't able to add transaction with id  _**censored**_, status 3 error: Err.UNKNOWN_UNSPENT

updated a hour ago to 1.1.3

**Comment by louisphilippe2** [comment]
I have the SAME BUG

**Comment by only-cliches** [comment]
+1

**Comment by gs517** [comment]
+2
status 3 error: Err.DOUBLE_SPEND
status 3 error: Err.MEMPOOL_NOT_INITIALIZED

**Comment by mariano54** [comment]
There is an issue with pending transactions being stuck. Please follow the following steps:

1. Shut down your wallet and node
2. Delete your wallet db files: located at `~/.chia/mainnet/wallet/db`. This will require syncing up your wallet, but not your node. And then you can resubmit the transaction.
3. Make sure you have upgraded to the latest version
4. Start the application and wait for the wallet to sync up

**Comment by gs517** [comment]
I got 20 such errors in 10 minutes:

`2021-05-04T09:58:51.566 full_node chia.full_node.full_node: WARNING  Wasn't able to add transaction with id ....... status 3 error: Err.DOUBLE_SPEND`

**Comment by adrdadr** [comment]
Same issue https://github.com/Chia-Network/chia-blockchain/discussions/3632
Wallet deleted and chia 1.1.3 restarted since 4 hours

Nothing change in logs

2021-05-04T08:57:05.422 full_node chia.full_node.full_node: WARNING  Wasn't able to add transaction with id 3263245f9ad4d838112d62a4ac9cbe665c2f7e0c9704925689541bb547b82236, status 3 error: Err.DOUBLE_SPEND
2021-05-04T08:57:05.434 full_node chia.full_node.full_node: WARNING  Wasn't able to add transaction with id 76e05e72225db89cddc7da671ac9a0bd7f24c2387778c9b63cb5b2b3e06d876d, status 3 error: Err.DOUBLE_SPEND
2021-05-04T09:44:28.965 full_node full_node_server        : ERROR    Exception: Failed to fetch block 228548 from {'host': '119.133.253.140', 'port': 8444}, timed out, {'host': '119.133.253.140', 'port': 8444}. Traceback (most recent call last):
  File "chia\server\server.py", line 521, in wrapped_coroutine
  File "chia\full_node\full_node_api.py", line 104, in new_peak
  File "chia\full_node\full_node.py", line 361, in new_peak
  File "chia\full_node\full_node.py", line 310, in short_sync_backtrack
  File "chia\full_node\full_node.py", line 295, in short_sync_backtrack
ValueError: Failed to fetch block 228548 from {'host': '119.133.253.140', 'port': 8444}, timed out

**Comment by only-cliches** [comment]
Resyncing my wallet did the trick so far!  Running Ubuntu 20.04 LTS.

**Comment by DrHou83** [comment]
> There is an issue with pending transactions being stuck. Please follow the following steps:
> 
> 1. Shut down your wallet and node
> 2. Delete your wallet db files: located at `~/.chia/mainnet/wallet/db`. This will require syncing up your wallet, but not your node. And then you can resubmit the transaction.
> 3. Make sure you have upgraded to the latest version
> 4. Start the application and wait for the wallet to sync up

Hey there I did this and now my XCH has disappeared from my wallet. Will this return once my wallet is synced ;/ ?

**Comment by parko86** [comment]
> > There is an issue with pending transactions being stuck. Please follow the following steps:
> > 
> > 1. Shut down your wallet and node
> > 2. Delete your wallet db files: located at `~/.chia/mainnet/wallet/db`. This will require syncing up your wallet, but not your node. And then you can resubmit the transaction.
> > 3. Make sure you have upgraded to the latest version
> > 4. Start the application and wait for the wallet to sync up
> 
> Hey there I did this and now my XCH has disappeared from my wallet. Will this return once my wallet is synced ;/ ?

It better be.....

**Comment by DrHou83** [comment]
> > > There is an issue with pending transactions being stuck. Please follow the following steps:
> > > 
> > > 1. Shut down your wallet and node
> > > 2. Delete your wallet db files: located at `~/.chia/mainnet/wallet/db`. This will require syncing up your wallet, but not your node. And then you can resubmit the transaction.
> > > 3. Make sure you have upgraded to the latest version
> > > 4. Start the application and wait for the wallet to sync up
> > 
> > 
> > Hey there I did this and now my XCH has disappeared from my wallet. Will this return once my wallet is synced ;/ ?
> 
> It better be.....

tell me about it..its syncing now but VERY slowly!!

**Comment by danktankk** [comment]
it is taking ages to resync the wallet.  I hope this doesnt prevent possible tokens from being awarded!

**Comment by a-shvedov** [comment]
I'm not sure if the program is working correctly. Warnings appear every day:

`2021-05-06T05:10:50.251 full_node chia.full_node.full_node: WARNING  Wasn't able to add transaction with id 864cfd743d8411eb4a613d9bc7dc8ca8e2e89f827d30e39c832e86de0243b005, status 3 error: Err.DOUBLE_SPEND
2021-05-06T05:10:50.259 full_node chia.full_node.full_node: WARNING  Wasn't able to add transaction with id a9ac28391ca80e10a9f9913c526095e863a3b50796e822bf77e150b354bf8d34, status 3 error: Err.DOUBLE_SPEND
2021-05-06T05:10:50.268 full_node chia.full_node.full_node: WARNING  Wasn't able to add transaction with id 68ac27d050c2b393b4eef695a6dc1a28e67564bff532e2b986eee43ed42d0a7b, status 3 error: Err.DOUBLE_SPEND
2021-05-06T05:10:50.275 full_node chia.full_node.full_node: WARNING  Wasn't able to add transaction with id 7d618c46f9dda5c499fda173ee9f417f6154748df26385fce0cc4e76576e5c57, status 3 error: Err.DOUBLE_SPEND
2021-05-06T05:10:50.282 full_node chia.full_node.full_node: WARNING  Wasn't able to add transaction with id 8b6340fe77f7e39538172a6ecf5aac7350328bf6bac77da896f0063125c91482, status 3 error: Err.DOUBLE_SPEND
2021-05-06T05:10:50.290 full_node chia.full_node.full_node: WARNING  Wasn't able to add transaction with id 8519070374c4cfaf4ef8a475e1c9cd996f3e671a39d0cf3c3730a8d4f5eed05b, status 3 error: Err.DOUBLE_SPEND
2021-05-06T05:10:50.296 full_node chia.full_node.full_node: WARNING  Wasn't able to add transaction with id eda11806f8af4e5e3080606af7d72db41fc478871962e706238569b504e97f6d, status 3 error: Err.DOUBLE_SPEND
2021-05-06T05:10:50.303 full_node chia.full_node.full_node: WARNING  Wasn't able to add transaction with id 46e94fde4b84b6ddaf00a792ce1efea5a92f5e0697a8300ba6a5f44cebae36fc, status 3 error: Err.DOUBLE_SPEND
2021-05-06T05:10:50.310 full_node chia.full_node.full_node: WARNING  Wasn't able to add transaction with id 8ccfa37d67156607c37eb44dd55c91ab5c775fcaa234e2addbfb687da9d7f7f8, status 3 error: Err.DOUBLE_SPEND
2021-05-06T05:10:50.316 full_node chia.full_node.full_node: WARNING  Wasn't able to add transaction with id d5fd1c2af2f978af8c0c273bb1c760e32ee5e81b77e294790c32a8c86c0de45b, status 3 error: Err.DOUBLE_SPEND
2021-05-06T05:10:50.323 full_node chia.full_node.full_node: WARNING  Wasn't able to add transaction with id 395f9f5faf9f7093f81e33638d299ccb52b5222f0f257647f64a40012c0b1f71, status 3 error: Err.DOUBLE_SPEND
2021-05-06T07:21:22.112 full_node chia.full_node.full_node: WARNING  Wasn't able to add transaction with id 864cfd743d8411eb4a613d9bc7dc8ca8e2e89f827d30e39c832e86de0243b005, status 3 error: Err.DOUBLE_SPEND
2021-05-06T07:21:22.130 full_node chia.full_node.full_node: WARNING  Wasn't able to add transaction with id a9ac28391ca80e10a9f9913c526095e863a3b50796e822bf77e150b354bf8d34, status 3 error: Err.DOUBLE_SPEND
2021-05-06T07:21:22.140 full_node chia.full_node.full_node: WARNING  Wasn't able to add transaction with id 68ac27d050c2b393b4eef695a6dc1a28e67564bff532e2b986eee43ed42d0a7b, status 3 error: Err.DOUBLE_SPEND
2021-05-06T07:21:22.149 full_node chia.full_node.full_node: WARNING  Wasn't able to add transaction with id 7d618c46f9dda5c499fda173ee9f417f6154748df26385fce0cc4e76576e5c57, status 3 error: Err.DOUBLE_SPEND
2021-05-06T07:21:22.157 full_node chia.full_node.full_node: WARNING  Wasn't able to add transaction with id 8b6340fe77f7e39538172a6ecf5aac7350328bf6bac77da896f0063125c91482, status 3 error: Err.DOUBLE_SPEND
2021-05-06T07:21:22.165 full_node chia.full_node.full_node: WARNING  Wasn't able to add transaction with id 8519070374c4cfaf4ef8a475e1c9cd996f3e671a39d0cf3c3730a8d4f5eed05b, status 3 error: Err.DOUBLE_SPEND
2021-05-06T07:21:22.172 full_node chia.full_node.full_node: WARNING  Wasn't able to add transaction with id eda11806f8af4e5e3080606af7d72db41fc478871962e706238569b504e97f6d, status 3 error: Err.DOUBLE_SPEND
2021-05-06T07:21:22.180 full_node chia.full_node.full_node: WARNING  Wasn't able to add transaction with id 46e94fde4b84b6ddaf00a792ce1efea5a92f5e0697a8300ba6a5f44cebae36fc, status 3 error: Err.DOUBLE_SPEND
2021-05-06T07:21:22.187 full_node chia.full_node.full_node: WARNING  Wasn't able to add transaction with id 8ccfa37d67156607c37eb44dd55c91ab5c775fcaa234e2addbfb687da9d7f7f8, status 3 error: Err.DOUBLE_SPEND
2021-05-06T07:21:22.194 full_node chia.full_node.full_node: WARNING  Wasn't able to add transaction with id d5fd1c2af2f978af8c0c273bb1c760e32ee5e81b77e294790c32a8c86c0de45b, status 3 error: Err.DOUBLE_SPEND
2021-05-06T07:21:22.202 full_node chia.full_node.full_node: WARNING  Wasn't able to add transaction with id 395f9f5faf9f7093f81e33638d299ccb52b5222f0f257647f64a40012c0b1f71, status 3 error: Err.DOUBLE_SPEND
2021-05-06T08:25:28.969 full_node full_node_server        : ERROR    Exception: Failed to fetch block 238696 from {'host': '83.8.254.1', 'port': 8444}, timed out, {'host': '83.8.254.1', 'port': 8444}. Traceback (most recent call last):
  File "chia\server\server.py", line 511, in wrapped_coroutine
  File "chia\full_node\full_node_api.py", line 100, in new_peak
  File "chia\full_node\full_node.py", line 358, in new_peak
  File "chia\full_node\full_node.py", line 307, in short_sync_backtrack
  File "chia\full_node\full_node.py", line 292, in short_sync_backtrack
ValueError: Failed to fetch block 238696 from {'host': '83.8.254.1', 'port': 8444}, timed out`

**Comment by asd0834** [comment]
me too

**Comment by dutchmulti** [comment]
i will try:

 There is an issue with pending transactions being stuck. Please follow the following steps:

Shut down your wallet and node
Delete your wallet db files: located at ~/.chia/mainnet/wallet/db. This will require syncing up your wallet, but not your node. And then you can resubmit the transaction.
Make sure you have upgraded to the latest version
Start the application and wait for the wallet to sync up

Hope it helps

**Comment by dutchmulti** [comment]
> There is an issue with pending transactions being stuck. Please follow the following steps:
> 
> 1. Shut down your wallet and node
> 2. Delete your wallet db files: located at `~/.chia/mainnet/wallet/db`. This will require syncing up your wallet, but not your node. And then you can resubmit the transaction.
> 3. Make sure you have upgraded to the latest version
> 4. Start the application and wait for the wallet to sync up

After done this the bug is gone? What does it really means no payouts?

**Comment by dutchmulti** [comment]
> 2\. elete your wallet db files: located at `~/.chia/mainnet/wallet/db`. This will require syncing up your wallet, but not your node. And then you can resubmit the transaction.

everything in the folder of ~/.chia/mainnet/wallet/db 

there are 

- blockchain_wallet_v1_mainnet_329974173.sqlite
- blockchain_wallet_v1_mainnet_329974173.sqlite-shm
- blockchain_wallet_v1_mainnet_329974173.sqlite-wal
- wallet_peers.sqlite

Regards

**Comment by im-mike** [comment]
I've got over 2000 mentions of "status 3 error: Err.DOUBLE_SPEND" in the log since 3rd May but never had an "Err.MEMPOOL_NOT_INITIALIZED" - is this ok? Do I need to delete and resync my wallet?

I'm running 1.1.5 on Windows, thank you.

**Comment by jedocampo** [comment]
Im getting the same error already updated to 1.1.5... i guess deleting the db wallet doesn't work in most cases.

**Comment by Sabcoll** [comment]
+1

**Comment by btalachian** [comment]
> There is an issue with pending transactions being stuck. Please follow the following steps:
> 
> 1. Shut down your wallet and node
> 2. Delete your wallet db files: located at `~/.chia/mainnet/wallet/db`. This will require syncing up your wallet, but not your node. And then you can resubmit the transaction.
> 3. Make sure you have upgraded to the latest version
> 4. Start the application and wait for the wallet to sync up

My node has synced and I deleted all files in wallet/db and restart the PC after 2 hours still shows me not synced,

status: not synced
height: 0
connections: 0

**Comment by pdenning1984** [comment]
Anything ever come of this? See this all throughout my log file....

**Comment by pdenning1984** [comment]
Anything ever come of this, still having this issue!

**Comment by saifsayed00** [comment]
I am seeing the same issue with double spend errors. I wonder if this is causing me to lose chia

**Comment by jmjava** [comment]
I am seeing the same issue

**Comment by bashar1988** [comment]
me too, there 100 bug with chia we need help in order to keep going not to give up

**Comment by uberadminer** [comment]
Me too, hundreds of times

**Comment by sunami133** [comment]
+1

**Comment by pdenning1984** [comment]
Everything I read says that this is not so much an error but notification basically when a coin get submitted other coins at the same time do not when it tries to redo all coins the other coins have already been counted. They need to get rid of this alert!

**Comment by saifsayed00** [comment]
So why is this happening? How do I fix this problem on my setup?

**Comment by Scholarmate** [comment]
I am deleted all items in the wallet and still get the error:

2021-05-13T10:30:52.891 full_node chia.full_node.full_node: WARNING  Wasn't able to add transaction with id e71c62eb3a8b71d52752429faa00f50fb1a108498e264a00dbd272f0ec6ccc08, status 3 error: Err.DOUBLE_SPEND
2021-05-13T10:32:25.269 full_node chia.full_node.full_node: ERROR    Consensus error 124, not disconnecting

**Comment by t1m3fr33d0m** [comment]
+1

**Comment by brizio1971** [comment]
Does this BUG impact the block wins ?

**Comment by cchriso** [comment]
+1

**Comment by dutchmulti** [comment]
It is okay. That warming let you know that there is an transactions are being resubmitted. That is blockchain warming for developer.  Just ignore it. 
Got this from see comments under you tube https://www.youtube.com/watch?v=gMMimeMFGxI&lc=UgxuEY0_kSX9kAA9Nal4AaABAg.9NISksbO9bN9NJ84iRUXQz

**Comment by thiagoegito01** [comment]
> > 2\. elete your wallet db files: located at `~/.chia/mainnet/wallet/db`. This will require syncing up your wallet, but not your node. And then you can resubmit the transaction.
> 
> 
> 
> everything in the folder of ~/.chia/mainnet/wallet/db 
> 
> 
> 
> there are 
> 
> 
> 
> - blockchain_wallet_v1_mainnet_329974173.sqlite
> 
> - blockchain_wallet_v1_mainnet_329974173.sqlite-shm
> 
> - blockchain_wallet_v1_mainnet_329974173.sqlite-wal
> 
> - wallet_peers.sqlite
> 
> 
> 
>the filesappeared after exclude the file in DB and sync, but the problem persist

**Comment by Koesters** [comment]
The faucet that does send 10000000 mojo which sends it daily said my address was OK. I did this twice before and made sure it was way in excess of 24 hours. Now nothing arrives in my wallet but I get 
```
2021-05-15T19:30:27.228 full_node chia.full_node.full_node: WARNING  Wasn't able to add transaction with id c0084818bfe36a7af2185c5fbb87808409c18e5ad495a67b7ff3cd3bff1a371d, status 3 error: Err.DOUBLE_SPEND
2021-05-15T19:34:04.311 full_node chia.full_node.full_node: WARNING  Wasn't able to add transaction with id 095665fcc61b9fa0f06dda77cf7de76188983a5d890ce5efb0acec077bb17f4f, status 3 error: Err.MEMPOOL_NOT_INITIALIZED
2021-05-15T19:34:04.313 full_node chia.full_node.full_node: WARNING  Wasn't able to add transaction with id cfc05e558b4ea2595b195cef9d1e50a375df92298a023d47123950c663d657ee, status 3 error: Err.MEMPOOL_NOT_INITIALIZED
2021-05-15T19:34:04.317 full_node chia.full_node.full_node: WARNING  Wasn't able to add transaction with id 7f2b3e2426d49ce31e4157b6f4ba04b3e7f34836d4eb21b0c91e8ce18796c7c3, status 3 error: Err.MEMPOOL_NOT_INITIALIZED
2021-05-15T19:34:04.320 full_node chia.full_node.full_node: WARNING  Wasn't able to add transaction with id 451b04435a03408149b9ab18cf3f84ec70eed0a4b159a145b54a0fc4f2716465, status 3 error: Err.MEMPOOL_NOT_INITIALIZED
2021-05-15T19:34:04.322 full_node chia.full_node.full_node: WARNING  Wasn't able to add transaction with id bd0f575f4c9446c7a969231ecddb5b54dd6dab096317fb3f96b5a398db18473b, status 3 error: Err.MEMPOOL_NOT_INITIALIZED
2021-05-15T19:34:04.324 full_node chia.full_node.full_node: WARNING  Wasn't able to add transaction with id 2b2d90b05936627b74963dc492461ca9af551a6e0dbff7c3689906e4d4a51bce, status 3 error: Err.MEMPOOL_NOT_INITIALIZED
2021-05-15T19:34:04.331 full_node chia.full_node.full_node: WARNING  Wasn't able to add transaction with id 6aae0b6bab59be04a98ad8ef8c9833bc2154830a262700f36ccfe96eec1f7b31, status 3 error: Err.MEMPOOL_NOT_INITIALIZED
2021-05-15T19:34:04.332 full_node chia.full_node.full_node: WARNING  Wasn't able to add transaction with id 3e9a258fc43e01208347bdd0430a838a9a997c386380273627c42b47a3ed341d, status 3 error: Err.MEMPOOL_NOT_INITIALIZED
2021-05-15T19:34:04.333 full_node chia.full_node.full_node: WARNING  Wasn't able to add transaction with id 30da63f4f9ce308ea58f8e9b820e121a0592428822966f79fabf02b4e20d9016, status 3 error: Err.MEMPOOL_NOT_INITIALIZED
2021-05-15T19:34:04.335 full_node chia.full_node.full_node: WARNING  Wasn't able to add transaction with id 9d535f2f02c3151d14d340a1f6b3f98ff1d6916003391e0e4b5376df8ddb5f0c, status 3 error: Err.MEMPOOL_NOT_INITIALIZED
2021-05-15T19:36:21.513 full_node chia.full_node.full_node: WARNING  Wasn't able to add transaction with id 5e0fd02fa737a16dd9252f00973c1de56ebd70a947592925f1389673e4a78c2a, status 3 error: Err.COIN_AMOUNT_NEGATIVE

```


Looking up in chia explorer these transactions don't exist, not even once and my wallet stays at the same amount.

**Comment by saifsayed00** [comment]
> > 2. elete your wallet db files: located at `~/.chia/mainnet/wallet/db`. This will require syncing up your wallet, but not your node. And then you can resubmit the transaction.
> 
> everything in the folder of ~/.chia/mainnet/wallet/db
> 
> there are
> 
> * blockchain_wallet_v1_mainnet_329974173.sqlite
> * blockchain_wallet_v1_mainnet_329974173.sqlite-shm
> * blockchain_wallet_v1_mainnet_329974173.sqlite-wal
> * wallet_peers.sqlite
> 
> Regards

I only have two .sqlite files in my wallet/db folder. Is there something wrong

**Comment by mmatrosov** [comment]
> https://www.youtube.com/watch?v=gMMimeMFGxI&lc=UgxuEY0_kSX9kAA9Nal4AaABAg.9NISksbO9bN9NJ84iRUXQz

Sounds relaxing, but who is this Sam Ho guy, how do we know he knows what he is talking about? I'd prefer an official comment from the developers themselves (is he the one?).

**Comment by mmatrosov** [comment]
About `DOUBLE_SPEND`: https://github.com/Chia-Network/chia-blockchain/issues/3696#issuecomment-833369491
