### ISSUE TITLE
No sync since 3 May 10:00 PDT

### ISSUE THREAD

**Issue by COX888** [Chia-Network/chia-blockchain#3626]
No sync since 3 May 10:00 PDT
I did restart several times, no result

**Comment by Leozolt** [comment]
- Version?
- OS ?
- Node connections?
- What did you restart? The router for the internet connection, the software, the computer or the washing machine?

**Comment by Leozolt** [comment]
Did you try adding node.chia.net 8444 to the node connections

**Comment by ramzai23rus** [comment]
> * Версия?
> * ОПЕРАЦИОННЫЕ СИСТЕМЫ ?
> * Узловые соединения?
> * Что перезапускал? Маршрутизатор для подключения к Интернету, программное обеспечение, компьютер или стиральная машина?

Chia 1.1.3
Win10 19042.928
Farmer and Wallet
Restart PC, port 8444 open
![Скриншот 04-05-2021 101305](https://user-images.githubusercontent.com/29545081/116970842-55052c00-acc1-11eb-8549-6bc554642e60.jpg)

**Comment by mariano54** [comment]
Also make sure you're on 1.1.3

**Comment by ramzai23rus** [comment]
> Также убедитесь, что вы используете 1.1.3

The most recent version
![Uploading Скриншот 04-05-2021 101854.jpg…]()

**Comment by vbr07** [comment]
Same problem 🥶 network really not stable ....

**Comment by Leozolt** [comment]
> > * Версия?
> > * ОПЕРАЦИОННЫЕ СИСТЕМЫ ?
> > * Узловые соединения?
> > * Что перезапускал? Маршрутизатор для подключения к Интернету, программное обеспечение, компьютер или стиральная машина?
> 
> Chia 1.1.3
> Win10 19042.928
> Farmer and Wallet
> Restart PC, port 8444 open
> ![Скриншот 04-05-2021 101305](https://user-images.githubusercontent.com/29545081/116970842-55052c00-acc1-11eb-8549-6bc554642e60.jpg)
> 
> Nodes are not added manually
> node-eu.chia.net 8444
> node-or.chia.net 8444
> node-apne.chia.net 8444

the images you show has only localhost peers. maybe you can click on connect to peers and enter an adress like node.chia.net 8444. I is already clear that ther is a bug that prevents the connection and syncing automatically. as I heard there will be a 1.1.4 release sonn that might help.

**Comment by ramzai23rus** [comment]
> > > * Версия?
> > > * ОПЕРАЦИОННЫЕ СИСТЕМЫ?
> > > * Узловые соединения?
> > > * Что перезапускал? Маршрутизатор для подключения к Интернету, программное обеспечение, компьютер или стиральная машина?
> > 
> > 
> > Chia 1.1.3 
> > Win10 19042.928 
> > Farmer and Wallet 
> > Restart PC, порт 8444 открыт
> > ![Скриншот 04-05-2021 101305](https://user-images.githubusercontent.com/29545081/116970842-55052c00-acc1-11eb-8549-6bc554642e60.jpg)
> > Узлы не добавляются вручную 
> > node-eu.chia.net 8444 
> > node-or.chia.net 8444 
> > node-apne.chia.net 8444
> 
> изображения, которые вы показываете, имеют только одноранговые узлы localhost (127.0.0.1). возможно, вы можете щелкнуть «Подключиться к одноранговым узлам» и ввести адрес типа node.chia.net 8444. Уже ясно, что существует ошибка, которая в некоторых случаях препятствует автоматическому подключению и синхронизации. как я слышал, скоро выйдет версия 1.1.4, которая может помочь.

Doesn't connect node.chia.net 8444

**Comment by COX888** [comment]
Version 1.1.3 Windows 10. It was working till 10:00PDT. Chia app and PC was restarted several times, nothing happened. 
Also I cannot add node.chia.net 8444, nothing happened.

**Comment by vbr07** [comment]
Exactly same matter for me. They change something... now impossible to sync...

**Comment by Leozolt** [comment]
Try a virtual machine on your windows with ubuntu. sorry if I can not help you more than that. The most problems seem to be on win10 so I suspect a firwall / security thingy

**Comment by kdemer** [comment]
Same with me. I manage to manually add the 'node.chia.net' and 'node-eu.chia.net' (39.101.182.14) but still not........ wait....just fixed! ok  (I have update the program, restart the pc and cleanup the temp folders)

**Comment by johny182** [comment]
I have the same problem. After updating to 1.1.3 about 2h after release, i can not sync. Also downgrading does not help. And adding node.chia.net:8444 doesn't works also. Before update worked everything without any problems or need to open port in router or firewall/AV - which i did afterwards. Windows is up to date, python is up to date. In Log is lot of lines like this:
**_2021-05-04T10:14:46.392 full_node full_node_server        : INFO     Cannot connect to host 150.249.112.134:8444 ssl:<ssl.SSLContext object at 0x000002A101AC6978> [Connect call failed ('150.249.112.134', 8444)]_**

**Comment by Leozolt** [comment]
> Same with me. I manage to manually add the 'node.chia.net' and 'node-eu.chia.net' (39.101.182.14) but still not........ wait....just fixed! ok (I have update the program, restart the pc and cleanup the temp folders)
> (Win10, 1.13)

Let the others know what helped if you find out

**Comment by kdemer** [comment]
Update to the last version the program (I use win 10 pc) restart pc, delete all files in plot temporary directory, start the application and add manually the two nodes (node.chia.net:8444, and node-eu.chia.net:8444) and after couple minutes sync cames back.

**Comment by DIlbert25** [comment]
> Update to the last version the program (I use win 10 pc) restart pc, delete all files in plot temporary directory, start the application and add manually the two nodes (node.chia.net:8444, and node-eu.chia.net:8444) and after couple minutes sync cames back.

I do all this, not work.

Is possible do unistall 1.1.3 and camo back to previous version?

**Comment by kdemer** [comment]
Maybe it is chia's network error.... randomly not sync - sync the last hour. the problem was and before the update so I don't thing this is the problem....

**Comment by vbr07** [comment]
CONFIRMED
I TOUCH NOTHING AND SUDDENLY START SYNCING AGAIN JUST NOW
CRAZY !

**Comment by vbr07** [comment]
And sync failed again just right now

**Comment by ramzai23rus** [comment]
> Обновите программу до последней версии (я использую win 10 pc) перезагрузите компьютер, удалите все файлы во временном каталоге plot, запустите приложение и вручную добавьте два узла (node.chia.net:8444 и node-eu.chia. net: 8444) и через пару минут синхронизация вернулась.

these steps did not help me

**Comment by degrott** [comment]
The same issue happened 04.05.21 @1.1.2 Win10 version. Direct connections via GUI to the public nodes kinda node-eu.chia.net:8444 and etc. make no changes. Updated GUI to 1.1.3, still the same problem and it seems there is no solutions here

**Comment by dorkmo** [comment]
You might post your hardware processor specs

**Comment by ramzai23rus** [comment]
> Also make sure you're on 1.1.3

I connected the Internet via my phone, synchronization started.
Problems with the provider.
Tell me where to look, what ports to check?

**Comment by dorkmo** [comment]
cell operators usually block a lot of stuff

**Comment by johny182** [comment]
I have tried complete new installation and no luck. 

![obrazek](https://user-images.githubusercontent.com/22098380/117044161-688ab400-ad0e-11eb-9f4c-d592c06df98f.png)

 From Log with DEBUG level:

_2021-05-04T19:15:37.350 full_node full_node_server        : DEBUG    Timeout error connecting to wss://introducer.chia.net:8444/ws
2021-05-04T19:15:58.349 full_node full_node_server        : DEBUG    Connecting: wss://introducer.chia.net:8444/ws, Peer info: {'host': 'introducer.chia.net', 'port': 8444}
2021-05-04T19:16:29.353 full_node full_node_server        : DEBUG    Timeout error connecting to wss://introducer.chia.net:8444/ws
2021-05-04T19:17:06.379 full_node full_node_server        : DEBUG    Connecting: wss://introducer.chia.net:8444/ws, Peer info: {'host': 'introducer.chia.net', 'port': 8444}
2021-05-04T19:17:37.360 full_node full_node_server        : DEBUG    Timeout error connecting to wss://introducer.chia.net:8444/ws
2021-05-04T19:18:46.372 full_node full_node_server        : DEBUG    Connecting: wss://introducer.chia.net:8444/ws, Peer info: {'host': 'introducer.chia.net', 'port': 8444}
2021-05-04T19:19:17.345 full_node full_node_server        : DEBUG    Timeout error connecting to wss://introducer.chia.net:8444/ws_

Btw my PC: 3900x, 32GB Ram, Win10 19042.964, AV Eset SSP 14.0.22.0, SW up to date, Ports open in Router, Firewall and AV

**Comment by Leozolt** [comment]
click on "connect to other peers"  Host: node.chia.net Port: 8444

or any other node of your trust.

After the connections populate you can remove node.chia.net again...

**Comment by ramzai23rus** [comment]
Create a file and change its extension to .bat

echo off

cd /d %LOCALAPPDATA%\chia-blockchain\app-1.1.3\resources\app.asar.unpacked\daemon

chia show -a chiadb.net:8444
chia show -a 3.1.2.65:8444
chia show -a 35.80.8.179:8444
chia show -a 18.168.101.107:8444
chia show -a 222.95.182.99:8444
chia show -a 220.133.51.213:8444
chia show -a node.chia.net:8444
chia show -a node01.chiapaas.com:8444
chia show -a 109.146.197.182:8444
chia show -a 109.186.118.87:8444
chia show -a 152.136.28.181:8444
chia show -a 73.178.96.199:8444
chia show -a 73.178.96.199:8444
chia show -a 114.231.83.138:8444
chia show -a 70.124.151.91:8444
chia show -a 174.52.147.230:8444
chia show -a 59.36.190.110:8444
chia show -a pyl.dk:8444
chia show -a farmer1.chia.net:8444
chia show -a farmer2.chia.net:8444
chia show -a sumo.chia.net:8444
chia show -a beast.chia.net:8444
chia show -a 81.83.5.50:8444
chia show -a 54.200.113.72:8444
chia show -a 118.189.201.184:8444
chia show -a 135.181.176.20:8444
chia show -a 84.213.89.142:8444
chia show -a 35.209.51.153:8444
chia show -a 96.55.68.145:8444
chia show -a 79.208.170.133:8444
chia show -a 67.161.167.237:8444
chia show -a 82.209.154.140:8444
chia show -a 63.86.188.28:8444
chia show -a 70.67.4.75:8444
chia show -a 80.254.212.16:8444
chia show -a 159.28.171.166:8444
chia show -a 221.194.44.233:8444
chia show -a 210.54.32.139:8444
chia show -a 90.39.83.235:8444
chia show -a 220.133.77.36:8444
chia show -a 89.74.40.135:8444
chia show -a 35.242.164.134:8444
chia show -a 39.57.87.148:8444
chia show -a 112.94.75.184:8444
chia show -a 193.44.211.178:8444
chia show -a 187.22.135.248:8444
chia show -a 73.33.58.218:8444
chia show -a 36.35.18.57:8444

**Comment by johny182** [comment]
> 
> 
> click on "connect to other peers" Host: node.chia.net Port: 8444
> 
> or any other node of your trust.
> 
> After the connections populate you can remove node.chia.net again...

Doesn't work. The peer is not added and in log is:

_2021-05-04T21:30:48.523 full_node full_node_server        : DEBUG    Connecting: wss://node.chia.net:8444/ws, Peer info: {'host': 'node.chia.net', 'port': 8444}
2021-05-04T21:31:19.351 full_node full_node_server        : DEBUG    Timeout error connecting to wss://node.chia.net:8444/ws
2021-05-04T21:31:19.352 full_node chia.rpc.rpc_server     : WARNING  Error while handling message: Traceback (most recent call last):
  File "chia\rpc\rpc_server.py", line 212, in safe_handle
  File "chia\rpc\rpc_server.py", line 200, in ws_api
  File "chia\rpc\rpc_server.py", line 161, in open_connection
ValueError: Start client failed, or server is not set_

>Create a file and change its extension to .bat
>
>echo off
> ...

Nope, only errors in log:

_Connecting to chiadb.net, 8444
Failed to connect to chiadb.net:8444
Connecting to 3.1.2.65, 8444
Failed to connect to 3.1.2.65:8444
Connecting to 35.80.8.179, 8444
Failed to connect to 35.80.8.179:8444
Connecting to 18.168.101.107, 8444
Failed to connect to 18.168.101.107:8444
Connecting to 222.95.182.99, 8444
Failed to connect to 222.95.182.99:8444
Connecting to 220.133.51.213, 8444
Failed to connect to 220.133.51.213:8444
Connecting to node.chia.net, 8444
Failed to connect to node.chia.net:8444
Connecting to node01.chiapaas.com, 8444
Failed to connect to node01.chiapaas.com:8444
Connecting to 109.146.197.182, 8444
Failed to connect to 109.146.197.182:8444
....._

and

2021-05-04T21:39:12.166 full_node full_node_server        : INFO     Cannot connect to host chiadb.net:8444 ssl:<ssl.SSLContext object at 0x000002CEC8AFCBA8> [Connect call failed ('202.61.226.20', 8444)]
2021-05-04T21:39:12.166 full_node chia.rpc.rpc_server     : WARNING  Error while handling message: Traceback (most recent call last):
  File "chia\rpc\rpc_server.py", line 81, in inner
  File "chia\rpc\rpc_server.py", line 161, in open_connection
ValueError: Start client failed, or server is not set

2021-05-04T21:39:12.732 full_node full_node_server        : DEBUG    Connecting: wss://3.1.2.65:8444/ws, Peer info: {'host': '3.1.2.65', 'port': 8444}
2021-05-04T21:39:33.768 full_node full_node_server        : INFO     Cannot connect to host 3.1.2.65:8444 ssl:<ssl.SSLContext object at 0x000002CEC8AFCD68> [Connect call failed ('3.1.2.65', 8444)]
2021-05-04T21:39:33.768 full_node chia.rpc.rpc_server     : WARNING  Error while handling message: Traceback (most recent call last):
  File "chia\rpc\rpc_server.py", line 81, in inner
  File "chia\rpc\rpc_server.py", line 161, in open_connection
ValueError: Start client failed, or server is not set

2021-05-04T21:39:34.366 full_node full_node_server        : DEBUG    Connecting: wss://35.80.8.179:8444/ws, Peer info: {'host': '35.80.8.179', 'port': 8444}
2021-05-04T21:39:55.407 full_node full_node_server        : INFO     Cannot connect to host 35.80.8.179:8444 ssl:<ssl.SSLContext object at 0x000002CEC8AFCBA8> [Connect call failed ('35.80.8.179', 8444)]
2021-05-04T21:39:55.407 full_node chia.rpc.rpc_server     : WARNING  Error while handling message: Traceback (most recent call last):
  File "chia\rpc\rpc_server.py", line 81, in inner
  File "chia\rpc\rpc_server.py", line 161, in open_connection
ValueError: Start client failed, or server is not set

2021-05-04T21:39:55.967 full_node full_node_server        : DEBUG    Connecting: wss://18.168.101.107:8444/ws, Peer info: {'host': '18.168.101.107', 'port': 8444}
2021-05-04T21:40:08.431 farmer chia.farmer.farmer         : DEBUG    Cleared farmer cache. Num sps: 0 0 0 0
2021-05-04T21:40:16.986 full_node full_node_server        : INFO     Cannot connect to host 18.168.101.107:8444 ssl:<ssl.SSLContext object at 0x000002CEC8AFC278> [Connect call failed ('18.168.101.107', 8444)]
2021-05-04T21:40:16.986 full_node chia.rpc.rpc_server     : WARNING  Error while handling message: Traceback (most recent call last):
  File "chia\rpc\rpc_server.py", line 81, in inner
  File "chia\rpc\rpc_server.py", line 161, in open_connection
ValueError: Start client failed, or server is not set

2021-05-04T21:40:17.540 full_node full_node_server        : DEBUG    Connecting: wss://222.95.182.99:8444/ws, Peer info: {'host': '222.95.182.99', 'port': 8444}
2021-05-04T21:40:38.588 full_node full_node_server        : INFO     Cannot connect to host 222.95.182.99:8444 ssl:<ssl.SSLContext object at 0x000002CEC8AFC5F8> [Connect call failed ('222.95.182.99', 8444)]
2021-05-04T21:40:38.588 full_node chia.rpc.rpc_server     : WARNING  Error while handling message: Traceback (most recent call last):
  File "chia\rpc\rpc_server.py", line 81, in inner
  File "chia\rpc\rpc_server.py", line 161, in open_connection
ValueError: Start client failed, or server is not set

2021-05-04T21:40:39.151 full_node full_node_server        : DEBUG    Connecting: wss://220.133.51.213:8444/ws, Peer info: {'host': '220.133.51.213', 'port': 8444}
2021-05-04T21:41:00.202 full_node full_node_server        : INFO     Cannot connect to host 220.133.51.213:8444 ssl:<ssl.SSLContext object at 0x000002CEC8B1D128> [Connect call failed ('220.133.51.213', 8444)]
2021-05-04T21:41:00.203 full_node chia.rpc.rpc_server     : WARNING  Error while handling message: Traceback (most recent call last):
  File "chia\rpc\rpc_server.py", line 81, in inner
  File "chia\rpc\rpc_server.py", line 161, in open_connection
ValueError: Start client failed, or server is not set

2021-05-04T21:41:00.774 full_node full_node_server        : DEBUG    Connecting: wss://node.chia.net:8444/ws, Peer info: {'host': 'node.chia.net', 'port': 8444}
2021-05-04T21:41:31.345 full_node full_node_server        : DEBUG    Timeout error connecting to wss://node.chia.net:8444/ws
2021-05-04T21:41:31.346 full_node chia.rpc.rpc_server     : WARNING  Error while handling message: Traceback (most recent call last):
  File "chia\rpc\rpc_server.py", line 81, in inner
  File "chia\rpc\rpc_server.py", line 161, in open_connection
ValueError: Start client failed, or server is not set
...

**Comment by Leozolt** [comment]
Strange that all the connections fail..

can you try "telnet portquiz.net 8444" in the command line. You can also try it on a node ip or hostname I guess

You might neet to enable a windows functionality "Telnet"

Does it connect?

**Comment by johny182** [comment]
Nope. _Cannot connet to host on port 8444_ 
I think my connection is broken.

**Comment by Leozolt** [comment]
> Nope. _Cannot connet to host on port 8444_
> I think my connection is broken.

Could be a policy from the ISP. Port 8444 is or was used for encrypted p2p communication, witch in som countrys may be prohibited.

**Comment by johny182** [comment]
And now it just start to work... Don't ask, i have no idea what happend. I have touched nothing. My ISP blocks no ports, he says at least. Maybe some sort of update at ISP was causing that? Btw i am in Germany, my ISP is Vodafone/UnityMedia and connection is over DSL.

![obrazek](https://user-images.githubusercontent.com/22098380/117112805-e7710280-ad89-11eb-8c8f-a8b879e8a665.png)

**Comment by Leozolt** [comment]
Good that it is working.

Next possible step would have been traceroute with port 8444 to track down the error maybe

**Comment by vbr07** [comment]
Same for me, i change nothing and all started to work again.
This confirm it is only network too young and unstable. Hope rhis will be solved soon.

**Comment by johny182** [comment]
So far so good. Just syncing from 0 take a lot of time... It runs about 8h and i am on 171584/233956.
