### ISSUE TITLE
[BUG] Faild fetch Block add Sync node full overload.

### ISSUE THREAD

**Issue by vanthoi** [Chia-Network/chia-blockchain#3643]
**Describe the bug**
I looked at the log and saw an error like this appearing many times.
```
2021-05-04T15:10:43.440 full_node full_node_server        : ERROR    Exception: Failed to fetch block 228631 from None, timed out, None. Traceback (most recent call last):
  File "chia\server\server.py", line 521, in wrapped_coroutine
  File "chia\full_node\full_node_api.py", line 104, in new_peak
  File "chia\full_node\full_node.py", line 361, in new_peak
  File "chia\full_node\full_node.py", line 310, in short_sync_backtrack
  File "chia\full_node\full_node.py", line 295, in short_sync_backtrack
ValueError: Failed to fetch block 228631 from None, timed out

2021-05-04T15:10:43.456 full_node full_node_server        : ERROR    Exception: Failed to fetch block 228631 from None, timed out <class 'ValueError'>, closing connection None. Traceback (most recent call last):
  File "chia\server\server.py", line 531, in api_call
  File "asyncio\tasks.py", line 414, in wait_for
  File "chia\server\server.py", line 528, in wrapped_coroutine
  File "chia\server\server.py", line 521, in wrapped_coroutine
  File "chia\full_node\full_node_api.py", line 104, in new_peak
  File "chia\full_node\full_node.py", line 361, in new_peak
  File "chia\full_node\full_node.py", line 310, in short_sync_backtrack
  File "chia\full_node\full_node.py", line 295, in short_sync_backtrack
ValueError: Failed to fetch block 228631 from None, timed out
```

My Full node is frequently overloaded asynchronously. If I don't open port 8444 everything is fine. If I open this port. There are over 55 Full nodes connected to my node and they frequently change node addresses. I see the log to see error not connect node, reconect node. Each time like this, about 1 to 2 hours is repeated once. Each time, it takes about 10 to 15 minutes to sync again. If I run the command chia.exe start node -r then the problem gets fixed.

`2021-05-04T15:38:10.190 full_node chia.full_node.full_node: ERROR    Respond peers exception: . Traceback: Traceback (most recent call last):
  File "chia\server\node_discovery.py", line 507, in respond_peers
  File "chia\server\node_discovery.py", line 397, in _respond_peers_common
  File "chia\server\address_manager.py", line 602, in add_to_new_table
  File "asyncio\locks.py", line 92, in __aenter__
  File "asyncio\locks.py", line 192, in acquire
concurrent.futures._base.CancelledError`

**Desktop (please complete the following information):**
- OS: Windows Server 2019
- RAM: 64GB,
- CPU: [e.g. Intel Xeon E5 2670]

**Comment by ricki008** [comment]
Can you explain how can I run this command? I'm having the same problem now... 
Yesterday I had problems with port 8444 today I open the 8444 to 8449 and now this, this chia.exe start node -r where you write?

**Comment by vanthoi** [comment]
> Can you explain how can I run this command? I'm having the same problem now...
> Yesterday I had problems with port 8444 today I open the 8444 to 8449 and now this, this chia.exe start node -r where you write?

If run OS Windows : Right click ic chia: Open location --> Appxxx>Resource>deamon hold Shift Click Right open Windows Shell

**Comment by ricki008** [comment]
> > Can you explain how can I run this command? I'm having the same problem now...
> > Yesterday I had problems with port 8444 today I open the 8444 to 8449 and now this, this chia.exe start node -r where you write?
> 
> If run OS Windows : Right click icon chia: Open location --> Appxxx>Resource>deamon hold Shift Click Right open Windows Shell

Lot of thanks! @vanthoi

**Comment by spammenotinoz** [comment]
I also receive this error in the debug logs, but always self recovers.
In my case it's usually a result of a peer not listening (eg: not running, not port forwarding ect..) or running older software.
I think the popularity of this network is a downside, too many people running full nodes on under resourced hardware (due to plotting on the same hardware).

**Comment by vanthoi** [comment]
Ver 1.4 fixed error

**Comment by tschechniker** [comment]
@vanthoi 

i have the same issue with V 1.4

**Comment by njtnestor** [comment]
I have same issue with v 1.4 too

**Comment by JakeShirley** [comment]
Having these errors spew on my Unraid farmer on 1.1.6.dev0.

**Comment by kevinkk525** [comment]
Same problem here with docker 1.1.6.dev0 on ubuntu. Driving me nuts as the node can't even stay synced for 30 minutes, then I have to restart it and manually connect the previous nodes to get it synced quickly. 
What's the equivalent of "-r" option for using docker?

**Comment by dennis1511** [comment]
Has anyone solve the issue?

**Comment by kevinkk525** [comment]
No problems anymore here since the last update.

**Comment by cantak** [comment]
I only had this issue with one plot. No hardware issues. Unfortunately it was a K35 plot and 884 GiB give or take in size. I recreated the plot and had no issues. I certainly hate to recreate it though.

**Comment by Senyalool** [comment]
### **Please help me solve the error!
can't find the answer :(**
2021-06-08T19:25:23.584 full_node full_node_server        : INFO     Cannot connect to host 89.74.230.174:8444 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE
_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1091)')]
2021-06-08T21:36:27.968 full_node full_node_server        : ERROR    Exception: Failed to fetch block 403169 from None, timed out, None. Traceback (most recent call last
):
ValueError: Failed to fetch block 403169 from None, timed out
2021-06-08T21:36:27.970 full_node full_node_server        : ERROR    Exception: Failed to fetch block 403169 from None, timed out <class 'ValueError'>, closing connectio
n None. Traceback (most recent call last):
ValueError: Failed to fetch block 403169 from None, timed out
2021-06-08T22:46:04.468 full_node full_node_server        : ERROR    Exception: Failed to fetch block 403376 from None, timed out, None. Traceback (most recent call last
):
ValueError: Failed to fetch block 403376 from None, timed out
2021-06-08T22:46:04.470 full_node full_node_server        : ERROR    Exception: Failed to fetch block 403376 from None, timed out <class 'ValueError'>, closing connectio
n None. Traceback (most recent call last):
ValueError: Failed to fetch block 403376 from None, timed out
2021-06-08T23:01:18.168 full_node full_node_server        : ERROR    Exception: Failed to fetch block 403424 from None, timed out, None. Traceback (most recent call last
):
ValueError: Failed to fetch block 403424 from None, timed out
2021-06-08T23:01:18.170 full_node full_node_server        : ERROR    Exception: Failed to fetch block 403424 from None, timed out <class 'ValueError'>, closing connectio
n None. Traceback (most recent call last):
ValueError: Failed to fetch block 403424 from None, timed out
2021-06-08T23:01:19.022 full_node full_node_server        : ERROR    Exception: Failed to fetch block 403424 from None, timed out, None. Traceback (most recent call last
):
ValueError: Failed to fetch block 403424 from None, timed out
2021-06-08T23:01:19.023 full_node full_node_server        : ERROR    Exception: Failed to fetch block 403424 from None, timed out <class 'ValueError'>, closing connectio
n None. Traceback (most recent call last):
ValueError: Failed to fetch block 403424 from None, timed out
2021-06-08T23:01:19.265 full_node full_node_server        : ERROR    Exception: Failed to fetch block 403424 from None, timed out, None. Traceback (most recent call last
):
ValueError: Failed to fetch block 403424 from None, timed out
2021-06-08T23:01:19.267 full_node full_node_server        : ERROR    Exception: Failed to fetch block 403424 from None, timed out <class 'ValueError'>, closing connectio
n None. Traceback (most recent call last):
ValueError: Failed to fetch block 403424 from None, timed out
2021-06-08T23:01:21.543 full_node full_node_server        : ERROR    Exception: Failed to fetch block 403424 from None, timed out, None. Traceback (most recent call last
):
ValueError: Failed to fetch block 403424 from None, timed out
2021-06-08T23:01:21.544 full_node full_node_server        : ERROR    Exception: Failed to fetch block 403424 from None, timed out <class 'ValueError'>, closing connectio
n None. Traceback (most recent call last):
ValueError: Failed to fetch block 403424 from None, timed out
2021-06-08T23:08:45.643 full_node full_node_server        : INFO     Cannot connect to host 89.74.230.174:8444 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE
_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1091)')]
2021-06-08T23:29:44.192 full_node full_node_server        : INFO     Cannot connect to host 185.120.154.237:8444 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICA
TE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1091)')]
**Please help me solve the error!
can't find the answer :(**
