### ISSUE TITLE
[BUG] Local Harvester Plots

### ISSUE THREAD

**Issue by ElganPy** [Chia-Network/chia-blockchain#3692]
- OS: [Windows 10]
- CPU: [Intel Pentium G5400]
- Failed to execute script chia
Traceback (most recent call last):
  File "chia\cmds\chia.py", line 81, in <module>
  File "chia\cmds\chia.py", line 77, in main
  File "click\core.py", line 829, in __call__
  File "click\core.py", line 782, in main
  File "click\core.py", line 1259, in invoke
  File "click\core.py", line 1259, in invoke
  File "click\core.py", line 1066, in invoke
  File "click\core.py", line 610, in invoke
  File "click\decorators.py", line 21, in new_func
  File "chia\cmds\plots.py", line 135, in create_cmd
  File "chia\plotting\create_plots.py", line 176, in create_plots
RuntimeError: Unknown exception

**Comment by Gomes1990** [comment]
disable bitfield ploting
