### ISSUE TITLE
[BUG]  full_node chia.full_node.full_node: WARNING  Wasn't able to add transaction with id

### ISSUE THREAD

**Issue by Djomla003** [Chia-Network/chia-blockchain#3696]
beeing spamed in the debug.log file of chia with following output: 

```
2021-05-02T15:46:09.100 full_node chia.full_node.full_node: ERROR    Respond peers exception: . Traceback: Traceback (most recent call last):
  File "/INSTALL/chia-blockchain/chia/server/node_discovery.py", line 507, in respond_peers
    await self._respond_peers_common(request, peer_src, is_full_node)
  File "/INSTALL/chia-blockchain/chia/server/node_discovery.py", line 397, in _respond_peers_common
    await self.address_manager.add_to_new_table(peers_adjusted_timestamp, peer_src, 2 * 60 * 60)
  File "/INSTALL/chia-blockchain/chia/server/address_manager.py", line 602, in add_to_new_table
    async with self.lock:
  File "/usr/local/lib/python3.7/asyncio/locks.py", line 92, in __aenter__
    await self.acquire()
  File "/usr/local/lib/python3.7/asyncio/locks.py", line 192, in acquire
    await fut
concurrent.futures._base.CancelledError

2021-05-02T15:46:09.100 full_node chia.full_node.full_node: ERROR    Respond peers exception: . Traceback: Traceback (most recent call last):
  File "/INSTALL/chia-blockchain/chia/server/node_discovery.py", line 507, in respond_peers
    await self._respond_peers_common(request, peer_src, is_full_node)
  File "/INSTALL/chia-blockchain/chia/server/node_discovery.py", line 397, in _respond_peers_common
    await self.address_manager.add_to_new_table(peers_adjusted_timestamp, peer_src, 2 * 60 * 60)
  File "/INSTALL/chia-blockchain/chia/server/address_manager.py", line 602, in add_to_new_table
    async with self.lock:
  File "/usr/local/lib/python3.7/asyncio/locks.py", line 92, in __aenter__
    await self.acquire()
  File "/usr/local/lib/python3.7/asyncio/locks.py", line 192, in acquire
    await fut
concurrent.futures._base.CancelledError

2021-05-03T04:49:00.350 full_node chia.full_node.full_node: WARNING  Do not have sub slot XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
2021-05-03T22:11:36.894 full_node chia.full_node.full_node: WARNING  Wasn't able to add transaction with id XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX, status 3 error: Err.UNKNOWN_UNSPENT
2021-05-04T01:22:35.726 full_node full_node_server        : ERROR    Exception: Failed to fetch block 226703 from {'host': '128.74.211.53', 'port': 8444}, timed out, {'host': '128.74.211.53', 'port': 8444}. Traceback (most recent call last):
  File "/INSTALL/chia-blockchain/chia/server/server.py", line 521, in wrapped_coroutine
    result = await coroutine
  File "/INSTALL/chia-blockchain/chia/full_node/full_node_api.py", line 104, in new_peak
    return await self.full_node.new_peak(request, peer)
  File "/INSTALL/chia-blockchain/chia/full_node/full_node.py", line 361, in new_peak
    peer, curr_peak_height, request.height, request.unfinished_reward_block_hash
  File "/INSTALL/chia-blockchain/chia/full_node/full_node.py", line 310, in short_sync_backtrack
    raise e
  File "/INSTALL/chia-blockchain/chia/full_node/full_node.py", line 295, in short_sync_backtrack
    raise ValueError(f"Failed to fetch block {curr_height} from {peer.get_peer_info()}, timed out")
ValueError: Failed to fetch block XXXXX from {'host': '128.74.211.53', 'port': 8444}, timed out

2021-05-04T01:22:35.730 full_node full_node_server        : ERROR    Exception: Failed to fetch block XXXXXX from {'host': '128.74.211.53', 'port': 8444}, timed out <class 'ValueError'>, closing connection {'host': '128.74.211.53', 'port': 8444}. Traceback (most recent call last):
  File "/INSTALL/chia-blockchain/chia/server/server.py", line 531, in api_call
    response: Optional[Message] = await asyncio.wait_for(wrapped_coroutine(), timeout=timeout)
  File "/usr/local/lib/python3.7/asyncio/tasks.py", line 414, in wait_for
    return await fut
  File "/INSTALL/chia-blockchain/chia/server/server.py", line 528, in wrapped_coroutine
    raise e
  File "/INSTALL/chia-blockchain/chia/server/server.py", line 521, in wrapped_coroutine
    result = await coroutine
  File "/INSTALL/chia-blockchain/chia/full_node/full_node_api.py", line 104, in new_peak
    return await self.full_node.new_peak(request, peer)
  File "/INSTALL/chia-blockchain/chia/full_node/full_node.py", line 361, in new_peak
    peer, curr_peak_height, request.height, request.unfinished_reward_block_hash
  File "/INSTALL/chia-blockchain/chia/full_node/full_node.py", line 310, in short_sync_backtrack
    raise e
  File "/INSTALL/chia-blockchain/chia/full_node/full_node.py", line 295, in short_sync_backtrack
    raise ValueError(f"Failed to fetch block {curr_height} from {peer.get_peer_info()}, timed out")
ValueError: Failed to fetch block XXXXXX from {'host': '128.74.211.53', 'port': 8444}, timed out

2021-05-04T01:22:35.731 full_node full_node_server        : WARNING  Banning 128.74.211.53 for 10 seconds
2021-05-04T03:39:10.556 full_node chia.full_node.full_node: WARNING  Wasn't able to add transaction with id XXXXXXXXXXXXX, status 3 error: Err.UNKNOWN_UNSPENT
```

Based on the GUI everything is synced and working. 

Does this BUG impact the block wins / chia wins? 

Thanks.

**Comment by temicus** [comment]
Hey I have similar error:
`2021-05-04T09:44:04.055 full_node full_node_server        : WARNING  Cannot write to closing transport XX
2021-05-04T09:50:40.660 full_node chia.full_node.full_node: WARNING  Wasn't able to add transaction with id XXXX, status 3 error: Err.DOUBLE_SPEND`

Please help!

**Comment by hexslav** [comment]
Hello, next similar one, started popping out for me today

`2021-05-04T11:05:21.327 full_node chia.full_node.full_node: WARNING  Wasn't able to add transaction with id XXX, status 3 error: Err.MEMPOOL_NOT_INITIALIZED`

Everything in GUI looks fine. 
Cheers, have a good day!

**Comment by ricki008** [comment]
Somebody know the answer yet?? I'm having the same problem :(

**Comment by LamichhaneKamal** [comment]
same issue

**Comment by temicus** [comment]
still have it even after updating to 1.1.4
+ this one now:
UNKNOWN_UNSPENT and DOUBLE_SPEND

**Comment by djdookie** [comment]
Same here, sseing this error in debug.log several times per minute. I think I get this error since v1.1.3 under Ubuntu.

**Comment by SKYBILLS** [comment]
In Windows Gui also have same problems !!! Please Fixed it

**Comment by iLexGit** [comment]
This is happening to me now that i have updated to 1.1.4, it didn't happen before. IT HAPPENS EVERY TIME SOME OF MY BLOCKS PASS THE FILTER. EVERY. SINGLE. TIME.

**Comment by zewort** [comment]
full_node chia.full_node.full_node: WARNING  Wasn't able to add transaction with id XXXXXXXXXXX, status 3 error: Err.DOUBLE_SPEND

¿?¿?¿?¿?¿?¿?¿

**Comment by iLexGit** [comment]
Always "status error 3" followed by one of these two:
- UNKNOWN_UNSPENT
- DOUBLE_SPEND

Also, to the dev that answers this, appart from saying this is going to be fixed or if it is a bug at all (maybe the 1.1.4 logging is more verbose). EXPLAIN WHY this happens or WHAT it is. If the community understands better how your network works and what casues the issues we will be here asking recurrent questions MUCH LESS!!! It is in everyone's best interest. Just consider it.

Thx

**Comment by Muffexx** [comment]
Might not be an issue.
Check #3773

**Comment by iLexGit** [comment]
Yeah mariano said this happens cause " Transactions are being resubmitted sometimes" but this is not sometimes... this is absolutely everytime I receive an uncompleted block . My log is absolutely full of lines like this. Also, why is this happening, how can this be solved and what has changed in 1.1.4 that makes this happen...

IDK but i feel like we should have a lot more information about how the network works, what it uses, etc

**Comment by Muffexx** [comment]
I'm also having the same issue (_Err.DOUBLE_SPEND_) multiple times per minute.

**Comment by hobbit6** [comment]
I'm having this issue too, every few minutes I get Err.DOUBLE_SPEND

**Comment by meaverick** [comment]
full_node chia.full_node.full_node: WARNING  Wasn't able to add transaction with id ### status 3 error: Err.DOUBLE_SPEND

**Comment by Cheshyr** [comment]
Ubuntu 20.04.  Same issue.  Was not present on 1.1.2, but took over my logs in 1.1.4

Log transitioning between 1.1.2 and 1.1.4

`2021-05-05T22:52:57.297 timelord chia.timelord.timelord   : WARNING  Will not infuse e7e01c929f8f4db1d8b79d1e679dec7ba9e473eb35de13330d073490c47dae74 because its reward chain challenge is not in the chain
2021-05-05T22:52:57.297 timelord chia.timelord.timelord   : WARNING  Received invalid unfinished block: Required iters 2062250 is not below the sp interval iters 1720320 110100480 or not >0..
2021-05-05T22:52:57.298 timelord chia.timelord.timelord   : WARNING  Will not infuse 641731ae9f8f0cf8a4cfcf54c9308b2a95735d7f1c4893463458618c682d0b93 because its reward chain challenge is not in the chain
2021-05-05T22:52:57.298 timelord chia.timelord.timelord   : WARNING  Will not infuse 8ed9ce1e2ec3cc6d80a04b090851e2b9fe2967e59a8678cf285fd45040ed0a48 because its reward chain challenge is not in the chain
2021-05-05T22:52:57.299 timelord chia.timelord.timelord   : WARNING  Will not infuse 8d1bb8f55a110792ba975d46e7fc94d7acc2c556caa6672b6b8024ca48fc2d88 because its reward chain challenge is not in the chain
2021-05-05T22:52:57.299 timelord chia.timelord.timelord   : WARNING  Will not infuse 8d1bb8f55a110792ba975d46e7fc94d7acc2c556caa6672b6b8024ca48fc2d88 because its reward chain challenge is not in the chain
2021-05-05T22:52:57.299 timelord chia.timelord.timelord   : WARNING  Will not infuse 566b5122572ed24fa0a85c0709d778c2e54b27a46c1ad3a4478d5d34a106c4fa because its reward chain challenge is not in the chain
2021-05-05T22:52:57.300 timelord chia.timelord.timelord   : WARNING  Will not infuse e68ba852c55fb87d967b2e3a91587b7bb4b9c7439cc894451a33f4e3589a223f because its reward chain challenge is not in the chain
2021-05-05T22:52:57.300 timelord chia.timelord.timelord   : WARNING  Will not infuse 668a238bc4dbef02847e2c9ad6fbf9fe3c564f33528d226362fce07420d8907b because its reward chain challenge is not in the chain
2021-05-05T22:52:57.300 timelord chia.timelord.timelord   : WARNING  Will not infuse 1a08d22d310db7f193350087e4982e38c765fb6f7cdaec87be3239184b669a7e because its reward chain challenge is not in the chain
2021-05-05T22:52:57.301 timelord chia.timelord.timelord   : WARNING  Will not infuse fbde57f0e39d439249655271910c39cebe6d75e19219eb0a7e06963656eea5de because its reward chain challenge is not in the chain
2021-05-05T22:53:04.056 full_node asyncio                 : ERROR    Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7fdefec70820>
2021-05-05T22:55:47.921 full_node chia.full_node.full_node: WARNING  Wasn't able to add transaction with id 6c76014e93d265daa337e6d62ec6b8c92957b4ca8545bb2ea842f4a19adcbf44, status 3 error: Err.MEMPOOL_NOT_INITIALIZED
2021-05-05T22:56:36.907 wallet asyncio                    : ERROR    Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7f39fad446a0>
2021-05-05T23:03:05.864 full_node chia.full_node.full_node: WARNING  Wasn't able to add transaction with id 66586e9665c895cb561acc36cbd1f93d4ad31c80cbe5d1348b18870cb6d5c153, status 3 error: Err.DOUBLE_SPEND
2021-05-05T23:03:05.958 full_node chia.full_node.full_node: WARNING  Wasn't able to add transaction with id 004c906601c936836b228af243dfa281d273179e84f3445d22d2f54b0c95635c, status 3 error: Err.DOUBLE_SPEND
2021-05-05T23:04:02.047 full_node chia.full_node.full_node: WARNING  Wasn't able to add transaction with id 302335b20c5726b55288a6379437b1de7e8e391b1d4106fd93fa74fe7304073d, status 3 error: Err.DOUBLE_SPEND
2021-05-05T23:04:07.539 full_node chia.full_node.full_node: WARNING  Wasn't able to add transaction with id e1846633d9f9bf5d4adcbb15197155f01e478ccf679d3fa50f511f62542ff4f7, status 3 error: Err.DOUBLE_SPEND
2021-05-05T23:04:27.728 full_node chia.full_node.full_node: WARNING  Wasn't able to add transaction with id 6bc6e78d5aad9340e30f214655fa9cf386c1aa388f67ec7be55912852eb9a67d, status 3 error: Err.DOUBLE_SPEND
2021-05-05T23:13:03.634 full_node chia.full_node.full_node: WARNING  Wasn't able to add transaction with id 9952d511e1bdabe2e3fa33b6111836a9388c3c8094ed9f8efb604d3a880c4cfe, status 3 error: Err.DOUBLE_SPEND
2021-05-05T23:17:38.883 full_node chia.full_node.full_node: WARNING  Wasn't able to add transaction with id 1ee0edb35fabbe8ba0fceffffe3ab588d04e3b40fbe6cc4de74559ef1608b7fc, status 3 error: Err.DOUBLE_SPEND
`

**Comment by danktankk** [comment]
Im having the same issue

**Comment by JamLeeSut** [comment]
Same issue here too on Win10 GUI

**Comment by Justinapica** [comment]
Same Issue. Chia 1.1.4 linux.

**Comment by mariano54** [comment]
MEMPOOL_NOT_INITIALIZED happens when you are just starting up your node. If you are still seeing this, restart the node.

I will explain why DOUBLE_SPEND is printed. Let's say you have transactions A, B and C in the mempool. The mempool is where you keep transactions that people send, but have not been included in a block yet.

Let's say you then get a new block, which includes transactions B and C. What do we do with the mempool? We create a new mempool, and try to add all transactions to it. When we add tx A, it validates with no problem. However when we try to add transactions B and C, they are no longer valid because they are trying to spend coins which have already been spent. Those transactions are conflicting with the same transactions that just got included. So that is how we clear the mempool from old transactions.

There are some differences with chia and other coins, because any 2 transactions can be combined. It's possible that the block did not include B and C, but it included another transaction X, which is a combination of multiple transactions (BCD) for example. So in this case, transaction B was never included on chain, but a conflicting transaction was. So B is now considered a "double spend" and is no longer valid. So this is how we filter out things from the mempool when we get a new block: we just try adding them all again one by one.

We can remove these warnings so there is less confusion

**Comment by SKYBILLS** [comment]
Thanks fully understood

**Comment by Cheshyr** [comment]
Thank you for clarifying. I think some of this might be specific to the error level evoked. If this is normal operation, and perhaps it is INFO, not WARNING. When I see a warning, I assume I need to do something about it. I suspect this is similar for other people

**Comment by hbroer** [comment]
@mariano54

> If you are still seeing this, restart the node.

Just looked into my logs. Started the GUI around 13:40 and got the message a few minutes later. Ok so far, was expected. But one hour later it began to spam the log with 304 lines of that error (until now 19:30)

Is the node broken then if it needs a restart, or is it still ok. The GUI did not show any error. I don't want to look into my logs every 10 minutes ;)

**Comment by a-shvedov** [comment]
> 
> 
> Thank you for clarifying. I think some of this might be specific to the error level evoked. If this is normal operation, then perhaps it is INFO, not WARNING. When I see a warning, I assume I need to do something about it. I suspect this is similar for other people

Support the proposal. This message is a false positive, which confuses.

**Comment by swissarmybox** [comment]
Same issue, please fix.

**Comment by vicentemangas** [comment]
Will we see this in the next version of Chia fixed to INFO? Cheers
