### ISSUE TITLE
[BUG]cannot sync while delete sqlite and add connections

### ISSUE THREAD

**Issue by evanslight** [Chia-Network/chia-blockchain#3706]
**Describe the bug**
Not Sync for one day. I tried to delete "~\.chia\mainnet\db\peer_table_node.sqlite." on Windows and restart the app and add connections like node.chia.net 8444 and chiadb.net 8444 but the wallet keep stuck. When I check the debug log. it shows:

2021-05-05T00:50:15.453 full_node full_node_server        : ERROR    Exception:  <class 'concurrent.futures._base.CancelledError'>, closing connection {'host': '2406:da14:5ed:ad24:dac3:3216:b510:8b67', 'port': 8444}. Traceback (most recent call last):
  File "chia\server\server.py", line 531, in api_call
  File "asyncio\tasks.py", line 435, in wait_for
concurrent.futures._base.CancelledError

**Screenshots**
![图片](https://user-images.githubusercontent.com/11497640/117042981-39406b00-ad3f-11eb-98bd-88bef4cc3c05.png)

![图片](https://user-images.githubusercontent.com/11497640/117042808-04341880-ad3f-11eb-8785-500e066bde2f.png)
![图片](https://user-images.githubusercontent.com/11497640/117043277-963c2100-ad3f-11eb-8a34-6cd3ade6a8ab.png)

**Desktop (please complete the following information):**

- OS: Windows
- OS Version/Flavor: 10
- CPU: 5800x
- chia wallet version: 1.1.3

**Comment by evanslight** [comment]
I wait a couple of hours. it suddenly works.
