### ISSUE TITLE
Error starting CHIA on Ubuntu 18.04 

### ISSUE THREAD

**Issue by iEddie-cmd** [Chia-Network/chia-blockchain#3709]
When I hit chia start all on ubuntu 18.04 I first get: 
Daemon not started yet
Starting daemon
chia_harvester: started
chia_timelord_launcher: started
chia_timelord: started
chia_farmer: started
chia_full_node: started
chia_wallet: started

Then:
(venv) eddie@ubuntubase:~/chia-blockchain$ Traceback (most recent call last):
  File "/home/eddie/chia-blockchain/venv/bin/chia_timelord_launcher", line 33, in <module>
    sys.exit(load_entry_point('chia-blockchain', 'console_scripts', 'chia_timelord_launcher')())
  File "/home/eddie/chia-blockchain/chia/timelord/timelord_launcher.py", line 107, in main
    loop.run_until_complete(spawn_all_processes(config, net_config))
  File "/usr/lib/python3.7/asyncio/base_events.py", line 579, in run_until_complete
    return future.result()
  File "/home/eddie/chia-blockchain/chia/timelord/timelord_launcher.py", line 85, in spawn_all_processes
    await asyncio.gather(*awaitables)
  File "/home/eddie/chia-blockchain/chia/timelord/timelord_launcher.py", line 45, in spawn_process
    path_to_vdf_client = find_vdf_client()
  File "/home/eddie/chia-blockchain/chia/timelord/timelord_launcher.py", line 39, in find_vdf_client
    raise FileNotFoundError("can't find vdf_client binary")
FileNotFoundError: can't find vdf_client binary
Traceback (most recent call last):
  File "/home/eddie/chia-blockchain/venv/bin/chia_wallet", line 33, in <module>
    sys.exit(load_entry_point('chia-blockchain', 'console_scripts', 'chia_wallet')())
  File "/home/eddie/chia-blockchain/chia/server/start_wallet.py", line 92, in main
    return run_service(**kwargs)
  File "/home/eddie/chia-blockchain/chia/server/start_service.py", line 218, in run_service
    return asyncio.run(async_run_service(*args, **kwargs))
  File "/usr/lib/python3.7/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.7/asyncio/base_events.py", line 579, in run_until_complete
    return future.result()
  File "/home/eddie/chia-blockchain/chia/server/start_service.py", line 212, in async_run_service
    return await service.run()
  File "/home/eddie/chia-blockchain/chia/server/start_service.py", line 156, in run
    await self.start()
  File "/home/eddie/chia-blockchain/chia/server/start_service.py", line 127, in start
    await self._node._start(**kwargs)
  File "/home/eddie/chia-blockchain/chia/wallet/wallet_node.py", line 152, in _start
    private_key, self.config, path, self.constants, self.server
  File "/home/eddie/chia-blockchain/chia/wallet/wallet_state_manager.py", line 143, in create
    self.lock,
  File "/home/eddie/chia-blockchain/chia/wallet/wallet_blockchain.py", line 106, in create
    await self._load_chain_from_store()
  File "/home/eddie/chia-blockchain/chia/wallet/wallet_blockchain.py", line 117, in _load_chain_from_store
    height_to_hash, sub_epoch_summaries = await self.block_store.get_peak_heights_dicts()
  File "/home/eddie/chia-blockchain/chia/wallet/wallet_block_store.py", line 283, in get_peak_heights_dicts
    curr_height = hash_to_height[curr_header_hash]
KeyError: b'9S\x12!\xa8_g\xb9\xf0\xa2`\xbf\xad!\xd7\xe4\xa1\x9c\xcbo\xf4\xa7\r\xc8\xfa\xcd>v4\x1a//'

No Ideas whats wrong.

**Comment by lvcivs** [comment]
the command `chia start all` will start everything, including a timelord. That's an advanced use case that you most likely don't want to do. Use `chia start farmer` instead.

**Comment by jh7383** [comment]
Hello,
Same error on Ubuntu 20.04.
`chia start all` resolve anything

**Comment by DonielMoins** [comment]
Same problem here, would rather not delete wallet db file

**Comment by McTonderski** [comment]
same thing ubuntu 20.04 reinstall doesn't help

**Comment by krowll** [comment]
Same Issue with 21.04 and 20.04
#4268

**Comment by barneyjackson** [comment]
Same error for me, though it worked for 2 days totally fine.

ubuntu server 20.04
5.4.0-73-generic kernel
chia 1.1.5

**Comment by nzkozar** [comment]
Same error for me on Ubuntu desktop 20.04. chia 1.1.6
It started happening today after I had a power outage during plotting.

I've isolated the issue to starting the wallet, as it also appears when running `chia start wallet`

Any help would be awesome.

**Comment by nzkozar** [comment]
> Same error for me on Ubuntu desktop 20.04. chia 1.1.6
> It started happening today after I had a power outage during plotting.
> 
> I've isolated the issue to starting the wallet, as it also appears when running `chia start wallet`
> 
> Any help would be awesome.

**Update:** I just solved this by deleting everything in `.chia/mainnet/wallet/db/` folder

After this, the wallet started up again no problem
