### ISSUE TITLE
[BUG] RuntimeWarning: Enable tracemalloc to get the object allocation traceback

### ISSUE THREAD

**Issue by toconspiracy** [Chia-Network/chia-blockchain#3782]
**Describe the bug**
I have running a Chia node in Docker with 2GB memory allocated. Once it is reached i get following error and need to restart the container:

```
Process ForkProcess-6:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.8/concurrent/futures/process.py", line 233, in _process_worker
    call_item = call_queue.get(block=True)
  File "/usr/lib/python3.8/multiprocessing/queues.py", line 96, in get
    with self._rlock:
  File "/usr/lib/python3.8/multiprocessing/synchronize.py", line 95, in __enter__
    return self._semlock.__enter__()
  File "/chia-blockchain/chia/server/start_service.py", line 168, in _accept_signal
    self.stop()
  File "/chia-blockchain/chia/server/start_service.py", line 177, in stop
    self._server.close_all()
  File "/chia-blockchain/chia/server/server.py", line 624, in close_all
    self.connection_close_task = asyncio.create_task(self.close_all_connections())
  File "/usr/lib/python3.8/asyncio/tasks.py", line 381, in create_task
    loop = events.get_running_loop()
RuntimeError: no running event loop
/usr/lib/python3.8/multiprocessing/process.py:331: RuntimeWarning: coroutine 'ChiaServer.close_all_connections' was never awaited
  traceback.print_exc()
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
Process ForkProcess-3:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.8/concurrent/futures/process.py", line 233, in _process_worker
    call_item = call_queue.get(block=True)
  File "/usr/lib/python3.8/multiprocessing/queues.py", line 96, in get
    with self._rlock:
  File "/usr/lib/python3.8/multiprocessing/synchronize.py", line 95, in __enter__
    return self._semlock.__enter__()
  File "/chia-blockchain/chia/server/start_service.py", line 168, in _accept_signal
    self.stop()
  File "/chia-blockchain/chia/server/start_service.py", line 177, in stop
    self._server.close_all()
  File "/chia-blockchain/chia/server/server.py", line 624, in close_all
    self.connection_close_task = asyncio.create_task(self.close_all_connections())
  File "/usr/lib/python3.8/asyncio/tasks.py", line 381, in create_task
    loop = events.get_running_loop()
RuntimeError: no running event loop
/usr/lib/python3.8/multiprocessing/process.py:331: RuntimeWarning: coroutine 'ChiaServer.close_all_connections' was never awaited
  traceback.print_exc()
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
Process ForkProcess-2:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.8/concurrent/futures/process.py", line 233, in _process_worker
    call_item = call_queue.get(block=True)
  File "/usr/lib/python3.8/multiprocessing/queues.py", line 96, in get
    with self._rlock:
  File "/usr/lib/python3.8/multiprocessing/synchronize.py", line 95, in __enter__
    return self._semlock.__enter__()
  File "/chia-blockchain/chia/server/start_service.py", line 168, in _accept_signal
    self.stop()
  File "/chia-blockchain/chia/server/start_service.py", line 177, in stop
    self._server.close_all()
  File "/chia-blockchain/chia/server/server.py", line 624, in close_all
    self.connection_close_task = asyncio.create_task(self.close_all_connections())
  File "/usr/lib/python3.8/asyncio/tasks.py", line 381, in create_task
    loop = events.get_running_loop()
RuntimeError: no running event loop
/usr/lib/python3.8/multiprocessing/process.py:331: RuntimeWarning: coroutine 'ChiaServer.close_all_connections' was never awaited
  traceback.print_exc()
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
Process ForkProcess-7:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.8/concurrent/futures/process.py", line 233, in _process_worker
    call_item = call_queue.get(block=True)
  File "/usr/lib/python3.8/multiprocessing/queues.py", line 97, in get
    res = self._recv_bytes()
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 216, in recv_bytes
    buf = self._recv_bytes(maxlength)
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 414, in _recv_bytes
    buf = self._recv(4)
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 379, in _recv
    chunk = read(handle, remaining)
  File "/chia-blockchain/chia/server/start_service.py", line 168, in _accept_signal
    self.stop()
  File "/chia-blockchain/chia/server/start_service.py", line 177, in stop
    self._server.close_all()
  File "/chia-blockchain/chia/server/server.py", line 624, in close_all
    self.connection_close_task = asyncio.create_task(self.close_all_connections())
  File "/usr/lib/python3.8/asyncio/tasks.py", line 381, in create_task
    loop = events.get_running_loop()
RuntimeError: no running event loop
/usr/lib/python3.8/multiprocessing/process.py:331: RuntimeWarning: coroutine 'ChiaServer.close_all_connections' was never awaited
  traceback.print_exc()
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
/chia-blockchain/chia/full_node/mempool_check_conditions.py:170: RuntimeWarning: coroutine 'ChiaServer.close_all_connections' was never awaited
  return NPCResult(uint16(Err.GENERATOR_RUNTIME_ERROR.value), [], uint64(0))
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
```

**Comment by toconspiracy** [comment]
I have now added 2 GB Memory to the Container (now in total 4), and it seems to be fine now. It looks like it always uses a bit more than 2GB so I was on the edge, I think 3 GB would be enough.
