### ISSUE TITLE
[BUG]got this error while making a plot

### ISSUE THREAD

**Issue by dantdmlol54** [Chia-Network/chia-blockchain#3805]
**Describe the bug**

Starting plotting progress into temporary dirs: C:\ and C:\
ID: f921df4566f556648871ee047640fe12da1ddb54525ff0879662b6a66770617f
Plot size is: 32
Buffer size is: 3390MiB
Using 128 buckets
Using 2 threads of stripe size 65536
Caught plotting error: Could not open C:\plot-k32-2021-05-05-19-33-f921df4566f556648871ee047640fe12da1ddb54525ff0879662b6a66770617f.plot.sort.tmp: Permission denied.
[32108] Failed to execute script chia
Traceback (most recent call last):
  File "chia\cmds\chia.py", line 81, in <module>
  File "chia\cmds\chia.py", line 77, in main
  File "click\core.py", line 829, in __call__
  File "click\core.py", line 782, in main
  File "click\core.py", line 1259, in invoke
  File "click\core.py", line 1259, in invoke
  File "click\core.py", line 1066, in invoke
  File "click\core.py", line 610, in invoke
  File "click\decorators.py", line 21, in new_func
  File "chia\cmds\plots.py", line 135, in create_cmd
  File "chia\plotting\create_plots.py", line 176, in create_plots
RuntimeError: Unknown exception
**To Reproduce**

i just made a new plot and this error pops up

**Expected behavior**
![image_2021-05-05_194841](https://user-images.githubusercontent.com/58716421/117136397-e5835f80-adda-11eb-96bd-762bfdde52f5.png)

**Screenshots**

**Desktop (please complete the following information):**

- OS: windows
- OS Version/Flavor: windows 10 Pro
- CPU: Ryzen 5 3500x 6-core processor

**Additional context**

**Comment by Plopsi** [comment]
try not to put the temp directly on C: but in a subfolder
