### ISSUE TITLE
[BUG] WARNING Wasn't able to add transaction

### ISSUE THREAD

**Issue by majekqwert** [Chia-Network/chia-blockchain#3815]
After upadte do 1.1.4 i get a lot of:

2021-05-05T14:25:59.010 full_node chia.full_node.full_node: WARNING  Wasn't able to add transaction with id 71f6985e402f0fa0f32fa9b73f90c59e44ee1dfae29cd666b1c6573f5d4d71c1, status 3 error: Err.DOUBLE_SPEND
2021-05-05T14:33:30.432 full_node chia.full_node.full_node: WARNING  Wasn't able to add transaction with id 03cf27dd945b61244a8a98d56c5c453629e04cc0ec99de82f059879567e265cc, status 3 error: Err.DOUBLE_SPEND
2021-05-05T14:33:53.448 full_node chia.full_node.full_node: WARNING  Wasn't able to add transaction with id 7960666207398cf44aeb2252f19c740795f2a4e2ba122e44b42000ca9b0e6e99, status 3 error: Err.DOUBLE_SPEND
2021-05-05T14:33:53.448 full_node chia.full_node.full_node: WARNING  Wasn't able to add transaction with id 8a185ee4a57d4cbe0cf84b61dbfcc8141995b711370e9af0c34ec3c5da48074a, status 3 error: Err.DOUBLE_SPEND
2021-05-05T14:33:53.464 full_node chia.full_node.full_node: WARNING  Wasn't able to add transaction with id da844c728254a471cc9bb8f7eb6b7413ac5a15db45193c80d7b85056452f9922, status 3 error: Err.DOUBLE_SPEND
2021-05-05T14:34:24.588 full_node chia.full_node.full_node: WARNING  Wasn't able to add transaction with id 53841870949307f24d3e2c656c6c5d7330bff2eeb7c424351abbbf9a24aa0b57, status 3 error: Err.DOUBLE_SPEND
2021-05-05T14:35:10.260 full_node chia.full_node.full_node: WARNING  Wasn't able to add transaction with id ab1afaddc264433dd8a8dc47cd64ec7f9021c72392bb1c3ba680d4774ea12167, status 3 error: Err.DOUBLE_SPEND
2021-05-05T14:36:37.494 full_node chia.full_node.full_node: WARNING  Wasn't able to add transaction with id 09e45c5c924408bcc8351eb62680d5984d5ecf4de46d8b7cf22afea646c80116, status 3 error: Err.DOUBLE_SPEND
2021-05-05T14:36:37.494 full_node chia.full_node.full_node: WARNING  Wasn't able to add transaction with id 0bd05fdd471ef99f9f7b8d102bcc1f1c216f136a321383b5f3f9c5320e1e359e, status 3 error: Err.DOUBLE_SPEND
2021-05-05T14:36:37.995 full_node chia.full_node.full_node: WARNING  Wasn't able to add transaction with id cfb326d71b8e4b9cb24b9c3000dfbbc9a9e6a42dbef9a6f404ed290db7aa3ca6, status 3 error: Err.DOUBLE_SPEND
2021-05-05T14:37:31.557 full_node chia.full_node.full_node: WARNING  Wasn't able to add transaction with id fe6cd3a708ae14083226ff9d72e292e70db16509d67a1a849171142cdf0188a0, status 3 error: Err.DOUBLE_SPEND
2021-05-05T14:39:41.244 full_node chia.full_node.full_node: WARNING  Wasn't able to add transaction with id ab1afaddc264433dd8a8dc47cd64ec7f9021c72392bb1c3ba680d4774ea12167, status 3 error: Err.DOUBLE_SPEND
2021-05-05T14:39:41.292 full_node chia.full_node.full_node: WARNING  Wasn't able to add transaction with id ea57bdbda950b13f5bf5f7ef38b9d64f1f9d5fc63314b76181d5c69c0899037a, status 3 error: Err.DOUBLE_SPEND
2021-05-05T14:39:41.323 full_node chia.full_node.full_node: WARNING  Wasn't able to add transaction with id 09e45c5c924408bcc8351eb62680d5984d5ecf4de46d8b7cf22afea646c80116, status 3 error: Err.DOUBLE_SPEND
2021-05-05T14:39:41.416 full_node chia.full_node.full_node: WARNING  Wasn't able to add transaction with id 0bd05fdd471ef99f9f7b8d102bcc1f1c216f136a321383b5f3f9c5320e1e359e, status 3 error: Err.DOUBLE_SPEND
2021-05-05T14:39:45.909 full_node chia.full_node.full_node: WARNING  Wasn't able to add transaction with id ce3102ae8899559c17f003811c7b2c59c55b48fd1edfca146c942ba8036da83d, status 3 error: Err.DOUBLE_SPEND
2021-05-05T14:39:46.238 full_node chia.full_node.full_node: WARNING  Wasn't able to add transaction with id 8321350fa74988f4f6b3f0aae8b3bee11a1831032f5e4502bc72755d1443b1f3, status 3 error: Err.DOUBLE_SPEND
2021-05-05T14:39:46.262 full_node chia.full_node.full_node: WARNING  Wasn't able to add transaction with id 60b73376fdd77e75e1b0ce4877021d1dd1c595b744f4702f48e027ec449c646a, status 3 error: Err.DOUBLE_SPEND
2021-05-05T14:42:22.760 full_node chia.full_node.full_node: WARNING  Wasn't able to add transaction with id eb1a3098de7b5685620317ddaf2cfa3e6fae76d4800fa6c0d31c75c4cfd2fb75, status 3 error: Err.DOUBLE_SPEND
2021-05-05T14:50:26.701 full_node full_node_server        : WARNING  Banning 218.19.247.60 for 10 seconds
2021-05-05T14:50:26.702 full_node full_node_server        : WARNING  Invalid handshake with peer. Maybe the peer is running old software.
2021-05-05T14:53:09.635 full_node chia.full_node.full_node: WARNING  Wasn't able to add transaction with id 4c8cce1356b03b9ba66acdd6bf2ff68c1c701bce4b7d90acaf4cf69e7750c617, status 3 error: Err.DOUBLE_SPEND
2021-05-05T14:56:25.916 full_node chia.full_node.full_node: WARNING  Wasn't able to add transaction with id bb71dc892bd137f3537560acbf79268a8b274ac2b3cf582c2013ca028d489947, status 3 error: Err.DOUBLE_SPEND
2021-05-05T14:56:25.916 full_node chia.full_node.full_node: WARNING  Wasn't able to add transaction with id 51f33b89c2435f83e23a217f97f0c51e89547f227c23947e6768cd49e90d63cf, status 3 error: Err.DOUBLE_SPEND
2021-05-05T14:56:25.932 full_node chia.full_node.full_node: WARNING  Wasn't able to add transaction with id 9785e293341f66c1a047b29b080b85cfa6c996cabe538673212993c141730d7b, status 3 error: Err.DOUBLE_SPEND
2021-05-05T15:01:34.479 full_node chia.full_node.full_node: WARNING  Wasn't able to add transaction with id 2b87263ff57d2a875d1adc99c482d2b1534d9bb8326444e1a22b2c2d149a439e, status 3 error: Err.DOUBLE_SPEND
2021-05-05T15:01:34.479 full_node chia.full_node.full_node: WARNING  Wasn't able to add transaction with id 53052e8a87154f43a1eace1c8fe2262ab0d663cb7e2a1958716ffd0a61bec9aa, status 3 error: Err.DOUBLE_SPEND
2021-05-05T15:01:34.651 full_node chia.full_node.full_node: WARNING  Wasn't able to add transaction with id f5dfdc61de8617ea3c28357f76112e850c99b7d8ed51dabfe40f37d7400965f2, status 3 error: Err.DOUBLE_SPEND
2021-05-05T15:01:34.651 full_node chia.full_node.full_node: WARNING  Wasn't able to add transaction with id 10fa7ca9f223554152fed80639c9d4685b607f4ab9ec72c6ebe5080bc3630e5e, status 3 error: Err.DOUBLE_SPEND
2021-05-05T15:01:34.698 full_node chia.full_node.full_node: WARNING  Wasn't able to add transaction with id 11d5a14c73c0873a059a793e35d5bcf178bd9f443ae8980a48ff8f93c39e795a, status 3 error: Err.DOUBLE_SPEND
2021-05-05T15:01:34.698 full_node chia.full_node.full_node: WARNING  Wasn't able to add transaction with id ae65dda7166c04ccf1dcea05a2ab3c26ad2c22e5c0c17f6fefc2a5d5abd0d9e9, status 3 error: Err.DOUBLE_SPEND
2021-05-05T15:01:34.698 full_node chia.full_node.full_node: WARNING  Wasn't able to add transaction with id 7f6ec0a9e1989f9330f9811d07d996e2dff64d1bf14ca10e13cde9816d966d49, status 3 error: Err.DOUBLE_SPEND
2021-05-05T15:03:25.291 full_node chia.full_node.full_node: WARNING  Wasn't able to add transaction with id 7e11dc1d0de7503062db9e46c807149d71ed1ead218c6388d32046c75ab8a2b7, status 3 error: Err.DOUBLE_SPEND
2021-05-05T15:09:52.913 full_node chia.full_node.full_node: WARNING  Wasn't able to add transaction with id 14ab7e65ff227b83a07e8946956a2c2b37c120796b735e61e3dcb1dc5a1a7f1b, status 3 error: Err.DOUBLE_SPEND
2021-05-05T15:09:55.756 full_node chia.full_node.full_node: WARNING  Wasn't able to add transaction with id 79954fdc4708bcd59dfb3e4e9be1e0dc3c3f9d9259811836beb947bda8d31c22, status 3 error: Err.DOUBLE_SPEND
2021-05-05T15:09:55.757 full_node chia.full_node.full_node: WARNING  Wasn't able to add transaction with id cb626578c20527fdf1535a31cf13fde0e530ffeae2740c257c40760b8d38d4f4, status 3 error: Err.DOUBLE_SPEND
2021-05-05T15:09:55.758 full_node chia.full_node.full_node: WARNING  Wasn't able to add transaction with id 3edfaf81ad629a30aff1446c467d2d1746b75305bf19a9dc4218de33988bbdc2, status 3 error: Err.DOUBLE_SPEND
2021-05-05T15:09:55.758 full_node chia.full_node.full_node: WARNING  Wasn't able to add transaction with id e8b29a0ee90c405faccd0771d1e062d7b3313381169bc9876091970851f17935, status 3 error: Err.DOUBLE_SPEND
2021-05-05T15:09:55.759 full_node chia.full_node.full_node: WARNING  Wasn't able to add transaction with id bb3707586bb5809dafd370dbe6a025bf4a8196f2d0b25381a95e01f8ed1c530b, status 3 error: Err.DOUBLE_SPEND
2021-05-05T15:09:55.760 full_node chia.full_node.full_node: WARNING  Wasn't able to add transaction with id ee314274309ed9a262c49849e6af002804bca0e42014479cbe68368653f3185d, status 3 error: Err.DOUBLE_SPEND
2021-05-05T15:09:55.761 full_node chia.full_node.full_node: WARNING  Wasn't able to add transaction with id 9bf536c1b8fb5d67be0ecc96a18555fb8571a01497e6b145eadc5835cc91c993, status 3 error: Err.DOUBLE_SPEND
2021-05-05T15:09:55.761 full_node chia.full_node.full_node: WARNING  Wasn't able to add transaction with id df7ced16b09537900bf09aff6ac6a707b11cfe9c0de5812ba3afe46ec6f190c9, status 3 error: Err.DOUBLE_SPEND
2021-05-05T15:09:55.762 full_node chia.full_node.full_node: WARNING  Wasn't able to add transaction with id 791f1ab037e0b42aac68a08311709be095a87d5e100177ed7432467e6e8da1f1, status 3 error: Err.DOUBLE_SPEND
2021-05-05T15:15:33.176 full_node chia.full_node.full_node: WARNING  Wasn't able to add transaction with id dc94901ac60135263664e0e1f39d1ef3bc1c0e78c97595c743d628fabbd99f9c, status 3 error: Err.DOUBLE_SPEND
2021-05-05T15:15:33.208 full_node chia.full_node.full_node: WARNING  Wasn't able to add transaction with id faa5f000992bee9b04dfcde281f464a8cb967349faa451516b445fcf2cdaed51, status 3 error: Err.DOUBLE_SPEND
2021-05-05T15:15:33.324 full_node chia.full_node.full_node: WARNING  Wasn't able to add transaction with id c55d73b309a9b411640ff3bc936ec33f7d8f15479b8ba09c022a950c30617c72, status 3 error: Err.DOUBLE_SPEND
2021-05-05T15:15:33.558 full_node chia.full_node.full_node: WARNING  Wasn't able to add transaction with id 03ffcf01bd3493bc8d032e21a0a847ea0e335ffbe02f034d88aff4e538234ee0, status 3 error: Err.DOUBLE_SPEND
2021-05-05T15:15:33.682 full_node chia.full_node.full_node: WARNING  Wasn't able to add transaction with id 7d86e0aa62f56f962c3f1ff85661fb84889215c1292731a1ac73fd6af817975e, status 3 error: Err.DOUBLE_SPEND
2021-05-05T15:15:34.741 full_node chia.full_node.full_node: WARNING  Wasn't able to add transaction with id c1c055f2ff9c6cf4be85d8ded06e23a81e48ed8d2261f44ffcc7d00bcb21da18, status 3 error: Err.DOUBLE_SPEND
2021-05-05T15:17:40.695 full_node chia.full_node.full_node: WARNING  Wasn't able to add transaction with id c0431cc774ecd3beccdbdc52916d3ce9109c22f01c91fb09823f35880c554f0c, status 3 error: Err.DOUBLE_SPEND
2021-05-05T15:22:24.291 full_node chia.full_node.full_node: WARNING  Wasn't able to add transaction with id eac5ae31a4c92ae05f079e34a13fe0b58e03565f9c19bf5a93f017b135fe7bb9, status 3 error: Err.DOUBLE_SPEND
2021-05-05T15:22:24.573 full_node chia.full_node.full_node: WARNING  Wasn't able to add transaction with id 11348fbd41fd5d1c976da020db905f7681de9dfb19c1cf67ac6288d050e697e6, status 3 error: Err.DOUBLE_SPEND
2021-05-05T15:22:24.604 full_node chia.full_node.full_node: WARNING  Wasn't able to add transaction with id 22a0c2947d9b75acf6bc1092f38a57a44b71c40bc038ef1fb139e859f66f0d92, status 3 error: Err.DOUBLE_SPEND
2021-05-05T15:22:24.729 full_node chia.full_node.full_node: WARNING  Wasn't able to add transaction with id 20fdad9b0cf3c9a40fa5b4ff29540b43342ecb962f351c5a61dffb642c70237d, status 3 error: Err.DOUBLE_SPEND
2021-05-05T15:22:24.870 full_node chia.full_node.full_node: WARNING  Wasn't able to add transaction with id cbaef9b1276d37f9d5dd81eb443e205fe59525bc233b439d6016e29c717b3251, status 3 error: Err.DOUBLE_SPEND
2021-05-05T15:22:24.932 full_node chia.full_node.full_node: WARNING  Wasn't able to add transaction with id f482633ef482738136968d055a1ff3864c97b287888d4ac871d9ef008d89200e, status 3 error: Err.DOUBLE_SPEND
2021-05-05T15:22:24.979 full_node chia.full_node.full_node: WARNING  Wasn't able to add transaction with id 83684d3f0b82d10d2220586c995c24481a2301bcfad5e71ce3aa107f483d6bed, status 3 error: Err.DOUBLE_SPEND
2021-05-05T15:22:25.010 full_node chia.full_node.full_node: WARNING  Wasn't able to add transaction with id 6bbdad26a43ffa249db804e89ee01cda6e150e890472cb948ccff27ef49da46d, status 3 error: Err.DOUBLE_SPEND
2021-05-05T15:22:54.384 full_node chia.full_node.full_node: WARNING  Wasn't able to add transaction with id aa42efc8deb90978fb7cc1b88a752c4c53c2f19a61ec5fcf4ab39e8bdcee3901, status 3 error: Err.DOUBLE_SPEND
2021-05-05T15:23:03.681 full_node full_node_server        : WARNING  Banning 116.208.218.178 for 10 seconds
2021-05-05T15:23:03.682 full_node full_node_server        : WARNING  Invalid handshake with peer. Maybe the peer is running old software.
2021-05-05T15:23:12.713 full_node chia.full_node.full_node: WARNING  Wasn't able to add transaction with id aa42efc8deb90978fb7cc1b88a752c4c53c2f19a61ec5fcf4ab39e8bdcee3901, status 3 error: Err.DOUBLE_SPEND
2021-05-05T15:24:21.442 full_node chia.full_node.full_node: WARNING  Wasn't able to add transaction with id dc38c177e69740a62bb3012b808a5c946224132eca0a21eefabe5bc6d06e8f4d, status 3 error: Err.DOUBLE_SPEND
2021-05-05T15:24:21.479 full_node chia.full_node.full_node: WARNING  Wasn't able to add transaction with id ac679acd102ec48120d794c06958c667fd92cf6ced68ea6bab9fad33fd128d22, status 3 error: Err.DOUBLE_SPEND
2021-05-05T15:24:21.537 full_node chia.full_node.full_node: WARNING  Wasn't able to add transaction with id 9d4830c46cbafb18f1e81dcc051a671d47a00adcfb851570796e2ead7f630605, status 3 error: Err.DOUBLE_SPEND
2021-05-05T15:24:21.581 full_node chia.full_node.full_node: WARNING  Wasn't able to add transaction with id ae405f002e0c0cda0c721f19207fed4e719d653bdf1b83cc19dce3ccf1e5584f, status 3 error: Err.DOUBLE_SPEND
2021-05-05T15:24:27.822 full_node chia.full_node.full_node: WARNING  Wasn't able to add transaction with id 66c25319ff73e8be4548eb3e89011c6f639ce665408367b120889e582d53239f, status 3 error: Err.DOUBLE_SPEND
2021-05-05T15:24:59.541 full_node chia.full_node.full_node: WARNING  Wasn't able to add transaction with id 68b48db19904ea797446ad852958760b80d462fbdb5ed4bcd8d62975bfa536d1, status 3 error: Err.DOUBLE_SPEND
2021-05-05T15:24:59.541 full_node chia.full_node.full_node: WARNING  Wasn't able to add transaction with id 2c95cc2c96c8a877ca920b4106369321af708e5b5855e3bb40c3c1bd755e2a3a, status 3 error: Err.DOUBLE_SPEND
2021-05-05T15:24:59.745 full_node chia.full_node.full_node: WARNING  Wasn't able to add transaction with id cfc33a43a64e2072d4aa4738050af60f118109c3f44e26861c1b53db5e002a4a, status 3 error: Err.DOUBLE_SPEND
2021-05-05T15:24:59.776 full_node chia.full_node.full_node: WARNING  Wasn't able to add transaction with id 64cf72205d26bcc98dbe052324dad4ef08b38c99b055f772d5becf57b5f44cb5, status 3 error: Err.DOUBLE_SPEND
2021-05-05T15:24:59.791 full_node chia.full_node.full_node: WARNING  Wasn't able to add transaction with id 999ec611fc20f7a3b73c8bd61123c813ec8c2a962f6c19c6d67b3c30b205ef2c, status 3 error: Err.DOUBLE_SPEND
2021-05-05T15:24:59.791 full_node chia.full_node.full_node: WARNING  Wasn't able to add transaction with id 27ce24a571e8e9bc2cf86cb98eae1716f178902f200af3470bc28d4057d547cb, status 3 error: Err.DOUBLE_SPEND
2021-05-05T15:24:59.807 full_node chia.full_node.full_node: WARNING  Wasn't able to add transaction with id b8835bf1a51b7f22115f8aecf39aa1073bbb0141b1a11fd5dfdf6ce306aba5c9, status 3 error: Err.DOUBLE_SPEND
2021-05-05T15:25:28.398 full_node full_node_server        : WARNING  Banning 27.18.59.166 for 10 seconds
2021-05-05T15:25:28.398 full_node full_node_server        : WARNING  Invalid handshake with peer. Maybe the peer is running old software.
2021-05-05T15:28:09.760 full_node full_node_server        : ERROR    Exception:  <class 'concurrent.futures._base.CancelledError'>, closing connection None. Traceback (most recent call last):
  File "chia\server\server.py", line 531, in api_call
  File "asyncio\tasks.py", line 435, in wait_for
concurrent.futures._base.CancelledError

2021-05-05T15:28:18.494 full_node chia.full_node.full_node: WARNING  Wasn't able to add transaction with id 0307d4532746b82c7d544aee22c46dfcb28dcbe3a4ebfea72481f6f1ab2ae88d, status 3 error: Err.DOUBLE_SPEND
2021-05-05T15:28:18.541 full_node chia.full_node.full_node: WARNING  Wasn't able to add transaction with id 90a98ced7d61c96a5b7383b7e00c5d749baf4fccf236f7bd252d4e4d7e6efea9, status 3 error: Err.DOUBLE_SPEND
2021-05-05T15:29:16.932 full_node chia.full_node.full_node: WARNING  Wasn't able to add transaction with id d01134d18c03f37f0734f8dd6136996d24eb6f70a90b3e368e8b8d6f88070531, status 3 error: Err.DOUBLE_SPEND
2021-05-05T15:29:17.073 full_node chia.full_node.full_node: WARNING  Wasn't able to add transaction with id 6e63f5a7241e0692f749fd576734199058195aedbcdb86f3cc03c4bf50f8907e, status 3 error: Err.DOUBLE_SPEND
2021-05-05T15:29:17.135 full_node chia.full_node.full_node: WARNING  Wasn't able to add transaction with id 62a43d0bfa2094d61392785b864715ad4406983f8f1a3ef19eae99bbb264c9aa, status 3 error: Err.DOUBLE_SPEND
2021-05-05T15:29:17.229 full_node chia.full_node.full_node: WARNING  Wasn't able to add transaction with id 9ce1d9d09216838eea8c78e6d4a7d890f3e94f128666cb918581acb37d221906, status 3 error: Err.DOUBLE_SPEND
2021-05-05T15:29:17.260 full_node chia.full_node.full_node: WARNING  Wasn't able to add transaction with id 2b2c7ce147879ae1a96c6848b31b7e89fb4662e38b24ed9a5e32928363b81534, status 3 error: Err.DOUBLE_SPEND
2021-05-05T15:29:17.432 full_node chia.full_node.full_node: WARNING  Wasn't able to add transaction with id 749a7134845375bfef838bad807390a1aa0658ec473e45c815d9f23535751dfb, status 3 error: Err.DOUBLE_SPEND
2021-05-05T15:29:17.526 full_node chia.full_node.full_node: WARNING  Wasn't able to add transaction with id ab9906a87c22218d963a14047fc086d3af4999df963ce0814563c895a3086b5e, status 3 error: Err.DOUBLE_SPEND
2021-05-05T15:29:17.776 full_node chia.full_node.full_node: WARNING  Wasn't able to add transaction with id 183cf04f0db0dfe12c43501fe9eebd622a4e0afa82c76b7ed489fc15c13c3434, status 3 error: Err.DOUBLE_SPEND
2021-05-05T15:29:17.885 full_node chia.full_node.full_node: WARNING  Wasn't able to add transaction with id cad4041329d3104afe1e3e79489cf21811d14283848637aa1dbd13728c459ac3, status 3 error: Err.DOUBLE_SPEND
2021-05-05T15:31:36.323 full_node chia.full_node.full_node: WARNING  Wasn't able to add transaction with id 313bfba635e17ab491ba4cbf57174fd45aca48d0532503647c4996dec4e392c9, status 3 error: Err.DOUBLE_SPEND
2021-05-05T15:31:36.557 full_node chia.full_node.full_node: WARNING  Wasn't able to add transaction with id 8de99a16c8cdc9566dbff4e9d932334d0d91aef7b93f58702bf9f77fd4e5e33b, status 3 error: Err.DOUBLE_SPEND
2021-05-05T15:31:36.823 full_node chia.full_node.full_node: WARNING  Wasn't able to add transaction with id 2495821ed980fa9951d0dde8cda49be4a8cda06aacd177a3a9a3cdc386897134, status 3 error: Err.DOUBLE_SPEND
2021-05-05T15:32:46.245 full_node chia.full_node.full_node: WARNING  Wasn't able to add transaction with id 06e8672df880a5afa46c3c6895101ded60f9cd7de3a5c36699d5689496be80fd, status 3 error: Err.DOUBLE_SPEND
2021-05-05T15:33:30.791 full_node chia.full_node.full_node: WARNING  Wasn't able to add transaction with id 3a5be4d39a6bb34c434b823540976cb464781be09cc1a650d4c0a307b42ecd89, status 3 error: Err.DOUBLE_SPEND
2021-05-05T15:36:19.416 full_node full_node_server        : WARNING  Banning 27.18.59.166 for 10 seconds
2021-05-05T15:36:19.416 full_node full_node_server        : WARNING  Invalid handshake with peer. Maybe the peer is running old software.
2021-05-05T15:38:03.776 full_node chia.full_node.full_node: WARNING  Wasn't able to add transaction with id 892dc70e958a7347ba88e88ba30ffed22640766e82cf94e643643d7bce9e7c04, status 3 error: Err.DOUBLE_SPEND
2021-05-05T15:38:05.332 full_node chia.full_node.full_node: WARNING  Wasn't able to add transaction with id 8cf60c1f26c3fee4c02a98017a6a6e50119bd6c9ea11bed4d7b8c98e17449443, status 3 error: Err.DOUBLE_SPEND
2021-05-05T15:41:22.916 full_node chia.full_node.full_node: WARNING  Wasn't able to add transaction with id 68ff8f0398cb5f4206b023279e21fcd0528898d714abf7fd4de630a4f65859ce, status 3 error: Err.DOUBLE_SPEND
2021-05-05T15:41:22.963 full_node chia.full_node.full_node: WARNING  Wasn't able to add transaction with id 2c215bdad11834d34d3ef0fcdc429cb31d0586891a3ba963b6325d8aa8575b5c, status 3 error: Err.DOUBLE_SPEND
2021-05-05T15:41:22.994 full_node chia.full_node.full_node: WARNING  Wasn't able to add transaction with id fd4c039da66ee6d6c32baeb82190d2915b5b4b587aa34fb9d92a9e32a1f5fa9d, status 3 error: Err.DOUBLE_SPEND

**Comment by djdookie** [comment]
Duplicate https://github.com/Chia-Network/chia-blockchain/issues/3696
Please search issues before posting new ones! ;)

**Comment by mariano54** [comment]
This is fine
