### ISSUE TITLE
[BUG} Sync is static

### ISSUE THREAD

**Issue by Bossnut** [Chia-Network/chia-blockchain#3823]
Was running version 1.1.1 when I had to shut down the PC.

On restart Sync would not happen - always connected but no sync. 

Updated to 1.1.4 and still the same issue, always connects, attempts to sync, sometimes with no sync improvement then goes red and "not Synced" and the cycle continues. 

Still plotting fine.

Windows 10 PC

**Comment by Malejosanchez88** [comment]
I have the same problem!  :(

**Comment by mfrancekovic** [comment]
I have the same problem, also this error appears in the logs.


2021-05-06T09:49:18.814 full_node full_node_server        : ERROR    Exception:  <class 'concurrent.futures._base.CancelledError'>, closing connection {'host': '<IP HERE>', 'port': 8444}. Traceback (most recent call last):
  File "chia\server\server.py", line 531, in api_call
  File "asyncio\tasks.py", line 435, in wait_for
concurrent.futures._base.CancelledError

**Comment by Bossnut** [comment]
> I have the same problem, also this error appears in the logs.
> 
> 2021-05-06T09:49:18.814 full_node full_node_server : ERROR Exception: <class 'concurrent.futures._base.CancelledError'>, closing connection {'host': '', 'port': 8444}. Traceback (most recent call last):
> File "chia\server\server.py", line 531, in api_call
> File "asyncio\tasks.py", line 435, in wait_for
> concurrent.futures._base.CancelledError

Where do I find the logs @mfrancekovic ?

**Comment by mfrancekovic** [comment]
For me it's under: `C:\Users\<my username>\.chia\mainnet\logs`.

**Comment by Bossnut** [comment]
> For me it's under: `C:\Users\<my username>\.chia\mainnet\logs`.

Thank you (same for me)... I have hundreds of lines of lines like this:
2021-05-06T04:25:00.075 full_node full_node_server        : WARNING  Banning xxx.xxx.74.197 for 600 seconds
2021-05-06T04:25:00.076 full_node chia.full_node.full_node: ERROR    Error with syncing: <class 'RuntimeError'>Traceback (most recent call last):
  File "chia\full_node\full_node.py", line 628, in _sync
RuntimeError: Weight proof did not arrive in time from peer: xxx.xxx.74.197

**Comment by mfrancekovic** [comment]
@Bossnut I've figured out now what's bothering me. The thing was that I had 2 machines, one PC and one Mac, running Chia GUI on the same router. It seems that caused the problem. Now that I've killed the mac and restarted the router, things started working.
