### ISSUE TITLE
[BUG] Harvester keeps closed

### ISSUE THREAD

**Issue by gigauser7** [Chia-Network/chia-blockchain#3843]
**Describe the bug**
harvester keeps closed
**To Reproduce**

1. Run wallet on Ubuntu on a computer in my room
2. Run harvester on Windows10 on the other computer connected with the router in the same room
3. After several minutes the harvester closed like this and I have to restart it again and again :
2021-05-05T23:15:18.367 daemon chia.daemon.server         : INFO     Websocket exception. Closing websocket with chia_harvester code = 1006 (connection closed abnormally [internal]), no reason Traceback (most recent call last):
  File "websockets\protocol.py", line 827, in transfer_data
  File "websockets\protocol.py", line 895, in read_message
  File "websockets\protocol.py", line 971, in read_data_frame
  File "websockets\protocol.py", line 1051, in read_frame
  File "websockets\framing.py", line 105, in read
  File "asyncio\streams.py", line 679, in readexactly
  File "asyncio\streams.py", line 473, in _wait_for_data
  File "asyncio\selector_events.py", line 814, in _read_ready__data_received
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "chia\daemon\server.py", line 172, in safe_handle
  File "websockets\protocol.py", line 439, in __aiter__
  File "websockets\protocol.py", line 509, in recv
  File "websockets\protocol.py", line 803, in ensure_open
websockets.exceptions.ConnectionClosedError: code = 1006 (connection closed abnormally [internal]), no reason

**Expected behavior**
keeps running well without closing.

**Desktop (please complete the following information):**

- OS: Wallet on Ubuntu 18.04, harvester on windows 10 2020H2
- CPU: intel G4600(Wallet computer), intel 11700(harvester)

**Comment by dnsgram** [comment]
How come this open for almost one month without any response from the team?

https://github.com/Chia-Network/chia-blockchain/issues/6047

**Comment by juggernog20** [comment]
Also getting this error on my harvester. All the correct ports are open so I am not sure why the full node computer would be terminating the connection
