### ISSUE TITLE
[BUG]I found these errors, and I don't know if my settings are correct.

### ISSUE THREAD

**Issue by lihat1992** [Chia-Network/chia-blockchain#3845]
[jack@localhost ~]$ cat ~/.chia/mainnet/log/debug.log | grep 'error'
    client_error=client_error,
    client_error=client_error,
2021-05-04T03:16:20.848 full_node chia.full_node.full_node: WARNING  Wasn't able to add transaction with id e67b938b9bbf2946f41549d9985fd122556e71fc6cc7187370d1e9335c84438e, status 2 error: Err.MEMPOOL_CONFLICT
2021-05-04T23:21:14.968 full_node chia.full_node.full_node: WARNING  Wasn't able to add transaction with id 4363e8b7ef86608a8ef015f87cbd00ce13c4c89a788b8d58a26c5f1529a90bf4, status 3 error: Err.UNKNOWN_UNSPENT
2021-05-04T23:21:23.942 full_node chia.full_node.full_node: WARNING  Wasn't able to add transaction with id c33a73b73eee8327558ba5f3ebb8f0bdfb2ffa9416e834e86e2ff88da30170f8, status 3 error: Err.UNKNOWN_UNSPENT

centos7  Python3.7  gnome  gui

**Comment by drugsnhugs** [comment]
Same, i got hundreds. 

Are we at least farming? 

2021-05-05T21:44:19.933 full_node chia.full_node.full_node: WARNING  Wasn't able to add transaction with id 83e8eff2fc5a00bb69195eb0e0372309ba2d896cc63283b42b77c27230e6942f, status 3 error: Err.DOUBLE_SPEND
2021-05-05T21:44:19.938 full_node chia.full_node.full_node: WARNING  Wasn't able to add transaction with id 8fd0aa6c2afd917b967ab19f5da770f8b649b554852902ae2cb8f633f466d579, status 3 error: Err.DOUBLE_SPEND
2021-05-05T21:44:19.959 full_node chia.full_node.full_node: WARNING  Wasn't able to add transaction with id 4acafef88917dd2edfaf9c208f74ee853e755f940951a4f5f4cf94360ec87a18, status 3 error: Err.DOUBLE_SPEND
2021-05-05T21:44:19.962 full_node chia.full_node.full_node: WARNING  Wasn't able to add transaction with id 5b59054fe8e25c2f41ac6f910bc16f00f7c697f951123185d0f1866b302ac3b5, status 3 error: Err.DOUBLE_SPEND
2021-05-05T21:44:20.320 full_node chia.full_node.full_node: WARNING  Wasn't able to add transaction with id 08fb1ca842edf05181f5592f833e1252b5449ab7ed6aaceb196e2c6561e79028, status 3 error: Err.DOUBLE_SPEND
2021-05-05T21:44:20.341 full_node chia.full_node.full_node: WARNING  Wasn't able to add transaction with id bcb0bdd9b44587c3fcf1e7c82f3c54f9d905fdafb669539d1ea28a9326d23b31, status 3 error: Err.DOUBLE_SPEND
2021-05-05T21:44:20.355 full_node chia.full_node.full_node: WARNING  Wasn't able to add transaction with id 42483f9df6dd7b307c66b77658c59c8046114666c26389ecd5e2aae5a51b253b, status 3 error: Err.DOUBLE_SPEND
2021-05-05T21:44:22.464 full_node chia.full_node.full_node: WARNING  Wasn't able to add transaction with id 3d445d6d3d572109bc9453ce869b1f7bdf69efcfbf12c1f81902b6cde8580bf4, status 3 error: Err.DOUBLE_SPEND
2021-05-05T21:44:22.465 full_node chia.full_node.full_node: WARNING  Wasn't able to add transaction with id e13e43dedfe232d08ac0365583638e23e9b7b243265b20e5d0d8cb728d81fe2f, status 3 error: Err.DOUBLE_SPEND
2021-05-05T22:17:23.063 full_node chia.full_node.full_node: ERROR    Respond peers exception: 'NoneType' object has no attribute 'host'. Traceback: Traceback (most recent call last):
  File "chia\server\node_discovery.py", line 509, in respond_peers
  File "chia\server\node_discovery.py", line 474, in add_peers_neighbour
AttributeError: 'NoneType' object has no attribute 'host'

2021-05-05T22:17:23.090 full_node full_node_server        : ERROR    Exception:  <class 'concurrent.futures._base.CancelledError'>, closing connection None. Traceback (most recent call last):
  File "chia\server\server.py", line 531, in api_call
  File "asyncio\tasks.py", line 435, in wait_for
concurrent.futures._base.CancelledError

2021-05-05T22:25:09.138 full_node chia.full_node.full_node: WARNING  Wasn't able to add transaction with id d000694afada59dc6657fb430a5cad4509f3765980cba116e1f5bc2425256f6b, status 3 error: Err.DOUBLE_SPEND

**Comment by Chia-Blockchain** [comment]
I get these


2021-05-05T20:44:15.163 full_node chia.full_node.full_node: WARNING  Wasn't able to add transaction with id e13e43dedfe232d08ac0365583638e23e9b7b243265b20e5d0d8cb728d81fe2f, status 3 error: Err.DOUBLE_SPEND
2021-05-05T21:15:39.722 full_node full_node_server        : WARNING  Banning 121.12.167.179 for 10 seconds
2021-05-05T21:15:39.722 full_node full_node_server        : WARNING  Invalid handshake with peer. Maybe the peer is running old software.
2021-05-05T21:23:51.614 full_node full_node_server        : ERROR    Exception Was not able to get peername from <function WSChiaConnection.__getattr__.<locals>.invoke at 0x0000028BDF1B2318> at 101.228.202.203, exception Stack: Traceback (most recent call last):
  File "chia\server\server.py", line 245, in incoming_connection
  File "chia\server\ws_connection.py", line 59, in __init__
ValueError: Was not able to get peername from <function WSChiaConnection.__getattr__.<locals>.invoke at 0x0000028BDF1B2318> at 101.228.202.203
