### ISSUE TITLE
Latest version not running on Ubuntu

### ISSUE THREAD

**Issue by lasoniss** [Chia-Network/chia-blockchain#385]
The top line of "git log" reads:

commit cea45ebaac3b03118a6f45105f138b4368027963 (HEAD -> master, tag: 1.0beta11, origin/master, origin/HEAD)
Author: Gene Hoffman <hoffmang@hoffmang.com>
Date:   Mon Aug 24 14:59:12 2020 -0700

    Update changelog for beta 11 release

"npm run build" compiles successfully. 

"npm run electron" returns the following javascript error:

App threw an error during load
Error: Cannot find module 'about-window'
Require stack:
- /<path redacted>/chia/chia-blockchain/electron-react/src/electron-starter.js
- /<path redacted>/chia/chia-blockchain/electron-react/node_modules/electron/dist/resources/default_app.asar/main.js
- 
    at Module._resolveFilename (internal/modules/cjs/loader.js:798:15)
    at Function../lib/common/reset-search-paths.ts.Module._resolveFilename (electron/js2c/browser_init.js:7620:16)
    at Module._load (internal/modules/cjs/loader.js:691:27)
    at Module._load (electron/js2c/asar.js:717:26)
    at Function.Module._load (electron/js2c/asar.js:717:26)
    at Module.require (internal/modules/cjs/loader.js:853:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/<path redacted>/chia/chia-blockchain/electron-react/src/electron-starter.js:17:25)
    at Module._compile (internal/modules/cjs/loader.js:968:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:986:10)

**Comment by lasoniss** [comment]
I redacted identifying path details. Github has mangled what I wrote in, which appears as // in the submission.

**Comment by hoffmang9** [comment]
Can you confirm two things?

1. Did you run `sh install.sh` and it completed without error?

2. Were you in the venv when you ran `npm run build`?

**Comment by lasoniss** [comment]
I forgot to re-run sh install.sh. Thanks, that worked. 

FYI, it's synced now, but I'm back to the problem of unspeandible coins. I'll try deleting my wallet and resyncing like last time and see if it fixes it again.
