### ISSUE TITLE
[BUG] Cannot start Chia: cannot import name 'serialized_length' from 'clvm_rs' (Manjaro Linux)

### ISSUE THREAD

**Issue by mtnakayama** [Chia-Network/chia-blockchain#3858]
**Describe the bug**
I just upgraded to commit 0fbf998bf7ad88f1ccad86acbbd6f1334a043ee6 (Tag 1.1.4), following the Ubuntu instructions on the wiki (I am on Manjaro Linux). The program was working correctly before, but now I cannot start due to a Python exception.

**To Reproduce**
```bash
. ./activate
chia start all
```

**Expected behavior**
Chia should start.

**Screenshots**
```
Traceback (most recent call last):
  File "/home/matthew/.local/chia-blockchain/venv/bin/chia", line 33, in <module>
    sys.exit(load_entry_point('chia-blockchain', 'console_scripts', 'chia')())
  File "/home/matthew/.local/chia-blockchain/chia/cmds/chia.py", line 77, in main
    cli()  # pylint: disable=no-value-for-parameter
  File "/home/matthew/.local/chia-blockchain/venv/lib/python3.9/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/matthew/.local/chia-blockchain/venv/lib/python3.9/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/matthew/.local/chia-blockchain/venv/lib/python3.9/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/matthew/.local/chia-blockchain/venv/lib/python3.9/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/matthew/.local/chia-blockchain/venv/lib/python3.9/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/matthew/.local/chia-blockchain/venv/lib/python3.9/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/matthew/.local/chia-blockchain/chia/cmds/start.py", line 12, in start_cmd
    from .start_funcs import async_start
  File "/home/matthew/.local/chia-blockchain/chia/cmds/start_funcs.py", line 9, in <module>
    from chia.daemon.client import DaemonProxy, connect_to_daemon_and_validate
  File "/home/matthew/.local/chia-blockchain/chia/daemon/client.py", line 9, in <module>
    from chia.server.server import ssl_context_for_client
  File "/home/matthew/.local/chia-blockchain/chia/server/server.py", line 19, in <module>
    from chia.protocols.shared_protocol import protocol_version
  File "/home/matthew/.local/chia-blockchain/chia/protocols/shared_protocol.py", line 6, in <module>
    from chia.util.streamable import Streamable, streamable
  File "/home/matthew/.local/chia-blockchain/chia/util/streamable.py", line 14, in <module>
    from chia.types.blockchain_format.program import Program, SerializedProgram
  File "/home/matthew/.local/chia-blockchain/chia/types/blockchain_format/program.py", line 10, in <module>
    from clvm_rs import STRICT_MODE, deserialize_and_run_program, serialized_length
ImportError: cannot import name 'serialized_length' from 'clvm_rs' (/home/matthew/.local/chia-blockchain/venv/lib/python3.9/site-packages/clvm_rs.cpython-39-x86_64-linux-gnu.so)
```

**Desktop (please complete the following information):**

- OS: Linux
- OS Version/Flavor: Manjaro
- CPU: Intel i7 6700K

**Additional context**
 - Commit: 0fbf998bf7ad88f1ccad86acbbd6f1334a043ee6
 - Tag: 1.1.4

**Comment by mtnakayama** [comment]
I forgot to run `deactivate` before I upgraded. 
I went through the upgrade process and am no longer encountering the bug.
