### ISSUE TITLE
[help] ERROR    Exception Was not able to get peername from <function WSChiaConnection.__getattr__.<locals>.invoke at 0x0000028BDF1B2318> at

### ISSUE THREAD

**Issue by Chia-Blockchain** [Chia-Network/chia-blockchain#3861]
I get these errors

2021-05-05T20:44:15.163 full_node chia.full_node.full_node: WARNING  Wasn't able to add transaction with id e13e43dedfe232d08ac0365583638e23e9b7b243265b20e5d0d8cb728d81fe2f, status 3 error: Err.DOUBLE_SPEND
2021-05-05T21:15:39.722 full_node full_node_server        : WARNING  Banning 121.12.167.179 for 10 seconds
2021-05-05T21:15:39.722 full_node full_node_server        : WARNING  Invalid handshake with peer. Maybe the peer is running old software.
2021-05-05T21:23:51.614 full_node full_node_server        : ERROR    Exception Was not able to get peername from <function WSChiaConnection.__getattr__.<locals>.invoke at 0x0000028BDF1B2318> at 101.228.202.203, exception Stack: Traceback (most recent call last):
  File "chia\server\server.py", line 245, in incoming_connection
  File "chia\server\ws_connection.py", line 59, in __init__
ValueError: Was not able to get peername from <function WSChiaConnection.__getattr__.<locals>.invoke at 0x0000028BDF1B2318> at 101.228.202.203

What do they mean?

**Comment by pkosingbtc** [comment]
+++same problem

**Comment by tammanie** [comment]
Und jemand ne Lösung??

**Comment by feydkin** [comment]
`2021-06-02T10:30:26.757 full_node full_node_server        : ERROR    Exception Was not able to get peername from <function WSChiaConnection.__getattr__.<locals>.invoke at 0x7fe8070210d0> at 124.122.22.192, exception Stack: Traceback (mo>
  File "/home/username/chia-blockchain/chia/server/server.py", line 235, in incoming_connection
    connection = WSChiaConnection(
  File "/home/username/chia-blockchain/chia/server/ws_connection.py", line 59, in __init__
    raise ValueError(f"Was not able to get peername from {self.ws_witer} at {self.peer_host}")
ValueError: Was not able to get peername from <function WSChiaConnection.__getattr__.<locals>.invoke at 0x7fe8070210d0> at 124.122.22.192
`
Same here. Running farmer on Ubuntu server.

**Comment by richardwhatever** [comment]
same

**Comment by RocketLR** [comment]
Im still getting it. 
Also in the "about chia blockchain" window my version says 0.0 
I've tried reinstalling and updating.. but this never gets fixed.

**Comment by Dartellum** [comment]
I am also having this error.
```
2021-07-19T01:22:48.020 full_node full_node_server        : ERROR    Exception Was not able to get peername from <function WSChiaConne>
82832   File "/home/chia/chia-blockchain/chia/server/server.py", line 232, in incoming_connection
82833     connection = WSChiaConnection(
82834   File "/home/chia/chia-blockchain/chia/server/ws_connection.py", line 59, in __init__
82835     raise ValueError(f"Was not able to get peername from {self.ws_witer} at {self.peer_host}")
82836 ValueError: Was not able to get peername from <function WSChiaConnection.__getattr__.<locals>.invoke at 0x7f0b2a4a0e50> at 104.200.131>
82837
```

**Comment by emlowe** [comment]
This isn't a serious error, although the logging makes it seem that way. From time to time you will connect to peers that either don't respond properly or otherwise go away. In this case, the connection is just closed and you will continue with connecting with other peers. However, the logging is excessive.
