### ISSUE TITLE
[BUG] No peer connections after upgrade to 1.1.3&4, errors in log

### ISSUE THREAD

**Issue by DefiantMiner** [Chia-Network/chia-blockchain#3895]
**Describe the bug**
Was running great on 1.1.2, was dropped off all connections overnight, now it doesn't find peers automatically after upgrade to 1.1.3 and 1.1.4. 

**To Reproduce**
Just run node...

**Expected behavior**
No peers connected automatically, can manually enter peer and connect (I only know one reliable IP) and will sync and farm normally but with only one peer the connection is unstable for long periods.

**Desktop (please complete the following information):**
Win10 latest, Intel i5, full-node on dedicated stand-alone system

Error log segment just after reboot:
2021-05-06T00:24:08.458 full_node full_node_server        : ERROR    Exception , exception Stack: Traceback (most recent call last):
  File "chia\server\server.py", line 356, in start_client
  File "aiohttp\client.py", line 763, in _ws_connect
  File "aiohttp\client.py", line 521, in _request
  File "aiohttp\connector.py", line 535, in connect
  File "aiohttp\connector.py", line 892, in _create_connection
  File "aiohttp\connector.py", line 1032, in _create_direct_connection
  File "aiohttp\connector.py", line 969, in _wrap_create_connection
  File "asyncio\base_events.py", line 949, in create_connection
  File "asyncio\selector_events.py", line 473, in sock_connect
concurrent.futures._base.CancelledError

Also, there are alot of these entries in the log running before that last reboot:  (unknown if it is related)

2021-05-05T18:10:58.888 full_node chia.full_node.full_node: ERROR    Respond peers exception: . Traceback: Traceback (most recent call last):
  File "chia\server\node_discovery.py", line 507, in respond_peers
  File "chia\server\node_discovery.py", line 397, in _respond_peers_common
  File "chia\server\address_manager.py", line 602, in add_to_new_table
  File "asyncio\locks.py", line 92, in __aenter__
  File "asyncio\locks.py", line 192, in acquire
concurrent.futures._base.CancelledError

2021-05-05T23:27:34.780 full_node chia.rpc.rpc_server     : WARNING  Error while handling message: Traceback (most recent call last):
  File "chia\rpc\rpc_server.py", line 212, in safe_handle
  File "chia\rpc\rpc_server.py", line 200, in ws_api
  File "chia\rpc\rpc_server.py", line 161, in open_connection
ValueError: Start client failed, or server is not set

2021-05-05T23:28:45.948 full_node chia.rpc.rpc_server     : WARNING  Error while handling message: Traceback (most recent call last):
  File "chia\rpc\rpc_server.py", line 212, in safe_handle
  File "chia\rpc\rpc_server.py", line 200, in ws_api
  File "chia\rpc\rpc_server.py", line 161, in open_connection
ValueError: Start client failed, or server is not set

2021-05-05T23:29:38.092 full_node chia.rpc.rpc_server     : WARNING  Error while handling message: Traceback (most recent call last):
  File "chia\rpc\rpc_server.py", line 212, in safe_handle
  File "chia\rpc\rpc_server.py", line 200, in ws_api
  File "chia\rpc\rpc_server.py", line 161, in open_connection
ValueError: Start client failed, or server is not set

These last ones have not yet reappeared since the reboot but still no peers.

**Comment by DefiantMiner** [comment]
Something changed, but I don't what it was....peers have begun to appear again.   The weirdness continues...
