### ISSUE TITLE
[BUG] not syncing

### ISSUE THREAD

**Issue by chiabetatester** [Chia-Network/chia-blockchain#3947]
ver 1.1.4 was sync'ed and farming until i get this error now in the debug
and cannot connect to host

tried adding a chia introducer but still have no sync

2021-05-07T00:09:12.614 full_node chia.rpc.rpc_server     : WARNING  Error while handling message: Traceback (most recent call last):
  File "chia\rpc\rpc_server.py", line 212, in safe_handle
  File "chia\rpc\rpc_server.py", line 200, in ws_api
  File "chia\rpc\rpc_server.py", line 161, in open_connection
ValueError: Start client failed, or server is not set

i tried exiting the program in windows and shutting the server with running plots in the program and the window is gone. however i  can see the chia process still going in the task manager using resources. running the program again , shows no plots in progress when clearly the task manager resources shows otherwise. ending both chia programs now via end task and restart still hasn't solved th problem

**Comment by alekisminerador** [comment]
not syncing

**Comment by BluefireXD** [comment]
same issue

**Comment by biostone** [comment]
same issue.

**Comment by macaryus** [comment]
same issue

**Comment by AbstractGaze** [comment]
It helped me to delete folder
 C:\Users\your_user\.chia

**Comment by Yamanipanuchi** [comment]
Any resolution to this issue. I've been experiencing it also on two of my machines.

**Comment by tacci101** [comment]
The same issue here...
Anyone could take a look at it please?

**Comment by struxoje** [comment]
Chia version 1.2.2 issue still exists:

2021-07-15T00:10:27.789 full_node chia.rpc.rpc_server     : WARNING  Error while handling message: Traceback (most recent call last):
  File "/srv/chia/chia-blockchain/chia/rpc/rpc_server.py", line 81, in inner
    res_object = await f(request_data)
  File "/srv/chia/chia-blockchain/chia/rpc/full_node_rpc_api.py", line 130, in get_blockchain_state
    {"newer_block_header_hash": newer_block_hex, "older_block_header_hash": older_block_hex}
  File "/srv/chia/chia-blockchain/chia/rpc/full_node_rpc_api.py", line 391, in get_network_space
    newer_block = await self.service.block_store.get_block_record(newer_block_bytes)
  File "/srv/chia/chia-blockchain/chia/full_node/block_store.py", line 232, in get_block_record
    (header_hash.hex(),),
  File "/srv/chia/chia-blockchain/venv/lib/python3.7/site-packages/aiosqlite/core.py", line 184, in execute
    cursor = await self._execute(self._conn.execute, sql, parameters)
  File "/srv/chia/chia-blockchain/venv/lib/python3.7/site-packages/aiosqlite/core.py", line 129, in _execute
    return await future
concurrent.futures._base.CancelledError
