### ISSUE TITLE
[BUG] chia_harvester goes defunct after sometime

### ISSUE THREAD

**Issue by drewmullen** [Chia-Network/chia-blockchain#3980]
**Describe the bug**
after some time, `chia_harvester` process becomes `defunct` from parent `chia_daemon` and both must be killed

Error in debug.log (chia logs it at `INFO` level):
```
2021-05-06T12:01:57.485 daemon chia.daemon.server         : INFO     Websocket exception. Closing websocket with chia_harvester code = 1006 (connection closed abnormally [internal]), no reason Traceback (most recent call last):
  File "/home/farmer3/chia-1.1.4/chia-blockchain/venv/lib/python3.7/site-packages/websockets/protocol.py", line 827, in transfer_data
    message = await self.read_message()
  File "/home/farmer3/chia-1.1.4/chia-blockchain/venv/lib/python3.7/site-packages/websockets/protocol.py", line 895, in read_message
    frame = await self.read_data_frame(max_size=self.max_size)
  File "/home/farmer3/chia-1.1.4/chia-blockchain/venv/lib/python3.7/site-packages/websockets/protocol.py", line 971, in read_data_frame
    frame = await self.read_frame(max_size)
  File "/home/farmer3/chia-1.1.4/chia-blockchain/venv/lib/python3.7/site-packages/websockets/protocol.py", line 1051, in read_frame
    extensions=self.extensions,
  File "/home/farmer3/chia-1.1.4/chia-blockchain/venv/lib/python3.7/site-packages/websockets/framing.py", line 105, in read
    data = await reader(2)
  File "/usr/local/lib/python3.7/asyncio/streams.py", line 677, in readexactly
    raise IncompleteReadError(incomplete, n)
asyncio.streams.IncompleteReadError: 0 bytes read on a total of 2 expected bytes

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/farmer3/chia-1.1.4/chia-blockchain/chia/daemon/server.py", line 172, in safe_handle
    async for message in websocket:
  File "/home/farmer3/chia-1.1.4/chia-blockchain/venv/lib/python3.7/site-packages/websockets/protocol.py", line 439, in __aiter__
    yield await self.recv()
  File "/home/farmer3/chia-1.1.4/chia-blockchain/venv/lib/python3.7/site-packages/websockets/protocol.py", line 509, in recv
    await self.ensure_open()
  File "/home/farmer3/chia-1.1.4/chia-blockchain/venv/lib/python3.7/site-packages/websockets/protocol.py", line 803, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedError: code = 1006 (connection closed abnormally [internal]), no reason
```

```
$ ps aux | grep chia
farmer3   241404  0.0  0.1 413920 48408 pts/2    Sl   09:57   0:02 chia_daemon
farmer3   241619  0.4  0.0      0     0 pts/2    Z    09:57   0:16 [chia_harvester] <defunct>
```

My setup:
1 full node: windows, gui, used for farming
2 harvester nodes that also plot

**To Reproduce**
1. `chia start harvester`
2. wait some time
3. `ps aux | grep chia`

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

- OS: Linux
- OS Version/Flavor: Fedora 34
- CPU: intel 10850k

**Additional context**
I did some troubleshooting in [this issue](https://github.com/Chia-Network/chia-blockchain/issues/3810) but i now think this could be a bug and opened a new, less confusing issue.

**Comment by mariano54** [comment]
This is most likely a bad plot, we will fix this soon. Try running `chia plots check` to see if you can find it

**Comment by drewmullen** [comment]
`chia plots check` failed pretty late into the testing process
```
malloc(): invalid size (unsorted)
Aborted (core dumped)
```

**Comment by drewmullen** [comment]
@mariano54 any advice on whats going on with the errors above? is it appropriate to just delete plots that have any of those errors?

**Comment by drewmullen** [comment]
im not even getting errors anymore during `chia plots check` but the error keeps killing the process:
```
malloc(): invalid size (unsorted)
Aborted (core dumped)
```

**Comment by drewmullen** [comment]
over the last day i have probably deleted about 30 plots that some how went bad. my harvester has only gone down once but that was early on in the process when most of those 30 were still alive. 

if theres a bug here its 2:
1. `chia plots check` should **not** crash when it comes across bad plots
2. why are many of these plots going bad? 

regarding 1: i have some strace logs if thats helpful, just lmk where to dump them.
regarding 2: idk what happened but i suspect some of these went bad because of `mv`. i cant confirm this is the case but its my only current suspicion. a friend recommended i start using rsync when moving files so im testing that out by moving 1 plot then running `chia plots check`

**Comment by drewmullen** [comment]
i installed 1.1.5, we'll see if i have better luck with that

**Comment by drewmullen** [comment]
seems to be resolved since new version. thanks for mentioning the bad plots
