### ISSUE TITLE
[BUG] ValueError: Weight proof validation failed

### ISSUE THREAD

**Issue by temicus** [Chia-Network/chia-blockchain#3991]
**Describe the bug**
After reboot can not sync. Getting error: 
"ValueError: Weight proof validation failed". Reinstall of the chia has not helped.
Win 10, V.1.1.4

Example:
2021-05-06T21:58:10.603 full_node chia.full_node.full_node: WARNING  Invalid response for slot None
2021-05-06T22:03:05.000 full_node chia.full_node.weight_proof: ERROR    failed validating weight proof recent blocks
2021-05-06T22:03:05.199 full_node full_node_server        : WARNING  Banning xxx for 600 seconds
2021-05-06T22:03:05.200 full_node chia.full_node.full_node: ERROR    Error with syncing: <class 'ValueError'>Traceback (most recent call last):
  File "chia\full_node\full_node.py", line 651, in _sync
ValueError: Weight proof validation failed

**Comment by ox-prog** [comment]
@temicus, Have you already solve your problem? The same issue to me.
```
2021-05-14T19:38:25.286 full_node chia.full_node.weight_proof: ERROR    failed validating weight proof recent blocks
2021-05-14T19:38:25.628 full_node full_node_server        : WARNING  Banning " ${IP_ADRESS}" for 600 seconds
2021-05-14T19:38:25.630 full_node chia.full_node.full_node: ERROR    Error with syncing: <class 'ValueError'>Traceback (most recent call last):
  File "chia\full_node\full_node.py", line 651, in _sync
ValueError: Weight proof validation failed
```

**Comment by temicus** [comment]
@ox-prog It works with 1.1.5 fine now 🤞

**Comment by temicus** [comment]
I had to remove everything, install and sync again 🤮

**Comment by ox-prog** [comment]
> @ox-prog It works with 1.1.5 fine now 🤞

I'm afraid, but I have already installed 1.1.5, nevertheless thank you.
