### ISSUE TITLE
[help]

### ISSUE THREAD

**Issue by SeruousMax** [Chia-Network/chia-blockchain#4005]
CentOS 8.3
i am run:  chia plots create -k 32 -b 10000 -u 128 -r 10 -f <key> -p <key> -t /chiatemp -d /chiamain

And ERROR:

Traceback (most recent call last):
  File "/root/chia-blockchain/venv/bin/chia", line 33, in <module>
    sys.exit(load_entry_point('chia-blockchain', 'console_scripts', 'chia')())
  File "/root/chia-blockchain/chia/cmds/chia.py", line 77, in main
    cli()  # pylint: disable=no-value-for-parameter
  File "/root/chia-blockchain/venv/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/root/chia-blockchain/venv/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/root/chia-blockchain/venv/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/root/chia-blockchain/venv/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/root/chia-blockchain/venv/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/root/chia-blockchain/venv/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/root/chia-blockchain/venv/lib/python3.7/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/root/chia-blockchain/chia/cmds/plots.py", line 135, in create_cmd
    create_plots(Params(), ctx.obj["root_path"])
  File "/root/chia-blockchain/chia/plotting/create_plots.py", line 55, in create_plots
    farmer_public_key = G1Element.from_bytes(bytes.fromhex(args.farmer_public_key))
ValueError: Length of bytes object not equal to G1Element::SIZE

**Comment by SeruousMax** [comment]
Wrong farmer key
