### ISSUE TITLE
[help] Not synced again and again

### ISSUE THREAD

**Issue by hapablap** [Chia-Network/chia-blockchain#4033]
I have two full nodes on different locations, both with different keys. One has a log of connections and is online all the time (synced). The other one hardly gets connections and is not synced again and again. Sometimes, it helps just to wait. But sometimes it takes hours and then I can try to add peers manually. First I could add my other node from the other location manually, but when I add it now, it's simply not added to the list. No error message, no feedback.

Today it helped to add the node.chia.net. Sometimes I can't even add that node and my node is offline for a long time, which for me is a problem, because the farm is offline, too. I don't understand why it is so hard for one machine to sync and so easy for others? It's also not a network problem, I enabled UPNP.

**Comment by DatDraggy** [comment]
Disable UPNP and forward port 8444 instead.
It's most likely a network problem because chia can't handle dynamic ips or short disconnects yet. A lot of people are complaining about this. You have to restart chia and then it'll be able to sync again

**Comment by racabu** [comment]
Same issue here. Using the latest version, Port forwarding turned on. UPNP also enabled.
It's a problem having to restart the client... if we are creating plots. This is making us loosing machine work and therefore not that "green" as it should be.

**Comment by jayMcBee** [comment]
Same here - losing sync **at least** once a day due to forced ISP reconnect.
This is very common in Europe and limits farming for pretty much everybody using a standard internet provider in Europe.

Issue remains unchanged with recent versions (up to and including current 1.1.4)

**Comment by hapablap** [comment]
Thanks for all your help. I have tried disabling UPnP and port forwarding 8444. Nothing helps. As @jayMcBee mentioned, once a day I am getting out of sync. This is really annoying and I can't believe that this is not fixed yet, as so many have this problem.

**Comment by hapablap** [comment]
So, every morning I am again out of sync. This is from my debug log:

2021-05-11T19:35:14.915 full_node full_node_server        : ERROR    Exception: Failed to fetch block 265222 from {'host': '27.194.198.216', 'port': 8444}, timed out, {'host': '27.194.198.216', 'port': 8444}. Traceback (most recent call last):
  File "chia\server\server.py", line 521, in wrapped_coroutine
  File "chia\full_node\full_node_api.py", line 104, in new_peak
  File "chia\full_node\full_node.py", line 361, in new_peak
  File "chia\full_node\full_node.py", line 310, in short_sync_backtrack
  File "chia\full_node\full_node.py", line 295, in short_sync_backtrack
ValueError: Failed to fetch block 265222 from {'host': '27.194.198.216', 'port': 8444}, timed out

2021-05-11T19:35:14.961 full_node full_node_server        : ERROR    Exception: Failed to fetch block 265222 from {'host': '27.194.198.216', 'port': 8444}, timed out <class 'ValueError'>, closing connection {'host': '27.194.198.216', 'port': 8444}. Traceback (most recent call last):
  File "chia\server\server.py", line 531, in api_call
  File "asyncio\tasks.py", line 414, in wait_for
  File "chia\server\server.py", line 528, in wrapped_coroutine
  File "chia\server\server.py", line 521, in wrapped_coroutine
  File "chia\full_node\full_node_api.py", line 104, in new_peak
  File "chia\full_node\full_node.py", line 361, in new_peak
  File "chia\full_node\full_node.py", line 310, in short_sync_backtrack
  File "chia\full_node\full_node.py", line 295, in short_sync_backtrack
ValueError: Failed to fetch block 265222 from {'host': '27.194.198.216', 'port': 8444}, timed out

2021-05-11T19:35:16.449 full_node full_node_server        : ERROR    Exception: Failed to fetch block 265223 from {'host': '27.194.198.216', 'port': 8444}, timed out, {'host': '27.194.198.216', 'port': 8444}. Traceback (most recent call last):
  File "chia\server\server.py", line 521, in wrapped_coroutine
  File "chia\full_node\full_node_api.py", line 104, in new_peak
  File "chia\full_node\full_node.py", line 361, in new_peak
  File "chia\full_node\full_node.py", line 310, in short_sync_backtrack
  File "chia\full_node\full_node.py", line 295, in short_sync_backtrack
ValueError: Failed to fetch block 265223 from {'host': '27.194.198.216', 'port': 8444}, timed out

2021-05-11T19:35:16.450 full_node full_node_server        : ERROR    Exception: Failed to fetch block 265223 from {'host': '27.194.198.216', 'port': 8444}, timed out <class 'ValueError'>, closing connection {'host': '27.194.198.216', 'port': 8444}. Traceback (most recent call last):
  File "chia\server\server.py", line 531, in api_call
  File "asyncio\tasks.py", line 414, in wait_for
  File "chia\server\server.py", line 528, in wrapped_coroutine
  File "chia\server\server.py", line 521, in wrapped_coroutine
  File "chia\full_node\full_node_api.py", line 104, in new_peak
  File "chia\full_node\full_node.py", line 361, in new_peak
  File "chia\full_node\full_node.py", line 310, in short_sync_backtrack
  File "chia\full_node\full_node.py", line 295, in short_sync_backtrack
ValueError: Failed to fetch block 265223 from {'host': '27.194.198.216', 'port': 8444}, timed out

2021-05-11T19:35:24.957 full_node full_node_server        : WARNING  Banning 27.194.198.216 for 10 seconds
2021-05-11T19:35:24.961 full_node full_node_server        : ERROR    Exception: Failed to fetch block 265224 from {'host': '27.194.198.216', 'port': 8444}, timed out, {'host': '27.194.198.216', 'port': 8444}. Traceback (most recent call last):
  File "chia\server\server.py", line 521, in wrapped_coroutine
  File "chia\full_node\full_node_api.py", line 104, in new_peak
  File "chia\full_node\full_node.py", line 361, in new_peak
  File "chia\full_node\full_node.py", line 310, in short_sync_backtrack
  File "chia\full_node\full_node.py", line 295, in short_sync_backtrack
ValueError: Failed to fetch block 265224 from {'host': '27.194.198.216', 'port': 8444}, timed out

2021-05-11T19:35:24.963 full_node full_node_server        : ERROR    Exception: Failed to fetch block 265224 from {'host': '27.194.198.216', 'port': 8444}, timed out <class 'ValueError'>, closing connection {'host': '27.194.198.216', 'port': 8444}. Traceback (most recent call last):
  File "chia\server\server.py", line 531, in api_call
  File "asyncio\tasks.py", line 414, in wait_for
  File "chia\server\server.py", line 528, in wrapped_coroutine
  File "chia\server\server.py", line 521, in wrapped_coroutine
  File "chia\full_node\full_node_api.py", line 104, in new_peak
  File "chia\full_node\full_node.py", line 361, in new_peak
  File "chia\full_node\full_node.py", line 310, in short_sync_backtrack
  File "chia\full_node\full_node.py", line 295, in short_sync_backtrack
ValueError: Failed to fetch block 265224 from {'host': '27.194.198.216', 'port': 8444}, timed out

2021-05-11T19:35:24.964 full_node full_node_server        : ERROR    Exception: Failed to fetch block 265225 from {'host': '27.194.198.216', 'port': 8444}, timed out, {'host': '27.194.198.216', 'port': 8444}. Traceback (most recent call last):
  File "chia\server\server.py", line 521, in wrapped_coroutine
  File "chia\full_node\full_node_api.py", line 104, in new_peak
  File "chia\full_node\full_node.py", line 361, in new_peak
  File "chia\full_node\full_node.py", line 310, in short_sync_backtrack
  File "chia\full_node\full_node.py", line 295, in short_sync_backtrack
ValueError: Failed to fetch block 265225 from {'host': '27.194.198.216', 'port': 8444}, timed out

2021-05-11T19:35:24.966 full_node full_node_server        : ERROR    Exception: Failed to fetch block 265225 from {'host': '27.194.198.216', 'port': 8444}, timed out <class 'ValueError'>, closing connection {'host': '27.194.198.216', 'port': 8444}. Traceback (most recent call last):
  File "chia\server\server.py", line 531, in api_call
  File "asyncio\tasks.py", line 414, in wait_for
  File "chia\server\server.py", line 528, in wrapped_coroutine
  File "chia\server\server.py", line 521, in wrapped_coroutine
  File "chia\full_node\full_node_api.py", line 104, in new_peak
  File "chia\full_node\full_node.py", line 361, in new_peak
  File "chia\full_node\full_node.py", line 310, in short_sync_backtrack
  File "chia\full_node\full_node.py", line 295, in short_sync_backtrack
ValueError: Failed to fetch block 265225 from {'host': '27.194.198.216', 'port': 8444}, timed out

2021-05-11T23:51:03.374 full_node chia.full_node.full_node: WARNING  Invalid response for slot None
2021-05-12T00:10:33.757 full_node chia.full_node.full_node: WARNING  Invalid response for slot None
2021-05-12T00:12:19.471 full_node chia.full_node.full_node: WARNING  Wasn't able to add transaction with id ..., status 3 error: Err.UNKNOWN_UNSPENT
2021-05-12T00:12:19.477 full_node chia.full_node.full_node: WARNING  Wasn't able to add transaction with id ..., status 3 error: Err.UNKNOWN_UNSPENT
2021-05-12T01:07:20.891 wallet chia.wallet.wallet_node    : ERROR    Error while trying to fetch from peer:Peer returned no response Traceback (most recent call last):
  File "chia\wallet\wallet_node.py", line 597, in _sync
  File "chia\wallet\wallet_node.py", line 635, in fetch_blocks_and_validate
ValueError: Peer returned no response

2021-05-12T01:07:20.903 wallet chia.wallet.wallet_node    : ERROR    Loop exception in sync Was not able to add blocks 265616-265648. Traceback (most recent call last):
  File "chia\wallet\wallet_node.py", line 509, in sync_job
  File "chia\wallet\wallet_node.py", line 606, in _sync
RuntimeError: Was not able to add blocks 265616-265648

2021-05-12T01:07:20.899 full_node full_node_server        : ERROR    Exception:  <class 'concurrent.futures._base.CancelledError'>, closing connection {'host': '127.0.0.1', 'port': 8449}. Traceback (most recent call last):
  File "chia\server\server.py", line 531, in api_call
  File "asyncio\tasks.py", line 435, in wait_for
concurrent.futures._base.CancelledError

2021-05-12T01:12:44.989 wallet chia.wallet.wallet_node    : ERROR    Error while trying to fetch from peer:Peer returned no response Traceback (most recent call last):
  File "chia\wallet\wallet_node.py", line 597, in _sync
  File "chia\wallet\wallet_node.py", line 635, in fetch_blocks_and_validate
ValueError: Peer returned no response

2021-05-12T01:12:44.995 wallet chia.wallet.wallet_node    : ERROR    Loop exception in sync Was not able to add blocks 264592-264624. Traceback (most recent call last):
  File "chia\wallet\wallet_node.py", line 509, in sync_job
  File "chia\wallet\wallet_node.py", line 606, in _sync
RuntimeError: Was not able to add blocks 264592-264624

2021-05-12T01:12:44.990 full_node full_node_server        : ERROR    Exception:  <class 'concurrent.futures._base.CancelledError'>, closing connection {'host': '127.0.0.1', 'port': 8449}. Traceback (most recent call last):
  File "chia\server\server.py", line 531, in api_call
  File "asyncio\tasks.py", line 435, in wait_for
concurrent.futures._base.CancelledError

2021-05-12T01:12:45.993 full_node full_node_server        : ERROR    Exception:  <class 'concurrent.futures._base.CancelledError'>, closing connection {'host': '127.0.0.1', 'port': 8449}. Traceback (most recent call last):
  File "chia\server\server.py", line 531, in api_call
  File "asyncio\tasks.py", line 435, in wait_for
concurrent.futures._base.CancelledError

**Comment by jayMcBee** [comment]
FWIW - I'm now monitoring the connections (outgoing to `8444`) automatically and notify myself when things break.
Then I'm launching a script connecting to a bunch of known addresses, e.g.
`chia show -a node.chia.net:8444`

Chia is quite brittle as a P2P client in my setup (friend with static IP having similar but less frequent issues) so I've resorted to nannying it for now....

**Comment by hapablap** [comment]
> FWIW - I'm now monitoring the connections (outgoing to `8444`) automatically and notify myself when things break.
> Then I'm launching a script connecting to a bunch of known addresses, e.g.
> `chia show -a node.chia.net:8444`
> 
> Chia is quite brittle as a P2P client in my setup (friend with static IP having similar but less frequent issues) so I've resorted to nannying it for now....

Yes it is brittle, but when I check my connection in the morning and see it's not synced, then it might be out of sync for the last hours and this is really a no go, when you think about keeping a node with a farm online, which is waste of power and hardware if it is out of sync.

I also manually connect to nodes, but for example today I can't get connected to any node and I have absolutely no idea why. If I wouldn't have created so many plots until now, I would quit Chia. Many people seem to have this problem and until now I can't find a good official solution from the Chia devs.
