### ISSUE TITLE
[BUG] Failed to execute script chia

### ISSUE THREAD

**Issue by im-mike** [Chia-Network/chia-blockchain#4057]
**Describe the bug**
I've added 3 plots in parallel as usual, two are plotting fine but the third one stopped at 1%.

**To Reproduce**

1. Click add a plot.
2. Select three, plot in parallel, change max RAM to 2500, select temp and final directories, click create plot. 

**Expected behavior**
It should plot all three plots without errors.

**Desktop:**

- OS: Windows 
- OS Version/Flavor: 10 Pro 20H2 19042.928 Windows Feature Experience Pack 120.2212.551.0
- CPU: Intel i7-4790K @ 4.00HGz
- RAM: 16GB

**Additional context**
Log:
2021-05-07T11:45:30.786  chia.plotting.create_plots       : [32mINFO    [0m Adding directory I:\Chia temp to harvester for farming[0m
[10388] Failed to execute script chia
Traceback (most recent call last):
  File "chia\cmds\chia.py", line 81, in <module>
  File "chia\cmds\chia.py", line 77, in main
  File "click\core.py", line 829, in __call__
  File "click\core.py", line 782, in main
  File "click\core.py", line 1259, in invoke
  File "click\core.py", line 1259, in invoke
  File "click\core.py", line 1066, in invoke
  File "click\core.py", line 610, in invoke
  File "click\decorators.py", line 21, in new_func
  File "chia\cmds\plots.py", line 135, in create_cmd
  File "chia\plotting\create_plots.py", line 158, in create_plots
  File "chia\plotting\plot_tools.py", line 110, in add_plot_directory
  File "chia\util\config.py", line 55, in load_config
  File "yaml\__init__.py", line 162, in safe_load
  File "yaml\__init__.py", line 114, in load
  File "yaml\constructor.py", line 49, in get_single_data
  File "yaml\composer.py", line 36, in get_single_node
  File "yaml\composer.py", line 55, in compose_document
  File "yaml\composer.py", line 84, in compose_node
  File "yaml\composer.py", line 133, in compose_mapping_node
  File "yaml\composer.py", line 84, in compose_node
  File "yaml\composer.py", line 127, in compose_mapping_node
  File "yaml\parser.py", line 98, in check_event
  File "yaml\parser.py", line 428, in parse_block_mapping_key
  File "yaml\scanner.py", line 115, in check_token
  File "yaml\scanner.py", line 152, in need_more_tokens
  File "yaml\scanner.py", line 292, in stale_possible_simple_keys
yaml.scanner.ScannerError: while scanning a simple key
  in "C:\Users\micha\.chia\mainnet\config\config.yaml", line 214, column 1
could not find expected ':'
  in "C:\Users\micha\.chia\mainnet\config\config.yaml", line 215, column 1

That's the end of the config.yaml referenced above:

  start_height_buffer: 100
  starting_height: 0
  target_peer_count: 5
  testing: false
  trusted_peers:
    public_crt: config/ssl/full_node/public_full_node.crt
  wallet_peers_path: wallet/db/wallet_peers.sqlite

**Comment by hocheung20** [comment]
I also experienced this bug. 1.1.6 Windows client.
```
...
yaml.scanner.ScannerError: while scanning a simple key
  in "C:\Users\hocheung20\.chia\mainnet\config\config.yaml", line 266, column 1
could not find expected ':'
  in "C:\Users\hocheung20\.chia\mainnet\config\config.yaml", line 267, column 1
  ```
