### ISSUE TITLE
Healp ERROR    Error with syncing

### ISSUE THREAD

**Issue by yar4uk123** [Chia-Network/chia-blockchain#4058]
I see such an error in debug log can anyone say what the reason is?

full_node chia.full_node.full_node: ERROR    Error with syncing: <class 'concurrent.futures.process.BrokenProcessPool'>Traceback (most recent call last):
  File "chia\full_node\full_node.py", line 659, in _sync
  File "chia\full_node\full_node.py", line 725, in sync_from_fork_point
  File "chia\full_node\full_node.py", line 789, in receive_block_batch
  File "chia\consensus\blockchain.py", line 555, in pre_validate_blocks_multiprocessing
  File "chia\consensus\multiprocess_validation.py", line 298, in pre_validate_blocks_multiprocessing
  File "asyncio\base_events.py", line 755, in run_in_executor
  File "concurrent\futures\process.py", line 625, in submit
concurrent.futures.process.BrokenProcessPool: A child process terminated abruptly, the process pool is not usable anymore

And the wallet doesn't sync =(

**Comment by racabu** [comment]
same problem

**Comment by elimes1** [comment]
same problem

**Comment by ninthwalker** [comment]
Isee these as well. Looks like this for me:

`2021-05-12T11:41:00.118 full_node full_node_server        : ERROR    Exception: A child process terminated abruptly, the process pool is not usable anymore <class 'concurrent.futures.process.BrokenProcessPool'>, closing connection {'host': '111.16.175.228', 'port': 8444}. Traceback (most recent call last):
  File "chia\server\server.py", line 531, in api_call
  File "asyncio\tasks.py", line 442, in wait_for
  File "chia\server\server.py", line 528, in wrapped_coroutine
  File "chia\server\server.py", line 521, in wrapped_coroutine
  File "chia\full_node\full_node_api.py", line 227, in respond_transaction
  File "chia\full_node\full_node.py", line 1562, in respond_transaction
  File "chia\full_node\full_node.py", line 1559, in respond_transaction
  File "chia\full_node\mempool_manager.py", line 217, in pre_validate_spendbundle
  File "asyncio\base_events.py", line 755, in run_in_executor
  File "concurrent\futures\process.py", line 625, in submit
concurrent.futures.process.BrokenProcessPool: A child process terminated abruptly, the process pool is not usable anymore`

**Comment by adobito** [comment]
@yar4uk123 @racabu @ninthwalker did you ever solve this?
