### ISSUE TITLE
[REQ]Help please,Iget problem "RuntimeError: Unknown exception"

### ISSUE THREAD

**Issue by Jackkosum** [Chia-Network/chia-blockchain#4106]
Caught plotting error: Bitfield plotting not supported by CPU
[532] Failed to execute script chia
Traceback (most recent call last):
File "chia\cmds\chia.py", line 81, in
File "chia\cmds\chia.py", line 77, in main
File "click\core.py", line 829, in call
File "click\core.py", line 782, in main
File "click\core.py", line 1259, in invoke
File "click\core.py", line 1259, in invoke
File "click\core.py", line 1066, in invoke
File "click\core.py", line 610, in invoke
File "click\decorators.py", line 21, in new_func
File "chia\cmds\plots.py", line 135, in create_cmd
File "chia\plotting\create_plots.py", line 176, in create_plots
RuntimeError: Unknown exception

my plots stop at 1%

**Comment by zengyunsi** [comment]
C TO C

**Comment by wambax37** [comment]
i Have same problem, help us?

**Comment by Plopsi** [comment]
Caught plotting error: **Bitfield plotting not supported by CPU**

deactivate bitfield plotting - in the gui there is a checkbox for this.

**Comment by Plopsi** [comment]
![grafik](https://user-images.githubusercontent.com/17942998/117591514-265dda00-b135-11eb-97f6-09ecff951437.png)

just in case ;) (windows client)

**Comment by lvpcguru** [comment]
> 
> 
> Caught plotting error: Bitfield plotting not supported by CPU
> [532] Failed to execute script chia
> Traceback (most recent call last):
> File "chia\cmds\chia.py", line 81, in
> File "chia\cmds\chia.py", line 77, in main
> File "click\core.py", line 829, in call
> File "click\core.py", line 782, in main
> File "click\core.py", line 1259, in invoke
> File "click\core.py", line 1259, in invoke
> File "click\core.py", line 1066, in invoke
> File "click\core.py", line 610, in invoke
> File "click\decorators.py", line 21, in new_func
> File "chia\cmds\plots.py", line 135, in create_cmd
> File "chia\plotting\create_plots.py", line 176, in create_plots
> RuntimeError: Unknown exception
> 
> my plots stop at 1%

Did this work for you?  if so please close the issue
