### ISSUE TITLE
[BUG] CLI exception when harvester is non responsive

### ISSUE THREAD

**Issue by linnik** [Chia-Network/chia-blockchain#4120]
**Describe the bug**

Chia version 1.1.5.dev0
CLI raises exception when attempting to restart an unresponsive harvester
Machine has plenty of free RAM and CPU resources, I dont know what exactly is causing connection error.

```
user@bench:~$ docker exec -it chia venv/bin/chia farm summary
Connection error. Check if harvester is running at 8560                                            
Farming status: Farming   
Total chia farmed: 0.0                                                  
User transaction fees: 0.0                  
Block rewards: 0.0                                                         
Last height farmed: 0 
Plot count: Unknown              
Total size of plots: Unknown
Estimated network space: 2767.941 PiB                               
Expected time to win: Unknown
Note: log into your key using 'chia wallet show' to see rewards for each key
```
```
user@bench:~$ docker exec -it chia venv/bin/chia start all
chia_harvester: Already running, use `-r` to restart
chia_timelord_launcher: started
chia_timelord: started
chia_farmer: Already running, use `-r` to restart
chia_full_node: Already running, use `-r` to restart
chia_wallet: Already running, use `-r` to restart
```
```
user@bench:~$ docker exec -it chia venv/bin/chia start -r harvester
chia_harvester: Error, timeout.
stop failed
chia_harvester: Task exception was never retrieved
future: <Task finished name='Task-5' coro=<DaemonProxy.start.<locals>.listener() done, defined at /chia-blockchain/chia/daemon/client.py:30> exception=ConnectionClosedError('code = 1006 (connection closed abnormally [internal]), no reason')>
Traceback (most recent call last):
  File "/chia-blockchain/venv/lib/python3.8/site-packages/websockets/protocol.py", line 827, in transfer_data
    message = await self.read_message()
  File "/chia-blockchain/venv/lib/python3.8/site-packages/websockets/protocol.py", line 895, in read_message
    frame = await self.read_data_frame(max_size=self.max_size)
  File "/chia-blockchain/venv/lib/python3.8/site-packages/websockets/protocol.py", line 971, in read_data_frame
    frame = await self.read_frame(max_size)
  File "/chia-blockchain/venv/lib/python3.8/site-packages/websockets/protocol.py", line 1047, in read_frame
    frame = await Frame.read(
  File "/chia-blockchain/venv/lib/python3.8/site-packages/websockets/framing.py", line 105, in read
    data = await reader(2)
  File "/usr/lib/python3.8/asyncio/streams.py", line 723, in readexactly
    await self._wait_for_data('readexactly')
  File "/usr/lib/python3.8/asyncio/streams.py", line 517, in _wait_for_data
    await self._waiter
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/chia-blockchain/chia/daemon/client.py", line 33, in listener
    message = await self.websocket.recv()
  File "/chia-blockchain/venv/lib/python3.8/site-packages/websockets/protocol.py", line 509, in recv
    await self.ensure_open()
  File "/chia-blockchain/venv/lib/python3.8/site-packages/websockets/protocol.py", line 812, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedError: code = 1006 (connection closed abnormally [internal]), no reason
Error, timeout.
Traceback (most recent call last):
  File "venv/bin/chia", line 33, in <module>
    sys.exit(load_entry_point('chia-blockchain', 'console_scripts', 'chia')())
  File "/chia-blockchain/chia/cmds/chia.py", line 77, in main
    cli()  # pylint: disable=no-value-for-parameter
  File "/chia-blockchain/venv/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/chia-blockchain/venv/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/chia-blockchain/venv/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/chia-blockchain/venv/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/chia-blockchain/venv/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/chia-blockchain/venv/lib/python3.8/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/chia-blockchain/chia/cmds/start.py", line 14, in start_cmd
    asyncio.get_event_loop().run_until_complete(async_start(ctx.obj["root_path"], group, restart))
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/chia-blockchain/chia/cmds/start_funcs.py", line 59, in async_start
    success = msg["data"]["success"]
TypeError: 'NoneType' object is not subscriptable
```

**To Reproduce**
Exact steps are unknown.

**Expected behavior**
Exception should not happen, print a human-friendly error message?

**Screenshots**
-

**Desktop (please complete the following information):**

- OS: Ubuntu
- OS Version/Flavor: Ubuntu 18.04
- CPU: Intel Xeon 2697v2

**Additional context**
-

**Comment by linnik** [comment]
fixed in #4122
