### ISSUE TITLE
[BUG] Failed to create the chia daemon

### ISSUE THREAD

**Issue by ailtonjr01** [Chia-Network/chia-blockchain#4153]
**Describe the bug**
I am studying the platform and trying to use a server in the cloud to make the plots. I'm using a Contabo VPS with ubuntu linux operating system.
I have already performed the entire installation process and git clone ... When using the command ". ./activate" everything is ok, however when using the "chia init" command I get the following error: 
Chia directory /root/.chia/mainnet
/root/.chia/mainnet already exists, no migration action taken

with the command: "(venv) root@chiatest:~/chia-blockchain# chia start node farmer wallet" returns the following error:

Daemon not started yet
Starting daemon
Traceback (most recent call last):
  File "/root/chia-blockchain/venv/bin/chia", line 33, in <module>
    sys.exit(load_entry_point('chia-blockchain', 'console_scripts', 'chia')())
  File "/root/chia-blockchain/chia/cmds/chia.py", line 77, in main
    cli()  # pylint: disable=no-value-for-parameter
  File "/root/chia-blockchain/venv/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/root/chia-blockchain/venv/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/root/chia-blockchain/venv/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/root/chia-blockchain/venv/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/root/chia-blockchain/venv/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/root/chia-blockchain/venv/lib/python3.8/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/root/chia-blockchain/chia/cmds/chia.py", line 60, in run_daemon_cmd
    asyncio.get_event_loop().run_until_complete(async_run_daemon(ctx.obj["root_path"]))
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/root/chia-blockchain/chia/daemon/server.py", line 964, in async_run_daemon
    await ws_server.start()
  File "/root/chia-blockchain/chia/daemon/server.py", line 143, in start
    self.websocket_server = await serve(
  File "/root/chia-blockchain/venv/lib/python3.8/site-packages/websockets/server.py", line 965, in __await_impl__
    server = await self._create_server()
  File "/usr/lib/python3.8/asyncio/base_events.py", line 1463, in create_server
    raise OSError(err.errno, 'error while attempting '
OSError: [Errno 99] error while attempting to bind on address ('::1', 55400, 0, 0): cannot assign requested address
Daemon not started yet
Failed to create the chia daemon

When using chia-blockchain-gui the app simply does not connect, the message appears: "connecting to wallet" infinitely

**Comment by ailtonjr01** [comment]
Thanksss, this is funcional for me! you are monster of linux!

**Comment by 035uros** [comment]
Hi, I had the same problem. But after changing couple of the lines I got this:

` File "/mnt/chia-blockchain/venv/bin/chia_timelord_launcher", line 33, in <module>
    sys.exit(load_entry_point('chia-blockchain', 'console_scripts', 'chia_timelord_launcher')())
  File "/mnt/chia-blockchain/chia/timelord/timelord_launcher.py", line 107, in main
    loop.run_until_complete(spawn_all_processes(config, net_config))
  File "/usr/local/lib/python3.7/asyncio/base_events.py", line 587, in run_until_complete
    return future.result()
  File "/mnt/chia-blockchain/chia/timelord/timelord_launcher.py", line 85, in spawn_all_processes
    await asyncio.gather(*awaitables)
  File "/mnt/chia-blockchain/chia/timelord/timelord_launcher.py", line 45, in spawn_process
    path_to_vdf_client = find_vdf_client()
  File "/mnt/chia-blockchain/chia/timelord/timelord_launcher.py", line 39, in find_vdf_client
    raise FileNotFoundError("can't find vdf_client binary")
FileNotFoundError: can't find vdf_client binary`

Everything else seems just fine, wallet and farmer started without any problems!
Thanks for helping us!

**Comment by stikbomb** [comment]
You do not need to start timelord in common case especially if you don't know what to do. you can start full_node/harvester/farmer depending on what you need.

**Comment by 035uros** [comment]
So I do not need to touch that. Thanks!
