### ISSUE TITLE
im lost help! [BUG]

### ISSUE THREAD

**Issue by Lexxir1** [Chia-Network/chia-blockchain#4154]
AttributeError: 'list' object has no attribute 'pid'
2021-05-07T23:44:44.652 full_node chia.full_node.full_node: WARNING  Wasn't able to add transaction with id 67afd567a5d7c356cedafdaf726f1b503f0597d248b0000f1af7384c158461d4, status 3 error: Err.DOUBLE_SPEND
2021-05-07T23:44:44.652 full_node chia.full_node.full_node: WARNING  Wasn't able to add transaction with id 26b9a2863b012767cd92fbf08e55e69fb6327d40bdff619cfbb0f550ff7af647, status 3 error: Err.DOUBLE_SPEND
2021-05-07T23:44:44.652 full_node chia.full_node.full_node: WARNING  Wasn't able to add transaction with id 92e66515761ca676987042b010c8443b58c3e504ce70ab7160ba7d30b73ffd74, status 3 error: Err.DOUBLE_SPEND
2021-05-07T23:44:44.652 full_node chia.full_node.full_node: WARNING  Wasn't able to add transaction with id 20086208863a130c344dbb7de5d9b860711107179611f415813307c93bf41528, status 3 error: Err.DOUBLE_SPEND
2021-05-07T23:47:03.096 full_node chia.full_node.full_node: WARNING  Wasn't able to add transaction with id 1db03fafec859be796c8a92ae1ca414fb399fa688c0222a6545b017fa3c65cfe, status 3 error: Err.DOUBLE_SPEND
2021-05-07T23:47:22.976 full_node chia.full_node.full_node: WARNING  Wasn't able to add transaction with id aef84dc815ceacdd23fe1c2a29d167e93fdb074674604a82e3c25b0bfa9e9122, status 3 error: Err.DOUBLE_SPEND
2021-05-07T23:47:53.723 full_node chia.full_node.full_node: WARNING  Wasn't able to add transaction with id 353d050eaaeb058811871908d10309a9d72d85ee5b408689fe6554243ae3da08, status 3 error: Err.DOUBLE_SPEND
2021-05-07T23:47:53.761 full_node chia.full_node.full_node: WARNING  Wasn't able to add transaction with id f36cfdd954786a1a910838c9191fd00cc0b9e8857761e8541e4084f174eb8d09, status 3 error: Err.DOUBLE_SPEND
2021-05-07T23:53:11.115 full_node chia.full_node.full_node: WARNING  Wasn't able to add transaction with id 2033567d2f9671cbda0f5c92d713b996233fb08fac55751736209b88dc754222, status 3 error: Err.DOUBLE_SPEND
2021-05-07T23:56:14.789 full_node chia.full_node.full_node: WARNING  Wasn't able to add transaction with id 71564a4a7cad88f99d06648c7963515883bed9bc745444849166082d7293ecd0, status 3 error: Err.DOUBLE_SPEND
2021-05-07T23:59:16.688 full_node chia.full_node.full_node: WARNING  Wasn't able to add transaction with id 4a061e0433088d1a7eee7a570e3d1c06396d8ef5ca4982bcb50a229ce4d43c47, status 3 error: Err.DOUBLE_SPEND
2021-05-08T00:55:37.878 full_node chia.full_node.full_node: WARNING  Wasn't able to add transaction with id 1e61fa0af2eead762f7b1acd2c83e8e79fc2ceedd1322b2516bb63037d410878, status 3 error: Err.DOUBLE_SPEND
2021-05-08T00:55:38.368 full_node chia.full_node.full_node: WARNING  Wasn't able to add transaction with id a0e63ac2742edf40abc9e60f26a3370d88a29c901cda7f2aa7f39e861ad07378, status 3 error: Err.DOUBLE_SPEND
2021-05-08T00:55:38.633 full_node chia.full_node.full_node: WARNING  Wasn't able to add transaction with id 5e3852671eeb01fb3a126e5d5f4f1f7c8fb002ae631febe11dad0aa6001d7dd4, status 3 error: Err.DOUBLE_SPEND
2021-05-08T01:27:10.232 full_node chia.full_node.full_node: ERROR    Exception in create outbound connections: 
2021-05-08T01:27:10.233 full_node chia.full_node.full_node: ERROR    Traceback: Traceback (most recent call last):
  File "chia\server\node_discovery.py", line 325, in _connect_to_peers
  File "asyncio\tasks.py", line 595, in sleep
concurrent.futures._base.CancelledError

**Comment by Lexxir1** [comment]
:( my life sucks, help please or send nudes XD

021-05-08T05:51:00.878 full_node full_node_server        : ERROR    Exception: Failed to fetch block 249400 from {'host': '219.70.13.71', 'port': 8444}, timed out <class 'ValueError'>, closing connection {'host': '219.70.13.71', 'port': 8444}. Traceback (most recent call last):
  File "chia\server\server.py", line 531, in api_call
  File "asyncio\tasks.py", line 414, in wait_for
  File "chia\server\server.py", line 528, in wrapped_coroutine
  File "chia\server\server.py", line 521, in wrapped_coroutine
  File "chia\full_node\full_node_api.py", line 104, in new_peak
  File "chia\full_node\full_node.py", line 361, in new_peak
  File "chia\full_node\full_node.py", line 310, in short_sync_backtrack
  File "chia\full_node\full_node.py", line 295, in short_sync_backtrack
ValueError: Failed to fetch block 249400 from {'host': '219.70.13.71', 'port': 8444}, timed out

2021-05-08T05:51:01.209 full_node full_node_server        : WARNING  Banning 219.70.13.71 for 10 seconds
2021-05-08T05:58:35.563 full_node chia.full_node.full_node: WARNING  Wasn't able to add transaction with id ad331919130f1fe27aebe61148b9df8a869225e4c2a0ae59549455deba8abcc1, status 3 error: Err.DOUBLE_SPEND
2021-05-08T06:04:04.525 full_node chia.full_node.full_node: WARNING  Wasn't able to add transaction with id 24e5f2f3f8a8ff9b5b5e5d09a88c948fa462d5c06f55cd2a9e8ad9c955ff7f1d, status 3 error: Err.DOUBLE_SPEND
2021-05-08T06:04:06.288 full_node chia.full_node.full_node: WARNING  Wasn't able to add transaction with id 1f2c613030f31cd85c2fef9473a22663bc5aad93876b3dcca2637d84148f7710, status 3 error: Err.DOUBLE_SPEND
2021-05-08T06:09:29.379 full_node chia.full_node.full_node: WARNING  Wasn't able to add transaction with id 24e5f2f3f8a8ff9b5b5e5d09a88c948fa462d5c06f55cd2a9e8ad9c955ff7f1d, status 3 error: Err.DOUBLE_SPEND
2021-05-08T06:09:29.459 full_node chia.full_node.full_node: WARNING  Wasn't able to add transaction with id 1f2c613030f31cd85c2fef9473a22663bc5aad93876b3dcca2637d84148f7710, status 3 error: Err.DOUBLE_SPEND
2021-05-08T06:09:29.550 full_node chia.full_node.full_node: WARNING  Wasn't able to add transaction with id 49931f1e6c3293aee43186807d076e3b0bb15e5736cc05a755d1cf2f341b062f, status 3 error: Err.DOUBLE_SPEND
2021-05-08T06:09:29.648 full_node chia.full_node.full_node: WARNING  Wasn't able to add transaction with id 0059b1c72a14b62fbca1979f7263cc09bf02bee95b34eda402fe67edbf2cb4e7, status 3 error: Err.DOUBLE_SPEND
2021-05-08T06:09:29.911 full_node chia.full_node.full_node: WARNING  Wasn't able to add transaction with id 6e7c595c475a918e6a17f97313db90392370353e73e7917a5b95459ecffd0caf, status 3 error: Err.DOUBLE_SPEND
2021-05-08T06:09:30.122 full_node chia.full_node.full_node: WARNING  Wasn't able to add transaction with id 0301f5c4543d8c32072b797a5f4c71c236a408e53e062924bdcb4a93fb2c5ae0, status 3 error: Err.DOUBLE_SPEND
2021-05-08T06:09:30.180 full_node chia.full_node.full_node: WARNING  Wasn't able to add transaction with id a906361015bce7d345d09ecf5ef838ff4ba2273ed88bdc0dd1ee9d08107c159b, status 3 error: Err.DOUBLE_SPEND
2021-05-08T06:34:17.923 full_node full_node_server        : WARNING  Cannot write to closing transport 178.237.240.148
2021-05-08T07:29:05.120 full_node chia.full_node.full_node: WARNING  Wasn't able to add transaction with id 19849e312e2fbfcce87d02e78f56f0da8be0a34aafa7aae931db3b9e092714e0, status 3 error: Err.DOUBLE_SPEND
2021-05-08T07:29:05.562 full_node chia.full_node.full_node: WARNING  Wasn't able to add transaction with id 81989d388895ef8960335fe9490e032adfba67761aea0f61f5b599da1c7a6b91, status 3 error: Err.DOUBLE_SPEND
2021-05-08T07:29:05.622 full_node chia.full_node.full_node: WARNING  Wasn't able to add transaction with id a943ce8fa4be0c59020dbe08f044f98d0f71a9e8286f2cbd0907af18e0184cb2, status 3 error: Err.DOUBLE_SPEND
2021-05-08T07:33:51.611 full_node chia.full_node.full_node: WARNING  Wasn't able to add transaction with id 723d6b46ec46db8c9e7471d7cb935ebcd81384bae2a20a7062b1d382693a779b, status 3 error: Err.DOUBLE_SPEND
2021-05-08T07:36:02.486 full_node chia.full_node.full_node: WARNING  Wasn't able to add transaction with id 926c074c04a38361b0b7fc817818ae17b97c16e1fc93964da81f1d5d8360915c, status 3 error: Err.DOUBLE_SPEND
2021-05-08T07:37:26.137 full_node chia.full_node.full_node: WARNING  Wasn't able to add transaction with id 1b2296b84df1185bd687449a8e2e3e6ee28379656d8b9baba612f654772581a1, status 3 error: Err.DOUBLE_SPEND
2021-05-08T07:37:26.378 full_node chia.full_node.full_node: WARNING  Wasn't able to add transaction with id fbfdca6b9ed77dc4a5ae6b87d82ae554a1c7e7a6479fe5ed95e638452fd9b099, status 3 error: Err.DOUBLE_SPEND
2021-05-08T07:37:26.388 full_node chia.full_node.full_node: WARNING  Wasn't able to add transaction with id 2204a145a85016d0c55d9aa024e30dbeabfd277330f6363c132754613de5ded5, status 3 error: Err.DOUBLE_SPEND
2021-05-08T07:37:26.390 full_node chia.full_node.full_node: WARNING  Wasn't able to add transaction with id ffbf6e6d4ddfe9ffe050a74037f7df089491dbf911f7b8b3a9fc2490aa334e8a, status 3 error: Err.DOUBLE_SPEND
2021-05-08T07:37:26.438 full_node chia.full_node.full_node: WARNING  Wasn't able to add transaction with id 05b428ad205bc713823fc92050bb9ec83a2153a2823ee092003f1d5780b87746, status 3 error: Err.DOUBLE_SPEND
2021-05-08T07:37:26.440 full_node chia.full_node.full_node: WARNING  Wasn't able to add transaction with id fd10cdb358ec54a509ae142d0a783726e70404df4eda6d6c8083fd588a56ab47, status 3 error: Err.DOUBLE_SPEND
2021-05-08T07:37:26.468 full_node chia.full_node.full_node: WARNING  Wasn't able to add transaction with id 579d7670237540750af76f516d8648260238bedd6058165cde70ed65cf5ad7c9, status 3 error: Err.DOUBLE_SPEND
2021-05-08T07:37:26.490 full_node chia.full_node.full_node: WARNING  Wasn't able to add transaction with id 9995282e8f87aeeb73dd20b9cde7ec88864bbccfa6fe394371efaef9df0c530a, status 3 error: Err.DOUBLE_SPEND
2021-05-08T07:37:26.580 full_node chia.full_node.full_node: WARNING  Wasn't able to add transaction with id 2a5243249c6b7f96b28a2a45861bcee46e545b4c684b3db972923840babe5aa0, status 3 error: Err.DOUBLE_SPEND
2021-05-08T07:37:26.580 full_node chia.full_node.full_node: WARNING  Wasn't able to add transaction with id 7510a3a6f390a9be32ef962f248628c0beff97bee9c4bd30a2738bc1875708da, status 3 error: Err.DOUBLE_SPEND

**Comment by Lexxir1** [comment]
chia.full_node.full_node: ERROR    Consensus error 124, not disconnecting

NOW THIS???
