### ISSUE TITLE
Failed building wheel for blspy on i686

### ISSUE THREAD

**Issue by zenone87** [Chia-Network/chia-blockchain#4168]
Hi all,

I am using Debian i686 (it is an old laptop). When trying to compile chia-blockchain from source, following the guide on these pages, I get this error

```
: error: unknown type name ‘__uint128_t’
     113 | typedef __uint128_t;
 ERROR: Failed building wheel for blspy
```

Below the full log of the error

```
  [  3%] Building C object _deps/relic-build/src/CMakeFiles/relic_s.dir/relic_core.c.o
  In file included from /tmp/pip-install-4yo1e8ye/blspy_7deea107cc544c96aae56fd05dccd3ab/build/temp.linux-i686-3.9/_deps/relic-src/include/relic_arch.h:39,
                   from /tmp/pip-install-4yo1e8ye/blspy_7deea107cc544c96aae56fd05dccd3ab/build/temp.linux-i686-3.9/_deps/relic-src/include/relic_util.h:39,
                   from /tmp/pip-install-4yo1e8ye/blspy_7deea107cc544c96aae56fd05dccd3ab/build/temp.linux-i686-3.9/_deps/relic-src/include/relic_err.h:43,
                   from /tmp/pip-install-4yo1e8ye/blspy_7deea107cc544c96aae56fd05dccd3ab/build/temp.linux-i686-3.9/_deps/relic-src/include/relic_core.h:44,
                   from /tmp/pip-install-4yo1e8ye/blspy_7deea107cc544c96aae56fd05dccd3ab/build/temp.linux-i686-3.9/_deps/relic-src/src/relic_core.c:36:
  /tmp/pip-install-4yo1e8ye/blspy_7deea107cc544c96aae56fd05dccd3ab/build/temp.linux-i686-3.9/_deps/relic-src/include/relic_types.h:113:9: error: unknown type name ‘__uint128_t’
    113 | typedef __uint128_t dbl_t;
        |         ^~~~~~~~~~~
  In file included from /tmp/pip-install-4yo1e8ye/blspy_7deea107cc544c96aae56fd05dccd3ab/build/temp.linux-i686-3.9/_deps/relic-src/include/relic_arch.h:39,
                   from /tmp/pip-install-4yo1e8ye/blspy_7deea107cc544c96aae56fd05dccd3ab/build/temp.linux-i686-3.9/_deps/relic-src/include/relic_util.h:39,
                   from /tmp/pip-install-4yo1e8ye/blspy_7deea107cc544c96aae56fd05dccd3ab/build/temp.linux-i686-3.9/_deps/relic-src/include/relic_err.h:43,
                   from /tmp/pip-install-4yo1e8ye/blspy_7deea107cc544c96aae56fd05dccd3ab/build/temp.linux-i686-3.9/_deps/relic-src/include/relic_core.h:44,
                   from /tmp/pip-install-4yo1e8ye/blspy_7deea107cc544c96aae56fd05dccd3ab/build/temp.linux-i686-3.9/_deps/relic-src/src/relic_err.c:37:
  /tmp/pip-install-4yo1e8ye/blspy_7deea107cc544c96aae56fd05dccd3ab/build/temp.linux-i686-3.9/_deps/relic-src/include/relic_types.h:113:9: error: unknown type name ‘__uint128_t’
    113 | typedef __uint128_t dbl_t;
        |         ^~~~~~~~~~~
  gmake[2]: *** [_deps/relic-build/src/CMakeFiles/relic_s.dir/build.make:82: _deps/relic-build/src/CMakeFiles/relic_s.dir/relic_err.c.o] Errore 1
  gmake[2]: *** Attesa per i processi non terminati....
  gmake[2]: *** [_deps/relic-build/src/CMakeFiles/relic_s.dir/build.make:95: _deps/relic-build/src/CMakeFiles/relic_s.dir/relic_core.c.o] Errore 1
  gmake[1]: *** [CMakeFiles/Makefile2:338: _deps/relic-build/src/CMakeFiles/relic_s.dir/all] Errore 2
  gmake[1]: *** Attesa per i processi non terminati....
  In file included from /tmp/pip-install-4yo1e8ye/blspy_7deea107cc544c96aae56fd05dccd3ab/build/temp.linux-i686-3.9/_deps/relic-src/include/relic_arch.h:39,
                   from /tmp/pip-install-4yo1e8ye/blspy_7deea107cc544c96aae56fd05dccd3ab/build/temp.linux-i686-3.9/_deps/relic-src/include/relic.h:81,
                   from /tmp/pip-install-4yo1e8ye/blspy_7deea107cc544c96aae56fd05dccd3ab/src/elements.hpp:19,
                   from /tmp/pip-install-4yo1e8ye/blspy_7deea107cc544c96aae56fd05dccd3ab/src/privatekey.hpp:24,
                   from /tmp/pip-install-4yo1e8ye/blspy_7deea107cc544c96aae56fd05dccd3ab/src/bls.hpp:18,
                   from /tmp/pip-install-4yo1e8ye/blspy_7deea107cc544c96aae56fd05dccd3ab/src/privatekey.cpp:15:
  /tmp/pip-install-4yo1e8ye/blspy_7deea107cc544c96aae56fd05dccd3ab/build/temp.linux-i686-3.9/_deps/relic-src/include/relic_types.h:113:9: error: ‘__uint128_t’ does not name a type; did you mean ‘__uint32_t’?
    113 | typedef __uint128_t dbl_t;
        |         ^~~~~~~~~~~
        |         __uint32_t
  In file included from /tmp/pip-install-4yo1e8ye/blspy_7deea107cc544c96aae56fd05dccd3ab/build/temp.linux-i686-3.9/_deps/relic-src/include/relic_arch.h:39,
                   from /tmp/pip-install-4yo1e8ye/blspy_7deea107cc544c96aae56fd05dccd3ab/build/temp.linux-i686-3.9/_deps/relic-src/include/relic.h:81,
                   from /tmp/pip-install-4yo1e8ye/blspy_7deea107cc544c96aae56fd05dccd3ab/src/elements.hpp:19,
                   from /tmp/pip-install-4yo1e8ye/blspy_7deea107cc544c96aae56fd05dccd3ab/src/privatekey.hpp:24,
                   from /tmp/pip-install-4yo1e8ye/blspy_7deea107cc544c96aae56fd05dccd3ab/src/bls.hpp:18,
                   from /tmp/pip-install-4yo1e8ye/blspy_7deea107cc544c96aae56fd05dccd3ab/src/elements.cpp:17:
  /tmp/pip-install-4yo1e8ye/blspy_7deea107cc544c96aae56fd05dccd3ab/build/temp.linux-i686-3.9/_deps/relic-src/include/relic_types.h:113:9: error: ‘__uint128_t’ does not name a type; did you mean ‘__uint32_t’?
    113 | typedef __uint128_t dbl_t;
        |         ^~~~~~~~~~~
        |         __uint32_t
  In file included from /tmp/pip-install-4yo1e8ye/blspy_7deea107cc544c96aae56fd05dccd3ab/build/temp.linux-i686-3.9/_deps/relic-src/include/relic_arch.h:39,
                   from /tmp/pip-install-4yo1e8ye/blspy_7deea107cc544c96aae56fd05dccd3ab/build/temp.linux-i686-3.9/_deps/relic-src/include/relic.h:81,
                   from /tmp/pip-install-4yo1e8ye/blspy_7deea107cc544c96aae56fd05dccd3ab/src/elements.hpp:19,
                   from /tmp/pip-install-4yo1e8ye/blspy_7deea107cc544c96aae56fd05dccd3ab/src/privatekey.hpp:24,
                   from /tmp/pip-install-4yo1e8ye/blspy_7deea107cc544c96aae56fd05dccd3ab/src/bls.hpp:18,
                   from /tmp/pip-install-4yo1e8ye/blspy_7deea107cc544c96aae56fd05dccd3ab/src/bls.cpp:15:
  /tmp/pip-install-4yo1e8ye/blspy_7deea107cc544c96aae56fd05dccd3ab/build/temp.linux-i686-3.9/_deps/relic-src/include/relic_types.h:113:9: error: ‘__uint128_t’ does not name a type; did you mean ‘__uint32_t’?
    113 | typedef __uint128_t dbl_t;
        |         ^~~~~~~~~~~
        |         __uint32_t
  In file included from /tmp/pip-install-4yo1e8ye/blspy_7deea107cc544c96aae56fd05dccd3ab/build/temp.linux-i686-3.9/_deps/relic-src/include/relic_arch.h:39,
                   from /tmp/pip-install-4yo1e8ye/blspy_7deea107cc544c96aae56fd05dccd3ab/build/temp.linux-i686-3.9/_deps/relic-src/include/relic.h:81,
                   from /tmp/pip-install-4yo1e8ye/blspy_7deea107cc544c96aae56fd05dccd3ab/src/elements.hpp:19,
                   from /tmp/pip-install-4yo1e8ye/blspy_7deea107cc544c96aae56fd05dccd3ab/src/privatekey.hpp:24,
                   from /tmp/pip-install-4yo1e8ye/blspy_7deea107cc544c96aae56fd05dccd3ab/src/bls.hpp:18,
                   from /tmp/pip-install-4yo1e8ye/blspy_7deea107cc544c96aae56fd05dccd3ab/src/schemes.cpp:18:
  /tmp/pip-install-4yo1e8ye/blspy_7deea107cc544c96aae56fd05dccd3ab/build/temp.linux-i686-3.9/_deps/relic-src/include/relic_types.h:113:9: error: ‘__uint128_t’ does not name a type; did you mean ‘__uint32_t’?
    113 | typedef __uint128_t dbl_t;
        |         ^~~~~~~~~~~
        |         __uint32_t
  gmake[2]: *** [src/CMakeFiles/blstmp.dir/build.make:95: src/CMakeFiles/blstmp.dir/bls.cpp.o] Errore 1
  gmake[2]: *** Attesa per i processi non terminati....
  gmake[2]: *** [src/CMakeFiles/blstmp.dir/build.make:82: src/CMakeFiles/blstmp.dir/privatekey.cpp.o] Errore 1
  gmake[2]: *** [src/CMakeFiles/blstmp.dir/build.make:108: src/CMakeFiles/blstmp.dir/elements.cpp.o] Errore 1
  gmake[2]: *** [src/CMakeFiles/blstmp.dir/build.make:121: src/CMakeFiles/blstmp.dir/schemes.cpp.o] Errore 1
  gmake[1]: *** [CMakeFiles/Makefile2:284: src/CMakeFiles/blstmp.dir/all] Errore 2
  gmake: *** [Makefile:149: all] Errore 2
  Traceback (most recent call last):
    File "/home/claudio/chia-blockchain/venv/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 280, in <module>
      main()
    File "/home/claudio/chia-blockchain/venv/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 263, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/home/claudio/chia-blockchain/venv/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 204, in build_wheel
      return _build_backend().build_wheel(wheel_directory, config_settings,
    File "/tmp/pip-build-env-crka6osi/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 221, in build_wheel
      return self._build_with_temp_dir(['bdist_wheel'], '.whl',
    File "/tmp/pip-build-env-crka6osi/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 207, in _build_with_temp_dir
      self.run_setup()
    File "/tmp/pip-build-env-crka6osi/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 150, in run_setup
      exec(compile(code, __file__, 'exec'), locals())
    File "setup.py", line 206, in <module>
      setup(
    File "/tmp/pip-build-env-crka6osi/overlay/lib/python3.9/site-packages/setuptools/__init__.py", line 153, in setup
      return distutils.core.setup(**attrs)
    File "/usr/lib/python3.9/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/usr/lib/python3.9/distutils/dist.py", line 966, in run_commands
      self.run_command(cmd)
    File "/usr/lib/python3.9/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/tmp/pip-build-env-crka6osi/overlay/lib/python3.9/site-packages/wheel/bdist_wheel.py", line 299, in run
      self.run_command('build')
    File "/usr/lib/python3.9/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/lib/python3.9/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/usr/lib/python3.9/distutils/command/build.py", line 135, in run
      self.run_command(cmd_name)
    File "/usr/lib/python3.9/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/lib/python3.9/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "setup.py", line 38, in run
      self.build_extension(ext)
    File "setup.py", line 70, in build_extension
      subprocess.check_call(
    File "/usr/lib/python3.9/subprocess.py", line 373, in check_call
      raise CalledProcessError(retcode, cmd)
  subprocess.CalledProcessError: Command '['cmake', '--build', '.', '--config', 'Release', '--', '-j', '6']' returned non-zero exit status 2.
  ----------------------------------------
  ERROR: Failed building wheel for blspy
```
The same happens for other components, e.g., chiapos, chiavdf, ...

How could I solve this issue?

Thank you.

**Comment by JCAK1967** [comment]
The same problem with Debian-10.9.0-i386-netinst.iso

Please Help !!!!

**Comment by JCAK1967** [comment]
> This issue has been flagged as stale as there has been no activity on it in 14 days. If this issue is still affecting you and in need of review, please update it to keep it open.

No solution yet. I would appreciate a 32-bit version to be able to take advantage of old equipment.
