### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by rexhzhang** [Chia-Network/chia-blockchain#4182]
**Expected behavior**
Expect to have synced with the mainnet

**Screenshots**
![image](https://user-images.githubusercontent.com/25043064/117537630-20da8580-afb7-11eb-8f1c-e21f47404050.png)

**Desktop (please complete the following information):**

- OS: Windows 10
- OS Version/Flavor: Latest Windows 10 version
- CPU: i5-9600k

**Additional context**

LOG:
```
2021-05-08T04:05:57.804 harvester chia.harvester.harvester: WARNING  Not farming any plots on this harvester. Check your configuration.
2021-05-08T04:06:10.572 full_node full_node_server        : ERROR    Exception Trying to connect to a peer ({'host': 'introducer.chia.net', 'port': 8444}) with the same peer_id: 0afa748b8ef8fa05a8d4426a2dd3800ccca7a7d5ee5dbbc3399709d2e26a351f, exception Stack: Traceback (most recent call last):
  File "chia\server\server.py", line 373, in start_client
RuntimeError: Trying to connect to a peer ({'host': 'introducer.chia.net', 'port': 8444}) with the same peer_id: 0afa748b8ef8fa05a8d4426a2dd3800ccca7a7d5ee5dbbc3399709d2e26a351f

2021-05-08T04:06:13.432 wallet chia.rpc.wallet_rpc_api    : ERROR    error 0, message='Attempt to decode JSON with unexpected mimetype: text/plain; charset=utf-8', url=URL('https://backup.chia.net/download_backup')
2021-05-08T04:06:17.604 full_node full_node_server        : ERROR    Exception Trying to connect to a peer ({'host': 'introducer.chia.net', 'port': 8444}) with the same peer_id: 0afa748b8ef8fa05a8d4426a2dd3800ccca7a7d5ee5dbbc3399709d2e26a351f, exception Stack: Traceback (most recent call last):
  File "chia\server\server.py", line 373, in start_client
RuntimeError: Trying to connect to a peer ({'host': 'introducer.chia.net', 'port': 8444}) with the same peer_id: 0afa748b8ef8fa05a8d4426a2dd3800ccca7a7d5ee5dbbc3399709d2e26a351f

2021-05-08T04:06:26.657 full_node full_node_server        : ERROR    Exception Trying to connect to a peer ({'host': 'introducer.chia.net', 'port': 8444}) with the same peer_id: 0afa748b8ef8fa05a8d4426a2dd3800ccca7a7d5ee5dbbc3399709d2e26a351f, exception Stack: Traceback (most recent call last):
  File "chia\server\server.py", line 373, in start_client
RuntimeError: Trying to connect to a peer ({'host': 'introducer.chia.net', 'port': 8444}) with the same peer_id: 0afa748b8ef8fa05a8d4426a2dd3800ccca7a7d5ee5dbbc3399709d2e26a351f

2021-05-08T04:06:39.717 full_node full_node_server        : ERROR    Exception Trying to connect to a peer ({'host': 'introducer.chia.net', 'port': 8444}) with the same peer_id: 0afa748b8ef8fa05a8d4426a2dd3800ccca7a7d5ee5dbbc3399709d2e26a351f, exception Stack: Traceback (most recent call last):
  File "chia\server\server.py", line 373, in start_client
RuntimeError: Trying to connect to a peer ({'host': 'introducer.chia.net', 'port': 8444}) with the same peer_id: 0afa748b8ef8fa05a8d4426a2dd3800ccca7a7d5ee5dbbc3399709d2e26a351f

2021-05-08T04:07:00.843 full_node full_node_server        : ERROR    Exception Trying to connect to a peer ({'host': 'introducer.chia.net', 'port': 8444}) with the same peer_id: 0afa748b8ef8fa05a8d4426a2dd3800ccca7a7d5ee5dbbc3399709d2e26a351f, exception Stack: Traceback (most recent call last):
  File "chia\server\server.py", line 373, in start_client
RuntimeError: Trying to connect to a peer ({'host': 'introducer.chia.net', 'port': 8444}) with the same peer_id: 0afa748b8ef8fa05a8d4426a2dd3800ccca7a7d5ee5dbbc3399709d2e26a351f

2021-05-08T04:08:38.348 full_node asyncio                 : ERROR    Task exception was never retrieved
future: <Task finished coro=<WebSocketWriter.ping() done, defined at aiohttp\http_websocket.py:669> exception=ConnectionResetError('Cannot write to closing transport')>
Traceback (most recent call last):
  File "aiohttp\http_websocket.py", line 673, in ping
  File "aiohttp\http_websocket.py", line 643, in _send_frame
  File "aiohttp\http_websocket.py", line 660, in _write
ConnectionResetError: Cannot write to closing transport
2021-05-08T04:08:47.071 full_node full_node_server        : ERROR    Exception Trying to connect to a peer ({'host': 'introducer.chia.net', 'port': 8444}) with the same peer_id: 0afa748b8ef8fa05a8d4426a2dd3800ccca7a7d5ee5dbbc3399709d2e26a351f, exception Stack: Traceback (most recent call last):
  File "chia\server\server.py", line 373, in start_client
RuntimeError: Trying to connect to a peer ({'host': 'introducer.chia.net', 'port': 8444}) with the same peer_id: 0afa748b8ef8fa05a8d4426a2dd3800ccca7a7d5ee5dbbc3399709d2e26a351f
```

**Comment by bizzqu1t** [comment]
Hey, did u solved your problem?

**Comment by rexhzhang** [comment]
Yes I managed to debug the problem myself

**Comment by simseb** [comment]
> Yes I managed to debug the problem myself

and what was the issue?

**Comment by Kusey86** [comment]
?
