### ISSUE TITLE
[BUG][HIGH PRIORITY] GUI Stuck Loading, CLI Connection error. Check if wallet is running at 9256

### ISSUE THREAD

**Issue by CMEONE** [Chia-Network/chia-blockchain#4245]
EDIT: SEE THE MOST RECENT COMMENT

**Describe the bug**
I have been using my wallet for many days, synced, and confirmed that transactions are being confirmed on-chain.

After my wallet crashed today, the GUI would be stuck on the "Connecting to wallet" screen. From the console:
```
Already connected, not reconnecting.          main.js:1
1          main.js:1
Already connected, not reconnecting.          main.js:1
1          main.js:1
Already connected, not reconnecting.          main.js:1
1          main.js:1
Already connected, not reconnecting.          main.js:1
1          main.js:1
Already connected, not reconnecting.          main.js:1
1          main.js:1
```

I tried to use the CLI instead, but after using `chia wallet show`, I got the following error:
```
Connection error. Check if wallet is running at 9256
```
Going to `localhost:9256` does not produce any results (This site can’t be reached, localhost refused to connect.)

**To Reproduce**

1. Open the wallet
2. Make your wallet crash
3. Open the wallet again

**Expected behavior**
Wallet should load in the GUI or CLI.

**Desktop (please complete the following information):**

- OS: MacOS
- OS Version/Flavor: Catalina 10.15

**Comment by CMEONE** [comment]
Here is some additional debug info:
```
user > chia start all

chia_harvester: started
chia_timelord_launcher: chia_timelord_launcher failed to start. Error: start failed
chia_timelord: started
chia_farmer: started
chia_full_node: started
chia_wallet: started

daemon > Traceback (most recent call last):

  File "chia/server/start_wallet.py", line 97, in <module>
  File "chia/server/start_wallet.py", line 92, in main
  File "chia/server/start_service.py", line 218, in run_service
  File "asyncio/runners.py", line 44, in run
  File "asyncio/base_events.py", line 642, in run_until_complete
  File "chia/server/start_service.py", line 212, in async_run_service
  File "chia/server/start_service.py", line 156, in run
  File "chia/server/start_service.py", line 127, in start
  File "chia/wallet/wallet_node.py", line 151, in _start
  File "chia/wallet/wallet_state_manager.py", line 138, in create
  File "chia/wallet/wallet_blockchain.py", line 106, in create
  File "chia/wallet/wallet_blockchain.py", line 117, in _load_chain_from_store
  File "chia/wallet/wallet_block_store.py", line 283, in get_peak_heights_dicts
KeyError: redacted
[2810] Failed to execute script start_wallet
Traceback (most recent call last):
  File "chia/server/start_full_node.py", line 65, in <module>
  File "chia/server/start_full_node.py", line 60, in main
  File "chia/server/start_service.py", line 218, in run_service
  File "asyncio/runners.py", line 44, in run
  File "asyncio/base_events.py", line 642, in run_until_complete
  File "chia/server/start_service.py", line 212, in async_run_service
  File "chia/server/start_service.py", line 156, in run
  File "chia/server/start_service.py", line 127, in start
  File "chia/full_node/full_node.py", line 126, in _start
  File "chia/consensus/blockchain.py", line 111, in create
  File "chia/consensus/blockchain.py", line 139, in _load_chain_from_store
AssertionError
[2809] Failed to execute script start_full_node

**Comment by CMEONE** [comment]
I think this is fixed now (I can load the wallet), but I had to manually repair the SQL wallet database (`~/.chia/mainnet/wallet/db.blockchain_wallet_v1_mainnet_NUMBER.sqlite`), made sure that the `header_blocks` and `block_records` were of the same length, had the same end height, and same ending records (I just chopped off around 30 records to be safe). The full node and wallet are both synced.

I'm leaving this open for one very important reason. **When you don't handle database table discrepancies from unnecessarily duplicating data, your code is unfortunately not suitable for production.** Although the issue isn't critical, many people are experiencing this exact problem, which will hurt the Chia image as a whole. I highly recommend adding some database validation and **actually handling when the database doesn't line up by truncating some records (not deleting the entire thing because people do not want to resync) instead of crashing**.

**Comment by DaChiaGuy** [comment]
Well I had the same issue and it's solution is magically simple
1- You got to force stop Chia application and end it's task from the task manager, or simply reboot your pc.
2- delete the following files

C:/Users/"PC-name"/.chia

C:/Users/"PC-name"/AppData/Local/chia-blockchain

C:/Users/"PC-name"/AppDate/Roaming/Chia Blockchain

3- reinstall the the latest chia version.

That's it.

**Comment by mrzana** [comment]
I have the problem on ubuntu server 20.10. Does anybody know a solution (without change the db?)

**Comment by yuebaixiao** [comment]
> My problem is now solved. The problem was a corrupted wallet. Th solution was:
> 
> chia stop wallet-only (ignore if it says not running)
> mv ~/.chia/mainnet/wallet/db/_blockchain_ ~/
> chia start wallet-only
> chia wallet show (if it ask about backup, S to skip)
> 
> ok, so we can clean up after us, with rm ~/_wallet_v1_
> and you should be back with a fully synced wallet in 12-24 hours

thanks a lot

**Comment by evilstack** [comment]
+1 on this. I am keeping the corrupted wallet DB in case it can be of any use for debugging.

**Comment by jrial** [comment]
> Hi guys, Can you tell me how to repair the SQL wallet database manually ?

Before doing this, it's best to take a backup of the DB file (`~/.chia/mainnet/wallet/db.blockchain_wallet_v1_mainnet_NUMBER.sqlite`), in case you accidentally mess up.

The easiest way is to install sqlitebrowser, and use it to open the file. It has a graphical interface, which is more accessible for people who don't know SQL. Look for the tables `header_blocks` and `block_records`. Scroll all the way down, and delete the bottom 10-20 records, making sure both tables contain the same number of records when you're done. Don't forget to write the changes to disk. Then restart Chia, and see if the problem is solved.

**Comment by jrial** [comment]
Nah, I'm pretty sure bugs don't just decide to fix themselves when they notice you can't be bothered to handle them.

**Comment by Thorgrlm** [comment]
I have the same error

**Connection error. Check if the wallet is running at 9256**

**Comment by Lissanro** [comment]
> Look for the tables `header_blocks` and `block_records`. Scroll all the way down, and delete the bottom 10-20 records, making sure both tables contain the same number of records when you're done.

Thank you, this has helped me. In my case database became corrupted after I ran out of disk space on one of my 16TB drives where my home directory with chia wallet was located. I found this issue by googling. This is the traceback I was getting before I fixed the database manually:

```
Traceback (most recent call last):
  File "chia/server/start_wallet.py", line 97, in <module>
  File "chia/server/start_wallet.py", line 92, in main
  File "chia/server/start_service.py", line 226, in run_service
  File "asyncio/runners.py", line 44, in run
  File "asyncio/base_events.py", line 616, in run_until_complete
  File "chia/server/start_service.py", line 220, in async_run_service
  File "chia/server/start_service.py", line 160, in run
  File "chia/server/start_service.py", line 128, in start
  File "chia/wallet/wallet_node.py", line 153, in _start
  File "chia/wallet/wallet_state_manager.py", line 138, in create
  File "chia/wallet/wallet_blockchain.py", line 112, in create
  File "chia/wallet/wallet_blockchain.py", line 123, in _load_chain_from_store
  File "chia/wallet/wallet_block_store.py", line 283, in get_peak_heights_dicts
KeyError: b'[\x02/\x15\xe7\xece\xb2u\xc9\x19\xcb\xfc\xb38\xa7\x86\xaeXju\xf75@eE%\xb3\x86\x04^\xe2'
[1521863] Failed to execute script start_wallet
```
It would be a lot nicer if it could automatically deleted corrupted records, since it is not possible to launch the wallet otherwise.
