### ISSUE TITLE
[BUG] Key-Error - Chia wallet not loading (latest checkout)

### ISSUE THREAD

**Issue by krowll** [Chia-Network/chia-blockchain#4268]
After checking out the newest commit, I'm unable to start the wallet:

    `stderr: Traceback (most recent call last):
      File "/chia/chia-blockchain/venv/bin/chia_wallet", line 33, in <module>
    stderr:     sys.exit(load_entry_point('chia-blockchain', 'console_scripts', 'chia_wallet')())
      File "/chia/chia-blockchain/chia/server/start_wallet.py", line 92, in main
        return run_service(**kwargs)
      File "/chia/chia-blockchain/chia/server/start_service.py", line 218, in run_service
        return asyncio.run(async_run_service(*args, **kwargs))
      File "/usr/lib/python3.9/asyncio/runners.py", line 44, in run
        return loop.run_until_complete(main)
      File "/usr/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    stderr:     return future.result()
      File "/chia/chia-blockchain/chia/server/start_service.py", line 212, in async_run_service
    stderr:     return await service.run()
      File "/chia/chia-blockchain/chia/server/start_service.py", line 156, in run
        await self.start()
      File "/chia/chia-blockchain/chia/server/start_service.py", line 127, in start
        await self._node._start(**kwargs)
    stderr:   File "/chia/chia-blockchain/chia/wallet/wallet_node.py", line 151, in _start
        self.wallet_state_manager = await WalletStateManager.create(
      File "/chia/chia-blockchain/chia/wallet/wallet_state_manager.py", line 138, in create
        self.blockchain = await WalletBlockchain.create(
      File "/chia/chia-blockchain/chia/wallet/wallet_blockchain.py", line 106, in create
    stderr:     await self._load_chain_from_store()
      File "/chia/chia-blockchain/chia/wallet/wallet_blockchain.py", line 117, in _load_chain_from_store
        height_to_hash, sub_epoch_summaries = await self.block_store.get_peak_heights_dicts()
      File "/chia/chia-blockchain/chia/wallet/wallet_block_store.py", line 283, in get_peak_heights_dicts
    stderr:     curr_height = hash_to_height[curr_header_hash]
    KeyError: b'6\xe0p\xf2\xbd\xd9!a\xdf\xfe\xcc\xa1\x03\.................... (removed the last few chars)`

**Comment by OmarChia** [comment]
Same problem here

**Comment by gigipl** [comment]
Same here.

**Comment by krowll** [comment]
Just a quick follow-up:

I have now deleted

(location: ~./chia/mainnet/wallet/db/)
- blockchain_wallet_v1_mainnet_"somenumber".sqlite
and
(location: ~./chia/mainnet/db/)
- blockchain_v1_mainnet.sqlite

I have then closed and restarted chia. Unfortunately, with the deleting of the blockchain-db, you have to resync.

**Comment by baclijad** [comment]
THANKS @krowll it works ! ! !

**Comment by mcmara** [comment]
Same error for me. Deleting the files above worked, although I had to re-sync.
The error was generated probably because I ran out of space on the OS filesystem, although temporarily, while it was syncing, and that corrupted the database. It did not recover even after freeing back the SSD space.

**Comment by GuidoBartoli** [comment]
> Same error for me. Deleting the files above worked, although I had to re-sync.
> The error was generated probably because I ran out of space on the OS filesystem, although temporarily, while it was syncing, and that corrupted the database. It did not recover even after freeing back the SSD space.

Yep, the same here, but @krowll workaround worked for me, too!

**Comment by mikloskolovics** [comment]
I ran out of space yesterday and wallet keeps throwing the same error ever since.

Would it be possible to delete only the db of the wallet so I wouldn't have to re-sync for another 3 days? Or the db and wallet db are bound together?
