### ISSUE TITLE
[help] WARNING  Trying to ban localhost for 10, but will not ban

### ISSUE THREAD

**Issue by shaunlourdes84** [Chia-Network/chia-blockchain#4270]
2021-05-09T13:29:27.701 full_node full_node_server        : WARNING  Trying to ban localhost for 10, but will not ban
2021-05-09T13:29:27.701 full_node asyncio                 : ERROR    Task exception was never retrieved
future: <Task finished coro=<ChiaServer.incoming_api_task.<locals>.api_call() done, defined at chia\server\server.py:482> exception=CancelledError()>
concurrent.futures._base.CancelledError

2021-05-09T13:38:15.375 full_node chia.rpc.rpc_server     : WARNING  Error while handling message: Traceback (most recent call last):
  File "chia\rpc\rpc_server.py", line 212, in safe_handle
  File "chia\rpc\rpc_server.py", line 200, in ws_api
  File "chia\rpc\rpc_server.py", line 161, in open_connection
ValueError: Start client failed, or server is not set

I am a beginner to coding, please advise wat is this error means please

**Comment by kubalatv** [comment]
full_node full_node_server        : WARNING  Trying to ban localhost for 10, but will not ban

**Comment by 85256638** [comment]
what does this even mean?

**Comment by Elyasin** [comment]
I can find this issue in my logs too. I am curious about the meaning and a solution to this issue.
