### ISSUE TITLE
[help] ERROR    Exception:  <class 'concurrent.futures._base.CancelledError'>, closing connection

### ISSUE THREAD

**Issue by shaunlourdes84** [Chia-Network/chia-blockchain#4271]
2021-05-09T15:56:23.996 full_node full_node_server        : ERROR    Exception:  <class 'concurrent.futures._base.CancelledError'>, closing connection None. Traceback (most recent call last):
  File "chia\server\server.py", line 531, in api_call
  File "asyncio\tasks.py", line 435, in wait_for
concurrent.futures._base.CancelledError

I am new to coding can anyone advise what is this issue

**Comment by CosmicAriel** [comment]
It's still an open issue:

https://github.com/Chia-Network/chia-blockchain/issues/4045

You on Windows 10 using the GUI app, by any chance?
