### ISSUE TITLE
full_node chia.rpc.rpc_server     : WARNING

### ISSUE THREAD

**Issue by Makusm1990** [Chia-Network/chia-blockchain#4274]
2021-05-09T05:59:27.533 full_node chia.rpc.rpc_server     : WARNING  Error while handling message: Traceback (most recent call last):
  File "chia\rpc\rpc_server.py", line 81, in inner
  File "chia\rpc\rpc_server.py", line 161, in open_connection
ValueError: Start client failed, or server is not set

Win 10
Gui 1.1.4

8444 is open

**Comment by MontajnikRTA** [comment]
Same problem, don't know how to solve it

**Comment by MontajnikRTA** [comment]
hyperx@hyperx-MS-7C56:~$ cat ~/.chia/mainnet/log/debug.log | grep -i 'error'
2021-05-19T00:11:51.217 wallet chia.rpc.rpc_server        : WARNING  Error while handling message: Traceback (most recent call last):
ValueError: MAC check failed
ValueError: MAC check failed
2021-05-19T00:11:51.217 wallet asyncio                    : ERROR    Unclosed client session
2021-05-19T00:12:02.370 wallet chia.rpc.rpc_server        : WARNING  Error while handling message: Traceback (most recent call last):
KeyError: 'fingerprint'
2021-05-19T00:12:29.417 wallet chia.rpc.rpc_server        : WARNING  Error while handling message: Traceback (most recent call last):
KeyError: 'fingerprint'
2021-05-19T00:12:50.539 wallet chia.rpc.wallet_rpc_api    : ERROR    error No backup on backup service
2021-05-19T00:15:26.847 full_node chia.full_node.full_node: ERROR    Error with syncing: <class 'RuntimeError'>Traceback (most recent call last):
RuntimeError: Weight proof did not arrive in time from peer: 118.166.66.223
2021-05-19T00:16:43.342 full_node chia.full_node.full_node: ERROR    Error with syncing: <class 'RuntimeError'>Traceback (most recent call last):
RuntimeError: Weight proof did not arrive in time from peer: 178.184.52.184
2021-05-19T00:24:46.525 full_node asyncio                 : ERROR    Unclosed client session
2021-05-19T00:24:46.870 full_node chia.full_node.full_node: ERROR    Error with syncing: <class 'RuntimeError'>Traceback (most recent call last):
RuntimeError: Weight proof did not arrive in time from peer: 119.27.170.114
2021-05-19T00:54:16.749 full_node chia.rpc.rpc_server     : WARNING  Error while handling message: Traceback (most recent call last):
    raise ValueError("Start client failed, or server is not set")
ValueError: Start client failed, or server is not set
2021-05-19T00:54:47.750 full_node chia.rpc.rpc_server     : WARNING  Error while handling message: Traceback (most recent call last):
    raise ValueError("Start client failed, or server is not set")
ValueError: Start client failed, or server is not set
2021-05-19T00:55:19.750 full_node chia.rpc.rpc_server     : WARNING  Error while handling message: Traceback (most recent call last):
    raise ValueError("Start client failed, or server is not set")
ValueError: Start client failed, or server is not set
2021-05-19T00:55:50.749 full_node chia.rpc.rpc_server     : WARNING  Error while handling message: Traceback (most recent call last):
    raise ValueError("Start client failed, or server is not set")
ValueError: Start client failed, or server is not set
2021-05-19T00:56:21.749 full_node chia.rpc.rpc_server     : WARNING  Error while handling message: Traceback (most recent call last):
    raise ValueError("Start client failed, or server is not set")
ValueError: Start client failed, or server is not set
2021-05-19T00:56:58.749 full_node chia.rpc.rpc_server     : WARNING  Error while handling message: Traceback (most recent call last):
    raise ValueError("Start client failed, or server is not set")
ValueError: Start client failed, or server is not set
2021-05-19T00:57:33.749 full_node chia.rpc.rpc_server     : WARNING  Error while handling message: Traceback (most recent call last):
    raise ValueError("Start client failed, or server is not set")
ValueError: Start client failed, or server is not set
2021-05-19T00:58:33.818 full_node chia.rpc.rpc_server     : WARNING  Error while handling message: Traceback (most recent call last):
    raise ValueError("Start client failed, or server is not set")
ValueError: Start client failed, or server is not set
2021-05-19T00:59:04.749 full_node chia.rpc.rpc_server     : WARNING  Error while handling message: Traceback (most recent call last):
    raise ValueError("Start client failed, or server is not set")
ValueError: Start client failed, or server is not set
2021-05-19T01:03:21.749 full_node chia.rpc.rpc_server     : WARNING  Error while handling message: Traceback (most recent call last):
    raise ValueError("Start client failed, or server is not set")
ValueError: Start client failed, or server is not set
2021-05-19T08:09:13.905 full_node asyncio                 : ERROR    Unclosed client session
2021-05-19T08:09:16.398 daemon __main__                   : ERROR    Unexpected exception trying to send to websocket: code = 1006 (connection closed abnormally [internal]), no reason Traceback (most recent call last):
    raise exceptions.IncompleteReadError(incomplete, n)
asyncio.exceptions.IncompleteReadError: 0 bytes read on a total of 2 expected bytes
websockets.exceptions.ConnectionClosedError: code = 1006 (connection closed abnormally [internal]), no reason
2021-05-19T08:09:50.023 full_node asyncio                 : ERROR    Unclosed client session
2021-05-19T08:09:53.459 daemon __main__                   : ERROR    Unexpected exception trying to send to websocket: code = 1006 (connection closed abnormally [internal]), no reason Traceback (most recent call last):
    raise exceptions.IncompleteReadError(incomplete, n)
asyncio.exceptions.IncompleteReadError: 0 bytes read on a total of 2 expected bytes
websockets.exceptions.ConnectionClosedError: code = 1006 (connection closed abnormally [internal]), no reason
2021-05-19T08:10:42.946 wallet chia.wallet.wallet_blockchain: ERROR    Error during db transaction: 
2021-05-19T08:10:42.948 wallet chia.wallet.wallet_node    : ERROR    Error while trying to fetch from peer:no active connection Traceback (most recent call last):
asyncio.exceptions.CancelledError
    (result, error, fork_h,) = await self.wallet_state_manager.blockchain.receive_block(
    raise ValueError("no active connection")
ValueError: no active connection
2021-05-19T08:10:42.949 wallet chia.wallet.wallet_node    : ERROR    Loop exception in sync Was not able to add blocks 127071-127103. Traceback (most recent call last):
    raise RuntimeError(f"Was not able to add blocks {start_height}-{end_height}")
RuntimeError: Was not able to add blocks 127071-127103
2021-05-19T08:11:08.855 full_node chia.full_node.full_node: ERROR    Error with syncing: <class 'RuntimeError'>Traceback (most recent call last):
    raise RuntimeError(f"Weight proof did not arrive in time from peer: {weight_proof_peer.peer_host}")
RuntimeError: Weight proof did not arrive in time from peer: 121.237.60.111
2021-05-19T08:12:33.227 full_node chia.rpc.rpc_server     : WARNING  Error while handling message: Traceback (most recent call last):
    raise ValueError("Start client failed, or server is not set")
ValueError: Start client failed, or server is not set
2021-05-19T08:13:05.277 full_node chia.rpc.rpc_server     : WARNING  Error while handling message: Traceback (most recent call last):
    raise ValueError("Start client failed, or server is not set")
ValueError: Start client failed, or server is not set
2021-05-19T08:13:36.228 full_node chia.rpc.rpc_server     : WARNING  Error while handling message: Traceback (most recent call last):
    raise ValueError("Start client failed, or server is not set")
ValueError: Start client failed, or server is not set
2021-05-19T08:14:07.227 full_node chia.rpc.rpc_server     : WARNING  Error while handling message: Traceback (most recent call last):
    raise ValueError("Start client failed, or server is not set")
ValueError: Start client failed, or server is not set
2021-05-19T08:14:42.227 full_node chia.rpc.rpc_server     : WARNING  Error while handling message: Traceback (most recent call last):
    raise ValueError("Start client failed, or server is not set")
ValueError: Start client failed, or server is not set
2021-05-19T08:15:13.227 full_node chia.rpc.rpc_server     : WARNING  Error while handling message: Traceback (most recent call last):
    raise ValueError("Start client failed, or server is not set")
ValueError: Start client failed, or server is not set
2021-05-19T08:15:47.227 full_node chia.rpc.rpc_server     : WARNING  Error while handling message: Traceback (most recent call last):
    raise ValueError("Start client failed, or server is not set")
ValueError: Start client failed, or server is not set
2021-05-19T08:16:18.227 full_node chia.rpc.rpc_server     : WARNING  Error while handling message: Traceback (most recent call last):
    raise ValueError("Start client failed, or server is not set")
ValueError: Start client failed, or server is not set
2021-05-19T08:16:50.227 full_node chia.rpc.rpc_server     : WARNING  Error while handling message: Traceback (most recent call last):
    raise ValueError("Start client failed, or server is not set")
ValueError: Start client failed, or server is not set
2021-05-19T08:17:36.931 full_node chia.full_node.full_node: ERROR    Error with syncing: <class 'RuntimeError'>Traceback (most recent call last):
    raise RuntimeError(f"Weight proof did not arrive in time from peer: {weight_proof_peer.peer_host}")
RuntimeError: Weight proof did not arrive in time from peer: 82.156.105.245
2021-05-19T08:19:28.227 full_node chia.rpc.rpc_server     : WARNING  Error while handling message: Traceback (most recent call last):
    raise ValueError("Start client failed, or server is not set")
ValueError: Start client failed, or server is not set
2021-05-19T08:31:21.692 full_node full_node_server        : ERROR    Exception Was not able to get peername from <function WSChiaConnection.__getattr__.<locals>.invoke at 0x7f4212a6fb80> at 149.129.55.120, exception Stack: Traceback (most recent call last):
    raise ValueError(f"Was not able to get peername from {self.ws_witer} at {self.peer_host}")
ValueError: Was not able to get peername from <function WSChiaConnection.__getattr__.<locals>.invoke at 0x7f4212a6fb80> at 149.129.55.120
2021-05-19T15:55:27.300 full_node asyncio                 : ERROR    Unclosed client session
2021-05-19T15:55:27.314 full_node chia.full_node.full_node: ERROR    Error with syncing: <class 'RuntimeError'>Traceback (most recent call last):
    raise RuntimeError(f"Weight proof did not arrive in time from peer: {weight_proof_peer.peer_host}")
RuntimeError: Weight proof did not arrive in time from peer: 91.203.167.203
2021-05-19T16:05:14.462 wallet asyncio                    : ERROR    Unclosed client session
2021-05-19T16:09:12.178 full_node chia.rpc.rpc_server     : WARNING  Error while handling message: Traceback (most recent call last):
    raise ValueError("Start client failed, or server is not set")
ValueError: Start client failed, or server is not set
2021-05-19T16:09:44.178 full_node chia.rpc.rpc_server     : WARNING  Error while handling message: Traceback (most recent call last):
    raise ValueError("Start client failed, or server is not set")
ValueError: Start client failed, or server is not set
2021-05-19T16:10:15.179 full_node chia.rpc.rpc_server     : WARNING  Error while handling message: Traceback (most recent call last):
    raise ValueError("Start client failed, or server is not set")
ValueError: Start client failed, or server is not set
2021-05-19T16:10:46.204 full_node chia.rpc.rpc_server     : WARNING  Error while handling message: Traceback (most recent call last):
    raise ValueError("Start client failed, or server is not set")
ValueError: Start client failed, or server is not set
2021-05-19T16:11:22.178 full_node chia.rpc.rpc_server     : WARNING  Error while handling message: Traceback (most recent call last):
    raise ValueError("Start client failed, or server is not set")
ValueError: Start client failed, or server is not set
2021-05-19T16:11:53.179 full_node chia.rpc.rpc_server     : WARNING  Error while handling message: Traceback (most recent call last):
    raise ValueError("Start client failed, or server is not set")
ValueError: Start client failed, or server is not set
2021-05-19T16:12:27.181 full_node chia.rpc.rpc_server     : WARNING  Error while handling message: Traceback (most recent call last):
    raise ValueError("Start client failed, or server is not set")
ValueError: Start client failed, or server is not set
2021-05-19T16:12:58.178 full_node chia.rpc.rpc_server     : WARNING  Error while handling message: Traceback (most recent call last):
    raise ValueError("Start client failed, or server is not set")
ValueError: Start client failed, or server is not set
2021-05-19T16:13:29.179 full_node chia.rpc.rpc_server     : WARNING  Error while handling message: Traceback (most recent call last):
    raise ValueError("Start client failed, or server is not set")
ValueError: Start client failed, or server is not set
2021-05-19T16:14:00.179 full_node chia.rpc.rpc_server     : WARNING  Error while handling message: Traceback (most recent call last):
    raise ValueError("Start client failed, or server is not set")
