### ISSUE TITLE
[help]DOUBLE_SPEND？

### ISSUE THREAD

**Issue by Eden0628** [Chia-Network/chia-blockchain#4281]
2021-05-08T17:55:26.219 full_node chia.full_node.full_node: WARNING  Wasn't able to add transaction with id 70cd3dc04739a6584b63bee0c8c0b64f78e56c79d894441a1ce121f80294e65b, status 3 error: Err.DOUBLE_SPEND
2021-05-08T17:55:26.221 full_node chia.full_node.full_node: WARNING  Wasn't able to add transaction with id d092c8e48315872fbc3c0401204001927a089e5f3049afde2e824e6264630eb4, status 3 error: Err.DOUBLE_SPEND
2021-05-08T17:55:26.223 full_node chia.full_node.full_node: WARNING  Wasn't able to add transaction with id 9b1803a8c7586a5778da1d6a1eb01adf304e7f32077eed162210d08b6fff98d3, status 3 error: Err.DOUBLE_SPEND
2021-05-08T17:55:26.225 full_node chia.full_node.full_node: WARNING  Wasn't able to add transaction with id 6861fb69c330afa470fd901967c5e6d1c09d3861147999b13d9d4dbed6852183, status 3 error: Err.DOUBLE_SPEND
2021-05-08T17:55:26.227 full_node chia.full_node.full_node: WARNING  Wasn't able to add transaction with id 1609dc42ac010697f6fed6f44194fbbc39e0ab2e07f4c5f4f1f97d1d4e585c4f, status 3 error: Err.DOUBLE_SPEND
2021-05-08T17:55:26.229 full_node chia.full_node.full_node: WARNING  Wasn't able to add transaction with id 9a3f77456fec51fce16b217a118ae185f6382e15958cf839511a8262fa8fc20f, status 3 error: Err.DOUBLE_SPEND
2021-05-08T17:55:31.873 full_node chia.rpc.rpc_server     : WARNING  Error while handling message: Traceback (most recent call last):
  File "chia\rpc\rpc_server.py", line 212, in safe_handle
  File "chia\rpc\rpc_server.py", line 200, in ws_api
  File "chia\rpc\rpc_server.py", line 161, in open_connection
ValueError: Start client failed, or server is not set

**Comment by Muffexx** [comment]
Hello @Eden0628,

please consider searching before creating new issues.
There are several issues regarding this topic e.g. #4164 #3917 #3696 

regards
muffexx
