### ISSUE TITLE
Help pls

### ISSUE THREAD

**Issue by Makusm1990** [Chia-Network/chia-blockchain#4289]
sqlite3.ProgrammingError: Cannot operate on a closed database.
2021-05-09T15:37:10.722 full_node chia.full_node.full_node: ERROR    Exception in create outbound connections: 
2021-05-09T15:37:10.723 full_node chia.full_node.full_node: ERROR    Traceback: Traceback (most recent call last):
  File "chia\server\node_discovery.py", line 325, in _connect_to_peers
  File "asyncio\tasks.py", line 595, in sleep
concurrent.futures._base.CancelledError

**Comment by hateriarch** [comment]
I am getting this same issue and cannot sync.

**Comment by Yuanyp8** [comment]
I am getting this same issue and cannot sync.

```
2021-05-12T00:22:39.304 full_node chia.full_node.full_node: ERROR    Exception in create outbound connections:
2021-05-12T00:22:39.308 full_node chia.full_node.full_node: ERROR    Traceback: Traceback (most recent call last):
  File "/...../python3.7/site-packages/chia/server/node_discovery.py", line 325, in _connect_to_peers
    await asyncio.sleep(sleep_interval)
  File "/..../python3.7/asyncio/tasks.py", line 595, in sleep
    return await future

```

**Comment by jfelixff** [comment]
2021-05-12T01:09:52.552 full_node chia.full_node.full_node: ERROR    Exception in create outbound connections: 
2021-05-12T01:09:52.554 full_node chia.full_node.full_node: ERROR    Traceback: Traceback (most recent call last):
  File "chia\server\node_discovery.py", line 325, in _connect_to_peers
  File "asyncio\tasks.py", line 595, in sleep
concurrent.futures._base.CancelledError

2021-05-12T01:09:57.152 daemon asyncio                    : ERROR    Task exception was never retrieved
future: <Task finished coro=<kill_service() done, defined at chia\daemon\server.py:833> exception=AttributeError("'list' object has no attribute 'pid'")>
Traceback (most recent call last):
  File "chia\daemon\server.py", line 841, in kill_service
  File "chia\daemon\server.py", line 805, in kill_process
AttributeError: 'list' object has no attribute 'pid'

**Comment by andy008** [comment]
Same:-

2021-05-16T23:03:44.240 full_node chia.full_node.full_node: ERROR    Exception in create outbound connections: 
2021-05-16T23:03:44.245 full_node chia.full_node.full_node: ERROR    Traceback: Traceback (most recent call last):
  File "chia\server\node_discovery.py", line 325, in _connect_to_peers
  File "asyncio\tasks.py", line 595, in sleep
concurrent.futures._base.CancelledError

**Comment by Makusm1990** [comment]
Why no Support Help?

**Comment by tkmbe99** [comment]
Same isue here. 
What hw are you using?
In my case I have a netbook with Intel Celeron  N2806 1.60GHz and 4 GB Ram.
This has only 2 cores and 2 threads
I want to use only for farming not to create plot.

**Comment by NOFOX** [comment]
same not synced issue issue.
2021-05-22T14:48:40.380 full_node chia.full_node.full_node: ERROR    Exception in create outbound connections:
2021-05-22T14:48:40.381 full_node chia.full_node.full_node: ERROR    Traceback: Traceback (most recent call last):
  File "/root/chia-blockchain/chia/server/node_discovery.py", line 325, in _connect_to_peers
    await asyncio.sleep(sleep_interval)
  File "/usr/local/lib/python3.7/asyncio/tasks.py", line 595, in sleep
    return await future
concurrent.futures._base.CancelledError

2021-05-22T14:48:42.387 full_node asyncio                 : ERROR    Task exception was never retrieved
future: <Task finished coro=<FullNode.initialize_weight_proof() done, defined at /root/chia-blockchain/chia/full_node/full_node.py:165> exception=ProgrammingError('Cannot operate on a closed database.')>
Traceback (most recent call last):
  File "/root/chia-blockchain/chia/full_node/full_node.py", line 169, in initialize_weight_proof
    await self.weight_proof_handler.create_sub_epoch_segments()

**Comment by azhetube** [comment]
same :-
Windows10
Chia 1.1.6

2021-05-30T09:14:38.114 wallet chia.wallet.wallet_blockchain: ERROR    Error during db transaction: Cannot operate on a closed database.
2021-05-30T09:14:38.115 wallet wallet_server              : ERROR    Exception: Cannot operate on a closed database., None. Traceback (most recent call last):
  File "chia\server\server.py", line 526, in wrapped_coroutine
  File "chia\wallet\wallet_node_api.py", line 49, in new_peak_wallet
  File "chia\wallet\wallet_node.py", line 441, in new_peak_wallet
  File "chia\wallet\wallet_node.py", line 392, in complete_blocks
  File "chia\wallet\wallet_blockchain.py", line 227, in receive_block
  File "chia\wallet\wallet_block_store.py", line 90, in add_block_record
  File "aiosqlite\cursor.py", line 69, in close
  File "aiosqlite\cursor.py", line 31, in _execute
  File "aiosqlite\core.py", line 129, in _execute
  File "aiosqlite\core.py", line 102, in run
sqlite3.ProgrammingError: Cannot operate on a closed database.

2021-05-30T09:14:38.116 wallet wallet_server              : ERROR    Exception: Cannot operate on a closed database. <class 'sqlite3.ProgrammingError'>, closing connection None. Traceback (most recent call last):
  File "chia\server\server.py", line 536, in api_call
  File "asyncio\tasks.py", line 414, in wait_for
  File "chia\server\server.py", line 533, in wrapped_coroutine
  File "chia\server\server.py", line 526, in wrapped_coroutine
  File "chia\wallet\wallet_node_api.py", line 49, in new_peak_wallet
  File "chia\wallet\wallet_node.py", line 441, in new_peak_wallet
  File "chia\wallet\wallet_node.py", line 392, in complete_blocks
  File "chia\wallet\wallet_blockchain.py", line 227, in receive_block
  File "chia\wallet\wallet_block_store.py", line 90, in add_block_record
  File "aiosqlite\cursor.py", line 69, in close
  File "aiosqlite\cursor.py", line 31, in _execute
  File "aiosqlite\core.py", line 129, in _execute
  File "aiosqlite\core.py", line 102, in run
sqlite3.ProgrammingError: Cannot operate on a closed database.
