### ISSUE TITLE
[BUG] Stuck on connecting to wallet since last update. 

### ISSUE THREAD

**Issue by doumination** [Chia-Network/chia-blockchain#4455]
After my last update, I'm not able to launch Chia Network. In fact, I'm stuck on "connecting to wallet" and it keeps loading endlessly. I uninstall then reinstall the Chia Network (1.1.5) and it does the same thing... 

![image](https://user-images.githubusercontent.com/83973701/117692940-83847a80-b18b-11eb-87ca-ccf0acfa1d01.png)

- OS: Windows 10
- OS Version 1.1.5

I can provide any additional information and answer your questions..

**Comment by Dariux1991** [comment]
Same bug

**Comment by joframel** [comment]
Same bug in v. 1.1.4 and 1.1.5.

**Comment by otnoukra** [comment]
I've had the same problem for 5 hours. never connects.

**Comment by Dariux1991** [comment]
someone find solution?

**Comment by Reflect-DAo** [comment]
I have the following in the error log:

can anyone help with that ?

2021-05-15T17:28:12.976 full_node chia.rpc.rpc_server     : WARNING  Cannot connect to daemon at ws://localhost:55400
2021-05-15T17:28:14.981 full_node chia.rpc.rpc_server     : WARNING  Cannot connect to daemon at ws://localhost:55400
2021-05-15T17:28:16.991 full_node chia.rpc.rpc_server     : WARNING  Cannot connect to daemon at ws://localhost:55400
2021-05-15T17:28:18.983 full_node chia.rpc.rpc_server     : WARNING  Cannot connect to daemon at ws://localhost:55400
2021-05-15T17:28:20.989 full_node chia.rpc.rpc_server     : WARNING  Cannot connect to daemon at ws://localhost:55400
2021-05-15T17:28:22.987 full_node chia.rpc.rpc_server     : WARNING  Cannot connect to daemon at ws://localhost:55400
2021-05-15T17:28:24.995 full_node chia.rpc.rpc_server     : WARNING  Cannot connect to daemon at ws://localhost:55400
2021-05-15T17:28:27.000 full_node chia.rpc.rpc_server     : WARNING  Cannot connect to daemon at ws://localhost:55400
2021-05-15T17:28:29.010 full_node chia.rpc.rpc_server     : WARNING  Cannot connect to daemon at ws://localhost:55400
2021-05-15T17:28:31.017 full_node chia.rpc.rpc_server     : WARNING  Cannot connect to daemon at ws://localhost:55400
2021-05-15T17:29:30.119 daemon websockets.protocol        : ERROR    Error in data transfer
Traceback (most recent call last):
  File "websockets\protocol.py", line 827, in transfer_data
  File "websockets\protocol.py", line 895, in read_message
  File "websockets\protocol.py", line 995, in read_data_frame
  File "websockets\protocol.py", line 766, in pong
  File "websockets\protocol.py", line 803, in ensure_open
websockets.exceptions.ConnectionClosedError: code = 1006 (connection closed abnormally [internal]), no reason
2021-05-15T17:33:13.890 daemon websockets.protocol        : ERROR    Error in data transfer

**Comment by mariano54** [comment]
Many bugs related to wallet syncing have been fixed. Please update and follow the steps here https://github.com/Chia-Network/chia-blockchain/issues/6993
