### ISSUE TITLE
[BUG] status 3 error: Err.UNKNOWN_UNSPENT

### ISSUE THREAD

**Issue by ramkom9** [Chia-Network/chia-blockchain#4488]
Describe the bug
2021-05-10T21:36:12.056 full_node full_node_server        : INFO     <- new_compact_vdf from peer 3cc33ce94ccdd32c050f7e25484ec16efc575ab02f08b1303413231efc918128 82.119.105.242
2021-05-10T21:36:12.275 full_node chia.full_node.full_node: WARNING  Wasn't able to add transaction with id 7bb8bb2a601aed4b79c00e98725379d93dea53c5db51ee3b7c90a4f9883fb301, status 3 error: Err.UNKNOWN_UNSPENT
2021-05-10T21:36:13.598 full_node full_node_server        : INFO     <- new_compact_vdf from peer dbc56bf96ebd8d8e8e4c8023a88a84847fca066686895ebca131b93538b32dbc 2.183.124.123

To Reproduce

1. Go to C:\Users\user\.chia\mainnet\log
2. Click on debug.txt
3. Scroll down to line starting with 2021-05-10T21:36:12.275
4. See error  status 3 error: Err.UNKNOWN_UNSPENT

- OS: Windows 10PRO VM on esxi 6.5
- OS Version/Flavor: 20H2
- CPU: Intel(R) Xeon(R) CPU  E5620  @ 2.40GHz   2.40 GHz  (2 processors)
- RAM: 68Gb

v. 1.1.5

**Comment by dmontes46** [comment]
hi all

i am seeing the same

status 3 error: Err.UNKNOWN_UNSPENT

**Comment by xeijo** [comment]
I only see that error 6890 times (in two days) status 3 error: Err.DOUBLE_SPEND

**Comment by SICKFREDO** [comment]
So what does the error mean? "UNKNOWN_UNSPENT" is all over the logs. same with this sql one

full_node full_node_server        : ERROR    Exception: too many SQL variables <class 'sqlite3.OperationalError'>, closing connection {'host': '127.0.0.1', 'port': 8449}. Traceback (most recent call last):
  File "chia\server\server.py", line 531, in api_call
  File "asyncio\tasks.py", line 442, in wait_for
  File "chia\server\server.py", line 528, in wrapped_coroutine
  File "chia\server\server.py", line 521, in wrapped_coroutine
  File "chia\full_node\full_node_api.py", line 244, in request_proof_of_weight
  File "chia\full_node\weight_proof.py", line 77, in get_proof_of_weight
  File "chia\full_node\weight_proof.py", line 119, in _create_proof_of_weight
  File "chia\consensus\blockchain.py", line 686, in get_block_records_at
  File "chia\full_node\block_store.py", line 181, in get_block_records_by_hash
  File "aiosqlite\core.py", line 184, in execute
  File "aiosqlite\core.py", line 129, in _execute
  File "aiosqlite\core.py", line 102, in run
sqlite3.OperationalError: too many SQL variables
