### ISSUE TITLE
[Bug] (Maybe?)If you run 16 plots the 16th plot will fail

### ISSUE THREAD

**Issue by Jerkysan** [Chia-Network/chia-blockchain#4592]
I use HDD's to plot with since I can't get any DC NVME. I run multiple plots at a time using the GUI but it appears after the 15th plot it will no longer function properly. Using a 5950x with 64gb of ram Windows 10 Fully patched latest build of chia 1.1.5. After it builds the initial files it will erase everything and you'll end up with only 9 files in the folder. You then get the "bad allocation" error. Going to try switching to command line and then maybe even ubuntu

2021-05-11T09:49:58.289  chia.plotting.create_plots       : [32mINFO    [0m Creating 1 plots of size 32, pool public key:  farmer public key: [0m
2021-05-11T09:49:58.294  chia.plotting.create_plots       : [32mINFO    [0m Memo: [0m
2021-05-11T09:49:58.296  chia.plotting.create_plots       : [32mINFO    [0m Starting plot 1/1[0m

Starting plotting progress into temporary dirs: S:\ and S:\
ID: 
Plot size is: 32
Buffer size is: 3390MiB
Using 128 buckets
Using 2 threads of stripe size 65536

Starting phase 1/4: Forward Propagation into tmp files... Tue May 11 09:49:58 2021
Computing table 1
F1 complete, time: 894.438 seconds. CPU (18.05%) Tue May 11 10:04:52 2021
Computing table 2
Caught plotting error: bad allocation
[12992] Failed to execute script chia
Traceback (most recent call last):
  File "chia\cmds\chia.py", line 81, in <module>
  File "chia\cmds\chia.py", line 77, in main
  File "click\core.py", line 829, in __call__
  File "click\core.py", line 782, in main
  File "click\core.py", line 1259, in invoke
  File "click\core.py", line 1259, in invoke
  File "click\core.py", line 1066, in invoke
  File "click\core.py", line 610, in invoke

**Comment by ilyakooo0** [comment]
https://github.com/Chia-Network/chia-blockchain/wiki/FAQ#my-plotting-attempt-ended-with-runtimeerror-bad-allocation

**Comment by Jerkysan** [comment]
> https://github.com/Chia-Network/chia-blockchain/wiki/FAQ#my-plotting-attempt-ended-with-runtimeerror-bad-allocation

I've run it for a few hundred hours doing this. It always fails on the 16th plot. With it deleting all the files it just got done creating and leaving 9 blank files instead of 250+ files it just made..
