### ISSUE TITLE
 ERROR Exception: Failed to fetch block XXXXXX from None

### ISSUE THREAD

**Issue by VisualWebTech** [Chia-Network/chia-blockchain#4632]
**Describe the bug**
Got this error (more than 3 times just saved the last two logs and here is one of them the second one exactly the same just different block number)

**Screenshots**
2021-05-11T15:39:13.937 full_node full_node_server        : ERROR    Exception: Failed to fetch block XXXXXX from None, timed out, None. Traceback (most recent call last):
  File "/home/hanzi/chia-blockchain/chia/server/server.py", line 521, in wrapped_coroutine
    result = await coroutine
  File "/home/XXXXX/chia-blockchain/chia/full_node/full_node_api.py", line 104, in new_peak
    return await self.full_node.new_peak(request, peer)
  File "/home/XXXXX/chia-blockchain/chia/full_node/full_node.py", line 360, in new_peak
    if await self.short_sync_backtrack(
  File "/home/XXXXXX/chia-blockchain/chia/full_node/full_node.py", line 310, in short_sync_backtrack
    raise e
  File "/home/XXXXXX/chia-blockchain/chia/full_node/full_node.py", line 295, in short_sync_backtrack
    raise ValueError(f"Failed to fetch block {curr_height} from {peer.get_peer_info()}, timed out")
ValueError: Failed to fetch block 265981 from None, timed out

**Desktop (please complete the following information):**

- OS: Ubuntu desktop 
- OS Latest
- CPU: AMD Ryzen 5800X 8 core 16 thread
- 32GB memory
- 2x Sebgent 2T NVME
- Kingston SSD 240GB for OS

**Additional context**
Installed everything brand new 3 days ago no changes to any files programs or chia files running just chia and os

any help will be really appreciated
thanks

**Comment by husar516** [comment]
me too!!!

**Comment by VisualWebTech** [comment]
Got another one dose any one know if that's OS related? or where to look to fix that error? its sad to see those errors

harvester harvester_server        : WARNING  Peer surpassed rate limit 127.0.0.1, message: new_signage_point_harvester, port 8447 but not disconnecting

**Comment by MacbethFPV** [comment]
Describe the bug:
I believe I have the same issue

Screenshots:

2021-05-14T10:24:31.521 full_node full_node_server        : ERROR    Exception: Failed to fetch block 280077 from None, timed out, None. Traceback (most recent call last):
  File "/home/main/chia-blockchain/chia/server/server.py", line 521, in wrapped_coroutine
    result = await coroutine
  File "/home/main/chia-blockchain/chia/full_node/full_node_api.py", line 104, in new_peak
    return await self.full_node.new_peak(request, peer)
  File "/home/main/chia-blockchain/chia/full_node/full_node.py", line 360, in new_peak
    if await self.short_sync_backtrack(
  File "/home/main/chia-blockchain/chia/full_node/full_node.py", line 310, in short_sync_backtrack
    raise e
  File "/home/main/chia-blockchain/chia/full_node/full_node.py", line 295, in short_sync_backtrack
    raise ValueError(f"Failed to fetch block {curr_height} from {peer.get_peer_info()}, timed out")
ValueError: Failed to fetch block 280077 from None, timed out

2021-05-14T10:24:31.521 full_node full_node_server        : ERROR    Exception: Failed to fetch block 280077 from None, timed out <class 'ValueError'>, closing connection None. Traceback (most recent call last):
  File "/home/main/chia-blockchain/chia/server/server.py", line 531, in api_call
    response: Optional[Message] = await asyncio.wait_for(wrapped_coroutine(), timeout=timeout)
  File "/usr/lib/python3.8/asyncio/tasks.py", line 455, in wait_for
    return await fut
  File "/home/main/chia-blockchain/chia/server/server.py", line 528, in wrapped_coroutine
    raise e
  File "/home/main/chia-blockchain/chia/server/server.py", line 521, in wrapped_coroutine
    result = await coroutine
  File "/home/main/chia-blockchain/chia/full_node/full_node_api.py", line 104, in new_peak
    return await self.full_node.new_peak(request, peer)
  File "/home/main/chia-blockchain/chia/full_node/full_node.py", line 360, in new_peak
    if await self.short_sync_backtrack(
  File "/home/main/chia-blockchain/chia/full_node/full_node.py", line 310, in short_sync_backtrack
    raise e
  File "/home/main/chia-blockchain/chia/full_node/full_node.py", line 295, in short_sync_backtrack
    raise ValueError(f"Failed to fetch block {curr_height} from {peer.get_peer_info()}, timed out")
ValueError: Failed to fetch block 280077 from None, timed out

Desktop (please complete the following information):

OS: Ubuntu desktop
OS 20.04.2 LTS
CPU: i7-8550U
16GB mem

Additional context:
I have a more extensive sample as well with the same issue but happened to ~4 blocks back to back

**Comment by q246121410** [comment]
I have the same issues, and chia can not synced.
`2021-05-26T19:20:43.055 full_node full_node_server        : ERROR    Exception: Failed to fetch block 338498 from None, timed out <class 'ValueError'>, closing connection None. Traceback (most recent call last):
  File "chia\server\server.py", line 531, in api_call
  File "asyncio\tasks.py", line 414, in wait_for
  File "chia\server\server.py", line 528, in wrapped_coroutine
  File "chia\server\server.py", line 521, in wrapped_coroutine
  File "chia\full_node\full_node_api.py", line 104, in new_peak
  File "chia\full_node\full_node.py", line 361, in new_peak
  File "chia\full_node\full_node.py", line 310, in short_sync_backtrack
  File "chia\full_node\full_node.py", line 295, in short_sync_backtrack
ValueError: Failed to fetch block 338498 from None, timed out`

**Comment by matteoaugelli** [comment]
I have same issue:




2021-05-29T02:44:07.201 full_node full_node_server        : ERROR    Exception: Failed to fetch block 351444 from None, timed out <class 'ValueError'>, closing connection None. Traceback (most recent call last):
  File "/home/ifritprog/Dev/chia/chia-blockchain/chia/server/server.py", line 536, in api_call
    response: Optional[Message] = await asyncio.wait_for(wrapped_coroutine(), timeout=timeout)
  File "/usr/lib/python3.8/asyncio/tasks.py", line 455, in wait_for
    return await fut
  File "/home/ifritprog/Dev/chia/chia-blockchain/chia/server/server.py", line 533, in wrapped_coroutine
    raise e
  File "/home/ifritprog/Dev/chia/chia-blockchain/chia/server/server.py", line 526, in wrapped_coroutine
    result = await coroutine
  File "/home/ifritprog/Dev/chia/chia-blockchain/chia/full_node/full_node_api.py", line 104, in new_peak
    return await self.full_node.new_peak(request, peer)
  File "/home/ifritprog/Dev/chia/chia-blockchain/chia/full_node/full_node.py", line 372, in new_peak
    if await self.short_sync_backtrack(
  File "/home/ifritprog/Dev/chia/chia-blockchain/chia/full_node/full_node.py", line 322, in short_sync_backtrack
    raise e
  File "/home/ifritprog/Dev/chia/chia-blockchain/chia/full_node/full_node.py", line 307, in short_sync_backtrack
    raise ValueError(f"Failed to fetch block {curr_height} from {peer.get_peer_info()}, timed out")
ValueError: Failed to fetch block 351444 from None, timed out


- Kubuntu 20.04.2
- Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz
- 32GB Ram

**Comment by malahhaor** [comment]
as of 7/15 issue persists
full_node full_node_server        : ERROR    Exception: Failed to fetch block 577803 from None

**Comment by djarbz** [comment]
I'm getting it as well, node keeps failing to stay in sync and needs a restart.

```
2021-07-16T10:24:06.218 full_node full_node_server        : ERROR    Exception: Failed to fetch block 579812 from None, timed out, None. Traceback (most recent call last):
  File "/opt/chia/blockchain/chia/server/server.py", line 523, in wrapped_coroutine
    result = await coroutine
  File "/opt/chia/blockchain/chia/full_node/full_node_api.py", line 106, in new_peak
    return await self.full_node.new_peak(request, peer)
  File "/opt/chia/blockchain/chia/full_node/full_node.py", line 398, in new_peak
    peer, curr_peak_height, request.height, request.unfinished_reward_block_hash
  File "/opt/chia/blockchain/chia/full_node/full_node.py", line 331, in short_sync_backtrack
    raise e
  File "/opt/chia/blockchain/chia/full_node/full_node.py", line 316, in short_sync_backtrack
    raise ValueError(f"Failed to fetch block {curr_height} from {peer.get_peer_info()}, timed out")
ValueError: Failed to fetch block 579812 from None, timed out

2021-07-16T10:24:06.254 full_node full_node_server        : ERROR    Exception: Failed to fetch block 579812 from None, timed out <class 'ValueError'>, closing connection None. Traceback (most recent call last):
  File "/opt/chia/blockchain/chia/server/server.py", line 533, in api_call
    response: Optional[Message] = await asyncio.wait_for(wrapped_coroutine(), timeout=timeout)
  File "/usr/lib/python3.7/asyncio/tasks.py", line 388, in wait_for
    return await fut
  File "/opt/chia/blockchain/chia/server/server.py", line 530, in wrapped_coroutine
    raise e
  File "/opt/chia/blockchain/chia/server/server.py", line 523, in wrapped_coroutine
    result = await coroutine
  File "/opt/chia/blockchain/chia/full_node/full_node_api.py", line 106, in new_peak
    return await self.full_node.new_peak(request, peer)
  File "/opt/chia/blockchain/chia/full_node/full_node.py", line 398, in new_peak
    peer, curr_peak_height, request.height, request.unfinished_reward_block_hash
  File "/opt/chia/blockchain/chia/full_node/full_node.py", line 331, in short_sync_backtrack
    raise e
  File "/opt/chia/blockchain/chia/full_node/full_node.py", line 316, in short_sync_backtrack
    raise ValueError(f"Failed to fetch block {curr_height} from {peer.get_peer_info()}, timed out")
ValueError: Failed to fetch block 579812 from None, timed out
```

**Comment by emlowe** [comment]
Errors such as ```ValueError: Failed to fetch block 579812 from None, timed out``` are normal in a peer network, from time to time you will get peers that don't respond properly or time out or otherwise are problematic. The software will drop the connection to that peer, ban the peer for a set amount of time, and attempt syncing from other peers in your peer list.
