### ISSUE TITLE
[BUG] Chia windows GUI application crash

### ISSUE THREAD

**Issue by wizwin** [Chia-Network/chia-blockchain#4636]
**Describe the bug**
Looks like there was a crash in one of the modules. When I came back to me PC today morning the GUI was not there. 

Logs with WARNING level attached. I see many exceptions and warnings before it could no longer connect.

**To Reproduce**

1. Launch Chia windows GUI application
2. Let it run for several days (16 plots and synced)
3. GUI window will be closed automatically

**Expected behavior**
GUI window should not close automatically. It should display any error which caused chia operations to stop.

**Screenshots**
No screenshot since GUI was not present.

**Desktop (please complete the following information):**

- OS: Windows
- OS Version/Flavor: Windows 10 20H2
- CPU: Intel Core i5 3rd Generation

**Additional context**
[debug.zip](https://github.com/Chia-Network/chia-blockchain/files/6463367/debug.zip)

**Comment by wizwin** [comment]
After this sync is not happening (Stuck at height 267650):

```
2021-05-13T09:58:20.570 full_node full_node_server        : ERROR    Exception:  <class 'concurrent.futures._base.CancelledError'>, closing connection None. Traceback (most recent call last):
  File "chia\server\server.py", line 531, in api_call
  File "asyncio\tasks.py", line 435, in wait_for
concurrent.futures._base.CancelledError

2021-05-13T10:08:32.912 full_node full_node_server        : WARNING  Banning 176.213.69.193 for 600 seconds
2021-05-13T10:08:32.915 full_node chia.full_node.full_node: ERROR    Error with syncing: <class 'RuntimeError'>Traceback (most recent call last):
  File "chia\full_node\full_node.py", line 628, in _sync
RuntimeError: Weight proof did not arrive in time from peer: 176.213.69.193

2021-05-13T10:12:56.202 full_node full_node_server        : WARNING  Banning 37.189.145.42 for 600 seconds
2021-05-13T10:12:56.204 full_node chia.full_node.full_node: ERROR    Error with syncing: <class 'RuntimeError'>Traceback (most recent call last):
  File "chia\full_node\full_node.py", line 628, in _sync
RuntimeError: Weight proof did not arrive in time from peer: 37.189.145.42

2021-05-13T10:15:37.016 full_node chia.full_node.full_node: WARNING  Invalid response for slot None
2021-05-13T10:18:53.930 full_node full_node_server        : WARNING  Banning 24.14.240.13 for 600 seconds
2021-05-13T10:18:53.933 full_node chia.full_node.full_node: ERROR    Error with syncing: <class 'RuntimeError'>Traceback (most recent call last):
  File "chia\full_node\full_node.py", line 628, in _sync
RuntimeError: Weight proof did not arrive in time from peer: 24.14.240.13
```
