### ISSUE TITLE
[BUG] Problem with python - MAC Check Failed

### ISSUE THREAD

**Issue by dusanradojcic00** [Chia-Network/chia-blockchain#4672]
I get this error when I try to generate keys, to start chia or anything else. Looks like a problem with python encription

Ubuntu 20.04

(venv) bogito@chia:~/chia-blockchain$ chia keys generate
Generating private key
Added private key with public key fingerprint 2917882584 and mnemonic
nurse derive virus bicycle forget laptop gaze uncle uniform citizen fiction emotion hockey seed hire live warfare perfect laptop century easy fashion fi                                     tness hockey
Traceback (most recent call last):
  File "/home/bogito/chia-blockchain/venv/lib/python3.8/site-packages/keyrings/cryptfile/file_base.py", line 116, in get_password
    password = self.decrypt(password_encrypted, assoc).decode('utf-8')
  File "/home/bogito/chia-blockchain/venv/lib/python3.8/site-packages/keyrings/cryptfile/cryptfile.py", line 130, in decrypt
    return cipher.decrypt_and_verify(data['data'], data['mac'])
  File "/home/bogito/chia-blockchain/venv/lib/python3.8/site-packages/Crypto/Cipher/_mode_gcm.py", line 567, in decrypt_and_verify
    self.verify(received_mac_tag)
  File "/home/bogito/chia-blockchain/venv/lib/python3.8/site-packages/Crypto/Cipher/_mode_gcm.py", line 508, in verify
    raise ValueError("MAC check failed")
ValueError: MAC check failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/bogito/chia-blockchain/venv/bin/chia", line 33, in <module>
    sys.exit(load_entry_point('chia-blockchain', 'console_scripts', 'chia')())
  File "/home/bogito/chia-blockchain/chia/cmds/chia.py", line 77, in main
    cli()  # pylint: disable=no-value-for-parameter
  File "/home/bogito/chia-blockchain/venv/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/bogito/chia-blockchain/venv/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/bogito/chia-blockchain/venv/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/bogito/chia-blockchain/venv/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/bogito/chia-blockchain/venv/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/bogito/chia-blockchain/venv/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/bogito/chia-blockchain/venv/lib/python3.8/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/bogito/chia-blockchain/chia/cmds/keys.py", line 22, in generate_cmd
    check_keys(ctx.obj["root_path"])
  File "/home/bogito/chia-blockchain/chia/cmds/init_funcs.py", line 51, in check_keys
    all_sks = keychain.get_all_private_keys()
  File "/home/bogito/chia-blockchain/chia/util/keychain.py", line 243, in get_all_private_keys
    pkent = self._get_pk_and_entropy(self._get_private_key_user(index))
  File "/home/bogito/chia-blockchain/chia/util/keychain.py", line 142, in _get_pk_and_entropy
    read_str = keyring.get_password(self._get_service(), user)
  File "/home/bogito/chia-blockchain/venv/lib/python3.8/site-packages/keyrings/cryptfile/file_base.py", line 119, in get_password
    password = self.decrypt(password_encrypted).decode('utf-8')
  File "/home/bogito/chia-blockchain/venv/lib/python3.8/site-packages/keyrings/cryptfile/cryptfile.py", line 130, in decrypt
    return cipher.decrypt_and_verify(data['data'], data['mac'])
  File "/home/bogito/chia-blockchain/venv/lib/python3.8/site-packages/Crypto/Cipher/_mode_gcm.py", line 567, in decrypt_and_verify
    self.verify(received_mac_tag)
  File "/home/bogito/chia-blockchain/venv/lib/python3.8/site-packages/Crypto/Cipher/_mode_gcm.py", line 508, in verify
    raise ValueError("MAC check failed")
ValueError: MAC check failed

**Comment by tryfan** [comment]
Also happening on FreeBSD 11.3 with python 3.7 on Chia latest and 1.1.5
