### ISSUE TITLE
[BUG] Banning node - Losing Sync (Report 2)

### ISSUE THREAD

**Issue by AlexJofer** [Chia-Network/chia-blockchain#4703]
After a while my wallet lose the synchronization:

![Sem Título](https://user-images.githubusercontent.com/83883461/118000136-727b6b00-b33d-11eb-84a6-f941a758b3ff.png)

Error on log file:

Traceback (most recent call last):
  File "chia\full_node\full_node.py", line 647, in _sync
ValueError: Weight proof validation threw an error A process in the process pool was terminated abruptly while the future was running or pending.

2021-05-12T15:46:23.454 full_node full_node_server        : ERROR    Exception , exception Stack: Traceback (most recent call last):
  File "chia\server\server.py", line 356, in start_client
  File "aiohttp\client.py", line 763, in _ws_connect
  File "aiohttp\client.py", line 521, in _request
  File "aiohttp\connector.py", line 535, in connect
  File "aiohttp\connector.py", line 892, in _create_connection
  File "aiohttp\connector.py", line 1032, in _create_direct_connection
  File "aiohttp\connector.py", line 969, in _wrap_create_connection
  File "asyncio\base_events.py", line 989, in create_connection
  File "asyncio\base_events.py", line 1017, in _create_connection_transport
concurrent.futures._base.CancelledError

2021-05-12T15:47:56.379 full_node chia.rpc.rpc_server     : WARNING  Error while handling message: Traceback (most recent call last):
  File "chia\rpc\rpc_server.py", line 212, in safe_handle
  File "chia\rpc\rpc_server.py", line 200, in ws_api
  File "chia\rpc\rpc_server.py", line 161, in open_connection
ValueError: Start client failed, or server is not set

2021-05-12T15:56:14.370 full_node full_node_server        : WARNING  Banning 95.188.65.134 for 600 seconds
2021-05-12T15:56:14.372 full_node chia.full_node.full_node: ERROR    Error with syncing: <class 'RuntimeError'>Traceback (most recent call last):
  File "chia\full_node\full_node.py", line 628, in _sync
RuntimeError: Weight proof did not arrive in time from peer: 95.188.65.134

2021-05-12T15:56:30.200 full_node chia.full_node.full_node: WARNING  Invalid response for slot None
2021-05-12T15:56:32.862 full_node chia.full_node.full_node: WARNING  Invalid response for slot None

**Comment by mariano54** [comment]
Many bugs related to wallet syncing have been fixed. Please update and follow the steps here https://github.com/Chia-Network/chia-blockchain/issues/6993, and continue discussion in that thread instead.
