### ISSUE TITLE
[BUG]task stoped in the begining

### ISSUE THREAD

**Issue by bi-kai** [Chia-Network/chia-blockchain#4718]
task stop at 1%, logs are below:
```
2021-05-12T21:41:13.786  chia.plotting.create_plots       : [32mINFO    [0m Creating 1 plots of size 32, pool public key:  8d08eec041f23a6ea822f8e458b87ab0e36da6fa56c724d77a5e3bfc477f94f00e5607069566477c7629ee3199871ff4 farmer public key: 92adc7ff6f313bb4d235bd47efd2889319cc1f825d015e639a138bec4a0ec6d7835e9b7a73a33d33134241347a098b01[0m
2021-05-12T21:41:13.799  chia.plotting.create_plots       : [32mINFO    [0m Memo: 8d08eec041f23a6ea822f8e458b87ab0e36da6fa56c724d77a5e3bfc477f94f00e5607069566477c7629ee3199871ff492adc7ff6f313bb4d235bd47efd2889319cc1f825d015e639a138bec4a0ec6d7835e9b7a73a33d33134241347a098b013a81659fa66a374b95e06c4084a0ebb0e0c12ca80ab14efdce1fed5a36c96026[0m
2021-05-12T21:41:13.800  chia.plotting.create_plots       : [32mINFO    [0m Adding directory \\192.168.50.162\plots\sn850 to harvester for farming[0m
[1708] Failed to execute script chia
Traceback (most recent call last):
  File "chia\cmds\chia.py", line 81, in <module>
  File "chia\cmds\chia.py", line 77, in main
  File "click\core.py", line 829, in __call__
  File "click\core.py", line 782, in main
  File "click\core.py", line 1259, in invoke
  File "click\core.py", line 1259, in invoke
  File "click\core.py", line 1066, in invoke
  File "click\core.py", line 610, in invoke
  File "click\decorators.py", line 21, in new_func
  File "chia\cmds\plots.py", line 135, in create_cmd
  File "chia\plotting\create_plots.py", line 158, in create_plots
  File "chia\plotting\plot_tools.py", line 110, in add_plot_directory
  File "chia\util\config.py", line 55, in load_config
  File "yaml\__init__.py", line 162, in safe_load
  File "yaml\__init__.py", line 114, in load
  File "yaml\constructor.py", line 49, in get_single_data
  File "yaml\composer.py", line 36, in get_single_node
  File "yaml\composer.py", line 55, in compose_document
  File "yaml\composer.py", line 84, in compose_node
  File "yaml\composer.py", line 133, in compose_mapping_node
  File "yaml\composer.py", line 84, in compose_node
  File "yaml\composer.py", line 127, in compose_mapping_node
  File "yaml\parser.py", line 98, in check_event
  File "yaml\parser.py", line 428, in parse_block_mapping_key
  File "yaml\scanner.py", line 115, in check_token
  File "yaml\scanner.py", line 152, in need_more_tokens
  File "yaml\scanner.py", line 292, in stale_possible_simple_keys
yaml.scanner.ScannerError: while scanning a simple key
  in "C:\Users\bikai\.chia\mainnet\config\config.yaml", line 264, column 1
could not find expected ':'
  in "C:\Users\bikai\.chia\mainnet\config\config.yaml", line 265, column 1
```

**Comment by Universe-Inc** [comment]
### Same issue. 2 threads of 5 consecutive plots (10) on a 5950x with plenty of resources. The other 8 plotted fine but for some reason 2 of the plots stuck at 1% with this error.

2021-06-13T01:09:04.136  chia.plotting.create_plots       : [32mINFO    [0m Creating 1 plots of size 32, pool public key:  b66c5b503ff0a935e37b8e100dae1a75bb841556a5e846cc22d4e8768c4290c74a44576e7d86773ad9d95b8f966d8ea7 farmer public key: b7c08b83d5d37ecd2f18223dc1e06684bc03efa4f58f984aea52bf770e80399711a83f4ace2d7c8d44b639bfd222839e[0m
2021-06-13T01:09:04.141  chia.plotting.create_plots       : [32mINFO    [0m Memo: b66c5b503ff0a935e37b8e100dae1a75bb841556a5e846cc22d4e8768c4290c74a44576e7d86773ad9d95b8f966d8ea7b7c08b83d5d37ecd2f18223dc1e06684bc03efa4f58f984aea52bf770e80399711a83f4ace2d7c8d44b639bfd222839e24d274260b582c50b1508890ae3163bd187406a49a53e8ebabb42191c2fc82c0[0m
2021-06-13T01:09:04.142  chia.plotting.create_plots       : [32mINFO    [0m Adding directory Z:\ to harvester for farming[0m
[14836] Failed to execute script chia
Traceback (most recent call last):
  File "chia\cmds\chia.py", line 81, in <module>
  File "chia\cmds\chia.py", line 77, in main
  File "click\core.py", line 829, in __call__
  File "click\core.py", line 782, in main
  File "click\core.py", line 1259, in invoke
  File "click\core.py", line 1259, in invoke
  File "click\core.py", line 1066, in invoke
  File "click\core.py", line 610, in invoke
  File "click\decorators.py", line 21, in new_func
  File "chia\cmds\plots.py", line 135, in create_cmd
  File "chia\plotting\create_plots.py", line 158, in create_plots
  File "chia\plotting\plot_tools.py", line 110, in add_plot_directory
  File "chia\util\config.py", line 55, in load_config
  File "yaml\__init__.py", line 162, in safe_load
  File "yaml\__init__.py", line 114, in load
  File "yaml\constructor.py", line 49, in get_single_data
  File "yaml\composer.py", line 36, in get_single_node
  File "yaml\composer.py", line 55, in compose_document
  File "yaml\composer.py", line 84, in compose_node
  File "yaml\composer.py", line 133, in compose_mapping_node
  File "yaml\composer.py", line 84, in compose_node
  File "yaml\composer.py", line 127, in compose_mapping_node
  File "yaml\parser.py", line 98, in check_event
  File "yaml\parser.py", line 428, in parse_block_mapping_key
  File "yaml\scanner.py", line 115, in check_token
  File "yaml\scanner.py", line 152, in need_more_tokens
  File "yaml\scanner.py", line 292, in stale_possible_simple_keys
yaml.scanner.ScannerError: while scanning a simple key
  in "C:\Users\Atheros\.chia\mainnet\config\config.yaml", line 280, column 1
could not find expected ':'
  in "C:\Users\Atheros\.chia\mainnet\config\config.yaml", line 281, column 1
