### ISSUE TITLE
[BUG] Status not Sync But Still can plot

### ISSUE THREAD

**Issue by brianlee1982** [Chia-Network/chia-blockchain#4759]
**Describe the bug**
It was plotting fine but Status suddenly changed to Not Available. I waited for the plot to finish 100% and successfully turn into farm status, but the rest of them still not sync. I exit the program and restart, it still can plot but not sync.

None.

**Screenshots**

2021-05-13T09:40:23.173 wallet chia.wallet.wallet_node    : ERROR    Loop exception in sync Was not able to add blocks 61471-61503. Traceback (most recent call last):
  File "chia\wallet\wallet_node.py", line 509, in sync_job
  File "chia\wallet\wallet_node.py", line 606, in _sync
RuntimeError: Was not able to add blocks 61471-61503

2021-05-13T09:40:26.719 daemon asyncio                    : ERROR    Task exception was never retrieved
future: <Task finished coro=<kill_service() done, defined at chia\daemon\server.py:833> exception=AttributeError("'list' object has no attribute 'pid'")>
Traceback (most recent call last):
  File "chia\daemon\server.py", line 841, in kill_service
  File "chia\daemon\server.py", line 805, in kill_process
AttributeError: 'list' object has no attribute 'pid'
2021-05-13T09:42:49.030 wallet wallet_server              : ERROR    Exception:  <class 'concurrent.futures._base.CancelledError'>, closing connection {'host': '2406:da18:d7f:5501:4e34:e391:a8bd:368d', 'port': 8444}. Traceback (most recent call last):
  File "chia\server\server.py", line 531, in api_call
  File "asyncio\tasks.py", line 435, in wait_for
concurrent.futures._base.CancelledError

2021-05-13T09:43:31.675 full_node full_node_server        : ERROR    Exception:  <class 'concurrent.futures._base.CancelledError'>, closing connection {'host': '127.0.0.1', 'port': 8449}. Traceback (most recent call last):
  File "chia\server\server.py", line 531, in api_call
  File "asyncio\tasks.py", line 435, in wait_for
concurrent.futures._base.CancelledError

2021-05-13T10:12:39.263 full_node full_node_server        : WARNING  Banning 82.121.1.84 for 600 seconds
2021-05-13T10:12:39.279 full_node chia.full_node.full_node: ERROR    Error with syncing: <class 'RuntimeError'>Traceback (most recent call last):
  File "chia\full_node\full_node.py", line 628, in _sync
RuntimeError: Weight proof did not arrive in time from peer: 82.121.1.84

2021-05-13T10:15:54.926 full_node chia.full_node.full_node: WARNING  Invalid response for slot None
2021-05-13T10:16:20.104 full_node full_node_server        : WARNING  Banning 190.245.68.131 for 600 seconds
2021-05-13T10:16:20.104 full_node chia.full_node.full_node: ERROR    Error with syncing: <class 'RuntimeError'>Traceback (most recent call last):
  File "chia\full_node\full_node.py", line 628, in _sync
RuntimeError: Weight proof did not arrive in time from peer: 190.245.68.131

2021-05-13T10:22:39.355 full_node full_node_server        : ERROR    Exception:  <class 'concurrent.futures._base.TimeoutError'>, closing connection {'host': '127.0.0.1', 'port': 8449}. Traceback (most recent call last):
  File "chia\server\server.py", line 531, in api_call
  File "asyncio\tasks.py", line 449, in wait_for
concurrent.futures._base.TimeoutError

2021-05-13T10:22:39.364 full_node full_node_server        : WARNING  Trying to ban localhost for 10, but will not ban
2021-05-13T10:22:39.370 full_node asyncio                 : ERROR    Task exception was never retrieved
future: <Task finished coro=<ChiaServer.incoming_api_task.<locals>.api_call() done, defined at chia\server\server.py:482> exception=CancelledError()>
concurrent.futures._base.CancelledError
2021-05-13T10:22:39.377 full_node full_node_server        : ERROR    Exception:  <class 'concurrent.futures._base.CancelledError'>, closing connection {'host': '127.0.0.1', 'port': 8449}. Traceback (most recent call last):
  File "chia\server\server.py", line 531, in api_call
  File "asyncio\tasks.py", line 435, in wait_for
concurrent.futures._base.CancelledError

2021-05-13T10:32:41.168 full_node full_node_server        : ERROR    Exception:  <class 'concurrent.futures._base.TimeoutError'>, closing connection {'host': '127.0.0.1', 'port': 8449}. Traceback (most recent call last):
  File "chia\server\server.py", line 531, in api_call
  File "asyncio\tasks.py", line 449, in wait_for
concurrent.futures._base.TimeoutError

2021-05-13T10:32:41.170 full_node full_node_server        : WARNING  Trying to ban localhost for 10, but will not ban
2021-05-13T10:32:42.924 full_node asyncio                 : ERROR    Task exception was never retrieved
future: <Task finished coro=<ChiaServer.incoming_api_task.<locals>.api_call() done, defined at chia\server\server.py:482> exception=CancelledError()>

**Desktop (please complete the following information):**

- OS:  Win10
- OS Pro
- CPU: Intel Pentium G4560
- Ram 20GB
- 
**Additional context**

**Comment by Edmonas** [comment]
Same issue, lost synchronization and all the farming stopped, still can plot. 
![Not sync](https://user-images.githubusercontent.com/84113476/118071463-7eecdb80-b3b0-11eb-87be-fe726a4e4005.PNG)

**Comment by Edmonas** [comment]
Also noticed that it got stuck on the block height 272270, Shutting down the wallet and restarting did not help
![Stuck](https://user-images.githubusercontent.com/84113476/118072612-dee48180-b3b2-11eb-9302-9eb66477fc1d.PNG)

**Comment by brianlee1982** [comment]
For mine, peak height is at 270884. Now status start to show Syncing. I think must be some problem with their network side that caused this. It happened since around 10 hours ago that it stopped syncing.

**Comment by brianlee1982** [comment]
![image](https://user-images.githubusercontent.com/62213459/118072987-91313e80-b3dd-11eb-99bd-25f89398a995.png)

**Comment by aircoolza** [comment]
in my problem is 

Farm overview in Last Attempted Proof I'm not active  please tell me how to fix 

![รูปที่1](https://www.img.in.th/images/120bf74c582c6329bba203f052ea0871.png)

**Comment by tuthanhnguyen** [comment]
I have same issues, waiting for 12 hours, restarted PC 3 times, but still "not synced"

**Comment by bo3b** [comment]
Might be a regression in 1.1.5.  I was running 1.1.4 without any problems, and just updated to 1.1.5.  Now I'm stuck at "Not Synced" as well.

DevLog shows: ``` DevTools failed to load SourceMap: Could not parse content for file:///C:/Users/bo3b/AppData/Local/chia-blockchain/app-1.1.5/resources/app.asar/build/renderer/js/main.js.map: Unexpected end of JSON input ```

**Comment by tuthanhnguyen** [comment]
Yeah, I got issue after updating to 1.1.5

**Comment by HEITORHOG1** [comment]
I went back to version 1.1.4 now it's normal

**Comment by brianlee1982** [comment]
Now it stopped syncing. I think something is wrong with their mainnet. is like up then system down, then up again.... Just wait for the next update. Still can plot.

**Comment by sbstockmeup** [comment]
I am having the same issues, 1.1.5, Full Node, open port on my network. I have tons of connections but all the connections stop at similar height number and then I get unsynced. 

I just added some random peers and that helped jumpstart the connection but the peer to peer system is having severe issues.

**Comment by grafbcn** [comment]
I have different errors. Ploting well, opened port with NAT in router, turn off firewall, sync clock. But sync is work one hours and others don't work without change anything for my self.
Errors:
`2021-05-16T13:33:07.453 wallet wallet_server              : ERROR    Exception , exception Stack: Traceback (most recent call last):
  File "chia\server\server.py", line 356, in start_client
  File "aiohttp\client.py", line 763, in _ws_connect
  File "aiohttp\client.py", line 521, in _request
  File "aiohttp\connector.py", line 535, in connect
  File "aiohttp\connector.py", line 892, in _create_connection
  File "aiohttp\connector.py", line 1032, in _create_direct_connection
  File "aiohttp\connector.py", line 969, in _wrap_create_connection
  File "asyncio\base_events.py", line 949, in create_connection
  File "asyncio\selector_events.py", line 473, in sock_connect
concurrent.futures._base.CancelledError

2021-05-16T13:36:22.284 full_node chia.rpc.rpc_server     : WARNING  Error while handling message: Traceback (most recent call last):
  File "chia\rpc\rpc_server.py", line 212, in safe_handle
  File "chia\rpc\rpc_server.py", line 200, in ws_api
  File "chia\rpc\rpc_server.py", line 161, in open_connection
ValueError: Start client failed, or server is not set

2021-05-16T13:50:36.763 full_node chia.full_node.full_node: WARNING  Invalid response for slot None
2021-05-16T13:55:32.483 full_node chia.rpc.rpc_server     : WARNING  Error while handling message: Traceback (most recent call last):
  File "chia\rpc\rpc_server.py", line 220, in safe_handle
  File "aiohttp\client_ws.py", line 150, in send_str
  File "aiohttp\http_websocket.py", line 687, in send
  File "aiohttp\http_websocket.py", line 643, in _send_frame
  File "aiohttp\http_websocket.py", line 660, in _write
ConnectionResetError: Cannot write to closing transport

2021-05-16T13:55:32.494 full_node chia.rpc.rpc_server     : WARNING  Exception: Traceback (most recent call last):
  File "chia\rpc\rpc_server.py", line 220, in safe_handle
  File "aiohttp\client_ws.py", line 150, in send_str
  File "aiohttp\http_websocket.py", line 687, in send
  File "aiohttp\http_websocket.py", line 643, in _send_frame
  File "aiohttp\http_websocket.py", line 660, in _write
ConnectionResetError: Cannot write to closing transport

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "chia\rpc\rpc_server.py", line 281, in connect_to_daemon
  File "chia\rpc\rpc_server.py", line 243, in connection
  File "chia\rpc\rpc_server.py", line 231, in safe_handle
  File "aiohttp\client_ws.py", line 150, in send_str
  File "aiohttp\http_websocket.py", line 687, in send
  File "aiohttp\http_websocket.py", line 643, in _send_frame
  File "aiohttp\http_websocket.py", line 660, in _write
ConnectionResetError: Cannot write to closing transport
 <class 'ConnectionResetError'>
2021-05-16T13:58:29.883 full_node full_node_server        : ERROR    Exception:  <class 'concurrent.futures._base.TimeoutError'>, closing connection {'host': '81.82.254.192', 'port': 8444}. Traceback (most recent call last):
  File "chia\server\server.py", line 531, in api_call
  File "asyncio\tasks.py", line 449, in wait_for
concurrent.futures._base.TimeoutError

2021-05-16T13:58:29.942 full_node full_node_server        : WARNING  Banning 81.82.254.192 for 10 seconds
2021-05-16T13:58:29.945 full_node asyncio                 : ERROR    Task exception was never retrieved
future: <Task finished coro=<ChiaServer.incoming_api_task.<locals>.api_call() done, defined at chia\server\server.py:482> exception=CancelledError()>
concurrent.futures._base.CancelledError
2021-05-16T13:58:29.949 full_node full_node_server        : ERROR    Exception:  <class 'concurrent.futures._base.CancelledError'>, closing connection {'host': '81.82.254.192', 'port': 8444}. Traceback (most recent call last):
  File "chia\server\server.py", line 531, in api_call
  File "asyncio\tasks.py", line 435, in wait_for
concurrent.futures._base.CancelledError

2021-05-16T13:58:29.953 full_node full_node_server        : ERROR    Exception:  <class 'concurrent.futures._base.CancelledError'>, closing connection {'host': '81.82.254.192', 'port': 8444}. Traceback (most recent call last):
  File "chia\server\server.py", line 531, in api_call
  File "asyncio\tasks.py", line 435, in wait_for
concurrent.futures._base.CancelledError

2021-05-16T13:58:29.956 full_node full_node_server        : ERROR    Exception:  <class 'concurrent.futures._base.CancelledError'>, closing connection {'host': '81.82.254.192', 'port': 8444}. Traceback (most recent call last):
  File "chia\server\server.py", line 531, in api_call
  File "asyncio\tasks.py", line 435, in wait_for
concurrent.futures._base.CancelledError

2021-05-16T13:58:29.958 full_node full_node_server        : ERROR    Exception:  <class 'concurrent.futures._base.CancelledError'>, closing connection {'host': '81.82.254.192', 'port': 8444}. Traceback (most recent call last):
  File "chia\server\server.py", line 531, in api_call
  File "asyncio\tasks.py", line 435, in wait_for
concurrent.futures._base.CancelledError

2021-05-16T13:58:29.961 full_node full_node_server        : ERROR    Exception:  <class 'concurrent.futures._base.CancelledError'>, closing connection {'host': '81.82.254.192', 'port': 8444}. Traceback (most recent call last):
  File "chia\server\server.py", line 531, in api_call
  File "asyncio\tasks.py", line 435, in wait_for
concurrent.futures._base.CancelledError

2021-05-16T13:58:29.964 full_node full_node_server        : ERROR    Exception:  <class 'concurrent.futures._base.CancelledError'>, closing connection {'host': '81.82.254.192', 'port': 8444}. Traceback (most recent call last):
  File "chia\server\server.py", line 531, in api_call
  File "asyncio\tasks.py", line 435, in wait_for
concurrent.futures._base.CancelledError

2021-05-16T13:58:29.968 full_node full_node_server        : ERROR    Exception:  <class 'concurrent.futures._base.CancelledError'>, closing connection {'host': '81.82.254.192', 'port': 8444}. Traceback (most recent call last):
  File "chia\server\server.py", line 531, in api_call
  File "asyncio\tasks.py", line 435, in wait_for
concurrent.futures._base.CancelledError

2021-05-16T13:58:29.971 full_node full_node_server        : ERROR    Exception:  <class 'concurrent.futures._base.CancelledError'>, closing connection {'host': '81.82.254.192', 'port': 8444}. Traceback (most recent call last):
  File "chia\server\server.py", line 531, in api_call
  File "asyncio\tasks.py", line 435, in wait_for
concurrent.futures._base.CancelledError

2021-05-16T14:00:40.646 full_node chia.full_node.full_node: WARNING  Invalid response for slot None
2021-05-16T14:00:40.728 full_node chia.full_node.full_node: WARNING  Invalid response for slot None
2021-05-16T14:02:06.139 full_node full_node_server        : ERROR    Exception:  <class 'concurrent.futures._base.CancelledError'>, closing connection {'host': '95.67.30.4', 'port': 8449}. Traceback (most recent call last):
  File "chia\server\server.py", line 531, in api_call
  File "asyncio\tasks.py", line 435, in wait_for
concurrent.futures._base.CancelledError

2021-05-16T14:05:16.213 full_node chia.rpc.rpc_server     : WARNING  Error while handling message: Traceback (most recent call last):
  File "chia\rpc\rpc_server.py", line 220, in safe_handle
  File "aiohttp\client_ws.py", line 150, in send_str
  File "aiohttp\http_websocket.py", line 687, in send
  File "aiohttp\http_websocket.py", line 643, in _send_frame
  File "aiohttp\http_websocket.py", line 660, in _write
ConnectionResetError: Cannot write to closing transport

2021-05-16T14:05:16.356 full_node chia.rpc.rpc_server     : WARNING  Exception: Traceback (most recent call last):
  File "chia\rpc\rpc_server.py", line 220, in safe_handle
  File "aiohttp\client_ws.py", line 150, in send_str
  File "aiohttp\http_websocket.py", line 687, in send
  File "aiohttp\http_websocket.py", line 643, in _send_frame
  File "aiohttp\http_websocket.py", line 660, in _write
ConnectionResetError: Cannot write to closing transport

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "chia\rpc\rpc_server.py", line 281, in connect_to_daemon
  File "chia\rpc\rpc_server.py", line 243, in connection
  File "chia\rpc\rpc_server.py", line 231, in safe_handle
  File "aiohttp\client_ws.py", line 150, in send_str
  File "aiohttp\http_websocket.py", line 687, in send
  File "aiohttp\http_websocket.py", line 643, in _send_frame
  File "aiohttp\http_websocket.py", line 660, in _write
ConnectionResetError: Cannot write to closing transport
 <class 'ConnectionResetError'>
2021-05-16T14:06:58.873 full_node full_node_server        : ERROR    Exception:  <class 'concurrent.futures._base.CancelledError'>, closing connection {'host': '84.9.247.245', 'port': 8444}. Traceback (most recent call last):
  File "chia\server\server.py", line 531, in api_call
  File "asyncio\tasks.py", line 435, in wait_for
concurrent.futures._base.CancelledError

2021-05-16T14:07:00.495 full_node full_node_server        : ERROR    Exception:  <class 'concurrent.futures._base.CancelledError'>, closing connection {'host': '79.157.1.3', 'port': 8444}. Traceback (most recent call last):
  File "chia\server\server.py", line 531, in api_call
  File "asyncio\tasks.py", line 435, in wait_for
concurrent.futures._base.CancelledError

2021-05-16T14:07:28.974 full_node full_node_server        : ERROR    Exception:  <class 'concurrent.futures._base.CancelledError'>, closing connection {'host': '95.12.126.128', 'port': 8444}. Traceback (most recent call last):
  File "chia\server\server.py", line 531, in api_call
  File "asyncio\tasks.py", line 435, in wait_for
concurrent.futures._base.CancelledError

2021-05-16T14:08:15.059 full_node full_node_server        : ERROR    Exception:  <class 'concurrent.futures._base.CancelledError'>, closing connection {'host': '85.221.144.199', 'port': 8444}. Traceback (most recent call last):
  File "chia\server\server.py", line 531, in api_call
  File "asyncio\tasks.py", line 435, in wait_for
concurrent.futures._base.CancelledError

2021-05-16T14:08:45.162 full_node full_node_server        : ERROR    Exception:  <class 'concurrent.futures._base.CancelledError'>, closing connection {'host': '46.182.136.100', 'port': 8444}. Traceback (most recent call last):
  File "chia\server\server.py", line 531, in api_call
  File "asyncio\tasks.py", line 435, in wait_for
concurrent.futures._base.CancelledError

2021-05-16T14:09:50.710 full_node full_node_server        : ERROR    Exception:  <class 'concurrent.futures._base.CancelledError'>, closing connection {'host': '90.255.16.229', 'port': 8444}. Traceback (most recent call last):
  File "chia\server\server.py", line 531, in api_call
  File "asyncio\tasks.py", line 435, in wait_for
concurrent.futures._base.CancelledError

2021-05-16T14:10:14.282 full_node full_node_server        : ERROR    Exception:  <class 'concurrent.futures._base.CancelledError'>, closing connection None. Traceback (most recent call last):
  File "chia\server\server.py", line 531, in api_call
  File "asyncio\tasks.py", line 435, in wait_for
concurrent.futures._base.CancelledError

2021-05-16T14:10:43.000 full_node full_node_server        : WARNING  Cannot write to closing transport 70.53.225.62
2021-05-16T14:10:43.006 full_node full_node_server        : ERROR    Exception:  <class 'concurrent.futures._base.CancelledError'>, closing connection {'host': '70.53.225.62', 'port': 8444}. Traceback (most recent call last):
  File "chia\server\server.py", line 531, in api_call
  File "asyncio\tasks.py", line 435, in wait_for
concurrent.futures._base.CancelledError

2021-05-16T14:20:38.981 full_node full_node_server        : ERROR    Exception:  <class 'concurrent.futures._base.CancelledError'>, closing connection {'host': '94.41.85.111', 'port': 8444}. Traceback (most recent call last):
  File "chia\server\server.py", line 531, in api_call
  File "asyncio\tasks.py", line 435, in wait_for
concurrent.futures._base.CancelledError

2021-05-16T14:25:44.136 full_node full_node_server        : ERROR    Exception:  <class 'concurrent.futures._base.CancelledError'>, closing connection {'host': '14.155.159.230', 'port': 8444}. Traceback (most recent call last):
  File "chia\server\server.py", line 531, in api_call
  File "asyncio\tasks.py", line 435, in wait_for
concurrent.futures._base.CancelledError

2021-05-16T14:30:57.773 full_node full_node_server        : ERROR    Exception:  <class 'concurrent.futures._base.CancelledError'>, closing connection {'host': '90.255.16.229', 'port': 8444}. Traceback (most recent call last):
  File "chia\server\server.py", line 531, in api_call
  File "asyncio\tasks.py", line 435, in wait_for
concurrent.futures._base.CancelledError

2021-05-16T14:31:34.279 full_node full_node_server        : ERROR    Exception:  <class 'concurrent.futures._base.CancelledError'>, closing connection {'host': '85.221.144.199', 'port': 8444}. Traceback (most recent call last):
  File "chia\server\server.py", line 531, in api_call
  File "asyncio\tasks.py", line 435, in wait_for
concurrent.futures._base.CancelledError

2021-05-16T15:11:24.522 full_node full_node_server        : ERROR    Exception: Error short batch syncing, invalid/no response for 289325-289357, None. Traceback (most recent call last):
  File "chia\server\server.py", line 521, in wrapped_coroutine
  File "chia\full_node\full_node_api.py", line 104, in new_peak
  File "chia\full_node\full_node.py", line 374, in new_peak
  File "chia\full_node\full_node.py", line 246, in short_sync_batch
ValueError: Error short batch syncing, invalid/no response for 289325-289357

2021-05-16T15:11:24.530 full_node full_node_server        : ERROR    Exception: Error short batch syncing, invalid/no response for 289325-289357 <class 'ValueError'>, closing connection None. Traceback (most recent call last):
  File "chia\server\server.py", line 531, in api_call
  File "asyncio\tasks.py", line 414, in wait_for
  File "chia\server\server.py", line 528, in wrapped_coroutine
  File "chia\server\server.py", line 521, in wrapped_coroutine
  File "chia\full_node\full_node_api.py", line 104, in new_peak
  File "chia\full_node\full_node.py", line 374, in new_peak
  File "chia\full_node\full_node.py", line 246, in short_sync_batch
ValueError: Error short batch syncing, invalid/no response for 289325-289357

2021-05-16T15:11:34.411 full_node full_node_server        : ERROR    Exception: Error short batch syncing, invalid/no response for 289336-289368, None. Traceback (most recent call last):
  File "chia\server\server.py", line 521, in wrapped_coroutine
  File "chia\full_node\full_node_api.py", line 104, in new_peak
  File "chia\full_node\full_node.py", line 374, in new_peak
  File "chia\full_node\full_node.py", line 246, in short_sync_batch
ValueError: Error short batch syncing, invalid/no response for 289336-289368

2021-05-16T15:11:34.415 full_node full_node_server        : ERROR    Exception: Error short batch syncing, invalid/no response for 289336-289368 <class 'ValueError'>, closing connection None. Traceback (most recent call last):
  File "chia\server\server.py", line 531, in api_call
  File "asyncio\tasks.py", line 414, in wait_for
  File "chia\server\server.py", line 528, in wrapped_coroutine
  File "chia\server\server.py", line 521, in wrapped_coroutine
  File "chia\full_node\full_node_api.py", line 104, in new_peak
  File "chia\full_node\full_node.py", line 374, in new_peak
  File "chia\full_node\full_node.py", line 246, in short_sync_batch
ValueError: Error short batch syncing, invalid/no response for 289336-289368

2021-05-16T15:11:36.309 full_node full_node_server        : ERROR    Exception: Error short batch syncing, invalid/no response for 289337-289369, None. Traceback (most recent call last):
  File "chia\server\server.py", line 521, in wrapped_coroutine
  File "chia\full_node\full_node_api.py", line 104, in new_peak
  File "chia\full_node\full_node.py", line 374, in new_peak
  File "chia\full_node\full_node.py", line 246, in short_sync_batch
ValueError: Error short batch syncing, invalid/no response for 289337-289369

2021-05-16T15:11:36.313 full_node full_node_server        : ERROR    Exception: Error short batch syncing, invalid/no response for 289337-289369 <class 'ValueError'>, closing connection None. Traceback (most recent call last):
  File "chia\server\server.py", line 531, in api_call
  File "asyncio\tasks.py", line 414, in wait_for
  File "chia\server\server.py", line 528, in wrapped_coroutine
  File "chia\server\server.py", line 521, in wrapped_coroutine
  File "chia\full_node\full_node_api.py", line 104, in new_peak
  File "chia\full_node\full_node.py", line 374, in new_peak
  File "chia\full_node\full_node.py", line 246, in short_sync_batch
ValueError: Error short batch syncing, invalid/no response for 289337-289369

2021-05-16T16:39:38.910 full_node full_node_server        : WARNING  Cannot write to closing transport 158.140.137.102
2021-05-16T16:39:38.920 full_node full_node_server        : ERROR    Exception:  <class 'concurrent.futures._base.CancelledError'>, closing connection {'host': '158.140.137.102', 'port': 8444}. Traceback (most recent call last):
  File "chia\server\server.py", line 531, in api_call
  File "asyncio\tasks.py", line 435, in wait_for
concurrent.futures._base.CancelledError
`

**Comment by rtom098** [comment]
got the same, it starts synching sometimes lile 22300/30000 but then stops.


2021-05-18T20:34:42.910 full_node full_node_server        : WARNING  Banning X1.67.195.XX for 600 seconds
2021-05-18T20:34:42.913 full_node chia.full_node.full_node: ERROR    Error with syncing: <class 'RuntimeError'>Traceback (most recent call last):
  File "chia\full_node\full_node.py", line 628, in _sync
RuntimeError: Weight proof did not arrive in time from peer: X1.67.195.XX

**Comment by mauibilly** [comment]
Same issue. Mac Mojave. Upgraded to 1.16 and haven't been able to connect since then? Suggestions????
