### ISSUE TITLE
[BUG] Wallet sync exception while running `chia wallet show`

### ISSUE THREAD

**Issue by gldecurtins** [Chia-Network/chia-blockchain#4792]
**Describe the bug**
I've set loglevel to INFO for the wallet and noticed that the sync can get cancelled if you execute `chia wallet show`.

**To Reproduce**

1. Reset the wallet - delete the databases
2. Set the loglevel of wallet to INFO
3. Start synchronisation
4. Execute `chia wallet show`while you see the money bags (💰).

**Expected behavior**
Ideally it continues syncing, as the sync already takes a long time...

**Versions**
chia-blockchain: 1.1.5
Python: 3.9.4

**Logs**
```
2021-05-13T09:00:06.415 wallet chia.wallet.wallet_blockchain: INFO     💰 Updated wallet peak to height 259571, weight 11850011, 
2021-05-13T09:00:06.728 wallet chia.wallet.wallet_blockchain: INFO     💰 Updated wallet peak to height 259572, weight 11850178, 
2021-05-13T09:00:07.040 wallet chia.wallet.wallet_blockchain: INFO     💰 Updated wallet peak to height 259573, weight 11850345, 
2021-05-13T09:00:09.113 wallet chia.wallet.wallet_node    : INFO     self._close
2021-05-13T09:00:09.114 wallet chia.wallet.wallet_node    : INFO     self._await_closed
2021-05-13T09:00:09.118 wallet wallet_server              : INFO     Connection closed: 127.0.0.1, node id: xxx
2021-05-13T09:00:10.539 wallet wallet                     : INFO     Reconnecting to peer {'host': '127.0.0.1', 'port': 8444}
2021-05-13T09:00:12.409 wallet chia.wallet.wallet_blockchain: ERROR    Error during db transaction: 
2021-05-13T09:00:12.573 wallet chia.wallet.wallet_node    : ERROR    Error while trying to fetch from peer:no active connection Traceback (most recent call last):
  File "/opt/chia-blockchain/chia/wallet/wallet_blockchain.py", line 225, in receive_block
    fork_height: Optional[uint32] = await self._reconsider_peak(
  File "/opt/chia-blockchain/chia/wallet/wallet_blockchain.py", line 274, in _reconsider_peak
    await self.reorg_rollback(fork_h)
  File "/opt/chia-blockchain/chia/wallet/wallet_state_manager.py", line 917, in reorg_rollback
    reorged: List[TransactionRecord] = await self.tx_store.get_transaction_above(height)
  File "/opt/chia-blockchain/chia/wallet/wallet_transaction_store.py", line 435, in get_transaction_above
    await cursor.close()
  File "/opt/chia-blockchain/venv/lib/python3.9/site-packages/aiosqlite/cursor.py", line 69, in close
    await self._execute(self._cursor.close)
  File "/opt/chia-blockchain/venv/lib/python3.9/site-packages/aiosqlite/cursor.py", line 31, in _execute
    return await self._conn._execute(fn, *args, **kwargs)
  File "/opt/chia-blockchain/venv/lib/python3.9/site-packages/aiosqlite/core.py", line 129, in _execute
    return await future
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/chia-blockchain/chia/wallet/wallet_node.py", line 596, in _sync
    added, advanced_peak = await self.fetch_blocks_and_validate(
  File "/opt/chia-blockchain/chia/wallet/wallet_node.py", line 683, in fetch_blocks_and_validate
    (result, error, fork_h,) = await self.wallet_state_manager.blockchain.receive_block(
  File "/opt/chia-blockchain/chia/wallet/wallet_blockchain.py", line 231, in receive_block
    await self.block_store.db_wrapper.rollback_transaction()
  File "/opt/chia-blockchain/chia/util/db_wrapper.py", line 24, in rollback_transaction
    if self.db.in_transaction:
  File "/opt/chia-blockchain/venv/lib/python3.9/site-packages/aiosqlite/core.py", line 258, in in_transaction
    return self._conn.in_transaction
  File "/opt/chia-blockchain/venv/lib/python3.9/site-packages/aiosqlite/core.py", line 67, in _conn
    raise ValueError("no active connection")
ValueError: no active connection

2021-05-13T09:00:12.575 wallet chia.wallet.wallet_node    : ERROR    Loop exception in sync Was not able to add blocks 259565-259597. Traceback (most recent call last):
  File "/opt/chia-blockchain/chia/wallet/wallet_node.py", line 509, in sync_job
    await self._sync()
  File "/opt/chia-blockchain/chia/wallet/wallet_node.py", line 606, in _sync
    raise RuntimeError(f"Was not able to add blocks {start_height}-{end_height}")
RuntimeError: Was not able to add blocks 259565-259597

2021-05-13T09:00:12.576 wallet chia.wallet.wallet_node    : INFO     Loop end in sync job
2021-05-13T09:00:12.577 wallet chia.wallet.wallet_node    : INFO     Loop start in sync job
```

**Comment by pangchia** [comment]
i have same issue

**Comment by mariano54** [comment]
Many bugs related to wallet syncing have been fixed. Please update and follow the steps here https://github.com/Chia-Network/chia-blockchain/issues/6993, and continue discussion in that thread instead.
