### ISSUE TITLE
[BUG] Plot stopped (ConnectionClosedError: code = 1006 )

### ISSUE THREAD

**Issue by Yajiinn** [Chia-Network/chia-blockchain#4798]
Plot stops at %87-%89 and does not continue. Error in log file ;

2021-05-13T12:15:02.954 daemon _main_                   : ERROR    Unexpected exception trying to send to websocket: code = 1006 (connection closed abnormally [internal]), no reason Traceback (most recent call last):
  File "websockets\protocol.py", line 838, in transfer_data
concurrent.futures._base.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "chia\daemon\server.py", line 187, in safe_handle
  File "websockets\protocol.py", line 555, in send
  File "websockets\protocol.py", line 812, in ensure_open
websockets.exceptions.ConnectionClosedError: code = 1006 (connection closed abnormally [internal]), no reason

What is the reason of this error ? Help please. Thanks.
![error](https://user-images.githubusercontent.com/83921458/118109374-c479ca80-b3e9-11eb-9c82-e1d69e260084.png)

**Comment by mariano54** [comment]
Probably a bad plot. This crash will be fixed in the next release

**Comment by Yajiinn** [comment]
I hope so

**Comment by Yajiinn** [comment]
Thank you for your interest.

**Comment by njtnestor** [comment]
Where is that log file?

**Comment by Yajiinn** [comment]
C:\Users\Administrator\.chia\mainnet\log

**Comment by Yajiinn** [comment]
C:\Users\username\.chia\mainnet\log

**Comment by Yajiinn** [comment]
C:\Users\username\.chia\mainnet\log

**Comment by Cumulo56** [comment]
2021-07-16T12:11:56.906 daemon websockets.protocol        : ERROR    Error in data transfer
Traceback (most recent call last):
  File "websockets\protocol.py", line 827, in transfer_data
  File "websockets\protocol.py", line 895, in read_message
  File "websockets\protocol.py", line 995, in read_data_frame
  File "websockets\protocol.py", line 766, in pong
  File "websockets\protocol.py", line 803, in ensure_open
websockets.exceptions.ConnectionClosedError: code = 1006 (connection closed abnormally [internal]), no reason
2021-07-16T12:12:00.949 daemon __main__                   : ERROR    Unexpected exception trying to send to websocket: code = 1006 (connection closed abnormally [internal]), no reason Traceback (most recent call last):
  File "websockets\protocol.py", line 838, in transfer_data
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\a\chia-blockchain\chia-blockchain\venv\Lib\site-packages\chia\daemon\server.py", line 187, in safe_handle
  File "websockets\protocol.py", line 555, in send
  File "websockets\protocol.py", line 803, in ensure_open
websockets.exceptions.ConnectionClosedError: code = 1006 (connection closed abnormally [internal]), no reason

**Comment by Cumulo56** [comment]
Chia 1.2.2 installed

Last Attempted Proof since 1.2.0 very slow / invalid
