### ISSUE TITLE
[BUG]  it just keeps loading on Connecting to the wallet 

### ISSUE THREAD

**Issue by impoziss** [Chia-Network/chia-blockchain#4829]
When I try to open the Chia Blockchain application it just keeps loading on Connecting to the wallet 
Here is the screenshot
https://gyazo.com/3a9124a19ac3de4d7ab84ad29b58efbf

On windows 10 latest version and Chia version 1.1.5

**Comment by peacebaylan** [comment]
aynısını bende yaşıyorum

**Comment by bassivity** [comment]
Similar thing here. I was plotting for a good 8 hours, got to 78% or something like that and when i maximized app window after a few mins, it stuck on this same message as above
Connecting to the wallet ...and its stuck there for good half an hour. 
whew, 8 hours of plotting lost :D

**Comment by deslumoprime** [comment]
Restart. Everyone has the same issues. Happens to me too, and restarting seems to be the only thing. If you want a better experience, there's always Linux CLI, where these common issues don't happen.

**Comment by Reflect-DAo** [comment]
I have the following in the error log:

can anyone help with that ?

2021-05-15T17:28:12.976 full_node chia.rpc.rpc_server     : WARNING  Cannot connect to daemon at ws://localhost:55400
2021-05-15T17:28:14.981 full_node chia.rpc.rpc_server     : WARNING  Cannot connect to daemon at ws://localhost:55400
2021-05-15T17:28:16.991 full_node chia.rpc.rpc_server     : WARNING  Cannot connect to daemon at ws://localhost:55400
2021-05-15T17:28:18.983 full_node chia.rpc.rpc_server     : WARNING  Cannot connect to daemon at ws://localhost:55400
2021-05-15T17:28:20.989 full_node chia.rpc.rpc_server     : WARNING  Cannot connect to daemon at ws://localhost:55400
2021-05-15T17:28:22.987 full_node chia.rpc.rpc_server     : WARNING  Cannot connect to daemon at ws://localhost:55400
2021-05-15T17:28:24.995 full_node chia.rpc.rpc_server     : WARNING  Cannot connect to daemon at ws://localhost:55400
2021-05-15T17:28:27.000 full_node chia.rpc.rpc_server     : WARNING  Cannot connect to daemon at ws://localhost:55400
2021-05-15T17:28:29.010 full_node chia.rpc.rpc_server     : WARNING  Cannot connect to daemon at ws://localhost:55400
2021-05-15T17:28:31.017 full_node chia.rpc.rpc_server     : WARNING  Cannot connect to daemon at ws://localhost:55400
2021-05-15T17:29:30.119 daemon websockets.protocol        : ERROR    Error in data transfer
Traceback (most recent call last):
  File "websockets\protocol.py", line 827, in transfer_data
  File "websockets\protocol.py", line 895, in read_message
  File "websockets\protocol.py", line 995, in read_data_frame
  File "websockets\protocol.py", line 766, in pong
  File "websockets\protocol.py", line 803, in ensure_open
websockets.exceptions.ConnectionClosedError: code = 1006 (connection closed abnormally [internal]), no reason
2021-05-15T17:33:13.890 daemon websockets.protocol        : ERROR    Error in data transfer
