### ISSUE TITLE
bug wallet connection (5444)

### ISSUE THREAD

**Issue by muratsoydanduyar** [Chia-Network/chia-blockchain#4841]
![start issue](https://user-images.githubusercontent.com/84150397/118170521-daf84400-b432-11eb-955b-7d047e12b164.jpg)
when I start programme, the programme get to us this error every time.
errror code 
.
2021-05-13T13:34:09.255 full_node chia.full_node.full_node: WARNING  Wasn't able to add transaction with id 34c2e40640c674b3e452f1f1e92a4863047e84fcbd89ffb845649ecbf95b4836, status 3 error: Err.DOUBLE_SPEND
2021-05-13T13:34:14.293 full_node chia.full_node.full_node: WARNING  Wasn't able to add transaction with id a361d5b64cd12459b70f8299cb750129b78003a8391d8c8cb0b71e1049a05be9, status 3 error: Err.DOUBLE_SPEND
2021-05-13T13:34:14.295 full_node chia.full_node.full_node: WARNING  Wasn't able to add transaction with id c75eb8138603a7ed49d0dc345a5ad53551eed247416e7fd9b7b3d733808c4e74, status 3 error: Err.DOUBLE_SPEND
2021-05-13T13:34:14.297 full_node chia.full_node.full_node: WARNING  Wasn't able to add transaction with id 788e75f140fa4e834ff56da5a5f292247781efc74a497c2582c997d3dd87210d, status 3 error: Err.DOUBLE_SPEND
2021-05-13T13:34:14.298 full_node chia.full_node.full_node: WARNING  Wasn't able to add transaction with id 820c8fc8d18e7b0a7c21b2472f1e135517b265e676702d65119cc0ebf2735f55, status 3 error: Err.DOUBLE_SPEND
2021-05-13T13:34:14.299 full_node chia.full_node.full_node: WARNING  Wasn't able to add transaction with id 6d65f1f89261d445558b69787205c522ef03b4314b773fe3efb1703ee22baa8d, status 3 error: Err.DOUBLE_SPEND
2021-05-13T13:34:14.300 full_node chia.full_node.full_node: WARNING  Wasn't able to add transaction with id 31334eb074a5a267ee7fce4fb1ed70378198bf1f7731076b2b715c765143e515, status 3 error: Err.DOUBLE_SPEND
2021-05-13T13:34:14.301 full_node chia.full_node.full_node: WARNING  Wasn't able to add transaction with id f013663af32e40433f51e5d4c3a05344d20a4c8e9c0f15ad1a11c2f3f9acaaa3, status 3 error: Err.DOUBLE_SPEND
2021-05-13T13:34:17.621 full_node chia.rpc.rpc_server     : WARNING  Cannot connect to daemon at ws://localhost:55400
2021-05-13T13:34:17.637 wallet chia.rpc.rpc_server        : WARNING  Cannot connect to daemon at ws://localhost:55400
2021-05-13T13:34:18.337 farmer chia.rpc.rpc_server        : WARNING  Cannot connect to daemon at ws://localhost:55400
2021-05-13T13:34:18.475 harvester chia.rpc.rpc_server     : WARNING  Cannot connect to daemon at ws://localhost:55400
2021-05-13T13:34:20.215 full_node chia.full_node.full_node: WARNING  Wasn't able to add transaction with id a38b99c7095fc3476c5f77bc3bdf3c056585fd48ed493e40ebaa38d060863d62, status 3 error: Err.DOUBLE_SPEND
2021-05-13T13:34:20.512 full_node chia.full_node.full_node: WARNING  Wasn't able to add transaction with id 78f10ebef3402c1bc1cbd47ae2c8f95263ce3f3cbe7e54a3e06e7bdf2aa0f548, status 3 error: Err.DOUBLE_SPEND
2021-05-13T13:34:20.513 full_node chia.full_node.full_node: WARNING  Wasn't able to add transaction with id 6da177c574ea0d08e55df59854cd7567f20ca308a65b4b61bc0e6cf078dbe41d, status 3 error: Err.DOUBLE_SPEND
2021-05-13T13:34:23.692 full_node chia.rpc.rpc_server     : WARNING  Cannot connect to daemon at ws://localhost:55400
2021-05-13T13:34:23.708 wallet chia.rpc.rpc_server        : WARNING  Cannot connect to daemon at ws://localhost:55400
2021-05-13T13:34:24.420 farmer chia.rpc.rpc_server        : WARNING  Cannot connect to daemon at ws://localhost:55400
2021-05-13T13:34:24.729 harvester chia.rpc.rpc_server     : WARNING  Cannot connect to daemon at ws://localhost:55400
2021-05-13T13:34:26.457 harvester chia.plotting.plot_tools: WARNING  Directory: D:\farm does not exist.
2021-05-13T13:34:27.198 full_node chia.full_node.full_node: WARNING  Wasn't able to add transaction with id b09dc830535fe5e3d78e12e7c71361dcbc09efb3332250d9455ff5953d97eb73, status 3 error: Err.UNKNOWN_UNSPENT
2021-05-13T13:34:29.790 wallet chia.rpc.rpc_server        : WARNING  Cannot connect to daemon at ws://localhost:55400
2021-05-13T13:34:29.960 full_node chia.rpc.rpc_server     : WARNING  Cannot connect to daemon at ws://localhost:55400
2021-05-13T13:34:31.084 full_node chia.full_node.full_node: WARNING  Wasn't able to add transaction with id 8ba4f2004c4b083ec5b6a478662e09fa542689670993a830ce08477f359fd9f9, status 3 error: Err.UNKNOWN_UNSPENT
2021-05-13T13:34:30.644 farmer chia.rpc.rpc_server        : WARNING  Cannot connect to daemon at ws://localhost:55400
2021-05-13T13:34:32.270 full_node chia.full_node.full_node: WARNING  Wasn't able to add transaction with id bf3334740e3084fffc4773ebdbe6e07b039ddda97e38023095cc5084f6b88c67, status 3 error: Err.UNKNOWN_UNSPENT
2021-05-13T13:34:30.813 harvester chia.rpc.rpc_server     : WARNING  Cannot connect to daemon at ws://localhost:55400
2021-05-13T14:11:01.295 harvester chia.plotting.plot_tools: WARNING  Directory: D:\farm does not exist.
2021-05-13T14:11:01.494 harvester chia.harvester.harvester: WARNING  Not farming any plots on this harvester. Check your configuration.
2021-05-13T14:26:43.115 harvester chia.plotting.plot_tools: WARNING  Directory: D:\farm does not exist.
2021-05-13T14:26:43.116 harvester chia.harvester.harvester: WARNING  Not farming any plots on this harvester. Check your configuration.
2021-05-13T14:34:18.067 harvester chia.rpc.rpc_server     : WARNING  Cannot connect to daemon at ws://localhost:55400
2021-05-13T14:34:18.082 farmer chia.rpc.rpc_server        : WARNING  Cannot connect to daemon at ws://localhost:55400
2021-05-13T14:34:18.067 wallet chia.rpc.rpc_server        : WARNING  Cannot connect to daemon at ws://localhost:55400
2021-05-13T14:34:24.159 harvester chia.rpc.rpc_server     : WARNING  Cannot connect to daemon at ws://localhost:55400
2021-05-13T14:34:24.175 farmer chia.rpc.rpc_server        : WARNING  Cannot connect to daemon at ws://localhost:55400
2021-05-13T14:34:25.155 wallet chia.rpc.rpc_server        : WARNING  Cannot connect to daemon at ws://localhost:55400
2021-05-13T14:34:30.259 harvester chia.rpc.rpc_server     : WARNING  Cannot connect to daemon at ws://localhost:55400
2021-05-13T14:34:31.571 wallet chia.rpc.rpc_server        : WARNING  Cannot connect to daemon at ws://localhost:55400
2021-05-13T14:34:30.274 farmer chia.rpc.rpc_server        : WARNING  Cannot connect to daemon at ws://localhost:55400
2021-05-13T15:21:44.202 harvester chia.plotting.plot_tools: WARNING  Directory: D:\farm does not exist.
2021-05-13T15:21:44.350 harvester chia.harvester.harvester: WARNING  Not farming any plots on this harvester. Check your configuration.
2021-05-13T15:24:08.359 harvester chia.plotting.plot_tools: WARNING  Directory: D:\farm does not exist.
2021-05-13T15:24:08.360 harvester chia.harvester.harvester: WARNING  Not farming any plots on this harvester. Check your configuration.
2021-05-13T15:31:31.115 harvester chia.rpc.rpc_server     : WARNING  Cannot connect to daemon at ws://localhost:55400
2021-05-13T15:31:31.147 farmer chia.rpc.rpc_server        : WARNING  Cannot connect to daemon at ws://localhost:55400
2021-05-13T15:31:37.163 harvester chia.rpc.rpc_server     : WARNING  Cannot connect to daemon at ws://localhost:55400
2021-05-13T15:31:37.216 farmer chia.rpc.rpc_server        : WARNING  Cannot connect to daemon at ws://localhost:55400
system: i7 intel 7700hq. 8gb ram. win 1o home pre.
_

- pls help huury up to us thanks for all

_ ###

**Comment by Vagex** [comment]
clean all
resintall
but first backup the file: C:\Users\Administrator\.chia\mainnet\db\blockchain_v1_mainnet.sqlite

**Comment by nothinglastsforever** [comment]
> but first backup the file: C:\Users\Administrator.chia\mainnet\db\blockchain_v1_mainnet.sqlite

If they don't backup the C:\Users\Administrator\.chia\mainnet\wallet\db\blockchain_wallet_v1_mainnet_XXXXXXXXXX.sqlite file they'll still have to sync the 2.4GB wallet sql file, which is a mistake I made and now I'm paying dearly: 12 hours and only 32% synced. The blockchain_v1_mainnet.sqlite I backed up and copied back is also stuck at Syncing 274558/277869 and hasn't moved for 12 hours.

**Comment by chahurec** [comment]
> clean all
> reinstall
> but first backup the file: C:\Users\Administrator.chia\mainnet\db\blockchain_v1_mainnet.sqlite

doesnt help. only other ssd with other windows can help. i tried it with 1.1.3 & 1.1.4 and 1.1.5 still not working

**Comment by chahurec** [comment]
u should delete .chia in C:\Users\_____ and chia-blockchain in C:\Users\________\AppData\Local\ and reinstall

**Comment by Plopsi** [comment]
I had (and probaly will) such issues in the past. For me it was enough to delete the wallet/db folder. without reinstall.

For me it looks like the wallet db files got corrupted and chia has currently no good recovery strategy.

**Comment by chahurec** [comment]
> I had (and probaly will) such issues in the past. For me it was enough to delete the wallet/db folder. without reinstall.
> 
> For me it looks like the wallet db files got corrupted and chia has currently no good recovery strategy.

maybe ur decision looks like better

**Comment by Plopsi** [comment]
Be aware that it takes some while for the wallet to resync agains the chain, even that it uses the local fullnode. So don't be frightened that the wallet looks empty at start. You can check the wallet sync state under *giggles* the tab "Wallets" :D

**Comment by nothinglastsforever** [comment]
> Be aware that it takes some while for the wallet to resync agains the chain, even that it uses the local fullnode. So don't be frightened that the wallet looks empty at start. You can check the wallet sync state under _giggles_ the tab "Wallets" :D

Does the wallet have to be fully synced before the full node can be synced again? I'm in this very conundrum currently where the full node is stuck.

![image](https://user-images.githubusercontent.com/6544432/118238062-9a4c0980-b4ca-11eb-886f-4bce0e66e757.png)

**Comment by Plopsi** [comment]
@nothinglastsforever other way. The wallet can only sync as far as the full node is sync - up to the latest known block of the full node. It will follow as the node synces further or receives blocks.

**Comment by Plopsi** [comment]
If your node seems stuck, check if you still have peer-connections under the tab "full node"

**Comment by nothinglastsforever** [comment]
> The wallet can only sync as far as the full node is sync - up to the latest known block of the full node. It will follow as the node synces further or receives blocks.

So the wallet is currently syncing to the full node block height I'm stuck at and that being 274558/278218, therefore it will not begin moving again once the wallet is synced to said height? Well, that sucks. 😭 

> If your node seems stuck, check if you still have peer-connections under the tab "full node"

![image](https://user-images.githubusercontent.com/6544432/118239320-30346400-b4cc-11eb-9d5e-b71511a40520.png)

I have a bunch of peers as you can see.

I've also got port 8444 open on a static  IP and disabled UPnP in the config.yaml file.

I really don't want to redownload the full node again. I originally got started quickly with full sync thanks to someone on reddit hosting the blockchain_v1_mainnet.sqlite file for download 😞 . This was working fine until I changed the PC I farmed on.

**Comment by Plopsi** [comment]
The wallet will not sync above the current node height, but will. As you see in your node-list :D there are more peers with blockheights above you than below yours :D Be patient, from that 3 you will get your blocks, but depends how fast their upload is ^^

**Comment by nothinglastsforever** [comment]
```
2021-05-14T19:51:34.355 full_node chia.full_node.full_node: ERROR    Error with syncing: <class 'ValueError'>Traceback (most recent call last):
  File "chia\full_node\full_node.py", line 651, in _sync
ValueError: Weight proof validation failed

2021-05-14T19:51:34.066 full_node chia.full_node.weight_proof: ERROR    failed validating weight proof recent blocks

2021-05-14T20:10:00.732 full_node chia.full_node.full_node: ERROR    Error with syncing: <class 'RuntimeError'>Traceback (most recent call last):
  File "chia\full_node\full_node.py", line 628, in _sync
RuntimeError: Weight proof did not arrive in time from peer: 115.219.34.146

```

There's got to be something wrong

**Comment by Plopsi** [comment]
Hmm there was an invalid block send by the peer - your client should throw it away and try again.. Shouldn't be an ERROR in my opinion - just INFO. - If it not repeats endless I wouldn't care.

**Comment by muratsoydanduyar** [comment]
We solved this issue. First of all, find all chia files on C:users/user/.chia 
C:users/user/appdata
C:users/user/chianetwork
