### ISSUE TITLE
[BUG] Chia GUI white screen with folder choose window - not connecting after reload

### ISSUE THREAD

**Issue by irocket94** [Chia-Network/chia-blockchain#4849]
Hi, I've started plotting via GUI (planned plots until Monday) and when I checked about two hours later I had two windows opened - one with folder choosing, other, main, was blank. I've tried reloading GUI with Ctrl+R and Ctrl+Shift+R without success. First stops on "Connecting to wallet", second on "Logging in". There is a part of log with errors I get, they are both repeating. 

```
2021-05-13T22:03:18.730 daemon __main__                   : ERROR    Unexpected exception trying to send to websocket: code = 1006 (connection closed abnormally [internal]), no reason Traceback (most recent call last):
  File "websockets/protocol.py", line 838, in transfer_data
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "chia/daemon/server.py", line 351, in _state_changed
  File "websockets/protocol.py", line 567, in send
  File "websockets/protocol.py", line 1083, in write_frame
  File "websockets/protocol.py", line 803, in ensure_open
websockets.exceptions.ConnectionClosedError: code = 1006 (connection closed abnormally [internal]), no reason

2021-05-13T22:03:18.730 daemon asyncio                    : ERROR    Task exception was never retrieved
future: <Task finished name='Task-219305' coro=<WebSocketServer._state_changed() done, defined at chia/daemon/server.py:337> exception=ValueError('list.remove(x): x not in list')>
Traceback (most recent call last):
  File "websockets/protocol.py", line 838, in transfer_data
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "chia/daemon/server.py", line 351, in _state_changed
  File "websockets/protocol.py", line 567, in send
  File "websockets/protocol.py", line 1083, in write_frame
  File "websockets/protocol.py", line 803, in ensure_open
websockets.exceptions.ConnectionClosedError: code = 1006 (connection closed abnormally [internal]), no reason

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "chia/daemon/server.py", line 355, in _state_changed
ValueError: list.remove(x): x not in list
```

I know that the best thing for now should be restarting GUI, but I don't want to stop ploting (they are probably half way to go)

- OS: Ubuntu 20.04 Desktop
- CPU: Ryzen 9 5900X

**Comment by Froliskop** [comment]
me to same problem

**Comment by ivensaugusto** [comment]
same here, chia version 1.1.5
