### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by ThaiCat** [Chia-Network/chia-blockchain#4857]
**Describe the bug**
wallet doesn't start, hang in gui. If I attempt to start it from powershell i see the following

PS C:\Users\ThaiCat\AppData\Local\chia-blockchain\app-1.1.5\resources\app.asar.unpacked\daemon> ./chia.exe start farmer
Daemon not started yet
Starting daemon
chia_harvester: started
chia_farmer: started
chia_full_node: started
chia_wallet: started
PS C:\Users\ThaiCat\AppData\Local\chia-blockchain\app-1.1.5\resources\app.asar.unpacked\daemon> Traceback (most recent call last):
  File "chia\server\start_wallet.py", line 97, in <module>
  File "chia\server\start_wallet.py", line 92, in main
  File "chia\server\start_service.py", line 218, in run_service
  File "asyncio\runners.py", line 43, in run
  File "asyncio\base_events.py", line 587, in run_until_complete
  File "chia\server\start_service.py", line 212, in async_run_service
  File "chia\server\start_service.py", line 156, in run
  File "chia\server\start_service.py", line 127, in start
  File "chia\wallet\wallet_node.py", line 152, in _start
  File "chia\wallet\wallet_state_manager.py", line 143, in create
  File "chia\wallet\wallet_blockchain.py", line 106, in create
  File "chia\wallet\wallet_blockchain.py", line 117, in _load_chain_from_store
  File "chia\wallet\wallet_block_store.py", line 283, in get_peak_heights_dicts
KeyError: b'\xbd?Q\xa9^\x07/\x11XI\x92-\xa9\xcf\xc6I+I;/\xcb2JO\xa6\xbe\xbd9\t\xd7Q\xd2'
[13284] Failed to execute script start_wallet

I tried to reinstall the key from the gui and from cli, error remains

- OS: Windows 10 20H2
- CPU: i5 4690k

**Comment by sandoval** [comment]
I don't believe there is a risk of losing private keys in this procedure, but I recommend backing them up before by running `chia keys show --show-mnemonic-seed` and storing the output, since I don't really know where they are stored.

I managed to solve it by deleting all files in `~/.chia/mainnet/wallet/db/blockchain*`. It causes the wallet to resync, but solved my problem immediately.
