### ISSUE TITLE
[BUG] Cannot stop node

### ISSUE THREAD

**Issue by pluto2021** [Chia-Network/chia-blockchain#4935]
**Describe the bug**
After Windows forced updated that killed and messed up the blockchain GUI, and possible some other things. it has been syncing extremely slow somehow for a couple of days now. I am still able to plot. However, when I tried to stop all in command mode, while the GUI still plotting, it gives the following error,

C:\Users\USER\AppData\Local\chia-blockchain\app-1.1.5\resources\app.asar.unpacked\daemon>chia stop all
chia_harvester: Error, timeout.
Stop failed
chia_timelord_launcher: Error, timeout.
Traceback (most recent call last):
  File "chia\cmds\chia.py", line 81, in <module>
  File "chia\cmds\chia.py", line 77, in main
  File "click\core.py", line 829, in __call__
  File "click\core.py", line 782, in main
  File "click\core.py", line 1259, in invoke
  File "click\core.py", line 1066, in invoke
  File "click\core.py", line 610, in invoke
  File "click\decorators.py", line 21, in new_func
  File "chia\cmds\stop.py", line 46, in stop_cmd
  File "asyncio\base_events.py", line 587, in run_until_complete
  File "chia\cmds\stop.py", line 27, in async_stop
  File "chia\daemon\client.py", line 86, in is_running
TypeError: 'NoneType' object is not subscriptable
[3372] Failed to execute script chia

**To Reproduce**
[1] Force shutdown Windows while the GUI is syncing and plotting.
[2] Delete the .chia folder and start syncing from zero
[3] Start plotting while syncing
[4] run the "chia stop all" command

**Expected behavior**
The chia command should be able to handle this exception and give out proper steps to follow when this exception would happen. For example, a message like, "please wait for the plotting process to complete before stopping". If this error is due to whatever the windows update did to the system, not sure what would be the fix.

**Screenshots**

**Desktop (please complete the following information):**

- OS: Windows 10
- OS Version/Flavor: latest build and updates
- CPU: Intel

**Additional context**

**Comment by wjblanke** [comment]
Maybe the CPU is overloaded and then Chia is not able to respond to the close commands? Make sure plotting is not taking all of the CPU time.
