### ISSUE TITLE
Caught plotting error: Matches do not match with number of write entries

### ISSUE THREAD

**Issue by brezapour81** [Chia-Network/chia-blockchain#4964]
**Describe the bug**
whilst plotting away, i got the following error in the plotting logs for two of my plots at 17% in progress:

Caught plotting error: Matches do not match with number of write entries 4294491024 4294490818
[4136] Failed to execute script chia
Traceback (most recent call last):
  File "chia\cmds\chia.py", line 81, in <module>
  File "chia\cmds\chia.py", line 77, in main
  File "click\core.py", line 829, in __call__
  File "click\core.py", line 782, in main
  File "click\core.py", line 1259, in invoke
  File "click\core.py", line 1259, in invoke
  File "click\core.py", line 1066, in invoke
  File "click\core.py", line 610, in invoke
  File "click\decorators.py", line 21, in new_func
  File "chia\cmds\plots.py", line 135, in create_cmd
  File "chia\plotting\create_plots.py", line 176, in create_plots
RuntimeError: Unknown exception

Any ideas?

**Comment by prophetz2021** [comment]
i have a same problem. not get a solution yet. sa sad

**Comment by mezcalz9** [comment]
I got the same error

**Comment by iimoos9** [comment]
I am getting the same error for the last 4 days. I put an exclusion for the directory so it's not  my virus scanner. Did anyone find out how to fix ? 

Caught plotting error: Matches do not match with number of write entries 4182562002 4182561946
[23532] Failed to execute script chia
Traceback (most recent call last):
  File "chia\cmds\chia.py", line 81, in <module>
  File "chia\cmds\chia.py", line 77, in main
  File "click\core.py", line 829, in __call__
  File "click\core.py", line 782, in main
  File "click\core.py", line 1259, in invoke
  File "click\core.py", line 1259, in invoke
  File "click\core.py", line 1066, in invoke
  File "click\core.py", line 610, in invoke
  File "click\decorators.py", line 21, in new_func
  File "chia\cmds\plots.py", line 135, in create_cmd
  File "chia\plotting\create_plots.py", line 176, in create_plots
RuntimeError: Unknown exception

**Comment by Ismas** [comment]
Several cases opened with this problem. Admin, where are?

**Comment by iimoos9** [comment]
I've been trying 2-3 times a day for the last week it's still happening.
