### ISSUE TITLE
[BUG] Sync Failing v1.1.5

### ISSUE THREAD

**Issue by uxrobinson** [Chia-Network/chia-blockchain#5028]
**Describe the bug**
Sync not holding with version 1.1.5, dropping out approximately 50% of the time, with long periods of not synced, prior to syncing period, and short "synced" period.

**To Reproduce**

1. Launch Chia on Mac OS X
2. Wait for sync
3. Synced status 
4. Sync fails to display "not synced"

**Expected behavior**
Expectation is that sync mostly holds.

**Screenshots**

**Desktop (please complete the following information):**

- OS: OSX
- OS Version/Flavor: Big Sur
- CPU: M1

**Additional context**
Issue was occurring on Mac which was creating plots, so launched Chia on other Mac (intel), chia synced, then dropped sync. Behavior consistent whether plotting or not.

**Comment by uxrobinson** [comment]
2021-05-14T23:52:47.291 full_node chia.full_node.full_node: ERROR    Error with syncing: <class 'RuntimeError'>Traceback (most recent call last):
  File "chia/full_node/full_node.py", line 628, in _sync
RuntimeError: Weight proof did not arrive in time from peer: 151.252.65.57

2021-05-15T00:09:55.009 full_node chia.full_node.full_node: ERROR    Error with syncing: <class 'RuntimeError'>Traceback (most recent call last):
  File "chia/full_node/full_node.py", line 628, in _sync
RuntimeError: Weight proof did not arrive in time from peer: 124.219.236.12

2021-05-15T00:16:44.388 full_node full_node_server        : WARNING  Banning 178.38.238.207 for 600 seconds
2021-05-15T00:16:44.395 full_node chia.full_node.full_node: ERROR    Error with syncing: <class 'RuntimeError'>Traceback (most recent call last):
  File "chia/full_node/full_node.py", line 628, in _sync
RuntimeError: Weight proof did not arrive in time from peer: 178.38.238.207

2021-05-15T00:19:31.378 full_node chia.full_node.full_node: WARNING  Invalid response for slot None
2021-05-15T00:20:52.784 full_node chia.full_node.full_node: ERROR    Error with syncing: <class 'RuntimeError'>Traceback (most recent call last):
  File "chia/full_node/full_node.py", line 628, in _sync
RuntimeError: Weight proof did not arrive in time from peer: 139.192.21.124

**Comment by forrestcamps** [comment]
I'm facing "Not Synced" as well on my MBP 15' 2017 i7.  At "Full Node" tab, go to Connections -> Connect to others peers - > And put IP Adress: "introducer-or.chia.net" Port: "8444" Should work, worked for me.
