### ISSUE TITLE
BUG  File "chia\cmds\chia.py", line 81, in <module> 

### ISSUE THREAD

**Issue by fxjl123** [Chia-Network/chia-blockchain#5034]
Plot size is: 32
Buffer size is: 13560MiB
Using 128 buckets
Using 6 threads of stripe size 65536

Starting phase 1/4: Forward Propagation into tmp files... Sat May 15 01:09:27 2021
Computing table 1
F1 complete, time: 341.795 seconds. CPU (124.71%) Sat May 15 01:15:09 2021
Computing table 2
Caught plotting error: bad allocation
Traceback (most recent call last):
  File "chia\cmds\chia.py", line 81, in <module>
  File "chia\cmds\chia.py", line 77, in main
  File "click\core.py", line 829, in __call__
  File "click\core.py", line 782, in main
  File "click\core.py", line 1259, in invoke
  File "click\core.py", line 1259, in invoke
  File "click\core.py", line 1066, in invoke
  File "click\core.py", line 610, in invoke
  File "click\decorators.py", line 21, in new_func
  File "chia\cmds\plots.py", line 135, in create_cmd
  File "chia\plotting\create_plots.py", line 176, in create_plots
RuntimeError: bad allocation
[3080] Failed to execute script chia

s P chart reporting errors recently? What causes this? GUI and command are the same

**Comment by Jufik** [comment]
Duplicate of #1847
> https://github.com/Chia-Network/chia-blockchain/wiki/FAQ#my-plotting-attempt-ended-with-runtimeerror-bad-allocation
