### ISSUE TITLE
Cannot connect to daemon at ws://localhost:55400

### ISSUE THREAD

**Issue by Suprdude4** [Chia-Network/chia-blockchain#5049]
I've been unable to sync with the Chia network for the past 2 days without a hint as to why.

I'm using the Swar Chia Plot Manager for parallel plotting. 
My Chia Software has been updated to 1.1.5,
 
I checked task manager and it shows many instances of these programs running, not sure if this is normal for parallel plotting or not.

![Screenshot (2)](https://user-images.githubusercontent.com/84213558/118345314-f2d9d180-b4df-11eb-988a-387a1cd59b80.png)

Has anyone else had this issue?
 
I pulled this from the debug log: 

Traceback (most recent call last):
  File "chia\rpc\rpc_server.py", line 281, in connect_to_daemon
  File "chia\rpc\rpc_server.py", line 239, in connection
  File "aiohttp\client_ws.py", line 230, in receive
  File "aiohttp\streams.py", line 644, in read
  File "aiohttp\streams.py", line 604, in read
concurrent.futures._base.CancelledError
 <class 'concurrent.futures._base.CancelledError'>
2021-05-13T20:15:37.975 harvester chia.rpc.rpc_server     : WARNING  Cannot connect to daemon at ws://localhost:55400
2021-05-13T20:15:37.994 full_node chia.rpc.rpc_server     : WARNING  Cannot connect to daemon at ws://localhost:55400
2021-05-13T20:15:38.007 wallet chia.rpc.rpc_server        : WARNING  Cannot connect to daemon at ws://localhost:55400
2021-05-13T20:15:38.347 harvester chia.rpc.rpc_server     : WARNING  Cannot connect to daemon at ws://localhost:55400 

- OS: [Windows 10]

- CPU: [Ryzen 7 2700x]

-16 GB (2x8) DDR4 3200 mHz

-x2 1TB WD Blue m.2 nvme ssd raid 0 

-x1 500GB SATA ssd 

any help is greatly appreciated.

**Comment by eissko** [comment]
first what comes into my mind - check if services is running properly and even listening on localhost:55400. 
by command: 
`netstat -an | findstr -i 55400`
