### ISSUE TITLE
[BUG] Multiple copies of the plot / Status 3 error: Err.DOUBLE_SPEND

### ISSUE THREAD

**Issue by uxrobinson** [Chia-Network/chia-blockchain#5059]
**Describe the bug**
I'm running into sync issues with 1.1.5 (while creating plots, but with plenty of memory to spare), so running another instance (1.1.4) on another machine which is fully synced (with the same plots). But seeing this in the logs, despite 1.1.5 being in a state of pretty much constant "not synced". Any advice greatly appreciated, thanks.

**To Reproduce**

Running 1.1.5 on an M1 mac, seems to drop sync often.

**Expected behavior**
Maintains sync.

**Log examples 1.1.4**

2021-05-15T03:42:44.604 full_node chia.full_node.full_node: WARNING Wasn't able to add transaction with id [ID], status 3 error: Err.DOUBLE_SPEND
2021-05-15T03:44:29.781 harvester chia.plotting.plot_tools: WARNING Have multiple copies of the plot [Plot], not adding it.

**Log examples 1.1.5**

Here's some of the errors I am seeing on the 1.1.5 machine, which is plotting:

2021-05-14T20:32:36.581 full_node chia.full_node.full_node: WARNING Wasn't able to add transaction with id [ID], status 3 error: Err.DOUBLE_SPEND
2021-05-14T20:33:19.106 full_node chia.full_node.full_node: ERROR Consensus error 124, not disconnecting
2021-05-14T20:33:29.657 full_node chia.full_node.full_node: WARNING Wasn't able to add transaction with id [ID], status 3 error: Err.COIN_AMOUNT_NEGATIVE
2021-05-14T20:34:00.087 harvester chia.plotting.plot_tools: WARNING Have multiple copies of the plot [Plot], not adding it.
2021-05-14T20:34:00.179 harvester chia.plotting.plot_tools: WARNING Have multiple copies of the plot [Plot], not adding it.

...
2021-05-14T21:35:20.560 full_node chia.full_node.full_node: WARNING Invalid response for slot None
2021-05-14T21:39:03.642 full_node full_node_server : ERROR Exception: <class 'asyncio.exceptions.TimeoutError'>, closing connection {'host': '[An external IP]', 'port': 8444}. Traceback (most recent call last):
File "chia/server/server.py", line 531, in api_call
File "asyncio/tasks.py", line 496, in wait_for
asyncio.exceptions.TimeoutError

2021-05-14T21:39:07.247 full_node full_node_server : WARNING Banning [Same external IP] for 10 seconds
2021-05-14T21:41:38.895 full_node full_node_server : WARNING Cannot write to closing transport 45.135.4.116
2021-05-14T22:08:34.580 full_node full_node_server : ERROR Exception: Failed to fetch block 281361 from None, timed out, None. Traceback (most recent call last):
File "chia/server/server.py", line 521, in wrapped_coroutine
File "chia/full_node/full_node_api.py", line 104, in new_peak
File "chia/full_node/full_node.py", line 360, in new_peak
File "chia/full_node/full_node.py", line 310, in short_sync_backtrack
File "chia/full_node/full_node.py", line 295, in short_sync_backtrack
ValueError: Failed to fetch block 281361 from None, timed out

2021-05-14T22:08:34.659 full_node full_node_server : ERROR Exception: Failed to fetch block 281361 from None, timed out <class 'ValueError'>, closing connection None. Traceback (most recent call last):
File "chia/server/server.py", line 531, in api_call
File "asyncio/tasks.py", line 442, in wait_for
File "chia/server/server.py", line 528, in wrapped_coroutine
File "chia/server/server.py", line 521, in wrapped_coroutine
File "chia/full_node/full_node_api.py", line 104, in new_peak
File "chia/full_node/full_node.py", line 360, in new_peak
File "chia/full_node/full_node.py", line 310, in short_sync_backtrack
File "chia/full_node/full_node.py", line 295, in short_sync_backtrack
ValueError: Failed to fetch block 281361 from None, timed out
...
2021-05-14T21:35:20.560 full_node chia.full_node.full_node: WARNING Invalid response for slot None
2021-05-14T21:39:03.642 full_node full_node_server : ERROR Exception: <class 'asyncio.exceptions.TimeoutError'>, closing connection {'host': '[Same IP]', 'port': 8444}. Traceback (most recent call last):
File "chia/server/server.py", line 531, in api_call
File "asyncio/tasks.py", line 496, in wait_for
asyncio.exceptions.TimeoutError
...
2021-05-14T21:39:07.247 full_node full_node_server : WARNING Banning [Same IP] for 10 seconds
2021-05-14T21:41:38.895 full_node full_node_server : WARNING Cannot write to closing transport 45.135.4.116
2021-05-14T22:08:34.580 full_node full_node_server : ERROR Exception: Failed to fetch block 281361 from None, timed out, None. Traceback (most recent call last):
File "chia/server/server.py", line 521, in wrapped_coroutine
File "chia/full_node/full_node_api.py", line 104, in new_peak
File "chia/full_node/full_node.py", line 360, in new_peak
File "chia/full_node/full_node.py", line 310, in short_sync_backtrack
File "chia/full_node/full_node.py", line 295, in short_sync_backtrack
ValueError: Failed to fetch block 281361 from None, timed out
...
2021-05-14T22:08:34.659 full_node full_node_server : ERROR Exception: Failed to fetch block 281361 from None, timed out <class 'ValueError'>, closing connection None. Traceback (most recent call last):
File "chia/server/server.py", line 531, in api_call
File "asyncio/tasks.py", line 442, in wait_for
File "chia/server/server.py", line 528, in wrapped_coroutine
File "chia/server/server.py", line 521, in wrapped_coroutine
File "chia/full_node/full_node_api.py", line 104, in new_peak
File "chia/full_node/full_node.py", line 360, in new_peak
File "chia/full_node/full_node.py", line 310, in short_sync_backtrack
File "chia/full_node/full_node.py", line 295, in short_sync_backtrack
ValueError: Failed to fetch block 281361 from None, timed out
...
2021-05-14T22:08:36.723 full_node full_node_server : ERROR Exception: Error short batch syncing, could not fetch block at height 281343 <class 'ValueError'>, closing connection None. Traceback (most recent call last):
File "chia/server/server.py", line 531, in api_call
File "asyncio/tasks.py", line 442, in wait_for
File "chia/server/server.py", line 528, in wrapped_coroutine
File "chia/server/server.py", line 521, in wrapped_coroutine
File "chia/full_node/full_node_api.py", line 104, in new_peak
File "chia/full_node/full_node.py", line 374, in new_peak
File "chia/full_node/full_node.py", line 225, in short_sync_batch
ValueError: Error short batch syncing, could not fetch block at height 281343

2021-05-14T22:08:36.730 full_node full_node_server : ERROR Exception: Error short batch syncing, could not fetch block at height 281343, None. Traceback (most recent call last):
File "chia/server/server.py", line 521, in wrapped_coroutine
File "chia/full_node/full_node_api.py", line 104, in new_peak
File "chia/full_node/full_node.py", line 374, in new_peak
File "chia/full_node/full_node.py", line 225, in short_sync_batch
ValueError: Error short batch syncing, could not fetch block at height 281343

2021-05-14T22:08:36.733 full_node full_node_server : ERROR Exception: Error short batch syncing, could not fetch block at height 281343 <class 'ValueError'>, closing connection None. Traceback (most recent call last):
File "chia/server/server.py", line 531, in api_call
File "asyncio/tasks.py", line 442, in wait_for
File "chia/server/server.py", line 528, in wrapped_coroutine
File "chia/server/server.py", line 521, in wrapped_coroutine
File "chia/full_node/full_node_api.py", line 104, in new_peak
File "chia/full_node/full_node.py", line 374, in new_peak
File "chia/full_node/full_node.py", line 225, in short_sync_batch
ValueError: Error short batch syncing, could not fetch block at height 281343
...
2021-05-15T00:08:25.065 full_node chia.full_node.full_node: ERROR Error with syncing: <class 'RuntimeError'>Traceback (most recent call last):
File "chia/full_node/full_node.py", line 628, in _sync
RuntimeError: Weight proof did not arrive in time from peer: [Other peer IP]
2021-05-15T00:09:40.636 full_node chia.full_node.full_node: WARNING Invalid response for slot None
2021-05-15T00:09:44.796 harvester chia.plotting.plot_tools: WARNING Have multiple copies of the plot /[plot], not adding it.
2021-05-15T00:20:12.248 full_node full_node_server : ERROR Exception: <class 'asyncio.exceptions.TimeoutError'>, closing connection {'host': '[another external IP]', 'port': 8444}. Traceback (most recent call last):
File "chia/server/server.py", line 531, in api_call
File "asyncio/tasks.py", line 496, in wait_for
asyncio.exceptions.TimeoutError
2021-05-15T00:20:12.616 full_node full_node_server : WARNING Banning [another external IP] for 10 seconds

**Desktop (please complete the following information):**

- OS: 11.3
- OS Version/Flavor: OSX
- CPU: M1

**Additional context**
Trying to bypass the sync issue by running 1.1.4 on a different machine.

**Comment by uxrobinson** [comment]
Sorry if this is doubling up on Double_Spend bug reports. I did search before posting, and see there is plenty of 1.1.4 Double_Spend issues reported / discussed, but I am thinking my work around to the not syncing issues is causing the problem here (multiple copies of plot). Any advice on setting role of instance much appreciated - farmer, plotter for example.
