### ISSUE TITLE
[BUG] Chia full_node, wallet and harvester goes down after few minutes

### ISSUE THREAD

**Issue by JordyBaylac** [Chia-Network/chia-blockchain#5063]
**Describe the bug**
I am seeing the chia full_node, farmer and harvester go down from time to time. After I checked I only see the chia_daemon active, see logs below.

- OS: Linux
- Chia version: 1.1.6 with CLI

```sh
Traceback (most recent call last):
  File "/home/user/chia-blockchain/chia/daemon/server.py", line 627, in start_service
    process, pid_path = launch_service(self.root_path, exe_command)
  File "/home/user/chia-blockchain/chia/daemon/server.py", line 784, in launch_service
    process = subprocess.Popen(
  File "/usr/lib/python3.8/subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.8/subprocess.py", line 1702, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'chia_harvester'
2021-05-15T00:30:06.052 daemon chia.daemon.server         : ERROR    problem starting chia_farmer
Traceback (most recent call last):
  File "/home/user/chia-blockchain/chia/daemon/server.py", line 627, in start_service
    process, pid_path = launch_service(self.root_path, exe_command)
  File "/home/user/chia-blockchain/chia/daemon/server.py", line 784, in launch_service
    process = subprocess.Popen(
  File "/usr/lib/python3.8/subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.8/subprocess.py", line 1702, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'chia_farmer'
2021-05-15T00:30:06.056 daemon chia.daemon.server         : ERROR    problem starting chia_full_node
Traceback (most recent call last):
  File "/home/user/chia-blockchain/chia/daemon/server.py", line 627, in start_service
    process, pid_path = launch_service(self.root_path, exe_command)
  File "/home/user/chia-blockchain/chia/daemon/server.py", line 784, in launch_service
    process = subprocess.Popen(
  File "/usr/lib/python3.8/subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.8/subprocess.py", line 1702, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'chia_full_node'
2021-05-15T00:30:06.060 daemon chia.daemon.server         : ERROR    problem starting chia_wallet
Traceback (most recent call last):
  File "/home/user/chia-blockchain/chia/daemon/server.py", line 627, in start_service
    process, pid_path = launch_service(self.root_path, exe_command)
  File "/home/user/chia-blockchain/chia/daemon/server.py", line 784, in launch_service
    process = subprocess.Popen(
  File "/usr/lib/python3.8/subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.8/subprocess.py", line 1702, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'chia_wallet'
```

When I restart with **chia stop -d all**, and **chia start farmer**, it works but after few minutes it crashes again

**Comment by JordyBaylac** [comment]
I noted that this happened after I call **chia farm summary** not from chia virtual environment

**Comment by tinodj** [comment]
What happened whit this bug? Is there a way to use chia commands outside from the chia virtual environment ?
