### ISSUE TITLE
Plotting Error,RuntimeError: std::exception

### ISSUE THREAD

**Issue by mrbaiwei** [Chia-Network/chia-blockchain#5086]
Traceback (most recent call last):
  File "/usr/local/bin/chia", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/chia/cmds/chia.py", line 77, in main
    cli()  # pylint: disable=no-value-for-parameter
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/chia/cmds/plots.py", line 135, in create_cmd
    create_plots(Params(), ctx.obj["root_path"])
  File "/usr/local/lib/python3.7/site-packages/chia/plotting/create_plots.py", line 176, in create_plots
    args.nobitfield,
RuntimeError: std::exception

There are several poltting failures every day,how to fix it

**Comment by ajantoniou** [comment]
same issue

**Comment by lzzkey** [comment]
same issue
