### ISSUE TITLE
Sync issue - slow, never completes

### ISSUE THREAD

**Issue by leefarg** [Chia-Network/chia-blockchain#5088]
I am currently using 1.1.3 and have been using it for over a week.
It had been working just fine after initial synchronization, and I have been creating plots.
A couple days ago, though, I lost sync. Plotting is still proceeding normally. I had an issue where I lost sync once before, but that was fixed by shutting down and force reloading.

I'm currently on 282066/282406. The sync moves along very slowly (it is not stuck) but never gets to full synchronization. I am connected to many peers. Plotting is still moving along as normal.

Absolutely nothing else has changed on my system since I started farming/plotting. I have tried shutting down the program, tried turning off my computer and restarting, and still get this same issue.

Any other suggestions?  Thanks all for your help!

**Comment by fabioyy** [comment]
same here, ( and a lot of people with the same problem on other topics )can you please  check if there is a Single process using 100% of a Single cpu core?

**Comment by AlexAlexAlex26** [comment]
Same Issue with 1.1.5 since yesterday. The sync starts but dont move and "disconntect".

**Comment by mdp19900707** [comment]
@AlexAlexAlex26  me to! Since yesterday. 
My Peak Time   is  05 /15/2021 a.m. 12:32:04.Block explorer is ok.
![image](https://user-images.githubusercontent.com/16143961/118358489-921ac980-b5b1-11eb-8f9a-e95f520c7990.png)

**Comment by FSys77** [comment]
Same here. imho Chia software is a piece of shit, hacky and flaky as hell.

**Comment by AlexAlexAlex26** [comment]
They are about the same Estimated network space and Peak Heigh. 
This buggy cost money ...
![2](https://user-images.githubusercontent.com/84229372/118359415-929c6b80-b583-11eb-91bb-93cc50123a17.PNG)

**Comment by leefarg** [comment]
I am plotting and average CPU is about 30-44% (which is a bit high for plotting for me). But none of the cores running at 100%.

**Comment by COX888** [comment]
Same situation from yesterday, no sync

**Comment by AkiraDX** [comment]
I'm also having the issue whereby my node keep on dropping out of sync.

Here is the error.

2021-05-15T21:44:38.859 full_node full_node_server        : ERROR    Exception: Failed to fetch block 284668 from None, timed out <class 'ValueError'>, closing connection None. Traceback (most recent call last):
  File "chia\server\server.py", line 531, in api_call
  File "asyncio\tasks.py", line 414, in wait_for
  File "chia\server\server.py", line 528, in wrapped_coroutine
  File "chia\server\server.py", line 521, in wrapped_coroutine
  File "chia\full_node\full_node_api.py", line 104, in new_peak
  File "chia\full_node\full_node.py", line 361, in new_peak
  File "chia\full_node\full_node.py", line 310, in short_sync_backtrack
  File "chia\full_node\full_node.py", line 295, in short_sync_backtrack
ValueError: Failed to fetch block 284668 from None, timed out

2021-05-15T21:44:38.862 full_node full_node_server        : ERROR    Exception: Failed to fetch block 284668 from None, timed out, None. Traceback (most recent call last):
  File "chia\server\server.py", line 521, in wrapped_coroutine
  File "chia\full_node\full_node_api.py", line 104, in new_peak
  File "chia\full_node\full_node.py", line 361, in new_peak
  File "chia\full_node\full_node.py", line 310, in short_sync_backtrack
  File "chia\full_node\full_node.py", line 295, in short_sync_backtrack
ValueError: Failed to fetch block 284668 from None, timed out

2021-05-15T21:44:38.863 full_node full_node_server        : ERROR    Exception: Failed to fetch block 284668 from None, timed out <class 'ValueError'>, closing connection None. Traceback (most recent call last):
  File "chia\server\server.py", line 531, in api_call
  File "asyncio\tasks.py", line 414, in wait_for
  File "chia\server\server.py", line 528, in wrapped_coroutine
  File "chia\server\server.py", line 521, in wrapped_coroutine
  File "chia\full_node\full_node_api.py", line 104, in new_peak
  File "chia\full_node\full_node.py", line 361, in new_peak
  File "chia\full_node\full_node.py", line 310, in short_sync_backtrack
  File "chia\full_node\full_node.py", line 295, in short_sync_backtrack
ValueError: Failed to fetch block 284668 from None, timed out

2021-05-15T21:45:26.782 full_node chia.full_node.full_node: WARNING  Invalid response for slot None
2021-05-15T21:45:26.957 full_node chia.full_node.full_node: WARNING  Invalid response for slot None
2021-05-15T21:45:27.022 full_node chia.full_node.full_node: WARNING  Invalid response for slot None
2021-05-15T21:45:27.040 full_node chia.full_node.full_node: WARNING  Invalid response for slot None
2021-05-15T21:45:27.140 full_node chia.full_node.full_node: WARNING  Invalid response for slot None
2021-05-15T21:45:27.220 full_node chia.full_node.full_node: WARNING  Invalid response for slot None
2021-05-15T21:45:27.286 full_node chia.full_node.full_node: WARNING  Invalid response for slot None
2021-05-15T21:45:27.408 full_node chia.full_node.full_node: WARNING  Invalid response for slot None
2021-05-15T21:45:27.551 full_node chia.full_node.full_node: WARNING  Invalid response for slot None
2021-05-15T21:45:27.579 full_node chia.full_node.full_node: WARNING  Invalid response for slot None
2021-05-15T21:45:27.629 full_node chia.full_node.full_node: WARNING  Invalid response for slot None
2021-05-15T21:45:27.719 full_node chia.full_node.full_node: WARNING  Invalid response for slot None
2021-05-15T21:45:27.807 full_node chia.full_node.full_node: WARNING  Invalid response for slot None
2021-05-15T21:45:27.988 full_node chia.full_node.full_node: WARNING  Invalid response for slot None
2021-05-15T21:45:28.197 full_node chia.full_node.full_node: WARNING  Invalid response for slot None
2021-05-15T21:45:29.394 full_node chia.full_node.full_node: WARNING  Invalid response for slot None
2021-05-15T21:45:37.557 full_node chia.full_node.full_node: WARNING  Invalid response for slot None
2021-05-15T21:47:00.299 full_node chia.full_node.full_node: WARNING  Invalid response for slot None
2021-05-15T21:47:32.636 full_node chia.full_node.full_node: WARNING  Invalid response for slot None

**Comment by HudsonProdigy** [comment]
I am having this same issue, ports are open and properly forwarded but syncing not keeping up

**Comment by statop** [comment]
Same, haven’t synced in days

**Comment by nothinglastsforever** [comment]
Delete your db folder in .chia\mainnet\ and re-sync. Nothing else will fix it. It should only take 24 hours to re-download as that's how long it took me.

**Comment by gldstrrbt** [comment]
> Delete your db folder in .chia\mainnet\ and re-sync. Nothing else will fix it. It should only take 24 hours to re-download as that's how long it took me.

Having the same issue, just tried this, and for the last 15 min "Blocks" is stuck on the loading animation and the status remains as "Not Synced".

**Comment by statop** [comment]
> Delete your db folder in .chia\mainnet\ and re-sync. Nothing else will fix it. It should only take 24 hours to re-download as that's how long it took me.

Bad advice, I did that a few days ago and am stuck around 500 behind, seemingly forever.
