### ISSUE TITLE
Unexpected exception trying to send to websocket

### ISSUE THREAD

**Issue by stavrt** [Chia-Network/chia-blockchain#5100]
In the debug.log file I keep getting these errors:

2021-05-15T09:45:15.819 daemon __main__                   : ERROR    Unexpected exception trying to send to websocket: code = 1005 (no status code [internal]), no reason Traceback (most recent call last):
  File "chia\daemon\server.py", line 187, in safe_handle
  File "websockets\protocol.py", line 555, in send
  File "websockets\protocol.py", line 803, in ensure_open
websockets.exceptions.ConnectionClosedError: code = 1005 (no status code [internal]), no reason

I also noticed that my average response time to the harvesters is very high now. Currently I have a Windows PC as a full node and 3 harvesters connected using the CA cert method described in the docs page.

**Comment by AkiraDX** [comment]
I'm also having exactly the same issue.

My node keep dropping out of sync.
