### ISSUE TITLE
[BUG] Wallet stuck even after deleting the contents of db folder

### ISSUE THREAD

**Issue by homerts95** [Chia-Network/chia-blockchain#5154]
**Describe the bug**
On my main windows PC used `chia show wallet` received not synced- stuck at height 13592, gui wallet status shows syncing and stuck height 13592
on my harvester (windows) used  `chia show wallet` received not synced- stuck at height 270k, gui wallet status shows synching and stuck at 270k

- OS: Windows

- CPU: ryzen 5 5800x

from debug.log
`2021-05-16T00:27:50.045 wallet chia.wallet.wallet_node    : ERROR    Error while trying to fetch from peer: Traceback (most recent call last):
  File "chia\wallet\wallet_node.py", line 597, in _sync
  File "chia\wallet\wallet_node.py", line 665, in fetch_blocks_and_validate
  File "chia\wallet\wallet_state_manager.py", line 824, in get_filter_additions_removals
  File "chia\wallet\wallet_block_store.py", line 127, in get_header_block_record
  File "aiosqlite\cursor.py", line 69, in close
  File "aiosqlite\cursor.py", line 31, in _execute
  File "aiosqlite\core.py", line 129, in _execute
concurrent.futures._base.CancelledError

2021-05-16T00:27:50.050 wallet chia.wallet.wallet_node    : ERROR    Loop exception in sync Was not able to add blocks 14787-14819. Traceback (most recent call last):
  File "chia\wallet\wallet_node.py", line 509, in sync_job
  File "chia\wallet\wallet_node.py", line 606, in _sync
RuntimeError: Was not able to add blocks 14787-14819

2021-05-16T00:27:55.138 full_node chia.full_node.full_node: ERROR    Exception in create outbound connections: 
2021-05-16T00:27:55.139 full_node chia.full_node.full_node: ERROR    Traceback: Traceback (most recent call last):
  File "chia\server\node_discovery.py", line 325, in _connect_to_peers
  File "asyncio\tasks.py", line 595, in sleep
concurrent.futures._base.CancelledError

2021-05-16T00:30:35.727 wallet wallet_server              : ERROR    Exception , exception Stack: Traceback (most recent call last):
  File "chia\server\server.py", line 356, in start_client
  File "aiohttp\client.py", line 763, in _ws_connect
  File "aiohttp\client.py", line 521, in _request
  File "aiohttp\connector.py", line 535, in connect
  File "aiohttp\connector.py", line 892, in _create_connection
  File "aiohttp\connector.py", line 1032, in _create_direct_connection
  File "aiohttp\connector.py", line 969, in _wrap_create_connection
  File "asyncio\base_events.py", line 949, in create_connection
  File "asyncio\selector_events.py", line 473, in sock_connect
concurrent.futures._base.CancelledError`

**Comment by carlospaulino** [comment]
I am experiencing the exact same issue. 

My wallet is not syncing and stuck at height 285,356. 

The node is synced and the computer is farming, so the only issue is the wallet.

I am running Windows and Chia 1.1.5

**Comment by bhushanjss** [comment]
I had to delete my db as sqlite got corrupted due to unexpected computer crash, now I have to restart the whole sync from 0, I already reached 150,000+. Is there any way to backup the db so I can restore the crashed db?

**Comment by mariano54** [comment]
Can you update to the latest, and post any issues you see on https://github.com/Chia-Network/chia-blockchain/issues/6993?
Thank you

**Comment by dmitryalexandrow** [comment]
добрый день! у меня так же проблема с синхронизацией кошелька завис на высоте 408 удаление папки db  и перезагрузка ничего не дали. Как быть?
