### ISSUE TITLE
There is a problem when i'm trying to polt a new file

### ISSUE THREAD

**Issue by Alex20041130** [Chia-Network/chia-blockchain#5197]
>>Plot size is: 32
Buffer size is: 65536MiB
Using 128 buckets
Using 36 threads of stripe size 65536
Starting phase 1/4: Forward Propagation into tmp files... Sun May 16 19:04:53 2021
Computing table 1
F1 complete, time: 311.893 seconds. CPU (130.7%) Sun May 16 19:10:05 2021
Computing table 2
Caught plotting error: bad allocation
[23260] Failed to execute script chia
Traceback (most recent call last):
  File "chia\cmds\chia.py", line 81, in <module>
  File "chia\cmds\chia.py", line 77, in main
  File "click\core.py", line 829, in __call__
  File "click\core.py", line 782, in main
  File "click\core.py", line 1259, in invoke
  File "click\core.py", line 1259, in invoke
  File "click\core.py", line 1066, in invoke
  File "click\core.py", line 610, in invoke
  File "click\decorators.py", line 21, in new_func
  File "chia\cmds\plots.py", line 135, in create_cmd
  File "chia\plotting\create_plots.py", line 176, in create_plots
RuntimeError: bad allocation

**Comment by ramkom9** [comment]
hope you not using whole CPU. leave at least 4 cores for your hardware and system
