### ISSUE TITLE
[BUG] Sync Lost without  reason during plotting or during transferring  plot from temp to final directory

### ISSUE THREAD

**Issue by casa10** [Chia-Network/chia-blockchain#5201]
**Describe the bug**
During this day, synchronization with full node stops without reason (often : every 10-15 minutes).
I noted that appears only from today morining.
Before in full node i had a lot of connections to the node id with diffrent IP adresses and the connection is Full Node.
Now only one or two @IP and sometimes nothing. When nothing no synced to the full node. That is to say no farming, no test o filter of the plots.

I tried to put the following adress to resync :
- node.chia.net
- node-eu.chia.net
- node-or.chia.net
- introducer.chia.net
- introducer-eu.chia.net
The port 8444.
I cheked my port 8444 : it is opened. 

Doing this thing, i dont have results right now because no more node id appeared. Only my wallet and Farm adress (127.0.0.1).
Need to wait and try several time to have again synced full node and syced wallets and to have plots who pass the filter.

I tried to shut down chia and restart or restart all computer. Conclusion : same problem

I looked inside debug.log file :
_2021-05-16T12:28:12.856 full_node full_node_server        : ERROR    Exception: Failed to fetch block 289278 from None, timed out <class 'ValueError'>, closing connection None. Traceback (most recent call last):
  File "chia\server\server.py", line 531, in api_call
  File "asyncio\tasks.py", line 414, in wait_for
  File "chia\server\server.py", line 528, in wrapped_coroutine
  File "chia\server\server.py", line 521, in wrapped_coroutine
  File "chia\full_node\full_node_api.py", line 104, in new_peak
  File "chia\full_node\full_node.py", line 361, in new_peak
  File "chia\full_node\full_node.py", line 310, in short_sync_backtrack
  File "chia\full_node\full_node.py", line 295, in short_sync_backtrack
ValueError: Failed to fetch block 289278 from None, timed out

2021-05-16T12:51:20.244 full_node full_node_server        : ERROR    Exception , exception Stack: Traceback (most recent call last):
  File "chia\server\server.py", line 356, in start_client
  File "aiohttp\client.py", line 763, in _ws_connect
  File "aiohttp\client.py", line 521, in _request
  File "aiohttp\connector.py", line 535, in connect
  File "aiohttp\connector.py", line 892, in _create_connection
  File "aiohttp\connector.py", line 1032, in _create_direct_connection
  File "aiohttp\connector.py", line 969, in _wrap_create_connection
  File "asyncio\base_events.py", line 949, in create_connection
  File "asyncio\selector_events.py", line 473, in sock_connect
concurrent.futures._base.CancelledError

2021-05-16T12:51:29.289 daemon asyncio                    : ERROR    Task exception was never retrieved
future: <Task finished coro=<kill_service() done, defined at chia\daemon\server.py:833> exception=AttributeError("'list' object has no attribute 'pid'")>
Traceback (most recent call last):
  File "chia\daemon\server.py", line 841, in kill_service
  File "chia\daemon\server.py", line 805, in kill_process
AttributeError: 'list' object has no attribute 'pid'
2021-05-16T13:25:57.541 full_node chia.full_node.full_node: WARNING  Wasn't able to add transaction with id 5e0fd02fa737a16dd9252f00973c1de56ebd70a947592925f1389673e4a78c2a, status 3 error: Err.COIN_AMOUNT_NEGATIVE
2021-05-16T13:35:04.119 full_node chia.full_node.full_node: WARNING  Wasn't able to add transaction with id 5e0fd02fa737a16dd9252f00973c1de56ebd70a947592925f1389673e4a78c2a, status 3 error: Err.COIN_AMOUNT_NEGATIVE
2021-05-16T13:35:04.175 full_node chia.full_node.full_node: WARNING  Wasn't able to add transaction with id b319cccd6727325e1427b8ab57b01dbbcfd21cf927af2134013cc333b0c98153, status 3 error: Err.UNKNOWN_UNSPENT
2021-05-16T13:35:19.041 full_node chia.full_node.full_node: WARNING  Wasn't able to add transaction with id 52bbe75f786715bed8afee730ba846578d7af732e7ae3fb27a333213bc67eec1, status 3 error: Err.UNKNOWN_UNSPENT
2021-05-16T13:42:04.977 full_node chia.full_node.full_node: ERROR    Consensus error 124, not disconnecting_

or 
2021-05-16T14:08:57.382 full_node full_node_server        : INFO     Connection closed: 67.169.107.168, node id: a907d94b802a2305c3ad2f6a35599ec282d04811763849d9bd97f792e82232e1
2021-05-16T14:08:57.383 full_node chia.full_node.full_node: INFO     peer disconnected {'host': '67.169.107.168', 'port': 8444}
2021-05-16T14:09:20.427 full_node full_node_server        : INFO     Cannot connect to host 185.253.101.159:8444 ssl:<ssl.SSLContext object at 0x00000249E6BE22E8> [Connect call failed ('185.253.101.159', 8444)]
2021-05-16T14:09:43.496 full_node full_node_server        : INFO     Cannot connect to host 74.71.163.98:8444 ssl:<ssl.SSLContext object at 0x00000249EFE6C438> [Connect call failed ('74.71.163.98', 8444)]
2021-05-16T14:10:06.567 full_node full_node_server        : INFO     Cannot connect to host 223.112.24.131:8444 ssl:<ssl.SSLContext object at 0x00000249F462B208> [Connect call failed ('223.112.24.131', 8444)]
2021-05-16T14:10:16.452 full_node full_node_server        : INFO     -> handshake to peer 159.69.68.162 5c101f0810c26dda6d20bcfb2d8a1c8282c91c925bdc5cfde6c9291477d0fcc9
2021-05-16T14:10:16.571 full_node full_node_server        : INFO     Connected with full_node {'host': '159.69.68.162', 'port': 8444}
2021-05-16T14:10:16.572 full_node full_node_server        : INFO     -> request_mempool_transactions to peer 159.69.68.162 5c101f0810c26dda6d20bcfb2d8a1c8282c91c925bdc5cfde6c9291477d0fcc9
2021-05-16T14:10:16.573 full_node full_node_server        : INFO     -> new_peak to peer 159.69.68.162 5c101f0810c26dda6d20bcfb2d8a1c8282c91c925bdc5cfde6c9291477d0fcc9
2021-05-16T14:10:16.575 full_node full_node_server        : INFO     -> request_peers to peer 159.69.68.162 5c101f0810c26dda6d20bcfb2d8a1c8282c91c925bdc5cfde6c9291477d0fcc9
2021-05-16T14:10:16.576 full_node full_node_server        : INFO     Connection closed: 159.69.68.162, node id: 5c101f0810c26dda6d20bcfb2d8a1c8282c91c925bdc5cfde6c9291477d0fcc9
2021-05-16T14:10:16.577 full_node chia.full_node.full_node: INFO     peer disconnected {'host': '159.69.68.162', 'port': 8444}
2021-05-16T14:10:18.849 full_node full_node_server        : INFO     -> handshake to peer 195.192.233.214 664282354543774e43a55f1508275313ce07839b87b9b3192a58d2776c5139ef
2021-05-16T14:10:18.923 full_node full_node_server        : INFO     Connected with full_node {'host': '195.192.233.214', 'port': 8444}
2021-05-16T14:10:18.924 full_node full_node_server        : INFO     -> request_mempool_transactions to peer 195.192.233.214 664282354543774e43a55f1508275313ce07839b87b9b3192a58d2776c5139ef
2021-05-16T14:10:18.925 full_node full_node_server        : INFO     -> new_peak to peer 195.192.233.214 664282354543774e43a55f1508275313ce07839b87b9b3192a58d2776c5139ef
2021-05-16T14:10:18.927 full_node full_node_server        : INFO     Connection closed: 195.192.233.214, node id: 664282354543774e43a55f1508275313ce07839b87b9b3192a58d2776c5139ef

**To Reproduce**
Appear without reason or when a plot is finished and transfer begin between temporary folder from SSD to final folder on hard disk.

**Expected behavior**
No lost of synced without reason.
Develop module who try directly to reconnect to the nodes ID + error message in the GUI who alert user of this thing.
To have list of connexion peers who is able to connect quickly + on dashboard alerts for that too.

**Desktop (please complete the following information):**

- OS: Windows 10 last version
- CHIA version : 1.1.5
- NAS to stock plots

**Comment by BluefireXD** [comment]
`_2021-05-16T12:28:12.856 full_node full_node_server : ERROR Exception: Failed to fetch block 289278 from None, timed out <class 'ValueError'>, closing connection None. Traceback (most recent call last):...`

Looks similar to my case.. just to connect them ^^
https://github.com/Chia-Network/chia-blockchain/issues/5175

**Comment by casa10** [comment]
Thank you.
I tried to look ip address and put too.
Sometimes that work but often no. Problem with the GUI nothing who show type of error. 
We need to pass time to check if synced working good :( .
We work everyday so minimum to have good and mature system is better. 

> 
> 
> `_2021-05-16T12:28:12.856 full_node full_node_server : ERROR Exception: Failed to fetch block 289278 from None, timed out <class 'ValueError'>, closing connection None. Traceback (most recent call last):...`
> 
> Looks similar to my case.. just to connect them ^^
> Link to my issue: #5175

**Comment by Marigold5** [comment]
I checked I have 60 plus connections

**Comment by Marigold5** [comment]
sync is now ok but i will keep checking

**Comment by casa10** [comment]
> 
> 
> sync is now ok but i will keep checking

ok. but do you have answers to solve the problem ?

**Comment by secco04** [comment]
ive got sync problems too ... i ve managed to sync again if i restart the wallet / fullnode  `chia.exe start wallet -r ` and then add some of the above mentioned peers manually 

as error i get this in my log while its not syncing... 
`
2021-05-16T15:05:24.516 harvester chia.harvester.harvester: INFO     1 plots were eligible for farming d5d0218fa2... Found 0 proofs. Time: 1.07301 s. Total 253 plots <--- here is in sync 
from here to end it seems unsynced and there are multiple banned ips ...  
2021-05-16T15:15:23.085 full_node full_node_server        : ERROR    Exception:  <class 'concurrent.futures._base.TimeoutError'>, closing connection {'host': '173.218.xxx.xxx', 'port':
8444}. Traceback (most recent call last):
concurrent.futures._base.TimeoutError
2021-05-16T15:15:23.227 full_node full_node_server        : WARNING  Banning 173.218.xxx.xxx for 10 seconds
2021-05-16T15:15:23.231 full_node asyncio                 : ERROR    Task exception was never retrieved
future: <Task finished coro=<ChiaServer.incoming_api_task.<locals>.api_call() done, defined at chia\server\server.py:482> exception=CancelledError()>
concurrent.futures._base.CancelledError
  File "chia\server\server.py", line 531, in api_call
  File "asyncio\tasks.py", line 435, in wait_for

`

**Comment by Doom4535** [comment]
I believe I am encountering this issue as well, it seems that maintaining sync is *very* IO dependent and anything that may take IO from the full node can cause it to loose sync.

In my case I have my blockchain stored on the same NAS volume as my plots; I suspect that with the current implementation we will need to move the blockchain to a dedicated drive, possibly an SSD.

**Comment by Marigold5** [comment]
Hi Aaron

Although mine corrected itself (so far), I have the blockchain on an SSD the plot temps on two others and the farm plots exclusively on USB HDDs.

Hopefully it is enough, although I’m concerned I got the fault at all.

In your case, your own suggestion sounds good, just move the blockchain to a local drive…not sure it needs to be an SSD necessarily, but I had space.

Note the “no sleep” requirement, check your NAS for that and latency perhaps.

Tony

**Comment by casa10** [comment]
i have my blockchain on SSD and i have the problem of lost of synchro with full node. That is to say i lost all node id in connection peer. :(

**Comment by Marigold5** [comment]
Its clear that the blockchain needs to be readily accessible, while the farm plots do not.
I have it on a local M2SSD, so not an issue for me.

I have only lost sync a couple of times since, and not for more than a few minutes.

A bigger issue has been getting to 30% on parallel plots and the SSD being full. 5 plots on a blank 2TB SSD.  Something is not right!

I notice there are two temp drives if you look in advanced. Im now testing setting them on two different SSDs.
It’s a pain, as if it fails, it just sits there retrying, but I cannot cancel plots without shutting the entire blockchain off and restarting Chia.
Sorry I know this is off-thread, but I had to moan to someone. On the plus-side, when Ive figured it out, I’ll share the solution with you.
