### ISSUE TITLE
[BUG] Full node crashes with multiple harvesters connected

### ISSUE THREAD

**Issue by jiaolovekt** [Chia-Network/chia-blockchain#5202]
**Describe the bug**
fullnode crashes with 300+ harvesters connected
happened 4 times in last 12hours

**To Reproduce**

1. Start full node
2. Connect 200~300 harvesters to full node
3. wait a few hours (sometimes less than 1 hour)

**Screenshots**
stderr: Traceback (most recent call last):
  File "chia/daemon/server.py", line 982, in <module>
  File "chia/daemon/server.py", line 978, in main
  File "chia/daemon/server.py", line 972, in run_daemon
  File "asyncio/base_events.py", line 616, in run_until_complete
  File "chia/daemon/server.py", line 964, in async_run_daemon
  File "chia/daemon/server.py", line 143, in start
  File "websockets/server.py", line 965, in __await_impl__
  File "asyncio/base_events.py", line 1463, in create_server
OSError: [Errno 98] error while attempting to bind on address ('127.0.0.1', 55400): address already in use
[18442] Failed to execute script server
closing code: 255

<--- Last few GCs --->

[18436:0x2d8f00000000]  5276729 ms: Scavenge 3507.0 (3542.9) -> 3506.9 (3542.9) MB, 3.6 / 0.0 ms  (average mu = 0.119, current mu = 0.000) allocation failure 
[18436:0x2d8f00000000]  5276733 ms: Scavenge 3506.9 (3542.9) -> 3506.9 (3546.9) MB, 4.0 / 0.0 ms  (average mu = 0.119, current mu = 0.000) allocation failure 
[18436:0x2d8f00000000]  5277934 ms: Mark-sweep (reduce) 3506.9 (3546.9) -> 3504.0 (3537.2) MB, 1200.1 / 0.0 ms  (average mu = 0.074, current mu = 0.026) last resort GC in old space requested

<--- JS stacktrace --->

**Desktop (please complete the following information):**

- OS: Debian 10u6
- OS 4.19.0-16-amd64
- CPU: 2* 2640v3 16C32T in total
- Mem: 384G DDR4 RECC
- NIC: 10GE

**Additional context**
At first there's only 240 nodes, and seems crashes more frequently when increased to 300+.
harvester nodes are 2U 12Disks individual servers.

**Comment by wbendick** [comment]
your port is in use, probably have some old processes running, try rebooting

**Comment by jiaolovekt** [comment]
seems just the UI crashed, farmer and wallet still working but should kill the UI process instead of click the exit or all the process will exit.
