### ISSUE TITLE
Cant start electron 

### ISSUE THREAD

**Issue by wuast94** [Chia-Network/chia-blockchain#523]
Console Output:
```
(venv) root@server:/home/user/chia-blockchain/electron-react# npm run electron &
[1] 1955
(venv) root@server:/home/user/chia-blockchain/electron-react# 
> chia-blockchain@ electron /home/user/chia-blockchain/electron-react
> electron .

/home/user/chia-blockchain/electron-react/node_modules/electron/dist/electron: error while loading shared libraries: libgobject-2.0.so.0: cannot open shared object file: No such file or directory
npm ERR! code ELIFECYCLE
npm ERR! syscall spawn
npm ERR! file sh
npm ERR! errno ENOENT
npm ERR! chia-blockchain@ electron: `electron .`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the chia-blockchain@ electron script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-11-14T00_12_00_040Z-debug.log
```
and here teh log: 

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'run', 'electron' ]
2 info using npm@6.14.8
3 info using node@v14.15.0
4 verbose run-script [ 'preelectron', 'electron', 'postelectron' ]
5 info lifecycle chia-blockchain@~preelectron: chia-blockchain@
6 info lifecycle chia-blockchain@~electron: chia-blockchain@
7 verbose lifecycle chia-blockchain@~electron: unsafe-perm in lifecycle true
8 verbose lifecycle chia-blockchain@~electron: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/user/chia-blockchain/electron-react/node_modules/.bin:/home/user/chia-blo$
9 verbose lifecycle chia-blockchain@~electron: CWD: /home/user/chia-blockchain/electron-react
10 silly lifecycle chia-blockchain@~electron: Args: [ '-c', 'electron .' ]
11 info lifecycle chia-blockchain@~electron: Failed to exec electron script
12 verbose stack Error: chia-blockchain@ electron: `electron .`
12 verbose stack spawn ENOENT
12 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:48:18)
12 verbose stack     at ChildProcess.emit (events.js:315:20)
12 verbose stack     at maybeClose (internal/child_process.js:1048:16)
12 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
13 verbose pkgid chia-blockchain@
14 verbose cwd /home/user/chia-blockchain/electron-react
15 verbose Linux 4.19.0-11-amd64
16 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "electron"
17 verbose node v14.15.0
18 verbose npm  v6.14.8
19 error code ELIFECYCLE
20 error syscall spawn
21 error file sh
22 error errno ENOENT
23 error chia-blockchain@ electron: `electron .`
23 error spawn ENOENT
24 error Failed at the chia-blockchain@ electron script.
24 error This is probably not a problem with npm. There is likely additional logging output above.
25 verbose exit [ 1, true ]
```

**Comment by hoffmang9** [comment]
What version/branch are you attempting to run and on what Linux flavor/version?

This is your problem. You're missing a required shared module `libgobject-2.0.so.0: cannot open shared object file: No such file or directory`

**Comment by wuast94** [comment]
> What version/branch are you attempting to run and on what Linux flavor/version?
Debian Buster 10
> This is your problem. You're missing a required shared module `libgobject-2.0.so.0: cannot open shared object file: No such file or directory`

after installing this packages: 
libglib2.0-0 libxcomposite1 libxcursor1 libxi6 libxtst6 libnss3 libgdk-pixbuf2.0-0 libgtk-3-0 libxss1 libasound2
and fixing the chrome-sandbox owner and permissions i get this output: 

```
npm run electron &
[1] 22085
(venv) wuast94@fogserver:~/chia-blockchain/electron-react$ 
> chia-blockchain@ electron /home/wuast94/chia-blockchain/electron-react
> electron .

*DEV false
```
but no webpage shows up here on port 8444

**Comment by hoffmang9** [comment]
There is not a webpage at 8444. This should start an electron application so something is still broken with your node or your graphical desktop.

**Comment by seeden** [comment]
@hoffmang9  I see something similar at this moment. It is related to the "ping" command. We are sending it but a response will never come from the backend.

**Comment by seeden** [comment]
it is working fine with python 3.8

**Comment by hoffmang9** [comment]
I think the backup service was down over the weekend. If the wallet is stuck waiting on backup recovery this could be the issue.

**Comment by hoffmang9** [comment]
I believe this is resolved in Beta 21 - https://github.com/Chia-Network/chia-blockchain/releases/tag/1.0beta21
