### ISSUE TITLE
[BUG] Caught plotting error: Matches do not match with number of write entries

### ISSUE THREAD

**Issue by tkmbe99** [Chia-Network/chia-blockchain#5237]
**Describe the bug**
Plot of Chia 1.1.5 GUI dies with Unknown exception

**Screenshots**
![Captura de pantalla (4)](https://user-images.githubusercontent.com/48949966/118413963-5e56a700-b678-11eb-9405-f9b678ca804e.png)

**Desktop (please complete the following information):**
- OS: Win10 Pro
- OS 20H2
- CPU: Intel i5 760

**Additional context**
I was generating 2 plots with 4M/2Threas where I have 16M memory
The first plottstill working, the second one died after 2h 30min as noted in Phase 1/4 Computing table 3

Caught plotting error: Matches do not match with number of write entries 4294843967 4294844005
[8216] Failed to execute script chia
Traceback (most recent call last):
  File "chia\cmds\chia.py", line 81, in <module>
  File "chia\cmds\chia.py", line 77, in main
  File "click\core.py", line 829, in __call__
  File "click\core.py", line 782, in main
  File "click\core.py", line 1259, in invoke
  File "click\core.py", line 1259, in invoke
  File "click\core.py", line 1066, in invoke
  File "click\core.py", line 610, in invoke
  File "click\decorators.py", line 21, in new_func
  File "chia\cmds\plots.py", line 135, in create_cmd
  File "chia\plotting\create_plots.py", line 176, in create_plots
RuntimeError: Unknown exception

**Comment by wanghaijie2017** [comment]
same bug here

**Comment by MellowX** [comment]
and here

**Comment by prophetz2021** [comment]
i have this problem too

**Comment by Maschell** [comment]
Same bug here

**Comment by Chr1stm4s** [comment]
does anyone know how to solve this bug?

**Comment by Ismas** [comment]
Same bug. Still crashing on last code retrieved from repo (1.1.7-devel). Cannot plot, and I plotted >200 plots until now

**Comment by iimoos9** [comment]
I've been trying 2-3 times a day for the last week it's still happening.

**Comment by 2020movievault** [comment]
Let me join this club as I have the same problem =) Plotting Chia has been more challenging than GPU mining.
