### ISSUE TITLE
Connecting to Wallet - Software Hang

### ISSUE THREAD

**Issue by shinesoncc2** [Chia-Network/chia-blockchain#524]
After a restart of the PC, Chia got stuck at Hung.
![Connecting to Wallett](https://user-images.githubusercontent.com/68351189/99178805-687f0380-2730-11eb-9228-1a61e4d327fd.jpg)
 "Connecting to Wallet"
08:05:16.924 wallet wallet_server              : WARNING  Could not connect to {'host': '127.0.0.1', 'port': 8444}. <class 'ConnectionRefusedError'>[Errno 10061] Connect call failed ('127.0.0.1', 8444). Aborting and removing peer.
08:05:21.968 wallet wallet_server              : WARNING  Could not connect to {'host': '127.0.0.1', 'port': 8444}. <class 'ConnectionRefusedError'>[Errno 10061] Connect call failed ('127.0.0.1', 8444). Aborting and removing peer.
08:05:27.012 wallet wallet_server              : WARNING  Could not connect to {'host': '127.0.0.1', 'port': 8444}. <class 'ConnectionRefusedError'>[Errno 10061] Connect call failed ('127.0.0.1', 8444). Aborting and removing peer.
08:05:31.785 wallet src.rpc.wallet_rpc_api     : ERROR    error Cannot connect to host backup.chia.net:443 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1091)')]
08:05:32.578 wallet wallet_server              : WARNING  Could not connect to {'host': '127.0.0.1', 'port': 8444}. <class 'ConnectionRefusedError'>[Errno 10061] Connect call failed ('127.0.0.1', 8444). Aborting and removing peer.
08:05:37.675 wallet wallet_server              : WARNING  Could not connect to {'host': '127.0.0.1', 'port': 8444}. <class 'ConnectionRefusedError'>[Errno 10061] Connect call failed ('127.0.0.1', 8444). Aborting and removing peer.
08:05:38.893 wallet src.rpc.wallet_rpc_api     : ERROR    error Cannot connect to host backup.chia.net:443 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1091)')]
08:05:43.528 wallet src.wallet.wallet_node     : ERROR    Exception in create outbound connections: 
08:05:43.535 wallet src.wallet.wallet_node     : ERROR    Traceback: Traceback (most recent call last):
  File "src\server\node_discovery.py", line 160, in connectto_peers
  File "asyncio\tasks.py", line 595, in sleep
concurrent.futures._base.CancelledError
From debug log

**Comment by shinesoncc2** [comment]
Os: Windows 10 Pro
Uninstalled Chia software. Removed "\.chia\beta-1.0b17" folder.
Restarted machine. 
Reinstalled Chia.
Now back to normal.
