### ISSUE TITLE
Errors in Log chia

### ISSUE THREAD

**Issue by Sitnnov** [Chia-Network/chia-blockchain#5259]
hello , my errors .

seldom------full_node chia.full_node.full_node: ERROR    Consensus error 124, not disconnecting
Often----------status 3 error: Err.DOUBLE_SPEND
seldom -------status 3 error: Err.COIN_AMOUNT_NEGATIVE ---always for one transaction

ERROR    Exception:  <class 'concurrent.futures._base.CancelledError'>, closing connection {'host': '113.236.16.35', 'port': 8444}. Traceback (most recent call last):
  File "chia\server\server.py", line 531, in api_call
  File "asyncio\tasks.py", line 435, in wait_for
concurrent.futures._base.CancelledError

Read the topics on this topic, did not understand anything, I am not an experienced user

- OS: WIN 10
- CPU : amd 3500
- Chia 1.1.5
help me please
![Файл 00001](https://user-images.githubusercontent.com/84305774/118450870-5260f880-b6fd-11eb-8090-37edd5b955b8.jpg)

**Comment by shaunlourdes84** [comment]
hello , my errors .

2021-05-17T14:11:07.183 full_node chia.full_node.full_node: ERROR    Consensus error 124, not disconnecting
2021-05-17T14:11:34.986 full_node chia.full_node.full_node: ERROR    Consensus error 124, not disconnecting
2021-05-17T14:11:58.192 full_node chia.full_node.full_node: ERROR    Consensus error 124, not disconnecting

Read the topics on this topic, did not understand anything, I am not an experienced user help me please

OS: WIN 10
CPU : amd 3700x
Chia :1.1.5
