### ISSUE TITLE
RuntimeError: bad allocation

### ISSUE THREAD

**Issue by KennethAguilar** [Chia-Network/chia-blockchain#5288]
When creating one or more simultaneous plots it throws the error:
Computing table 2
Caught plotting error: bad allocation
[18168] Failed to execute script chia
Traceback (most recent call last):
   File "chia \ cmds \ chia.py", line 81, in <module>
   File "chia \ cmds \ chia.py", line 77, in main
   File "click \ core.py", line 829, in __call__
   File "click \ core.py", line 782, in main
   File "click \ core.py", line 1259, in invoke
   File "click \ core.py", line 1259, in invoke
   File "click \ core.py", line 1066, in invoke
   File "click \ core.py", line 610, in invoke
   File "click \ decorators.py", line 21, in new_func
   File "chia \ cmds \ plots.py", line 135, in create_cmd
   File "chia \ plotting \ create_plots.py", line 176, in create_plots
RuntimeError: bad allocation

**Comment by wbendick** [comment]
how much ram did you configure the plotter to use. how much is available in your system?

**Comment by Siom-lab** [comment]
64000 MB
