### ISSUE TITLE
[BUG]FileNotFoundError: [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by fullet-tortuga** [Chia-Network/chia-blockchain#5301]
Fresh install of version 1.1.5 on a clean Windows.

GUI yields software exception 0xe00000008 at 0xfd4dbe0d.

CLI:
Starting daemon
Traceback (most recent call last):
  File "chia\cmds\chia.py", line 81, in <module>
  File "chia\cmds\chia.py", line 77, in main
  File "click\core.py", line 829, in __call__
  File "click\core.py", line 782, in main
  File "click\core.py", line 1259, in invoke
  File "click\core.py", line 1066, in invoke
  File "click\core.py", line 610, in invoke
  File "click\decorators.py", line 21, in new_func
  File "chia\cmds\chia.py", line 60, in run_daemon_cmd
  File "asyncio\base_events.py", line 587, in run_until_complete
  File "chia\daemon\server.py", line 963, in async_run_daemon
  File "chia\daemon\server.py", line 128, in __init__
  File "chia\server\server.py", line 36, in ssl_context_for_server
FileNotFoundError: [Errno 2] No such file or directory
[3880] Failed to execute script chia
Daemon not started yet
Failed to create the chia daemon

**Comment by wbendick** [comment]
did you run . activate ?

**Comment by fullet-tortuga** [comment]
I don't think so since I don't know about that activation ^_^ Could you please elavorate on that? It was working okay back in version 1.1.1 but now installing 1.1.5. doesn't work for me anymore. Not even upgrading over a 1.1.1. install.

**Comment by sparky3387** [comment]
To anyone that has this issue after running outside of a VENV, ensure all chia programs other than plotting are closed and delete mainnet/run folders contents

**Comment by fullet-tortuga** [comment]
Upgrading from 1.1.5. to 1.1.7. yields the same error.

Starting daemon
Traceback (most recent call last):
  File "chia\cmds\chia.py", line 81, in <module>
  File "chia\cmds\chia.py", line 77, in main
  File "click\core.py", line 829, in __call__
  File "click\core.py", line 782, in main
  File "click\core.py", line 1259, in invoke
  File "click\core.py", line 1066, in invoke
  File "click\core.py", line 610, in invoke
  File "click\decorators.py", line 21, in new_func
  File "chia\cmds\chia.py", line 60, in run_daemon_cmd
  File "asyncio\base_events.py", line 587, in run_until_complete
  File "chia\daemon\server.py", line 976, in async_run_daemon
  File "chia\daemon\server.py", line 128, in __init__
  File "chia\server\server.py", line 36, in ssl_context_for_server
FileNotFoundError: [Errno 2] No such file or directory
[2364] Failed to execute script chia
Daemon not started yet
Failed to create the chia daemon

**Comment by fullet-tortuga** [comment]
Bug is not fixed either as in last version. So you cannot close it. Bug is open.
