### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by miguelo8** [Chia-Network/chia-blockchain#5360]
1%

2021-05-17T22:24:45.886  chia.plotting.create_plots       : [32mINFO    [0m Creating 1 plots of size 32, pool public key:  a6f8f779abc70da31749aefa9f73d9a23ea23b6254f6d618268eada79f5da5681a7c2e600451cc126b3d7f8ee1062aa4 farmer public key: 830568de47381d2477dd9f141a6e36f0bdfbe0513ea8dbcaa3940c26e4e1e61e4a47a332b7690459b71ea0ad44df7be0[0m
2021-05-17T22:24:45.906  chia.plotting.create_plots       : [32mINFO    [0m Memo: a6f8f779abc70da31749aefa9f73d9a23ea23b6254f6d618268eada79f5da5681a7c2e600451cc126b3d7f8ee1062aa4830568de47381d2477dd9f141a6e36f0bdfbe0513ea8dbcaa3940c26e4e1e61e4a47a332b7690459b71ea0ad44df7be01db72d0208e026ed2c0082c98283c29119c68d895ba82b355dbb2df2a867e363[0m
2021-05-17T22:24:45.907  chia.plotting.create_plots       : [32mINFO    [0m Starting plot 1/1[0m
Caught plotting error: Bitfield plotting not supported by CPU
[1636] Failed to execute script chia
Traceback (most recent call last):
  File "chia\cmds\chia.py", line 81, in <module>
  File "chia\cmds\chia.py", line 77, in main
  File "click\core.py", line 829, in __call__
  File "click\core.py", line 782, in main
  File "click\core.py", line 1259, in invoke
  File "click\core.py", line 1259, in invoke
  File "click\core.py", line 1066, in invoke
  File "click\core.py", line 610, in invoke
  File "click\decorators.py", line 21, in new_func
  File "chia\cmds\plots.py", line 135, in create_cmd
  File "chia\plotting\create_plots.py", line 176, in create_plots
RuntimeError: Unknown exception

**Comment by miguelo8** [comment]
solution please...

**Comment by redbaron** [comment]
@miguelo8 , you can disable bitfield plotting with the tickbox under advanced section in the UI.

**Comment by miguelo8** [comment]
Thanks..
