### ISSUE TITLE
[BUG] Results in desync very frequently and for hours sometimes

### ISSUE THREAD

**Issue by Drewski-Ariz** [Chia-Network/chia-blockchain#5362]
2021-05-17T19:10:26.520 full_node full_node_server        : ERROR    Exception: Error short batch syncing, invalid/no response for 297090-297122, None. Traceback (most recent call last):
  File "chia\server\server.py", line 521, in wrapped_coroutine
  File "chia\full_node\full_node_api.py", line 104, in new_peak
  File "chia\full_node\full_node.py", line 374, in new_peak
  File "chia\full_node\full_node.py", line 246, in short_sync_batch
ValueError: Error short batch syncing, invalid/no response for 297090-297122

2021-05-17T19:10:26.521 full_node full_node_server        : ERROR    Exception: Error short batch syncing, invalid/no response for 297090-297122 <class 'ValueError'>, closing connection None. Traceback (most recent call last):
  File "chia\server\server.py", line 531, in api_call
  File "asyncio\tasks.py", line 414, in wait_for
  File "chia\server\server.py", line 528, in wrapped_coroutine
  File "chia\server\server.py", line 521, in wrapped_coroutine
  File "chia\full_node\full_node_api.py", line 104, in new_peak
  File "chia\full_node\full_node.py", line 374, in new_peak
  File "chia\full_node\full_node.py", line 246, in short_sync_batch
ValueError: Error short batch syncing, invalid/no response for 297090-297122

Keep getting this resulting in desyncing, anyone know how to resolve this? port:8444 is open

**Comment by sudo-mk-sandwich** [comment]
Same here, 1.1.5 Linux Mint, not synced. Lot of Error short batch syncing. 8444 open.
