### ISSUE TITLE
chia error help

### ISSUE THREAD

**Issue by thensley84** [Chia-Network/chia-blockchain#5379]
here is the message i am repeatedly getting in my log file, please help me out with this, thanks for your time

2021-05-17T21:02:36.201 full_node chia.rpc.rpc_server     : WARNING  Sending data failed. Exception Traceback (most recent call last):
  File "chia\rpc\rpc_server.py", line 67, in _state_changed
  File "aiohttp\client_ws.py", line 150, in send_str
  File "aiohttp\http_websocket.py", line 687, in send
  File "aiohttp\http_websocket.py", line 643, in _send_frame
  File "aiohttp\http_websocket.py", line 660, in _write
ConnectionResetError: Cannot write to closing transport
.

**Comment by wbendick** [comment]
it means a peer disappeared
