### ISSUE TITLE
Local Chia node ban himself[BUG]

### ISSUE THREAD

**Issue by dipol0** [Chia-Network/chia-blockchain#5430]
In LOG:

`2021-05-18T18:09:44.931 full_node full_node_server        : WARNING  Trying to ban localhost for 10, but will not ban
2021-05-18T18:26:41.114 full_node full_node_server        : ERROR    Exception:  <class 'asyncio.exceptions.TimeoutError'>, closing connection {'host': '127.0.0.1', 'port': 8449}. Traceback (most recent call last):
  File "chia/server/server.py", line 531, in api_call
  File "asyncio/tasks.py", line 501, in wait_for
asyncio.exceptions.TimeoutError
`
and client (node) very very long time synching....

**Desktop (please complete the following information):**

- OS: [Ubuntu]
- OS Version/Flavor: [Linux land33 5.10.3-custom-zfs200rc1 #4 SMP Sun Dec 27 15:53:36 MSK 2020 x86_64 x86_64 x86_64 GNU/Linux]
- CPU: [Intel Core i7 7700K]
- Chia - v1.1.5

**Comment by dipol0** [comment]
Chia - v 1.1.5

**Comment by gldecurtins** [comment]
I had the same.. while the system was under heavy load - e.g. copying over files to the final folder.
I think I only got it syncing again after I restarted the farmer.
