### ISSUE TITLE
[BUG] Syncing slow and localhost ban

### ISSUE THREAD

**Issue by chienbinhso14** [Chia-Network/chia-blockchain#5492]
Fullnode GUI on windows slow in syncing. I have another fullnode - Ubuntu 20.4 Fully synced but windows node keeping remove it's from Connection.

```
2021-05-19T13:57:57.943 full_node full_node_server        : ERROR    Exception:  <class 'concurrent.futures._base.CancelledError'>, closing connection {'host': '35.236.207.155', 'port': 8444}. Traceback (most recent call last):
  File "chia\server\server.py", line 531, in api_call
  File "asyncio\tasks.py", line 435, in wait_for
concurrent.futures._base.CancelledError

2021-05-19T13:57:57.948 full_node full_node_server        : ERROR    Exception:  <class 'concurrent.futures._base.CancelledError'>, closing connection {'host': '35.236.207.155', 'port': 8444}. Traceback (most recent call last):
  File "chia\server\server.py", line 531, in api_call
  File "asyncio\tasks.py", line 435, in wait_for
concurrent.futures._base.CancelledError

2021-05-19T14:01:08.393 full_node full_node_server        : ERROR    Exception:  <class 'concurrent.futures._base.TimeoutError'>, closing connection {'host': '127.0.0.1', 'port': 8449}. Traceback (most recent call last):
  File "chia\server\server.py", line 531, in api_call
  File "asyncio\tasks.py", line 449, in wait_for
concurrent.futures._base.TimeoutError

2021-05-19T14:01:08.415 full_node full_node_server        : WARNING  Trying to ban localhost for 10, but will not ban
2021-05-19T14:01:08.418 full_node asyncio                 : ERROR    Task exception was never retrieved
future: <Task finished coro=<ChiaServer.incoming_api_task.<locals>.api_call() done, defined at chia\server\server.py:482> exception=CancelledError()>
concurrent.futures._base.CancelledError
2021-05-19T14:04:13.369 full_node full_node_server        : ERROR    Exception: Error short batch syncing, invalid/no response for 302972-303004, None. Traceback (most recent call last):
  File "chia\server\server.py", line 521, in wrapped_coroutine
  File "chia\full_node\full_node_api.py", line 104, in new_peak
  File "chia\full_node\full_node.py", line 374, in new_peak
  File "chia\full_node\full_node.py", line 246, in short_sync_batch
ValueError: Error short batch syncing, invalid/no response for 302972-303004

2021-05-19T14:04:13.395 full_node full_node_server        : ERROR    Exception: Error short batch syncing, invalid/no response for 302972-303004 <class 'ValueError'>, closing connection None. Traceback (most recent call last):
  File "chia\server\server.py", line 531, in api_call
  File "asyncio\tasks.py", line 414, in wait_for
  File "chia\server\server.py", line 528, in wrapped_coroutine
  File "chia\server\server.py", line 521, in wrapped_coroutine
  File "chia\full_node\full_node_api.py", line 104, in new_peak
  File "chia\full_node\full_node.py", line 374, in new_peak
  File "chia\full_node\full_node.py", line 246, in short_sync_batch
ValueError: Error short batch syncing, invalid/no response for 302972-303004

2021-05-19T14:04:13.402 full_node full_node_server        : ERROR    Exception: Error short batch syncing, invalid/no response for 302972-303004, None. Traceback (most recent call last):
  File "chia\server\server.py", line 521, in wrapped_coroutine
  File "chia\full_node\full_node_api.py", line 104, in new_peak
  File "chia\full_node\full_node.py", line 374, in new_peak
  File "chia\full_node\full_node.py", line 246, in short_sync_batch
ValueError: Error short batch syncing, invalid/no response for 302972-303004

2021-05-19T14:04:13.406 full_node full_node_server        : ERROR    Exception: Error short batch syncing, invalid/no response for 302972-303004 <class 'ValueError'>, closing connection None. Traceback (most recent call last):
  File "chia\server\server.py", line 531, in api_call
  File "asyncio\tasks.py", line 414, in wait_for
  File "chia\server\server.py", line 528, in wrapped_coroutine
  File "chia\server\server.py", line 521, in wrapped_coroutine
  File "chia\full_node\full_node_api.py", line 104, in new_peak
  File "chia\full_node\full_node.py", line 374, in new_peak
  File "chia\full_node\full_node.py", line 246, in short_sync_batch
ValueError: Error short batch syncing, invalid/no response for 302972-303004


```

**Comment by BigFactHunt** [comment]
Looks the same as BUG #5471 ??

**Comment by alex-oden** [comment]
Hi, I have installed this version of chia (beta build as I understand) and all working fine and stable with lot of connection from another peers. As I understand and see in logs - if there is some failure in connection it will not stop with sync and beginning with new connection but stays stable with existing peer connection

https://github.com/Chia-Network/chia-blockchain/actions/runs/853387813

Right now by me it working very good without any issues and Full node don't take a lot of power with CPU consumption. Already in Sync about 6 hours stable and FINALLY it sees my another local harvester...

(Also if you have not opened or forward on your router port 8444) You need to do that - here some help
https://portforward.com/
