### ISSUE TITLE
RuntimeError: bad allocation

### ISSUE THREAD

**Issue by Siom-lab** [Chia-Network/chia-blockchain#5494]
I have an issue.
Windows 10 has 64 GB of ram. 30 GB RAM of plotter

Starting plotting progress into temporary dirs: D:\Chia and D:\Chia
ID: 8126c8c7747c32d348c574e71cf45c466d73c7e7835a7fb69d78854352ca4e12
Plot size is: 32
Buffer size is: 30600MiB
Using 128 buckets
Using 6 threads of stripe size 65536

Starting phase 1/4: Forward Propagation into tmp files... Tue May 18 13:18:23 2021
Computing table 1
F1 complete, time: 97.958 seconds. CPU (194.45%) Tue May 18 13:20:00 2021
Computing table 2
Caught plotting error: bad allocation
[7764] Failed to execute script chia
Traceback (most recent call last):
File "chia\cmds\chia.py", line 81, in
File "chia\cmds\chia.py", line 77, in main
File "click\core.py", line 829, in call
File "click\core.py", line 782, in main
File "click\core.py", line 1259, in invoke
File "click\core.py", line 1259, in invoke
File "click\core.py", line 1066, in invoke
File "click\core.py", line 610, in invoke
File "click\decorators.py", line 21, in new_func
File "chia\cmds\plots.py", line 135, in create_cmd
File "chia\plotting\create_plots.py", line 176, in create_plots
RuntimeError: bad allocation

If anone know how to resolve that issue ? I will be grateful

**Comment by 42x42x42** [comment]
your problem is "Buffer size is: 30600MiB" you allocated 30gb of RAM it's too much for a single plot, 4-5gb is enough
