### ISSUE TITLE
Что означает? Что делать?

### ISSUE THREAD

**Issue by AlecseyM** [Chia-Network/chia-blockchain#5499]
Постоянно выдает какую ни будь ошибку, уже озвученную в чате!!!
Но это началось сейчас и пополняет лог!

2021-05-19T17:05:22.885 full_node chia.full_node.full_node: WARNING  Wasn't able to add transaction with id 002a80409f565742bedbb6ff6b10ef726afa3aeca60fc80b9c4e6564a23b6f36, status 3 error: Err.DOUBLE_SPEND
2021-05-19T17:05:23.073 full_node chia.full_node.full_node: WARNING  Wasn't able to add transaction with id a0c2b7377e054fed0e3ca3edb0e34c847deb8e87203ac3a399560ea06a6989a8, status 3 error: Err.DOUBLE_SPEND
2021-05-19T17:05:24.242 full_node chia.full_node.full_node: WARNING  Wasn't able to add transaction with id b485a80af72b8ecdc4093eda5f5729c6966efe1532145a02df2746807c9cd366, status 3 error: Err.DOUBLE_SPEND
2021-05-19T17:05:24.259 full_node chia.full_node.full_node: WARNING  Wasn't able to add transaction with id 49665bed47e88f81030c1ae9fbaa75582a2831d933ff933acca466343fe0b293, status 3 error: Err.DOUBLE_SPEND
2021-05-19T17:05:24.274 full_node chia.full_node.full_node: WARNING  Wasn't able to add transaction with id af350881ce5f05602144e5e10b52f6b87a707a2449ba09a93e9d30fc8c71420b, status 3 error: Err.DOUBLE_SPEND
2021-05-19T17:05:24.437 full_node chia.full_node.full_node: WARNING  Wasn't able to add transaction with id f95eb1132cf36fc8de73739266b030654d5cfc5f069d3d64408bf5dac56df9fe, status 3 error: Err.DOUBLE_SPEND
2021-05-19T17:05:24.483 full_node chia.full_node.full_node: WARNING  Wasn't able to add transaction with id a73b2491c3aa8b77689e97d9b6b999eeab5a97aeabf92cd4bcc880d915a1037e, status 3 error: Err.DOUBLE_SPEND
2021-05-19T17:05:33.370 full_node chia.full_node.full_node: WARNING  Wasn't able to add transaction with id 8f79a0e24e90e313209261cc0b96cad8499e6ac471dd9d8deabf8421b7e36f10, status 3 error: Err.DOUBLE_SPEND
2021-05-19T17:05:33.376 full_node chia.full_node.full_node: WARNING  Wasn't able to add transaction with id 4b75b9199fc601b52fdce6e2cb581c2418038945ebc4dc412b44bfee1271a48b, status 3 error: Err.DOUBLE_SPEND
2021-05-19T17:05:45.938 full_node chia.full_node.full_node: WARNING  Wasn't able to add transaction with id 32017ec05255f135ab710ce74ca6d9e8e29cdff9cb6f19b6d235c6a7d0c961ea, status 3 error: Err.DOUBLE_SPEND
2021-05-19T17:05:45.942 full_node chia.full_node.full_node: WARNING  Wasn't able to add transaction with id ffdc756e790d9eff39d3f9f01dad3e796699c13dc06f195acac346705515e6a1, status 3 error: Err.DOUBLE_SPEND
2021-05-19T17:05:45.945 full_node chia.full_node.full_node: WARNING  Wasn't able to add transaction with id 53cbf20f807e5ca8f62520f40d3a6c6318cd78df50641de5e506a0359b55e1b2, status 3 error: Err.DOUBLE_SPEND
2021-05-19T17:05:45.946 full_node chia.full_node.full_node: WARNING  Wasn't able to add transaction with id d405e9b1c8e0aa78bfa1093aed1bf77eff253e84f2cdfd9f928ac7f19233aad6, status 3 error: Err.DOUBLE_SPEND
2021-05-19T17:05:45.948 full_node chia.full_node.full_node: WARNING  Wasn't able to add transaction with id 7d77f94820e0aa71079912839b89ecad118c8badae85db4ce01697c7cd90a3a3, status 3 error: Err.DOUBLE_SPEND
2021-05-19T17:05:45.949 full_node chia.full_node.full_node: WARNING  Wasn't able to add transaction with id 26abb91290bcb70ceba3d43455b8435bbb61cd5f7967db0b9b684de280b8f652, status 3 error: Err.DOUBLE_SPEND
2021-05-19T17:06:12.563 full_node chia.full_node.full_node: WARNING  Wasn't able to add transaction with id 699a439fe419d8ed2d5da6ad88130c423ce4e5f79199f18ec0021913e035a197, status 3 error: Err.DOUBLE_SPEND
2021-05-19T17:06:12.663 full_node chia.full_node.full_node: WARNING  Wasn't able to add transaction with id 876cf95f113f29072e97e7bf2537a41e3e0a92cbfa9a8b8e5338a28afaaf37cb, status 3 error: Err.DOUBLE_SPEND
2021-05-19T17:06:12.667 full_node chia.full_node.full_node: WARNING  Wasn't able to add transaction with id 10ab548243e269deaa8d67c1f31340d917e58c4f288c03b032406939d8b650c5, status 3 error: Err.DOUBLE_SPEND
2021-05-19T17:06:12.672 full_node chia.full_node.full_node: WARNING  Wasn't able to add transaction with id e89caed457e01278f537c6282b32648041d1287aea91757cd4244f19434b8759, status 3 error: Err.DOUBLE_SPEND
2021-05-19T17:06:12.675 full_node chia.full_node.full_node: WARNING  Wasn't able to add transaction with id 02e7c2cf6c5f7884ac1742cdff7bc9e747d9b56d2b4637c9040abcfda988b09b, status 3 error: Err.DOUBLE_SPEND
2021-05-19T17:06:12.680 full_node chia.full_node.full_node: WARNING  Wasn't able to add transaction with id e81926d70f6f32c322d7d43329edd617e78ba5e5f687c0b8d2c5c5bcdb2ed7f1, status 3 error: Err.DOUBLE_SPEND
2021-05-19T17:06:12.686 full_node chia.full_node.full_node: WARNING  Wasn't able to add transaction with id c2a31b0f70247f6ab3cf405a8c5fafc6da86a10ff6585bdfba7d9223a8d04f34, status 3 error: Err.DOUBLE_SPEND
2021-05-19T17:06:12.692 full_node chia.full_node.full_node: WARNING  Wasn't able to add transaction with id 9377a4be0cb5047597a34e4470d0256aba5c214587ac3d595174154e374c7835, status 3 error: Err.DOUBLE_SPEND
2021-05-19T17:06:12.695 full_node chia.full_node.full_node: WARNING  Wasn't able to add transaction with id 4224ab85cf82b4a745964f0b9c8dc0d048bc45fd327d3dcca6419b2b51a55022, status 3 error: Err.DOUBLE_SPEND
2021-05-19T17:06:12.700 full_node chia.full_node.full_node: WARNING  Wasn't able to add transaction with id c2d3b260d6d96fd53c8a467fc409476b83bb648cad73897c5004bcedd8174f7f, status 3 error: Err.DOUBLE_SPEND
2021-05-19T17:07:52.212 full_node chia.full_node.full_node: ERROR    Consensus error 124, not disconnecting
2021-05-19T17:08:21.870 full_node chia.full_node.full_node: WARNING  Wasn't able to add transaction with id 053e50167774353425c2650929ce45f919f6185b06799cefb15ec74fe0b55f89, status 3 error: Err.DOUBLE_SPEND
2021-05-19T17:08:21.886 full_node chia.full_node.full_node: WARNING  Wasn't able to add transaction with id f400064d6d489b53e9887ff3adff5929a35d61fbc448d4e4540df367bd9aac92, status 3 error: Err.DOUBLE_SPEND
2021-05-19T17:08:22.465 full_node chia.full_node.full_node: WARNING  Wasn't able to add transaction with id 5b034418a775b95ef50fc2fb64206c1cb1fb8a51ccfe229fccdda46c2a821cbb, status 3 error: Err.DOUBLE_SPEND
2021-05-19T17:08:22.497 full_node chia.full_node.full_node: WARNING  Wasn't able to add transaction with id d0a6880f9de14e90c9a025171253f2d3045bbe0cabc1de340c65c6a17efa1b87, status 3 error: Err.DOUBLE_SPEND
2021-05-19T17:08:22.512 full_node chia.full_node.full_node: WARNING  Wasn't able to add transaction with id 00b10b1da4b77fddbb4e87a8d565a8e1998ac8b2253c76d54b610ce065ce034b, status 3 error: Err.DOUBLE_SPEND
2021-05-19T17:08:30.769 full_node chia.full_node.full_node: WARNING  Wasn't able to add transaction with id b161aadd3d93d14efd4761175107777161e0ca1068a3bf0a33cc510e61936bfb, status 3 error: Err.DOUBLE_SPEND
2021-05-19T17:08:30.769 full_node chia.full_node.full_node: WARNING  Wasn't able to add transaction with id 434e86f1bade47541b4206d48ac3dbd14954c0f5aacaf0bb356e72423999dc65, status 3 error: Err.DOUBLE_SPEND
2021-05-19T17:08:30.831 full_node chia.full_node.full_node: WARNING  Wasn't able to add transaction with id 48e005664f0e72901b905bed5400fdae4910c0b3af0b5938aa56ad470010da84, status 3 error: Err.DOUBLE_SPEND
2021-05-19T17:08:30.847 full_node chia.full_node.full_node: WARNING  Wasn't able to add transaction with id 2d6b305edbd8b874b3330ad417a5de696e1bc1889cfad708f44b406c0eca96a3, status 3 error: Err.DOUBLE_SPEND
2021-05-19T17:08:30.847 full_node chia.full_node.full_node: WARNING  Wasn't able to add transaction with id d8b5b9bba912f19a3b4d6b4f6617964fdafdc073236e3f9d4a37162d72fa16d4, status 3 error: Err.DOUBLE_SPEND
2021-05-19T17:08:30.847 full_node chia.full_node.full_node: WARNING  Wasn't able to add transaction with id 89a78c9263336e29cb5e94654a902a216f14a8d3e2fc2f69ca850b7fa4a05e95, status 3 error: Err.DOUBLE_SPEND
2021-05-19T17:08:30.878 full_node chia.full_node.full_node: WARNING  Wasn't able to add transaction with id 2ce8aa880befb86277ebde758f875d48bf2801d82c2062f575a6ce9d861564b9, status 3 error: Err.DOUBLE_SPEND
2021-05-19T17:09:04.674 full_node chia.full_node.full_node: WARNING  Wasn't able to add transaction with id ccd40cd833bccb94dfddd7a0cde5a16c2a61e557ed3806333257c20cb4b6ce6e, status 3 error: Err.DOUBLE_SPEND
2021-05-19T17:09:04.708 full_node chia.full_node.full_node: WARNING  Wasn't able to add transaction with id f3b2abd63b5ddaf56b01e08cf14c6da9e6936789429e3aea7bc96ef58175ca9f, status 3 error: Err.DOUBLE_SPEND
2021-05-19T17:09:04.783 full_node chia.full_node.full_node: WARNING  Wasn't able to add transaction with id 4d8f5504db96a2294c4a2a0dd0f2312992ec39687c2e9df3a00517306afbc131, status 3 error: Err.DOUBLE_SPEND
2021-05-19T17:12:41.819 full_node chia.full_node.full_node: WARNING  Wasn't able to add transaction with id 0fe9986ad0c33f3e1c3f141f0281646ee663d47b3ec6c8ecd1d6d2de27583626, status 3 error: Err.DOUBLE_SPEND
2021-05-19T17:12:41.821 full_node chia.full_node.full_node: WARNING  Wasn't able to add transaction with id cb28a93dd6cf51a36057fe76d7600951b40c9e7aa2e60d6718018299f0fdae48, status 3 error: Err.DOUBLE_SPEND
2021-05-19T17:12:42.932 full_node chia.full_node.full_node: WARNING  Wasn't able to add transaction with id 2dc443a2442a40521f702a1308ab005f410a4ccc1a4d1a9e7d65a807ede6be2e, status 3 error: Err.DOUBLE_SPEND
2021-05-19T17:12:42.934 full_node chia.full_node.full_node: WARNING  Wasn't able to add transaction with id ae96846d084e00f3cfea736bdcd024c2878ab9758f828bdb1b223af2f5ab1d3c, status 3 error: Err.DOUBLE_SPEND
2021-05-19T17:14:07.748 full_node chia.full_node.full_node: WARNING  Wasn't able to add transaction with id 5e0fd02fa737a16dd9252f00973c1de56ebd70a947592925f1389673e4a78c2a, status 3 error: Err.COIN_AMOUNT_NEGATIVE
2021-05-19T17:17:03.131 full_node chia.full_node.full_node: WARNING  Wasn't able to add transaction with id 5e0fd02fa737a16dd9252f00973c1de56ebd70a947592925f1389673e4a78c2a, status 3 error: Err.COIN_AMOUNT_NEGATIVE
2021-05-19T17:19:30.095 full_node chia.full_node.full_node: WARNING  Wasn't able to add transaction with id 3133cbc9aa71f69486b038af8e61a188e6a02a90e7ca110aa66d663cc3a69a5a, status 3 error: Err.UNKNOWN_UNSPENT
2021-05-19T17:19:30.110 full_node chia.full_node.full_node: WARNING  Wasn't able to add transaction with id b3ddaa2cf44a33c76079544b8c8e6308f42b47684de688382b788bb7c7694bdb, status 3 error: Err.UNKNOWN_UNSPENT
2021-05-19T17:19:32.051 full_node chia.full_node.full_node: WARNING  Wasn't able to add transaction with id 1ef5e342ec5e8ca43294c2a8532d51f1065f05eeb730dfb614b51458797fb4f8, status 3 error: Err.UNKNOWN_UNSPENT
2021-05-19T17:19:32.473 full_node chia.full_node.full_node: WARNING  Wasn't able to add transaction with id aa62e04be82492949fb08a0f3047da04f8e2af23497409909fe2b46098d3358e, status 3 error: Err.UNKNOWN_UNSPENT
2021-05-19T17:19:32.473 full_node chia.full_node.full_node: WARNING  Wasn't able to add transaction with id d4ab0a38dbdd9bcc2a6bc91ced0f3e40cb36e20f1992253692b7c43d4ffad501, status 3 error: Err.UNKNOWN_UNSPENT
2021-05-19T17:19:32.895 full_node chia.full_node.full_node: WARNING  Wasn't able to add transaction with id a5e7508ba3b68913252684a8fba3bc5eb622c9394886d6316b73e14d5b0de88d, status 3 error: Err.UNKNOWN_UNSPENT
2021-05-19T17:20:08.848 full_node chia.full_node.full_node: WARNING  Wasn't able to add transaction with id e8ddf0d79d1351c97c9108ef8006685111189eaae47c3727afcd960218f1aa7d, status 3 error: Err.UNKNOWN_UNSPENT
2021-05-19T17:20:09.254 full_node chia.full_node.full_node: WARNING  Wasn't able to add transaction with id 7436d2dcf5e74ccd3b14195bbe1b3ab81a214a4662f3139ae987bb59fb922008, status 3 error: Err.UNKNOWN_UNSPENT
2021-05-19T17:20:09.739 full_node chia.full_node.full_node: WARNING  Wasn't able to add transaction with id 27ebbdd238215a5105d7bdd49e1408535e653e4cdfc3cb68d387aacd7dede05e, status 3 error: Err.UNKNOWN_UNSPENT
2021-05-19T17:20:13.956 full_node chia.full_node.full_node: WARNING  Wasn't able to add transaction with id 6e78674544088c84be8428777494370566a6cf9750161123e15dfd9ae204757b, status 3 error: Err.UNKNOWN_UNSPENT
2021-05-19T17:20:13.956 full_node chia.full_node.full_node: WARNING  Wasn't able to add transaction with id cf2ed0d11ab87fd867db0b1435db8bc6b4900a553842e6b322181fd31425ffad, status 3 error: Err.UNKNOWN_UNSPENT
2021-05-19T17:20:14.363 full_node chia.full_node.full_node: WARNING  Wasn't able to add transaction with id 89d9c069667a0204dd84183ab2dccdd0d559c726a15741be077f7ac94334046b, status 3 error: Err.UNKNOWN_UNSPENT
2021-05-19T17:21:16.410 full_node chia.full_node.full_node: WARNING  Wasn't able to add transaction with id 4146f38295dcbdab37ba546d6576e82e56e5ba1b61a9daabd1015c4f661f9998, status 3 error: Err.DOUBLE_SPEND
2021-05-19T17:21:16.410 full_node chia.full_node.full_node: WARNING  Wasn't able to add transaction with id 7fb28d5a4c2a6ec390a88bbc922b86b69be73289ca56d5d5b7d38408320a5cb8, status 3 error: Err.DOUBLE_SPEND
2021-05-19T17:21:16.410 full_node chia.full_node.full_node: WARNING  Wasn't able to add transaction with id 050c6ab68c8c6c51c27f689a828ddceffdd0842111debb7b327d89b8d07b977b, status 3 error: Err.DOUBLE_SPEND
2021-05-19T17:21:27.422 full_node chia.full_node.full_node: WARNING  Wasn't able to add transaction with id e3b497ab1d4cf41a29832fb5bd81b0e3e5379854c6313381b8957795a4359a0f, status 3 error: Err.UNKNOWN_UNSPENT
2021-05-19T17:21:28.750 full_node chia.full_node.full_node: WARNING  Wasn't able to add transaction with id cd3957b248f6f52161b6180087e13e932af377329f8e319ead5633ad6aacc8cb, status 3 error: Err.UNKNOWN_UNSPENT
2021-05-19T17:21:30.125 full_node chia.full_node.full_node: WARNING  Wasn't able to add transaction with id 770b0f15e1aebdf56cb55758813db319ba31b24634e673de61a3e00f778e65bd, status 3 error: Err.UNKNOWN_UNSPENT
2021-05-19T17:22:32.366 full_node chia.full_node.full_node: WARNING  Wasn't able to add transaction with id 24a28a6c12b14e2667603378b0d0b39f0d7151dcf87861640b4b4678ae8ebe2e, status 3 error: Err.UNKNOWN_UNSPENT
2021-05-19T17:22:32.376 full_node chia.full_node.full_node: WARNING  Wasn't able to add transaction with id 4fa9166f4864bf1db4490ea6455858fcd699c84d09d28421f3c1f81be42c3b58, status 3 error: Err.UNKNOWN_UNSPENT
2021-05-19T17:22:33.204 full_node chia.full_node.full_node: WARNING  Wasn't able to add transaction with id c5b73f82b0038a3168363f1463841a17e7c6f47f5f139c24554a27ffec002bb4, status 3 error: Err.UNKNOWN_UNSPENT
2021-05-19T17:22:33.699 full_node chia.full_node.full_node: WARNING  Wasn't able to add transaction with id 770b0f15e1aebdf56cb55758813db319ba31b24634e673de61a3e00f778e65bd, status 3 error: Err.UNKNOWN_UNSPENT
2021-05-19T17:22:35.533 full_node chia.full_node.full_node: WARNING  Wasn't able to add transaction with id 65c3ccdf42c33958d812d660c3fb3690d48fcb00ce0f91e9c64f0fddda46bcb3, status 3 error: Err.DOUBLE_SPEND
2021-05-19T17:22:35.535 full_node chia.full_node.full_node: WARNING  Wasn't able to add transaction with id c8538e04a72dd1ef3754ff7a4f97459e1426460a5090301f18fd681be3ea7091, status 3 error: Err.DOUBLE_SPEND
2021-05-19T17:22:35.537 full_node chia.full_node.full_node: WARNING  Wasn't able to add transaction with id ee481552aa3a5f7e55a75c93bf9288878f8abf13dcdc17aa0f0ae5a9ff7a83c9, status 3 error: Err.DOUBLE_SPEND
2021-05-19T17:22:35.538 full_node chia.full_node.full_node: WARNING  Wasn't able to add transaction with id 98f47675303c1c4dc098225ef8db44787acf3303d94312a7f81d1f9c04f2f77d, status 3 error: Err.DOUBLE_SPEND
2021-05-19T17:22:35.540 full_node chia.full_node.full_node: WARNING  Wasn't able to add transaction with id a5c67479e555763d599cc39acbb114c6cafc0b3f1d9d8269a266b15ea01b0451, status 3 error: Err.DOUBLE_SPEND
2021-05-19T17:22:35.542 full_node chia.full_node.full_node: WARNING  Wasn't able to add transaction with id 4744238a6c18f1b43b09247f918395e356331c0fe60ca5ddf92386aaeb0af371, status 3 error: Err.DOUBLE_SPEND
2021-05-19T17:22:35.543 full_node chia.full_node.full_node: WARNING  Wasn't able to add transaction with id eae2e07a83cddba7c78fac692c7c30dcd39129d73b2cee4c5cc4afc0fb5cbbc9, status 3 error: Err.DOUBLE_SPEND
2021-05-19T17:22:35.545 full_node chia.full_node.full_node: WARNING  Wasn't able to add transaction with id 6ea6ba5947cc7c3915aeef8a339a1b013936e3412f6f672910b5722061aaaca3, status 3 error: Err.DOUBLE_SPEND
2021-05-19T17:22:35.548 full_node chia.full_node.full_node: WARNING  Wasn't able to add transaction with id d7c23cc34eccf52da2b720964cc661b83c953ae75b2c382e559a561c4fa3472e, status 3 error: Err.DOUBLE_SPEND
2021-05-19T17:22:35.549 full_node chia.full_node.full_node: WARNING  Wasn't able to add transaction with id e3d427eb9a08cf7c63139bd2f80c0533de7bf586cb0972ea74bbe15f2a6a7a3c, status 3 error: Err.DOUBLE_SPEND
2021-05-19T17:22:35.551 full_node chia.full_node.full_node: WARNING  Wasn't able to add transaction with id 9107b6d36aaac635c845082a01908d1b634503456d9c544d12bee0ac7f0f3cce, status 3 error: Err.DOUBLE_SPEND
2021-05-19T17:22:35.552 full_node chia.full_node.full_node: WARNING  Wasn't able to add transaction with id 2d28215774738332fe983609a1d6355cc650267b49754600b1bcaa89f54c4d87, status 3 error: Err.DOUBLE_SPEND
2021-05-19T17:22:35.554 full_node chia.full_node.full_node: WARNING  Wasn't able to add transaction with id 29023fc312e37da0370c960e4bf2e7468fd16d48768e5bfa52cea4819f51bebc, status 3 error: Err.DOUBLE_SPEND
2021-05-19T17:22:35.555 full_node chia.full_node.full_node: WARNING  Wasn't able to add transaction with id b501c1ad9816156660ef8b06817753ffa39722c58f14541d93c47c0d8c3550d3, status 3 error: Err.DOUBLE_SPEND
2021-05-19T17:22:35.557 full_node chia.full_node.full_node: WARNING  Wasn't able to add transaction with id f718b05c45e3f6f6d96b21f50d8f7aeeffd1b951be62783b8645aaf77977c188, status 3 error: Err.DOUBLE_SPEND
2021-05-19T17:22:35.558 full_node chia.full_node.full_node: WARNING  Wasn't able to add transaction with id 9492f54f6e3e2771fa668d75792d59a9d534aa1f45d411455f75ceb26d6a333b, status 3 error: Err.DOUBLE_SPEND
2021-05-19T17:22:35.560 full_node chia.full_node.full_node: WARNING  Wasn't able to add transaction with id 83deeb55a01324adf0bf0b564af0ce9c4185e63c7c84aeb759ee8e95e176a4b8, status 3 error: Err.DOUBLE_SPEND
2021-05-19T17:22:44.046 full_node chia.full_node.full_node: WARNING  Wasn't able to add transaction with id c4fa0d03d5b1dfd3cd3533201c34974da3cac1136dc6dfaa8ab34e0a6fdfa505, status 3 error: Err.DOUBLE_SPEND
2021-05-19T17:22:44.050 full_node chia.full_node.full_node: WARNING  Wasn't able to add transaction with id 895f55c8d15e2c888496b4022fc47f86469092a812aba8aaa20f5355dbfd01be, status 3 error: Err.DOUBLE_SPEND
2021-05-19T17:22:44.052 full_node chia.full_node.full_node: WARNING  Wasn't able to add transaction with id 4fc39194f945d6af6201ee22909fc9e1183c0db85580a789ebf902b31797c09d, status 3 error: Err.DOUBLE_SPEND
2021-05-19T17:22:47.579 full_node chia.full_node.full_node: WARNING  Wasn't able to add transaction with id 27beb3de92fb88bd07f0c03ae32fe113df6c6f668045f69b9993d4667c812776, status 3 error: Err.DOUBLE_SPEND
2021-05-19T17:22:48.032 full_node chia.full_node.full_node: WARNING  Wasn't able to add transaction with id b32fb60f23ad136b8738f74cb69d0773d23d6b08290347a4b385e215ae9eea7b, status 3 error: Err.UNKNOWN_UNSPENT
2021-05-19T17:22:48.501 full_node chia.full_node.full_node: WARNING  Wasn't able to add transaction with id b3319fc55ad67a5ce40528af4ffdfec5097cfd40dea3ae76653873f4b331652e, status 3 error: Err.UNKNOWN_UNSPENT
2021-05-19T17:22:49.376 full_node chia.full_node.full_node: WARNING  Wasn't able to add transaction with id 1ecbc6c7b19e09112287929263e72eea8ee1c70d3128875a179c566acff1883e, status 3 error: Err.UNKNOWN_UNSPENT

- OS: Win 10
- OS Version/Flavor: 20H2
- CPU: Intel(R) Pentium(R) CPU G2030 @ 3.00GHz   3.00 GHz
- GUI v.1.1.5

А это продолжение время +8  18-30

2021-05-19T18:23:04.066 full_node full_node_server        : ERROR    Exception: Failed to fetch block 304175 from None, timed out <class 'ValueError'>, closing connection None. Traceback (most recent call last):
  File "chia\server\server.py", line 531, in api_call
  File "asyncio\tasks.py", line 414, in wait_for
  File "chia\server\server.py", line 528, in wrapped_coroutine
  File "chia\server\server.py", line 521, in wrapped_coroutine
  File "chia\full_node\full_node_api.py", line 104, in new_peak
  File "chia\full_node\full_node.py", line 361, in new_peak
  File "chia\full_node\full_node.py", line 310, in short_sync_backtrack
  File "chia\full_node\full_node.py", line 295, in short_sync_backtrack
ValueError: Failed to fetch block 304175 from None, timed out

2021-05-19T18:23:04.068 full_node full_node_server        : ERROR    Exception: Failed to fetch block 304175 from None, timed out, None. Traceback (most recent call last):
  File "chia\server\server.py", line 521, in wrapped_coroutine
  File "chia\full_node\full_node_api.py", line 104, in new_peak
  File "chia\full_node\full_node.py", line 361, in new_peak
  File "chia\full_node\full_node.py", line 310, in short_sync_backtrack
  File "chia\full_node\full_node.py", line 295, in short_sync_backtrack
ValueError: Failed to fetch block 304175 from None, timed out

2021-05-19T18:23:04.069 full_node full_node_server        : ERROR    Exception: Failed to fetch block 304175 from None, timed out <class 'ValueError'>, closing connection None. Traceback (most recent call last):
  File "chia\server\server.py", line 531, in api_call
  File "asyncio\tasks.py", line 414, in wait_for
  File "chia\server\server.py", line 528, in wrapped_coroutine
  File "chia\server\server.py", line 521, in wrapped_coroutine
  File "chia\full_node\full_node_api.py", line 104, in new_peak
  File "chia\full_node\full_node.py", line 361, in new_peak
  File "chia\full_node\full_node.py", line 310, in short_sync_backtrack
  File "chia\full_node\full_node.py", line 295, in short_sync_backtrack
ValueError: Failed to fetch block 304175 from None, timed out

2021-05-19T18:23:04.094 full_node full_node_server        : ERROR    Exception: Failed to fetch block 304171 from None, timed out, None. Traceback (most recent call last):
  File "chia\server\server.py", line 521, in wrapped_coroutine
  File "chia\full_node\full_node_api.py", line 104, in new_peak
  File "chia\full_node\full_node.py", line 361, in new_peak
  File "chia\full_node\full_node.py", line 310, in short_sync_backtrack
  File "chia\full_node\full_node.py", line 295, in short_sync_backtrack
ValueError: Failed to fetch block 304171 from None, timed out

2021-05-19T18:23:04.096 full_node full_node_server        : ERROR    Exception: Failed to fetch block 304171 from None, timed out <class 'ValueError'>, closing connection None. Traceback (most recent call last):
  File "chia\server\server.py", line 531, in api_call
  File "asyncio\tasks.py", line 414, in wait_for
  File "chia\server\server.py", line 528, in wrapped_coroutine
  File "chia\server\server.py", line 521, in wrapped_coroutine
  File "chia\full_node\full_node_api.py", line 104, in new_peak
  File "chia\full_node\full_node.py", line 361, in new_peak
  File "chia\full_node\full_node.py", line 310, in short_sync_backtrack
  File "chia\full_node\full_node.py", line 295, in short_sync_backtrack
ValueError: Failed to fetch block 304171 from None, timed out

**Comment by nmmmnu** [comment]
I think that is normal.

Someone try to do double spent.

**Comment by AlecseyM** [comment]
Спасибо!!!

**Comment by 42x42x42** [comment]
read other issues here, it already discussed, and close this one. reason - someone with an old  invalid version connected to you
