### ISSUE TITLE
[BUG] last changes broke plotter and farmer in v 1.1.5 and v 1.1.6

### ISSUE THREAD

**Issue by ramkom9** [Chia-Network/chia-blockchain#5501]
**Describe the bug**
Plotter and farmer wont load, see pictures. Full node and wallet ok fully sync.

**To Reproduce**
Run latest ChiaSetup-1.1.5.exe

**Expected behavior**
Update to latest ver. to fix previous bugs.

**Screenshots**
![chia1](https://user-images.githubusercontent.com/31524426/118794487-879e4f80-b891-11eb-885b-1ccc8617bfcc.jpg)

![chia2](https://user-images.githubusercontent.com/31524426/118794532-9258e480-b891-11eb-93b6-389eabf68da5.jpg)

**Desktop (please complete the following information):**

- OS: Windows 10 pro
- OS Version/Flavor: 20H2
- CPU: AMD Ryzen 5 3600

**Comment by room101-dev** [comment]
1.3 was the last working version of chia, I think they rushed to main-net for 5may2021, and then mis-managed the bugs after that, now its time for a timeout and triage
heads will roll

It's almost like they put together a team of solo mercenarys, but neglected to find a working software dev manager.

People like Richard Kiss are great for python the c++ guy for chia-pos is good, the chia-lisp is very nice, but the main-net was not ready for prime-time

Just like promising the pool-protocol for may17, what are these people thinking? Its like they have lots of public relations and influencers on youtube, but somebody forgot to budget sw dev management. :(

Given this past two weeks has been the ostriche approach to management & shoot the messenger, I suspect that the shit going to hit the fan, all us in the field can do is fall back to working code, and move ahead on our own, and fix the bugs ourselves, its clear that China now owns Chia.

The funniest thing of all is that all the HOFFMAN & BRAM videos talk of IPO, and being the next RedHat for crypto, hell why in the hell would any company hire the team that couldn't shoot right to do their sw support?  Reality is a bitch.

**Comment by ramkom9** [comment]
I've roll back to 1.1.3 now and have same issue. Someone do your job or it's end of Chia story.

**Comment by ramkom9** [comment]
./chia.exe start all
--- Logging error ---
Traceback (most recent call last):
  File "chia\daemon\server.py", line 138, in start
  File "asyncio\events.py", line 540, in add_signal_handler
NotImplementedError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "concurrent_log_handler\__init__.py", line 330, in emit
  File "concurrent_log_handler\__init__.py", line 418, in _do_lock
RuntimeError: Cannot acquire lock after 10 attempts
Call stack:
  File "chia\cmds\chia.py", line 81, in <module>
  File "chia\cmds\chia.py", line 77, in main
  File "click\core.py", line 829, in __call__
  File "click\core.py", line 782, in main
  File "click\core.py", line 1259, in invoke
  File "click\core.py", line 1066, in invoke
  File "click\core.py", line 610, in invoke
  File "click\decorators.py", line 21, in new_func
  File "chia\cmds\chia.py", line 60, in run_daemon_cmd
  File "asyncio\base_events.py", line 574, in run_until_complete
  File "asyncio\base_events.py", line 541, in run_forever
  File "asyncio\base_events.py", line 1786, in _run_once
  File "asyncio\events.py", line 88, in _run
  File "chia\daemon\server.py", line 964, in async_run_daemon
  File "chia\daemon\server.py", line 141, in start
  File "logging\__init__.py", line 1378, in info
  File "logging\__init__.py", line 1514, in _log
  File "logging\__init__.py", line 1524, in handle
  File "logging\__init__.py", line 1586, in callHandlers
  File "logging\__init__.py", line 894, in handle
  File "concurrent_log_handler\__init__.py", line 346, in emit
Message: 'Not implemented'
Arguments: ()
Daemon not started yet
Starting daemon
--- Logging error ---
Traceback (most recent call last):
  File "concurrent_log_handler\__init__.py", line 330, in emit
  File "concurrent_log_handler\__init__.py", line 418, in _do_lock
RuntimeError: Cannot acquire lock after 10 attempts
Call stack:
  File "chia\cmds\chia.py", line 81, in <module>
  File "chia\cmds\chia.py", line 77, in main
  File "click\core.py", line 829, in __call__
  File "click\core.py", line 782, in main
  File "click\core.py", line 1259, in invoke
  File "click\core.py", line 1066, in invoke
  File "click\core.py", line 610, in invoke
  File "click\decorators.py", line 21, in new_func
  File "chia\cmds\chia.py", line 60, in run_daemon_cmd
  File "asyncio\base_events.py", line 574, in run_until_complete
  File "asyncio\base_events.py", line 541, in run_forever
  File "asyncio\base_events.py", line 1786, in _run_once
  File "asyncio\events.py", line 88, in _run
  File "chia\daemon\server.py", line 964, in async_run_daemon
  File "chia\daemon\server.py", line 152, in start
  File "logging\__init__.py", line 1378, in info
  File "logging\__init__.py", line 1514, in _log
  File "logging\__init__.py", line 1524, in handle
  File "logging\__init__.py", line 1586, in callHandlers
  File "logging\__init__.py", line 894, in handle
  File "concurrent_log_handler\__init__.py", line 346, in emit
Message: 'Waiting Daemon WebSocketServer closure'
Arguments: ()
chia_harvester: started
chia_timelord_launcher: Traceback (most recent call last):
  File "chia\server\start_harvester.py", line 57, in <module>
  File "chia\server\start_harvester.py", line 52, in main
  File "chia\server\start_harvester.py", line 27, in service_kwargs_for_harvester
KeyError: 'constants'
[12584] Failed to execute script start_harvester

**Comment by ramkom9** [comment]
updated to v 1.1.6 no change still same

**Comment by ramkom9** [comment]
ok I did solved the problem. Seems that latest v 1.1.5 broke everything and upgrading to 1.1.6 wont help cos still will use broken code. BUT after uninstall and fresh install v 1.1.6 work and it load everything
