### ISSUE TITLE
[BUG] concurrent.futures._base.CancelledError causing sync issues (not synced)

### ISSUE THREAD

**Issue by thederpinator** [Chia-Network/chia-blockchain#5513]
**Describe the bug**
Currently running a full node on a plotter/farmer/harvester machine. Running the plotting on half of capacity to make sure there are no CPU related issues. Lately I have been experiencing a lot of concurrent.futures errors, but mostly from disconnecting nodes. I am uncertain if these are causing issues as well as I didn't catch them in time on my dashboard.

The issue is that every time the errors (as pasted below) occur, the full node goes out of sync. This lasts for about one minute since it's probably catching up again. I can see the exact timing of this in my dashboard (see screenshots).

As said, my CPU load is about 50%, so lack of CPU power shouldn't be the cause.

Error example 1:
2021-05-19T13:42:01.762 full_node chia.rpc.rpc_server     : WARNING  Error while handling message: Traceback (most recent call last):
  File "chia\rpc\rpc_server.py", line 81, in inner
  File "chia\rpc\full_node_rpc_api.py", line 120, in get_blockchain_state
  File "chia\rpc\full_node_rpc_api.py", line 295, in get_network_space
  File "chia\full_node\block_store.py", line 227, in get_block_record
  File "aiosqlite\cursor.py", line 69, in close
  File "aiosqlite\cursor.py", line 31, in _execute
  File "aiosqlite\core.py", line 129, in _execute
concurrent.futures._base.CancelledError

Error example2:
2021-05-19T13:45:43.334 wallet chia.rpc.rpc_server        : WARNING  Error while handling message: Traceback (most recent call last):
  File "chia\rpc\rpc_server.py", line 81, in inner
  File "chia\rpc\wallet_rpc_api.py", line 307, in get_wallets
  File "chia\wallet\wallet_state_manager.py", line 956, in get_all_wallet_info_entries
  File "chia\wallet\wallet_user_store.py", line 110, in get_all_wallet_info_entries
  File "aiosqlite\core.py", line 184, in execute
  File "aiosqlite\core.py", line 129, in _execute
concurrent.futures._base.CancelledError

**To Reproduce**

1. Setting debug to INFO level
2. Running a good accurate dashboard to catch the moment you go out of sync (using myself: https://github.com/retzkek/chiamon)
2. As soon as out of sync, check the debug log and search for 'futures' as recent as possible

**Expected behavior**
Not throwing errors and staying in sync

**Screenshots**
The gap shows where the error happened (about 2 minutes ago). You can also see it in the drop of peers connected.

![afbeelding](https://user-images.githubusercontent.com/36163123/118808496-de178800-b8a9-11eb-8d92-3f72348ac05b.png)

The actual error, followed by not adding signage points due to not being synced.

![afbeelding](https://user-images.githubusercontent.com/36163123/118808655-07381880-b8aa-11eb-9966-c24c7a336736.png)

**Desktop (please complete the following information):**

- OS: Windows 10 Pro
- OS Version/Flavor: Pro, version 20H2
- CPU: Intel(R) Core(TM) i7-10710U CPU @ 1.10GHz   1.61 GHz

**Additional context**
Also often seeing the concurrent futures error on disconnects of some nodes/peers, but unsure if this affects stability as well.

EDIT: before I get the question about the standard stuff:
- Forwarding port 8444 (verified)
- Connected to 80 peers usually
- Firewall allows traffic (verified)
- CPU running at half capacity
- Only using a third of my RAM (20 of 64GB)
- Internet connection stable (verified by running a ping script)

EDIT2: this is a fresh install of Chia 1.1.5 as before this weekend my Pi4 could no longer keep up.

**Comment by chelseadole** [comment]
I am having this issue as well

**Comment by thederpinator** [comment]
Adding to this the following errors. Please note that I was on the desktop remotely over the internet since my first post. Therefore I'm certain that my internet connection is fine. Also I'm running even less plots now than earlier (let them run out, not starting new ones).


2021-05-19T17:12:29.155 daemon __main__                   : ERROR    Unexpected exception trying to send to websocket: code = 1006 (connection closed abnormally [internal]), no reason Traceback (most recent call last):
  File "websockets\protocol.py", line 827, in transfer_data
  File "websockets\protocol.py", line 895, in read_message
  File "websockets\protocol.py", line 971, in read_data_frame
  File "websockets\protocol.py", line 1051, in read_frame
  File "websockets\framing.py", line 105, in read
  File "asyncio\streams.py", line 679, in readexactly
  File "asyncio\streams.py", line 473, in _wait_for_data
  File "asyncio\selector_events.py", line 814, in _read_ready__data_received
ConnectionResetError: [WinError 10054] De externe host heeft een verbinding verbroken

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "chia\daemon\server.py", line 187, in safe_handle
  File "websockets\protocol.py", line 555, in send
  File "websockets\protocol.py", line 803, in ensure_open
websockets.exceptions.ConnectionClosedError: code = 1006 (connection closed abnormally [internal]), no reason

2021-05-19T17:12:30.171 daemon __main__                   : ERROR    Unexpected exception trying to send to websocket: code = 1006 (connection closed abnormally [internal]), no reason Traceback (most recent call last):
  File "websockets\protocol.py", line 827, in transfer_data
  File "websockets\protocol.py", line 895, in read_message
  File "websockets\protocol.py", line 971, in read_data_frame
  File "websockets\protocol.py", line 1051, in read_frame
  File "websockets\framing.py", line 105, in read
  File "asyncio\streams.py", line 679, in readexactly
  File "asyncio\streams.py", line 473, in _wait_for_data
  File "asyncio\selector_events.py", line 814, in _read_ready__data_received
ConnectionResetError: [WinError 10054] De externe host heeft een verbinding verbroken

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "chia\daemon\server.py", line 187, in safe_handle
  File "websockets\protocol.py", line 555, in send
  File "websockets\protocol.py", line 803, in ensure_open
websockets.exceptions.ConnectionClosedError: code = 1006 (connection closed abnormally [internal]), no reason

2021-05-19T17:12:30.180 daemon __main__                   : ERROR    Unexpected exception trying to send to websocket: code = 1006 (connection closed abnormally [internal]), no reason Traceback (most recent call last):
  File "websockets\protocol.py", line 827, in transfer_data
  File "websockets\protocol.py", line 895, in read_message
  File "websockets\protocol.py", line 971, in read_data_frame
  File "websockets\protocol.py", line 1051, in read_frame
  File "websockets\framing.py", line 105, in read
  File "asyncio\streams.py", line 679, in readexactly
  File "asyncio\streams.py", line 473, in _wait_for_data
  File "asyncio\selector_events.py", line 814, in _read_ready__data_received
ConnectionResetError: [WinError 10054] De externe host heeft een verbinding verbroken

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "chia\daemon\server.py", line 187, in safe_handle
  File "websockets\protocol.py", line 555, in send
  File "websockets\protocol.py", line 803, in ensure_open
websockets.exceptions.ConnectionClosedError: code = 1006 (connection closed abnormally [internal]), no reason

This is how the sync stability looks like:

![afbeelding](https://user-images.githubusercontent.com/36163123/118838328-dfef4480-b8c5-11eb-84b1-e27f183747a8.png)

**Comment by alex-oden** [comment]
I don't think you will get here some useful answer. Developers are ignoring these / such issues to answer...

**Comment by thederpinator** [comment]
I have good hopes. They aren't answering every issue, but that doesn't mean they don't see them or work on them. I am certain they are trying to improve their product as good and fast as they can.

Update on my side with a new screenshot. Errors are still the same. I guess it helps to see it with a dashboard.

![Screenshot_20210520-070514_Chrome](https://user-images.githubusercontent.com/36163123/118922271-0353d700-b93a-11eb-898f-87eed012eae9.jpg)

**Comment by thederpinator** [comment]
Another update. I ruled out a network and CPU issue earlier, so I am now trying to figure out if the issue is app related or coming from outside. Therefore I have setup a VPN connection. Connections over 8444 are now filtered, but still forwarded. Guess what? It is running in sync now. Screenshot below. Building up the connections over VPN seems slower, but as long as it goes up, it should be good.

I can't prove what this means, but it should help the Chia devs in finding the cause. Will update after a while to see if it keeps running.

![afbeelding](https://user-images.githubusercontent.com/36163123/118954222-d87b7a00-b95d-11eb-8e39-873688f53e4a.png)

**Comment by thederpinator** [comment]
Challenges come in as clockwork now:

![afbeelding](https://user-images.githubusercontent.com/36163123/118956529-f8ac3880-b95f-11eb-8d3d-dc5e9106ac6c.png)

**Comment by bl0p3** [comment]
Having the same problem, was about to say the same about network attacks, looks like attacks on harvester nodes with corrupted data that slows the node. How do you filter the connections? Software and approved ips?

**Comment by thederpinator** [comment]
Update: after the 8 connections, no new connections were added, so I manually add more European-only connections. Still stable. Below the screenshot for the last 3 hours. Haven't been this stable since weeks.

Only a few explanations seem to be feasible: corrupted nodes, deliberate attacks or too many nodes might crash the app (unlikely).

![Uploading afbeelding.png…]()

**Comment by thederpinator** [comment]
> 
> 
> Having the same problem, was about to say the same about network attacks, looks like attacks on harvester nodes with corrupted data that slows the node. How do you filter the connections? Software and approved ips?

It's the VPN that does all the magic. Standard Norton 360 VPN

**Comment by thederpinator** [comment]
> I have installed this version of chia (beta build as I understand) and all working fine and stable with lot of connection from another peers. As I understand and see in logs - if there is some failure in connection it will not stop with sync and beginning with new connection but stays stable with existing peer connection
> 
> https://github.com/Chia-Network/chia-blockchain/actions/runs/853387813
> 
> Right now by me it working very good without any issues and Full node don't take a lot of power with CPU consumption. Already in Sync about 6 hours stable and FINALLY it sees my another local harvester...

Thanks a lot! I will try this out tomorrow!

**Comment by thederpinator** [comment]
So I 've shut down my plotting again and tried some new stuff.

The first thing I did was switch back to my non- VPN connection, but without port forwarding. I manually added the few connections I had on the VPN. Immediately the connection became more unstable (see screenshot). 

I turned port forwarding on: unstable as a day ago. Then I wanted to see if it was the amount of connections that caused the instability or increased chances for errors to occur so I manually added more peers with a script every 60 minutes. As you can see: I went out of sync more and more often until I'm fullylost now.

Again...says nothing about the cause, just that chances of a crash increase with a higher amount of peers. But I guess it has nothing to do with 'idle' connections as suggested in other posted issues. The added connections were fetched from the available active nodes on chia.keva.app.

![20210521_025925](https://user-images.githubusercontent.com/36163123/119067021-6fd5e100-b9e1-11eb-8dd5-13db55d23077.jpg)

**Comment by thederpinator** [comment]
Updating: it indeed seems to be dead peers that are connected at boot. Node stays in sync now, but really needs freshly added peers frequently. Often the top active peers seem to be full and can't be added, causing the node to go out of sync.
![Screenshot_20210521-065049_Chrome](https://user-images.githubusercontent.com/36163123/119084082-75432380-ba01-11eb-9611-425c76fcbbbc.jpg)

**Comment by thederpinator** [comment]
Fixed after 1.1.6
