### ISSUE TITLE
ValueError: MAC check failed

### ISSUE THREAD

**Issue by MontajnikRTA** [Chia-Network/chia-blockchain#5518]
Hello, I'm asking for help since nobody on githab and discord or telegram channels can help me with CHIA on Linux. Installation from scratch, Linux Mint kernel 5.4. I'm installing according to the instructions from the githab. I keep getting an error.
ValueError: MAC check failed

hyperx@hyperx-MS-7C56:~$ cd chia-blockchain
hyperx@hyperx-MS-7C56:~/chia-blockchain$ . ./activate
(venv) hyperx@hyperx-MS-7C56:~/chia-blockchain$ cd chia-blockchain-gui
(venv) hyperx@hyperx-MS-7C56:~/chia-blockchain/chia-blockchain-gui$ npm run electron &
[1] 11183
(venv) hyperx@hyperx-MS-7C56:~/chia-blockchain/chia-blockchain-gui$ 
chia-blockchain@ electron /home/hyperx/chia-blockchain/chia-blockchain-gui
electron .

/home/hyperx/chia-blockchain/app.asar.unpacked/daemon
false
Error loading config - using defaults
startUrl file:///home/hyperx/chia-blockchain/chia-blockchain-gui/build/renderer/index.html
/home/hyperx/chia-blockchain/app.asar.unpacked/daemon
false
/home/hyperx/chia-blockchain/app.asar.unpacked/daemon
false
Running python script
Script ../chia/daemon/server.py
child process success
(node:11202) electron: The default of contextIsolation is deprecated and will be changing from false to true in a future release of Electron.  See https://github.com/electron/electron/issues/23506 for more information
No cert
Chia directory /home/hyperx/.chia/mainnet
stderr: Traceback (most recent call last):
  File "/home/hyperx/chia-blockchain/venv/lib/python3.8/site-packages/keyrings/cryptfile/file_base.py", line 116, in get_password
    password = self.decrypt(password_encrypted, assoc).decode('utf-8')
  File "/home/hyperx/chia-blockchain/venv/lib/python3.8/site-packages/keyrings/cryptfile/cryptfile.py", line 130, in decrypt
    return cipher.decrypt_and_verify(data['data'], data['mac'])
  File "/home/hyperx/chia-blockchain/venv/lib/python3.8/site-packages/Crypto/Cipher/modegcm.py", line 567, in decrypt_and_verify
    self.verify(received_mac_tag)
  File "/home/hyperx/chia-blockchain/venv/lib/python3.8/site-packages/Crypto/Cipher/modegcm.py", line 508, in verify
    raise ValueError("MAC check failed")
ValueError: MAC check failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "../chia/daemon/server.py", line 982, in <module>
    main()
  File "../chia/daemon/server.py", line 978, in main
    return run_daemon(DEFAULT_ROOT_PATH)
  File "../chia/daemon/server.py", line 972, in run_daemon
    return asyncio.get_event_loop().run_until_complete(async_run_daemon(root_path))
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "../chia/daemon/server.py", line 936, in async_run_daemon
    chia_init(root_path)
  File "/home/hyperx/chia-blockchain/chia/cmds/init_funcs.py", line 316, in chia_init
    check_keys(root_path)
  File "/home/hyperx/chia-blockchain/chia/cmds/init_funcs.py", line 51, in check_keys
    all_sks = keychain.get_all_private_keys()
  File "/home/hyperx/chia-blockchain/chia/util/keychain.py", line 243, in get_all_private_keys
    pkent = self.getpk_and_entropy(self.getprivate_key_user(index))
  File "/home/hyperx/chia-blockchain/chia/util/keychain.py", line 142, in getpk_and_entropy
    read_str = keyring.get_password(self.getservice(), user)
  File "/home/hyperx/chia-blockchain/venv/lib/python3.8/site-packages/keyrings/cryptfile/file_base.py", line 119, in get_password
    password = self.decrypt(password_encrypted).decode('utf-8')
  File "/home/hyperx/chia-blockchain/venv/lib/python3.8/site-packages/keyrings/cryptfile/cryptfile.py", line 130, in decrypt
    return cipher.decrypt_and_verify(data['data'], data['mac'])
  File "/home/hyperx/chia-blockchain/venv/lib/python3.8/site-packages/Crypto/Cipher/modegcm.py", line 567, in decrypt_and_verify
    self.verify(received_mac_tag)
  File "/home/hyperx/chia-blockchain/venv/lib/python3.8/site-packages/Crypto/Cipher/modegcm.py", line 508, in verify
    raise ValueError("MAC check failed")
ValueError: MAC check failed
closing code: 1

hyperx@hyperx-MS-7C56:$ cat /.chia/mainnet/log/debug.log | grep -i 'error'
2021-05-19T00:11:51.217 wallet chia.rpc.rpc_server        : WARNING  Error while handling message: Traceback (most recent call last):
ValueError: MAC check failed
ValueError: MAC check failed
2021-05-19T00:11:51.217 wallet asyncio                    : ERROR    Unclosed client session
2021-05-19T00:12:02.370 wallet chia.rpc.rpc_server        : WARNING  Error while handling message: Traceback (most recent call last):
KeyError: 'fingerprint'
2021-05-19T00:12:29.417 wallet chia.rpc.rpc_server        : WARNING  Error while handling message: Traceback (most recent call last):
KeyError: 'fingerprint'
2021-05-19T00:12:50.539 wallet chia.rpc.wallet_rpc_api    : ERROR    error No backup on backup service
2021-05-19T00:15:26.847 full_node chia.full_node.full_node: ERROR    Error with syncing: <class 'RuntimeError'>Traceback (most recent call last):
RuntimeError: Weight proof did not arrive in time from peer: 118.166.66.223
2021-05-19T00:16:43.342 full_node chia.full_node.full_node: ERROR    Error with syncing: <class 'RuntimeError'>Traceback (most recent call last):
RuntimeError: Weight proof did not arrive in time from peer: 178.184.52.184
2021-05-19T00:24:46.525 full_node asyncio                 : ERROR    Unclosed client session
2021-05-19T00:24:46.870 full_node chia.full_node.full_node: ERROR    Error with syncing: <class 'RuntimeError'>Traceback (most recent call last):
RuntimeError: Weight proof did not arrive in time from peer: 119.27.170.114
2021-05-19T00:54:16.749 full_node chia.rpc.rpc_server     : WARNING  Error while handling message: Traceback (most recent call last):
    raise ValueError("Start client failed, or server is not set")
ValueError: Start client failed, or server is not set
2021-05-19T00:54:47.750 full_node chia.rpc.rpc_server     : WARNING  Error while handling message: Traceback (most recent call last):
    raise ValueError("Start client failed, or server is not set")

**Comment by lvpcguru** [comment]
That error makes me think one or more of the daemons are already running. try rebooting or stopping all?

**Comment by MontajnikRTA** [comment]
This problem was solved by copying from ~.chia/... app file to user/home/... Electron runs without error.

**Comment by lvpcguru** [comment]
Nice find, close the issue?

**Comment by Anankke** [comment]
same issue here, cannot connect to any peer node and not syncing. Manually adding doesn't work. Log shows 

`2021-05-20T20:18:34.786 full_node chia.rpc.rpc_server     : WARNING  Error while handling message: Traceback (most recent call last):
  File "/opt/chia-blockchain/chia/rpc/rpc_server.py", line 81, in inner
    res_object = await f(request_data)
  File "/opt/chia-blockchain/chia/rpc/rpc_server.py", line 161, in open_connection
    raise ValueError("Start client failed, or server is not set")
ValueError: Start client failed, or server is not set
`

Changing directory did not help.

**Comment by MontajnikRTA** [comment]
> Хорошая находка, закрыть вопрос?
Да проблема решена

**Comment by lvpcguru** [comment]
> 
> 
> This problem was solved by copying from ~.chia/... app file to user/home/... Electron runs without error.

please close the issue

**Comment by jgeurts** [comment]
I get the same error when installing on Ubuntu 20.04.2 LTS:

```sh
~$ sudo apt-get update && sudo apt-get upgrade -y
~$ sudo apt-get install -y git curl net-tools
~$ # Install node.js v12 or later
~$ curl -fsSL https://deb.nodesource.com/setup_12.x | sudo -E bash -
~$ sudo apt-get install -y nodejs
~$ # Clone latest copy of chia repo
~$ git clone https://github.com/Chia-Network/chia-blockchain.git -b latest --recurse-submodules
~$ cd chia-blockchain
~/chia-blockchain$ # Comment out npm from install.sh. See https://github.com/Chia-Network/chia-blockchain/pull/3132
~/chia-blockchain$ sh install.sh
~/chia-blockchain$ . ./activate
~/chia-blockchain$ chia init
```

Output:
```
Chia directory /home/chiahut/.chia/mainnet
Traceback (most recent call last):
  File "/home/chiahut/chia-blockchain/venv/lib/python3.8/site-packages/keyrings/cryptfile/file_base.py", line 116, in get_password
    password = self.decrypt(password_encrypted, assoc).decode('utf-8')
  File "/home/chiahut/chia-blockchain/venv/lib/python3.8/site-packages/keyrings/cryptfile/cryptfile.py", line 130, in decrypt
    return cipher.decrypt_and_verify(data['data'], data['mac'])
  File "/home/chiahut/chia-blockchain/venv/lib/python3.8/site-packages/Crypto/Cipher/_mode_gcm.py", line 567, in decrypt_and_verify
    self.verify(received_mac_tag)
  File "/home/chiahut/chia-blockchain/venv/lib/python3.8/site-packages/Crypto/Cipher/_mode_gcm.py", line 508, in verify
    raise ValueError("MAC check failed")
ValueError: MAC check failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/chiahut/chia-blockchain/venv/bin/chia", line 33, in <module>
    sys.exit(load_entry_point('chia-blockchain', 'console_scripts', 'chia')())
  File "/home/chiahut/chia-blockchain/chia/cmds/chia.py", line 77, in main
    cli()  # pylint: disable=no-value-for-parameter
  File "/home/chiahut/chia-blockchain/venv/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/chiahut/chia-blockchain/venv/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/chiahut/chia-blockchain/venv/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/chiahut/chia-blockchain/venv/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/chiahut/chia-blockchain/venv/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/chiahut/chia-blockchain/venv/lib/python3.8/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/chiahut/chia-blockchain/chia/cmds/init.py", line 29, in init_cmd
    init(Path(create_certs) if create_certs is not None else None, ctx.obj["root_path"])
  File "/home/chiahut/chia-blockchain/chia/cmds/init_funcs.py", line 249, in init
    return chia_init(root_path)
  File "/home/chiahut/chia-blockchain/chia/cmds/init_funcs.py", line 323, in chia_init
    check_keys(root_path)
  File "/home/chiahut/chia-blockchain/chia/cmds/init_funcs.py", line 51, in check_keys
    all_sks = keychain.get_all_private_keys()
  File "/home/chiahut/chia-blockchain/chia/util/keychain.py", line 243, in get_all_private_keys
    pkent = self._get_pk_and_entropy(self._get_private_key_user(index))
  File "/home/chiahut/chia-blockchain/chia/util/keychain.py", line 142, in _get_pk_and_entropy
    read_str = keyring.get_password(self._get_service(), user)
  File "/home/chiahut/chia-blockchain/venv/lib/python3.8/site-packages/keyrings/cryptfile/file_base.py", line 119, in get_password
    password = self.decrypt(password_encrypted).decode('utf-8')
  File "/home/chiahut/chia-blockchain/venv/lib/python3.8/site-packages/keyrings/cryptfile/cryptfile.py", line 130, in decrypt
    return cipher.decrypt_and_verify(data['data'], data['mac'])
  File "/home/chiahut/chia-blockchain/venv/lib/python3.8/site-packages/Crypto/Cipher/_mode_gcm.py", line 567, in decrypt_and_verify
    self.verify(received_mac_tag)
  File "/home/chiahut/chia-blockchain/venv/lib/python3.8/site-packages/Crypto/Cipher/_mode_gcm.py", line 508, in verify
    raise ValueError("MAC check failed")
ValueError: MAC check failed
```

**Comment by cujo0072** [comment]
running the install.sh again worked for me.

**Comment by MontajnikRTA** [comment]
After a few weeks of running my PC, I had to do a reboot. The error appeared again. This time, I copied the .chia/mainnet/daemon folder to chia-blockchain/chia/daemon. I also deleted the entire db database. After running the wallet and still the error repeated. After that I killed all the processes. I ran . ./activate ran chia start node - everything ran without errors, then I ran npm run electron & - and everything worked fine. But I have to wait for the synchronization of the base and the wallet again, I am just wasting time

Translated with www.DeepL.com/Translator (free version)

**Comment by MontajnikRTA** [comment]
Synchronization can not go well, stops and hangs in place


hyperx@hyperx-MS-7C56:~$ cd chia-blockchain
hyperx@hyperx-MS-7C56:~/chia-blockchain$ . ./activate
(venv) hyperx@hyperx-MS-7C56:~/chia-blockchain$ chia start node
Daemon not started yet
Starting daemon
chia_full_node: started
(venv) hyperx@hyperx-MS-7C56:~/chia-blockchain$ Traceback (most recent call last):
  File "/home/hyperx/chia-blockchain/venv/bin/chia_full_node", line 8, in <module>
    sys.exit(main())
  File "/home/hyperx/chia-blockchain/venv/lib/python3.9/site-packages/chia/server/start_full_node.py", line 60, in main
    return run_service(**kwargs)
  File "/home/hyperx/chia-blockchain/venv/lib/python3.9/site-packages/chia/server/start_service.py", line 226, in run_service
    return asyncio.run(async_run_service(*args, **kwargs))
  File "/usr/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/home/hyperx/chia-blockchain/venv/lib/python3.9/site-packages/chia/server/start_service.py", line 220, in async_run_service
    return await service.run()
  File "/home/hyperx/chia-blockchain/venv/lib/python3.9/site-packages/chia/server/start_service.py", line 160, in run
    await self.start()
  File "/home/hyperx/chia-blockchain/venv/lib/python3.9/site-packages/chia/server/start_service.py", line 128, in start
    await self._node._start(**kwargs)
  File "/home/hyperx/chia-blockchain/venv/lib/python3.9/site-packages/chia/full_node/full_node.py", line 127, in _start
    self.blockchain = await Blockchain.create(self.coin_store, self.block_store, self.constants)
  File "/home/hyperx/chia-blockchain/venv/lib/python3.9/site-packages/chia/consensus/blockchain.py", line 113, in create
    await self._load_chain_from_store()
  File "/home/hyperx/chia-blockchain/venv/lib/python3.9/site-packages/chia/consensus/blockchain.py", line 125, in _load_chain_from_store
    height_to_hash, sub_epoch_summaries = await self.block_store.get_peak_height_dicts()
  File "/home/hyperx/chia-blockchain/venv/lib/python3.9/site-packages/chia/full_node/block_store.py", line 315, in get_peak_height_dicts
    rows = await cursor.fetchall()
  File "/home/hyperx/chia-blockchain/venv/lib/python3.9/site-packages/aiosqlite/cursor.py", line 65, in fetchall
    return await self._execute(self._cursor.fetchall)
  File "/home/hyperx/chia-blockchain/venv/lib/python3.9/site-packages/aiosqlite/cursor.py", line 31, in _execute
    return await self._conn._execute(fn, *args, **kwargs)
  File "/home/hyperx/chia-blockchain/venv/lib/python3.9/site-packages/aiosqlite/core.py", line 129, in _execute
    return await future
  File "/home/hyperx/chia-blockchain/venv/lib/python3.9/site-packages/aiosqlite/core.py", line 102, in run
    result = function()
sqlite3.DatabaseError: database disk image is malformed

(venv) hyperx@hyperx-MS-7C56:~/chia-blockchain$ chia start node
chia_full_node: Already running, use `-r` to restart
(venv) hyperx@hyperx-MS-7C56:~/chia-blockchain$ cd chia-blockchain-пгш
bash: cd: chia-blockchain-пгш: Нет такого файла или каталога
(venv) hyperx@hyperx-MS-7C56:~/chia-blockchain$ cd chia-blockchain-gui
(venv) hyperx@hyperx-MS-7C56:~/chia-blockchain/chia-blockchain-gui$ npm run electron &
[1] 367882
(venv) hyperx@hyperx-MS-7C56:~/chia-blockchain/chia-blockchain-gui$ 
> electron
> electron .

/home/hyperx/chia-blockchain/app.asar.unpacked/daemon
false
startUrl file:///home/hyperx/chia-blockchain/chia-blockchain-gui/build/renderer/index.html
/home/hyperx/chia-blockchain/app.asar.unpacked/daemon
false
/home/hyperx/chia-blockchain/app.asar.unpacked/daemon
false
Running python script
Script ../chia/daemon/server.py
child process success
(node:367901) electron: The default of contextIsolation is deprecated and will be changing from false to true in a future release of Electron.  See https://github.com/electron/electron/issues/23506 for more information
No cert
Have cert
daemon: already launching
closing code: 0

(venv) hyperx@hyperx-MS-7C56:~/chia-blockchain/chia-blockchain-gui$ Exception ignored in: <module 'threading' from '/usr/lib/python3.9/threading.py'>
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 1428, in _shutdown
    lock.acquire()
  File "/home/hyperx/chia-blockchain/venv/lib/python3.9/site-packages/chia/server/start_service.py", line 172, in _accept_signal
    self.stop()
  File "/home/hyperx/chia-blockchain/venv/lib/python3.9/site-packages/chia/server/start_service.py", line 181, in stop
    self._server.close_all()
  File "/home/hyperx/chia-blockchain/venv/lib/python3.9/site-packages/chia/server/server.py", line 637, in close_all
    self.connection_close_task = asyncio.create_task(self.close_all_connections())
  File "/usr/lib/python3.9/asyncio/tasks.py", line 360, in create_task
    loop = events.get_running_loop()
RuntimeError: no running event loop
sys:1: RuntimeWarning: coroutine 'ChiaServer.close_all_connections' was never awaited
RuntimeWarning: Enable tracemalloc to get the object allocation traceback

[1]+  Завершён        npm run electron
(venv) hyperx@hyperx-MS-7C56:~/chia-blockchain/chia-blockchain-gui$
