### ISSUE TITLE
[BUG] New Syncing error 1.1.5

### ISSUE THREAD

**Issue by vladymyrkulinich** [Chia-Network/chia-blockchain#5527]
Have some syncing issue in my log, during last 2 days I was not able to sync v1.1.5 (couple days ago at the same version all was ok):

2021-05-18T20:33:54.701 full_node full_node_server        : ERROR    Exception:  <class 'concurrent.futures._base.CancelledError'>, closing connection None. Traceback (most recent call last):
  File "chia\server\server.py", line 531, in api_call
  File "asyncio\tasks.py", line 435, in wait_for
concurrent.futures._base.CancelledError

2021-05-18T20:40:46.814 full_node chia.full_node.full_node: ERROR    Error with syncing: <class 'RuntimeError'>Traceback (most recent call last):
  File "chia\full_node\full_node.py", line 628, in _sync
RuntimeError: Weight proof did not arrive in time from peer: 94.16.133.30

2021-05-18T20:50:16.188 full_node full_node_server        : WARNING  Banning 220.126.20.145 for 600 seconds
2021-05-18T20:50:16.222 full_node chia.full_node.full_node: ERROR    Error with syncing: <class 'RuntimeError'>Traceback (most recent call last):
  File "chia\full_node\full_node.py", line 628, in _sync
RuntimeError: Weight proof did not arrive in time from peer: 220.126.20.145

2021-05-18T21:14:34.798 full_node chia.full_node.full_node: WARNING  Invalid response for slot None
2021-05-18T21:17:31.383 full_node full_node_server        : WARNING  Banning 99.61.21.150 for 600 seconds
2021-05-18T21:17:31.384 full_node chia.full_node.full_node: ERROR    Error with syncing: <class 'RuntimeError'>Traceback (most recent call last):
  File "chia\full_node\full_node.py", line 628, in _sync
RuntimeError: Weight proof did not arrive in time from peer: 99.61.21.150

OS: [Windows]
OS Version/Flavor: [10Pro]
CPU: [I-7]

**Comment by Stanley899** [comment]
Indeed!  not synced intermittently v1.1.5
Windows Pro 10

**Comment by davidbro-in** [comment]
Same issue here 👎

**Comment by firesh** [comment]
Can not sync start block #305213

**Comment by kubalatv** [comment]
I have 3 harvesters and main computer.
Now only one harvester is Synced, but rest of computers and main computer is red: Not Synced.
I have above 40 TB and I dont kwnow .... for what purpose... better way is sold HDD's by 2x proce and wait for stable chia apps?
Now it's waste of power, waste odf time ... f.. y... chia!

**Comment by SirVladislav** [comment]
> I have 3 harvesters and main computer.
> Now only one harvester is Synced, but rest of computers and main computer is red: Not Synced.
> I have above 40 TB and I dont kwnow .... for what purpose... better way is sold HDD's by 2x proce and wait for stable chia apps?
> Now it's waste of power, waste odf time ... green coin? -> you must be joking :D !
> 
> harvester 1: Not Synced (main) 40 TB
> harvester 2: Syncing 237952/296148 (the same LAN; SSD wrote 12 TB but chia not synced yet LOL LOL :D :D )
> harvester 3: **Synced** -but it only plots and send via LAN to main harvester 1
> harvester 4: Not Synced (dedicated server ovh)
> 
> Maybe one wallet can by synced? But how to disable that on other machines?
> 
> Edited:
> after 1 hour:
> harvester 1: **Synced (main)**
> harvester 2: Syncing ....
> harvester 3: **Synced**
> harvester 4: Not Synced

same problem for 3 harvester 
only 2 of them can sync

**Comment by alex-oden** [comment]
Hi, I have installed this version of chia (beta build as I understand) and all working fine and stable with lot of connection from another peers. As I understand and see in logs - if there is some failure in connection it will not stop with sync and beginning with new connection but stays stable with existing peer connection

https://github.com/Chia-Network/chia-blockchain/actions/runs/853387813

Right now by me it working very good without any issues and Full node don't take a lot of power with CPU consumption. Already in Sync about 6 hours stable and FINALLY it sees my another local harvester...

(Also if you have not opened or forward on your router port 8444) You need to do that - here some help
https://portforward.com/

**Comment by vladymyrkulinich** [comment]
Fixed after new version 1.1.6 was installed
