### ISSUE TITLE
[BUG] Failed to fetch block

### ISSUE THREAD

**Issue by Sitnnov** [Chia-Network/chia-blockchain#5554]
2021-05-19T20:51:39.089 full_node full_node_server        : ERROR    Exception: Failed to fetch block 305655 from None, timed out, None. Traceback (most recent call last):
  File "chia\server\server.py", line 521, in wrapped_coroutine
  File "chia\full_node\full_node_api.py", line 104, in new_peak
  File "chia\full_node\full_node.py", line 361, in new_peak
  File "chia\full_node\full_node.py", line 310, in short_sync_backtrack
  File "chia\full_node\full_node.py", line 295, in short_sync_backtrack
ValueError: Failed to fetch block 305655 from None, timed out

2021-05-19T20:51:39.090 full_node full_node_server        : ERROR    Exception: Failed to fetch block 305655 from None, timed out <class 'ValueError'>, closing connection None. Traceback (most recent call last):
  File "chia\server\server.py", line 531, in api_call
  File "asyncio\tasks.py", line 414, in wait_for
  File "chia\server\server.py", line 528, in wrapped_coroutine
  File "chia\server\server.py", line 521, in wrapped_coroutine
  File "chia\full_node\full_node_api.py", line 104, in new_peak
  File "chia\full_node\full_node.py", line 361, in new_peak
  File "chia\full_node\full_node.py", line 310, in short_sync_backtrack
  File "chia\full_node\full_node.py", line 295, in short_sync_backtrack
ValueError: Failed to fetch block 305655 from None, timed out

- OS: Windows
- OS -chia 1.1.5
- CPU: amd 3500
- 
please tell me is this a bug or part of the process? i lost the block?

**Comment by Sitnnov** [comment]
2021-05-20T21:51:16.087 full_node full_node_server        : ERROR    Exception: Failed to fetch block 310561 from None, timed out, None. Traceback (most recent call last):
  File "chia\server\server.py", line 521, in wrapped_coroutine
  File "chia\full_node\full_node_api.py", line 104, in new_peak
  File "chia\full_node\full_node.py", line 361, in new_peak
  File "chia\full_node\full_node.py", line 310, in short_sync_backtrack
  File "chia\full_node\full_node.py", line 295, in short_sync_backtrack
ValueError: Failed to fetch block 310561 from None, timed out

2021-05-20T21:51:16.088 full_node full_node_server        : ERROR    Exception: Failed to fetch block 310561 from None, timed out <class 'ValueError'>, closing connection None. Traceback (most recent call last):
  File "chia\server\server.py", line 531, in api_call
  File "asyncio\tasks.py", line 414, in wait_for
  File "chia\server\server.py", line 528, in wrapped_coroutine
  File "chia\server\server.py", line 521, in wrapped_coroutine
  File "chia\full_node\full_node_api.py", line 104, in new_peak
  File "chia\full_node\full_node.py", line 361, in new_peak
  File "chia\full_node\full_node.py", line 310, in short_sync_backtrack
  File "chia\full_node\full_node.py", line 295, in short_sync_backtrack
ValueError: Failed to fetch block 310561 from None, timed out

**Comment by shaunlourdes84** [comment]
2021-05-22T18:42:05.852 full_node full_node_server        : ERROR    Exception: Failed to fetch block 318972 from {'host': '116.235.217.135', 'port': 8444}, timed out <class 'ValueError'>, closing connection {'host': '116.235.217.135', 'port': 8444}. Traceback (most recent call last):
  File "chia\server\server.py", line 536, in api_call
  File "asyncio\tasks.py", line 414, in wait_for
  File "chia\server\server.py", line 533, in wrapped_coroutine
  File "chia\server\server.py", line 526, in wrapped_coroutine
  File "chia\full_node\full_node_api.py", line 104, in new_peak
  File "chia\full_node\full_node.py", line 373, in new_peak
  File "chia\full_node\full_node.py", line 322, in short_sync_backtrack
  File "chia\full_node\full_node.py", line 307, in short_sync_backtrack
ValueError: Failed to fetch block 318972 from {'host': '116.235.217.135', 'port': 8444}, timed out

**Comment by dennis1511** [comment]
Did you solve the issue?
