### ISSUE TITLE
No Syn since Block 305286

### ISSUE THREAD

**Issue by WestfalenerAgrarvideos** [Chia-Network/chia-blockchain#5556]
![Chia](https://user-images.githubusercontent.com/57158350/118880242-eeebec00-b8f1-11eb-993e-3b0cfe44094d.PNG)

Since 17.58 German Time my Chia is not Syn anymore. I did have start it new for so many Times maybe someone can help me.

Some Parts from the Log

2021-05-19T22:35:18.648 wallet wallet_server              : INFO     Cannot connect to host 127.0.0.1:8444 ssl:<ssl.SSLContext object at 0x000001FF5BCF2BA8> [Connect call failed ('127.0.0.1', 8444)]
2021-05-19T22:35:19.836 farmer farmer                     : INFO     Reconnecting to peer {'host': '127.0.0.1', 'port': 8444}
2021-05-19T22:35:20.948 full_node chia.server.upnp        : INFO     UPnP failed. This is not required to run chia, but it allows incoming connections from other peers.
2021-05-19T22:35:21.084 full_node full_node_server        : INFO     Started listening on port: 8444
2021-05-19T22:35:21.085 full_node full_node               : INFO     Started full_node service on network_id: mainnet
2021-05-19T22:35:21.137 daemon __main__                   : INFO     Register service {'service': 'chia_full_node'}
2021-05-19T22:35:21.138 daemon __main__                   : INFO     registered for service chia_full_node
2021-05-19T22:35:21.138 daemon __main__                   : INFO     {'success': True}
2021-05-19T22:35:21.649 wallet wallet                     : INFO     Reconnecting to peer {'host': '127.0.0.1', 'port': 8444}
2021-05-19T22:35:22.032 farmer farmer_server              : INFO     -> handshake to peer 127.0.0.1 46087f9ff2dc47054f666b7da1f849ae8789461caf018ca91b36d7d82d575928
2021-05-19T22:35:22.034 wallet wallet_server              : INFO     -> handshake to peer 127.0.0.1 46087f9ff2dc47054f666b7da1f849ae8789461caf018ca91b36d7d82d575928
2021-05-19T22:35:22.034 full_node full_node_server        : INFO     -> handshake to peer 127.0.0.1 da38dd67a5ecaf854a2d8d92d3797c083c3eabd1e5f073dfbe065908c5410ce2
2021-05-19T22:35:23.049 full_node full_node_server        : INFO     -> handshake to peer 127.0.0.1 247b1d12d8dc707da1adfe5307d8713c9d4523cd7ae9452c8e26f51e73fa40af
2021-05-19T22:35:23.050 wallet wallet_server              : INFO     Connected with full_node {'host': '127.0.0.1', 'port': 8444}
2021-05-19T22:35:23.050 full_node full_node_server        : INFO     -> new_peak_wallet to peer 127.0.0.1 247b1d12d8dc707da1adfe5307d8713c9d4523cd7ae9452c8e26f51e73fa40af
2021-05-19T22:35:23.051 wallet chia.wallet.wallet_node    : INFO     self._close
2021-05-19T22:35:23.051 wallet chia.wallet.wallet_node    : INFO     self._await_closed
2021-05-19T22:35:23.052 wallet wallet_server              : INFO     <- new_peak_wallet from peer 46087f9ff2dc47054f666b7da1f849ae8789461caf018ca91b36d7d82d575928 127.0.0.1
2021-05-19T22:35:22.034 farmer farmer_server              : INFO     Connected with full_node {'host': '127.0.0.1', 'port': 8444}
2021-05-19T22:35:24.105 full_node full_node_server        : INFO     Connection closed: 127.0.0.1, node id: 247b1d12d8dc707da1adfe5307d8713c9d4523cd7ae9452c8e26f51e73fa40af
2021-05-19T22:35:24.106 full_node chia.full_node.full_node: INFO     peer disconnected {'host': '127.0.0.1', 'port': 8449}
2021-05-19T22:35:24.105 wallet wallet_server              : INFO     Connection closed: 127.0.0.1, node id: 46087f9ff2dc47054f666b7da1f849ae8789461caf018ca91b36d7d82d575928
2021-05-19T22:35:25.140 wallet chia.wallet.wallet_blockchain: INFO     Started 14 processes for block validation
2021-05-19T22:35:26.225 wallet wallet                     : INFO     Reconnecting to peer {'host': '127.0.0.1', 'port': 8444}
2021-05-19T22:35:26.236 wallet wallet_server              : INFO     -> handshake to peer 127.0.0.1 46087f9ff2dc47054f666b7da1f849ae8789461caf018ca91b36d7d82d575928
2021-05-19T22:35:26.236 wallet wallet_server              : INFO     Connected with full_node {'host': '127.0.0.1', 'port': 8444}
2021-05-19T22:35:26.871 wallet chia.wallet.wallet_node    : INFO     Will not attempt to connect to other nodes, already connected to {'host': 'localhost', 'port': 8444}
2021-05-19T22:35:26.871 wallet chia.wallet.wallet_node    : INFO     Loop start in sync job
2021-05-19T22:35:26.978 wallet chia.wallet.wallet_state_manager: INFO     Confirmed balance amount is 100
2021-05-19T22:35:26.979 wallet chia.wallet.wallet_state_manager: INFO     Confirmed balance amount is 100
2021-05-19T22:35:26.982 wallet chia.wallet.wallet         : INFO     coins is not None {Coin(parent_coin_info=<bytes32: b4fb2c9b93ae63f751c4538d93a7351991cbe48192a64678707faccc33a795ce>, puzzle_hash=<bytes32: 33c4036acbede928756fa26248daaf7a2257d5b4135404c6b0842777d9d85996>, amount=100)}
2021-05-19T22:35:26.983 wallet chia.wallet.wallet         : INFO     coin from coins {'amount': 100,
 'parent_coin_info': '0xb4fb2c9b93ae63f751c4538d93a7351991cbe48192a64678707faccc33a795ce',
 'puzzle_hash': '0x33c4036acbede928756fa26248daaf7a2257d5b4135404c6b0842777d9d85996'}
2021-05-19T22:35:26.994 wallet chia.wallet.wallet         : INFO     Spends is [CoinSolution(coin=Coin(parent_coin_info=<bytes32: b4fb2c9b93ae63f751c4538d93a7351991cbe48192a64678707faccc33a795ce>, puzzle_hash=<bytes32: 33c4036acbede928756fa26248daaf7a2257d5b4135404c6b0842777d9d85996>, amount=100), puzzle_reveal=SerializedProgram(ff02ffff01ff02ffff01ff02ffff03ff0bffff01ff02ffff03ffff09ff05ffff1dff0bffff1effff0bff0bffff02ff06ffff04ff02ffff04ff17ff8080808080808080ffff01ff02ff17ff2f80ffff01ff088080ff0180ffff01ff04ffff04ff04ffff04ff05ffff04ffff02ff06ffff04ff02ffff04ff17ff80808080ff80808080ffff02ff17ff2f808080ff0180ffff04ffff01ff32ff02ffff03ffff07ff0580ffff01ff0bffff0102ffff02ff06ffff04ff02ffff04ff09ff80808080ffff02ff06ffff04ff02ffff04ff0dff8080808080ffff01ff0bffff0101ff058080ff0180ff018080ffff04ffff01b0a756c9efb2b92ead6817dd28cc938177887cdec32cb1bd9e5b9f8b5c2989ce327923be57f8451daae051f30ba5e4e560ff018080), solution=SerializedProgram(ff80ffff01ffff33ffa033c4036acbede928756fa26248daaf7a2257d5b4135404c6b0842777d9d85996ff6480ffff3cffa00a874586b456f2e809a18933d40f75bdeab08d1decd0954ac1bf0e31d35b835b8080ff8080))]
2021-05-19T22:35:26.995 wallet chia.wallet.wallet         : INFO     About to sign a transaction
2021-05-19T22:35:26.999 wallet chia.wallet.wallet         : INFO     Cost of a single tx for standard wallet: 8480552
2021-05-19T22:35:26.236 full_node full_node_server        : INFO     -> handshake to peer 127.0.0.1 247b1d12d8dc707da1adfe5307d8713c9d4523cd7ae9452c8e26f51e73fa40af
2021-05-19T22:35:27.244 full_node full_node_server        : INFO     -> new_peak_wallet to peer 127.0.0.1 247b1d12d8dc707da1adfe5307d8713c9d4523cd7ae9452c8e26f51e73fa40af
2021-05-19T22:35:27.244 wallet wallet_server              : INFO     <- new_peak_wallet from peer 46087f9ff2dc47054f666b7da1f849ae8789461caf018ca91b36d7d82d575928 127.0.0.1
2021-05-19T22:35:37.256 wallet chia.wallet.wallet_state_manager: INFO     Confirmed balance amount is 100
2021-05-19T22:35:37.256 wallet chia.wallet.wallet_state_manager: INFO     Confirmed balance amount is 100
2021-05-19T22:35:56.098 full_node full_node_server        : INFO     -> handshake to peer introducer-eu.chia.net 3c1a1e3fb2f4cb3e14829f84395c45856c8215bc2e602b1fa2db275ddf731174
2021-05-19T22:35:56.135 full_node full_node_server        : INFO     Connected with introducer {'host': 'introducer-eu.chia.net', 'port': 8444}
2021-05-19T22:35:56.135 full_node full_node_server        : INFO     -> request_peers_introducer to peer introducer-eu.chia.net 3c1a1e3fb2f4cb3e14829f84395c45856c8215bc2e602b1fa2db275ddf731174
2021-05-19T22:35:56.204 full_node full_node_server        : INFO     <- respond_peers_introducer from peer 3c1a1e3fb2f4cb3e14829f84395c45856c8215bc2e602b1fa2db275ddf731174 introducer-eu.chia.net
2021-05-19T22:35:56.251 full_node full_node_server        : INFO     Connection closed: introducer-eu.chia.net, node id: 3c1a1e3fb2f4cb3e14829f84395c45856c8215bc2e602b1fa2db275ddf731174
2021-05-19T22:35:56.266 full_node chia.full_node.full_node: INFO     peer disconnected {'host': '2a05:d01c:e44:d701:ca21:417e:7305:31b0', 'port': 8444}
2021-05-19T22:35:56.266 full_node full_node_server        : ERROR    Exception:  <class 'concurrent.futures._base.CancelledError'>, closing connection {'host': '2a05:d01c:e44:d701:ca21:417e:7305:31b0', 'port': 8444}. Traceback (most recent call last):
  File "chia\server\server.py", line 531, in api_call
  File "asyncio\tasks.py", line 435, in wait_for
concurrent.futures._base.CancelledError

2021-05-19T22:36:10.576 full_node full_node_server        : INFO     Cannot connect to host 212.34.225.118:8444 ssl:<ssl.SSLContext object at 0x000002224DB5D908> [Connect call failed ('212.34.225.118', 8444)]
2021-05-19T22:36:33.617 full_node full_node_server        : INFO     Cannot connect to host 218.157.83.208:8444 ssl:<ssl.SSLContext object at 0x000002224EBA1F98> [Connect call failed ('218.157.83.208', 8444)]

End Sorry for my bad English.

**Comment by alex-oden** [comment]
Hello, for your sync problem - I think you need to open on your router port 8444 (Forward a port for connection). With ip of your main pc. But first you need to change dchp to static ip on your pc - find in google how to do that on Windows 10.

1. Windows 10 how to change DCHP to Static IP
2. Forward port on router (with your static IP)

**Comment by Trustmeimtheninja** [comment]
Alex-oden has the right idea. I think this is your problem also. Checking online to see if your port if open doesn't always work. You can use the free tool from https://portforward.com/ to check if the port is open or not. I've used this for a lot of games in the past. Just do the trial of it (there's no charge, and the features that will be needed are included in the trial, there's also no limit to how long you can use the trial)

**Comment by bandit8623** [comment]
i have over 100 connection to the network and im having the same problem.  it wont catch up.  i also have gig internet.. was working yesterday. ive restarted as well

**Comment by Trustmeimtheninja** [comment]
> i have over 100 connection to the network and im having the same problem. it wont catch up. i also have gig internet.. was working yesterday. ive restarted as well

For some reason, I believe I read that the max peers that a node can have is 60. Are you running everything from the CLI/CMD or the GUI? What does your log file say for "WARNING"s?

**Comment by bandit8623** [comment]
> > i have over 100 connection to the network and im having the same problem. it wont catch up. i also have gig internet.. was working yesterday. ive restarted as well
> 
> For some reason, I believe I read that the max peers that a node can have is 60. Are you running everything from the CLI/CMD or the GUI? What does your log file say for "WARNING"s?

It's closer to 70 ish for me. My status is climbing but it's 200 behind and not catching the group. I'm not seeing errors.

**Comment by WestfalenerAgrarvideos** [comment]
> Hello, for your sync problem - I think you need to open on your router port 8444 (Forward a port for connection). With ip of your main pc. But first you need to change dchp to static ip on your pc - find in google how to do that on Windows 10.
> 
> 1. Windows 10 how to change DCHP to Static IP
> 2. Forward port on router (with your static IP)

Hey i can not find wher i can Open Port 8444 on my router. Maybe the problem is that IT is an LTE Mobile Router (Huawei B529s-23a Telekom Speedbox)

Can someone help me please?

**Comment by alex-oden** [comment]
Hi, I have installed this version of chia (beta build as I understand) and all working fine and stable with lot of connection from another peers. As I understand and see in logs - if there is some failure in connection it will not stop with sync and beginning with new connection but stays stable with existing peer connection

https://github.com/Chia-Network/chia-blockchain/actions/runs/853387813

Right now by me it working very good without any issues and Full node don't take a lot of power with CPU consumption. Already in Sync about 6 hours stable and FINALLY it sees my another local harvester...

(Also if you have not opened or forward on your router port 8444) You need to do that - here some help
https://portforward.com/
