### ISSUE TITLE
[BUG] My wallet don't Connecting to wallet on MAC 

### ISSUE THREAD

**Issue by luisfgbb** [Chia-Network/chia-blockchain#5560]
Después de reiniciar el Mac para actualizaciones, la cartera ya no se abre. Por otro lado, desinstala y vuelva a instalarla y no se abre. Se mantiene cargando durante muchas horas y no se carga. Imagen https://ibb.co/4FQ2q8t Have a BUG

chia_full_node: /Applications/Chia.app/Contents/Resources/app.asar.unpacked/daemon/chia Stopped
MacBook-Pro-de-Fraga-2:~ cryptofraga$ /Applications/Chia.app/Contents/Resources/app.asar.unpacked/daemon/chia start wallet
chia_wallet: started
chia_full_node: started
MacBook-Pro-de-Fraga-2:~ cryptofraga$ Traceback (most recent call last):
  File "chia/server/start_wallet.py", line 97, in <module>
  File "chia/server/start_wallet.py", line 92, in main
  File "chia/server/start_service.py", line 221, in run_service
  File "asyncio/runners.py", line 44, in run
  File "asyncio/base_events.py", line 642, in run_until_complete
  File "chia/server/start_service.py", line 215, in async_run_service
  File "chia/server/start_service.py", line 156, in run
  File "chia/server/start_service.py", line 127, in start
  File "chia/wallet/wallet_node.py", line 151, in _start
  File "chia/wallet/wallet_state_manager.py", line 138, in create
  File "chia/wallet/wallet_blockchain.py", line 106, in create
  File "chia/wallet/wallet_blockchain.py", line 117, in _load_chain_from_store
  File "chia/wallet/wallet_block_store.py", line 259, in get_peak_heights_dicts
  File "aiosqlite/cursor.py", line 65, in fetchall
  File "aiosqlite/cursor.py", line 31, in _execute
  File "aiosqlite/core.py", line 129, in _execute
  File "aiosqlite/core.py", line 102, in run
sqlite3.DatabaseError: database disk image is malformed
[1000] Failed to execute script start_wallet

**Comment by KartmanBro** [comment]
I have the same problem

**Comment by Znuff** [comment]
Just close down the GUI and then delete the `~/.chia/mainnet/db/blockchain_v1_mainnet.sqlite` or the files in `~/.chia/mainnet/wallet/`.

**Comment by luisfgbb** [comment]
> Just close down the GUI and then delete the `~/.chia/mainnet/db/blockchain_v1_mainnet.sqlite` or the files in `~/.chia/mainnet/wallet/`.
 
 
 with  command sudo rm --rf

-bash: /Users/fraga/.chia/mainnet/db/blockchain_v1_mainnet.sqlite: Permission denied

**Comment by luisfgbb** [comment]
> I have the same problem

DONE follow the tutorial up, it worked.

**Comment by KartmanBro** [comment]
А можно для тупых то же самое простыми словами?

**Comment by JerryLerman** [comment]
This did not solve it for me

**Comment by justinbread** [comment]
> > Just close down the GUI and then delete the `~/.chia/mainnet/db/blockchain_v1_mainnet.sqlite` or the files in `~/.chia/mainnet/wallet/`.
> 
> sudo rm -R ~/.chia/mainnet/db/blockchain_v1_mainnet.sqlite
> password
> 
> enter a
> sudo rm -R ~/.chia/mainnet/db/blockchain_v1_mainnet.sqlite-shm
> sudo rm -R ~/.chia/mainnet/db/blockchain_v1_mainnet.sqlite -wal
> 
> and now result:
> rm: /Users/fraga/.chia/mainnet/db/blockchain_v1_mainnet.sqlite: No such file or directory
> rm: /Users/fraga/.chia/mainnet/db/blockchain_v1_mainnet.sqlite-wal: No such file or directory
> rm: /Users/fraga/.chia/mainnet/db/blockchain_v1_mainnet.sqlite-shm: No such file or directory
> 
> I open the wallet and work :)
> tkx bro....

password for what?
