### ISSUE TITLE
[BUG]Current Blockchain Status: Not Synced. Peak height: 298829

### ISSUE THREAD

**Issue by arayalways** [Chia-Network/chia-blockchain#5581]
**Describe the bug**

Current Blockchain Status: Not Synced. Peak height: 298829

**To Reproduce**
1.Clone from code run in . ./activate `chia start farmer`
2.Tried restart for several times and add peer `chia show -a node.chia.net:8444`

**Expected behavior**
Sync to the best height!

**Screenshots**
```
Current Blockchain Status: Not Synced. Peak height: 298829
      Time: Tue May 18 2021 08:09:26 UTC                  Height:     298829

Estimated network space: 6.350 EiB
Current difficulty: 426
Current VDF sub_slot_iters: 114294784
Total iterations since the start of the blockchain: 965855573591

  Height: |   Hash:
   298829 | d1623339d537ca8cef3a678fb549e804ce4ad392f5383db6ef6c6dcdf7f142e5
   298828 | a60e14cdc06a25b00f7ceada9b1d41700b4cf28e5ba94cefca5eec07a0a4ede3
   298827 | 64920792ff9fed6fe01ecfdc5d03a327441a5274b8a7356cc6feb4a5e23ba1af
   298826 | 0496fbe61c52b3fb26d6805ee16c56a39e93a1bc2967c66ccbfdbc88fef92d62
   298825 | c5cb67a4472ab5365f9e0b9478509d6c9747cb290256f00229c781ea840292fa
   298824 | 93a564d677d41ff7b33933858de3a1f7cc8678883335f680230198c83ba0ad03
   298823 | 6c187113e10cf29a427a2cbdd590804dd74726b2f439fa4717a291d774681fb9
   298822 | 535a07d4234c6156e97ffd35e4f05dc223bebc201b9a562846d172cf88146c1a
   298821 | 5910522fc13d4401cfb7db2c75e74ee26a049dbd2133e249a17772ddbbd10510
   298820 | 7835e7c4eaa588a04d7a22c45c422e00ef9233561656967693617de8d6006133

Connections:
Type      IP                                     Ports       NodeID      Last Connect      MiB Up|Dwn
WALLET    127.0.0.1                              38676/8449  d5bf007a... May 20 08:46:42      0.0|0.0    
FARMER    127.0.0.1                              38686/8447  b16884a2... May 20 08:46:43      0.0|0.0 
```

**Desktop (please complete the following information):**

- OS: Linux
- OS Version/Flavor:  4.15.0-135-generic #139-Ubuntu SMP Mon Jan 18 17:38:24 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
- CPU:  Intel(R) Xeon(R) Platinum 8269CY CPU T 3.10GHz *8

**Additional context**
ERROR LOGS:
```
2021-05-19T11:04:36.607 full_node chia.rpc.rpc_server     : WARNING  Error while handling message: Traceback (most recent call last):
  File "/root/chia-blockchain/chia/rpc/rpc_server.py", line 81, in inner
    res_object = await f(request_data)
  File "/root/chia-blockchain/chia/rpc/rpc_server.py", line 161, in open_connection
    raise ValueError("Start client failed, or server is not set")
ValueError: Start client failed, or server is not set

2021-05-19T11:07:01.031 full_node full_node_server        : WARNING  Banning 222.170.67.86 for 600 seconds
2021-05-19T11:07:01.031 full_node chia.full_node.full_node: ERROR    Error with syncing: <class 'RuntimeError'>Traceback (most recent call last):
  File "/root/chia-blockchain/chia/full_node/full_node.py", line 628, in _sync
    raise RuntimeError(f"Weight proof did not arrive in time from peer: {weight_proof_peer.peer_host}")
RuntimeError: Weight proof did not arrive in time from peer: 222.170.67.86

2021-05-20T08:46:15.606 farmer asyncio                    : ERROR    Task exception was never retrieved
future: <Task finished name='Task-3006' coro=<WebSocketWriter.ping() done, defined at /root/chia-blockchain/venv/lib/python3.8/site-packages/aiohttp/http_websocket.py:669> exception=ConnectionResetError('Cannot write to closing transport')>
Traceback (most recent call last):
  File "/root/chia-blockchain/venv/lib/python3.8/site-packages/aiohttp/http_websocket.py", line 673, in ping
    await self._send_frame(message, WSMsgType.PING)
  File "/root/chia-blockchain/venv/lib/python3.8/site-packages/aiohttp/http_websocket.py", line 643, in _send_frame
    self._write(header + mask + message)
  File "/root/chia-blockchain/venv/lib/python3.8/site-packages/aiohttp/http_websocket.py", line 660, in _write
    raise ConnectionResetError("Cannot write to closing transport")
ConnectionResetError: Cannot write to closing transport
2021-05-20T08:46:17.776 full_node asyncio                 : ERROR    Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7f749576a610>
2021-05-20T08:46:37.725 harvester chia.harvester.harvester: WARNING  Not farming any plots on this harvester. Check your configuration.
2021-05-20T09:10:19.139 full_node full_node_server        : WARNING  Banning 107.214.10.114 for 600 seconds
2021-05-20T09:10:19.140 full_node chia.full_node.full_node: ERROR    Error with syncing: <class 'RuntimeError'>Traceback (most recent call last):
  File "/root/chia-blockchain/chia/full_node/full_node.py", line 628, in _sync
    raise RuntimeError(f"Weight proof did not arrive in time from peer: {weight_proof_peer.peer_host}")
RuntimeError: Weight proof did not arrive in time from peer: 107.214.10.114

2021-05-20T09:18:18.545 full_node chia.rpc.rpc_server     : WARNING  Error while handling message: Traceback (most recent call last):
  File "/root/chia-blockchain/chia/rpc/rpc_server.py", line 81, in inner
    res_object = await f(request_data)
  File "/root/chia-blockchain/chia/rpc/rpc_server.py", line 154, in open_connection
    target_node: PeerInfo = PeerInfo(host, uint16(int(port)))
  File "/root/chia-blockchain/chia/util/struct_stream.py", line 17, in __new__
    raise ValueError(
ValueError: Value 84444 of size 17 does not fit into uint16 of size 16

2021-05-20T09:25:01.106 full_node full_node_server        : WARNING  Banning 90.178.21.186 for 600 seconds
2021-05-20T09:25:01.107 full_node chia.full_node.full_node: ERROR    Error with syncing: <class 'RuntimeError'>Traceback (most recent call last):
  File "/root/chia-blockchain/chia/full_node/full_node.py", line 628, in _sync
    raise RuntimeError(f"Weight proof did not arrive in time from peer: {weight_proof_peer.peer_host}")
RuntimeError: Weight proof did not arrive in time from peer: 90.178.21.186

2021-05-20T09:28:41.190 full_node full_node_server        : WARNING  Banning 51.154.10.127 for 600 seconds
2021-05-20T09:28:41.190 full_node chia.full_node.full_node: ERROR    Error with syncing: <class 'RuntimeError'>Traceback (most recent call last):
  File "/root/chia-blockchain/chia/full_node/full_node.py", line 628, in _sync
    raise RuntimeError(f"Weight proof did not arrive in time from peer: {weight_proof_peer.peer_host}")
RuntimeError: Weight proof did not arrive in time from peer: 51.154.10.12
```

**Comment by arayalways** [comment]
No team support help?
At lease I post the logs. Could anyone help to check these logs?

**Comment by alex-oden** [comment]
Hi, I have installed this version of chia (beta build as I understand) and all working fine and stable with lot of connection from another peers. As I understand and see in logs - if there is some failure in connection it will not stop with sync and beginning with new connection but stays stable with existing peer connection

https://github.com/Chia-Network/chia-blockchain/actions/runs/853387813

Right now by me it working very good without any issues and Full node don't take a lot of power with CPU consumption. Already in Sync about 6 hours stable and FINALLY it sees my another local harvester...

(Also if you have not opened or forward on your router port 8444) You need to do that - here some help
https://portforward.com/

**Comment by phtp** [comment]
@alex-oden Thanks for the beta build info. will have to try this as I'm having random sync issues since 1.1.5 and I never did before. It would show sync then at somepoint it would random lag behind.

**Comment by mariano54** [comment]
1.1.6 is out! sync issues are fixed
