### ISSUE TITLE
[BUG] I'm unabel to create 2 plots in parallel. Everytime one plot or the 2 plots fails on i5 760 16GB

### ISSUE THREAD

**Issue by tkmbe99** [Chia-Network/chia-blockchain#5698]
**Describe the bug**
I'm unabel to create 2 plots in parallel. Everytime one plot or the 2 plots fails.
One plot in one mecanical 1TB WD disc (new one) one plot on an other mecanical 1TB seagate disk (new one).
This occured the same on 2 other one mecanical discs.
All suspend is disabled on disk, usb, etc.
First one hangs at 63% other one at 90%. 

**Screenshots**
![Captura de pantalla (25)](https://user-images.githubusercontent.com/48949966/119132014-8e9f9c00-ba10-11eb-9b13-f349723cb794.png)

**Desktop (please complete the following information):**

- OS: Win10 Pro
- OS Version/Flavor: 20H2
- CPU: i5 760 with 16GB

**Additional context**
This night again2 plots failed. I don't know is this is an i5 1. generation only problem.
The only strange is that even actualization of win10 is paused for 7 days the defender has begun to download 10min before first plot hanged up but I guess this has nothing todo.
I tried with 4MB/2threads 6MB/2threas 4MB/3threads etc.
Now I tried one with 6MB/3threads and one with 4MB/2threads

Here are part of the log files:

Start and end of Plot 1
```
2021-05-20T13:40:15.166  chia.plotting.create_plots       : [32mINFO    [0m Creating 1 plots of size 32, pool public key:  afadbd80d6f1dd8f71e195396a1b1f3ead2927070a04abd760ced15eed8a1a85b20245ca9ed814fd5bcd5b528f38a53e farmer public key: 926e2a37817fc4dce4ed8b56771a88ff4a4e0e1122ed6cfed705343ab863a86d7287d365c1073199423efefb84791468[0m
2021-05-20T13:40:15.180  chia.plotting.create_plots       : [32mINFO    [0m Memo: afadbd80d6f1dd8f71e195396a1b1f3ead2927070a04abd760ced15eed8a1a85b20245ca9ed814fd5bcd5b528f38a53e926e2a37817fc4dce4ed8b56771a88ff4a4e0e1122ed6cfed705343ab863a86d7287d365c1073199423efefb8479146810587092dfc800b6b68014e44294078ef9369019e8b2570efe3730dd0959002f[0m
2021-05-20T13:40:15.180  chia.plotting.create_plots       : [32mINFO    [0m Starting plot 1/1[0m

Starting plotting progress into temporary dirs: D:\Chia Temp D and D:\Chia Temp D
ID: f549fa9408db72d3e7c4e56d06dc33b01c9d76d15fe55009c298ae8c88114c8c
Plot size is: 32
Buffer size is: 6000MiB
Using 128 buckets
Using 3 threads of stripe size 65536

Starting phase 1/4: Forward Propagation into tmp files... Thu May 20 13:40:15 2021
Computing table 1
F1 complete, time: 319.29 seconds. CPU (141.17%) Thu May 20 13:45:34 2021
Computing table 2
	Bucket 0 uniform sort. Ram: 5.796GiB, u_sort min: 0.563GiB, qs min: 0.281GiB.
	Bucket 1 uniform sort. Ram: 5.796GiB, u_sort min: 1.125GiB, qs min: 0.281GiB.
	Bucket 2 uniform sort. Ram: 5.796GiB, u_sort min: 0.563GiB, qs min: 0.281GiB.
	Bucket 3 uniform sort. Ram: 5.796GiB, u_sort min: 1.125GiB, qs min: 0.281GiB.
....
	Bucket 82 QS. Ram: 5.796GiB, u_sort min: 0.188GiB, qs min: 0.051GiB. force_qs: 1
	Second computation pass time: 1488.956 seconds. CPU (47.130%) Fri May 21 00:16:40 2021
	Wrote 3466157893 entries
Total compress table time: 3855.602 seconds. CPU (54.300%) Fri May 21 00:16:40 2021
Compressing tables 4 and 5
	Bucket 0 uniform sort. Ram: 2.898GiB, u_sort min: 1.250GiB, qs min: 0.319GiB.
	Bucket 0 uniform sort. Ram: 2.898GiB, u_sort min: 0.500GiB, qs min: 0.250GiB.
	Bucket 1 uniform sort. Ram: 2.898GiB, u_sort min: 1.250GiB, qs min: 0.319GiB.
	Bucket 1 uniform sort. Ram: 2.898GiB, u_sort min: 0.500GiB, qs min: 0.250GiB.
	Bucket 2 uniform sort. Ram: 2.898GiB, u_sort min: 1.250GiB, qs min: 0.319GiB.
	Bucket 2 uniform sort. Ram: 2.898GiB, u_sort min: 0.500GiB, qs min: 0.250GiB.
```

Start and end of Plot 2:

```
2021-05-20T15:20:55.729  chia.plotting.create_plots       : [32mINFO    [0m Creating 1 plots of size 32, pool public key:  afadbd80d6f1dd8f71e195396a1b1f3ead2927070a04abd760ced15eed8a1a85b20245ca9ed814fd5bcd5b528f38a53e farmer public key: 926e2a37817fc4dce4ed8b56771a88ff4a4e0e1122ed6cfed705343ab863a86d7287d365c1073199423efefb84791468[0m
2021-05-20T15:20:55.744  chia.plotting.create_plots       : [32mINFO    [0m Memo: afadbd80d6f1dd8f71e195396a1b1f3ead2927070a04abd760ced15eed8a1a85b20245ca9ed814fd5bcd5b528f38a53e926e2a37817fc4dce4ed8b56771a88ff4a4e0e1122ed6cfed705343ab863a86d7287d365c1073199423efefb847914681451d47afb998f45ecffb002d4c7d77230f96130d9fdde47594cd244cd10f52e[0m
2021-05-20T15:20:55.753  chia.plotting.create_plots       : [32mINFO    [0m Starting plot 1/1[0m

Starting plotting progress into temporary dirs: E:\Chia Temp E and E:\Chia Temp E
ID: 8e3ce3195af75f9c172c30f064800e3f1e2b915d30d33f881bce4221250c3703
Plot size is: 32
Buffer size is: 4000MiB
Using 128 buckets
Using 2 threads of stripe size 65536

Starting phase 1/4: Forward Propagation into tmp files... Thu May 20 15:20:55 2021
Computing table 1
F1 complete, time: 392.834 seconds. CPU (65.34%) Thu May 20 15:27:28 2021
Computing table 2
	Bucket 0 uniform sort. Ram: 3.847GiB, u_sort min: 0.563GiB, qs min: 0.281GiB.
	Bucket 1 uniform sort. Ram: 3.847GiB, u_sort min: 0.563GiB, qs min: 0.281GiB.
	Bucket 2 uniform sort. Ram: 3.847GiB, u_sort min: 0.563GiB, qs min: 0.281GiB.
	Bucket 3 uniform sort. Ram: 3.847GiB, u_sort min: 1.125GiB, qs min: 0.281GiB.
	Bucket 4 uniform sort. Ram: 3.847GiB, u_sort min: 1.125GiB, qs min: 0.281GiB.

	Second computation pass time: 1250.710 seconds. CPU (56.160%) Fri May 21 04:23:11 2021
	Wrote 3712167780 entries
Total compress table time: 3029.341 seconds. CPU (67.470%) Fri May 21 04:23:11 2021
Compressing tables 6 and 7
	Bucket 0 uniform sort. Ram: 3.847GiB, u_sort min: 0.500GiB, qs min: 0.250GiB.
	Bucket 1 uniform sort. Ram: 3.847GiB, u_sort min: 0.500GiB, qs min: 0.250GiB.
	Bucket 2 uniform sort. Ram: 3.847GiB, u_sort min: 0.500GiB, qs min: 0.250GiB.
	Bucket 3 uniform sort. Ram: 3.847GiB, u_sort min: 0.500GiB, qs min: 0.250GiB.
	Bucket 4 uniform sort. Ram: 3.847GiB, u_sort min: 0.500GiB, qs min: 0.250GiB.
	Bucket 5 uniform sort. Ram: 3.847GiB, u_sort min: 0.500GiB, qs min: 0.250GiB.
	Bucket 6 uniform sort. Ram: 3.847GiB, u_sort min: 0.500GiB, qs min: 0.250GiB.
	Bucket 7 uniform sort. Ram: 3.847GiB, u_sort min: 0.500GiB, qs min: 0.250GiB.
	Bucket 8 uniform sort. Ram: 3.847GiB, u_sort min: 0.500GiB, qs min: 0.250GiB.
	Bucket 9 uniform sort. Ram: 3.847GiB, u_sort min: 0.500GiB, qs min: 0.250GiB.
	Bucket 10 uniform sort. Ram: 3.847GiB, u_sort min: 0.500GiB, qs min: 0.250GiB.
	Bucket 11 uniform sort. Ram: 3.847GiB, u_sort min: 0.500GiB, qs min: 0.250GiB.
	Bucket 12 uniform sort. Ram: 3.847GiB, u_sort min: 0.500GiB, qs min: 0.250GiB.
	Bucket 13 uniform sort. Ram: 3.847GiB, u_sort min: 0.500GiB, qs min: 0.250GiB.
	Bucket 14 uniform sort. Ram: 3.847GiB, u_sort min: 0.500GiB, qs min: 0.250GiB.
	Bucket 15 uniform sort. Ram: 3.847GiB, u_sort min: 0.500GiB, qs min: 0.250GiB.
	Bucket 16 uniform sort. Ram: 3.847GiB, u_sort min: 0.500GiB, qs min: 0.250GiB.
	Bucket 17 uniform sort. Ram: 3.847GiB, u_sort min: 0.500GiB, qs min: 0.250GiB.
	Bucket 18 uniform sort. Ram: 3.847GiB, u_sort min: 0.500GiB, qs min: 0.250GiB.
	Bucket 19 uniform sort. Ram: 3.847GiB, u_sort min: 0.500GiB, qs min: 0.250GiB.
	Bucket 20 uniform sort. Ram: 3.847GiB, u_sort min: 0.500GiB, qs min: 0.250GiB.
	Bucket 21 uniform sort. Ram: 3.847GiB, u_sort min: 0.500GiB, qs min: 0.250GiB.
	Bucket 22 uniform sort. Ram: 3.847GiB, u_sort min: 0.500GiB, qs min: 0.250GiB.
	Bucket 23 uniform sort. Ram: 3.847GiB, u_sort min: 0.500GiB, qs min: 0.250GiB.
	Bucket 24 uniform sort. Ram: 3.847GiB, u_sort min: 0.500GiB, qs min: 0.250GiB.
	Bucket 25 uniform sort. Ram: 3.847GiB, u_sort min: 0.500GiB, qs min: 0.250GiB.
	Bucket 26 uniform sort. Ram: 3.847GiB, u_sort min: 0.500GiB, qs min: 0.250GiB.
	Bucket 27 uniform sort. Ram: 3.847GiB, u_sort min: 0.500GiB, qs min: 0.250GiB.
	Bucket 28 uniform sort. Ram: 3.847GiB, u_sort min: 0.500GiB, qs min: 0.250GiB.
	Bucket 29 uniform sort. Ram: 3.847GiB, u_sort min: 0.500GiB, qs min: 0.250GiB.
	Bucket 30 uniform sort. Ram: 3.847GiB, u_sort min: 0.500GiB, qs min: 0.250GiB.
	Bucket 31 uniform sort. Ram: 3.847GiB, u_sort min: 0.500GiB, qs min: 0.250GiB.
	Bucket 32 uniform sort. Ram: 3.847GiB, u_sort min: 0.500GiB, qs min: 0.250GiB.
	Bucket 33 uniform sort. Ram: 3.847GiB, u_sort min: 0.500GiB, qs min: 0.250GiB.
	Bucket 34 uniform sort. Ram: 3.847GiB, u_sort min: 0.500GiB, qs min: 0.250GiB.
	Bucket 35 uniform sort. Ram: 3.847GiB, u_sort min: 0.500GiB, qs min: 0.250GiB.
	Bucket 36 uniform sort. Ram: 3.847GiB, u_sort min: 0.500GiB, qs min: 0.250GiB.
	Bucket 37 uniform sort. Ram: 3.847GiB, u_sort min: 0.500GiB, qs min: 0.250GiB.
	Bucket 38 uniform sort. Ram: 3.847GiB, u_sort min: 0.500GiB, qs min: 0.250GiB.
	Bucket 39 uniform sort. Ram: 3.847GiB, u_sort min: 0.500GiB, qs min: 0.250GiB.
	Bucket 40 uniform sort. Ram: 3.847GiB, u_sort min: 0.500GiB, qs min: 0.250GiB.
	Bucket 41 uniform sort. Ram: 3.847GiB, u_sort min: 0.500GiB, qs min: 0.250GiB.
	Bucket 42 uniform sort. Ram: 3.847GiB, u_sort min: 0.500GiB, qs min: 0.250GiB.
	Bucket 43 uniform sort. Ram: 3.847GiB, u_sort min: 0.500GiB, qs min: 0.250GiB.
	Bucket 44 uniform sort. Ram: 3.847GiB, u_sort min: 0.500GiB, qs min: 0.250GiB.
	Bucket 45 uniform sort. Ram: 3.847GiB, u_sort min: 0.500GiB, qs min: 0.250GiB.
	Bucket 46 uniform sort. Ram: 3.847GiB, u_sort min: 0.500GiB, qs min: 0.250GiB.
	Bucket 47 uniform sort. Ram: 3.847GiB, u_sort min: 0.500GiB, qs min: 0.250GiB.
	Bucket 48 uniform sort. Ram: 3.847GiB, u_sort min: 0.500GiB, qs min: 0.250GiB.
	Bucket 49 uniform sort. Ram: 3.847GiB, u_sort min: 0.500GiB, qs min: 0.250GiB.
	Bucket 50 uniform sort. Ram: 3.847GiB, u_sort min: 0.500GiB, qs min: 0.250GiB.
	Bucket 51 uniform sort. Ram: 3.847GiB, u_sort min: 0.500GiB, qs min: 0.250GiB.
	Bucket 52 uniform sort. Ram: 3.847GiB, u_sort min: 0.500GiB, qs min: 0.250GiB.
	Bucket 53 uniform sort. Ram: 3.847GiB, u_sort min: 0.500GiB, qs min: 0.250GiB.
	Bucket 54 uniform sort. Ram: 3.847GiB, u_sort min: 0.500GiB, qs min: 0.250GiB.
	Bucket 55 uniform sort. Ram: 3.847GiB, u_sort min: 0.500GiB, qs min: 0.250GiB.
	Bucket 56 uniform sort. Ram: 3.847GiB, u_sort min: 0.500GiB, qs min: 0.250GiB.
	Bucket 57 uniform sort. Ram: 3.847GiB, u_sort min: 0.500GiB, qs min: 0.250GiB.
	Bucket 58 uniform sort. Ram: 3.847GiB, u_sort min: 0.500GiB, qs min: 0.250GiB.
	Bucket 59 uniform sort. Ram: 3.847GiB, u_sort min: 0.500GiB, qs min: 0.250GiB.
	Bucket 60 uniform sort. Ram: 3.847GiB, u_sort min: 0.500GiB, qs min: 0.250GiB.
	Bucket 61 uniform sort. Ram: 3.847GiB, u_sort min: 0.500GiB, qs min: 0.250GiB.
	Bucket 62 uniform sort. Ram: 3.847GiB, u_sort min: 0.500GiB, qs min: 0.250GiB.
	Bucket 63 uniform sort. Ram: 3.847GiB, u_sort min: 0.500GiB, qs min: 0.250GiB.
	Bucket 64 uniform sort. Ram: 3.847GiB, u_sort min: 0.500GiB, qs min: 0.250GiB.
	Bucket 65 uniform sort. Ram: 3.847GiB, u_sort min: 0.500GiB, qs min: 0.250GiB.
	Bucket 66 uniform sort. Ram: 3.847GiB, u_sort min: 0.500GiB, qs min: 0.250GiB.
	Bucket 67 uniform sort. Ram: 3.847GiB, u_sort min: 0.500GiB, qs min: 0.250GiB.
	Bucket 68 uniform sort. Ram: 3.847GiB, u_sort min: 0.500GiB, qs min: 0.250GiB.
	Bucket 69 uniform sort. Ram: 3.847GiB, u_sort min: 0.500GiB, qs min: 0.250GiB.
	Bucket 70 uniform sort. Ram: 3.847GiB, u_sort min: 0.500GiB, qs min: 0.250GiB.
	Bucket 71 uniform sort. Ram: 3.847GiB, u_sort min: 0.500GiB, qs min: 0.250GiB.
	Bucket 72 uniform sort. Ram: 3.847GiB, u_sort min: 0.500GiB, qs min: 0.250GiB.
	Bucket 73 uniform sort. Ram: 3.847GiB, u_sort min: 0.500GiB, qs min: 0.250GiB.
	Bucket 74 uniform sort. Ram: 3.847GiB, u_sort min: 0.500GiB, qs min: 0.250GiB.
	Bucket 75 uniform sort. Ram: 3.847GiB, u_sort min: 0.500GiB, qs min: 0.250GiB.
	Bucket 76 uniform sort. Ram: 3.847GiB, u_sort min: 0.500GiB, qs min: 0.250GiB.
	Bucket 77 uniform sort. Ram: 3.847GiB, u_sort min: 0.500GiB, qs min: 0.250GiB.
	Bucket 78 uniform sort. Ram: 3.847GiB, u_sort min: 0.500GiB, qs min: 0.250GiB.
	Bucket 79 uniform sort. Ram: 3.847GiB, u_sort min: 0.500GiB, qs min: 0.250GiB.
	Bucket 80 uniform sort. Ram: 3.847GiB, u_sort min: 0.500GiB, qs min: 0.250GiB.
	Bucket 81 uniform sort. Ram: 3.847GiB, u_sort min: 0.500GiB, qs min: 0.250GiB.
	Bucket 82 uniform sort. Ram: 3.847GiB, u_sort min: 0.500GiB, qs min: 0.250GiB.
	Bucket 83 uniform sort. Ram: 3.847GiB, u_sort min: 0.500GiB, qs min: 0.250GiB.
	Bucket 84 uniform sort. Ram: 3.847GiB, u_sort min: 0.500GiB, qs min: 0.250GiB.
	Bucket 85 uniform sort. Ram: 3.847GiB, u_sort min: 0.500GiB, qs min: 0.250GiB.
	Bucket 86 uniform sort. Ram: 3.847GiB, u_sort min: 0.500GiB, qs min: 0.250GiB.
	Bucket 87 uniform sort. Ram: 3.847GiB, u_sort min: 0.500GiB, qs min: 0.250GiB.
	Bucket 88 uniform sort. Ram: 3.847GiB, u_sort min: 0.500GiB, qs min: 0.250GiB.
	Bucket 89 uniform sort. Ram: 3.847GiB, u_sort min: 0.500GiB, qs min: 0.250GiB.
	Bucket 90 uniform sort. Ram: 3.847GiB, u_sort min: 0.500GiB, qs min: 0.250GiB.
```

**Comment by MustDhiMust** [comment]
so you are plotting with mechanical drive?

**Comment by s12321** [comment]
could you double check your disk space?

**Comment by tkmbe99** [comment]
Both disk are 1TB emptyonly for plotting...
And yes I'm plotting on mecanical disc on SSD it was the same problem...

**Comment by MustDhiMust** [comment]
did you upgrade to the last version?

**Comment by tkmbe99** [comment]
I had until 2days ago... Now there is 1.1.6 out but I don't think there is any changein this problem.
My sons both have no problem on the pc they have. I had the same problem eith 1.1.3 and 1.1.4
I will try 1.1.6 if not go back to1.1.2 if I remembre right there was not the problem...

**Comment by wbendick** [comment]
try running memtest86 to make sure you don't have a hardware issue

**Comment by PsychoLogiKal** [comment]
Pay special attention to step #5 i bet its your issue............ It seems odd to have to change virtual memory settings in the day and age of SSD's, considering i can run MasterCAM and AutoCAD at the same time with 0 issues but my parallel plots were failing over night every night for a few nights until i fixed it and now they run marvelously by setting the system virtual memory settings to 10240-30720 Min-Max.................
https://wccftech.com/how-to-fix-chia-runtime-error-bad-allocation-on-windows/

**Comment by brezapour81** [comment]
I had this issue. And it was annoying!!!

Finally found out it was due to memory module issue. 

Replaced memory module and it works now.

If people are interest, we are launching a Chia Pool soon called https://Seedpool.org. Check it out.

**Comment by tkmbe99** [comment]
The problem seems to be in the following:
But this occurs only on this processor, nor on i5-9400F nor on Ryzen 5 3600 does occure this. Very strange...

```
2021-06-10T16:35:18.871 full_node full_node_server        : ERROR    Exception: too many SQL variables, {'host': '127.0.0.1', 'port': 8449}. Traceback (most recent call last):
  File "chia\server\server.py", line 526, in wrapped_coroutine
  File "chia\full_node\full_node_api.py", line 244, in request_proof_of_weight
  File "chia\full_node\weight_proof.py", line 77, in get_proof_of_weight
  File "chia\full_node\weight_proof.py", line 119, in _create_proof_of_weight
  File "chia\consensus\blockchain.py", line 695, in get_block_records_at
  File "chia\full_node\block_store.py", line 181, in get_block_records_by_hash
  File "aiosqlite\core.py", line 184, in execute
  File "aiosqlite\core.py", line 129, in _execute
  File "aiosqlite\core.py", line 102, in run
sqlite3.OperationalError: too many SQL variables

2021-06-10T16:35:18.873 full_node full_node_server        : ERROR    Exception: too many SQL variables <class 'sqlite3.OperationalError'>, closing connection {'host': '127.0.0.1', 'port': 8449}. Traceback (most recent call last):
  File "chia\server\server.py", line 536, in api_call
  File "asyncio\tasks.py", line 442, in wait_for
  File "chia\server\server.py", line 533, in wrapped_coroutine
  File "chia\server\server.py", line 526, in wrapped_coroutine
  File "chia\full_node\full_node_api.py", line 244, in request_proof_of_weight
  File "chia\full_node\weight_proof.py", line 77, in get_proof_of_weight
  File "chia\full_node\weight_proof.py", line 119, in _create_proof_of_weight
  File "chia\consensus\blockchain.py", line 695, in get_block_records_at
  File "chia\full_node\block_store.py", line 181, in get_block_records_by_hash
  File "aiosqlite\core.py", line 184, in execute
  File "aiosqlite\core.py", line 129, in _execute
  File "aiosqlite\core.py", line 102, in run
sqlite3.OperationalError: too many SQL variables
```
