### ISSUE TITLE
[BUG] Not Connect My Wallet after update 1.1.6

### ISSUE THREAD

**Issue by Ragnarzeiro** [Chia-Network/chia-blockchain#5721]
**Describe the bug**
it was apparently not possible to load the dns module and this would be making it impossible to open the wallet

**To Reproduce**

1). ./activate
2) npm run electron &

**Expected behavior**
I would like my wallet to open 

**Screenshots**
https://i.imgur.com/9Fr42MP.png

**Desktop

- OS: Linux
- OS Version/Flavor: Ubuntu 21.04
- CPU: i5-8600k

(venv) vittor@vittor-Z370-AORUS-Ultra-Gaming:~/chia-blockchain/chia-blockchain-gui$ 
> electron
> electron .

/home/vittor/chia-blockchain/app.asar.unpacked/daemon
false
Error loading config - using defaults

(electron:8978): Gtk-WARNING **: 12:06:37.127: include in Compose files not supported: include "/usr/share/X11/locale/en_US.UTF-8/Compose"

(electron:8978): Gtk-WARNING **: 12:06:37.128: Need to double-quote the value: "Ə" U018f: <Multi_key> <e> <e> 			: "Ə" U018f

(electron:8978): Gtk-WARNING **: 12:06:37.128: Need to double-quote the value: "〝" U301d	# REVERSED DOUBLE PRIME QUOTATION MARK: <Multi_key> <quotedbl> <backslash> 	: "〝" U301d	# REVERSED DOUBLE PRIME QUOTATION MARK

(electron:8978): Gtk-WARNING **: 12:06:37.128: Need to double-quote the value: "〞" U301e	# DOUBLE PRIME QUOTATION MARK: <Multi_key> <quotedbl> <slash>  	: "〞" U301e	# DOUBLE PRIME QUOTATION MARK

(electron:8978): Gtk-WARNING **: 12:06:37.128: Need to double-quote the value: "Ç" Ccedilla	# LATIN CAPITAL LETTER C WITH CEDILLA: <dead_acute> <C> 			: "Ç" Ccedilla	# LATIN CAPITAL LETTER C WITH CEDILLA

(electron:8978): Gtk-WARNING **: 12:06:37.128: Need to double-quote the value: "ç" ccedilla	# LATIN SMALL LETTER C WITH CEDILLA: <dead_acute> <c> 			: "ç" ccedilla	# LATIN SMALL LETTER C WITH CEDILLA

(electron:8978): Gtk-WARNING **: 12:06:37.128: Need to double-quote the value: "Ȩ" U0228	# LATIN CAPITAL LETTER E WITH CEDILLA: <Multi_key> <comma> <E> 		: "Ȩ" U0228	# LATIN CAPITAL LETTER E WITH CEDILLA

(electron:8978): Gtk-WARNING **: 12:06:37.128: Need to double-quote the value: "ȩ" U0229	# LATIN SMALL LETTER E WITH CEDILLA: <Multi_key> <comma> <e> 		: "ȩ" U0229	# LATIN SMALL LETTER E WITH CEDILLA

(electron:8978): Gtk-WARNING **: 12:06:37.128: Need to double-quote the value: "Ḝ" U1E1C	# LATIN CAPITAL LETTER E WITH CEDILLA AND BREVE: <Multi_key> <U> <comma> <E> 		: "Ḝ" U1E1C	# LATIN CAPITAL LETTER E WITH CEDILLA AND BREVE

(electron:8978): Gtk-WARNING **: 12:06:37.128: Need to double-quote the value: "ḝ" U1E1D	# LATIN SMALL LETTER E WITH CEDILLA AND BREVE: <Multi_key> <U> <comma> <e> 		: "ḝ" U1E1D	# LATIN SMALL LETTER E WITH CEDILLA AND BREVE

(electron:8978): Gtk-WARNING **: 12:06:37.128: Need to double-quote the value: "ϓ" U03D3	# GREEK UPSILON WITH ACUTE AND HOOK SYMBOL: <Multi_key> <acute> <U03D2> 		: "ϓ" U03D3	# GREEK UPSILON WITH ACUTE AND HOOK SYMBOL

(electron:8978): Gtk-WARNING **: 12:06:37.128: Need to double-quote the value: "ϓ" U03D3	# GREEK UPSILON WITH ACUTE AND HOOK SYMBOL: <Multi_key> <apostrophe> <U03D2> 	: "ϓ" U03D3	# GREEK UPSILON WITH ACUTE AND HOOK SYMBOL
startUrl file:///home/vittor/chia-blockchain/chia-blockchain-gui/build/renderer/index.html
/home/vittor/chia-blockchain/app.asar.unpacked/daemon
false
/home/vittor/chia-blockchain/app.asar.unpacked/daemon
false
Running python script
Script ../chia/daemon/server.py
child process success
(node:8978) electron: The default of contextIsolation is deprecated and will be changing from false to true in a future release of Electron.  See https://github.com/electron/electron/issues/23506 for more information
No cert
Have cert
stderr: Traceback (most recent call last):
  File "/home/vittor/chia-blockchain/venv/bin/chia_full_node", line 33, in <module>
    sys.exit(load_entry_point('chia-blockchain', 'console_scripts', 'chia_full_node')())
  File "/home/vittor/chia-blockchain/venv/bin/chia_full_node", line 25, in importlib_load_entry_point
stderr:     return next(matches).load()
  File "/usr/lib/python3.9/importlib/metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
stderr:   File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/vittor/chia-blockchain/chia/server/start_full_node.py", line 8, in <module>
    from chia.full_node.full_node import FullNode
  File "/home/vittor/chia-blockchain/chia/full_node/full_node.py", line 39, in <module>
    from chia.server.node_discovery import FullNodePeers
  File "/home/vittor/chia-blockchain/chia/server/node_discovery.py", line 13, in <module>
stderr:     import dns.asyncresolver
ModuleNotFoundError: No module named 'dns'
stderr: Traceback (most recent call last):
  File "/home/vittor/chia-blockchain/venv/bin/chia_wallet", line 33, in <module>
stderr:     sys.exit(load_entry_point('chia-blockchain', 'console_scripts', 'chia_wallet')())
  File "/home/vittor/chia-blockchain/venv/bin/chia_wallet", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/lib/python3.9/importlib/metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/vittor/chia-blockchain/chia/server/start_wallet.py", line 7, in <module>
stderr:     from chia.rpc.wallet_rpc_api import WalletRpcApi
  File "/home/vittor/chia-blockchain/chia/rpc/wallet_rpc_api.py", line 33, in <module>
    from chia.wallet.wallet_node import WalletNode
  File "/home/vittor/chia-blockchain/chia/wallet/wallet_node.py", line 28, in <module>
    from chia.server.node_discovery import WalletPeers
  File "/home/vittor/chia-blockchain/chia/server/node_discovery.py", line 13, in <module>
    import dns.asyncresolver
ModuleNotFoundError: No module named 'dns'

**Comment by Artawower** [comment]
Your can install it manually
https://stackoverflow.com/questions/21641696/python-dns-module-import-error

**Comment by tanaesset** [comment]
Just install dnspython inside the venv. That is:
. ./activate
pip3 install dnspython
