### ISSUE TITLE
RuntimeError: bad allocation

### ISSUE THREAD

**Issue by miracorhan** [Chia-Network/chia-blockchain#5778]
Starting phase 1/4: Forward Propagation into tmp files... Sat May 22 04:06:46 2021
Computing table 1
F1 complete, time: 111.613 seconds. CPU (102.01%) Sat May 22 04:08:38 2021
Computing table 2
Caught plotting error: bad allocation
[2004] Failed to execute script chia
Traceback (most recent call last):
  File "chia\cmds\chia.py", line 81, in <module>
  File "chia\cmds\chia.py", line 77, in main
  File "click\core.py", line 829, in __call__
  File "click\core.py", line 782, in main
  File "click\core.py", line 1259, in invoke
  File "click\core.py", line 1259, in invoke
  File "click\core.py", line 1066, in invoke
  File "click\core.py", line 610, in invoke
  File "click\decorators.py", line 21, in new_func
  File "chia\cmds\plots.py", line 135, in create_cmd
  File "chia\plotting\create_plots.py", line 176, in create_plots
RuntimeError: bad allocation

Plot process does not progress, freezes. Usually this error is around 1%. The next plotting process is in progress.
We could delete this plot operation in version 1.1.5. When I update to version 1.1.6 the delete button is not active.
Error caused by the cause, thanks.

**Comment by miracorhan** [comment]
repeated error entry can be deleted
