### ISSUE TITLE
[BUG] Exception Was not able to get peername from <function WSChiaConnection.__getattr__.<locals>.invoke at 0x7ff235e6e3a0>

### ISSUE THREAD

**Issue by abargstaedt** [Chia-Network/chia-blockchain#5782]
**Describe the bug**
The following error occurs from time to time during farming with version 1.1.6:

```
full_node full_node_server        : ERROR    Exception Was not able to get peername from <function WSChiaConnection.__getattr__.<locals>.invoke at 0x7ff235e6e3a0> at 123.192.231.122, exception Stack: Traceback (most recent call last):
  File "/home/user/chia-blockchain/chia/server/server.py", line 235, in incoming_connection
    connection = WSChiaConnection(
  File "/home/user/chia-blockchain/chia/server/ws_connection.py", line 59, in __init__
    raise ValueError(f"Was not able to get peername from {self.ws_witer} at {self.peer_host}")
ValueError: Was not able to get peername from <function WSChiaConnection.__getattr__.<locals>.invoke at 0x7ff235e6e3a0> at 123.192.231.122
```

**To Reproduce**
```sh
cd chia-blockchain
. ./activate
chia start farmer
tail -f ~/.chia/mainnet/log/debug.log
```

**Desktop (please complete the following information):**

- OS: Arch Linux
- OS Version/Flavor: 5.12.5-arch1-1
- CPU: Intel Celeron J4125
- Architecture: x86-64

**Comment by richardwhatever** [comment]
i'm getting this a lot the last few days
