### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by ohniel** [Chia-Network/chia-blockchain#5830]
Buenas noches. tengo dos días que se queda en sincronizando, no es capaz de establecer conexión las parcelas.
![Captura de pantalla 2021-05-22 222754](https://user-images.githubusercontent.com/84644661/119241313-708b8600-bb4d-11eb-86e0-5c69b015f7d7.png)
![Captura de pantalla 2021-05-22 222839](https://user-images.githubusercontent.com/84644661/119241314-71241c80-bb4d-11eb-8c0e-e11ef387bfe7.png)
![Captura de pantalla 2021-05-22 222929](https://user-images.githubusercontent.com/84644661/119241315-71241c80-bb4d-11eb-8211-0012a56a44e1.png)
![Captura de pantalla 2021-05-22 223011](https://user-images.githubusercontent.com/84644661/119241316-71bcb300-bb4d-11eb-8216-bf93810b91cc.png)

**Comment by LuanSouza28** [comment]
Ver log de tarefas
1%

2021-05-22T20:29:39.505  chia.plotting.create_plots       : [33mWARNING [0m Creating plots with size k=25, which is less than the minimum required for mainnet[0m
2021-05-22T20:29:39.505  chia.plotting.create_plots       : [32mINFO    [0m Creating 1 plots of size 25, pool public key:  917bed9b68e135e634686ae2e59b4407c29b2aea1d4acc1523508453b1d3cc504bd9e53789a973e9717080db6b0408cc farmer public key: ae04aaef8436358f89850ccc7e507080614d80ab64f95bbd7ba1a8d056c3dce0087cf59e15bcb36b2236161d0de300a9[0m
2021-05-22T20:29:39.534  chia.plotting.create_plots       : [32mINFO    [0m Memo: 917bed9b68e135e634686ae2e59b4407c29b2aea1d4acc1523508453b1d3cc504bd9e53789a973e9717080db6b0408ccae04aaef8436358f89850ccc7e507080614d80ab64f95bbd7ba1a8d056c3dce0087cf59e15bcb36b2236161d0de300a95eea6da663bc931d931dbbf273b08cb70b975ed6d4763deeeb582f10e3bda669[0m
2021-05-22T20:29:39.536  chia.plotting.create_plots       : [32mINFO    [0m Starting plot 1/1[0m
Caught plotting error: Bitfield plotting not supported by CPU
[728] Failed to execute script chia
Traceback (most recent call last):
  File "chia\cmds\chia.py", line 81, in <module>
  File "chia\cmds\chia.py", line 77, in main
  File "click\core.py", line 829, in __call__
  File "click\core.py", line 782, in main
  File "click\core.py", line 1259, in invoke
  File "click\core.py", line 1259, in invoke
  File "click\core.py", line 1066, in invoke
  File "click\core.py", line 610, in invoke
  File "click\decorators.py", line 21, in new_func
  File "chia\cmds\plots.py", line 135, in create_cmd
  File "chia\plotting\create_plots.py", line 176, in create_plots
RuntimeError: Unknown exception

**Comment by LuanSouza28** [comment]
DOES NOT WORK ON OLDER COMPUTERS,
I CANNOT USE MY 8GB PENDRIVE

**Comment by ohniel** [comment]
Good Morning.
until 3 days ago it worked perfectly for me.
I have a PC with Rayzen 5400G with 4 cores at 8 threads.
Windows 10 home.
I don't understand why it suddenly stopped syncing

Buenos días.
hasta hace 3 días me funcionaba perfectamente.
tengo un PC con Rayzen 5400G con 4 nucleos a 8hilos.
Windows 10 home.
no entiendo porque de repente dejó de sincronizar.

Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________

**Comment by gromran** [comment]
rtfm...

> Caught plotting error: Bitfield plotting not supported by CPU

**Comment by lvpcguru** [comment]
try turning off bitfield if your on an old cpu.
![image](https://user-images.githubusercontent.com/4685333/119256769-4b6c3700-bb90-11eb-83f1-7bcc6ee92dbc.png)

**Comment by lvpcguru** [comment]
> 
> 
> Buenas noches. tengo dos días que se queda en sincronizando, no es capaz de establecer conexión las parcelas.
> ![Captura de pantalla 2021-05-22 222754](https://user-images.githubusercontent.com/84644661/119241313-708b8600-bb4d-11eb-86e0-5c69b015f7d7.png)
> ![Captura de pantalla 2021-05-22 222839](https://user-images.githubusercontent.com/84644661/119241314-71241c80-bb4d-11eb-8c0e-e11ef387bfe7.png)
> ![Captura de pantalla 2021-05-22 222929](https://user-images.githubusercontent.com/84644661/119241315-71241c80-bb4d-11eb-8211-0012a56a44e1.png)
> ![Captura de pantalla 2021-05-22 223011](https://user-images.githubusercontent.com/84644661/119241316-71bcb300-bb4d-11eb-8216-bf93810b91cc.png)

what version are you on? and what OS?
