### ISSUE TITLE
[BUG]runtime error during ploting

### ISSUE THREAD

**Issue by zfeher79** [Chia-Network/chia-blockchain#5942]
**Describe the bug**
Ploting stops at 1%. 

LOG:
2021-05-24T14:58:52.530  chia.plotting.create_plots       : [32mINFO    [0m Creating 1 plots of size 32, pool public key:  8798e564c8a48edcc2e588b00864cdccde720ee852e9f368a5b2a1556c590fac9a518e7b1702789d8cd81fd269a7ac0d farmer public key: a481ebde145eb9be707b2b977c21a34fea8326e955e701cba810947779c47b38173e8acff02415c9c2d2f90f3be2f739[0m
2021-05-24T14:58:52.620  chia.plotting.create_plots       : [32mINFO    [0m Memo: 8798e564c8a48edcc2e588b00864cdccde720ee852e9f368a5b2a1556c590fac9a518e7b1702789d8cd81fd269a7ac0da481ebde145eb9be707b2b977c21a34fea8326e955e701cba810947779c47b38173e8acff02415c9c2d2f90f3be2f739186f12751c9595ff1f85481a23adef99d3d326c1f87499bbbaf0a7b9b865f6ab[0m
2021-05-24T14:58:52.620  chia.plotting.create_plots       : [32mINFO    [0m Starting plot 1/1[0m
Caught plotting error: Bitfield plotting not supported by CPU
Traceback (most recent call last):
  File "/home/zfeher/chia-blockchain/venv/bin/chia", line 33, in <module>
    sys.exit(load_entry_point('chia-blockchain', 'console_scripts', 'chia')())
  File "/home/zfeher/chia-blockchain/chia/cmds/chia.py", line 77, in main
    cli()  # pylint: disable=no-value-for-parameter
  File "/home/zfeher/chia-blockchain/venv/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/zfeher/chia-blockchain/venv/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/zfeher/chia-blockchain/venv/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/zfeher/chia-blockchain/venv/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/zfeher/chia-blockchain/venv/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/zfeher/chia-blockchain/venv/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/zfeher/chia-blockchain/venv/lib/python3.8/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/zfeher/chia-blockchain/chia/cmds/plots.py", line 135, in create_cmd
    create_plots(Params(), ctx.obj["root_path"])
  File "/home/zfeher/chia-blockchain/chia/plotting/create_plots.py", line 164, in create_plots
    plotter.create_plot_disk(
RuntimeError: std::exception

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

- OS: Ubuntu
- OS Version/Flavor: 20.04
- CPU: Intel® Pentium(R) D CPU 3.00GHz × 2 

**Additional context**

**Comment by lvpcguru** [comment]
'Caught plotting error: Bitfield plotting not supported by CPU'

If using the CLI add the -e argument to your call

If your using the GUI check this option:
https://user-images.githubusercontent.com/17942998/117591514-265dda00-b135-11eb-97f6-09ecff951437.png

**Comment by zfeher79** [comment]
It works!
Thank you so much!

**Comment by lvpcguru** [comment]
Woot! glad to hear it, happy plotting
