### ISSUE TITLE
websockets.exceptions.ConnectionClosedError: code = 1005 (no status code [internal]), no reason

### ISSUE THREAD

**Issue by dorofino** [Chia-Network/chia-blockchain#6012]
Hi, I'm getting this error all over the logs

I'm not sure if is affecting my chances of winning lots.
Any advice will greatly appreciate.

2021-05-25T12:34:33.522 daemon chia.daemon.server         : ERROR    Unexpected exception trying to send to websocket: code = 1005 (no status code [internal]), no reason Traceback (most recent call last):
  File "chia\daemon\server.py", line 187, in safe_handle
  File "websockets\protocol.py", line 555, in send
  File "websockets\protocol.py", line 803, in ensure_open
websockets.exceptions.ConnectionClosedError: code = 1005 (no status code [internal]), no reason

**Comment by lvpcguru** [comment]
this can happen when daemons are left open for some reason. use the cli or services list to make sure chis is full off. The try it again.

CLI:
`chia stop all`

**Comment by saladm2** [comment]
Same issue here. 'chia stop all' then restarting does not fix it. On Ubuntu 20
