### ISSUE TITLE
[BUG] harvester can not reconnect after network problem

### ISSUE THREAD

**Issue by dnsgram** [Chia-Network/chia-blockchain#6047]
**Describe the bug**

I run a full-node farmer on one server and other harvester in diff server.

After harvester Websocket exception,  it stop work and not able to reconnect.

**To Reproduce**

1.  setup a full node 
2.  setup harvester on other server
3. turn out the network of harvester, then turn on network
4. the harvester stop working

**Expected behavior**

 expect harvester auto reconnect to continue work

**Desktop (please complete the following information):**

- OS: Linux
- OS: ubuntu 21.04
- CPU:  7700K
**Additional context**

here is the error message :

```sh
2021-05-26T03:44:59.609 daemon chia.daemon.server         : INFO     Websocket exception. Closing websocket with chia_harvester code = 1006 (connection closed abnormally [internal]), no reason Traceback (most recent call last):
  File "/app/venv/lib/python3.9/site-packages/websockets/protocol.py", line 827, in transfer_data
    message = await self.read_message()
  File "/app/venv/lib/python3.9/site-packages/websockets/protocol.py", line 895, in read_message
    frame = await self.read_data_frame(max_size=self.max_size)
  File "/app/venv/lib/python3.9/site-packages/websockets/protocol.py", line 971, in read_data_frame
    frame = await self.read_frame(max_size)
  File "/app/venv/lib/python3.9/site-packages/websockets/protocol.py", line 1047, in read_frame
    frame = await Frame.read(
  File "/app/venv/lib/python3.9/site-packages/websockets/framing.py", line 105, in read
    data = await reader(2)
  File "/usr/lib/python3.9/asyncio/streams.py", line 721, in readexactly
    raise exceptions.IncompleteReadError(incomplete, n)
asyncio.exceptions.IncompleteReadError: 0 bytes read on a total of 2 expected bytes

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/app/chia/daemon/server.py", line 172, in safe_handle
    async for message in websocket:
  File "/app/venv/lib/python3.9/site-packages/websockets/protocol.py", line 439, in __aiter__
    yield await self.recv()
  File "/app/venv/lib/python3.9/site-packages/websockets/protocol.py", line 509, in recv
    await self.ensure_open()
  File "/app/venv/lib/python3.9/site-packages/websockets/protocol.py", line 803, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedError: code = 1006 (connection closed abnormally [internal]), no reason
```

This project should not goto release with so much bugs.

**Comment by keliew** [comment]
Most likely a misconfiguration on your part...

Would be best to provide more information about your configuration/setup...

**Comment by dnsgram** [comment]
I have 6 harvester and one furl node run for 7 days, I setup the harvester and from the logs I can confirm it is working.


This is working harvester logs:
```sh
2021-05-26T09:03:13.175 harvester chia.harvester.harvester: INFO     0 plots were eligible for farming bf294b72c9... Found 0 proofs. Time: 1.60359 s. Total 343 plots
2021-05-26T09:03:19.948 harvester chia.harvester.harvester: INFO     1 plots were eligible for farming bf294b72c9... Found 0 proofs. Time: 0.18620 s. Total 343 plots
2021-05-26T09:03:29.149 harvester chia.harvester.harvester: INFO     0 plots were eligible for farming bf294b72c9... Found 0 proofs. Time: 0.02301 s. Total 343 plots
2021-05-26T09:03:39.014 harvester chia.harvester.harvester: INFO     1 plots were eligible for farming bf294b72c9... Found 0 proofs. Time: 0.31220 s. Total 343 plots
````

I am not sure what part coud be wrong here, the problem is after network error the harvester stop work until I restart it.

**Comment by keliew** [comment]
What does the farmer's log say?

**Comment by dnsgram** [comment]
farmer logs is too long, I filter with IP:
```sh
2021-05-25T18:53:26.240 farmer farmer_server              : INFO     Connection closed: 192.168.192.122, node id: dfa82286ed7d9aacf85e2d3b1751f59aee5dc75108ad5ec4ea56f3496a3e45e7
2021-05-25T18:53:26.241 farmer chia.farmer.farmer         : INFO     peer disconnected {'host': '192.168.192.122', 'port': 8448}
2021-05-25T19:58:43.894 farmer farmer_server              : INFO     Connection closed: 192.168.192.122, node id: dfa82286ed7d9aacf85e2d3b1751f59aee5dc75108ad5ec4ea56f3496a3e45e7
2021-05-26T00:02:24.379 farmer farmer_server              : INFO     Connection closed: 192.168.192.122, node id: dfa82286ed7d9aacf85e2d3b1751f59aee5dc75108ad5ec4ea56f3496a3e45e7
2021-05-26T01:27:03.757 full_node chia.full_node.full_node: INFO     Block validation time: 0.23562192916870117, cost: 37944740, percent full: 0.345%
2021-05-26T03:44:59.599 farmer farmer_server              : INFO     Connection closed: 192.168.192.122, node id: dfa82286ed7d9aacf85e2d3b1751f59aee5dc75108ad5ec4ea56f3496a3e45e7
2021-05-26T05:36:46.744 farmer farmer_server              : INFO     Connection closed: 192.168.192.122, node id: dfa82286ed7d9aacf85e2d3b1751f59aee5dc75108ad5ec4ea56f3496a3e45e7
2021-05-26T07:24:09.790 farmer farmer_server              : INFO     Connection closed: 192.168.192.122, node id: dfa82286ed7d9aacf85e2d3b1751f59aee5dc75108ad5ec4ea56f3496a3e45e7
2021-05-26T08:26:15.356 farmer farmer_server              : INFO     Connection closed: 192.168.192.122, node id: dfa82286ed7d9aacf85e2d3b1751f59aee5dc75108ad5ec4ea56f3496a3e45e7
2021-05-26T09:06:58.052 farmer farmer_server              : INFO     Connection closed: 192.168.192.122, node id: dfa82286ed7d9aacf85e2d3b1751f59aee5dc75108ad5ec4ea56f3496a3e45e7
2021-05-26T09:19:17.190 full_node chia.full_node.full_node: INFO     ⏲️  Finished signage point 52/64: CC: 71a1c886a4f3e932530119a9cbc34a4d2a874592cb6e7cc8883290eef8355f61 RC: 8f9f691973031f352842deee937140683dfa3a92b39a3a438b9c61da19251681 
```

**Comment by keliew** [comment]
So your setup may not be correct...

**Comment by dnsgram** [comment]
which part ?

**Comment by dnsgram** [comment]
@keliew  can you confirm my setup is wrong that is why I am not get any farmer reward ?

I read somewhere said if I get to see "0 plots were eligible for farming bf294b72c9... Found 0 proofs", then harvester is working.

**Comment by keliew** [comment]
> @keliew can you confirm my setup is wrong that is why I am not get any farmer reward ?
> 
> I read somewhere said if I get to see "0 plots were eligible for farming bf294b72c9... Found 0 proofs", then harvester is working.

It's hard to tell, there are so many possibilities...

Going pass the filter is a good indication that harvester is working. But...do you see something like these?
```
harvester chia.harvester.harvester: WARNING  Looking up qualities on /home/some/plot/name.plot took: 20.710764408111572. This should be below 5 seconds to minimize risk of losing rewards.```

I'd also run a `chia plots check` to see if there are any permission errors or any other errors/warnings.

I'd also de-couple the remote harvester, and run everything locally and see what sort of results I get.

**Comment by dnsgram** [comment]
Thanks for the update, I can not find any of log include " Looking up qualities on",  I copy the ca and init it at every  harvester.

It is hard to keep sync on my harvester and that is why I am not run full-node. seems I waste all me week on this wrong setup.

**Comment by keliew** [comment]
Then maybe it's just the link between your harvester and farmer...Maybe just connect 2-3 harvesters and see what sort of results?

**Comment by dnsgram** [comment]
Thanks for the tips. the link is not stable but it not remain stable for long time.   and some local subnet is stable still i don't get to see " Looking up qualities".  I can not know for sure which part is wrong of my setting,  but I think every expect the harvester cloud recover from a network error, so it is sure a serious bugs require the chia team attention.

**Comment by the-crypt-keeper** [comment]
I am running a Harvester over the internet, it's been steady for 2 weeks but I found it crashed with the same error this morning:

`2021-05-30T09:04:59.116 daemon chia.daemon.server         : INFO     Websocket exception. Closing websocket with chia_harvester code = 1006 (connection closed abnormally [internal]), no reason
`
The internet is sometimes unstable - is it only supported to harvest on a LAN, with perfect networking?

**Comment by the-crypt-keeper** [comment]
As an fun side-effect of this bug the chia_daemon becomes unresponsive and chia CLI commands stop working until it is killed and restarted.  I have arrived at the following work-around:

`#!/bin/bash

while true; do
  FATALS=`tail -n 10 ~/.chia/mainnet/log/debug.log | grep -c "code = 1006 (connection closed abnormally"`
  if [ ! "$FATALS"  == "0" ]; then
    echo "Connection error detected!"
    killall chia_daemon
    sleep 10
    chia start harvester
  else
    echo "All good, going back to sleep"
  fi
  sleep 60
done
`
