### ISSUE TITLE
The machine doesnt plot

### ISSUE THREAD

**Issue by RRCHA000** [Chia-Network/chia-blockchain#6068]
The log seems to be corrupted and it doesnt dellete. Its necessary to shut down the Chia program.

Thats the log

2021-05-26T07:22:33.135  chia.plotting.create_plots       : [32mINFO    [0m Creating 1 plots of size 32, pool public key:  b28f7f73b1c010056e1449dcbf0b5d0e84f184c400c609f86419a98fd23dad81c03c48b3a6733191bfdef2d1c666c06a farmer public key: af15643ece821526b77f13edd8eedad33020844183bd0751cb533d857f67295f9ad3e9208ac5457edb65b8e6d6035dc0[0m
2021-05-26T07:22:33.142  chia.plotting.create_plots       : [32mINFO    [0m Memo: b28f7f73b1c010056e1449dcbf0b5d0e84f184c400c609f86419a98fd23dad81c03c48b3a6733191bfdef2d1c666c06aaf15643ece821526b77f13edd8eedad33020844183bd0751cb533d857f67295f9ad3e9208ac5457edb65b8e6d6035dc0735a8ec6431edf4eef65cbc4365cc20c88443498b00ed3f9bd12165a90bb2821[0m
2021-05-26T07:22:33.142  chia.plotting.create_plots       : [32mINFO    [0m Starting plot 1/1[0m
Caught plotting error: Maximum buckets is 128
[4136] Failed to execute script chia
Traceback (most recent call last):
  File "chia\cmds\chia.py", line 81, in <module>
  File "chia\cmds\chia.py", line 77, in main
  File "click\core.py", line 829, in __call__
  File "click\core.py", line 782, in main
  File "click\core.py", line 1259, in invoke
  File "click\core.py", line 1259, in invoke
  File "click\core.py", line 1066, in invoke
  File "click\core.py", line 610, in invoke
  File "click\decorators.py", line 21, in new_func
  File "chia\cmds\plots.py", line 135, in create_cmd
  File "chia\plotting\create_plots.py", line 176, in create_plots
RuntimeError: Unknown exception

**Comment by AndersStruck** [comment]
What are your settings for the plot?
Seems like you use more than 128 buckets?

`Caught plotting error: Maximum buckets is 128`

**Comment by keliew** [comment]
Stick to default value for bucket size.

**Comment by gromran** [comment]
> When the number of buckets can be raised?

There is no reason for that

**Comment by edufrancioni** [comment]
i dont know what happen


![image](https://user-images.githubusercontent.com/84925252/119859074-6bcb2700-beeb-11eb-9b0b-0e667e3f11f0.png)
