### ISSUE TITLE
[BUG] After Update can't launch both cli and gui

### ISSUE THREAD

**Issue by Zenage98** [Chia-Network/chia-blockchain#6075]
After the update to 1.1.6 i'm not able to launch both the cli and the gui, for an error on the wallet

Simply start chia with powershell

PS C:\Users\*****\AppData\Local\Chia-Blockchain\app-1.1.6\resources\app.asar.unpacked\daemon> ./chia start -r all
chia_harvester: stopped
chia_harvester: started
chia_timelord_launcher: chia_timelord_launcher failed to start. Error: start failed
chia_timelord: started
chia_farmer: stopped
chia_farmer: started
chia_full_node: stopped
chia_full_node: started
chia_wallet: started
PS C:\Users\******\AppData\Local\Chia-Blockchain\app-1.1.6\resources\app.asar.unpacked\daemon> Traceback (most recent call last):
  File "chia\server\start_wallet.py", line 97, in <module>
  File "chia\server\start_wallet.py", line 92, in main
  File "chia\server\start_service.py", line 226, in run_service
  File "asyncio\runners.py", line 43, in run
  File "asyncio\base_events.py", line 587, in run_until_complete
  File "chia\server\start_service.py", line 219, in async_run_service
  File "chia\server\start_service.py", line 93, in __init__
  File "chia\wallet\wallet_node.py", line 317, in set_server
  File "chia\server\node_discovery.py", line 645, in __init__
  File "chia\server\node_discovery.py", line 66, in __init__
  File "dns\resolver.py", line 732, in __init__
  File "dns\resolver.py", line 928, in read_registry
  File "dns\resolver.py", line 891, in _config_win32_fromkey
  File "dns\resolver.py", line 854, in _config_win32_domain
  File "dns\name.py", line 942, in from_text
dns.name.EmptyLabel: A DNS label is empty.
[10016] Failed to execute script start_wallet
Socket error: connect, 10060

- OS: Win 10
- OS Version/Flavor: 1909
- CPU: Ryzen 9 3900X

tryed to delete the full .chia folder in C but i'm unable to make it start

**Comment by keliew** [comment]
looks like you have a DNS issue...

**Comment by keliew** [comment]
Not sure. The only change related to DNS is the [introducer](https://github.com/Chia-Network/chia-blockchain/blob/main/CHANGELOG.md), but I kinda don't think it's the issue, because there's a fallback if the dns introducer isn't in `config.yaml`.

Something else changed at the OS level?

**Comment by Zenage98** [comment]
nothing changed literally reintalled 1.1.5 and it works, update and nothing, reintall work

**Comment by Zenage98** [comment]
new error after update: 
./chia start -r farmer

Daemon not started yet
Starting daemon
chia_harvester: started
chia_timelord_launcher: chia_timelord_launcher failed to start. Error: start failed
chia_timelord: started
chia_farmer: started
chia_full_node: started
chia_wallet: started
PS C:\Users\*****\AppData\Local\Chia-Blockchain\app-1.1.6\resources\app.asar.unpacked\daemon> Traceback (most recent call last):
  File "chia\server\start_wallet.py", line 97, in <module>
  File "chia\server\start_wallet.py", line 92, in main
  File "chia\server\start_service.py", line 226, in run_service
  File "asyncio\runners.py", line 43, in run
Traceback (most recent call last):
  File "asyncio\base_events.py", line 587, in run_until_complete
  File "chia\server\start_farmer.py", line 68, in <module>
  File "chia\server\start_service.py", line 219, in async_run_service
  File "chia\server\start_service.py", line 93, in __init__
  File "chia\server\start_farmer.py", line 64, in main
  File "chia\wallet\wallet_node.py", line 317, in set_server
  File "chia\server\start_service.py", line 226, in run_service
  File "chia\server\node_discovery.py", line 645, in __init__
  File "asyncio\runners.py", line 43, in run
  File "chia\server\node_discovery.py", line 66, in __init__
  File "asyncio\base_events.py", line 587, in run_until_complete
  File "dns\resolver.py", line 732, in __init__
  File "chia\server\start_service.py", line 220, in async_run_service
  File "dns\resolver.py", line 928, in read_registry
  File "chia\server\start_service.py", line 160, in run
  File "dns\resolver.py", line 891, in _config_win32_fromkey
  File "chia\server\start_service.py", line 136, in start
  File "dns\resolver.py", line 854, in _config_win32_domain
  File "chia\server\server.py", line 218, in start_server
  File "dns\name.py", line 942, in from_text
  File "aiohttp\web_runner.py", line 128, in start
dns.name.EmptyLabel:   File "asyncio\base_events.py", line 1389, in create_server
A DNS label is empty.
[18588] OSErrorF: ailed to execute script start_wallet
[Errno 10048] error while attempting to bind on address ('0.0.0.0', 8447): di norma è consentito un solo utilizzo di ogni indirizzo di socket (protocollo/indirizzo di rete/porta)
[19432] Failed to execute script start_farmer
Traceback (most recent call last):
  File "chia\server\start_full_node.py", line 65, in <module>
  File "chia\server\start_full_node.py", line 60, in main
  File "chia\server\start_service.py", line 226, in run_service
  File "asyncio\runners.py", line 43, in run
  File "asyncio\base_events.py", line 587, in run_until_complete
  File "chia\server\start_service.py", line 220, in async_run_service
  File "chia\server\start_service.py", line 160, in run
  File "chia\server\start_service.py", line 136, in start
  File "chia\server\server.py", line 218, in start_server
  File "aiohttp\web_runner.py", line 128, in start
  File "asyncio\base_events.py", line 1389, in create_server
OSError: [Errno 10048] error while attempting to bind on address ('::', 8444, 0, 0): di norma è consentito un solo utilizzo di ogni indirizzo di socket (protocollo/indirizzo di rete/porta)
[19396] Failed to execute script start_full_node
Socket error: connect, 10060

**Comment by nodaone** [comment]
A **solution** that worked for me after trying sooo many things:

1. In this folder "C:\Users(...).chia\mainnet\wallet\db" delete ALL files starting with blockchain_wallet...
2. Safe them somewhere if you like. After deleting these, I manually closed all programs (you could do a restart if you like) and
3. then I started the GUI..
This worked for me, I hope it solves your problems as well. Good luck

**Comment by Zenage98** [comment]
PS C:\Users\******\AppData\Local\Chia-Blockchain\app-1.1.6\resources\app.asar.unpacked\daemon> Traceback (most recent call last):
  File "chia\server\start_wallet.py", line 97, in <module>
  File "chia\server\start_wallet.py", line 92, in main
  File "chia\server\start_service.py", line 226, in run_service
  File "asyncio\runners.py", line 43, in run
  File "asyncio\base_events.py", line 587, in run_until_complete
  File "chia\server\start_service.py", line 219, in async_run_service
  File "chia\server\start_service.py", line 93, in __init__
  File "chia\wallet\wallet_node.py", line 317, in set_server
  File "chia\server\node_discovery.py", line 645, in __init__
  File "chia\server\node_discovery.py", line 66, in __init__
  File "dns\resolver.py", line 732, in __init__
  File "dns\resolver.py", line 928, in read_registry
  File "dns\resolver.py", line 891, in _config_win32_fromkey
  File "dns\resolver.py", line 854, in _config_win32_domain
  File "dns\name.py", line 942, in from_text
dns.name.EmptyLabel: A DNS label is empty.
[7872] Failed to execute script start_wallet

Right now the wallet start but dns label is empty, i've tryed changing my dns on pc and on main router but nothing worked, any ideas

**Comment by keliew** [comment]
Which python version?

**Comment by nodaone** [comment]
> Which python version?

I installed the latest available via the **Microsoft Store** in **Windows 10** (3.9)

**Comment by bobro2** [comment]
Check #6675 I found temporary workaround.
