### ISSUE TITLE
Build failed on MacOS (Catalina v10.15.7)

### ISSUE THREAD

**Issue by frzsombor** [Chia-Network/chia-blockchain#6162]
**Describe the bug**
MacOS build script stops with the following error.
Am I missing something or is this a bug?

```
% sh ./build_scripts/build_macos.sh                                   
Requirement already satisfied: setuptools_scm in /usr/local/lib/python3.9/site-packages (6.0.1)
Requirement already satisfied: setuptools>=45 in /usr/local/lib/python3.9/site-packages (from setuptools_scm) (51.1.1)
/System/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python: can't open file 'installer-version.py': [Errno 2] No such file or directory
WARNING: No environment variable CHIA_INSTALLER_VERSION set. Using 0.0.0.
Chia Installer Version is: 0.0.0
Installing npm and electron packagers
/Users/user/.nvm/versions/node/v12.20.1/bin/electron-installer-dmg -> /Users/user/.nvm/versions/node/v12.20.1/lib/node_modules/electron-installer-dmg/bin/electron-installer-dmg.js
+ electron-installer-dmg@3.0.0
updated 1 package in 2.419s
/Users/user/.nvm/versions/node/v12.20.1/bin/electron-packager -> /Users/user/.nvm/versions/node/v12.20.1/lib/node_modules/electron-packager/bin/electron-packager.js
+ electron-packager@15.2.0
updated 1 package in 5.008s
/Users/user/.nvm/versions/node/v12.20.1/bin/electron-osx-flat -> /Users/user/.nvm/versions/node/v12.20.1/lib/node_modules/electron-osx-sign/bin/electron-osx-flat.js
/Users/user/.nvm/versions/node/v12.20.1/bin/electron-osx-sign -> /Users/user/.nvm/versions/node/v12.20.1/lib/node_modules/electron-osx-sign/bin/electron-osx-sign.js
+ electron-osx-sign@0.5.0
updated 1 package in 3.784s
/Users/user/.nvm/versions/node/v12.20.1/bin/notarize-cli -> /Users/user/.nvm/versions/node/v12.20.1/lib/node_modules/notarize-cli/bin/run
+ notarize-cli@0.1.1
updated 1 package in 3.651s
Create dist/
Create executables with pyinstaller
Requirement already satisfied: pyinstaller==4.2 in /usr/local/lib/python3.9/site-packages (4.2)
Requirement already satisfied: macholib>=1.8 in /usr/local/lib/python3.9/site-packages (from pyinstaller==4.2) (1.14)
Requirement already satisfied: altgraph in /usr/local/lib/python3.9/site-packages (from pyinstaller==4.2) (0.17)
Requirement already satisfied: pyinstaller-hooks-contrib>=2020.6 in /usr/local/lib/python3.9/site-packages (from pyinstaller==4.2) (2021.1)
Requirement already satisfied: setuptools in /usr/local/lib/python3.9/site-packages (from pyinstaller==4.2) (51.1.1)
73 INFO: PyInstaller: 4.2
74 INFO: Python: 3.9.1
85 INFO: Platform: macOS-10.15.7-x86_64-i386-64bit
89 INFO: UPX is not available.
Traceback (most recent call last):
  File "/usr/local/bin/pyinstaller", line 8, in <module>
    sys.exit(run())
  File "/usr/local/lib/python3.9/site-packages/PyInstaller/__main__.py", line 114, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "/usr/local/lib/python3.9/site-packages/PyInstaller/__main__.py", line 65, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/PyInstaller/building/build_main.py", line 725, in main
    build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
  File "/usr/local/lib/python3.9/site-packages/PyInstaller/building/build_main.py", line 672, in build
    exec(code, spec_namespace)
  File "chia/pyinstaller.spec", line 12, in <module>
    ROOT = pathlib.Path(importlib.import_module("chia").__file__).absolute().parent.parent
  File "/usr/local/Cellar/python@3.9/3.9.1_6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'chia'
pyinstaller failed!
```

**To Reproduce**

1. Clone the project
2. Run `sh ./build_scripts/build_macos.sh`

**Expected behavior**
Build script finish without errors

**Desktop (please complete the following information):**

- OS: MacOS
- OS Version/Flavor: Catalina 10.15.7
- CPU: Intel Core i7

**Comment by frzsombor** [comment]
Well, this is not how you build chia on MacOS, that was the problem..
