### ISSUE TITLE
[BUG]can't find plots

### ISSUE THREAD

**Issue by skystone011** [Chia-Network/chia-blockchain#6174]
`2021-05-28T15:08:56.557  chia.plotting.check_plots        : INFO     Summary
2021-05-28T15:08:56.558  chia.plotting.check_plots        : INFO     Found 35 valid plots, total size 3.46431 TiB
2021-05-28T15:08:56.558  chia.plotting.check_plots        : INFO     35 plots of size 32

(venv) root@raspberrypi:/home/chia/chia-blockchain# chia farm summary
Farming status: Farming
Total chia farmed: 0.0
User transaction fees: 0.0
Block rewards: 0.0
Last height farmed: 0
Plot count: 0
Total size of plots: 0.000 GiB
Estimated network space: 12904.110 PiB
Expected time to win: Unknown
`
"chia plots check" discover 35plots, but "chia farm summary" says "plot count: 0"
 i have restart farm many times, and still can't fix it
chia version: 1.1.6
is it a bug?

**Comment by BonTron1** [comment]
Have you added the full path to your plots?

**Comment by skystone011** [comment]
> Have you added the full path to your plots?

chia plots add -d /mnt/usb_disk/chia
`
(venv) root@raspberrypi:/home/chia/chia-blockchain# chia plots show
Directories where plots are being searched for:
Note that subdirectories must be added manually
Add with 'chia plots add -d [dir]' and remove with 'chia plots remove -d [dir]' Scan and check plots with 'chia plots check'

/mnt/usb_disk/chia
`

**Comment by BonTron1** [comment]
Were the plots made with the same key that you're using to farm them? 

Can you post your full log?

**Comment by skystone011** [comment]
> Were the plots made with the same key that you're using to farm them?
> 
> Can you post your full log?

(venv) root@raspberrypi:/home/chia/chia-blockchain# chia plots check
2021-05-29T06:32:45.890  chia.plotting.check_plots        : INFO     Loading plots in config.yaml using plot_tools loading code

2021-05-29T06:32:49.378  chia.plotting.plot_tools         : INFO     Searching directories ['/mnt/usb_disk/chia']
2021-05-29T06:32:49.380  chia.plotting.plot_tools         : INFO     Not checking subdirectory /mnt/usb_disk/chia/backup, subdirectories not added by default
2021-05-29T06:32:49.528  chia.plotting.plot_tools         : INFO     Found plot /mnt/usb_disk/chia/plot-k32-2021-05-27-08-09-109802a40579b7d169d41d9ab63229b3d2058a23132ec264dc3d1d0e9a1a6f76.plot of size 32
2021-05-29T06:32:49.529  chia.plotting.plot_tools         : INFO     Loaded a total of 1 plots of size 0.09898357892507192 TiB, in 0.2956817150115967 seconds
2021-05-29T06:32:49.530  chia.plotting.check_plots        : INFO
2021-05-29T06:32:49.530  chia.plotting.check_plots        : INFO
2021-05-29T06:32:49.531  chia.plotting.check_plots        : INFO     Starting to test each plot with 30 challenges each

2021-05-29T06:32:49.531  chia.plotting.check_plots        : INFO     Testing plot /mnt/usb_disk/chia/plot-k32-2021-05-27-08-09-109802a40579b7d169d41d9ab63229b3d2058a23132ec264dc3d1d0e9a1a6f76.plot k=32
2021-05-29T06:32:49.531  chia.plotting.check_plots        : INFO        Pool public key: b9644db131de078b6c9166e90ca9e805953c024c8c1d985a561db1e6cd286612982f7155dc2eaf12fae47f1039203430
2021-05-29T06:32:49.555  chia.plotting.check_plots        : INFO        Farmer public key: adc37bc7e72c6f601f5ef0bb5f9a95f1f695f1a248415ca73cce253b5f2b9a19539c33fd2cc3afa30e5b60c7320a6d80
2021-05-29T06:32:49.555  chia.plotting.check_plots        : INFO        Local sk: <PrivateKey 0b87a8d49e136b203689e0199a91bf245f71afeb4ca2f7aa4d1aae35ec857c74>
2021-05-29T06:32:50.566  chia.plotting.check_plots        : INFO        Proofs 38 / 30, 1.2667
2021-05-29T06:32:50.566  chia.plotting.check_plots        : INFO
2021-05-29T06:32:50.567  chia.plotting.check_plots        : INFO
2021-05-29T06:32:50.567  chia.plotting.check_plots        : INFO     Summary
2021-05-29T06:32:50.567  chia.plotting.check_plots        : INFO     Found 1 valid plots, total size 0.09898 TiB
2021-05-29T06:32:50.568  chia.plotting.check_plots        : INFO     1 plots of size 32
(venv) root@raspberrypi:/home/chia/chia-blockchain# chia farm summary
Farming status: Farming
Total chia farmed: 0.0
User transaction fees: 0.0
Block rewards: 0.0
Last height farmed: 0
Plot count: 0
Total size of plots: 0.000 GiB
Estimated network space: 13792.752 PiB
Expected time to win: Unknown
Note: log into your key using 'chia wallet show' to see rewards for each key

**Comment by JanKukovic** [comment]
had the same problem. this is how I fixed it:

in .chia/mainnet/config/config.yaml
in harvester farmer_peer, host was set to introducer-eu.chia.net with port 8444, but I believe it should be set to localhost with port 8447 

like so:

harvester:
  chia_ssl_ca:
    crt: config/ssl/ca/chia_ca.crt
    key: config/ssl/ca/chia_ca.key
  farmer_peer:
    host: localhost
    port: 8447

**Comment by McMac** [comment]
Thank you @70hnKuky, it worked!

**Comment by skystone011** [comment]
> had the same problem. this is how I fixed it:
> 
> in .chia/mainnet/config/config.yaml
> in harvester farmer_peer, host was set to introducer-eu.chia.net with port 8444, but I believe it should be set to localhost with port 8447
> 
> like so:
> 
> harvester:
> chia_ssl_ca:
> crt: config/ssl/ca/chia_ca.crt
> key: config/ssl/ca/chia_ca.key
> farmer_peer:
> host: localhost
> port: 8447
mine is already set to 8447, didn't work:

harvester:
  chia_ssl_ca:
    crt: config/ssl/ca/chia_ca.crt
    key: config/ssl/ca/chia_ca.key
  farmer_peer:
    host: localhost
    port: 8447
  logging: *id001
  network_overrides: *id002
  num_threads: 30

**Comment by McMac** [comment]
@skystone011, only difference I have I set it to 127.0.0.1 instead of localhost. I vaguely recall something, doing that when you also use IPv6 if memory serves.

**Comment by skystone011** [comment]
> @skystone011, only difference I have I set it to 127.0.0.1 instead of localhost. I vaguely recall something, doing that when you also use IPv6 if memory serves.

I change all localhost into 127.0.0.1, but nothing changes

**Comment by 70hnKuky** [comment]
can you set log_level  to INFO, restart chia and then paste here last few lines of .chia/mainnet/log/debug.log

**Comment by skystone011** [comment]
> can you set log_level to INFO, restart chia and then paste here last few lines of .chia/mainnet/log/debug.log

2021-05-30T11:47:22.737 harvester harvester_server        : INFO     Cannot connect to host 61.146.17.70:8444 ssl:True [SSLCertVerificationError:$
2021-05-30T11:47:23.045 wallet chia.wallet.wallet_blockchain: INFO     Started 2 processes for block validation
2021-05-30T11:47:24.596 farmer farmer                     : INFO     Reconnecting to peer {'host': '127.0.0.1', 'port': 8444}
2021-05-30T11:47:24.602 farmer farmer_server              : INFO     Cannot connect to host 127.0.0.1:8444 ssl:<ssl.SSLContext object at 0x7f8c6c$
2021-05-30T11:47:25.742 harvester harvester               : INFO     Reconnecting to peer {'host': '61.146.17.70', 'port': 8444}
2021-05-30T11:47:25.827 harvester asyncio                 : ERROR    SSL handshake failed on verifying the certificate
protocol: <asyncio.sslproto.SSLProtocol object at 0x7faf105a90>
transport: <_SelectorSocketTransport fd=6 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/usr/lib/python3.7/asyncio/sslproto.py", line 625, in _on_handshake_complete
    raise handshake_exc
  File "/usr/lib/python3.7/asyncio/sslproto.py", line 189, in feed_ssldata
    self._sslobj.do_handshake()
  File "/usr/lib/python3.7/ssl.py", line 763, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate signature failure (_ssl.c:1056)
2021-05-30T11:47:25.829 harvester asyncio                 : ERROR    SSL error in data received
protocol: <asyncio.sslproto.SSLProtocol object at 0x7faf105a90>
transport: <_SelectorSocketTransport closing fd=6 read=idle write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/usr/lib/python3.7/asyncio/sslproto.py", line 526, in data_received
    ssldata, appdata = self._sslpipe.feed_ssldata(data)
  File "/usr/lib/python3.7/asyncio/sslproto.py", line 189, in feed_ssldata
    self._sslobj.do_handshake()
  File "/usr/lib/python3.7/ssl.py", line 763, in do_handshake
    self._sslobj.do_handshake()
  File "/usr/lib/python3.7/ssl.py", line 763, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate signature failure (_ssl.c:1056)
2021-05-30T11:47:28.923 harvester asyncio                 : ERROR    SSL error in data received
protocol: <asyncio.sslproto.SSLProtocol object at 0x7faef6ceb8>
transport: <_SelectorSocketTransport closing fd=6 read=idle write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/usr/lib/python3.7/asyncio/sslproto.py", line 526, in data_received
    ssldata, appdata = self._sslpipe.feed_ssldata(data)
  File "/usr/lib/python3.7/asyncio/sslproto.py", line 189, in feed_ssldata
    self._sslobj.do_handshake()
  File "/usr/lib/python3.7/ssl.py", line 763, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate signature failure (_ssl.c:1056)
2021-05-30T11:47:28.925 harvester harvester_server        : INFO     Cannot connect to host 61.146.17.70:8444 ssl:True [SSLCertVerificationError:$
2021-05-30T11:47:30.616 farmer farmer                     : INFO     Reconnecting to peer {'host': '127.0.0.1', 'port': 8444}
2021-05-30T11:47:30.623 farmer farmer_server              : INFO     Cannot connect to host 127.0.0.1:8444 ssl:<ssl.SSLContext object at 0x7f8c25$

**Comment by 70hnKuky** [comment]
2021-05-30T11:47:25.742 harvester harvester : INFO Reconnecting to peer {'host': '61.146.17.70', 'port': 8444}

harvester should connect to localhost on port 8447.  check your config.

**Comment by skystone011** [comment]
> 2021-05-30T11:47:25.742 harvester harvester : INFO Reconnecting to peer {'host': '61.146.17.70', 'port': 8444}
> 
> harvester should connect to localhost on port 8447. check your config.
> this is in my working config:
> 
> farmer:
> full_node_peer:
> host: localhost
> port: 8444
> harvester_peer:
> host: localhost
> port: 8448
> 
> full_node:
> database_path: db/blockchain_v1_CHALLENGE.sqlite
> enable_upnp: true
> farmer_peer:
> host: localhost
> port: 8447
> introducer_peer:
> host: introducer.chia.net
> port: 8444
> logging: *id001
> 
> harvester:
> chia_ssl_ca:
> crt: config/ssl/ca/chia_ca.crt
> key: config/ssl/ca/chia_ca.key
> farmer_peer:
> host: localhost
> port: 8447
> logging: *id001
> network_overrides: *id002

it works!   Thank you, 70hnKuky！
