### ISSUE TITLE
[BUG] Fresh installed node not connecting to any peers - not syncing

### ISSUE THREAD

**Issue by mahaupt** [Chia-Network/chia-blockchain#6191]
**Describe the bug**
I installed a fresh Ubuntu 20.04 LTS server according to the INSTALL instructions
Started chia with "chia init" and "chia start node"
Node never connects or syncs. "chia show -c" shows nothing
Trying "chia show -a" with a valid peer results in the following error:

`2021-05-28T23:44:52.147 full_node chia.rpc.rpc_server     : WARNING  Error while handling message: Traceback (most recent call last):
  File "/home/marcel/chia-blockchain/chia/rpc/rpc_server.py", line 81, in inner
    res_object = await f(request_data)
  File "/home/marcel/chia-blockchain/chia/rpc/rpc_server.py", line 161, in open_connection
    raise ValueError("Start client failed, or server is not set")
ValueError: Start client failed, or server is not set`

Also tried with a fresh CentOs 8 installation and got the same error.

**Comment by mahaupt** [comment]
I can confirm that the server is not behind a NAT and the port 8444 is directly accessable

**Comment by mahaupt** [comment]
`2021-05-29T00:07:26.558 full_node chia.full_node.full_node: INFO     Initializing blockchain from disk
2021-05-29T00:07:26.560 full_node chia.consensus.blockchain: INFO     Started 1 processes for block validation
2021-05-29T00:07:26.563 full_node chia.full_node.full_node: INFO     Initialized with empty blockchain time taken: 0s
2021-05-29T00:07:26.596 full_node full_node_server        : INFO     Started listening on port: 8444
2021-05-29T00:07:26.596 full_node full_node               : INFO     Started full_node service on network_id: mainnet
2021-05-29T00:07:28.057 full_node chia.full_node.full_node: INFO     Received 32 peers from DNS seeder.
2021-05-29T00:07:30.569 full_node chia.server.upnp        : INFO     UPnP failed. This is not required to run chia, it allows incoming connections from other peers.
2021-05-29T00:07:30.570 full_node chia.server.upnp        : INFO     No UPnP device discovered
2021-05-29T00:09:09.149 full_node chia.rpc.rpc_server     : WARNING  Error while handling message: Traceback (most recent call last):
  File "/home/marcel/chia-blockchain/chia/rpc/rpc_server.py", line 81, in inner
    res_object = await f(request_data)
  File "/home/marcel/chia-blockchain/chia/rpc/rpc_server.py", line 161, in open_connection
    raise ValueError("Start client failed, or server is not set")
ValueError: Start client failed, or server is not set

2021-05-29T00:09:55.645 full_node chia.full_node.full_node: INFO     Received 32 peers from DNS seeder.`

this is my info log right after startup
this message is coming over and over again:

` full_node chia.full_node.full_node: INFO     Received 32 peers from DNS seeder.`

**Comment by sobertram** [comment]
"File "/home/marcel/chia-blockchain/chia/rpc/rpc_server.py", line 161, in open_connection
raise ValueError("Start client failed, or server is not set")
`ValueError: Start client failed, or server is not set`"

That seems to be your issue. Not a synch issue. Try and figure out why you  are getting that error. make sure log mode is debug and not info and hopefully you can get more information.
