### ISSUE TITLE
about 1 in 10 plottings stalling, usually without an error [BUG]

### ISSUE THREAD

**Issue by number435398** [Chia-Network/chia-blockchain#6223]
When plotting in windows 10 (v1.16 of the program), about 1 in every 10 plots I have just stall at some point, usually with no error at all.  Anywhere from ~13% to 90+%.  One did give an error:

Caught plotting error: Matches do not match with number of write entries 4294919162 4294919127
[27452] Failed to execute script chia
Traceback (most recent call last):
  File "chia\cmds\chia.py", line 81, in <module>
  File "chia\cmds\chia.py", line 77, in main
  File "click\core.py", line 829, in __call__
  File "click\core.py", line 782, in main
  File "click\core.py", line 1259, in invoke
  File "click\core.py", line 1259, in invoke
  File "click\core.py", line 1066, in invoke
  File "click\core.py", line 610, in invoke
  File "click\decorators.py", line 21, in new_func
  File "chia\cmds\plots.py", line 135, in create_cmd
  File "chia\plotting\create_plots.py", line 176, in create_plots
RuntimeError: Unknown exception

**Comment by zeafynx** [comment]
You may want to see #5552

**Comment by number435398** [comment]
Interesting. Though this error was the first error I saw for my failing plots and it hasn't happened since. I think I've had nearly 10 plots totally stall (for many hours at a time) in the last week.  This error was for only one as a possible reference point.
