### ISSUE TITLE
[BUG] can't farm error at log -debug.log

### ISSUE THREAD

**Issue by WHYbugNOW** [Chia-Network/chia-blockchain#6238]
i think that i never farmed, i am trying for 45 days and i can't try to win, Help please.

my log:

2021-05-26T16:36:11.035 full_node full_node_server        : ERROR    Exception: Failed to fetch block 340772 from None, timed out, None. Traceback (most recent call last):
  File "chia\server\server.py", line 526, in wrapped_coroutine
  File "chia\full_node\full_node_api.py", line 104, in new_peak
  File "chia\full_node\full_node.py", line 373, in new_peak
  File "chia\full_node\full_node.py", line 322, in short_sync_backtrack
  File "chia\full_node\full_node.py", line 307, in short_sync_backtrack
ValueError: Failed to fetch block 340772 from None, timed out

2021-05-26T16:36:11.038 full_node full_node_server        : ERROR    Exception: Failed to fetch block 340772 from None, timed out <class 'ValueError'>, closing connection None. Traceback (most recent call last):
  File "chia\server\server.py", line 536, in api_call
  File "asyncio\tasks.py", line 414, in wait_for
  File "chia\server\server.py", line 533, in wrapped_coroutine
  File "chia\server\server.py", line 526, in wrapped_coroutine
  File "chia\full_node\full_node_api.py", line 104, in new_peak
  File "chia\full_node\full_node.py", line 373, in new_peak
  File "chia\full_node\full_node.py", line 322, in short_sync_backtrack
  File "chia\full_node\full_node.py", line 307, in short_sync_backtrack
ValueError: Failed to fetch block 340772 from None, timed out

2021-05-26T18:08:36.978 full_node full_node_server        : WARNING  Cannot write to closing transport 98.221.215.30
2021-05-27T20:35:43.420 full_node full_node_server        : WARNING  Cannot write to closing transport 79.144.101.95
2021-05-28T12:18:42.456 full_node full_node_server        : WARNING  Cannot write to closing transport 103.130.28.11
2021-05-28T13:44:49.665 full_node full_node_server        : WARNING  Cannot write to closing transport 80.103.141.227
2021-05-28T14:47:49.566 full_node full_node_server        : WARNING  Cannot write to closing transport 178.206.230.36
2021-05-29T06:44:52.341 full_node full_node_server        : WARNING  Cannot write to closing transport 98.235.41.116
2021-05-29T13:06:21.289 full_node full_node_server        : WARNING  Cannot write to closing transport 68.9.48.23
2021-05-29T13:11:59.561 full_node full_node_server        : WARNING  Banning 84.192.74.25 for 10 seconds
2021-05-29T13:11:59.562 full_node full_node_server        : WARNING  Invalid handshake with peer {'host': '84.192.74.25', 'port': 8444}. Maybe the peer is running old software.
2021-05-29T16:39:00.950 full_node full_node_server        : WARNING  Banning 183.196.59.174 for 10 seconds
2021-05-29T16:39:00.956 full_node full_node_server        : WARNING  Invalid handshake with peer {'host': '183.196.59.174', 'port': 8444}. Maybe the peer is running old software.
2021-05-29T20:23:55.708 full_node chia.full_node.full_node: ERROR    Exception in create outbound connections: 
2021-05-29T20:23:55.710 full_node chia.full_node.full_node: ERROR    Traceback: Traceback (most recent call last):
  File "chia\server\node_discovery.py", line 378, in _connect_to_peers
  File "asyncio\tasks.py", line 595, in sleep
concurrent.futures._base.CancelledError

2021-05-29T20:24:00.111 daemon asyncio                    : ERROR    Task exception was never retrieved
future: <Task finished coro=<kill_service() done, defined at chia\daemon\server.py:846> exception=AttributeError("'list' object has no attribute 'pid'")>
Traceback (most recent call last):
  File "chia\daemon\server.py", line 854, in kill_service
  File "chia\daemon\server.py", line 818, in kill_process
AttributeError: 'list' object has no attribute 'pid'
2021-05-29T21:09:29.745 full_node full_node_server        : WARNING  Cannot write to closing transport 120.194.55.194
2021-05-30T00:49:16.540 full_node full_node_server        : WARNING  Cannot write to closing transport 120.194.55.194
2021-05-30T11:46:02.830 full_node chia.full_node.full_node: ERROR    Exception in create outbound connections: 
2021-05-30T11:46:02.832 full_node chia.full_node.full_node: ERROR    Traceback: Traceback (most recent call last):
  File "chia\server\node_discovery.py", line 378, in _connect_to_peers
  File "asyncio\tasks.py", line 595, in sleep
concurrent.futures._base.CancelledError

**Comment by WHYbugNOW** [comment]
anyone can help ?
