### ISSUE TITLE
[BUG] panic when  harvester remote 

### ISSUE THREAD

**Issue by vipwzw** [Chia-Network/chia-blockchain#6303]
**Describe the bug**
2021-05-31T20:20:14.943 harvester chia.harvester.harvester: INFO     1 plots were eligible for farming 7660c22aa2... Found 0 proofs. Time: 0.79666 s. Total 687 plots
2021-05-31T20:20:19.596 harvester chia.harvester.harvester: INFO     3 plots were eligible for farming 7660c22aa2... Found 0 proofs. Time: 0.56171 s. Total 687 plots
2021-05-31T20:20:30.632 daemon chia.daemon.server         : INFO     Websocket exception. Closing websocket with chia_harvester code = 1006 (connection closed abnormally [internal]), no reason Traceback (most recent call last):
  File "/root/chia-blockchain/venv/lib/python3.8/site-packages/websockets/protocol.py", line 827, in transfer_data
    message = await self.read_message()
  File "/root/chia-blockchain/venv/lib/python3.8/site-packages/websockets/protocol.py", line 895, in read_message
    frame = await self.read_data_frame(max_size=self.max_size)
  File "/root/chia-blockchain/venv/lib/python3.8/site-packages/websockets/protocol.py", line 971, in read_data_frame
    frame = await self.read_frame(max_size)
  File "/root/chia-blockchain/venv/lib/python3.8/site-packages/websockets/protocol.py", line 1047, in read_frame
    frame = await Frame.read(
  File "/root/chia-blockchain/venv/lib/python3.8/site-packages/websockets/framing.py", line 105, in read
    data = await reader(2)
  File "/usr/lib/python3.8/asyncio/streams.py", line 721, in readexactly
    raise exceptions.IncompleteReadError(incomplete, n)
asyncio.exceptions.IncompleteReadError: 0 bytes read on a total of 2 expected bytes

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/chia-blockchain/chia/daemon/server.py", line 172, in safe_handle
    async for message in websocket:
  File "/root/chia-blockchain/venv/lib/python3.8/site-packages/websockets/protocol.py", line 439, in __aiter__
    yield await self.recv()
  File "/root/chia-blockchain/venv/lib/python3.8/site-packages/websockets/protocol.py", line 509, in recv
    await self.ensure_open()
  File "/root/chia-blockchain/venv/lib/python3.8/site-packages/websockets/protocol.py", line 803, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedError: code = 1006 (connection closed abnormally [internal]), no reason

**To Reproduce**

chia start harvester -r
wait some time
system may be panic

**Desktop (please complete the following information):**

- OS: linux 
- OS Version/Flavor: Linux wzw 5.8.0-53-generic #60~20.04.1-Ubuntu SMP Thu May 6 09:52:46 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
- CPU:  Intel(R) Core(TM) i5-10400 CPU @ 2.90GHz

**Comment by KmBooy** [comment]
![image](https://user-images.githubusercontent.com/35790216/120278817-5473ab80-c2e8-11eb-90f1-2cbdfd76b179.png)
I don't know how to solve this problem

**Comment by lpaln** [comment]
This is still happening as of today. How to get devs attention??

![image](https://user-images.githubusercontent.com/80719229/125706344-b4744aed-6c6f-4f71-945b-452f538bdad4.png)
