### ISSUE TITLE
[BUG] Can't plot, runs out of ram

### ISSUE THREAD

**Issue by lasoniss** [Chia-Network/chia-blockchain#632]
I'm running Chia 1.0b19.dev1 on an Ubuntu 20.04 machine with 32 gig of ram. Whenever I try to plot I get messages of the sort 

"Caught plotting error: Not enough memory for sort in memory. Need to sort 0.471054GiB"

The last time I tried it was during "Compressing tables 2 and 3". Interestingly it was able to do tables 1 and 2 fine.

**Comment by hoffmang9** [comment]
This is a known issue that is fixed in Beta 19. You can revert to Beta 17 until Beta 19 is out.

**Comment by 6enno** [comment]
@hoffmang9 we're running on RC2 and still seem to be getting the following:

```
Caught plotting error: Not enough memory for sort in memory. Need to sort 4.082846GiB
Traceback (most recent call last):
  File "/home/hectore/chia-blockchain/venv/bin/chia", line 33, in <module>
    sys.exit(load_entry_point('chia-blockchain', 'console_scripts', 'chia')())
  File "/home/hectore/chia-blockchain/src/cmds/chia.py", line 59, in main
    return chia(args, parser)
  File "/home/hectore/chia-blockchain/src/cmds/chia.py", line 53, in chia
    return args.function(args, parser)
  File "/home/hectore/chia-blockchain/src/cmds/plots.py", line 192, in handler
    create_plots(args, root_path)
  File "/home/hectore/chia-blockchain/src/plotting/create_plots.py", line 186, in create_plots
    args.nobitfield,
RuntimeError: std::exception
```

Any advice?

**Comment by hoffmang9** [comment]
you aren't allocating enough memory - either you're using too many buckets or not enough ram. See https://www.chia.net/2021/02/22/plotting-basics.html
