### ISSUE TITLE
Status Not Synced

### ISSUE THREAD

**Issue by DavidNestak** [Chia-Network/chia-blockchain#6334]
Hello, I have some plots and I was farming about 14-21 days, everything was fine but one day ago SYNC doesn't work and unfortunatelly I have a **Status: Not Synced** now. I didn't do any change, my computer was still turned on but suddenly it doesn't work. Could you help me pleae?

My version is 1.1.6
Windows 10

Thanks a lot
David

**Comment by SRMJ** [comment]
i have the same problem

**Comment by Atorr1** [comment]
The same problem
My log:

2021-06-01T19:50:48.004 full_node chia.full_node.full_node: ERROR    Exception while querying DNS server: The DNS response does not contain an answer to the question: dns-introducer.chia.net. IN A
2021-06-01T20:17:36.270 full_node chia.full_node.full_node: ERROR    Exception while querying DNS server: The DNS response does not contain an answer to the question: dns-introducer.chia.net. IN A
2021-06-01T20:44:23.997 full_node chia.full_node.full_node: ERROR    Exception while querying DNS server: The DNS response does not contain an answer to the question: dns-introducer.chia.net. IN A
2021-06-01T21:11:12.005 full_node chia.full_node.full_node: ERROR    Exception while querying DNS server: The DNS response does not contain an answer to the question: dns-introducer.chia.net. IN A
2021-06-01T21:38:00.221 full_node chia.full_node.full_node: ERROR    Exception while querying DNS server: The DNS response does not contain an answer to the question: dns-introducer.chia.net. IN A
2021-06-01T22:04:48.058 full_node chia.full_node.full_node: ERROR    Exception while querying DNS server: The DNS response does not contain an answer to the question: dns-introducer.chia.net. IN A
2021-06-01T22:31:36.712 full_node chia.full_node.full_node: ERROR    Exception while querying DNS server: The DNS response does not contain an answer to the question: dns-introducer.chia.net. IN A
2021-06-01T22:58:24.178 full_node chia.full_node.full_node: ERROR    Exception while querying DNS server: The DNS response does not contain an answer to the question: dns-introducer.chia.net. IN A
2021-06-01T23:25:12.726 full_node chia.full_node.full_node: ERROR    Exception while querying DNS server: The DNS response does not contain an answer to the question: dns-introducer.chia.net. IN A
2021-06-01T23:52:00.222 full_node chia.full_node.full_node: ERROR    Exception while querying DNS server: The DNS response does not contain an answer to the question: dns-introducer.chia.net. IN A
2021-06-02T00:18:48.068 full_node chia.full_node.full_node: ERROR    Exception while querying DNS server: The DNS response does not contain an answer to the question: dns-introducer.chia.net. IN A
2021-06-02T00:45:43.694 full_node chia.full_node.full_node: ERROR    Exception while querying DNS server: The DNS response does not contain an answer to the question: dns-introducer.chia.net. IN A
2021-06-02T01:12:31.001 full_node chia.full_node.full_node: ERROR    Exception while querying DNS server: The DNS response does not contain an answer to the question: dns-introducer.chia.net. IN A
2021-06-02T01:39:18.972 full_node chia.full_node.full_node: ERROR    Exception while querying DNS server: The DNS response does not contain an answer to the question: dns-introducer.chia.net. IN A
2021-06-02T02:06:07.228 full_node chia.full_node.full_node: ERROR    Exception while querying DNS server: The DNS response does not contain an answer to the question: dns-introducer.chia.net. IN A
2021-06-02T02:32:55.147 full_node chia.full_node.full_node: ERROR    Exception while querying DNS server: The DNS response does not contain an answer to the question: dns-introducer.chia.net. IN A
2021-06-02T02:59:43.268 full_node chia.full_node.full_node: ERROR    Exception while querying DNS server: The DNS response does not contain an answer to the question: dns-introducer.chia.net. IN A
2021-06-02T03:26:31.711 full_node chia.full_node.full_node: ERROR    Exception while querying DNS server: The DNS response does not contain an answer to the question: dns-introducer.chia.net. IN A
2021-06-02T03:53:19.063 full_node chia.full_node.full_node: ERROR    Exception while querying DNS server: The DNS response does not contain an answer to the question: dns-introducer.chia.net. IN A
2021-06-02T04:20:07.788 full_node chia.full_node.full_node: ERROR    Exception while querying DNS server: The DNS response does not contain an answer to the question: dns-introducer.chia.net. IN A
2021-06-02T04:46:55.130 full_node chia.full_node.full_node: ERROR    Exception while querying DNS server: The DNS response does not contain an answer to the question: dns-introducer.chia.net. IN A
2021-06-02T05:13:43.134 full_node chia.full_node.full_node: ERROR    Exception while querying DNS server: The DNS response does not contain an answer to the question: dns-introducer.chia.net. IN A
2021-06-02T05:40:30.973 full_node chia.full_node.full_node: ERROR    Exception while querying DNS server: The DNS response does not contain an answer to the question: dns-introducer.chia.net. IN A
2021-06-02T06:07:19.875 full_node chia.full_node.full_node: ERROR    Exception while querying DNS server: The DNS response does not contain an answer to the question: dns-introducer.chia.net. IN A
2021-06-02T06:34:07.863 full_node chia.full_node.full_node: ERROR    Exception while querying DNS server: The DNS response does not contain an answer to the question: dns-introducer.chia.net. IN A
2021-06-02T07:00:55.878 full_node chia.full_node.full_node: ERROR    Exception while querying DNS server: The DNS response does not contain an answer to the question: dns-introducer.chia.net. IN A
2021-06-02T07:27:43.088 full_node chia.full_node.full_node: ERROR    Exception while querying DNS server: The DNS response does not contain an answer to the question: dns-introducer.chia.net. IN A
2021-06-02T07:54:31.169 full_node chia.full_node.full_node: ERROR    Exception while querying DNS server: The DNS response does not contain an answer to the question: dns-introducer.chia.net. IN A
2021-06-02T08:19:12.126 full_node chia.rpc.rpc_server     : WARNING  Error while handling message: Traceback (most recent call last):
  File "/root/chia-blockchain/chia/rpc/rpc_server.py", line 81, in inner
    res_object = await f(request_data)
  File "/root/chia-blockchain/chia/rpc/rpc_server.py", line 161, in open_connection
    raise ValueError("Start client failed, or server is not set")
ValueError: Start client failed, or server is not set

2021-06-02T08:21:19.848 full_node chia.full_node.full_node: ERROR    Exception while querying DNS server: The DNS response does not contain an answer to the question: dns-introducer.chia.net. IN A


The error a got when a try use comand like:  chia show -a introducer-eu.chia.net:8444 so I got this in log:

2021-06-02T08:19:12.126 full_node chia.rpc.rpc_server     : WARNING  Error while handling message: Traceback (most recent call last):
  File "/root/chia-blockchain/chia/rpc/rpc_server.py", line 81, in inner
    res_object = await f(request_data)
  File "/root/chia-blockchain/chia/rpc/rpc_server.py", line 161, in open_connection
    raise ValueError("Start client failed, or server is not set")
ValueError: Start client failed, or server is not set

**Comment by softwareuser99** [comment]
did you make any changes in the config yaml that may have rendered the config invalid? Just a guess here...

**Comment by Ralle001** [comment]
Have a similar problem. Mine just simple starts farming and after a few hours it says not farming, then waiting for a few hours and it starts farming again. I dont know what is going on.

**Comment by DevelopDaily** [comment]
@DavidNestak "...delete all files from Users/Nickname/chia folder..." won't work because a fresh system I installed today (June 5) does not work. Here is the error message in the log:

`2021-06-05T14:05:48.879 full_node chia.full_node.full_node: ERROR    Exception while querying DNS server: The DNS operation timed out after 32.00606679916382 seconds`

So, I ping the `dns-introducer.chia.net` and get this result:

`ping: dns-introducer.chia.net: Temporary failure in name resolution`

To rule out my own machine problems, I go to a random public ping website ([https://www.site24x7.com/ping-test.html](https://www.site24x7.com/ping-test.html)) to do the ping test, and get the following result. In fact, doing the ping test repeatedly has never yielded a 100% good result. The chia dns introducer is supposed to be a mission critical service, isn't it? It turns out to be the single point of failure now.

![chia-dns-introducer](https://user-images.githubusercontent.com/54299975/120901682-661bc280-c60a-11eb-86ee-248e4c975087.png)
