### ISSUE TITLE
[BUG] [5404] Failed to execute script chia RuntimeError: bad allocation

### ISSUE THREAD

**Issue by mub1jo** [Chia-Network/chia-blockchain#6367]
Caught plotting error: bad allocation
[5404] Failed to execute script chia
Traceback (most recent call last):
  File "chia\cmds\chia.py", line 81, in <module>
  File "chia\cmds\chia.py", line 77, in main
  File "click\core.py", line 829, in __call__
  File "click\core.py", line 782, in main
  File "click\core.py", line 1259, in invoke
  File "click\core.py", line 1259, in invoke
  File "click\core.py", line 1066, in invoke
  File "click\core.py", line 610, in invoke
  File "click\decorators.py", line 21, in new_func
  File "chia\cmds\plots.py", line 135, in create_cmd
  File "chia\plotting\create_plots.py", line 176, in create_plots
RuntimeError: bad allocation

- OS: Windows 10
- OS Version/Flavor: 20H2
- CPU: Intel i5-9600KF (OC)
- RAM 16Gb (OC)

Set plotting only 2 plots at a time with a delay second plot start after phase 1,
When add the other queue the old plot will crush on some how it's stop plotting with no errors or got a  blue srceen. and this time it's got an error.

Once plotting with powershell it's just stop plotting and turn back to 
C:\Users\xxxx\AppData\Local\chia-blockchain\app-1.1.6\resources\app.asar.unpacked\daemon>
guess chia.exe is close itself with no any errors showing on sreen, really want to know why it's keep stop plotting.

**Comment by faheem2100** [comment]
![120755193-a3356700-c4db-11eb-8ed8-9ef43b8cecc7](https://user-images.githubusercontent.com/85276668/120969444-294de980-c738-11eb-9e2e-f49eb2033d72.jpg)

**Comment by faheem2100** [comment]
I also have the same problem.  Please advise on it.  Thanks
