### ISSUE TITLE
[BUG] sh install-timelord.sh

### ISSUE THREAD

**Issue by wearechiarex** [Chia-Network/chia-blockchain#6418]
**Describe the bug**
The following error occurs while installing Timelord on Centos 8. We have installed the operating system for CMake 3.20.2. Error details:

`
(venv) [root@node chia-blockchain]# sh install-timelord.sh
Timelord requires CMake 3.14+ to compile vdf_client.
Python version: python3.7
install-timelord.sh: line 43: type: apt-get: not found
dnf is /usr/bin/dnf
Found RedHat.
Installing chiavdf from source on RedHat/CentOS/Fedora
yum install gcc gcc-c++ gmp-devel python3-devel libtool make autoconf automake openssl-devel libevent-devel boost-devel python3 -y
Last metadata expiration check: 1:01:03 ago on Fri 04 Jun 2021 11:51:11 AM +03.
Package gcc-8.4.1-1.el8.x86_64 is already installed.
Package gcc-c++-8.4.1-1.el8.x86_64 is already installed.
Package gmp-devel-1:6.1.2-10.el8.x86_64 is already installed.
Package python36-devel-3.6.8-2.module_el8.4.0+790+083e3d81.x86_64 is already installed.
Package libtool-2.4.6-25.el8.x86_64 is already installed.
Package make-1:4.2.1-10.el8.x86_64 is already installed.
Package autoconf-2.69-27.el8.noarch is already installed.
Package automake-1.16.1-7.el8.noarch is already installed.
Package openssl-devel-1:1.1.1g-15.el8_3.x86_64 is already installed.
Package libevent-devel-2.1.8-5.el8.x86_64 is already installed.
Package boost-devel-1.66.0-10.el8.x86_64 is already installed.
Package python36-3.6.8-2.module_el8.4.0+790+083e3d81.x86_64 is already installed.
Dependencies resolved.
Nothing to do.
Complete!
venv/bin/python -m pip install --force --no-binary chiavdf chiavdf==1.0.1
Collecting chiavdf==1.0.1
  Using cached chiavdf-1.0.1.tar.gz (639 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Building wheels for collected packages: chiavdf
  Building wheel for chiavdf (PEP 517) ... error
  ERROR: Command errored out with exit status 1:
   command: /root/chia-blockchain/venv/bin/python /root/chia-blockchain/venv/lib/python3.7/site-packages/pip/_vendor/pep517/in_process/_in_process.py build_wheel /tmp/tmpgbjqx1sb
       cwd: /tmp/pip-install-oi20ow9s/chiavdf_54bad5ded7c345aa9ec8b0e4175292d9
  Complete output (81 lines):
  running bdist_wheel
  running build
  running build_ext
  -- The C compiler identification is GNU 8.4.1
  -- The CXX compiler identification is GNU 8.4.1
  -- Detecting C compiler ABI info
  -- Detecting C compiler ABI info - done
  -- Check for working C compiler: /usr/bin/cc - skipped
  -- Detecting C compile features
  -- Detecting C compile features - done
  -- Detecting CXX compiler ABI info
  -- Detecting CXX compiler ABI info - done
  -- Check for working CXX compiler: /usr/bin/c++ - skipped
  -- Detecting CXX compile features
  -- Detecting CXX compile features - done
  GMP_INCLUDES=/usr/include
  -- Found GMP: /usr/include (Required is at least version "5.1.0")
  GMP_INCLUDES=/usr/include
  -- Found GMPXX: /usr/lib64/libgmpxx.so
  -- pybind11 v2.6.2
  -- Found PythonInterp: /root/chia-blockchain/venv/bin/python (found version "3.7.7")
  -- Found PythonLibs: /usr/local/lib/libpython3.7m.a
  -- Performing Test HAS_FLTO
  -- Performing Test HAS_FLTO - Success
  -- Configuring done
  -- Generating done
  -- Build files have been written to: /tmp/pip-install-oi20ow9s/chiavdf_54bad5ded7c345aa9ec8b0e4175292d9
  [ 33%] Building C object CMakeFiles/chiavdf.dir/refcode/lzcnt.c.o
  [ 33%] Building CXX object CMakeFiles/chiavdf.dir/python_bindings/fastvdf.cpp.o
  [ 50%] Building C object CMakeFiles/verifier_test.dir/refcode/lzcnt.c.o
  [ 66%] Building CXX object CMakeFiles/verifier_test.dir/verifier_test.cpp.o
  [ 83%] Linking CXX executable verifier_test
  [ 83%] Built target verifier_test
  [100%] Linking CXX shared module build/lib.linux-x86_64-3.7/chiavdf.cpython-37m-x86_64-linux-gnu.so
  [100%] Built target chiavdf
  running build_hook
  make: *** [Makefile.vdf-client:44: asm_compiled.s] Segmentation fault (core dumped)
  Traceback (most recent call last):
    File "/root/chia-blockchain/venv/lib/python3.7/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 280, in <module>
      main()
    File "/root/chia-blockchain/venv/lib/python3.7/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 263, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/root/chia-blockchain/venv/lib/python3.7/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 205, in build_wheel
      metadata_directory)
    File "/tmp/pip-build-env-bo4dl8cl/overlay/lib/python3.7/site-packages/setuptools/build_meta.py", line 222, in build_wheel
      wheel_directory, config_settings)
    File "/tmp/pip-build-env-bo4dl8cl/overlay/lib/python3.7/site-packages/setuptools/build_meta.py", line 207, in _build_with_temp_dir
      self.run_setup()
    File "/tmp/pip-build-env-bo4dl8cl/overlay/lib/python3.7/site-packages/setuptools/build_meta.py", line 150, in run_setup
      exec(compile(code, __file__, 'exec'), locals())
    File "setup.py", line 281, in <module>
      zip_safe=False,
    File "/tmp/pip-build-env-bo4dl8cl/overlay/lib/python3.7/site-packages/setuptools/__init__.py", line 153, in setup
      return distutils.core.setup(**attrs)
    File "/usr/local/lib/python3.7/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/usr/local/lib/python3.7/distutils/dist.py", line 966, in run_commands
      self.run_command(cmd)
    File "/usr/local/lib/python3.7/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/tmp/pip-build-env-bo4dl8cl/overlay/lib/python3.7/site-packages/wheel/bdist_wheel.py", line 299, in run
      self.run_command('build')
    File "/usr/local/lib/python3.7/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/local/lib/python3.7/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/usr/local/lib/python3.7/distutils/command/build.py", line 135, in run
      self.run_command(cmd_name)
    File "/usr/local/lib/python3.7/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/local/lib/python3.7/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "setup.py", line 44, in run
      _(install_dir=self.install_dir, build_dir=self.build_dir)
    File "setup.py", line 76, in invoke_make
      subprocess.check_output("make -C src -f Makefile.vdf-client", shell=True)
    File "/usr/local/lib/python3.7/subprocess.py", line 411, in check_output
      **kwargs).stdout
    File "/usr/local/lib/python3.7/subprocess.py", line 512, in run
      output=stdout, stderr=stderr)
  subprocess.CalledProcessError: Command 'make -C src -f Makefile.vdf-client' returned non-zero exit status 2.
  ----------------------------------------
  ERROR: Failed building wheel for chiavdf
Failed to build chiavdf
ERROR: Could not build wheels for chiavdf which use PEP 517 and cannot be installed directly
ERROR: Could not find venv/lib/python3.7/site-packages/vdf_bench
To estimate a timelord on this CPU try './vdf_bench square_asm 400000' for an ips estimate.
`

**Comment by wearechiarex** [comment]
Problem on Centos 8 :( U have to use Debian/Ubuntu OS.
