### ISSUE TITLE
[BUG] bad allocation when creating plots

### ISSUE THREAD

**Issue by danielcg** [Chia-Network/chia-blockchain#6437]
**Describe the bug**
A clear and concise description of what the bug is. (If what you are experiencing is NOT a bug but instead a support issue, please open a Discussion instead!)

**To Reproduce**
-Install Chia for the first time
-Create a K-25 sized plot successfully
-Create 8 new K-25s in the same directory as the first
-4 of them completed successfully but 4 got stuck at 1%.

**Expected behavior**
I expected to have 9 plots created successfully.

**Desktop (please complete the following information):**

- OS: Windows 10 (Latest build as of 6/4/2021)
- CPU: Ryzen 3600XT

**Logs from failed plots**

Log 1:
2021-06-04T16:41:51.144  chia.plotting.create_plots       : [33mWARNING [0m Creating plots with size k=25, which is less than the minimum required for mainnet[0m
2021-06-04T16:41:51.144  chia.plotting.create_plots       : [32mINFO    [0m Creating 1 plots of size 25, pool public key:  b640758199520571377de3f0082dd4b270c58c9279ccf67ffac396b9ed144067ca4b65b3af7e8627cd8bde6ef35f3f22 farmer public key: 9787fb96b4240ea35c3d486850c5705e0270a0b1f669da2232c511d578a98e5e9e5908ba7cd4d31cbf807c7d06a0eb37[0m
2021-06-04T16:41:51.156  chia.plotting.create_plots       : [32mINFO    [0m Memo: b640758199520571377de3f0082dd4b270c58c9279ccf67ffac396b9ed144067ca4b65b3af7e8627cd8bde6ef35f3f229787fb96b4240ea35c3d486850c5705e0270a0b1f669da2232c511d578a98e5e9e5908ba7cd4d31cbf807c7d06a0eb375e946f37920bf209258242d0a53b02c6e64678a5e473ac17e805d13160ee4931[0m
2021-06-04T16:41:51.156  chia.plotting.create_plots       : [32mINFO    [0m Starting plot 1/1[0m

Starting plotting progress into temporary dirs: C:\Users\Daniel\.chia\tdir and C:\Users\Daniel\.chia\tdir
ID: 9936f03ffa51d6e34d2065ce6eddfbd5539ab89d4dd3094b9cfdcaeee695283b
Plot size is: 25
Buffer size is: 8192MiB
Using 128 buckets
Using 8 threads of stripe size 65536

Starting phase 1/4: Forward Propagation into tmp files... Fri Jun  4 16:41:51 2021
Computing table 1
F1 complete, time: 1.685 seconds. CPU (124.25%) Fri Jun  4 16:41:52 2021
Computing table 2
Caught plotting error: bad allocation
[17564] Failed to execute script chia
Traceback (most recent call last):
  File "chia\cmds\chia.py", line 81, in <module>
  File "chia\cmds\chia.py", line 77, in main
  File "click\core.py", line 829, in __call__
  File "click\core.py", line 782, in main
  File "click\core.py", line 1259, in invoke
  File "click\core.py", line 1259, in invoke
  File "click\core.py", line 1066, in invoke
  File "click\core.py", line 610, in invoke
  File "click\decorators.py", line 21, in new_func
  File "chia\cmds\plots.py", line 135, in create_cmd
  File "chia\plotting\create_plots.py", line 176, in create_plots
RuntimeError: bad allocation

Log 2:
2021-06-04T16:41:50.972  chia.plotting.create_plots       : [33mWARNING [0m Creating plots with size k=25, which is less than the minimum required for mainnet[0m
2021-06-04T16:41:50.972  chia.plotting.create_plots       : [32mINFO    [0m Creating 1 plots of size 25, pool public key:  b640758199520571377de3f0082dd4b270c58c9279ccf67ffac396b9ed144067ca4b65b3af7e8627cd8bde6ef35f3f22 farmer public key: 9787fb96b4240ea35c3d486850c5705e0270a0b1f669da2232c511d578a98e5e9e5908ba7cd4d31cbf807c7d06a0eb37[0m
2021-06-04T16:41:50.984  chia.plotting.create_plots       : [32mINFO    [0m Memo: b640758199520571377de3f0082dd4b270c58c9279ccf67ffac396b9ed144067ca4b65b3af7e8627cd8bde6ef35f3f229787fb96b4240ea35c3d486850c5705e0270a0b1f669da2232c511d578a98e5e9e5908ba7cd4d31cbf807c7d06a0eb373bf05ee5ed6eda1b93c6e4038c8892ee50374ea0995ad29304fe4930ab6d167c[0m
2021-06-04T16:41:50.984  chia.plotting.create_plots       : [32mINFO    [0m Starting plot 1/1[0m

Starting plotting progress into temporary dirs: C:\Users\Daniel\.chia\tdir and C:\Users\Daniel\.chia\tdir
ID: b94ed2aa03473744d475bd6b60dd1dde640a039ea1cb959412be72998c7106bd
Plot size is: 25
Buffer size is: 8192MiB
Using 128 buckets
Using 8 threads of stripe size 65536

Starting phase 1/4: Forward Propagation into tmp files... Fri Jun  4 16:41:50 2021
Computing table 1
F1 complete, time: 1.459 seconds. CPU (144.57%) Fri Jun  4 16:41:52 2021
Computing table 2
Caught plotting error: bad allocation
[1840] Failed to execute script chia
Traceback (most recent call last):
  File "chia\cmds\chia.py", line 81, in <module>
  File "chia\cmds\chia.py", line 77, in main
  File "click\core.py", line 829, in __call__
  File "click\core.py", line 782, in main
  File "click\core.py", line 1259, in invoke
  File "click\core.py", line 1259, in invoke
  File "click\core.py", line 1066, in invoke
  File "click\core.py", line 610, in invoke
  File "click\decorators.py", line 21, in new_func
  File "chia\cmds\plots.py", line 135, in create_cmd
  File "chia\plotting\create_plots.py", line 176, in create_plots
RuntimeError: bad allocation

Log 3:
2021-06-04T16:41:52.516  chia.plotting.create_plots       : [33mWARNING [0m Creating plots with size k=25, which is less than the minimum required for mainnet[0m
2021-06-04T16:41:52.516  chia.plotting.create_plots       : [32mINFO    [0m Creating 1 plots of size 25, pool public key:  b640758199520571377de3f0082dd4b270c58c9279ccf67ffac396b9ed144067ca4b65b3af7e8627cd8bde6ef35f3f22 farmer public key: 9787fb96b4240ea35c3d486850c5705e0270a0b1f669da2232c511d578a98e5e9e5908ba7cd4d31cbf807c7d06a0eb37[0m
2021-06-04T16:41:52.528  chia.plotting.create_plots       : [32mINFO    [0m Memo: b640758199520571377de3f0082dd4b270c58c9279ccf67ffac396b9ed144067ca4b65b3af7e8627cd8bde6ef35f3f229787fb96b4240ea35c3d486850c5705e0270a0b1f669da2232c511d578a98e5e9e5908ba7cd4d31cbf807c7d06a0eb374580e2c3c0521eacb50316d24d6d07f6c21bdda16f40c68ca4347243ba05ae4c[0m
2021-06-04T16:41:52.532  chia.plotting.create_plots       : [32mINFO    [0m Starting plot 1/1[0m

Starting plotting progress into temporary dirs: C:\Users\Daniel\.chia\tdir and C:\Users\Daniel\.chia\tdir
ID: d4825c27a7ba65eb118032171fae15eabd46c22ea9278519b545e46e06581df6
Plot size is: 25
Buffer size is: 8192MiB
Using 128 buckets
Using 8 threads of stripe size 65536

Starting phase 1/4: Forward Propagation into tmp files... Fri Jun  4 16:41:52 2021
Computing table 1
F1 complete, time: 1.517 seconds. CPU (147.28%) Fri Jun  4 16:41:54 2021
Computing table 2
Caught plotting error: bad allocation
[16044] Failed to execute script chia
Traceback (most recent call last):
  File "chia\cmds\chia.py", line 81, in <module>
  File "chia\cmds\chia.py", line 77, in main
  File "click\core.py", line 829, in __call__
  File "click\core.py", line 782, in main
  File "click\core.py", line 1259, in invoke
  File "click\core.py", line 1259, in invoke
  File "click\core.py", line 1066, in invoke
  File "click\core.py", line 610, in invoke
  File "click\decorators.py", line 21, in new_func
  File "chia\cmds\plots.py", line 135, in create_cmd
  File "chia\plotting\create_plots.py", line 176, in create_plots
RuntimeError: bad allocation

Log 4:
2021-06-04T16:41:51.792  chia.plotting.create_plots       : [33mWARNING [0m Creating plots with size k=25, which is less than the minimum required for mainnet[0m
2021-06-04T16:41:51.792  chia.plotting.create_plots       : [32mINFO    [0m Creating 1 plots of size 25, pool public key:  b640758199520571377de3f0082dd4b270c58c9279ccf67ffac396b9ed144067ca4b65b3af7e8627cd8bde6ef35f3f22 farmer public key: 9787fb96b4240ea35c3d486850c5705e0270a0b1f669da2232c511d578a98e5e9e5908ba7cd4d31cbf807c7d06a0eb37[0m
2021-06-04T16:41:51.820  chia.plotting.create_plots       : [32mINFO    [0m Memo: b640758199520571377de3f0082dd4b270c58c9279ccf67ffac396b9ed144067ca4b65b3af7e8627cd8bde6ef35f3f229787fb96b4240ea35c3d486850c5705e0270a0b1f669da2232c511d578a98e5e9e5908ba7cd4d31cbf807c7d06a0eb37697fe0b0925ec89f4ab0613f29efa50fbd3f86020213e5d83eaae79f082aaf60[0m
2021-06-04T16:41:51.820  chia.plotting.create_plots       : [32mINFO    [0m Starting plot 1/1[0m

Starting plotting progress into temporary dirs: C:\Users\Daniel\.chia\tdir and C:\Users\Daniel\.chia\tdir
ID: 10a8fb17fd29131513f55c1666546c9cffba71b442a1dd0acf6b159e4ae70559
Plot size is: 25
Buffer size is: 8192MiB
Using 128 buckets
Using 8 threads of stripe size 65536

Starting phase 1/4: Forward Propagation into tmp files... Fri Jun  4 16:41:51 2021
Computing table 1
F1 complete, time: 1.764 seconds. CPU (135.52%) Fri Jun  4 16:41:53 2021
Computing table 2
Caught plotting error: bad allocation
[6176] Failed to execute script chia
Traceback (most recent call last):
  File "chia\cmds\chia.py", line 81, in <module>
  File "chia\cmds\chia.py", line 77, in main
  File "click\core.py", line 829, in __call__
  File "click\core.py", line 782, in main
  File "click\core.py", line 1259, in invoke
  File "click\core.py", line 1259, in invoke
  File "click\core.py", line 1066, in invoke
  File "click\core.py", line 610, in invoke
  File "click\decorators.py", line 21, in new_func
  File "chia\cmds\plots.py", line 135, in create_cmd
  File "chia\plotting\create_plots.py", line 176, in create_plots
RuntimeError: bad allocation

**Comment by gromran** [comment]
have you deactivated the swap file?

**Comment by joelrb** [comment]
Why are you using size k=25? it already says in the warning that's below minimum for mainnet. Use size k=32.

https://github.com/Chia-Network/chia-blockchain/wiki/k-sizes
