### ISSUE TITLE
[BUG] Exception: too many SQL variables <class 'sqlite3.OperationalError'>

### ISSUE THREAD

**Issue by grafbcn** [Chia-Network/chia-blockchain#6450]
Yesterday power of my server go OFF and it go down.
After that, when I put chia to sync and farm, I get next error in debug.log:
2021-06-05T06:12:09.165 full_node full_node_server        : ERROR    Exception: too many SQL variables <class 'sqlite3.OperationalError'>, closing connection {'host': '206.163.229.201', 'port': 8444}. Traceback (most recent call last):
  File "chia\server\server.py", line 536, in api_call
  File "asyncio\tasks.py", line 442, in wait_for
  File "chia\server\server.py", line 533, in wrapped_coroutine
  File "chia\server\server.py", line 526, in wrapped_coroutine
  File "chia\full_node\full_node_api.py", line 244, in request_proof_of_weight
  File "chia\full_node\weight_proof.py", line 77, in get_proof_of_weight
  File "chia\full_node\weight_proof.py", line 119, in _create_proof_of_weight
  File "chia\consensus\blockchain.py", line 695, in get_block_records_at
  File "chia\full_node\block_store.py", line 181, in get_block_records_by_hash
  File "aiosqlite\core.py", line 184, in execute
  File "aiosqlite\core.py", line 129, in _execute
  File "aiosqlite\core.py", line 102, in run
sqlite3.OperationalError: too many SQL variables

Every 5-10 min.

I don't how to do reproduce it, maybe kill all chia process in PC without "good exit".

I think that even though the computer can shut down badly, the database should be protected by means of cache-> db write. Or in any case I need to know what to do now, do I have to re-synchronize from 0?

My server is:
- OS: Windows
- OS Version/Flavor: MS Windows Server 2016
- CPU: Intel Xeon CPU E5-2670 v2 @ 2.50 GHz

**Comment by DocFraggle** [comment]
Same here... both on Windows and Linux

**Comment by blik137** [comment]
+1 and wallet sync stuck

chia\full_node\block_store.py 181
```
header_hashes_db = tuple([hh.hex() for hh in header_hashes])
        formatted_str = f'SELECT block from block_records WHERE header_hash in ({"?," * (len(header_hashes_db) - 1)}?)'
        cursor = await self.db.execute(formatted_str, header_hashes_db)
```
**SQLITE_MAX_VARIABLE_NUMBER ???**

<details>
  <summary>log</summary>
  ```
2021-06-05T12:40:55.430 wallet wallet_server              : INFO     Connected with full_node {'host': '127.0.0.1', 'port': 8444}
2021-06-05T12:40:56.448 wallet wallet_server              : DEBUG    <- new_peak_wallet from peer e99d8e53d82b7f4855088b2a7d9311c88a939f64ad2aef77ff4866c5653b1a62 127.0.0.1
2021-06-05T12:40:56.448 wallet wallet_server              : DEBUG    -> request_block_header to peer 127.0.0.1 e99d8e53d82b7f4855088b2a7d9311c88a939f64ad2aef77ff4866c5653b1a62
2021-06-05T12:40:56.448 full_node full_node_server        : DEBUG    <- request_block_header from peer 37b248dbad46981dda30cf8f41190da9c5f4e5f243ba58dd280c1818c19451b3 127.0.0.1
2021-06-05T12:40:56.448 full_node chia.full_node.block_store: DEBUG    cache hit for block 75635e3731d63d7b0c4a7d06f03f261f95b7f1efcaf557118de79e59a0d9f85f
2021-06-05T12:40:56.448 full_node full_node_server        : DEBUG    Time taken to process request_block_header from 37b248dbad46981dda30cf8f41190da9c5f4e5f243ba58dd280c1818c19451b3 is 0.0 seconds
2021-06-05T12:40:56.448 full_node full_node_server        : DEBUG    -> respond_block_header to peer 127.0.0.1 37b248dbad46981dda30cf8f41190da9c5f4e5f243ba58dd280c1818c19451b3
2021-06-05T12:40:56.448 wallet wallet_server              : DEBUG    <- respond_block_header from: 127.0.0.1:8444
2021-06-05T12:40:56.448 wallet wallet_server              : DEBUG    Time for request request_block_header: {'host': '127.0.0.1', 'port': 8444} = 0.0, None? False
2021-06-05T12:40:56.448 wallet wallet_server              : DEBUG    -> request_proof_of_weight to peer 127.0.0.1 e99d8e53d82b7f4855088b2a7d9311c88a939f64ad2aef77ff4866c5653b1a62
2021-06-05T12:40:56.448 full_node full_node_server        : DEBUG    <- request_proof_of_weight from peer 37b248dbad46981dda30cf8f41190da9c5f4e5f243ba58dd280c1818c19451b3 127.0.0.1
2021-06-05T12:40:56.448 full_node chia.full_node.weight_proof: INFO     create weight proof peak 75635e3731d63d7b0c4a7d06f03f261f95b7f1efcaf557118de79e59a0d9f85f 386669
2021-06-05T12:40:56.448 full_node chia.full_node.weight_proof: DEBUG    start 385924 end 386669
2021-06-05T12:40:56.602 full_node chia.full_node.weight_proof: INFO     recent chain, start: 385924 end:  386669 
2021-06-05T12:40:56.602 full_node chia.full_node.weight_proof: DEBUG    handle sub epoch summary 0 at height: 386 ses {'new_difficulty': None,
 'new_sub_slot_iters': None,
 'num_blocks_overflow': 0,
 'prev_subepoch_summary_hash': '0xccd5bb71183532bff220ba46c268991a3ff07eb358e8255a65c30a2dce0e5fbb',
 'reward_chain_hash': '0xccd5bb71183532bff220ba46c268991a3ff07eb358e8255a65c30a2dce0e5fbb'}
2021-06-05T12:40:56.602 full_node chia.full_node.weight_proof: DEBUG    handle sub epoch summary 1 at height: 776 ses {'new_difficulty': None,
 'new_sub_slot_iters': None,
 'num_blocks_overflow': 2,
 'prev_subepoch_summary_hash': '0x6c6c5401c7b912fafbc7c99b7ef6d469ba0e349616766e006f0e588ae0d7057b',
 'reward_chain_hash': '0xa569905dc89bd7825c29e9f799a0685141d0a56a24f43ce3c454d1dd253f492c'}
2021-06-05T12:40:56.602 full_node chia.full_node.weight_proof: DEBUG    handle sub epoch summary 2 at height: 1187 ses {'new_difficulty': None,
 'new_sub_slot_iters': None,
 'num_blocks_overflow': 8,
 'prev_subepoch_summary_hash': '0xa3cef49e626c52920365ce5c0ef489bffecd432e87d4dc3d83b7c7003a73d3c1',
 'reward_chain_hash': '0x66c4f703420fd38e4431bd4aed12323655d289c55f157d2bac40a331d476039b'}
2021-06-05T12:40:56.602 full_node chia.full_node.weight_proof: DEBUG    handle sub epoch summary 3 at height: 1575 ses {'new_difficulty': None,
 'new_sub_slot_iters': None,
 'num_blocks_overflow': 35,
 'prev_subepoch_summary_hash': '0x21c2add2a18d196a734e3430f1f0d1d22243ce27d17ac8d9a421fc70743a7915',
 'reward_chain_hash': '0xe1c2a6da302a5387977541657510d6993ed58b4326e9bb006cd82783bf8368f9'}


 
....... many lines .......



2021-06-05T12:40:57.065 full_node chia.full_node.weight_proof: DEBUG    handle sub epoch summary 1002 at height: 385156 ses {'new_difficulty': None,
 'new_sub_slot_iters': None,
 'num_blocks_overflow': 15,
 'prev_subepoch_summary_hash': '0x23732efecce24b16e17688ce415eb937fefaca2c5aa33f1a80b281d17e0c0dca',
 'reward_chain_hash': '0x0a8e2bf91515cdde04d8c448805e541ab058e36c58c3c7648febcbc2a3d5d6a6'}
2021-06-05T12:40:57.065 full_node chia.full_node.weight_proof: DEBUG    handle sub epoch summary 1003 at height: 385563 ses {'new_difficulty': None,
 'new_sub_slot_iters': None,
 'num_blocks_overflow': 4,
 'prev_subepoch_summary_hash': '0xf352666a19ffde409dedbce37052fa3161c9961d112037b4c4864e93fd4c8a84',
 'reward_chain_hash': '0x08040d6c9b51994a3cdf684308bd836c273947d740dbbf2482cdd5d447a77d14'}
2021-06-05T12:40:57.065 full_node chia.full_node.weight_proof: DEBUG    handle sub epoch summary 1004 at height: 385925 ses {'new_difficulty': None,
 'new_sub_slot_iters': None,
 'num_blocks_overflow': 27,
 'prev_subepoch_summary_hash': '0x51c1aeadd98862aa27e1caa1b1b8b86c10c58ea76f69204eaea6b3d3f3123082',
 'reward_chain_hash': '0x638460df51ea6691e9ae64e3d7c6bff5b1cf28862291101e1a206ccc9752f54f'}
2021-06-05T12:40:57.065 full_node chia.full_node.weight_proof: DEBUG    handle sub epoch summary 1005 at height: 386323 ses {'new_difficulty': None,
 'new_sub_slot_iters': None,
 'num_blocks_overflow': 5,
 'prev_subepoch_summary_hash': '0x9781d562060e3d04880b5b0c395f7fe15931825893ae8a01445c7e48239ec3d5',
 'reward_chain_hash': '0x06490ac1be1a31059ce7e02a4598392133121f5d66ab460e1f012c05d17901d7'}
2021-06-05T12:40:57.065 full_node full_node_server        : ERROR    Exception: too many SQL variables, {'host': '127.0.0.1', 'port': 8449}. Traceback (most recent call last):
  File "chia\server\server.py", line 526, in wrapped_coroutine
  File "chia\full_node\full_node_api.py", line 244, in request_proof_of_weight
  File "chia\full_node\weight_proof.py", line 77, in get_proof_of_weight
  File "chia\full_node\weight_proof.py", line 119, in _create_proof_of_weight
  File "chia\consensus\blockchain.py", line 695, in get_block_records_at
  File "chia\full_node\block_store.py", line 181, in get_block_records_by_hash
  File "aiosqlite\core.py", line 184, in execute
  File "aiosqlite\core.py", line 129, in _execute
  File "aiosqlite\core.py", line 102, in run
sqlite3.OperationalError: too many SQL variables

2021-06-05T12:40:57.065 full_node full_node_server        : ERROR    Exception: too many SQL variables <class 'sqlite3.OperationalError'>, closing connection {'host': '127.0.0.1', 'port': 8449}. Traceback (most recent call last):
  File "chia\server\server.py", line 536, in api_call
  File "asyncio\tasks.py", line 442, in wait_for
  File "chia\server\server.py", line 533, in wrapped_coroutine
  File "chia\server\server.py", line 526, in wrapped_coroutine
  File "chia\full_node\full_node_api.py", line 244, in request_proof_of_weight
  File "chia\full_node\weight_proof.py", line 77, in get_proof_of_weight
  File "chia\full_node\weight_proof.py", line 119, in _create_proof_of_weight
  File "chia\consensus\blockchain.py", line 695, in get_block_records_at
  File "chia\full_node\block_store.py", line 181, in get_block_records_by_hash
  File "aiosqlite\core.py", line 184, in execute
  File "aiosqlite\core.py", line 129, in _execute
  File "aiosqlite\core.py", line 102, in run
sqlite3.OperationalError: too many SQL variables

2021-06-05T12:40:57.065 full_node full_node_server        : DEBUG    Inbound_handler task cancelled
2021-06-05T12:40:57.065 full_node full_node_server        : WARNING  Trying to ban localhost for 10, but will not ban
2021-06-05T12:40:57.065 full_node full_node_server        : INFO     Connection closed: 127.0.0.1, node id: 37b248dbad46981dda30cf8f41190da9c5f4e5f243ba58dd280c1818c19451b3
2021-06-05T12:40:57.065 full_node chia.full_node.full_node: INFO     peer disconnected {'host': '127.0.0.1', 'port': 8449}
2021-06-05T12:40:57.065 wallet wallet_server              : DEBUG    Peer closed connection full_node 127.0.0.1:8444/8444
2021-06-05T12:40:58.083 wallet wallet_server              : DEBUG    Inbound_handler task cancelled
2021-06-05T12:40:58.083 wallet wallet_server              : INFO     Connection closed: 127.0.0.1, node id: e99d8e53d82b7f4855088b2a7d9311c88a939f64ad2aef77ff4866c5653b1a62
2021-06-05T12:40:58.083 wallet wallet_server              : DEBUG    Time for request request_proof_of_weight: None = 1.6351737976074219, None? True
2021-06-05T12:40:58.083 wallet wallet_server              : DEBUG    Time taken to process new_peak_wallet from 
  ```
</details>

**Comment by gotblindside** [comment]
Same error.

deleting the wallet blockchain is not correct specially if you have chia.

I cut the folder first instead of deleting the wallet blockchain because I have chia that is still pending.
When I restarted chia was lost.

So I closed the application and placed back my original folder and my chia is back.

**Comment by xlhh** [comment]
+1

**Comment by walruzperil** [comment]
Chia wallet can't sync... Same error. How fix it?

**Comment by Muasin94** [comment]
same here and i think all the users have the same problem. i hope is ready a new ver. for Chia.
wallet offline.

**Comment by MarcusB2105** [comment]
There are four issues to the same problem already: #6478 and #6466 and #6450 including this one #6455 .

**Comment by MarcusB2105** [comment]
Looks like Chia 1.1.7 is out (see https://thechiaplot.net/2021/06/05/chia-1-1-7-released/)

I downloaded it from https://github.com/Chia-Network/chia-blockchain/releases/tag/1.1.7 and it works for me. see #6493

**Comment by www-asics-ws** [comment]
I'm running 1.1.7, and have the same issue described by the OP. 
Wallet does not sync (even though the Full Node is synced).
And log file has these errors ...
