### ISSUE TITLE
[BUG] Wallet does not sync "to many SQL variables"

### ISSUE THREAD

**Issue by marcus-garvey** [Chia-Network/chia-blockchain#6455]
**Describe the bug**
My wallet does not sync, it stay at height 0.
The Debug log shows every 5 min this.

```
2021-06-05T10:39:46.930 full_node full_node_server        : ERROR    Exception: too many SQL variables, {'host': '127.0.0.1', 'port': 8449}. Traceback (most recent call last):
  File "chia\server\server.py", line 526, in wrapped_coroutine
  File "chia\full_node\full_node_api.py", line 244, in request_proof_of_weight
  File "chia\full_node\weight_proof.py", line 77, in get_proof_of_weight
  File "chia\full_node\weight_proof.py", line 119, in _create_proof_of_weight
  File "chia\consensus\blockchain.py", line 695, in get_block_records_at
  File "chia\full_node\block_store.py", line 181, in get_block_records_by_hash
  File "aiosqlite\core.py", line 184, in execute
  File "aiosqlite\core.py", line 129, in _execute
  File "aiosqlite\core.py", line 102, in run
sqlite3.OperationalError: too many SQL variables

2021-06-05T10:39:46.934 full_node full_node_server        : ERROR    Exception: too many SQL variables <class 'sqlite3.OperationalError'>, closing connection {'host': '127.0.0.1', 'port': 8449}. Traceback (most recent call last):
  File "chia\server\server.py", line 536, in api_call
  File "asyncio\tasks.py", line 442, in wait_for
  File "chia\server\server.py", line 533, in wrapped_coroutine
  File "chia\server\server.py", line 526, in wrapped_coroutine
  File "chia\full_node\full_node_api.py", line 244, in request_proof_of_weight
  File "chia\full_node\weight_proof.py", line 77, in get_proof_of_weight
  File "chia\full_node\weight_proof.py", line 119, in _create_proof_of_weight
  File "chia\consensus\blockchain.py", line 695, in get_block_records_at
  File "chia\full_node\block_store.py", line 181, in get_block_records_by_hash
  File "aiosqlite\core.py", line 184, in execute
  File "aiosqlite\core.py", line 129, in _execute
  File "aiosqlite\core.py", line 102, in run
sqlite3.OperationalError: too many SQL variables

2021-06-05T10:39:46.937 full_node full_node_server        : WARNING  Trying to ban localhost for 10, but will not ban
2021-06-05T10:39:46.940 full_node full_node_server        : INFO     Connection closed: 127.0.0.1, node id: 8426f374460c99b360faf921085c2e8811b3260c0ed367c023ec598567eccd00
2021-06-05T10:39:46.942 full_node chia.full_node.full_node: INFO     peer disconnected {'host': '127.0.0.1', 'port': 8449}
2021-06-05T10:39:46.945 full_node asyncio                 : ERROR    Task exception was never retrieved
future: <Task finished coro=<ChiaServer.incoming_api_task.<locals>.api_call() done, defined at chia\server\server.py:487> exception=CancelledError()>
concurrent.futures._base.CancelledError
2021-06-05T10:39:46.948 full_node full_node_server        : ERROR    Exception:  <class 'concurrent.futures._base.CancelledError'>, closing connection {'host': '127.0.0.1', 'port': 8449}. Traceback (most recent call last):
  File "chia\server\server.py", line 536, in api_call
  File "asyncio\tasks.py", line 435, in wait_for
concurrent.futures._base.CancelledError

2021-06-05T10:39:46.938 wallet wallet_server              : INFO     Connection closed: 127.0.0.1, node id: 80a9d89faaa5b446daaba4b508411ef8cd35f01a39fce3f4098a23c6d2d97bd0
2021-06-05T10:39:49.604 wallet wallet                     : INFO     Reconnecting to peer {'host': '127.0.0.1', 'port': 8444}
2021-06-05T10:39:49.618 wallet wallet_server              : INFO     Connected with full_node {'host': '127.0.0.1', 'port': 8444}
2021-06-05T10:39:49.640 full_node chia.full_node.weight_proof: INFO     create weight proof peak bae6ece6aa29bc1ffb75766aed2b92734a65ba6de59ed4318d84ca93901714a2 386888
2021-06-05T10:39:49.806 full_node chia.full_node.weight_proof: INFO     recent chain, start: 386322 end:  386888 
2021-06-05T10:39:49.934 full_node full_node_server        : ERROR    Exception: too many SQL variables, {'host': '127.0.0.1', 'port': 8449}. Traceback (most recent call last):
  File "chia\server\server.py", line 526, in wrapped_coroutine
  File "chia\full_node\full_node_api.py", line 244, in request_proof_of_weight
  File "chia\full_node\weight_proof.py", line 77, in get_proof_of_weight
  File "chia\full_node\weight_proof.py", line 119, in _create_proof_of_weight
  File "chia\consensus\blockchain.py", line 695, in get_block_records_at
  File "chia\full_node\block_store.py", line 181, in get_block_records_by_hash
  File "aiosqlite\core.py", line 184, in execute
  File "aiosqlite\core.py", line 129, in _execute
  File "aiosqlite\core.py", line 102, in run
sqlite3.OperationalError: too many SQL variables

2021-06-05T10:39:49.939 full_node full_node_server        : ERROR    Exception: too many SQL variables <class 'sqlite3.OperationalError'>, closing connection {'host': '127.0.0.1', 'port': 8449}. Traceback (most recent call last):
  File "chia\server\server.py", line 536, in api_call
  File "asyncio\tasks.py", line 442, in wait_for
  File "chia\server\server.py", line 533, in wrapped_coroutine
  File "chia\server\server.py", line 526, in wrapped_coroutine
  File "chia\full_node\full_node_api.py", line 244, in request_proof_of_weight
  File "chia\full_node\weight_proof.py", line 77, in get_proof_of_weight
  File "chia\full_node\weight_proof.py", line 119, in _create_proof_of_weight
  File "chia\consensus\blockchain.py", line 695, in get_block_records_at
  File "chia\full_node\block_store.py", line 181, in get_block_records_by_hash
  File "aiosqlite\core.py", line 184, in execute
  File "aiosqlite\core.py", line 129, in _execute
  File "aiosqlite\core.py", line 102, in run
sqlite3.OperationalError: too many SQL variables

2021-06-05T10:39:49.942 full_node full_node_server        : WARNING  Trying to ban localhost for 10, but will not ban
2021-06-05T10:39:49.944 full_node full_node_server        : INFO     Connection closed: 127.0.0.1, node id: 8426f374460c99b360faf921085c2e8811b3260c0ed367c023ec598567eccd00
2021-06-05T10:39:49.947 full_node chia.full_node.full_node: INFO     peer disconnected {'host': '127.0.0.1', 'port': 8449}
2021-06-05T10:39:50.028 full_node asyncio                 : ERROR    Task exception was never retrieved
future: <Task finished coro=<ChiaServer.incoming_api_task.<locals>.api_call() done, defined at chia\server\server.py:487> exception=CancelledError()>
concurrent.futures._base.CancelledError
2021-06-05T10:39:49.942 wallet wallet_server              : INFO     Connection closed: 127.0.0.1, node id: 80a9d89faaa5b446daaba4b508411ef8cd35f01a39fce3f4098a23c6d2d97bd0
2021-06-05T10:39:52.621 wallet wallet                     : INFO     Reconnecting to peer {'host': '127.0.0.1', 'port': 8444}
2021-06-05T10:39:52.635 wallet wallet_server              : INFO     Connected with full_node {'host': '127.0.0.1', 'port': 8444}
```

**Desktop (please complete the following information):**

- OS: Windows 10
- Chia version 1.1.6

Anyone knows this problem and can help to fix this?
I tried to stop everything and delete the wallet db, but after a restart the same error happens again.

**Comment by DocFraggle** [comment]
Both on Windows and Linux, deleting the wallet blockchain fingers and restarting afterwards doesn't help

**Comment by gotblindside** [comment]
Same error.

deleting the wallet blockchain is not correct specially if you have chia.

I cut the folder first instead of deleting the wallet blockchain because I have chia that is still pending.
When I restarted chia was lost.

So I closed the application and placed back my original folder and my chia is back.

**Comment by xlhh** [comment]
Same

**Comment by NEITG** [comment]
Updated to 1.1.6 on Windows today and getting the same SQL exceptions. Wallet is not syncing either.

**Comment by MarcusB2105** [comment]
I'm having the same issues. see  #6478 and #6466 and #6450 including this one #6455 four issues to the same problem.

**Comment by MarcusB2105** [comment]
The ChiaSetup 1.1.7 is now available on the official chia.net download section. This should solve the problem.

**Comment by DocFraggle** [comment]
Correct, with 1.1.7 everything works again

**Comment by marcus-garvey** [comment]
Thx the update solves the problems
