### ISSUE TITLE
too many SQL variables [ERROR]

### ISSUE THREAD

**Issue by empereurfn** [Chia-Network/chia-blockchain#6466]
Getting this error in the debbug log every 2 minutes since today. I havent changed anything to my farmer in a week and it just started. Using GUI on windows 10. 

2021-06-05T08:21:16.032 full_node full_node_server        : ERROR    Exception: too many SQL variables <class 'sqlite3.OperationalError'>, closing connection {'host': '42.202.134.162', 'port': 8444}. Traceback (most recent call last):
  File "chia\server\server.py", line 536, in api_call
  File "asyncio\tasks.py", line 442, in wait_for
  File "chia\server\server.py", line 533, in wrapped_coroutine
  File "chia\server\server.py", line 526, in wrapped_coroutine
  File "chia\full_node\full_node_api.py", line 244, in request_proof_of_weight
  File "chia\full_node\weight_proof.py", line 77, in get_proof_of_weight
  File "chia\full_node\weight_proof.py", line 119, in _create_proof_of_weight
  File "chia\consensus\blockchain.py", line 695, in get_block_records_at
  File "chia\full_node\block_store.py", line 181, in get_block_records_by_hash
  File "aiosqlite\core.py", line 184, in execute
  File "aiosqlite\core.py", line 129, in _execute
  File "aiosqlite\core.py", line 102, in run
sqlite3.OperationalError: too many SQL variables

Cant find anyone else with this error.

Thanks

**Comment by imakhack** [comment]
Got the same issue:

2021-06-05T17:33:22.918 full_node full_node_server        : ERROR    Exception: too many SQL variables <class 'sqlite3.OperationalError'>, closing connection {'host': '89.155.26.170', 'port': 8444}. Traceback (most recent call last):
  File "chia\server\server.py", line 536, in api_call
  File "asyncio\tasks.py", line 442, in wait_for
  File "chia\server\server.py", line 533, in wrapped_coroutine
  File "chia\server\server.py", line 526, in wrapped_coroutine
  File "chia\full_node\full_node_api.py", line 244, in request_proof_of_weight
  File "chia\full_node\weight_proof.py", line 77, in get_proof_of_weight
  File "chia\full_node\weight_proof.py", line 119, in _create_proof_of_weight
  File "chia\consensus\blockchain.py", line 695, in get_block_records_at
  File "chia\full_node\block_store.py", line 181, in get_block_records_by_hash
  File "aiosqlite\core.py", line 184, in execute
  File "aiosqlite\core.py", line 129, in _execute
  File "aiosqlite\core.py", line 102, in run
sqlite3.OperationalError: too many SQL variables

2021-06-05T17:33:23.006 full_node full_node_server        : WARNING  Banning 89.155.26.170 for 10 seconds
2021-06-05T17:33:23.018 full_node asyncio                 : ERROR    Task exception was never retrieved
future: <Task finished coro=<ChiaServer.incoming_api_task.<locals>.api_call() done, defined at chia\server\server.py:487> exception=CancelledError()>
concurrent.futures._base.CancelledError

**Comment by xlhh** [comment]
same that....

**Comment by TechAddict000** [comment]
Same issue:
2021-06-05T11:27:04.347 full_node full_node_server        : ERROR    Exception: too many SQL variables, {'host': '39.128.35.134', 'port': 8444}. Traceback (most recent call last):
  File "chia\server\server.py", line 526, in wrapped_coroutine
  File "chia\full_node\full_node_api.py", line 244, in request_proof_of_weight
  File "chia\full_node\weight_proof.py", line 77, in get_proof_of_weight
  File "chia\full_node\weight_proof.py", line 119, in _create_proof_of_weight
  File "chia\consensus\blockchain.py", line 695, in get_block_records_at
  File "chia\full_node\block_store.py", line 181, in get_block_records_by_hash
  File "aiosqlite\core.py", line 184, in execute
  File "aiosqlite\core.py", line 129, in _execute
  File "aiosqlite\core.py", line 102, in run
sqlite3.OperationalError: too many SQL variables

2021-06-05T11:27:04.349 full_node full_node_server        : ERROR    Exception: too many SQL variables <class 'sqlite3.OperationalError'>, closing connection {'host': '39.128.35.134', 'port': 8444}. Traceback (most recent call last):
  File "chia\server\server.py", line 536, in api_call
  File "asyncio\tasks.py", line 442, in wait_for
  File "chia\server\server.py", line 533, in wrapped_coroutine
  File "chia\server\server.py", line 526, in wrapped_coroutine
  File "chia\full_node\full_node_api.py", line 244, in request_proof_of_weight
  File "chia\full_node\weight_proof.py", line 77, in get_proof_of_weight
  File "chia\full_node\weight_proof.py", line 119, in _create_proof_of_weight
  File "chia\consensus\blockchain.py", line 695, in get_block_records_at
  File "chia\full_node\block_store.py", line 181, in get_block_records_by_hash
  File "aiosqlite\core.py", line 184, in execute
  File "aiosqlite\core.py", line 129, in _execute
  File "aiosqlite\core.py", line 102, in run
sqlite3.OperationalError: too many SQL variables

2021-06-05T11:27:04.352 full_node full_node_server        : INFO     Connection closed: 39.128.35.134, node id: 19de4b25276fa640d1df5999b9d54b621d3a6ecef0395b17364dfbf05e68e4c7
2021-06-05T11:27:04.352 full_node full_node_server        : WARNING  Banning 39.128.35.134 for 10 seconds
2021-06-05T11:27:04.353 full_node chia.full_node.full_node: INFO     peer disconnected {'host': '39.128.35.134', 'port': 8444}
2021-06-05T11:27:04.353 full_node asyncio                 : ERROR    Task exception was never retrieved
future: <Task finished coro=<ChiaServer.incoming_api_task.<locals>.api_call() done, defined at chia\server\server.py:487> exception=CancelledError()>
concurrent.futures._base.CancelledError

**Comment by NEITG** [comment]
Same since updating to 1.1.6 today, Windows 2019..

Started with:

full_node full_node_server : ERROR Exception , exception Stack: Traceback (most recent call last):
File "chia\server\server.py", line 356, in start_client
File "aiohttp\client.py", line 763, in _ws_connect
File "aiohttp\client.py", line 521, in _request
File "aiohttp\connector.py", line 535, in connect
File "aiohttp\connector.py", line 892, in _create_connection
File "aiohttp\connector.py", line 1032, in _create_direct_connection
File "aiohttp\connector.py", line 969, in _wrap_create_connection
File "asyncio\base_events.py", line 949, in create_connection
File "asyncio\selector_events.py", line 473, in sock_connect
concurrent.futures._base.CancelledError

wallet wallet_server : ERROR Exception: <class 'concurrent.futures._base.CancelledError'>, closing connection None. Traceback (most recent call last):
File "chia\server\server.py", line 536, in api_call
File "asyncio\tasks.py", line 435, in wait_for
concurrent.futures._base.CancelledError

Then over and over these:

2021-06-05T12:47:17.484 full_node full_node_server : ERROR Exception: too many SQL variables <class 'sqlite3.OperationalError'>, closing connection {'host': '127.0.0.1', 'port': 8449}. Traceback (most recent call last):
File "chia\server\server.py", line 536, in api_call
File "asyncio\tasks.py", line 442, in wait_for
File "chia\server\server.py", line 533, in wrapped_coroutine
File "chia\server\server.py", line 526, in wrapped_coroutine
File "chia\full_node\full_node_api.py", line 244, in request_proof_of_weight
File "chia\full_node\weight_proof.py", line 77, in get_proof_of_weight
File "chia\full_node\weight_proof.py", line 119, in _create_proof_of_weight
File "chia\consensus\blockchain.py", line 695, in get_block_records_at
File "chia\full_node\block_store.py", line 181, in get_block_records_by_hash
File "aiosqlite\core.py", line 184, in execute
File "aiosqlite\core.py", line 129, in _execute
File "aiosqlite\core.py", line 102, in run
sqlite3.OperationalError: too many SQL variables

2021-06-05T12:47:17.484 full_node full_node_server : WARNING Trying to ban localhost for 10, but will not ban
2021-06-05T12:47:17.484 full_node full_node_server : ERROR Exception: <class 'concurrent.futures._base.CancelledError'>, closing connection {'host': '127.0.0.1', 'port': 8449}. Traceback (most recent call last):
File "chia\server\server.py", line 536, in api_call
File "asyncio\tasks.py", line 435, in wait_for
concurrent.futures._base.CancelledError

2021-06-05T12:47:17.609 full_node asyncio : ERROR Task exception was never retrieved
future: <Task finished coro=<ChiaServer.incoming_api_task..api_call() done, defined at chia\server\server.py:487> exception=CancelledError()>
concurrent.futures._base.CancelledError
2021-06-05T12:47:18.094 full_node full_node_server : ERROR Exception: too many SQL variables, {'host': '127.0.0.1', 'port': 8449}. Traceback (most recent call last):
File "chia\server\server.py", line 526, in wrapped_coroutine
File "chia\full_node\full_node_api.py", line 244, in request_proof_of_weight
File "chia\full_node\weight_proof.py", line 77, in get_proof_of_weight
File "chia\full_node\weight_proof.py", line 119, in _create_proof_of_weight
File "chia\consensus\blockchain.py", line 695, in get_block_records_at
File "chia\full_node\block_store.py", line 181, in get_block_records_by_hash
File "aiosqlite\core.py", line 184, in execute
File "aiosqlite\core.py", line 129, in _execute
File "aiosqlite\core.py", line 102, in run
sqlite3.OperationalError: too many SQL variables

**Comment by zombie665** [comment]
[debug.log](https://github.com/Chia-Network/chia-blockchain/files/6602907/debug.log)

**Comment by TechAddict000** [comment]
Anyone that might be paying attention to this - INFO level debug log shows this before each error message (this is the first instance I found):
2021-06-04T15:16:37.955 full_node chia.full_node.weight_proof: INFO     create weight proof peak c96f10918a769dcd62e34b306278631e99cee939d8f416d9041485a60c6c069e 384139
2021-06-04T15:16:40.628 full_node chia.full_node.weight_proof: INFO     recent chain, start: 383631 end:  384139 
...then this...
2021-06-04T15:16:40.712 full_node full_node_server        : ERROR    Exception: too many SQL variables, {'host': '46.238.50.51', 'port': 8444}. Traceback (most recent call last):
  File "chia\server\server.py", line 526, in wrapped_coroutine
  File "chia\full_node\full_node_api.py", line 244, in request_proof_of_weight
  File "chia\full_node\weight_proof.py", line 77, in get_proof_of_weight
  File "chia\full_node\weight_proof.py", line 119, in _create_proof_of_weight
  File "chia\consensus\blockchain.py", line 695, in get_block_records_at
  File "chia\full_node\block_store.py", line 181, in get_block_records_by_hash
  File "aiosqlite\core.py", line 184, in execute
  File "aiosqlite\core.py", line 129, in _execute
  File "aiosqlite\core.py", line 102, in run
sqlite3.OperationalError: too many SQL variables

2021-06-04T15:16:40.713 full_node full_node_server        : ERROR    Exception: too many SQL variables <class 'sqlite3.OperationalError'>, closing connection {'host': '46.238.50.51', 'port': 8444}. Traceback (most recent call last):
  File "chia\server\server.py", line 536, in api_call
  File "asyncio\tasks.py", line 442, in wait_for
  File "chia\server\server.py", line 533, in wrapped_coroutine
  File "chia\server\server.py", line 526, in wrapped_coroutine
  File "chia\full_node\full_node_api.py", line 244, in request_proof_of_weight
  File "chia\full_node\weight_proof.py", line 77, in get_proof_of_weight
  File "chia\full_node\weight_proof.py", line 119, in _create_proof_of_weight
  File "chia\consensus\blockchain.py", line 695, in get_block_records_at
  File "chia\full_node\block_store.py", line 181, in get_block_records_by_hash
  File "aiosqlite\core.py", line 184, in execute
  File "aiosqlite\core.py", line 129, in _execute
  File "aiosqlite\core.py", line 102, in run
sqlite3.OperationalError: too many SQL variables

2021-06-04T15:16:40.714 full_node full_node_server        : INFO     Connection closed: 46.238.50.51, node id: 2f87506c45f8ed28bd0af163261ea5708df76cdfa698de97de79c12b1a9c8f54
2021-06-04T15:16:40.715 full_node full_node_server        : WARNING  Banning 46.238.50.51 for 10 seconds
2021-06-04T15:16:40.715 full_node chia.full_node.full_node: INFO     peer disconnected {'host': '46.238.50.51', 'port': 8444}
2021-06-04T15:16:40.716 full_node asyncio                 : ERROR    Task exception was never retrieved
future: <Task finished coro=<ChiaServer.incoming_api_task.<locals>.api_call() done, defined at chia\server\server.py:487> exception=CancelledError()>
concurrent.futures._base.CancelledError

Anyone else?

**Comment by Ron-ski** [comment]
I'm having the same issues, see my post here https://github.com/Chia-Network/chia-blockchain/issues/6478#issuecomment-855306119

**Comment by MarcusB2105** [comment]
Same here, started yesterday night 3:36 CET (Germany). Running Windows 2010 and Chia 1.1.6. Chia is synced and I see plots passing the filter. Really anayoing since I don´t know if farming is still working or not (probably not). Searching for a solution the whole day.

2021-06-05T03:36:29.240 full_node full_node_server        : ERROR    Exception: too many SQL variables, {'host': '127.0.0.1', 'port': 8449}. Traceback (most recent call last):
  File "chia\server\server.py", line 526, in wrapped_coroutine
  File "chia\full_node\full_node_api.py", line 244, in request_proof_of_weight
  File "chia\full_node\weight_proof.py", line 77, in get_proof_of_weight
  File "chia\full_node\weight_proof.py", line 119, in _create_proof_of_weight
  File "chia\consensus\blockchain.py", line 695, in get_block_records_at
  File "chia\full_node\block_store.py", line 181, in get_block_records_by_hash
  File "aiosqlite\core.py", line 184, in execute
  File "aiosqlite\core.py", line 129, in _execute
  File "aiosqlite\core.py", line 102, in run
sqlite3.OperationalError: too many SQL variables

2021-06-05T03:36:29.256 full_node full_node_server        : ERROR    Exception: too many SQL variables <class 'sqlite3.OperationalError'>, closing connection {'host': '127.0.0.1', 'port': 8449}. Traceback (most recent call last):
  File "chia\server\server.py", line 536, in api_call
  File "asyncio\tasks.py", line 442, in wait_for
  File "chia\server\server.py", line 533, in wrapped_coroutine
  File "chia\server\server.py", line 526, in wrapped_coroutine
  File "chia\full_node\full_node_api.py", line 244, in request_proof_of_weight
  File "chia\full_node\weight_proof.py", line 77, in get_proof_of_weight
  File "chia\full_node\weight_proof.py", line 119, in _create_proof_of_weight
  File "chia\consensus\blockchain.py", line 695, in get_block_records_at
  File "chia\full_node\block_store.py", line 181, in get_block_records_by_hash
  File "aiosqlite\core.py", line 184, in execute
  File "aiosqlite\core.py", line 129, in _execute
  File "aiosqlite\core.py", line 102, in run
sqlite3.OperationalError: too many SQL variables

2021-06-05T03:36:29.256 full_node full_node_server        : WARNING  Trying to ban localhost for 10, but will not ban
2021-06-05T03:36:29.256 full_node asyncio                 : ERROR    Task exception was never retrieved
future: <Task finished coro=<ChiaServer.incoming_api_task.<locals>.api_call() done, defined at chia\server\server.py:487> exception=CancelledError()>
concurrent.futures._base.CancelledError
2021-06-05T03:36:29.256 full_node full_node_server        : ERROR    Exception:  <class 'concurrent.futures._base.CancelledError'>, closing connection {'host': '127.0.0.1', 'port': 8449}. Traceback (most recent call last):
  File "chia\server\server.py", line 536, in api_call
  File "asyncio\tasks.py", line 435, in wait_for
concurrent.futures._base.CancelledError

2021-06-05T03:39:23.954 full_node asyncio                 : ERROR    Task exception was never retrieved
future: <Task finished coro=<FullNode._sync() done, defined at chia\full_node\full_node.py:549> exception=OperationalError('too many SQL variables')>
Traceback (most recent call last):
  File "chia\full_node\full_node.py", line 680, in _sync
  File "chia\full_node\full_node.py", line 856, in _finish_sync
  File "chia\full_node\weight_proof.py", line 77, in get_proof_of_weight
  File "chia\full_node\weight_proof.py", line 119, in _create_proof_of_weight
  File "chia\consensus\blockchain.py", line 695, in get_block_records_at
  File "chia\full_node\block_store.py", line 181, in get_block_records_by_hash
  File "aiosqlite\core.py", line 184, in execute
  File "aiosqlite\core.py", line 129, in _execute
  File "aiosqlite\core.py", line 102, in run
sqlite3.OperationalError: too many SQL variables
2021-06-05T03:42:36.225 full_node full_node_server        : ERROR    Exception: too many SQL variables, {'host': '127.0.0.1', 'port': 8449}. Traceback (most recent call last):
  File "chia\server\server.py", line 526, in wrapped_coroutine
  File "chia\full_node\full_node_api.py", line 244, in request_proof_of_weight
  File "chia\full_node\weight_proof.py", line 77, in get_proof_of_weight
  File "chia\full_node\weight_proof.py", line 119, in _create_proof_of_weight
  File "chia\consensus\blockchain.py", line 695, in get_block_records_at
  File "chia\full_node\block_store.py", line 181, in get_block_records_by_hash
  File "aiosqlite\core.py", line 184, in execute
  File "aiosqlite\core.py", line 129, in _execute
  File "aiosqlite\core.py", line 102, in run
sqlite3.OperationalError: too many SQL variables

2021-06-05T03:42:36.225 full_node full_node_server        : ERROR    Exception: too many SQL variables <class 'sqlite3.OperationalError'>, closing connection {'host': '127.0.0.1', 'port': 8449}. Traceback (most recent call last):
  File "chia\server\server.py", line 536, in api_call
  File "asyncio\tasks.py", line 442, in wait_for
  File "chia\server\server.py", line 533, in wrapped_coroutine
  File "chia\server\server.py", line 526, in wrapped_coroutine
  File "chia\full_node\full_node_api.py", line 244, in request_proof_of_weight
  File "chia\full_node\weight_proof.py", line 77, in get_proof_of_weight
  File "chia\full_node\weight_proof.py", line 119, in _create_proof_of_weight
  File "chia\consensus\blockchain.py", line 695, in get_block_records_at
  File "chia\full_node\block_store.py", line 181, in get_block_records_by_hash
  File "aiosqlite\core.py", line 184, in execute
  File "aiosqlite\core.py", line 129, in _execute
  File "aiosqlite\core.py", line 102, in run
sqlite3.OperationalError: too many SQL variables

2021-06-05T03:42:36.225 full_node full_node_server        : WARNING  Trying to ban localhost for 10, but will not ban
2021-06-05T03:42:36.225 full_node asyncio                 : ERROR    Task exception was never retrieved
future: <Task finished coro=<ChiaServer.incoming_api_task.<locals>.api_call() done, defined at chia\server\server.py:487> exception=CancelledError()>
concurrent.futures._base.CancelledError
2021-06-05T03:42:36.225 full_node full_node_server        : ERROR    Exception:  <class 'concurrent.futures._base.CancelledError'>, closing connection {'host': '127.0.0.1', 'port': 8449}. Traceback (most recent call last):
  File "chia\server\server.py", line 536, in api_call
  File "asyncio\tasks.py", line 435, in wait_for
concurrent.futures._base.CancelledError

2021-06-05T03:42:39.756 full_node full_node_server        : ERROR    Exception: too many SQL variables, {'host': '127.0.0.1', 'port': 8449}. Traceback (most recent call last):
  File "chia\server\server.py", line 526, in wrapped_coroutine
  File "chia\full_node\full_node_api.py", line 244, in request_proof_of_weight
  File "chia\full_node\weight_proof.py", line 77, in get_proof_of_weight
  File "chia\full_node\weight_proof.py", line 119, in _create_proof_of_weight
  File "chia\consensus\blockchain.py", line 695, in get_block_records_at
  File "chia\full_node\block_store.py", line 181, in get_block_records_by_hash
  File "aiosqlite\core.py", line 184, in execute
  File "aiosqlite\core.py", line 129, in _execute
  File "aiosqlite\core.py", line 102, in run
sqlite3.OperationalError: too many SQL variables

2021-06-05T03:42:39.772 full_node full_node_server        : ERROR    Exception: too many SQL variables <class 'sqlite3.OperationalError'>, closing connection {'host': '127.0.0.1', 'port': 8449}. Traceback (most recent call last):
  File "chia\server\server.py", line 536, in api_call
  File "asyncio\tasks.py", line 442, in wait_for
  File "chia\server\server.py", line 533, in wrapped_coroutine
  File "chia\server\server.py", line 526, in wrapped_coroutine
  File "chia\full_node\full_node_api.py", line 244, in request_proof_of_weight
  File "chia\full_node\weight_proof.py", line 77, in get_proof_of_weight
  File "chia\full_node\weight_proof.py", line 119, in _create_proof_of_weight
  File "chia\consensus\blockchain.py", line 695, in get_block_records_at
  File "chia\full_node\block_store.py", line 181, in get_block_records_by_hash
  File "aiosqlite\core.py", line 184, in execute
  File "aiosqlite\core.py", line 129, in _execute
  File "aiosqlite\core.py", line 102, in run
sqlite3.OperationalError: too many SQL variables

2021-06-05T03:42:39.772 full_node full_node_server        : WARNING  Trying to ban localhost for 10, but will not ban
2021-06-05T03:42:39.772 full_node asyncio                 : ERROR    Task exception was never retrieved
future: <Task finished coro=<ChiaServer.incoming_api_task.<locals>.api_call() done, defined at chia\server\server.py:487> exception=CancelledError()>
concurrent.futures._base.CancelledError
2021-06-05T03:48:43.021 full_node full_node_server        : ERROR    Exception: too many SQL variables, {'host': '127.0.0.1', 'port': 8449}. Traceback (most recent call last):
  File "chia\server\server.py", line 526, in wrapped_coroutine
  File "chia\full_node\full_node_api.py", line 244, in request_proof_of_weight
  File "chia\full_node\weight_proof.py", line 77, in get_proof_of_weight
  File "chia\full_node\weight_proof.py", line 119, in _create_proof_of_weight
  File "chia\consensus\blockchain.py", line 695, in get_block_records_at
  File "chia\full_node\block_store.py", line 181, in get_block_records_by_hash
  File "aiosqlite\core.py", line 184, in execute
  File "aiosqlite\core.py", line 129, in _execute
  File "aiosqlite\core.py", line 102, in run
sqlite3.OperationalError: too many SQL variables

This repeats around every 6 minutes.

**Comment by MarcusB2105** [comment]
There are four issues to the same problem already:  #6478 and #6466 and #6450 including this one #6455 .

**Comment by MarcusB2105** [comment]
The ChiaSetup 1.1.7 is now available on the official chia.net download section. This should solve the problem.

**Comment by mariano54** [comment]
Fixed as marcus pointed out.
