### ISSUE TITLE
[BUG] TypeError: fromhex() argument must be str, not int

### ISSUE THREAD

**Issue by KrakenTyio** [Chia-Network/chia-blockchain#6553]
**Describe the bug**
After upgrade on ubuntu 20.04 server+openbox to version 1.1.7 by tags/1.1.7 and install, cannot run full_node, bc after few second rase this error.
Downgrading back to branch latest, its also cannot be runned, same error. Probably somthing crash there in stored blocks.

**Additional context**
```
Traceback (most recent call last):
  File "/home/sultan/chia-blockchain/venv/bin/chia_full_node", line 33, in <module>
    sys.exit(load_entry_point('chia-blockchain', 'console_scripts', 'chia_full_node')())
  File "/home/sultan/chia-blockchain/chia/server/start_full_node.py", line 60, in main
    return run_service(**kwargs)
  File "/home/sultan/chia-blockchain/chia/server/start_service.py", line 226, in run_service
    return asyncio.run(async_run_service(*args, **kwargs))
  File "/usr/lib/python3.8/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/sultan/chia-blockchain/chia/server/start_service.py", line 220, in async_run_service
    return await service.run()
  File "/home/sultan/chia-blockchain/chia/server/start_service.py", line 160, in run
    await self.start()
  File "/home/sultan/chia-blockchain/chia/server/start_service.py", line 128, in start
    await self._node._start(**kwargs)
  File "/home/sultan/chia-blockchain/chia/full_node/full_node.py", line 127, in _start
    self.blockchain = await Blockchain.create(self.coin_store, self.block_store, self.constants)
  File "/home/sultan/chia-blockchain/chia/consensus/blockchain.py", line 113, in create
    await self._load_chain_from_store()
  File "/home/sultan/chia-blockchain/chia/consensus/blockchain.py", line 125, in _load_chain_from_store
    height_to_hash, sub_epoch_summaries = await self.block_store.get_peak_height_dicts()
  File "/home/sultan/chia-blockchain/chia/full_node/block_store.py", line 322, in get_peak_height_dicts
    hash_to_prev_hash[bytes.fromhex(row[0])] = bytes.fromhex(row[1])
TypeError: fromhex() argument must be str, not int

```

**Comment by KrakenTyio** [comment]
clear `~/.chia/mainnet/db` help but its not a solution

**Comment by Knight1** [comment]
Had the same problem. Chia was accidentally still running while i copied the db / wallet/db.
Shut down all daemons, verify that and then copy the folder. What way it works!

**Comment by Surajsonkar07** [comment]
{
  "error": "argument must be str, not int"
}
