### ISSUE TITLE
[BUG] ERROR Exception fetching pool info from

### ISSUE THREAD

**Issue by RustyCleaner** [Chia-Network/chia-blockchain#6564]
What could be wrong with this ? 
This is from Client pooling on testnet >

2021-06-07T06:06:18.443 farmer chia.farmer.farmer         : ERROR    Exception fetching pool info from http:// pooladdressblahblah. org, Cannot connect to host http:80 ssl:default [Temporary failure in name resolution]

This is from Pool Server > 

ERROR:aiohttp.server:Error handling request
Traceback (most recent call last):
  File "/home/chia/pool-reference/venv/lib/python3.8/site-packages/aiohttp/web_protocol.py", line 314, in data_received
    messages, upgraded, tail = self._request_parser.feed_data(data)
  File "aiohttp/_http_parser.pyx", line 546, in aiohttp._http_parser.HttpParser.feed_data
aiohttp.http_exceptions.BadStatusLine: 400, message="Bad status line 'invalid HTTP method" 

Harvester is working, and we are getting points in gui-pool info. But we have this error on Client and Server side from logs.

**Comment by Djomla003** [comment]
@mariano54 @ChiaMineJP @seeden @eFishCent   this looks like a DNS/CNAME problem right?

**Comment by Nico-VanHaaster** [comment]
I have the same problem however with mine we are using https with the exception
```
Exception fetching pool info from https://hostname, Cannot connect to host https:80 ssl:default [Temporary failure in name resolution]
```
I have gone through the command line and tried adding the pool that way with `chia plotnft create -u hostname:443` and this doest not work. However using `chia plotnft create -u hostname:80` and so far no errors. I will post back if we start seeing partials coming through.

**Comment by RustyCleaner** [comment]
@Nico-VanHaaster 
Thank you for response.
I will try this later to see if it works.
