### ISSUE TITLE
Chia synchronizing and Wallet synchronizing issues still exist in Chia1.7 Windows 10

### ISSUE THREAD

**Issue by Tiger-Stone** [Chia-Network/chia-blockchain#6616]
The Chia synchronizing and Chia wallet synchronizing issues are not new, but they are still big issues in Chia 1.1.7. The question is: if this issue can not be fixed or Chia project is not willing to fix it?

**Comment by egarcia17e** [comment]
I have the same issue, in the log appear a lot of SSL issues.

2021-06-08T21:42:34.411 full_node full_node_server        : INFO     Cannot connect to host 73.53.49.76:8444 ssl:<ssl.SSLContext object at 0x00000235F3D2CC18> [Connect call failed ('73.53.49.76', 8444)]
2021-06-08T21:42:36.693 full_node full_node_server        : INFO     Cannot connect to host 219.114.233.96:8444 ssl:<ssl.SSLContext object at 0x00000235E7125B38> [Connect call failed ('219.114.233.96', 8444)]
2021-06-08T21:42:38.934 full_node full_node_server        : INFO     Cannot connect to host 82.14.98.123:8444 ssl:<ssl.SSLContext object at 0x00000235F3237DD8> [Connect call failed ('82.14.98.123', 8444)]
2021-06-08T21:42:43.446 full_node full_node_server        : INFO     Cannot connect to host 88.3.19.86:8444 ssl:<ssl.SSLContext object at 0x00000235F4148DD8> [Connect call failed ('88.3.19.86', 8444)]
2021-06-08T21:42:45.702 full_node full_node_server        : INFO     Cannot connect to host 76.64.112.231:8444 ssl:<ssl.SSLContext object at 0x00000235F49A9358> [Connect call failed ('76.64.112.231', 8444)]
2021-06-08T21:42:47.970 full_node full_node_server        : INFO     Cannot connect to host 115.44.37.17:8444 ssl:<ssl.SSLContext object at 0x00000235F34566D8> [Connect call failed ('115.44.37.17', 8444)]
2021-06-08T21:42:50.233 full_node full_node_server        : INFO     Cannot connect to host 5.12.234.251:8444 ssl:<ssl.SSLContext object at 0x00000235F48442E8> [Connect call failed ('5.12.234.251', 8444)]
2021-06-08T21:42:52.518 full_node full_node_server        : INFO     Cannot connect to host 80.202.37.228:8444 ssl:<ssl.SSLContext object at 0x00000235F4844E48> [Connect call failed ('80.202.37.228', 8444)]
2021-06-08T21:42:54.786 full_node full_node_server        : INFO     Cannot connect to host 5.116.70.103:8444 ssl:<ssl.SSLContext object at 0x00000235E8A01128> [Connect call failed ('5.116.70.103', 8444)]

**Comment by egarcia17e** [comment]
I detect this error in log:
2021-06-08T23:56:42.181 full_node chia.full_node.full_node: WARNING  Received unsolicited/late block from peer {'host': '85.93.250.176', 'port': 8444}
2021-06-08T23:56:42.638 full_node full_node_server        : INFO     Connection closed: 85.93.250.176, node id: ba87f3ad28703fc454ca749c4fadf42bada99f28407a367d83dbc176b1e00cc0
2021-06-08T23:56:42.639 full_node chia.full_node.full_node: INFO     peer disconnected None
2021-06-08T23:56:42.641 full_node chia.full_node.full_node: ERROR    Error with syncing: <class 'RuntimeError'>Traceback (most recent call last):
  File "chia\full_node\full_node.py", line 640, in _sync
RuntimeError: Weight proof did not arrive in time from peer: 85.93.250.176

Ver 1.1.7
Win10

**Comment by egarcia17e** [comment]
Another error in the log:

2021-06-09T00:14:19.180 full_node chia.full_node.full_node: INFO     Requesting weight proof from peer 66.147.239.173 up to height 405042
2021-06-09T00:14:19.559 full_node full_node_server        : INFO     Connected with full_node {'host': '86.9.80.248', 'port': 8444}
2021-06-09T00:14:19.597 full_node full_node_server        : INFO     Connection closed: 86.9.80.248, node id: 9e9d761cf589bf395107389da7d3093e8a71e9b56351bf4d685c9f2efa42b3d2
2021-06-09T00:14:19.599 full_node chia.full_node.full_node: INFO     peer disconnected {'host': '86.9.80.248', 'port': 8444}
2021-06-09T00:14:20.294 full_node chia.full_node.full_node: WARNING  Received unsolicited/late block from peer {'host': '66.147.239.173', 'port': 8444}
2021-06-09T00:14:21.989 full_node full_node_server        : INFO     Cannot connect to host 78.182.139.72:8444 ssl:<ssl.SSLContext object at 0x000001FB8E1DE748> [Connect call failed ('78.182.139.72', 8444)]
2021-06-09T00:14:22.057 full_node full_node_server        : INFO     Connection closed: 66.147.239.173, node id: cea1fcde17c7e31387393d8c90deddd058fffcc127468fc6fde13310059ac130
2021-06-09T00:14:22.059 full_node chia.full_node.full_node: INFO     peer disconnected None
2021-06-09T00:14:22.061 full_node full_node_server        : ERROR    Exception:  <class 'concurrent.futures._base.CancelledError'>, closing connection None. Traceback (most recent call last):
  File "chia\server\server.py", line 536, in api_call
  File "asyncio\tasks.py", line 435, in wait_for
concurrent.futures._base.CancelledError

2021-06-09T00:14:22.063 full_node chia.full_node.full_node: ERROR    Error with syncing: <class 'RuntimeError'>Traceback (most recent call last):
  File "chia\full_node\full_node.py", line 640, in _sync
RuntimeError: Weight proof did not arrive in time from peer: 66.147.239.173

Ver 1.1.7
win10
