### ISSUE TITLE
 Failed to open file ,Invalid number of bytes 3 Traceback (most recent call last), ValueError: Invalid number of bytes 3

### ISSUE THREAD

**Issue by alexey-sl** [Chia-Network/chia-blockchain#6633]
The problem occurs on one linux PC. 
After ploting completion, running `chia plots check` results in the error:
` Failed to open file /home/alexey/mnt/hdd1/p/plot-k32-2021-06-08-22-59-110fe45bc6d231a8d16df0f7ac8d90fc10d71030e227137c564591ba162ffa84.plot. Invalid number of bytes 3 Traceback (most recent call last):
  File "/home/alexey/chia-blockchain/chia/plotting/plot_tools.py", line 208, in process_file
    ) = parse_plot_info(prover.get_memo())
  File "/home/alexey/chia-blockchain/chia/plotting/plot_tools.py", line 82, in parse_plot_info
    raise ValueError(f"Invalid number of bytes {len(memo)}")
ValueError: Invalid number of bytes 3
`

Reinstalled chia. Replottet (twice). All the same behavior. 
Plotting on other PC - all is just fine.
Where to dig?

**Comment by alexey-sl** [comment]
No clue for now. 
PC is Ryzen 3700X. No overclock, just defauls settings. 16Gb RAM. NVME 1Gb.
Just a PC. Nothing special.
System is Linux Debian. 
Tested on different filesystems. On EXT4 and XFS - same result. 
Can anyone just tell me what is wrong with plotting on this PC?
I have other PCs on net. They all plotting just fine.

**Comment by alexey-sl** [comment]
Is anybody here? Can anyone just tell me what is wrong with this PC. What exactly the error means? Maybe I'can find the clue myself, but I need to know where to dig.

**Comment by alexey-sl** [comment]
Tested non functional plots on other PC.
Same result.
It seems that this machine creates corrupted plots. Somehow.
For this moment I have no feedback about the subject - what exactly wrong wight plot-files.

**Comment by alexey-sl** [comment]
Solution is to remove flags 'discard' and 'noatime'. 
I don't know which of them affected the plotting process making plot corrupted. 
Thanks for help... :(
