### ISSUE TITLE
[BUG]Caught plotting error: Not enough memory for sort in memory

### ISSUE THREAD

**Issue by mub1jo** [Chia-Network/chia-blockchain#6643]
Compressing tables 1 and 2
Caught plotting error: Not enough memory for sort in memory. Need to sort 14.818211GiB
Traceback (most recent call last):
  File "chia\cmds\chia.py", line 81, in <module>
  File "chia\cmds\chia.py", line 77, in main
  File "click\core.py", line 829, in __call__
  File "click\core.py", line 782, in main
  File "click\core.py", line 1259, in invoke
  File "click\core.py", line 1259, in invoke
  File "click\core.py", line 1066, in invoke
  File "click\core.py", line 610, in invoke
  File "click\decorators.py", line 21, in new_func
  File "chia\cmds\plots.py", line 135, in create_cmd
  File "chia\plotting\create_plots.py", line 176, in create_plots
RuntimeError: Unknown exception
[13052] Failed to execute script chia

THIS SHOULD'NT HAPPEN WHEN HAVING 8GB FREE RAM

![Screenshot_4](https://user-images.githubusercontent.com/84607750/121395577-c6995f80-c97c-11eb-9ead-9ef36fe51db0.jpg)

- OS: windows
- OS Version/Flavor: 
- CPU: i5-9600kf  ram 16gb

**Comment by gromran** [comment]
> THIS SHOULD'NT HAPPEN WHEN HAVING 8GB FREE RAM

> Need to sort 14.818211GiB

...
Have you changed anything in the settings?

**Comment by racergoodwin** [comment]
This is the same as my #6053

**Comment by OldButtKicking** [comment]
I'm seeing the same problem. Plotting has been fine then all of a sudden I notice the following in the log. There is 16GB free on a 32GB machine but it claims to not have enough to sort .5 GB

Forward propagation table time: 1398.952 seconds. CPU (179.700%) Tue Jun 22 15:11:19 2021
Computing table 3
Caught plotting error: Not enough memory for sort in memory. Need to sort 0.562430GiB
[11524] Failed to execute script chia
Traceback (most recent call last):
  File "chia\cmds\chia.py", line 81, in <module>
  File "chia\cmds\chia.py", line 77, in main
  File "click\core.py", line 829, in __call__
  File "click\core.py", line 782, in main
  File "click\core.py", line 1259, in invoke
  File "click\core.py", line 1259, in invoke
  File "click\core.py", line 1066, in invoke
  File "click\core.py", line 610, in invoke
  File "click\decorators.py", line 21, in new_func
  File "chia\cmds\plots.py", line 135, in create_cmd
  File "chia\plotting\create_plots.py", line 176, in create_plots
RuntimeError: Unknown exception

**Comment by gromran** [comment]
> I'm seeing the same problem. Plotting has been fine then all of a sudden I notice the following in the log. There is 16GB free on a 32GB machine but it claims to not have enough to sort .5 GB
> 
> Forward propagation table time: 1398.952 seconds. CPU (179.700%) Tue Jun 22 15:11:19 2021
> Computing table 3
> Caught plotting error: Not enough memory for sort in memory. Need to sort 0.562430GiB
> [11524] Failed to execute script chia
> Traceback (most recent call last):
> File "chia\cmds\chia.py", line 81, in
> File "chia\cmds\chia.py", line 77, in main
> File "click\core.py", line 829, in **call**
> File "click\core.py", line 782, in main
> File "click\core.py", line 1259, in invoke
> File "click\core.py", line 1259, in invoke
> File "click\core.py", line 1066, in invoke
> File "click\core.py", line 610, in invoke
> File "click\decorators.py", line 21, in new_func
> File "chia\cmds\plots.py", line 135, in create_cmd
> File "chia\plotting\create_plots.py", line 176, in create_plots
> RuntimeError: Unknown exception

As with the first post (where there was no reaction ...)
Have you changed anything in the settings? For example something like deactivating the swap file?

**Comment by ShawnArcher** [comment]
No changes at all. It had been running fine. There were two plotters running but the first had finished it’s queue and I noticed the second seemed to have stopped and that was at the end of its log. I was using the GUI 4 threads , 6 gig ram each plotter

**Comment by ShawnArcher** [comment]
Sorry I am the same person I guess I’m logged in with a different account on my phone

**Comment by OldButtKicking** [comment]
I don't now if it adds any value but when I went in to clean up the temp files and it seemed like there were not very many, I thought there were  usually more...
![image](https://user-images.githubusercontent.com/58090640/123501911-25a5d800-d5fd-11eb-93d4-4daaebe02388.png)
