### ISSUE TITLE
[BUG] ERROR Exception: Failed to fetch block XXXXXX from None, timed out

### ISSUE THREAD

**Issue by jsvuz** [Chia-Network/chia-blockchain#6645]
**Describe the bug**
Got this error by running the command Get-Content $env:USERPROFILE\.chia\mainnet\log\debug.log | Select-String -Pattern ("warning","error") in PowerShell.

**Screenshots**
![image](https://user-images.githubusercontent.com/85643812/121411955-d610ac80-c96c-11eb-84b6-a28273702a31.PNG)

**Desktop (please complete the following information):**

- OS: Windows
- OS Version/Flavor: 10
- CPU: Intel Core i7-8700K
- 32GB memory
- 1x Samsung 970 EVO Plus 1T NVME
- 1x PNY CS3030 1T NVME
- 1x Samsung 980 500GB for OS

**Additional context**
Installed Chia version 1.1.7, no changes to program files or chia files running only Chia and OS.
What caused it?
I would be grateful for any help! Thank you!

**Comment by Flint4** [comment]
Still happening. Full message from debug.log: 

```
2021-07-14T21:17:18.252 full_node full_node_server        : ERROR    Exception: Failed to fetch block 571919 from None, timed out, None. Traceback (most recent call last):
  File "/home/ubuntu/chia-blockchain/chia/server/server.py", line 523, in wrapped_coroutine
    result = await coroutine
  File "/home/ubuntu/chia-blockchain/chia/full_node/full_node_api.py", line 106, in new_peak
    return await self.full_node.new_peak(request, peer)
  File "/home/ubuntu/chia-blockchain/chia/full_node/full_node.py", line 397, in new_peak
    if await self.short_sync_backtrack(
  File "/home/ubuntu/chia-blockchain/chia/full_node/full_node.py", line 331, in short_sync_backtrack
    raise e
  File "/home/ubuntu/chia-blockchain/chia/full_node/full_node.py", line 316, in short_sync_backtrack
    raise ValueError(f"Failed to fetch block {curr_height} from {peer.get_peer_info()}, timed out")
ValueError: Failed to fetch block 571919 from None, timed out

2021-07-14T21:17:18.255 full_node full_node_server        : ERROR    Exception: Failed to fetch block 571919 from None, timed out <class 'ValueError'>, closing connection None. Traceback (most recent call last):
  File "/home/ubuntu/chia-blockchain/chia/server/server.py", line 533, in api_call
    response: Optional[Message] = await asyncio.wait_for(wrapped_coroutine(), timeout=timeout)
  File "/usr/lib/python3.9/asyncio/tasks.py", line 442, in wait_for
    return await fut
  File "/home/ubuntu/chia-blockchain/chia/server/server.py", line 530, in wrapped_coroutine
    raise e
  File "/home/ubuntu/chia-blockchain/chia/server/server.py", line 523, in wrapped_coroutine
    result = await coroutine
  File "/home/ubuntu/chia-blockchain/chia/full_node/full_node_api.py", line 106, in new_peak
    return await self.full_node.new_peak(request, peer)
  File "/home/ubuntu/chia-blockchain/chia/full_node/full_node.py", line 397, in new_peak
    if await self.short_sync_backtrack(
  File "/home/ubuntu/chia-blockchain/chia/full_node/full_node.py", line 331, in short_sync_backtrack
    raise e
  File "/home/ubuntu/chia-blockchain/chia/full_node/full_node.py", line 316, in short_sync_backtrack
    raise ValueError(f"Failed to fetch block {curr_height} from {peer.get_peer_info()}, timed out")
ValueError: Failed to fetch block 571919 from None, timed out
```
Ubuntu 21, Chia 1.2.2

**Comment by shaunlourdes84** [comment]
Desktop (please complete the following information):

OS: Windows
OS Version/Flavor: 10
CPU: AMD Ryzen 7 3800x
32GB memory
1x Samsung 970 EVO Plus 1T NVME

2021-07-21T15:33:50.297 full_node full_node_server        : ERROR    Exception: Failed to fetch block 602144 from None, timed out, None. Traceback (most recent call last):
  File "chia\server\server.py", line 523, in wrapped_coroutine
  File "chia\full_node\full_node_api.py", line 106, in new_peak
  File "chia\full_node\full_node.py", line 397, in new_peak
  File "chia\full_node\full_node.py", line 331, in short_sync_backtrack
  File "chia\full_node\full_node.py", line 316, in short_sync_backtrack
ValueError: Failed to fetch block 602144 from None, timed out

2021-07-21T15:33:50.299 full_node full_node_server        : ERROR    Exception: Failed to fetch block 602144 from None, timed out <class 'ValueError'>, closing connection None. Traceback (most recent call last):
  File "chia\server\server.py", line 533, in api_call
  File "asyncio\tasks.py", line 442, in wait_for
  File "chia\server\server.py", line 530, in wrapped_coroutine
  File "chia\server\server.py", line 523, in wrapped_coroutine
  File "chia\full_node\full_node_api.py", line 106, in new_peak
  File "chia\full_node\full_node.py", line 397, in new_peak
  File "chia\full_node\full_node.py", line 331, in short_sync_backtrack
  File "chia\full_node\full_node.py", line 316, in short_sync_backtrack
ValueError: Failed to fetch block 602144 from None, timed out

2021-07-21T15:54:55.719 full_node full_node_server        : ERROR    Exception: Failed to fetch block 602220 from {'host': '37.235.195.240', 'port': 8444}, timed out, {'host': '37.235.195.240', 'port': 8444}. Traceback (most recent call last):
  File "chia\server\server.py", line 523, in wrapped_coroutine
  File "chia\full_node\full_node_api.py", line 106, in new_peak
  File "chia\full_node\full_node.py", line 397, in new_peak
  File "chia\full_node\full_node.py", line 331, in short_sync_backtrack
  File "chia\full_node\full_node.py", line 316, in short_sync_backtrack
ValueError: Failed to fetch block 602220 from {'host': '37.235.195.240', 'port': 8444}, timed out

2021-07-21T15:54:55.720 full_node full_node_server        : ERROR    Exception: Failed to fetch block 602220 from {'host': '37.235.195.240', 'port': 8444}, timed out <class 'ValueError'>, closing connection {'host': '37.235.195.240', 'port': 8444}. Traceback (most recent call last):
  File "chia\server\server.py", line 533, in api_call
  File "asyncio\tasks.py", line 442, in wait_for
  File "chia\server\server.py", line 530, in wrapped_coroutine
  File "chia\server\server.py", line 523, in wrapped_coroutine
  File "chia\full_node\full_node_api.py", line 106, in new_peak
  File "chia\full_node\full_node.py", line 397, in new_peak
  File "chia\full_node\full_node.py", line 331, in short_sync_backtrack
  File "chia\full_node\full_node.py", line 316, in short_sync_backtrack
ValueError: Failed to fetch block 602220 from {'host': '37.235.195.240', 'port': 8444}, timed out

2021-07-21T15:55:06.003 full_node full_node_server        : WARNING  Banning 37.235.195.240 for 10 seconds
2021-07-21T15:55:47.787 farmer chia.farmer.farmer         : ERROR    Error in GET /farmer https://asia.ecochia.io, 502
2021-07-21T15:55:48.641 farmer chia.farmer.farmer         : ERROR    Error in GET /farmer https://asia.ecochia.io, 502
