### ISSUE TITLE
[BUG] Connecting to wallet v1.1.7

### ISSUE THREAD

**Issue by cafsantos7** [Chia-Network/chia-blockchain#6646]
I since I have updated for the new Chia version 1.1.7, I cannot pass from the "Connecting to wallet" message...

I have to reinstall the v1.1.5, that was the last working version on my machine. And I have already clear .chia folders, restart machine, un-install and install again Chia, ...

- OS: Windows 10 Pro (64-bit)
- OS Version/Flavor: 20H2
- CPU: AMD Ryzen 9 3900X 12-Core Processor

Log info:
2021-06-09T10:47:20.557 harvester chia.harvester.harvester: WARNING  Not farming any plots on this harvester. Check your configuration.
2021-06-09T15:06:18.264 full_node chia.full_node.full_node: ERROR    Exception: A DNS label is empty.
2021-06-09T15:06:18.269 full_node chia.full_node.full_node: ERROR    Exception in peer discovery: A DNS label is empty.
2021-06-09T15:06:18.271 full_node chia.full_node.full_node: ERROR    Exception Stack: Traceback (most recent call last):
  File "chia\full_node\full_node.py", line 194, in set_server
  File "chia\server\node_discovery.py", line 476, in __init__
  File "chia\server\node_discovery.py", line 66, in __init__
  File "dns\resolver.py", line 732, in __init__
  File "dns\resolver.py", line 928, in read_registry
  File "dns\resolver.py", line 891, in _config_win32_fromkey
  File "dns\resolver.py", line 854, in _config_win32_domain
  File "dns\name.py", line 942, in from_text
dns.name.EmptyLabel: A DNS label is empty.

2021-06-09T15:06:19.946 harvester chia.harvester.harvester: WARNING  Not farming any plots on this harvester. Check your configuration.

Thank you in advance for your help.
Regards
![chia](https://user-images.githubusercontent.com/13049668/121415241-8367ce00-c935-11eb-8ba4-1ee895796a8a.png)

**Comment by bobro2** [comment]
Check #6675 I found temporary workaround.
