### ISSUE TITLE
Exception in thread Thread-1 when starting node

### ISSUE THREAD

**Issue by gcraenen** [Chia-Network/chia-blockchain#6701]
Running latest version 1.1.7 of chia-blockchain on an Ubuntu linux 20.04 box, from github and conform wiki installed/upgraded.

Starting up (cli): chia start farmer after . ./activate.

Then:

```
 Exception in thread Thread-1:
Traceback (most recent call last):
Traceback (most recent call last):
  File "/home/gcraenen/chia-blockchain/venv/lib/python3.8/site-packages/aiosqlite/core.py", line 109, in run
  File "/home/gcraenen/chia-blockchain/venv/bin/chia_full_node", line 33, in <module>
    get_loop(future).call_soon_threadsafe(set_result, future, result)
    sys.exit(load_entry_point('chia-blockchain', 'console_scripts', 'chia_full_node')())
  File "/home/gcraenen/chia-blockchain/chia/server/start_full_node.py", line 60, in main
    return run_service(**kwargs)
  File "/home/gcraenen/chia-blockchain/chia/server/start_service.py", line 226, in run_service
    return asyncio.run(async_run_service(*args, **kwargs))
  File "/usr/lib/python3.8/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
  File "/usr/lib/python3.8/asyncio/base_events.py", line 764, in call_soon_threadsafe
    return future.result()
  File "/home/gcraenen/chia-blockchain/chia/server/start_service.py", line 220, in async_run_service
    self._check_closed()
  File "/usr/lib/python3.8/asyncio/base_events.py", line 508, in _check_closed
    return await service.run()
  File "/home/gcraenen/chia-blockchain/chia/server/start_service.py", line 160, in run
    await self.start()
  File "/home/gcraenen/chia-blockchain/chia/server/start_service.py", line 136, in start
    await self._server.start_server(self._on_connect_callback)
  File "/home/gcraenen/chia-blockchain/chia/server/server.py", line 218, in start_server
    await self.site.start()
    raise RuntimeError('Event loop is closed')
  File "/home/gcraenen/chia-blockchain/venv/lib/python3.8/site-packages/aiohttp/web_runner.py", line 121, in start
RuntimeError: Event loop is closed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self._server = await loop.create_server(
  File "/usr/lib/python3.8/asyncio/base_events.py", line 1463, in create_server
    self.run()
  File "/home/gcraenen/chia-blockchain/venv/lib/python3.8/site-packages/aiosqlite/core.py", line 117, in run
    raise OSError(err.errno, 'error while attempting '
OSError: [Errno 98] error while attempting to bind on address ('0.0.0.0', 8444): address already in use
    get_loop(future).call_soon_threadsafe(set_exception, future, e)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 764, in call_soon_threadsafe
    self._check_closed()
  File "/usr/lib/python3.8/asyncio/base_events.py", line 508, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
```

Then: chia show -s:

```
Connection error. Check if full node rpc is running at 8555
This is normal if full node is still starting up
```

Node is not up and no farming is taking place.

**Comment by arielylim** [comment]
Getting this now on 1.1.7. you manage to resolve it? 1.1.6 was working fine. 

One additional thing is my wallet is syncing. Only the node is affected. The opposite of most farmers where node is syncing and wallet isn’t.

**Comment by sostela** [comment]
use command " kill -9 ****" to kill all chia process that find in "ps aux | grep chia" before start.
