### ISSUE TITLE
Login error

### ISSUE THREAD

**Issue by seeden** [Chia-Network/chia-blockchain#6814]
I am using the latest *pools.dev8 branch with *testnet8* and I see an error message in the GUI when I try to call command "log_in".

<img width="595" alt="Screenshot 2021-06-16 at 22 14 28" src="https://user-images.githubusercontent.com/3958832/122286646-61032100-cef0-11eb-8dbe-05f72fe074e4.png">
<img width="679" alt="Screenshot 2021-06-16 at 22 14 45" src="https://user-images.githubusercontent.com/3958832/122286657-63fe1180-cef0-11eb-8fca-18f740e787b6.png">

I see these issues in the debug.log:

```log

2021-06-16T22:10:41.427 wallet chia.rpc.rpc_server        : WARNING  Error while handling message: Traceback (most recent call last):
  File "/Users/seeden/Documents/git/chia-blockchain/chia/rpc/rpc_server.py", line 212, in safe_handle
    response = await self.ws_api(message)
  File "/Users/seeden/Documents/git/chia-blockchain/chia/rpc/rpc_server.py", line 203, in ws_api
    return await f(data)
  File "/Users/seeden/Documents/git/chia-blockchain/chia/rpc/wallet_rpc_api.py", line 164, in log_in
    started = await self.service._start(fingerprint)
  File "/Users/seeden/Documents/git/chia-blockchain/chia/wallet/wallet_node.py", line 158, in _start
    self.wallet_state_manager = await WalletStateManager.create(
  File "/Users/seeden/Documents/git/chia-blockchain/chia/wallet/wallet_state_manager.py", line 146, in create
    self.blockchain = await WalletBlockchain.create(
  File "/Users/seeden/Documents/git/chia-blockchain/chia/wallet/wallet_blockchain.py", line 116, in create
    await self._load_chain_from_store()
  File "/Users/seeden/Documents/git/chia-blockchain/chia/wallet/wallet_blockchain.py", line 127, in _load_chain_from_store
    height_to_hash, sub_epoch_summaries = await self.block_store.get_peak_heights_dicts()
  File "/Users/seeden/Documents/git/chia-blockchain/chia/wallet/wallet_block_store.py", line 322, in get_peak_heights_dicts
    curr_height = hash_to_height[curr_header_hash]
KeyError: b'3)(\xdd\xff&o*\n\xb1g\x1e\x9d\x14tZ\xb2\xa6\x8e\xa9\xfe3?\xfd\x18\xa1O\x9f\xedB\x9e\xef'

2021-06-16T22:11:22.638 wallet chia.rpc.rpc_server        : WARNING  Error while handling message: Traceback (most recent call last):
  File "/Users/seeden/Documents/git/chia-blockchain/chia/rpc/rpc_server.py", line 212, in safe_handle
    response = await self.ws_api(message)
  File "/Users/seeden/Documents/git/chia-blockchain/chia/rpc/rpc_server.py", line 203, in ws_api
    return await f(data)
  File "/Users/seeden/Documents/git/chia-blockchain/chia/rpc/wallet_rpc_api.py", line 164, in log_in
    started = await self.service._start(fingerprint)
  File "/Users/seeden/Documents/git/chia-blockchain/chia/wallet/wallet_node.py", line 158, in _start
    self.wallet_state_manager = await WalletStateManager.create(
  File "/Users/seeden/Documents/git/chia-blockchain/chia/wallet/wallet_state_manager.py", line 146, in create
    self.blockchain = await WalletBlockchain.create(
  File "/Users/seeden/Documents/git/chia-blockchain/chia/wallet/wallet_blockchain.py", line 116, in create
    await self._load_chain_from_store()
  File "/Users/seeden/Documents/git/chia-blockchain/chia/wallet/wallet_blockchain.py", line 127, in _load_chain_from_store
    height_to_hash, sub_epoch_summaries = await self.block_store.get_peak_heights_dicts()
  File "/Users/seeden/Documents/git/chia-blockchain/chia/wallet/wallet_block_store.py", line 322, in get_peak_heights_dicts
    curr_height = hash_to_height[curr_header_hash]
KeyError: b'3)(\xdd\xff&o*\n\xb1g\x1e\x9d\x14tZ\xb2\xa6\x8e\xa9\xfe3?\xfd\x18\xa1O\x9f\xedB\x9e\xef'
```

**Comment by luismichelve** [comment]
i have the same problem

**Comment by seeden** [comment]
It is somehow connected to the second error message and debug log.
<img width="594" alt="Screenshot 2021-06-16 at 22 23 38" src="https://user-images.githubusercontent.com/3958832/122287804-a4aa5a80-cef1-11eb-9a53-5c4a2bf16e83.png">

```log
2021-06-16T22:23:22.318 wallet chia.rpc.rpc_server        : WARNING  Error while handling message: Traceback (most recent call last):
  File "/Users/seeden/Documents/git/chia-blockchain/chia/rpc/rpc_server.py", line 212, in safe_handle
    response = await self.ws_api(message)
  File "/Users/seeden/Documents/git/chia-blockchain/chia/rpc/rpc_server.py", line 203, in ws_api
    return await f(data)
  File "/Users/seeden/Documents/git/chia-blockchain/chia/rpc/wallet_rpc_api.py", line 288, in get_height_info
    assert self.service.wallet_state_manager is not None
AssertionError
```

**Comment by seeden** [comment]
I have 3 keys but I am not able to use 2 of them because of this. One key is working fine.

**Comment by luismichelve** [comment]
i have a 2 key. 1 is ok, and other not :(

**Comment by luismichelve** [comment]
@mariano54

**Comment by luismichelve** [comment]
.chia -> mainnet -> wallet -> db (them, delete all files)

**Comment by inkviz96** [comment]
Did u find decision?

**Comment by emlowe** [comment]
Closing old issue
