### ISSUE TITLE
[BUG] Cannot see plots

### ISSUE THREAD

**Issue by ehsanasadi1366** [Chia-Network/chia-blockchain#6895]
Plots made by Chia Blockchain are not placed on the farm. How to solve the problem
![New Bitmap Image1](https://user-images.githubusercontent.com/86263392/122820673-b8a6e100-d290-11eb-8781-ba9e597b6059.jpg)
![Untitled](https://user-images.githubusercontent.com/86263392/122820771-d7a57300-d290-11eb-91f1-b33098e0347a.jpg)

**Comment by devtestnet** [comment]
You can do that for one week and if I will do it again I can do that for
tomorrow or Friday o

**Comment by ehsanasadi1366** [comment]
Is it possible that this problem is caused by a virus in the system?
Will replacing Windows solve this problem?

**Comment by mariano54** [comment]
Have you tried clicking on "Add plot directory" and adding the folder where your plots are?

**Comment by d3vplpl** [comment]
Same issue. No plots visible :(. Attaching the log file.
In logs error like: 2021-06-28T17:56:52.706 wallet chia.wallet.wallet_node    : ERROR    Error while trying to fetch from peer: Traceback (most recent call last):
  File "chia\wallet\wallet_node.py", line 605, in _sync
  File "chia\wallet\wallet_node.py", line 692, in fetch_blocks_and_validate
  File "chia\wallet\wallet_blockchain.py", line 227, in receive_block
  File "chia\wallet\wallet_block_store.py", line 86, in add_block_record
  File "aiosqlite\core.py", line 184, in execute
  File "aiosqlite\core.py", line 129, in _execute
concurrent.futures._base.CancelledError

or:

2021-06-28T17:56:52.706 wallet chia.wallet.wallet_node    : ERROR    Loop exception in sync Was not able to add blocks 474433-474465. Traceback (most recent call last):
  File "chia\wallet\wallet_node.py", line 515, in sync_job
  File "chia\wallet\wallet_node.py", line 614, in _sync

or:
2021-06-28T17:59:02.249 full_node chia.full_node.full_node: ERROR    Exception in create outbound connections: 
2021-06-28T17:59:02.250 full_node chia.full_node.full_node: ERROR    Traceback: Traceback (most recent call last):
  File "chia\server\node_discovery.py", line 378, in _connect_to_peers
  File "asyncio\tasks.py", line 595, in sleep
concurrent.futures._base.CancelledError


2021-06-28T17:59:02.251 full_node full_node_server        : INFO     Cannot connect to host 121.8.137.2:8444 ssl:<ssl.SSLContext object at 0x0000028111F11CF8> [Connect call failed ('121.8.137.2', 8444)]

2021-06-28T17:59:02.588 full_node chia.full_node.full_node: ERROR    Error with syncing: <class 'ValueError'>Traceback (most recent call last):
  File "chia\full_node\full_node.py", line 656, in _sync
  File "chia\full_node\weight_proof.py", line 606, in validate_weight_proof
concurrent.futures.process.BrokenProcessPool: A process in the process pool was terminated abruptly while the future was running or pending.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "chia\full_node\full_node.py", line 659, in _sync
ValueError: Weight proof validation threw an error A process in the process pool was terminated abruptly while the future was running or pending.

**Comment by Teramire** [comment]
This problem too. I have power shutdown and when I turn everything on app can't see anny plots.

**Comment by TomekLBN** [comment]
HI today I reboot chia blockchain and can`t add and see my plots

**Comment by ehsanasadi1366** [comment]
The software does not run completely

**Comment by TomekLBN** [comment]
Hi i fix my problem i find config.yaml backup and i copy all backup to normal file config.yaml now all plot working
