### ISSUE TITLE
chia log dubug info is always writing this error[BUG]

### ISSUE THREAD

**Issue by TedC1** [Chia-Network/chia-blockchain#6896]
2021-06-01T23:21:29.829 full_node chia.rpc.rpc_server     : WARNING  Sending data failed. Exception Traceback (most recent call last):
  File "chia\rpc\rpc_server.py", line 67, in _state_changed
  File "aiohttp\client_ws.py", line 150, in send_str
  File "aiohttp\http_websocket.py", line 687, in send
  File "aiohttp\http_websocket.py", line 643, in _send_frame
  File "aiohttp\http_websocket.py", line 660, in _write
ConnectionResetError: Cannot write to closing transport

NEED HELP TO RESOLVE THE ERROR.

Use windows10 and Chia GUI.

Chia Blockchain 1.1.6.

**Comment by gromran** [comment]
First: old version...
