### ISSUE TITLE
[BUG] - wallet aiosqlite - Cannot operate on a closed database

### ISSUE THREAD

**Issue by yrjo** [Chia-Network/chia-blockchain#700]
during checking wallet via "chia wallet":

**chia version**
1.0b20

**system:**
uname -a
Linux XXXX 5.4.0-58-generic #64-Ubuntu SMP Wed Dec 9 08:16:25 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

**Distro:**
cat /etc/issue
Ubuntu 20.04.1 LTS \n \l

```
10:20:47.962 wallet aiosqlite                  : ERROR    returning exception Cannot operate on a closed database.
Traceback (most recent call last):
  File "/root/chia-blockchain/venv/lib/python3.8/site-packages/aiosqlite/core.py", line 99, in run
    result = function()
sqlite3.ProgrammingError: Cannot operate on a closed database.
10:20:48.838 wallet asyncio                    : ERROR    Exception in callback Future.set_exception(ProgrammingEr...ed database.'))
handle: <Handle Future.set_exception(ProgrammingEr...ed database.'))>
Traceback (most recent call last):
  File "/usr/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
asyncio.exceptions.InvalidStateError: invalid state
```

**Comment by hoffmang9** [comment]
The wallet sync and interaction is a mess and we know. Wallet improvement branch was not quite ready for Beta 21 but will be in the next release.
