### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by chehlvs** [Chia-Network/chia-blockchain#7062]
**Describe the bug**
Hi, since 2 days I get in the CHIA main log the following error mesage frequently every 2 to 3 minutes:

Exception 2 is not a valid ProtocolMessageTypes, exception Stack: ValueError: 2 is not a valid ProtocolMessageTypes

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "chia\server\server.py", line 254, in incoming_connection
  File "chia\server\ws_connection.py", line 142, in perform_handshake
  File "C:\hostedtoolcache\windows\Python\3.7.9\x64\lib\enum.py", line 315, in __call__
  File "C:\hostedtoolcache\windows\Python\3.7.9\x64\lib\enum.py", line 569, in __new__
  File "C:\hostedtoolcache\windows\Python\3.7.9\x64\lib\enum.py", line 553, in __new__
  File "C:\hostedtoolcache\windows\Python\3.7.9\x64\lib\enum.py", line 582, in _missing_
ValueError: 2 is not a valid ProtocolMessageTypes

**To Reproduce**

The error message is produced every 2 to 3 minutes.

**Expected behavior**
This error message is new since 2 days

**Screenshots**
error message as above

**Desktop (please complete the following information):**

- OS: Windows 
- OS Version/Flavor: 10
- CPU: [e.AMD 2600 6 Core, 16 gb RAM
- CHIA: 1.1.7

**Additional context**
Please let me know if oyu need any further information. Thanks in advance!

**Comment by mariano54** [comment]
Duplicate https://github.com/Chia-Network/chia-blockchain/issues/7064

**Comment by Kikicaj** [comment]
Hi Mariano. Is it solved, norhing to worry about? Thanks for actions, was away for a while to reply in 7064.
