### ISSUE TITLE
[BUG] Unable to create new plots with beta 21

### ISSUE THREAD

**Issue by krispipeleers** [Chia-Network/chia-blockchain#707]
Installed beta 21 last night and wanted to add a new plot. Nothing happens in the UI (no error message), but plot creation doesn't start. Getting below error message in the log file.

11:01:55.311 daemon __main__                   : ERROR    problem starting chia plots create
Traceback (most recent call last):
  File "src\daemon\server.py", line 419, in _start_plotting
  File "src\daemon\server.py", line 666, in launch_plotter
  File "subprocess.py", line 800, in __init__
  File "subprocess.py", line 1207, in _execute_child
FileNotFoundError: [WinError 2] The system cannot find the file specified
11:01:55.316 daemon asyncio                    : ERROR    Task exception was never retrieved
future: <Task finished coro=<WebSocketServer._start_plotting() done, defined at src\daemon\server.py:400> exception=Exception('Start plotting failed')>
Traceback (most recent call last):
  File "src\daemon\server.py", line 419, in _start_plotting
  File "src\daemon\server.py", line 666, in launch_plotter
  File "subprocess.py", line 800, in __init__
  File "subprocess.py", line 1207, in _execute_child
FileNotFoundError: [WinError 2] The system cannot find the file specified

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "src\daemon\server.py", line 4

**Comment by hoffmang9** [comment]
I'm pretty sure Windows Defender is deleting daemon. Re-install and don't let it override. We've opened a false positive request with Microsoft.

**Comment by krispipeleers** [comment]
Stopped my defender, reinstalled and that fixed the problem.
