### ISSUE TITLE
Runtime Error: No Keys exist. Please run 'chia keys generate' or open the UI.

### ISSUE THREAD

**Issue by forReason** [Chia-Network/chia-blockchain#7099]
**Describe the bug**
I have a major issue, farming with chia. The Farmer won't start reliably, this makes unattended farming impossible.

**To Reproduce**
Execute batch script in order to start farmer:
 ```
cd C:\Users\%username%\AppData\Local\chia-blockchain\app-1.1.7\resources\app.asar.unpacked\daemon  
chia start farmer
```

Result (around 70% of tries):

> Traceback (most recent call last):
  File "chia\server\start_farmer.py", line 68, in <module>
  File "chia\server\start_farmer.py", line 63, in main
  File "chia\server\start_farmer.py", line 38, in service_kwargs_for_farmer
  File "chia\farmer\farmer.py", line 73, in __init__
RuntimeError: No keys exist. Please run 'chia keys generate' or open the UI.
[10976] Failed to execute script start_farmer

**Expected behavior**
farmer detects saved keys and starts apropriately
![image](https://user-images.githubusercontent.com/12736950/125470646-afa73586-19b9-4274-a373-8b42de41052c.png)

**Desktop (please complete the following information):**

- OS: Windows 10
- OS Version 20H2 Build 19042.1052
- CPU: AMD Ryzen 3600
- Chia Version: 1.2

**Additional context**
The Keys are definitely there. The Gui will always start without any issue.

Executing the script again mostly resolves the issue. So the keys are definitely there.

**Comment by adarshtjc** [comment]
I have the same issue

**Comment by forReason** [comment]
bump issue still exists with latest version.

```
C:\Users\username\AppData\Local\chia-blockchain\app-1.2.3\resources\app.asar.unpacked\daemon>chia start farmer
Daemon not started yet
Starting daemon
chia_harvester: started
chia_farmer: started
chia_full_node: started
chia_wallet: started
Traceback (most recent call last):
  File "D:\a\chia-blockchain\chia-blockchain\venv\Lib\site-packages\chia\server\start_farmer.py", line 68, in <module>
  File "D:\a\chia-blockchain\chia-blockchain\venv\Lib\site-packages\chia\server\start_farmer.py", line 63, in main
  File "D:\a\chia-blockchain\chia-blockchain\venv\Lib\site-packages\chia\server\start_farmer.py", line 38, in service_kwargs_for_farmer
  File "chia\farmer\farmer.py", line 125, in __init__
RuntimeError: No keys exist. Please run 'chia keys generate' or open the UI.
[11824] Failed to execute script start_farmer
```

**Comment by Phanh234** [comment]
> `
Duplicate of #`

**Comment by forReason** [comment]
C:\Windows\system32>C:

C:\Windows\system32>cd C:\Users\julia\AppData\Local\chia-blockchain\app-1.2.5\resources\app.asar.unpacked\daemon

C:\Users\julia\AppData\Local\chia-blockchain\app-1.2.5\resources\app.asar.unpacked\daemon>chia start farmer
Daemon not started yet
Starting daemon
chia_harvester: started
chia_farmer: started
chia_full_node: started
chia_wallet: started
Traceback (most recent call last):
  File "D:\a\chia-blockchain\chia-blockchain\venv\Lib\site-packages\chia\server\start_farmer.py", line 67, in <module>
  File "D:\a\chia-blockchain\chia-blockchain\venv\Lib\site-packages\chia\server\start_farmer.py", line 63, in main
  File "chia\server\start_service.py", line 255, in run_service
  File "asyncio\runners.py", line 44, in run
  File "asyncio\base_events.py", line 642, in run_until_complete
  File "chia\server\start_service.py", line 249, in async_run_service
  File "chia\server\start_service.py", line 171, in run
  File "chia\server\start_service.py", line 135, in start
  File "chia\farmer\farmer.py", line 183, in _start
  File "chia\farmer\farmer.py", line 148, in setup_keys
RuntimeError: No keys exist. Please run 'chia keys generate' or open the UI.
[2032] Failed to execute script 'start_farmer' due to unhandled exception!


Issue still exists on 1.2.5
