### ISSUE TITLE
[BUG] sh install-timelord.sh broken

### ISSUE THREAD

**Issue by dragonfly-net** [Chia-Network/chia-blockchain#7149]
After install chia (debian 10), i run sh install-timelord.sh and got 'no cmake' even if install it before.

(venv) playnet@SuperMicro:~/chia-blockchain$ sh install-timelord.sh
Timelord requires CMake 3.14+ to compile vdf_client.
Python version: python3.7
apt-get is /usr/bin/apt-get
Found Ubuntu/Debian.
Installing chiavdf from source on Ubuntu/Debian
Ubuntu version is pre 20.04LTS - installing CMake with snap.
Reading package lists... Done
Building dependency tree
Reading state information... Done
snap is already the newest version (2013-11-29-9).
The following package was automatically installed and is no longer required:
  linux-image-4.19.0-11-amd64
Use 'sudo apt autoremove' to remove it.
0 upgraded, 0 newly installed, 0 to remove and 70 not upgraded.
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following packages were automatically installed and are no longer required:
  cmake-data libarchive13 libjsoncpp1 librhash0 libuv1 linux-image-4.19.0-11-amd64
Use 'sudo apt autoremove' to remove them.
The following packages will be REMOVED:
  cmake*
0 upgraded, 0 newly installed, 1 to remove and 70 not upgraded.
After this operation, 18.0 MB disk space will be freed.
(Reading database ... 136131 files and directories currently installed.)
Removing cmake (3.13.4-1) ...
Processing triggers for man-db (2.8.5-2) ...
sudo: snap: command not found
apt-get install libgmp-dev libboost-python-dev libpython3.7-dev libboost-system-dev build-essential -y
Reading package lists... Done
Building dependency tree
Reading state information... Done
libboost-python-dev is already the newest version (1.67.0.1).
libboost-system-dev is already the newest version (1.67.0.1).
build-essential is already the newest version (12.6).
libgmp-dev is already the newest version (2:6.1.2+dfsg-4).
libpython3.7-dev is already the newest version (3.7.3-2+deb10u3).
The following packages were automatically installed and are no longer required:
  cmake-data libarchive13 libjsoncpp1 librhash0 libuv1 linux-image-4.19.0-11-amd64
Use 'sudo apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 70 not upgraded.
venv/bin/python -m pip install --force --no-binary chiavdf chiavdf==1.0.1
Collecting chiavdf==1.0.1
  Using cached chiavdf-1.0.1.tar.gz (639 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Building wheels for collected packages: chiavdf
  Building wheel for chiavdf (PEP 517) ... error
  ERROR: Command errored out with exit status 1:
   command: /home/playnet/chia-blockchain/venv/bin/python /home/playnet/chia-blockchain/venv/lib/python3.7/site-packages/pip/_vendor/pep517/in_process/_in_process.py build_wheel /tmp/tmpzjykwouy
       cwd: /tmp/pip-install-kyz8yn1r/chiavdf_b9f8bae1bee64579a0dfd5207dfb7e35
  Complete output (56 lines):
  running bdist_wheel
  running build
  running build_ext
  Traceback (most recent call last):
    File "setup.py", line 96, in run
      out = subprocess.check_output(["cmake", "--version"])
    File "/usr/lib/python3.7/subprocess.py", line 395, in check_output
      **kwargs).stdout
    File "/usr/lib/python3.7/subprocess.py", line 472, in run
      with Popen(*popenargs, **kwargs) as process:
    File "/usr/lib/python3.7/subprocess.py", line 775, in __init__
      restore_signals, start_new_session)
    File "/usr/lib/python3.7/subprocess.py", line 1522, in _execute_child
      raise child_exception_type(errno_num, err_msg, err_filename)
  FileNotFoundError: [Errno 2] No such file or directory: 'cmake': 'cmake'

  During handling of the above exception, another exception occurred:

  Traceback (most recent call last):
    File "/home/playnet/chia-blockchain/venv/lib/python3.7/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 280, in <module>
      main()
    File "/home/playnet/chia-blockchain/venv/lib/python3.7/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 263, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/home/playnet/chia-blockchain/venv/lib/python3.7/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 205, in build_wheel
      metadata_directory)
    File "/tmp/pip-build-env-8ovo7zse/overlay/lib/python3.7/site-packages/setuptools/build_meta.py", line 222, in build_wheel
      wheel_directory, config_settings)
    File "/tmp/pip-build-env-8ovo7zse/overlay/lib/python3.7/site-packages/setuptools/build_meta.py", line 207, in _build_with_temp_dir
      self.run_setup()
    File "/tmp/pip-build-env-8ovo7zse/overlay/lib/python3.7/site-packages/setuptools/build_meta.py", line 150, in run_setup
      exec(compile(code, __file__, 'exec'), locals())
    File "setup.py", line 281, in <module>
      zip_safe=False,
    File "/tmp/pip-build-env-8ovo7zse/overlay/lib/python3.7/site-packages/setuptools/__init__.py", line 153, in setup
      return distutils.core.setup(**attrs)
    File "/usr/lib/python3.7/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/usr/lib/python3.7/distutils/dist.py", line 966, in run_commands
      self.run_command(cmd)
    File "/usr/lib/python3.7/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/tmp/pip-build-env-8ovo7zse/overlay/lib/python3.7/site-packages/wheel/bdist_wheel.py", line 299, in run
      self.run_command('build')
    File "/usr/lib/python3.7/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/lib/python3.7/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/usr/lib/python3.7/distutils/command/build.py", line 135, in run
      self.run_command(cmd_name)
    File "/usr/lib/python3.7/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/lib/python3.7/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "setup.py", line 101, in run
      + ", ".join(e.name for e in self.extensions)
  RuntimeError: CMake must be installed to build the following extensions: chiavdf
  ----------------------------------------
  ERROR: Failed building wheel for chiavdf
Failed to build chiavdf
ERROR: Could not build wheels for chiavdf which use PEP 517 and cannot be installed directly
ERROR: Could not find venv/lib/python3.7/site-packages/vdf_bench
To estimate a timelord on this CPU try './vdf_bench square_asm 400000' for an ips estimate.

$ lsb_release -a
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 10 (buster)
Release:        10
Codename:       buster

No any gui. it's just server without video.

**Comment by hoffmang9** [comment]
This install script assumes an ubuntu specific way to update cmake to 3.14+. Make sure you have cmake 3.14 or newer installed and try again.
