### ISSUE TITLE
[BUG] sqlite3.DatabaseError: database disk image is malformed

### ISSUE THREAD

**Issue by sn0wyfall** [Chia-Network/chia-blockchain#7160]
**Describe the bug**

I get a strange error after running various commands in the chia-blockchain folder. They are described below. 

**To Reproduce**

* Type in `cd chia-blockchain`
* Type in `. ./activate`
* Type in `chia start farmer`
This will output
```
Daemon not started yet
Starting daemon
chia_harvester: started
chia_farmer: started
chia_full_node: started
chia_wallet: started
```
Then the next command prompt will appear, as usual. But after about 5-10 seconds, I will get the following error:
```
  File "/home/user/chia-blockchain/venv/bin/chia_full_node", line 33, in <module>
    sys.exit(load_entry_point('chia-blockchain', 'console_scripts', 'chia_full_node')())
  File "/home/user/chia-blockchain/chia/server/start_full_node.py", line 60, in main
    return run_service(**kwargs)
  File "/home/user/chia-blockchain/chia/server/start_service.py", line 255, in run_service
    return asyncio.run(async_run_service(*args, **kwargs))
  File "/usr/lib/python3.7/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.7/asyncio/base_events.py", line 579, in run_until_complete
    return future.result()
  File "/home/user/chia-blockchain/chia/server/start_service.py", line 249, in async_run_service
    return await service.run()
  File "/home/user/chia-blockchain/chia/server/start_service.py", line 171, in run
    await self.start()
  File "/home/user/chia-blockchain/chia/server/start_service.py", line 135, in start
    await self._node._start(**kwargs)
  File "/home/user/chia-blockchain/chia/full_node/full_node.py", line 129, in _start
    self.blockchain = await Blockchain.create(self.coin_store, self.block_store, self.constants)
  File "/home/user/chia-blockchain/chia/consensus/blockchain.py", line 113, in create
    await self._load_chain_from_store()
  File "/home/user/chia-blockchain/chia/consensus/blockchain.py", line 125, in _load_chain_from_store
    height_to_hash, sub_epoch_summaries = await self.block_store.get_peak_height_dicts()
  File "/home/user/chia-blockchain/chia/full_node/block_store.py", line 300, in get_peak_height_dicts
    rows = await cursor.fetchall()
  File "/home/user/chia-blockchain/venv/lib/python3.7/site-packages/aiosqlite/cursor.py", line 65, in fetchall
    return await self._execute(self._cursor.fetchall)
  File "/home/user/chia-blockchain/venv/lib/python3.7/site-packages/aiosqlite/cursor.py", line 31, in _execute
    return await self._conn._execute(fn, *args, **kwargs)
  File "/home/user/chia-blockchain/venv/lib/python3.7/site-packages/aiosqlite/core.py", line 129, in _execute
    return await future
  File "/home/user/chia-blockchain/venv/lib/python3.7/site-packages/aiosqlite/core.py", line 102, in run
    result = function()
sqlite3.DatabaseError: database disk image is malformed
```
I have to press Control+C to exit out of this error message. 

* Type in `chia stop -d all`. I will get the following error:
```
Exception ignored in: <module 'threading' from '/usr/lib/python3.7/threading.py'>
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 1307, in _shutdown
    lock.acquire()
  File "/home/user/chia-blockchain/chia/server/start_service.py", line 193, in _accept_signal
    self.stop()
  File "/home/user/chia-blockchain/chia/server/start_service.py", line 209, in stop
    self._server.close_all()
  File "/home/user/chia-blockchain/chia/server/server.py", line 634, in close_all
    self.connection_close_task = asyncio.create_task(self.close_all_connections())
  File "/usr/lib/python3.7/asyncio/tasks.py", line 350, in create_task
    loop = events.get_running_loop()
RuntimeError: no running event loop
sys:1: RuntimeWarning: coroutine 'ChiaServer.close_all_connections' was never awaited
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
daemon: {'ack': True, 'command': 'exit', 'data': {'success': True}, 'destination': 'client', 'origin': 'daemon', 'request_id': '419e90d955c4a846b42eeec3ef24c5236b15665546985be3a5462101b7b05dda'}
```

but I will be taken back to a new command prompt line. 

* This keeps happening no matter how much I do them. 

**Screenshots**

![image](https://user-images.githubusercontent.com/24374968/124695833-fa9b6e00-deb1-11eb-89eb-dddfb4532b1b.png)

![image](https://user-images.githubusercontent.com/24374968/124695856-02f3a900-deb2-11eb-894f-07b51094eb37.png)

**Desktop (please complete the following information):**

- OS: Linux
- OS Version/Flavor: Ubuntu something
- CPU: Ryzen 7 2700

**Comment by mariano54** [comment]
The only way to fix this is to delete the Db at ~/.chia/mainnet/db
