### ISSUE TITLE
[BUG] Wallet refuses to sync

### ISSUE THREAD

**Issue by jadechip** [Chia-Network/chia-blockchain#7171]
**Describe the bug**

I am running Chia nodes in multiple Kubernetes clusters, and the wallet constantly gets stuck and refuses to sync.
Below is the output from `~/.chia/mainnet/log/debug.log`

```
2021-07-08T00:25:33.613 wallet chia.wallet.wallet_node    : ERROR    Loop exception in sync Was not able to add blocks 0-32. Traceback (most recent call last):
  File "/chia-blockchain/chia/wallet/wallet_node.py", line 581, in sync_job
    await self._sync()
  File "/chia-blockchain/chia/wallet/wallet_node.py", line 661, in _sync
    await self.batch_sync_to_peak(fork_height, peak)
  File "/chia-blockchain/chia/wallet/wallet_node.py", line 538, in batch_sync_to_peak
    raise RuntimeError(f"Was not able to add blocks {start_height}-{end_height}")
RuntimeError: Was not able to add blocks 0-32
```
and 

```
2021-07-08T00:32:40.917 wallet chia.wallet.wallet_node    : ERROR    Error while trying to fetch from peer:Peer returned no response Traceback (most recent call last):
  File "/chia-blockchain/chia/wallet/wallet_node.py", line 528, in batch_sync_to_peak
    added, advanced_peak = await self.fetch_blocks_and_validate(
  File "/chia-blockchain/chia/wallet/wallet_node.py", line 680, in fetch_blocks_and_validate
    raise ValueError("Peer returned no response")
ValueError: Peer returned no response
```
**To Reproduce**

I tried with both the official Docker images, version `1.1.7` and a custom Docker image that pulls the latest changes from `main`.

I've tried within multiple Kubernetes clusters in different regions and with different cloud providers so it is not a networking issue.

Here is the entry point script I am using:

```
    TZ="Asia/Singapore"

    echo "Setting timezone to ${TZ}"
    ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

    cd /chia-blockchain

    . ./activate

    chia init
    
    sed -i 's/localhost/0.0.0.0/g' ~/.chia/mainnet/config/config.yaml
    # sed -i 's/127.0.0.1/0.0.0.0/g' ~/.chia/mainnet/config/config.yaml

    chia start wallet

    while true; do sleep 30; done;
```

**Expected behavior**
Wallet should begin syncing

- OS: Ubuntu

**Additional context**

**Comment by pnobrega80** [comment]
mine also stopped syncing a few hours.. i'm expecting a new deb release... stopped at 295417 but is connected to a lot of hosts

**Comment by longyuanli** [comment]
same, ubuntu CLI installed chia full node response very slow. And refuse to sync

**Comment by vrichv** [comment]
same,chia show -cs very slow. and wallet not sync.

**Comment by loppefaaret** [comment]
is the `full_node` disconnecting the wallet around the same time this error is happening ?

**Comment by dgfmdrv** [comment]
same, I'm unable to sync my wallet. I tested on the node as farm service is launched and in another wallet-only node.

running a wallet-only service on another host I got this error #7248 and running on the same farm node I get: RuntimeError: Was not able to add blocks 0-32:

```
2021-07-08T22:12:48.084 wallet wallet_server              : DEBUG    <- new_peak_wallet from peer 1faa9176e014e0db3c0faee464dfe1f3230ccbcdd9a251720c8081ac60b07595 127.0.0.1
2021-07-08T22:13:22.435 wallet wallet_server              : DEBUG    <- new_peak_wallet from peer 1faa9176e014e0db3c0faee464dfe1f3230ccbcdd9a251720c8081ac60b07595 127.0.0.1
2021-07-08T22:13:23.332 wallet wallet_server              : DEBUG    <- new_peak_wallet from peer 1faa9176e014e0db3c0faee464dfe1f3230ccbcdd9a251720c8081ac60b07595 127.0.0.1
2021-07-08T22:13:35.787 wallet chia.wallet.wallet_node    : INFO     self._close
2021-07-08T22:13:35.787 wallet chia.wallet.wallet_node    : INFO     self._await_closed
2021-07-08T22:13:35.787 wallet wallet_server              : DEBUG    Inbound_handler task cancelled
2021-07-08T22:13:35.788 wallet wallet_server              : INFO     Connection closed: 127.0.0.1, node id: 1faa9176e014e0db3c0faee464dfe1f3230ccbcdd9a251720c8081ac60b07595
2021-07-08T22:13:37.663 wallet chia.wallet.wallet_state_manager: DEBUG    Starting in db path: /msas/crworld/chia-root/mainnet/wallet/db/blockchain_wallet_v1_mainnet_3868480568.sqlite
2021-07-08T22:13:37.674 wallet asyncio                    : ERROR    Task exception was never retrieved
2021-07-08T22:13:37.690 wallet chia.wallet.wallet_blockchain: INFO     Started 1 processes for block validation
2021-07-08T22:13:39.620 wallet wallet                     : INFO     Reconnecting to peer {'host': '127.0.0.1', 'port': 8444}
2021-07-08T22:13:39.621 wallet wallet_server              : DEBUG    Connecting: wss://127.0.0.1:8444/ws, Peer info: {'host': '127.0.0.1', 'port': 8444}
2021-07-08T22:13:39.630 wallet wallet_server              : DEBUG    -> handshake to peer 127.0.0.1 1faa9176e014e0db3c0faee464dfe1f3230ccbcdd9a251720c8081ac60b07595
2021-07-08T22:13:39.635 wallet wallet_server              : INFO     Connected with full_node {'host': '127.0.0.1', 'port': 8444}
2021-07-08T22:13:39.635 wallet wallet_server              : DEBUG    <- new_peak_wallet from peer 1faa9176e014e0db3c0faee464dfe1f3230ccbcdd9a251720c8081ac60b07595 127.0.0.1
2021-07-08T22:13:41.021 wallet chia.rpc.wallet_rpc_api    : ERROR    error No backup on backup service
2021-07-08T22:13:43.561 wallet wallet_server              : DEBUG    <- new_peak_wallet from peer 1faa9176e014e0db3c0faee464dfe1f3230ccbcdd9a251720c8081ac60b07595 127.0.0.1
2021-07-08T22:13:44.248 wallet wallet_server              : DEBUG    <- new_peak_wallet from peer 1faa9176e014e0db3c0faee464dfe1f3230ccbcdd9a251720c8081ac60b07595 127.0.0.1
2021-07-08T22:13:50.402 wallet wallet_server              : DEBUG    <- new_peak_wallet from peer 1faa9176e014e0db3c0faee464dfe1f3230ccbcdd9a251720c8081ac60b07595 127.0.0.1
2021-07-08T22:14:00.741 wallet chia.wallet.wallet_node    : INFO     self._close
2021-07-08T22:14:00.742 wallet chia.wallet.wallet_node    : INFO     self._await_closed
2021-07-08T22:14:00.742 wallet wallet_server              : DEBUG    Inbound_handler task cancelled
2021-07-08T22:14:00.743 wallet wallet_server              : INFO     Connection closed: 127.0.0.1, node id: 1faa9176e014e0db3c0faee464dfe1f3230ccbcdd9a251720c8081ac60b07595
2021-07-08T22:14:01.877 wallet chia.wallet.wallet_state_manager: DEBUG    Starting in db path: /msas/crworld/chia-root/mainnet/wallet/db/blockchain_wallet_v1_mainnet_3868480568.sqlite
2021-07-08T22:14:01.886 wallet chia.wallet.wallet_blockchain: INFO     Started 1 processes for block validation
2021-07-08T22:14:01.909 wallet chia.wallet.wallet_node    : INFO     Loop start in sync job
2021-07-08T22:14:03.654 wallet wallet                     : INFO     Reconnecting to peer {'host': '127.0.0.1', 'port': 8444}
2021-07-08T22:14:03.655 wallet wallet_server              : DEBUG    Connecting: wss://127.0.0.1:8444/ws, Peer info: {'host': '127.0.0.1', 'port': 8444}
2021-07-08T22:14:03.664 wallet wallet_server              : DEBUG    -> handshake to peer 127.0.0.1 1faa9176e014e0db3c0faee464dfe1f3230ccbcdd9a251720c8081ac60b07595
2021-07-08T22:14:03.667 wallet wallet_server              : INFO     Connected with full_node {'host': '127.0.0.1', 'port': 8444}
2021-07-08T22:14:03.668 wallet wallet_server              : DEBUG    <- new_peak_wallet from peer 1faa9176e014e0db3c0faee464dfe1f3230ccbcdd9a251720c8081ac60b07595 127.0.0.1
2021-07-08T22:14:03.720 wallet wallet_server              : DEBUG    -> request_block_header to peer 127.0.0.1 1faa9176e014e0db3c0faee464dfe1f3230ccbcdd9a251720c8081ac60b07595
2021-07-08T22:14:03.722 wallet wallet_server              : DEBUG    <- respond_block_header from: 127.0.0.1:8444
2021-07-08T22:14:03.722 wallet wallet_server              : DEBUG    Time for request request_block_header: {'host': '127.0.0.1', 'port': 8444} = 0.0028579235076904297, None? False
2021-07-08T22:14:03.726 wallet wallet_server              : DEBUG    -> request_proof_of_weight to peer 127.0.0.1 1faa9176e014e0db3c0faee464dfe1f3230ccbcdd9a251720c8081ac60b07595
2021-07-08T22:14:05.099 wallet wallet_server              : DEBUG    <- respond_proof_of_weight from: 127.0.0.1:8444
2021-07-08T22:14:05.100 wallet wallet_server              : DEBUG    Time for request request_proof_of_weight: {'host': '127.0.0.1', 'port': 8444} = 1.3744242191314697, None? False
2021-07-08T22:14:09.113 wallet wallet_server              : DEBUG    trusted node 1faa9176e014e0db3c0faee464dfe1f3230ccbcdd9a251720c8081ac60b07595 127.0.0.1
2021-07-08T22:14:09.113 wallet chia.full_node.weight_proof: DEBUG    get fork point skip validations
2021-07-08T22:14:09.114 wallet chia.full_node.weight_proof: DEBUG    sub epoch 0 start weight is 7
2021-07-08T22:14:09.114 wallet chia.full_node.weight_proof: DEBUG    sub epoch 1 start weight is 2709
2021-07-08T22:14:09.114 wallet chia.full_node.weight_proof: DEBUG    sub epoch 2 start weight is 5439
.
.
2021-07-08T22:14:09.398 wallet chia.full_node.weight_proof: DEBUG    sub epoch 1415 start weight is 386459392
2021-07-08T22:14:09.398 wallet chia.full_node.weight_proof: INFO     validating 1417 sub epochs
2021-07-08T22:14:09.399 wallet chia.full_node.weight_proof: DEBUG    last ses sub height 544129
2021-07-08T22:14:09.399 wallet chia.wallet.wallet_node    : INFO     Validated, fork point is 0
2021-07-08T22:14:09.400 wallet chia.wallet.wallet_node    : INFO     self.sync_event.set()
2021-07-08T22:14:09.424 wallet wallet_server              : DEBUG    Time taken to process new_peak_wallet from 1faa9176e014e0db3c0faee464dfe1f3230ccbcdd9a251720c8081ac60b07595 is 5.756070137023926 seconds
2021-07-08T22:14:09.425 wallet chia.wallet.wallet_node    : INFO     Have collected 1 potential peaks
2021-07-08T22:14:09.425 wallet chia.wallet.wallet_node    : INFO     Requesting blocks 0-32
2021-07-08T22:14:09.426 wallet wallet_server              : DEBUG    -> request_header_blocks to peer 127.0.0.1 1faa9176e014e0db3c0faee464dfe1f3230ccbcdd9a251720c8081ac60b07595
2021-07-08T22:14:09.429 wallet wallet_server              : DEBUG    <- new_peak_wallet from peer 1faa9176e014e0db3c0faee464dfe1f3230ccbcdd9a251720c8081ac60b07595 127.0.0.1
2021-07-08T22:14:09.429 wallet wallet_server              : DEBUG    Time taken to process new_peak_wallet from 1faa9176e014e0db3c0faee464dfe1f3230ccbcdd9a251720c8081ac60b07595 is 0.0004477500915527344 seconds
2021-07-08T22:14:09.425 wallet chia.wallet.wallet_node    : INFO     Requesting blocks 0-32
2021-07-08T22:14:09.426 wallet wallet_server              : DEBUG    -> request_header_blocks to peer 127.0.0.1 1faa9176e014e0db3c0faee464dfe1f3230ccbcdd9a251720c8081ac60b07595
2021-07-08T22:14:09.429 wallet wallet_server              : DEBUG    <- new_peak_wallet from peer 1faa9176e014e0db3c0faee464dfe1f3230ccbcdd9a251720c8081ac60b07595 127.0.0.1
2021-07-08T22:14:09.429 wallet wallet_server              : DEBUG    Time taken to process new_peak_wallet from 1faa9176e014e0db3c0faee464dfe1f3230ccbcdd9a251720c8081ac60b07595 is 0.0004477500915527344 seconds
2021-07-08T22:15:01.911 wallet chia.wallet.wallet_node    : INFO     Will not attempt to connect to other nodes, already connected to {'host': 'localhost', 'port': 8444}
2021-07-08T22:15:09.430 wallet wallet_server              : DEBUG    Time for request request_header_blocks: {'host': '127.0.0.1', 'port': 8444} = 60.004639625549316, None? True
2021-07-08T22:15:09.430 wallet wallet_server              : DEBUG    Inbound_handler task cancelled
2021-07-08T22:15:09.432 wallet wallet_server              : INFO     Connection closed: 127.0.0.1, node id: 1faa9176e014e0db3c0faee464dfe1f3230ccbcdd9a251720c8081ac60b07595
2021-07-08T22:15:09.441 wallet chia.wallet.wallet_node    : ERROR    Error while trying to fetch from peer:Peer returned no response Traceback (most recent call last):
  File "/home/msaschia/chia-blockchain/chia/wallet/wallet_node.py", line 528, in batch_sync_to_peak
    added, advanced_peak = await self.fetch_blocks_and_validate(
  File "/home/msaschia/chia-blockchain/chia/wallet/wallet_node.py", line 680, in fetch_blocks_and_validate
    raise ValueError("Peer returned no response")
ValueError: Peer returned no response

2021-07-08T22:15:09.441 wallet chia.wallet.wallet_node    : ERROR    Loop exception in sync Was not able to add blocks 0-32. Traceback (most recent call last):
  File "/home/msaschia/chia-blockchain/chia/wallet/wallet_node.py", line 581, in sync_job
    await self._sync()
  File "/home/msaschia/chia-blockchain/chia/wallet/wallet_node.py", line 661, in _sync
    await self.batch_sync_to_peak(fork_height, peak)
  File "/home/msaschia/chia-blockchain/chia/wallet/wallet_node.py", line 538, in batch_sync_to_peak
    raise RuntimeError(f"Was not able to add blocks {start_height}-{end_height}")
RuntimeError: Was not able to add blocks 0-32
2021-07-08T22:15:09.441 wallet chia.wallet.wallet_node    : INFO     Loop end in sync job
2021-07-08T22:15:09.442 wallet chia.wallet.wallet_node    : INFO     Loop start in sync job
2021-07-08T22:15:09.442 wallet wallet_server              : DEBUG    Time for request request_block_header: {'host': '127.0.0.1', 'port': 8444} = 0.00010228157043457031, None? True
2021-07-08T22:15:09.442 wallet chia.wallet.wallet_node    : WARNING  bad peak response from peer None
2021-07-08T22:15:09.480 wallet wallet                     : INFO     Reconnecting to peer {'host': '127.0.0.1', 'port': 8444}
2021-07-08T22:15:09.481 wallet wallet_server              : DEBUG    Connecting: wss://127.0.0.1:8444/ws, Peer info: {'host': '127.0.0.1', 'port': 8444}
2021-07-08T22:15:09.490 wallet wallet_server              : DEBUG    -> handshake to peer 127.0.0.1 1faa9176e014e0db3c0faee464dfe1f3230ccbcdd9a251720c8081ac60b07595
2021-07-08T22:15:09.494 wallet wallet_server              : INFO     Connected with full_node {'host': '127.0.0.1', 'port': 8444}
2021-07-08T22:15:09.494 wallet wallet_server              : DEBUG    <- new_peak_wallet from peer 1faa9176e014e0db3c0faee464dfe1f3230ccbcdd9a251720c8081ac60b07595 127.0.0.1
2021-07-08T22:15:09.495 wallet wallet_server              : DEBUG    -> request_block_header to peer 127.0.0.1 1faa9176e014e0db3c0faee464dfe1f3230ccbcdd9a251720c8081ac60b07595
2021-07-08T22:15:09.497 wallet wallet_server              : DEBUG    <- respond_block_header from: 127.0.0.1:8444
2021-07-08T22:15:09.497 wallet wallet_server              : DEBUG    Time for request request_block_header: {'host': '127.0.0.1', 'port': 8444} = 0.002649068832397461, None? False
2021-07-08T22:15:09.501 wallet wallet_server              : DEBUG    -> request_proof_of_weight to peer 127.0.0.1 1faa9176e014e0db3c0faee464dfe1f3230ccbcdd9a251720c8081ac60b07595
```

**Comment by rmica** [comment]
Same problem here. Ubuntu 20.04.2 LTS, chia version 1.1.7 and 1.2.1, same behaviour.
I noticed that wallet sync process disrupts the normal signage point flow, impacting on the farming work.
I start node, wait for connections and sp flow to stabilize and for the blockchian to sync. Then I run wallet-only and 'chia wallet show' and opt for 'S' to start resync (after cleaning wallet/db directory). At this point the node starts to emit rows of "don't have rc hash ... cached signage point" messages, and wallet's "RuntimeError: Was not able to add blocks 0-32" errors. By time to time a wave of blocks arrive and then starts back caching signage points. Harvesters' challenge 5m rate goes up and down.
If I don't run wallet synchronization the farming is regular and smooth.

**Comment by rmica** [comment]
Ok, in my case the sync fails only in the case of total resync from zero, after a wallet/db cleanup or new generated keys. When  I begin from an existing wallet .sqlite, the sync works well.
