### ISSUE TITLE
66 is not a valid ProtocolMessageTypes

### ISSUE THREAD

**Issue by HsiangSun** [Chia-Network/chia-blockchain#7211]
**To Reproduce**

1. update ubuntu 20.04 chia harvester(1.2.0)
2. connected to windows 10 farmer(1.2.0)
3. See error

**log snap**

```python
2021-07-08T18:26:04.628 harvester harvester_server        : INFO     Connection closed: 170.7.7.99, node id: 9b7f0854240c984a87ca9f72ff426382fbf2207f09d94f87840f953c0b267e5f
2021-07-08T18:26:04.629 harvester harvester_server        : WARNING  Banning 170.7.7.99 for 10 seconds
2021-07-08T18:26:04.629 harvester chia.harvester.harvester: INFO     peer disconnected {'host': '170.7.7.99', 'port': 8447}
2021-07-08T18:26:05.113 harvester harvester               : INFO     Reconnecting to peer {'host': '170.7.7.99', 'port': 8447}
2021-07-08T18:26:05.114 harvester harvester_server        : WARNING  Peer 170.7.7.99 is still banned, not connecting to it
2021-07-08T18:26:08.116 harvester harvester               : INFO     Reconnecting to peer {'host': '170.7.7.99', 'port': 8447}
2021-07-08T18:26:08.117 harvester harvester_server        : WARNING  Peer 170.7.7.99 is still banned, not connecting to it
2021-07-08T18:26:11.120 harvester harvester               : INFO     Reconnecting to peer {'host': '170.7.7.99', 'port': 8447}
2021-07-08T18:26:11.121 harvester harvester_server        : WARNING  Peer 170.7.7.99 is still banned, not connecting to it
2021-07-08T18:26:14.124 harvester harvester               : INFO     Reconnecting to peer {'host': '170.7.7.99', 'port': 8447}
2021-07-08T18:26:14.124 harvester harvester_server        : WARNING  Peer 170.7.7.99 is still banned, not connecting to it
2021-07-08T18:26:17.128 harvester harvester               : INFO     Reconnecting to peer {'host': '170.7.7.99', 'port': 8447}
2021-07-08T18:26:17.145 harvester harvester_server        : INFO     Connected with farmer {'host': '170.7.7.99', 'port': 8447}
2021-07-08T18:26:17.185 harvester chia.plotting.plot_tools: INFO     Searching directories ['/media/dbs01/data10', '/media/dbs01/data3', '/media/dbs01/data5', '/media/dbs01/data6', '/media/dbs01/data7', '/media/dbs01/data8', '/media/dbs01/data9', '/media/dbs01/mbF']
2021-07-08T18:26:17.248 harvester chia.plotting.plot_tools: INFO     Loaded a total of 157 plots of size 15.540083131701067 TiB, in 0.09930849075317383 seconds
2021-07-08T18:26:21.180 harvester chia.server.rate_limits : WARNING  Invalid message: 66, 66 is not a valid ProtocolMessageTypes
2021-07-08T18:26:21.182 harvester harvester_server        : ERROR    Exception: 66 is not a valid ProtocolMessageTypes <class 'ValueError'>, closing connection {'host': '170.7.7.99', 'port': 8447}. Traceback (most recent call last):
  File "chia/server/server.py", line 493, in api_call
  File "/opt/hostedtoolcache/Python/3.8.10/x64/lib/python3.8/enum.py", line 339, in __call__
  File "/opt/hostedtoolcache/Python/3.8.10/x64/lib/python3.8/enum.py", line 663, in __new__
ValueError: 66 is not a valid ProtocolMessageTypes
```

**Comment by HsiangSun** [comment]
> # Not forget update certificate. chia init -c /path/of/ca
