### ISSUE TITLE
[BUG] The full node stopping on Windows

### ISSUE THREAD

**Issue by ITPrism** [Chia-Network/chia-blockchain#7226]
**Describe the bug**
The full node stopping regularly with the following error. The wallets cannot be synced.

chia_full_node: Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x000002ED252DEDC0>
Traceback (most recent call last):
  File "asyncio\proactor_events.py", line 116, in __del__
  File "asyncio\proactor_events.py", line 108, in close
  File "asyncio\base_events.py", line 746, in call_soon
  File "asyncio\base_events.py", line 510, in _check_closed
RuntimeError: Event loop is closed
stopped

**To Reproduce**
run the following command several times 

./chia wallet show -f _YOUR_FINGERPRINT_

- OS: Windows 10
- CPU: AMD Ryzen 5 PRO 4650G

**Comment by DaveKoz** [comment]
Same results on windows 10. Mac version works fine.

**Comment by brasrox** [comment]
same, my wallet stop sync ( windows 10 )
