### ISSUE TITLE
Running chia plotnft get_login_link -l NAME gives error

### ISSUE THREAD

**Issue by doma2345** [Chia-Network/chia-blockchain#7243]
When I run chia plotnft get_login_link -l WHATEVERNAME I get the following error

Traceback (most recent call last):
  File "/chia-blockchain/venv/bin/chia", line 33, in <module>
    sys.exit(load_entry_point('chia-blockchain', 'console_scripts', 'chia')())
  File "/chia-blockchain/chia/cmds/chia.py", line 79, in main
    cli()  # pylint: disable=no-value-for-parameter
  File "/chia-blockchain/venv/lib/python3.9/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/chia-blockchain/venv/lib/python3.9/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/chia-blockchain/venv/lib/python3.9/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/chia-blockchain/venv/lib/python3.9/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/chia-blockchain/venv/lib/python3.9/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/chia-blockchain/venv/lib/python3.9/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/chia-blockchain/chia/cmds/plotnft.py", line 35, in get_login_link_cmd
    asyncio.run(get_login_link(launcher_id))
  File "/usr/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/chia-blockchain/chia/cmds/plotnft_funcs.py", line 217, in get_login_link
    launcher_id: bytes32 = hexstr_to_bytes(launcher_id_str)
  File "/chia-blockchain/chia/util/byte_types.py", line 11, in hexstr_to_bytes
    return bytes.fromhex(input_str)
ValueError: non-hexadecimal number found in fromhex() arg at position 2

**Comment by richardhkirkando** [comment]
Also having this issue, running CentOS 7.9 & python 3.7.7 and the latest branch pulled yesterday (1.2.0).  I'm happy to provide further details if needed.

**Comment by emlowe** [comment]
The get_login_link takes the launcher_id which is shown in `plotnft show` Please confirm you are using the launcher_id. I'm not sure what "WHATEVERNAME" is referring to in this case.

**Comment by doma2345** [comment]
@emlowe the cmd i am running is “ get_login_link -l NAME whatevername” to change my launcher id to something more memorable. Is this the correct usage?

**Comment by emlowe** [comment]
No. Example

```
chia plotnft show
Sync status: Synced
Wallet id 2: 
Current state: SELF_POOLING
Current state from block height: 332764
Launcher ID: f0bf5c59872165354900ff98aaf95b0b2c8a423200efe3493de370f0a1461942
```

``` chia plotnft get_login_link -l f0bf5c59872165354900ff98aaf95b0b2c8a423200efe3493de370f0a1461942```

It will return to you a URL you can use to login into your pool if your pool supports it.

**Comment by doma2345** [comment]
> ` chia plotnft get_login_link -l f0bf5c59872165354900ff98aaf95b0b2c8a423200efe3493de370f0a1461942`
> 
> It will return to you a URL you can use to login into your pool if your pool supports it.

the cmd you are giving the example of is different from the cmd i am running and for a different usage, i dont want the login link i want to change the launcher ID. This was dosumented on space pools setup guide but i cant find it now
