### ISSUE TITLE
[BUG] wallet_server RuntimeError got Future <Future pending> attached to a different loop

### ISSUE THREAD

**Issue by greg-fischer** [Chia-Network/chia-blockchain#7248]
**Describe the bug**
```
2021-07-08T12:05:01.469 wallet wallet_server              : ERROR    Exception: Task <Task pending name='Task-12377' coro=<ChiaServer.incoming_api_task.<locals>.api_call() running at chia/server/server.py:533>> got Future <Future pending> attached to a different loop, {'host': '127.0.0.1', 'port': 8444}. Traceback (most recent call last):
  File "chia/server/server.py", line 523, in wrapped_coroutine
  File "chia/wallet/wallet_node_api.py", line 49, in new_peak_wallet
  File "chia/wallet/wallet_node.py", line 446, in new_peak_wallet
  File "asyncio/locks.py", line 97, in __aenter__
  File "asyncio/locks.py", line 203, in acquire
RuntimeError: Task <Task pending name='Task-12377' coro=<ChiaServer.incoming_api_task.<locals>.api_call() running at chia/server/server.py:533>> got Future <Future pending> attached to a different loop

2021-07-08T12:05:01.470 wallet wallet_server              : ERROR    Exception: Task <Task pending name='Task-12377' coro=<ChiaServer.incoming_api_task.<locals>.api_call() running at chia/server/server.py:533>> got Future <Future pending> attached to a different loop <class 'RuntimeError'>, closing connection {'host': '127.0.0.1', 'port': 8444}. Traceback (most recent call last):
  File "chia/server/server.py", line 533, in api_call
  File "asyncio/tasks.py", line 455, in wait_for
  File "chia/server/server.py", line 530, in wrapped_coroutine
  File "chia/server/server.py", line 523, in wrapped_coroutine
  File "chia/wallet/wallet_node_api.py", line 49, in new_peak_wallet
  File "chia/wallet/wallet_node.py", line 446, in new_peak_wallet
  File "asyncio/locks.py", line 97, in __aenter__
  File "asyncio/locks.py", line 203, in acquire
RuntimeError: Task <Task pending name='Task-12377' coro=<ChiaServer.incoming_api_task.<locals>.api_call() running at chia/server/server.py:533>> got Future <Future pending> attached to a different loop
```

**To Reproduce**

Shows in the debug.log while connected to pool.

**Expected behavior**
Not show RuntimeError ?

**Desktop**
Debian 10 
Chia 1.2.0

**Additional context**
Just upgraded and joined a pool.  Newly created plots appear to be working.  However none show up on the pool's website yet, after a couple hours. Maybe nothing to do with this error, I'm sure.

**Comment by dgfmdrv** [comment]
I'm unable to sync a wallet.

I have one full node sync and another node where I run wallet-only. 
DB for wallet don't exists (~/.chia/mainnet/wallet/db/ empty).

Then
```
$ chia start wallet-only 
$ chia wallet show
No online backup file found,
 Press S to skip restore from backup
 Press F to use your own backup file: S
```
In log:
```
2021-07-08T22:05:27.411 wallet wallet_server              : INFO     Connected with full_node {'host': '10.179.14.5', 'port': 8444}
2021-07-08T22:05:27.412 wallet wallet_server              : DEBUG    <- new_peak_wallet from peer 1faa9176e014e0db3c0faee464dfe1f3230ccbcdd9a251720c8081ac60b07595 10.179.14.5
2021-07-08T22:05:28.734 wallet chia.rpc.wallet_rpc_api    : ERROR    error 0, message='Attempt to decode JSON with unexpected mimetype: text/plain; charset=utf-8', url=URL('https://backup.chia.net/download_backup')
2021-07-08T22:05:30.860 wallet chia.wallet.wallet_node    : INFO     self._close
2021-07-08T22:05:30.860 wallet chia.wallet.wallet_node    : INFO     self._await_closed
2021-07-08T22:05:30.860 wallet wallet_server              : DEBUG    Inbound_handler task cancelled
2021-07-08T22:05:30.940 wallet wallet_server              : INFO     Connection closed: 10.179.14.5, node id: 1faa9176e014e0db3c0faee464dfe1f3230ccbcdd9a251720c8081ac60b07595
2021-07-08T22:05:31.209 wallet chia.wallet.wallet_state_manager: DEBUG    Starting in db path: /home/test/.chia/mainnet/wallet/db/blockchain_wallet_v1_mainnet_3868480568.sqlite
2021-07-08T22:05:31.216 wallet chia.wallet.wallet_blockchain: INFO     Started 22 processes for block validation
2021-07-08T22:05:31.219 wallet chia.wallet.wallet_node    : INFO     Loop start in sync job
2021-07-08T22:05:33.415 wallet wallet                     : INFO     Reconnecting to peer {'host': '10.179.14.5', 'port': 8444}
2021-07-08T22:05:33.416 wallet wallet_server              : DEBUG    Connecting: wss://10.179.14.5:8444/ws, Peer info: {'host': '10.179.14.5', 'port': 8444}
2021-07-08T22:05:33.631 wallet wallet_server              : DEBUG    -> handshake to peer 10.179.14.5 1faa9176e014e0db3c0faee464dfe1f3230ccbcdd9a251720c8081ac60b07595
2021-07-08T22:05:33.706 wallet wallet_server              : INFO     Connected with full_node {'host': '10.179.14.5', 'port': 8444}
2021-07-08T22:05:33.706 wallet wallet_server              : DEBUG    <- new_peak_wallet from peer 1faa9176e014e0db3c0faee464dfe1f3230ccbcdd9a251720c8081ac60b07595 10.179.14.5
2021-07-08T22:05:33.722 wallet wallet_server              : DEBUG    -> request_block_header to peer 10.179.14.5 1faa9176e014e0db3c0faee464dfe1f3230ccbcdd9a251720c8081ac60b07595
2021-07-08T22:05:33.789 wallet wallet_server              : DEBUG    <- respond_block_header from: 10.179.14.5:8444
2021-07-08T22:05:33.789 wallet wallet_server              : DEBUG    Time for request request_block_header: {'host': '10.179.14.5', 'port': 8444} = 0.06727838516235352, None? False
2021-07-08T22:05:33.791 wallet wallet_server              : DEBUG    -> request_proof_of_weight to peer 10.179.14.5 1faa9176e014e0db3c0faee464dfe1f3230ccbcdd9a251720c8081ac60b07595
2021-07-08T22:05:33.818 wallet wallet_server              : DEBUG    <- new_peak_wallet from peer 1faa9176e014e0db3c0faee464dfe1f3230ccbcdd9a251720c8081ac60b07595 10.179.14.5
2021-07-08T22:05:33.819 wallet wallet_server              : ERROR    Exception: Task <Task pending name='Task-61' coro=<ChiaServer.incoming_api_task.<locals>.api_call() running at /home/test/chia-blockchain/chia/server/server.py:533>> got Future <Future pending> attached to a different loop, {'host': '10.179.14.5', 'port': 8444}. Traceback (most recent call last):
  File "/home/test/chia-blockchain/chia/server/server.py", line 523, in wrapped_coroutine
    result = await coroutine
  File "/home/test/chia-blockchain/chia/wallet/wallet_node_api.py", line 49, in new_peak_wallet
    await self.wallet_node.new_peak_wallet(peak, peer)
  File "/home/test/chia-blockchain/chia/wallet/wallet_node.py", line 446, in new_peak_wallet
    async with self.new_peak_lock:
  File "/usr/lib64/python3.8/asyncio/locks.py", line 97, in __aenter__
    await self.acquire()
  File "/usr/lib64/python3.8/asyncio/locks.py", line 203, in acquire
    await fut
RuntimeError: Task <Task pending name='Task-61' coro=<ChiaServer.incoming_api_task.<locals>.api_call() running at /home/test/chia-blockchain/chia/server/server.py:533>> got Future <Future pending> attached to a different loop

2021-07-08T22:05:33.819 wallet wallet_server              : ERROR    Exception: Task <Task pending name='Task-61' coro=<ChiaServer.incoming_api_task.<locals>.api_call() running at /home/test/chia-blockchain/chia/server/server.py:533>> got Future <Future pending> attached to a different loop <class 'RuntimeError'>, closing connection {'host': '10.179.14.5', 'port': 8444}. Traceback (most recent call last):
  File "/home/test/chia-blockchain/chia/server/server.py", line 533, in api_call
    response: Optional[Message] = await asyncio.wait_for(wrapped_coroutine(), timeout=timeout)
  File "/usr/lib64/python3.8/asyncio/tasks.py", line 455, in wait_for
    return await fut
  File "/home/test/chia-blockchain/chia/server/server.py", line 530, in wrapped_coroutine
    raise e
  File "/home/test/chia-blockchain/chia/server/server.py", line 523, in wrapped_coroutine
    result = await coroutine
  File "/home/test/chia-blockchain/chia/wallet/wallet_node_api.py", line 49, in new_peak_wallet
    await self.wallet_node.new_peak_wallet(peak, peer)
  File "/home/test/chia-blockchain/chia/wallet/wallet_node.py", line 446, in new_peak_wallet
    async with self.new_peak_lock:
  File "/usr/lib64/python3.8/asyncio/locks.py", line 97, in __aenter__
    await self.acquire()
  File "/usr/lib64/python3.8/asyncio/locks.py", line 203, in acquire
    await fut
RuntimeError: Task <Task pending name='Task-61' coro=<ChiaServer.incoming_api_task.<locals>.api_call() running at /home/test/chia-blockchain/chia/server/server.py:533>> got Future <Future pending> attached to a different loop

2021-07-08T22:05:33.819 wallet wallet_server              : DEBUG    Inbound_handler task cancelled
2021-07-08T22:05:33.884 wallet wallet_server              : INFO     Connection closed: 10.179.14.5, node id: 1faa9176e014e0db3c0faee464dfe1f3230ccbcdd9a251720c8081ac60b07595
2021-07-08T22:05:33.884 wallet wallet_server              : WARNING  Banning 10.179.14.5 for 10 seconds
```
This error is repeated on log and height shows 0 after a few hours:
$ chia wallet show
Wallet height: 0
Sync status: Not synced

**Comment by greg-fischer** [comment]
My wallet is in sync, even with this error:

```
greg@grenchler-> chia wallet show
Wallet height: 545188
Sync status: Synced
Balances, fingerprint: ###
Wallet ID 1 type STANDARD_WALLET Chia Wallet
   -Total Balance: 5.69899e-07 xch (569899 mojo)
   -Pending Total Balance: 5.69899e-07 xch (569899 mojo)
   -Spendable: 5.69899e-07 xch (569899 mojo)
Wallet ID 2 type POOLING_WALLET Pool wallet
   -Total Balance: 0.0 xch (0 mojo)
   -Pending Total Balance: 0.0 xch (0 mojo)
   -Spendable: 0.0 xch (0 mojo)
```

Also, I don't really get that Total Balance of 5.69899e-07 xch (569899 mojo). That makes no sense. I only have that amount of mojo, I believe, but I don't get the 5.xxx xch part?

**Comment by dgfmdrv** [comment]
5.69899e-07xch = 569899 mojo

![image](https://user-images.githubusercontent.com/1451834/125081409-4292de80-e0c6-11eb-8485-fa35b2ffe104.png)
