### ISSUE TITLE
chia plots create -k 20 -> RuntimeError

### ISSUE THREAD

**Issue by altendky** [Chia-Network/chia-blockchain#727]
**Describe the bug**
```console
$ venv/bin/chia plots create -k 20 -n 1 -b 4096 -r 8 -t /chia/temporary -d /chia/final/
22:26:46.652  src.plotting.create_plots        : WARNING  CREATING PLOTS WITH SIZE k=20, which is less than the minimum required for mainnet
22:26:46.652  src.plotting.create_plots        : INFO     Creating 1 plots of size 20, pool public key:  a55d8fdada643a43d86a889c2c746ce848c0e2d00f7c012fc4c6e77d1e2f9f54a99dd38af59f8284f2178b810ecc7a95 farmer public key: b0a374845f4f4d6eab62fc4c5e17965d82ad7eee105818e5bd0cfcb46275a16acc4cd30955779bec841a716473416b21
22:26:46.658  src.plotting.create_plots        : INFO     Adding directory /chia/final to harvester for farming
22:26:46.682  src.plotting.create_plots        : INFO     Starting plot 1/1
Caught plotting error: Stripe size too large
Traceback (most recent call last):
  File "venv/bin/chia", line 33, in <module>
    sys.exit(load_entry_point('chia-blockchain', 'console_scripts', 'chia')())
  File "/home/altendky/repos/chia-blockchain/src/cmds/chia.py", line 60, in main
    return chia(args, parser)
  File "/home/altendky/repos/chia-blockchain/src/cmds/chia.py", line 54, in chia
    return args.function(args, parser)
  File "/home/altendky/repos/chia-blockchain/src/cmds/plots.py", line 158, in handler
    create_plots(args, root_path)
  File "/home/altendky/repos/chia-blockchain/src/plotting/create_plots.py", line 153, in create_plots
    args.nobitfield,
RuntimeError: std::exception
```

**To Reproduce**
```console
$ git rev-parse HEAD
b82f3ba8a2953de12bddf5c5d6a33e443b51bc8b
```

```console
$ venv/bin/python --version --version
Python 3.7.9 (default, Oct  8 2020, 21:25:44) 
[GCC 9.3.0]
```

```console
$ venv/bin/chia plots create -k 20 -n 1 -b 4096 -r 8 -t /chia/temporary -d /chia/final/
<see above>
```

```console
$ venv/bin/pip freeze --all
aiohttp==3.7.3
aiosqlite @ git+https://github.com/mariano54/aiosqlite.git@28cb5754deec562ac931da8fca799fb82df97a12
aiter==0.13.20191203
argon2-cffi==20.1.0
async-timeout==3.0.1
attrs==20.3.0
bitstring==3.1.7
blspy==0.3.1
cbor2==5.2.0
cffi==1.14.4
chardet==3.0.4
-e git+git@github.com:Chia-Network/chia-blockchain@b82f3ba8a2953de12bddf5c5d6a33e443b51bc8b#egg=chia_blockchain
chiabip158==0.17
chiapos==0.12.41
chiavdf==0.13.2
clvm==0.7
clvm-tools==0.2.0
colorlog==4.7.2
concurrent-log-handler==0.9.19
cryptography==3.3.1
idna==3.1
importlib-metadata==3.4.0
jeepney==0.6.0
keyring==21.5.0
keyrings.cryptfile==1.3.4
miniupnpc==2.1
multidict==5.1.0
pip==20.3.3
portalocker==2.0.0
pycparser==2.20
pycryptodome==3.9.9
PyYAML==5.3.1
SecretStorage==3.3.0
setproctitle==1.1.10
setuptools==47.1.0
six==1.15.0
sortedcontainers==2.3.0
typing-extensions==3.7.4.3
websockets==8.1
wheel==0.36.2
yarl==1.6.3
zipp==3.4.0
```

**Expected behavior**
It seems to detect a bad situation (stripe size too large) so I would expect it to not `RuntimeError` following that.

**Desktop (please complete the following information):**

- OS: Linux
- OS Version/Flavor: Ubuntu 20.04.1 LTS
- CPU: Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz

**Comment by hoffmang9** [comment]
There are known issues with k's below 25. The way python imports the C++ plotting library means that it can only report the C failure. I'll add warning or disable under 25 in the python side.

**Comment by hoffmang9** [comment]
https://github.com/Chia-Network/chia-blockchain/commit/79561acbb40a00eeee568d32af1ae4f4f6d791d5

**Comment by hoffmang9** [comment]
Excellent bug report though - thank you!

**Comment by altendky** [comment]
Thanks for the quick resolution.  `:]`

**Comment by mariano54** [comment]
If you want to make super small plots though, you can decrease the stripe size
