### ISSUE TITLE
v1.2.0 ERROR    Exception: Task <Task pending coro=<ChiaServer.incoming_api_task.<locals>.api_call()

### ISSUE THREAD

**Issue by struxoje** [Chia-Network/chia-blockchain#7281]
**Describe the bug**
I'm seeing following exceptions periodically in debug.log

2021-07-09T12:15:14.463 wallet wallet_server              : ERROR    Exception: Task <Task pending coro=<ChiaServer.incoming_api_task.<locals>.api_call() running at /srv/chia/chia-blockchain/chia/server/server.py:533>> got Future <Future pending> attached to a different loop, {'host': '127.0.0.1', 'port': 8444}. Traceback (most recent call last):
  File "/srv/chia/chia-blockchain/chia/server/server.py", line 523, in wrapped_coroutine
    result = await coroutine
  File "/srv/chia/chia-blockchain/chia/wallet/wallet_node_api.py", line 49, in new_peak_wallet
    await self.wallet_node.new_peak_wallet(peak, peer)
  File "/srv/chia/chia-blockchain/chia/wallet/wallet_node.py", line 446, in new_peak_wallet
    async with self.new_peak_lock:
  File "/usr/lib/python3.7/asyncio/locks.py", line 92, in __aenter__
    await self.acquire()
  File "/usr/lib/python3.7/asyncio/locks.py", line 192, in acquire
    await fut
RuntimeError: Task <Task pending coro=<ChiaServer.incoming_api_task.<locals>.api_call() running at /srv/chia/chia-blockchain/chia/server/server.py:533>> got Future <Future pending> attached to a different loop

2021-07-09T12:15:14.464 wallet wallet_server              : ERROR    Exception: Task <Task pending coro=<ChiaServer.incoming_api_task.<locals>.api_call() running at /srv/chia/chia-blockchain/chia/server/server.py:533>> got Future <Future pending> attached to a different loop <class 'RuntimeError'>, closing connection {'host': '127.0.0.1', 'port': 8444}. Traceback (most recent call last):
  File "/srv/chia/chia-blockchain/chia/server/server.py", line 533, in api_call
    response: Optional[Message] = await asyncio.wait_for(wrapped_coroutine(), timeout=timeout)
  File "/usr/lib/python3.7/asyncio/tasks.py", line 414, in wait_for
    return await fut
  File "/srv/chia/chia-blockchain/chia/server/server.py", line 530, in wrapped_coroutine
    raise e
  File "/srv/chia/chia-blockchain/chia/server/server.py", line 523, in wrapped_coroutine
    result = await coroutine
  File "/srv/chia/chia-blockchain/chia/wallet/wallet_node_api.py", line 49, in new_peak_wallet
    await self.wallet_node.new_peak_wallet(peak, peer)
  File "/srv/chia/chia-blockchain/chia/wallet/wallet_node.py", line 446, in new_peak_wallet
    async with self.new_peak_lock:
  File "/usr/lib/python3.7/asyncio/locks.py", line 92, in __aenter__
    await self.acquire()
  File "/usr/lib/python3.7/asyncio/locks.py", line 192, in acquire
    await fut
RuntimeError: Task <Task pending coro=<ChiaServer.incoming_api_task.<locals>.api_call() running at /srv/chia/chia-blockchain/chia/server/server.py:533>> got Future <Future pending> attached to a different loop

**To Reproduce**

**Expected behavior**
No Exception

**Screenshots**

**Desktop**

- OS: Linux
- OS Version/Flavor: Ubuntu 20.04
- 
- CPU:  Xeon(R) CPU E3-1265L V2

**Additional context**

**Comment by FuzoCZ** [comment]
2021-07-13T15:03:15.014 wallet wallet_server              : ERROR    Exception: Task <Task pending name='Task-15910' coro=<ChiaServer.incoming_api_task.<locals>.api_call() running at chia\server\server.py:533>> got Future <Future pending> attached to a different loop <class 'RuntimeError'>, closing connection {'host': '127.0.0.1', 'port': 8444}. Traceback (most recent call last):
  File "chia\server\server.py", line 533, in api_call
  File "asyncio\tasks.py", line 442, in wait_for
  File "chia\server\server.py", line 530, in wrapped_coroutine
  File "chia\server\server.py", line 523, in wrapped_coroutine
  File "chia\wallet\wallet_node_api.py", line 49, in new_peak_wallet
  File "chia\wallet\wallet_node.py", line 446, in new_peak_wallet
  File "asyncio\locks.py", line 14, in __aenter__
  File "asyncio\locks.py", line 120, in acquire
RuntimeError: Task <Task pending name='Task-15910' coro=<ChiaServer.incoming_api_task.<locals>.api_call() running at chia\server\server.py:533>> got Future <Future pending> attached to a different loop

2021-07-13T15:03:15.015 wallet wallet_server              : WARNING  Trying to ban localhost for 10, but will not ban



Chia 1.2.0
Windows 10
CPU Intel I7-10700 

Older version without bug

**Comment by FuzoCZ** [comment]
So far, so good. No error reporting. THX
