### ISSUE TITLE
New Issues with 1.2 (CODE 1006 as well as Cannot write to Closing Transport)

### ISSUE THREAD

**Issue by miketom72** [Chia-Network/chia-blockchain#7313]
### Discussed in https://github.com/Chia-Network/chia-blockchain/discussions/7293

<div type='discussions-op-text'>

<sup>Originally posted by **miketom72** July  9, 2021</sup>
I had no Errors for weeks till 1.2 Pooling. The two below are the only ones but they are repeating and I cannot find and historical conversations with a resolution
I do not know where the "File "D:\a\chia..."" is coming from. My D drive is a secondary plotting drive on my rig, not my OS. Havent had anything on there  except temp plotting files. 
Would really appreciate some help. I am not great with writing commands, on Windows 10

2021-07-09T10:11:49.164 daemon __main__                   : ERROR    Unexpected exception trying to send to websocket: code = 1006 (connection closed abnormally [internal]), no reason Traceback (most recent call last):
  File "websockets\protocol.py", line 827, in transfer_data
  File "websockets\protocol.py", line 895, in read_message
  File "websockets\protocol.py", line 971, in read_data_frame
  File "websockets\protocol.py", line 1047, in read_frame
  File "websockets\framing.py", line 105, in read
  File "asyncio\streams.py", line 712, in readexactly
  File "asyncio\proactor_events.py", line 395, in _loop_writing
  File "asyncio\windows_events.py", line 532, in send
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\a\chia-blockchain\chia-blockchain\venv\Lib\site-packages\chia\daemon\server.py", line 187, in safe_handle
  File "websockets\protocol.py", line 555, in send
  File "websockets\protocol.py", line 803, in ensure_open
websockets.exceptions.ConnectionClosedError: code = 1006 (connection closed abnormally [internal]), no reason

2021-07-09T10:11:53.824 farmer chia.rpc.rpc_server        : WARNING  Sending data failed. Exception Traceback (most recent call last):
  File "chia\rpc\rpc_server.py", line 67, in _state_changed
  File "aiohttp\client_ws.py", line 150, in send_str
  File "aiohttp\http_websocket.py", line 687, in send
  File "aiohttp\http_websocket.py", line 643, in _send_frame
  File "aiohttp\http_websocket.py", line 660, in _write
ConnectionResetError: Cannot write to closing transport
.
2021-07-09T10:11:54.022 farmer chia.rpc.rpc_server        : WARNING  Sending data failed. Exception Traceback (most recent call last):
  File "chia\rpc\rpc_server.py", line 67, in _state_changed
  File "aiohttp\client_ws.py", line 150, in send_str
  File "aiohttp\http_websocket.py", line 687, in send
  File "aiohttp\http_websocket.py", line 643, in _send_frame
  File "aiohttp\http_websocket.py", line 660, in _write
ConnectionResetError: Cannot write to closing transport</div>

**Comment by whgipt** [comment]
I am having the same issue, didn't see this from earlier versions.

Whenever this issue happens, only restarting GUI can fix it. But after some time, the error returns.
The worse thing is that whenever this issue happens, the sync status would go "wrong", status is "Synced" on GUI, but the "Peak Height"  is actually not sycned with mainnet, local height hardly increase any more,  you can still see "Plots Passed Filter" on GUI, but I think it's doing useless work because the height(challenge) is not correct.

**Comment by Pikislavcheck** [comment]
Same problem here:

2021-07-10T09:43:08.347 full_node chia.rpc.rpc_server     : WARNING  Sending data failed. Exception Traceback (most recent call last):
  File "chia\rpc\rpc_server.py", line 67, in _state_changed
  File "aiohttp\client_ws.py", line 150, in send_str
  File "aiohttp\http_websocket.py", line 687, in send
  File "aiohttp\http_websocket.py", line 643, in _send_frame
  File "aiohttp\http_websocket.py", line 660, in _write
ConnectionResetError: Cannot write to closing transport

...and yes as @whgipt  mentioned, a lot of proofs found with no proper feedback.

**Comment by mravkine** [comment]
My node also keeps dying with code 1006, I am unable to sync past 25k height with 1.2.0, keep getting this:

2021-07-09T23:37:03.457 full_node chia.full_node.full_node: INFO     Requesting blocks: 25312 to 25344
2021-07-09T23:44:49.687 daemon chia.daemon.server         : INFO     Websocket exception. Closing websocket with chia_full_node code = 1006 (connection closed abnormally [internal]), no reason Traceback (most recent call last):
  File "/home/chia/chia-120/venv/lib/python3.7/site-packages/websockets/protocol.py", line 827, in transfer_data
    message = await self.read_message()
  File "/home/chia/chia-120/venv/lib/python3.7/site-packages/websockets/protocol.py", line 895, in read_message
    frame = await self.read_data_frame(max_size=self.max_size)
  File "/home/chia/chia-120/venv/lib/python3.7/site-packages/websockets/protocol.py", line 971, in read_data_frame
    frame = await self.read_frame(max_size)
  File "/home/chia/chia-120/venv/lib/python3.7/site-packages/websockets/protocol.py", line 1051, in read_frame
    extensions=self.extensions,
  File "/home/chia/chia-120/venv/lib/python3.7/site-packages/websockets/framing.py", line 105, in read
    data = await reader(2)
  File "/usr/lib/python3.7/asyncio/streams.py", line 679, in readexactly
    await self._wait_for_data('readexactly')
  File "/usr/lib/python3.7/asyncio/streams.py", line 473, in _wait_for_data
    await self._waiter
concurrent.futures._base.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/chia/chia-120/chia/daemon/server.py", line 172, in safe_handle
    async for message in websocket:
  File "/home/chia/chia-120/venv/lib/python3.7/site-packages/websockets/protocol.py", line 439, in __aiter__
    yield await self.recv()
  File "/home/chia/chia-120/venv/lib/python3.7/site-packages/websockets/protocol.py", line 509, in recv
    await self.ensure_open()
  File "/home/chia/chia-120/venv/lib/python3.7/site-packages/websockets/protocol.py", line 812, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedError: code = 1006 (connection closed abnormally [internal]), no reason

**Comment by Pikislavcheck** [comment]
I have deleted chia GUI (win 10) and also deleted all my wallet folder. 
It was in resync for nearly 28 hours and seeing the log files when synced after several hours the problem does not appear any more.
I also initialised ca folder on harvesters with "new" certificate files  and everything went back to normal.

**Comment by leoliyuanduo** [comment]
same errors here. It may be caused plotting and farming at same time.

**Comment by whgipt** [comment]
> same errors here. It may be caused plotting and farming at same time.

Yes, I also noticed this after observation on my two machines these two days.
one or two plotting jobs seemed ok, but when it came to three or four in parallal, the issue would appear even CPU was not 100% used.

**Comment by miketom72** [comment]
Just a heads up
I did all the same things, reloaded, resynced etc.. but I think it was because I allocated too much RAM to my queue. I have 64GB but had moved up the ram to 5000GB and had too many plots running at one time. 
FYI, I also changed to Madmax and am having no issues now 
Check out this link, lays it out very well. I am creating a plot ever 34minutes
https://thechiaplot.net/2021/07/09/full-step-by-step-guide-on-plotting-for-pools-with-mad-max/

**Comment by emlowe** [comment]
Closing issue per previous comment

**Comment by mark1no79** [comment]
i start to receive this message
Warning Sending data failed... 
connectionreseterror: cannot write closing transport

**Comment by TechAddict000** [comment]
@emlowe - it appears that people still have this issue. #7832 I tried what was mentioned in this thread - reducing RAM during plotting did not resolve the issue.
