### ISSUE TITLE
[BUG] BrokenProcessPool error aborts syncing

### ISSUE THREAD

**Issue by mravkine** [Chia-Network/chia-blockchain#7339]
**Describe the bug**

Syncing stops with the following error repeating over and over in the logs:

2021-07-10T07:50:54.813 full_node chia.full_node.full_node: ERROR    Error with syncing: <class 'concurrent.futures.process.BrokenProcessPool'>Traceback (most recent call last):
  File "/home/chia/chia-120/chia/full_node/full_node.py", line 700, in _sync
    await self.sync_from_fork_point(fork_point, heaviest_peak_height, heaviest_peak_hash, summaries)
  File "/home/chia/chia-120/chia/full_node/full_node.py", line 766, in sync_from_fork_point
    response.blocks, peer, None if advanced_peak else uint32(fork_point_height), summaries
  File "/home/chia/chia-120/chia/full_node/full_node.py", line 830, in receive_block_batch
    ] = await self.blockchain.pre_validate_blocks_multiprocessing(blocks_to_validate, {}, wp_summaries=wp_summaries)
  File "/home/chia/chia-120/chia/consensus/blockchain.py", line 574, in pre_validate_blocks_multiprocessing
    wp_summaries,
  File "/home/chia/chia-120/chia/consensus/multiprocess_validation.py", line 316, in pre_validate_blocks_multiprocessing
    for batch_result in (await asyncio.gather(*futures))
concurrent.futures.process.BrokenProcessPool: A process in the process pool was terminated abruptly while the future was running or pending.
2021-07-10T07:50:54.813 full_node chia.full_node.full_node: INFO     long sync done

**To Reproduce**

Ubuntu 18.04 LTS

This is a fresh 1.2.0

Still happens if I delete ~/.chia and re-initialize.

**Expected behavior**
Not crashing.

**Screenshots**

**Desktop**

- OS: Linux
- OS Version/Flavor: Ubuntu 18.04.5
- CPU: Intel i7-3770K

**Additional context**

**Comment by mravkine** [comment]
This appears to be a consequence of full_node/daemon crashing with code 1006 and leaving the SQlite db corrupted, deleting ~/.chia/mainnet/db/ solves it (at the expense of starting to sync all over again).

Grabbed ubuntu 18.04 python 3.8 ppas from https://launchpad.net/~deadsnakes/+archive/ubuntu/ppa and re-installed with `INSTALL_PYTHON_VERSION=3.8 sh ./install.sh` and so far so good..
