### ISSUE TITLE
Plot stops at 67% every time

### ISSUE THREAD

**Issue by KillerPriest86** [Chia-Network/chia-blockchain#7350]
Plot stops each time I make pool plots at 67% I get this log for plots.

Starting phase 3/4: Compression from tmp files into "G:\\Temp\\plot-k32-2021-07-10-10-49-a39b48a1390d6f8466bfdd0160f38013f86e6a693924810864b0c450030c9b01.plot.2.tmp" ... Sat Jul 10 14:17:32 2021
Compressing tables 1 and 2
Caught plotting error: bad allocation
Traceback (most recent call last):
  File "D:\a\chia-blockchain\chia-blockchain\venv\Lib\site-packages\chia\cmds\chia.py", line 83, in <module>
  File "D:\a\chia-blockchain\chia-blockchain\venv\Lib\site-packages\chia\cmds\chia.py", line 79, in main
  File "click\core.py", line 829, in __call__
  File "click\core.py", line 782, in main
  File "click\core.py", line 1259, in invoke
  File "click\core.py", line 1259, in invoke
  File "click\core.py", line 1066, in invoke
  File "click\core.py", line 610, in invoke
  File "click\decorators.py", line 21, in new_func
  File "chia\cmds\plots.py", line 135, in create_cmd
  File "chia\plotting\create_plots.py", line 168, in create_plots
RuntimeError: bad allocation
[16624] Failed to execute script chia

**Comment by PsychoLogiKal** [comment]
disable windows managing your virtual memory and set the MIN to 10240 and set the MAX to 30720.........that should solve your issue...
