### ISSUE TITLE
[BUG] esx Datastore problems - resulting in Harvester Problems 

### ISSUE THREAD

**Issue by secco04** [Chia-Network/chia-blockchain#7353]
i have problems with my datastores / drives... they suddenly disconnect.

if that happens the Harvester will freeze and wont continue farming the still working hdds

LOG: ERROR    Harvester did not respond. You might need to update harvester to the latest version

to get it working again i have to at least restart the client - or the whole vm 

**Expected behavior**
harvester should skip not accessible folders faster 
**Desktop**
- OS: Windows 10 VM on esx
- OS Version/Flavor: ESX6.7

**Comment by laozhang713** [comment]
ubuntu20 1.2.1 same promble

**Comment by secco04** [comment]
ok "new" behavior is all HDDs are accessible but neither linux via SMB nor windows direct attached storage want to harvest.
restarting the Harvester results in following error message 

` .\chia.exe start harvester -r
chia_harvester: Error, timeout.
stop failed
chia_harvester: Task exception was never retrieved
future: <Task finished name='Task-5' coro=<DaemonProxy.start.<locals>.listener() done, defined at chia\daemon\client.py:30> exception=ConnectionClosedError('code = 1006 (connection closed abnormally [internal]), no reason')>
Traceback (most recent call last):
  File "websockets\protocol.py", line 827, in transfer_data
  File "websockets\protocol.py", line 895, in read_message
  File "websockets\protocol.py", line 971, in read_data_frame
  File "websockets\protocol.py", line 1047, in read_frame
  File "websockets\framing.py", line 105, in read
  File "asyncio\streams.py", line 723, in readexactly
  File "asyncio\streams.py", line 517, in _wait_for_data
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "chia\daemon\client.py", line 33, in listener
  File "websockets\protocol.py", line 509, in recv
  File "websockets\protocol.py", line 812, in ensure_open
websockets.exceptions.ConnectionClosedError: code = 1006 (connection closed abnormally [internal]), no reason
Error, timeout.
chia_harvester failed to start. Error: no response`

**Comment by keliew** [comment]
I have a similar issue (`asyncio.streams.IncompleteReadError: 0 bytes read on a total of 2 expected bytes`) as well (v1.2.2), wherein the harvester stops responding.
```
2021-07-15T11:38:45.564 daemon chia.daemon.server         : INFO     Websocket exception. Clo
sing websocket with chia_harvester code = 1006 (connection closed abnormally [internal]), no
reason Traceback (most recent call last):
  File "/home/chia/chia/venv/lib/python3.7/site-packages/websockets/protocol.py", line 827, i
n transfer_data
    message = await self.read_message()
  File "/home/chia/chia/venv/lib/python3.7/site-packages/websockets/protocol.py", line 895, i
n read_message
    frame = await self.read_data_frame(max_size=self.max_size)
  File "/home/chia/chia/venv/lib/python3.7/site-packages/websockets/protocol.py", line 971, i
n read_data_frame
    frame = await self.read_frame(max_size)
  File "/home/chia/chia/venv/lib/python3.7/site-packages/websockets/protocol.py", line 1051,
in read_frame
    extensions=self.extensions,
  File "/home/chia/chia/venv/lib/python3.7/site-packages/websockets/framing.py", line 105, in
 read
    data = await reader(2)
  File "/usr/lib/python3.7/asyncio/streams.py", line 677, in readexactly
    raise IncompleteReadError(incomplete, n)
asyncio.streams.IncompleteReadError: 0 bytes read on a total of 2 expected bytes

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/chia/chia/chia/daemon/server.py", line 172, in safe_handle
    async for message in websocket:
  File "/home/chia/chia/venv/lib/python3.7/site-packages/websockets/protocol.py", line 439, in __aiter__
    yield await self.recv()
  File "/home/chia/chia/venv/lib/python3.7/site-packages/websockets/protocol.py", line 509, in recv
    await self.ensure_open()
  File "/home/chia/chia/venv/lib/python3.7/site-packages/websockets/protocol.py", line 803, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedError: code = 1006 (connection closed abnormally [internal]), no reason
```
