### ISSUE TITLE
Chia never sync's

### ISSUE THREAD

**Issue by toxicroadkill** [Chia-Network/chia-blockchain#7360]
I have the correct port open, and have installed from scratch last week, same as the older version, never syncs'

Current Blockchain Status: Not Synced. Peak height: 554615
      Time: Sun Jul 11 2021 02:29:57 UTC                  Height:     554615

Estimated network space: 30.447 EiB
Current difficulty: 2272
Current VDF sub_slot_iters: 120061952
Total iterations since the start of the blockchain: 1869233427939

  Height: |   Hash:
   554615 | 0d402cacc49325cc757bba71d9997afb395c68dc62416558fc53320ff37b04d1
   554614 | f50c39f869961a39d12ae5fdccce02d5d96ebee6b6f2b6c2ab783cffdf6b92cb
   554613 | f0ce6afb1efe18e0883c81aa6804fd09994d6cd1c645e6c76758c871ef91d79b
   554612 | 795abfccdfe08cb350ea4f3f599eef1d2b508c06cb5558693b0b5621eb96d568
   554611 | 92b094708f4cba03304ffe1879c7b02250fc6dc8467d352c6b2fcc58b35b1964
   554610 | 8a998e38d874ea7bc0639a620be913340005f8da2d32e0fe0ee6874ae6b2d3ff
   554609 | 99269ac2e8047cf78644a4881c8c90930a2dd74997bcaeb75b5c35c109a6ae70
   554608 | 4ad3ed1865d9de2dff4876bc717fe713cf6a1191d7454beef5368d5085fae4fa
   554607 | b8ede1620ff844e78eccb829e46f41fe6aee10371a2ddeae184223443b19638c
   554606 | 369b53a4e150970f0b03048be157b8fcf35ee4790fb1b605d30b19c18d123bfa

any ideas?

**Comment by Kgonla** [comment]
Hello, I don't know if it is the same but just after upgrading to 1.2.0 my wallet never syncs:

Already connected, not reconnecting.
​ 0
​ Uncaught Error: connect ECONNREFUSED 127.0.0.1:55400
    at TCPConnectWrap.afterConnect [as oncomplete] (​)

This is continuous error, retry after retry

http://fotos.subefotos.com/2229250e4fbf0caa06e81dcd1832da79o.jpg

**Comment by keliew** [comment]
what does the `debug.log` say?

**Comment by Kgonla** [comment]
> what does the `debug.log` say?

If you are asking to me, I get nothing inside debug.log.
Tested with WARNING, INFO & DEBUG. Log is empty.

**Comment by toxicroadkill** [comment]
here is a sample, LOTS of ssl errors


2021-07-11T19:16:52.968 full_node asyncio                 : ERROR    SSL error in data received
protocol: <asyncio.sslproto.SSLProtocol object at 0x7f3b15262860>
transport: <_SelectorSocketTransport fd=89 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/usr/lib/python3.7/asyncio/sslproto.py", line 526, in data_received
    ssldata, appdata = self._sslpipe.feed_ssldata(data)
  File "/usr/lib/python3.7/asyncio/sslproto.py", line 207, in feed_ssldata
    self._sslobj.unwrap()
  File "/usr/lib/python3.7/ssl.py", line 767, in unwrap
    return self._sslobj.shutdown()
ssl.SSLError: [SSL: KRB5_S_INIT] application data after close notify (_ssl.c:2609)
2021-07-11T19:16:53.596 full_node asyncio                 : ERROR    SSL error in data received
protocol: <asyncio.sslproto.SSLProtocol object at 0x7f3aa02a0198>
transport: <_SelectorSocketTransport fd=118 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/usr/lib/python3.7/asyncio/sslproto.py", line 526, in data_received
    ssldata, appdata = self._sslpipe.feed_ssldata(data)
  File "/usr/lib/python3.7/asyncio/sslproto.py", line 207, in feed_ssldata
    self._sslobj.unwrap()
  File "/usr/lib/python3.7/ssl.py", line 767, in unwrap
    return self._sslobj.shutdown()
ssl.SSLError: [SSL: KRB5_S_INIT] application data after close notify (_ssl.c:2609)
2021-07-11T19:17:02.873 full_node asyncio                 : ERROR    SSL error in data received
protocol: <asyncio.sslproto.SSLProtocol object at 0x7f3a40429278>
transport: <_SelectorSocketTransport fd=89 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/usr/lib/python3.7/asyncio/sslproto.py", line 526, in data_received
    ssldata, appdata = self._sslpipe.feed_ssldata(data)
  File "/usr/lib/python3.7/asyncio/sslproto.py", line 207, in feed_ssldata
    self._sslobj.unwrap()
  File "/usr/lib/python3.7/ssl.py", line 767, in unwrap
    return self._sslobj.shutdown()
ssl.SSLError: [SSL: KRB5_S_INIT] application data after close notify (_ssl.c:2609)
2021-07-11T19:17:03.534 full_node asyncio                 : ERROR    SSL error in data received
protocol: <asyncio.sslproto.SSLProtocol object at 0x7f3a40429128>
transport: <_SelectorSocketTransport fd=118 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/usr/lib/python3.7/asyncio/sslproto.py", line 526, in data_received
    ssldata, appdata = self._sslpipe.feed_ssldata(data)
  File "/usr/lib/python3.7/asyncio/sslproto.py", line 207, in feed_ssldata
    self._sslobj.unwrap()
  File "/usr/lib/python3.7/ssl.py", line 767, in unwrap
    return self._sslobj.shutdown()
ssl.SSLError: [SSL: KRB5_S_INIT] application data after close notify (_ssl.c:2609)
2021-07-11T19:17:10.259 full_node asyncio                 : ERROR    SSL error in data received
protocol: <asyncio.sslproto.SSLProtocol object at 0x7f3b2034de80>
transport: <_SelectorSocketTransport fd=89 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/usr/lib/python3.7/asyncio/sslproto.py", line 526, in data_received
    ssldata, appdata = self._sslpipe.feed_ssldata(data)
  File "/usr/lib/python3.7/asyncio/sslproto.py", line 207, in feed_ssldata
    self._sslobj.unwrap()
  File "/usr/lib/python3.7/ssl.py", line 767, in unwrap
    return self._sslobj.shutdown()
ssl.SSLError: [SSL: KRB5_S_INIT] application data after close notify (_ssl.c:2609)
2021-07-11T19:17:13.219 full_node asyncio                 : ERROR    SSL error in data received
protocol: <asyncio.sslproto.SSLProtocol object at 0x7f39ea28cd68>
transport: <_SelectorSocketTransport fd=89 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/usr/lib/python3.7/asyncio/sslproto.py", line 526, in data_received
    ssldata, appdata = self._sslpipe.feed_ssldata(data)
  File "/usr/lib/python3.7/asyncio/sslproto.py", line 207, in feed_ssldata
    self._sslobj.unwrap()
  File "/usr/lib/python3.7/ssl.py", line 767, in unwrap
    return self._sslobj.shutdown()
ssl.SSLError: [SSL: KRB5_S_INIT] application data after close notify (_ssl.c:2609)
2021-07-11T19:17:13.950 full_node asyncio                 : ERROR    SSL error in data received
protocol: <asyncio.sslproto.SSLProtocol object at 0x7f3b25c9b780>
transport: <_SelectorSocketTransport fd=89 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/usr/lib/python3.7/asyncio/sslproto.py", line 526, in data_received
    ssldata, appdata = self._sslpipe.feed_ssldata(data)
  File "/usr/lib/python3.7/asyncio/sslproto.py", line 207, in feed_ssldata
    self._sslobj.unwrap()
  File "/usr/lib/python3.7/ssl.py", line 767, in unwrap
    return self._sslobj.shutdown()
ssl.SSLError: [SSL: KRB5_S_INIT] application data after close notify (_ssl.c:2609)
2021-07-11T19:17:16.431 full_node asyncio                 : ERROR    SSL error in data received
protocol: <asyncio.sslproto.SSLProtocol object at 0x7f3b1d440cc0>
transport: <_SelectorSocketTransport fd=37 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/usr/lib/python3.7/asyncio/sslproto.py", line 526, in data_received
    ssldata, appdata = self._sslpipe.feed_ssldata(data)
  File "/usr/lib/python3.7/asyncio/sslproto.py", line 207, in feed_ssldata
    self._sslobj.unwrap()
  File "/usr/lib/python3.7/ssl.py", line 767, in unwrap
    return self._sslobj.shutdown()
ssl.SSLError: [SSL: KRB5_S_INIT] application data after close notify (_ssl.c:2609)
2021-07-11T19:17:23.732 full_node asyncio                 : ERROR    SSL error in data received
protocol: <asyncio.sslproto.SSLProtocol object at 0x7f3a0009e160>
transport: <_SelectorSocketTransport fd=37 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/usr/lib/python3.7/asyncio/sslproto.py", line 526, in data_received
    ssldata, appdata = self._sslpipe.feed_ssldata(data)
  File "/usr/lib/python3.7/asyncio/sslproto.py", line 207, in feed_ssldata
    self._sslobj.unwrap()
  File "/usr/lib/python3.7/ssl.py", line 767, in unwrap
    return self._sslobj.shutdown()
ssl.SSLError: [SSL: KRB5_S_INIT] application data after close notify (_ssl.c:2609)
2021-07-11T19:17:45.686 full_node asyncio                 : ERROR    SSL error in data received
protocol: <asyncio.sslproto.SSLProtocol object at 0x7f3ae3e62400>
transport: <_SelectorSocketTransport fd=37 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/usr/lib/python3.7/asyncio/sslproto.py", line 526, in data_received
    ssldata, appdata = self._sslpipe.feed_ssldata(data)
  File "/usr/lib/python3.7/asyncio/sslproto.py", line 207, in feed_ssldata
    self._sslobj.unwrap()
  File "/usr/lib/python3.7/ssl.py", line 767, in unwrap
    return self._sslobj.shutdown()
ssl.SSLError: [SSL: KRB5_S_INIT] application data after close notify (_ssl.c:2609)
2021-07-11T19:17:54.267 full_node asyncio                 : ERROR    SSL error in data received
protocol: <asyncio.sslproto.SSLProtocol object at 0x7f3af270e320>
transport: <_SelectorSocketTransport fd=37 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/usr/lib/python3.7/asyncio/sslproto.py", line 526, in data_received
    ssldata, appdata = self._sslpipe.feed_ssldata(data)
  File "/usr/lib/python3.7/asyncio/sslproto.py", line 207, in feed_ssldata
    self._sslobj.unwrap()
  File "/usr/lib/python3.7/ssl.py", line 767, in unwrap
    return self._sslobj.shutdown()
ssl.SSLError: [SSL: KRB5_S_INIT] application data after close notify (_ssl.c:2609)
2021-07-11T19:17:54.977 full_node asyncio                 : ERROR    SSL error in data received
protocol: <asyncio.sslproto.SSLProtocol object at 0x7f39ead002b0>
transport: <_SelectorSocketTransport fd=76 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/usr/lib/python3.7/asyncio/sslproto.py", line 526, in data_received
    ssldata, appdata = self._sslpipe.feed_ssldata(data)
  File "/usr/lib/python3.7/asyncio/sslproto.py", line 207, in feed_ssldata
    self._sslobj.unwrap()
  File "/usr/lib/python3.7/ssl.py", line 767, in unwrap
    return self._sslobj.shutdown()
ssl.SSLError: [SSL: KRB5_S_INIT] application data after close notify (_ssl.c:2609)
2021-07-11T19:17:58.729 full_node asyncio                 : ERROR    SSL error in data received
protocol: <asyncio.sslproto.SSLProtocol object at 0x7f3ae0312470>
transport: <_SelectorSocketTransport fd=76 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/usr/lib/python3.7/asyncio/sslproto.py", line 526, in data_received
    ssldata, appdata = self._sslpipe.feed_ssldata(data)
  File "/usr/lib/python3.7/asyncio/sslproto.py", line 207, in feed_ssldata
    self._sslobj.unwrap()
  File "/usr/lib/python3.7/ssl.py", line 767, in unwrap
    return self._sslobj.shutdown()
ssl.SSLError: [SSL: KRB5_S_INIT] application data after close notify (_ssl.c:2609)
2021-07-11T19:18:05.632 full_node asyncio                 : ERROR    SSL error in data received
protocol: <asyncio.sslproto.SSLProtocol object at 0x7f39ea7e5e10>
transport: <_SelectorSocketTransport fd=76 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/usr/lib/python3.7/asyncio/sslproto.py", line 526, in data_received
    ssldata, appdata = self._sslpipe.feed_ssldata(data)
  File "/usr/lib/python3.7/asyncio/sslproto.py", line 207, in feed_ssldata
    self._sslobj.unwrap()
  File "/usr/lib/python3.7/ssl.py", line 767, in unwrap
    return self._sslobj.shutdown()
ssl.SSLError: [SSL: KRB5_S_INIT] application data after close notify (_ssl.c:2609)
2021-07-11T19:18:07.019 full_node asyncio                 : ERROR    SSL error in data received
protocol: <asyncio.sslproto.SSLProtocol object at 0x7f3a6013c3c8>
transport: <_SelectorSocketTransport fd=89 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/usr/lib/python3.7/asyncio/sslproto.py", line 526, in data_received
    ssldata, appdata = self._sslpipe.feed_ssldata(data)
  File "/usr/lib/python3.7/asyncio/sslproto.py", line 207, in feed_ssldata
    self._sslobj.unwrap()
  File "/usr/lib/python3.7/ssl.py", line 767, in unwrap
    return self._sslobj.shutdown()
ssl.SSLError: [SSL: KRB5_S_INIT] application data after close notify (_ssl.c:2609)
2021-07-11T19:18:07.793 full_node asyncio                 : ERROR    SSL error in data received
protocol: <asyncio.sslproto.SSLProtocol object at 0x7f3ae3ef3dd8>
transport: <_SelectorSocketTransport fd=76 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/usr/lib/python3.7/asyncio/sslproto.py", line 526, in data_received
    ssldata, appdata = self._sslpipe.feed_ssldata(data)
  File "/usr/lib/python3.7/asyncio/sslproto.py", line 207, in feed_ssldata
    self._sslobj.unwrap()
  File "/usr/lib/python3.7/ssl.py", line 767, in unwrap
    return self._sslobj.shutdown()
ssl.SSLError: [SSL: KRB5_S_INIT] application data after close notify (_ssl.c:2609)
2021-07-11T19:18:08.124 full_node asyncio                 : ERROR    SSL error in data received
protocol: <asyncio.sslproto.SSLProtocol object at 0x7f3ae3ef3d68>
transport: <_SelectorSocketTransport fd=89 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/usr/lib/python3.7/asyncio/sslproto.py", line 526, in data_received
    ssldata, appdata = self._sslpipe.feed_ssldata(data)
  File "/usr/lib/python3.7/asyncio/sslproto.py", line 207, in feed_ssldata
    self._sslobj.unwrap()
  File "/usr/lib/python3.7/ssl.py", line 767, in unwrap
    return self._sslobj.shutdown()
ssl.SSLError: [SSL: KRB5_S_INIT] application data after close notify (_ssl.c:2609)

**Comment by toxicroadkill** [comment]
ok


updated debian 10 to the latest packages
updated python 
updated chia on the main machine(the farmer)

now...

in the log


 farmer chia.farmer.farmer         : ERROR    Harvester did not respond. You might need to update harvester to the latest version


you have to be kidding me, now i have to go update a ****** of machines also?


seriously?


not a happy  camper here at all!


BACKWARD COMPATIBILITY FOLKS!!!!

**Comment by emlowe** [comment]
Harvesters and Farmers must be both on the 1.2.x release - recommend upgrading to 1.2.1 as there are some additional communication bugs with 1.2.0
