### ISSUE TITLE
[BUG] Wallet sync stuck at height: 45280

### ISSUE THREAD

**Issue by only-one-suchy** [Chia-Network/chia-blockchain#7398]
**Describe the bug**
Wallet synchronization stops at height 45280

**To Reproduce**

1. Delete wallet db
2. Restart wallet
3. Wait for synchronization
4. Synchronization stops at height 45280

**Expected behavior**
Wallet syncs completely.

**Desktop**
XFCE4 / Windows 10

- OS: Linux & Windows
- OS Version/Flavor: Linux Debian 10, Windows 10
- CPU: Intel(R) Core(TM) i5-2540M CPU @ 2.60GHz, Intel Core i7 vPro 9th Gen

**Additional context**
Deleted wallet db and started syncing from start. Same problem. All test ran on same private key.

**Comment by loppefaaret** [comment]
can you check `debug.log` for ERROR or WARNING reported by the wallet service ?
it is located in your user folder, under `~/.chia/mainnet/log/`
if any other WARNING or ERROR his happening around the same timestamp, please include those as well

**Comment by only-one-suchy** [comment]
[](url)

**Comment by only-one-suchy** [comment]
[debug.log](https://github.com/Chia-Network/chia-blockchain/files/6801156/debug.log)
Hmm, the blockchain has been copied to both of the machines encoutering issue. But the full node syncs correctly

**Comment by loppefaaret** [comment]
seems to be a possibility that the copied blockchain has been corrupted, and the wallet gets that data around 45280 ?

**Comment by only-one-suchy** [comment]
No I don't think so. I did additional tests. Deleted wallet db and blockchain and started syncing from start. Now the full node is stuck at 45280

**Comment by loppefaaret** [comment]
and what are you seeing in `debug.log` now ?

**Comment by deanrey** [comment]
Seeing similar issues with wallet partially syncing. To be honest I'm having several issues with connecting to and failed wallet syncing.

I've tried deleting my wallet files several times and issue keep on coming back.

**Comment by madrigo64** [comment]
Try to check if you have free space on drive where is config folder of chia.
Try to use this  file to add pears  **pears.bat**
`echo off
cd /d %LOCALAPPDATA%\chia-blockchain\app-1.2.2\resources\app.asar.unpacked\daemon


chia show -a node-apne.chia.net:8444

chia show -a introducer-apne.chia.net:8444

chia show -a introducer-apse.chia.net:8444

chia show -a introducer-or.chia.net:8444

chia show -a introducer-va.chia.net:8444

chia show -a introducer-eu.chia.net:8444

chia show -a chiadb.net:8444

chia show -a pyl.dk:8444

chia show -a node.chia.net:8444

chia show -a 81.83.5.50:8444

chia show -a 118.189.201.184:8444

chia show -a 63.86.188.28:8444

chia show -a 70.67.4.75:8444

chia show -a 159.28.171.166:8444

chia show -a 37.145.52.144:8444

chia show -a 123.57.42.226:8444

chia show -a 76.251.32.219:8444

chia show -a 70.224.19.232:8444

chia show -a 73.252.215.180:8444

chia show -a 205.134.173.77:8444


chia show -a 84.107.167.248:8444

chia show -a 86.57.236.161:8444

chia show -a 211.227.132.15:8444

chia show -a 72.39.161.212:8444

chia show -a 201.131.68.254:8444

chia show -a 90.222.8.93:8444

chia show -a 178.82.152.5:8444

chia show -a 24.24.132.82:8444

chia show -a 80.212.44.58:8444

chia show -a 37.193.78.56:8444

chia show -a 65.24.91.237:8444

`

**Comment by dmitryalexandrow** [comment]
здравствуйте!у меня аналогичная проблема кошелёк зависает на высоте 564654 и в debag log выдаёт  RuntimeError: Was not able to add blocks 564653-564685. Подскажите что делать

**Comment by madrigo64** [comment]
> 
> 
> здравствуйте!у меня аналогичная проблема кошелёк зависает на высоте 564654 и в debag log выдаёт RuntimeError: Was not able to add blocks 564653-564685. Подскажите что делать

Перезапускаешь пару раз, если все равно зависает на этом.
То проверь есть ли свободное место на диске где находится конфиг файл .chia
Запусти команду что я писал выше.
Если проблема осталась, скорей всего есть проблема с базой данных кошелька
Удали его и синхронизируйся заново
Базы данных кошелька находятся по адресу C:\Users\user\.chia\mainnet\wallet\db
И вообще, когда сможешь синхронизироваться, я рекомендую переодически делать бекап всей папки .chia с ее БД

**Comment by dmitryalexandrow** [comment]
Благо дарю,Олег! Я так и сделал!только я полностью снёс всю папку Chia (предварительно сохранив её),и всё синхронизировал по новой.
25.07.2021, 17:14, Oleg < ***@***.*** ***@***.*** >
здравствуйте!у меня аналогичная проблема кошелёк зависает на высоте 564654 и в debag log выдаёт RuntimeError: Was not able to add blocks 564653-564685. Подскажите что делать
Перезапускаешь пару раз, если все равно зависает на этом. То проверь есть ли свободное место на диске где находится конфиг файл .chia Запусти команду что я писал выше. Если проблема осталась, скорей всего есть проблема с базой данных кошелька Удали его и синхронизируйся заново Базы данных кошелька находятся по адресу C:\Users\user.chia\mainnet\wallet\db И вообще, когда сможешь синхронизироваться, я рекомендую переодически делать бекап всей папки .chia с ее БД

**Comment by only-one-suchy** [comment]
Same error again. This time in my lab. I have 4 debian 10 machines. Using 1.2.2 chia version. Removed .chia folder on all 4 of them, and configured to use testnet7. Node synced on all of the machines. Wallet synced correctly on only one, three other machines stuck on the same wallet height.

Debug.log

```2021-07-26T14:50:30.223 wallet chia.pools.pool_puzzles    : ERROR    Unexpected return from PoolWallet Smart Contract code cannot unpack non-iterable int object
2021-07-26T14:50:30.228 wallet chia.wallet.wallet_blockchain: ERROR    Error during db transaction: cannot unpack non-iterable int object
2021-07-26T14:50:30.236 wallet chia.wallet.wallet_node    : ERROR    Error while trying to fetch from peer:cannot unpack non-iterable int object Traceback (most recent call last):
  File "/home/chia/chia-blockchain/chia/wallet/wallet_node.py", line 528, in batch_sync_to_peak
    peer, uint32(start_height), uint32(end_height), None if advanced_peak else fork_height
  File "/home/chia/chia-blockchain/chia/wallet/wallet_node.py", line 733, in fetch_blocks_and_validate
    additional_coin_spends=additional_coin_spends,
  File "/home/chia/chia-blockchain/chia/wallet/wallet_blockchain.py", line 238, in receive_block
    block_record, genesis, fork_point_with_peak, additional_coin_spends, heights_changed
  File "/home/chia/chia-blockchain/chia/wallet/wallet_blockchain.py", line 353, in _reconsider_peak
    additional_coin_spends,
  File "/home/chia/chia-blockchain/chia/wallet/wallet_state_manager.py", line 600, in new_transaction_block_callback
    self, self.main_wallet, cs.coin.name(), additional_coin_spends, height, True, "pool_wallet"
  File "/home/chia/chia-blockchain/chia/pools/pool_wallet.py", line 358, in create
    await self.update_pool_config(True)
  File "/home/chia/chia-blockchain/chia/pools/pool_wallet.py", line 230, in update_pool_config
    current_state: PoolWalletInfo = await self.get_current_state()
  File "/home/chia/chia-blockchain/chia/pools/pool_wallet.py", line 189, in get_current_state
    delayed_seconds, delayed_puzhash = get_delayed_puz_info_from_launcher_spend(all_spends[0])
  File "/home/chia/chia-blockchain/chia/pools/pool_puzzles.py", line 103, in get_delayed_puz_info_from_launcher_spend
    for key, value in extra_data.as_python():
TypeError: cannot unpack non-iterable int object

2021-07-26T14:50:30.238 wallet chia.wallet.wallet_node    : ERROR    Loop exception in sync Was not able to add blocks 146269-146301. Traceback (most recent call last):
  File "/home/chia/chia-blockchain/chia/wallet/wallet_node.py", line 580, in sync_job
    await self._sync()
  File "/home/chia/chia-blockchain/chia/wallet/wallet_node.py", line 660, in _sync
    await self.batch_sync_to_peak(fork_height, peak)
  File "/home/chia/chia-blockchain/chia/wallet/wallet_node.py", line 537, in batch_sync_to_peak
    raise RuntimeError(f"Was not able to add blocks {start_height}-{end_height}")
RuntimeError: Was not able to add blocks 146269-146301
```

**Comment by only-one-suchy** [comment]
I stopped chia, deleted wallet db and started it to sync again. Still the same, synced to 146270.
debug.log:
```
2021-07-27T00:05:40.959 wallet chia.wallet.wallet_node    : ERROR    Loop exception in sync Was not able to add blocks 146240-146272. Traceback (most recent call last):
  File "/home/chia/chia-blockchain/chia/wallet/wallet_node.py", line 580, in sync_job
    await self._sync()
  File "/home/chia/chia-blockchain/chia/wallet/wallet_node.py", line 660, in _sync
    await self.batch_sync_to_peak(fork_height, peak)
  File "/home/chia/chia-blockchain/chia/wallet/wallet_node.py", line 537, in batch_sync_to_peak
    raise RuntimeError(f"Was not able to add blocks {start_height}-{end_height}")
RuntimeError: Was not able to add blocks 146240-146272
```

**Comment by dmitryalexandrow** [comment]
порт 8444 проброшен? если да ! Есть ещё один вариант проблемы.Синхронизация прошла на основной машине. а на харвестерах нет?  нужно поменять динамичный IP на статичный IP  даю ссылку для настройки :http://chia-farming.ru/chia_horvwin
26.07.2021, 21:24, only-one-suchy < ***@***.*** ***@***.*** >
Same error again. This time in my lab. I have 4 debian 10 machines. Using 1.2.2 chia version. Removed .chia folder on all 4 of them, and configured to use testnet7. Node synced on all of the machines. Wallet synced correctly on only one, three other machines stuck on the same wallet height.
Debug.log
2021-07-26T14:50:30.228 wallet chia.wallet.wallet_blockchain: ERROR    Error during db transaction: cannot unpack non-iterable int object
2021-07-26T14:50:30.236 wallet chia.wallet.wallet_node    : ERROR    Error while trying to fetch from peer:cannot unpack non-iterable int object Traceback (most recent call last):
  File "/home/chia/chia-blockchain/chia/wallet/wallet_node.py", line 528, in batch_sync_to_peak
    peer, uint32(start_height), uint32(end_height), None if advanced_peak else fork_height
  File "/home/chia/chia-blockchain/chia/wallet/wallet_node.py", line 733, in fetch_blocks_and_validate
    additional_coin_spends=additional_coin_spends,
  File "/home/chia/chia-blockchain/chia/wallet/wallet_blockchain.py", line 238, in receive_block
    block_record, genesis, fork_point_with_peak, additional_coin_spends, heights_changed
  File "/home/chia/chia-blockchain/chia/wallet/wallet_blockchain.py", line 353, in _reconsider_peak
    additional_coin_spends,
  File "/home/chia/chia-blockchain/chia/wallet/wallet_state_manager.py", line 600, in new_transaction_block_callback
    self, self.main_wallet, cs.coin.name(), additional_coin_spends, height, True, "pool_wallet"
  File "/home/chia/chia-blockchain/chia/pools/pool_wallet.py", line 358, in create
    await self.update_pool_config(True)
  File "/home/chia/chia-blockchain/chia/pools/pool_wallet.py", line 230, in update_pool_config
    current_state: PoolWalletInfo = await self.get_current_state()
  File "/home/chia/chia-blockchain/chia/pools/pool_wallet.py", line 189, in get_current_state
    delayed_seconds, delayed_puzhash = get_delayed_puz_info_from_launcher_spend(all_spends[0])
  File "/home/chia/chia-blockchain/chia/pools/pool_puzzles.py", line 103, in get_delayed_puz_info_from_launcher_spend
    for key, value in extra_data.as_python():
TypeError: cannot unpack non-iterable int object

2021-07-26T14:50:30.238 wallet chia.wallet.wallet_node    : ERROR    Loop exception in sync Was not able to add blocks 146269-146301. Traceback (most recent call last):
  File "/home/chia/chia-blockchain/chia/wallet/wallet_node.py", line 580, in sync_job
    await self._sync()
  File "/home/chia/chia-blockchain/chia/wallet/wallet_node.py", line 660, in _sync
    await self.batch_sync_to_peak(fork_height, peak)
  File "/home/chia/chia-blockchain/chia/wallet/wallet_node.py", line 537, in batch_sync_to_peak
    raise RuntimeError(f"Was not able to add blocks {start_height}-{end_height}")

**Comment by only-one-suchy** [comment]
The only thing that solves the problem is creating new set of keys and deleting blockchain data, wallet data and syncing from beginning.

**Comment by madrigo64** [comment]
> The only thing that solves the problem is creating new set of keys and deleting blockchain data, wallet data and syncing from beginning.

You can just delete DB files

**Comment by dmitryalexandrow** [comment]
Maybe.I think that the algorithm of actions depends on the essence of the problem.I managed without replacing the keys
03.08.2021, 00:42, only-one-suchy < ***@***.*** ***@***.*** >
The only thing that solves the problem is creating new set of keys and deleting blockchain data, wallet data and syncing from beginning.

**Comment by only-one-suchy** [comment]
> > The only thing that solves the problem is creating new set of keys and deleting blockchain data, wallet data and syncing from beginning.
> 
> You can just delete DB files

Not in my case. I tried:

- deleting wallet db only
- deleting wallet and blockchain db
- deleting and creating new keys and deleting wallet db

And only the third option worked for me.
