### ISSUE TITLE
full_node full_node_server        : ERROR    Exception: Could not decode to UTF-8 column 'coin_parent' with text[BUG]

### ISSUE THREAD

**Issue by inkpool** [Chia-Network/chia-blockchain#7428]
**Describe the bug**
Cannot sync wallet after the node is synced.

**To Reproduce**

Ubuntu 20.04 CLI tools. 

version 1.2.0 and 1.2.1

Repeated logs in debug.log:

full_node full_node_server        : ERROR    Exception: Could not decode to UTF-8 column 'coin_parent' with text 'xxxxx'
 <class 'sqlite3.OperationalError'>, closing connection {'host': '127.0.0.1', 'port': 8449}. Traceback (most recent call last):
  File "/home/chia/chia-blockchain/chia/server/server.py", line 533, in api_call
    response: Optional[Message] = await asyncio.wait_for(wrapped_coroutine(), timeout=timeout)
  File "/usr/lib/python3.8/asyncio/tasks.py", line 494, in wait_for
    return fut.result()
  File "/home/chia/chia-blockchain/chia/server/server.py", line 530, in wrapped_coroutine
    raise e
  File "/home/chia/chia-blockchain/chia/server/server.py", line 523, in wrapped_coroutine
    result = await coroutine
  File "/home/chia/chia-blockchain/chia/full_node/full_node_api.py", line 1258, in request_header_blocks
    removed_coins_records = await self.full_node.coin_store.get_coins_removed_at_height(block.height)
  File "/home/chia/chia-blockchain/chia/full_node/coin_store.py", line 134, in get_coins_removed_at_height
    rows = await cursor.fetchall()
  File "/home/chia/chia-blockchain/venv/lib/python3.8/site-packages/aiosqlite/cursor.py", line 65, in fetchall
    return await self._execute(self._cursor.fetchall)
  File "/home/chia/chia-blockchain/venv/lib/python3.8/site-packages/aiosqlite/cursor.py", line 31, in _execute
    return await self._conn._execute(fn, *args, **kwargs)
  File "/home/chia/chia-blockchain/venv/lib/python3.8/site-packages/aiosqlite/core.py", line 129, in _execute
    return await future
  File "/home/chia/chia-blockchain/venv/lib/python3.8/site-packages/aiosqlite/core.py", line 102, in run
    result = function()
sqlite3.OperationalError: Could not decode to UTF-8 column 'coin_parent' with text 'xxxxx'

**Comment by inkpool** [comment]
I deleted the db files and re-sync them again. Still the same error. Stuck on the same height 343488.

2021-07-12T18:53:36.711 full_node full_node_server        : ERROR    Exception: Could not decode to UTF-8 column 'coin_parent' with text '5b�2962141f29c48f435043b8509a0504037be428ea9b522878141241c8aa486' <class 'sqlite3.OperationalError'>, closing connection {'host': '127.0.0.1', 'port': 8449}. Traceback (most recent call last):
  File "/home/chia/chia-blockchain/chia/server/server.py", line 533, in api_call
    response: Optional[Message] = await asyncio.wait_for(wrapped_coroutine(), timeout=timeout)
  File "/usr/lib/python3.8/asyncio/tasks.py", line 494, in wait_for
    return fut.result()
  File "/home/chia/chia-blockchain/chia/server/server.py", line 530, in wrapped_coroutine
    raise e
  File "/home/chia/chia-blockchain/chia/server/server.py", line 523, in wrapped_coroutine
    result = await coroutine
  File "/home/chia/chia-blockchain/chia/full_node/full_node_api.py", line 1257, in request_header_blocks
    added_coins_records = await self.full_node.coin_store.get_coins_added_at_height(block.height)
  File "/home/chia/chia-blockchain/chia/full_node/coin_store.py", line 124, in get_coins_added_at_height
    rows = await cursor.fetchall()
  File "/home/chia/chia-blockchain/venv/lib/python3.8/site-packages/aiosqlite/cursor.py", line 65, in fetchall
    return await self._execute(self._cursor.fetchall)
  File "/home/chia/chia-blockchain/venv/lib/python3.8/site-packages/aiosqlite/cursor.py", line 31, in _execute
    return await self._conn._execute(fn, *args, **kwargs)
  File "/home/chia/chia-blockchain/venv/lib/python3.8/site-packages/aiosqlite/core.py", line 129, in _execute
    return await future
  File "/home/chia/chia-blockchain/venv/lib/python3.8/site-packages/aiosqlite/core.py", line 102, in run
    result = function()
sqlite3.OperationalError: Could not decode to UTF-8 column 'coin_parent' with text '5b�2962141f29c48f435043b8509a0504037be428ea9b522878141241c8aa486'
