### ISSUE TITLE
Not Synced,reinstall and delete .chia config no effect

### ISSUE THREAD

**Issue by locetyang** [Chia-Network/chia-blockchain#7491]
2021-07-14T22:51:59.016 harvester chia.harvester.harvester: WARNING  Not farming any plots on this harvester. Check your configuration.
2021-07-14T22:52:15.826 wallet asyncio                    : ERROR    Task exception was never retrieved
future: <Task finished name='Task-16' coro=<WalletPeers.ensure_is_closed() done, defined at chia\server\node_discovery.py:701> exception=AttributeError("'WalletPeers' object has no attribute 'connection'")>
Traceback (most recent call last):
  File "chia\server\node_discovery.py", line 704, in ensure_is_closed
  File "chia\server\node_discovery.py", line 118, in _close_common
AttributeError: 'WalletPeers' object has no attribute 'connection'
2021-07-14T22:52:17.681 wallet chia.rpc.wallet_rpc_api    : ERROR    error No backup on backup service
2021-07-14T22:52:33.467 full_node chia.full_node.full_node: WARNING  querying DNS introducer failed: The DNS operation timed out after 32.00313687324524 seconds
2021-07-14T22:53:21.367 full_node chia.full_node.full_node: ERROR    Respond peers exception: 'NoneType' object has no attribute 'host'. Traceback: Traceback (most recent call last):
  File "chia\server\node_discovery.py", line 608, in respond_peers
  File "chia\server\node_discovery.py", line 573, in add_peers_neighbour
AttributeError: 'NoneType' object has no attribute 'host'

**Comment by locetyang** [comment]
version 1.2.1

**Comment by JoacoB** [comment]
I have the same problem bro. Please tell me if you could solve it

**Comment by madrigo64** [comment]
https://github.com/Chia-Network/chia-blockchain/issues/5308
