### ISSUE TITLE
[BUG] Chia.exe crash.

### ISSUE THREAD

**Issue by lpaln** [Chia-Network/chia-blockchain#7508]
**Describe the bug**
The Chia.exe application randomly crashes on my windows x64 machine. I have also seen the same logs in another thread posted by a Linux user marked as "Stale"

https://github.com/Chia-Network/chia-blockchain/issues/6303

**To Reproduce**

Leave Chia.exe farming for some period of time. Could be days or weeks. Eventually at some random point the crash occurs. There are no indications in the log of any issue prior to the crash entries.

**LOG**
_2021-07-13T18:25:02.460 daemon __main__                   : INFO     Websocket exception. Closing websocket with wallet_ui code = 1006 (connection closed abnormally [internal]), no reason Traceback (most recent call last):
  File "asyncio\windows_events.py", line 457, in finish_recv
OSError: [WinError 64] The specified network name is no longer available
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "websockets\protocol.py", line 827, in transfer_data
  File "websockets\protocol.py", line 895, in read_message
  File "websockets\protocol.py", line 971, in read_data_frame
  File "websockets\protocol.py", line 1047, in read_frame
  File "websockets\framing.py", line 105, in read
  File "asyncio\streams.py", line 723, in readexactly
  File "asyncio\streams.py", line 517, in _wait_for_data
  File "asyncio\proactor_events.py", line 280, in _loop_reading
  File "asyncio\windows_events.py", line 812, in _poll
  File "asyncio\windows_events.py", line 461, in finish_recv
ConnectionResetError: [WinError 64] The specified network name is no longer available
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "D:\a\chia-blockchain\chia-blockchain\venv\Lib\site-packages\chia\daemon\server.py", line 172, in safe_handle
  File "websockets\protocol.py", line 439, in __aiter__
  File "websockets\protocol.py", line 509, in recv
  File "websockets\protocol.py", line 803, in ensure_open
websockets.exceptions.ConnectionClosedError: code = 1006 (connection closed abnormally [internal]), no reason_

**Desktop**
- OS: Windows & Linux
- OS Version/Flavor: All
- CPU: 10850k Intel

**Additional context**
The issue seemingly occurs and random and stops all farming until the machine is attended to.

**Comment by Aidan24** [comment]
I have pages of this type of error too. Running Windows 10, version 1.2.2 of Chia. Leads to farmer showing increasingly delayed challenges eventually getting out of time sequence. Space reported on the pool then drops (I'm assuming it is not seeing any proofs from me). I've only noticed this when plotting (from the GUI). Reported before (but didn't check the log) on issue #7444, but marked as SSL duplicate. Since upgrading to 1.2.2 still an issue.

Traceback (most recent call last):
  File "D:\a\chia-blockchain\chia-blockchain\venv\Lib\site-packages\chia\daemon\server.py", line 187, in safe_handle
  File "websockets\protocol.py", line 555, in send
  File "websockets\protocol.py", line 812, in ensure_open
websockets.exceptions.ConnectionClosedError: code = 1006 (connection closed abnormally [internal]), no reason

2021-07-15T09:25:09.115 daemon websockets.protocol        : ERROR    Error in data transfer
Traceback (most recent call last):
  File "websockets\protocol.py", line 827, in transfer_data
  File "websockets\protocol.py", line 895, in read_message
  File "websockets\protocol.py", line 995, in read_data_frame
  File "websockets\protocol.py", line 766, in pong
  File "websockets\protocol.py", line 803, in ensure_open
websockets.exceptions.ConnectionClosedError: code = 1006 (connection closed abnormally [internal]), no reason
2021-07-15T09:26:07.098 daemon __main__                   : ERROR    Unexpected exception trying to send to websocket: code = 1006 (connection closed abnormally [internal]), no reason Traceback (most recent call last):
  File "websockets\protocol.py", line 827, in transfer_data
  File "websockets\protocol.py", line 895, in read_message
  File "websockets\protocol.py", line 995, in read_data_frame
  File "websockets\protocol.py", line 766, in pong
  File "websockets\protocol.py", line 803, in ensure_open
websockets.exceptions.ConnectionClosedError: code = 1006 (connection closed abnormally [internal]), no reason

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\a\chia-blockchain\chia-blockchain\venv\Lib\site-packages\chia\daemon\server.py", line 187, in safe_handle
  File "websockets\protocol.py", line 555, in send
  File "websockets\protocol.py", line 803, in ensure_open
websockets.exceptions.ConnectionClosedError: code = 1006 (connection closed abnormally [internal]), no reason

**Comment by lpaln** [comment]
I just want to add this is not related to plotting as stated above. I finished my plotting quite some time ago and did not use the GUI for plotting. This is occuring randomly while farming. I check the machine roughly daily and several times I have logged in over the last couple months to find chia completely shutdown. I analyzed the logs this time and these are the lines right before the client closes.

**Comment by Aidan24** [comment]
Fair comment. I have only noticed this since version 1.20 and have been doing quite a bit of NFT replotting since then so probably haven't left it running long without plotting. However I would say that for me, it seems to get messed up very quickly. For example I rebooted this morning and installed 1.22 then began plotting and farming and (at least from the look of the GUI) it is completely messed up already. See timestamps of proofs and order of challenges below:
![image](https://user-images.githubusercontent.com/41297044/125802904-c8d0d2a4-e96d-4545-8696-102b0fa54b18.png)
Also Pooling is also showing zero points in the last hour:
![image](https://user-images.githubusercontent.com/41297044/125803185-9c464653-af0c-43c6-a377-9df48fcd5839.png)

**Comment by lpaln** [comment]
Just trying to keep this thread in track. Lots of stuff can go wrong when pushing hardware to the max plotting. This is not the case here though. This machine is doing almost nothing and this crash occurs.  All of my challenges are coming at regular intervals.

**Comment by Aidan24** [comment]
I'm not pushing this machine as hard as I used to with pre version 1.20 plotting. Nothing is showing max: 
![image](https://user-images.githubusercontent.com/41297044/125806018-6d163a81-00e3-4810-b4b3-05501b03172b.png)
Although I haven't run it today, I've previously been able to run 4k video editing at the same time as plotting with higher setting than this, and nothing got messed up. (That was pre-NFT plotting). Machine is i9 (18 physical cores) 128GB RAM and nothing is using 100% disk capacity.

Have you had the issues with 1.1.7 and before? I hadn't noticed them, but it's possible this has always been an issue, or that there are 2 different issues.

**Comment by lpaln** [comment]
I can't say exactly when this started, but looking back at logs it seems that it has been present for at least the last 2 versions. The link I posted in the OP above shows the same exact log entries on a Linux system from the first week of June.
