### ISSUE TITLE
Error while trying to fetch from peer:ValidationError(<Err.INVALID_PLOT_SIGNATURE: 28>) 

### ISSUE THREAD

**Issue by egoncris** [Chia-Network/chia-blockchain#7516]
**Describe the bug**
MY WALLET DON'T SYNC

, I've done everything, I deleted the .chia folder and all the chia-blockchain, reinstalled everything from scratch, deleted all plots and that complicated everything... 4 days for sync full node, 2 hours for one plot...and now i need to sinc my wallet to show the MOJO and then have a contract with a pool, i don't know what else to do, i need help

**To Reproduce**
2021-07-15T22:53:56.523 wallet chia.wallet.wallet_node    : ERROR    Error while trying to fetch from peer:ValidationError(<Err.INVALID_PLOT_SIGNATURE: 28>) is not a valid Err Traceback (most recent call last):
  File "chia\wallet\wallet_node.py", line 527, in batch_sync_to_peak
  File "chia\wallet\wallet_node.py", line 728, in fetch_blocks_and_validate
  File "chia\wallet\wallet_blockchain.py", line 209, in receive_block
  File "C:\hostedtoolcache\windows\Python\3.9.5\x64\lib\enum.py", line 360, in __call__
  File "C:\hostedtoolcache\windows\Python\3.9.5\x64\lib\enum.py", line 678, in __new__
ValueError: ValidationError(<Err.INVALID_PLOT_SIGNATURE: 28>) is not a valid Err

2021-07-15T22:53:56.526 wallet chia.wallet.wallet_node    : ERROR    Loop exception in sync Was not able to add blocks 66732-66764. Traceback (most recent call last):
  File "chia\wallet\wallet_node.py", line 580, in sync_job
  File "chia\wallet\wallet_node.py", line 660, in _sync
  File "chia\wallet\wallet_node.py", line 537, in batch_sync_to_peak
RuntimeError: Was not able to add blocks 66732-66764

**Expected behavior**

**Screenshots**
![WALLET](https://user-images.githubusercontent.com/87457856/125725401-f4e31829-b9a7-4ab4-8ce0-e9b910b39e6c.PNG)
![PLOTS](https://user-images.githubusercontent.com/87457856/125725422-cc47868b-84d5-45c5-9135-7ebdf20d4bd5.PNG)
![FARM](https://user-images.githubusercontent.com/87457856/125725435-7d63ce5b-7332-4448-b901-b9c7c10f4506.PNG)
![FULLNODE](https://user-images.githubusercontent.com/87457856/125725444-b600703e-7d4a-48d0-b202-8ce2119e07ed.PNG)

**Desktop**
![HARDWARE](https://user-images.githubusercontent.com/87457856/125725886-b17bb449-34f3-4519-9a2d-f1ed267c7611.PNG)
![WINDOWS](https://user-images.githubusercontent.com/87457856/125725898-0318049e-6c94-404a-ac5c-db80121d9ff4.PNG)

**Additional context**

**Comment by egoncris** [comment]
nothing :(
