### ISSUE TITLE
[BUG] Permission denied when starting plotting for pool plots

### ISSUE THREAD

**Issue by michaelpalumbo** [Chia-Network/chia-blockchain#7537]
**Describe the bug**
Plot creation cannot write to directory, "permission denied". Have mounted drives with full permissions for all users, including using chmod 777. 

**To Reproduce**

```
chia plots create -n 10 -r 8 -c <omitted> -t /home/chia/mount/plotting/plots -d /home/chia/mount/2TB_1 -f <omitted> -e
2021-07-15T17:15:00.229  chia.plotting.create_plots       : INFO     Creating 10 plots of size 32, pool contract address:  <omitted> farmer public key: <omitted>
2021-07-15T17:15:00.234  chia.plotting.create_plots       : INFO     Memo: <omitted>
2021-07-15T17:15:00.234  chia.plotting.create_plots       : INFO     Starting plot 1/10

Starting plotting progress into temporary dirs: /home/chia/mount/plotting/plots and /home/chia/mount/plotting/plots
ID: <omitted>
Plot size is: 32
Buffer size is: 3389MiB
Using 128 buckets
Final Directory is: /home/chia/mount/2TB_1
Using 8 threads of stripe size 65536
Process ID is: 1161
Caught plotting error: Could not open /home/chia/mount/plotting/plots/plot-k32-2021-07-15-17-15-2c8a1a90b4d948a718cba64447ada17a79f162a873ef6a8094628e2cf3116cd5.plot.sort.tmp: Permission denied.
Traceback (most recent call last):
  File "/home/chia/chia-blockchain/venv/bin/chia", line 33, in <module>
    sys.exit(load_entry_point('chia-blockchain', 'console_scripts', 'chia')())
  File "/home/chia/chia-blockchain/chia/cmds/chia.py", line 79, in main
    cli()  # pylint: disable=no-value-for-parameter
  File "/home/chia/chia-blockchain/venv/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/chia/chia-blockchain/venv/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/chia/chia-blockchain/venv/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/chia/chia-blockchain/venv/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/chia/chia-blockchain/venv/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/chia/chia-blockchain/venv/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/chia/chia-blockchain/venv/lib/python3.8/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/chia/chia-blockchain/chia/cmds/plots.py", line 135, in create_cmd
    create_plots(Params(), ctx.obj["root_path"])
  File "/home/chia/chia-blockchain/chia/plotting/create_plots.py", line 168, in create_plots
    plotter.create_plot_disk(
RuntimeError: std::exception
```

**Expected behavior**
That my machine begins to create pool plots. 

**Screenshots**
n/a

**Desktop**
- OS: Ubuntu Server 20 LTS
- CPU: AMD Ryzen 3800
**Additional context**

**Comment by michaelpalumbo** [comment]
Ah i found the issue. Simple really, needed to go up one level in the path by prepending a *../* to both the plot and dest directories because I was working from the /chia-blockchain folder.
