### ISSUE TITLE
[BUG] AttributeError: 'FullNode' object has no attribute 'blockchain'

### ISSUE THREAD

**Issue by seanvetter** [Chia-Network/chia-blockchain#7553]
**To Reproduce**
OS Version: Freebsd 12.2 Release P9
Built From source following wiki guide, using python3.8 instead of 3.7 and clvm_rs 0.1.8
Chia version: Latest - 1.2.3.dev0

**Expected behavior**
Probably shouldn't have a traceback why trying to stop the full node

**Screenshots**
```
(venv) [root@chia ~/chia-1.2.2/chia-blockchain]# chia start farmer -r
chia_harvester: stopped
chia_harvester: started
chia_farmer: stopped
chia_farmer: started
chia_full_node: Traceback (most recent call last):
  File "/root/chia-1.2.2/chia-blockchain/venv/bin/chia_full_node", line 33, in <module>
    sys.exit(load_entry_point('chia-blockchain', 'console_scripts', 'chia_full_node')())
  File "/root/chia-1.2.2/chia-blockchain/chia/server/start_full_node.py", line 60, in main
    return run_service(**kwargs)
  File "/root/chia-1.2.2/chia-blockchain/chia/server/start_service.py", line 255, in run_service
    return asyncio.run(async_run_service(*args, **kwargs))
  File "/usr/local/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/local/lib/python3.8/asyncio/base_events.py", line 603, in run_until_complete
    self.run_forever()
  File "/usr/local/lib/python3.8/asyncio/base_events.py", line 570, in run_forever
    self._run_once()
  File "/usr/local/lib/python3.8/asyncio/base_events.py", line 1823, in _run_once
    event_list = self._selector.select(timeout)
  File "/usr/local/lib/python3.8/selectors.py", line 558, in select
    kev_list = self._selector.control(None, max_ev, timeout)
  File "/root/chia-1.2.2/chia-blockchain/chia/server/start_service.py", line 193, in _accept_signal
    self.stop()
  File "/root/chia-1.2.2/chia-blockchain/chia/server/start_service.py", line 210, in stop
    self._node._close()
  File "/root/chia-1.2.2/chia-blockchain/chia/full_node/full_node.py", line 561, in _close
    if self.blockchain is not None:
AttributeError: 'FullNode' object has no attribute 'blockchain'
stopped
chia_full_node: started
chia_wallet: stopped
chia_wallet: started
```

Rebuilt after updating my jails and had to make some changes to dependencies. When I did a restart of the farmer services I got this traceback but it seemed to stopped even with the failure and restart correctly. After the restart farming has continued and node is synced. Just the traceback when stopping is the problem it seems.

**Comment by maxpierpont** [comment]
it happens to me too since 1.2+ update . i just run a script with 'chia start farmer' on each system reboot, and most times full node won't start normally, so i have to restart it manually and see "AttributeError: 'FullNode' object has no attribute 'blockchain'" message upon restarting... tried to redownload and rebuild, same behavouir. system is clean ubuntu 20.04 under esxi 6.7

**Comment by urgor** [comment]
Same issue at
Ubuntu 20.04.2 LTS (Focal Fossa)
Chia ver.1.2.2

**Comment by ohadcn** [comment]
had similar problem
running `sh install.sh` again and restarting the node seems to solve the problem, let's hope this will hold for time

**Comment by fostro** [comment]
Seeing the same issue on Arch Linux with Chia v 1.2.3.

**Comment by stasmikhalych** [comment]
The same bug. Chia v. 1.2.3
Ubuntu Ubuntu 20.04.2 LTS.

Acording to this report first time this BUG was almost months ago. Still no solutions ??

**Comment by emlowe** [comment]
I don't believe this has any serious impact as the node will still shutdown - but it is a little messy
