### ISSUE TITLE
 Log show warning  :WARNING Sending data failed. Exception Traceback (most recent call last)

### ISSUE THREAD

**Issue by rjacobs022** [Chia-Network/chia-blockchain#7576]
Please help!

I noticed I proofs found but have not won any reward. When checking the logs I noticed the below warning, 

**2021-07-16T18:17:03.975 harvester chia.harvester.harvester: INFO     4 plots were eligible for farming.  Found 1 proofs. Time: 0.71858 s. Total 761 plots
2021-07-16T18:17:03.975 farmer chia.rpc.rpc_server        : WARNING  Sending data failed. Exception Traceback (most recent call last):
  File "chia\rpc\rpc_server.py", line 67, in _state_changed
  File "aiohttp\client_ws.py", line 150, in send_str
  File "aiohttp\http_websocket.py", line 687, in send
  File "aiohttp\http_websocket.py", line 643, in _send_frame
  File "aiohttp\http_websocket.py", line 660, in _write
ConnectionResetError: Cannot write to closing transport**

Is something wrong? How do I fix this?

**Comment by hoffmang9** [comment]
Nothing is wrong - a peer you were connected to disconnecte.d

**Comment by Robert-The-Sandwitch** [comment]
Is it still normal if you get this warning every few minutes?

**Comment by TechAddict000** [comment]
This issue is still active - and has other threads - #7832. @hoffmang9 This issue is causing issues with my sync. Please help - it's not just a disconnect
