### ISSUE TITLE
[BUG] synchronization does not start

### ISSUE THREAD

**Issue by kadirguloglu** [Chia-Network/chia-blockchain#7592]
synchronization does not start. I opened port 8444 from the modem interface and controlled it with port checker. computer date time is automatic and accurate. I'm running as administrator and all permissions are given to everyone on chia and all other folders. my internet connection is 100 mbps and uninterrupted (corporate connection). Chia version 1.2.2.
 
- OS: Windows
- OS Version/Flavor: 
Edisyon	Windows 10 Home
Sürüm	20H2
Yüklenme tarihi	‎10.‎06.‎2021
İS derlemesi	19042.1110
Deneyim	Windows Feature Experience Pack 120.2212.3530.0

- CPU: 
İşlemci	AMD Ryzen Threadripper 3960X 24-Core Processor    3.90 GHz
Takılı RAM	64,0 GB (kullanılabilir: 63,9 GB)
Cihaz Kimliği	58272A99-5D27-4922-8F40-FE879A9B894D
Sistem türü	64 bit işletim sistemi, x64 tabanlı işlemci

debug.log file 
2021-07-17T14:01:33.913 daemon __main__                   : INFO     sending CTRL_BREAK_EVENT signal to chia_harvester
2021-07-17T14:01:33.915 daemon __main__                   : INFO     sending CTRL_BREAK_EVENT signal to chia_full_node
2021-07-17T14:01:33.916 daemon __main__                   : INFO     sending CTRL_BREAK_EVENT signal to chia_wallet
2021-07-17T14:01:33.917 daemon __main__                   : INFO     sending CTRL_BREAK_EVENT signal to chia_farmer
2021-07-17T14:01:33.917 wallet wallet                     : INFO     got signal 21
2021-07-17T14:01:33.918 wallet wallet                     : INFO     Cancelling reconnect task
2021-07-17T14:01:33.919 wallet wallet                     : INFO     Closing connections
2021-07-17T14:01:33.919 wallet chia.wallet.wallet_node    : INFO     self._close
2021-07-17T14:01:33.920 wallet wallet                     : INFO     Calling service stop callback
2021-07-17T14:01:33.921 wallet wallet                     : INFO     Closing RPC server
2021-07-17T14:01:33.921 wallet wallet                     : INFO     Waiting for socket to be closed (if opened)
2021-07-17T14:01:33.922 wallet wallet                     : INFO     Waiting for ChiaServer to be closed
2021-07-17T14:01:33.916 full_node full_node               : INFO     got signal 21
2021-07-17T14:01:34.927 full_node full_node               : INFO     Cancelling reconnect task
2021-07-17T14:01:34.927 full_node chia.server.upnp        : INFO     UPnP, releasing port 8444
2021-07-17T14:01:34.928 full_node full_node               : INFO     Closing connections
2021-07-17T14:01:34.929 full_node full_node               : INFO     Calling service stop callback
2021-07-17T14:01:34.930 full_node full_node               : INFO     Closing RPC server
2021-07-17T14:01:34.930 full_node full_node               : INFO     Waiting for socket to be closed (if opened)
2021-07-17T14:01:34.931 full_node full_node               : INFO     Waiting for ChiaServer to be closed
2021-07-17T14:01:34.935 full_node full_node_server        : INFO     Connection closed: 127.0.0.1, node id: f125a6569136130121918b84961af3ab99a836f097ef46706b3a659631e6ed7f
2021-07-17T14:01:34.936 full_node chia.full_node.full_node: INFO     peer disconnected {'host': '127.0.0.1', 'port': 8447}
2021-07-17T14:01:34.937 full_node full_node_server        : INFO     Connection closed: 127.0.0.1, node id: 8de38ef87d3ad3a4cf4df90842ab5cd9251c26f409e4ff83af940e53b733efae
2021-07-17T14:01:34.937 full_node chia.full_node.full_node: INFO     peer disconnected {'host': '127.0.0.1', 'port': 8449}
2021-07-17T14:01:34.939 full_node full_node               : INFO     Waiting for RPC server
2021-07-17T14:01:34.946 full_node chia.server.upnp        : INFO     UPnP, Port 8444 closed
2021-07-17T14:01:34.936 wallet wallet_server              : INFO     Connection closed: 127.0.0.1, node id: 9d5c440b5ad5dbd3b77bdc0841ae26888673fef5ff5c4bc6577e27efda7aa4b3
2021-07-17T14:01:35.940 wallet wallet                     : INFO     Waiting for RPC server
2021-07-17T14:01:35.941 wallet wallet                     : INFO     Closed RPC server
2021-07-17T14:01:35.942 wallet wallet                     : INFO     Waiting for service _await_closed callback
2021-07-17T14:01:35.942 wallet chia.wallet.wallet_node    : INFO     self._await_closed
2021-07-17T14:01:35.944 wallet wallet                     : INFO     Service wallet at port 8449 fully closed
2021-07-17T14:01:36.444 daemon __main__                   : INFO     process chia_wallet returned 0
2021-07-17T14:01:33.918 farmer farmer                     : INFO     got signal 21
2021-07-17T14:01:36.951 full_node full_node               : INFO     Closed RPC server
2021-07-17T14:01:36.952 full_node full_node               : INFO     Waiting for service _await_closed callback
2021-07-17T14:01:36.953 full_node chia.server.upnp        : INFO     UPnP, shutting down thread
2021-07-17T14:01:36.954 full_node full_node               : INFO     Service full_node at port 8444 fully closed
2021-07-17T14:01:37.458 daemon __main__                   : INFO     process chia_full_node returned 0
2021-07-17T14:01:33.915 harvester harvester               : INFO     got signal 21
2021-07-17T14:01:37.965 harvester harvester               : INFO     Cancelling reconnect task
2021-07-17T14:01:37.966 harvester harvester               : INFO     Closing connections
2021-07-17T14:01:37.966 harvester harvester               : INFO     Calling service stop callback
2021-07-17T14:01:37.967 harvester harvester               : INFO     Closing RPC server
2021-07-17T14:01:37.968 harvester harvester               : INFO     Waiting for socket to be closed (if opened)
2021-07-17T14:01:37.968 harvester harvester               : INFO     Waiting for ChiaServer to be closed
2021-07-17T14:01:36.951 farmer farmer                     : INFO     Cancelling reconnect task
2021-07-17T14:01:38.979 farmer farmer                     : INFO     Closing connections
2021-07-17T14:01:38.980 farmer farmer                     : INFO     Calling service stop callback
2021-07-17T14:01:38.981 farmer farmer                     : INFO     Closing RPC server
2021-07-17T14:01:38.981 farmer farmer                     : INFO     Waiting for socket to be closed (if opened)
2021-07-17T14:01:38.982 farmer farmer                     : INFO     Waiting for ChiaServer to be closed
2021-07-17T14:01:38.984 farmer farmer_server              : INFO     Connection closed: 127.0.0.1, node id: 10dd7caeb6f811dc047a2b6c5145816a0340fd9a5b54c7c9786ef93103cc254c
2021-07-17T14:01:38.984 harvester harvester_server        : INFO     Connection closed: 127.0.0.1, node id: b728685e58e59879c297c0b3baa238b3d348ceb26c1d835a7187528af4da6187
2021-07-17T14:01:38.985 harvester chia.harvester.harvester: INFO     peer disconnected {'host': '127.0.0.1', 'port': 8447}
2021-07-17T14:01:38.986 harvester harvester               : INFO     Waiting for RPC server
2021-07-17T14:01:47.863 daemon __main__                   : INFO     Starting Daemon Server
2021-07-17T14:01:47.863 daemon __main__                   : INFO     Not implemented
2021-07-17T14:01:47.869 daemon __main__                   : INFO     Waiting Daemon WebSocketServer closure
2021-07-17T14:01:48.563 daemon __main__                   : INFO     Register service {'service': 'wallet_ui'}
2021-07-17T14:01:48.564 daemon __main__                   : INFO     registered for service wallet_ui
2021-07-17T14:01:48.565 daemon __main__                   : INFO     {'success': True}
2021-07-17T14:01:48.566 daemon __main__                   : INFO     Register service {'service': 'chia plots create'}
2021-07-17T14:01:48.567 daemon __main__                   : INFO     registered for service chia plots create
2021-07-17T14:01:48.567 daemon __main__                   : INFO     {'success': True, 'service': 'chia plots create', 'queue': []}
2021-07-17T14:01:49.505 full_node chia.full_node.full_node: INFO     Initializing blockchain from disk
2021-07-17T14:01:49.507 full_node chia.consensus.blockchain: INFO     Started 22 processes for block validation
2021-07-17T14:01:49.509 full_node chia.full_node.full_node: INFO     Initialized with empty blockchain time taken: 0s
2021-07-17T14:01:49.515 full_node full_node_server        : INFO     Started listening on port: 8444
2021-07-17T14:01:49.515 full_node full_node               : INFO     Started full_node service on network_id: mainnet
2021-07-17T14:01:49.528 daemon __main__                   : INFO     Register service {'service': 'chia_full_node'}
2021-07-17T14:01:49.529 daemon __main__                   : INFO     registered for service chia_full_node
2021-07-17T14:01:49.529 daemon __main__                   : INFO     {'success': True}
2021-07-17T14:01:49.552 harvester harvester               : INFO     Started harvester service on network_id: mainnet
2021-07-17T14:01:49.553 harvester harvester               : INFO     Reconnecting to peer {'host': '127.0.0.1', 'port': 8447}
2021-07-17T14:01:49.568 daemon __main__                   : INFO     Register service {'service': 'chia_harvester'}
2021-07-17T14:01:49.568 daemon __main__                   : INFO     registered for service chia_harvester
2021-07-17T14:01:49.569 daemon __main__                   : INFO     {'success': True}
2021-07-17T14:01:49.649 farmer farmer_server              : INFO     Started listening on port: 8447
2021-07-17T14:01:49.652 farmer farmer                     : INFO     Started farmer service on network_id: mainnet
2021-07-17T14:01:49.653 farmer farmer                     : INFO     Reconnecting to peer {'host': '127.0.0.1', 'port': 8444}
2021-07-17T14:01:49.667 daemon __main__                   : INFO     Register service {'service': 'chia_farmer'}
2021-07-17T14:01:49.668 daemon __main__                   : INFO     registered for service chia_farmer
2021-07-17T14:01:49.669 daemon __main__                   : INFO     {'success': True}
2021-07-17T14:01:49.529 wallet chia.wallet.wallet_blockchain: INFO     Started 22 processes for block validation
2021-07-17T14:01:50.533 wallet wallet                     : INFO     Started wallet service on network_id: mainnet
2021-07-17T14:01:50.539 wallet chia.wallet.wallet_node    : INFO     Loop start in sync job
2021-07-17T14:01:50.540 wallet wallet                     : INFO     Reconnecting to peer {'host': '127.0.0.1', 'port': 8444}
2021-07-17T14:01:50.551 full_node chia.server.upnp        : INFO     Attempting to enable UPnP (open up port 8444)
2021-07-17T14:01:50.557 full_node chia.server.upnp        : INFO     Removal of previous portmapping failed. This does not indicate an error: NoSuchEntryInArray
2021-07-17T14:01:50.558 daemon __main__                   : INFO     Register service {'service': 'chia_wallet'}
2021-07-17T14:01:50.559 daemon __main__                   : INFO     registered for service chia_wallet
2021-07-17T14:01:50.560 daemon __main__                   : INFO     {'success': True}
2021-07-17T14:01:50.582 full_node chia.server.upnp        : INFO     Port 8444 opened with UPnP. lanaddr 192.168.2.96 external: 78.181.82.149
2021-07-17T14:01:49.667 farmer farmer_server              : INFO     Connected with full_node {'host': '127.0.0.1', 'port': 8444}
2021-07-17T14:01:50.681 harvester harvester_server        : INFO     Connected with farmer {'host': '127.0.0.1', 'port': 8447}
2021-07-17T14:01:50.723 harvester chia.plotting.plot_tools: INFO     Searching directories []
2021-07-17T14:01:50.724 harvester chia.plotting.plot_tools: INFO     Loaded a total of 0 plots of size 0.0 TiB, in 0.02609872817993164 seconds
2021-07-17T14:01:50.725 harvester chia.harvester.harvester: WARNING  Not farming any plots on this harvester. Check your configuration.
2021-07-17T14:01:50.558 wallet wallet_server              : INFO     Connected with full_node {'host': '127.0.0.1', 'port': 8444}
2021-07-17T14:01:53.770 wallet chia.wallet.wallet_node    : INFO     self._close
2021-07-17T14:01:53.771 wallet chia.wallet.wallet_node    : INFO     self._await_closed
2021-07-17T14:01:53.772 wallet wallet_server              : INFO     Connection closed: 127.0.0.1, node id: 9d5c440b5ad5dbd3b77bdc0841ae26888673fef5ff5c4bc6577e27efda7aa4b3
2021-07-17T14:01:53.813 wallet chia.wallet.wallet_blockchain: INFO     Started 22 processes for block validation
2021-07-17T14:01:53.816 wallet chia.wallet.wallet_node    : INFO     Loop start in sync job
2021-07-17T14:01:54.574 wallet wallet                     : INFO     Reconnecting to peer {'host': '127.0.0.1', 'port': 8444}
2021-07-17T14:01:53.772 full_node full_node_server        : INFO     Connection closed: 127.0.0.1, node id: 8de38ef87d3ad3a4cf4df90842ab5cd9251c26f409e4ff83af940e53b733efae
2021-07-17T14:01:54.781 full_node chia.full_node.full_node: INFO     peer disconnected {'host': '127.0.0.1', 'port': 8449}
2021-07-17T14:01:54.787 wallet wallet_server              : INFO     Connected with full_node {'host': '127.0.0.1', 'port': 8444}
2021-07-17T14:02:23.179 full_node chia.full_node.full_node: WARNING  querying DNS introducer failed: The DNS operation timed out after 32.027018785476685 seconds
2021-07-17T14:02:53.838 wallet chia.wallet.wallet_node    : INFO     Will not attempt to connect to other nodes, already connected to {'host': 'localhost', 'port': 8444}
2021-07-17T14:04:20.348 full_node chia.full_node.full_node: WARNING  querying DNS introducer failed: The DNS operation timed out after 32.00341868400574 seconds
2021-07-17T14:07:56.371 full_node chia.full_node.full_node: WARNING  querying DNS introducer failed: The DNS operation timed out after 32.02465891838074 seconds
2021-07-17T14:09:12.784 full_node full_node_server        : INFO     Cannot connect to host 45.56.122.189:8444 ssl:<ssl.SSLContext object at 0x00000197761982C0> [Semafor zaman aşımı süresi geçildi]
2021-07-17T14:09:12.785 full_node chia.rpc.rpc_server     : WARNING  Error while handling message: Traceback (most recent call last):
  File "chia\rpc\rpc_server.py", line 81, in inner
  File "chia\rpc\rpc_server.py", line 161, in open_connection
ValueError: Start client failed, or server is not set

add peers command line 1:
...\app-1.2.2\resources\app.asar.unpacked\daemon>.\chia.exe show -a 45.56.122.189:8444
Connecting to 45.56.122.189, 8444
Failed to connect to 45.56.122.189:8444

add peers command line 2:
...\app-1.2.2\resources\app.asar.unpacked\daemon>.\chia.exe show -a node.chia.net:8444
Connecting to node.chia.net, 8444
Failed to connect to node.chia.net:8444

**Comment by madrigo64** [comment]
Check if you have free space on drive where installed config folder of chia.  you should have min 20 GB free space for DB
try this  commands 
create file  peers.bat  and put this code

echo off
cd /d %LOCALAPPDATA%\chia-blockchain\app-1.2.2\resources\app.asar.unpacked\daemon


chia show -a node-apne.chia.net:8444

chia show -a introducer-apne.chia.net:8444

chia show -a introducer-apse.chia.net:8444

chia show -a introducer-or.chia.net:8444

chia show -a introducer-va.chia.net:8444

chia show -a introducer-eu.chia.net:8444

chia show -a chiadb.net:8444

chia show -a pyl.dk:8444

chia show -a node.chia.net:8444

chia show -a 81.83.5.50:8444

chia show -a 118.189.201.184:8444

chia show -a 63.86.188.28:8444

chia show -a 70.67.4.75:8444

chia show -a 159.28.171.166:8444

chia show -a 37.145.52.144:8444

chia show -a 123.57.42.226:8444

chia show -a 76.251.32.219:8444

chia show -a 70.224.19.232:8444

chia show -a 73.252.215.180:8444

chia show -a 205.134.173.77:8444


chia show -a 84.107.167.248:8444

chia show -a 86.57.236.161:8444

chia show -a 211.227.132.15:8444

chia show -a 72.39.161.212:8444

chia show -a 201.131.68.254:8444

chia show -a 90.222.8.93:8444

chia show -a 178.82.152.5:8444

chia show -a 24.24.132.82:8444

chia show -a 80.212.44.58:8444

chia show -a 37.193.78.56:8444

chia show -a 65.24.91.237:8444

**Comment by kadirguloglu** [comment]
> Check if you have free space on drive where installed config folder of chia. you should have min 20 GB free space for DB
> try this commands
> create file peers.bat and put this code (don't forget to check version of chia and change 1.2.2 to actually vesion)
> 
> echo off
> cd /d %LOCALAPPDATA%\chia-blockchain\app-1.2.2\resources\app.asar.unpacked\daemon
> 
> chia show -a node-apne.chia.net:8444
> 
> chia show -a introducer-apne.chia.net:8444
> 
> chia show -a introducer-apse.chia.net:8444
> 
> chia show -a introducer-or.chia.net:8444
> 
> chia show -a introducer-va.chia.net:8444
> 
> chia show -a introducer-eu.chia.net:8444
> 
> chia show -a chiadb.net:8444
> 
> chia show -a pyl.dk:8444
> 
> chia show -a node.chia.net:8444
> 
> chia show -a 81.83.5.50:8444
> 
> chia show -a 118.189.201.184:8444
> 
> chia show -a 63.86.188.28:8444
> 
> chia show -a 70.67.4.75:8444
> 
> chia show -a 159.28.171.166:8444
> 
> chia show -a 37.145.52.144:8444
> 
> chia show -a 123.57.42.226:8444
> 
> chia show -a 76.251.32.219:8444
> 
> chia show -a 70.224.19.232:8444
> 
> chia show -a 73.252.215.180:8444
> 
> chia show -a 205.134.173.77:8444
> 
> chia show -a 84.107.167.248:8444
> 
> chia show -a 86.57.236.161:8444
> 
> chia show -a 211.227.132.15:8444
> 
> chia show -a 72.39.161.212:8444
> 
> chia show -a 201.131.68.254:8444
> 
> chia show -a 90.222.8.93:8444
> 
> chia show -a 178.82.152.5:8444
> 
> chia show -a 24.24.132.82:8444
> 
> chia show -a 80.212.44.58:8444
> 
> chia show -a 37.193.78.56:8444
> 
> chia show -a 65.24.91.237:8444

**Comment by kadirguloglu** [comment]
> Check if you have free space on drive where installed config folder of chia. you should have min 20 GB free space for DB
> try this commands
> create file peers.bat and put this code (don't forget to check version of chia and change 1.2.2 to actually vesion)
> 
> echo off
> cd /d %LOCALAPPDATA%\chia-blockchain\app-1.2.2\resources\app.asar.unpacked\daemon
> 
> chia show -a node-apne.chia.net:8444
> 
> chia show -a introducer-apne.chia.net:8444
> 
> chia show -a introducer-apse.chia.net:8444
> 
> chia show -a introducer-or.chia.net:8444
> 
> chia show -a introducer-va.chia.net:8444
> 
> chia show -a introducer-eu.chia.net:8444
> 
> chia show -a chiadb.net:8444
> 
> chia show -a pyl.dk:8444
> 
> chia show -a node.chia.net:8444
> 
> chia show -a 81.83.5.50:8444
> 
> chia show -a 118.189.201.184:8444
> 
> chia show -a 63.86.188.28:8444
> 
> chia show -a 70.67.4.75:8444
> 
> chia show -a 159.28.171.166:8444
> 
> chia show -a 37.145.52.144:8444
> 
> chia show -a 123.57.42.226:8444
> 
> chia show -a 76.251.32.219:8444
> 
> chia show -a 70.224.19.232:8444
> 
> chia show -a 73.252.215.180:8444
> 
> chia show -a 205.134.173.77:8444
> 
> chia show -a 84.107.167.248:8444
> 
> chia show -a 86.57.236.161:8444
> 
> chia show -a 211.227.132.15:8444
> 
> chia show -a 72.39.161.212:8444
> 
> chia show -a 201.131.68.254:8444
> 
> chia show -a 90.222.8.93:8444
> 
> chia show -a 178.82.152.5:8444
> 
> chia show -a 24.24.132.82:8444
> 
> chia show -a 80.212.44.58:8444
> 
> chia show -a 37.193.78.56:8444
> 
> chia show -a 65.24.91.237:8444

I have 200GB of Free space. I did what you said. unsuccessful :(
