### ISSUE TITLE
Can not change my alais

### ISSUE THREAD

**Issue by 1801S** [Chia-Network/chia-blockchain#7612]
C:\Users\popov\AppData\Local\chia-blockchain\app-1.2.1\resources\app.asar.unpacked\daemon>.\chia plotnft get_login_link -l "Sasha"
Traceback (most recent call last):
  File "D:\a\chia-blockchain\chia-blockchain\venv\Lib\site-packages\chia\cmds\chia.py", line 83, in <module>
  File "D:\a\chia-blockchain\chia-blockchain\venv\Lib\site-packages\chia\cmds\chia.py", line 79, in main
  File "click\core.py", line 829, in __call__
  File "click\core.py", line 782, in main
  File "click\core.py", line 1259, in invoke
  File "click\core.py", line 1259, in invoke
  File "click\core.py", line 1066, in invoke
  File "click\core.py", line 610, in invoke
  File "chia\cmds\plotnft.py", line 35, in get_login_link_cmd
  File "asyncio\runners.py", line 44, in run
  File "asyncio\base_events.py", line 642, in run_until_complete
  File "chia\cmds\plotnft_funcs.py", line 217, in get_login_link
  File "chia\util\byte_types.py", line 11, in hexstr_to_bytes
ValueError: non-hexadecimal number found in fromhex() arg at position 0
[1628] Failed to execute script chia

**Comment by gryan315** [comment]
Are you using a pool that supports this function?

**Comment by hoffmang9** [comment]
This is not supported yet.
