### ISSUE TITLE
[BUG] Traceback and [Errno -2] Name or service not known

### ISSUE THREAD

**Issue by ViperGuyMike** [Chia-Network/chia-blockchain#7622]
This is my first attempt to create a harvester. I installed Ubuntu 20.04 on my server, then installed Chia. I ran "chia init" and added my keys with "chia keys add". I then installed my "ca" folder from my farmer and ran "chia init -c" with the location of my "ca" folder, and got the notification that my ca was copied and generated the TLS certs. Now, when I run 'chia start harvester', I get 'Chia harvester: started', immediately followed by:

  Traceback (most recent call last):
  File "/home/troubles/chia-blockchain/venv/bin/chia_harvester", line 33, in <module>
    sys.exit(load_entry_point('chia-blockchain', 'console_scripts', 'chia_harvester')())
  File "/home/troubles/chia-blockchain/chia/server/start_harvester.py", line 53, in main
    return run_service(**kwargs)
  File "/home/troubles/chia-blockchain/chia/server/start_service.py", line 255, in run_service
    return asyncio.run(async_run_service(*args, **kwargs))
  File "/usr/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/troubles/chia-blockchain/chia/server/start_service.py", line 249, in async_run_service
    return await service.run()
  File "/home/troubles/chia-blockchain/chia/server/start_service.py", line 171, in run
    await self.start()
  File "/home/troubles/chia-blockchain/chia/server/start_service.py", line 145, in start
    self._reconnect_tasks = [
  File "/home/troubles/chia-blockchain/chia/server/start_service.py", line 146, in <listcomp>
    start_reconnect_task(self._server, _, self._log, self._auth_connect_peers) for _ in self._connect_peers
  File "/home/troubles/chia-blockchain/chia/server/reconnect_task.py", line 12, in start_reconnect_task
    peer_info = PeerInfo(socket.gethostbyname(peer_info_arg.host), peer_info_arg.port)
socket.gaierror: [Errno -2] Name or service not known

**Comment by ViperGuyMike** [comment]
Okay, so the issue was that my harvester "host:" in my config.yaml included "ip-" before the actual ip address. So it looked like "host: ip-192.168.1.1" and I had to change it to "host: 192.168.1.1" and it is now working. I hope this helps someone else out in the future.
