### ISSUE TITLE
[BUG] Missing resolv.conf

### ISSUE THREAD

**Issue by GreatApo** [Chia-Network/chia-blockchain#7647]
**Describe the bug**
I got the following error while trying to run `chia start wallet -r` on my Pi 4:

````
Traceback (most recent call last):
  File "/home/pi/chia-blockchain/venv/lib/python3.7/site-packages/dns/resolver.py", line 782, in read_resolv_conf
    f = stack.enter_context(open(f))
FileNotFoundError: [Errno 2] No such file or directory: '/etc/resolv.conf'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/chia-blockchain/venv/bin/chia_wallet", line 33, in <module>
    sys.exit(load_entry_point('chia-blockchain', 'console_scripts', 'chia_wallet')())
  File "/home/pi/chia-blockchain/chia/server/start_wallet.py", line 92, in main
    return run_service(**kwargs)
  File "/home/pi/chia-blockchain/chia/server/start_service.py", line 226, in run_service
    return asyncio.run(async_run_service(*args, **kwargs))
  File "/usr/lib/python3.7/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.7/asyncio/base_events.py", line 584, in run_until_complete
    return future.result()
  File "/home/pi/chia-blockchain/chia/server/start_service.py", line 219, in async_run_service
    service = Service(*args, **kwargs)
  File "/home/pi/chia-blockchain/chia/server/start_service.py", line 93, in __init__
    f(self._server)
  File "/home/pi/chia-blockchain/chia/wallet/wallet_node.py", line 317, in set_server
    self.log,
  File "/home/pi/chia-blockchain/chia/server/node_discovery.py", line 645, in __init__
    log,
  File "/home/pi/chia-blockchain/chia/server/node_discovery.py", line 66, in __init__
    self.resolver = dns.asyncresolver.Resolver()
  File "/home/pi/chia-blockchain/venv/lib/python3.7/site-packages/dns/resolver.py", line 734, in __init__
    self.read_resolv_conf(filename)
  File "/home/pi/chia-blockchain/venv/lib/python3.7/site-packages/dns/resolver.py", line 785, in read_resolv_conf
    raise NoResolverConfiguration
dns.resolver.NoResolverConfiguration: Resolver configuration could not be read or specified no nameservers.
````

**To Reproduce**
Delete `resolv.conf`

**Expected behavior**
Not to crash.

**Desktop**
OS: Debian GNU/Linux 10 (buster)
OS Version/Flavor: 10
CPU: BCM2835

**Additional context**
I think `resolv.conf` is not necessary on linux systems. For anyone encountering this error, in my case the file is under `/var/run/dnsmasq/`, thus I had to edit `/home/pi/chia-blockchain/venv/lib/python3.7/site-packages/dns/resolver.py`.
![image](https://user-images.githubusercontent.com/9620510/126239906-578122a7-839a-4592-bfbb-83bfe0f57f70.png)

**Comment by sargonas** [comment]
While I agree with you that the core chia code should not fail out if there is no resolv.conf file, this problem doesn't stem from Chia, but from Python. Unfortunately we can't solve for that requirement here on our side but is worth raising with Python developers, unless they have chosen to include this requirement for a reason (and given the deliberate way the error messages indicate the issue, I'm led to think this was an intentional choice by them.)
