### ISSUE TITLE
[BUG]node sync crash!

### ISSUE THREAD

**Issue by maybeTomorrow** [Chia-Network/chia-blockchain#7808]
**Describe the bug**
full node <defunct>

2021-07-27T12:22:58.269 full_node asyncio                 : ERROR    Task exception was never retrieved
future: <Task finished coro=<ChiaServer.incoming_api_task.<locals>.api_call() done, defined at /data/chia/chia-blockchain/chia/server/server.py:489> exception=CancelledError()>
concurrent.futures._base.CancelledError

**To Reproduce**

when node synced,start wallet.then got error

 
 
 CentOS 7.4
 chia v1.2.3

wallet log
2021-07-27T14:42:15.319 wallet chia.wallet.wallet_node    : INFO     Have collected 1 potential peaks
2021-07-27T14:42:15.320 wallet chia.wallet.wallet_node    : INFO     Requesting blocks 0-32
2021-07-27T14:42:15.321 wallet wallet_server              : DEBUG    -> request_header_blocks to peer 127.0.0.1 d2303df58ee5df7099a7b0af3905817b985bc88d9550803c04678d29173838e2
2021-07-27T14:42:34.148 wallet wallet_server              : DEBUG    Inbound_handler task cancelled
2021-07-27T14:42:34.181 wallet wallet_server              : INFO     Connection closed: 127.0.0.1, node id: d2303df58ee5df7099a7b0af3905817b985bc88d9550803c04678d29173838e2
2021-07-27T14:42:34.182 wallet wallet_server              : DEBUG    Time for request request_header_blocks: None = 18.861478805541992, None? True
2021-07-27T14:42:34.182 wallet chia.wallet.wallet_node    : ERROR    Error while trying to fetch from peer:Peer returned no response Traceback (most recent call last):
  File "/data/chia/chia-blockchain/chia/wallet/wallet_node.py", line 528, in batch_sync_to_peak
  File "/data/chia/chia-blockchain/chia/wallet/wallet_node.py", line 679, in fetch_blocks_and_validate
2021-07-27T14:42:34.182 wallet chia.wallet.wallet_node    : ERROR    Loop exception in sync Was not able to add blocks 0-32. Traceback (most recent call last):
  File "/data/chia/chia-blockchain/chia/wallet/wallet_node.py", line 580, in sync_job
  File "/data/chia/chia-blockchain/chia/wallet/wallet_node.py", line 660, in _sync
  File "/data/chia/chia-blockchain/chia/wallet/wallet_node.py", line 537, in batch_sync_to_peak

**Comment by keliew** [comment]
try `chia wallet show`, `s`kip, then `chia start -r farmer`

**Comment by maybeTomorrow** [comment]
> try `chia wallet show`, `s`kip, then `chia start -r farmer`

i have try restart many times

node log:
2021-07-28T10:38:52.658 full_node full_node_server        : ERROR    Exception:  <class 'concurrent.futures._base.CancelledError'>, closing connection {'host': '127.0.0.1', 'port': 8449}. Traceback (most recent call last):
  File "/data/chia/chia-blockchain/chia/server/server.py", line 538, in api_call
    response: Optional[Message] = await asyncio.wait_for(wrapped_coroutine(), timeout=timeout)
  File "/usr/local/lib/python3.7/asyncio/tasks.py", line 435, in wait_for
    await waiter
concurrent.futures._base.CancelledError

2021-07-28T10:39:21.960 full_node full_node_server        : ERROR    Exception: A child process terminated abruptly, the process pool is not usable anymore, {'host': '93.99.228.96', 'port': 8444}. Traceback (most recent call last):
  File "/data/chia/chia-blockchain/chia/server/server.py", line 528, in wrapped_coroutine
    result = await coroutine
  File "/data/chia/chia-blockchain/chia/full_node/full_node_api.py", line 229, in respond_transaction
    await self.full_node.respond_transaction(tx.transaction, spend_name, peer, test)
  File "/data/chia/chia-blockchain/chia/full_node/full_node.py", line 1644, in respond_transaction
    raise e
  File "/data/chia/chia-blockchain/chia/full_node/full_node.py", line 1641, in respond_transaction
    cost_result = await self.mempool_manager.pre_validate_spendbundle(transaction)
  File "/data/chia/chia-blockchain/chia/full_node/mempool_manager.py", line 222, in pre_validate_spendbundle
    self.constants.COST_PER_BYTE,
  File "/usr/local/lib/python3.7/asyncio/base_events.py", line 755, in run_in_executor
    executor.submit(func, *args), loop=self)
  File "/usr/local/lib/python3.7/concurrent/futures/process.py", line 625, in submit
    raise BrokenProcessPool(self._broken)
concurrent.futures.process.BrokenProcessPool: A child process terminated abruptly, the process pool is not usable anymore

**Comment by keliew** [comment]
turn on `DEBUG` and try catching/greping before and after `concurrent.futures.process.BrokenProcessPool: A child process terminated abruptly, the process pool is not usable anymore`
