### ISSUE TITLE
[BUG] Opening a wallet backup with a non ASCII character in the path fails

### ISSUE THREAD

**Issue by hoffmang9** [Chia-Network/chia-blockchain#782]
**Describe the bug**
The GUI hangs due to a problem with wallet backup using Beta 23.
```
`20:02:30.790 wallet src.rpc.rpc_server         : WARNING  Error while handling message: Traceback (most recent call last):
  File "src/rpc/rpc_server.py", line 207, in safe_handle
  File "src/rpc/rpc_server.py", line 198, in ws_api
  File "src/rpc/wallet_rpc_api.py", line 632, in get_backup_info
  File "src/wallet/util/backup_utils.py", line 49, in get_backup_info
  File "src/wallet/util/backup_utils.py", line 16, in open_backup_file
  File "pathlib.py", line 1236, in read_text
  File "/Users/runner/hostedtoolcache/Python/3.8.7/x64/lib/python3.8/encodings/ascii.py", line 26, in decode
UnicodeDecodeError: 'ascii' codec can't decode byte 0xf8 in position 26: ordinal not in range(128)
```

**Expected behavior**
Should handle any valid path character

**Screenshots**
![image](https://user-images.githubusercontent.com/30377676/106401038-be318680-63d6-11eb-9611-c273326c91e7.png)

**Desktop (please complete the following information):**

- OS: MacOS
- OS Version/Flavor: Big Sur
- CPU: NA

**Additional context**

**Comment by hoffmang9** [comment]
Need to reconfirm.
