### ISSUE TITLE
[SOLVED]:  Farmer taking a month to sync, updating only 17 blocks per second

### ISSUE THREAD

**Issue by Furious-George** [Chia-Network/chia-blockchain#7855]
I have plotted close to 3000 plots over the last few weeks.  Early on in the process I moved to a single farmer + 3 harvester setup, per the official documentation.

I installed the farmer node on a clean debian 10 vm, with 24 logical cores and 12 gb of ram.  CPU usage and load are low.

I am currently syncing about 17 blocks per minute, and still >10% from completion.  

```
chia show -s
Current Blockchain Status: Syncing 561225/637953.
```

After searching online and asking in Keybase, it does not appear that there's an easy answer for this.

I've tried forwarding port 8444 tcp/udp to my main node/farmer, as well as disabling upnp in config.yaml.  I can't tell if that might have slowed things down an additional 10% or so.

Looking at my logs, I don't see anything too unusual, other than the long pauses in the block update process following requests, followed by syncing multiple blocks per second for a short while,  followed  by another long pause:

```
2021-07-28T21:20:17.469 wallet chia.wallet.wallet_blockchain: INFO     💰 Updated wallet peak to height 561734, weight 429098928,
2021-07-28T21:20:45.616 full_node chia.full_node.full_node: INFO     Added blocks 561734 to 561766
2021-07-28T21:20:45.617 full_node chia.full_node.full_node: INFO     Requesting blocks: 561766 to 561798
2021-07-28T21:20:45.685 wallet chia.wallet.wallet_node    : INFO     Requesting blocks 561733-561765
2021-07-28T21:20:48.640 wallet chia.wallet.wallet_blockchain: INFO     💰 Updated wallet peak to height 561735, weight 429101312,
2021-07-28T21:20:48.721 wallet chia.wallet.wallet_blockchain: INFO     💰 Updated wallet peak to height 561736, weight 429103696,
2021-07-28T21:20:50.069 wallet chia.wallet.wallet_blockchain: INFO     💰 Updated wallet peak to height 561737, weight 429106080,
2021-07-28T21:20:50.125 wallet chia.wallet.wallet_blockchain: INFO     💰 Updated wallet peak to height 561738, weight 429108464,
2021-07-28T21:20:50.525 wallet chia.wallet.wallet_blockchain: INFO     💰 Updated wallet peak to height 561739, weight 429110848,
2021-07-28T21:20:50.668 wallet chia.wallet.wallet_blockchain: INFO     💰 Updated wallet peak to height 561740, weight 429113232,
2021-07-28T21:20:51.156 wallet chia.wallet.wallet_blockchain: INFO     💰 Updated wallet peak to height 561741, weight 429115616,
2021-07-28T21:20:52.062 wallet chia.wallet.wallet_blockchain: INFO     💰 Updated wallet peak to height 561742, weight 429118000,
2021-07-28T21:20:52.123 wallet chia.wallet.wallet_blockchain: INFO     💰 Updated wallet peak to height 561743, weight 429120384,
2021-07-28T21:20:52.208 wallet chia.wallet.wallet_blockchain: INFO     💰 Updated wallet peak to height 561744, weight 429122768,
2021-07-28T21:20:52.352 wallet chia.wallet.wallet_blockchain: INFO     💰 Updated wallet peak to height 561745, weight 429125152,
2021-07-28T21:20:52.405 wallet chia.wallet.wallet_blockchain: INFO     💰 Updated wallet peak to height 561746, weight 429127536,
2021-07-28T21:20:52.502 wallet chia.wallet.wallet_blockchain: INFO     💰 Updated wallet peak to height 561747, weight 429129920,
2021-07-28T21:20:52.620 wallet chia.wallet.wallet_blockchain: INFO     💰 Updated wallet peak to height 561748, weight 429132304,
2021-07-28T21:20:52.680 wallet chia.wallet.wallet_blockchain: INFO     💰 Updated wallet peak to height 561749, weight 429134688,
2021-07-28T21:20:52.735 wallet chia.wallet.wallet_blockchain: INFO     💰 Updated wallet peak to height 561750, weight 429137072,
2021-07-28T21:20:52.772 wallet chia.wallet.wallet_blockchain: INFO     💰 Updated wallet peak to height 561751, weight 429139456,
2021-07-28T21:20:52.824 wallet chia.wallet.wallet_blockchain: INFO     💰 Updated wallet peak to height 561752, weight 429141840,
2021-07-28T21:20:52.909 wallet chia.wallet.wallet_blockchain: INFO     💰 Updated wallet peak to height 561753, weight 429144224,
2021-07-28T21:20:52.946 wallet chia.wallet.wallet_blockchain: INFO     💰 Updated wallet peak to height 561754, weight 429146608,
2021-07-28T21:20:53.004 wallet chia.wallet.wallet_blockchain: INFO     💰 Updated wallet peak to height 561755, weight 429148992,
2021-07-28T21:20:53.077 wallet chia.wallet.wallet_blockchain: INFO     💰 Updated wallet peak to height 561756, weight 429151376,
2021-07-28T21:20:53.113 wallet chia.wallet.wallet_blockchain: INFO     💰 Updated wallet peak to height 561757, weight 429153760,
2021-07-28T21:20:53.180 wallet chia.wallet.wallet_blockchain: INFO     💰 Updated wallet peak to height 561758, weight 429156144,
2021-07-28T21:20:53.311 wallet chia.wallet.wallet_blockchain: INFO     💰 Updated wallet peak to height 561759, weight 429158528,
2021-07-28T21:20:53.427 wallet chia.wallet.wallet_blockchain: INFO     💰 Updated wallet peak to height 561760, weight 429160912,
2021-07-28T21:20:53.497 wallet chia.wallet.wallet_blockchain: INFO     💰 Updated wallet peak to height 561761, weight 429163296,
2021-07-28T21:20:53.534 wallet chia.wallet.wallet_blockchain: INFO     💰 Updated wallet peak to height 561762, weight 429165680,
2021-07-28T21:20:53.599 wallet chia.wallet.wallet_blockchain: INFO     💰 Updated wallet peak to height 561763, weight 429168064,
2021-07-28T21:20:53.660 wallet chia.wallet.wallet_blockchain: INFO     💰 Updated wallet peak to height 561764, weight 429170448,
2021-07-28T21:20:53.767 wallet chia.wallet.wallet_blockchain: INFO     💰 Updated wallet peak to height 561765, weight 429172832,
2021-07-28T21:20:53.771 wallet chia.wallet.wallet_node    : INFO     Requesting blocks 561765-561766
2021-07-28T21:20:53.868 wallet chia.wallet.wallet_blockchain: INFO     💰 Updated wallet peak to height 561766, weight 429175216,
2021-07-28T21:21:45.620 full_node full_node_server        : INFO     Connection closed: 67.4.98.200, node id: 8bd607e0feeacb253e95864286aedf6830d6b75ccbeba907aba680ec48abf12c
2021-07-28T21:21:45.620 full_node chia.full_node.full_node: INFO     peer disconnected {'host': '67.4.98.200', 'port': 8444}
2021-07-28T21:22:35.586 full_node chia.full_node.full_node: INFO     Number of peers we are syncing from: 66
2021-07-28T21:22:35.586 full_node chia.full_node.full_node: INFO     Added blocks 561766 to 561798
2021-07-28T21:22:35.587 full_node chia.full_node.full_node: INFO     Requesting blocks: 561798 to 561830
2021-07-28T21:22:35.596 wallet chia.wallet.wallet_node    : INFO     Requesting blocks 561765-561797
2021-07-28T21:22:37.831 wallet chia.wallet.wallet_blockchain: INFO     💰 Updated wallet peak to height 561767, weight 429177600,
2021-07-28T21:22:38.339 wallet chia.wallet.wallet_blockchain: INFO     💰 Updated wallet peak to height 561768, weight 429179984,
2021-07-28T21:22:39.468 wallet chia.wallet.wallet_blockchain: INFO     💰 Updated wallet peak to height 561769, weight 429182368,
2021-07-28T21:22:39.981 wallet chia.wallet.wallet_blockchain: INFO     💰 Updated wallet peak to height 561770, weight 429184752,
2021-07-28T21:22:43.394 wallet chia.wallet.wallet_blockchain: INFO     💰 Updated wallet peak to height 561771, weight 429187136,
2021-07-28T21:22:50.024 wallet chia.wallet.wallet_blockchain: INFO     💰 Updated wallet peak to height 561772, weight 429189520,
2021-07-28T21:22:51.877 wallet chia.wallet.wallet_blockchain: INFO     💰 Updated wallet peak to height 561773, weight 429191904,
```

It seems like I'm requesting blocks and processing them relatively quickly, but only when and if they arrive in small batches.  In the case above, a peer seems to have timed out, but other times a crash will appear in the logs after a pear rejects/disconnects:

```
2021-07-28T21:46:56.002 wallet chia.wallet.wallet_node    : INFO     Requesting blocks 562725-562726
2021-07-28T21:46:56.350 wallet chia.wallet.wallet_blockchain: INFO     💰 Updated wallet peak to height 562726, weight 431472384,

2021-07-28T21:47:13.652 full_node full_node_server        : INFO     Not accepting inbound connection: {'host': '73.175.60.181', 'port': 84
44}.Inbound limit reached.
2021-07-28T21:47:13.692 full_node full_node_server        : INFO     Connection closed: 73.175.60.181, node id: 08959edee4933c93f513167375a
a99f6f36a1d820828e25f477d5e81837e2fc0
2021-07-28T21:47:13.693 full_node chia.full_node.full_node: INFO     peer disconnected {'host': '73.175.60.181', 'port': 8444}
2021-07-28T21:47:13.696 full_node asyncio                 : ERROR    SSL error in data received
protocol: <asyncio.sslproto.SSLProtocol object at 0x7f95fc202c88>
transport: <_SelectorSocketTransport fd=141 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/usr/lib/python3.7/asyncio/sslproto.py", line 526, in data_received
    ssldata, appdata = self._sslpipe.feed_ssldata(data)
  File "/usr/lib/python3.7/asyncio/sslproto.py", line 207, in feed_ssldata
    self._sslobj.unwrap()
  File "/usr/lib/python3.7/ssl.py", line 767, in unwrap
    return self._sslobj.shutdown()
ssl.SSLError: [SSL: KRB5_S_INIT] application data after close notify (_ssl.c:2609)
2021-07-28T21:47:15.698 full_node chia.full_node.full_node: INFO     Number of peers we are syncing from: 66
2021-07-28T21:47:15.698 full_node chia.full_node.full_node: INFO     Added blocks 562726 to 562758
2021-07-28T21:47:15.699 full_node chia.full_node.full_node: INFO     Requesting blocks: 562758 to 562790
2021-07-28T21:47:15.706 wallet chia.wallet.wallet_node    : INFO     Requesting blocks 562725-562757
```

Other times, the pauses are associated with read errors:

```
2021-07-28T21:54:49.576 full_node asyncio                 : ERROR    Fatal read error on socket transport
protocol: <asyncio.sslproto.SSLProtocol object at 0x7f960641fb38>
transport: <_SelectorSocketTransport fd=103 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/usr/lib/python3.7/asyncio/selector_events.py", line 801, in _read_ready__data_received
    data = self._sock.recv(self.max_size)
TimeoutError: [Errno 110] Connection timed out
```
I'm actually not sure if the cadence is normal but the block updates are slow, or if the pauses described above are the problem, since I don't believe it's ever been working right, and I did not run individual full nodes long enough to notice if any of them ever synced.

I haven't won any coin, so I suspect I've never had a node that was fully synced for their portion of the plots, let alone all my plots on synced nodes at the same time.

My config.yaml farmer section is close to defaults:, aside from disabling upnp.  I verified that the port is open from the outside, and made sure it was pointing to the right ip on the inside, without port number redirection.

```
farmer:
  full_node_peer:
    host: localhost
    port: 8444
  harvester_peer:
    host: localhost
    port: 8448
  logging: &id001
    log_filename: log/debug.log
    log_level: INFO
    log_maxfilesrotation: 7
    log_stdout: false
    log_syslog: false
    log_syslog_host: localhost
    log_syslog_port: 514
  network_overrides: &id002
    config:
      mainnet:
        address_prefix: xch
        default_full_node_port: 8444
      testnet0:
        address_prefix: txch
      testnet1:
        address_prefix: txch
      testnet2:
        address_prefix: txch
      testnet3:
        address_prefix: txch
      testnet4:
        address_prefix: txch
      testnet7:
        address_prefix: txch
        default_full_node_port: 58444
```

As I mentioned before, I cannot find any real solution online, or really any troubleshooting information at all for a similar problem, other than to port forward, which I have done.

Any tips are much appreciated.

**Comment by mariano54** [comment]
That is very strange. Maybe it's something related to the VM not allocating significant resources? With that many cores, you should be syncing much faster (fully done in 1 day).

**Comment by nbauernfeind** [comment]
Check to see if your sqlite version is up-to-date. I had an old version from 2016 that became very slow when adding new blocks. Sometimes it would take 90s to commit a single full block!

**Comment by emlowe** [comment]
> Check to see if your sqlite version is up-to-date. I had an old version from 2016 that became very slow when adding new blocks. Sometimes it would take 90s to commit a single full block!

Chia should be using the version of sqlite3 bundled with the python version you are using. `python -c "import sqlite3; print(sqlite3.sqlite_version)"`

**Comment by Furious-George** [comment]
> python -c "import sqlite3; print(sqlite3.sqlite_version)"

```
# python -c "import sqlite3; print(sqlite3.sqlite_version)"
3.27.2
```
Seems to be from early 2019.

Today:
596061/642053 = 0.92836728432

Yesterday:
561225/637953 = 0.87972781693


> Maybe it's something related to the VM not allocating significant resources? With that many cores, you should be syncing much faster (fully done in 1 day).

Now that you mention it, and in the context of sqlite:  the vm is using virtio for the virtual hdd, but I realized when I tried to plot in a vm, even if I pass the entire disk to the vm as a raw device node, diskio performance in vms is still pretty bad.

In this case, my vm's hdd is on a 2 x spindle disk raid-1 array, on a nas with a gbe uplink.  My disk IO is not getting above 1 MB/s, so the vm may be having problems handling all the tiny sql operations along with everything else.

I could move the root disk to a machine with local sdd storage, but I'd have to stop RAM disk plotting, and my next option is a single internal spindle disk....  I could (and eventually, will) add an sdd just for chia farming, but by the time I got over to the server to do that, I'd be done syncing anyway.

If we assume the VM's disk IO is the problem, it seems like I'm stuck with it for now.

**Comment by Furious-George** [comment]
UPDATE:  I moved the farmer to my backup nas, which is a lot less busy most of the time, and has more favorable raid-5+spare 4 disk setup, and I'm grabbing blocks about ten times faster.
