### ISSUE TITLE
[BUG] Chia 1.2.3: Logging error occurs at Mac terminal all the time, runnig CLI

### ISSUE THREAD

**Issue by Trypt88** [Chia-Network/chia-blockchain#7880]
After starting farmer for how long unclear, terminal begins to show below logging error msg... 

--- Logging error ---
Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.9/3.9.6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/selector_events.py", line 164, in _accept_connection
  File "/usr/local/Cellar/python@3.9/3.9.6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/socket.py", line 293, in accept
OSError: [Errno 24] Too many open files

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/trypt/chia-blockchain/venv/lib/python3.9/site-packages/concurrent_log_handler/__init__.py", line 330, in emit
  File "/Users/trypt/chia-blockchain/venv/lib/python3.9/site-packages/concurrent_log_handler/__init__.py", line 407, in _do_lock
  File "/Users/trypt/chia-blockchain/venv/lib/python3.9/site-packages/concurrent_log_handler/__init__.py", line 253, in _open_lockfile
OSError: [Errno 24] Too many open files: '/Users/trypt/.chia/mainnet/log/.__debug.lock'
Call stack:
  File "/Users/trypt/chia-blockchain/venv/bin/chia_full_node", line 33, in <module>
  File "/Users/trypt/chia-blockchain/chia/server/start_full_node.py", line 60, in main
  File "/Users/trypt/chia-blockchain/chia/server/start_service.py", line 255, in run_service
  File "/usr/local/Cellar/python@3.9/3.9.6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/runners.py", line 44, in run
  File "/usr/local/Cellar/python@3.9/3.9.6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/base_events.py", line 629, in run_until_complete
  File "/usr/local/Cellar/python@3.9/3.9.6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/base_events.py", line 596, in run_forever
  File "/usr/local/Cellar/python@3.9/3.9.6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/base_events.py", line 1890, in _run_once
  File "/usr/local/Cellar/python@3.9/3.9.6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/events.py", line 80, in _run
  File "/usr/local/Cellar/python@3.9/3.9.6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/selector_events.py", line 179, in _accept_connection
  File "/usr/local/Cellar/python@3.9/3.9.6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/base_events.py", line 1764, in call_exception_handler
  File "/usr/local/Cellar/python@3.9/3.9.6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/base_events.py", line 1738, in default_exception_handler
  File "/usr/local/Cellar/python@3.9/3.9.6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/logging/__init__.py", line 1475, in error
  File "/usr/local/Cellar/python@3.9/3.9.6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/logging/__init__.py", line 1589, in _log
  File "/usr/local/Cellar/python@3.9/3.9.6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/logging/__init__.py", line 1599, in handle
  File "/usr/local/Cellar/python@3.9/3.9.6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/logging/__init__.py", line 1661, in callHandlers
  File "/usr/local/Cellar/python@3.9/3.9.6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/logging/__init__.py", line 952, in handle
  File "/Users/trypt/chia-blockchain/venv/lib/python3.9/site-packages/concurrent_log_handler/__init__.py", line 346, in emit
Message: "socket.accept() out of system resource\nsocket: <asyncio.TransportSocket fd=36, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('0.0.0.0', 8444)>"
Arguments: ()

Many many times, so need to Ctrl+C to stop it.

1. Run terminal
2. cd chia-blockchain
3. . ./activate
4. chia start farmer -r
5. after running for a while, it will happen.

<img width="1440" alt="截屏2021-07-31 10 28 44" src="https://user-images.githubusercontent.com/84079245/127727429-645069d8-0801-4a12-9dd4-b59e9cffaa15.png">

- OS: Macos
- OS Version/Flavor: macOS Big Sur 11.4
- CPU: 2.4 GHz Quad Core Intel Core i5

**Comment by Trypt88** [comment]
Getting these errors and warning in debug.log:

2021-07-31T10:40:49.602 farmer chia.farmer.farmer         : ERROR    Failed to update farmer information on the pool https://asia1.pool.space
2021-07-31T10:43:11.704 full_node chia.rpc.rpc_server     : WARNING  Error while handling message: Traceback (most recent call last):
    raise ValueError("Start client failed, or server is not set")
ValueError: Start client failed, or server is not set
2021-07-31T10:44:07.707 full_node chia.rpc.rpc_server     : WARNING  Error while handling message: Traceback (most recent call last):
    raise ValueError("Start client failed, or server is not set")
ValueError: Start client failed, or server is not set
2021-07-31T10:44:39.704 full_node chia.rpc.rpc_server     : WARNING  Error while handling message: Traceback (most recent call last):
    raise ValueError("Start client failed, or server is not set")
ValueError: Start client failed, or server is not set
2021-07-31T10:45:18.710 full_node chia.rpc.rpc_server     : WARNING  Error while handling message: Traceback (most recent call last):
    raise ValueError("Start client failed, or server is not set")
ValueError: Start client failed, or server is not set
2021-07-31T10:45:49.707 full_node chia.rpc.rpc_server     : WARNING  Error while handling message: Traceback (most recent call last):
    raise ValueError("Start client failed, or server is not set")
ValueError: Start client failed, or server is not set
2021-07-31T10:45:56.671 farmer chia.farmer.farmer         : ERROR    Failed to update farmer information on the pool https://asia1.pool.space
2021-07-31T10:46:41.711 full_node chia.rpc.rpc_server     : WARNING  Error while handling message: Traceback (most recent call last):
    raise ValueError("Start client failed, or server is not set")
ValueError: Start client failed, or server is not set
2021-07-31T10:46:56.162 full_node chia.rpc.rpc_server     : WARNING  Error while handling message: Traceback (most recent call last):
    raise ValueError("Start client failed, or server is not set")
ValueError: Start client failed, or server is not set
2021-07-31T10:47:28.712 full_node chia.rpc.rpc_server     : WARNING  Error while handling message: Traceback (most recent call last):
    raise ValueError("Start client failed, or server is not set")
ValueError: Start client failed, or server is not set
2021-07-31T10:48:06.711 full_node chia.rpc.rpc_server     : WARNING  Error while handling message: Traceback (most recent call last):
    raise ValueError("Start client failed, or server is not set")
ValueError: Start client failed, or server is not set
2021-07-31T10:48:39.711 full_node chia.rpc.rpc_server     : WARNING  Error while handling message: Traceback (most recent call last):
    raise ValueError("Start client failed, or server is not set")
ValueError: Start client failed, or server is not set
2021-07-31T10:49:27.715 full_node chia.rpc.rpc_server     : WARNING  Error while handling message: Traceback (most recent call last):
    raise ValueError("Start client failed, or server is not set")
ValueError: Start client failed, or server is not set
2021-07-31T10:49:58.710 full_node chia.rpc.rpc_server     : WARNING  Error while handling message: Traceback (most recent call last):
    raise ValueError("Start client failed, or server is not set")
ValueError: Start client failed, or server is not set

2021-07-31T10:43:11.704 full_node chia.rpc.rpc_server     : WARNING  Error while handling message: Traceback (most recent call last):
2021-07-31T10:44:07.707 full_node chia.rpc.rpc_server     : WARNING  Error while handling message: Traceback (most recent call last):
2021-07-31T10:44:39.704 full_node chia.rpc.rpc_server     : WARNING  Error while handling message: Traceback (most recent call last):
2021-07-31T10:45:18.710 full_node chia.rpc.rpc_server     : WARNING  Error while handling message: Traceback (most recent call last):
2021-07-31T10:45:49.707 full_node chia.rpc.rpc_server     : WARNING  Error while handling message: Traceback (most recent call last):
2021-07-31T10:46:41.711 full_node chia.rpc.rpc_server     : WARNING  Error while handling message: Traceback (most recent call last):
2021-07-31T10:46:56.162 full_node chia.rpc.rpc_server     : WARNING  Error while handling message: Traceback (most recent call last):
2021-07-31T10:47:28.712 full_node chia.rpc.rpc_server     : WARNING  Error while handling message: Traceback (most recent call last):
2021-07-31T10:48:06.711 full_node chia.rpc.rpc_server     : WARNING  Error while handling message: Traceback (most recent call last):
2021-07-31T10:48:39.711 full_node chia.rpc.rpc_server     : WARNING  Error while handling message: Traceback (most recent call last):
2021-07-31T10:49:27.715 full_node chia.rpc.rpc_server     : WARNING  Error while handling message: Traceback (most recent call last):
2021-07-31T10:49:58.710 full_node chia.rpc.rpc_server     : WARNING  Error while handling message: Traceback (most recent call last):
