### ISSUE TITLE
wallet chia.wallet.wallet_node    : ERROR    Loop exception in sync Was not able to add blocks 646779-646811.

### ISSUE THREAD

**Issue by SWICTH13** [Chia-Network/chia-blockchain#7886]
The wallet has stopped syncing, help !!!! ChiaSetup-1.2.3

![Screenshot_1](https://user-images.githubusercontent.com/85879399/127740231-95754236-2044-40d7-bf93-270d38dff17d.jpg)

**Comment by oOyH** [comment]
![image](https://user-images.githubusercontent.com/34229155/127966514-fed56740-5d09-4685-bf35-ab989f7f0941.png)
I also encountered the same problem, has not solved the 1.2.3 version, Windows

**Comment by LouisLoudogTrottier** [comment]
Ubuntu server 20.04 Wallet are stuck at 0 after removing wallet/db

wallet chia.wallet.wallet_node    : ERROR    Loop exception in sync Was not able to add blocks 0-32.
.../wallet_node.py", line 537, in batch_sync_to_peak
    raise RuntimeError(f"Was not able to add blocks {start_height}-{end_height}")
RuntimeError: Was not able to add blocks 0-32

wallet chia.wallet.wallet_node    : ERROR    Loop exception in sync Was not able to add blocks 5152-5184.

**Comment by thberger** [comment]
I have the same problem. Once the wallet DB files are removed, one is stuck with this bug.

Copying wallet db files over from other PCs didn't work for me as well. Either the wallet is not starting up at all (with no error message in the logs), or it is saying that the wallet DB is corrupted.

**Comment by HelixiR** [comment]
Same issue 

`2021-08-15T00:03:40.694 wallet chia.wallet.wallet_node    : ERROR    Loop exception in sync Was not able to add blocks 0-32. Traceback (most recent call last):
  File "/home/ubuntu/chia-blockchain/chia/wallet/wallet_node.py", line 580, in sync_job
    await self._sync()
  File "/home/ubuntu/chia-blockchain/chia/wallet/wallet_node.py", line 660, in _sync
    await self.batch_sync_to_peak(fork_height, peak)
  File "/home/ubuntu/chia-blockchain/chia/wallet/wallet_node.py", line 537, in batch_sync_to_peak
    raise RuntimeError(f"Was not able to add blocks {start_height}-{end_height}")
RuntimeError: Was not able to add blocks 0-32
`

**Comment by hardhub** [comment]
> 
> 
> This issue has been flagged as stale as there has been no activity on it in 14 days. If this issue is still affecting you and in need of review, please update it to keep it open.

What exactly should we do to keep it open? Write "Up" every 2 weeks? Ridiculous...

**Comment by boner-cmd** [comment]
At least two of you are already there, but you can always keep bumping the consolidated issue at #6993 (which funnily enough is also "stale" despite containing at least three if not six months of bug reports)

**Comment by hardhub** [comment]
I have solved my own siuation.  
I restart chia each time when it stucks.   
I did that probably 10 times and finally I got all synced.  

Do not forget to open chia port and map it to PC in your router/firewall.   
For many users that is usually the reason of bad sync.   
But I am absolutely sure chia has issue with sync.

**Comment by jack60612** [comment]
> I have solved my own siuation.
> I restart chia each time when it stucks.
> I did that probably 10 times and finally I got all synced.
> 
> Do not forget to open chia port and map it to PC in your router/firewall.
> For many users that is usually the reason of bad sync.
> But I am absolutely sure chia has issue with sync.

what version are you using?

**Comment by hardhub** [comment]
> what version are you using?

Usually latest. It was 1.2.7 on that moment.

**Comment by emlowe** [comment]
Duplicate of #6993
