### ISSUE TITLE
Constant Warning: Sending data failed. Exception Tracebac  & Error: Unexpected exception trying to send to websocket: code

### ISSUE THREAD

**Issue by rjacobs022** [Chia-Network/chia-blockchain#7888]
This is constantly happening. Please help!!!

Traceback (most recent call last):
  File "D:\a\chia-blockchain\chia-blockchain\venv\Lib\site-packages\chia\daemon\server.py", line 187, in safe_handle
  File "websockets\protocol.py", line 555, in send
  File "websockets\protocol.py", line 803, in ensure_open
websockets.exceptions.ConnectionClosedError: code = 1006 (connection closed abnormally [internal]), no reason

2021-07-31T13:32:24.239 full_node chia.full_node.full_node: INFO       Finished signage point 45/64: CC: 4ed9aa43a8bf7c7b9e105ef58875d74761f448247fd868174e0669b3ac4663bb RC: e982e7403434c0e9cb2a4c7e5ba65944f06d399adc10c85eae631204b71ae779 
2021-07-31T13:32:24.301 harvester chia.harvester.harvester: INFO     0 plots were eligible for farming 348831f6a5... Found 0 proofs. Time: 0.04686 s. Total 1001 plots
2021-07-31T13:32:25.330 full_node full_node_server        : INFO     Not accepting inbound connection: {'host': '113.100.186.187', 'port': 8444}.Inbound limit reached.
2021-07-31T13:32:25.573 full_node chia.full_node.mempool_manager: INFO     It took 0.0019948482513427734 to pre validate transaction
2021-07-31T13:32:25.575 full_node full_node_server        : INFO     Connection closed: 113.100.186.187, node id: dd9cf0c861ab3ea337003b48b87c70fcb3492c48e0f17650c50cc4724bfa6943
2021-07-31T13:32:25.575 full_node chia.full_node.full_node: INFO     peer disconnected {'host': '113.100.186.187', 'port': 8444}
2021-07-31T13:32:25.578 full_node chia.rpc.rpc_server     : WARNING  Sending data failed. Exception Traceback (most recent call last):
  File "chia\rpc\rpc_server.py", line 67, in _state_changed
  File "aiohttp\client_ws.py", line 150, in send_str
  File "aiohttp\http_websocket.py", line 687, in send
  File "aiohttp\http_websocket.py", line 643, in _send_frame
  File "aiohttp\http_websocket.py", line 660, in _write
ConnectionResetError: Cannot write to closing transport
.
2021-07-31T13:32:25.580 full_node chia.rpc.rpc_server     : WARNING  Sending data failed. Exception Traceback (most recent call last):
  File "chia\rpc\rpc_server.py", line 67, in _state_changed
  File "aiohttp\client_ws.py", line 150, in send_str
  File "aiohttp\http_websocket.py", line 687, in send
  File "aiohttp\http_websocket.py", line 643, in _send_frame
  File "aiohttp\http_websocket.py", line 660, in _write
ConnectionResetError: Cannot write to closing transport
.
2021-07-31T13:32:27.831 daemon __main__                   : ERROR    Unexpected exception trying to send to websocket: code = 1006 (connection closed abnormally [internal]), no reason Traceback (most recent call last):
  File "websockets\protocol.py", line 827, in transfer_data
  File "websockets\protocol.py", line 895, in read_message
  File "websockets\protocol.py", line 995, in read_data_frame
  File "websockets\protocol.py", line 766, in pong
  File "websockets\protocol.py", line 803, in ensure_open
websockets.exceptions.ConnectionClosedError: code = 1006 (connection closed abnormally [internal]), no reason

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\a\chia-blockchain\chia-blockchain\venv\Lib\site-packages\chia\daemon\server.py", line 187, in safe_handle
  File "websockets\protocol.py", line 555, in send
  File "websockets\protocol.py", line 803, in ensure_open
websockets.exceptions.ConnectionClosedError: code = 1006 (connection closed abnormally [internal]), no reason

2021-07-31T13:32:29.681 full_node chia.full_node.full_node: INFO     Added unfinished_block a51543fd5c1e686a419769551d08e9a78ba5a6013986d706f08b68a926e2d94d, not farmed by us, SP: 45 farmer response time: 5.442101240158081, Pool pk xch1gue4gjy7ca9l5n0w4l8whkhz0k99fguz8ayqhzx9zknz5pwdvw9sr0es3v, validation time: 0.04686331748962402, cost: 242347982, percent full: 2.203%
2021-07-31T13:32:33.394 full_node chia.full_node.full_node: INFO       Finished signage point 46/64: CC: 5e74ba2398a0220ff0af563fa2a7b29b28b513b44768b1e5505b3ce0a53d23a0 RC: c164e99f3495ae8c96b4c83879f7c3458241e9b5ab3a8c515e4afee2136db13f 
2021-07-31T13:32:33.457 daemon __main__                   : ERROR    Unexpected exception trying to send to websocket: code = 1006 (connection closed abnormally [internal]), no reason Traceback (most recent call last):
  File "websockets\protocol.py", line 827, in transfer_data
  File "websockets\protocol.py", line 895, in read_message
  File "websockets\protocol.py", line 995, in read_data_frame
  File "websockets\protocol.py", line 766, in pong
  File "websockets\protocol.py", line 803, in ensure_open
websockets.exceptions.ConnectionClosedError: code = 1006 (connection closed abnormally [internal]), no reason

**Comment by toolmanlife** [comment]
i happen often too

**Comment by Drakanus** [comment]
it happens each single day
