### ISSUE TITLE
Every time a plot is found it triggers a series of errors [BUG]

### ISSUE THREAD

**Issue by HowardW56** [Chia-Network/chia-blockchain#7957]
**Describe the bug**

**Screenshots**

**Desktop**

- OS: 
- OS Version/Flavor: 
- CPU: 

**Additional context**

**Comment by HowardW56** [comment]
Windows 10; I7

**Comment by keliew** [comment]
What does the error say?

**Comment by HowardW56** [comment]
2021-08-05T08:07:26.914 farmer chia.farmer.farmer         : ERROR    Exception in GET /farmer https://na1.pool.space, Cannot connect to host na1.pool.space:443 ssl:<ssl.SSLContext object at 0x0000023F47FE4440> [getaddrinfo failed]

2021-08-05T08:08:28.307 farmer chia.farmer.farmer         : ERROR    Exception in GET /farmer https://na1.pool.space, Cannot connect to host na1.pool.space:443 ssl:<ssl.SSLContext object at 0x0000023F47FD0840> [getaddrinfo failed]

2021-08-05T08:09:29.712 farmer chia.farmer.farmer         : ERROR    Exception in GET /farmer https://na1.pool.space, Cannot connect to host na1.pool.space:443 ssl:<ssl.SSLContext object at 0x0000023F47F1C640> [getaddrinfo failed]

2021-08-05T08:10:31.087 farmer chia.farmer.farmer         : ERROR    Exception in GET /farmer https://na1.pool.space, Cannot connect to host na1.pool.space:443 ssl:<ssl.SSLContext object at 0x0000023F46CD8040> [getaddrinfo failed]

2021-08-05T08:11:32.575 farmer chia.farmer.farmer         : ERROR    Exception in GET /farmer https://na1.pool.space, Cannot connect to host na1.pool.space:443 ssl:<ssl.SSLContext object at 0x0000023F47F95B40> [getaddrinfo failed]

2021-08-05T08:12:34.105 farmer chia.farmer.farmer         : ERROR    Exception in GET /farmer https://na1.pool.space, Cannot connect to host na1.pool.space:443 ssl:<ssl.SSLContext object at 0x0000023F47F958C0> [getaddrinfo failed]

2021-08-05T08:13:35.542 farmer chia.farmer.farmer         : ERROR    Exception in GET /farmer https://na1.pool.space, Cannot connect to host na1.pool.space:443 ssl:<ssl.SSLContext object at 0x0000023F46CC5E40> [getaddrinfo failed]

2021-08-05T08:14:37.228 farmer chia.farmer.farmer         : ERROR    Exception in GET /farmer https://na1.pool.space, Cannot connect to host na1.pool.space:443 ssl:<ssl.SSLContext object at 0x0000023F47FD05C0> [getaddrinfo failed]

2021-08-05T08:15:38.711 farmer chia.farmer.farmer         : ERROR    Exception in GET /farmer https://na1.pool.space, Cannot connect to host na1.pool.space:443 ssl:<ssl.SSLContext object at 0x0000023F47F78E40> [getaddrinfo failed]

2021-08-05T08:16:40.355 farmer chia.farmer.farmer         : ERROR    Exception in GET /farmer https://na1.pool.space, Cannot connect to host na1.pool.space:443 ssl:<ssl.SSLContext object at 0x0000023F46DC71C0> [getaddrinfo failed]

2021-08-05T08:17:41.911 farmer chia.farmer.farmer         : ERROR    Exception in GET /farmer https://na1.pool.space, Cannot connect to host na1.pool.space:443 ssl:<ssl.SSLContext object at 0x0000023F46C411C0> [getaddrinfo failed]

2021-08-05T08:18:43.399 farmer chia.farmer.farmer         : ERROR    Exception in GET /farmer https://na1.pool.space, Cannot connect to host na1.pool.space:443 ssl:<ssl.SSLContext object at 0x0000023F46C411C0> [getaddrinfo failed]

2021-08-05T08:19:44.805 farmer chia.farmer.farmer         : ERROR    Exception in GET /farmer https://na1.pool.space, Cannot connect to host na1.pool.space:443 ssl:<ssl.SSLContext object at 0x0000023F4627EAC0> [getaddrinfo failed]

2021-08-05T08:20:46.405 farmer chia.farmer.farmer         : ERROR    Exception in GET /farmer https://na1.pool.space, Cannot connect to host na1.pool.space:443 ssl:<ssl.SSLContext object at 0x0000023F46C41D40> [getaddrinfo failed]

2021-08-05T08:21:47.934 farmer chia.farmer.farmer         : ERROR    Exception in GET /farmer https://na1.pool.space, Cannot connect to host na1.pool.space:443 ssl:<ssl.SSLContext object at 0x0000023F46C41D40> [getaddrinfo failed]

2021-08-05T08:22:49.418 farmer chia.farmer.farmer         : ERROR    Exception in GET /farmer https://na1.pool.space, Cannot connect to host na1.pool.space:443 ssl:<ssl.SSLContext object at 0x0000023F46CB7D40> [getaddrinfo failed]

2021-08-05T08:23:51.046 farmer chia.farmer.farmer         : ERROR    Exception in GET /farmer https://na1.pool.space, Cannot connect to host na1.pool.space:443 ssl:<ssl.SSLContext object at 0x0000023F47FBEA40> [getaddrinfo failed]

2021-08-05T08:34:03.805 daemon asyncio                    : ERROR    Task exception was never retrieved

future: <Task finished name='Task-80293' coro=<kill_service() done, defined at D:\a\chia-blockchain\chia-blockchain\venv\Lib\site-packages\chia\daemon\server.py:875> exception=AttributeError("'list' object has no attribute 'pid'")>

Traceback (most recent call last):

  File "D:\a\chia-blockchain\chia-blockchain\venv\Lib\site-packages\chia\daemon\server.py", line 883, in kill_service

  File "D:\a\chia-blockchain\chia-blockchain\venv\Lib\site-packages\chia\daemon\server.py", line 847, in kill_process

AttributeError: 'list' object has no attribute 'pid'

2021-08-05T10:05:20.548 full_node full_node_server        : ERROR    Exception: Value -4994627 of size 23 does not fit into uint64 of size 64, {'host': '168.226.219.8', 'port': 8444}. Traceback (most recent call last):

  File "chia\util\struct_stream.py", line 16, in __new__

struct.error: int too large to convert

 

During handling of the above exception, another exception occurred:

 

Traceback (most recent call last):

  File "chia\server\server.py", line 528, in wrapped_coroutine

  File "chia\full_node\full_node_api.py", line 620, in respond_end_of_sub_slot

  File "chia\full_node\full_node.py", line 1567, in respond_end_of_sub_slot

  File "chia\full_node\full_node_store.py", line 289, in new_finished_sub_slot

  File "chia\util\struct_stream.py", line 21, in __new__

ValueError: Value -4994627 of size 23 does not fit into uint64 of size 64

 

2021-08-05T10:05:20.550 full_node full_node_server        : ERROR    Exception: Value -4994627 of size 23 does not fit into uint64 of size 64 <class 'ValueError'>, closing connection {'host': '168.226.219.8', 'port': 8444}. Traceback (most recent call last):

  File "chia\util\struct_stream.py", line 16, in __new__

struct.error: int too large to convert

 

During handling of the above exception, another exception occurred:

 

Traceback (most recent call last):

  File "chia\server\server.py", line 538, in api_call

  File "asyncio\tasks.py", line 481, in wait_for

  File "chia\server\server.py", line 535, in wrapped_coroutine

  File "chia\server\server.py", line 528, in wrapped_coroutine

  File "chia\full_node\full_node_api.py", line 620, in respond_end_of_sub_slot

  File "chia\full_node\full_node.py", line 1567, in respond_end_of_sub_slot

  File "chia\full_node\full_node_store.py", line 289, in new_finished_sub_slot

  File "chia\util\struct_stream.py", line 21, in __new__

ValueError: Value -4994627 of size 23 does not fit into uint64 of size 64

 

2021-08-05T10:05:21.470 full_node full_node_server        : ERROR    Exception: Error short batch syncing, invalid/no response for 673370-673402, None. Traceback (most recent call last):

  File "chia\server\server.py", line 528, in wrapped_coroutine

  File "chia\full_node\full_node_api.py", line 106, in new_peak

  File "chia\full_node\full_node.py", line 411, in new_peak

  File "chia\full_node\full_node.py", line 267, in short_sync_batch

ValueError: Error short batch syncing, invalid/no response for 673370-673402

 

2021-08-05T10:05:21.471 full_node full_node_server        : ERROR    Exception: Error short batch syncing, invalid/no response for 673370-673402 <class 'ValueError'>, closing connection None. Traceback (most recent call last):

  File "chia\server\server.py", line 538, in api_call

  File "asyncio\tasks.py", line 442, in wait_for

  File "chia\server\server.py", line 535, in wrapped_coroutine

  File "chia\server\server.py", line 528, in wrapped_coroutine

  File "chia\full_node\full_node_api.py", line 106, in new_peak

  File "chia\full_node\full_node.py", line 411, in new_peak

  File "chia\full_node\full_node.py", line 267, in short_sync_batch

ValueError: Error short batch syncing, invalid/no response for 673370-673402

 

2021-08-05T10:05:21.485 farmer chia.farmer.farmer         : ERROR    Harvester did not respond. You might need to update harvester to the latest version

**Comment by keliew** [comment]
Better to ask [Space@Discord](https://discord.gg/spacepool)

**Comment by loppefaaret** [comment]
Did you try and contact your pool ? did they have any directions for you to try ? perhaps you could try and better explain exactly what you problem is, and what you are doing prior for the problem to occur ?

**Comment by emlowe** [comment]
Closing issue - you are having some network problem connecting to the pool which is unrelated to chia directly
