### ISSUE TITLE
[BUG] chia stops working

### ISSUE THREAD

**Issue by rthorntn** [Chia-Network/chia-blockchain#7994]
**Describe the bug**
A disk failed the other night and chia stopped working at around the same time

**To Reproduce**

Can't reproduce

**Expected behavior**

Chia doesn't stop working

**Desktop**

- OS: Linux
- OS Version: Ubuntu 20.04 Server
- CPU: TR 3960X
- 1.2.3-dev0
- Single server "full-node" no seperate harvesters
- 50 disks

**Additional context**
dmesg
I got hundreds of these: `EXT4-fs warning (device sdat): dx_probe:761: inode #2: lblock 0: comm chia_harvester: error -5 reading directory block`

Then this `EXT4-fs error (device sdat): _ext4get_inode_loc:4712: inode #2: block 1640: comm chia_harvester: unable to read itable block`

Finally just before the stack trace `EXT4-fs error (device sdat) in ext4_reserve_inode_write:5956: IO failure`

Stack trace:
![paste](https://user-images.githubusercontent.com/12758977/128656653-1a5c7a06-795f-4a46-9001-62130a51aae5.png)

I woke up and `chia farm summary` just hung until I started the farmer

I have removed the disk that was `sdat`

`tail -f  ~/.chia/mainnet/log/debug.log | grep "[1-99999] plots were"` did nothing

**Chia logs**
```
2021-08-07T05:11:49.460 wallet wallet_server              : INFO     Connection closed: 127.0.0.1, node id: fea7b8a30b9000b7e4a676ee51184bf79ea9c07504316a6782724cb19278a950
2021-08-07T05:11:52.191 wallet wallet                     : INFO     Reconnecting to peer {'host': '127.0.0.1', 'port': 8444}
2021-08-07T05:12:25.303 wallet wallet                     : INFO     Reconnecting to peer {'host': '127.0.0.1', 'port': 8444}
2021-08-07T05:12:59.281 wallet wallet                     : INFO     Reconnecting to peer {'host': '127.0.0.1', 'port': 8444}
2021-08-07T05:13:26.875 farmer farmer_server              : INFO     Connection closed: 127.0.0.1, node id: fea7b8a30b9000b7e4a676ee51184bf79ea9c07504316a6782724cb19278a950
2021-08-07T05:13:26.875 farmer chia.farmer.farmer         : INFO     peer disconnected {'host': '127.0.0.1', 'port': 8444}
2021-08-07T05:13:28.556 farmer farmer                     : INFO     Reconnecting to peer {'host': '127.0.0.1', 'port': 8444}
2021-08-07T05:24:17.457 daemon chia.daemon.server         : INFO     Websocket exception. Closing websocket with chia_full_node code = 1006 (connection closed abnormally [internal]), no reason Traceback (most recent call last):
  File "/home/rthorntn/chia-blockchain/venv/lib/python3.8/site-packages/websockets/protocol.py", line 827, in transfer_data
    message = await self.read_message()
  File "/home/rthorntn/chia-blockchain/venv/lib/python3.8/site-packages/websockets/protocol.py", line 895, in read_message
    frame = await self.read_data_frame(max_size=self.max_size)
  File "/home/rthorntn/chia-blockchain/venv/lib/python3.8/site-packages/websockets/protocol.py", line 971, in read_data_frame
    frame = await self.read_frame(max_size)
  File "/home/rthorntn/chia-blockchain/venv/lib/python3.8/site-packages/websockets/protocol.py", line 1047, in read_frame
    frame = await Frame.read(
  File "/home/rthorntn/chia-blockchain/venv/lib/python3.8/site-packages/websockets/framing.py", line 105, in read
    data = await reader(2)
  File "/usr/lib/python3.8/asyncio/streams.py", line 723, in readexactly
    await self.waitfor_data('readexactly')
  File "/usr/lib/python3.8/asyncio/streams.py", line 517, in waitfor_data
    await self._waiter
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/rthorntn/chia-blockchain/chia/daemon/server.py", line 172, in safe_handle
    async for message in websocket:
  File "/home/rthorntn/chia-blockchain/venv/lib/python3.8/site-packages/websockets/protocol.py", line 439, in aiter
    yield await self.recv()
  File "/home/rthorntn/chia-blockchain/venv/lib/python3.8/site-packages/websockets/protocol.py", line 509, in recv
    await self.ensure_open()
  File "/home/rthorntn/chia-blockchain/venv/lib/python3.8/site-packages/websockets/protocol.py", line 812, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedError: code = 1006 (connection closed abnormally [internal]), no reason

2021-08-07T05:24:19.279 wallet wallet                     : INFO     Reconnecting to peer {'host': '127.0.0.1', 'port': 8444}
2021-08-07T08:41:31.293 wallet wallet                     : INFO     Reconnecting to peer {'host': '127.0.0.1', 'port': 8444}
2021-08-07T12:02:19.736 daemon chia.daemon.server         : INFO     Starting Daemon Server
```

I snipped out a lot of `Reconnecting to peer {'host': '127.0.0.1', 'port': 8444}`

It was reconnecting from 05:11 until 08:41. At 12:02 I started bringing everything back up

There are tons of harvester log entries before 05:11 and after 12:02 but none in between

**Comment by rthorntn** [comment]
@altendky (thanks Kyle) made the comment on 9th Aug at 12:08 AEST to my posting on KeyBase chia_network.public#farming:

"there may be some improvements to make in the harvester code to avoid this, or it may be that the system killed the process, i don't know.  but regardless i think that if you are wanting to be really proper about uptime then you ought to setup chia with your system service manager.  i'm not sure what exactly that would look like since i haven't done much with custom service definitions, but i'm asking around and will let you know if i get some good advice"

**Comment by keliew** [comment]
I think to test this, one could forcibly `umount` the disk while chia is running. The harvester would fail, whilst farming is still running.

**Comment by rthorntn** [comment]
@keliew I think the disk took a while to cause problems, the disk is still recognised but refuses to mount now, I think its this "zombie" disk is maybe something that wasn't tested, `umount` or just pulling a mounted disk don't seem to cause any problems with Chia.

**Comment by zlatovlas** [comment]
Seeing this part:
<code>
Connection closed: 127.0.0.1, node id: fea7b8a30b9000b7e4a676ee51184bf79ea9c07504316a6782724cb19278a950
2021-08-07T05:13:26.875 farmer chia.farmer.farmer         : INFO     peer disconnected {'host': '127.0.0.1', 'port': 8444}
2021-08-07T05:13:28.556 farmer farmer                     : INFO     Reconnecting to peer {'host': '127.0.0.1', 'port': 8444}
2021-08-07T05:24:17.457 daemon chia.daemon.server         : INFO     Websocket exception. Closing websocket with chia_full_node code = 1006 (connection closed abnormally [internal]), no reason Traceback (most recent call last):
</code>

made me think it might be the same culprit as #7845, #7458, #7684 and/or #7943.

I started logging when it happens and there does not seem to be any particular period/duration when it happens:

**Date | Time**
28.07.2021 | 08:08:58
29.07.2021 | 12:38:26
30.07.2021 | 16:10:59
02.08.2021 | 23:13:31
03.08.2021 | 04:06:08
04.08.2021 | 04:18:25
04.08.2021 | 22:02:58
07.08.2021 | 16:52:18
07.08.2021 | 21:20:00
09.08.2021 | 11:41:02
09.08.2021 | 17:07:15

**Comment by keliew** [comment]
> Sadly the fix is here, but no one will approve / merge it in to resolve the code 1006 websockets error. So annoying!
> #6305

Have you tested that? It seems to be quite an easy fix to test. Just change it, and restart. Their comments in #6305 worth noting though.

**Comment by archery1998** [comment]
> Sadly the fix is here, but no one will approve / merge it in to resolve the code 1006 websockets error. So annoying!
> #6305

This does not fix the issue.
