### ISSUE TITLE
Fail to create daemon

### ISSUE THREAD

**Issue by 26z1a** [Chia-Network/chia-blockchain#8022]
can't launch chia successful after reboot the pc(both gui and cli), on gui it stucks on"connecting to wallet" and on cli it's like:

```
PS C:\Users\MYUSERNAMEHERE\AppData\Local\chia-blockchain\app-1.2.3\resources\app.asar.unpacked\daemon> .\chia.exe start farmer

Daemon not started yet
Starting daemon
Daemon not started yet
Failed to create the chia daemon
```

log looks like same for both gui and cli :

```
2021-08-11T00:49:02.443 daemon __main__                   : INFO     Starting Daemon Server
2021-08-11T00:49:02.443 daemon __main__                   : INFO     Not implemented
2021-08-11T00:49:02.445 daemon __main__                   : INFO     Waiting Daemon WebSocketServer closure
2021-08-11T00:49:03.279 daemon asyncio                    : ERROR    Accept failed on a socket
socket: <asyncio.TransportSocket fd=940, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('127.0.0.1', 55400)>
Traceback (most recent call last):
  File "asyncio\proactor_events.py", line 818, in loop
  File "asyncio\windows_events.py", line 812, in _poll
  File "asyncio\windows_events.py", line 561, in finish_accept
OSError: [WinError 10014] The system detected an invalid pointer address in attempting to use a pointer argument in a call
2021-08-11T00:49:03.279 daemon asyncio                    : ERROR    Task exception was never retrieved
future: <Task finished name='Task-3' coro=<IocpProactor.accept.<locals>.accept_coro() done, defined at asyncio\windows_events.py:563> exception=OSError(10014, 'The system detected an invalid pointer address in attempting to use a pointer argument in a call', None, 10014, None)>
Traceback (most recent call last):
  File "asyncio\windows_events.py", line 566, in accept_coro
  File "asyncio\proactor_events.py", line 818, in loop
  File "asyncio\windows_events.py", line 812, in _poll
  File "asyncio\windows_events.py", line 561, in finish_accept
OSError: [WinError 10014] The system detected an invalid pointer address in attempting to use a pointer argument in a call
```

OS: win10 pro n 21h1 build 19043.1110

**Comment by loppefaaret** [comment]
Do you have any other Hyper-V / Docker / Virtual Machines services running on the system ?
at times, the `winnat` service can reserve port ranges that covers the daemons port 55400

**Comment by 26z1a** [comment]
> Do you have any other Hyper-V / Docker / Virtual Machines services running on the system ?
> at times, the `winnat` service can reserve port ranges that covers the daemons port 55400

no hyper-v is installed but not using. the others haven't install on the system
