### ISSUE TITLE
看看你的钱包是不是一样[BUG]

### ISSUE THREAD

**Issue by 405421622** [Chia-Network/chia-blockchain#8066]
Bug wallet seems to run normally. Synchronization, a preliminary screening. But Full Node Connection Kib upload the farm inside is always zero. Download data are available. Asked around a lot of people have the same error. Hope to be official

**To Reproduce**

2021-08-14T19:25:52.462 full_node full_node_server        : ERROR    Exception: Failed to fetch block 714233 from None, timed out, None. Traceback (most recent call last):
  File "chia\server\server.py", line 528, in wrapped_coroutine
  File "chia\full_node\full_node_api.py", line 106, in new_peak
  File "chia\full_node\full_node.py", line 397, in new_peak
  File "chia\full_node\full_node.py", line 331, in short_sync_backtrack
  File "chia\full_node\full_node.py", line 316, in short_sync_backtrack
ValueError: Failed to fetch block 714233 from None, timed out

2021-08-14T19:25:52.463 full_node full_node_server        : ERROR    Exception: Failed to fetch block 714233 from None, timed out <class 'ValueError'>, closing connection None. Traceback (most recent call last):
  File "chia\server\server.py", line 538, in api_call
  File "asyncio\tasks.py", line 442, in wait_for
  File "chia\server\server.py", line 535, in wrapped_coroutine
  File "chia\server\server.py", line 528, in wrapped_coroutine
  File "chia\full_node\full_node_api.py", line 106, in new_peak
  File "chia\full_node\full_node.py", line 397, in new_peak
  File "chia\full_node\full_node.py", line 331, in short_sync_backtrack
  File "chia\full_node\full_node.py", line 316, in short_sync_backtrack
ValueError: Failed to fetch block 714233 from None, timed out

**Expected behavior**

**Screenshots**

**Desktop**

![QQ图片20210814203957](https://user-images.githubusercontent.com/88928589/129447401-f1c0a7fd-4495-4980-90de-92c6def6c2fb.png)

**Additional context**

**Comment by chiazhang** [comment]
这个页面似乎是正常的，我的钱包和你的一样，用协议也是正常挖矿。同步偶尔会获取不到块，同步是否成功要看左边全节点那个页面，能连到其它节点，有上传下载记录就可以了。

**Comment by loppefaaret** [comment]
dupe #8065
