### ISSUE TITLE
[BUG] what's this error mean?   There are many such errors in my debug log .thank you！

### ISSUE THREAD

**Issue by tracy32792** [Chia-Network/chia-blockchain#8067]
2021-08-05T22:51:09.440 full_node full_node_server        : ERROR    Exception: Failed to fetch block 673118 from None, timed out <class 'ValueError'>, closing connection None. Traceback (most recent call last):
  File "chia\server\server.py", line 536, in api_call
  File "asyncio\tasks.py", line 414, in wait_for
  File "chia\server\server.py", line 533, in wrapped_coroutine
  File "chia\server\server.py", line 526, in wrapped_coroutine
  File "chia\full_node\full_node_api.py", line 104, in new_peak
  File "chia\full_node\full_node.py", line 373, in new_peak
  File "chia\full_node\full_node.py", line 322, in short_sync_backtrack
  File "chia\full_node\full_node.py", line 307, in short_sync_backtrack
ValueError: Failed to fetch block 673118 from None, timed out

**Comment by xxxguoxinxxx** [comment]
很多人都有这问题，不知道有没有被重视
