### ISSUE TITLE
[BUG]我的这个问题困扰我很久了。

### ISSUE THREAD

**Issue by JustcallmeXiaoLi** [Chia-Network/chia-blockchain#8086]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop**

收割机客户端
- OS: 
- OS Version/Flavor: 
- CPU: 
钱包机
- OS: 
- OS Version/Flavor: 
- CPU: 

总是提示错误信息为：
2021-08-16T11:00:55.552 daemon __main__                   : ERROR    Unexpected exception trying to send to websocket: code = 1006 (connection closed abnormally [internal]), no reason Traceback (most recent call last):
  File "asyncio\windows_events.py", line 538, in finish_send
OSError: [WinError 64] 指定的网络名不再可用。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "websockets\protocol.py", line 1077, in write_frame
  File "websockets\protocol.py", line 306, in _drain
  File "websockets\protocol.py", line 1077, in write_frame
  File "websockets\protocol.py", line 306, in _drain
  File "websockets\protocol.py", line 1077, in write_frame
  File "websockets\protocol.py", line 306, in _drain
  File "websockets\protocol.py", line 1077, in write_frame
  File "websockets\protocol.py", line 318, in _drain
  File "websockets\protocol.py", line 299, in _drain_helper
  File "websockets\protocol.py", line 827, in transfer_data
  File "websockets\protocol.py", line 895, in read_message
  File "websockets\protocol.py", line 971, in read_data_frame
  File "websockets\protocol.py", line 1047, in read_frame
  File "websockets\framing.py", line 105, in read
  File "asyncio\streams.py", line 723, in readexactly
  File "asyncio\streams.py", line 517, in _wait_for_data
  File "asyncio\proactor_events.py", line 379, in _loop_writing
  File "asyncio\windows_events.py", line 812, in _poll
  File "asyncio\windows_events.py", line 542, in finish_send
ConnectionResetError: [WinError 64] 指定的网络名不再可用。

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\a\chia-blockchain\chia-blockchain\venv\Lib\site-packages\chia\daemon\server.py", line 187, in safe_handle
  File "websockets\protocol.py", line 567, in send
  File "websockets\protocol.py", line 1083, in write_frame
  File "websockets\protocol.py", line 803, in ensure_open
websockets.exceptions.ConnectionClosedError: code = 1006 (connection closed abnormally [internal]), no reason

我根本就没有这个D:\a\chia-blockchain的这个目录，新安装的系统，收割机客户端有25台，总算力大概是4P左右,每天增量为700TB

**Comment by JustcallmeXiaoLi** [comment]
收割机客户端

    OS:linux
    OS Version/Flavor: ubuntu20.04 server
    CPU:2680v2
    钱包机
    OS:windows
    OS Version/Flavor:windows10专业工作站X64
    CPU:5950X

**Comment by JustcallmeXiaoLi** [comment]
农田，农场，还有农业合作社点了半天都没有反应。

**Comment by keliew** [comment]
for the harvester, could you try https://github.com/Chia-Network/chia-blockchain/pull/8009?

probably it's overloaded and then crashed the daemon/farmer/etc.

could you also turn on log level `INFO` and try to catch what happens before those errors?

**Comment by JustcallmeXiaoLi** [comment]
我的收割机客户端设置的日志等级就是INFO，总是提示2021-08-15T12:26:02.614 harvester chia.harvester.harvester: WARNING  Looking up qualities on /mnt/data/d6/plot-k32-2021-08-11-22-44-****************************************.plot took: 5.093957424163818. This should be below 5 seconds to minimize risk of losing rewards.

**Comment by elliottback** [comment]
I was getting this a lot with python 3.7 and upgrading to a 3.9 docker image resolved it mysteriously.

**Comment by keliew** [comment]
Good point. https://github.com/Chia-Network/chia-blockchain/pull/6703
