### ISSUE TITLE
[BUG]'PoolWallet' object has no attribute 'generate_signed_transaction'

### ISSUE THREAD

**Issue by cszhi** [Chia-Network/chia-blockchain#8096]
**Describe the bug**
When Send chia to another wallet, I get the following exception：
```
chia wallet send  -t xch1ppw98spccx50l3pqrf56ww7fw0ev4mj9hdz8mpjzxe6a2kfpk0rsna36pw -a 0.05 -i 2 
Submitting transaction...
Exception from 'wallet' {'error': "'PoolWallet' object has no attribute 'generate_signed_transaction'", 'success': False}
```

debug log:
```
2021-08-17T00:57:31.359 wallet chia.rpc.rpc_server        : WARNING  Error while handling message: Traceback (most recent call last):
  File "/opt/chia-blockchain/chia/rpc/rpc_server.py", line 81, in inner
    res_object = await f(request_data)
  File "/opt/chia-blockchain/chia/rpc/wallet_rpc_api.py", line 714, in send_transaction
    tx: TransactionRecord = await wallet.generate_signed_transaction(amount, puzzle_hash, fee)
AttributeError: 'PoolWallet' object has no attribute 'generate_signed_transaction'
```

My wallet：
```
chia wallet show
Wallet height: 726105
Sync status: Synced
Balances, fingerprint: 600143915
Wallet ID 1 type STANDARD_WALLET Chia Wallet
   -Total Balance: 0.0 xch (0 mojo)
   -Pending Total Balance: 0.0 xch (0 mojo)
   -Spendable: 0.0 xch (0 mojo)
Wallet ID 2 type POOLING_WALLET Pool wallet
   -Total Balance: 1.75 xch (1750000000000 mojo)
   -Pending Total Balance: 1.75 xch (1750000000000 mojo)
   -Spendable: 1.75 xch (1750000000000 mojo)
```
**To Reproduce**

On the cli, `chia wallet send  -t xch1ppw98spccx50l3pqrf56ww7fw0ev4mj9hdz8mpjzxe6a2kfpk0rsna36pw -a 0.05 -i 2 `

**Expected behavior**
chia can be send to another wallet

**Desktop**

- OS: Linux
- OS Version/Flavor: Ubuntu 20.04.2 LTS
- Blockchain: 1.2.3

**Comment by cszhi** [comment]
wrong

**Comment by SongyuanHan** [comment]
I also encounter this problem. who knows why and how to trans from poll wallet? thanks

**Comment by SongyuanHan** [comment]
we should claim from pool wallet first. then transfer coin from standard wallet.
chia plotnft claim -f <fontprint> -i <poolwallet-id>
After confirmation, do transfer.
