### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by 405421622** [Chia-Network/chia-blockchain#8099]
**Describe the bug**

2021-08-17T16:06:28.870 full_node full_node_server        : WARNING  Banning 94.232.133.44 for 10 seconds
2021-08-17T16:06:28.871 full_node full_node_server        : WARNING  Invalid handshake with peer {'host': '94.232.133.44', 'port': 8444}. Maybe the peer is running old software.
2021-08-17T16:07:18.793 full_node full_node_server        : ERROR    Exception: Failed to fetch block 727548 from {'host': '91.122.56.17', 'port': 8444}, timed out, {'host': '91.122.56.17', 'port': 8444}. Traceback (most recent call last):
  File "chia\server\server.py", line 528, in wrapped_coroutine
  File "chia\full_node\full_node_api.py", line 106, in new_peak
  File "chia\full_node\full_node.py", line 397, in new_peak
  File "chia\full_node\full_node.py", line 331, in short_sync_backtrack
  File "chia\full_node\full_node.py", line 316, in short_sync_backtrack
ValueError: Failed to fetch block 727548 from {'host': '91.122.56.17', 'port': 8444}, timed out

2021-08-17T16:07:18.794 full_node full_node_server        : ERROR    Exception: Failed to fetch block 727548 from {'host': '91.122.56.17', 'port': 8444}, timed out <class 'ValueError'>, closing connection {'host': '91.122.56.17', 'port': 8444}. Traceback (most recent call last):
  File "chia\server\server.py", line 538, in api_call
  File "asyncio\tasks.py", line 442, in wait_for
  File "chia\server\server.py", line 535, in wrapped_coroutine
  File "chia\server\server.py", line 528, in wrapped_coroutine
  File "chia\full_node\full_node_api.py", line 106, in new_peak
  File "chia\full_node\full_node.py", line 397, in new_peak
  File "chia\full_node\full_node.py", line 331, in short_sync_backtrack
  File "chia\full_node\full_node.py", line 316, in short_sync_backtrack
ValueError: Failed to fetch block 727548 from {'host': '91.122.56.17', 'port': 8444}, timed out

2021-08-17T16:07:28.798 full_node full_node_server        : WARNING  Banning 91.122.56.17 for 10 seconds
2021-08-17T16:16:31.321 full_node full_node_server        : WARNING  Cannot write to closing transport 172.117.187.46
2021-08-17T16:53:54.080 full_node full_node_server        : WARNING  Cannot write to closing transport 178.149.200.225
2021-08-17T16:57:13.810 full_node full_node_server        : WARNING  Cannot write to closing transport 62.73.84.81
2021-08-17T17:03:47.814 full_node full_node_server        : WARNING  Invalid handshake with peer {'host': '155.133.91.30', 'port': 6899}. Maybe the peer is running old software.
重现
   这个什么意思.有2P的算力目前20天没爆块了.求解决方案

-

**Comment by xxxguoxinxxx** [comment]
不爆块应该不是这个原因，估计是要控制一下概率

**Comment by 405421622** [comment]
还能控制爆块概率吗？------------------&nbsp;原始邮件&nbsp;------------------
***@***.***&gt;
发送时间:&nbsp;2021年8月17日(星期二) 晚上7:03
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Chia-Network/chia-blockchain] [BUG] (#8099)

**Comment by xxxguoxinxxx** [comment]
猜测而已

**Comment by emlowe** [comment]
There does not appear to be a bug here.
