### ISSUE TITLE
[BUG] farmer chia.farmer.farmer : ERROR Harvester did not respond. You might need to update harvester to the latest version[BUG]

### ISSUE THREAD

**Issue by Drakanus** [Chia-Network/chia-blockchain#8191]
**Describe the bug**
Every few hours "last attempted proof " stops. I kill GUI, restart the windows then start it again.. When I check log file it shows:

2021-08-24T11:11:31.680 farmer chia.farmer.farmer         : ERROR    Harvester did not respond. You might need to update harvester to the latest version
2021-08-24T11:13:02.723 farmer chia.farmer.farmer         : ERROR    Harvester did not respond. You might need to update harvester to the latest version
2021-08-24T11:14:33.746 farmer chia.farmer.farmer         : ERROR    Harvester did not respond. You might need to update harvester to the latest version
2021-08-24T11:16:04.772 farmer chia.farmer.farmer         : ERROR    Harvester did not respond. You might need to update harvester to the latest version
2021-08-24T11:17:35.791 farmer chia.farmer.farmer         : ERROR    Harvester did not respond. You might need to update harvester to the latest version
2021-08-24T11:19:06.829 farmer chia.farmer.farmer         : ERROR    Harvester did not respond. You might need to update harvester to the latest version
2021-08-24T11:20:37.847 farmer chia.farmer.farmer         : ERROR    Harvester did not respond. You might need to update harvester to the latest version
2021-08-24T11:21:59.538 daemon __main__                   : ERROR    Unexpected exception trying to send to websocket: code = 1006 (connection closed abnormally [internal]), no reason Traceback (most recent call last):
  File "websockets\protocol.py", line 827, in transfer_data
  File "websockets\protocol.py", line 895, in read_message
  File "websockets\protocol.py", line 971, in read_data_frame
  File "websockets\protocol.py", line 1047, in read_frame
  File "websockets\framing.py", line 105, in read
  File "asyncio\streams.py", line 723, in readexactly
  File "asyncio\streams.py", line 517, in _wait_for_data
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\a\chia-blockchain\chia-blockchain\venv\Lib\site-packages\chia\daemon\server.py", line 187, in safe_handle
  File "websockets\protocol.py", line 555, in send
  File "websockets\protocol.py", line 812, in ensure_open
websockets.exceptions.ConnectionClosedError: code = 1006 (connection closed abnormally [internal]), no reason

2021-08-24T11:22:08.868 farmer chia.farmer.farmer         : ERROR    Harvester did not respond. You might need to update harvester to the latest version

**Desktop**

- OS: Windows10
- Chia is on the 1.2.3 version (newest one)

**Comment by overlords** [comment]
Bug+1

**Comment by berlef80** [comment]
Same issue
