### ISSUE TITLE
[BUG] What does this error report mean? Does it affect farming

### ISSUE THREAD

**Issue by tracy32792** [Chia-Network/chia-blockchain#8193]
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x00000221BA0778B0>
Traceback (most recent call last):
  File "asyncio\proactor_events.py", line 116, in __del__
  File "asyncio\proactor_events.py", line 108, in close
  File "asyncio\base_events.py", line 746, in call_soon
  File "asyncio\base_events.py", line 510, in _check_closed
RuntimeError: Event loop is closed

**Comment by emlowe** [comment]
Insufficient details provided - please post more of the log with DEBUG enabled
