### ISSUE TITLE
Can't connect to the wallet after 1.2.5 update -- on 3 different harvesters

### ISSUE THREAD

**Issue by hejz0r** [Chia-Network/chia-blockchain#8267]
`2021-08-29T17:07:21.278 farmer farmer                     : INFO     Reconnecting to peer {'host': '127.0.0.1', 'port': 8444}
2021-08-29T17:07:21.763 wallet wallet                     : INFO     Reconnecting to peer {'host': '127.0.0.1', 'port': 8444}
2021-08-29T17:07:22.280 farmer farmer_server              : INFO     Cannot connect to host 127.0.0.1:8444 ssl:<ssl.SSLContext object at 0x0000006EC7BD7BC0> [Komputer zdalny odrzucił połączenie sieciowe]
2021-08-29T17:07:22.775 wallet wallet_server              : INFO     Cannot connect to host 127.0.0.1:8444 ssl:<ssl.SSLContext object at 0x000000DA150F1540> [Komputer zdalny odrzucił połączenie sieciowe]
2021-08-29T17:07:25.288 farmer farmer                     : INFO     Reconnecting to peer {'host': '127.0.0.1', 'port': 8444}
2021-08-29T17:07:25.777 wallet wallet                     : INFO     Reconnecting to peer {'host': '127.0.0.1', 'port': 8444}
2021-08-29T17:07:26.295 farmer farmer_server              : INFO     Cannot connect to host 127.0.0.1:8444 ssl:<ssl.SSLContext object at 0x0000006EC7BD7B40> [Komputer zdalny odrzucił połączenie sieciowe]
2021-08-29T17:07:26.780 wallet wallet_server              : INFO     Cannot connect to host 127.0.0.1:8444 ssl:<ssl.SSLContext object at 0x000000DA150F1140> [Komputer zdalny odrzucił połączenie sieciowe]`

3 different harvesters, 3 different networks and PC's ...

Wallet Status : Not Synced // Full Node Synced

**Comment by ai2020xml** [comment]
same issue have with my chia program . all time trying to connect to wallet

**Comment by sven3550** [comment]
Same thing: 
`2021-08-30T13:31:24.984 farmer farmer                     : INFO     Reconnecting to peer {'host': '127.0.0.1', 'port': 8444}
2021-08-30T13:31:24.985 farmer farmer_server              : DEBUG    Connecting: wss://127.0.0.1:8444/ws, Peer info: {'host': '127.0.0.1', 'port': 8444}
2021-08-30T13:31:24.986 farmer farmer_server              : INFO     Cannot connect to host 127.0.0.1:8444 ssl:<ssl.SSLContext object at 0x7fb544236a40> [Connect call failed ('127.0.0.1', 8444)]
2021-08-30T13:31:25.230 wallet wallet                     : INFO     Reconnecting to peer {'host': '127.0.0.1', 'port': 8444}
2021-08-30T13:31:25.231 wallet wallet_server              : DEBUG    Connecting: wss://127.0.0.1:8444/ws, Peer info: {'host': '127.0.0.1', 'port': 8444}
2021-08-30T13:31:25.232 wallet wallet_server              : INFO     Cannot connect to host 127.0.0.1:8444 ssl:<ssl.SSLContext object at 0x7fb6c53801c0> [Connect call failed ('127.0.0.1', 8444)]`

**Comment by ElyadM** [comment]
Hi, i did also update from 1.2.3 to 1.2.5 and now i am stocking at connecting to wallet,, (ubuntu 21.04)


venv) mars@mars-HP-Z440-Workstation:~/chia-blockchain/chia-blockchain-gui$ npm run electron &
[1] 6530
(venv) mars@mars-HP-Z440-Workstation:~/chia-blockchain/chia-blockchain-gui$ 
> chia-blockchain@0.0.0 electron
> electron .

/home/mars/chia-blockchain/app.asar.unpacked/daemon
false
startUrl file:///home/mars/chia-blockchain/chia-blockchain-gui/build/renderer/index.html
/home/mars/chia-blockchain/app.asar.unpacked/daemon
false
/home/mars/chia-blockchain/app.asar.unpacked/daemon
false
Running python script
Script ../chia/daemon/server.py
child process success
(node:6549) electron: The default of contextIsolation is deprecated and will be changing from false to true in a future release of Electron.  See https://github.com/electron/electron/issues/23506 for more information
stderr: Traceback (most recent call last):
  File "/home/mars/chia-blockchain/chia-blockchain-gui/../chia/daemon/server.py", line 19, in <module>
    from chia.cmds.init_funcs import check_keys, chia_init
  File "/home/mars/chia-blockchain/chia/cmds/init_funcs.py", line 9, in <module>
    from chia.consensus.coinbase import create_puzzlehash_for_pk
  File "/home/mars/chia-blockchain/chia/consensus/coinbase.py", line 3, in <module>
    from chia.types.blockchain_format.coin import Coin
  File "/home/mars/chia-blockchain/chia/types/blockchain_format/coin.py", line 8, in <module>
stderr:     from chia.util.streamable import Streamable, streamable
  File "/home/mars/chia-blockchain/chia/util/streamable.py", line 14, in <module>
    from chia.types.blockchain_format.program import Program, SerializedProgram
  File "/home/mars/chia-blockchain/chia/types/blockchain_format/program.py", line 10, in <module>
    from clvm_rs import STRICT_MODE, deserialize_and_run_program2, serialized_length, run_generator
ImportError: cannot import name 'run_generator' from 'clvm_rs' (/home/mars/chia-blockchain/venv/lib/python3.9/site-packages/clvm_rs.cpython-39-x86_64-linux-gnu.so)
closing code: 1

can you please advise how to fix this?! i am having 1689 plots and cant farm anymore...!!

**Comment by emlowe** [comment]
@ElyadM I suspect you forgot to `sh install.sh` after you upgraded (assuming you upgraded using git)

**Comment by emlowe** [comment]
@hejz0r Recommand stopping everything (`chia stop -d all`) and restarting your wallet

**Comment by emlowe** [comment]
Moving to support
