### ISSUE TITLE
Useless plotnft leads full_node process defunct 1.2.4 [BUG]

### ISSUE THREAD

**Issue by laozhang713** [Chia-Network/chia-blockchain#8281]
**Describe the bug**
Useless plotnft leads full_node process defunct 1.2.4

I plotnft in space pool . But I have a useless plotnft joined teepool.

Today, my process was defunct due to this useless teepool server error.

1. I think we should consider the process defunct after a problem with the pool server.

2. The problem of a pool server should not affect the rest of plotnft

**To Reproduce**
2021-08-31T03:47:42.131 full_node chia.full_node.full_node: INFO     Already compactified block: c8fb23caa338ccbd2d8eb0e987f0314c4e8d2f6bda3801c04556d9857ff06cd5. Ignoring.
2021-08-31T03:47:44.675 full_node chia.full_node.full_node: INFO     ⏲️  Finished signage point 32/64: CC: 8348657a5597b04c851b61965f5b7dae84c5c2bf6ff173a5a426fa7f6865a84c RC: 66c32e72ad255e74aaf317e183cd31e0f1e2088da3a79d0d09ce8918b285bce1 
2021-08-31T03:47:44.684 harvester chia.harvester.harvester: INFO     0 plots were eligible for farming c92ffdda34... Found 0 proofs. Time: 0.00017 s. Total 0 plots
2021-08-31T03:47:48.909 farmer chia.farmer.farmer         : INFO     GET /farmer response: {'authentication_public_key': '0x8210440318aaaab6666bb3e80d954ced45deaa0599f5d77e59fecf90e78ee443800b05d597203946112769b85dac4854', 'current_difficulty': 2, 'current_points': 0, 'payout_instructions': '1846ea4df3afa0705dda176e23d9d64c1fd2cbbbac28f9bdea4d5ed8ed076231'}
2021-08-31T03:48:50.247 wallet wallet_server              : INFO     Connection closed: 127.0.0.1, node id: a21f8f48a09370b1d523df74e80c594eac9703da14b9bbc38e0b0073e4a658a2
2021-08-31T03:48:53.174 wallet wallet                     : INFO     Reconnecting to peer {'host': '127.0.0.1', 'port': 8444}
2021-08-31T03:49:26.453 wallet wallet                     : INFO     Reconnecting to peer {'host': '127.0.0.1', 'port': 8444}
2021-08-31T03:49:50.223 farmer farmer_server              : INFO     Connection closed: 127.0.0.1, node id: a21f8f48a09370b1d523df74e80c594eac9703da14b9bbc38e0b0073e4a658a2
2021-08-31T03:49:50.223 farmer chia.farmer.farmer         : INFO     peer disconnected {'host': '127.0.0.1', 'port': 8444}
2021-08-31T03:49:53.210 farmer farmer                     : INFO     Reconnecting to peer {'host': '127.0.0.1', 'port': 8444}
2021-08-31T03:50:00.433 wallet wallet                     : INFO     Reconnecting to peer {'host': '127.0.0.1', 'port': 8444}
2021-08-31T03:50:27.125 farmer farmer                     : INFO     Reconnecting to peer {'host': '127.0.0.1', 'port': 8444}
2021-08-31T03:50:34.455 wallet wallet                     : INFO     Reconnecting to peer {'host': '127.0.0.1', 'port': 8444}
2021-08-31T03:51:00.426 farmer farmer                     : INFO     Reconnecting to peer {'host': '127.0.0.1', 'port': 8444}
2021-08-31T03:51:08.432 wallet wallet                     : INFO     Reconnecting to peer {'host': '127.0.0.1', 'port': 8444}
2021-08-31T03:51:34.427 farmer farmer                     : INFO     Reconnecting to peer {'host': '127.0.0.1', 'port': 8444}
2021-08-31T03:51:42.450 wallet wallet                     : INFO     Reconnecting to peer {'host': '127.0.0.1', 'port': 8444}
2021-08-31T03:51:53.242 farmer chia.farmer.farmer         : INFO     GET /farmer response: {'authentication_public_key': '0xafa5d46a717a415392b85358dad1f54169270dc292881aa29a5573a2f50613745c34781a0d19b920d64d7d8e5553a314', 'payout_instructions': '45591ae90361e6a545fa020d7e4041bc31f45b8bef8725d99d9f7883172fcfed', 'current_difficulty': 433, 'current_points': 29312}
2021-08-31T03:52:08.426 farmer farmer                     : INFO     Reconnecting to peer {'host': '127.0.0.1', 'port': 8444}
2021-08-31T03:52:16.433 wallet wallet                     : INFO     Reconnecting to peer {'host': '127.0.0.1', 'port': 8444}
2021-08-31T03:52:42.426 farmer farmer                     : INFO     Reconnecting to peer {'host': '127.0.0.1', 'port': 8444}
2021-08-31T03:52:50.452 wallet wallet                     : INFO     Reconnecting to peer {'host': '127.0.0.1', 'port': 8444}
**2021-08-31T03:52:54.603 farmer chia.farmer.farmer         : ERROR    Exception in GET /farmer https://vip.teepool.com:9443, Cannot connect to host vip.teepool.com:9443 ssl:<ssl.SSLContext object at 0x7f1854b864c0> [Name or service not known]**
2021-08-31T03:53:16.426 farmer farmer                     : INFO     Reconnecting to peer {'host': '127.0.0.1', 'port': 8444}
2021-08-31T03:53:24.433 wallet wallet                     : INFO     Reconnecting to peer {'host': '127.0.0.1', 'port': 8444}
2021-08-31T03:53:50.427 farmer farmer                     : INFO     Reconnecting to peer {'host': '127.0.0.1', 'port': 8444}
2021-08-31T03:53:56.982 farmer chia.farmer.farmer         : ERROR    Exception in GET /pool_info https://vip.teepool.com:9443, Cannot connect to host vip.teepool.com:9443 ssl:<ssl.SSLContext object at 0x7f1853d861c0> [Name or service not known]
2021-08-31T03:53:56.992 farmer chia.farmer.farmer         : ERROR    Exception in GET /farmer https://vip.teepool.com:9443, Cannot connect to host vip.teepool.com:9443 ssl:<ssl.SSLContext object at 0x7f1853c325c0> [Name or service not known]
2021-08-31T03:53:58.459 wallet wallet                     : INFO     Reconnecting to peer {'host': '127.0.0.1', 'port': 8444}
2021-08-31T03:54:24.426 farmer farmer                     : INFO     Reconnecting to peer {'host': '127.0.0.1', 'port': 8444}
2021-08-31T03:54:32.451 wallet wallet                     : INFO     Reconnecting to peer {'host': '127.0.0.1', 'port': 8444}
2021-08-31T03:54:58.367 farmer chia.farmer.farmer         : ERROR    Exception in GET /pool_info https://vip.teepool.com:9443, Cannot connect to host vip.teepool.com:9443 ssl:<ssl.SSLContext object at 0x7f18534a51c0> [Name or service not known]
2021-08-31T03:54:58.376 farmer chia.farmer.farmer         : ERROR    Exception in GET /farmer https://vip.teepool.com:9443, Cannot connect to host vip.teepool.com:9443 ssl:<ssl.SSLContext object at 0x7f18534a5ac0> [Name or service not known]
2021-08-31T03:54:58.576 farmer farmer                     : INFO     Reconnecting to peer {'host': '127.0.0.1', 'port': 8444}
2021-08-31T03:55:06.455 wallet wallet                     : INFO     Reconnecting to peer {'host': '127.0.0.1', 'port': 8444}
2021-08-31T03:55:24.208 daemon chia.daemon.server         : INFO     Websocket exception. Closing websocket with chia_full_node code = 1006 (connection closed abnormally [internal]), no reason Traceback (most recent call last):
  File "/root/chia-blockchain/venv/lib/python3.8/site-packages/websockets/protocol.py", line 827, in transfer_data
    message = await self.read_message()
  File "/root/chia-blockchain/venv/lib/python3.8/site-packages/websockets/protocol.py", line 895, in read_message
    frame = await self.read_data_frame(max_size=self.max_size)
  File "/root/chia-blockchain/venv/lib/python3.8/site-packages/websockets/protocol.py", line 971, in read_data_frame
    frame = await self.read_frame(max_size)
  File "/root/chia-blockchain/venv/lib/python3.8/site-packages/websockets/protocol.py", line 1047, in read_frame
    frame = await Frame.read(
  File "/root/chia-blockchain/venv/lib/python3.8/site-packages/websockets/framing.py", line 105, in read
    data = await reader(2)
  File "/usr/lib/python3.8/asyncio/streams.py", line 723, in readexactly
    await self._wait_for_data('readexactly')
  File "/usr/lib/python3.8/asyncio/streams.py", line 517, in _wait_for_data
    await self._waiter
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/chia-blockchain/chia/daemon/server.py", line 190, in safe_handle
    self.log.error(f"Unexpected exception trying to send to websocket: {e} {tb}")
  File "/root/chia-blockchain/venv/lib/python3.8/site-packages/websockets/protocol.py", line 439, in __aiter__
    yield await self.recv()
  File "/root/chia-blockchain/venv/lib/python3.8/site-packages/websockets/protocol.py", line 509, in recv
    await self.ensure_open()
  File "/root/chia-blockchain/venv/lib/python3.8/site-packages/websockets/protocol.py", line 812, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedError: code = 1006 (connection closed abnormally [internal]), no reason

2021-08-31T03:55:32.427 farmer farmer                     : INFO     Reconnecting to peer {'host': '127.0.0.1', 'port': 8444}
2021-08-31T03:55:40.450 wallet wallet                     : INFO     Reconnecting to peer {'host': '127.0.0.1', 'port': 8444}
2021-08-31T03:56:00.212 farmer chia.farmer.farmer         : ERROR    Exception in GET /pool_info https://vip.teepool.com:9443, Cannot connect to host vip.teepool.com:9443 ssl:<ssl.SSLContext object at 0x7f1852a6d9c0> [Name or service not known]
2021-08-31T03:56:00.222 farmer chia.farmer.farmer         : ERROR    Exception in GET /farmer https://vip.teepool.com:9443, Cannot connect to host vip.teepool.com:9443 ssl:<ssl.SSLContext object at 0x7f18525f8640> [Name or service not known]
2021-08-31T03:56:06.429 farmer farmer                     : INFO     Reconnecting to peer {'host': '127.0.0.1', 'port': 8444}
2021-08-31T03:56:14.429 wallet wallet                     : INFO     Reconnecting to peer {'host': '127.0.0.1', 'port': 8444}
2021-08-31T03:56:40.427 farmer farmer                     : INFO     Reconnecting to peer {'host': '127.0.0.1', 'port': 8444}
2021-08-31T03:56:48.450 wallet wallet                     : INFO     Reconnecting to peer {'host': '127.0.0.1', 'port': 8444}
2021-08-31T03:57:02.456 farmer chia.farmer.farmer         : ERROR    Exception in GET /pool_info https://vip.teepool.com:9443, Cannot connect to host vip.teepool.com:9443 ssl:<ssl.SSLContext object at 0x7f18538dfcc0> [Name or service not known]

- OS: Ubuntu 20 service, Chia 1.2.4

**Comment by emlowe** [comment]
The issue with the pool is not related to your other errors. It appears your full node is not running. If you want to you can switch whatever NFT you have to self-pooling.

**Comment by laozhang713** [comment]
> The issue with the pool is not related to your other errors. It appears your full node is not running. If you want to you can switch whatever NFT you have to self-pooling.


I know that modifying a pool can solve this problem. But the instability of the pool will cause full_node process defunct 。When the pool is normal, full_node cannot recover normally
