### ISSUE TITLE
[BUG] chia hardester failed to find any pilot to hardvest.

### ISSUE THREAD

**Issue by spamkutu** [Chia-Network/chia-blockchain#8330]
my hardvester cannot see any pilot and its reclame add pliot with the flower picture just like start i restarted cmd much no effect
i were also restarted gui with no change since than i cant restart becouse i had to wait my five pilot finish first its almost %80 arround but not going much so so slow hope its all done until the morning and i could restart my windows too and hope after restart it will be all good and my hardvester reseen my pilots too i am hopeless atm and hope my pilots could finish to i have half chance very weird :(

here below the err reply caused exception bug.
please find a clue why that thats and fix as soon thanks.
C:\Users\INT>chia start farmer -r
chia_harvester: started
chia_farmer: Error, timeout.
stop failed
chia_farmer: Task exception was never retrieved
future: <Task finished name='Task-5' coro=<DaemonProxy.start..listener() done, defined at chia\daemon\client.py:29> exception=ConnectionClosedError('code = 1006 (connection closed abnormally [internal]), no reason')>
Traceback (most recent call last):
File "websockets\protocol.py", line 827, in transfer_data
File "websockets\protocol.py", line 895, in read_message
File "websockets\protocol.py", line 971, in read_data_frame
File "websockets\protocol.py", line 1047, in read_frame
File "websockets\framing.py", line 105, in read
File "asyncio\streams.py", line 723, in readexactly
File "asyncio\streams.py", line 517, in _wait_for_data
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
File "chia\daemon\client.py", line 32, in listener
File "websockets\protocol.py", line 509, in recv
File "websockets\protocol.py", line 812, in ensure_open
websockets.exceptions.ConnectionClosedError: code = 1006 (connection closed abnormally [internal]), no reason
Error, timeout.
chia_farmer failed to start. Error: no response
Task exception was never retrieved
future: <Task finished name='Task-22' coro=<WebSocketCommonProtocol.send() done, defined at websockets\protocol.py:521> exception=ConnectionClosedError('code = 1006 (connection closed abnormally [internal]), no reason')>
Traceback (most recent call last):
File "websockets\protocol.py", line 827, in transfer_data
File "websockets\protocol.py", line 895, in read_message
File "websockets\protocol.py", line 971, in read_data_frame
File "websockets\protocol.py", line 1047, in read_frame
File "websockets\framing.py", line 105, in read
File "asyncio\streams.py", line 723, in readexactly
File "asyncio\streams.py", line 517, in _wait_for_data
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
File "websockets\protocol.py", line 555, in send
File "websockets\protocol.py", line 803, in ensure_open
websockets.exceptions.ConnectionClosedError: code = 1006 (connection closed abnormally [internal]), no reason
Error, timeout.
Traceback (most recent call last):
File "D:\a\chia-blockchain\chia-blockchain\venv\Lib\site-packages\chia\cmds\chia.py", line 132, in
File "D:\a\chia-blockchain\chia-blockchain\venv\Lib\site-packages\chia\cmds\chia.py", line 128, in main
File "click\core.py", line 829, in call
File "click\core.py", line 782, in main
File "click\core.py", line 1259, in invoke
File "click\core.py", line 1066, in invoke
File "click\core.py", line 610, in invoke
File "click\decorators.py", line 21, in new_func
File "chia\cmds\start.py", line 14, in start_cmd
File "asyncio\base_events.py", line 642, in run_until_complete
File "chia\cmds\start_funcs.py", line 60, in async_start
File "chia\daemon\client.py", line 85, in is_running
TypeError: 'NoneType' object is not subscriptable
[102560] Failed to execute script 'chia' due to unhandled exception!

**Describe the bug**
Chia gui can not find any pilot looklike just started show pilot directories but its show always zero pilot and inform to add pilot.

**To Reproduce**
this happens first time no clue how to reproduce

**Screenshots**
![chibuggy](https://user-images.githubusercontent.com/13944520/132092553-bcd41468-04e3-45fc-a208-467d0ef302f9.jpg)

**Desktop**

- OS: Windows 10
- OS Version/Flavor:  Pro
- CPU: Intel(R) Core(TM) i7-9850H CPU

**Comment by loppefaaret** [comment]
dupe #8322 
please refer to the above
