### ISSUE TITLE
[BUG] Runtime Error: No Keys exist. Please run 'chia keys generate' or open the UI.

### ISSUE THREAD

**Issue by forReason** [Chia-Network/chia-blockchain#8352]
This is a Duplicate of #7099 which got automatically closed. the issue still persists on 1.2.5

**Describe the bug**
I have a major issue, farming with chia. The Farmer won't start reliably, this makes unattended farming impossible.

**To Reproduce**
Execute batch script in order to start farmer:
 ```
cd C:\Users\%username%\AppData\Local\chia-blockchain\app-1.1.7\resources\app.asar.unpacked\daemon  
chia start farmer
```

Result (around 70% of tries):

> Traceback (most recent call last):
  File "chia\server\start_farmer.py", line 68, in <module>
  File "chia\server\start_farmer.py", line 63, in main
  File "chia\server\start_farmer.py", line 38, in service_kwargs_for_farmer
  File "chia\farmer\farmer.py", line 73, in __init__
RuntimeError: No keys exist. Please run 'chia keys generate' or open the UI.
[10976] Failed to execute script start_farmer

**Expected behavior**
farmer detects saved keys and starts apropriately
![image](https://user-images.githubusercontent.com/12736950/125470646-afa73586-19b9-4274-a373-8b42de41052c.png)

**Desktop (please complete the following information):**

- OS: Windows 10
- OS Version 20H2 Build 19042.1052
- CPU: AMD Ryzen 3600
- Chia Version: 1.2

**Additional context**
The Keys are definitely there. The Gui will always start without any issue.

Executing the script again mostly resolves the issue. So the keys are definitely there.

- OS: 
- OS Version/Flavor: 
- CPU: 

**Additional context**

**Comment by forReason** [comment]
```
C:\Windows\system32>C:

C:\Windows\system32>cd C:\Users\julia\AppData\Local\chia-blockchain\app-1.2.5\resources\app.asar.unpacked\daemon

C:\Users\julia\AppData\Local\chia-blockchain\app-1.2.5\resources\app.asar.unpacked\daemon>chia start farmer
Daemon not started yet
Starting daemon
chia_harvester: started
chia_farmer: started
chia_full_node: started
chia_wallet: started
Traceback (most recent call last):
File "D:\a\chia-blockchain\chia-blockchain\venv\Lib\site-packages\chia\server\start_farmer.py", line 67, in
File "D:\a\chia-blockchain\chia-blockchain\venv\Lib\site-packages\chia\server\start_farmer.py", line 63, in main
File "chia\server\start_service.py", line 255, in run_service
File "asyncio\runners.py", line 44, in run
File "asyncio\base_events.py", line 642, in run_until_complete
File "chia\server\start_service.py", line 249, in async_run_service
File "chia\server\start_service.py", line 171, in run
File "chia\server\start_service.py", line 135, in start
File "chia\farmer\farmer.py", line 183, in _start
File "chia\farmer\farmer.py", line 148, in setup_keys
RuntimeError: No keys exist. Please run 'chia keys generate' or open the UI.
[2032] Failed to execute script 'start_farmer' due to unhandled exception!

Issue still exists on 1.2.5
```

**Comment by jack60612** [comment]
> ```
> C:\Windows\system32>C:
> 
> C:\Windows\system32>cd C:\Users\julia\AppData\Local\chia-blockchain\app-1.2.5\resources\app.asar.unpacked\daemon
> 
> C:\Users\julia\AppData\Local\chia-blockchain\app-1.2.5\resources\app.asar.unpacked\daemon>chia start farmer
> Daemon not started yet
> Starting daemon
> chia_harvester: started
> chia_farmer: started
> chia_full_node: started
> chia_wallet: started
> Traceback (most recent call last):
> File "D:\a\chia-blockchain\chia-blockchain\venv\Lib\site-packages\chia\server\start_farmer.py", line 67, in
> File "D:\a\chia-blockchain\chia-blockchain\venv\Lib\site-packages\chia\server\start_farmer.py", line 63, in main
> File "chia\server\start_service.py", line 255, in run_service
> File "asyncio\runners.py", line 44, in run
> File "asyncio\base_events.py", line 642, in run_until_complete
> File "chia\server\start_service.py", line 249, in async_run_service
> File "chia\server\start_service.py", line 171, in run
> File "chia\server\start_service.py", line 135, in start
> File "chia\farmer\farmer.py", line 183, in _start
> File "chia\farmer\farmer.py", line 148, in setup_keys
> RuntimeError: No keys exist. Please run 'chia keys generate' or open the UI.
> [2032] Failed to execute script 'start_farmer' due to unhandled exception!
> 
> Issue still exists on 1.2.5
> ```

100% an issue with your setup as the library's used to get chias root dir are standard python libraries that everyone uses.
Your install might be corrupted or your windows might be. or just try linux

**Comment by hoffmang9** [comment]
If you run `chia keys generate` or `chia keys add` first, then this will work fine.

**Comment by hoffmang9** [comment]
Maybe the keys are not there. I bet your powershell user doesn't have permissions to open the windows keyring from that user. Try it from an Administrator powershell to confirm or rule out my suspicion.

**Comment by forReason** [comment]
@hoffmang9
The Keys do exist, the user has permissions to open the keyring:
![image](https://user-images.githubusercontent.com/12736950/132456236-6f41290e-7061-4cc5-a6aa-47095f17465c.png)

a permission issue would result in consistent behavior I guess. But when the issue happens, it will work after triggering the Task one more time (with the same user than before)

@jack60612 I doubt it. I got chia executables from the official webpage, with versions 1.1.7, 1.2.0, 1.2.1, 1.2.3 and 1.2.5
Ill have more farmers soon, then I can tell if its an issue on that particular machine.
Linux is an option I'm evaluating at the time.

**Comment by emlowe** [comment]
Please put your logs into DEBUG and attach any relevant log lines from failures. `chia configure --set-log-level DEBUG`

**Comment by emlowe** [comment]
Closing issue due to no response to request for log information
