### ISSUE TITLE
[BUG] Hardversters sleeping cant awake

### ISSUE THREAD

**Issue by spamkutu** [Chia-Network/chia-blockchain#8355]
**Describe the bug**
chia start farmer progress cant help all my pilots look like green but i checked hardvester last check was yesterday so no working,
chia start farmer also not succeced.

here by err;
------------

C:\Users\INT>farmfarm

C:\Users\INT>chia start farmer -r
chia_harvester: stopped
chia_harvester: started
chia_farmer: Error, timeout.
stop failed
chia_farmer: Error, timeout.
chia_farmer failed to start. Error: no response
Error, timeout.
Traceback (most recent call last):
  File "D:\a\chia-blockchain\chia-blockchain\venv\Lib\site-packages\chia\cmds\chia.py", line 132, in <module>
  File "D:\a\chia-blockchain\chia-blockchain\venv\Lib\site-packages\chia\cmds\chia.py", line 128, in main
  File "click\core.py", line 829, in __call__
  File "click\core.py", line 782, in main
  File "click\core.py", line 1259, in invoke
  File "click\core.py", line 1066, in invoke
  File "click\core.py", line 610, in invoke
  File "click\decorators.py", line 21, in new_func
  File "chia\cmds\start.py", line 14, in start_cmd
  File "asyncio\base_events.py", line 642, in run_until_complete
  File "chia\cmds\start_funcs.py", line 60, in async_start
  File "chia\daemon\client.py", line 85, in is_running
TypeError: 'NoneType' object is not subscriptable
[18608] Failed to execute script 'chia' due to unhandled exception!

C:\Users\INT>farmfarm

C:\Users\INT>chia start farmer -r
chia_harvester: stopped
chia_harvester: started
chia_farmer: stopped
chia_farmer: started
chia_full_node: Error, timeout.
stop failed
chia_full_node: Error, timeout.
chia_full_node failed to start. Error: no response
Error, timeout.
Traceback (most recent call last):
  File "D:\a\chia-blockchain\chia-blockchain\venv\Lib\site-packages\chia\cmds\chia.py", line 132, in <module>
  File "D:\a\chia-blockchain\chia-blockchain\venv\Lib\site-packages\chia\cmds\chia.py", line 128, in main
  File "click\core.py", line 829, in __call__
  File "click\core.py", line 782, in main
  File "click\core.py", line 1259, in invoke
  File "click\core.py", line 1066, in invoke
  File "click\core.py", line 610, in invoke
  File "click\decorators.py", line 21, in new_func
  File "chia\cmds\start.py", line 14, in start_cmd
  File "asyncio\base_events.py", line 642, in run_until_complete
  File "chia\cmds\start_funcs.py", line 60, in async_start
  File "chia\daemon\client.py", line 85, in is_running
TypeError: 'NoneType' object is not subscriptable
[14768] Failed to execute script 'chia' due to unhandled exception!

- OS: Windows 10
- OS Version/Flavor: pro
- CPU: Intel I7

**Comment by loppefaaret** [comment]
does this persist after a reboot ?
could you check your `debug.log` file located under your users folder `~\.chia\mainnet\log\` for any `ERROR` or `WARNING` entries ?

**Comment by spamkutu** [comment]
Its ok now after cold reboot but yes i have alot alot alot warn and errors in the log entries i will share that log when that happens again and hope it wont happen becouse its not give us any clue if we not check the last hardvest time.

**Comment by emlowe** [comment]
Closing issue per recent comments
