### ISSUE TITLE
BUG WITH NPM INSTALL

### ISSUE THREAD

**Issue by ProfyTourny** [Chia-Network/chia-blockchain#837]
Dear
I have tried apt remove, many times, many ways, nothing still
Latest Ubuntu 20.04
Kindly,
LOG :
/home/proftournesol/Chia/Beta26/Chia-blockchain/electron-react/node_modules/electron/index.js:14
    throw new Error('Electron failed to install correctly, please delete node_modules/electron and try installing again')
    ^

Error: Electron failed to install correctly, please delete node_modules/electron and try installing again
    at getElectronPath (/home/proftournesol/Chia/Beta26/Chia-blockchain/electron-react/node_modules/electron/index.js:14:11)
    at Object.<anonymous> (/home/proftournesol/Chia/Beta26/Chia-blockchain/electron-react/node_modules/electron/index.js:18:18)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/home/proftournesol/Chia/Beta26/Chia-blockchain/electron-react/node_modules/electron/cli.js:3:16)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! chia-blockchain@ electron: `electron .`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the chia-blockchain@ electron script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-02-05T05_00_33_066Z-debug.log

**Comment by ProfyTourny** [comment]
A thorough reinstall worked. Sudo rm -r * , apt remove npm, apt remove nodejs 
Reinstalling in root mode
but activating in non root
Case closed
