### ISSUE TITLE
[BUG] local variable 'self' referenced before assignment

### ISSUE THREAD

**Issue by iRexLyys** [Chia-Network/chia-blockchain#8370]
What is the reason for this problem... I haven't been able to get paid properly from the pool for 2 weeks now I'm getting bored and I can't earn at all. I go to work, the system stops, I want an immediate solution to this, if it doesn't get better, pay my loan debt...

2021-09-07T10:35:35.342 harvester harvester_server        : ERROR    Exception: local variable 'self' referenced before assignment, {'host': '127.0.0.1', 'port': 8447}. Traceback (most recent call last):
  File "chia\server\server.py", line 528, in wrapped_coroutine
  File "chia\harvester\harvester_api.py", line 299, in request_plots
  File "<string>", line 11, in __init__
  File "chia\util\type_checking.py", line 87, in __post_init__
UnboundLocalError: local variable 'self' referenced before assignment

2021-09-07T10:35:35.342 harvester harvester_server        : ERROR    Exception: local variable 'self' referenced before assignment <class 'UnboundLocalError'>, closing connection {'host': '127.0.0.1', 'port': 8447}. Traceback (most recent call last):
  File "chia\server\server.py", line 538, in api_call
  File "asyncio\tasks.py", line 481, in wait_for
  File "chia\server\server.py", line 535, in wrapped_coroutine
  File "chia\server\server.py", line 528, in wrapped_coroutine
  File "chia\harvester\harvester_api.py", line 299, in request_plots
  File "<string>", line 11, in __init__
  File "chia\util\type_checking.py", line 87, in __post_init__
UnboundLocalError: local variable 'self' referenced before assignment

2021-09-07T10:35:35.342 harvester harvester_server        : WARNING  Trying to ban localhost for 10, but will not ban
2021-09-07T10:35:35.342 farmer chia.farmer.farmer         : ERROR    Harvester did not respond. You might need to update harvester to the latest version
2021-09-07T12:44:40.339 full_node full_node_server        : WARNING  Invalid handshake with peer {'host': '85.15.179.190', 'port': 8744}. Maybe the peer is running old software.
2021-09-07T13:13:06.289 full_node full_node_server        : ERROR    Exception: Value -29417640 of size 25 does not fit into uint64 of size 64, {'host': '79.45.232.57', 'port': 8444}. Traceback (most recent call last):
  File "chia\util\struct_stream.py", line 16, in __new__
struct.error: int too large to convert

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "chia\server\server.py", line 528, in wrapped_coroutine
  File "chia\full_node\full_node_api.py", line 620, in respond_end_of_sub_slot
  File "chia\full_node\full_node.py", line 1567, in respond_end_of_sub_slot
  File "chia\full_node\full_node_store.py", line 289, in new_finished_sub_slot
  File "chia\util\struct_stream.py", line 21, in __new__
ValueError: Value -29417640 of size 25 does not fit into uint64 of size 64

2021-09-07T13:13:06.289 full_node full_node_server        : ERROR    Exception: Value -29417640 of size 25 does not fit into uint64 of size 64 <class 'ValueError'>, closing connection {'host': '79.45.232.57', 'port': 8444}. Traceback (most recent call last):
  File "chia\util\struct_stream.py", line 16, in __new__
struct.error: int too large to convert

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "chia\server\server.py", line 538, in api_call
  File "asyncio\tasks.py", line 481, in wait_for
  File "chia\server\server.py", line 535, in wrapped_coroutine
  File "chia\server\server.py", line 528, in wrapped_coroutine
  File "chia\full_node\full_node_api.py", line 620, in respond_end_of_sub_slot
  File "chia\full_node\full_node.py", line 1567, in respond_end_of_sub_slot
  File "chia\full_node\full_node_store.py", line 289, in new_finished_sub_slot
  File "chia\util\struct_stream.py", line 21, in __new__
ValueError: Value -29417640 of size 25 does not fit into uint64 of size 64

2021-09-07T13:13:06.367 full_node full_node_server        : WARNING  Banning 79.45.232.57 for 10 seconds
2021-09-07T13:13:06.683 full_node full_node_server        : ERROR    Exception: Value -37957850 of size 26 does not fit into uint64 of size 64, {'host': '75.155.179.27', 'port': 8444}. Traceback (most recent call last):
  File "chia\util\struct_stream.py", line 16, in __new__
struct.error: int too large to convert

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "chia\server\server.py", line 528, in wrapped_coroutine
  File "chia\full_node\full_node_api.py", line 620, in respond_end_of_sub_slot
  File "chia\full_node\full_node.py", line 1567, in respond_end_of_sub_slot
  File "chia\full_node\full_node_store.py", line 289, in new_finished_sub_slot
  File "chia\util\struct_stream.py", line 21, in __new__
ValueError: Value -37957850 of size 26 does not fit into uint64 of size 64

2021-09-07T13:13:06.683 full_node full_node_server        : ERROR    Exception: Value -37957850 of size 26 does not fit into uint64 of size 64 <class 'ValueError'>, closing connection {'host': '75.155.179.27', 'port': 8444}. Traceback (most recent call last):
  File "chia\util\struct_stream.py", line 16, in __new__
struct.error: int too large to convert

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "chia\server\server.py", line 538, in api_call
  File "asyncio\tasks.py", line 481, in wait_for
  File "chia\server\server.py", line 535, in wrapped_coroutine
  File "chia\server\server.py", line 528, in wrapped_coroutine
  File "chia\full_node\full_node_api.py", line 620, in respond_end_of_sub_slot
  File "chia\full_node\full_node.py", line 1567, in respond_end_of_sub_slot
  File "chia\full_node\full_node_store.py", line 289, in new_finished_sub_slot
  File "chia\util\struct_stream.py", line 21, in __new__
ValueError: Value -37957850 of size 26 does not fit into uint64 of size 64

2021-09-07T13:13:07.027 full_node full_node_server        : WARNING  Banning 75.155.179.27 for 10 seconds
2021-09-07T13:13:07.708 full_node full_node_server        : ERROR    Exception: Error short batch syncing, invalid/no response for 825085-825095, None. Traceback (most recent call last):
  File "chia\server\server.py", line 528, in wrapped_coroutine
  File "chia\full_node\full_node_api.py", line 106, in new_peak
  File "chia\full_node\full_node.py", line 411, in new_peak
  File "chia\full_node\full_node.py", line 267, in short_sync_batch
ValueError: Error short batch syncing, invalid/no response for 825085-825095

2021-09-07T13:13:07.708 full_node full_node_server        : ERROR    Exception: Error short batch syncing, invalid/no response for 825085-825095 <class 'ValueError'>, closing connection None. Traceback (most recent call last):
  File "chia\server\server.py", line 538, in api_call
  File "asyncio\tasks.py", line 442, in wait_for
  File "chia\server\server.py", line 535, in wrapped_coroutine
  File "chia\server\server.py", line 528, in wrapped_coroutine
  File "chia\full_node\full_node_api.py", line 106, in new_peak
  File "chia\full_node\full_node.py", line 411, in new_peak
  File "chia\full_node\full_node.py", line 267, in short_sync_batch
ValueError: Error short batch syncing, invalid/no response for 825085-825095

2021-09-07T13:13:07.708 full_node full_node_server        : ERROR    Exception: Error short batch syncing, invalid/no response for 825077-825095, None. Traceback (most recent call last):
  File "chia\server\server.py", line 528, in wrapped_coroutine
  File "chia\full_node\full_node_api.py", line 106, in new_peak
  File "chia\full_node\full_node.py", line 411, in new_peak
  File "chia\full_node\full_node.py", line 267, in short_sync_batch
ValueError: Error short batch syncing, invalid/no response for 825077-825095

2021-09-07T13:13:07.708 full_node full_node_server        : ERROR    Exception: Error short batch syncing, invalid/no response for 825077-825095 <class 'ValueError'>, closing connection None. Traceback (most recent call last):
  File "chia\server\server.py", line 538, in api_call
  File "asyncio\tasks.py", line 442, in wait_for
  File "chia\server\server.py", line 535, in wrapped_coroutine
  File "chia\server\server.py", line 528, in wrapped_coroutine
  File "chia\full_node\full_node_api.py", line 106, in new_peak
  File "chia\full_node\full_node.py", line 411, in new_peak
  File "chia\full_node\full_node.py", line 267, in short_sync_batch
ValueError: Error short batch syncing, invalid/no response for 825077-825095

2021-09-07T13:14:05.951 harvester chia.harvester.harvester: WARNING  Looking up qualities on I:\plot-k32-2021-08-24-17-31-9ced882b83356c335128caf14a5bae26ebc9bb05b41f9a7fce04f16be1d03640.plot took: 6.323347330093384. This should be below 5 seconds to minimize risk of losing rewards.
2021-09-07T13:58:18.245 harvester harvester_server        : ERROR    Exception: local variable 'self' referenced before assignment, {'host': '127.0.0.1', 'port': 8447}. Traceback (most recent call last):
  File "chia\server\server.py", line 528, in wrapped_coroutine
  File "chia\harvester\harvester_api.py", line 299, in request_plots
  File "<string>", line 11, in __init__
  File "chia\util\type_checking.py", line 87, in __post_init__
UnboundLocalError: local variable 'self' referenced before assignment

2021-09-07T13:58:18.245 harvester harvester_server        : ERROR    Exception: local variable 'self' referenced before assignment <class 'UnboundLocalError'>, closing connection {'host': '127.0.0.1', 'port': 8447}. Traceback (most recent call last):
  File "chia\server\server.py", line 538, in api_call
  File "asyncio\tasks.py", line 481, in wait_for
  File "chia\server\server.py", line 535, in wrapped_coroutine
  File "chia\server\server.py", line 528, in wrapped_coroutine
  File "chia\harvester\harvester_api.py", line 299, in request_plots
  File "<string>", line 11, in __init__
  File "chia\util\type_checking.py", line 87, in __post_init__
UnboundLocalError: local variable 'self' referenced before assignment

2021-09-07T13:58:18.245 harvester harvester_server        : WARNING  Trying to ban localhost for 10, but will not ban
2021-09-07T13:58:18.245 farmer chia.farmer.farmer         : ERROR    Harvester did not respond. You might need to update harvester to the latest version
2021-09-07T14:05:53.095 farmer chia.farmer.farmer         : ERROR    Harvester did not respond. You might need to update harvester to the latest version
2021-09-07T17:31:30.686 full_node full_node_server        : WARNING  Banning 182.18.92.234 for 10 seconds
2021-09-07T17:31:30.686 full_node full_node_server        : WARNING  Invalid handshake with peer {'host': '182.18.92.234', 'port': 8444}. Maybe the peer is running old software.

**Comment by jack60612** [comment]
Reinstall chia

**Comment by iRexLyys** [comment]
ok i uninstalled and reinstalled if the problem persists i will write again.
