### ISSUE TITLE
I got stuck on syncing 552.064 / 833.387 version 1.2.5 please help [BUG]

### ISSUE THREAD

**Issue by FrederickBTZ** [Chia-Network/chia-blockchain#8414]
**Describe the bug**
I am stuck on sync 552.064 / 833.387 from 09/07/2021 to 09/09/2021 today. I am currently using GUI version 1.2.5 for windows 10 64-bit operating system. I clarify I am new in CHIA, I hope you can help me please!

**To Reproduce**

5.The error is general, since by not synchronizing I cannot do anything else!

**Expected behavior**
What I hope is that the Node can be fully synchronized (and of course everything works fine), to generate Chia (Money) with the plots.

**Screenshots**
I don't know how to add a screenshot to Github.

**Desktop**

- OS: Windows 10
- OS Version/Flavor: Windows 10 Home Single Language/20H2
- CPU: AMD A10-7850K Radeon R7, 12 Compute Cores 4C+8G   4.00 GHz

**Additional context**
I installed the Chia wallet more than a week ago and I'm still waiting to be able to make a profit and have fun, greetings!

**Comment by shaneo257** [comment]
1) open port 8444 - https://github.com/Chia-Network/chia-blockchain/wiki/Resolving-Sync-Issues---Port-8444 
2) make SURE it is open with telnet (telnet <node-ip> <8444>) 
3) disable upnp everywhere. (chia configure -upnp false) 
4) make sure system clock is set to the actual time in your time zone 
5) are you plotting or doing other high intensity jobs on the node? 
6) what does top or task manager say about resource usage? 
7) set your logs to INFO, capture them. Share them as a gist. (if you do not have github, pastebin.com) 
8) what system specs? Os? Chia version? 
9) has your wan IP changed recently? 
10) are you behind double or cgnat? 
11) have you added node.chia.net:8444 to your peers manually?

**Comment by FrederickBTZ** [comment]
1. I don't have access to the router, I can't configure it.
2. I don't have access to the router, I can't configure it.
3. I don't have access to the router, I can't configure it.
4. yes
5. no
6. CPU 7%
7. no
8. CPU: AMD A10-7850K Radeon R7, 12 Compute Cores 4C+8G   4.00 GHz / RAM: 16,0 GB (14,9 GB usable) / OS: Windows 10 64 bits / CHIA: GUI version 1.2.5 / Available disk storage: 18 TB
9. no
10. no
11. no

**Comment by loppefaaret** [comment]
could you try and opening up the `debug.log` file located in you users folder `~\.chia\mainnet\log\` and check for the latest ERROR lines please ?

**Comment by mariano54** [comment]
Also, can you post a screenshot of what your GUI looks like?
Have you tried restarting the Chia app?

**Comment by FrederickBTZ** [comment]
2021-09-09T03:11:18.135 full_node chia.full_node.full_node: ERROR    Error with syncing: <class 'RuntimeError'>Traceback (most recent call last):
  File "chia\full_node\full_node.py", line 672, in _sync
RuntimeError: Weight proof did not arrive in time from peer: 8.210.81.116

2021-09-09T03:12:09.505 full_node full_node_server        : WARNING  Cannot write to closing transport 47.55.46.249
2021-09-09T03:13:51.763 full_node chia.full_node.full_node: ERROR    Error with syncing: <class 'RuntimeError'>Traceback (most recent call last):
  File "chia\full_node\full_node.py", line 672, in _sync
RuntimeError: Weight proof did not arrive in time from peer: 174.119.19.66

2021-09-09T03:16:02.619 full_node chia.full_node.full_node: ERROR    Error with syncing: <class 'RuntimeError'>Traceback (most recent call last):
  File "chia\full_node\full_node.py", line 672, in _sync
RuntimeError: Weight proof did not arrive in time from peer: 176.49.245.249

2021-09-09T03:16:34.159 full_node chia.full_node.full_node: WARNING  Received unsolicited/late block from peer {'host': '136.25.162.226', 'port': 8444}
2021-09-09T03:16:35.941 full_node chia.full_node.full_node: WARNING  Received unsolicited/late block from peer {'host': '219.79.56.191', 'port': 8444}
2021-09-09T03:16:36.509 full_node chia.full_node.full_node: WARNING  Received unsolicited/late block from peer {'host': '112.118.54.13', 'port': 8444}
2021-09-09T03:18:13.163 full_node chia.full_node.full_node: ERROR    Error with syncing: <class 'RuntimeError'>Traceback (most recent call last):
  File "chia\full_node\full_node.py", line 672, in _sync
RuntimeError: Weight proof did not arrive in time from peer: 136.25.162.226

**Comment by mariano54** [comment]
Hmm maybe slow network connection. Try fast.com and see how fast that it?

**Comment by boner-cmd** [comment]
Master thread for problems like this is #6993 if any information there helps
