### ISSUE TITLE
Wallet isn't syncing on docker

### ISSUE THREAD

**Issue by benthetechguy** [Chia-Network/chia-blockchain#8422]
**Describe the bug**
Started Chia on Docker using [this](https://github.com/orgs/Chia-Network/packages/container/package/chia), and the node synced just fine, everything else is working as expected, but the wallet isn't syncing, staying at height 0.

**To Reproduce**
Run `sudo docker exec -it chia-blockchain venv/bin/chia wallet show` and see the height at 0, not moving for days

**Expected behavior**
Wallet syncs with the node

**Screenshots**
```
Wallet height: 0
Sync status: Not synced
```

**Desktop**
- OS: Linux
- OS Version/Flavor: Debian 11
- CPU: Intel Core i5-4570S
- Additional Note: Running in a Docker container, so the fact that it's Debian should be irrelevant

**Comment by loppefaaret** [comment]
im not entirely sure how to, but are you able to access the `debug.log` ? should be under `chia/mainnet/log/` i believe - look for messages from `wallet`

**Comment by davidbarratt** [comment]
I'm having the same problem, here is the `debug.log`:
```
2021-09-14T11:23:20.242 full_node full_node_server        : WARNING  Banning 124.126.202.82 for 10 seconds
2021-09-14T11:23:20.244 full_node full_node_server        : WARNING  Invalid handshake with peer. Maybe the peer is running old software.
2021-09-14T11:24:50.547 wallet chia.wallet.wallet_node    : WARNING  bad peak response from peer None
2021-09-14T11:24:50.551 wallet chia.wallet.wallet_node    : WARNING  bad peak response from peer None
2021-09-14T11:25:50.557 wallet chia.wallet.wallet_node    : ERROR    Error while trying to fetch from peer:Peer returned no response Traceback (most recent call last):
  File "/chia-blockchain/chia/wallet/wallet_node.py", line 555, in batch_sync_to_peak
    added, advanced_peak = await self.fetch_blocks_and_validate(
  File "/chia-blockchain/chia/wallet/wallet_node.py", line 687, in fetch_blocks_and_validate
    raise ValueError("Peer returned no response")
ValueError: Peer returned no response

2021-09-14T11:25:50.559 wallet chia.wallet.wallet_node    : ERROR    Loop exception in sync Was not able to add blocks 0-32. Traceback (most recent call last):
  File "/chia-blockchain/chia/wallet/wallet_node.py", line 608, in sync_job
    await self._sync()
  File "/chia-blockchain/chia/wallet/wallet_node.py", line 668, in _sync
    await self.batch_sync_to_peak(fork_height, peak)
  File "/chia-blockchain/chia/wallet/wallet_node.py", line 565, in batch_sync_to_peak
    raise RuntimeError(f"Was not able to add blocks {start_height}-{end_height}")
RuntimeError: Was not able to add blocks 0-32

2021-09-14T11:35:53.453 full_node full_node_server        : ERROR    Exception:  <class 'asyncio.exceptions.TimeoutError'>, closing connection {'host': '127.0.0.1', 'port': 8449}. Traceback (most recent call last):
  File "/chia-blockchain/chia/server/server.py", line 563, in api_call
    response: Optional[Message] = await asyncio.wait_for(wrapped_coroutine(), timeout=timeout)
  File "/usr/lib/python3.8/asyncio/tasks.py", line 501, in wait_for
    raise exceptions.TimeoutError()
asyncio.exceptions.TimeoutError

2021-09-14T11:35:53.498 full_node full_node_server        : WARNING  Trying to ban localhost for 10, but will not ban
2021-09-14T11:43:25.456 wallet chia.wallet.wallet_node    : ERROR    Error while trying to fetch from peer:Peer returned no response Traceback (most recent call last):
  File "/chia-blockchain/chia/wallet/wallet_node.py", line 555, in batch_sync_to_peak
    added, advanced_peak = await self.fetch_blocks_and_validate(
  File "/chia-blockchain/chia/wallet/wallet_node.py", line 687, in fetch_blocks_and_validate
    raise ValueError("Peer returned no response")
ValueError: Peer returned no response

2021-09-14T11:43:25.457 wallet chia.wallet.wallet_node    : ERROR    Loop exception in sync Was not able to add blocks 0-32. Traceback (most recent call last):
  File "/chia-blockchain/chia/wallet/wallet_node.py", line 608, in sync_job
    await self._sync()
  File "/chia-blockchain/chia/wallet/wallet_node.py", line 668, in _sync
    await self.batch_sync_to_peak(fork_height, peak)
  File "/chia-blockchain/chia/wallet/wallet_node.py", line 565, in batch_sync_to_peak
    raise RuntimeError(f"Was not able to add blocks {start_height}-{end_height}")
RuntimeError: Was not able to add blocks 0-32

2021-09-14T11:43:25.461 wallet chia.wallet.wallet_node    : WARNING  bad peak response from peer None
2021-09-14T11:43:25.463 wallet chia.wallet.wallet_node    : WARNING  bad peak response from peer None
2021-09-14T11:43:25.465 wallet chia.wallet.wallet_node    : WARNING  bad peak response from peer None
2021-09-14T11:43:25.468 wallet chia.wallet.wallet_node    : WARNING  bad peak response from peer None
2021-09-14T11:43:25.470 wallet chia.wallet.wallet_node    : WARNING  bad peak response from peer None
2021-09-14T11:45:37.377 full_node full_node_server        : WARNING  Was not able to get peername from 111.117.118.161 - closing connection
```

**Comment by boner-cmd** [comment]
Master thread for wallet sync issues is #6993 if that helps you get visibility. Also I think there are other users (maybe you already, not sure) who have the `Loop exception in sync` specific issue
