### ISSUE TITLE
Pool connection dropped after finding a corrupted file.

### ISSUE THREAD

**Issue by KSum** [Chia-Network/chia-blockchain#8432]
This has happened to me a few times where the GUI would disconnect from the pool when I was using the GUI to plot.

I finally found in the log what's happening at that moment.
It looks like it comes across a file error and it seems to cause the connection to drop and not reconnect.
The graph on the GUI drops to 0 and no points are earned until you restart the Chia GUI.

`2021-09-07T10:29:57.812 harvester chia.harvester.harvester: ERROR    Error using prover object Src size is incorrect
2021-09-07T10:29:57.813 harvester chia.harvester.harvester: ERROR    File: E:\plot-k32-2021-09-04-06-10-4cba13f102c0f655226e267e531df1b378d043fefb9593468626e6ae404683e9.plot Plot ID: 4cba13f102c0f655226e267e531df1b378d043fefb9593468626e6ae404683e9, challenge: 00029b14c581c7980afb75ee51992704c43c766752e7cc2603bd732a4ae86767, plot_info: PlotInfo(prover=<chiapos.DiskProver object at 0x000001BCC9A581B0>, pool_public_key=None, pool_contract_puzzle_hash=<bytes32: dd281beef90790866ff797520ad3a37fcb75f559e6e57ab31ae8b1b8f1ad6e7b>, plot_public_key=<G1Element 8fefe9696015fe62d7f158a687b1878e8f9ac163c5df0afacc4477a13873d6c85853f527030623c997bec507304e85f3>, file_size=108831655532, time_modified=1630794726.596919)
2021-09-07T10:47:19.095 farmer chia.rpc.rpc_server        : WARNING  Sending data failed. Exception Traceback (most recent call last):
  File "chia\rpc\rpc_server.py", line 69, in _state_changed
  File "aiohttp\client_ws.py", line 150, in send_str
  File "aiohttp\http_websocket.py", line 687, in send
  File "aiohttp\http_websocket.py", line 656, in _send_frame
  File "aiohttp\base_protocol.py", line 84, in _drain_helper
AssertionError
.
2021-09-07T10:53:21.462 daemon __main__                   : ERROR    Unexpected exception trying to send to websocket: code = 1006 (connection closed abnormally [internal]), no reason Traceback (most recent call last):
  File "websockets\protocol.py", line 827, in transfer_data
  File "websockets\protocol.py", line 895, in read_message
  File "websockets\protocol.py", line 971, in read_data_frame
  File "websockets\protocol.py", line 1047, in read_frame
  File "websockets\framing.py", line 133, in read
  File "asyncio\streams.py", line 723, in readexactly
  File "asyncio\streams.py", line 517, in _wait_for_data
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\a\chia-blockchain\chia-blockchain\venv\Lib\site-packages\chia\daemon\server.py", line 205, in safe_handle
  File "websockets\protocol.py", line 555, in send
  File "websockets\protocol.py", line 812, in ensure_open
websockets.exceptions.ConnectionClosedError: code = 1006 (connection closed abnormally [internal]), no reason

2021-09-07T10:53:51.442 farmer chia.rpc.rpc_server        : WARNING  Sending data failed. Exception Traceback (most recent call last):
  File "chia\rpc\rpc_server.py", line 69, in _state_changed
  File "aiohttp\client_ws.py", line 150, in send_str
  File "aiohttp\http_websocket.py", line 687, in send
  File "aiohttp\http_websocket.py", line 643, in _send_frame
  File "aiohttp\http_websocket.py", line 660, in _write
ConnectionResetError: Cannot write to closing transport`

It repeats the last warning until you restart the GUI.

**Comment by loppefaaret** [comment]
you did double check that the file is not there ? what if you try `chia plots check -g E:\plot-k32-2021-09-04-06-10-4cba13f102c0f655226e267e531df1b378d043fefb9593468626e6ae404683e9.plot` what does that return ?

**Comment by KSum** [comment]
Ran that and it could not find the file.
