### ISSUE TITLE
[BUG] After reinstalling my computer, I have an issue with "Connecting my wallet", it stands there for days. I cannot reach the afterwards steps

### ISSUE THREAD

**Issue by filipzivkovicc** [Chia-Network/chia-blockchain#8444]
![image](https://user-images.githubusercontent.com/90529587/132960477-8a54119b-92fa-448c-96a6-b2b55ff999a5.png)

**Comment by 988387069** [comment]
我也是出现这个问题,CHIA一直迟迟不修复这个问题.

**Comment by shaneo257** [comment]
was this a new install of the chia client, or did you copy your db's over as well?

**Comment by filipzivkovicc** [comment]
> was this a new install of the chia client, or did you copy your db's over as well?

That was a new chia client install..I have tried many things, but for a week I cannot reach mine wallet..Do you have any idea how can I solve this problem?

**Comment by loppefaaret** [comment]
so chia has never successfully been running on this machine ? im going to need some data from you `debug.log` file, locvated in your users folder `~\.chia\mainnet\log\`
nothing in the devtools console is preventing the app from opening up correcetly

**Comment by filipzivkovicc** [comment]
> so chia has never successfully been running on this machine ? im going to need some data from you `debug.log` file, locvated in your users folder `~\.chia\mainnet\log\`
> nothing in the devtools console is preventing the app from opening up correcetly

Yes, it has been running for a couple of months without any problem.Everything was ok, untill I reinstalled my laptop.
Which data do you need.Maybe, there is one more problem, I don't have that folder...

**Comment by thomasjvnk** [comment]
> so chia has never successfully been running on this machine ? im going to need some data from you `debug.log` file, locvated in your users folder `~\.chia\mainnet\log\`
> nothing in the devtools console is preventing the app from opening up correcetly

i'm having this issue

here is the full_node message:

2021-09-04T17:06:56.150 full_node full_node_server : ERROR Exception: Failed to fetch block 813038 from None, timed out, None. Traceback (most recent call last):
File "chia\server\server.py", line 523, in wrapped_coroutine
File "chia\full_node\full_node_api.py", line 106, in new_peak
File "chia\full_node\full_node.py", line 397, in new_peak
File "chia\full_node\full_node.py", line 331, in short_sync_backtrack
File "chia\full_node\full_node.py", line 316, in short_sync_backtrack
ValueError: Failed to fetch block 813038 from None, timed out

2021-09-04T17:06:56.152 full_node full_node_server : ERROR Exception: Failed to fetch block 813038 from None, timed out <class 'ValueError'>, closing connection None. Traceback (most recent call last):
File "chia\server\server.py", line 533, in api_call
File "asyncio\tasks.py", line 442, in wait_for
File "chia\server\server.py", line 530, in wrapped_coroutine
File "chia\server\server.py", line 523, in wrapped_coroutine
File "chia\full_node\full_node_api.py", line 106, in new_peak
File "chia\full_node\full_node.py", line 397, in new_peak
File "chia\full_node\full_node.py", line 331, in short_sync_backtrack
File "chia\full_node\full_node.py", line 316, in short_sync_backtrack
ValueError: Failed to fetch block 813038 from None, timed out

2021-09-05T09:27:12.229 full_node full_node_server : WARNING Cannot write to closing transport 69.178.113.57
2021-09-05T13:51:44.013 harvester chia.harvester.harvester: WARNING Looking up qualities on E:\plot chia\plot-k32-2021-08-10-18-10-f0ac27a71e522be79f298d40643788c21af1987964a911f0b2dae350fce90642.plot took: 5.437026739120483. This should be below 5 seconds to minimize risk of losing rewards.
2021-09-07T02:08:14.526 full_node full_node_server : ERROR Exception: database or disk is full, {'host': '68.227.1.80', 'port': 8444}. Traceback (most recent call last):
File "chia\server\server.py", line 523, in wrapped_coroutine
File "chia\full_node\full_node_api.py", line 106, in new_peak
File "chia\full_node\full_node.py", line 397, in new_peak
File "chia\full_node\full_node.py", line 331, in short_sync_backtrack
File "chia\full_node\full_node.py", line 328, in short_sync_backtrack
File "chia\full_node\full_node.py", line 1202, in respond_block
File "chia\consensus\blockchain.py", line 265, in receive_block
File "chia\consensus\blockchain.py", line 364, in _reconsider_peak
File "chia\full_node\coin_store.py", line 81, in new_block
File "chia\full_node\coin_store.py", line 232, in _add_coin_record
File "aiosqlite\core.py", line 184, in execute
File "aiosqlite\core.py", line 129, in _execute
File "aiosqlite\core.py", line 102, in run
sqlite3.OperationalError: database or disk is full

2021-09-07T02:08:15.468 full_node full_node_server : ERROR Exception: database or disk is full, {'host': '190.19.109.46', 'port': 8444}. Traceback (most recent call last):
File "chia\server\server.py", line 523, in wrapped_coroutine
File "chia\full_node\full_node_api.py", line 106, in new_peak
File "chia\full_node\full_node.py", line 397, in new_peak
File "chia\full_node\full_node.py", line 331, in short_sync_backtrack
File "chia\full_node\full_node.py", line 328, in short_sync_backtrack
File "chia\full_node\full_node.py", line 1202, in respond_block
File "chia\consensus\blockchain.py", line 265, in receive_block
File "chia\consensus\blockchain.py", line 364, in _reconsider_peak
File "chia\full_node\coin_store.py", line 81, in new_block
File "chia\full_node\coin_store.py", line 232, in _add_coin_record
File "aiosqlite\core.py", line 184, in execute
File "aiosqlite\core.py", line 129, in _execute
File "aiosqlite\core.py", line 102, in run
sqlite3.OperationalError: database or disk is full

2021-09-07T02:08:15.559 full_node full_node_server : WARNING Banning 68.227.1.80 for 10 seconds
2021-09-07T02:22:49.959 full_node full_node_server : WARNING Banning 85.201.34.43 for 10 seconds
2021-09-08T06:19:45.563 full_node full_node_server : WARNING Cannot write to closing transport 47.148.158.242
2021-09-08T22:25:17.998 wallet chia.wallet.wallet_node : WARNING bad peak response from peer None
2021-09-10T12:02:32.328 full_node full_node_server : ERROR Exception: Failed to fetch block 839852 from None, timed out, None. Traceback (most recent call last):
File "chia\server\server.py", line 523, in wrapped_coroutine
File "chia\full_node\full_node_api.py", line 106, in new_peak
File "chia\full_node\full_node.py", line 397, in new_peak
File "chia\full_node\full_node.py", line 331, in short_sync_backtrack
File "chia\full_node\full_node.py", line 316, in short_sync_backtrack
ValueError: Failed to fetch block 839852 from None, timed out

2021-09-10T12:02:32.333 full_node full_node_server : ERROR Exception: Failed to fetch block 839852 from None, timed out <class 'ValueError'>, closing connection None. Traceback (most recent call last):
File "chia\server\server.py", line 533, in api_call
File "asyncio\tasks.py", line 442, in wait_for
File "chia\server\server.py", line 530, in wrapped_coroutine
File "chia\server\server.py", line 523, in wrapped_coroutine
File "chia\full_node\full_node_api.py", line 106, in new_peak
File "chia\full_node\full_node.py", line 397, in new_peak
File "chia\full_node\full_node.py", line 331, in short_sync_backtrack
File "chia\full_node\full_node.py", line 316, in short_sync_backtrack
ValueError: Failed to fetch block 839852 from None, timed out

2021-09-10T19:13:50.372 full_node full_node_server : WARNING Cannot write to closing transport 91.125.65.77

**Comment by thomasjvnk** [comment]
> > so chia has never successfully been running on this machine ? im going to need some data from you `debug.log` file, locvated in your users folder `~\.chia\mainnet\log\`
> > nothing in the devtools console is preventing the app from opening up correcetly
> 
> Yes, it has been running for a couple of months without any problem.Everything was ok, untill I reinstalled my laptop.
> Which data do you need.Maybe, there is one more problem, I don't have that folder...

here the address

C:\Users\Thomas\.chia\mainnet\log

**Comment by jfernmez** [comment]
I have the same problem
![IssueJFM](https://user-images.githubusercontent.com/90664785/133183839-5d9d1525-af8b-4aff-8e42-b5bc0e2e85a0.jpg)

**Comment by thomasjvnk** [comment]
i deleted all folders of chia, unistalled the chia blockchain and reinstalled, then i was able to enter the wallet, with the 24 words, but my wallet is empty and my plots  and wallet don't sync

**Comment by jack60612** [comment]
> i deleted all folders of chia, unistalled the chia blockchain and reinstalled, then i was able to enter the wallet, with the 24 words, but my wallet is empty and my plots and wallet don't sync

is your node syncing?
and what version are you on?

**Comment by thomasjvnk** [comment]
> > i deleted all folders of chia, unistalled the chia blockchain and reinstalled, then i was able to enter the wallet, with the 24 words, but my wallet is empty and my plots and wallet don't sync
> 
> is your node syncing?
> and what version are you on?

version 1.2.6

3 hours and its syncing 140.768/859.783, but still no chia in my wallet

**Comment by shaneo257** [comment]
your chia wont show until the wallet has past the height in the blockchain  to when your received it

**Comment by jack60612** [comment]
> your chia wont show until the wallet has past the height in the blockchain to when your received it

Exactly

**Comment by filipzivkovicc** [comment]
> i deleted all folders of chia, unistalled the chia blockchain and reinstalled, then i was able to enter the wallet, with the 24 words, but my wallet is empty and my plots and wallet don't sync

I cannot make it work, even with this steps...I did it a couple of times

**Comment by filipzivkovicc** [comment]
> > > i deleted all folders of chia, unistalled the chia blockchain and reinstalled, then i was able to enter the wallet, with the 24 words, but my wallet is empty and my plots and wallet don't sync
> > 
> > 
> > is your node syncing?
> > and what version are you on?
> 
> version 1.2.6
> 
> 3 hours and its syncing 140.768/859.783, but still no chia in my wallet

I dont have problem with syncing..I can not even reach syncing step.

**Comment by thomasjvnk** [comment]
> > i deleted all folders of chia, unistalled the chia blockchain and reinstalled, then i was able to enter the wallet, with the 24 words, but my wallet is empty and my plots and wallet don't sync
> 
> I cannot make it work, even with this steps...I did it a couple of times

did you deleted even the folders in the users folder? 

there are two places that chia maintain files

C:\Users\Thomas\AppData\Local\chia-blockchain
C:\Users\Thomas\.chia

**Comment by thomasjvnk** [comment]
> your chia wont show until the wallet has past the height in the blockchain to when your received it

still syncing, since yesterday, but looks like it gonna work, 676000/859783

**Comment by thomasjvnk** [comment]
problem solved, after sync is completed, started mining and all my chia back to wallet, but i had to delete all folders from my pc and reinstall again

**Comment by loppefaaret** [comment]
> > > > i deleted all folders of chia, unistalled the chia blockchain and reinstalled, then i was able to enter the wallet, with the 24 words, but my wallet is empty and my plots and wallet don't sync
> > > 
> > > 
> > > is your node syncing?
> > > and what version are you on?
> > 
> > 
> > version 1.2.6
> > 3 hours and its syncing 140.768/859.783, but still no chia in my wallet
> 
> I dont have problem with syncing..I can not even reach syncing step.

could you try and open up a file explorer window, and browse to `C:\Users\<USERNAME>\.chia\mainnet\log\` and then add the `debug.log` in here ? you can drag the file from the window, into the text ox here on github

**Comment by filipzivkovicc** [comment]
I deleted every single file which is connected to chia.Also, when I am installing again, I am not offered an classic installation.When click on .exe file, just new icon come up on desktop and app i trying to connect to wallet, but unsuccessfully....

I am just trying for a week, and I am giving up slowly...

**Comment by jack60612** [comment]
> I deleted every single file which is connected to chia.Also, when I am installing again, I am not offered an classic installation.When click on .exe file, just new icon come up on desktop and app i trying to connect to wallet, but unsuccessfully....
> 
> I am just trying for a week, and I am giving up slowly...

the exe is an installer it just won't prompt you 
just look in the start menu and you will find it

**Comment by boner-cmd** [comment]
master thread is #6993 in case that helps you get visibility

**Comment by olivier91360** [comment]
Bonjour;
Je suis un peu dans la meme situation, depuis une coupure internet, je n'arrive plus à me connecter a aucun portefeuille, que ce soit CHIa ou d'autres Forks, 
Pouvez vous m'aider, je ne suis pas un As de l'informatique,
Merci d'avance

**Comment by loppefaaret** [comment]
> Bonjour;
> Je suis un peu dans la meme situation, depuis une coupure internet, je n'arrive plus à me connecter a aucun portefeuille, que ce soit CHIa ou d'autres Forks,
> Pouvez vous m'aider, je ne suis pas un As de l'informatique,
> Merci d'avance

do you have only a message saying "Connecting to wallet..." and a spinning circle ? 
you might have corrupted databases, and need to remove the wallet database located in your users folder `~\.chia\mainnet\wallet\db\wallet*`
first, i would try and move the file to desktop, and try opening chia again, and see if that helped

**Comment by kevin198612** [comment]
It has been going on for almost two weeks, and it won’t work even after deleting all the files.
![屏幕快照 2021-10-12 上午2 39 37](https://user-images.githubusercontent.com/92344501/136871691-ccced520-a8d4-423a-acbb-896eae515fea.png)

**Comment by kevin198612** [comment]
> @kevin198612 did you try and move out the wallet database ?

yes ! i did

**Comment by loppefaaret** [comment]
could you try and locate your `debug.log` - its default location is under your users folder `~\.chia\mainnet\log\debug.log` - if you can attach it to this thread, we might be able to see if there is anything special happening.
if you have privacy concerns about uploading your `debug.log` to an open platform, you can DM it securely on our Keybase chat:
https://keybase.io/team/chia_network.public to @pyl on Keybase
or email as an attachment to "rc 'at' chia.net"
