### ISSUE TITLE
[BUG] can't sync wallet (new installation from existing keys)

### ISSUE THREAD

**Issue by kamilmiotk** [Chia-Network/chia-blockchain#8546]
2021-09-20T14:59:04.384 wallet chia.wallet.wallet_node    : ERROR    Loop exception in sync Was not able to add blocks 0-32. Traceback (most recent call last):
  File "/root/chia-blockchain/chia/wallet/wallet_node.py", line 608, in sync_job
    await self._sync()
  File "/root/chia-blockchain/chia/wallet/wallet_node.py", line 668, in _sync
    await self.batch_sync_to_peak(fork_height, peak)
  File "/root/chia-blockchain/chia/wallet/wallet_node.py", line 565, in batch_sync_to_peak
    raise RuntimeError(f"Was not able to add blocks {start_height}-{end_height}")
RuntimeError: Was not able to add blocks 0-32

**Comment by loppefaaret** [comment]
#8538
