### ISSUE TITLE
[BUG] Cannot use IPv6 for remote harvester or between any Chia services

### ISSUE THREAD

**Issue by emlowe** [Chia-Network/chia-blockchain#8565]
### Discussed in https://github.com/Chia-Network/chia-blockchain/discussions/8552

<div type='discussions-op-text'>

<sup>Originally posted by **cross** September 21, 2021</sup>
chia-blockchain 1.2.3, Ubuntu 20.  installed from the .deb distribution here.

I have a harvester I'm trying to connect to a farmer peer in the same building.  I have other harvesters connected via IPv4.  This newest harvester is on a segmented IPv4 network, so I'm specifying the IPv6 address of the farmer as follows in my config.yml:

```
harvester:
  chia_ssl_ca:
    crt: config/ssl/ca/chia_ca.crt
    key: config/ssl/ca/chia_ca.key
  farmer_peer:
    host: 2000:3000:4000:5000::101
    port: 8447
  logging: *id001
  network_overrides: *id002
```

But, when I start `chia start harvester -r` the following appears on my terminal:
 
```
chia_harvester: started
user@host:~$ Traceback (most recent call last):
  File "chia/server/start_harvester.py", line 57, in <module>
  File "chia/server/start_harvester.py", line 53, in main
  File "chia/server/start_service.py", line 255, in run_service
  File "asyncio/runners.py", line 44, in run
  File "asyncio/base_events.py", line 616, in run_until_complete
  File "chia/server/start_service.py", line 249, in async_run_service
  File "chia/server/start_service.py", line 171, in run
  File "chia/server/start_service.py", line 145, in start
  File "chia/server/start_service.py", line 146, in <listcomp>
  File "chia/server/reconnect_task.py", line 12, in start_reconnect_task
socket.gaierror: [Errno -9] Address family for hostname not supported
[1752] Failed to execute script start_harvester
```

Do I have the syntax wrong, or does IPv6 connections to farmer have an issue?

(`netstat -an | grep 8447` on the farmer shows `tcp6       0      0 :::8447                 :::*                    LISTEN` amongst `tcp LISTEN` and ESTABLISHED connections via IPv4.  And I've verified I can establish the tcp connection using `telnet` to that IPv6 address, port 8447.)</div>

**Comment by cross** [comment]
Looking into the code for this, it took me a while to figure where the fix needs to be, mostly due to my confusion about PeerInfo's `host`.  That value, passed into PeerInfo _must_ be an address.  I recommend you rename that instance variable in `types/peer_info.py` to `hostaddr`.  (You could add a getter named `host` if it's too widespread to update)  That would make it much easier to understand PeerInfo, and how/why it's called the way it is in `start_reconnect_task`.

**Comment by cross** [comment]
Actually, looking again, if the `host` member of `PeerInfo` must be an address string, there is no reason to call `gethostbyname` in `start_reconnect_task`.  Am I missing something?  Why does start_reconnect_task call gethostbyname on that PeerInfo.host value?  Can that just be removed?  @emlowe

**Comment by emlowe** [comment]
Actually, PeerInfo.host is just a string and we support using DNS/mDNS names in config.yaml for the peers, for example, the default in config.yaml is for the peer to be "localhost". The value is read in from config.yaml and put into a PeerInfo instance as a string. This is then created into a proper address using gethostbyname and into another PeerInfo. I'll grant it's a little strange that the initial PeerInfo used when reading from config.yaml would technically fail the PeerInfo is_valid() function

**Comment by cross** [comment]
Okay, then that makes my earlier suggestion somewhat moot.  :-/  Okay, then I don't know how to figure out where PeerInfo needs to be an address for host, and where it needs to be a resolvable string.  If there is a clear definition of that, I could try to help fix this.  Without, and looking only at `start_reconnect_task`, I tried using `socket.getaddrinfo(peer_info_arg.host,None,flags=socket.AI_ADDRCONFIG)[0][4][0]` and that worked for IPv4 and IPv6 addresses, and names.  But, I'm not sure how portable `AI_ADDRCONFIG` is, or if you want to evaluate the IPv4 vs IPv6 responses.
(I think a global config about whether or not IPv6 should be used, preferred, etc would be right.  But that's a lot more work.)
Thanks for your input.

**Comment by emlowe** [comment]
The minimal patch is probably catching the exception from gethostbyname() and then specifically getting the IPv6 with `socket.getaddrinfo(peer_info_arg.host, None, family=socket.AF_INET6, proto=socket.IPPROTO_TCP)` (no flags).

Alternatively, you could just get everything with `socket.getaddrinfo(peer_info_arg.host, None)` and parse the returned tuples.

Second alternative - if the value in config.yaml is already an IPv4/IPv6 address, we could not call gethostbyname at all. This could be checked with using `PeerInfo.is_valid()`. If that is true, then don't bother calling either `gethostbyname` or `getaddrinfo` here. This would then require users wanting to use IPv6 to enter in the address in config.yaml without any name resolution.

Actually I think I like this last one.

I don't think in either case we need to use any flags.

For the remote harvester, I think this is the only place it needs to be changed - however, the wallet code also has a place where it does a similar thing - see `wallet_node.py` around line 398

**Comment by cross** [comment]
I think IPv6 resolution is a good idea, and I'd love to be able to set a config/setting to "prefer IPv6".  But, for my immediate need, allowing addresses (via is_valid) and then calling gethostbyname() for names would work.  I don't _like_ it, but it would be easier/faster.

**Comment by emlowe** [comment]
It has the advantage that it also eliminates a lookup call - one could argue it should already have been doing this.

**Comment by cross** [comment]
Okay.  Should we resolve this bug by putting in the ability to specify and IPv6 address, without fixing any of the IPv4-only resolution code?  If so that's fine, we can open a new bug for the other.  But we can get this one fixed faster, because it's less invasive.

**Comment by emlowe** [comment]
If your harvester is on Linux/MacOS - it's pretty easy. Just run `pip install -e ".[dev]"`, then edit your python, save the file, and run it inside the venv.
So
- `sh install.sh`
- `pip install -e ".[dev]"` - the install.sh may already do this, but it doesn't hurt
- `source ./activate`
- Edit and save your changes
- `chia start harvester`

You only need to do the first 3 steps once, then you can edit python and make whatever changes you want as many times as needed.

This can also be done on Windows, but it's a little more work to set. We have new powershell scripts to help setup though you can look at install.ps1.
