### ISSUE TITLE
[BUG]websockets.exceptions.ConnectionClosedError: code = 1006

### ISSUE THREAD

**Issue by electroboyz** [Chia-Network/chia-blockchain#8592]
**Describe the bug**
2021-09-25T09:42:03.911 daemon __main__                   : ERROR    Unexpected exception trying to send to websocket: code = 1006 (connection closed abnormally [internal]), no reason Traceback (most recent call last):
  File "websockets/protocol.py", line 827, in transfer_data
  File "websockets/protocol.py", line 895, in read_message
  File "websockets/protocol.py", line 971, in read_data_frame
  File "websockets/protocol.py", line 1047, in read_frame
  File "websockets/framing.py", line 105, in read
  File "asyncio/streams.py", line 721, in readexactly
asyncio.exceptions.IncompleteReadError: 0 bytes read on a total of 2 expected bytes

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "chia/daemon/server.py", line 187, in safe_handle
  File "websockets/protocol.py", line 555, in send
  File "websockets/protocol.py", line 803, in ensure_open
websockets.exceptions.ConnectionClosedError: code = 1006 (connection closed abnormally [internal]), no reason

**To Reproduce**
check debug.log

**Expected behavior**
connection closed

**Screenshots**

**Desktop**

- OS: 
- OS Version/Flavor: 
- CPU: 

**Additional context**

**Comment by snajperus** [comment]
On my windows are similar problem

2021-09-29T09:32:52.874 farmer farmer_server              : INFO     Connection closed: 127.0.0.1, node id: 6c0e2167f683fd305a2ab9c6766a7c5b60ec056849e5c584e7c7fb67add948f3
2021-09-29T09:32:52.875 farmer chia.farmer.farmer         : INFO     peer disconnected {'host': '127.0.0.1', 'port': 8444}
2021-09-29T09:32:52.877 daemon __main__                   : INFO     Websocket exception. Closing websocket with chia_full_node code = 1006 (connection closed abnormally [internal]), no reason Traceback (most recent call last):
  File "asyncio\windows_events.py", line 457, in finish_recv
OSError: [WinError 64] Określona nazwa sieciowa już jest niedostępna

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "websockets\protocol.py", line 827, in transfer_data
  File "websockets\protocol.py", line 895, in read_message
  File "websockets\protocol.py", line 971, in read_data_frame
  File "websockets\protocol.py", line 1047, in read_frame
  File "websockets\framing.py", line 105, in read
  File "asyncio\streams.py", line 723, in readexactly
  File "asyncio\streams.py", line 517, in _wait_for_data
  File "asyncio\proactor_events.py", line 280, in _loop_reading
  File "asyncio\windows_events.py", line 812, in _poll
  File "asyncio\windows_events.py", line 461, in finish_recv
ConnectionResetError: [WinError 64] Określona nazwa sieciowa już jest niedostępna

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "Lib\site-packages\chia\daemon\server.py", line 190, in safe_handle
  File "websockets\protocol.py", line 439, in __aiter__
  File "websockets\protocol.py", line 509, in recv
  File "websockets\protocol.py", line 803, in ensure_open
websockets.exceptions.ConnectionClosedError: code = 1006 (connection closed abnormally [internal]), no reason

2021-09-29T09:32:52.885 wallet wallet_server              : INFO     Connection closed: 127.0.0.1, node id: 6c0e2167f683fd305a2ab9c6766a7c5b60ec056849e5c584e7c7fb67add948f3
2021-09-29T09:32:53.404 farmer farmer                     : INFO     Reconnecting to peer {'host': '127.0.0.1', 'port': 8444}
2021-09-29T09:32:53.404 wallet wallet                     : INFO     Reconnecting to peer {'host': '127.0.0.1', 'port': 8444}
2021-09-29T09:32:55.549 farmer farmer_server              : INFO     Cannot connect to host 127.0.0.1:8444 ssl:<ssl.SSLContext object at 0x000001AB1102CB40> [Komputer zdalny odrzucił połączenie sieciowe]
2021-09-29T09:32:56.445 wallet wallet_server              : INFO     Cannot connect to host 127.0.0.1:8444 ssl:<ssl.SSLContext object at 0x000001E21A17A1C0> [Komputer zdalny odrzucił połączenie sieciowe]

Windows Client 1.2.6 after upgrade to 1.2.8(1.2.9) nothing changed. 
Firewall disabled, antivirus not installed. Any help?

**Comment by snajperus** [comment]
After delete config.yaml and auto create with start of chia.exe working again.
