### ISSUE TITLE
[BUG] Wallet does not sync - RuntimeError: Was not able to add blocks 0-32

### ISSUE THREAD

**Issue by forReason** [Chia-Network/chia-blockchain#8618]
**Describe the bug**
My farm was running and showed farming. However, the pool did not recognize any plots.
looking at more detail, I noticed i was not at full block height. ~500 blocks behind.

Executing chia wallet show prompted to restore from backup. As suggested in some places, I confirmed with s to resync wallet.
Now the wallet and node show "not synced". As to my understanding, it should show "syncing" if it was actually doing something.

**Expected behavior**
wallet syncs and farms

**Desktop**
- OS: Ubuntu 20.04.3 LTS
- CPU: amd ryzen 2600

**Additional context**
debug.log:  
[debug.log](https://github.com/Chia-Network/chia-blockchain/files/7242594/debug.log)
```2021-09-28T09:38:50.886 wallet chia.wallet.wallet_node    : ERROR    Loop exception in sync Was not able to add blocks 0-32. Traceback (most recent call last):
  File "/opt/chia/chia-blockchain/chia/wallet/wallet_node.py", line 608, in sync_job
    await self._sync()
  File "/opt/chia/chia-blockchain/chia/wallet/wallet_node.py", line 668, in _sync
    await self.batch_sync_to_peak(fork_height, peak)
  File "/opt/chia/chia-blockchain/chia/wallet/wallet_node.py", line 565, in batch_sync_to_peak
    raise RuntimeError(f"Was not able to add blocks {start_height}-{end_height}")
RuntimeError: Was not able to add blocks 0-32
```

chia wallet show:  
```Wallet height: 0
Sync status: Not synced
Balances, fingerprint: 2331440369
Wallet ID 1 type STANDARD_WALLET Chia Wallet
   -Total Balance: 0.0 xch (0 mojo)
   -Pending Total Balance: 0.0 xch (0 mojo)
   -Spendable: 0.0 xch (0 mojo)
```

chia farm summary:  
```Farming status: Not synced or not connected to peers
Total chia farmed: 0.0
User transaction fees: 0.0
Block rewards: 0.0
Last height farmed: 0
Local Harvester
   108 plots of size: 10.689 TiB
Plot count for all harvesters: 108
Total size of plots: 10.689 TiB
Estimated network space: 34.867 EiB
Expected time to win: 2 years
Note: log into your key using 'chia wallet show' to see rewards for each key
```

chia show -s -c:  
```Current Blockchain Status: Not Synced. Peak height: 921731
      Time: Tue Sep 28 2021 09:43:58 CEST                  Height:     921731

Estimated network space: 34.819 EiB
Current difficulty: 2976
Current VDF sub_slot_iters: 135266304
Total iterations since the start of the blockchain: 3360361104355

  Height: |   Hash:
   921731 | ef859347d9b11bab904e6b851472a96b9359b9b75baff947a758f096a9cc20fe
   921730 | ddea7a38f216d8d48a5c245326cb86e58d8a20d3ce5280185a7809e8b3c387f8
   921729 | 3592366c642354b58883b8b2b2e687a20500014e023604bc2bd1a8c431fceb84
   921728 | d026af99127467740a850b877e27c1c4ae7a0929c5fdcecb04646c7c4b26105d
   921727 | 0b5c6f21ba1363810bd418a5954e89a7f6945bb7f3f3293adbd416583e902df1
   921726 | 198ce7a51f305d1cb7dca356eb1c988273792abf7462bb780f50ce2c0d62f334
   921725 | dc94973578ac4dc114d86d96e8a13d1a68fbdd07872375488b3f2cfb42b27cc9
   921724 | d0e499d21673405a0186950056fd8a62d39545cd86e487dfbd7615a17b5bb292
   921723 | 6bfa91fa808b41e1aadb213daad23f0d0257c58b26c595f5f6932195431c0813
   921722 | 8eb1499f318d7b385fca44ab09f9517e50f702b83b1ef4eb1325f201d2125dbd

Connections:
Type      IP                                     Ports       NodeID      Last Connect      MiB Up|Dwn
FARMER    127.0.0.1                              57798/8447  549fbda8... Sep 28 09:09:49      0.0|0.0
FULL_NODE 84.119.236.130                          8444/8444  8bf33f77... Sep 28 09:55:13      0.1|6.4
                                                 -SB Height:   921756    -Hash: bf9b1456...
FULL_NODE 159.196.71.244                          8444/8444  f4189543... Sep 28 09:55:13      0.0|5.3
                                                 -SB Height:   921756    -Hash: bf9b1456...
FULL_NODE 71.56.216.195                           8444/8444  f375ea81... Sep 28 09:55:13      0.0|5.3
                                                 -SB Height:   921756    -Hash: bf9b1456...
FULL_NODE 89.127.41.57                            8444/8444  ecab5708... Sep 28 09:55:13      0.0|5.5
                                                 -SB Height:   921756    -Hash: bf9b1456...
FULL_NODE 94.74.126.207                           8444/8444  f57ba986... Sep 28 09:55:13      0.0|6.1
                                                 -SB Height:   921756    -Hash: bf9b1456...
FULL_NODE 114.230.221.78                          8444/8444  b55e07b1... Sep 28 09:55:13      0.0|6.0
                                                 -SB Height:   921756    -Hash: bf9b1456...
FULL_NODE 62.182.28.166                           8444/8444  3899592a... Sep 28 09:55:13      0.0|6.7
                                                 -SB Height:   921756    -Hash: bf9b1456...
FULL_NODE 194.36.145.117                          8444/8444  64b26f0d... Sep 28 09:54:44      0.0|0.0
                                                 -SB Height:   855450    -Hash: 3a1e63a7...
WALLET    127.0.0.1                              58650/8449  0c9b2c8f... Sep 28 09:54:43      0.0|0.0
```
the full node to me indicates that it is syncing, by the mib up/down peak height also rises BUT, on my other node in comparison, it says: `Current Blockchain Status: Syncing 821440/919289.`

**Comment by forReason** [comment]
the full node now appears to be fully synced.

Steps to reproduce:
```
chia stop farmer
cd ~/.chia/mainnet/log
rm debug.log
cd ~/.chia/mainnet/wallet
rm -r db
chia wallet show
s
chia start farmer
```

after this process, a fresh log was generated, which is attached here:
[debug.log](https://github.com/Chia-Network/chia-blockchain/files/7242663/debug.log)

**Comment by forReason** [comment]
had to try multiple times. It might also be related to port forwarding of port 8444.

**Comment by Tomaszu97** [comment]
I've also had that issue and I have properly configured port forwarding which never had any issues.
