### ISSUE TITLE
[BUG] Upgrade from 1.2.5 to 1.2.8 on PopOS 21.04 Fails

### ISSUE THREAD

**Issue by rocketeerbkw** [Chia-Network/chia-blockchain#8665]
**Describe the bug**
When running `install.sh` following the [upgrade instructions in the wiki](https://github.com/Chia-Network/chia-blockchain/wiki/INSTALL#ubuntudebian) the script fails with:

```
user@pop-os:~/chia-blockchain$ sh install.sh
apt-get is /usr/bin/apt-get
Installing on Ubuntu 21.04 or newer.
Hit:1 http://apt.pop-os.org/proprietary hirsute InRelease
Hit:2 http://ppa.launchpad.net/system76/pop/ubuntu hirsute InRelease
Hit:3 http://us.archive.ubuntu.com/ubuntu hirsute InRelease
Hit:4 http://us.archive.ubuntu.com/ubuntu hirsute-security InRelease
Hit:5 http://us.archive.ubuntu.com/ubuntu hirsute-updates InRelease
Hit:6 http://us.archive.ubuntu.com/ubuntu hirsute-backports InRelease
Reading package lists... Done
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
python3-distutils is already the newest version (3.9.5-0ubuntu3~21.04).
python3.9-venv is already the newest version (3.9.5-3~21.04).
0 upgraded, 0 newly installed, 0 to remove and 128 not upgraded.
Python version is 3.9
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/user/chia-blockchain/venv/lib/python3.8/site-packages/pip/__main__.py", line 29, in <module>
    from pip._internal.cli.main import main as _main
  File "/home/user/chia-blockchain/venv/lib/python3.8/site-packages/pip/_internal/cli/main.py", line 9, in <module>
    from pip._internal.cli.autocompletion import autocomplete
  File "/home/user/chia-blockchain/venv/lib/python3.8/site-packages/pip/_internal/cli/autocompletion.py", line 10, in <module>
    from pip._internal.cli.main_parser import create_main_parser
  File "/home/user/chia-blockchain/venv/lib/python3.8/site-packages/pip/_internal/cli/main_parser.py", line 8, in <module>
    from pip._internal.cli import cmdoptions
  File "/home/user/chia-blockchain/venv/lib/python3.8/site-packages/pip/_internal/cli/cmdoptions.py", line 23, in <module>
    from pip._internal.cli.parser import ConfigOptionParser
  File "/home/user/chia-blockchain/venv/lib/python3.8/site-packages/pip/_internal/cli/parser.py", line 12, in <module>
    from pip._internal.configuration import Configuration, ConfigurationError
  File "/home/user/chia-blockchain/venv/lib/python3.8/site-packages/pip/_internal/configuration.py", line 27, in <module>
    from pip._internal.utils.misc import ensure_dir, enum
  File "/home/user/chia-blockchain/venv/lib/python3.8/site-packages/pip/_internal/utils/misc.py", line 42, in <module>
    from pip._internal.locations import get_major_minor_version, site_packages, user_site
  File "/home/user/chia-blockchain/venv/lib/python3.8/site-packages/pip/_internal/locations/__init__.py", line 14, in <module>
    from . import _distutils, _sysconfig
  File "/home/user/chia-blockchain/venv/lib/python3.8/site-packages/pip/_internal/locations/_distutils.py", line 9, in <module>
    from distutils.cmd import Command as DistutilsCommand
ModuleNotFoundError: No module named 'distutils.cmd'
```

**To Reproduce**

1. Install chia pre 1.2.8 with python 3.8
2. Upgrade chia to 1.2.9
3. It fails

**Expected behavior**
A user can upgrade without errors.

**Screenshots**
n/a

**Desktop**

- OS: PopOS
- OS Version/Flavor: 21.04
- CPU: Intel i7-920

**Additional context**
From the script output, it was able to install and find python 3.9 `Python version is 3.9`, but it looks like all the pip commands are running python 3.8 instead.

I fixed this locally by removing the symlinks `venv/bin/python` and `venv/bin/python3` which were both pointing to 3.8. After running install.sh again, the symlinks were recreated and pointing to python 3.9.

**Comment by emlowe** [comment]
Although PopOS is a ubuntu-based distro, we depend on community support for it and a variety of other linux distros. We would welcome any PRs

**Comment by rocketeerbkw** [comment]
@emlowe If I can reproduce on ubuntu would you re-open? I'd bet money that a different windowing system has nothing to do with a bug in a CLI installer.

**Comment by emlowe** [comment]
Yes (I think you yourself can re-open the issue) - however, if on Ubuntu this happens for sure we will take a look. I have tested it and haven't seen it myself - but of course environments are always different
