### ISSUE TITLE
Wallet type 9 cannot create puzzle hashes

### ISSUE THREAD

**Issue by Lowestofttim** [Chia-Network/chia-blockchain#8667]
I am seeing this in my log

It all looks good then i get a spout of this then all goes back to normal again.

**It happen every ten mins without fail?**

2021-10-01T13:14:45.384 wallet chia.rpc.rpc_server        : WARNING  Error while handling message: Traceback (most recent call last):
  File "chia\rpc\rpc_server.py", line 83, in inner
  File "chia\rpc\wallet_rpc_api.py", line 714, in get_next_address
ValueError: Wallet type 9 cannot create puzzle hashes

2021-10-01T13:14:45.814 wallet chia.rpc.rpc_server        : WARNING  Error while handling message: Traceback (most recent call last):
  File "chia\rpc\rpc_server.py", line 83, in inner
  File "chia\rpc\wallet_rpc_api.py", line 714, in get_next_address
ValueError: Wallet type 9 cannot create puzzle hashes

2021-10-01T13:14:46.258 wallet chia.rpc.rpc_server        : WARNING  Error while handling message: Traceback (most recent call last):
  File "chia\rpc\rpc_server.py", line 83, in inner
  File "chia\rpc\wallet_rpc_api.py", line 714, in get_next_address
ValueError: Wallet type 9 cannot create puzzle hashes

2021-10-01T13:14:46.500 wallet chia.rpc.rpc_server        : WARNING  Error while handling message: Traceback (most recent call last):
  File "chia\rpc\rpc_server.py", line 83, in inner
  File "chia\rpc\wallet_rpc_api.py", line 714, in get_next_address
ValueError: Wallet type 9 cannot create puzzle hashes

2021-10-01T13:14:46.745 wallet chia.rpc.rpc_server        : WARNING  Error while handling message: Traceback (most recent call last):
  File "chia\rpc\rpc_server.py", line 83, in inner
  File "chia\rpc\wallet_rpc_api.py", line 714, in get_next_address
ValueError: Wallet type 9 cannot create puzzle hashes

2021-10-01T13:14:47.083 wallet chia.rpc.rpc_server        : WARNING  Error while handling message: Traceback (most recent call last):
  File "chia\rpc\rpc_server.py", line 83, in inner
  File "chia\rpc\wallet_rpc_api.py", line 714, in get_next_address
ValueError: Wallet type 9 cannot create puzzle hashes

2021-10-01T13:14:47.511 wallet chia.rpc.rpc_server        : WARNING  Error while handling message: Traceback (most recent call last):
  File "chia\rpc\rpc_server.py", line 83, in inner
  File "chia\rpc\wallet_rpc_api.py", line 714, in get_next_address
ValueError: Wallet type 9 cannot create puzzle hashes

2021-10-01T13:14:48.059 wallet chia.rpc.rpc_server        : WARNING  Error while handling message: Traceback (most recent call last):
  File "chia\rpc\rpc_server.py", line 83, in inner
  File "chia\rpc\wallet_rpc_api.py", line 714, in get_next_address
ValueError: Wallet type 9 cannot create puzzle hashes

2021-10-01T13:14:48.881 wallet chia.rpc.rpc_server        : WARNING  Error while handling message: Traceback (most recent call last):
  File "chia\rpc\rpc_server.py", line 83, in inner
  File "chia\rpc\wallet_rpc_api.py", line 714, in get_next_address
ValueError: Wallet type 9 cannot create puzzle hashes

**Comment by SAVAMforWIN** [comment]
i have same problem
