### ISSUE TITLE
Chia hangs and absolutely not usable

### ISSUE THREAD

**Issue by hardhub** [Chia-Network/chia-blockchain#8722]
It is latest message from log:

```
2021-10-05T06:38:02.972 full_node full_node_server        : ERROR    Exception: G2 element is invalid <class 'ValueError'>, closing connection {'host': 'x.x.x.x', 'port': 8444}. Traceback (most recent call last):
  File "/root/Products/chia-blockchain/chia/server/server.py", line 569, in api_call
    response: Optional[Message] = await asyncio.wait_for(wrapped_coroutine(), timeout=timeout)
  File "/usr/lib64/python3.9/asyncio/tasks.py", line 442, in wait_for
    return await fut
  File "/root/Products/chia-blockchain/chia/server/server.py", line 566, in wrapped_coroutine
    raise e
  File "/root/Products/chia-blockchain/chia/server/server.py", line 559, in wrapped_coroutine
    result = await coroutine
  File "/root/Products/chia-blockchain/chia/full_node/full_node_api.py", line 1313, in new_compact_vdf
    await self.full_node.new_compact_vdf(request, peer)
  File "/root/Products/chia-blockchain/chia/full_node/full_node.py", line 1955, in new_compact_vdf
    header_block = await self.blockchain.get_header_block_by_height(
  File "/root/Products/chia-blockchain/chia/consensus/blockchain.py", line 780, in get_header_block_by_height
    header_dict: Dict[bytes32, HeaderBlock] = await self.get_header_blocks_in_range(height, height, tx_filter)
  File "/root/Products/chia-blockchain/chia/consensus/blockchain.py", line 756, in get_header_blocks_in_range
    blocks_on_disk: List[FullBlock] = await self.block_store.get_blocks_by_hash(hashes)
  File "/root/Products/chia-blockchain/chia/full_node/block_store.py", line 217, in get_blocks_by_hash
    full_block: FullBlock = FullBlock.from_bytes(row[1])
  File "/root/Products/chia-blockchain/chia/util/streamable.py", line 341, in from_bytes
    parsed = cls.parse(f)
  File "/root/Products/chia-blockchain/chia/util/streamable.py", line 279, in parse
    for field, value in zip(fields, values):
  File "/root/Products/chia-blockchain/chia/util/streamable.py", line 278, in <genexpr>
    values: Iterator = (parse_f(f) for parse_f in PARSE_FUNCTIONS_FOR_STREAMABLE_CLASS[cls])
  File "/root/Products/chia-blockchain/chia/util/streamable.py", line 279, in parse
    for field, value in zip(fields, values):
  File "/root/Products/chia-blockchain/chia/util/streamable.py", line 278, in <genexpr>
    values: Iterator = (parse_f(f) for parse_f in PARSE_FUNCTIONS_FOR_STREAMABLE_CLASS[cls])
  File "/root/Products/chia-blockchain/chia/util/streamable.py", line 268, in <lambda>
    return lambda f: parse_size_hints(f, f_type, bytes_to_read)
  File "/root/Products/chia-blockchain/chia/util/streamable.py", line 230, in parse_size_hints
    return f_type.from_bytes(bytes_read)
ValueError: G2 element is invalid

2021-10-05T06:38:03.073 full_node full_node_server        : WARNING  Banning x.x.x.x for 10 seconds
```

After restarting it works during 10-20 minutes and all happens again.

**Comment by hardhub** [comment]
From console window after restart:

```
  File "/root/Products/chia-blockchain/venv/bin/chia_full_node", line 33, in <module>
    sys.exit(load_entry_point('chia-blockchain', 'console_scripts', 'chia_full_node')())
  File "/root/Products/chia-blockchain/chia/server/start_full_node.py", line 60, in main
    return run_service(**kwargs)
  File "/root/Products/chia-blockchain/chia/server/start_service.py", line 255, in run_service
Exception in thread Thread-3:
    return asyncio.run(async_run_service(*args, **kwargs))
Traceback (most recent call last):
Exception in thread Thread-1:
  File "/root/Products/chia-blockchain/venv/lib64/python3.9/site-packages/aiosqlite/core.py", line 109, in run
Traceback (most recent call last):
  File "/usr/lib64/python3.9/asyncio/runners.py", line 44, in run
  File "/root/Products/chia-blockchain/venv/lib64/python3.9/site-packages/aiosqlite/core.py", line 109, in run
    return loop.run_until_complete(main)
  File "/usr/lib64/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    get_loop(future).call_soon_threadsafe(set_result, future, result)
  File "/usr/lib64/python3.9/asyncio/base_events.py", line 791, in call_soon_threadsafe
    get_loop(future).call_soon_threadsafe(set_result, future, result)
    return future.result()
  File "/root/Products/chia-blockchain/chia/server/start_service.py", line 249, in async_run_service
  File "/usr/lib64/python3.9/asyncio/base_events.py", line 791, in call_soon_threadsafe
    self._check_closed()
    self._check_closed()
  File "/usr/lib64/python3.9/asyncio/base_events.py", line 510, in _check_closed
  File "/usr/lib64/python3.9/asyncio/base_events.py", line 510, in _check_closed
    return await service.run()
  File "/root/Products/chia-blockchain/chia/server/start_service.py", line 171, in run
    await self.start()
  File "/root/Products/chia-blockchain/chia/server/start_service.py", line 143, in start
    raise RuntimeError('Event loop is closed')
    await self._server.start_server(self._on_connect_callback)
  File "/root/Products/chia-blockchain/chia/server/server.py", line 240, in start_server
RuntimeError: Event loop is closed

During handling of the above exception, another exception occurred:

    await self.site.start()
  File "/root/Products/chia-blockchain/venv/lib64/python3.9/site-packages/aiohttp/web_runner.py", line 121, in start
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
    self._server = await loop.create_server(
  File "/usr/lib64/python3.9/asyncio/base_events.py", line 1494, in create_server
Traceback (most recent call last):
  File "/usr/lib64/python3.9/threading.py", line 973, in _bootstrap_inner
    raise OSError(err.errno, 'error while attempting '
  File "/usr/lib64/python3.9/threading.py", line 973, in _bootstrap_inner
OSError: [Errno 98] error while attempting to bind on address ('::', 8444, 0, 0): address already in use
    self.run()
  File "/root/Products/chia-blockchain/venv/lib64/python3.9/site-packages/aiosqlite/core.py", line 117, in run
    self.run()
  File "/root/Products/chia-blockchain/venv/lib64/python3.9/site-packages/aiosqlite/core.py", line 117, in run
    get_loop(future).call_soon_threadsafe(set_exception, future, e)
  File "/usr/lib64/python3.9/asyncio/base_events.py", line 791, in call_soon_threadsafe
    get_loop(future).call_soon_threadsafe(set_exception, future, e)
  File "/usr/lib64/python3.9/asyncio/base_events.py", line 791, in call_soon_threadsafe
    self._check_closed()
  File "/usr/lib64/python3.9/asyncio/base_events.py", line 510, in _check_closed
    self._check_closed()
  File "/usr/lib64/python3.9/asyncio/base_events.py", line 510, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
```
