### ISSUE TITLE
[BUG] 1.2.9 - Not Synced since 2 days - full_node hitting Err.UNKNOWN_UNSPENT in DB

### ISSUE THREAD

**Issue by Jcragons** [Chia-Network/chia-blockchain#8739]
Since 2 days i'm not synced anymore, i think it was the case too on 1.2.6, so just in case i've upgraded (Debian Buster here). I've seen there was some issues with database sqlite crash, but look like it's not the case here. I've started with info log, and i've seen a lot of ssl issues on peers

2021-10-06T09:44:43.742 full_node full_node_server        : INFO     Cannot connect to host 178.174.129.122:8444 ssl:<ssl.SSLContext object at 0x7fed85513740> [Connect call failed ('178.174.129.122', 8444)]
2021-10-06T09:44:44.356 full_node full_node_server        : INFO     Cannot connect to host 59.45.18.250:6899 ssl:<ssl.SSLContext object at 0x7fed85513ec0> [Connect call failed ('59.45.18.250', 6899)]

and receive a lot of 
ERROR    Error: Err.UNKNOWN_UNSPENT, Invalid block from peer: {'host': '84.191.251.231', 'port': 8444}

I don't know if it's more than habitual, maybe there is some bugs spreading in all clients. Maybe it's related too to a revoked ssl certification due to end date like some pools (has they have started nearly 1 year ago and forget to renew ssl ...)

**Comment by Jcragons** [comment]
Thx, i'll contact you here.

**Comment by xiaocairush** [comment]
Hi is there any solution? I have the same issue today.

```
2021-10-10T16:13:02.500 wallet wallet                     : INFO     Reconnecting to peer {'host': '127.0.0.1', 'port': 8444}
2021-10-10T16:13:03.389 farmer farmer                     : INFO     Reconnecting to peer {'host': '127.0.0.1', 'port': 8444}
2021-10-10T16:13:04.531 wallet wallet_server              : INFO     Cannot connect to host 127.0.0.1:8444 ssl:<ssl.SSLContext object at 0x0000029C38759840> [Ô¶³Ì¼ÆËã»ú¾Ü¾øÍøÂçÁ¬½Ó¡£]
2021-10-10T16:13:05.421 farmer farmer_server              : INFO     Cannot connect to host 127.0.0.1:8444 ssl:<ssl.SSLContext object at 0x0000025CD184A440> [Ô¶³Ì¼ÆËã»ú¾Ü¾øÍøÂçÁ¬½Ó¡£]
```

**Comment by xiaocairush** [comment]
Found there are some errors in my log:
```
2021-10-10T19:05:02.493 wallet chia.wallet.wallet_node    : ERROR    Error while trying to fetch from peer:Peer returned no response Traceback (most recent call last):
  File "chia\wallet\wallet_node.py", line 555, in batch_sync_to_peak
  File "chia\wallet\wallet_node.py", line 687, in fetch_blocks_and_validate
ValueError: Peer returned no response
```

**Comment by loppefaaret** [comment]
Internally, this has been flagged as a potential corrupted DB - if removing the DB, and resyncing does not change the outcome, please reopen the issue
