### ISSUE TITLE
[BUG] 1.2.9 can't sync anymore!

### ISSUE THREAD

**Issue by xiaocairush** [Chia-Network/chia-blockchain#8788]
**Describe the bug**

1.2.9 can't sync anymore.

**To Reproduce**

Not exactly know how to reproduce it.
Today I found the issue but it's ok before.
I'm creating plotnft in this matchine.

**Expected behavior**
The node should be syncd.

**Desktop**

- OS: Windows

**Additional context**

debug.log
```
2021-10-10T19:05:02.493 wallet chia.wallet.wallet_node    : ERROR    Error while trying to fetch from peer:Peer returned no response Traceback (most recent call last):
  File "chia\wallet\wallet_node.py", line 555, in batch_sync_to_peak
  File "chia\wallet\wallet_node.py", line 687, in fetch_blocks_and_validate
ValueError: Peer returned no response
```
have a quick scan on source code, the error message is logged in this [line](https://github.com/Chia-Network/chia-blockchain/blob/1.2.9/chia/wallet/wallet_node.py#L687)

Have tried 1.2.3, 1.2.6, 1.2,7, 1.2.8. None of them work.

**Comment by tobros91** [comment]
I solved this issue by syncing the time. For some reason the NTP service on my computer stopped and time got offset with +2 hours.
