### ISSUE TITLE
Spinning for all tiles in GUI + KeyError in debug for Wallet Start

### ISSUE THREAD

**Issue by BigPeteL** [Chia-Network/chia-blockchain#8798]
### Discussed in https://github.com/Chia-Network/chia-blockchain/discussions/8751

<div type='discussions-op-text'>

<sup>Originally posted by **BigPeteL** October  7, 2021</sup>
Hi Folks,
I've recently upgraded to 1.2.9 and on starting the full node the gui it shows the correct account but when selected everything on the Full Node Tab is the spinning circle (even after 48hrs+)  On investigation I can see the following errors in the debug.log

`2021-10-06T12:25:43.217 farmer farmer_server              : INFO     Cannot connect to host 127.0.0.1:8444 ssl:<ssl.SSLContext object at 0x7f74b4a9a740> [Connect call failed ('127.0.0.1', 8444)]
2021-10-06T12:25:44.372 wallet wallet                     : INFO     Reconnecting to peer {'host': '127.0.0.1', 'port': 8444}
2021-10-06T12:25:44.375 wallet wallet_server              : INFO     Cannot connect to host 127.0.0.1:8444 ssl:<ssl.SSLContext object at 0x7f5b8d17a4c0> [Connect call failed ('127.0.0.1', 8444)]
2021-10-06T12:25:46.220 farmer farmer                     : INFO     Reconnecting to peer {'host': '127.0.0.1', 'port': 8444}
2021-10-06T12:25:46.223 farmer farmer_server              : INFO     Cannot connect to host 127.0.0.1:8444 ssl:<ssl.SSLContext object at 0x7f74b4a76ac0> [Connect call failed ('127.0.0.1', 8444)]
2021-10-06T12:25:47.376 wallet wallet                     : INFO     Reconnecting to peer {'host': '127.0.0.1', 'port': 8444}
2021-10-06T12:25:47.379 wallet wallet_server              : INFO     Cannot connect to host 127.0.0.1:8444 ssl:<ssl.SSLContext object at 0x7f5b8d17a840> [Connect call failed ('127.0.0.1', 8444)]
2021-10-06T12:25:49.225 farmer farmer                     : INFO     Reconnecting to peer {'host': '127.0.0.1', 'port': 8444}
2021-10-06T12:25:49.228 farmer farmer_server              : INFO     Cannot connect to host 127.0.0.1:8444 ssl:<ssl.SSLContext object at 0x7f74b4b18e40> [Connect call failed ('127.0.0.1', 8444)]
2021-10-06T12:25:50.383 wallet wallet                     : INFO     Reconnecting to peer {'host': '127.0.0.1', 'port': 8444}`

After starting the full node (or just wallet-only) I get an error on screen of - 
`Traceback (most recent call last):
  File "/home/username/chia-blockchain/venv/bin/chia_full_node", line 33, in <module>
    sys.exit(load_entry_point('chia-blockchain', 'console_scripts', 'chia_full_node')())
  File "/home/username/chia-blockchain/chia/server/start_full_node.py", line 60, in main
    return run_service(**kwargs)
  File "/home/username/chia-blockchain/chia/server/start_service.py", line 255, in run_service
    return asyncio.run(async_run_service(*args, **kwargs))
  File "/usr/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/username/chia-blockchain/chia/server/start_service.py", line 249, in async_run_service
    return await service.run()
  File "/home/username/chia-blockchain/chia/server/start_service.py", line 171, in run
    await self.start()
  File "/home/username/chia-blockchain/chia/server/start_service.py", line 135, in start
    await self._node._start(**kwargs)
  File "/home/username/chia-blockchain/chia/full_node/full_node.py", line 153, in _start
    self.blockchain = await Blockchain.create(self.coin_store, self.block_store, self.constants, self.hint_store)
  File "/home/username/chia-blockchain/chia/consensus/blockchain.py", line 116, in create
    await self._load_chain_from_store()
  File "/home/username/chia-blockchain/chia/consensus/blockchain.py", line 129, in _load_chain_from_store
    height_to_hash, sub_epoch_summaries = await self.block_store.get_peak_height_dicts()
  File "/home/username/chia-blockchain/chia/full_node/block_store.py", line 322, in get_peak_height_dicts
    curr_height = hash_to_height[curr_header_hash]
KeyError: b'<SNIP FOR PRIVACY>'`

I've tried even just starting the wallet-only and still receive the same KeyError above.  I've tried renaming the .chia folder and re-setting up/resyncing but neither seem to help.

Anyone have any suggestions?</div>

**Comment by shaneo257** [comment]
i would restart the computer, make sure your system clock is showing the correct time and then start the client

**Comment by hoangviet1990** [comment]
Are you using Windows 11?

**Comment by BigPeteL** [comment]
After 12days syncing back up its back and running again.  Hope this helps someone else.
