### ISSUE TITLE
[BUG] Chia client CRASH - The Network name is no longer valid -  Second post

### ISSUE THREAD

**Issue by lpaln** [Chia-Network/chia-blockchain#8817]
**Describe the bug**
This error seems to be getting worse all the sudden. Many people had this months ago. I have now experienced this 2 times over the last 5 days resulting in significant lost  farming time.  This has become a priority for me now.

The chia client crashes and produces the following log entry. All activity stops.

_2_021-10-12T21:29:02.145 daemon __main__                   : INFO     Websocket exception. Closing websocket with wallet_ui code = 1006 (connection closed abnormally [internal]), no reason Traceback (most recent call last):
  File "asyncio\windows_events.py", line 457, in finish_recv
OSError: [WinError 64] The specified network name is no longer available

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "websockets\protocol.py", line 827, in transfer_data
  File "websockets\protocol.py", line 895, in read_message
  File "websockets\protocol.py", line 971, in read_data_frame
  File "websockets\protocol.py", line 1047, in read_frame
  File "websockets\framing.py", line 105, in read
  File "asyncio\streams.py", line 723, in readexactly
  File "asyncio\streams.py", line 517, in _wait_for_data
  File "asyncio\proactor_events.py", line 280, in _loop_reading
  File "asyncio\windows_events.py", line 812, in _poll
  File "asyncio\windows_events.py", line 461, in finish_recv
ConnectionResetError: [WinError 64] The specified network name is no longer available

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "Lib\site-packages\chia\daemon\server.py", line 193, in safe_handle
  File "websockets\protocol.py", line 439, in __aiter__
  File "websockets\protocol.py", line 509, in recv
  File "websockets\protocol.py", line 803, in ensure_open
websockets.exceptions.ConnectionClosedError: code = 1006 (connection closed abnormally [internal]), no reason__

**To Reproduce**
Leave the Chia client farming on the PC.

- OS: Windows 10

- CPU: intel 10850k

**Additional context**

**Comment by emlowe** [comment]
Closing issue as it seems newer versions largely resolve related issues
