### ISSUE TITLE
[BUG] Can't sync wallet-node (Loop exception in sync Was not able to add blocks 1029930-1029962)

### ISSUE THREAD

**Issue by andriitalkstech** [Chia-Network/chia-blockchain#8923]
**Describe the bug**
Can't sync a wallet although the blockchain itself is synced.
Have tried to delete both DBs - wallet and blockchain, and resynced again.
Tried deleting the wallet and importing it back.
The wallet is the latest version - 1.2.9

**To Reproduce**

1. Start a wallet and try to Sync
2. Go log and see the error

```
2021-10-25T10:48:11.386 wallet chia.full_node.weight_proof: INFO     validating 2725 sub epochs
2021-10-25T10:48:11.448 wallet chia.wallet.wallet_node    : INFO     Validated, fork point is 1029146
2021-10-25T10:48:11.449 wallet chia.wallet.wallet_node    : INFO     self.sync_event.set()
2021-10-25T10:48:11.470 wallet chia.wallet.wallet_node    : INFO     Have collected 1721 potential peaks
2021-10-25T10:48:11.474 wallet chia.wallet.wallet_node    : INFO     self.sync_event.set()
2021-10-25T10:48:11.475 wallet chia.wallet.wallet_node    : INFO     self.sync_event.set()
2021-10-25T10:48:12.402 full_node chia.full_node.full_node: INFO       Finished signage point 11/64: CC: 8f9d464d079ca17********************* RC: e50ef8b2786fe2************ 
2021-10-25T10:48:12.562 wallet chia.wallet.wallet_node    : INFO     Requesting blocks 1029931-1029963
2021-10-25T10:48:12.958 harvester chia.harvester.harvester: INFO     2 plots were eligible for farming 1205ec2e02... Found 0 proofs. Time: 0.54900 s. Total 280 plots
2021-10-25T10:48:13.167 full_node full_node_server        : INFO     Connection closed: 127.0.0.1, node id: 7fc545f45bf46c441***********
2021-10-25T10:48:13.168 full_node chia.full_node.full_node: INFO     peer disconnected {'host': '127.0.0.1', 'port': 8449}
2021-10-25T10:48:13.167 wallet wallet_server              : INFO     Connection closed: 127.0.0.1, node id: 02f8f86aa0c96****
2021-10-25T10:48:14.176 wallet chia.wallet.wallet_node    : ERROR    Error while trying to fetch from peer:Was not able to obtain solution {'coin_name': '0xbd6dd88e84*****a4e925', 'height': 1029933} Traceback (most recent call last):
  File "chia\wallet\wallet_node.py", line 555, in batch_sync_to_peak
  File "chia\wallet\wallet_node.py", line 726, in fetch_blocks_and_validate
  File "chia\wallet\wallet_node.py", line 893, in get_additional_coin_spends
  File "chia\wallet\wallet_node.py", line 876, in fetch_puzzle_solution
ValueError: Was not able to obtain solution {'coin_name': '0xbd6dd88e84af***********', 'height': 1029933}

2021-10-25T10:48:14.177 wallet chia.wallet.wallet_node    : ERROR    Loop exception in sync Was not able to add blocks 1029931-1029963. Traceback (most recent call last):
  File "chia\wallet\wallet_node.py", line 608, in sync_job
  File "chia\wallet\wallet_node.py", line 668, in _sync
  File "chia\wallet\wallet_node.py", line 565, in batch_sync_to_peak
RuntimeError: Was not able to add blocks 1029931-1029963

2021-10-25T10:48:14.178 wallet chia.wallet.wallet_node    : INFO     Loop end in sync job
2021-10-25T10:48:14.178 wallet chia.wallet.wallet_node    : INFO     Loop start in sync job
2021-10-25T10:48:14.179 wallet chia.wallet.wallet_node    : INFO     Have collected 1721 potential peaks
2021-10-25T10:48:14.181 wallet chia.wallet.wallet_node    : INFO     No peers to sync to
2021-10-25T10:48:14.182 wallet chia.wallet.wallet_node    : INFO     Loop end in sync job
2021-10-25T10:48:14.182 wallet chia.wallet.wallet_node    : INFO     Loop start in sync job
2021-10-25T10:48:14.183 wallet chia.wallet.wallet_node    : WARNING  bad peak response from peer None
2021-10-25T10:48:14.471 wallet wallet                     : INFO     Reconnecting to peer {'host': '127.0.0.1', 'port': 8444}
2021-10-25T10:48:14.478 wallet wallet_server              : INFO     Connected with full_node {'host': '127.0.0.1', 'port': 8444}
```

**Expected behavior**
Wallet and blockchain can be synced to the netspace

**Desktop**

- OS: Win10
- CPU: AMD Ryzen 5 2600

**Comment by andriitalkstech** [comment]
@emlowe Thanks for the answers, I have backed down to 1.2.10 and it's working since...
The strange thing is with a new version is that pooling doesn't work properly - spacepool only sees my ~15% of my plots and I'm not getting any better with that over time...
I've tried even newer versions and it doesn't seem to be very stable for me...
Let me know if you want any other version tested and get some feedback - would be glad to help.

For my node everything was running great on 1.2.10 until it hit the dead-end with specific block, after which everything(expect node itself) started to be unstable:
* wallet syncing really slow or couldn't seek (keep up with the blockchain)
* Pooling system is using ~15% of my registered and valid plots (only valid on specific build version)
* Clicking a second time(after initialization) on "Keys" button messes up with everything and it stops responding.

I see with new versions you are working guys on a really great stuff and features, hope they will come very soon and become more stable <3

**Comment by Gigko** [comment]
was not able to sync my wallet on the latest version on ubuntu.


2021-10-30T18:25:42.859 wallet chia.wallet.wallet_node    : ERROR    Loop exception in sync Was not able to add blocks 1028137-1028169. Traceback (most recent call last):

+ 

2021-10-30T18:25:57.156 wallet chia.wallet.wallet_node    : ERROR    Error while trying to fetch from peer:Was not able to obtain solution {'coin_name': '0xf2381f7e787884542c3191dbc53d28b3fcd53c5ac4483df03164e809b96e5c4b', 'height': 1028139} Traceback (most recent call last):

**Comment by rizkyaulya** [comment]
> was not able to sync my wallet on the latest version on ubuntu.
> 
> 2021-10-30T18:25:42.859 wallet chia.wallet.wallet_node : ERROR Loop exception in sync Was not able to add blocks 1028137-1028169. Traceback (most recent call last):
> 
> 
> 2021-10-30T18:25:57.156 wallet chia.wallet.wallet_node : ERROR Error while trying to fetch from peer:Was not able to obtain solution {'coin_name': '0xf2381f7e787884542c3191dbc53d28b3fcd53c5ac4483df03164e809b96e5c4b', 'height': 1028139} Traceback (most recent call last):

Try the newest beta realease:
https://download-chia-net.s3-us-west-2.amazonaws.com/builds/ChiaSetup-1.2.119.exe
It fixed the problem for me

**Comment by rizkyaulya** [comment]
> was not able to sync my wallet on the latest version on ubuntu.
> 
> 2021-10-30T18:25:42.859 wallet chia.wallet.wallet_node : ERROR Loop exception in sync Was not able to add blocks 1028137-1028169. Traceback (most recent call last):
> 
> 
> 2021-10-30T18:25:57.156 wallet chia.wallet.wallet_node : ERROR Error while trying to fetch from peer:Was not able to obtain solution {'coin_name': '0xf2381f7e787884542c3191dbc53d28b3fcd53c5ac4483df03164e809b96e5c4b', 'height': 1028139} Traceback (most recent call last):

Try the newest beta release:  
https://download-chia-net.s3-us-west-2.amazonaws.com/builds/ChiaSetup-1.2.120.exe
It fixed the problem for me

**Comment by Gigko** [comment]
> 
> 
> > was not able to sync my wallet on the latest version on ubuntu.
> > 2021-10-30T18:25:42.859 wallet chia.wallet.wallet_node : ERROR Loop exception in sync Was not able to add blocks 1028137-1028169. Traceback (most recent call last):
> > 2021-10-30T18:25:57.156 wallet chia.wallet.wallet_node : ERROR Error while trying to fetch from peer:Was not able to obtain solution {'coin_name': '0xf2381f7e787884542c3191dbc53d28b3fcd53c5ac4483df03164e809b96e5c4b', 'height': 1028139} Traceback (most recent call last):
> 
> Try the newest beta release: https://download-chia-net.s3-us-west-2.amazonaws.com/builds/ChiaSetup-1.2.119.exe It fixed the problem for me
Thank you very much for the response, but is there this version for linux?

**Comment by Gigko** [comment]
I've managed to sync my wallet using the beta version from the chia official website, but it created additional pooling wallets that I don't need and I can't delete them.
![изображение](https://user-images.githubusercontent.com/3913126/139956727-bae26f85-e738-48f4-867d-4c31f4609826.png)

**Comment by rizkyaulya** [comment]
> > > was not able to sync my wallet on the latest version on ubuntu.
> > > 2021-10-30T18:25:42.859 wallet chia.wallet.wallet_node : ERROR Loop exception in sync Was not able to add blocks 1028137-1028169. Traceback (most recent call last):
> > > 2021-10-30T18:25:57.156 wallet chia.wallet.wallet_node : ERROR Error while trying to fetch from peer:Was not able to obtain solution {'coin_name': '0xf2381f7e787884542c3191dbc53d28b3fcd53c5ac4483df03164e809b96e5c4b', 'height': 1028139} Traceback (most recent call last):
> > 
> > 
> > Try the newest beta release: https://download-chia-net.s3-us-west-2.amazonaws.com/builds/ChiaSetup-1.2.119.exe It fixed the problem for me
> > Thank you very much for the response, but is there this version for linux?

I think you can always find it at official download page :
https://www.chia.net/download/

as I learned from this discussion the latest beta version fix some reported bugs.
While we waiting for  the latest stable release from the team.
