### ISSUE TITLE
[BUG] Chia does not handle out-of-memory (or other) exceptions during plotting

### ISSUE THREAD

**Issue by monta990** [Chia-Network/chia-blockchain#9005]
**Describe the bug**
It happens when i create a parallels plots, only the first start

**To Reproduce**
Normal steps to create plots

**Expected behavior**
Can plot in parallel

**Desktop**
Windows 10 21H2
Intel i5-10400
16 GB RAM

**Additional context**
Log:

```
2021-10-28T08:25:24.601  chia.plotting.create_plots       : [32mINFO    [0m Creating 1 plots of size 32, pool contract address:  xch17hfyf3kdkyegpyc5cdkryuqlzyxc8p9dacym4xtemvdvwdxn6k7svax75r farmer public key: af7285b94eb02e417fa3fa78a5b30dec7ded1c67a094464cfd7f575af6a96bc482e6393763edd00bbfa868d43c3f7175[0m
2021-10-28T08:25:24.608  chia.plotting.create_plots       : [32mINFO    [0m Memo: f5d244c6cdb132809314c36c32701f110d8384adee09ba9979db1ac734d3d5bdaf7285b94eb02e417fa3fa78a5b30dec7ded1c67a094464cfd7f575af6a96bc482e6393763edd00bbfa868d43c3f71753f3b4ccbe763e3a59063d62a5ae0cfba3d7aef352fb01032a2191724f0d661b4[0m
2021-10-28T08:25:24.608  chia.plotting.create_plots       : [32mINFO    [0m Starting plot 1/1[0m

Starting plotting progress into temporary dirs: D:\ and D:\
ID: 044e2ab8187f05cd78bfdd5f045cce8715c793a71231bc66271429585ce134a6
Plot size is: 32
Buffer size is: 6000MiB
Using 128 buckets
Final Directory is: E:\
Using 4 threads of stripe size 65536
Process ID is: 5088

Starting phase 1/4: Forward Propagation into tmp files... Thu Oct 28 08:25:24 2021
Computing table 1
F1 complete, time: 223.007 seconds. CPU (89.24%) Thu Oct 28 08:29:07 2021
Computing table 2
Caught plotting error: bad allocation
Traceback (most recent call last):
  File "Lib\site-packages\chia\cmds\chia.py", line 132, in <module>
  File "Lib\site-packages\chia\cmds\chia.py", line 128, in main
  File "click\core.py", line 829, in __call__
  File "click\core.py", line 782, in main
  File "click\core.py", line 1259, in invoke
  File "click\core.py", line 1259, in invoke
  File "click\core.py", line 1066, in invoke
  File "click\core.py", line 610, in invoke
  File "click\decorators.py", line 21, in new_func
  File "chia\cmds\plots.py", line 153, in create_cmd
  File "asyncio\base_events.py", line 642, in run_until_complete
  File "chia\plotting\create_plots.py", line 250, in create_plots
RuntimeError: bad allocation
[5088] Failed to execute script 'chia' due to unhandled exception!
```

**Comment by emlowe** [comment]
You don't have enough memory  - `RunTimeError: bad allocation` means you are out of memory. I'm not sure how many plots you are trying to run in parallel - but you don't have enough memory. You are using a memory reserve of `Buffer size is: 6000MiB` , those running even two in parallel puts you up to 12GiB. 

The error messaging could be improved here - but the result is that you don't have enough memory to perform the action you are trying to perform

**Comment by emlowe** [comment]
Added trello card for exception handling here : https://trello.com/c/ZOCc50dj/1406-add-exception-handling-for-creating-plots
