### ISSUE TITLE
Error in debug.log causing Harvester to crash

### ISSUE THREAD

**Issue by brianwfreeman** [Chia-Network/chia-blockchain#9014]
I have a remote harvester that keeps disconnecting and I suspect it is due to the following error in my debug.log:

2021-10-28T01:37:10.305 harvester chia.plotting.util      : WARNING  Error reading directory /mnt/007 [Errno 5] Input/output error: '/mnt/007/plot-k32-2021-08-03-08-02-71a9332e5a6945ab28633933415937399ba43a16c352036ddacf24ef5be953ad.plot.tmp'

The problem here is that this file does not exist.  I searched for the file, showed hidden files etc.  I have restarted the harvester, and I have rebooted the machine.  Nothing stops this error from recurring.

**Comment by emlowe** [comment]
Note, I wouldn't have expected this file to cause the harvester to crash or disconnect. what OS are you using and how are these drives mounted?

**Comment by brianwfreeman** [comment]
This harvester is cursed. Here is my new disconnect error:
```
2021-10-30T00:12:40.889 daemon chia.daemon.server         : INFO     Websocket exception. Closing websocket with chia_harvester code = 1006 (connection closed abnormally [internal]), no reason Traceback (most recent call last):
  File "/home/brian/chia-blockchain/venv/lib/python3.8/site-packages/websockets/protocol.py", line 827, in transfer_data
    message = await self.read_message()
  File "/home/brian/chia-blockchain/venv/lib/python3.8/site-packages/websockets/protocol.py", line 895, in read_message
    frame = await self.read_data_frame(max_size=self.max_size)
  File "/home/brian/chia-blockchain/venv/lib/python3.8/site-packages/websockets/protocol.py", line 971, in read_data_frame
    frame = await self.read_frame(max_size)
  File "/home/brian/chia-blockchain/venv/lib/python3.8/site-packages/websockets/protocol.py", line 1047, in read_frame
    frame = await Frame.read(
  File "/home/brian/chia-blockchain/venv/lib/python3.8/site-packages/websockets/framing.py", line 105, in read
    data = await reader(2)
  File "/usr/lib/python3.8/asyncio/streams.py", line 721, in readexactly
    raise exceptions.IncompleteReadError(incomplete, n)
asyncio.exceptions.IncompleteReadError: 0 bytes read on a total of 2 expected bytes

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/brian/chia-blockchain/chia/daemon/server.py", line 193, in safe_handle
    async for message in websocket:
  File "/home/brian/chia-blockchain/venv/lib/python3.8/site-packages/websockets/protocol.py", line 439, in __aiter__
    yield await self.recv()
  File "/home/brian/chia-blockchain/venv/lib/python3.8/site-packages/websockets/protocol.py", line 509, in recv
    await self.ensure_open()
  File "/home/brian/chia-blockchain/venv/lib/python3.8/site-packages/websockets/protocol.py", line 803, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedError: code = 1006 (connection closed abnormally [internal]), no reason

```
