### ISSUE TITLE
[BUG]Not Connected No Syncing released 1.2.10

### ISSUE THREAD

**Issue by Jutean** [Chia-Network/chia-blockchain#9028]
2021-10-30T09:41:10.589 full_node asyncio                 : ERROR    Future exception was never retrieved
future: <Future finished exception=BrokenProcessPool('A process in the process pool was terminated abruptly while the future was running or pending.')>
Traceback (most recent call last):
  File "chia\full_node\full_node.py", line 734, in _sync
  File "chia\full_node\weight_proof.py", line 606, in validate_weight_proof
concurrent.futures.process.BrokenProcessPool: A process in the process pool was terminated abruptly while the future was running or pending.
2021-10-30T09:43:51.051 farmer chia.farmer.farmer         : ERROR    Failed to update farmer information on the pool https://asia1.pool.space
2021-10-30T09:45:13.764 full_node chia.full_node.full_node: ERROR    Error with syncing: <class 'RuntimeError'>Traceback (most recent call last):
  File "chia\full_node\full_node.py", line 718, in _sync
RuntimeError: Weight proof did not arrive in time from peer: 155.137.147.156

2021-10-30T09:45:32.275 farmer chia.farmer.farmer         : ERROR    Failed to update farmer information on the pool https://asia1.pool.space
2021-10-30T09:46:29.460 full_node chia.full_node.full_node: ERROR    Error with syncing: <class 'RuntimeError'>Traceback (most recent call last):
  File "chia\full_node\full_node.py", line 723, in _sync
RuntimeError: Weight proof did not arrive in time from peer: 85.25.198.92

2021-10-30T09:48:39.937 full_node chia.full_node.full_node: ERROR    Error with syncing: <class 'RuntimeError'>Traceback (most recent call last):
  File "chia\full_node\full_node.py", line 723, in _sync
RuntimeError: Weight proof did not arrive in time from peer: 73.223.183.74

**Comment by blackmennewstyle** [comment]
Why upgrading the GUI often ends in this kind of situation when syncing is not possible anymore and as always the only fix is to delete the whole database and start over the blockchain synchronization, it takes days on my Raspberry PI. It's so annoying.

**Comment by Elyasin** [comment]
This not only annoying. It is bad practice and not up to professional standard.

When upgrading at least I would expect in the Release Notes or similar some information about what to expect, compatibility issues, etc. In the last updates I have done (1.2.10 lately) this was never the case. Correct me if I am wrong (with a link or an excerpt).

It is not the biggest challenge to make sure that a database schema fits and I wonder how a database can get corrupted. What does corrupted mean in the first place? If it gets corrupted so often then wouldn't it be right to let the users know? Maybe inform that this is a possibility and what solutions exist? (e.g. how to avoid a corrupted database or a "sorry, but you have to sync for days again.")

Unfortunately there is a lot of room for improvement in many areas in Chia. I am afraid we will have to bear with this; it certainly will take time.

**Comment by paulhainsworth-chia** [comment]
Added it to backlog. https://trello.com/c/i9Cbfopj
