### ISSUE TITLE
[BUG]unable to sync full node after PC crash, permanent error

### ISSUE THREAD

**Issue by electroboyz** [Chia-Network/chia-blockchain#9034]
```
2021-10-30T18:13:41.414 wallet chia.rpc.rpc_server        : WARNING  Error while handling message: Traceback (most recent call last):
  File "chia\rpc\rpc_server.py", line 83, in inner
  File "chia\rpc\wallet_rpc_api.py", line 1127, in get_farmed_amount
  File "chia\wallet\wallet_transaction_store.py", line 298, in get_farming_rewards
  File "aiosqlite\core.py", line 184, in execute
  File "aiosqlite\core.py", line 129, in _execute
  File "aiosqlite\core.py", line 102, in run
sqlite3.ProgrammingError: Cannot operate on a closed database.

```
And this
```
**2021-10-30T19:22:52.393 full_node chia.full_node.full_node: INFO     Collected a total of 8 peaks.
2021-10-30T19:22:52.394 full_node chia.full_node.full_node: INFO     Selected peak 1070494, b1a12a7dde52d25dd7c9dc6f783cc4ec449666f2f445179526c47b88f10f0c73
2021-10-30T19:22:53.588 full_node full_node_server        : INFO     Connected with full_node {'host': '95.17.130.119', 'port': 8444}
2021-10-30T19:22:53.590 full_node full_node_server        : INFO     Connection closed: 95.17.130.119, node id: 2826e633f2c34a6f67419452ca2594d55b9e4b0faf51c0dc489dd5175352756c
2021-10-30T19:22:53.590 full_node chia.full_node.full_node: INFO     peer disconnected {'host': '95.17.130.119', 'port': 8444}
2021-10-30T19:22:55.037 full_node chia.full_node.full_node: INFO     Total of 8 peers with peak 1070494
2021-10-30T19:22:55.039 full_node chia.full_node.full_node: INFO     Requesting weight proof from peer 86.126.10.181 up to height 1070494
2021-10-30T19:23:08.183 harvester chia.harvester.harvester: INFO     refresh_batch: loaded_plots 0, loaded_size 0.00 TiB, removed_plots 0, processed_plots 0, remaining_plots 0, duration: 0.62 seconds
2021-10-30T19:23:08.357 full_node chia.full_node.weight_proof: INFO     validate weight proof peak height 1070494
2021-10-30T19:23:08.408 full_node chia.full_node.weight_proof: INFO     validating 2787 sub epochs
2021-10-30T19:23:20.391 full_node full_node_server        : INFO     Cannot connect to host 176.36.7.43:8444 ssl:<ssl.SSLContext object at 0x00000171E0244540> [The semaphore timeout period has expired]
2021-10-30T19:23:20.392 full_node chia.rpc.rpc_server     : WARNING  Error while handling message: Traceback (most recent call last):
  File "chia\rpc\rpc_server.py", line 83, in inner
  File "chia\rpc\rpc_server.py", line 166, in open_connection
ValueError: Start client failed, or server is not set
2021-10-30T19:23:29.455 full_node full_node_server        : INFO     Cannot connect to host 185.53.229.210:8444 ssl:<ssl.SSLContext object at 0x00000171E0244F40> [The remote computer refused the network connection]
2021-10-30T19:23:29.456 full_node chia.rpc.rpc_server     : WARNING  Error while handling message: Traceback (most recent call last):
  File "chia\rpc\rpc_server.py", line 83, in inner
  File "chia\rpc\rpc_server.py", line 166, in open_connection
ValueError: Start client failed, or server is not set**
```

Windows 10 on VirtualBox, Chia 1.2.9
Tried restart the whole system, uninstall/reinstall Chia. Problem persists

**Comment by emlowe** [comment]
Your DB is corrupted - you need to delete your chia blockchain DB - in C:\users\USERNAME\.chia\mainnet\db. Then you will resync .
