### ISSUE TITLE
[BUG] - Harvester Crashing and Debug.log not helping solve issue

### ISSUE THREAD

**Issue by brianwfreeman** [Chia-Network/chia-blockchain#9046]
**Describe the bug**

Debug.log reads:

```
2021-10-31T07:56:17.297 daemon chia.daemon.server         : INFO     Websocket exception. Closing websocket with chia_harvester code = 1006 (connection closed abnormally [internal]), no reason Traceback (most recent call last):
  File "/home/brian/chia-blockchain/venv/lib/python3.8/site-packages/websockets/protocol.py", line 827, in transfer_data
    message = await self.read_message()
  File "/home/brian/chia-blockchain/venv/lib/python3.8/site-packages/websockets/protocol.py", line 895, in read_message
    frame = await self.read_data_frame(max_size=self.max_size)
  File "/home/brian/chia-blockchain/venv/lib/python3.8/site-packages/websockets/protocol.py", line 971, in read_data_frame
    frame = await self.read_frame(max_size)
  File "/home/brian/chia-blockchain/venv/lib/python3.8/site-packages/websockets/protocol.py", line 1047, in read_frame
    frame = await Frame.read(
  File "/home/brian/chia-blockchain/venv/lib/python3.8/site-packages/websockets/framing.py", line 105, in read
    data = await reader(2)
  File "/usr/lib/python3.8/asyncio/streams.py", line 721, in readexactly
    raise exceptions.IncompleteReadError(incomplete, n)
asyncio.exceptions.IncompleteReadError: 0 bytes read on a total of 2 expected bytes

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/brian/chia-blockchain/chia/daemon/server.py", line 193, in safe_handle
    async for message in websocket:
  File "/home/brian/chia-blockchain/venv/lib/python3.8/site-packages/websockets/protocol.py", line 439, in __aiter__
    yield await self.recv()
  File "/home/brian/chia-blockchain/venv/lib/python3.8/site-packages/websockets/protocol.py", line 509, in recv
    await self.ensure_open()
  File "/home/brian/chia-blockchain/venv/lib/python3.8/site-packages/websockets/protocol.py", line 803, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedError: code = 1006 (connection closed abnormally [internal]), no reason
```

**To Reproduce**

Running harvester with latest version of Chia in Ubuntu Linux.

**Expected behavior**

Should not be crashing

**Comment by loppefaaret** [comment]
you have no entries from the harvester itself ? 
if not, try and see if you can find a potential damaged plot, possibly using `chia plots check`

**Comment by brianwfreeman** [comment]
Ok, I will run "chia plots check" but this will probably take a while on 1.2 PiB of K32s with the default of 30 checks per plot

**Comment by brianwfreeman** [comment]
> you have no entries from the harvester itself ? if not, try and see if you can find a potential damaged plot, possibly using `chia plots check`

This debug.log was from the harvester itself - not the main full node.

**Comment by loppefaaret** [comment]
i meant that this above entry is from the `daemon` service, and not the `harvester` service - i got your full `debug.log` now through keybase, so ill go through it, and see if i can find something...

**Comment by loppefaaret** [comment]
going through the `debug.log` i found these entries from `harvester`:
```
2021-10-30T22:43:33.451 harvester chia.harvester.harvester: ERROR    Error using prover object Src size is incorrect
2021-10-30T22:43:33.452 harvester chia.harvester.harvester: ERROR    File: /modified/path/plot-k32-modified-filename.plot
```
these can potentially be bad plots, a drive that is acting up, a controller overheating... a bad cable ? cleaning around the server knocked something loose ? a bad PSU ? the options are plenty.
atleast try and eleminate these direct issues fro mthe harvester is a first step towards it not crashing.

**Comment by loppefaaret** [comment]
having not heard anything bad since our list interaction, closing issue

**Comment by brianwfreeman** [comment]
Just to come back full circle to close this out -- the bad plots seemed to have been the issue. After deleting the bad plots indicated in the debug.log, the harvester has not crashed.
