### ISSUE TITLE
[BUG]Chia Blockchain 1.2.10 not sync

### ISSUE THREAD

**Issue by 13C0der70** [Chia-Network/chia-blockchain#9099]
Hi

![IMG_20211103_114414_988](https://user-images.githubusercontent.com/65393925/140027511-c8a90529-33d6-41d2-8f5c-71bc9fe1a3e5.png)

**Comment by loppefaaret** [comment]
could you try and locate your `debug.log` file located under your users folder `~\.chia\mainnet\log\debug.log` and attach it here to this issue

**Comment by 13C0der70** [comment]
2021-11-02T09:45:55.874 harvester chia.plotting.util      : WARNING  Directory: I:\pool does not exist.
2021-11-02T09:45:55.874 harvester chia.plotting.util      : WARNING  Directory: H:\pool_ does not exist.
2021-11-02T09:45:55.875 harvester chia.plotting.util      : WARNING  Directory: H:\1 does not exist.
2021-11-02T09:45:55.876 harvester chia.plotting.util      : WARNING  Directory: H:\pool does not exist.
2021-11-02T09:46:56.749 wallet asyncio                    : ERROR    Task exception was never retrieved
future: <Task finished name='Task-7' coro=<DaemonProxy.start.<locals>.listener() done, defined at chia\daemon\client.py:30> exception=ConnectionClosedError('code = 1006 (connection closed abnormally [internal]), no reason')>
Traceback (most recent call last):
  File "asyncio\windows_events.py", line 457, in finish_recv
OSError: [WinError 64] The specified network name is no longer available

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "websockets\protocol.py", line 827, in transfer_data
  File "websockets\protocol.py", line 895, in read_message
  File "websockets\protocol.py", line 971, in read_data_frame
  File "websockets\protocol.py", line 1047, in read_frame
  File "websockets\framing.py", line 105, in read
  File "asyncio\streams.py", line 723, in readexactly
  File "asyncio\streams.py", line 517, in _wait_for_data
  File "asyncio\proactor_events.py", line 280, in _loop_reading
  File "asyncio\windows_events.py", line 812, in _poll
  File "asyncio\windows_events.py", line 461, in finish_recv
ConnectionResetError: [WinError 64] The specified network name is no longer available

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "chia\daemon\client.py", line 33, in listener
  File "websockets\protocol.py", line 509, in recv
  File "websockets\protocol.py", line 803, in ensure_open
websockets.exceptions.ConnectionClosedError: code = 1006 (connection closed abnormally [internal]), no reason
2021-11-02T09:46:56.749 farmer asyncio                    : ERROR    Task exception was never retrieved
future: <Task finished name='Task-7' coro=<DaemonProxy.start.<locals>.listener() done, defined at chia\daemon\client.py:30> exception=ConnectionClosedError('code = 1006 (connection closed abnormally [internal]), no reason')>
Traceback (most recent call last):
  File "asyncio\windows_events.py", line 457, in finish_recv
OSError: [WinError 64] The specified network name is no longer available

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "websockets\protocol.py", line 827, in transfer_data
  File "websockets\protocol.py", line 895, in read_message
  File "websockets\protocol.py", line 971, in read_data_frame
  File "websockets\protocol.py", line 1047, in read_frame
  File "websockets\framing.py", line 105, in read
  File "asyncio\streams.py", line 723, in readexactly
  File "asyncio\streams.py", line 517, in _wait_for_data
  File "asyncio\proactor_events.py", line 280, in _loop_reading
  File "asyncio\windows_events.py", line 812, in _poll
  File "asyncio\windows_events.py", line 461, in finish_recv
ConnectionResetError: [WinError 64] The specified network name is no longer available

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "chia\daemon\client.py", line 33, in listener
  File "websockets\protocol.py", line 509, in recv
  File "websockets\protocol.py", line 803, in ensure_open
websockets.exceptions.ConnectionClosedError: code = 1006 (connection closed abnormally [internal]), no reason
2021-11-02T09:47:14.894 full_node full_node               : ERROR    full_node: already running
2021-11-02T09:47:16.486 harvester chia.plotting.util      : WARNING  Directory: G:\pool-G does not exist.

**Comment by loppefaaret** [comment]
all i can get from the above copy paste, is that something _has_ happened... all i can say to this is, close down Chia, reboot the machine, and start up Chia again...

**Comment by 13C0der70** [comment]
I did this 100 times but not worked....

i changed to old version not worked


> all i can get from the above copy paste, is that something _has_ happened... all i can say to this is, close down Chia, reboot the machine, and start up Chia again...

**Comment by loppefaaret** [comment]
are you overclocking any of your hardware in your BIOS ? perhaps try just a simple turn off XMP / DOCP memory overclocking, and see if that changes the situation

**Comment by 13C0der70** [comment]
> are you overclocking any of your hardware in your BIOS ? perhaps try just a simple turn off XMP / DOCP memory overclocking, and see if that changes the situation

no no 
just update to new version :|

**Comment by loppefaaret** [comment]
> > are you overclocking any of your hardware in your BIOS ? perhaps try just a simple turn off XMP / DOCP memory overclocking, and see if that changes the situation
> 
> no no just update to new version :|

does that mean you can confirm that you are not running XMP / DOCP profiles on your memory, and are running them at SPD standards ? 

it would be perhaps be a bit easier for me to help you, if you are able to navigate to `C:\Users\<USERNAME>\.chia\mainnet \log` and drag'n'drop the `debug.log` into the chat box here on github, so that you upload your log file, and i can see what is being logged

**Comment by IT2core** [comment]
Same issue here from 24/10/2021 - chia 1.2.9 and now on 1.2.10 still same
![image](https://user-images.githubusercontent.com/6873720/140415168-681fa71a-30d4-467a-a372-065de142ade9.png)

Device info
![image](https://user-images.githubusercontent.com/6873720/140415123-ff9b2b96-ec7a-44d1-a5d9-fd5ade8ca01f.png)

**Comment by loppefaaret** [comment]
there is a chance you are having a database with corrupted data, but without the actual log it is hard to confirm.
you can try this below, and see if this helps you out:
WINDOWS BLOCKCHAIN DATABASE RESET

Close down the Chia app, and open up a PowerShell window, and execute the below command:
```
mv ~\.chia\mainnet\db\block* ~\Desktop\
```
Then try opening up the Chia app again
If it worked, you can remove the files we put on the Desktop!

**Comment by 13C0der70** [comment]
I deleted the db folder....The application was activated.
But it is syncing again

**Comment by IT2core** [comment]
yeh looks that was problem with this. now back in sync mode and looks better
@loppefaaret thx for your help
