### ISSUE TITLE
[BUG]Timelord will not install on Centos8

### ISSUE THREAD

**Issue by smurfjack** [Chia-Network/chia-blockchain#9114]
**Describe the bug**

while running  sh install-timelord.sh the error occured at the step of
Building wheel for chiavdf (pyproject.toml) ... -

 
**To Reproduce**

1. RUN sh install-timelord.sh
2. See error
venv/bin/python -m pip install --force --no-binary chiavdf chiavdf==1.0.3
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Collecting chiavdf==1.0.3
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/74/ff/b10796699c1ef13a25bfaf0511fed40f8ab101120dc8b34e5a1af57c541f/chiavdf-1.0.3.tar.gz (635 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Building wheels for collected packages: chiavdf
  Building wheel for chiavdf (pyproject.toml) ... error
  ERROR: Command errored out with exit status 1:
   command: /home/jack/chia-blockchain/venv/bin/python /home/jack/chia-blockchain/venv/lib/python3.7/site-packages/pip/_vendor/pep517/in_process/_in_process.py build_wheel /tmp/tmpkn1ehkgm
       cwd: /tmp/pip-install-ic5j63e0/chiavdf_6f35149752ec4d37b781e2c3512640f9
  Complete output (83 lines):
  running bdist_wheel
  running build
  running build_ext
  -- The C compiler identification is GNU 8.4.1
  -- The CXX compiler identification is GNU 8.4.1
  -- Detecting C compiler ABI info
  -- Detecting C compiler ABI info - done
  -- Check for working C compiler: /usr/bin/cc - skipped
  -- Detecting C compile features
  -- Detecting C compile features - done
  -- Detecting CXX compiler ABI info
  -- Detecting CXX compiler ABI info - done
  -- Check for working CXX compiler: /usr/bin/c++ - skipped
  -- Detecting CXX compile features
  -- Detecting CXX compile features - done
  GMP_INCLUDES=/usr/include
  -- Found GMP: /usr/include (Required is at least version "5.1.0")
  GMP_INCLUDES=/usr/include
  -- Found GMPXX: /usr/lib64/libgmpxx.so
  -- pybind11 v2.6.2
  -- Found PythonInterp: /home/jack/chia-blockchain/venv/bin/python (found version "3.7.7")
  -- Found PythonLibs: /usr/local/lib/libpython3.7m.a
  -- Performing Test HAS_FLTO
  -- Performing Test HAS_FLTO - Success
  -- Configuring done
  -- Generating done
  -- Build files have been written to: /tmp/pip-install-ic5j63e0/chiavdf_6f35149752ec4d37b781e2c3512640f9
  Scanning dependencies of target verifier_test
  [ 33%] Building C object CMakeFiles/verifier_test.dir/refcode/lzcnt.c.o
  [ 33%] Building CXX object CMakeFiles/verifier_test.dir/verifier_test.cpp.o
  Scanning dependencies of target chiavdf
  [ 66%] Building C object CMakeFiles/chiavdf.dir/refcode/lzcnt.c.o
  [ 66%] Building CXX object CMakeFiles/chiavdf.dir/python_bindings/fastvdf.cpp.o
  [ 83%] Linking CXX executable verifier_test
  [ 83%] Built target verifier_test
  [100%] Linking CXX shared module build/lib.linux-x86_64-3.7/chiavdf.cpython-37m-x86_64-linux-gnu.so
  [100%] Built target chiavdf
  running build_hook
  make: *** [Makefile.vdf-client:44: asm_compiled.s] segment error (core dumped)
  Traceback (most recent call last):
    File "/home/jack/chia-blockchain/venv/lib/python3.7/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 363, in <module>
      main()
    File "/home/jack/chia-blockchain/venv/lib/python3.7/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 345, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/home/jack/chia-blockchain/venv/lib/python3.7/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 262, in build_wheel
      metadata_directory)
    File "/tmp/pip-build-env-ug0_dd2f/overlay/lib/python3.7/site-packages/setuptools/build_meta.py", line 231, in build_wheel
      wheel_directory, config_settings)
    File "/tmp/pip-build-env-ug0_dd2f/overlay/lib/python3.7/site-packages/setuptools/build_meta.py", line 215, in _build_with_temp_dir
      self.run_setup()
    File "/tmp/pip-build-env-ug0_dd2f/overlay/lib/python3.7/site-packages/setuptools/build_meta.py", line 158, in run_setup
      exec(compile(code, __file__, 'exec'), locals())
    File "setup.py", line 283, in <module>
      use_scm_version={"fallback_version": "unknown-no-.git-directory"},
    File "/tmp/pip-build-env-ug0_dd2f/overlay/lib/python3.7/site-packages/setuptools/__init__.py", line 159, in setup
      return distutils.core.setup(**attrs)
    File "/usr/local/lib/python3.7/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/usr/local/lib/python3.7/distutils/dist.py", line 966, in run_commands
      self.run_command(cmd)
    File "/usr/local/lib/python3.7/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/tmp/pip-build-env-ug0_dd2f/overlay/lib/python3.7/site-packages/wheel/bdist_wheel.py", line 299, in run
      self.run_command('build')
    File "/usr/local/lib/python3.7/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/local/lib/python3.7/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/usr/local/lib/python3.7/distutils/command/build.py", line 135, in run
      self.run_command(cmd_name)
    File "/usr/local/lib/python3.7/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/local/lib/python3.7/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "setup.py", line 44, in run
      _(install_dir=self.install_dir, build_dir=self.build_dir)
    File "setup.py", line 76, in invoke_make
      subprocess.check_output("make -C src -f Makefile.vdf-client", shell=True)
    File "/usr/local/lib/python3.7/subprocess.py", line 411, in check_output
      **kwargs).stdout
    File "/usr/local/lib/python3.7/subprocess.py", line 512, in run
      output=stdout, stderr=stderr)
  subprocess.CalledProcessError: Command 'make -C src -f Makefile.vdf-client' returned non-zero exit status 2.
  ----------------------------------------
  ERROR: Failed building wheel for chiavdf
Failed to build chiavdf
ERROR: Could not build wheels for chiavdf, which is required to install pyproject.toml-based projects
ERROR: Could not find venv/lib/python3.7/site-packages/vdf_bench
To estimate a timelord on this CPU try './vdf_bench square_asm 400000' for an ips estimate.
**Expected behavior**

**Screenshots**

**Desktop**

- OS: 
Linux
- OS Version/Flavor: 
Centos8.4
- CPU: 
Intel i9 10900K
**Additional context**

**Comment by emlowe** [comment]
This works fine for me on Rocky 8.5 and gcc 8.5.0

I'm going to assume this bug refers to Centos Linux 8 and not Centos Stream. And seeing the Centos 8 is being EOL'd at the end of this year (as Centos moves to Centos Stream) - I'm going to close this issue. Note I did not test Centos Stream 8.
