### ISSUE TITLE
Chia Wallet Does Not Start - Error None failed with error: unknown_command get_key_for_fingerprint [BUG]

### ISSUE THREAD

**Issue by whitetechnologies** [Chia-Network/chia-blockchain#9135]
**Describe the bug**

Updated to 1.2.10, previously everything was working fine
Chia Start Wallet will start node, but wallet throws error: 

2021-11-04T19:37:18.293 daemon chia.daemon.server         : ERROR    UK>> {'ack': False, 'command': 'get_key_for_fingerprint', 'data': {'fingerprint': None}, 'destination': 'daemon', 'origin': 'client', 'request_id': '062f4a76fcf1bd5576b9ad38a7f43974ee84bb63fc126153064e4e047263270c'}
2021-11-04T19:37:18.293 wallet chia.wallet.wallet_node    : ERROR    None failed with error: unknown_command get_key_for_fingerprint

**To Reproduce**

1. Upgrade to 1.2.10
2. CLI command: chia start wallet

**
- OS: Ubunto 20.04 LTS

**Additional context**

Deleting entire chia-blockchain directory and re-install from scratch results in same issue. 

I have not tried deleting .chia directory but don't want to do that yet due to having to re-sync a 26GB database unles that is confirmed to fix the issue

**Comment by whitetechnologies** [comment]
This is a confirmed issue in branch: latest

Repeating this process (delete chia-blockchain and reinstall) using branch: main   results in wallet starting properly without any issues

A dev should verify PR difference btw latest and main and see what is causing this to include fix in 1.2.11 as soon as possible since this is a breaking change for users upgrading to 1.2.10 (at least in my upgrade path)

**Comment by gryan315** [comment]
I'm experiencing a possibly related wallet issue on the latest linux build (1.2.11) in WSL2. When starting wallet-only, the wallet starts and syncs, but `chia wallet show` does not work and results in `Connection error. Check if the wallet is running at 9256. You can run the wallet via:
        chia start wallet`

Here is the entry from the logs when stopping the wallet:
```
2021-11-07T11:40:08.224 daemon chia.daemon.server         : INFO     Websocket exception. Closing websocket with Unknown code = 1006 (connection closed abnormally [internal]), no reason Traceback (most recent call last):
  File "/home/gary/chia-blockchain/venv/lib/python3.9/site-packages/websockets/protocol.py", line 827, in transfer_data
    message = await self.read_message()
  File "/home/gary/chia-blockchain/venv/lib/python3.9/site-packages/websockets/protocol.py", line 895, in read_message
    frame = await self.read_data_frame(max_size=self.max_size)
  File "/home/gary/chia-blockchain/venv/lib/python3.9/site-packages/websockets/protocol.py", line 971, in read_data_frame
    frame = await self.read_frame(max_size)
  File "/home/gary/chia-blockchain/venv/lib/python3.9/site-packages/websockets/protocol.py", line 1047, in read_frame
    frame = await Frame.read(
  File "/home/gary/chia-blockchain/venv/lib/python3.9/site-packages/websockets/framing.py", line 105, in read
    data = await reader(2)
  File "/usr/lib/python3.9/asyncio/streams.py", line 721, in readexactly
    raise exceptions.IncompleteReadError(incomplete, n)
asyncio.exceptions.IncompleteReadError: 0 bytes read on a total of 2 expected bytes

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/gary/chia-blockchain/chia/daemon/server.py", line 195, in safe_handle
    async for message in websocket:
  File "/home/gary/chia-blockchain/venv/lib/python3.9/site-packages/websockets/protocol.py", line 439, in __aiter__
    yield await self.recv()
  File "/home/gary/chia-blockchain/venv/lib/python3.9/site-packages/websockets/protocol.py", line 509, in recv
    await self.ensure_open()
  File "/home/gary/chia-blockchain/venv/lib/python3.9/site-packages/websockets/protocol.py", line 803, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedError: code = 1006 (connection closed abnormally [internal]), no reason
```

**Comment by boqian-nbai** [comment]
Same problem on both 1.2.10 and 1.2.11

```
farmer chia.farmer.farmer         : ERROR    None failed with error: unknown_command get_all_private_keys
```

```
wallet chia.wallet.wallet_node    : ERROR    None failed with error: unknown_command get_key_for_fingerprint

**Comment by whitetechnologies** [comment]
On 1.2.11 I am not getting this error anymore.  Also, branch main is working fine.

> Same problem on both 1.2.10 and 1.2.11
> 
> ```
> farmer chia.farmer.farmer         : ERROR    None failed with error: unknown_command get_all_private_keys
> ```
> 
> ```
> wallet chia.wallet.wallet_node    : ERROR    None failed with error: unknown_command get_key_for_fingerprint
> ```
