### ISSUE TITLE
[BUG] chia b27's clvm_rs failing on CentOS 7.9 - GLIBC_2.18 not found

### ISSUE THREAD

**Issue by af85** [Chia-Network/chia-blockchain#914]
**Describe the bug**
CentOS 7 comes with glibc 2.17, and the latest release of chia seems to be asking for glibc 2.18

**To Reproduce**
Install b27, and chia init
```
$ chia init
Traceback (most recent call last):
  File "/opt/chia/venv/bin/chia", line 33, in <module>
    sys.exit(load_entry_point('chia-blockchain', 'console_scripts', 'chia')())
  File "/opt/chia/src/cmds/chia.py", line 57, in main
    parser = create_parser()
  File "/opt/chia/src/cmds/chia.py", line 45, in create_parser
    mod = importlib.import_module("src.cmds.%s" % subcommand)
  File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/chia/src/cmds/init.py", line 13, in <module>
    from src.consensus.coinbase import create_puzzlehash_for_pk
  File "/opt/chia/src/consensus/coinbase.py", line 5, in <module>
    from src.types.coin import Coin
  File "/opt/chia/src/types/coin.py", line 9, in <module>
    from src.util.streamable import streamable, Streamable
  File "/opt/chia/src/util/streamable.py", line 11, in <module>
    from src.types.program import Program, SerializedProgram
  File "/opt/chia/src/types/program.py", line 15, in <module>
    from clvm_rs import serialize_and_run_program, STRICT_MODE
ImportError: /lib64/libc.so.6: version `GLIBC_2.18' not found (required by /opt/chia/venv/lib/python3.7/site-packages/clvm_rs.cpython-37m-x86_64-linux-gnu.so)
(venv) [arthur@crypto chia]$ cat /etc/redhat-release 
CentOS Linux release 7.9.2009 (Core)
```

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

- OS: Linux
- OS Version/Flavor: CentOS 7.9
- CPU: Intel(R) Xeon(R) CPU E5-2680 v4 @ 2.40GHz

**Additional context**

**Comment by af85** [comment]
This upgrade likely broke CentOS:

> We now use the rust version of clvm, clvm_rs, in preference to validate transactions. We have additionally published binary wheels or clvm_rs for all four platforms and all three supported python versions. The rust version is approximately 50 times faster than the python version used to validate on chain transactions in previous versions.

**Comment by hoffmang9** [comment]
the manylinux2010 docker is supposed to keep this from happening. Will dig into it as you're exactly right that the clvm_rs wheel must have picked up too new a clib...

**Comment by hoffmang9** [comment]
Can you try this and see if it works?
[clvm_rs-0.1.2-cp37-cp37m-manylinux2010_x86_64.whl.zip](https://github.com/Chia-Network/chia-blockchain/files/5976855/clvm_rs-0.1.2-cp37-cp37m-manylinux2010_x86_64.whl.zip)

**Comment by af85** [comment]
To be honest, this is the nail in the coffin for co7 for me, at least for home use. I’m working on sorting my data, and will rebuild with ubu-20.04 tonight. I’ll try this out before the rebuild in case anyone else is watching.

**Comment by dorkmo** [comment]
interesting! "In December 2020, Red Hat terminated CentOS development.[16][17] Red Hat will however continue to support the related rolling-release distro, CentOS Stream.[16][17] As a response, CentOS founder, Gregory Kurtzer, created the Rocky Linux project as a successor to the original mission of CentOS.[18] Similarly, Cloud Linux (makers of CloudLinux OS) announced a new CentOS clone.[19]"

**Comment by hoffmang9** [comment]
@af85 please do see if it works because I want to confirm we fixed it. I'm chuckling because I deleted my rant against RedHat and ancient dev tools 🤣

**Comment by af85** [comment]
@hoffmang9 that seems to work!

```
(venv) [arthur@crypto ~]$ pip install --force-reinstall clvm_rs-0.1.2-cp37-cp37m-manylinux2010_x86_64.whl
Processing ./clvm_rs-0.1.2-cp37-cp37m-manylinux2010_x86_64.whl
Installing collected packages: clvm-rs
  Attempting uninstall: clvm-rs
    Found existing installation: clvm-rs 0.1.2
    Uninstalling clvm-rs-0.1.2:
      Successfully uninstalled clvm-rs-0.1.2
Successfully installed clvm-rs-0.1.2
(venv) [arthur@crypto ~]$ chia init
Chia directory /home/arthur/.chia/beta-1.0b27
Install release number: 27
Checking /home/arthur/.chia/beta-1.0b26

/home/arthur/.chia/beta-1.0b26 found
Copying files from /home/arthur/.chia/beta-1.0b26 to /home/arthur/.chia/beta-1.0b27

/home/arthur/.chia/beta-1.0b27/config/config.yaml
/home/arthur/.chia/beta-1.0b27/config/ssl/ca/chia_ca.crt
/home/arthur/.chia/beta-1.0b27/config/ssl/ca/chia_ca.key
/home/arthur/.chia/beta-1.0b27/config/ssl/ca/private_ca.crt
/home/arthur/.chia/beta-1.0b27/config/ssl/ca/private_ca.key
/home/arthur/.chia/beta-1.0b27/config/ssl/timelord/private_timelord.crt
/home/arthur/.chia/beta-1.0b27/config/ssl/timelord/private_timelord.key
/home/arthur/.chia/beta-1.0b27/config/ssl/timelord/public_timelord.crt
/home/arthur/.chia/beta-1.0b27/config/ssl/timelord/public_timelord.key
/home/arthur/.chia/beta-1.0b27/config/ssl/daemon/private_daemon.crt
/home/arthur/.chia/beta-1.0b27/config/ssl/daemon/private_daemon.key
/home/arthur/.chia/beta-1.0b27/config/ssl/wallet/private_wallet.crt
/home/arthur/.chia/beta-1.0b27/config/ssl/wallet/private_wallet.key
/home/arthur/.chia/beta-1.0b27/config/ssl/wallet/public_wallet.crt
/home/arthur/.chia/beta-1.0b27/config/ssl/wallet/public_wallet.key
/home/arthur/.chia/beta-1.0b27/config/ssl/farmer/private_farmer.crt
/home/arthur/.chia/beta-1.0b27/config/ssl/farmer/private_farmer.key
/home/arthur/.chia/beta-1.0b27/config/ssl/farmer/public_farmer.crt
/home/arthur/.chia/beta-1.0b27/config/ssl/farmer/public_farmer.key
/home/arthur/.chia/beta-1.0b27/config/ssl/harvester/private_harvester.crt
/home/arthur/.chia/beta-1.0b27/config/ssl/harvester/private_harvester.key
/home/arthur/.chia/beta-1.0b27/config/ssl/full_node/private_full_node.crt
/home/arthur/.chia/beta-1.0b27/config/ssl/full_node/private_full_node.key
/home/arthur/.chia/beta-1.0b27/config/ssl/full_node/public_full_node.crt
/home/arthur/.chia/beta-1.0b27/config/ssl/full_node/public_full_node.key
/home/arthur/.chia/beta-1.0b27/config/ssl/introducer/public_introducer.crt
/home/arthur/.chia/beta-1.0b27/config/ssl/introducer/public_introducer.key
Found private CA in /home/arthur/.chia/beta-1.0b27, using it to generate TLS certificates
```

i'm still switching to ubu tho =) We can close this out. I'm satisfied.

**Comment by hoffmang9** [comment]
Great on both!
