### ISSUE TITLE
[Bug] 1.2.11 full_node crashes with BrokenProcessPool on RaspberryPi

### ISSUE THREAD

**Issue by djdookie** [Chia-Network/chia-blockchain#9183]
### What happened?

Got a lot of these messages some minutes ago, full node crashed. Latest version on RPi 4GB Ubuntu 20.04. Ran fine until now since update some days ago.

### Version

1.2.11

### What platform are you using?

Linux

### What ui mode are you using?

CLI

### Relevant log output

```shell
2021-11-08T00:03:28.932 full_node full_node_server        : ERROR    Exception: A child process terminated abruptly, the process pool is not usable anymore, {'host': '109.xxx.xxx.xxx', 'port': 8444}. Traceback (most recent call last):
2021-11-08T00:03:28.933 full_node full_node_server        : ERROR    Exception: A child process terminated abruptly, the process pool is not usable anymore <class 'concurrent.futures.process.BrokenProcessPool'>, closing connection {'host': '109.xxx.xxx.xxx', 'port': 8444}. Traceback (most recent call last):
2021-11-08T00:04:21.028 full_node full_node_server        : ERROR    Exception: A child process terminated abruptly, the process pool is not usable anymore, {'host': '213.xxx.xxx.xxx', 'port': 8444}. Traceback (most recent call last):
2021-11-08T00:04:21.030 full_node full_node_server        : ERROR    Exception: A child process terminated abruptly, the process pool is not usable anymore <class 'concurrent.futures.process.BrokenProcessPool'>, closing connection {'host': '213.xxx.xxx.xxx', 'port': 8444}. Traceback (most recent call last):
2021-11-08T00:05:03.976 full_node full_node_server        : ERROR    Exception: A child process terminated abruptly, the process pool is not usable anymore, {'host': '190.xxx.xxx.xxx', 'port': 8444}. Traceback (most recent call last):
2021-11-08T00:05:03.977 full_node full_node_server        : ERROR    Exception: A child process terminated abruptly, the process pool is not usable anymore <class 'concurrent.futures.process.BrokenProcessPool'>, closing connection {'host': '190.xxx.xxx.xxx', 'port': 8444}. Traceback (most recent call last):
2021-11-08T00:10:52.935 full_node full_node_server        : ERROR    Exception: Error short batch syncing, could not fetch block at height 1109243, {'host': '52.xxx.xxx.xxx', 'port': 8444}. Traceback (most recent call last):
2021-11-08T00:10:52.937 full_node full_node_server        : ERROR    Exception: Error short batch syncing, could not fetch block at height 1109243 <class 'ValueError'>, closing connection {'host': '52.xxx.xxx.xxx', 'port': 8444}. Traceback (most recent call last):
```

**Comment by minguohua** [comment]
me too, star_full_node stop working.

**Comment by djdookie** [comment]
Full node keeps crashed every 2-3 days since updating to v1.2.11. Only manually restarting it helps.

Another logfile extract of the recent crash today:

```
2021-11-19T14:18:38.571 daemon chia.daemon.server         : INFO     Websocket exception. Closing websocket with chia_full_node code = 1006 (connection closed abnormally [internal]), no reason Traceback (most recent call last):
  File "/home/ubuntu/chia-blockchain/venv/lib/python3.8/site-packages/websockets/protocol.py", line 827, in transfer_data
    message = await self.read_message()
  File "/home/ubuntu/chia-blockchain/venv/lib/python3.8/site-packages/websockets/protocol.py", line 895, in read_message
    frame = await self.read_data_frame(max_size=self.max_size)
  File "/home/ubuntu/chia-blockchain/venv/lib/python3.8/site-packages/websockets/protocol.py", line 971, in read_data_frame
    frame = await self.read_frame(max_size)
  File "/home/ubuntu/chia-blockchain/venv/lib/python3.8/site-packages/websockets/protocol.py", line 1047, in read_frame
    frame = await Frame.read(
  File "/home/ubuntu/chia-blockchain/venv/lib/python3.8/site-packages/websockets/framing.py", line 105, in read
    data = await reader(2)
  File "/usr/lib/python3.8/asyncio/streams.py", line 723, in readexactly
    await self._wait_for_data('readexactly')
  File "/usr/lib/python3.8/asyncio/streams.py", line 517, in _wait_for_data
    await self._waiter
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ubuntu/chia-blockchain/chia/daemon/server.py", line 195, in safe_handle
    async for message in websocket:
  File "/home/ubuntu/chia-blockchain/venv/lib/python3.8/site-packages/websockets/protocol.py", line 439, in __aiter__
    yield await self.recv()
  File "/home/ubuntu/chia-blockchain/venv/lib/python3.8/site-packages/websockets/protocol.py", line 509, in recv
    await self.ensure_open()
  File "/home/ubuntu/chia-blockchain/venv/lib/python3.8/site-packages/websockets/protocol.py", line 812, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedError: code = 1006 (connection closed abnormally [internal]), no reason
```

Can you please fix those bugs?

**Comment by djdookie** [comment]
And another crash on the current release version 1.2.11:

```
2021-11-22T22:15:22.224 daemon chia.daemon.server         : INFO     Websocket exception. Closing websocket with chia_full_node code = 1006 (connection closed abnormally [internal]), no reason Traceback (most recent call last):
  File "/home/ubuntu/chia-blockchain/venv/lib/python3.8/site-packages/websockets/protocol.py", line 827, in transfer_data
    message = await self.read_message()
  File "/home/ubuntu/chia-blockchain/venv/lib/python3.8/site-packages/websockets/protocol.py", line 895, in read_message
    frame = await self.read_data_frame(max_size=self.max_size)
  File "/home/ubuntu/chia-blockchain/venv/lib/python3.8/site-packages/websockets/protocol.py", line 971, in read_data_frame
    frame = await self.read_frame(max_size)
  File "/home/ubuntu/chia-blockchain/venv/lib/python3.8/site-packages/websockets/protocol.py", line 1047, in read_frame
    frame = await Frame.read(
  File "/home/ubuntu/chia-blockchain/venv/lib/python3.8/site-packages/websockets/framing.py", line 105, in read
    data = await reader(2)
  File "/usr/lib/python3.8/asyncio/streams.py", line 723, in readexactly
    await self._wait_for_data('readexactly')
  File "/usr/lib/python3.8/asyncio/streams.py", line 517, in _wait_for_data
    await self._waiter
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ubuntu/chia-blockchain/chia/daemon/server.py", line 195, in safe_handle
    async for message in websocket:
  File "/home/ubuntu/chia-blockchain/venv/lib/python3.8/site-packages/websockets/protocol.py", line 439, in __aiter__
    yield await self.recv()
  File "/home/ubuntu/chia-blockchain/venv/lib/python3.8/site-packages/websockets/protocol.py", line 509, in recv
    await self.ensure_open()
  File "/home/ubuntu/chia-blockchain/venv/lib/python3.8/site-packages/websockets/protocol.py", line 812, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedError: code = 1006 (connection closed abnormally [internal]), no reason
```

My chia fullnode never ran that bad on my RPi, even in the storm some weeks ago. And I joined pretty early.
Whatever changed in the core, it seems to be bad/fragile implemented and tested.
I hope some dev will care about those crashes. My hardware didn't change, so I assume it's a pure software problem.

**Comment by lorado** [comment]
I also have similar issue, my full node is running in an Odroid N2+ 4GB, similar to RPi 4. `~/.chia` ist mounted to an SSD.

Before 1.2.11 I had such problem once a month at most. Since 1.2.11 it crashes like once a day =( After crash, full node is not able to peek up the sync again. For me only the complete reboot of Odroid helps, that is why I made a watchdog monitoring the exception in logs, and reboot after that, so I don't have to reboot it manually. It works kinda, but is very annoying. And because of reboot, my farm stays about 5-10 minutes offline... sad.

Here is portion of related log entries:

```
2021-11-21T20:35:30.622 full_node full_node_server        : ERROR    Exception: A child process terminated abruptly, the process pool is not usable anymore, {'host': '194.1.253.15', 'port': 8444}. Traceback (most recent call last):
  File "/root/chia-blockchain/chia/server/server.py", line 566, in wrapped_coroutine
    result = await coroutine
  File "/root/chia-blockchain/chia/full_node/full_node_api.py", line 461, in respond_unfinished_block
    await self.full_node.respond_unfinished_block(
  File "/root/chia-blockchain/chia/full_node/full_node.py", line 1608, in respond_unfinished_block
    npc_result = await self.blockchain.run_generator(block_bytes, block_generator)
  File "/root/chia-blockchain/chia/consensus/blockchain.py", line 648, in run_generator
    task = asyncio.get_running_loop().run_in_executor(
  File "/usr/lib/python3.8/asyncio/base_events.py", line 783, in run_in_executor
    executor.submit(func, *args), loop=self)
  File "/usr/lib/python3.8/concurrent/futures/process.py", line 629, in submit
    raise BrokenProcessPool(self._broken)
concurrent.futures.process.BrokenProcessPool: A child process terminated abruptly, the process pool is not usable anymore

2021-11-21T20:35:30.623 full_node full_node_server        : ERROR    Exception: A child process terminated abruptly, the process pool is not usable anymore <class 'concurrent.futures.process.BrokenProcessPool'>, closing connection {'host': '194.1.253.15', 'port': 8444}. Traceback (most recent call last):
  File "/root/chia-blockchain/chia/server/server.py", line 576, in api_call
    response: Optional[Message] = await asyncio.wait_for(wrapped_coroutine(), timeout=timeout)
  File "/usr/lib/python3.8/asyncio/tasks.py", line 494, in wait_for
    return fut.result()
  File "/root/chia-blockchain/chia/server/server.py", line 573, in wrapped_coroutine
    raise e
  File "/root/chia-blockchain/chia/server/server.py", line 566, in wrapped_coroutine
    result = await coroutine
  File "/root/chia-blockchain/chia/full_node/full_node_api.py", line 461, in respond_unfinished_block
    await self.full_node.respond_unfinished_block(
  File "/root/chia-blockchain/chia/full_node/full_node.py", line 1608, in respond_unfinished_block
    npc_result = await self.blockchain.run_generator(block_bytes, block_generator)
  File "/root/chia-blockchain/chia/consensus/blockchain.py", line 648, in run_generator
    task = asyncio.get_running_loop().run_in_executor(
  File "/usr/lib/python3.8/asyncio/base_events.py", line 783, in run_in_executor
    executor.submit(func, *args), loop=self)
  File "/usr/lib/python3.8/concurrent/futures/process.py", line 629, in submit
    raise BrokenProcessPool(self._broken)
concurrent.futures.process.BrokenProcessPool: A child process terminated abruptly, the process pool is not usable anymore

2021-11-21T20:35:30.677 full_node full_node_server        : INFO     Connection closed: 194.1.253.15, node id: c9bb16ae57ad2f0e091718e570a626d78f6b49b3d8a0d6447e9cf706994e760f
2021-11-21T20:35:30.678 full_node full_node_server        : WARNING  Banning 194.1.253.15 for 10 seconds
```

**Comment by aaronscott072** [comment]
I am also experiencing this issue, RPi4 requires a restart every 1-2 days. This has only been occurring in the last month or so.

**Comment by djdookie** [comment]
And it keeps crashing:

```
2021-11-28T13:06:19.254 daemon chia.daemon.server         : INFO     Websocket exception. Closing websocket with chia_full_node code = 1006 (connection closed abnormally [internal]), no reason Traceback (most recent call last):
  File "/home/ubuntu/chia-blockchain/venv/lib/python3.8/site-packages/websockets/protocol.py", line 827, in transfer_data
    message = await self.read_message()
  File "/home/ubuntu/chia-blockchain/venv/lib/python3.8/site-packages/websockets/protocol.py", line 895, in read_message
    frame = await self.read_data_frame(max_size=self.max_size)
  File "/home/ubuntu/chia-blockchain/venv/lib/python3.8/site-packages/websockets/protocol.py", line 971, in read_data_frame
    frame = await self.read_frame(max_size)
  File "/home/ubuntu/chia-blockchain/venv/lib/python3.8/site-packages/websockets/protocol.py", line 1047, in read_frame
    frame = await Frame.read(
  File "/home/ubuntu/chia-blockchain/venv/lib/python3.8/site-packages/websockets/framing.py", line 105, in read
    data = await reader(2)
  File "/usr/lib/python3.8/asyncio/streams.py", line 723, in readexactly
    await self._wait_for_data('readexactly')
  File "/usr/lib/python3.8/asyncio/streams.py", line 517, in _wait_for_data
    await self._waiter
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ubuntu/chia-blockchain/chia/daemon/server.py", line 195, in safe_handle
    async for message in websocket:
  File "/home/ubuntu/chia-blockchain/venv/lib/python3.8/site-packages/websockets/protocol.py", line 439, in __aiter__
    yield await self.recv()
  File "/home/ubuntu/chia-blockchain/venv/lib/python3.8/site-packages/websockets/protocol.py", line 509, in recv
    await self.ensure_open()
  File "/home/ubuntu/chia-blockchain/venv/lib/python3.8/site-packages/websockets/protocol.py", line 812, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedError: code = 1006 (connection closed abnormally [internal]), no reason
```

**Comment by emlowe** [comment]
Please check to see if your node crashes are due to the linux OOM (out of memory) killer doing its thing.

`journalctl | grep -i oom` or `dmesg | grep -i oom`

**Comment by lorado** [comment]
Indeed, some of crashes were caused by OOM killer. Here is what I get from `journalctl | grep -i oom`

```
Nov 15 14:13:19 odroid kernel: python3 invoked oom-killer: gfp_mask=0x2400840(GFP_NOFS|__GFP_NOFAIL), nodemask=0, order=0, oom_score_adj=0
Nov 15 14:13:19 odroid kernel: [<ffffff80091c4514>] oom_kill_process+0x2dc/0x530
Nov 15 14:13:19 odroid kernel: [ pid ]   uid  tgid total_vm      rss nr_ptes nr_pmds swapents oom_score_adj name
Nov 23 09:55:58 odroid kernel: systemd-network invoked oom-killer: gfp_mask=0x24201ca(GFP_HIGHUSER_MOVABLE|__GFP_COLD), nodemask=0, order=0, oom_score_adj=0
Nov 23 09:55:59 odroid kernel: [<ffffff80091c4514>] oom_kill_process+0x2dc/0x530
Nov 23 09:55:59 odroid kernel: [ pid ]   uid  tgid total_vm      rss nr_ptes nr_pmds swapents oom_score_adj name
Nov 23 09:55:59 odroid kernel: oom_reaper: reaped process 2780 (chia_full_node), now anon-rss:0kB, file-rss:0kB, shmem-rss:12kB
``` 

BUT - there are much more crashes in between, which are not caused by OOM killer =(

**Comment by djdookie** [comment]
This could indeed be the cause for the crashes. I have a lot of these entries:

```
Nov 22 22:04:08 ubuntu kernel: chia_full_node invoked oom-killer: gfp_mask=0x100cca(GFP_HIGHUSER_MOVABLE), order=0, oom_score_adj=0
Nov 22 22:04:09 ubuntu kernel:  oom_kill_process+0x1d0/0x1d8
Nov 22 22:04:09 ubuntu kernel: [  pid  ]   uid  tgid total_vm      rss pgtables_bytes swapents oom_score_adj name
Nov 22 22:04:09 ubuntu kernel: oom-kill:constraint=CONSTRAINT_NONE,nodemask=(null),cpuset=/,mems_allowed=0,global_oom,task_memcg=/,task=chia_full_node,pid=2861,uid=1000
Nov 22 22:04:09 ubuntu kernel: Out of memory: Killed process 2861 (chia_full_node) total-vm:1642188kB, anon-rss:1043388kB, file-rss:600kB, shmem-rss:16kB, UID:1000 pgtables:2196kB oom_score_adj:0
Nov 22 22:04:09 ubuntu kernel: oom_reaper: reaped process 2861 (chia_full_node), now anon-rss:0kB, file-rss:0kB, shmem-rss:16kB
Nov 28 13:00:02 ubuntu kernel: systemd-journal invoked oom-killer: gfp_mask=0x100cca(GFP_HIGHUSER_MOVABLE), order=0, oom_score_adj=-250
Nov 28 13:00:02 ubuntu kernel:  oom_kill_process+0x1d0/0x1d8
Nov 28 13:00:02 ubuntu kernel: [  pid  ]   uid  tgid total_vm      rss pgtables_bytes swapents oom_score_adj name
Nov 28 13:00:02 ubuntu kernel: oom-kill:constraint=CONSTRAINT_NONE,nodemask=(null),cpuset=/,mems_allowed=0,global_oom,task_memcg=/,task=chia_full_node,pid=128330,uid=1000
Nov 28 13:00:02 ubuntu kernel: Out of memory: Killed process 128330 (chia_full_node) total-vm:1746000kB, anon-rss:1145620kB, file-rss:1064kB, shmem-rss:16kB, UID:1000 pgtables:2404kB oom_score_adj:0
Nov 28 13:00:02 ubuntu kernel: oom_reaper: reaped process 128330 (chia_full_node), now anon-rss:0kB, file-rss:0kB, shmem-rss:16kB
Nov 30 05:38:05 ubuntu kernel: chia_full_node invoked oom-killer: gfp_mask=0x100cca(GFP_HIGHUSER_MOVABLE), order=0, oom_score_adj=0
Nov 30 05:38:06 ubuntu kernel:  oom_kill_process+0x1d0/0x1d8
Nov 30 05:38:06 ubuntu kernel: [  pid  ]   uid  tgid total_vm      rss pgtables_bytes swapents oom_score_adj name
Nov 30 05:38:06 ubuntu kernel: oom-kill:constraint=CONSTRAINT_NONE,nodemask=(null),cpuset=/,mems_allowed=0,global_oom,task_memcg=/,task=chia_full_node,pid=336370,uid=1000
Nov 30 05:38:06 ubuntu kernel: Out of memory: Killed process 336370 (chia_full_node) total-vm:1596912kB, anon-rss:1025700kB, file-rss:1540kB, shmem-rss:16kB, UID:1000 pgtables:2172kB oom_score_adj:0
Nov 30 05:38:06 ubuntu kernel: oom_reaper: reaped process 336370 (chia_full_node), now anon-rss:0kB, file-rss:0kB, shmem-rss:16kB
```

**Comment by djdookie** [comment]
Since "swapon -s" doesn't give me any swapfile, I think I can workaround this problem with creating a swap.
Don't know why Ubuntu didn't create a swapfile with the installation on my RPi.

**Comment by emlowe** [comment]
closing issue - we have moved to using threads from process pools
