### ISSUE TITLE
[Bug] connection lost

### ISSUE THREAD

**Issue by vicentemangas** [Chia-Network/chia-blockchain#9201]
### What happened?

After update to the 1.2.11 the pool that I'm added to cannot see any of my plots.

So I'm loosing all the track there and all the benefits.

### Version

1.2.11

### What platform are you using?

Windows

### What ui mode are you using?

GUI

### Relevant log output

```shell
2021-11-09T13:12:32.608 farmer farmer_server              : ERROR    Exception:  <class 'AssertionError'>, closing connection {'host': '127.0.0.1', 'port': 8448}. Traceback (most recent call last):
  File "chia\server\server.py", line 576, in api_call
  File "asyncio\tasks.py", line 481, in wait_for
  File "chia\server\server.py", line 573, in wrapped_coroutine
  File "chia\server\server.py", line 566, in wrapped_coroutine
  File "chia\farmer\farmer_api.py", line 219, in new_proof_of_space
AssertionError

2021-11-09T13:12:32.609 farmer farmer_server              : WARNING  Trying to ban localhost for 10, but will not ban
2021-11-09T13:12:59.800 farmer farmer_server              : ERROR    Exception: , {'host': '127.0.0.1', 'port': 8448}. Traceback (most recent call last):
  File "chia\server\server.py", line 566, in wrapped_coroutine
  File "chia\farmer\farmer_api.py", line 219, in new_proof_of_space
AssertionError

2021-11-09T13:12:59.801 farmer farmer_server              : ERROR    Exception:  <class 'AssertionError'>, closing connection {'host': '127.0.0.1', 'port': 8448}. Traceback (most recent call last):
  File "chia\server\server.py", line 576, in api_call
  File "asyncio\tasks.py", line 481, in wait_for
  File "chia\server\server.py", line 573, in wrapped_coroutine
  File "chia\server\server.py", line 566, in wrapped_coroutine
  File "chia\farmer\farmer_api.py", line 219, in new_proof_of_space
AssertionError

2021-11-09T13:12:59.802 farmer farmer_server              : WARNING  Trying to ban localhost for 10, but will not ban
2021-11-09T13:19:58.412 farmer farmer_server              : ERROR    Exception: , {'host': '127.0.0.1', 'port': 8448}. Traceback (most recent call last):
  File "chia\server\server.py", line 566, in wrapped_coroutine
  File "chia\farmer\farmer_api.py", line 219, in new_proof_of_space
AssertionError

2021-11-09T13:19:58.413 farmer farmer_server              : ERROR    Exception:  <class 'AssertionError'>, closing connection {'host': '127.0.0.1', 'port': 8448}. Traceback (most recent call last):
  File "chia\server\server.py", line 576, in api_call
  File "asyncio\tasks.py", line 481, in wait_for
  File "chia\server\server.py", line 573, in wrapped_coroutine
  File "chia\server\server.py", line 566, in wrapped_coroutine
  File "chia\farmer\farmer_api.py", line 219, in new_proof_of_space
AssertionError

2021-11-09T13:19:58.414 farmer farmer_server              : WARNING  Trying to ban localhost for 10, but will not ban
2021-11-09T13:20:24.270 farmer farmer_server              : ERROR    Exception: , {'host': '127.0.0.1', 'port': 8448}. Traceback (most recent call last):
  File "chia\server\server.py", line 566, in wrapped_coroutine
  File "chia\farmer\farmer_api.py", line 219, in new_proof_of_space
AssertionError

2021-11-09T13:20:24.271 farmer farmer_server              : ERROR    Exception:  <class 'AssertionError'>, closing connection {'host': '127.0.0.1', 'port': 8448}. Traceback (most recent call last):
  File "chia\server\server.py", line 576, in api_call
  File "asyncio\tasks.py", line 481, in wait_for
  File "chia\server\server.py", line 573, in wrapped_coroutine
  File "chia\server\server.py", line 566, in wrapped_coroutine
  File "chia\farmer\farmer_api.py", line 219, in new_proof_of_space
AssertionError

2021-11-09T13:20:24.272 farmer farmer_server              : WARNING  Trying to ban localhost for 10, but will not ban
2021-11-09T13:22:08.572 farmer farmer_server              : ERROR    Exception: , {'host': '127.0.0.1', 'port': 8448}. Traceback (most recent call last):
  File "chia\server\server.py", line 566, in wrapped_coroutine
  File "chia\farmer\farmer_api.py", line 219, in new_proof_of_space
AssertionError

2021-11-09T13:22:08.573 farmer farmer_server              : ERROR    Exception:  <class 'AssertionError'>, closing connection {'host': '127.0.0.1', 'port': 8448}. Traceback (most recent call last):
  File "chia\server\server.py", line 576, in api_call
  File "asyncio\tasks.py", line 481, in wait_for
  File "chia\server\server.py", line 573, in wrapped_coroutine
  File "chia\server\server.py", line 566, in wrapped_coroutine
  File "chia\farmer\farmer_api.py", line 219, in new_proof_of_space
AssertionError

2021-11-09T13:22:08.574 farmer farmer_server              : WARNING  Trying to ban localhost for 10, but will not ban
```

**Comment by vicentemangas** [comment]
With the latest beta I still have the issue, can you guys prioritize that as I cannot connect with the pool at all so I'm going to disconnect from the net.

2021-12-01T16:36:12.916 farmer farmer_server              : ERROR    Exception: , {'host': '127.0.0.1', 'port': 8448}. Traceback (most recent call last):
  File "chia\server\server.py", line 574, in wrapped_coroutine
  File "chia\farmer\farmer_api.py", line 220, in new_proof_of_space
AssertionError

2021-12-01T16:36:12.917 farmer farmer_server              : ERROR    Exception:  <class 'AssertionError'>, closing connection {'host': '127.0.0.1', 'port': 8448}. Traceback (most recent call last):
  File "chia\server\server.py", line 584, in api_call
  File "asyncio\tasks.py", line 481, in wait_for
  File "chia\server\server.py", line 581, in wrapped_coroutine
  File "chia\server\server.py", line 574, in wrapped_coroutine
  File "chia\farmer\farmer_api.py", line 220, in new_proof_of_space
AssertionError

2021-12-01T16:36:12.918 farmer farmer_server              : WARNING  Trying to ban localhost for 10, but will not ban

**Comment by tim-brand** [comment]
I'm getting this same error. Started farming from my ubuntu server using `chia start farmer`. After the moment a proof is found, this error occurs:
```
2022-04-27T19:53:55.858 harvester chia.harvester.harvester: INFO     3 plots were eligible for farming 3ab2897478... Found 1 proofs. Time: 0.83309 s. Total 2067 plots
2022-04-27T19:53:55.889 farmer farmer_server              : ERROR    Exception: , {'host': '127.0.0.1', 'port': 8448}. Traceback (most recent call last):
  File "/home/tim/chia-blockchain/chia/server/server.py", line 595, in wrapped_coroutine
    result = await coroutine
  File "/home/tim/chia-blockchain/chia/farmer/farmer_api.py", line 223, in new_proof_of_space
    assert plot_signature is not None
AssertionError

2022-04-27T19:53:55.890 farmer farmer_server              : ERROR    Exception:  <class 'AssertionError'>, closing connection {'host': '127.0.0.1', 'port': 8448}. Traceback (most recent call last):
  File "/home/tim/chia-blockchain/chia/server/server.py", line 605, in api_call
    response: Optional[Message] = await asyncio.wait_for(wrapped_coroutine(), timeout=timeout)
  File "/usr/lib/python3.8/asyncio/tasks.py", line 494, in wait_for
    return fut.result()
  File "/home/tim/chia-blockchain/chia/server/server.py", line 602, in wrapped_coroutine
    raise e
  File "/home/tim/chia-blockchain/chia/server/server.py", line 595, in wrapped_coroutine
    result = await coroutine
  File "/home/tim/chia-blockchain/chia/farmer/farmer_api.py", line 223, in new_proof_of_space
    assert plot_signature is not None
AssertionError

2022-04-27T19:53:55.891 farmer farmer_server              : WARNING  Trying to ban localhost for 10, but will not ban
2022-04-27T19:53:55.891 farmer farmer_server              : INFO     Connection closed: 127.0.0.1, node id: 4129ad79cbc10b3da642bacb804e6638fc89419d86c948a9ed34a971ec28a14f
2022-04-27T19:53:55.892 harvester harvester_server        : INFO     Connection closed: 127.0.0.1, node id: f90df97860288e52ea2279288a84ca7dedf2d0151dbeed15741a474c3462e507
2022-04-27T19:53:55.892 farmer chia.farmer.farmer         : INFO     peer disconnected {'host': '127.0.0.1', 'port': 8448}
2022-04-27T19:53:55.893 harvester chia.harvester.harvester: INFO     peer disconnected {'host': '127.0.0.1', 'port': 8447}
2022-04-27T19:53:56.281 harvester harvester               : INFO     Reconnecting to peer {'host': '127.0.0.1', 'port': 8447}
2022-04-27T19:53:56.294 harvester harvester_server        : INFO     Connected with farmer {'host': '127.0.0.1', 'port': 8447}
```

It seems that somethong goes wrong when reporting a found proof, as the pool I'm using doesn't see my work anymore.
(Before I was farming on my Mac system)

**Comment by emlowe** [comment]
Original problems with pool connectivity seem largely solved with later releases.
The most revent comment here is unrelated to this. Closing issue
