### ISSUE TITLE
[BUG] Remote Harvester daemon server segfault: Websocket exception

### ISSUE THREAD

**Issue by eFishCent** [Chia-Network/chia-blockchain#921]
**Describe the bug**
Remote harvester daemon server segfault with a Websocket exception.

**Log**
```
10:19:52.926 daemon src.daemon.server          : INFO     Websocket exception. Closing websocket with chia_harvester code = 1006 (connection closed abnormally [internal]), no reason Traceback (most recent call last):
  File "/home/chia/Projects/chia-blockchain/venv/lib/python3.8/site-packages/websockets/protocol.py", line 827, in transfer_data
    message = await self.read_message()
  File "/home/chia/Projects/chia-blockchain/venv/lib/python3.8/site-packages/websockets/protocol.py", line 895, in read_message
    frame = await self.read_data_frame(max_size=self.max_size)
  File "/home/chia/Projects/chia-blockchain/venv/lib/python3.8/site-packages/websockets/protocol.py", line 971, in read_data_frame
    frame = await self.read_frame(max_size)
  File "/home/chia/Projects/chia-blockchain/venv/lib/python3.8/site-packages/websockets/protocol.py", line 1047, in read_frame
    frame = await Frame.read(
  File "/home/chia/Projects/chia-blockchain/venv/lib/python3.8/site-packages/websockets/framing.py", line 105, in read
    data = await reader(2)
  File "/usr/lib/python3.8/asyncio/streams.py", line 723, in readexactly
    await self._wait_for_data('readexactly')
  File "/usr/lib/python3.8/asyncio/streams.py", line 517, in _wait_for_data
    await self._waiter
  File "/usr/lib/python3.8/asyncio/selector_events.py", line 846, in _read_ready__data_received
    data = self._sock.recv(self.max_size)
ConnectionResetError: [Errno 104] Connection reset by peer

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/chia/Projects/chia-blockchain/src/daemon/server.py", line 149, in safe_handle
    async for message in websocket:
  File "/home/chia/Projects/chia-blockchain/venv/lib/python3.8/site-packages/websockets/protocol.py", line 439, in __aiter__
    yield await self.recv()
  File "/home/chia/Projects/chia-blockchain/venv/lib/python3.8/site-packages/websockets/protocol.py", line 509, in recv
    await self.ensure_open()
  File "/home/chia/Projects/chia-blockchain/venv/lib/python3.8/site-packages/websockets/protocol.py", line 803, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedError: code = 1006 (connection closed abnormally [internal]), no reason
```

**dmesg**
[388966.187137] chia_harvester[39153]: segfault at 2 ip 00007f225b187d01 sp 00007f221effb988 error 4 in chiapos.cpython-38-x86_64-linux-gnu.so[7f225b11b000+b8000]
[388966.187156] Code: 39 c6 75 e5 31 c0 c3 66 90 c3 0f 1f 44 00 00 66 2e 0f 1f 84 00 00 00 00 00 41 57 48 01 fe 41 56 48 8d 46 fd 41 55 41 54 55 53 <66> 41 83 78 02 00 48 89 44 24 b8 48 c7 c0 fd ff ff ff 48 89 7c 24

**Expected behavior**
Remote harvester continues running.

**Server**

- OS: Linux
- OS Version/Flavor: Ubuntu 20.04.2 LTS
- CPU: Intel 8Cx3.2GHz (Silver 4215R)

**Comment by mariano54** [comment]
Were there any logs before the Websocket Exception? I'm trying to see if the harvester logged something

**Comment by wjblanke** [comment]
crash is probably here in chiapos (<66> 41 83 78 02 00)?

000000000006ccf0 <FSE_decompress_usingDTable@@Base>:
   6ccf0:       41 57                   push   %r15
   6ccf2:       48 01 fe                add    %rdi,%rsi
   6ccf5:       41 56                   push   %r14
   6ccf7:       48 8d 46 fd             lea    -0x3(%rsi),%rax
   6ccfb:       41 55                   push   %r13
   6ccfd:       41 54                   push   %r12
   6ccff:       55                      push   %rbp
   6cd00:       53                      push   %rbx
<SEGFAULT HERE>   6cd01:       66 41 83 78 02 00       cmpw   $0x0,0x2(%r8)
   6cd07:       48 89 44 24 b8          mov    %rax,-0x48(%rsp)
   6cd0c:       48 c7 c0 fd ff ff ff    mov    $0xfffffffffffffffd,%rax
   6cd13:       48 89 7c 24 c0          mov    %rdi,-0x40(%rsp)
   6cd18:       48 89 74 24 b0          mov    %rsi,-0x50(%rsp)
   6cd1d:       0f 85 6d 03 00 00       jne    6d090 <FSE_decompress_usingDTable@@Base+0x3a0>
   6cd23:       48 85 c9                test   %rcx,%rcx
   6cd26:       0f 84 c7 02 00 00       je     6cff3 <FSE_decompress_usingDTable@@Base+0x303>
   6cd2c:       48 8d 42 08             lea    0x8(%rdx),%rax
   6cd30:       48 89 54 24 e0          mov    %rdx,-0x20(%rsp)
   6cd35:       44 0f b6 4c 0a ff       movzbl -0x1(%rdx,%rcx,1),%r9d
   6cd3b:       48 89 44 24 a8          mov    %rax,-0x58(%rsp)
   6cd40:       48 89 44 24 e8          mov    %rax,-0x18(%rsp)
   6cd45:       48 83 f9 07             cmp    $0x7,%rcx
   6cd49:       0f 86 b1 02 00 00       jbe    6d000 <FSE_decompress_usingDTable@@Base+0x310>
   6cd4f:       4c 8d 5c 0a f8          lea    -0x8(%rdx,%rcx,1),%r11
   6cd54:       48 c7 c0 ff ff ff ff    mov    $0xffffffffffffffff,%rax
   6cd5b:       49 8b 3b                mov    (%r11),%rdi

**Comment by wjblanke** [comment]
Looks like it can't access fastMode or something wrong with DTableH (if (fastMode))?

size_t FSE_decompress_usingDTable(void* dst, size_t originalSize,
                            const void* cSrc, size_t cSrcSize,
                            const FSE_DTable* dt)
{
    const void* ptr = dt;
    const FSE_DTableHeader* DTableH = (const FSE_DTableHeader*)ptr;
    const U32 fastMode = DTableH->fastMode;

    /* select fast mode (static) */
    if (fastMode) return FSE_decompress_usingDTable_generic(dst, originalSize, cSrc, cSrcSize, dt, 1);
    return FSE_decompress_usingDTable_generic(dst, originalSize, cSrc, cSrcSize, dt, 0);
}

**Comment by wjblanke** [comment]
6cd01: 66 41 83 78 02 00 cmpw $0x0,0x2(%r8)

offset of 2 would be fastMode

typedef struct {
    U16 tableLog;
    U16 fastMode;
} FSE_DTableHeader;   /* sizeof U32 */

**Comment by wjblanke** [comment]
Any info on which plot was being worked on?

**Comment by wjblanke** [comment]
My guess is FSE_DTableHeader is NULL from an earlier failure

**Comment by PanzerKunst** [comment]
Thank you @eFishCent for this bug report. My remote harvester also "crashed", with the same error.

**Comment by jmhands** [comment]
started remote harvester, and after an hour or so it stopped harvesting. INFO log just stops with no warnings
```19:42:50.870 harvester harvester_server        : INFO     <- new_signage_point_harvester from peer 8f84c32de18253b4fe4b2848c6afceb5e467fbbab1ff52dcb4aa2f46ac016772 192.168.x.x```

htop showing hung harvester
![2021-02-15_21-43-48](https://user-images.githubusercontent.com/69059890/108023609-c3e2bb00-6fd7-11eb-8920-8f117877cb07.jpg)


after restarting getting error
```chia start -r harvester
Traceback (most recent call last):
  File "/home/jm/chia-blockchain/venv/bin/chia", line 33, in <module>
    sys.exit(load_entry_point('chia-blockchain', 'console_scripts', 'chia')())
  File "/home/jm/chia-blockchain/src/cmds/chia.py", line 57, in main
    parser = create_parser()
  File "/home/jm/chia-blockchain/src/cmds/chia.py", line 45, in create_parser
    mod = importlib.import_module("src.cmds.%s" % subcommand)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/jm/chia-blockchain/src/cmds/plots.py", line 10, in <module>
    from src.util.logging import initialize_logging
  File "/home/jm/chia-blockchain/src/util/logging.py", line 8, in <module>
    from concurrent_log_handler import ConcurrentRotatingFileHandler
  File "/home/jm/chia-blockchain/venv/lib/python3.8/site-packages/concurrent_log_handler/__init__.py", line 69, in <module>
    from portalocker import LOCK_EX, lock, unlock
  File "/home/jm/chia-blockchain/venv/lib/python3.8/site-packages/portalocker/__init__.py", line 5, in <module>
    from . import utils
  File "/home/jm/chia-blockchain/venv/lib/python3.8/site-packages/portalocker/utils.py", line 274, in <module>
    class BoundedSemaphore(LockBase):
  File "/home/jm/chia-blockchain/venv/lib/python3.8/site-packages/portalocker/utils.py", line 292, in BoundedSemaphore
    str = tempfile.gettempdir(), timeout=DEFAULT_TIMEOUT,
  File "/usr/lib/python3.8/tempfile.py", line 425, in gettempdir
    tempdir = _get_default_tempdir()
  File "/usr/lib/python3.8/tempfile.py", line 357, in _get_default_tempdir
    raise FileNotFoundError(_errno.ENOENT,
FileNotFoundError: [Errno 2] No usable temporary directory found in ['/tmp', '/var/tmp', '/usr/tmp', '/home/jm/chia-blockchain']```

**Comment by eFishCent** [comment]
More details: I have been doing mass plot moves which included unmounting and remounting drives.

**Comment by PanzerKunst** [comment]
I also believe the "websocket exception" is related to plots being moved. I've also been moving plots on that harvester (via `rsync`).

**Comment by mariano54** [comment]
There was a regression from previous version (beta26). Plots used to not be checked if their sizes are not good. In beta27, they are still loaded.
https://github.com/Chia-Network/chia-blockchain/pull/933

This should help, but this does not fix the underlying issue of segfaults if plot is moving.

**Comment by wjblanke** [comment]
I added some error handling to throw since FSE is error code based. Still need to verify that we catch these.

https://github.com/Chia-Network/chiapos/commit/98aa6e80ff1f0145944faafd1e58495b69e437bd
