### ISSUE TITLE
ERROR    Could not find authentication sk for pk:[Bug] 

### ISSUE THREAD

**Issue by Aminmansouri2020** [Chia-Network/chia-blockchain#9245]
### What happened?

please fix bugs 
1. ERROR    Could not find authentication sk for pk
2. 2.ConnectionResetError: Cannot write to closing transport
3. 3.cant load plot (hange load plots )
4. please fix bugs !

### Version

1.2.11

### What platform are you using?

Windows

### What ui mode are you using?

GUI

### Relevant log output

```shell
2021-11-12T19:07:43.741 farmer chia.farmer.farmer         : ERROR    Could not find authentication sk for pk: 8323618aab0fc92c339fd164f670beecd9a8d03dfd950032
2021-11-12T19:07:50.907 farmer chia.farmer.farmer         : ERROR    Could not find authentication sk for pk: 90b822db1a73cbb7e238f871faaf229fe7fe171b443893f250bee816c721aa34d1696c17551a9
2021-11-12T19:07:58.122 farmer chia.farmer.farmer         : ERROR    Could not find authentication sk for pk: a7f2ef383b5dee0bb6717cf8e75abed6027034e990a54b0ecdfbd6e536fec30d9d435
2021-11-12T19:08:05.306 farmer chia.farmer.farmer         : ERROR    Could not find authentication sk for pk: b0a94ce7ffe0cbc6e08962eb9925b1f2c1cf9d73c15159cdb25c204fbd7b32c456b172daeb9a8618
2021-11-12T19:08:12.506 farmer chia.farmer.farmer         : ERROR    Could not find authentication sk for pk: 829415b611a3c8e87eaf03d511c210f9c02e5323921cf5d7d098a57b599335d62af775e39de
2021-11-12T19:08:19.759 farmer chia.farmer.farmer         : ERROR    Could not find authentication sk for pk: 870692dbd7720d87b4bbc230a9ef0be87620e6c17bd19cffda3df8e8cf432ec940
2021-11-12T19:08:25.474 full_node chia.rpc.rpc_server     : WARNING  Sending data failed. Exception Traceback (most recent call last):
  File "chia\rpc\rpc_server.py", line 69, in _state_changed
  File "aiohttp\client_ws.py", line 150, in send_str
  File "aiohttp\http_websocket.py", line 687, in send
  File "aiohttp\http_websocket.py", line 643, in _send_frame
  File "aiohttp\http_websocket.py", line 660, in _write
ConnectionResetError: Cannot write to closing transport
.
```

**Comment by emlowe** [comment]
`Could not find authentication sk for pk` is a pooling error. You have plotnfts listed in your config.yaml that are likely old or test ones created, possibly on a different machine, that you don't have the key for anymore.

You can look in your config.yaml for the matching items under pool_list and remove them

**Comment by emlowe** [comment]
closing issue
