### ISSUE TITLE
[Bug] Harvester dies when a network share becomes unavailable 

### ISSUE THREAD

**Issue by athena9** [Chia-Network/chia-blockchain#9269]
### What happened?

No plots were found when loading Chia despite multiple restarts - no 'Found plot...' log entries.

Nothing was logged under ERROR / WARNING.

When running 'chia plots check -l -n 0' the following error was revealed:

```
Traceback (most recent call last):
  File "Lib\site-packages\chia\cmds\chia.py", line 134, in <module>
  File "Lib\site-packages\chia\cmds\chia.py", line 130, in main
  File "click\core.py", line 829, in __call__
  File "click\core.py", line 782, in main
  File "click\core.py", line 1259, in invoke
  File "click\core.py", line 1259, in invoke
  File "click\core.py", line 1066, in invoke
  File "click\core.py", line 610, in invoke
  File "click\decorators.py", line 21, in new_func
  File "chia\cmds\plots.py", line 174, in check_cmd
  File "chia\plotting\check_plots.py", line 68, in check_plots
  File "chia\plotting\util.py", line 75, in get_plot_filenames
  File "pathlib.py", line 1215, in resolve
  File "pathlib.py", line 215, in resolve
PermissionError: [WinError 21] The device is not ready: '\\\\[computername]\\[drive]\\'
```
The problem was a disconnected SATA power cable on a remote system with a couple of old/small drives I ran out of space for in the main farm. 

- When a single device is unavailable for any reason it should not take down the entire farm
- When an exception occurs it should be logged. I've seen this sort of silent-exception behavior previously in https://github.com/Chia-Network/chia-blockchain/issues/8905

### Version

1.2.11

### What platform are you using?

Windows 10

### What ui mode are you using?

GUI

**Comment by geoexil** [comment]
I have the same problem very often. When a network shared disk is unavailable the harvester  dies. I have version 1.6.1 but i have the problem with all the previous versions.
