### ISSUE TITLE
[BUG] WebSocket connection is closed when I try to delete plot

### ISSUE THREAD

**Issue by seeden** [Chia-Network/chia-blockchain#927]
When I try to delete the existing plot it will close the current WebSocket connection.
GUI needs to reconnect.

**To Reproduce**
Open GUI and try to delete the existing plot.

**Expected behavior**
The backend will delete the plot and returns the correct value

Here is log:
```
17:06:48.705 daemon __main__                   : ERROR    Unexpected exception in websocket: string indices must be integers Traceback (most recent call last):
  File "../chia-blockchain/src/daemon/server.py", line 152, in safe_handle
    response, sockets_to_use = await self.handle_message(websocket, decoded)
  File "../chia-blockchain/src/daemon/server.py", line 225, in handle_message
    command = message["command"]
KeyError: 'command'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "../chia-blockchain/src/daemon/server.py", line 157, in safe_handle
    response = format_response(message, error)
  File "/Users/seeden/Documents/git/chia-blockchain/src/util/ws_message.py", line 21, in format_response
    "command": incoming_msg["command"],
TypeError: string indices must be integers
```

**Comment by seeden** [comment]
I am closing it. It is not a bug
