### ISSUE TITLE
Harvester dies when drives with loaded plots are umounted while harvester was reading proof data

### ISSUE THREAD

**Issue by xorinox** [Chia-Network/chia-blockchain#928]
**Describe the bug**
I believe the issue occurs when the harvester aims to read proof data while the OS is umounting a USB3 drive.

**Expected behavior**
Harvester moves on after logging to debug.log that there was a critical read error, without the need to be restarted.

**Additional context**
beta27

```
08:14:42.243 harvester src.harvester.harvester : ERROR    Error using prover object. Reinitializing prover object. Caught an unknown exception!
08:14:42.281 harvester src.harvester.harvester : ERROR    Error reinitializing plot /chia/plots/disk04/plot-k32-2021-01-10-23-25-c147d7110d74f4d4655e62ef7f2c320c4bc36236c5d6efccce55d7cd75c60bdc.plot. Caught an unknown exception!
08:14:42.527 daemon src.daemon.server          : INFO     Websocket exception. Closing websocket with chia_harvester code = 1006 (connection closed abnormally [internal]), no reason Traceback (most recent call last):
  File "/opt/chia-blockchain/venv/lib/python3.8/site-packages/websockets/protocol.py", line 827, in transfer_data
    message = await self.read_message()
  File "/opt/chia-blockchain/venv/lib/python3.8/site-packages/websockets/protocol.py", line 895, in read_message
    frame = await self.read_data_frame(max_size=self.max_size)
  File "/opt/chia-blockchain/venv/lib/python3.8/site-packages/websockets/protocol.py", line 971, in read_data_frame
    frame = await self.read_frame(max_size)
  File "/opt/chia-blockchain/venv/lib/python3.8/site-packages/websockets/protocol.py", line 1047, in read_frame
    frame = await Frame.read(
  File "/opt/chia-blockchain/venv/lib/python3.8/site-packages/websockets/framing.py", line 105, in read
    data = await reader(2)
  File "/usr/lib/python3.8/asyncio/streams.py", line 721, in readexactly
    raise exceptions.IncompleteReadError(incomplete, n)
asyncio.exceptions.IncompleteReadError: 0 bytes read on a total of 2 expected bytes

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/chia-blockchain/src/daemon/server.py", line 149, in safe_handle
    async for message in websocket:
  File "/opt/chia-blockchain/venv/lib/python3.8/site-packages/websockets/protocol.py", line 439, in __aiter__
    yield await self.recv()
  File "/opt/chia-blockchain/venv/lib/python3.8/site-packages/websockets/protocol.py", line 509, in recv
    await self.ensure_open()
  File "/opt/chia-blockchain/venv/lib/python3.8/site-packages/websockets/protocol.py", line 803, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedError: code = 1006 (connection closed abnormally [internal]), no reason
```

**Comment by mariano54** [comment]
Hopefully this helps: https://github.com/Chia-Network/chia-blockchain/pull/933
