### ISSUE TITLE
[Bug] Out of memory

### ISSUE THREAD

**Issue by jackouille-ch** [Chia-Network/chia-blockchain#9299]
### What happened?

Hi,
Many plots are stuck at 20%.
When I start one, I always provide more than 8GB RAM (my computer has 64GB).

### Version

1.2.11

### What platform are you using?

Windows

### What ui mode are you using?

GUI

### Relevant log output

```shell
Forward propagation table time: 2227.573 seconds. CPU (137.080%) Wed Nov 17 04:34:34 2021
Computing table 4
Progress update: 0.200
Caught plotting error: Not enough memory for sort in memory. Need to sort 0.812340GiB
Traceback (most recent call last):
  File "Lib\site-packages\chia\cmds\chia.py", line 134, in <module>
  File "Lib\site-packages\chia\cmds\chia.py", line 130, in main
  File "click\core.py", line 829, in __call__
  File "click\core.py", line 782, in main
  File "click\core.py", line 1259, in invoke
  File "click\core.py", line 1066, in invoke
  File "click\core.py", line 610, in invoke
  File "click\decorators.py", line 21, in new_func
  File "chia\cmds\plotters.py", line 14, in plotters_cmd
  File "chia\plotters\plotters.py", line 346, in call_plotters
  File "chia\plotters\chiapos.py", line 57, in plot_chia
  File "asyncio\base_events.py", line 642, in run_until_complete
  File "chia\plotting\create_plots.py", line 250, in create_plots
RuntimeError: Unknown exception
[16068] Failed to execute script 'chia' due to unhandled exception!
```

**Comment by loppefaaret** [comment]
> I always provide more than 8GB RAM

that might be the problem, if you start multiple plotters, even if they only use 3-4GB of physical memory, if you over commit memory like this, you are likely hitting the commit limit of your OS - add more pagefile, or less over commit
