### ISSUE TITLE
[Bug] Unable to open / sync wallet

### ISSUE THREAD

**Issue by xsoft** [Chia-Network/chia-blockchain#9317]
### What happened?

Like other, no wallet start is happening (not at sync / mining mode).
Screenshot: https://i.imgur.com/sZt08CF.png

By logs it looks on network issue.
Any tips? 

Please note that I was (happy) on 1.2.5, but it start to have this issue and it stopped at one moment.
Upgrade to 1.2.11 did NOT resolve this issue.

Many restarts (of PC and program itselfs).
None change at HW.
Im NOT using phrase at this setup.

### Version

1.2.11 (and same with old 1.2.5)

### What platform are you using?

Windows

### What ui mode are you using?

GUI

### Relevant log output

```shell
2021-11-18T11:10:26.417 full_node chia.full_node.full_node: ERROR    failed fetching 1151532 to 1151564 from peers
2021-11-18T11:10:26.439 full_node chia.rpc.rpc_server     : WARNING  Sending data failed. Exception Traceback (most recent call last):
  File "chia\rpc\rpc_server.py", line 69, in _state_changed
  File "aiohttp\client_ws.py", line 150, in send_str
  File "aiohttp\http_websocket.py", line 687, in send
  File "aiohttp\http_websocket.py", line 643, in _send_frame
  File "aiohttp\http_websocket.py", line 660, in _write
ConnectionResetError: Cannot write to closing transport
.
2021-11-18T15:07:54.680 daemon __main__                   : ERROR    Unexpected exception trying to send to websocket: code = 1006 (connection closed abnormally [internal]), no reason Traceback (most recent call last):
  File "asyncio\windows_events.py", line 457, in finish_recv
OSError: [WinError 64] Zadaný síťový název není již dále k dispozici

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "websockets\protocol.py", line 827, in transfer_data
  File "websockets\protocol.py", line 895, in read_message
  File "websockets\protocol.py", line 971, in read_data_frame
  File "websockets\protocol.py", line 1047, in read_frame
  File "websockets\framing.py", line 105, in read
  File "asyncio\streams.py", line 723, in readexactly
  File "asyncio\streams.py", line 517, in _wait_for_data
  File "asyncio\proactor_events.py", line 280, in _loop_reading
  File "asyncio\windows_events.py", line 812, in _poll
  File "asyncio\windows_events.py", line 461, in finish_recv
ConnectionResetError: [WinError 64] Zadaný síťový název není již dále k dispozici

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "Lib\site-packages\chia\daemon\server.py", line 210, in safe_handle
  File "websockets\protocol.py", line 555, in send
  File "websockets\protocol.py", line 803, in ensure_open
websockets.exceptions.ConnectionClosedError: code = 1006 (connection closed abnormally [internal]), no reason
```

**Comment by StudioCassiano** [comment]
Same problem, please help. No changes done! Just happened today after a computer restart due to a crash generated during a plotting

**Comment by xsoft** [comment]
Hello developers. It is 2 days and Im still offline. Any update?

**Comment by luotinen** [comment]
Hi! I have the same problem. It has been over 24 h and the circles just keep rolling. 

Screenshot: https://www.dropbox.com/s/yks3kps6dom4l54/no%20connect.PNG?dl=0

**Comment by jredner** [comment]
Seriously, I have the latest client on Mac.  I've restarted it with a clean db and wallet directory about 5 times now over the course of 3 weeks.  I find that I get to about the 600k range in the blockchain and it slows to a crawl.  So, first 24 hours up to 600k no problem, the remainder just never happens. 

@bramcohen, I think you need to seriously consider investing more time in the syncing and wallet performance. Full stop.  Thank you for listening.

**Comment by xsoft** [comment]
Complete resync. 4 days later ... no, still not fixed.
Any tips?
