### ISSUE TITLE
[Bug] chia.farmer.farmer         : ERROR    Harvester  did not respond

### ISSUE THREAD

**Issue by wgang0402** [Chia-Network/chia-blockchain#9340]
### Version

1.2.11

### What platform are you using?

Windows

### What ui mode are you using?

GUI

### Relevant log output

```shell
2021-11-22T12:55:27.182 farmer chia.farmer.farmer         : WARNING  Respond plots came too late from: {'host': '127.0.0.1', 'port': 8448}
2021-11-22T12:56:23.697 farmer chia.farmer.farmer         : ERROR    Harvester '127.0.0.1/b9fb5482df9daf40e254c7e82f7e74296e480b086a0830595d730e60c560235e' did not respond: (version mismatch or time out 90s)
2021-11-22T12:56:26.410 farmer chia.farmer.farmer         : ERROR    Invalid response from harvester: None
2021-11-22T12:56:26.412 farmer chia.farmer.farmer         : ERROR    Invalid response from harvester: None
2021-11-22T12:56:26.414 farmer chia.farmer.farmer         : ERROR    Invalid response from harvester: None
2021-11-22T12:56:26.415 farmer chia.farmer.farmer         : ERROR    Invalid response from harvester: None
2021-11-22T12:56:26.417 farmer chia.farmer.farmer         : ERROR    Invalid response from harvester: None
2021-11-22T12:56:26.419 farmer chia.farmer.farmer         : ERROR    Invalid response from harvester: None
2021-11-22T12:57:54.713 farmer chia.farmer.farmer         : ERROR    Harvester '127.0.0.1/b9fb5482df9daf40e254c7e82f7e74296e480b086a0830595d730e60c560235e' did not respond: (version mismatch or time out 90s)
2021-11-22T12:59:25.740 farmer chia.farmer.farmer         : ERROR    Harvester '127.0.0.1/b9fb5482df9daf40e254c7e82f7e74296e480b086a0830595d730e60c560235e' did not respond: (version mismatch or time out 90s)
2021-11-22T12:59:31.672 full_node chia.full_node.full_node: WARNING  Block validation time: 2.62 seconds, pre_validation time: 0.44 seconds, cost: 2302932016, percent full: 20.936%
2021-11-22T13:00:56.752 farmer chia.farmer.farmer         : ERROR    Harvester '127.0.0.1/b9fb5482df9daf40e254c7e82f7e74296e480b086a0830595d730e60c560235e' did not respond: (version mismatch or time out 90s)
2021-11-22T13:02:27.762 farmer chia.farmer.farmer         : ERROR    Harvester '127.0.0.1/b9fb5482df9daf40e254c7e82f7e74296e480b086a0830595d730e60c560235e' did not respond: (version mismatch or time out 90s)
2021-11-22T13:03:58.797 farmer chia.farmer.farmer         : ERROR    Harvester '127.0.0.1/b9fb5482df9daf40e254c7e82f7e74296e480b086a0830595d730e60c560235e' did not respond: (version mismatch or time out 90s)
2021-11-22T13:05:29.810 farmer chia.farmer.farmer         : ERROR    Harvester '127.0.0.1/b9fb5482df9daf40e254c7e82f7e74296e480b086a0830595d730e60c560235e' did not respond: (version mismatch or time out 90s)
2021-11-22T13:07:00.825 farmer chia.farmer.farmer         : ERROR    Harvester '127.0.0.1/b9fb5482df9daf40e254c7e82f7e74296e480b086a0830595d730e60c560235e' did not respond: (version mismatch or time out 90s)
2021-11-22T13:08:31.855 farmer chia.farmer.farmer         : ERROR    Harvester '127.0.0.1/b9fb5482df9daf40e254c7e82f7e74296e480b086a0830595d730e60c560235e' did not respond: (version mismatch or time out 90s)
2021-11-22T13:08:55.304 full_node chia.full_node.full_node: WARNING  Block validation time: 4.88 seconds, pre_validation time: 0.41 seconds, cost: 1604147488, percent full: 14.583%
2021-11-22T13:10:02.858 farmer chia.farmer.farmer         : ERROR    Harvester '127.0.0.1/b9fb5482df9daf40e254c7e82f7e74296e480b086a0830595d730e60c560235e' did not respond: (version mismatch or time out 90s)
2021-11-22T13:10:43.657 harvester chia.harvester.harvester: WARNING  Looking up qualities on I:\plot-k32-2021-07-20-17-44-45e36ca9fa24d288435ae9330603b00dcabd7bc30df960bb67b9d6a40a7d8fb4.plot took: 1213.583859205246. This should be below 5 seconds to minimize risk of losing rewards.
2021-11-22T13:10:43.658 harvester chia.harvester.harvester: WARNING  Looking up qualities on E:\plot-k32-2021-08-03-03-04-8a4d027ffc3c09728caa58fa7cb907f804adf19bbdc1e5636c0918d287fd29ab.plot took: 1213.5848560333252. This should be below 5 seconds to minimize risk of losing rewards.
2021-11-22T13:10:43.659 harvester chia.harvester.harvester: WARNING  Looking up qualities on F:\plot-k32-2021-08-26-12-05-49f62f3dd83bdccb4a7603b6219480c97bb45cdca3ece635b0969a425a0d8690.plot took: 1223.9311408996582. This should be below 5 seconds to minimize risk of losing rewards.
2021-11-22T13:10:43.659 harvester chia.harvester.harvester: WARNING  Looking up qualities on H:\plot-k32-2021-08-27-19-18-2d2dc080ff01602d63e0c29ea0b180af0d0583cd1357c5d46e018fe773f5f58c.plot took: 1223.9311408996582. This should be below 5 seconds to minimize risk of losing rewards.
2021-11-22T13:10:43.659 harvester chia.harvester.harvester: WARNING  Looking up qualities on Q:\plot-k32-2021-10-13-16-45-7c4b22016b500b00c62898129e94da16d990ce947f8a8c07b7ad1d625bd8cc0a.plot took: 998.4510982036591. This should be below 5 seconds to minimize risk of losing rewards.
2021-11-22T13:10:43.660 harvester chia.harvester.harvester: WARNING  Looking up qualities on F:\plot-k32-2021-07-20-01-41-35ceb00ed7390d899f3ab8be646c9349664cdaf1e817a9321e55b08fb9ae3242.plot took: 985.2307786941528. This should be below 5 seconds to minimize risk of losing rewards.
2021-11-22T13:10:43.665 harvester chia.harvester.harvester: WARNING  Looking up qualities on E:\plot-k32-2021-08-01-14-35-86db956de8dbd1f08a500a8304809853744b3c60d334da98e39d1f67d2e8b900.plot took: 988.8054096698761. This should be below 5 seconds to minimize risk of losing rewards.
2021-11-22T13:10:43.668 harvester chia.harvester.harvester: WARNING  Looking up qualities on M:\plot-k32-2021-07-15-17-01-b85c37b32e970c3fd0c1d1779deff368849d6579a338ab52280321f59f015982.plot took: 1223.9401378631592. This should be below 5 seconds to minimize risk of losing rewards.
2021-11-22T13:10:43.670 harvester chia.harvester.harvester: WARNING  Looking up qualities on K:\plot-k32-2021-07-24-16-50-67ea873000b2859de2de786cce4b2855eccc4f1230fff9eb45e66026fddfa75f.plot took: 1223.942137002945. This should be below 5 seconds to minimize risk of losing rewards.
2021-11-22T13:10:44.573 harvester harvester_server        : WARNING  Peer surpassed rate limit 127.0.0.1, message: new_signage_point_harvester, port 8447 but not disconnecting
2021-11-22T13:10:44.574 harvester harvester_server        : WARNING  Peer surpassed rate limit 127.0.0.1, message: new_signage_point_harvester, port 8447 but not disconnecting
2021-11-22T13:10:44.575 harvester harvester_server        : WARNING  Peer surpassed rate limit 127.0.0.1, message: new_signage_point_harvester, port 8447 but not disconnecting
2021-11-22T13:10:44.576 harvester harvester_server        : WARNING  Peer surpassed rate limit 127.0.0.1, message: new_signage_point_harvester, port 8447 but not disconnecting
2021-11-22T13:10:44.576 harvester harvester_server        : WARNING  Peer surpassed rate limit 127.0.0.1, message: new_signage_point_harvester, port 8447 but not disconnecting
2021-11-22T13:10:44.578 harvester harvester_server        : WARNING  Peer surpassed rate limit 127.0.0.1, message: new_signage_point_harvester, port 8447 but not disconnecting
2021-11-22T13:10:44.588 farmer farmer_server              : ERROR    Exception: <bytes32: cdaf49bfbf1c92d9c417784c1919eff394ca4c8c87ff4dce9bcc1fb3ab4cb461>, {'host': '127.0.0.1', 'port': 8448}. Traceback (most recent call last):
  File "chia\server\server.py", line 566, in wrapped_coroutine
  File "chia\farmer\farmer_api.py", line 287, in respond_signatures
KeyError: <bytes32: cdaf49bfbf1c92d9c417784c1919eff394ca4c8c87ff4dce9bcc1fb3ab4cb461>
```

**Comment by loppefaaret** [comment]
Your harvester spending 1200 seconds on a lookup sounds a little over the expected ? is the drive itself ok ? do you have any reports in your log from the harvester reporting ERROR about reading any of the plot files ?

**Comment by emlowe** [comment]
You are getting the harvester did not respond errors because your harvester is blocked while performing these very slow lookups on your disks. You need to figure out why your disks are not responding for 15 to 20 mins. Are your disks on a NAS?

In any event, this is a problem with your disk setup.

**Comment by wgang0402** [comment]
> 

@emlowe  A part of disks is directly connected to the SATA port of the computer motherboard, and the other part is connected to the computer motherboard through a PCIE adapter card. There is no abnormality .

**Comment by emlowe** [comment]
`Looking up qualities on I:\plot-k32-2021-07-20-17-44-45e36ca9fa24d288435ae9330603b00dcabd7bc30df960bb67b9d6a40a7d8fb4.plot took: 1213.583859205246`

This is over 20 minutes - there is definitely an abnormality

**Comment by wtfiwinomgs** [comment]
I am also getting this error no change to the system.
