### ISSUE TITLE
[Bug] daemon staicoin.daemon.server     : INFO     Websocket exception. Closing websocket with staicoin_harvester code = 1006 (connection closed abnormally [internal]), no reason Traceback (most recent call last):

### ISSUE THREAD

**Issue by linming66** [Chia-Network/chia-blockchain#9365]
### What happened?

2021-11-23T22:42:40.468 daemon staicoin.daemon.server: INFO Websocket exception. Closing websocket with staicoin_harvester code = 1006 (connection closed abnormally [internal]), no reason Traceback (most recent call last):
  File "asyncio\windows_events.py", line 457, in finish_recv
OSError: [WinError 64] The specified network name is no longer available.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "websockets\protocol.py", line 827, in transfer_data
  File "websockets\protocol.py", line 895, in read_message
  File "websockets\protocol.py", line 971, in read_data_frame
  File "websockets\protocol.py", line 1047, in read_frame
  File "websockets\framing.py", line 105, in read
  File "asyncio\streams.py", line 723, in readexactly
  File "asyncio\streams.py", line 517, in _wait_for_data
  File "asyncio\proactor_events.py", line 280, in _loop_reading
  File "asyncio\windows_events.py", line 812, in _poll
  File "asyncio\windows_events.py", line 461, in finish_recv
ConnectionResetError: [WinError 64] The specified network name is no longer available.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "staicoin\daemon\server.py", line 172, in safe_handle
  File "websockets\protocol.py", line 439, in __aiter__
  File "websockets\protocol.py", line 509, in recv
  File "websockets\protocol.py", line 803, in ensure_open
websockets.exceptions.ConnectionClosedError: code = 1006 (connection closed abnormally [internal]), no reason

**May I ask how to solve this problem. This problem has already wasted too much farming time. It drops 3-5 times a day. Now I often need to see him for fear that he will be disconnected.**

### Version

win10 professional edition 

### What platform are you using?

Windows

### What ui mode are you using?

CLI

### Relevant log output

```shell
2021-11-23T22:42:40.468 daemon staicoin.daemon.server: INFO Websocket exception. Closing websocket with staicoin_harvester code = 1006 (connection closed abnormally [internal]), no reason Traceback (most recent call last):
  File "asyncio\windows_events.py", line 457, in finish_recv
OSError: [WinError 64] The specified network name is no longer available.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "websockets\protocol.py", line 827, in transfer_data
  File "websockets\protocol.py", line 895, in read_message
  File "websockets\protocol.py", line 971, in read_data_frame
  File "websockets\protocol.py", line 1047, in read_frame
  File "websockets\framing.py", line 105, in read
  File "asyncio\streams.py", line 723, in readexactly
  File "asyncio\streams.py", line 517, in _wait_for_data
  File "asyncio\proactor_events.py", line 280, in _loop_reading
  File "asyncio\windows_events.py", line 812, in _poll
  File "asyncio\windows_events.py", line 461, in finish_recv
ConnectionResetError: [WinError 64] The specified network name is no longer available.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "staicoin\daemon\server.py", line 172, in safe_handle
  File "websockets\protocol.py", line 439, in __aiter__
  File "websockets\protocol.py", line 509, in recv
  File "websockets\protocol.py", line 803, in ensure_open
websockets.exceptions.ConnectionClosedError: code = 1006 (connection closed abnormally [internal]), no reason
```

**Comment by emlowe** [comment]
`staicoin.daemon.server` - this is a fork of chia - I suggest you talk to them
