### ISSUE TITLE
[Bug] 2021-11-25T12:13:34.126 full_node chia.rpc.rpc_server     : WARNING  Sending data failed. Exception Traceback (most recent call last)

### ISSUE THREAD

**Issue by ToniMarti** [Chia-Network/chia-blockchain#9389]
### What happened?

ERRORES

### Version

1.2.11 | 64 bits

### What platform are you using?

Windows

### What ui mode are you using?

GUI

### Relevant log output

```shell
2021-11-25T12:13:34.126 full_node chia.rpc.rpc_server     : WARNING  Sending data failed. Exception Traceback (most recent call last):
  File "chia\rpc\rpc_server.py", line 69, in _state_changed
  File "aiohttp\client_ws.py", line 150, in send_str
  File "aiohttp\http_websocket.py", line 687, in send
  File "aiohttp\http_websocket.py", line 643, in _send_frame
  File "aiohttp\http_websocket.py", line 660, in _write
ConnectionResetError: Cannot write to closing transport
.
2021-11-25T12:13:34.178 full_node chia.rpc.rpc_server     : WARNING  Sending data failed. Exception Traceback (most recent call last):
  File "chia\rpc\rpc_server.py", line 69, in _state_changed
  File "aiohttp\client_ws.py", line 150, in send_str
  File "aiohttp\http_websocket.py", line 687, in send
  File "aiohttp\http_websocket.py", line 643, in _send_frame
  File "aiohttp\http_websocket.py", line 660, in _write
ConnectionResetError: Cannot write to closing transport
.
2021-11-25T12:13:50.954 full_node chia.rpc.rpc_server     : WARNING  Sending data failed. Exception Traceback (most recent call last):
  File "chia\rpc\rpc_server.py", line 69, in _state_changed
  File "aiohttp\client_ws.py", line 150, in send_str
  File "aiohttp\http_websocket.py", line 687, in send
  File "aiohttp\http_websocket.py", line 643, in _send_frame
  File "aiohttp\http_websocket.py", line 660, in _write
ConnectionResetError: Cannot write to closing transport
.
2021-11-25T12:13:50.960 full_node chia.rpc.rpc_server     : WARNING  Sending data failed. Exception Traceback (most recent call last):
  File "chia\rpc\rpc_server.py", line 69, in _state_changed
  File "aiohttp\client_ws.py", line 150, in send_str
  File "aiohttp\http_websocket.py", line 687, in send
  File "aiohttp\http_websocket.py", line 643, in _send_frame
  File "aiohttp\http_websocket.py", line 660, in _write
ConnectionResetError: Cannot write to closing transport
.
2021-11-25T12:13:52.159 full_node chia.rpc.rpc_server     : WARNING  Sending data failed. Exception Traceback (most recent call last):
  File "chia\rpc\rpc_server.py", line 69, in _state_changed
  File "aiohttp\client_ws.py", line 150, in send_str
  File "aiohttp\http_websocket.py", line 687, in send
  File "aiohttp\http_websocket.py", line 643, in _send_frame
  File "aiohttp\http_websocket.py", line 660, in _write
ConnectionResetError: Cannot write to closing transport
.
2021-11-25T12:13:52.169 full_node chia.rpc.rpc_server     : WARNING  Sending data failed. Exception Traceback (most recent call last):
  File "chia\rpc\rpc_server.py", line 69, in _state_changed
  File "aiohttp\client_ws.py", line 150, in send_str
  File "aiohttp\http_websocket.py", line 687, in send
  File "aiohttp\http_websocket.py", line 643, in _send_frame
  File "aiohttp\http_websocket.py", line 660, in _write
ConnectionResetError: Cannot write to closing transport
.
2021-11-25T12:14:16.568 full_node chia.rpc.rpc_server     : WARNING  Sending data failed. Exception Traceback (most recent call last):
  File "chia\rpc\rpc_server.py", line 69, in _state_changed
  File "aiohttp\client_ws.py", line 150, in send_str
  File "aiohttp\http_websocket.py", line 687, in send
  File "aiohttp\http_websocket.py", line 643, in _send_frame
  File "aiohttp\http_websocket.py", line 660, in _write
ConnectionResetError: Cannot write to closing transport
.
2021-11-25T12:14:16.642 full_node chia.rpc.rpc_server     : WARNING  Sending data failed. Exception Traceback (most recent call last):
  File "chia\rpc\rpc_server.py", line 69, in _state_changed
  File "aiohttp\client_ws.py", line 150, in send_str
  File "aiohttp\http_websocket.py", line 687, in send
  File "aiohttp\http_websocket.py", line 643, in _send_frame
  File "aiohttp\http_websocket.py", line 660, in _write
ConnectionResetError: Cannot write to closing transport
.
2021-11-25T12:14:57.736 full_node chia.rpc.rpc_server     : WARNING  Sending data failed. Exception Traceback (most recent call last):
  File "chia\rpc\rpc_server.py", line 69, in _state_changed
  File "aiohttp\client_ws.py", line 150, in send_str
  File "aiohttp\http_websocket.py", line 687, in send
  File "aiohttp\http_websocket.py", line 643, in _send_frame
  File "aiohttp\http_websocket.py", line 660, in _write
ConnectionResetError: Cannot write to closing transport
.
2021-11-25T12:14:58.388 full_node chia.rpc.rpc_server     : WARNING  Sending data failed. Exception Traceback (most recent call last):
  File "chia\rpc\rpc_server.py", line 69, in _state_changed
  File "aiohttp\client_ws.py", line 150, in send_str
  File "aiohttp\http_websocket.py", line 687, in send
  File "aiohttp\http_websocket.py", line 643, in _send_frame
  File "aiohttp\http_websocket.py", line 660, in _write
ConnectionResetError: Cannot write to closing transport
.
2021-11-25T12:15:38.919 daemon websockets.protocol        : ERROR    Error in data transfer
Traceback (most recent call last):
  File "websockets\protocol.py", line 827, in transfer_data
  File "websockets\protocol.py", line 895, in read_message
  File "websockets\protocol.py", line 971, in read_data_frame
  File "websockets\protocol.py", line 1047, in read_frame
  File "websockets\framing.py", line 133, in read
  File "asyncio\streams.py", line 723, in readexactly
  File "asyncio\streams.py", line 513, in _wait_for_data
  File "asyncio\sslproto.py", line 343, in resume_reading
AttributeError: 'NoneType' object has no attribute 'resume_reading'
```

**Comment by loppefaaret** [comment]
Something prior to this log output cause it to loose the internal rpc connection with another chia service.
a simple reboot of the machine is recommended - if this is a returning problem, if we could ask you to turn on INFO level logging, either from CLI with `.\chia configure --log-level INFO` https://github.com/Chia-Network/chia-blockchain/wiki/CLI-Commands-Reference#windows
and when it has happened again, attach the `debug.log` file to this issue - it is located under your users folder `~\.chia\mainnet\log\`

**Comment by linming66** [comment]
2021-11-26T11:40:28.677 harvester chia.rpc.rpc_server     : WARNING  Sending data failed. Exception Traceback (most recent call last):
  File "chia\rpc\rpc_server.py", line 69, in _state_changed
  File "aiohttp\client_ws.py", line 150, in send_str
  File "aiohttp\http_websocket.py", line 687, in send
  File "aiohttp\http_websocket.py", line 656, in _send_frame
  File "aiohttp\base_protocol.py", line 84, in _drain_helper
AssertionError

**Boss, I also encountered the same problem, please solve it**

**Comment by jimmyeao** [comment]
I can verify I have the same issue, 
Win 11 22000.348
Chia Version 1.2.11
Example log entry:
```
2021-12-03T17:12:21.040 full_node chia.rpc.rpc_server     : WARNING  Sending data failed. Exception Traceback (most recent call last):
  File "chia\rpc\rpc_server.py", line 69, in _state_changed
  File "aiohttp\client_ws.py", line 150, in send_str
  File "aiohttp\http_websocket.py", line 687, in send
  File "aiohttp\http_websocket.py", line 643, in _send_frame
  File "aiohttp\http_websocket.py", line 660, in _write
ConnectionResetError: Cannot write to closing transport
.
2021-12-03T17:12:21.047 full_node chia.rpc.rpc_server     : WARNING  Sending data failed. Exception Traceback (most recent call last):
  File "chia\rpc\rpc_server.py", line 69, in _state_changed
  File "aiohttp\client_ws.py", line 150, in send_str
  File "aiohttp\http_websocket.py", line 687, in send
  File "aiohttp\http_websocket.py", line 643, in _send_frame
  File "aiohttp\http_websocket.py", line 660, in _write
ConnectionResetError: Cannot write to closing transport
.
2021-12-03T17:12:21.132 full_node chia.rpc.rpc_server     : WARNING  Sending data failed. Exception Traceback (most recent call last):
  File "chia\rpc\rpc_server.py", line 69, in _state_changed
  File "aiohttp\client_ws.py", line 150, in send_str
  File "aiohttp\http_websocket.py", line 687, in send
  File "aiohttp\http_websocket.py", line 643, in _send_frame
  File "aiohttp\http_websocket.py", line 660, in _write
ConnectionResetError: Cannot write to closing transport
.
2021-12-03T17:12:21.136 full_node chia.rpc.rpc_server     : WARNING  Sending data failed. Exception Traceback (most recent call last):
  File "chia\rpc\rpc_server.py", line 69, in _state_changed
  File "aiohttp\client_ws.py", line 150, in send_str
  File "aiohttp\http_websocket.py", line 687, in send
  File "aiohttp\http_websocket.py", line 643, in _send_frame
  File "aiohttp\http_websocket.py", line 660, in _write
ConnectionResetError: Cannot write to closing transport
.
2021-12-03T17:12:36.500 daemon asyncio                    : ERROR    Task exception was never retrieved
future: <Task finished name='Task-616' coro=<kill_service() done, defined at Lib\site-packages\chia\daemon\server.py:1291> exception=AttributeError("'list' object has no attribute 'pid'")>
Traceback (most recent call last):
  File "Lib\site-packages\chia\daemon\server.py", line 1299, in kill_service
  File "Lib\site-packages\chia\daemon\server.py", line 1263, in kill_process
AttributeError: 'list' object has no attribute 'pid'
```
