### ISSUE TITLE
[Bug] WinError 64 - WebSocket 1006

### ISSUE THREAD

**Issue by neo57500** [Chia-Network/chia-blockchain#9411]
### What happened?

bug

### Version

1.2.11

### What platform are you using?

Windows

### What ui mode are you using?

GUI

### Relevant log output

```shell
Traceback (most recent call last):
  File "websockets\protocol.py", line 827, in transfer_data
  File "websockets\protocol.py", line 895, in read_message
  File "websockets\protocol.py", line 971, in read_data_frame
  File "websockets\protocol.py", line 1047, in read_frame
  File "websockets\framing.py", line 105, in read
  File "asyncio\streams.py", line 723, in readexactly
  File "asyncio\streams.py", line 517, in _wait_for_data
  File "asyncio\proactor_events.py", line 280, in _loop_reading
  File "asyncio\windows_events.py", line 812, in _poll
  File "asyncio\windows_events.py", line 461, in finish_recv
ConnectionResetError: [WinError 64] Le nom réseau spécifié n’est plus disponible

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "chia\daemon\client.py", line 33, in listener
  File "websockets\protocol.py", line 509, in recv
  File "websockets\protocol.py", line 803, in ensure_open
websockets.exceptions.ConnectionClosedError: code = 1006 (connection closed abnormally [internal]), no reason
2021-11-27T13:58:28.948 wallet asyncio                    : ERROR    Task exception was never retrieved
future: <Task finished name='Task-7' coro=<DaemonProxy.start.<locals>.listener() done, defined at chia\daemon\client.py:30> exception=ConnectionClosedError('code = 1006 (connection closed abnormally [internal]), no reason')>
Traceback (most recent call last):
  File "asyncio\windows_events.py", line 457, in finish_recv
OSError: [WinError 64] Le nom réseau spécifié n’est plus disponible

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "websockets\protocol.py", line 827, in transfer_data
  File "websockets\protocol.py", line 895, in read_message
  File "websockets\protocol.py", line 971, in read_data_frame
  File "websockets\protocol.py", line 1047, in read_frame
  File "websockets\framing.py", line 105, in read
  File "asyncio\streams.py", line 723, in readexactly
  File "asyncio\streams.py", line 517, in _wait_for_data
  File "asyncio\proactor_events.py", line 280, in _loop_reading
  File "asyncio\windows_events.py", line 812, in _poll
  File "asyncio\windows_events.py", line 461, in finish_recv
ConnectionResetError: [WinError 64] Le nom réseau spécifié n’est plus disponible

The above exception was the direct cause of the following exception:
```

**Comment by paulhainsworth-chia** [comment]
@neo57500 can you please summarize what happened? What behavior are you seeing?

**Comment by paulhainsworth-chia** [comment]
@neo57500 can you let us know what CPU you're running?

**Comment by neo57500** [comment]
my cpu 2 x intel xeon e5 2650

**Comment by neo57500** [comment]
2021-11-28T17:43:02.052 full_node chia.full_node.full_node: WARNING  Block validation time: 3.45 seconds, pre_validation time: 0.71 seconds, cost: 184073730, percent full: 1.673%
2021-11-28T17:43:02.710 daemon __main__                   : ERROR    Error while handling message: Traceback (most recent call last):
  File "Lib\site-packages\chia\daemon\server.py", line 992, in stop_plotting
  File "Lib\site-packages\chia\daemon\server.py", line 824, in _get_plots_queue_item
StopIteration

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "Lib\site-packages\chia\daemon\server.py", line 200, in safe_handle
  File "Lib\site-packages\chia\daemon\server.py", line 306, in handle_message
RuntimeError: coroutine raised StopIteration

2021-11-28T17:53:42.581 wallet asyncio                    : ERROR    Task exception was never retrieved
future: <Task finished name='Task-7' coro=<DaemonProxy.start.<locals>.listener() done, defined at chia\daemon\client.py:30> exception=ConnectionClosedError('code = 1006 (connection closed abnormally [internal]), no reason')>
Traceback (most recent call last):
  File "asyncio\windows_events.py", line 457, in finish_recv
OSError: [WinError 64] Le nom réseau spécifié n’est plus disponible

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "websockets\protocol.py", line 827, in transfer_data
  File "websockets\protocol.py", line 895, in read_message
  File "websockets\protocol.py", line 971, in read_data_frame
  File "websockets\protocol.py", line 1047, in read_frame
  File "websockets\framing.py", line 105, in read
  File "asyncio\streams.py", line 723, in readexactly
  File "asyncio\streams.py", line 517, in _wait_for_data
  File "asyncio\proactor_events.py", line 280, in _loop_reading
  File "asyncio\windows_events.py", line 812, in _poll
  File "asyncio\windows_events.py", line 461, in finish_recv
ConnectionResetError: [WinError 64] Le nom réseau spécifié n’est plus disponible

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "chia\daemon\client.py", line 33, in listener
  File "websockets\protocol.py", line 509, in recv
  File "websockets\protocol.py", line 803, in ensure_open
websockets.exceptions.ConnectionClosedError: code = 1006 (connection closed abnormally [internal]), no reason
2021-11-28T17:53:42.581 farmer asyncio                    : ERROR    Task exception was never retrieved
future: <Task finished name='Task-7' coro=<DaemonProxy.start.<locals>.listener() done, defined at chia\daemon\client.py:30> exception=ConnectionClosedError('code = 1006 (connection closed abnormally [internal]), no reason')>
Traceback (most recent call last):
  File "asyncio\windows_events.py", line 457, in finish_recv
OSError: [WinError 64] Le nom réseau spécifié n’est plus disponible

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "websockets\protocol.py", line 827, in transfer_data
  File "websockets\protocol.py", line 895, in read_message
  File "websockets\protocol.py", line 971, in read_data_frame
  File "websockets\protocol.py", line 1047, in read_frame
  File "websockets\framing.py", line 105, in read
  File "asyncio\streams.py", line 723, in readexactly
  File "asyncio\streams.py", line 517, in _wait_for_data
  File "asyncio\proactor_events.py", line 280, in _loop_reading
  File "asyncio\windows_events.py", line 812, in _poll
  File "asyncio\windows_events.py", line 461, in finish_recv
ConnectionResetError: [WinError 64] Le nom réseau spécifié n’est plus disponible

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "chia\daemon\client.py", line 33, in listener
  File "websockets\protocol.py", line 509, in recv
  File "websockets\protocol.py", line 803, in ensure_open
websockets.exceptions.ConnectionClosedError: code = 1006 (connection closed abnormally [internal]), no reason
2021-11-28T18:08:44.695 farmer asyncio                    : ERROR    Task exception was never retrieved
future: <Task finished name='Task-7' coro=<DaemonProxy.start.<locals>.listener() done, defined at chia\daemon\client.py:30> exception=ConnectionClosedError('code = 1006 (connection closed abnormally [internal]), no reason')>
Traceback (most recent call last):
  File "asyncio\windows_events.py", line 457, in finish_recv
OSError: [WinError 64] Le nom réseau spécifié n’est plus disponible

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "websockets\protocol.py", line 827, in transfer_data
  File "websockets\protocol.py", line 895, in read_message
  File "websockets\protocol.py", line 971, in read_data_frame
  File "websockets\protocol.py", line 1047, in read_frame
  File "websockets\framing.py", line 105, in read
  File "asyncio\streams.py", line 723, in readexactly
  File "asyncio\streams.py", line 517, in _wait_for_data
  File "asyncio\proactor_events.py", line 280, in _loop_reading
  File "asyncio\windows_events.py", line 812, in _poll
  File "asyncio\windows_events.py", line 461, in finish_recv
ConnectionResetError: [WinError 64] Le nom réseau spécifié n’est plus disponible

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "chia\daemon\client.py", line 33, in listener
  File "websockets\protocol.py", line 509, in recv
  File "websockets\protocol.py", line 803, in ensure_open
websockets.exceptions.ConnectionClosedError: code = 1006 (connection closed abnormally [internal]), no reason
2021-11-28T18:08:44.695 wallet asyncio                    : ERROR    Task exception was never retrieved
future: <Task finished name='Task-7' coro=<DaemonProxy.start.<locals>.listener() done, defined at chia\daemon\client.py:30> exception=ConnectionClosedError('code = 1006 (connection closed abnormally [internal]), no reason')>
Traceback (most recent call last):
  File "asyncio\windows_events.py", line 457, in finish_recv
OSError: [WinError 64] Le nom réseau spécifié n’est plus disponible

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "websockets\protocol.py", line 827, in transfer_data
  File "websockets\protocol.py", line 895, in read_message
  File "websockets\protocol.py", line 971, in read_data_frame
  File "websockets\protocol.py", line 1047, in read_frame
  File "websockets\framing.py", line 105, in read
  File "asyncio\streams.py", line 723, in readexactly
  File "asyncio\streams.py", line 517, in _wait_for_data
  File "asyncio\proactor_events.py", line 280, in _loop_reading
  File "asyncio\windows_events.py", line 812, in _poll
  File "asyncio\windows_events.py", line 461, in finish_recv
ConnectionResetError: [WinError 64] Le nom réseau spécifié n’est plus disponible

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "chia\daemon\client.py", line 33, in listener
  File "websockets\protocol.py", line 509, in recv
  File "websockets\protocol.py", line 803, in ensure_open
websockets.exceptions.ConnectionClosedError: code = 1006 (connection closed abnormally [internal]), no reason
