### ISSUE TITLE
[Bug] RuntimeError: Was not able to add blocks 391793-391825 (wallet stuck at 391793)

### ISSUE THREAD

**Issue by luotinen** [Chia-Network/chia-blockchain#9412]
### What happened?

For over a week now, the wallet sync has been stuck at 391,793. Restarting does not solve the problem. Is there some way to enable the wallet to sync?

### Version

1.2.11

### What platform are you using?

Windows

### What ui mode are you using?

GUI

**Comment by luotinen** [comment]
I found something in the logs:
"
2021-11-27T16:22:47.113 wallet chia.wallet.wallet_node    : ERROR    Error while trying to fetch from peer:Peer returned no response Traceback (most recent call last):
  File "chia\wallet\wallet_node.py", line 563, in batch_sync_to_peak
  File "chia\wallet\wallet_node.py", line 695, in fetch_blocks_and_validate
ValueError: Peer returned no response

2021-11-27T16:22:47.115 wallet chia.wallet.wallet_node    : ERROR    Loop exception in sync Was not able to add blocks 391793-391825. Traceback (most recent call last):
  File "chia\wallet\wallet_node.py", line 616, in sync_job
  File "chia\wallet\wallet_node.py", line 676, in _sync
  File "chia\wallet\wallet_node.py", line 573, in batch_sync_to_peak
RuntimeError: Was not able to add blocks 391793-391825
"

**Comment by loppefaaret** [comment]
if you could locate you debug.log and attach it to this issue please.
the full path is C:\Users\<USERNAME>\.chia\mainnet\log\debug.log where <USERNAME> is the name of the user account on your windows installation.

**Comment by luotinen** [comment]
Here you go:
https://www.dropbox.com/s/f6gdocm1sclikbo/debug.log?dl=0

PS. Now it is stuck at 575,823 and the relevant clip is
"
2021-12-03T03:20:55.679 wallet chia.wallet.wallet_node    : ERROR    Error while trying to fetch from peer:Peer returned no response Traceback (most recent call last):
  File "chia\wallet\wallet_node.py", line 563, in batch_sync_to_peak
  File "chia\wallet\wallet_node.py", line 695, in fetch_blocks_and_validate
ValueError: Peer returned no response

2021-12-03T03:20:55.681 wallet chia.wallet.wallet_node    : ERROR    Loop exception in sync Was not able to add blocks 575823-575855. Traceback (most recent call last):
  File "chia\wallet\wallet_node.py", line 616, in sync_job
  File "chia\wallet\wallet_node.py", line 676, in _sync
  File "chia\wallet\wallet_node.py", line 573, in batch_sync_to_peak
RuntimeError: Was not able to add blocks 575823-575855

2021-12-03T03:20:55.683 wallet chia.wallet.wallet_node    : WARNING  bad peak response from peer None
"

**Comment by luotinen** [comment]
This issue is still affecting me. The GUI works otherwise fine but the wallet remains stuck and the syncing does not proceed.

**Comment by luotinen** [comment]
This issue is still affecting me. The GUI works otherwise fine but the wallet remains stuck and the syncing does not proceed.

**Comment by luotinen** [comment]
There was no way to resolve this, so I removed Chia and reinstalled it. In a week it has now synced to 615,872/1,415,188.

**Comment by luotinen** [comment]
Solution: 
1. Uninstall Chia
2. Reinstall Chia

Choose a fast drive. It takes 4 days to sync on a SSD or 33 days to sync on a HDD.

The ticket may now be closed.
