### ISSUE TITLE
[Bug] Value 0 of size 0 does not fit into uint64 of size 64

### ISSUE THREAD

**Issue by Phobas** [Chia-Network/chia-blockchain#9478]
### What happened?

Hi, today during the day, twice a pop-up window appeared with this text
"Value 0 of size 0 does not fit into uint64 of size 64"
And the OK button

### Version

1.2.11

### What platform are you using?

Windows

### What ui mode are you using?

GUI

**Comment by loppefaaret** [comment]
If you could please locate your `debug.log` fom `C:\Users\<USERNAME>\.chia\mainnet\log\` and please attach it to this issue, it would give is a better chance at identifying what is happening on your system, thank you.

**Comment by Phobas** [comment]
Oh sure
[debug.log](https://github.com/Chia-Network/chia-blockchain/files/7670483/debug.log)

**Comment by Phobas** [comment]
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "chia\rpc\rpc_server.py", line 217, in safe_handle
  File "chia\rpc\rpc_server.py", line 208, in ws_api
  File "chia\rpc\wallet_rpc_api.py", line 625, in get_wallet_balance
  File "chia\pools\pool_wallet.py", line 882, in get_unconfirmed_balance
  File "chia\pools\pool_wallet.py", line 871, in get_confirmed_balance
  File "chia\util\struct_stream.py", line 21, in __new__
ValueError: Value 0 of size 0 does not fit into uint64 of size 64

**Comment by loppefaaret** [comment]
you got a handful of potential bad plots in your farm, i'd suggest you search your `debug.log` for `harvester: ERROR` and look for repeating reports of the same files - some of them seem to potentially be residing on remote locations (network shares) and might just be a result of temporary problems with the connection to shares... but you do have some that have been reported for quite a while in there

do you run any 3rd party programs, such as farmr or chiadog ?

**Comment by loppefaaret** [comment]
```
2021-12-05T05:16:44.440 wallet chia.rpc.rpc_server        : WARNING  Error while handling message: Traceback (most recent call last):
  File "chia\util\struct_stream.py", line 16, in __new__
MemoryError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "chia\rpc\rpc_server.py", line 217, in safe_handle
  File "chia\rpc\rpc_server.py", line 208, in ws_api
  File "chia\rpc\wallet_rpc_api.py", line 625, in get_wallet_balance
  File "chia\pools\pool_wallet.py", line 882, in get_unconfirmed_balance
  File "chia\pools\pool_wallet.py", line 871, in get_confirmed_balance
  File "chia\util\struct_stream.py", line 21, in __new__
ValueError: Value 0 of size 0 does not fit into uint64 of size 64
```

this is the full entry of the above error, and it is only appearing one time - i think it might be worth just ignoring this one instance of it - and revisit it if ever starts repeating

**Comment by Phobas** [comment]
No, I do not use additional software. Okay, I hope it doesn't happen again. Thank you

**Comment by emlowe** [comment]
Closing issue, was apparently a one time issue.
