### ISSUE TITLE
[Bug] Wallet restore yields error when restoring mnemonic seed with large number of CAT transactions

### ISSUE THREAD

**Issue by darkverbito** [Chia-Network/chia-blockchain#9502]
### What happened?

When a CAT wallet has more than 1000 transactions restoring from a mnemonic seed results in a timeout error (600s) displayed in the GUI.

### Version

a01b254c13f4b31c2704da732a4f8de73067511f

### What platform are you using?

macOS

### What ui mode are you using?

GUI

### Relevant log output

```shell
2021-12-07T13:34:31.991 full_node full_node_server        : WARNING  Peer surpassed rate limit 127.0.0.1, message: request_puzzle_solution, port 57226 but not disconnecting

2021-12-07T13:34:41.573 daemon __main__                   : INFO     Websocket exception. Closing websocket with chia_wallet code = 1006 (connection closed abnormally [internal]), no reason Traceback (most recent call last):
  File "/Volumes/chia/Development/chia-blockchain-cat/venv/lib/python3.9/site-packages/websockets/protocol.py", line 827, in transfer_data
    message = await self.read_message()
  File "/Volumes/chia/Development/chia-blockchain-cat/venv/lib/python3.9/site-packages/websockets/protocol.py", line 895, in read_message
    frame = await self.read_data_frame(max_size=self.max_size)
  File "/Volumes/chia/Development/chia-blockchain-cat/venv/lib/python3.9/site-packages/websockets/protocol.py", line 971, in read_data_frame
    frame = await self.read_frame(max_size)
  File "/Volumes/chia/Development/chia-blockchain-cat/venv/lib/python3.9/site-packages/websockets/protocol.py", line 1047, in read_frame
    frame = await Frame.read(
  File "/Volumes/chia/Development/chia-blockchain-cat/venv/lib/python3.9/site-packages/websockets/framing.py", line 105, in read
    data = await reader(2)
  File "/usr/local/Cellar/python@3.9/3.9.6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/streams.py", line 721, in readexactly
    raise exceptions.IncompleteReadError(incomplete, n)
asyncio.exceptions.IncompleteReadError: 0 bytes read on a total of 2 expected bytes

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Volumes/chia/Development/chia-blockchain-cat/chia-blockchain-gui/packages/wallet/../../../chia/daemon/server.py", line 193, in safe_handle
    async for message in websocket:
  File "/Volumes/chia/Development/chia-blockchain-cat/venv/lib/python3.9/site-packages/websockets/protocol.py", line 439, in __aiter__
    yield await self.recv()
  File "/Volumes/chia/Development/chia-blockchain-cat/venv/lib/python3.9/site-packages/websockets/protocol.py", line 509, in recv
    await self.ensure_open()
  File "/Volumes/chia/Development/chia-blockchain-cat/venv/lib/python3.9/site-packages/websockets/protocol.py", line 803, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedError: code = 1006 (connection closed abnormally [internal]), no reason

2021-12-07T13:35:25.838 wallet wallet_server              : ERROR    Exception: , {'host': '127.0.0.1', 'port': 58444}. Traceback (most recent call last):
  File "/Volumes/chia/Development/chia-blockchain-cat/chia/server/server.py", line 562, in wrapped_coroutine
    result = await coroutine
  File "/Volumes/chia/Development/chia-blockchain-cat/chia/wallet/wallet_node_api.py", line 129, in respond_puzzle_solution
    await self.wallet_node.wallet_state_manager.puzzle_solution_received(request)
  File "/Volumes/chia/Development/chia-blockchain-cat/chia/wallet/wallet_state_manager.py", line 1147, in puzzle_solution_received
    await callback(unwrapped, action.id)
  File "/Volumes/chia/Development/chia-blockchain-cat/chia/wallet/cc_wallet/cc_wallet.py", line 342, in puzzle_solution_received
    coin_states: Optional[List[CoinState]] = await self.wallet_state_manager.get_coin_state([coin_name])
  File "/Volumes/chia/Development/chia-blockchain-cat/chia/wallet/wallet_node.py", line 480, in get_coin_state
    assert coin_state is not None
AssertionError
```

**Comment by emlowe** [comment]
What version of the node are you running for your local node? You need to run node from 1.2.11 if you run locally, as the rate limits were changed to better support the new lite wallet in 1.2.11

**Comment by darkverbito** [comment]
This is in the new CAT branch:
a01b254c13f4b31c2704da732a4f8de73067511f
protocol_and_cats_rebased

**Comment by emlowe** [comment]
Yes, you can use the wallet/GUI from that branch - but the recommendation is you do not run the node from that branch. I believe the problem you are having with the rate limit is in the node. So you should run the node itself from either 1.2.11 or main.

**Comment by emlowe** [comment]
Update from keybase chat.

This is primarily a GUI issue and probably unrelated to the local node rate limiting. After entering the mnemonic in the GUI, it eventually reaches some timeout while trying to get a response from RPCs - additionally, the RPCs data is very large. This is primarily seen if the wallet has around 1000+ CAT transactions.

Note, in this case, the user is able to use the CLI, however, the GUI continues to have issues, even if restarted after the initial sync.

**Comment by danieljperry** [comment]
Closing as this is likely fixed in the [most recent version](https://www.chia.net/downloads/). If it is still an issue, please open a new ticket.
