### ISSUE TITLE
[Bug] Lots of small CAT coins cause wallet error

### ISSUE THREAD

**Issue by darkverbito** [Chia-Network/chia-blockchain#9593]
### What happened?

If a large number of small CAT coins are sent to a wallet, it is no longer easy to send. After receiving many small coins (1-10 CAT) the following error occurs:

Error: Can't send more than 6611 in a single transaction

It is extremely onerous to determine what is happening as there is no way to list the coins in the wallet.

### Version

1.2.11.dev248

### What platform are you using?

macOS

### What ui mode are you using?

GUI

### Relevant log output

```shell
2021-12-16T13:54:00.827 wallet chia.rpc.rpc_server        : WARNING  Error while handling message: Traceback (most recent call last):
  File "/Volumes/chia/Development/chia-blockchain-cat/chia/rpc/rpc_server.py", line 217, in safe_handle
    response = await self.ws_api(message)
  File "/Volumes/chia/Development/chia-blockchain-cat/chia/rpc/rpc_server.py", line 208, in ws_api
    return await f(data)
  File "/Volumes/chia/Development/chia-blockchain-cat/chia/rpc/wallet_rpc_api.py", line 801, in cc_spend
    txs: List[TransactionRecord] = await wallet.generate_signed_transaction(
  File "/Volumes/chia/Development/chia-blockchain-cat/chia/wallet/cc_wallet/cc_wallet.py", line 719, in generate_signed_transaction
    raise ValueError(f"Can't send more than {max_send} in a single transaction")
ValueError: Can't send more than 6611 in a single transaction

The following error was additionally seen in the log

2021-12-16T13:51:10.385 wallet chia.wallet.wallet_node    : WARNING  SpendBundle has been rejected by the FullNode. {'error': 'GENERATOR_RUNTIME_ERROR',
 'status': 3,
 'txid': '0x43cf0cf8ec7456af522119f52465bcc6a3d1d64087c15caef8d40bc680082df8'}
```

**Comment by emlowe** [comment]
Yes, this is a gap in the way we present the coins set model to users that we haven't quite gotten right yet.
You can have 1 XCH in one coin of 1 trillion mojos, or 1 XCH in a trillion coins of 1 mojo. Sending the former is straightforward, sending the latter is more complicated.

**Comment by darkverbito** [comment]
So is this not going to be fixed or was it fixed already?
