### ISSUE TITLE
A process in the process pool was terminated abruptly while the future was running or pending.

### ISSUE THREAD

**Issue by ryu007za** [Chia-Network/chia-blockchain#9667]
### Discussed in https://github.com/Chia-Network/chia-blockchain/discussions/9659

<div type='discussions-op-text'>

<sup>Originally posted by **ryu007za** December 23, 2021</sup>
Chia Lost Sync after this error occurred.... never occurred before... Happened top anyone else?
Just randomly errors out and had to restart chia.

Log Snippet:

2021-12-22T19:49:48.529 full_node full_node_server        : ERROR    Exception: A process in the process pool was terminated abruptly while the future was running or pending., {'host': '126.93.75.181', 'port': 8444}. Traceback (most recent call last):
  File "chia\server\server.py", line 566, in wrapped_coroutine
  File "chia\full_node\full_node_api.py", line 461, in respond_unfinished_block
  File "chia\full_node\full_node.py", line 1608, in respond_unfinished_block
  File "chia\consensus\blockchain.py", line 655, in run_generator
concurrent.futures.process.BrokenProcessPool: A process in the process pool was terminated abruptly while the future was running or pending.

2021-12-22T19:49:48.531 full_node full_node_server        : ERROR    Exception: A process in the process pool was terminated abruptly while the future was running or pending. <class 'concurrent.futures.process.BrokenProcessPool'>, closing connection {'host': '126.93.75.181', 'port': 8444}. Traceback (most recent call last):
  File "chia\server\server.py", line 576, in api_call
  File "asyncio\tasks.py", line 481, in wait_for
  File "chia\server\server.py", line 573, in wrapped_coroutine
  File "chia\server\server.py", line 566, in wrapped_coroutine
  File "chia\full_node\full_node_api.py", line 461, in respond_unfinished_block
  File "chia\full_node\full_node.py", line 1608, in respond_unfinished_block
  File "chia\consensus\blockchain.py", line 655, in run_generator
concurrent.futures.process.BrokenProcessPool: A process in the process pool was terminated abruptly while the future was running or pending.

2021-12-22T19:49:48.987 full_node full_node_server        : INFO     Connection closed: 126.93.75.181, node id: f8388b664f54dcb51c59b7b5060f46c84f2e327a4382b90a118c504efd70ce50
2021-12-22T19:49:48.988 full_node full_node_server        : WARNING  Banning 126.93.75.181 for 10 seconds
2021-12-22T19:49:48.989 full_node chia.full_node.full_node: INFO     peer disconnected {'host': '126.93.75.181', 'port': 8444}
2021-12-22T19:49:49.368 full_node chia.full_node.full_node: INFO       Finished signage point 56/64: CC: d8c48f7f049ad6c800861f5711442537179aa627a8d754143dab8de489d184f9 RC: cb9b6cae2d4dc3de0449839b28f4b2a3c176fc9f8da4bcfaa3607d6313d0b04a 
2021-12-22T19:49:49.612 harvester chia.harvester.harvester: INFO     3 plots were eligible for farming e5333174fd... Found 0 proofs. Time: 0.24105 s. Total 1370 plots
2021-12-22T19:49:56.175 full_node full_node_server        : ERROR    Exception: A child process terminated abruptly, the process pool is not usable anymore, {'host': '80.128.152.68', 'port': 8444}. Traceback (most recent call last):
  File "chia\server\server.py", line 566, in wrapped_coroutine
  File "chia\full_node\full_node_api.py", line 461, in respond_unfinished_block
  File "chia\full_node\full_node.py", line 1608, in respond_unfinished_block
  File "chia\consensus\blockchain.py", line 648, in run_generator
  File "asyncio\base_events.py", line 814, in run_in_executor
  File "concurrent\futures\process.py", line 681, in submit
concurrent.futures.process.BrokenProcessPool: A child process terminated abruptly, the process pool is not usable anymore

2021-12-22T19:49:56.177 full_node full_node_server        : ERROR    Exception: A child process terminated abruptly, the process pool is not usable anymore <class 'concurrent.futures.process.BrokenProcessPool'>, closing connection {'host': '80.128.152.68', 'port': 8444}. Traceback (most recent call last):
  File "chia\server\server.py", line 576, in api_call
  File "asyncio\tasks.py", line 481, in wait_for
  File "chia\server\server.py", line 573, in wrapped_coroutine
  File "chia\server\server.py", line 566, in wrapped_coroutine
  File "chia\full_node\full_node_api.py", line 461, in respond_unfinished_block
  File "chia\full_node\full_node.py", line 1608, in respond_unfinished_block
  File "chia\consensus\blockchain.py", line 648, in run_generator
  File "asyncio\base_events.py", line 814, in run_in_executor
  File "concurrent\futures\process.py", line 681, in submit
concurrent.futures.process.BrokenProcessPool: A child process terminated abruptly, the process pool is not usable anymore</div>

**Comment by ryu007za** [comment]
This has now occurred a second time, and its only since the latest release thhis is happening

**Comment by brause** [comment]
are you out of memory ? or is your computer maxed out ? Linux for example starts killing processes if you are over capacity.

**Comment by ryu007za** [comment]
I will monitor it. Im on windows. But been running the same config since June and this has only occurred now.

**Comment by HVNC1** [comment]
у меня ьоже ета проблема.появилась после изменения времени опроса плотов

**Comment by HVNC1** [comment]
![image](https://user-images.githubusercontent.com/95166695/150883396-d889f062-6c8e-4ba6-b812-2f885795a1fa.png)
