### ISSUE TITLE
Chia Wallet Does Not Start - Error None failed with error: unknown_command get_key_for_fingerprint [Bug] 

### ISSUE THREAD

**Issue by XiaoHeitu** [Chia-Network/chia-blockchain#9690]
### What happened?

Describe the bug

Updated to 1.2.11, previously everything was working fine
Chia Start Wallet will start node, but wallet throws error:

2021-12-29T12:59:48.862 wallet chia.wallet.wallet_node    : ERROR    None failed with error: unknown_command get_key_for_fingerprint

To Reproduce

Upgrade to 1.2.11
CLI command: chia start wallet
**

OS: Ubunto 20.04 LTS

### Version

1.2.11

### What platform are you using?

Linux

### What ui mode are you using?

CLI

### Relevant log output

```shell
2021-12-29T12:32:49.956 timelord chia.timelord.timelord   : WARNING  Too late to infuse block
2021-12-29T12:33:10.016 daemon chia.daemon.server         : ERROR    UK>> {'ack': False, 'command': 'get_key_for_fingerprint', 'data': {'fingerprint': None}, 'destination': 'daemon', 'origin': 'client', 'request_id': '5eb32214c359ec3b0c9c0e8660bd26fa728fbe8247628d538354350b460f2616'}
2021-12-29T12:33:10.017 wallet chia.wallet.wallet_node    : ERROR    None failed with error: unknown_command get_key_for_fingerprint
2021-12-29T12:59:48.687 daemon chia.daemon.server         : ERROR    UK>> {'ack': False, 'command': 'get_all_private_keys', 'data': {}, 'destination': 'daemon', 'origin': 'client', 'request_id': 'e04b112b74f3bb89bd3c75ba0463f02a7db47d2a9754ff75a091677043ec1cf7'}
2021-12-29T12:59:48.688 farmer chia.farmer.farmer         : ERROR    None failed with error: unknown_command get_all_private_keys
2021-12-29T12:59:48.862 daemon chia.daemon.server         : ERROR    UK>> {'ack': False, 'command': 'get_key_for_fingerprint', 'data': {'fingerprint': None}, 'destination': 'daemon', 'origin': 'client', 'request_id': '6bb13fee4f03504f03de82e346a370672e41c762a7c4d319938ef1c618fd656f'}
2021-12-29T12:59:48.862 wallet chia.wallet.wallet_node    : ERROR    None failed with error: unknown_command get_key_for_fingerprint
2021-12-29T13:01:42.254 full_node full_node_server        : ERROR    Exception: Error short batch syncing, invalid/no response for 1345397-1345411, {'host': '50.72.103.48', 'port': 8444}. Traceback (most recent call last):
  File "/root/gits/chia-blockchain/chia/server/server.py", line 566, in wrapped_coroutine
    result = await coroutine
  File "/root/gits/chia-blockchain/chia/full_node/full_node_api.py", line 124, in new_peak
    return await self.full_node.new_peak(request, peer)
  File "/root/gits/chia-blockchain/chia/full_node/full_node.py", line 522, in new_peak
    if await self.short_sync_batch(peer, uint32(max(curr_peak_height - 6, 0)), request.height):
  File "/root/gits/chia-blockchain/chia/full_node/full_node.py", line 392, in short_sync_batch
    raise e
  File "/root/gits/chia-blockchain/chia/full_node/full_node.py", line 364, in short_sync_batch
    raise ValueError(f"Error short batch syncing, invalid/no response for {height}-{end_height}")
ValueError: Error short batch syncing, invalid/no response for 1345397-1345411

2021-12-29T13:01:42.255 full_node full_node_server        : ERROR    Exception: Error short batch syncing, invalid/no response for 1345397-1345411 <class 'ValueError'>, closing connection {'host': '50.72.103.48', 'port': 8444}. Traceback (most recent call last):
  File "/root/gits/chia-blockchain/chia/server/server.py", line 576, in api_call
    response: Optional[Message] = await asyncio.wait_for(wrapped_coroutine(), timeout=timeout)
  File "/usr/lib/python3.8/asyncio/tasks.py", line 455, in wait_for
    return await fut
  File "/root/gits/chia-blockchain/chia/server/server.py", line 573, in wrapped_coroutine
    raise e
  File "/root/gits/chia-blockchain/chia/server/server.py", line 566, in wrapped_coroutine
    result = await coroutine
  File "/root/gits/chia-blockchain/chia/full_node/full_node_api.py", line 124, in new_peak
    return await self.full_node.new_peak(request, peer)
  File "/root/gits/chia-blockchain/chia/full_node/full_node.py", line 522, in new_peak
    if await self.short_sync_batch(peer, uint32(max(curr_peak_height - 6, 0)), request.height):
  File "/root/gits/chia-blockchain/chia/full_node/full_node.py", line 392, in short_sync_batch
    raise e
  File "/root/gits/chia-blockchain/chia/full_node/full_node.py", line 364, in short_sync_batch
    raise ValueError(f"Error short batch syncing, invalid/no response for {height}-{end_height}")
ValueError: Error short batch syncing, invalid/no response for 1345397-1345411

2021-12-29T13:01:52.257 full_node full_node_server        : WARNING  Banning 50.72.103.48 for 10 seconds
2021-12-29T13:09:29.929 full_node full_node_server        : WARNING  Cannot write to closing transport 89.80.103.255
```

**Comment by emlowe** [comment]
This is likely caused by some running chia processes that are a different version - easiest here is to reboot

**Comment by XiaoHeitu** [comment]
> 

看起来不一定是这个问题，我在没重启的情况下，将版本降低至1.2.9 后，可以正常运行。
