### ISSUE TITLE
Error cannot convert 'NoneType' object to bytes [Bug] 

### ISSUE THREAD

**Issue by we-akri** [Chia-Network/chia-blockchain#9766]
### What happened?

i am trying to change Self Pooling to pool and give me Error
cannot convert 'NoneType' object to bytes
screenshot 
https://piccy.info/view3/15199708/5b4312d9121828016f29da92ddb6ba0d/
https://piccy.info/view3/15199710/5018812814f6360799f8d3ad05792046/

### Version

1.2.1299

### What platform are you using?

Windows

### What ui mode are you using?

GUI

### Relevant log output

```shell
2022-01-09T13:54:47.257 full_node chia.full_node.full_node: WARNING  Block validation time: 2.75 seconds, pre_validation time: 0.84 seconds, cost: 144814511, percent full: 1.316%
2022-01-09T13:55:02.309 wallet chia.rpc.rpc_server        : WARNING  Error while handling message: Traceback (most recent call last):
  File "chia\util\type_checking.py", line 72, in parse_item
  File "chia\util\byte_types.py", line 25, in __new__
TypeError: cannot convert 'NoneType' object to bytes

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "chia\util\type_checking.py", line 75, in parse_item
  File "chia\util\byte_types.py", line 43, in from_bytes
  File "chia\util\byte_types.py", line 33, in parse
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "chia\util\type_checking.py", line 93, in __post_init__
  File "chia\util\type_checking.py", line 77, in parse_item
TypeError: cannot convert 'NoneType' object to bytes

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "chia\util\type_checking.py", line 72, in parse_item
  File "chia\util\byte_types.py", line 25, in __new__
TypeError: cannot convert 'NoneType' object to bytes

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "chia\util\type_checking.py", line 75, in parse_item
  File "chia\util\byte_types.py", line 43, in from_bytes
  File "chia\util\byte_types.py", line 33, in parse
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "chia\rpc\rpc_server.py", line 215, in safe_handle
  File "chia\rpc\rpc_server.py", line 206, in ws_api
  File "chia\rpc\wallet_rpc_api.py", line 1216, in pw_join_pool
  File "chia\pools\pool_wallet_info.py", line 93, in create_pool_state
  File "<string>", line 9, in __init__
  File "chia\util\type_checking.py", line 96, in __post_init__
  File "chia\util\type_checking.py", line 77, in parse_item
TypeError: cannot convert 'NoneType' object to bytes

2022-01-09T13:55:18.257 full_node chia.full_node.full_node: WARNING  Block validation time: 3.03 seconds, pre_validation time: 0.74 seconds, cost: 38148760, percent full: 0.347%
2022-01-09T13:56:08.742 full_node chia.full_node.full_node: WARNING  Block validation time: 7.90 seconds, pre_validation time: 1.83 seconds, cost: 416871644, percent full: 3.79%
```

**Comment by mariano54** [comment]
Are you using python 3.10? Did you activate the venv?

**Comment by we-akri** [comment]
I did not install python on my windows machine
