### ISSUE TITLE
[Bug] Plotting issue

### ISSUE THREAD

**Issue by djlochin** [Chia-Network/chia-blockchain#9769]
### What happened?

While creating plot we have faced with a problem, could someone guide us what is wrong with it and how to get obstacles.... we can't create proceed once it reaches to 6% then we have this outcome (here I have enclosed)

Would really appreciate for help in advance

### Version

1.2.11

### What platform are you using?

Windows

### What ui mode are you using?

GUI

### Relevant log output

```shell
Starting plotting progress into temporary dirs: C:\ and C:\
ID: d6d9e2463dadb367b58283c6edb50a349940a27234a388c50e08aa5644209f6d
Plot size is: 32
Buffer size is: 3390MiB
Using 128 buckets
Final Directory is: D:\
Using 2 threads of stripe size 65536
Process ID is: 1912

Starting phase 1/4: Forward Propagation into tmp files... Mon Jan 10 08:12:31 2022
Computing table 1
Progress update: 0.01
F1 complete, time: 241.938 seconds. CPU (80.5%) Mon Jan 10 08:16:33 2022
Computing table 2
Progress update: 0.06
Caught plotting error: bad allocation
Traceback (most recent call last):
  File "Lib\site-packages\chia\cmds\chia.py", line 134, in <module>
  File "Lib\site-packages\chia\cmds\chia.py", line 130, in main
  File "click\core.py", line 829, in call
  File "click\core.py", line 782, in main
  File "click\core.py", line 1259, in invoke
  File "click\core.py", line 1066, in invoke
  File "click\core.py", line 610, in invoke
  File "click\decorators.py", line 21, in new_func
  File "chia\cmds\plotters.py", line 14, in plotters_cmd
  File "chia\plotters\plotters.py", line 346, in call_plotters
  File "chia\plotters\chiapos.py", line 57, in plot_chia
  File "asyncio\base_events.py", line 642, in run_until_complete
  File "chia\plotting\create_plots.py", line 250, in create_plots
RuntimeError: bad allocation
[1912] Failed to execute script 'chia' due to unhandled exception!
```

**Comment by emlowe** [comment]
It is an out of memory error - you don't have enough memory to perform the task. You should reduce your buffer size
