### ISSUE TITLE
[Bug] standalone wallet stuck in Syncing after importing old private key

### ISSUE THREAD

**Issue by ctrlaltdel** [Chia-Network/chia-blockchain#9784]
### What happened?

I've imported an old private key into the standalone wallet which then stayed stuck in Syncing for the last hours or so.

It looks like validation fails with each peers with the following exception.

```
  File "chia/wallet/wallet_node.py", line 714, in new_peak_wallet
  File "chia/wallet/wallet_node.py", line 1035, in untrusted_sync_to_peer
  File "chia/wallet/wallet_node.py", line 1002, in untrusted_subscribe_to_puzzle_hashes
  File "chia/wallet/wallet_node.py", line 1174, in validate_received_state_from_peer
  File "chia/wallet/wallet_node.py", line 1259, in validate_state
IndexError: list index out of range
```

```bash
$ grep "Error syncing to" debug.log 
2022-01-11T21:06:38.481 wallet chia.wallet.wallet_node    : ERROR    Error syncing to {'host': '82.40.141.102', 'port': 8444} Traceback (most recent call last):
2022-01-11T21:16:58.793 wallet chia.wallet.wallet_node    : ERROR    Error syncing to {'host': '47.25.94.11', 'port': 8444} Traceback (most recent call last):
2022-01-11T21:21:58.192 wallet chia.wallet.wallet_node    : ERROR    Error syncing to {'host': '151.229.178.2', 'port': 8444} Traceback (most recent call last):
2022-01-11T21:28:20.455 wallet chia.wallet.wallet_node    : ERROR    Error syncing to {'host': '102.32.54.197', 'port': 8444} Traceback (most recent call last):
2022-01-11T21:39:20.177 wallet chia.wallet.wallet_node    : ERROR    Error syncing to {'host': '145.82.192.101', 'port': 8444} Traceback (most recent call last):
2022-01-11T21:43:45.831 wallet chia.wallet.wallet_node    : ERROR    Error syncing to {'host': '94.114.218.114', 'port': 8444} Traceback (most recent call last):
2022-01-11T21:45:36.991 wallet chia.wallet.wallet_node    : ERROR    Error syncing to {'host': '218.68.251.170', 'port': 8444} Traceback (most recent call last):
2022-01-11T21:51:06.107 wallet chia.wallet.wallet_node    : ERROR    Error syncing to {'host': '212.40.90.120', 'port': 8444} Traceback (most recent call last):
2022-01-11T22:02:31.673 wallet chia.wallet.wallet_node    : ERROR    Error syncing to {'host': '85.73.38.58', 'port': 8444} Traceback (most recent call last):
2022-01-11T22:07:31.727 wallet chia.wallet.wallet_node    : ERROR    Error syncing to {'host': '77.56.189.119', 'port': 8444} Traceback (most recent call last):
2022-01-11T22:19:44.766 wallet chia.wallet.wallet_node    : ERROR    Error syncing to {'host': '145.82.192.101', 'port': 8444} Traceback (most recent call last):
2022-01-11T22:20:52.984 wallet chia.wallet.wallet_node    : ERROR    Error syncing to {'host': '91.13.137.248', 'port': 8444} Traceback (most recent call last):
2022-01-11T22:24:15.209 wallet chia.wallet.wallet_node    : ERROR    Error syncing to {'host': '77.56.189.119', 'port': 8444} Traceback (most recent call last):
2022-01-11T22:26:03.262 wallet chia.wallet.wallet_node    : ERROR    Error syncing to {'host': '212.40.90.120', 'port': 8444} Traceback (most recent call last):
2022-01-11T22:50:50.038 wallet chia.wallet.wallet_node    : ERROR    Error syncing to {'host': '47.25.94.11', 'port': 8444} Traceback (most recent call last):
2022-01-11T22:53:43.557 wallet chia.wallet.wallet_node    : ERROR    Error syncing to {'host': '70.88.76.97', 'port': 8444} Traceback (most recent call last):
2022-01-11T22:58:26.711 wallet chia.wallet.wallet_node    : ERROR    Error syncing to {'host': '95.32.123.41', 'port': 8444} Traceback (most recent call last):
2022-01-11T23:00:27.538 wallet chia.wallet.wallet_node    : ERROR    Error syncing to {'host': '73.137.19.29', 'port': 8444} Traceback (most recent call last):
2022-01-11T23:05:19.495 wallet chia.wallet.wallet_node    : ERROR    Error syncing to {'host': '91.122.12.128', 'port': 8444} Traceback (most recent call last):
2022-01-11T23:08:41.500 wallet chia.wallet.wallet_node    : ERROR    Error syncing to {'host': '77.56.189.119', 'port': 8444} Traceback (most recent call last):
```

### Version

Beta standalone wallet 1.2.11.dev254

### What platform are you using?

Linux

### What ui mode are you using?

GUI

### Relevant log output

```shell
2022-01-11T22:58:19.259 wallet chia.wallet.wallet_node    : INFO     Validating 48 of 152
2022-01-11T22:58:20.014 wallet chia.wallet.wallet_node    : INFO     Fetching blocks: 8448 - 8479
2022-01-11T22:58:20.341 wallet chia.wallet.wallet_node    : INFO     Fetching blocks: 8480 - 8511
2022-01-11T22:58:20.682 wallet chia.wallet.wallet_node    : INFO     Fetching blocks: 8512 - 8543
2022-01-11T22:58:21.051 wallet chia.wallet.wallet_node    : INFO     Fetching blocks: 8544 - 8575
2022-01-11T22:58:21.390 wallet chia.wallet.wallet_node    : INFO     Fetching blocks: 8576 - 8607
2022-01-11T22:58:22.683 wallet chia.wallet.wallet_node    : INFO     Fetching blocks: 8608 - 8639
2022-01-11T22:58:23.469 wallet chia.wallet.wallet_node    : INFO     Fetching blocks: 8640 - 8671
2022-01-11T22:58:23.900 wallet chia.wallet.wallet_node    : INFO     Fetching blocks: 8672 - 8703
2022-01-11T22:58:24.325 wallet chia.wallet.wallet_node    : INFO     Fetching blocks: 8704 - 8735
2022-01-11T22:58:24.668 wallet chia.wallet.wallet_node    : INFO     Fetching blocks: 8736 - 8767
2022-01-11T22:58:25.143 wallet chia.wallet.wallet_node    : INFO     Fetching blocks: 8768 - 8799
2022-01-11T22:58:25.545 wallet chia.wallet.wallet_node    : INFO     Fetching blocks: 8800 - 8831
2022-01-11T22:58:25.758 wallet chia.wallet.wallet_node    : INFO     Fetching blocks: 8832 - 8847
2022-01-11T22:58:26.193 wallet chia.wallet.wallet_node    : INFO     Fetching blocks: 289856 - 289887
2022-01-11T22:58:26.193 wallet chia.wallet.wallet_node    : INFO     Fetching blocks: 289888 - 289919
2022-01-11T22:58:26.194 wallet chia.wallet.wallet_node    : INFO     Fetching blocks: 289920 - 289937
2022-01-11T22:58:26.356 wallet chia.wallet.wallet_node    : INFO     Validating 49 of 152
2022-01-11T22:58:26.711 wallet chia.wallet.wallet_node    : ERROR    Error syncing to {'host': '95.32.123.41', 'port': 8444} Traceback (most recent call last):
  File "chia/wallet/wallet_node.py", line 714, in new_peak_wallet
  File "chia/wallet/wallet_node.py", line 1035, in untrusted_sync_to_peer
  File "chia/wallet/wallet_node.py", line 1002, in untrusted_subscribe_to_puzzle_hashes
  File "chia/wallet/wallet_node.py", line 1174, in validate_received_state_from_peer
  File "chia/wallet/wallet_node.py", line 1259, in validate_state
IndexError: list index out of range

[...]

2022-01-11T23:00:27.023 wallet chia.wallet.wallet_node    : INFO     Validating 20 of 152
2022-01-11T23:00:27.538 wallet chia.wallet.wallet_node    : ERROR    Error syncing to {'host': '73.137.19.29', 'port': 8444} Traceback (most recent call last):
  File "chia/wallet/wallet_node.py", line 714, in new_peak_wallet
  File "chia/wallet/wallet_node.py", line 1035, in untrusted_sync_to_peer
  File "chia/wallet/wallet_node.py", line 1002, in untrusted_subscribe_to_puzzle_hashes
  File "chia/wallet/wallet_node.py", line 1174, in validate_received_state_from_peer
  File "chia/wallet/wallet_node.py", line 1259, in validate_state
IndexError: list index out of range
```

**Comment by mariano54** [comment]
@Yostra

**Comment by mariano54** [comment]
Maybe it's one of these:
```python
                ses_0 = res_ses.reward_chain_hash[0]
                last_height = res_ses.heights[0][-1]  # Last height in sub epoch
```

**Comment by Seifollahy** [comment]
9784

**Comment by ctrlaltdel** [comment]
After the upgrade to Chia Wallet Beta 1.2.11.dev265, issue is still present.

**Comment by ctrlaltdel** [comment]
> Maybe it's one of these:
> 
> ```python
>                 ses_0 = res_ses.reward_chain_hash[0]
>                 last_height = res_ses.heights[0][-1]  # Last height in sub epoch
> ```

It's the first line.

Here's what I get with a fresh checkout of of the `protocol_and_cats_rebased` branch with additional logging of the `res_res` variable.

```
2022-01-13T08:32:46.617 wallet chia.wallet.wallet_node    : INFO     Validating 59 of 152
2022-01-13T08:32:46.959 wallet chia.wallet.wallet_node    : INFO     {'heights': [], 'reward_chain_hash': []}
2022-01-13T08:32:46.960 wallet chia.wallet.wallet_node    : ERROR    Error syncing to {'host': '96.237.100.77', 'port': 8444} Traceback (most recent call last):
  File "/home/user/chia-blockchain/chia/wallet/wallet_node.py", line 728, in new_peak_wallet
    await self.untrusted_sync_to_peer(peer, weight_proof, syncing, fork_point)
  File "/home/user/chia-blockchain/chia/wallet/wallet_node.py", line 1056, in untrusted_sync_to_peer
    await self.untrusted_subscribe_to_puzzle_hashes(peer, True, peer_request_cache, weight_proof)
  File "/home/user/chia-blockchain/chia/wallet/wallet_node.py", line 1018, in untrusted_subscribe_to_puzzle_hashes
    validated_state = await self.validate_received_state_from_peer(
  File "/home/user/chia-blockchain/chia/wallet/wallet_node.py", line 1196, in validate_received_state_from_peer
    validated = await self.validate_state(weight_proof, state_block, peer, peer_request_cache)
  File "/home/user/chia-blockchain/chia/wallet/wallet_node.py", line 1282, in validate_state
    ses_0 = res_ses.reward_chain_hash[0]
IndexError: list index out of range
```

**Comment by Birger78** [comment]
Same errors here, not possible to sync. Validation starts over and over again.

Validating 224 of 297
2022-01-14T07:35:38.834 wallet chia.wallet.wallet_node    : ERROR    Error syncing to {'host': '91.192.36.102', 'port': 8444} Traceback (most recent call last):
  File "/Users/user/protocol_and_cats_rebased/chia-blockchain/chia/wallet/wallet_node.py", line 726, in new_peak_wallet
    await self.untrusted_sync_to_peer(peer, weight_proof, syncing, fork_point)
  File "/Users/user/protocol_and_cats_rebased/chia-blockchain/chia/wallet/wallet_node.py", line 1055, in untrusted_sync_to_peer
    await self.untrusted_subscribe_to_puzzle_hashes(peer, True, peer_request_cache, weight_proof)
  File "/Users/user/protocol_and_cats_rebased/chia-blockchain/chia/wallet/wallet_node.py", line 1017, in untrusted_subscribe_to_puzzle_hashes
    validated_state = await self.validate_received_state_from_peer(
  File "/Users/user/protocol_and_cats_rebased/chia-blockchain/chia/wallet/wallet_node.py", line 1194, in validate_received_state_from_peer
    validated = await self.validate_state(weight_proof, state_block, peer, peer_request_cache)
  File "/Users/user/protocol_and_cats_rebased/chia-blockchain/chia/wallet/wallet_node.py", line 1279, in validate_state
    ses_0 = res_ses.reward_chain_hash[0]
IndexError: list index out of range

**Comment by vctrb** [comment]
Here's my 2 mojos, using win:

2022-01-16T15:20:15.973 wallet wallet_server              : DEBUG    -> request_header_blocks to peer 193.77.70.219 32e4a84642c3d25f73883ce69dfcce85adbad48702c3e513995f2804fe852ec6
2022-01-16T15:20:16.057 wallet wallet_server              : DEBUG    <- respond_header_blocks from: 193.77.70.219:8444
2022-01-16T15:20:16.057 wallet wallet_server              : DEBUG    Time for request request_header_blocks: {'host': '193.77.70.219', 'port': 8444} = 0.08361482620239258, None? False
2022-01-16T15:20:16.057 wallet wallet_server              : DEBUG    -> request_additions to peer 193.77.70.219 32e4a84642c3d25f73883ce69dfcce85adbad48702c3e513995f2804fe852ec6
2022-01-16T15:20:16.133 wallet wallet_server              : DEBUG    <- respond_additions from: 193.77.70.219:8444
2022-01-16T15:20:16.133 wallet wallet_server              : DEBUG    Time for request request_additions: {'host': '193.77.70.219', 'port': 8444} = 0.07636523246765137, None? False
2022-01-16T15:20:16.133 wallet wallet_server              : DEBUG    -> request_ses_hashes to peer 193.77.70.219 32e4a84642c3d25f73883ce69dfcce85adbad48702c3e513995f2804fe852ec6
2022-01-16T15:20:16.210 wallet wallet_server              : DEBUG    <- respond_ses_hashes from: 193.77.70.219:8444
2022-01-16T15:20:16.210 wallet wallet_server              : DEBUG    Time for request request_ses_hashes: {'host': '193.77.70.219', 'port': 8444} = 0.07691788673400879, None? False
2022-01-16T15:20:16.218 wallet chia.wallet.wallet_node    : ERROR    Error syncing to {'host': '193.77.70.219', 'port': 8444} Traceback (most recent call last):
  File "chia\wallet\wallet_node.py", line 726, in new_peak_wallet
  File "chia\wallet\wallet_node.py", line 1055, in untrusted_sync_to_peer
  File "chia\wallet\wallet_node.py", line 1017, in untrusted_subscribe_to_puzzle_hashes
  File "chia\wallet\wallet_node.py", line 1194, in validate_received_state_from_peer
  File "chia\wallet\wallet_node.py", line 1279, in validate_state
IndexError: list index out of range

2022-01-16T15:20:16.218 wallet wallet_server              : DEBUG    Inbound_handler task cancelled

**Comment by Birger78** [comment]
When debugging "res" from

request = RequestHeaderBlocks(confirmed_height, confirmed_height)
res = await peer.request_header_blocks(request)

in wallet_node.py

for block with start_height and end_height **129** the RespondSESInfo from validation is always empty.

My custom debug outputs:

Header blocks requested {'end_height': 129,
 'header_blocks': [{'challenge_chain_ip_proof': {'normalized_to_identity': True,
                                                 'witness': '0x010038a449943d13aa49a4d8052fb10f7f4193f87491c232d6b450ad7d89bd55681503d1685739d4f0d2875f0a2480fccd9282e2c3ea9ff83fbb7de863f8c195810f91d67a7fa3df31300b1c5034bc016320254e0a6461523d552d34597973d3a3190301',
                                                 'witness_type': 0},
                    'challenge_chain_sp_proof': {'normalized_to_identity': True,
                                                 'witness': '0x0300f5fabcbbc4092e1834ac2ea206404bd6dd7993208f61e3aef96fc4735d7ef48f071b268e72f88cbfa2e52c6d8420004e10dc860143697615718cb530667ec41f858de5e06042d48a031a495e59911ec91862ad4b2642d741be3bf83a990173080100',
                                                 'witness_type': 0},
                    'finished_sub_slots': [],
                    'foliage': {'foliage_block_data': {'extension_data': '0x0000000000000000000000000000000000000000000000000000000003a2c7c9',
                                                       'farmer_reward_puzzle_hash': '0xf1ef1c53d9b542d58ff0b25d1ea2d133061ae20b56e85d50a7fb6b70ab2341e3',
                                                       'pool_signature': '0x91bdd75a487df98a4247a1f6a0b189011ce9ada57186d9ecfa87679543e346bac5bbd08472025675a2f1424fa10851fc1737d964041794694949b8ada9f31d970279e34d254e2e528300fb1af23a4779be4e6ed8df0fd66ca12141caad98a411',
                                                       'pool_target': {'max_height': 0,
                                                                       'puzzle_hash': '0xf1ef1c53d9b542d58ff0b25d1ea2d133061ae20b56e85d50a7fb6b70ab2341e3'},
                                                       'unfinished_reward_block_hash': '0x26f519392c156c5117409ebce8fcb7ca1c9ed9fa551c30184013db57c44745d6'},
                                'foliage_block_data_signature': '0x99ce4de84f4f24035a980c0e114ea109dbb444e439ab4f718c0145d0140b6b4fd1a8a8c89acede49d7235fcc6516a6a110e037e7c52d0cd4ea19db1d09c4974539ba6da1ca8653eeaf9536d6c0baf161efe7c6702b3b9a83e355254022340b9f',
                                'foliage_transaction_block_hash': '0xaf72faa9bc549dca6487d671b60468114f20ada0309616d8ec9b1bd6af4f3e25',
                                'foliage_transaction_block_signature': '0xb2516a3ca7ddf5578fa65bde71c047005b64c83a613ba91d144bfb4304d681cb471082b5c4654f3d3b24497da90c28c21899d6d5c55f4993d0c7e7a4daa6084b1989e6196ac16f9b5173d3f4652bad385473e362a82d10e39a78c2d49ec21c03',
                                'prev_block_hash': '0x908d3177e8f51578aec00606f51c160b469e753163db25165ea9e3f694ac38b9',
                                'reward_block_hash': '0x898e471a24b91df3f32c2f2fa7886ba608fbae26f2a2580cc9699ea119e16038'},
                    'foliage_transaction_block': {'additions_root': '0x370bf95b618b50e01192c24aa98c43bd804ab2309efd8a277f11d40bdc2d4c6e',
                                                  'filter_hash': '0x2634196aa7e2bbbdcc30506190e1f5ac0b4f2b428418af9573fdba9cd1ccd08f',
                                                  'prev_transaction_block_hash': '0xffcf920f06a2c811a03ec221659b4ac32f284151871eb32c235efefd9b136f8a',
                                                  'removals_root': '0x0000000000000000000000000000000000000000000000000000000000000000',
                                                  'timestamp': 1616165213,
                                                  'transactions_info_hash': '0xeb3178891c8e6ed2998139d3926f9fdb87e420b58f26d6201e062793e509d92e'},
                    'infused_challenge_chain_ip_proof': {'normalized_to_identity': False,
                                                         'witness': '0x0100f1c30eb43cba33261e3ebe78162ff93733178b4ff7fc428e0d6f59cda2389cdb7c23906ca172fe3088ce67c20267bb186cd9765d79492a1c0872742ef69c6f073715829051a654e53e63631da686d56bc0e32e95d7b2bfe8360d95afc7bada0001000000000000182860f392fa238851cf353df12fa940f3a233c3620f9d87c809b04191286afc1c019f010100ed24d7b7fc44cab08b06fc687ac65226aecd968f0ca8fb049ff02f131815179c6f82761cb5e7a47035300ce8b909ba18de1aa810b5c51d082a610cd5ea6a0c3d49cae83e0df5dc6b6c218db8c1fe13993cbd6842a272856e658c088ca954ee66010000000000004879209e74da59ab667fa79b04146ecc6e6641c360fc95485853959655c6705b9e95df330100c9637a472d8e43b4370c092e77aee4a8eea10aed913da3b307f90758b7fa19bd2f44727e086c90130fcff355fb85ac092016cd51ca5bd09df5bda1536182980933ecc28ed3b180bd21fc4cfd4a5893f99e6571fffa76bac2206c118233915f040402',
                                                         'witness_type': 2},
                    'reward_chain_block': {'challenge_chain_ip_vdf': {'challenge': '0xa5762d4e8bfdb0a0b14fb5b64f498a47585716dc6f302c4856d69d629421db6d',
                                                                      'number_of_iterations': 116059979,
                                                                      'output': {'data': '0x0300644beb007d92b2644252b0245df9b93d2357f4df7ec2baf2afc8f9ffd87dff30871d04b39bf400cea9418c76bbd88a6de52d9761fe8a69036dff94eee68a7226ad526dd9466681dc0d6ef0382ff1ebdd526dbf3ceeb528bdd19c2e7cb6d1e80d0200'}},
                                           'challenge_chain_sp_signature': '0x96c1f46416b857eaf6a15d7d0e4ef4aabff6936cf6ffe3c5d56554c6c59d7af1073ca4ad4aaf8da7fd67e3fec3fbcf2a02fc3799a24c318abbdf0037db578cc14e5617b0e3983da6df0df3e46dbe27ba17312acd7fb231f32035eac089a70c02',
                                           'challenge_chain_sp_vdf': {'challenge': '0xa5762d4e8bfdb0a0b14fb5b64f498a47585716dc6f302c4856d69d629421db6d',
                                                                      'number_of_iterations': 109051904,
                                                                      'output': {'data': '0x03007e5ae2655ff6b7aa943012b587101551d65293ce04dccedd39c63b6e14876654d6f72341e6aea9599dcbc79c5ba2f739cbef96f50462e90488bd6855b3d37917ad1676eb102008f8900144a64675c13050a0ae9c116767c8df0acb272fa0b33a0100'}},
                                           'height': 129,
                                           'infused_challenge_chain_ip_vdf': {'challenge': '0xce285a81b684e3b30425fbf829c8b3da7e96d5e3983eb84c8c2ddece98b23eb5',
                                                                              'number_of_iterations': 7124525,
                                                                              'output': {'data': '0x0300e6eb9071d25bd12bd9d0488e6b7aae3b5dd342072fa4cd0d946618d74dd258b9339234eb4f8c43ad598b9b039319bbec3f0505328503dbecdc27463e8c94c655073ece8cbb1047190e094fce5e7c8783023a500da1617705791a5e47461b3e090100'}},
                                           'is_transaction_block': True,
                                           'pos_ss_cc_challenge_hash': '0xa5762d4e8bfdb0a0b14fb5b64f498a47585716dc6f302c4856d69d629421db6d',
                                           'proof_of_space': {'challenge': '0xa00681e81afd20dfb952eaeef697c99b08e813cbf5655776017b9d1b2d943af5',
                                                              'plot_public_key': '0x891e9e28806be22c2bfa18b0cb21c0c11ca414996895f3a62cb8f4bb177d778e1d6d432dc551e42d29aa97220a80e0ae',
                                                              'pool_contract_puzzle_hash': None,
                                                              'pool_public_key': '0xb990fbe68e322c884bbaf5de71e4de884e9d5c20ad54968f10ed2e63250bfaa084a631547a334514d2e3c23fb878ba43',
                                                              'proof': '0xc041bf6d46defd24993dd8f978b5f3bb2a7d7a14d0817f7bf84610325c7ab9b60f3f730a6dd86383875d7bdf30f1eba6e0c2a3e343a74ed7e31596aa317ad565a6bd5517797069a727a5d7e88c51fe9279c3be61a7ff3195b22b04dd901892fc2c634f4fc9d791a8c977914d34ce276af62e35477540df38cc0e0422ffab82431b48cacf82e7c0f329d44baaa8fff7d11f55bae80abb80bdac8ec118408004dbecaef7935977576d9835b64af60fab72af7278d0f64ff281dc1457593a39ba768a213a6ad8b0e161d4fb61ce1fbe40646fdf4a0d4df288954eca7245ad540e7e13c49dc615bdb5f1b4ca2c5b5eb2b27e81e629258e3ee889a267c18ef43f9a1c',
                                                              'size': 32},
                                           'reward_chain_ip_vdf': {'challenge': '0xa191c94789cd729265b7fd8b4d64cc614e6186f24b3eacf1a06bc169440cf020',
                                                                   'number_of_iterations': 7124525,
                                                                   'output': {'data': '0x01004918f8f1091c832e577834f136cf8cf3153270fdd4e45e42efec3b92ae64dd66752371b98dd1153c5387a18cecd82758cc3bfcda7d413187394f9395f3ddd621a5bf6f1e322231ee0a49d47d7be0d6515436be9fc3f732e755586f9056067a030200'}},
                                           'reward_chain_sp_signature': '0x81b3244bb2a3547884884da3a4e901bb0189621bdc6cb162d177665d1f86e3bc0c5fe066d3e1ef0869f68b19b973f54a0d90bd2189dd0862554a2bff6b4d358151164ea869b0d6574ff534e86aa66f0cc95f01264fb0b981d47aa3f1f9f07f2c',
                                           'reward_chain_sp_vdf': {'challenge': '0xa191c94789cd729265b7fd8b4d64cc614e6186f24b3eacf1a06bc169440cf020',
                                                                   'number_of_iterations': 116450,
                                                                   'output': {'data': '0x0200369c4e63a19b93ffce478fcb34ced51d9be03d8f3309b679af6cc67f567b6623c31c6e07f02f2541e406e5aec4e446aa63353201c801beddb94f4000bc3eb8603130576d2214386d4670190c5647c4700a58113906108f16d3d62c4b0d48b88a0100'}},
                                           'signage_point_index': 52,
                                           'total_iters': 518713163,
                                           'weight': 910},
                    'reward_chain_ip_proof': {'normalized_to_identity': False,
                                              'witness': '0x00002c7d9b6eabec60e1007dfeb64cdd1d61b07d228f253bdb28d1d8e0a3504c095e142eb9685924927a213938b0b67a8c63e57702992d7feae801c39f5c749a5a12db5fdc2206f02428bf8712305042c39dca4ce397cc82dcc7716f9a93da3ffa1005040000000000182860e29e522a4e80194f751674452a7912819c6d65c7a007b2d9f47ed2fd57a54c20310100cd5e9455a8332b38ee5ff0100247ed4102f7acfb0ad178664fc4f697597fe5c475c3b8d70878714bd43b9c4545f92443871510fc018d84f6fa453d5eb5687d2176aec3ab14cc3b2abcab536c7971a1229c7cc6fa2e5c07597699f2d3c279512603020000000000487920dc2854d3445c72e74a8d0c8b43d794f93f85bacc4b9ea05f5cbd1663218e0b7ff50100f65a7954c577e50db33a4b1666f8b965803d243d58ea20d1cfba0a2da986748dab49641361dcc5a646bf964a65387acc8fff70a7f6310c79cf1843d4321bde380bdab432eb7d058920d33d57c12712346576796aaa4fa7ce9fb012195cf50c4f0100',
                                              'witness_type': 2},
                    'reward_chain_sp_proof': {'normalized_to_identity': False,
                                              'witness': '0x0200829322c1619d2250bcda5fde041b77e80bf7ed55938ef23cb750a18d9824f71b80fc86db88cf72dcf8ef20c6f35cf06f8ba19ebcaebba848211fc4945d88fa17fd903067155b1b35a0fea937ac039a1e7cb8b27146fd735362dd2af10529961c0201000000000000652cdbe22d6c05f1a32c71dc9837619c80cd5333baa7b12f6d32e98a1f06f27e5695c303000553160e3455d9b12f4958ac3c8d38f510689c8d78f28ce6b316edd9b958dd4bad0fc5524dba725759e9c9427c8003ef994ebdf241ae466dcbaf60f30ab9fb237f99cbc4be306d812117e77644292abd6503a11c2e3b0c1402d97fdefe90293601000000000000012f20eb7e4941dad6bf1d30ffa15a5d4f6d375a5da3f0ff2a3fe58bad6c82eccd9a78710000d9e40ac094cfe1b94ce6023e6ff8e5415a86a26d50cc973703f7ce0b6da4c316627de3756ff50b2cc3edf9c481a38f08a691e5becf6bca4e0b98798960073406524805296f4d78d45f0c57a85318793ee2b1b1ade5670515b9615ffced88c2090601',
                                              'witness_type': 2},
                    'transactions_filter': '0x05c9d42674b8a2407a2d0666261160',
                    'transactions_info': {'aggregated_signature': '0xc00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000',
                                          'cost': 0,
                                          'fees': 0,
                                          'generator_refs_root': '0x0101010101010101010101010101010101010101010101010101010101010101',
                                          'generator_root': '0x0000000000000000000000000000000000000000000000000000000000000000',
                                          'reward_claims_incorporated': [{'amount': 1750000000000,
                                                                          'parent_coin_info': '0xccd5bb71183532bff220ba46c268991a0000000000000000000000000000007f',
                                                                          'puzzle_hash': '0xc06509b61e53cfd7b2ae1c8861fc087799cd9b27798ac6a899ecc709c073d4e8'},
                                                                         {'amount': 250000000000,
                                                                          'parent_coin_info': '0x3ff07eb358e8255a65c30a2dce0e5fbb0000000000000000000000000000007f',
                                                                          'puzzle_hash': '0xc06509b61e53cfd7b2ae1c8861fc087799cd9b27798ac6a899ecc709c073d4e8'},
                                                                         {'amount': 1750000000000,
                                                                          'parent_coin_info': '0xccd5bb71183532bff220ba46c268991a0000000000000000000000000000007e',
                                                                          'puzzle_hash': '0x7d8e0e7b0c14c00bf04e10bf6cb6d27ede9ddbf240c7efdf009bb673067d75fc'},
                                                                         {'amount': 250000000000,
                                                                          'parent_coin_info': '0x3ff07eb358e8255a65c30a2dce0e5fbb0000000000000000000000000000007e',
                                                                          'puzzle_hash': '0x7d8e0e7b0c14c00bf04e10bf6cb6d27ede9ddbf240c7efdf009bb673067d75fc'},
                                                                         {'amount': 1750000000000,
                                                                          'parent_coin_info': '0xccd5bb71183532bff220ba46c268991a0000000000000000000000000000007d',
                                                                          'puzzle_hash': '0x40b8471585bdc2f77cd83640f30d97c6f0cb048ce9507a9f003af51e4a3959d4'},
                                                                         {'amount': 250000000000,
                                                                          'parent_coin_info': '0x3ff07eb358e8255a65c30a2dce0e5fbb0000000000000000000000000000007d',
                                                                          'puzzle_hash': '0x40b8471585bdc2f77cd83640f30d97c6f0cb048ce9507a9f003af51e4a3959d4'},
                                                                         {'amount': 1750000000000,
                                                                          'parent_coin_info': '0xccd5bb71183532bff220ba46c268991a0000000000000000000000000000007c',
                                                                          'puzzle_hash': '0x7ad0ccca139df97601419b18c0fd49e42d9087ffd4033c48ab7d3faf6f44ede7'},
                                                                         {'amount': 250000000000,
                                                                          'parent_coin_info': '0x3ff07eb358e8255a65c30a2dce0e5fbb0000000000000000000000000000007c',
                                                                          'puzzle_hash': '0x7ad0ccca139df97601419b18c0fd49e42d9087ffd4033c48ab7d3faf6f44ede7'},
                                                                         {'amount': 1750000000000,
                                                                          'parent_coin_info': '0xccd5bb71183532bff220ba46c268991a0000000000000000000000000000007b',
                                                                          'puzzle_hash': '0xc74f0d6c7ab5d68a76bab07e3583fbaa135c191f353abb2926a98a2a70b703ad'},
                                                                         {'amount': 250000000000,
                                                                          'parent_coin_info': '0x3ff07eb358e8255a65c30a2dce0e5fbb0000000000000000000000000000007b',
                                                                          'puzzle_hash': '0xc74f0d6c7ab5d68a76bab07e3583fbaa135c191f353abb2926a98a2a70b703ad'}]}}],
 'start_height': 129}


2022-01-16T18:30:45.829 wallet chia.wallet.wallet_node    : INFO     received RespondSESInfo from peer {'heights': [], 'reward_chain_hash': []}

With these empty arrays in the response we get 
IndexError: list index out of range

**Comment by emlowe** [comment]
This issue hasn't been reported recently, so closing issue on the assumption it was resolved at some point.
