### ISSUE TITLE
Syncing Issue [Bug] 

### ISSUE THREAD

**Issue by erickuo1978** [Chia-Network/chia-blockchain#9818]
### What happened?

**.chia\mainnet\log\debug
2022-01-15T04:20:24.588 full_node chia.full_node.full_node: ERROR    Error with syncing: <class 'RuntimeError'>Traceback (most recent call last):
  File "chia\full_node\full_node.py", line 807, in _sync
RuntimeError: Weight proof did not arrive in time from peer: 1.159.86.87

→always Syncing on1,415,860, cannot be [synchronize.[](url)]([url](url
![always Syncing](https://user-images.githubusercontent.com/83088430/149581968-fb2c44f9-8fe1-4def-825c-ca23e0a6e791.png)
))

### Version

ChiaSetup-1.2.11

### What platform are you using?

Windows

### What ui mode are you using?

GUI

### Relevant log output

```shell
2022-01-15T04:12:27.806 full_node chia.full_node.full_node: ERROR    Error with syncing: <class 'RuntimeError'>Traceback (most recent call last):
  File "chia\full_node\full_node.py", line 807, in _sync
RuntimeError: Weight proof did not arrive in time from peer: 188.2.121.170

2022-01-15T04:14:37.348 full_node chia.full_node.full_node: ERROR    Error with syncing: <class 'RuntimeError'>Traceback (most recent call last):
  File "chia\full_node\full_node.py", line 807, in _sync
RuntimeError: Weight proof did not arrive in time from peer: 73.151.132.127

2022-01-15T04:16:16.492 full_node chia.full_node.full_node: ERROR    Error with syncing: <class 'RuntimeError'>Traceback (most recent call last):
  File "chia\full_node\full_node.py", line 807, in _sync
RuntimeError: Weight proof did not arrive in time from peer: 95.105.188.255

2022-01-15T04:18:43.341 full_node chia.full_node.full_node: ERROR    Error with syncing: <class 'RuntimeError'>Traceback (most recent call last):
  File "chia\full_node\full_node.py", line 807, in _sync
RuntimeError: Weight proof did not arrive in time from peer: 121.175.23.237

2022-01-15T04:20:24.588 full_node chia.full_node.full_node: ERROR    Error with syncing: <class 'RuntimeError'>Traceback (most recent call last):
  File "chia\full_node\full_node.py", line 807, in _sync
RuntimeError: Weight proof did not arrive in time from peer: 1.159.86.87

2022-01-15T04:22:09.465 full_node chia.full_node.full_node: ERROR    Error with syncing: <class 'RuntimeError'>Traceback (most recent call last):
  File "chia\full_node\full_node.py", line 807, in _sync
RuntimeError: Weight proof did not arrive in time from peer: 104.184.33.179

2022-01-15T04:23:56.467 full_node chia.full_node.full_node: ERROR    Error with syncing: <class 'RuntimeError'>Traceback (most recent call last):
  File "chia\full_node\full_node.py", line 807, in _sync
RuntimeError: Weight proof did not arrive in time from peer: 94.231.33.145

2022-01-15T04:25:46.433 full_node chia.full_node.full_node: ERROR    Error with syncing: <class 'RuntimeError'>Traceback (most recent call last):
  File "chia\full_node\full_node.py", line 807, in _sync
RuntimeError: Weight proof did not arrive in time from peer: 65.78.13.217

2022-01-15T04:28:05.515 full_node chia.full_node.full_node: ERROR    Error with syncing: <class 'RuntimeError'>Traceback (most recent call last):
  File "chia\full_node\full_node.py", line 807, in _sync
RuntimeError: Weight proof did not arrive in time from peer: 93.118.160.236

2022-01-15T04:30:03.348 full_node chia.full_node.full_node: ERROR    Error with syncing: <class 'RuntimeError'>Traceback (most recent call last):
  File "chia\full_node\full_node.py", line 807, in _sync
RuntimeError: Weight proof did not arrive in time from peer: 83.142.104.91
```

**Comment by ramark2** [comment]
Águia também!!!
Ajuda aí galera

**Comment by navyfeng** [comment]
Same at 1.2.11
