### ISSUE TITLE
[Bug] Can't open Wallet with 24 Word Mnemonics code on Kubuntu20.04

### ISSUE THREAD

**Issue by rwwendel** [Chia-Network/chia-blockchain#9846]
### What happened?

I made a second installation chia-blockchain_1.2.11_amd64.deb.
The app would not "log in" and it went to a "Select Key" page.
I chose IMPORT FROM MNEMONICS (24 WORDS).
I did that and got this page: Restore Metadata for Colored Coins and other Smart Wallets from Backup
I pressed green button SAFE TO SKIP  and got this message: 'NoneType' object is not subscriptable
Tried to drag and drop ... opened /home/myusername/.chia  ... tried dragging and dropping db and wallet folders ... then tried to drag and drop indivinal files from these 2 folders ... and got this message   "Unable to decrypt the backup file."
tried rebooting the system ... didn't help

System: Kubuntu 20.04
Pretty much a new install of chia ... not framing or have any plots yet ... just trying to set up a block chain first.
My first install went fine ... restarted with no problems.
Deleted first install because I wanted to  sym-link  my /home/myaccount/.chia to a larger drive ... didn't have to do that ... my sim-link seems to work  ... still using the original /home/myusername/.chia
After the new install the system does not "log in" / start up
I can send a log file from the .chia if that would help

### Version

chia-blockchain_1.2.11_amd64.deb

### What platform are you using?

Linux

### What ui mode are you using?

GUI

### Relevant log output

```shell
2022-01-14T15:28:51.020 wallet chia.wallet.wallet_node    : WARNING  No keys present. Create keys with the UI, or with the 'chia keys' program.
2022-01-14T15:45:52.833 wallet asyncio                    : ERROR    Task exception was never retrieved
future: <Task finished name='Task-138' coro=<WalletPeers.ensure_is_closed() done, defined at chia/server/node_discovery.py:703> exception=AttributeError("'WalletPeers' object has no attribute 'connection'")>
Traceback (most recent call last):
  File "chia/server/node_discovery.py", line 706, in ensure_is_closed
  File "chia/server/node_discovery.py", line 120, in _close_common
AttributeError: 'WalletPeers' object has no attribute 'connection'
2022-01-14T15:50:14.325 full_node chia.full_node.full_node: WARNING  Block pre-validation time: 10.01 seconds
2022-01-14T15:51:20.832 full_node chia.full_node.full_node: WARNING  Block pre-validation time: 11.02 seconds
2022-01-14T15:52:02.479 full_node chia.full_node.full_node: WARNING  Block pre-validation time: 10.40 seconds
2022-01-14T15:55:32.875 full_node chia.full_node.full_node: WARNING  Block pre-validation time: 10.25 seconds
2022-01-14T16:15:55.830 full_node chia.full_node.full_node: WARNING  Block pre-validation time: 10.07 seconds
2022-01-14T16:16:44.278 full_node chia.full_node.full_node: ERROR    sync from fork point failed err: no active connection
2022-01-16T23:03:50.903 full_node chia.full_node.full_node: ERROR    Error with syncing: <class 'RuntimeError'>Traceback (most recent call last):
  File "chia/full_node/full_node.py", line 807, in _sync
RuntimeError: Weight proof did not arrive in time from peer: 37.191.170.20

2022-01-16T23:10:24.664 daemon __main__                   : ERROR    Error while handling message: Traceback (most recent call last):
  File "chia/daemon/server.py", line 200, in safe_handle
  File "chia/daemon/server.py", line 298, in handle_message
  File "chia/daemon/keychain_server.py", line 60, in handle_command
  File "chia/daemon/keychain_server.py", line 89, in add_private_key
  File "chia/util/keychain.py", line 126, in wrapper
  File "chia/util/keychain.py", line 279, in add_private_key
  File "chia/util/keychain.py", line 194, in bytes_from_mnemonic
ValueError: Invalid order of mnemonic words

2022-01-16T23:18:23.673 wallet chia.rpc.rpc_server        : WARNING  Error while handling message: Traceback (most recent call last):
  File "chia/rpc/rpc_server.py", line 217, in safe_handle
  File "chia/rpc/rpc_server.py", line 208, in ws_api
  File "chia/rpc/wallet_rpc_api.py", line 945, in get_backup_info
ValueError: Unable to decrypt the backup file.

2022-01-16T23:18:34.165 wallet chia.rpc.rpc_server        : WARNING  Error while handling message: Traceback (most recent call last):
  File "chia/rpc/rpc_server.py", line 217, in safe_handle
  File "chia/rpc/rpc_server.py", line 208, in ws_api
  File "chia/rpc/wallet_rpc_api.py", line 945, in get_backup_info
ValueError: Unable to decrypt the backup file.

2022-01-16T23:18:40.222 wallet chia.rpc.rpc_server        : WARNING  Error while handling message: Traceback (most recent call last):
  File "chia/rpc/rpc_server.py", line 217, in safe_handle
  File "chia/rpc/rpc_server.py", line 208, in ws_api
  File "chia/rpc/wallet_rpc_api.py", line 151, in log_in
KeyError: 'fingerprint'

2022-01-16T23:18:59.223 wallet chia.rpc.rpc_server        : WARNING  Error while handling message: Traceback (most recent call last):
  File "chia/rpc/rpc_server.py", line 217, in safe_handle
  File "chia/rpc/rpc_server.py", line 208, in ws_api
  File "chia/rpc/wallet_rpc_api.py", line 151, in log_in
KeyError: 'fingerprint'

2022-01-16T23:20:39.757 wallet chia.rpc.rpc_server        : WARNING  Error while handling message: Traceback (most recent call last):
  File "chia/rpc/rpc_server.py", line 217, in safe_handle
  File "chia/rpc/rpc_server.py", line 208, in ws_api
  File "chia/rpc/wallet_rpc_api.py", line 945, in get_backup_info
ValueError: Unable to decrypt the backup file.

2022-01-16T23:21:02.680 wallet chia.rpc.rpc_server        : WARNING  Error while handling message: Traceback (most recent call last):
  File "chia/rpc/rpc_server.py", line 217, in safe_handle
  File "chia/rpc/rpc_server.py", line 208, in ws_api
  File "chia/rpc/wallet_rpc_api.py", line 945, in get_backup_info
ValueError: Unable to decrypt the backup file.

2022-01-16T23:21:09.340 wallet chia.rpc.rpc_server        : WARNING  Error while handling message: Traceback (most recent call last):
  File "chia/rpc/rpc_server.py", line 217, in safe_handle
  File "chia/rpc/rpc_server.py", line 208, in ws_api
  File "chia/rpc/wallet_rpc_api.py", line 151, in log_in
KeyError: 'fingerprint'

2022-01-16T23:21:26.951 wallet chia.rpc.rpc_server        : WARNING  Error while handling message: Traceback (most recent call last):
  File "chia/rpc/rpc_server.py", line 217, in safe_handle
  File "chia/rpc/rpc_server.py", line 208, in ws_api
  File "chia/rpc/wallet_rpc_api.py", line 945, in get_backup_info
ValueError: Unable to decrypt the backup file.

2022-01-16T23:27:17.883 full_node chia.full_node.coin_store: WARNING  It took 18.31s to apply 0 additions and 0 removals to the coin store. Make sure blockchain database is on a fast drive
2022-01-16T23:32:56.393 daemon __main__                   : ERROR    Error while handling message: Traceback (most recent call last):
  File "chia/daemon/server.py", line 200, in safe_handle
  File "chia/daemon/server.py", line 298, in handle_message
  File "chia/daemon/keychain_server.py", line 60, in handle_command
  File "chia/daemon/keychain_server.py", line 89, in add_private_key
  File "chia/util/keychain.py", line 126, in wrapper
  File "chia/util/keychain.py", line 279, in add_private_key
  File "chia/util/keychain.py", line 194, in bytes_from_mnemonic
ValueError: Invalid order of mnemonic words

2022-01-16T23:33:36.285 wallet chia.rpc.rpc_server        : WARNING  Error while handling message: Traceback (most recent call last):
  File "chia/rpc/rpc_server.py", line 217, in safe_handle
  File "chia/rpc/rpc_server.py", line 208, in ws_api
  File "chia/rpc/wallet_rpc_api.py", line 945, in get_backup_info
ValueError: Unable to decrypt the backup file.

2022-01-16T23:33:42.313 wallet chia.rpc.rpc_server        : WARNING  Error while handling message: Traceback (most recent call last):
  File "chia/rpc/rpc_server.py", line 217, in safe_handle
  File "chia/rpc/rpc_server.py", line 208, in ws_api
  File "chia/rpc/wallet_rpc_api.py", line 945, in get_backup_info
ValueError: Unable to decrypt the backup file.

2022-01-16T23:33:49.203 wallet chia.rpc.rpc_server        : WARNING  Error while handling message: Traceback (most recent call last):
  File "chia/rpc/rpc_server.py", line 217, in safe_handle
  File "chia/rpc/rpc_server.py", line 208, in ws_api
  File "chia/rpc/wallet_rpc_api.py", line 151, in log_in
KeyError: 'fingerprint'

2022-01-16T23:55:40.141 full_node chia.full_node.full_node: WARNING  Block pre-validation time: 10.52 seconds
2022-01-17T13:12:20.018 daemon __main__                   : ERROR    Error while handling message: Traceback (most recent call last):
  File "chia/daemon/server.py", line 200, in safe_handle
  File "chia/daemon/server.py", line 298, in handle_message
  File "chia/daemon/keychain_server.py", line 60, in handle_command
  File "chia/daemon/keychain_server.py", line 89, in add_private_key
  File "chia/util/keychain.py", line 126, in wrapper
  File "chia/util/keychain.py", line 279, in add_private_key
  File "chia/util/keychain.py", line 194, in bytes_from_mnemonic
ValueError: Invalid order of mnemonic words

2022-01-17T13:13:45.323 daemon __main__                   : ERROR    Error while handling message: Traceback (most recent call last):
  File "chia/daemon/server.py", line 200, in safe_handle
  File "chia/daemon/server.py", line 298, in handle_message
  File "chia/daemon/keychain_server.py", line 60, in handle_command
  File "chia/daemon/keychain_server.py", line 89, in add_private_key
  File "chia/util/keychain.py", line 126, in wrapper
  File "chia/util/keychain.py", line 279, in add_private_key
  File "chia/util/keychain.py", line 194, in bytes_from_mnemonic
ValueError: Invalid order of mnemonic words

2022-01-17T13:14:29.560 daemon __main__                   : ERROR    Error while handling message: Traceback (most recent call last):
  File "chia/daemon/server.py", line 200, in safe_handle
  File "chia/daemon/server.py", line 298, in handle_message
  File "chia/daemon/keychain_server.py", line 60, in handle_command
  File "chia/daemon/keychain_server.py", line 89, in add_private_key
  File "chia/util/keychain.py", line 126, in wrapper
  File "chia/util/keychain.py", line 279, in add_private_key
  File "chia/util/keychain.py", line 194, in bytes_from_mnemonic
ValueError: Invalid order of mnemonic words

2022-01-17T13:15:08.813 daemon __main__                   : ERROR    Error while handling message: Traceback (most recent call last):
  File "chia/daemon/server.py", line 200, in safe_handle
  File "chia/daemon/server.py", line 298, in handle_message
  File "chia/daemon/keychain_server.py", line 60, in handle_command
  File "chia/daemon/keychain_server.py", line 89, in add_private_key
  File "chia/util/keychain.py", line 126, in wrapper
  File "chia/util/keychain.py", line 279, in add_private_key
  File "chia/util/keychain.py", line 194, in bytes_from_mnemonic
ValueError: Invalid order of mnemonic words

2022-01-17T13:17:44.256 full_node chia.full_node.full_node: WARNING  Block pre-validation time: 10.41 seconds
2022-01-17T13:25:19.529 full_node chia.full_node.full_node: WARNING  Block pre-validation time: 11.57 seconds
2022-01-17T13:25:56.899 full_node chia.full_node.full_node: WARNING  Block pre-validation time: 11.99 seconds
2022-01-17T13:29:09.441 full_node chia.full_node.full_node: WARNING  Block pre-validation time: 10.50 seconds
2022-01-17T13:29:23.386 full_node chia.full_node.full_node: WARNING  Block pre-validation time: 10.87 seconds
2022-01-17T13:30:03.096 full_node chia.full_node.full_node: WARNING  Block pre-validation time: 10.50 seconds
2022-01-17T13:30:18.213 full_node chia.full_node.full_node: WARNING  Block pre-validation time: 10.69 seconds
2022-01-17T13:31:17.393 full_node chia.full_node.full_node: WARNING  Block pre-validation time: 10.62 seconds
2022-01-17T13:31:53.733 full_node chia.full_node.full_node: WARNING  Block pre-validation time: 11.54 seconds
2022-01-17T13:32:09.621 full_node chia.full_node.full_node: WARNING  Block pre-validation time: 11.73 seconds
2022-01-17T13:32:22.238 full_node chia.full_node.full_node: WARNING  Block pre-validation time: 10.15 seconds
2022-01-17T13:32:36.588 full_node chia.full_node.full_node: WARNING  Block pre-validation time: 11.23 seconds
2022-01-17T13:33:05.153 full_node chia.full_node.full_node: WARNING  Block pre-validation time: 10.74 seconds
2022-01-17T13:33:16.897 full_node chia.full_node.full_node: WARNING  Block pre-validation time: 10.50 seconds
2022-01-17T13:33:33.480 full_node chia.full_node.full_node: WARNING  Block pre-validation time: 11.29 seconds
2022-01-17T13:34:52.478 full_node chia.full_node.full_node: WARNING  Block pre-validation time: 10.33 seconds
2022-01-17T13:35:47.233 full_node chia.full_node.full_node: WARNING  Block pre-validation time: 12.31 seconds
2022-01-17T13:36:57.670 full_node chia.full_node.full_node: WARNING  Block pre-validation time: 11.15 seconds
2022-01-17T13:38:08.307 full_node chia.full_node.full_node: WARNING  Block pre-validation time: 10.15 seconds
2022-01-17T13:38:32.846 full_node chia.full_node.full_node: WARNING  Block pre-validation time: 11.76 seconds
2022-01-17T13:39:19.872 full_node chia.full_node.full_node: WARNING  Block pre-validation time: 10.02 seconds
2022-01-17T13:39:43.404 full_node chia.full_node.full_node: WARNING  Block pre-validation time: 10.62 seconds
2022-01-17T13:40:15.932 full_node chia.full_node.full_node: WARNING  Block pre-validation time: 11.04 seconds
2022-01-17T13:40:42.209 full_node chia.full_node.full_node: WARNING  Block pre-validation time: 10.65 seconds
2022-01-17T13:40:52.959 full_node chia.full_node.full_node: WARNING  Block pre-validation time: 10.16 seconds
2022-01-17T13:41:07.148 full_node chia.full_node.full_node: WARNING  Block pre-validation time: 12.21 seconds
2022-01-17T13:41:41.618 full_node chia.full_node.full_node: WARNING  Block pre-validation time: 10.21 seconds
2022-01-17T13:42:04.656 full_node chia.full_node.full_node: WARNING  Block pre-validation time: 11.00 seconds
2022-01-17T13:42:17.163 full_node chia.full_node.full_node: WARNING  Block pre-validation time: 10.63 seconds
2022-01-17T13:42:29.751 full_node chia.full_node.full_node: WARNING  Block pre-validation time: 10.65 seconds
2022-01-17T13:42:41.367 full_node chia.full_node.full_node: WARNING  Block pre-validation time: 10.87 seconds
2022-01-17T13:42:55.825 full_node chia.full_node.full_node: WARNING  Block pre-validation time: 12.40 seconds
2022-01-17T13:43:10.007 full_node chia.full_node.full_node: WARNING  Block pre-validation time: 12.26 seconds
2022-01-17T13:43:23.699 full_node chia.full_node.full_node: WARNING  Block pre-validation time: 13.20 seconds
2022-01-17T13:43:38.308 full_node chia.full_node.full_node: WARNING  Block pre-validation time: 12.38 seconds
2022-01-17T13:43:53.278 full_node chia.full_node.full_node: WARNING  Block pre-validation time: 12.40 seconds
2022-01-17T13:44:05.719 full_node chia.full_node.full_node: WARNING  Block pre-validation time: 11.48 seconds
2022-01-17T13:44:21.845 full_node chia.full_node.full_node: WARNING  Block pre-validation time: 12.13 seconds
2022-01-17T13:44:33.923 full_node chia.full_node.full_node: WARNING  Block pre-validation time: 10.17 seconds
2022-01-17T18:05:02.537 full_node chia.full_node.full_node: WARNING  Block pre-validation time: 11.34 seconds
2022-01-17T18:13:57.010 full_node chia.full_node.full_node: WARNING  Block pre-validation time: 10.51 seconds
2022-01-17T18:15:44.150 full_node chia.full_node.full_node: WARNING  Block pre-validation time: 10.13 seconds
2022-01-17T18:17:42.960 full_node chia.full_node.full_node: WARNING  Block pre-validation time: 10.28 seconds
2022-01-17T18:19:24.594 full_node chia.full_node.full_node: WARNING  Block pre-validation time: 10.45 seconds
2022-01-17T18:20:36.186 full_node chia.full_node.full_node: WARNING  Block pre-validation time: 10.09 seconds
2022-01-17T18:21:37.086 full_node chia.full_node.full_node: WARNING  Block pre-validation time: 10.68 seconds
2022-01-17T18:27:12.505 full_node chia.full_node.full_node: WARNING  Block pre-validation time: 10.19 seconds
2022-01-17T18:32:14.111 full_node chia.full_node.full_node: WARNING  Block pre-validation time: 10.03 seconds
2022-01-17T18:32:59.255 full_node chia.full_node.full_node: WARNING  Block pre-validation time: 10.62 seconds
2022-01-17T18:33:12.855 full_node chia.full_node.full_node: WARNING  Block pre-validation time: 11.17 seconds
2022-01-17T18:36:24.933 full_node chia.full_node.full_node: WARNING  Block pre-validation time: 10.16 seconds
2022-01-17T18:37:03.204 full_node chia.full_node.full_node: WARNING  Block pre-validation time: 10.41 seconds
2022-01-17T18:38:31.435 full_node chia.full_node.full_node: WARNING  Block pre-validation time: 10.63 seconds
2022-01-17T18:38:53.812 full_node chia.full_node.full_node: WARNING  Block pre-validation time: 10.28 seconds
2022-01-17T18:39:19.824 full_node chia.full_node.full_node: WARNING  Block pre-validation time: 10.89 seconds
2022-01-17T18:40:48.164 full_node chia.full_node.full_node: WARNING  Block pre-validation time: 11.49 seconds
2022-01-17T18:44:36.063 full_node chia.full_node.full_node: WARNING  Block pre-validation time: 10.34 seconds
2022-01-17T18:44:47.677 full_node chia.full_node.full_node: WARNING  Block pre-validation time: 10.86 seconds
2022-01-17T18:46:39.149 full_node chia.full_node.full_node: WARNING  Block pre-validation time: 10.65 seconds
2022-01-17T18:48:10.331 full_node chia.full_node.full_node: WARNING  Block pre-validation time: 11.53 seconds
2022-01-17T18:50:02.811 full_node chia.full_node.full_node: WARNING  Block pre-validation time: 10.35 seconds
2022-01-17T18:51:32.792 full_node chia.full_node.full_node: WARNING  Block pre-validation time: 10.47 seconds
2022-01-17T18:52:45.898 full_node chia.full_node.full_node: WARNING  Block pre-validation time: 13.64 seconds
2022-01-17T18:53:00.202 full_node chia.full_node.full_node: WARNING  Block pre-validation time: 11.71 seconds
2022-01-17T18:53:55.621 full_node chia.full_node.full_node: WARNING  Block pre-validation time: 11.07 seconds
2022-01-17T18:55:23.257 full_node chia.full_node.full_node: WARNING  Block pre-validation time: 10.34 seconds
2022-01-17T18:57:39.937 full_node chia.full_node.full_node: WARNING  Block pre-validation time: 10.21 seconds
2022-01-17T18:58:14.475 full_node chia.full_node.full_node: WARNING  Block pre-validation time: 10.35 seconds
2022-01-17T19:18:40.147 full_node chia.full_node.full_node: ERROR    sync from fork point failed err: no active connection
2022-01-17T19:18:39.749 daemon __main__                   : ERROR    Unexpected exception trying to send to websocket: code = 1006 (connection closed abnormally [internal]), no reason Traceback (most recent call last):
  File "websockets/protocol.py", line 827, in transfer_data
  File "websockets/protocol.py", line 895, in read_message
  File "websockets/protocol.py", line 971, in read_data_frame
  File "websockets/protocol.py", line 1047, in read_frame
  File "websockets/framing.py", line 105, in read
  File "asyncio/streams.py", line 723, in readexactly
  File "asyncio/streams.py", line 517, in _wait_for_data
  File "asyncio/selector_events.py", line 848, in _read_ready__data_received
ConnectionResetError: [Errno 104] Connection reset by peer

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "chia/daemon/server.py", line 210, in safe_handle
  File "websockets/protocol.py", line 555, in send
  File "websockets/protocol.py", line 803, in ensure_open
websockets.exceptions.ConnectionClosedError: code = 1006 (connection closed abnormally [internal]), no reason

2022-01-17T19:20:58.179 full_node chia.full_node.full_node: ERROR    Error with syncing: <class 'RuntimeError'>Traceback (most recent call last):
  File "chia/full_node/full_node.py", line 807, in _sync
RuntimeError: Weight proof did not arrive in time from peer: 61.61.81.191

2022-01-17T19:21:40.491 full_node chia.full_node.full_node: ERROR    Error with syncing: <class 'RuntimeError'>Traceback (most recent call last):
  File "chia/full_node/full_node.py", line 807, in _sync
RuntimeError: Weight proof did not arrive in time from peer: 216.120.255.241

2022-01-17T19:23:52.696 full_node chia.full_node.full_node: ERROR    Error with syncing: <class 'RuntimeError'>Traceback (most recent call last):
  File "chia/full_node/full_node.py", line 807, in _sync
RuntimeError: Weight proof did not arrive in time from peer: 78.121.79.155

2022-01-17T19:26:55.124 daemon __main__                   : ERROR    Error while handling message: Traceback (most recent call last):
  File "chia/daemon/server.py", line 200, in safe_handle
  File "chia/daemon/server.py", line 298, in handle_message
  File "chia/daemon/keychain_server.py", line 60, in handle_command
  File "chia/daemon/keychain_server.py", line 89, in add_private_key
  File "chia/util/keychain.py", line 126, in wrapper
  File "chia/util/keychain.py", line 279, in add_private_key
  File "chia/util/keychain.py", line 194, in bytes_from_mnemonic
ValueError: Invalid order of mnemonic words

2022-01-17T19:40:04.225 wallet chia.rpc.rpc_server        : WARNING  Error while handling message: Traceback (most recent call last):
  File "chia/rpc/rpc_server.py", line 217, in safe_handle
  File "chia/rpc/rpc_server.py", line 208, in ws_api
  File "chia/rpc/wallet_rpc_api.py", line 151, in log_in
KeyError: 'fingerprint'

2022-01-17T19:40:14.058 wallet chia.rpc.rpc_server        : WARNING  Error while handling message: Traceback (most recent call last):
  File "chia/rpc/rpc_server.py", line 217, in safe_handle
  File "chia/rpc/rpc_server.py", line 208, in ws_api
  File "chia/rpc/wallet_rpc_api.py", line 151, in log_in
KeyError: 'fingerprint'

2022-01-17T19:40:23.130 wallet chia.rpc.rpc_server        : WARNING  Error while handling message: Traceback (most recent call last):
  File "chia/rpc/rpc_server.py", line 217, in safe_handle
  File "chia/rpc/rpc_server.py", line 208, in ws_api
  File "chia/rpc/wallet_rpc_api.py", line 151, in log_in
KeyError: 'fingerprint'

2022-01-17T19:45:59.262 daemon __main__                   : ERROR    Error while handling message: Traceback (most recent call last):
  File "chia/daemon/server.py", line 200, in safe_handle
  File "chia/daemon/server.py", line 298, in handle_message
  File "chia/daemon/keychain_server.py", line 60, in handle_command
  File "chia/daemon/keychain_server.py", line 89, in add_private_key
  File "chia/util/keychain.py", line 126, in wrapper
  File "chia/util/keychain.py", line 279, in add_private_key
  File "chia/util/keychain.py", line 194, in bytes_from_mnemonic
ValueError: Invalid order of mnemonic words

2022-01-17T19:47:08.111 wallet chia.wallet.wallet_blockchain: ERROR    Error during db transaction: 
2022-01-17T19:47:19.204 full_node chia.full_node.full_node: ERROR    failed fetching 96947 to 96979 from peers
2022-01-17T19:47:19.204 full_node chia.full_node.full_node: ERROR    sync from fork point failed err: cannot schedule new futures after shutdown
2022-01-17T21:16:10.626 full_node chia.full_node.full_node: ERROR    Error with syncing: <class 'RuntimeError'>Traceback (most recent call last):
  File "chia/full_node/full_node.py", line 807, in _sync
RuntimeError: Weight proof did not arrive in time from peer: 61.61.81.191

2022-01-17T21:22:49.294 daemon __main__                   : ERROR    Error while handling message: Traceback (most recent call last):
  File "chia/daemon/server.py", line 200, in safe_handle
  File "chia/daemon/server.py", line 298, in handle_message
  File "chia/daemon/keychain_server.py", line 60, in handle_command
  File "chia/daemon/keychain_server.py", line 89, in add_private_key
  File "chia/util/keychain.py", line 126, in wrapper
  File "chia/util/keychain.py", line 279, in add_private_key
  File "chia/util/keychain.py", line 178, in bytes_from_mnemonic
ValueError: 'len' is not in the mnemonic dictionary; may be misspelled

2022-01-17T21:25:27.527 full_node chia.full_node.full_node: WARNING  Block pre-validation time: 10.81 seconds
2022-01-17T21:26:04.848 full_node chia.full_node.full_node: WARNING  Block pre-validation time: 11.59 seconds
2022-01-17T21:26:28.022 full_node chia.full_node.full_node: WARNING  Block pre-validation time: 10.10 seconds
2022-01-17T21:30:53.906 full_node chia.full_node.full_node: WARNING  Block pre-validation time: 10.94 seconds
2022-01-17T21:49:54.502 daemon __main__                   : ERROR    Error while handling message: Traceback (most recent call last):
  File "chia/daemon/server.py", line 200, in safe_handle
  File "chia/daemon/server.py", line 298, in handle_message
  File "chia/daemon/keychain_server.py", line 60, in handle_command
  File "chia/daemon/keychain_server.py", line 89, in add_private_key
  File "chia/util/keychain.py", line 126, in wrapper
  File "chia/util/keychain.py", line 279, in add_private_key
  File "chia/util/keychain.py", line 178, in bytes_from_mnemonic
ValueError: 'secon' is not in the mnemonic dictionary; may be misspelled

2022-01-17T21:51:01.006 wallet chia.rpc.rpc_server        : WARNING  Error while handling message: Traceback (most recent call last):
  File "chia/rpc/rpc_server.py", line 217, in safe_handle
  File "chia/rpc/rpc_server.py", line 208, in ws_api
  File "chia/rpc/wallet_rpc_api.py", line 945, in get_backup_info
ValueError: Unable to decrypt the backup file.

2022-01-17T21:51:10.184 wallet chia.rpc.rpc_server        : WARNING  Error while handling message: Traceback (most recent call last):
  File "chia/rpc/rpc_server.py", line 217, in safe_handle
  File "chia/rpc/rpc_server.py", line 208, in ws_api
  File "chia/rpc/wallet_rpc_api.py", line 945, in get_backup_info
ValueError: Unable to decrypt the backup file.

2022-01-17T21:51:16.996 wallet chia.rpc.rpc_server        : WARNING  Error while handling message: Traceback (most recent call last):
  File "chia/rpc/rpc_server.py", line 217, in safe_handle
  File "chia/rpc/rpc_server.py", line 208, in ws_api
  File "chia/rpc/wallet_rpc_api.py", line 945, in get_backup_info
ValueError: Unable to decrypt the backup file.

2022-01-17T21:51:25.802 wallet chia.rpc.rpc_server        : WARNING  Error while handling message: Traceback (most recent call last):
  File "chia/rpc/rpc_server.py", line 217, in safe_handle
  File "chia/rpc/rpc_server.py", line 208, in ws_api
  File "chia/rpc/wallet_rpc_api.py", line 945, in get_backup_info
ValueError: Unable to decrypt the backup file.

2022-01-17T21:51:31.871 wallet chia.rpc.rpc_server        : WARNING  Error while handling message: Traceback (most recent call last):
  File "chia/rpc/rpc_server.py", line 217, in safe_handle
  File "chia/rpc/rpc_server.py", line 208, in ws_api
  File "chia/rpc/wallet_rpc_api.py", line 945, in get_backup_info
ValueError: Unable to decrypt the backup file.

2022-01-17T21:51:41.969 wallet chia.rpc.rpc_server        : WARNING  Error while handling message: Traceback (most recent call last):
  File "chia/rpc/rpc_server.py", line 217, in safe_handle
  File "chia/rpc/rpc_server.py", line 208, in ws_api
  File "chia/rpc/wallet_rpc_api.py", line 945, in get_backup_info
ValueError: Unable to decrypt the backup file.

2022-01-17T21:51:58.307 wallet chia.rpc.rpc_server        : WARNING  Error while handling message: Traceback (most recent call last):
  File "chia/rpc/rpc_server.py", line 217, in safe_handle
  File "chia/rpc/rpc_server.py", line 208, in ws_api
  File "chia/rpc/wallet_rpc_api.py", line 945, in get_backup_info
ValueError: Unable to decrypt the backup file.

2022-01-17T21:52:03.568 wallet chia.rpc.rpc_server        : WARNING  Error while handling message: Traceback (most recent call last):
  File "chia/rpc/rpc_server.py", line 217, in safe_handle
  File "chia/rpc/rpc_server.py", line 208, in ws_api
  File "chia/rpc/wallet_rpc_api.py", line 945, in get_backup_info
ValueError: Unable to decrypt the backup file.

2022-01-17T21:52:08.214 wallet chia.rpc.rpc_server        : WARNING  Error while handling message: Traceback (most recent call last):
  File "chia/rpc/rpc_server.py", line 217, in safe_handle
  File "chia/rpc/rpc_server.py", line 208, in ws_api
  File "chia/rpc/wallet_rpc_api.py", line 945, in get_backup_info
ValueError: Unable to decrypt the backup file.

2022-01-17T21:52:12.733 wallet chia.rpc.rpc_server        : WARNING  Error while handling message: Traceback (most recent call last):
  File "chia/rpc/rpc_server.py", line 217, in safe_handle
  File "chia/rpc/rpc_server.py", line 208, in ws_api
  File "chia/rpc/wallet_rpc_api.py", line 945, in get_backup_info
ValueError: Unable to decrypt the backup file.

2022-01-17T21:52:20.112 wallet chia.rpc.rpc_server        : WARNING  Error while handling message: Traceback (most recent call last):
  File "chia/rpc/rpc_server.py", line 217, in safe_handle
  File "chia/rpc/rpc_server.py", line 208, in ws_api
  File "chia/rpc/wallet_rpc_api.py", line 945, in get_backup_info
ValueError: Unable to decrypt the backup file.

2022-01-17T21:52:26.430 wallet chia.rpc.rpc_server        : WARNING  Error while handling message: Traceback (most recent call last):
  File "chia/rpc/rpc_server.py", line 217, in safe_handle
  File "chia/rpc/rpc_server.py", line 208, in ws_api
  File "chia/rpc/wallet_rpc_api.py", line 945, in get_backup_info
ValueError: Unable to decrypt the backup file.

2022-01-17T21:52:36.518 wallet chia.rpc.rpc_server        : WARNING  Error while handling message: Traceback (most recent call last):
  File "chia/rpc/rpc_server.py", line 217, in safe_handle
  File "chia/rpc/rpc_server.py", line 208, in ws_api
  File "chia/rpc/wallet_rpc_api.py", line 945, in get_backup_info
ValueError: Unable to decrypt the backup file.
```

**Comment by rwwendel** [comment]
I solved the problem ... but really not the way I wanted to.  I just deleted all my keys and started up a new one.  Then I move my /home/myusername/.chia file to a 500gb drive and simlinked it to /home/myusername .  It all works and it's syncing the wallet.  It looks like it may take a few days to sync.  I would greatly prefer a more robust way of recovering a key ... but I have not seen any help with this issue.  Just a new user here, so there was no loss of anything valuable up to this point.
I closing this ticket.
