### ISSUE TITLE
push_tx and get 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by litterGuy** [Chia-Network/chia-blockchain#9865]
### Discussed in https://github.com/Chia-Network/chia-blockchain/discussions/9863

<div type='discussions-op-text'>

<sup>Originally posted by **litterGuy** January 19, 2022</sup>
use 1.2.11 version and nodel synced.when send a request that push_tx,then return 'NoneType' object is not iterable.

the error from debug.log is :

```
2022-01-19T09:12:28.081 full_node chia.rpc.rpc_server     : WARNING  Error while handling message: Traceback (most recent call last):
  File "/home/connuser/chia-blockchain/chia/rpc/rpc_server.py", line 83, in inner
    res_object = await f(request_data)
  File "/home/connuser/chia-blockchain/chia/rpc/full_node_rpc_api.py", line 520, in push_tx
    spend_bundle = SpendBundle.from_json_dict(request["spend_bundle"])
  File "/home/connuser/chia-blockchain/chia/types/spend_bundle.py", line 99, in from_json_dict
    return dataclass_from_dict(cls, json_dict)
  File "/home/connuser/chia-blockchain/chia/util/streamable.py", line 72, in dataclass_from_dict
    return klass(**{f: dataclass_from_dict(fieldtypes[f], d[f]) for f in d})
  File "/home/connuser/chia-blockchain/chia/util/streamable.py", line 72, in <dictcomp>
    return klass(**{f: dataclass_from_dict(fieldtypes[f], d[f]) for f in d})
  File "/home/connuser/chia-blockchain/chia/util/streamable.py", line 75, in dataclass_from_dict
    return [dataclass_from_dict(get_args(klass)[0], item) for item in d]
TypeError: 'NoneType' object is not iterable

2022-01-19T09:13:28.399 full_node chia.rpc.rpc_server     : WARNING  Error while handling message: Traceback (most recent call last):
  File "/home/connuser/chia-blockchain/chia/rpc/rpc_server.py", line 83, in inner
    res_object = await f(request_data)
  File "/home/connuser/chia-blockchain/chia/rpc/full_node_rpc_api.py", line 520, in push_tx
    spend_bundle = SpendBundle.from_json_dict(request["spend_bundle"])
  File "/home/connuser/chia-blockchain/chia/types/spend_bundle.py", line 99, in from_json_dict
    return dataclass_from_dict(cls, json_dict)
  File "/home/connuser/chia-blockchain/chia/util/streamable.py", line 72, in dataclass_from_dict
    return klass(**{f: dataclass_from_dict(fieldtypes[f], d[f]) for f in d})
  File "/home/connuser/chia-blockchain/chia/util/streamable.py", line 72, in <dictcomp>
    return klass(**{f: dataclass_from_dict(fieldtypes[f], d[f]) for f in d})
  File "/home/connuser/chia-blockchain/chia/util/streamable.py", line 75, in dataclass_from_dict
    return [dataclass_from_dict(get_args(klass)[0], item) for item in d]
TypeError: 'NoneType' object is not iterable

```

how to fix it?</div>

**Comment by litterGuy** [comment]
The problem caused by calling the create_signed_transaction method and then returning null in the result 'coin_solutions'.

so why create_signed_transaction returns success but coin_solutions is null?

the request like 
```
curl --insecure --cert ~/.chia/mainnet/config/ssl/wallet/private_wallet.crt --key ~/.chia/mainnet/config/ssl/wallet/private_wallet.key -d '{"additions": [{"amount": 10000000, "puzzle_hash": "3fa549a708302b401c45cf387f8f03b4f76b7c9eabf567bea974f61dedf721e0"}]}' -H "Content-Type: application/json" -X POST https://localhost:9256/create_signed_transaction
```

and result is 

```
"spend_bundle": {
	"aggregated_signature": "*************",
	"coin_solutions": null
},
```

**Comment by litterGuy** [comment]
coin_solutions was changed to coin_spends. 

And the wiki should updated: https://github.com/Chia-Network/chia-blockchain/wiki/RPCExamples
