### ISSUE TITLE
[Bug] Sync problem

### ISSUE THREAD

**Issue by WestCoastxz** [Chia-Network/chia-blockchain#9869]
### What happened?

From the second of January, the program began to lag in synchronization. While, I tried all the basic steps, and checked the quality of the Internet, but there was no break. I also restarted the computer and reinstalled the GUI. Then I tried to clean up the synchronization files, and the node started the synchronization and takes  3-4 days, but a day later everything happened again.

![image_2022-01-19_11-53-31](https://user-images.githubusercontent.com/83952116/150080490-7bbcbe41-66de-4074-8a4d-a8942e17911b.png)

### Version

1.2.11

### What platform are you using?

Windows

### What ui mode are you using?

GUI

### Relevant log output

```shell
2022-01-19T11:43:28.150 full_node full_node               : ERROR    full_node: already running
2022-01-19T11:43:33.109 harvester chia.plotting.manager   : WARNING  Have multiple copies of the plot plot-k32-2021-07-16-17-37-cf0c04157067faf3dd37f50ba8b24d816b47130ebd385073931ef2dbf19d6caf.plot in ['D:\\', 'J:\\new'].
2022-01-19T11:43:35.371 harvester chia.plotting.manager   : WARNING  Have multiple copies of the plot plot-k32-2021-07-17-19-44-dc55942d5b6d1e2a0495fdbcc04e61a19f6cf4753722112a022fe22238949183.plot in ['D:\\', 'N:\\'].
2022-01-19T11:43:35.470 harvester chia.plotting.manager   : WARNING  Have multiple copies of the plot plot-k32-2021-07-16-17-37-cf0c04157067faf3dd37f50ba8b24d816b47130ebd385073931ef2dbf19d6caf.plot in ['D:\\', 'J:\\new', 'N:\\'].
2022-01-19T11:43:35.484 harvester chia.plotting.manager   : WARNING  Have multiple copies of the plot plot-k32-2021-07-17-19-06-b710ab5217d1736e119169da2232c07337c55bcb4fcb5db199f81a1ce62b20dc.plot in ['D:\\', 'N:\\'].
2022-01-19T11:43:51.187 full_node asyncio                 : ERROR    Task exception was never retrieved
future: <Task finished name='Task-424714' coro=<RpcServer._state_changed() done, defined at chia\rpc\rpc_server.py:48> exception=ProgrammingError('Cannot operate on a closed database.')>
Traceback (most recent call last):
  File "chia\rpc\rpc_server.py", line 51, in _state_changed
  File "chia\rpc\full_node_rpc_api.py", line 61, in _state_changed
  File "chia\rpc\full_node_rpc_api.py", line 135, in get_blockchain_state
  File "chia\rpc\full_node_rpc_api.py", line 397, in get_network_space
  File "chia\full_node\block_store.py", line 237, in get_block_record
  File "aiosqlite\cursor.py", line 54, in fetchone
  File "aiosqlite\cursor.py", line 31, in _execute
  File "aiosqlite\core.py", line 129, in _execute
  File "aiosqlite\core.py", line 102, in run
sqlite3.ProgrammingError: Cannot operate on a closed database.
2022-01-19T11:43:51.189 full_node chia.full_node.full_node: ERROR    sync from fork point failed err: no active connection
2022-01-19T11:43:51.211 full_node asyncio                 : ERROR    Task exception was never retrieved
future: <Task finished name='Task-424759' coro=<RpcServer._state_changed() done, defined at chia\rpc\rpc_server.py:48> exception=ProgrammingError('Cannot operate on a closed database.')>
Traceback (most recent call last):
  File "chia\rpc\rpc_server.py", line 51, in _state_changed
  File "chia\rpc\full_node_rpc_api.py", line 61, in _state_changed
  File "chia\rpc\full_node_rpc_api.py", line 135, in get_blockchain_state
  File "chia\rpc\full_node_rpc_api.py", line 397, in get_network_space
  File "chia\full_node\block_store.py", line 237, in get_block_record
  File "aiosqlite\cursor.py", line 54, in fetchone
  File "aiosqlite\cursor.py", line 31, in _execute
  File "aiosqlite\core.py", line 129, in _execute
  File "aiosqlite\core.py", line 102, in run
sqlite3.ProgrammingError: Cannot operate on a closed database.
2022-01-19T11:46:59.235 wallet chia.wallet.wallet_node    : ERROR    Error while trying to fetch from peer:Peer returned no response Traceback (most recent call last):
  File "chia\wallet\wallet_node.py", line 563, in batch_sync_to_peak
  File "chia\wallet\wallet_node.py", line 695, in fetch_blocks_and_validate
ValueError: Peer returned no response

2022-01-19T11:46:59.236 wallet chia.wallet.wallet_node    : ERROR    Loop exception in sync Was not able to add blocks 1441012-1441044. Traceback (most recent call last):
  File "chia\wallet\wallet_node.py", line 616, in sync_job
  File "chia\wallet\wallet_node.py", line 676, in _sync
  File "chia\wallet\wallet_node.py", line 573, in batch_sync_to_peak
RuntimeError: Was not able to add blocks 1441012-1441044
```

**Comment by emlowe** [comment]
`sqlite3.ProgrammingError: Cannot operate on a closed database.` - suggests you may have other processes running. I recommend you close chia, reboot, and run chia again.

**Comment by Goagabi** [comment]
The same problem here.......Wait for the solution...

**Comment by ibotches** [comment]
The same problem here

**Comment by ibotches** [comment]
2022-01-20T08:47:10.430 full_node asyncio                 : ERROR    Task exception was never retrieved
future: <Task finished name='Task-295016' coro=<RpcServer._state_changed() done, defined at chia\rpc\rpc_server.py:48> exception=KeyError(b'\xd7\x80\xd2,z\x87\xc9\xe0\x1d\x98\xb4\x9a\t\x10\xf6p\x1c;\x95\x01WA1k?\xda\x04.]{\x81\xd2')>
Traceback (most recent call last):
  File "chia\rpc\rpc_server.py", line 51, in _state_changed
  File "chia\rpc\full_node_rpc_api.py", line 61, in _state_changed
  File "chia\rpc\full_node_rpc_api.py", line 102, in get_blockchain_state
  File "chia\consensus\blockchain.py", line 157, in get_peak
  File "chia\consensus\blockchain.py", line 674, in height_to_block_record
  File "chia\consensus\blockchain.py", line 670, in block_record
KeyError: b'\xd7\x80\xd2,z\x87\xc9\xe0\x1d\x98\xb4\x9a\t\x10\xf6p\x1c;\x95\x01WA1k?\xda\x04.]{\x81\xd2'
2022-01-20T08:47:10.435 full_node full_node_server        : WARNING  Banning 77.121.209.219 for 10 seconds
2022-01-20T08:47:10.437 full_node full_node_server        : ERROR    Exception b'\xd7\x80\xd2,z\x87\xc9\xe0\x1d\x98\xb4\x9a\t\x10\xf6p\x1c;\x95\x01WA1k?\xda\x04.]{\x81\xd2', exception Stack: Traceback (most recent call last):
  File "chia\server\server.py", line 437, in start_client
  File "chia\server\server.py", line 335, in connection_added
  File "chia\full_node\full_node.py", line 619, in on_connect
  File "chia\full_node\full_node.py", line 585, in synced
  File "chia\consensus\blockchain.py", line 157, in get_peak
  File "chia\consensus\blockchain.py", line 674, in height_to_block_record
  File "chia\consensus\blockchain.py", line 670, in block_record
KeyError: b'\xd7\x80\xd2,z\x87\xc9\xe0\x1d\x98\xb4\x9a\t\x10\xf6p\x1c;\x95\x01WA1k?\xda\x04.]{\x81\xd2'

**Comment by draegogsr** [comment]
same problem

**Comment by DaveTwoOh** [comment]
Same..i thought it was just me..but apparently not.

**Comment by paulhainsworth-chia** [comment]
iBotch has separate error: `KeyError: b'\xd7\x80\xd2,z\x87\xc9\xe0\x1d\x98\xb4\x9a\t\x10\xf6p\x1c;\x95\x01WA1k?\xda\x04.]{\x81\xd2'` It's a peak error and is separate from OP's issue.

**Comment by ibotches** [comment]
what should I do
