### ISSUE TITLE
[Bug] main node went pout of sync, now will not sync

### ISSUE THREAD

**Issue by draegogsr** [Chia-Network/chia-blockchain#9892]
### What happened?

went out of sync couple days a go. now stays at 0 synced. tries to connect top peers automatically and will not hold connection then loses all connections. have deleted keys and reinstalled from mnemonic and same issue. rebooted, set router correctly, 8444 is open, etc, tried introducer no luck, when i add peers manually from list of open 8444's the screen blinks as it tries to connect and just disconnects.

### Version

1.2.11

### What platform are you using?

Windows

### What ui mode are you using?

GUI

### Relevant log output

```shell
2022-01-20T04:32:12.045 full_node asyncio                 : ERROR    Task exception was never retrieved
future: <Task finished name='Task-371060' coro=<RpcServer._state_changed() done, defined at chia\rpc\rpc_server.py:48> exception=KeyError(b'\xd7\x80\xd2,z\x87\xc9\xe0\x1d\x98\xb4\x9a\t\x10\xf6p\x1c;\x95\x01WA1k?\xda\x04.]{\x81\xd2')>
Traceback (most recent call last):
  File "chia\rpc\rpc_server.py", line 51, in _state_changed
  File "chia\rpc\full_node_rpc_api.py", line 61, in _state_changed
  File "chia\rpc\full_node_rpc_api.py", line 102, in get_blockchain_state
  File "chia\consensus\blockchain.py", line 157, in get_peak
  File "chia\consensus\blockchain.py", line 674, in height_to_block_record
  File "chia\consensus\blockchain.py", line 670, in block_record
KeyError: b'\xd7\x80\xd2,z\x87\xc9\xe0\x1d\x98\xb4\x9a\t\x10\xf6p\x1c;\x95\x01WA1k?\xda\x04.]{\x81\xd2'
2022-01-20T04:32:12.054 full_node full_node_server        : WARNING  Banning 37.57.9.179 for 10 seconds
2022-01-20T04:32:12.055 full_node full_node_server        : ERROR    Exception b'\xd7\x80\xd2,z\x87\xc9\xe0\x1d\x98\xb4\x9a\t\x10\xf6p\x1c;\x95\x01WA1k?\xda\x04.]{\x81\xd2', exception Stack: Traceback (most recent call last):
  File "chia\server\server.py", line 437, in start_client
  File "chia\server\server.py", line 335, in connection_added
  File "chia\full_node\full_node.py", line 619, in on_connect
  File "chia\full_node\full_node.py", line 585, in synced
  File "chia\consensus\blockchain.py", line 157, in get_peak
  File "chia\consensus\blockchain.py", line 674, in height_to_block_record
  File "chia\consensus\blockchain.py", line 670, in block_record
KeyError: b'\xd7\x80\xd2,z\x87\xc9\xe0\x1d\x98\xb4\x9a\t\x10\xf6p\x1c;\x95\x01WA1k?\xda\x04.]{\x81\xd2'
```

**Comment by doma2345** [comment]
@draegogsr I just had this same issue last night.

The fix i used was 
stop chia
delete DB and wallet folder
Download new db from https://www.chia-database.com/
restore database in db folder
start chia

**Comment by mariano54** [comment]
Can you send me your debug.log file on keybase? I'm sorgente711.

**Comment by mariano54** [comment]
Also please continue discussion in this thread:
https://github.com/Chia-Network/chia-blockchain/issues/9677
